### ISSUE TITLE
Vulnerability scanner form windows 

### ISSUE THREAD

**Issue by mmbar1986** [wazuh/wazuh#10007]
|4.2.1|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager | Packages/Sources |Centos 7 |

Hi Everyone , 

I detected an anomalie on the vulnerability scanner : 

data.vulnerability.package.condition
**KB4512517 patch is not installed**
	
data.vulnerability.package.generated_cpe
**o:microsoft:windows_10:1809:::::::**
	
data.vulnerability.package.name
Windows 10
	

data.vulnerability.rationale
A remote code execution vulnerability exists in Remote Desktop Services â€“ formerly known as Terminal Services â€“ when an unauthenticated attacker connects to the target system using RDP and sends specially crafted requests, aka 'Remote Desktop ServicesÂ Remote Code Execution Vulnerability'. This CVE ID is unique from CVE-2019-1182, CVE-2019-1222, CVE-2019-1226.
	

As you can see my Windows version is  windows_10:1809 and the scanner is detecting that i have to apply  KB4512517 patch but after checking my WSUS server this KB is not applicable on this version , it's for older version 1607 !

https://support.microsoft.com/en-us/topic/august-13-2019-kb4512517-os-build-14393-3144-3fb291ba-06c9-6128-36fb-33de8ec12109

Any advice here ? 

Thank you

**Comment by MarcelKemp** [comment]
Hi @mmbar1986,

After checking that patch and the vulnerabilities that you have commented, I have verified that the three vulnerabilities are related to windows 10 version _`1809`_, but that the only one that fixes the `KB4512517` patch for version _`1607`_ is _CVE-2019-1182_, as you can see in the following link: https://msrc.microsoft.com/update-guide/en-US/vulnerability/CVE-2019-1182

Although I am investigating what could have happened so that vuln-detector does not report the `KB4511553` patch to you, which would be the one that fixes version _`1809`_.

> The other two vulnerabilities, you can see below that they are not related to that patch:
> [CVE-2019-1222](https://msrc.microsoft.com/update-guide/en-US/vulnerability/CVE-2019-1222)
> [CVE-2019-1226](https://msrc.microsoft.com/update-guide/vulnerability/CVE-2019-1226)

To speed up the investigation process, it would help me if you send the following information:

- The full alert of the anomalous vulnerability that vulnerability-detector reports to you.

- The patches installed and collected in the inventory. 

To get the patch list, you can get the information directly from the manager with the following command (where 001.db is the agent in question):

    sqlite3 /var/ossec/queue/db/001.db "select * from sys_hotfixes;"

Or you can get them from the WUI, heading to the section: `Agents` -> `Select Windows Agent` -> `Inventory Data`.
Where you will find a list in the **Windows updates** section with all the patches installed on the agent. 

Thanks in advance.

**Comment by MarcelKemp** [comment]
Hi @mmbar1986,

We have found the bug that causes the report of the patch that fixes the vulnerability to be wrong (affects another version of _Windows 10_). 

The fix has been implemented in the following PR: https://github.com/wazuh/wazuh/pull/10168

And the cause of this failure happened when a _Windows 10_ agent is vulnerable due to lack of a system update, so instead of reporting the patch that correctly fixed this vulnerability, it sometimes reported another patch that fixed this vulnerability but for a different version of _Windows 10_ . With the solution applied, it should already report the patches corresponding to the current version of _Windows 10_.

Thank you for your feedback and I am sorry for the inconvenience.
