### ISSUE TITLE
Investigate possible vulnerabilities alerting a possible binding to all interfaces in `framework/`

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#10146]
## Description

With the test created in the issue https://github.com/wazuh/wazuh-qa/issues/1615, some possible code flaws were found by Bandit.

In this issue we specify flaws regarding showing possible bindings to all interfaces.

This flaw told us that we are exposing something from all network interfaces.

- [framework/wazuh/core/cluster/cluster.py line 64](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/core/cluster/cluster.py#L64)

The flaw should be considered a false positive here as the IP 0.0.0.0 is just an IP included in a variable that work as a filter to indicate invalid elements:

```
reservated_ips = {'localhost', 'NODE_IP', '0.0.0.0', '127.0.1.1'}
...
invalid_elements = list(reservated_ips & set(config['nodes']))
```

- [framework/wazuh/core/cluster/utils.py line 48-57](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/core/cluster/utils.py#L48-L57)

This flaw is also shown in the Bandit result. Code:

```
cluster_default_configuration = {
        'disabled': False,
        'node_type': 'master',
        'name': 'wazuh',
        'node_name': 'node01',
        'key': '',
        'port': 1516,
        'bind_addr': '0.0.0.0',
        'nodes': ['NODE_IP'],
        'hidden': 'no'
    }
```
    

More info.: https://bandit.readthedocs.io/en/latest/plugins/b104_hardcoded_bind_all_interfaces.html

We should investigate these 2 results and see if they are real vulnerabilities.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Kondent** [comment]
## Issue Report - B104: hardcoded_bind_all_interfaces
```
Binding to all network interfaces can potentially open up a service to traffic on unintended interfaces,
that may not be properly documented or secured.
This plugin test looks for a string pattern “0.0.0.0” that may indicate a hardcoded binding to all network interfaces.
```

### `framework/wazuh/core/cluster/cluster.py`:

https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/core/cluster/cluster.py#L64

This is a false positive because it's only used as a variable, to verify the configuration.


### `framework/wazuh/core/cluster/utils.py`:

https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/core/cluster/utils.py#L48-L58

This block is different.
As we discussed in a related issue (wazuh/wazuh#10142), the flaw will exist if that the running program, which is binding to all network interfaces, is not secure.

After doing some research I found out a related problem that should be reviewed in more depth by the cluster team.
I reported it here: wazuh/wazuh#11492

Sending random data to the cluster socket can be done even if it's set to one interface.
However, it will be less likely to happen because we're binding to a well-known network.

In my opinion we should wait for more information from wazuh/wazuh#11492.

**Comment by Kondent** [comment]
## Update
* Wazuh QA PR: https://github.com/wazuh/wazuh-qa/pull/2449.
