### ISSUE TITLE
Wazuh can't start osquery with the run_daemon setting because now it's a service

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#10140]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3 | Wazuh wodle "osquery" | Manager/Agent | Packages/Sources | Unix |

### Related pull requests

|Repository|Link|
|---|---|
| Core | https://github.com/wazuh/wazuh/pull/10396 |
| Documentation | https://github.com/wazuh/wazuh-documentation/pull/4412 |

# Description 

The **osquery** wodle is capable of running this external software with the [run-daemon](https://documentation.wazuh.com/4.2/user-manual/reference/ossec-conf/wodle-osquery.html#run-daemon) setting. But if the [bin-path](https://documentation.wazuh.com/4.2/user-manual/reference/ossec-conf/wodle-osquery.html#bin-path) isn't set, Wazuh will try to run the binary **osqueryd** assuming it is in the PATH variable.

This is no longer posible, because now **osquery** is a service and Wazuh can no longer find it with the current mechanism of [Execute_Osquery()](https://github.com/wazuh/wazuh/blob/b1c7ae23cba517c05b64063e8d54121b9e003191/src/wazuh_modules/wm_osquery_monitor.c#L254) (thank you @vikman90 for the analysis).

# How to reproduce it

-  Install **osquery** following the [instructions](https://documentation.wazuh.com/4.2/user-manual/capabilities/osquery.html?highlight=osquery#configuration) detailed by Wazuh 
- Enable the **osquery** wodle in `ossec.conf`
- An error message is printed, even when the **osqueryd** daemon is running

```
2021/09/15 14:26:06 wazuh-modulesd:osquery: ERROR: Couldn't execute osquery (osqueryd). Check file and permissions. Sleeping for 10 minutes.
```

# Workaround

- Disable the `<run_daemon>` setting and start the service in the system

**Comment by branchnetconsulting** [comment]
I just installed osquery 5.0.1 on an Ubuntu 20.04 system running Wazuh agent 4.2.2 by fetching
**https://pkg.osquery.io/deb/osquery_5.0.1-1.linux_amd64.deb**
and installing it with dpkg.
The resulting output of "systemctl status osqueryd" seems to indicate the service is disabled by default, which is desirable so that the <run_daemon> feature can continue to have osquery run as a subprocess of Wazuh agent.
```
● osqueryd.service - The osquery Daemon
     Loaded: loaded (/lib/systemd/system/osqueryd.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
```
I symlinked the old osqueryd path to the new 5.0.1 path.
`ln -s /opt/osquery/bin/osqueryd /usr/bin/osqueryd`
But even better would be to just change the <bin_path> setting from **/usr/bin** to **/opt/osquery/bin**.
In either case, it is working fine for me.
Perhaps some other forms of Linux Osquery 5.x packaging are now enabling the osquery systemd service, in which case assuming you want to use <run_daemon>, you'll want to run this after installing the new osquery 5.x:
`systemctl disable osqueryd` 
so that Wazuh agent doesn't clash with an independently running systemd instance of osquery.
I greatly value running osquery as a subprocess under Wazuh agent because I use Wazuh centralized agent configuration to distribute osquery config files to agents and want osquery to restart every time Wazuh agent restarts so that newly distributed osquery config changes to into effect immediately.

**Comment by chemamartinez** [comment]
Hi @branchnetconsulting and @pereyra-m,

This has been addressed at https://github.com/wazuh/wazuh/pull/10396.

Best regards.
