### ISSUE TITLE
Investigate and fix possible vulnerability when using Try, Except, Pass in `wodles/`

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#10155]
## Description

With the test created in the issue https://github.com/wazuh/wazuh-qa/issues/1615, some possible code flaws were found by Bandit.

In this issue we specify flaws regarding the use of Try, Except, Pass in `wodles/`.

Issue text: Try, Except, Pass detected.

[wodles/utils.py line 47-48](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/wodles/utils.py#L47-L48)

https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/wodles/utils.py#L41-L48

More info: https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

We should investigate this result and see if it is a real vulnerability.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by noise-kngdm** [comment]
## Issue update
After thoroughly examining this issue, we've come to the conclusion that even though the use of a 'try: except: pass' block is not a good practice -and that will be addressed in this issue-, there's no vulnerability in the reported code, and therefore it's false positive.  

### Exceptions that Popen can raise
The exceptions that can be raised from a call to either the `Popen` constructor or the `communicate()` method are the following according with [subprocess documentation](https://docs.python.org/3/library/subprocess.html#exceptions):  

#### OSError
This exception will be raised when, for example, the program is trying to execute a file that doesn't exist.
#### ValueError
This exception will be raised if the `Popen` constructor is called with invalid arguments. Since the call to the `Popen` constructor is fixed and correct, this exception won't be raised in our case.
#### CalledProcessError
If the child process returns a non-zero return code, this exception will be raised.
#### TimeoutExpired
If the call to `communicate()` was made specifying a timeout -which is not our case- and this timeout expires before finishing the execution, a `TimeoutExpired` exception will be raised.

### Analysis of exceptions that could be raised and are not handled
Those exceptions are `OSError` and `CalledProcessError`, but having them raised won't mean that our program is in a vulnerable state. Since the worst-case scenario is that there was a problem with the executable and Wazuh is not properly working, or that there was a problem with the call to `Popen`, in which case the execution of the script would stop, as can be seen in the following code snippet:

https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/wodles/utils.py#L51-L54

### Conclusions
There are no security problems related to our use of a `try: except: pass` block, but it will get fixed to follow the best programming practices.

**Comment by noise-kngdm** [comment]
## Issue update
The `test_python_flaws.py` test was executed for the branch developed for this PR and no new issues were detected. Also, the flaws reported by this issue were succesfully removed by the test.
```
(venv) ➜  wazuh-qa git:(feature/2230-mark-wazuh-10155-solved) ✗ pytest tests/scans/code_analysis/test_python_flaws.py --branch feature/10155-handle-exception-wodles                   
==================================== test session starts ====================================
platform linux -- Python 3.9.9, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/gonzz/git/wazuh-qa
plugins: html-2.0.1, metadata-1.11.0, testinfra-5.0.0
collected 1 item                                                                            

tests/scans/code_analysis/test_python_flaws.py .                                      [100%]

===================================== warnings summary ======================================
tests/scans/code_analysis/test_python_flaws.py::test_check_security_flaws
  invalid escape sequence \g

tests/scans/code_analysis/test_python_flaws.py::test_check_security_flaws
  invalid escape sequence \d

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=============================== 1 passed, 2 warnings in 9.27s ===============================
```
