### ISSUE TITLE
install wazuh Plugin installation was unsuccessful due to error "No valid url specified."

### ISSUE THREAD

**Issue by DisMeo** [wazuh/wazuh#1016]
hello:
    My ELK version is 5.6.10,when i try to install wazuh app, i get this error:

/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://packages.wazuh.com/wazuhapp/wazuhapp.zip/https://packages.wazuh.com/wazuhapp/wazuhapp.zip-5.6.10.zip
Plugin installation was unsuccessful due to error "No valid url specified."

how i can fix it?
thank you for your help

**Comment by jesusgn90** [comment]
Hi @DisMeo ,

The URL you are trying to use is wrong. Usually our URLs are like this: https://packages.wazuh.com/wazuhapp/wazuhapp-3.0.0_6.0.0.zip, this means they include the Wazuh version (3.0.0 in example) and the Elastic stack version (6.0.0 in example). Our last package for Elastic 5.6.x was https://packages.wazuh.com/wazuhapp/wazuhapp-2.1.1_5.6.5.zip but I don't recommend to use it because you'll need to use Wazuh 2.1 and lot of improvements and bug fixes have been developed since that version. 

Also note you are using a deprecated Elastic version (5.6.10), currently we are supporting 6.0.0 onwards. Our latest version is 3.4.x for Wazuh and 6.3.y for the Elastic stack.

- https://documentation.wazuh.com/3.x/
- https://github.com/wazuh/wazuh-kibana-app#installation

Regards,
Jesús

**Comment by nitramhub** [comment]
hi there. i have a similar issue
I´m installing wazuh for the first time in an All-in-one deployement, step-by-step installation. I´m stuck in the Wazuh Kibana plugin installation.
The command at this step is:
`sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.5_7.10.2-1.zip`
The result is a "No valid url specified." message, which as far as i understand is because url´s are not correctly separated, instead they are all together.
What I dont know is where to locate this config file where this url´s in order to correct it.
```
[root@localhost kibana]# sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.5_7.10.2-1.zip
Attempting to transfer from https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.5_7.10.2-1.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.5_7.10.2-1.zip/https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.5_7.10.2-1.zip-7.10.2.zip
Plugin installation was unsuccessful due to error "No valid url specified."
[root@localhost kibana]#
```

**Comment by rauldpm** [comment]
> hi there. i have a similar issue I´m installing wazuh for the first time in an All-in-one deployement, step-by-step installation. I´m stuck in the Wazuh Kibana plugin installation. The command at this step is: `sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.5_7.10.2-1.zip` The result is a "No valid url specified." message, which as far as i understand is because url´s are not correctly separated, instead they are all together. What I dont know is where to locate this config file where this url´s in order to correct it.
> 
> ```
> [root@localhost kibana]# sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.5_7.10.2-1.zip
> Attempting to transfer from https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.5_7.10.2-1.zip
> Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.5_7.10.2-1.zip/https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.5_7.10.2-1.zip-7.10.2.zip
> Plugin installation was unsuccessful due to error "No valid url specified."
> [root@localhost kibana]#
> ```


Hello @nitramhub 

First I apologize for the delay in the response but keep in mind that this issue has been closed since 2018, for the next one I would ask you to open a new issue and referring the existing issue.

Currently this problem is something that we have detected but we have not yet managed to find out the cause, since the problem seems to be something specific in some configuration of the user system or in the kibana-plugin installer itself (maybe a bug when trying to download the url).

At that time, the problem was due to the wrong url to the zip file, which was solved using the correct url, in this case, the url https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.5_7.10.2-1.zip is correct and when accessing via browser or `curl -o` the file is downloaded.

Previously investigating this problem I realized that the problem is in the url itself that is passed to kibana-plugin installer, since if I force the wrong url (adding, for example: `\n`), the message shown with the url introduces this character:

```
root@centos8 kibana]# sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.5_7.10.2-1.zip\n

Attempting to transfer from https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.5_7.10.2-1.zipn

Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.5_7.10.2-1.zipn/https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.5_7.10.2-1.zipn-7.10.2.zip

Plugin installation was unsuccessful due to error "No valid url specified."
```

Note the "zipn"

```
https://artifacts.elastic.co/downloads/kibana-plugins/
https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.5_7.10.2-1.zipn
https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.5_7.10.2-1.zipn-7.10.2.zip
```

This led me to think that it may be a problem in some invisible character that causes this failure or that it is a problem of the kibana-plugin installer itself, but it is not something that we have been able to reproduce 100% even since the current failure is quite difficult to reproduce, in fact, for now I have seen this problem in two users only.

In principle, as a workaround, I can propose this alternative when installing the plugin:

- cd /usr/share/kibana
- curl -so wazuh_kibana-4.2.5_7.10.2-1.zip https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.2.5_7.10.2-1.zip
- sudo -u kibana /usr/share/kibana/bin/kibana-plugin install file://$(pwd)/wazuh_kibana-4.2.5_7.10.2-1.zip

Regards, Raúl.
