### ISSUE TITLE
Wazuh API will not work if it does not have permission to read /proc

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#10199]
As the [official documentation](https://docs.python.org/3/library/os.path.html#os.path.exists) says, the `os.path.exists` function:

> On some platforms, this function may return False if permission is not granted to execute os.stat() on the requested file, even if the path physically exists.

This means that on some platforms, the Wazuh API will not be able to work because all the daemons will have a `failed` status:

https://github.com/wazuh/wazuh/blob/7ec0a3603880b8d425d9fdffdd76363551cbc1dd/framework/wazuh/core/cluster/utils.py#L96-L131

We need to handle this exception more accurate to inform the user that the issue is related to `/proc` permissions if this happens.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by mcarmona99** [comment]
## Issue update

As it was told in this issue's body and as the official documentation says, the `os.path.exists` function may return `False` if permission is not granted to execute `os.stat()` on the requested file, even if the path physically exists.

After investigating possible exceptions when using `os.stat` on a file with permissions not being granted, I have seen the `os.path.exists` function is already using the `os.stat` function.

In [`genericpath.py`](https://github.com/python/cpython/blob/df9f7597559b6256924fcd3a1c3dc24cd5c5edaf/Lib/genericpath.py#L14-L22):


```python
# Does a path exist?
# This is false for dangling symbolic links on systems that support them.
def exists(path):
    """Test whether a path exists.  Returns False for broken symbolic links"""
    try:
        os.stat(path)
    except (OSError, ValueError):
        return False
    return True
```
    
Here we can see that if `stat` raises an error different to `FileNotFoundError` (and also child of `OSError` or `ValueError`), the path is also considered as non-existent.

I have been investigating which exceptions can be raised by the `os.stat` function. 

Some users agree that there is a lack of information about the possible exceptions raised in `os.stat` official documentation, as it can be seen [here](https://python-forum.io/thread-32605.html). This is due to the fact that these exception are `OSError` exceptions only (and `ValueError`). These exceptions can be found in the [OS exceptions section of the Python documentation](https://docs.python.org/3.9/library/exceptions.html#os-exceptions). All of them are subclasses of `OSError`:

- OSError
  - BlockingIOError
  - ChildProcessError
  - ConnectionError
  - BrokenPipeError
  - ConnectionAbortedError
  - ConnectionRefusedError
  - ConnectionRefusedError
  - FileExistsError
  - FileNotFoundError
  - InterruptedError
  - IsADirectoryError
  - NotADirectoryError
  - PermissionError
  - ProcessLookupError
  - TimeoutError
  
Obviously, not all of the `OSError` exceptions can be raised by the `os.stat` function. As I said, there is a lack of documentation about this, but we can investigate which errors can be raised by the [`stat` Linux command](https://linux.die.net/man/1/stat) since this is what the `os` Python module uses in the background. 

On the [second page of the `stat` Linux manual](https://linux.die.net/man/2/stat), we have the possible errors raised by stat: **EACCES**, **EBADF**, **EFAULT**, **ELOOP**, **ENAMETOOLONG**, **ENOENT**, **ENOMEM**, **ENOTDIR** and **EOVERFLOW**.

For this issue, we will consider the **ENOENT** and **EACCES** errors. These errors refer to non-existent path or path component; and permission denied for one of the directories in the path, respectively.

If we have a look at the [Python built-in exceptions documentation](https://docs.python.org/3.9/library/exceptions.html#os-exceptions) again, we will see that the `FileNotFoundError` exception corresponds to errno **ENOENT**; and the `PermissionError` exception corresponds to errno **EACCESS** and **EPERM**.

Note that the `NotADirectoryError` exception (**ENOTDIR**) can also be raised by `stat`, but we have not considered this error as we are only taking into account the `/proc` directory in this issue, so a `NotADirectoryError` exception will never be raised.
