### ISSUE TITLE
Change API login endpoint method

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#10203]
This issue is part of https://github.com/wazuh/wazuh/issues/12793.

As it was said in the epic issue, our API login endpoint to retrieve a token is `GET /security/user/authenticate`. This is incorrect, as login endpoints should use the `POST` method.

This issue aims to change the method in the API specification, update API integration tests, etc.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Kondent** [comment]
## Update
I've been doing few changes: `spec.yaml` and  `integration tests` are fixed, I'm currently working with documentation.

**Comment by Kondent** [comment]
## Update
As we discussed, `GET /security/user/authenticate` and `POST /security/user/authenticate` should coexist since the change of the request type itself will occur on a major release and there are several places where this endpoint is used and must be fixed.
In the meantime we'll have both request types available for the user to choose.

**Comment by Kondent** [comment]
# Update

## `POST /security/user/authenticate`:

I've been investigating about POST login request and if it's needed to provide this endpoint with a `body` with credentials or continue using **BasicAuth** as we do on `GET /security/user/authenticate`.

At this point, we have two possibilities to continue with:
* `POST /security/user/authenticate` + `body` with credentials.
* `POST /security/user/authenticate` + **BasicAuth**.

The main (and serious) problem with **BasicAuth** lies in the interception of the base64 encoded string from `username:password` and retrieve credentials from it because as we know base64 can be reversed. (this same problem occurs with `POST` and its body since it travels in plain text) but we're covered since we got our API paired with **SSL** as mentioned [here](https://documentation.wazuh.com/current/user-manual/api/securing_api.html).
Based on this, I suggest to change this endpoint type to `POST` as we discussed and keep **BasicAuth** working with it.


## `GET /security/user/authenticate` Deprecation:

I found out a solution to have this two endpoint coexisting and completely replace `GET` with `POST` later on.
First, we can mark `GET` endpoint as deprecated in API spec. With this, API reference gets modified as follows:

![image](https://user-images.githubusercontent.com/84642680/135341870-51a3568e-6877-457f-9261-e0f59d112ded.png)

And secondly, we can add two custom entries to the `GET /security/user/authenticate` response header to warn about this change:

* Deprecation: "This endpoint has been, or will be, deprecated, meaning you should move away from using it when you can. Its value can be a date or boolean".
* Sunset: "This endpoint will become unresponsive after this specified date." (maybe it could be a message pointing to a new Wazuh version)

These are `GET /security/user/authenticate` headers plus custom `Deprecation` entry:
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Deprecation: true
Strict-Transport-Security: max-age=63072000; includeSubdomains
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: none
Referrer-Policy: no-referrer, strict-origin-when-cross-origin
Pragma: no-cache
Expires: 0
Cache-control: no-cache, no-store, must-revalidate, max-age=0
Content-Length: 433
Date: Wed, 29 Sep 2021 19:09:56 GMT
```

Regards,
Alexis.

**Comment by Kondent** [comment]
# Update

## Response Headers
After doing more research I can say we should warn users via `GET /security/user/authenticate` header with `Deprecation` and `Sunset` entries.
It's a suggested standard which later on became [RFC 8594](https://datatracker.ietf.org/doc/html/rfc8594).

In other words I could be adding this two entries:
```
Deprecation: <DATE> || True.
Sunset: <DATE>. Link: <LINK>.
```

But since we don't have an exact date when this change will take place, maybe we can customize it a bit with a suggested date, along with a link to our api reference (the link can be a link to anything, the endpoint replacing it, a link to some human readable documentation, etc) or we can stay just with `Deprecation` entry for the moment and add `Sunset` later on, with a known release date for the new Wazuh version.

## API Reference
In addition of what I said in the [last comment](https://github.com/wazuh/wazuh/issues/10203#issuecomment-930515422): since every `GET /security/user/authenticate` mention in our Wazuh Docs will be replaced with `POST /security/user/authenticate` I suggest to add a warning message into `Authentication` block referencing this endpoint is about to be deprecated and users should start using the `POST` one.


Regards,
Alexis

**Comment by Kondent** [comment]
# Update
I've been working more on this issue and added few things:
* `GET /security/user/authenticate` headers:
![image](https://user-images.githubusercontent.com/84642680/135678652-bc0c7f9a-cf69-4300-a595-6a6b6a296774.png)
I decided that, since we don't have a specific date of the new Wazuh release, it would be better if this endpoint returns `Deprecated` and `Link` entries in the header so later on we add `Sunset` with that well known date.
* `Link` entry will be pointing to Login block at our API reference. At this point `GET` should already be marked as `Deprecated` since I added that config at `spec.yaml`.
* Refactored integration test configuration to use `POST` endpoint at every test.
* Added integration test for both login endpoints to verify its generated token.
* Fixed `login_user` at `security_controller.py` to handle this modified header.
* Fixed `security_controller` related unit test.
* Fixed wazuh-documentation to reference `/security/user/authenticate` as `POST` instead of `GET`. 

I'm going to give this development a new overall review before opening it's PR.

Regards
Alexis
