### ISSUE TITLE
Review of FIM sync settings to adapt them to the DBsync and Rsync integration

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#10224]
|EPIC|Component|
|---|---|
| https://github.com/wazuh/wazuh/issues/9103 | FIM |

## Description

The FIM synchronization engine implements its own settings as we can see in the [reference documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html#synchronization).

With the rework of the FIM DB and synchronization part, we have to review these settings to define their new behavior.

### File limit
One of the necessary changes to the FIM configuration is related to the maximum limit of entries that were allowed in the database tables, the `file_limit` configuration variable.
In Linux, there was only one table in the database, but for Windows, there are three tables, files, registry and registry values. The `file_limit` variable, in Windows, indicated the maximum limit of the three tables combined.
 
Due to the new implementation with DBSync, it will now be necessary to add a second similar value to indicate, separately, the limit of entries in both of the tables.
Files on the one hand, and registry and registry values on the other hand.

### Update

We will add a separate limit for file and registry entries. The first one will apply to the `file` table and the second one, to the `registry_key` and the `registry_value` tables.

**Old configuration**
```xml
<!-- Maximum number of files to be monitored -->
<file_limit>
  <enabled>yes</enabled>
  <entries>100000</entries>
</file_limit>
```

**New configuration**
```xml
<!-- Maximum entries in the FIM database -->
<db_entry_limit>
  <enabled>yes</enabled>
  <files>100000</files>
  <registries>100000</registries>
</db_entry_limit>
```

**Requirements**
- Old `<file_limit>` block should be still supported, including an informational log when read to inform about the new method.
- Replace the block in the configuration template.

**Comment by JoseAntonioMHerrera** [comment]
After reviewing the current syscheck options and how they are implemented in the rsync library, I think all of them should stay for the following reasons:

* max_eps and queue_size, based on the implementation by callbacks well the max_eps is passed as a parameter (wm_sys_send_dbsync_message function example) and the initialization of the syscheck queue needs a size parameter.

* enabled and interval are two parameters in charge of the synchronization taking place and the interval between synchronization processes.

* registry_enabled enables or disable de registries synchronization.

* max_interval and response timeout are on hold for know, I didn't find anything related to those in rsync implementation.

**Comment by JoseAntonioMHerrera** [comment]
**Update**: The substitution of the older fim synchronization options requires a code refactor affecting other issues like a rework of fim scan function and fim DB status check, among others. This issue will be set as stale to avoid working on things that will be reviewed again in the future. Following there is a list of things to take into account when we get back to this issue:

* Adapt the new two limits (files and registries) to the function checking the database state (Full, 80%, etc...)
* Adapt the debug messages to take account of the file limit and registry limit instead of the current message FIM_FILE_LIMIT_VALUE
* Check the unit tests using file_limit and substitute them/adapt them to use one of the limit options or both.
