### ISSUE TITLE
FIM DBsync and Rsync performance comparative

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#10223]
|EPIC|Component|
|---|---|
| https://github.com/wazuh/wazuh/issues/9103 | FIM |

### Description

The development associated with this issue performs a rework in the FIM engine to handle the databases and the synchronization process.

As a part of the development, we need to validate the performance of the FIM module against the current version.

### Tasks

- [x] Run FIM footprint tests for both versions
- [x] Attach the results in this issue and compare results

**Comment by jotacarma90** [comment]
## First iteration
- Test 1d: https://ci.wazuh.info/view/Tests/job/Test_stress/3130/
- Test 2.5d: https://ci.wazuh.info/view/Tests/job/Test_stress/3131/

Some errors founded, issues related and fixes:
- Problems with parallelism of scheduled and realtime modes
https://github.com/wazuh/wazuh/issues/12787
https://github.com/wazuh/wazuh/issues/12824

- Undefined errors Windows:
https://github.com/wazuh/wazuh/issues/12835

**Comment by jotacarma90** [comment]
## Second iteration
- Test 8h: https://ci.wazuh.info/view/Tests/job/Test_stress/3135/
- Test 1d: https://ci.wazuh.info/view/Tests/job/Test_stress/3136/

**Comment by jotacarma90** [comment]
## Third iteration of test for Windows

Issue comparative:
https://github.com/wazuh/wazuh/issues/13029

**Comment by jotacarma90** [comment]
## Fourth iteration - Comparing results 9103 with 4.3 RC

9103 branch:
- https://github.com/wazuh/wazuh/issues/13403
-https://ci.wazuh.info/job/Test_stress/3194/

4.3 branch:
- https://github.com/wazuh/wazuh/issues/12952
- https://devel.ci.wazuh.info/job/Test_stress/2549/
    

### Windows agent

  |Measure|Status|Comment|
  |---|---|---|
  | CPU | 🟡  | Peaks of the graph are double in 9103 |
  | Disk | 🟢  | Better use of disk in 9103 than 4.3 |
  | Disk_Read | 🟢  | Better in 9103 than 4.3 |
  | Disk_Written | 🟢  | Better in 9103 than 4.3 |
  | Handles | 🟡  | There are about 15 handles more on average |
  | RSS_MAXMIN | 🟢  | 9103 uses slightly more memory than 4.3 (from 18-19MB to 23-24MB)|
  | RSS | 🟢  | 9103 uses slightly more memory than 4.3 (from 18-19MB to 23-24MB)|
  | USS | 🟢  | 9103 uses slightly more memory than 4.3 (from 13-14MB to 18-19MB)|
  | VMS | 🟢  | 9103 uses slightly more memory than 4.3 (from 11-12MB to 14-16MB)|
  | Read_Ops | 🟢 | Better in 9103 than 4.3 |
  | Write_Ops | 🟢  | Better in 9103 than 4.3 |

### Linux agent (CentOS)

  |Measure|Status|Comment|
  |---|---|---|
  | CPU | 🟢  | Same in 9103 and 4.3.0 |
  | Disk | 🟢  | Same in 9103 and 4.3.0 |
  | Disk_Read | 🟢  | Same in 9103 and 4.3.0 |
  | Disk_Written | 🟢  | There is an improvement in 9103 |
  | FD | 🟢  | Same in 9103 and 4.3.0 |
  | PSS | 🟢  | 9103 uses slightly more memory than 4.3 (from 7.5MB to 10MB)|
  | RSS | 🟢  | 9103 uses slightly more memory than 4.3 (from 10MB to 12MB)|
  | RSS_MAXMIN | 🟢  | 9103 uses slightly more memory than 4.3 (from 10MB to 12MB)|
  | Read_Ops | 🟢  | Same in 9103 and 4.3.0 |
  | Write_Ops |  🟢  | There is an improvement in 9103 |
  | SWAP | 🟢  | Same in 9103 and 4.3.0 |
  | USS | 🟢  | 9103 uses slightly more memory than 4.3 (from 7MB to 9MB)|
  | VMS | 🟢  | 9103 uses slightly more memory than 4.3 (from 300MB to 400MB)|

**Comment by jotacarma90** [comment]
After the last tests, we have been analyzing the high CPU values shown by the metrics. We have been running tests with the same script used in the stress tests, looking for cases where these graphs had such high CPU peaks. Gathered a lot of information about how psutil works with the cpu_percent function and how it is used. After an arduous investigation, we have launched new footprint tests to try to find the causes. 
Here is a footprint test with all modules active, to make sure that the CPU did not grow even more:
https://github.com/wazuh/wazuh/issues/13429

Here a footprint test with synchronization disabled:
https://github.com/wazuh/wazuh/issues/13433

In this test the CPU spikes disappear, so it looks like we should take a closer look at how synchronization impacts.

**Comment by jotacarma90** [comment]
## Investigation of high CPU usage of FIM synchronization
After analyzing the synchronization in depth, the problem that causes high CPU usage is the overlapping of consecutive synchronizations. It occurs when the sync interval is much shorter than the total duration of an entire sync.
Some tests related to sync to see how it works:

### Sync without overlap

At first, if the interval is large enough, the synchronization ends without problems.
For this to happen correctly, the `max_eps` of the synchronization must be according to the `queue_size` of the clien_buffer (both in the stress test are set at 10).
If the buffer fills up, messages start to be lost. Synchronization is not terminated correctly in this iteration. And it is necessary to wait for the following synchronizations to complete it correctly.

### Sync with overlap
Configuration for testing:
|`max_eps` in sync | `queue_size` in clien_buffer | FIM entries |
|---|---|---|
| 20 | 20 | ~900 |
With this configuration, a normal synchronization should take about 45 seconds to finish.

Testing by modifying the interval:

| Interval | Duration |
|---|---|
| 60 | 47 |
| 30 | 60 |
| 10 | 90 |
| 5 | 124 |
| 1 | 268 |


### Conclusions

When the synchronizations start to overlap with small intervals, the total duration starts to get longer and longer.
It is necessary to add a mechanism that prevents rsync from starting synchronizations if there are still messages between agent and manager.

**Comment by jotacarma90** [comment]
## Testing rsync with just one thread - Comparing results 9103 with 4.3 RC

9103 branch:
- https://github.com/wazuh/wazuh/issues/13403
-https://ci.wazuh.info/job/Test_stress/3194/

4.3 branch:
- https://github.com/wazuh/wazuh/issues/12952
- https://devel.ci.wazuh.info/job/Test_stress/2549/
    

### Windows agent

  |Measure|Status|Comment|
  |---|---|---|
  | CPU | 🟢  | Less use of CPU in 9103 (rsync 1 thread) than 4.3 |
  | Disk | 🟢  | Better use of disk in 9103 than 4.3 in average |
  | Disk_Read | 🟢  | Better in 9103 than 4.3 |
  | Disk_Written | 🟢  | Better in 9103 than 4.3 |
  | Handles | 🟢  | There are about 15 handles more on average |
  | RSS_MAXMIN | 🟢  | 9103 uses slightly more memory than 4.3 (from 18-19MB to 23-24MB)|
  | RSS | 🟢  | 9103 uses slightly more memory than 4.3 (from 18-19MB to 23-24MB)|
  | USS | 🟢  | 9103 uses slightly more memory than 4.3 (from 13-14MB to 18-19MB)|
  | VMS | 🟢  | 9103 uses slightly more memory than 4.3 (from 11-12MB to 14-16MB)|
  | Read_Ops | 🟢 | Better in 9103 than 4.3 |
  | Write_Ops | 🟢  | Better in 9103 than 4.3 |

After these tests we were able to verify that the cause of the high CPU usage peaks was due to the parallelism used internally by rsync.
We have come to the conclusion that the FIM synchronization in the stress tests is constantly running, due to the fact that all the time events are being lost due to buffer overflow, full queues, etc.

For this reason, the old synchronization (which worked with a single thread) had less CPU usage.
We can say that now the FIM synchronization (with rsync) works faster because of the parallelization, which, added to the fact that the synchronization is permanently active, causes a higher CPU usage.

### Linux agent (CentOS)

  |Measure|Status|Comment|
  |---|---|---|
  | CPU | 🟢  | Same in 9103 and 4.3.0 |
  | Disk | 🟢  | Same in 9103 and 4.3.0 |
  | Disk_Read | 🟢  | Same in 9103 and 4.3.0 |
  | Disk_Written | 🟢  | There is an improvement in 9103 |
  | FD | 🟢  | Same in 9103 and 4.3.0 |
  | PSS | 🟢  | 9103 uses slightly more memory than 4.3 (from 7.5MB to 10MB)|
  | RSS | 🟢  | 9103 uses slightly more memory than 4.3 (from 10MB to 12MB)|
  | USS | 🟢  | 9103 uses slightly more memory than 4.3 (from 7MB to 9MB)|
  | VMS | 🟢  | 9103 uses slightly more memory than 4.3 (from 300MB to 400MB)|
  | RSS_MAXMIN | 🟢  | 9103 uses slightly more memory than 4.3 (from 10MB to 12MB)|
  | Read_Ops | 🟢  | Same in 9103 and 4.3.0 |
  | Write_Ops |  🟢  | There is an improvement in 9103 |
  | SWAP | 🟢  | Same in 9103 and 4.3.0 |
  
  
### Linux agent (Ubuntu)

  |Measure|Status|Comment|
  |---|---|---|
  | CPU | 🟢  | Slightly more in 9103 than 4.3.0 |
  | Disk | 🟢  | Same in 9103 and 4.3.0 |
  | Disk_Read | 🟢  | Same in 9103 and 4.3.0 |
  | Disk_Written | 🟢  | There is an improvement in 9103 |
  | FD | 🟢  | Same in 9103 and 4.3.0 |
  | PSS | 🟢  | 9103 uses slightly more memory than 4.3 (from 7.5MB to 10MB)|
  | RSS | 🟢  | 9103 uses slightly more memory than 4.3 (from 10MB to 12MB)|
  | USS | 🟢  | 9103 uses slightly more memory than 4.3 (from 7MB to 9MB)|
  | VMS | 🟢  | 9103 uses slightly more memory than 4.3 (from 300MB to 400MB)|
  | RSS_MAXMIN | 🟢  | 9103 uses slightly more memory than 4.3 (from 10MB to 12MB)|
  | Read_Ops | 🟢  | Same in 9103 and 4.3.0 |
  | Write_Ops |  🟢  | There is an improvement in 9103 |
  | SWAP | 🟢  | Same in 9103 and 4.3.0 |
