### ISSUE TITLE
Docker wodle on Debian Bullseye agent

### ISSUE THREAD

**Issue by lemrouch** [wazuh/wazuh#10231]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.1-1 | docker-listener | Agent | Packages | Debian 11 |

After upgrade from Debian 10 to 11 the docker listener failed to start as the python2 was removed from server and _/var/ossec/wodles/docker/DockerListener_ has `#!/usr/bin/env python` header.
According to [Debian](https://wiki.debian.org/Python):
> Debian testing (bullseye) has removed the "python" package and the '/usr/bin/python' symlink due to the deprecation of Python 2. No packaged scripts should depend on the existence of '/usr/bin/python'

As workaround I've applied their suggestion and installed _python-is-python3_ and _python3-docker_ packages which solved the problem and the listener is running now.
I'm not sure how to fix this in more systematic way.

**Comment by vikman90** [comment]
Hi @lemrouch,

Thank you for reporting this. I think this issue is related to #4879. Curiously, I'm still able to install Python 2 on Debian 11:

```sh
apt-get install python
```

As the documentation states ([Monitoring containers activity](https://documentation.wazuh.com/current/docker-monitor/monitoring_containers_activity.html)), the Docker Listener module currently requires Python 2.7. The reason for this is that it needs to support RHEL 6, which does not support Python 3.

As we explained in the issue above, these commands should help to link `python` command to `python3`:

- RHEL / CentOS 8:
```sh
alternatives --set python /usr/bin/python3
```

- Ubuntu 20.04 / Debian 11:
```sh
apt install python-is-python3
```
(Just as you made).

As you mentioned, operating systems are removing support for Python 2. Given that we need to support a wide range of OSs, we should either wrap the scripts to support both Python 2 and 3, or include Python 3 along with the agent (like the manager).

Thank you again.
Best regards.
