### ISSUE TITLE
wazuh can not using syscollector information to trigger alerts

### ISSUE THREAD

**Issue by feitianxuxueyaya** [wazuh/wazuh#10290]
|Wazuh version|Component|Install type|Install method|Platform|
|V4.2.0|manager|rpm|rpm -ivh  wazuh-manager-4.2.0-1.x86_64.rpm|centos7|

| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

we use wazuhv4.2.0, we want to using syscollector information to trigger alerts ,but wo can not get alert log.
we moidiy configure /var/ossec/etc/rules/local_rules.xml, and add content:
<group name="wazuh,"> 
        <rule id="221" level="12" overwrite="yes">
                <category>ossec</category>
                <decoded_as>syscollector</decoded_as>
                <description>Syscollector event.</description>
                <options>no_full_log</options>
        </rule>
</group>

but we find some syscollector information  in /var/ossec/queue/db/001.db

**Comment by jnasselle** [comment]
Hi @feitianxuxueyaya ,

It's seems that there was an error while copy-pasting your custom rule. Could you please share it again? I'll wait this information to move forward.

Regarding to your db mention, Wazuh v4.2.0 Syscollector involves a key change between agent and manager mechanism in order to, mainly, avoid network traffic consumption.
Let me explain to you how this new model works:
1. The first time the Wazuh agent starts, all system data will be collected and stored in a local database called local.db (this is new comparing the previous syscollector model)
	a. In Windows you'll see this database under `C:\Program Files(x86)\ossec\queue\syscollector\db` path.
	b. In non-Windows you'll see this database under `/var/ossec/queue/syscollector/db` path.

This data (the 100% of it) will be synchronized with the Wazuh server to be stored in their agend ID database and then be displayed under System Inventory Wazuh Dashboard.
2. When the [`interval`](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-syscollector.html#interval) being configured in the [`syscollector wodle tag`](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-syscollector.html) is reached, a new scan for system data will happen taking into account the previous already stored local data.
3. The real difference between the 1st scan data (100% of data) and the 2nd one obtained will be updated in the local database.
4. This difference/delta of information will be synchronized with the Wazuh server to be stored, as it did in the step 1.
5. This process will continue every time the interval being configured in the syscollector wodle tag is reached storing the data locally and synchronizing it with the Wazuh server for consistency.
The real benefit here is that Syscollector now sends chunks/deltas of information to the Wazuh server instead of the 100% of the data scanned each time.

Regards,
Nico

**Comment by feitianxuxueyaya** [comment]
we moidiy configure /var/ossec/etc/rules/local_rules.xml<group name="wazuh,">
  <rule id="221" level="3" overwrite="yes">
    <category>ossec</category>
    <decoded_as>syscollector</decoded_as>
    <description>Syscollector event.</description>
    <options>no_full_log</options>
  </rule>
</group>

**Comment by jnasselle** [comment]
Hi @feitianxuxueyaya ,

We are sorry to hear that you are experiencing this inconvenience. Unfortunately this feature is not working since v4.2.0 and new Syscollector architecture. Currently we are working on this issue to solve it: [Populate event_info structure in syscollector decoder #7279](https://github.com/wazuh/wazuh/issues/7279)

Also i opened a [documentation issue](https://github.com/wazuh/wazuh-documentation/issues/4400) to remove the related guide until the functionality is recovered.

Let me think if there's a easy way to temporarily work around this.
 
Regards,
Nico

**Comment by jnasselle** [comment]
Hi @feitianxuxueyaya ,

Unfortunately there's no fully equivalent workaround to this. I'm really sorry about this inconvenience, we are working hard on #7279 to get it into production as soon as possible.

Regards,
Nico
