### ISSUE TITLE
Analisysd memory growth in rootcheck footprint tests

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#10318]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.2- 40216| Analisysd | Manager | Packages/Sources | CentOS7 |

We found an anomalous behavior in the footprint tests launched for 4.2.2-rc2:

- https://github.com/wazuh/wazuh/issues/10280
- https://github.com/wazuh/wazuh/issues/10302

In the rootcheck only tests the memory of analisysd in the manager seems to grow for as long as the manager is receiving events.

![imagen](https://user-images.githubusercontent.com/19505384/134903755-31e17cc2-6cb8-4b7e-be9a-1792770cc543.png)

**Comment by vikman90** [comment]
After digging into this, we can confirm that Analysisd behaves just like in previous versions.

## Configuration

- Custom rootcheck configuration:
```xml
<rootcheck>
  <frequency>10</frequency>
</rootcheck>
```

## 4.2.1 Analysisd process stats

```
16:29                           -RSS-
20240 ossec     20   0 4613.6m  46.9m   3.5m S   1.7   0.2   0:00.27 wazuh-analysisd

16:30                           -RSS-
20240 ossec     20   0 5637.6m  51.2m   3.5m S   0.3   0.2   0:00.80 wazuh-analysisd

16:31                           -RSS-
20240 ossec     20   0 5637.6m  55.6m   3.5m S   0.3   0.2   0:01.38 wazuh-analysisd

16:32                           -RSS-
20240 ossec     20   0 5637.6m  64.1m   3.5m S   0.0   0.3   0:01.97 wazuh-analysisd

16:33                           -RSS-
20240 ossec     20   0 6341.6m  72.6m   3.5m S   4.3   0.3   0:02.61 wazuh-analysisd

16:34                           -RSS-
20240 ossec     20   0 6341.6m  76.7m   3.5m S   0.0   0.3   0:02.98 wazuh-analysisd

16:35                           -RSS-
20240 ossec     20   0 6341.6m  85.2m   3.5m S   0.0   0.3   0:03.46 wazuh-analysisd

16:36                           -RSS-
20240 ossec     20   0 6341.6m  89.1m   3.5m S   1.3   0.3   0:03.73 wazuh-analysisd

16:37                           -RSS-
20240 ossec     20   0 6341.6m  89.1m   3.5m S   0.0   0.3   0:04.14 wazuh-analysisd

16:53
20240 ossec     20   0 6661.6m  89.3m   3.5m S   0.0   0.4   0:10.55 wazuh-analysisd
```

![Analysisd resident memory usage](https://user-images.githubusercontent.com/10536251/135078076-202ab5e6-f1a5-4b25-88e7-d0c6a29195fe.png)

## Valgrind report

- [Valgrind log.txt](https://github.com/wazuh/wazuh/files/7243532/Valgrind.log.txt)

### Comments

- No memory leaks are detected.
- 27.155 MiB have been allocated by the Rootcheck decoder.

## Conclusions

After decoding an event and producing the corresponding alert, Analysisd holds this data in the alert history, in order to match frequency based rules. We estimate that the alert history may take up to 1 GB of memory. This is part of the normal operation of the product and does not mean a memory leak.
