### ISSUE TITLE
Error when processing master's files in the workers

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#10332]
|Wazuh version|Component|
|---|---|
| 4.2 | Wazuh cluster |

## Description

The following error logs have been found in a 4.2 cluster environment:
```
2021/09/28 01:51:08 ERROR: [Worker wazuh-manager-worker-1] [Integrity sync] Found errors: 0 overwriting, 1 creating and 0 removing
2021/09/28 02:25:24 ERROR: [Worker wazuh-manager-worker-1] [Integrity sync] Error processing missing file 'queue/agent-groups/703042': [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/703042'
2021/09/28 02:25:24 ERROR: [Worker wazuh-manager-worker-1] [Integrity sync] Found errors: 0 overwriting, 1 creating and 0 removing
2021/09/28 02:30:08 ERROR: [Worker wazuh-manager-worker-1] [Integrity sync] Error processing missing file 'queue/agent-groups/685679': [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/685679'
2021/09/28 02:30:08 ERROR: [Worker wazuh-manager-worker-1] [Integrity sync] Found errors: 0 overwriting, 1 creating and 0 removing
2021/09/28 02:53:27 ERROR: [Worker wazuh-manager-worker-1] [Integrity sync] Error processing missing file 'queue/agent-groups/702996': [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/702996'
2021/09/28 02:53:27 ERROR: [Worker wazuh-manager-worker-1] [Integrity sync] Found errors: 0 overwriting, 1 creating and 0 removing
2021/09/28 03:00:02 ERROR: [Worker wazuh-manager-worker-1] [Integrity sync] Error processing missing file 'queue/agent-groups/620293': [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/620293'
2021/09/28 03:00:02 ERROR: [Worker wazuh-manager-worker-1] [Integrity sync] Error processing missing file 'queue/agent-groups/703007': [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/703007'
2021/09/28 03:00:02 ERROR: [Worker wazuh-manager-worker-1] [Integrity sync] Error processing missing file 'queue/agent-groups/771262': [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/771262'
2021/09/28 03:00:02 ERROR: [Worker wazuh-manager-worker-1] [Integrity sync] Error processing missing file 'queue/agent-groups/686808': [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/686808'
```

This error or a very similar one has already been reported in https://github.com/wazuh/wazuh/issues/6367, where it should have been fixed. 

What happened in that issue was that the master sent a zip with the files that the worker needed, as well as a JSON with the information of those files. The worker walks through the information in said JSON and tries to move each listed file. However, sometimes the file was not inside the ZIP and this error appeared.

It is possible that the origin of the error is not the same this time, so it will be necessary to investigate.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by AdriiiPRodri** [comment]
## Status update

After several tests, we have not been able to replicate the error `2021/09/29 00:00:00 ERROR: [Worker wazuh-manager-worker-1] [Integrity sync] Error processing missing file 'queue/agent-groups/XXXXX': [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/XXXXX'`. We know that the error probably occurs in the following function:

https://github.com/wazuh/wazuh/blob/9d47d8ff71f3b775b8661f700ed68ee4ff3e7756/framework/wazuh/core/cluster/worker.py#L887-L988

More specifically between the lines:

https://github.com/wazuh/wazuh/blob/9d47d8ff71f3b775b8661f700ed68ee4ff3e7756/framework/wazuh/core/cluster/worker.py#L898-L936

An error within the `overwrite_or_create_files` function can cause an exception to be raised that eventually results in the lines:

https://github.com/wazuh/wazuh/blob/9d47d8ff71f3b775b8661f700ed68ee4ff3e7756/framework/wazuh/core/cluster/worker.py#L949-L952

This could happen in case there is a file inside `files_metadata.json` that does not exist in the ZIP sent to the worker. However, in theory and according to our tests, in case this happens, we introduced a mechanism by which the file would be excluded, we can see it here:

https://github.com/wazuh/wazuh/blob/9d47d8ff71f3b775b8661f700ed68ee4ff3e7756/framework/wazuh/core/cluster/cluster.py#L285-L327

More specifically in the `update_cluster_control_with_failed` function:

https://github.com/wazuh/wazuh/blob/9d47d8ff71f3b775b8661f700ed68ee4ff3e7756/framework/wazuh/core/cluster/cluster.py#L263-L282

In our tests, this mechanism solved the problem even when it was intentionally provoked.

To force this error we have added to the `safe_move` function a line to delete one of the `agent-group` files, by doing this we have managed to replicate the error, however, as we have said before, it should not be possible to get to this function and have such a case occur due to the mechanism mentioned above.

The ZIP file that is sent to the workers is generated from the `files_metadata.json` file, the mechanism already explained is used to check if there is any discrepancy between the moment in which the file is created and the moment of compressing the file. Because of this, as the ZIP is formed from `files_metadata.json`, it should not happen that a file is in `files_metadata.json` and not in the ZIP.

We will continue trying to replicate this bug and look for an alternative method to generate the `files_metadata.json` - file.ZIP pair.

Reference: https://github.com/wazuh/wazuh/issues/6367

**Comment by AdriiiPRodri** [comment]
## Status update

After investigating this problem, we have determined that the root of the problem is what was mentioned in the issue https://github.com/wazuh/wazuh/issues/10365. Therefore, we can conclude that once the issue mentioned here is fixed, the cluster will no longer have problems with synchronization.

Additionally, the error in the cluster was in the `safe_move` function:

https://github.com/wazuh/wazuh/blob/88b11bf4072c7106360b45b8348b27f5f21c6c0a/framework/wazuh/core/utils.py#L577-L609

What happens here to cause this error:
```
2021/10/01 09:24:37 ERROR: [Worker worker2] [Integrity sync] Error processing missing file 'queue/agent-groups/999': [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/999'
```

The master sends us the wrong file, in this case, the file corresponding to agent 999. This file for unknown reasons in the master node is not removed by modulesd, it is important to say that this file is empty and does not correspond to any agent of the system. Then the cluster, since the file exists, synchronizes it with the workers nodes, when this file is received in the workers, as soon as it is received, it generates a temporary file that is a clone of the original file. After this, the temporary file is moved to the target path, in this case, `queue/agent-groups`.

Instantly, the worker modulesd service deletes the file, and when the cluster tries to change the permissions and owner of the file as we see in the lines https://github.com/wazuh/wazuh/blob/88b11bf4072c7106360b45b8348b27f5f21c6c0a/framework/wazuh/core/utils.py#L605-L609 an error of type **FileNotFoundError** is generated that finally causes the error that we see in the log. This is a clusterd-modulesd race condition.

As we have already mentioned the root of the problem seems to be in modulesd, however, the safe_move function is not atomic, because we can see two steps that involve the target path of the file. On the one hand, the first move and on the other hand the change of permissions/owner. To solve this, we have been doing a lot of tests and finally, we have modified the permissions/owner change process.

Now the "Set up metadata" process is performed on the temporary file, which will later be moved to the target path. This way, as the temporary file is managed by the cluster itself, no process will delete it, so we can change its permissions without any external modification. After this, in a single instruction, we send the file to the target path, thus releasing the file and avoiding any kind of race condition.

The code of safe_move with this change looks like this:
```
def safe_move(source, target, ownership=(common.ossec_uid(), common.ossec_gid()), time=None, permissions=None):
    """Moves a file even between filesystems

    This function is useful to move files even when the target directory is in a different filesystem from the source.
    Write permissions are required on the target directory.

    Parameters
    ----------
    source : str
        Full path to source file
    target : str
        Full path to target file
    ownership : tuple
        Tuple in the form (user, group) to be set up after the file is moved
    time : tuple
        Tuple in the form (addition_timestamp, modified_timestamp)
    permissions : str
        String mask in octal notation. I.e.: '0o640'
    """
    # Create temp file. Move between
    tmp_path, tmp_filename = path.split(target)
    tmp_target = path.join(tmp_path, f".{tmp_filename}.tmp")
    move(source, tmp_target, copy_function=copyfile)

    # Set up metadata
    chown(tmp_target, *ownership)
    if permissions is not None:
        chmod(tmp_target, permissions)
    if time is not None:
        utime(tmp_target, time)

    try:
        # Overwrite the file atomically.
        rename(tmp_target, target)
    except OSError:
        # This is the last try when target is still in a different filesystem.
        # For example, when target is a mounted file in a Docker container
        # However, this is not an atomic operation and could lead to race conditions
        # if the file is read/written simultaneously with other processes
        move(tmp_target, target, copy_function=copyfile)
```

We have made the following test, we have forced the bug in the master node by killing the modulesd process. In the worker1 node, we have applied the changes and in the worker2 node, we have left the original function. After about half an hour, this is the log of the worker2 node:

```
root@wazuh-worker2:/# tail -f /var/ossec/logs/cluster.log | grep -i "Error processing"
2021/10/01 09:24:37 ERROR: [Worker worker2] [Integrity sync] Error processing missing file 'queue/agent-groups/999': [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/999'
2021/10/01 09:28:16 ERROR: [Worker worker2] [Integrity sync] Error processing missing file 'queue/agent-groups/999': [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/999'
2021/10/01 09:37:13 ERROR: [Worker worker2] [Integrity sync] Error processing missing file 'queue/agent-groups/989': [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/989'
2021/10/01 09:37:13 ERROR: [Worker worker2] [Integrity sync] Error processing missing file 'queue/agent-groups/990': [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/990'
2021/10/01 09:40:14 ERROR: [Worker worker2] [Integrity sync] Error processing missing file 'queue/agent-groups/998': [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/998'
2021/10/01 09:49:44 ERROR: [Worker worker2] [Integrity sync] Error processing missing file 'queue/agent-groups/992': [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/992'
2021/10/01 09:50:27 ERROR: [Worker worker2] [Integrity sync] Error processing missing file 'queue/agent-groups/993': [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/993'
2021/10/01 09:55:08 ERROR: [Worker worker2] [Integrity sync] Error processing missing file 'queue/agent-groups/991': [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/991'
2021/10/01 09:55:08 ERROR: [Worker worker2] [Integrity sync] Error processing missing file 'queue/agent-groups/990': [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/990'
```

The worker1 node log does not contain any reference to this error:
```
root@wazuh-worker1:/# cat /var/ossec/logs/cluster.log | grep -i "Error processing"
root@wazuh-worker1:/#
```

As for the files, in the master node we can see that even their permissions, as they have been created with root, are wrong:

```
root@wazuh-master:/# ls -la /var/ossec/queue/agent-groups/  
total 40
drwxrwx---. 1 root   ossec 194 Oct  1 03:16 .
drwxr-x---. 1 root   ossec 234 Oct  1 01:32 ..
-rw-rw----. 1 ossecr ossec   8 Oct  1 01:24 002
-rw-rw----. 1 ossecr ossec   8 Oct  1 01:24 003
-rw-rw----. 1 ossecr ossec   8 Oct  1 01:24 006
-rw-rw----. 1 ossecr ossec   8 Oct  1 01:25 007
-rw-rw----. 1 ossecr ossec   8 Oct  1 01:25 008
-rw-rw----. 1 ossecr ossec   8 Oct  1 01:25 009
-rw-rw----. 1 ossecr ossec   8 Oct  1 01:26 010
-rw-rw----. 1 ossecr ossec   8 Oct  1 01:28 012
-rw-rw----. 1 ossecr ossec   8 Oct  1 01:28 013
-rw-rw----. 1 ossecr ossec   8 Oct  1 01:28 014
-rw-r--r--. 1 root   root    0 Oct  1 03:16 980
-rw-r--r--. 1 root   root    0 Oct  1 03:16 981
-rw-r--r--. 1 root   root    0 Oct  1 03:16 982
-rw-r--r--. 1 root   root    0 Oct  1 03:16 983
-rw-r--r--. 1 root   root    0 Oct  1 03:16 984
-rw-r--r--. 1 root   root    0 Oct  1 03:16 985
-rw-r--r--. 1 root   root    0 Oct  1 03:16 986
-rw-r--r--. 1 root   root    0 Oct  1 03:15 987
-rw-r--r--. 1 root   root    0 Oct  1 03:15 988
-rw-r--r--. 1 root   root    0 Oct  1 02:58 989
-rw-r--r--. 1 root   root    0 Oct  1 02:58 990
-rw-r--r--. 1 root   root    0 Oct  1 02:58 991
-rw-r--r--. 1 root   root    0 Oct  1 02:58 992
-rw-r--r--. 1 root   root    0 Oct  1 02:58 993
-rw-r--r--. 1 root   root    0 Oct  1 02:58 994
-rw-r--r--. 1 root   root    0 Oct  1 02:58 995
-rw-r--r--. 1 root   root    0 Oct  1 02:58 996
-rw-r--r--. 1 root   root    0 Oct  1 02:12 997
-rw-r--r--. 1 root   root    0 Oct  1 02:12 998
-rw-r--r--. 1 root   root    0 Oct  1 02:08 999
-rw-r--r--. 1 root   root    0 Oct  1 02:25 testing
```

In addition to agent files, we have created a file called "testing" which does not correspond to any agent in order to see if the permissions are changed correctly after applying the changes in the worker1:

```
root@wazuh-worker1:/# ls -la /var/ossec/queue/agent-groups/  
total 40
drwxrwx---. 1 root  ossec  74 Oct  1 10:02 .
drwxr-x---. 1 root  ossec 234 Sep 21 11:12 ..
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 002
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 003
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 006
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 007
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 008
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 009
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 010
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 012
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 013
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 014
-rw-rw----. 1 ossec ossec   0 Oct  1 08:25 testing
```

As we can see the permissions are correct and equal to the ones produced in the worker2 node which does not have the change:

```
root@wazuh-worker2:/# ls -la /var/ossec/queue/agent-groups/ 
total 40
drwxrwx---. 1 root  ossec  74 Oct  1 10:03 .
drwxr-x---. 1 root  ossec 234 Sep 21 11:12 ..
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 002
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 003
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 006
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 007
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 008
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 009
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 010
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 012
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 013
-rw-rw----. 1 ossec ossec   8 Oct  1 07:32 014
-rw-rw----. 1 ossec ossec   0 Oct  1 08:25 testing
