### ISSUE TITLE
Fail to import ossec dashboards into kibana

### ISSUE THREAD

**Issue by dseira** [wazuh/wazuh#104]
I've followed the guide http://wazuh-documentation.readthedocs.io/en/latest/ossec_elk.html to deploy wazuh in a single-host installation.

I've used the **01-ossec-singlehost.conf** for the logstash configuration.

The elasticsearch also works:

**curl -XGET http://localhost:9200/**
```
{
  "name" : "ossec1",
  "cluster_name" : "ossec",
  "cluster_uuid" : "kdsJsDotQUqZB7DZTKdAIg",
  "version" : {
    "number" : "2.4.4",
    "build_hash" : "fcbb46dfd45562a9cf00c604b30849a6dec6b017",
    "build_timestamp" : "2017-01-03T11:33:16Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.2"
  },
  "tagline" : "You Know, for Search"
}
```

**curl -XGET 'http://localhost:9200/_cluster/health?pretty=true'**
```
{
  "cluster_name" : "ossec",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 10,
  "active_shards" : 10,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
```

The problem comes when I try to import the dashboard into kibana. It shows the following error:

``` Saved Objects: Could not locate that index-pattern (id: ossec-*) ```

I've also checked that there are some alerts in the alerts.json:

```
{"rule":{"level":3,"comment":"SSHD authentication success.","sidid":5715,"firedtimes":2,"groups":["syslog","sshd","authentication_success"],"PCI_DSS":["10.2.5"]},"srcip":"1.1.1.1","dstuser":"root","full_log":"Apr 20 02:48:07 ubuntu14 sshd[10579]: Accepted password for root from 1.2.3.4 port 49498 ssh2","program_name":"sshd","decoder":{"fts":2816,"parent":"sshd","name":"sshd"},"hostname":"ubuntu14","agentip":"1.1.1.1","timestamp":"2017 Apr 20 02:51:17","location":"/var/log/auth.log"}
{"rule":{"level":3,"comment":"Login session opened.","sidid":5501,"firedtimes":2,"groups":["pam","syslog","authentication_success"],"PCI_DSS":["10.2.5"]},"full_log":"Apr 20 02:48:07 ubuntu14 sshd[10579]: pam_unix(sshd:session): session opened for user root by (uid=0)","program_name":"sshd","decoder":{"name":"pam"},"hostname":"ubuntu14","agentip":"1.1..1","timestamp":"2017 Apr 20 02:51:17","location":"/var/log/auth.log"}
{"rule":{"level":3,"comment":"Ossec agent started.","sidid":503,"firedtimes":1,"groups":["ossec"],"PCI_DSS":["10.6.1"]},"full_log":"ossec: Agent started: 'ubuntu14->1.1.1.1'.","data":"ubuntu14->1.1.1.1","decoder":{"fts":784,"parent":"ossec","name":"ossec"},"hostname":"ubuntu14","agentip":"1.1.1.1","timestamp":"2017 Apr 20 02:51:33","location":"ossec"}

```

It seems that logstash doesn't read the alerts.json properly.

The version are the following:

```
wazuh-ossec - cloned from https://github.com/wazuh/wazuh.git ossec-wazuh using stable branch
OS  - Centos 7
elasticsearch-2.4.4-1.noarch
logstash-2.1.3-1.noarch
kibana-4.5.4-1.x86_64
```

Can anyone help?

**Comment by lthaele** [comment]
Hi *,

same Problem here. You will need to change the logstash Config to rename a lot of the used Variables. For Example you will need to covert PCI_DSS to lowercase. The reason is that the 5.0 Config using the non stable 2.0 Version of wazuh which has other Variable names. The 5.0 Version should actually be placed in the non stable Trunk. Either use the older  Versions of the dashboard and Elasticsearch Config .Or you will have to fix you logstash Config. I got the PCI and the OSSEC Dashboard running this way. You may also get the FIM Dashboard running.

**Comment by snaow** [comment]
Hi David, Ithaele,

Thanks you both for the feedback and help, I'll try to help here.

Ithaele is right, there are two different configuration depending if you
are on Wazuh 1.1.1 + Elastic 2.0 or Wazuh 2.0 + Elastic 5.0.

I can see on your really well detailed post, you are using Elastic 2.0 and
Wazuh 1.1.1, in order to import Kibana dashboards you will need to download
and load Dashboard file from stable branch:

https://github.com/wazuh/wazuh/blob/stable/extensions/kibana/kibana-ossecwazuh-dashboards.json


Main differences between 1.1.1. and 2.0 are the lowercase rework we did,
like Ihtaele said and the rename to use wazuh-alerts-* index pattern
instead ossec-*.


The error you got:

Saved Objects: Could not locate that index-pattern (id: ossec-*)


Means you did not created the index pattern for ossec-*, if you already
have data in your Elasticsearch cluster (check indices), create the index
pattern on Kibana before importing the dashboards:

http://wazuh-documentation.readthedocs.io/en/latest/ossec_elk_kibana.html#ossec-alerts-index
>


Hope it helps, please let us know if you need any more help.

Cheers,
Pedro.

**Comment by dseira** [comment]
It is working right now.

So, I can assume that the official documentation (http://wazuh-documentation.readthedocs.io/en/latest/) is for the 1.1.1 branch (plus elasticsearch 2 and kibana 4), isn't it?

Are there any guide to explain how to deploy wazuh 2 with kibana 5? Is the wazuh-ui for kibana 5 like the dashboard that appears in your website https://wazuh.com/ (looks really nice)?

Thanks!
David

**Comment by jesuslinares** [comment]
@dseira Yes, it is for Wazuh 1.1.1.

Here the beta documentation (Wazuh 2, Kibana 5): https://documentation-dev.wazuh.com/installation-guide/upgrading/index.html

Regards.

**Comment by dseira** [comment]
Cool!

Is wazuh 2 ready for production environments (medium to large environments) or should I still use the stable branch (1.1.1)?

Thanks,
David

**Comment by snaow** [comment]
Hi @dseira,

Wazuh 2.0 is more than ready for production environments, fully enterprise-ready.

We took our time to prepare everything, introducing some big changes (as OpenSCAP, dynamic fields, Wazuh Modules, SQLite DB's, Authd performance for large environments..), because all of those great improvements we have been testing Wazuh 2.0 for months, assuring performance and reliability.

I believe this great release will suppose great improvements to the entire Wazuh ecosystem.

Feel free to take a look into our documentation:

- [https://documentation.wazuh.com/2.0/](https://documentation.wazuh.com/2.0/)

Release notes (changelog):

- [https://github.com/wazuh/wazuh/releases/tag/v2.0](https://github.com/wazuh/wazuh/releases/tag/v2.0)

As usual, we really appreciate all your feedback, thanks.

Regards,
Pedro 'snaow' Sanchez.

**Comment by dseira** [comment]
Perfect.

Thanks,
David
