### ISSUE TITLE
Investigate to make the API `version` filter work with different Wazuh version formats

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#10426]
|Wazuh version|Component|
|---|---|
| 4.4.0 | API |

Right now, the `version` parameter used to filter by agent version in the API requests only works if we specify the agent version following the format: `Wazuh vX.Y.Z`

https://github.com/wazuh/wazuh/blob/9d109cc7e88c636cf70b911ad3e7ff4042eca86c/api/api/spec/spec.yaml#L4566-L4572

In this issue, we should investigate how to make the filter work with other Wazuh version formats. Formats like `X.Y.Z` or `vX.Y.Z` should be allowed when using this filter.

In case we cannot add these new formats, we could create a new validator in `validator.py` to indicate the specific format that the `version` parameter must follow.

#### Example:

Request

`GET /agents?select=version&version=Wazuh%20v4.3.0
`

Response: 

```
{
  "data": {
    "affected_items": [
      {
        "version": "Wazuh v4.3.0",
        "id": "000"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents information was returned",
  "error": 0
}
```

Request

`GET /agents?select=version&version=v4.3.0
`

Response

```
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "No agent information was returned",
  "error": 0
}
```

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Kondent** [comment]
## Issue update

### Endpoints using the `version` parameter:
* `DELETE /agents`
* `GET /agents`
* `PUT /agents/upgrade`
* `PUT /agents/upgrade_custom`
* `GET /agents/upgrade_result`
* `GET /experimental/syscollector/os`


### Possible solution `#1`

Since the possibilities of labeling a version could be the following:
* `wazuh vX.Y.Z`.
* `wazuh X.Y.Z`.
* `X.Y.Z`.
* `vX.Y.Z`.

We can implement a mechanism in which the value of the `version` parameter is verified and completed to match the `wazuh vX.Y.Z` schema.
The main disadvantage of this scenario is that there's no validation (at the spec file) and the value will be a string with no special formatting.


### Possible solution `#2`
There's a validator already implemented to verify wazuh version but it's only used for agent upgrading.

https://github.com/wazuh/wazuh/blob/1963cbee77e1c26c711410c1f92ab01e1cef1e48/api/api/spec/spec.yaml#L5321-L5327

https://github.com/wazuh/wazuh/blob/1963cbee77e1c26c711410c1f92ab01e1cef1e48/api/api/validator.py#L37

https://github.com/wazuh/wazuh/blob/1963cbee77e1c26c711410c1f92ab01e1cef1e48/api/api/validator.py#L355-L357

Using this validator, the version schemas `vX.Y.Z` and `X.Y.Z` will be valid. 
However as we saw in this issue description, this filter will not retrieve data from the database. It should be modify to match the `wazuh vX.Y.Z` pattern.
Since the `version` parameter is being used by several endpoints, the mentioned modification could be done at `WazuhDBQueryAgents`.


### Possible solution `#3`

_This is similar to the possible solution `#2`_.
We can specify a pattern to the `version` parameter at the `spec.yaml` and it will be used as a validator. This will raise a `bad request` error if it's not properly formatted.

> pattern:
> The pattern keyword lets you define a regular expression template for the string value. Only the values that match this template will be accepted.

For example, with the following pattern `^wazuh v[0-9][.][0-9][.][0-9]$` we have:
`GET /agents?select=version&version=v4.3.0`:
```json
{
  "title": "Bad Request",
  "detail": "'v4.3.0' does not match '^wazuh v[0-9][.][0-9][.][0-9]$'. Failed validating 'pattern' in schema: {'pattern': '^wazuh v[0-9][.][0-9][.][0-9]$', 'type': 'string'}. On instance: 'v4.3.0'"
}
```

To maintain consistency, the solution `#2` is preferable over this.

---
### Conclusion
Finally, I think the scenario `#2` is our best choice. I'll keep on going with the investigation and further modifications.
