### ISSUE TITLE
Logcollector events wrongly parsed for filenames with colons (:)

### ISSUE THREAD

**Issue by orsifacundo** [wazuh/wazuh#10489]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.2 | Logcollector | Agent | all | Linux |

Hi team, I'm getting a parse problem on the events for logfiles with a name similar to `2021-10-12.00:00:00.log` that has JSON events like `{KEY:VALUE}` . The events that arrive to the Wazuh Manager are shown as:

```
{"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"003","name":"899bd9c3d944","ip":"172.18.0.2"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"00:00.log:{KEY:VALUE}","decoder":{},"location":"PATH/2021-10-12.00"}
```
The `location` field doesn't have the full path (**PATH/2021-10-12.00**) and the last part of the filename is part of the `full_log` field (**"full_log":"00:00.log:{KEY:VALUE}"**)

The `localfile` block is like:

```
	<localfile>
		<location>PATH/*.log</location>
		<log_format>syslog</log_format>
	</localfile>
```

So that's breaking the JSON decoder and the events is not being decoded.

**Comment by branchnetconsulting** [comment]
This is seriously broken even in 4.3.6.  Please fix it.  I need to reach eve*.json files from Security Onion sensors that have a filename format like 
`/nsm/suricata/eve-2022-08-11-01:01.json`
and the json records get parsed as syslog lines instead of JSON with a prefix of "01.json" at the beginning of full_log.  It is completely valid to have colons in Linux filenames and I have no way to change Security Onion's file naming convention.
It appears that the colon in the filename is getting misinterpreted as the delimiter between the location and the log line in the event as it is inserted into the Wazuh event queue: 
`1:/nsm/suricata/eve-2022-08-11-01:01.json:{THE JSON RECORD HERE}`
