### ISSUE TITLE
Master node generates agent DBs (with no agents connected to it)

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh#10481]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.2-40316 | remoted | Manager | Packages | Any OS |

Hello Team,

The Wazuh manager master node is generating Wazuh agents DB files under `/var/ossec/queue/db/` when no agents are connected to it.

This issue will cause a lot of disk usage in the master node, even more, when you have ephemeral systems that are being created and destroyed dynamically.

I hope you can solve this.

Thank you in advance!

**Comment by MarcelKemp** [comment]
## Description

After researching the problem, I have been able to obtain the following information:

This problem seems to happen in the manager whenever we have an ID stored in the _global wdb_, but we don't have any DB created for that agent (it can happen when an agent is registered but not yet connected to any manager), then when trying to access it, an empty database is created for that ID.

According to the code, this happens when accessing the `wdb_parse()` function with an agent ID different from the manager, and where you can check in the _global wdb_ that the agent ID exists (`wdb_global_agent_exists()`). After performing these checks, it tries to open the agent database (`wdb_open_agent2()`), but as it does not exist, a new empty database is generated (`wdb_create_agent_db2()`).

In the case of a cluster, if we try to access the database through an **_API query_**, since we don't know which node the agent is connected to, then all the queries are sent to the **master** node and that's where the empty databases are generated.

### Steps to replicate it:
1. Register an agent without connecting it to any manager. Ex:
- From the API, we can use the following query: [POST /agents](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.add_agent)
- It is also possible to register it through `manage_agents` or `agent_auth`.
2. Perform a GET query to obtain some information about the agent. Ex: 
- [GET /syscollector/{agent_id}/hotfixes](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_hotfix_info)
- [GET /syscollector/{agent_id}/os](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_os_info)

3. It would return a result of the empty table (generating in turn the DB). Ex: 
```json
{"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 0, "failed_items": []}, "message": "No syscollector information was returned", "error": 0}
```

4. Check that in the **_master node_** the empty database has been generated.
