### ISSUE TITLE
wazuh log show Cannot find the ID of the agent. Source agent ID is unknown.

### ISSUE THREAD

**Issue by 384691251** [wazuh/wazuh#10503]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.3 | Wazuh component | Manager/Agent | Packages/Sources | OS version |

![image](https://user-images.githubusercontent.com/15191138/137251598-9e7c9c5e-9206-41ff-b7c6-a8d6d66e801a.png)
The wazuh manager’s ossec.log shows that there is an IP that cannot find the agent ID, but all my agents are active. I still can see this warning after restarting wazuh-manager. I don't know this IP. What should i do?

**Comment by TomasTurina** [comment]
Hi @384691251.

Yes, I think your problem is that you removed those agents and they are trying to reconnect with the manager, which cannot recognize them.

To solve this, you will need to re-register the agents again. If these agents can change their IP during time, I recommend you to register them using `any` as IP as I explained before.

Regarding the IP that you see in the Kibana dashboard, it is the one of the interface that is directly connected to the manager, so I'm afraid you want to be able to see the public IP if the communication is within a private network.

I hope this information helps.

Best regards.

**Comment by DougEllis** [comment]
Hello, I am seeing the same from my syslog (firewall) i have added the ip to the ossec.conf
