### ISSUE TITLE
Wazuh 4.2.3 - CIS Benchmarks report 'failed' for correct values

### ISSUE THREAD

**Issue by commandline-be** [wazuh/wazuh#10600]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---
|4.2.3|CIS-CAT|oneshot|packages|Linux|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |
| ??????? | CIS- CAT Benchmarks | Wazuh Agent 4.2.3 | ?/? | Centos 8.x

_note: Wazuh Slack is often a graveyard for support requests_

Wazuh 4.2.3 CIS Benchmark for Debian/Linux 10 is showing failed for values which do have the correct setting.  One setting doubled-checked is for `sysctl -a | grep kernel.randomize_va_space`  which is at the correct value of 2

I think it's fair to say other such benchmarks also show failed for correct values.

**Comment by commandline-be** [comment]
Thanks for this. I hope Wazuh builds a test for each of these :-)

How do i onboard these corrections ?

**Comment by jcruzlp** [comment]
Yes, after this issue we realized how badly we need to test each check of SCA, but it's a difficult task. At the moment, we will enforce and be more strict with testing the policies to avoid this.

Regarding loading the fixed version, you need to add it manually to the agent (since it stills in development), nevertheless the issue is not yet closed, I needed to put it aside to give more priority to the release of the 4.3 version. These checks should fix the issue, but not all the policy is checked and 100% tested. If you need it in a hurry then you can replace the file from the branch I mentioned in the comment in `/var/ossec/ruleset/sca` by removing what is there and adding the new file with the new name. But I would recommend waiting a bit more, thank you for your patience.

**Comment by commandline-be** [comment]
Thanks, i realised after posting i could do this myself. For me this is really a blocking factor since i now cannot rely on anything Wazuh reports. I'm also facing the fact Wazuh is unable to report vulnerabilities on Microsoft outside of patch levels for the OS.

My suggestion is to stop adding features and work on reliabilty exclusively, it is the crux of this type of software.

**Comment by 72nomada** [comment]
Hi @commandline-be, thanks so much for your feedback. 

We will provide updates about the work done to improve consistence and reliability of the SCA and Vulnerabilities reporting included features. As @jcruzlp says many tasks are ongoing internally to achieve this. SCA full review is in progress and expected to be done by 4.4.0 release, this will include current and missing ones.

In the meantime, any new public SCA released, or rework done will be available in wazuh/wazuh master repo so you can install in your environment as needed without waiting for 4.4.0 

Thanks to your and many others feedback, Wazuh is becoming better and better. Please keep pointing us where we will be more useful to your projects and stay tuned.

**Comment by 72nomada** [comment]
Moving SCA issues to 4.4.0 review. closing this
