### ISSUE TITLE
Vulnerability detector is not able to detect CVEs that depends on generic windows version

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#10633]
# Description

When Vulnerability detector uses the NVD to scan Windows agents, it was found that are some specific vulnerabilities that aren't processed correctly. 
In particular, if the OS is a dependency and it is not written with a specific version but in a generic way, the scanner doesn't considers it as a match. 

This case must be covered by the scanner, but without introducing false positives due to a generic CPE.

## More details

We found that CVEs that contains `running on/with` software configuration does not apply because it is not matching both criteria. 
i.e:  `cpe:2.3:o:microsoft:windows:-:*:*:*:*:*:*:*`

For this case, we are not translating a product name `windows` in function `wm_vuldet_generate_win_cpe()`

```C
int wm_vuldet_generate_win_cpe(scan_agent *agent) {
    STATIC const char *PR_WINXP = "windows_xp";
    STATIC const char *PR_WINVISTA = "windows_vista";
    STATIC const char *PR_WIN7 = "windows_7";
    STATIC const char *PR_WIN8 = "windows_8";
    STATIC const char *PR_WIN81 = "windows_8.1";
    STATIC const char *PR_WIN10 = "windows_10";
    STATIC const char *PR_WIN11 = "windows_11";
    STATIC const char *PR_WIN2003 = "windows_server_2003";
    STATIC const char *PR_WIN2008 = "windows_server_2008";
    STATIC const char *PR_WIN2012 = "windows_server_2012";
    STATIC const char *PR_WIN2016 = "windows_server_2016";
    STATIC const char *PR_WIN2019 = "windows_server_2019";
    STATIC const char *PR_WIN2022 = "windows_server_2022";
    STATIC const char *PR_WINSERVER = "windows_server";
    STATIC const char *VER_R2 = "r2";
    STATIC const char *VER_2022 = "2022";
```
The following CVE is affected by this: https://nvd.nist.gov/vuln/detail/CVE-2021-33500

**Comment by mlipscombe** [comment]
This seriously limits the utility of vulnerability scanning on Windows.  There are currently over 5,000 CVEs that will not match because of this bug, including almost every CVE for an Adobe product.

https://nvd.nist.gov/vuln/search/results?results_type=overview&search_type=all&form_type=Advanced&isCpeNameSearch=false&cpe_vendor=cpe%3A%2F%3Amicrosoft&cpe_product=cpe%3A%2F%3A%3Awindows&orderBy=publishDate&orderDir=desc

**Comment by jnasselle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core---Data-Pirates-603911cf3cadd10015e69707/issues/wazuh/wazuh/10633?planning-poker) with ZenHub @pereyra-m @MiguelazoDS @HanesSciarrone @Dwordcito

**Comment by pereyra-m** [comment]
### Analysis

To reproduce this issue, follow the steps provided by @MiguelazoDS in https://groups.google.com/g/wazuh/c/QkeA-i6tv0Y/m/lGgxExE9AgAJ.

It's necessary to update the `wm_vuldet_check_nvd_logical()` method because it contains some errors:
- The `VU_GET_MATCHES_AND` query gets the wrong ID
- The bind of the `VU_GET_CPE_AND` query is using the wrong STMT
- The `VU_GET_AGENTCPE_AND` query has syntax errors and it can't be prepared

After fixing these errors, it is necessary to check if the alerts are generated or if the CPE translation from 
a specific Windows to a generic one is still needed.
Consider also that the fix must be valid also for partial scans, and not only for full scans (where the OS CPE is inserted in the AGENTS table).

**Comment by pereyra-m** [comment]
## Linux agents' scan analysis

We can divide this scan into the following stages:
- First, the OVAL scan occurs in `wm_vuldet_linux_oval_vulnerabilities()`. The matches are stored as potential candidates but they aren't reported still. 
- Then the NVD scan `wm_vuldet_linux_nvd_vulnerabilities()` gets the packages and all the version ranges are compared. The matches are stored as potential candidates but they aren't reported still. This happens in `wm_vuldet_check_generic_package()` and `wm_vuldet_check_specific_package()`. The dependencies (up to `MAX_RELATED_PKGS`) are stored in memory but not compared yet.
- Both partial results (OVAL and NVD) are correlated in `wm_vuldet_linux_rm_false_positives()`. Many steps are taken, but here we are more interested in `wm_vuldet_linux_rm_nvd_not_dependencies_met_packages()`. All the comparisons are done in memory when the dependencies in the Windows agents are checked with queries.

As we can see, this is a long process and completely different from the Windows agents. But it also has a similar problem: in a partial scan, the complete dependencies can't be analyzed and we have to wait for a full scan (even with the kernel).

The possibility of a generic CPE like "running on Linux" wasn't researched.

## Proposal 

After the code analysis, this is a general overview of the work required to fix this issue.
Consider that the case of the Linux agents is different and isn't covered by this proposal. The new column shouldn't affect the Linux agents' scan because it'll be simply ignored. We only need to consider that the legacy behavior of the Wazuh-DB helper is still required to get the packages according to their **TRIAGED** state.

### New column in the AGENTS table

This table is used during the scan of the agents. Vulnerability Detector can only see the agents' software that it copies temporarily to this table for the scan.
- It may be called **SCAN_OR_USE_AS_DEPENDENCY** and its value can only be **SCAN** or **DEPENDENCY**.
- It has an inverse relation with the TRIAGED column: when the **TRIAGED** column for a package is **TRUE**, it means that the package was already scanned so it must be copied to **AGENTS** with **DEPENDENCY**.
- The upgrades don't need to be considered because the `cve.db` database is deleted after the upgrade.

### Adapt the packages insertion methods

Modify all the `wm_vuldet_insert_agent_data()` method calls and the corresponding queries to populate the new column according to the type of scan and/or the triaged state of every package. The **FULL** scan, for example, copies all the software as **SCAN** but the **PARTIAL** scans consider the **TRIAGED** column.
- The Wazuh-DB helper method `wm_vuldet_get_software()` is configured to get only triaged software or all packages. This helper and the corresponding Wazuh-DB side counterparts need to be updated. All the software must be always returned but now we need an extra field in the JSON payload that corresponds with the **TRIAGED** value.
- Use the new returned field as a parameter of `wm_vuldet_insert_agent_data()` and also modify the query to correctly fill the new column.

### New generic CPE 

Generate and insert a new, static, and generic Windows CPE that always will be used for dependencies and never for scans (`cpe:2.3:o:microsoft:windows:-:*:*:*:*:*:*:*`). A correct mapping for all the supported Windows versions must be implemented.
- Use the new modified call to ` wm_vuldet_insert_agent_data()` to always insert this generic CPE as a dependency.
- Make sure that the **CPE_INDEX** table has the corresponding match in the **AGENTS** table even when this generic "windows" package isn't installed (because this is necessary for the dependencies matching queries).

### Scanning methods and queries update

Modify all the queries and methods used during the scan so:
-  The scanning methods only use the packages with the new column enabled (**SCAN** value). The `wm_vuldet_find_nvd_vulnerabilities()` method in the **VU_GET_DICT_CPE** query shouldn't get the packages with the new column set in **DEPENDENCY**.
- The dependencies queries always have to use the complete **AGENTS** table so both **SCAN**/**DEPENDENCY** values are valid. 
- The `wm_vuldet_check_nvd_logical()` method and its queries only need the already known bug fixes and the corresponding logical verification
    - The **VU_GET_MATCHES_AND** query should get the `ID_CPE` value instead of `ID`.
    - The bind of the **VU_GET_CPE_AND** query should be in the STMT `stmt_cpe` and not in `stmt_match`
    - The **VU_GET_AGENTCPE_AND** query can't be prepared because it contains a syntax error. I suggest something like `SELECT CPE_INDEX.ID FROM CPE_INDEX INNER JOIN CPE_INDEX CPEI ON CPEI.VENDOR=? AND CPEI.PRODUCT=? AND CPEI.ID<0 INNER JOIN AGENTS AG ON AG.CPE_INDEX_ID = CPEI.ID AND AG.AGENT_ID=?`

## Research issue: automatic CPE detection experimental feature

It was found that there is a legacy mechanism capable of assigning a CPE automatically to every Windows package without an entry in the CPE helper dictionary. This code isn't being used currently because `wm_vuldet_generate_agent_cpes()` is always called with the **dic** parameter as `true`, so `wm_vuldet_generate_agent_cpes_with_terms()` is never used.

Even do this isn't strictly related to this issue, the lack of CPE for a package prevents its scan and this is an already known weak point of the scanner. But we can't discard that this omission has been intentional.
