### ISSUE TITLE
Issue in AWS-S3 integration with WAZUH manager

### ISSUE THREAD

**Issue by abarnar** [wazuh/wazuh#10644]
Hi Team,

We are currently evaluating WAZUH for our organisation's AWS environment. As part of this process, we are doing a POC exercise where we are analysing Cloudtrail logs which belongs to one of our AWS accounts. I have an s3 bucket where all the Cloudtrail logs are stored.

Activities completed from our end so far:

1. Installed WAZUH server and ElasticSearch server in the EC2 server inside AWS using "All-in-one deployment"(https://documentation.wazuh.com/current/installation-guide/open-distro/all-in-one-deployment/index.html) and "unattended installation"(https://documentation.wazuh.com/current/installation-guide/open-distro/all-in-one-deployment/unattended-installation.html) methods.
2. Launched the Kibana dashboard successfully.
3. Added the "aws-s3" wodle to "ossec.conf" file as given below:

```
<wodle name="aws-s3">
  <disabled>no</disabled>
  <interval>10m</interval>
  <run_on_start>yes</run_on_start>
  <skip_on_error>no</skip_on_error>
  <bucket type="cloudtrail">
  <name>bucket name</name>
  </bucket>
</wodle>
```

4. Restarted the WAZUH manager and got successful message from "ossec.log" file which says the AWS logs are successfully analysed as given below:

```
2021/10/25 06:27:33 wazuh-modulesd:aws-s3: INFO: Starting fetching of logs.
2021/10/25 06:27:33 wazuh-modulesd:aws-s3: INFO: Executing Bucket Analysis: (Bucket: bucket name, Type: cloudtrail)
2021/10/25 06:27:34 wazuh-modulesd:aws-s3: INFO: Fetching logs finished
```

Issue faced:
Despite all the above messages, the AWS-s3 module is not occurring in the Kibana dashboard. 

Workarounds tried so far:
Workaround 1:
I tried running the aws wodle manually using command **sudo /var/ossec/wodles/aws/aws-s3 --bucket bucketname --type cloudtrail --aws_account_id accountidvalue --regions us-east-1 --debug 3** and got the below error.

```
DEBUG: +++ Debug mode on - Level: 3
DEBUG: +++ Working on awsaccountid - us-east-1
DEBUG: +++ Marker: AWSLogs/awsaccountid/CloudTrail/us-east-1/2021/10/25
DEBUG: +++ No logs to process in bucket: awsaccountid/us-east-1
```

However, our buckets have logs present in them.

Workaround 2:
Tried increasing the AWS wodle event level from 0 to 3 in the "0350-amazon_rules.xml" file as mentioned in https://github.com/wazuh/wazuh/issues/3654 which is also not working.

 ```
<!-- AWS wodle -->
    <rule id="80200" level="3">
        <decoded_as>json</decoded_as>
        <field name="integration">aws</field>
        <description>AWS alert.</description>
        <options>no_full_log</options>
    </rule>
```

Observations:
After multiple analysis , we observed that the accepted s3 bucket path by WAZUH is 
**"<bucket_name>/<prefix>/AWSLogs/<account_id>/CloudTrail/<region>/<year>/<month>/<day>"**.

However, the current structure we have in our organisation is "**<bucket_name>/<prefix>/AWSLogs/o-<organisation account>/<account_id>/CloudTrail/<region>/<year>/<month>/<day>**".

Kindly let me know what kind of changes should be made in order to get the cloudtrail logs successfully analysed and have them appear in Kibana dashboard!

**Comment by orsifacundo** [comment]
Hi @abarnar, you are missing a few parameters on the wodle configuration.

The proper wodle block should be similar to this:

```
<wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>1h</interval>
    <run_on_start>yes</run_on_start>
    <bucket type="cloudtrail">
        <name>BUCKET_NAME</name>
        <access_key>ACCESS_KEY</access_key>     
        <secret_key>SECRET_KEY</secret_key>
        <regions>us-east-1</regions>
        <aws_account_id>ACCOUNT_ID</aws_account_id>
        <aws_organization_id>ORGANIZATION_ID</aws_organization_id>
    </bucket>
</wodle>
```
Even though our [documentation states that the bucket path](https://documentation.wazuh.com/current/amazon/services/supported-services/index.html) should be on the format `<bucket_name>/<prefix>/AWSLogs/<account_id>/CloudTrail/<region>/<year>/<month>/<day>` , there is an option that lets you define an organization so the path will look like  `<bucket_name>/<prefix>/AWSLogs/<organization_id>/<account_id>/CloudTrail/<region>/<year>/<month>/<day>`. I'll report the error to our documentation team in order to have them fix this.

The `<access_key>` and `<secret_key>` are optional and it depends on how you have configured your AWS credentials. Also  `<regions>` is optional and if not defined then it'll iterate over all the regions. For your case `<aws_account_id>` and ` <aws_organization_id>` are needed as they are part of the bucket path.

In case that you want to manually run the `aws-s3` script then you need to use this command (with the same considerations given above):

`/var/ossec/wodles/aws/aws-s3 --bucket bucketname --type cloudtrail --aws_account_id accountidvalue --aws_organization_id organizationidvalue --access_key acceskey --secret_key secretkey  --regions us-east-1 --debug 3`

For more information about this configuration you can read this: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#bucket-type

Regards.

**Comment by createchange** [comment]
I just ran up against this for issue for hours. Having finally found this thread after significant wasted time, I was able to resolve the issue.

It would be really nice if the documentation was updated to show that the wodle can accept an option `<organization_id>` parameter.
