### ISSUE TITLE
Custom Rule not work

### ISSUE THREAD

**Issue by oliveiralive** [wazuh/wazuh#10708]
|Wazuh version| Component | Action type |
|---| --- | --- |
| X.Y.Z-rev | Rules/Decoders | New/Error/Improve |

Hi Guys, i want to create a custon rule to netcat connections

By default he connection is loged by the rule bellow
![image](https://user-images.githubusercontent.com/35010493/139869251-27b34000-70fd-4477-a6f3-fce1396d1b78.png)

I create a custom rule bellow adding the *match* ^a0="netcat"|^a0=.netcat, but not work, i read the documentation and tryed many expressions but nothing work, someone help-me?

![image](https://user-images.githubusercontent.com/35010493/139870668-830bc4ac-73b6-4873-8be1-136e635a4d0a.png)

Thanks

**Comment by jcruzlp** [comment]
Hello @oliveiralive,

Seems like you want to trigger a rule when the field `a0` is `netcat`.

The first thing to note is the CDB list, the `check_value` makes the rule only trigger when it's equal to command you can take a deeper look at the cdb syntax here: https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#list

The other thing is the field `<match>`. This will trigger when it contains the value of this, the problem here is that you're using a regex, and the value `^` means that it will search for a string that starts with `a0="netcat"`. a way to do this will be by deleting the `^`.
A better way to do this is by using the `<field>` leaving it like:
```
<field name="a0">netcat</field>
```

I hope this could help, If you have any further questions, please do not hesitate to ask us!
Best regards!

**Comment by oliveiralive** [comment]
Hi @jcruzlp 
Great, working now

I finded 2 problems in my filter:
first, in the rule below, would need put the parent rule
`<if_sid>80792</if_sid>`


and after i use the `<field name="audit.file.name">/bin/netcat|/bin/nc|/usr/bin/ncat|/usr/bin/nmap</field>`

Work gracyfull
Thanks
