### ISSUE TITLE
Stop the Master-Worker tasks when an exception occurs in one or both parts

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#10735]
We have detected an inappropriate behavior in the Master-Workers communication. Right now, when a synchronization task is created, it is assigned an ID which is used to identify it. Right now, a worker node creates a synchronization task, it is sent to the master and saves the task ID.

Once this is done the worker node will wait to receive a file from the master, however, this wait has a maximum time defined in the `cluster.json` file, by default, 120 seconds.

This is the problem, if for any reason more than 120 seconds are consumed, the object in charge of receiving the file is deleted. Once the master node sends the file and notifies the worker, it does not recognize the ID because the object has already been deleted.

In this issue, we will explore the possibilities we have to stop this task from the worker. Ideally, the worker node should tell the master node that the task has to be canceled because it is no longer valid for it.

We must apply changes both on the master side and on the worker side. On the master side, we have to stop the execution of the `sync_integrity` function (`master.py`) which in turn calls `send_request` (`worker.py`) and it starts splitting the file and sends each of the parts.

https://github.com/wazuh/wazuh/blob/1104e8d018fda15de53ade001addf098191afbc0/framework/wazuh/core/cluster/master.py#L618-L743
https://github.com/wazuh/wazuh/blob/1104e8d018fda15de53ade001addf098191afbc0/framework/wazuh/core/cluster/common.py#L440-L476

More information here: https://github.com/wazuh/wazuh/issues/10595#issuecomment-949367585

**Comment by Selutario** [comment]
## Issue update

Until now, when a file was sent from one cluster node to another one, it was divided into chunks inside the `send_file()` function, in case the file was too big:
https://github.com/wazuh/wazuh/blob/d9bdabd771d70933276754fbab02c6939292065e/framework/wazuh/core/cluster/common.py#L457-L460

However, after this PR https://github.com/wazuh/wazuh/pull/8504, said dividing tasks is no longer performed at the `send_file()` function:
https://github.com/wazuh/wazuh/blob/c8a8a003dbafb801d7788ca56e55949173872281/framework/wazuh/core/cluster/common.py#L501-L504

but inside `send_request()`, which is much more generic and is used for absolutely every communication inside the cluster:
https://github.com/wazuh/wazuh/blob/c8a8a003dbafb801d7788ca56e55949173872281/framework/wazuh/core/cluster/common.py#L458-L461

This makes the task of canceling file delivery a bit more difficult to manage. I'm testing with adding an optional parameter to `send_request()` so an asyncio event can be used as a callback. Only `send_file` would call `send_request` with such a callback. The master must trigger the callback when it receives an error command from the worker. 

The problem is that chunks are not sent using an async function, so I will need to test if the master is capable of handling commands from the worker (a timeout command) while pushing those chunks:
https://github.com/wazuh/wazuh/blob/c8a8a003dbafb801d7788ca56e55949173872281/framework/wazuh/core/cluster/common.py#L460-L461

**Comment by Selutario** [comment]
## Issue update

The biggest obstacle in this issue was related to the fact that, in order to stop a task in progress (for example, sending chunks of a zip file), we had to interfere in the `send_request` method, which is not so easy since it is the last step before sending anything between two cluster nodes.

However, in https://github.com/wazuh/wazuh/issues/11266, the `send_file` and `send_string` methods were modified, giving them back control over division and sending of the data in chunks:
https://github.com/wazuh/wazuh/blob/a9d294619dcfb3e1cb04b29118bf00b537179103/framework/wazuh/core/cluster/common.py#L501-L504

This will make it easier to break the loop in case the sending node (usually the master) received an error message from a worker. The way to interrupt the loop from another point in the cluster is not yet defined, but any variable as a flag could be a good approximation, especially once it is decided how to deal with multiple simultaneous files being sent if some need to be stopped at the same time.

**Comment by Selutario** [comment]
## Issue update

I have been trying different approaches to interrupt the task. Finally I opted for one of these two: timeout in the sender node or an interrupt flag.

### Timeout in send_file function
I tried to use the timeout class that was already developed and used in other functions like the one for sending chunks from agent-info to wazuh-db or the one for processing extra-valid files:
```Python
# Send each chunk so it is updated in the destination.
try:
    with Timeout(n):
        file_hash = hashlib.sha256()
        with open(filename, 'rb') as f:
            for chunk in iter(lambda: f.read(self.request_chunk - len(relative_path) - 1), b''):
                self.logger.debug("Sending file")
                await self.send_request(command=b'file_upd', data=relative_path + b' ' + chunk)
                file_hash.update(chunk)
except Exception as e:
    self.logger.debug(f"Timeout reached while sending file: {e}")
```

The timeout would be the same in the sending node as in the receiver, so the task would theoretically stop at approximately the same time.

However, when said timeout is raised, sometimes an uncontrolled exception occurs and the clusterd process is halted, even though everything is enclosed in a try/except clause:
```
2021/12/31 10:43:03 DEBUG: [Worker worker1] [Main] Sending file
2021/12/31 10:43:03 DEBUG: [Worker worker1] [Main] Sending file
2021/12/31 10:43:03 DEBUG: [Worker worker1] [Main] Sending file
2021/12/31 10:43:03 DEBUG: [Worker worker1] [Main] Sending file
2021/12/31 10:43:03 DEBUG: [Worker worker1] [Integrity sync] Finished sending files to worker.
2021/12/31 10:43:03 INFO: [Worker worker1] [Integrity sync] Finished in 3.168s.
2021/12/31 10:43:03 ERROR: [Cluster] [Main] Unhandled exception: 
root@wazuh-master:/# 
root@wazuh-master:/# 
```

Other times, the process does not die:
```
2021/12/31 10:44:15 DEBUG: [Worker worker1] [Main] Sending file
2021/12/31 10:44:16 DEBUG: [Worker worker1] [Main] Sending file
2021/12/31 10:44:16 DEBUG: [Worker worker1] [Main] Sending file
2021/12/31 10:44:16 DEBUG: [Worker worker1] [Main] Sending file
2021/12/31 10:44:16 DEBUG: [Worker worker1] [Main] Timeout reached while sending file: Error 3018 - Error sending request
2021/12/31 10:44:16 DEBUG: [Worker worker1] [Main] Command received: b'syn_i_w_m_r'
2021/12/31 10:44:16 ERROR: [Worker worker1] [Main] Error in synchronization process: Error 3039 - Timeout while waiting to receive a file: Integrity sync at worker1
2021/12/31 10:44:16 DEBUG: [Worker worker1] [Integrity sync] Zip with files to be synced sent to worker.
2021/12/31 10:44:16 ERROR: [Worker worker1] [Main] Error sending files information: Error 3027 - Unknown received task name: 3e70f73d-e8f7-4ff2-90a0-f4e2b55aa540
```

I have discarded the use of the timeout class. In any case, I made sure that this problem does not occur in the other places it is used. It seems that the problem could be related to `send_request`.

### Interrumption flag

The other alternative and one that seems to be working fine in my tests is to use an empty set in the [Handler](https://github.com/wazuh/wazuh/blob/218787c1487ddf7a3f43d8c4727bd643c456ca8e/framework/wazuh/core/cluster/common.py#L242-L295) class. Then, the loop inside `send_file()` checks if the `taskID` that it received as a paremeter is inside the set created before. 

If a worker notifies the master that there has been a timeout or an error, the master adds the taskID to the set and the `send_file` loop will stop.

**Comment by Selutario** [comment]
## Issue update

After discussing it with the team, we have decided that the approach of using an interrupt flag is the best in this case. However, there some things to keep in mind:

### 1. Remove remaining files

Once the task to send a zip has been interrupted on the master side, it should not send the `syn_m_c_e` command to the worker:
```PYTHON
                # Send zip file to the worker into chunks.
                await self.send_file(compressed_data, task_id)
                logger.debug("Zip with files to be synced sent to worker.")

                if task_id not in self.interrupted_tasks:
                    # Notify what is the zip path for the current taskID.
                    result = await self.send_request(command=b'syn_m_c_e',
                                                     data=task_id + b' ' + os.path.relpath(
                                                         compressed_data, common.wazuh_path).encode())
                else:
                    # TODO: skip remaining actions if the task was cancelled during 'send_file()'.
                    pass
```

 since the `task_id` will not exist and if `syn_m_c_e` is sent, a confusing second error would be shown in the master log (`Unknown received task name`):
```
2022/01/17 13:19:11 INFO: [Worker worker1] [Main] Sending file
2022/01/17 13:19:12 INFO: [Worker worker1] [Main] Sending file
2022/01/17 13:19:12 ERROR: [Worker worker1] [Main] Error in synchronization process: Error 3039 - Timeout while waiting to receive a file: Integrity sync task.
2022/01/17 13:19:12 ERROR: [Worker worker1] [Main] Error sending files information: Error 3027 - Unknown received task name: c0e60409-8061-4eb6-bd6b-a0ce90efcc0e
```

However, the function that is responsible for deleting a file when the `task_id` does not exist is the one run when `syn_m_c_e` is received, so a new method should be created to delete the file without raising/printing the error log `Unknown received task name` after the timeout. I am working on this right now.

The alternative is to allow both errors to be displayed, which would avoid making the logic of this procedure more complex.

### 2. Review other places where this could happen

Theoretically, the same error could occur anywhere where a file is expected. For example, on the master node while waiting for zip with extra-valid files:
https://github.com/wazuh/wazuh/blob/0e2da8a7ed14c5f92889d54ea42a845a4b456f6b/framework/wazuh/core/cluster/master.py#L792-L794

We should make the procedure very general and can be reused in all these places.

**Comment by Selutario** [comment]
## Issue update

When a string is being sent between different nodes, if there is an error, it is notified within the [send_string()](https://github.com/wazuh/wazuh/blob/0e2da8a7ed14c5f92889d54ea42a845a4b456f6b/framework/wazuh/core/cluster/common.py#L511-L536) function itself, as shown below:
https://github.com/wazuh/wazuh/blob/0e2da8a7ed14c5f92889d54ea42a845a4b456f6b/framework/wazuh/core/cluster/common.py#L524-L530

I decided to handle interrupts in [send_file](https://github.com/wazuh/wazuh/blob/0e2da8a7ed14c5f92889d54ea42a845a4b456f6b/framework/wazuh/core/cluster/common.py#L478-L509) the same way:
```PYTHON
        with open(filename, 'rb') as f:
            for chunk in iter(lambda: f.read(self.request_chunk - len(relative_path) - 1), b''):
                await self.send_request(command=b'file_upd', data=relative_path + b' ' + chunk)
                file_hash.update(chunk)

                # If task was interrupted, close file descriptor, delete file and stop sending chunks.
                if task_id in self.interrupted_tasks:
                    await self.send_request(command=b'err_file', data=relative_path)
                    self.interrupted_tasks.discard(task_id)
                    return False
```

If the task is interrupted while sending a file, the command `err_file` is sent to the receiving node, so it is notified about the filename that should be deleted. In addition, the file descriptor is closed and the object instance is deleted. Some new protocols/commands were added in [Handler](https://github.com/wazuh/wazuh/blob/0e2da8a7ed14c5f92889d54ea42a845a4b456f6b/framework/wazuh/core/cluster/common.py#L242) class: 
- `cancel_task`
- `err_file`

Now, it is enough to catch `timeoutErrors` in those places where a file is expected and notify the sending node of it:
```PYTHON
        try:
            await asyncio.wait_for(received_file.wait(),
                                   timeout=self.cluster_items['intervals']['communication']['timeout_receiving_file'])
        except Exception:
            await self.send_request(
                command=b'cancel_task',
                data=task_id.encode() + b' ' + json.dumps(timeout_exc := exception.WazuhClusterError(3039),
                                                          cls=c_common.WazuhJSONEncoder).encode())
            raise timeout_exc
```
