### ISSUE TITLE
Add support for AlmaLinux OS in Vulnerability Detector

### ISSUE THREAD

**Issue by JeanGau-ops** [wazuh/wazuh#10774]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.4-1 | Wazuh Vulnerability module | Manager | Packages | AlmaLinux 8 |

I first posted this on slack which sent me here.
I'm having an issue with the vulnerability detector module on redhat environment.
It's reporting 50 vulnerabilities on my Almalinux 8 up to date but every CVE is, in fact, not affected.
For example CVE-2018-16865 where Red Hat says that systemd on Red Hat Enterprise Linux 8 is "Not affected" : https://access.redhat.com/security/cve/cve-2018-16865

The problem resides because it matches with the generic CPE of the NVD and that causes the false positive:

2021/11/08 13:40:24 wazuh-modulesd:vulnerability-detector[62239] wm_vuln_detector_nvd.c:2514 at wm_vuldet_check_generic_package(): DEBUG: (5458): Package 'systemd' inserted into the vulnerability 'CVE-2018-16865'. Version (239-45.el8_4.3) 'less than or equal' '240' (feed 'NVD').
2021/11/08 13:40:26 wazuh-modulesd:vulnerability-detector[62239] wm_vuln_detector.c:1532 at wm_vuldet_send_cve_report(): DEBUG: (5468): The 'systemd' package (239-45.el8_4.3) from agent '000' is vulnerable to 'CVE-2018-16865'. Condition: 'Package less or equal than 240'

Apparently we can't disable NVD because it is necessary for the vulnerability detector to work properly.

Is there a way to use the module on a majorly RedHat environment or should it be updated?
Thank you in advance.
Best regards.

Tasks
- [x] https://github.com/wazuh/wazuh/issues/15979

**Comment by chemamartinez** [comment]
Hi @formationdockerjean,

This issue is mainly caused because AlmaLinux is not officially supported by the Wazuh vulnerability detector. [Here](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/compatibility_matrix.html) you can see the list of operating systems natively supported.

Supported OS means that Vulnerability Detector indexes vulnerability feeds directly from these vendors, with specific vulnerability information for packages distributed by them (Canonical, Redhat, Debian, Microsoft...). Packages maintained by others such as the AlmaLinux team cannot be matched with those feeds since we are not able to ensure they belong to the same lineage (even matching CentOS packages with the RHEL feed is causing inconsistencies).

This is the case of AlmaLinux, if you see the specifications for the `systemd` package we can see:
```
# rpm -qi systemd
Name        : systemd
Version     : 239
Release     : 45.el8_4.3
Architecture: x86_64
Install Date: Thu 14 Oct 2021 07:36:57 PM UTC
Group       : Unspecified
Size        : 11189195
License     : LGPLv2+ and MIT and GPLv2+
Signature   : RSA/SHA256, Tue 10 Aug 2021 10:18:19 PM UTC, Key ID 51d6647ec21ad6ea
Source RPM  : systemd-239-45.el8_4.3.src.rpm
Build Date  : Tue 10 Aug 2021 09:20:59 PM UTC
Build Host  : buildfarm02
Relocations : (not relocatable)
Packager    : AlmaLinux Packaging Team <packager@almalinux.org>
Vendor      : AlmaLinux
URL         : http://www.freedesktop.org/wiki/Software/systemd
Summary     : System and Service Manager
```

So, regarding the packager and the vendor, we cannot match packages provided by the AlmaLinux team against a vulnerability database for RHEL packages. That would lead to unexpected results and surely a lot of false positives.

So, the only vulnerability database compatible with AlmaLinux right now is the NVD which refers to generic packages (not maintained by any OS vendor but the software owner). That is why the report you are getting is the result of evaluating the AlmaLinux package inventory against the NVD.

We can evaluate if it is possible to find a feed for AlmaLinux that allows us to improve the vulnerability detection in these agents. Currently, the team is working on improving the expectrum of supported OS:
- [Arch Linux support](https://github.com/wazuh/wazuh/pull/8178) (added in v4.2.0)
- [Amazon Linux support](https://github.com/wazuh/wazuh/pull/8830) (added for v4.3.0)
- [SUSE support](https://github.com/wazuh/wazuh/pull/9962)(in progress to be added)

These platforms were previously scanned against the Redhat feed leading to the same problems we are discussing here.

Please, let me adapt the issue title to a more precise feature request regarding the current Vulnerability Detector design.

Finally, thank you for your feedback! Don't hesitate to ask us any other doubts.

Best regards.

**Comment by JeanGau-ops** [comment]
Hi,

Thank you for your answer.
For what it's worth, AlmaLinux does have a json feed at : https://errata.almalinux.org/errata.json
I hope you can do something with it as our number of AlmaLinux is growing. :)

Best regards.

**Comment by EHRETic** [comment]
Hi there,

I can only upvote that request, AlmaLinux is the distro I chose to move from CentOS away... ;-)

**Comment by shoothub** [comment]
Hello there,
AlmaLinux started building OVAL database for AlmaLinux 8 and 9 version. 
https://almalinux.org/blog/introducing-albs-the-almalinux-build-system/
https://wiki.almalinux.org/documentation/oval-streams.html
https://security.almalinux.org/oval/

Please add support for AlmaLinux in Wazuh vulnerability detector, I also think that AlmaLinux is the best replacement distro for CentOS users with big community.

**Comment by djw-bsn** [comment]
Hi 
We're also really interested in this. We were looking to implement Wazuh but we recently mostly switched to Alma and without support in the vuln detector we've had to pause the project. 

Can we do anything to help? Could we use the PRs for Arch/Amazon/Suse as a template to try to implement this? Or is it more complex than that? 

Or now Suse support is implemented could this be the next on the list? ;)

Great project and keep up the good work!

**Comment by dransome** [comment]
@djw-bsn we are in exactly the same position, and also interested how we could potentially help. @Dwordcito pointed towards #14153

**Comment by juliocbc** [comment]
+1

**Comment by bstrin** [comment]
+1

**Comment by nguyenquoctan** [comment]
+1

**Comment by 499K** [comment]
Any update pls?

**Comment by gudmmk** [comment]
+1

**Comment by lexzz** [comment]
+1 this would be very useful

**Comment by sej7278** [comment]
:+1:
