### ISSUE TITLE
Rule error? or What can I do to trigger the rule[5904]?

### ISSUE THREAD

**Issue by WallaceCS** [wazuh/wazuh#10787]
|Wazuh version| Component | Action type |
|---| --- | --- |
|4.1.5 | Rules/Decoders | New/Error/Improve |

## Description

I have attempt to execute command `usermod -d /home/xxx abc`  to change the home directory of the user "abc" on Ubuntu18.04 and CentOS6.5.  
But I just get system log as these:  

Nov  9 18:08:07 xxx usermod[341]: change user 'abc' home from '/home/abc' to '/home/xxx'  

The rule 5904 is not triggered.
```
<rule id="5904" level="8">
<match>^changed user</match>
<description>Information from the user was changed.</description>
<mitre>
```

I am a little skeptical that the rule 5904 is correct.
Or What can I do to trigger the rule[5904]?

### Current results

`<match>^changed user</match>`

### Expected results

`<match>^change user</match>`

**Comment by jnasselle** [comment]
Hi @WallaceCS ,

Rules `5901`,`5902`,`5903` and `5904` are designed to match common patterns related to user handling of any program (see that they are not related to any specific program_name). In your log sample, the `change user` don't match expected `changed user`, so that's why the rule is not triggered.

This could be handled by a custom decoder and rule that match against `usermod` program name, for example setting the next decoders and rules in `/var/ossec/etc/decoders/local_decoders.xml` and `/var/ossec/etc/rules/local_rules.xml` respectively
```xml
<decoder name="usermod">
    <program_name>usermod</program_name>
</decoder>

<decoder name="usermod-changed-homedir">
    <parent>arbor</parent>
    <regex>change user '(\.+)' home from '(\.+)' to '(\.+)'</regex>
    <order>user, srchome, dsthome</order>
</decoder>
```

```xml
<group name="usermod,">

  <rule id="100001" level="0">
    <program_name>usermod</program_name>
    <description>Usermod grouping rule.</description>
  </rule>

  <rule id="100002" level="3">
    <if_sid>100001</if_sid>
    <regex>change user '\.+' home from '\.+' to '\.+'</regex>
    <description>User '$(dstuser)' home was changed</description>
  </rule>

</group>
```


Testing them with `wazuh-logtest`
```
/var/ossec/bin/wazuh-logtest       
Starting wazuh-logtest v4.1.5
Type one log per line

Nov  9 18:08:07 xxx usermod[341]: change user 'abc' home from '/home/abc' to '/home/xxx'


**Phase 1: Completed pre-decoding.
        full event: 'Nov  9 18:08:07 xxx usermod[341]: change user 'abc' home from '/home/abc' to '/home/xxx''
        timestamp: 'Nov  9 18:08:07'
        hostname: 'xxx'
        program_name: 'usermod'

**Phase 2: Completed decoding.
        name: 'usermod'
        dsthome: '/home/xxx'
        dstuser: 'abc'
        srchome: '/home/abc'

**Phase 3: Completed filtering (rules).
        id: '100002'
        level: '3'
        description: 'User 'abc' home was changed'
        groups: '['usermod']'
        firedtimes: '1'
        mail: 'False'
**Alert to be generated.
```

Hope this helps!
Nico

**Comment by WallaceCS** [comment]
Thank you very much for your detailed reply.
