### ISSUE TITLE
Fix cmocka unit tests after FIM DB rework

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#10806]
After the development of #9103, we moved the DB code to C++ alongside the unit tests.

The purpose of this issue is to look at all the problems in the C unit tests that have been broken with this change.
## Steps to complete the issue.
Using the current design, we will need to:
- [x] Delete all the deprecated UT.
- [x] Remove all the deprecated wrappers. 
- [x] Add/adapt the wrappers for the C interface of the new FIM DB library. -> in progress
- [x] Add/adapt the syscheck UT to use the interface wrappers.
- [x] #12242

**Comment by jotacarma90** [comment]
I have left the `10806-fix-cmocka-ut-fimdb` branch of work
I have managed to organize everything that is left over and I have eliminated all those functions that created conflicts when compiling the units with the new FIMDB module.
I have added to the CMakeList files all the necessary wrappers so that the compiler can do its job, since the new functions written in c++ must be wrapped in any file in which they are going to be present in c.
I have added the implementation of some new wrappers and their expect_function. And I have modified some tests so that they can pass correctly.
It remains to review some tests that are failing as a result of the changes due to the new FIMDB.

**Comment by antoniomanuelfr** [comment]
I realized that GCC 11 is raising the following error when compiling the UTs:
```
rConsolidate compiler generated dependencies of target test_syscheck
[ 70%] Linking C executable test_syscheck
/usr/bin/ld: CMakeFiles/test_syscheck.dir/home/antoniomanuelfr/vagrant/share/wazuh/src/syscheckd/src/syscheck.c.o:/home/antoniomanuelfr/vagrant/share/wazuh/src/syscheckd/src/syscheck.c:21: multiple definition of `syscheck'; CMakeFiles/test_syscheck.dir/test_syscheck.c.o:/home/antoniomanuelfr/vagrant/share/wazuh/src/unit_tests/syscheckd/test_syscheck.c:25: first defined here
/usr/bin/ld: CMakeFiles/test_syscheck.dir/home/antoniomanuelfr/vagrant/share/wazuh/src/syscheckd/src/syscheck.c.o:(.bss+0xc21): multiple definition of `__odr_asan.syscheck'; CMakeFiles/test_syscheck.dir/test_syscheck.c.o:(.bss+0xc00): first defined here
scollect2: error: ld returned 1 exit status
make[2]: *** [syscheckd/CMakeFiles/test_syscheck.dir/build.make:117: syscheckd/test_syscheck] Error 1
make[1]: *** [CMakeFiles/Makefile2:4006: syscheckd/CMakeFiles/test_syscheck.dir/all] Error 2
make: *** [Makefile:101: all] Error 2

antoniomanuelfr@laptop [12:40:03] [~/vagrant/share/wazuh/src/unit_tests/build] [10806-fix-cmocka-unit-test-for-linux *]
-> % gcc --version
gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


antoniomanuelfr@laptop [12:40:04] [~/vagrant/share/wazuh/src/unit_tests/build] [10806-fix-cmocka-unit-test-for-linux *]
-> % 
```

The following patch fixes the problem:
[patch.txt](https://github.com/wazuh/wazuh/files/8068704/patch.txt)
