### ISSUE TITLE
Adapt FIM scan function to dbsync

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#10847]
|EPIC|Component|
|---|---|
| https://github.com/wazuh/wazuh/issues/9103 | FIM |

### Description

Hi team,
This issue is to rewrite the FIM scan function to use the dbsync library, written in c++, but with a c interface.
This issue is part of the epic of wrappers, Implementation of FIM DB wrappers.

For the implementation of the new scan, besides using the **DBSync** interface, we want to use a transaction tool implemented together with DBSync, called **DBSyncTxn**. This is a class that can deal with the necessary database operations to be able to execute all the steps of the scan. So that we can launch the events of added or modified of each one of the FimItem scanned that require it. And when finishing, we will be able to execute with a single function the deletion of all the entries that have not been scanned (and that therefore correspond to a deleted event).

To perform the scan in basic lines, we need to create a transaction, with **dbsync_create_txn()** (c function of the dbsync interface), create the scan loop logic, and execute **syncTxnRow()** in every fim_entry converted to c++ FimItem. At the end, doing **get_deleted_elements()** we ensure that unscanned items are removed, and their corresponding events are triggered.

**Comment by antoniomanuelfr** [comment]
In order to follow the current structure of the FIM db library, we will need to add a new set of functions in the `FIMDBHelper` namespace to return the following:
1. Return the transaction object.
2. Function to perform the row operations.
3. Function to perform the deleted rows operations.

With this new set of functions, we will have the needed functions in the helper. We will also need the functions in the interface to be able to call this code from C.

After that, we will need to modify the current scan to call this new set of functions.
