### ISSUE TITLE
Review AWS VPCFlow implementation to remove unnecesary AWS API calls

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#10846]
|Component|
|---|
| AWS module |

## Description

The performance and efficiency of the current `AWS VPCFlow` implementation can be improved. It currently iterates several times through the AWS directories available in the bucket. For each one of the dates to be processed the flow is as follows:

1. Lists every existing flow log in the AWS environment for the affected region.
2. For each one of these flow logs the module request a list of every folder available in the bucket for the given date.
3. For each one of these directories, it checks if its name contains the name of the current flow log.
 it traverses through all the available folders in the bucket.
4. Repeat the procedure for the next flow log in the list, requesting again the same directory list and iterating over them.

This can and should be improved.

## Checks
- [x] Investigate if it is necessary to iterate over the existing flow logs or we should just stick to the contents of the bucket itself.
- [ ] Design a solution to avoid unnecessary calls to the AWS API.
- [ ] Implement the solution
- [ ] Test the module (for both managers and agents)
- [ ] Update the documentation explaining how the implementation is intended to work.
- [ ] Update the changelog (`CHANGELOG.md`)

**Comment by noise-kngdm** [comment]
## Issue update
We've been researching why the module was designed to work this way, and we have found no reason that could make it mandatory to separate the API requests depending on the Flow Log ID instead of requesting all of them at once.   

### Suggested design
We think that, if it's necessary to check that every fetched log pertains to an existing Flow Log ID, it would be a better solution to list all log keys starting from the last key processed and then filter them using the data provided by a call to `describe_flow_logs`. Doing so, the number of calls to the AWS API would decrease greatly as stated in the following table:  

<table>
    <thead>
        <tr>
            <th>Design</th>
            <th colspan=3>Number of calls</th>
        </tr>
        <tr>
            <th></th>
            <th>describe_flow_logs</th>
            <th>list_objects_v2</th>
            <th>get_object</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Actual design</td>
            <td>1</td>
            <td>1 per flow log and day</td>
            <td>1 per log file</td>
        </tr>
        <tr>
            <td>Suggested design</td>
            <td>1</td>
            <td>1</td>
            <td>1 per log file</td>
        </tr>
    </tbody>
</table>  

#### Implementation considerations 
To implement this design, we would need to refactor the `build_s3_filter_args` method overloaded by the `AWSVPCFlow` class to stop considering the Flow Log ID in the requests. Doing so would allow us to request all logs with the same API call. Then, it would be necessary to modify the `iter_files_in_buckets` method to check for a valid Flow Log ID in the filename in order to process it. I suggest removing the duplicated methods and adding the necessary functionality to the parent's method to increase the code's maintainability.

**Comment by noise-kngdm** [comment]
## Issue update
We think that it could be possible -and even desirable- to stop considering that the collected log correspond to an active Flow Log, and start processing all logs depending on the publish date instead. That's because there are some cases that, with the current implementation, could incur in lost alerts due to race conditions, for example:
1. A flow log has been created with an aggregation interval of 10 minutes -the default value-.
2. After the last log record was generated, the Flow Log is deleted. As stated in the [AWS Flow Logs documentation](https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html#flow-logs-aggregration-interval), the logs are delivered in a *best effort* basis, and typically the log records will have a 10 minutes delay until they are delivered to the S3 bucket.
3. Once the module collects all the log records, since that log corresponds to a deleted Flow Log, it will be skipped.

Before implementing this new behavior we will ensure that it's no necessary at all that the Flow Log is active before processing it.

**Comment by noise-kngdm** [comment]
## Issue update
After talking with the rest of the time about this issue, we concluded that the module was designed this way to encapsulate the processing of every Flow Log. We don't think that this would be necessary at all, and changing the design would need either the implementation of a migration logic or a full redesign. We will leave this issue on hold until we decide which would be the best solution.

**Comment by davidjiglesias** [comment]
We will not approach these changes as they require a full rework
