### ISSUE TITLE
Review and improve the usage of the skip_on_error option in the AWS module

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#10852]
|Component|
|---|
| AWS module |

## Description

The `skip_on_error` parameter seems to be used much less than it should be and even in some functions it is not being taken into consideration at all, making the decision on whether to continue with an execution or not in case of an error ourselves instead of allowing the user to choose.

## Checks
- [x] Review the module and look for every place when an event or log is being skipped. Add the skip_on_error logic if it is advisable to do so.
- [x] Review all those parts where we are handling exceptions. Determine whether the skip_on_error parameter is being taken into account and whether it should be.
- [x] Test the module.
- [x] Review the documentation to ensure the parameter explanation is valid. Issue wazuh/wazuh-documentation#4809 was opened to fix the description of the parameter.
- [x] Update the changelog (`CHANGELOG.md`)

**Comment by noise-kngdm** [comment]
## Issue update
We have finished reviewing the AWS and applying the required changes in f771deb6c802de23d707f37cb9bc7f4de913f9b3.
Now we are working on implementing the unit tests necessary to prove the changes. We will update the branch soon with those changes.

**Comment by noise-kngdm** [comment]
## Issue update
We have finished adding unit tests for the parts of the module that were modified for this issue. All the tests are passing, as can be seen in the following output:

```
(wazuh-unit) ➜  aws git:(feature/10852-review-aws-skip-on-error-usage) ✗ pytest
==================================== test session starts ====================================
platform linux -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-0.13.1
rootdir: /home/gonzz/git/wazuh/wodles/aws
plugins: asyncio-0.15.1
collected 21 items                                                                          

tests/test_aws.py .....................                                               [100%]

==================================== 21 passed in 0.12s =====================================
```

We will test the whole integration next and will submit a PR once we have checked that everything is working as expected.

**Comment by noise-kngdm** [comment]
## Issue update
We realized that the `skip_on_error` parameter was practically set to `True` even though it could be specified as a parameter. That's because of the following code snippet:

https://github.com/wazuh/wazuh/blob/9d8db160e0b4973a1abbfae940760f2617067f4c/wodles/aws/aws_s3.py#L3368-L3369

The `action='store_true'` parameter sets `False` as a default value for the destination variable. That was overrided by the `default=True` parameter, so executing the module using that option or not wouldn't have any consequences in the execution flow.

We have fixed it and will submit a PR with all the changes soon. As for the documentation, we will open an issue soon to stop [mentioning only CloudTrail](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#skip-on-error).

### Tests performed
We have tested all the parts of the code that could be affected by the changes introduced in this issue.  

#### Unit tests
```
(wazuh-unit) ➜  aws git:(feature/10852-review-aws-skip-on-error-usage) ✗ pytest
==================================== test session starts ====================================
platform linux -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-0.13.1
rootdir: /home/gonzz/git/wazuh/wodles/aws
plugins: asyncio-0.15.1
collected 21 items                                                                          

tests/test_aws.py .....................                                               [100%]

==================================== 21 passed in 0.10s =====================================
```

#### Test decompress file
To test these changes, we uploaded a file compressed using the snappy algorithm to S3 and tried to fetch and process it using the module. Depending on if the `skip_on_error` parameter was used or not, it should continue the execution or abort it.

##### With `skip_on_error` set to `True`

The command used to test this is:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-cloudtrail -p dev -s 2022-Jan-01 -d2 -t cloudtrail -l test_snappy --skip_on_error
```

<details><summary>Command output</summary>

	root@5f2d3d13fc1e:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-cloudtrail -p dev -s 2022-Jan-01 -d2 -t cloudtrail -l test_snappy --skip_on_error
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Working on XXXXXXXXXXXX - us-west-1
	DEBUG: +++ Marker: test_snappy/AWSLogs/XXXXXXXXXXXX/CloudTrail/us-west-1/2022/01/01
	DEBUG: ++ Found new log: test_snappy/AWSLogs/XXXXXXXXXXXX/CloudTrail/us-west-1/2022/01/24/XXXXXXXXXXXX_vpcflowlogs_us-east-1_fl-03fbf155728a27ded_20211223T0000Z_ce6176d8.log.snappy
	ERROR: couldn't decompress the test_snappy/AWSLogs/XXXXXXXXXXXX/CloudTrail/us-west-1/2022/01/24/XXXXXXXXXXXX_vpcflowlogs_us-east-1_fl-03fbf155728a27ded_20211223T0000Z_ce6176d8.log.snappy file, snappy compression is not supported.
	DEBUG: ++ Unkown error reading/parsing file test_snappy/AWSLogs/XXXXXXXXXXXX/CloudTrail/us-west-1/2022/01/24/XXXXXXXXXXXX_vpcflowlogs_us-east-1_fl-03fbf155728a27ded_20211223T0000Z_ce6176d8.log.snappy: __enter__; skipping...
	DEBUG: ++ Found new log: test_snappy/AWSLogs/XXXXXXXXXXXX/CloudTrail/us-west-1/2022/01/25/XXXXXXXXXXXX_CloudTrail_us-west-1_20220125T0000Z_HASDOtJxgfdNInHa.json.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance

</details>

##### Without `skip_on_error`

The command used to test this is:

```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-cloudtrail -p dev -s 2022-Jan-01 -d2 -t cloudtrail -l test_snappy
```

<details><summary>Command output</summary>

	root@5f2d3d13fc1e:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-cloudtrail -p dev -s 2022-Jan-01 -d2 -t cloudtrail -l test_snappy   
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Working on XXXXXXXXXXXX - us-west-1
	DEBUG: +++ Marker: test_snappy/AWSLogs/XXXXXXXXXXXX/CloudTrail/us-west-1/2022/01/01
	DEBUG: ++ Found new log: test_snappy/AWSLogs/XXXXXXXXXXXX/CloudTrail/us-west-1/2022/01/24/XXXXXXXXXXXX_vpcflowlogs_us-east-1_fl-03fbf155728a27ded_20211223T0000Z_ce6176d8.log.snappy
	ERROR: couldn't decompress the test_snappy/AWSLogs/XXXXXXXXXXXX/CloudTrail/us-west-1/2022/01/24/XXXXXXXXXXXX_vpcflowlogs_us-east-1_fl-03fbf155728a27ded_20211223T0000Z_ce6176d8.log.snappy file, snappy compression is not supported.
</details>


##### Conclusions
The module is working as expected.

#### Test load information from file
To test the modifications made to the implementation of the `load_information_from_file` that the `AWSWAFBucket` has, we uploaded to S3 a file without the expected fields in a folder with the prefix `test_invalid_structure`.

##### With `skip_on_error`

The command used to test this is:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-waf -p dev -s 2022-Jan-01 -d2 -t waf -l test_invalid_structure --skip_on_error
```

<details><summary>Command output</summary>

	root@5f2d3d13fc1e:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-waf -p dev -s 2022-Jan-01 -d2 -t waf -l test_invalid_structure --skip_on_error
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Marker: test_invalid_structure/2022/01/01
	DEBUG: ++ Found new log: test_invalid_structure/2022/02/09/aws-waf-logs-elb-co-2-2022-02-09-10-00-01-9dxc8jkl-6ddd-4419-96ac-c8d2716e52jk
	ERROR: the test_invalid_structure/2022/02/09/aws-waf-logs-elb-co-2-2022-02-09-10-00-01-9dxc8jkl-6ddd-4419-96ac-c8d2716e52jk file doesn't have the expected structure.
	DEBUG: ++ Found new log: test_invalid_structure/2022/02/09/aws-waf-logs-elb-co-2-2022-02-09-14-00-01-b66eb75e-6ddd-4419-96ac-c8d2716e5434
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance

</details>

##### Without `skip_on_error`

The command used to test this is:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-waf -p dev -s 2022-Jan-01 -d2 -t waf -l test_invalid_structure
```

<details><summary>Command output</summary>

	root@5f2d3d13fc1e:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-waf -p dev -s 2022-Jan-01 -d2 -t waf -l test_invalid_structure
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Marker: test_invalid_structure/2022/01/01
	DEBUG: ++ Found new log: test_invalid_structure/2022/02/09/aws-waf-logs-elb-co-2-2022-02-09-10-00-01-9dxc8jkl-6ddd-4419-96ac-c8d2716e52jk

</details>


##### Conclusions
The module is working as expected.

**Comment by noise-kngdm** [comment]
## Issue update
We opened wazuh/wazuh-documentation#4809 to fix the documentation of the `skip_on_error` parameter.
