### ISSUE TITLE
Migrate agent-group files to wazuh-db - Core analysis

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#10857]
|Related issue|
|---|
|#10771|

### Description

This is a tracking issue to reflect the analysis required before implementing the migration of the agent group files to Wazuh-DB.
Some details of the current behavior must be defined to create a design proposal.

**Comment by pereyra-m** [comment]
## Proof of concept

After some analysis and testing, this comment summarizes the conclusions of the first approach to the migration of the **agent-groups** files to Wazuh-DB

### Introduction

When an agent is added to a group in the manager, a file with its ID as name is created under the `queue/agent-groups` folder. It contains a comma separated string with all the groups whose the agent belongs. The same string is reflected in the column `group` of the **global.db** (`agent` table) and its hash is used to determine the multigroup of the agent.

We can also find two more tables related to the agent's groups:
- **group**: it is a list of all the existing groups with its corresponding ID
- **belongs**: every row has an agent ID and a group ID, representing the current assignations

Currently, the python script `agent_groups.py` is in charge of the groups manual operations, and the API can perform some actions too. The groups can be assigned during the registration or by **remoted** if the agent has a previous `merged.mg` file.

The files are constantly read by **modulesd** to keep the databases synced.

### Changes required

#### Synchronization mechanism

If the `agent-groups` files are deprecated, all the related methods in charge of reading these files can be removed. Also, some other methods that still need to read existing files have to be modified to stop reading **GROUPS_DIR**. Most of them are located in **wazuh_modules/wm_database.c**. These methods should be modified/deprecated:

- wm_clean_dangling_groups()
- wm_sync_file(GROUPS_DIR)
- wm_inotify_setup()
- wm_inotify_start()

#### Groups helpers

The existing commands to add/update/remove groups should be adapted and some new have to be created.
These are the existing commands for Wazuh-DB:

**group table**

- wdb_insert_group() -> wdb_global_insert_agent_group() -> WDB_STMT_GLOBAL_INSERT_AGENT_GROUP: inserts a new group in the `group` table. 
- wdb_find_group() -> wdb_global_find_group() -> WDB_STMT_GLOBAL_FIND_GROUP: selects the ID of a group from the `group` table
- wdb_remove_group_db() -> wdb_global_delete_group() -> WDB_STMT_GLOBAL_DELETE_GROUP: it deletes a row in `group` table

**agent table**

- wdb_get_agent_group() -> wdb_global_select_agent_group() -> WDB_STMT_GLOBAL_SELECT_AGENT_GROUP: selects the `group` column from the **agent** table
- wdb_update_agent_group() -> wdb_global_update_agent_group() -> WDB_STMT_GLOBAL_UPDATE_AGENT_GROUP: writes the `group` column in the **agent** table

**belongs table**

- wdb_update_agent_belongs() -> wdb_global_insert_agent_belong() -> WDB_STMT_GLOBAL_INSERT_AGENT_BELONG: inserts into `belongs` table an agent-id/group-id pair 
- wdb_delete_agent_belongs() -> wdb_global_delete_agent_belong() -> WDB_STMT_GLOBAL_DELETE_AGENT_BELONG: it deletes all the entries related to one agent from `belongs` table 
- wdb_remove_group_from_belongs_db() -> wdb_global_delete_group_belong() -> WDB_STMT_GLOBAL_DELETE_GROUP_BELONG: it deletes all entries related to one group from `belongs` table

**general tasks**

- wdb_update_groups(): This method performs a few tasks. First, it gets all the names from the `group` table and compares them with the folders in **SHAREDCFG_DIR**. If the group doesn't exists any more, it deletes the entry from the group table. Also, it reads all the existing groups folders and it checks their presence in the `group` table. It adds it if not found

So, it would be necessary:
- If the `group` column in the **agent** table is hard to maintain due to its format, a new `wdb_select_group_belong()` is needed to obtain the current groups of an agent. The resulting order is crucial, because the hash of this string is used for the multi-group feature. An specific query or a new column in the `belongs` table are posible options
- Deprecate `wdb_update_groups()`, this synchronization is no longer necessary
- Adapt the `get_agent_group()` method, it currently gets the agent's groups from files
- Adapt the `set_agent_group()` method, it saves the comma separated groups string in files
- Adapt `w_remove_multigroup()`, it looks for the comma separated groups string in all the groups file. If it isn't found, it removes that multi-group folder
- Adapt `c_files()`, because it reads the agent-groups files to generate the multi-group hash that will be saved in memory
- Adapt `purge_group()`, it looks for a single group in all aget-groups files and re-writes the comma separated string without this group
- Adapt `OS_RemoveAgentGroup()`, it deletes an agent-group file for a removed agent
- Adapt `w_auth_add_agent()` and `local_add()`, they shouldn't create an agent-group file during an agent registration 

### Upgrade mechanism

In case of upgrade, a mechanism should be implemented for:
- A fresh install doesn't create the deprecated folder
- The upgrade removes the old files and writes all the information in the DB
- The `global.db` is updated, to reflect a new foreign key relation between **belongs** and **group**

### Tests proposed 

- The `remoted.guess_agent_group` setting should keep working as expected
- The agents receive the right files and configurations in both single and multi group cases
- In case of an upgrade, the groups assignment doesn't change and the centralized configuration keeps working as expected. Also, the folder and its content should be removed (consider the change in packages to avoid the folder creation)
- The `files.yml` capability works as expected

### Notes

- It was confirmed that if two agents belong to the the same groups but they were added in a different order, the centralized configuration will be merged in a different order and the behavior for these agents may be different

**Comment by palaciosjeremias** [comment]
## Master-Worker groups synchronization design
![Sync de groups (2)](https://user-images.githubusercontent.com/11434230/144926219-ef5326cb-7750-44d3-909f-2bf4f3fc0fac.png)

**Comment by palaciosjeremias** [comment]
Opening this issue because it is required to fix the following scenario:
It was contemplated to have two columns with the groups hash (local_group_hash and sync_group_hash). a master node should have local_group_hash for their own DB and the worker DB status will be reflected in sync_group_hash. But it wasn´t contemplated that a master will have multiple workers and isn´t possible to have a column for each one.
At the moment, the following options were considered:
- Having the same logic on the worker side, and being the worker the one that requests a group to the master if it isn´t updated.
- Having a simpler logic on the columns, that only marks if a sync is required, but could lead to errors difficult to solve if the synchronization fails.
- Asking the workers all the agent_id and hash tuples, and hand this information to the get command to decide which of these agents requires sync.

**Comment by palaciosjeremias** [comment]
After a new analysis we concluded with the below sync mechanism:
![Sync de groups (3)](https://user-images.githubusercontent.com/11434230/149020342-f3723d52-a77e-489a-a022-b3b482645f38.png)

The synchronization of groups between workers and master will occur in three main steps:
A) Synchronization from worker to master:
- If the worker guesses a group, it is written with empty_only mode, which prevents information synchronized by the master from being stepped on. This insertion is marked as **sync_rec**.
- Cluster, as the first task, requests all the worker groups that were in sync_req status and sends them to be written into the master, also as empty_only mode.
- At this writing, the group is written as sync_req on the master, so that it will be sent back to all workers.
- The worker does NOT pass the sync_req state to synced, so that it is the master, in the step of the top row, that overwrites this state.
    
B) Master to worker synchronization:
- Whenever a group is written to the master, it is set as sync_req, in non empty_only modes (append or override)
- Cluster would request all agents as sync_req and broadcast them to all workers. It is written as override and in synced state.
- Master must mark these as synced (this will lead to possible errors if the worker does not receive this info correctly but it is solved with the integrity thread of C)

C) Integrity check:
- Master and Worker exchange CKS of global groups.
- If the global CKS differs, the master sends ALL groups to the worker.
