### ISSUE TITLE
Windows - OVAL

### ISSUE THREAD

**Issue by rhysxevans** [wazuh/wazuh#1087]
Hi

Is there any ETA on supporting windows Vulnerability details?  If it enabled already apologies I can's see how in https://documentation.wazuh.com/3.x/user-manual/capabilities/vulnerability-detection.html 

I have also tried

```
  <wodle name="vulnerability-detector">
    <disabled>no</disabled>
    <interval>30s</interval>
    <run_on_start>yes</run_on_start>
    <feed name="windows">
      <disabled>no</disabled>
      <update_interval>2h</update_interval>
      <url>https://oval.cisecurity.org/repository/download/5.11.2/vulnerability/windows.xml</url> 
    </feed>
  </wodle>
```

but am getting 

```
[root@wazuh-server ~]#  /var/ossec/bin/verify-agent-conf

verify-agent-conf: Verifying [/var/ossec/etc/shared/default/agent.conf]
verify-agent-conf: OK


verify-agent-conf: Verifying [/var/ossec/etc/shared/WKS/agent.conf]
2018/08/10 09:16:48 verify-agent-conf: ERROR: No such tag 'feed' at module 'vulnerability-detector'.
2018/08/10 09:16:48 verify-agent-conf: ERROR: (1202): Configuration error at '/var/ossec/etc/shared/WKS/agent.conf'.
2018/08/10 09:16:48 verify-agent-conf: ERROR: (1207): WModule remote configuration in '/var/ossec/etc/shared/WKS/agent.conf' is corrupted.

```
when running  `/var/ossec/bin/verify-agent-conf`

I am using the OVA and wazuh manager v3.4.0

Any help is appreciated

Thanks

**Comment by vikman90** [comment]
Hi @rhysxevans,

Let me clarify three points here:

1. Vulnerability Detector does not yet support Windows feeds. We are working on extending the support of OVAL for CIS, this will make Vuln Detector compatible with more operating systems, including Windows and macOS. Currently, only feeds from Red Hat and Canonical are supported. Hope to have extended support of OVAL in upcoming versions.

2. Vulnerability Detector is a manager-side component, you don't have to set it up in the agent configuration (agent's _ossec.conf_ or shared _agent.conf_). Instead, you should enable Syscollector in your agents. Vulnerability Detector uses the OVAL files and the data gathered by Syscollector in the agent to detect vulnerabilities.

3. Per the log you sent us, I think you are not running the latest version of Wazuh (supporting the tag `<feed>`). This option was introduced in Wazuh 3.5. Since Windows is not yet supported, this is the error you should have seen:

```sh
# verify-agent-conf
2018/08/12 13:56:27 verify-agent-conf: ERROR: Invalid OS for tag 'feed' at module 'vulnerability-detector'.
2018/08/12 13:56:27 verify-agent-conf: ERROR: (1202): Configuration error at '/var/ossec/etc/shared/default/agent.conf'.
2018/08/12 13:56:27 verify-agent-conf: ERROR: (1207): WModule remote configuration in '/var/ossec/etc/shared/default/agent.conf' is corrupted.
```

Hope it helps.
Best regards.

**Comment by rhysxevans** [comment]
Hi

Thanks.

Regarding

1) Do you have a ETA on this ?
2) Understood
3) I have upgraded to 3.5

Thanks

**Comment by vikman90** [comment]
Hi @rhysxevans,

I'm sorry we don't have an ETA yet, although I hope it comes within this year. We will keep you posted.

Best regards.

**Comment by sarankals** [comment]
kindly confirm wazuh 3.6 is supporting windows vulnerability detector

**Comment by antoniomanuelfr** [comment]
This issue was closed in https://github.com/wazuh/wazuh/issues/2430
