### ISSUE TITLE
Test AWS IAM role chaining from different AWS accounts

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#10898]
|Component|
|---|
| AWS module |

## Description
The Wazuh AWS module is able to assume an AWS IAM role to access the logs from the buckets as long as it has the required read permissions. This is achieved thanks to the `assume_role` functionality provided by `boto3`. 

We should test if our current implementation supports AWS IAM role chaining to access a different AWS account ID using IAM roles with trust policies. The idea is to provide the Wazuh aws integration with an IAM role which has permissions to assume another IAM role in a different AWS Account ID.

## Checks
- [x] Request the required IAM roles and policies
- [x] Test the IAM Role chaining
- [x] Update the documentation accordingly if required

**Comment by noise-kngdm** [comment]
## Issue update
We have ensured that role switching between different accounts is working by creating a new AWS account, creating a new role inside that account, and then adding to the trusted entities a user from a different AWS account. The result of executing the module this way is the following:


```
root@97ece866b973:/var/ossec/wodles/aws# ./aws-s3 -b wazuh-external-cloudtrail -t cloudtrail -d2 -s 2021-dec-01 -p dev  -i arn:aws:iam::XXXXXXXXXXXX:role/wazuh-role -i arn:aws:iam::XXXXXXXXXXXX:role/wazuh-role
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Table does not exist; create
DEBUG: +++ Working on XXXXXXXXXXXX - us-west-1
DEBUG: +++ Marker: AWSLogs/XXXXXXXXXXXX/CloudTrail/us-west-1/2021/12/01
DEBUG: ++ Found new log: AWSLogs/XXXXXXXXXXXX/CloudTrail/us-west-1/2022/01/04/XXXXXXXXXXXX_CloudTrail_us-west-1_20220104T0000Z_HASDOtJxgfdNInHa.json.gz
DEBUG: +++ DB Maintenance
DEBUG: +++ DB Maintenance
```

However, we are facing difficulties when trying to assume a role after having previously assumed a role. Since the script doesn't natively support such operation, we relied on configuring the AWS credentials using the `~/.aws/credentials` file in the following way:
```
[dev]
aws_access_key_id=xxxxxxxxxxxxxxxxxxxx
aws_secret_access_key=yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
region=us-west-1

[wazuh-with-role]
source_profile = dev
role_arn = arn:aws:iam::XXXXXXXXXXXX:role/deprecaped_test_role
```


Then, we executed the module using the 'wazuh-with-role' profile, which connects to AWS having assumed the `deprecaped_test_role` using the credentials defined in the 'dev' profile. Executing the module results gives the following output:

```
root@97ece866b973:/var/ossec/wodles/aws# ./aws-s3 -b wazuh-external-cloudtrail -t cloudtrail -d2 -s 2021-dec-01 -p wazuh-with-role  -i arn:aws:iam::XXXXXXXXXXXX:role/wazuh-role -i arn:aws:iam::XXXXXXXXXXXX:role/wazuh-role
DEBUG: +++ Debug mode on - Level: 2
ERROR: Access error: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::YYYYYYYYYYYY:assumed-role/deprecaped_test_role/botocore-session-1641313537 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::XXXXXXXXXXXX:role/wazuh-role
```

We are currently working on checking if it's possible to chain roles using a workaround or if the module would need some work to enable role-chaining.

**Comment by noise-kngdm** [comment]
## Issue update
After investigating how to make a role chaining operation with our module, we came around [this article of the AWS documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_terms-and-concepts.html#iam-term-role-chaining) that explains what is role chaining and how it can be performed. 

After editing the trust relationships of the wazuh-role role to give the appropriate permissions we were able to role chain different accounts using the configuration described in the last update. When we executed the module we got the following output:

```
root@02e4a07c000b:/var/ossec/wodles/aws# ./aws-s3 -b wazuh-external-cloudtrail -i arn:aws:iam::XXXXXXXXXXXX:role/wazuh-role -p wazuh-with-role -s 2021-dec-01 -d 2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Working on XXXXXXXXXXXX - us-west-1
DEBUG: +++ Marker: AWSLogs/XXXXXXXXXXXX/CloudTrail/us-west-1/2021/12/01
DEBUG: ++ Found new log: AWSLogs/XXXXXXXXXXXX/CloudTrail/us-west-1/2022/01/04/XXXXXXXXXXXX_CloudTrail_us-west-1_20220104T0000Z_HASDOtJxgfdNInHa.json.gz
DEBUG: +++ DB Maintenance
DEBUG: +++ DB Maintenance
```

So far we can say that, with appropriate configuration of the roles, which is adequately explained in the AWS documentation, users would be able to role chain accounts with no problems.
