### ISSUE TITLE
Update the `w_remove_multigroup` function to work with the `groups` column in Wazuh DB

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#10956]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/10771, we are migrating the `agent-group` files to `wazuh-db`. Without the existence of these files, the logic in `w_remove_multigroup` can't be done as it is right now because it makes use of these files. Having said that, this method should be updated to work with Wazuh DB.

### Requirements

- [x] A new Wazuh DB command called `check_multigroup_existance` should be implemented to verify a multigroup existence. It receives a groups string in CSV format as a parameter, then it verifies if any agent has that multigroup string, and finally returns `true` or `false` depending on the case.
- [x] The Wazuh DB command should include a helper method to simplify the call from any of the Wazuh daemons.
- [x] Rename the method to `w_clean_multigroup_files`.
- [x] The new `w_clean_multigroup_files` method should call the new Wazuh DB command and perform the cleaning tasks depending on whether the command returns `true` or `false`.

### Risk analysis

This change doesn't introduce any risk because the information in the database is a mirror of the one in the files.

### Testing required

- [x] Manual testing of the `check_multigroup_existance` Wazuh DB command.
- [ ] Manual testing of the `w_clean_multigroup_files` method to verify that actually perform the cleaning tasks.

### DoD

- [ ] All the requirements should be implemented.
- [x] All the suggested tests among others should pass successfully.
- [ ] The code review should be approved.
- [x] Scan-build execution without errors.
- [ ] Jenkins tests in green.

**Comment by MiguelazoDS** [comment]
After discussing with the team we found that the previous behavior is not easily triggered. The function `w_remove_multigroup` receives a comma-separated string with different group names coming from an `authd` request, It hashes the string, takes the first 8 characters, and checks if exists a multigroup folder with that hash. In case the hashed string matches with an existent folder, it does **not** delete the multigroup directory.  But there's always a multigroup folder since at least the more recent agent added through **authd** belongs to that multigroup. In consequence, the folder is never deleted.
