### ISSUE TITLE
Implement a new column in the `agent` table of global.db to save the hash of the agents' groups

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#10951]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/10771, we have the main goal of migrating the `agent-group` files to `wazuh-db`. Having said that, as part of this issue we should add a new column to the `agent` table that will save the agents' groups hash.

### Requirements

- [x] Implement a new column in the `agent` table of `global.db` called `groups_hash`. The data type of the column should be `string`.
- [x] Implement a mechanism to add this new column in upgrade scenarios.
- [x] Implement a mechanism to fill the column during the upgrades based on the string saved in the `groups` column. It should take the string, calculate the hash, and save it in the new `groups_hash` column.
- [x] The `wdb_update_agent_group` Wazu DB global helper should be updated to also write the groups hash in the new column. The logic of the hash calculus should be done in Wazuh DB so, the helper doesn't propagate the hash.

### Risks

It should be discussed with the team how this new column should behave in a scenario in which a group is removed. We shouldn't modify the current behavior by the moment.

- [x] Add a comment with details of the decisions that were taken.

### Testing required

- [x] Clean installation and verification that the new database column exists.
- [x] Upgrade and verification that the new column is added to the database and properly completed.
- [x] Manual testing of the `wdb_update_agent_group` Wazuh DB global helper to verify that when it is called, the hash of the groups string is also written in the new database column.

### DoD

- [x] All the requirements should be implemented.
- [x] All the suggested tests among others should pass successfully.
- [x] The code review should be approved.
- [x] Scan-build execution without errors.
- [x] Jenkins tests in green (except the UTs that will be implemented altogether at the end).

**Comment by pereyra-m** [comment]
### Risks evaluation

It was noted during the implementation that the `belongs` table in **global.db** already had a foreign key related to the agent ID to automatically delete all the groups assignations in case an agent is removed. This mechanism prevents a database inconsistency. 

Now that a new relation is created with the `group`table, it isn't possible to add a new entry in `belongs` table if the group ID isn't valid. But when a group is removed, two different situations are possible:
-  Replicate existing agent foreign key behavior and delete all the entries for the agents assigned to a group that was removed
- Imitate the current behavior of **agent_groups.py** script and prevent a group deletion when it still has agents assigned to it

It was decided to maintain the current behavior of the groups tool, and prevent a group removal until that group is empty.

**Comment by pereyra-m** [comment]
### New column use cases

All the posible applications of the new `grous_hash` column will be detailed here.

#### c_files()

This method of **remoted** is called when the daemon starts and every time the `shared_reload` time expires, controlled by `update_shared_files()`. It does, among other things, the hash calculation of every groups string to determine if there is a new multi-group folder that needs to be created.

The method now reads every groups file to get this information, and even when data is retrieved from Wazuh-DB, all the groups strings should be hashed. This method is slow for the following reasons

- Every time the interval expires, the hash of all the agents that belong to more than group needs to be calculated, even if it hasn't changed because it isn't saved
- The method stores all this information in a hash table for a later comparison, but there is a lot of repeated information.  We have the same multi-group hash repeated once for every agent that belongs to that group
- This repeated information is compared with the multi-groups folder, in order to decide if that folder should be created or not. Even when the group exists, we have one check for every agent

For this application, the `groups_hash` column is more eficient:
- The hash for every agent is calculated only if the groups have changed
- We can query only for the DISTINCT values of the column, so we'd have only one comparison for every different multi-group that we have, and not for every agent.

It is important to note that the hash of the groups-string during this process is saved in two different hash tables. The 

**m_hash**
- All the agents that have a multi-group, have their groups string hash in **m_hash**
- This hash table is iterated to create the multi-groups folder if necessary
- The agents' groups string hash is also stored in the **groups** hash table 
- The hash table is used by `send_file_toagent()` to determine the corresponding shared files to send

**groups**
- This hash table contains every agent that has a multi-group, with its groups string hash and merged sum
- It is used during the multi-groups folders population in `c_multi_group()`. This method is really unpractical, see https://github.com/wazuh/wazuh/issues/11054

This hash tables use could be adapted, so they are populated once from the Wazuh-DB new column.

#### w_remove_multigroup()

Every time it is required to detect the need of multi-group folder, a simple query to Wazuh-DB would determine if it is still valid or not

**Comment by pereyra-m** [comment]
I'm closing this issue, because the PR #10969 was merged.
