### ISSUE TITLE
whodata stops sending events on Windows 2016 Datacenter on AWS

### ISSUE THREAD

**Issue by orsifacundo** [wazuh/wazuh#10968]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.5 | FIM | Agent | Packages | Windows Server 2016 Datacenter [Ver: 10.0.14393] (on AWS) |

Hi team,

There is a problem with `whodata` on the FIM module for Windows Server 2016 running on AWS. With a simple configuration like the following (with the other options as default):

```
<syscheck>
  <directories check_all="yes" report_changes="yes" whodata="yes">C:/Users/xxx/Downloads</directories>
</syscheck>
```

The events are being sent for about 5m but then the Agent stops sending them on real-time. If I check the Security channel on the Event Viewer the events aren't registered. It starts working again after restarting the Agent but the events that weren't sent are lost. The FIM module works fine if `realtime` is used instead of `whodata`.

Regards

**Comment by MarcelKemp** [comment]
Hi team,

After having performed some tests in an environment similar to the one shown in the description of the issue:
```
Windows Server 2016 Datacenter [Ver: 10.0.14393] on AWS with Wazuh 4.1.5
```
The problem found with `whodata` in the FIM module could not be reproduced, since the correct functionality was always obtained in the module, without having any information leak in the _Security_ channel on the _Event Viewer_.

Here are some tests performed in the environment with the same configuration as specified in the description:
- Add, modify and delete files manually.
- Through scripts:
  - Create 2000 files with different names (it has been verified with both empty and filled information).
  - Modify and delete those 2000 files.
  - Generate a file every 30 seconds for 30 minutes.

All this, checking the logs in `debug2`, the `alerts` and the `Event Viewer`.

And after not reproducing the problem with those tests, it has also been tested:

- Modify the monitoring directory.
- Change `whodata` to `realtime`, test it and run it again with `whodata`.
- Duplicate <directories> settings

Based on the tests carried out, it is possible that due to some configuration that has been modified in the Windows operating system itself or due to a security audit policy, it causes this _whodata_ problem. However, further testing is required to learn more details about the problem encountered.
