### ISSUE TITLE
Wazuh Agent Error on CentOS 8 Stream

### ISSUE THREAD

**Issue by luiscontrerasdo** [wazuh/wazuh#11018]
Hi Team,

Using the commands provided by Wazuh deploy interface for CentOS Linux, I got errors at the time of doing the installation, check below, but, you can see that the agent was installed, and it works, because the endpoint is registered normally.

Thanks!

> sudo WAZUH_MANAGER='192.168.88.230' WAZUH_AGENT_GROUP='default' yum install -y https://packages.wazuh.com/4.x/yum/wazuh-agent-4.2.5-1.x86_64.rpm

```
Last metadata expiration check: 5:27:58 ago on Tue 16 Nov 2021 12:15:15 PM AST.
wazuh-agent-4.2.5-1.x86_64.rpm                                                                                                1.1 MB/s | 6.4 MB     00:05
Dependencies resolved.
==============================================================================================================================================================
 Package                                Architecture                      Version                               Repository                               Size
==============================================================================================================================================================
Installing:
 wazuh-agent                            x86_64                            4.2.5-1                               @commandline                            6.4 M

Transaction Summary
==============================================================================================================================================================
Install  1 Package

Total size: 6.4 M
Installed size: 18 M
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                      1/1
  Running scriptlet: wazuh-agent-4.2.5-1.x86_64                                                                                      1/1
  Installing       : wazuh-agent-4.2.5-1.x86_64                                                                                            1/1
  Running scriptlet: wazuh-agent-4.2.5-1.x86_64                                                                                       1/1
sed: can't read ERROR_PARAM: No such file or directory
sed: can't read ERROR_PARAM: No such file or directory
sed: can't read ERROR_PARAM: No such file or directory
cat: ERROR_PARAM: No such file or directory
cat: ERROR_PARAM: No such file or directory
cat: ERROR_PARAM: No such file or directory
cat: ERROR_PARAM: No such file or directory

  Verifying        : wazuh-agent-4.2.5-1.x86_64                                                                                                           1/1
Installed products updated.

Installed:
  wazuh-agent-4.2.5-1.x86_64
```

**Comment by alberpilot** [comment]
Thanks @verdx for your testing and the proposed solution. 
We found the root cause in `dist-detect.sh` script, which makes `gen_ossec.sh` script fail. This is due to a `/etc/centos-release` format change:

CentOS 8
```
[root@centos8 vagrant]# cat /etc/centos-release
CentOS Linux release 8.4.2105
```
CentOS 8 Stream:
```
[root@localhost wazuh]# cat /etc/centos-release
CentOS Stream release 8
```
The source installation, as the package installation, ends successfully with the issue described ERROR messages. But the generated `ossec.conf` is incomplete regarding a CentOS 8 expected configuration. Attached you will find both `ossec.conf`. 

[c8_stream_conf_fixed.txt](https://github.com/wazuh/wazuh/files/7606831/c8_stream_conf_fixed.txt)
[c8_stream_no_fix.txt](https://github.com/wazuh/wazuh/files/7606832/c8_stream_no_fix.txt)


This issue was transferred from `wazuh-packages` to this repository as it's a source code issue.

**Comment by MarcelKemp** [comment]
After conducting an investigation about the problem, the following information was obtained:

- The problem resides only in the generation of the configuration, since not having `subversion` does not affect the operation of the modules (such as `syscollector`, `vulnerability detector`…).

- The generation of the configuration is failing since the [**GetTemplate**](https://github.com/wazuh/wazuh/blob/274e797f7e3028a0407548dd2fab455a72a43b4a/src/init/template-select.sh#L12) function, in charge of obtaining the configuration templates of each module, requires 4 arguments in which the subversion is found. If it doesn't catch those 4 arguments, it always throws the same error:
```
ERROR_PARAM
```

- In addition, in cases where subversion is not found, it is always necessary to set it to 0. Because we also have some conditions that require subversion, and it is checked if said subversion is equal to 0 for the case of not existing. Ex:
https://github.com/wazuh/wazuh/blob/274e797f7e3028a0407548dd2fab455a72a43b4a/src/init/inst-functions.sh#L298

- This problem can occur in cases where the data from the `os-release` file is not obtained or where the OS is equal to `CentOS`:
https://github.com/wazuh/wazuh/blob/274e797f7e3028a0407548dd2fab455a72a43b4a/src/init/dist-detect.sh#L33

To avoid this, a condition must be added so that if the subversion is not found, set it to 0 to avoid future errors in the generation of the configuration. The following PR has been opened, so that we apply the fix and avoid these errors:
