### ISSUE TITLE
Release 4.3.0- Release Candidate RC1 - Footprint metrics

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh#11019]
### Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue** |  #10954 |
| **Version** | 4.3.0                                    |
| **Release candidate #** | rc1                                        |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.3.0-rc1                                       |
| **Previous footprint meetrics** | -- |

## Checks
Status | Result | Modules | 4.3.0 Issue (4h) | 4.3.0 Issue (1d) | 4.3.0 Issue (2.5d)  |
|-- | -- | -- | -- | -- | -- | 
| 🔴 | ✔️ | All | #10995 | #11039 |  #11070 |  
| 🟢 | ✔️ | Vulnerability-detector-register | -----  | #11047 |   #11083 | 
| ⚫ | 🕐 | Vulnerability-detector | #11167  | #11182 |   --- | 
| 🟢 | ✔️ | Logcollector | #10991 |  #11041 | #11075 | 
| 🔴 | ✔️ | Syscheck |  #10997  |  #11036 | #11078| 
| 🟢 | ✔️ | Rootcheck | #11001  |  #11044 | #11081 | 
| 🟢 | ✔️ | SCA | #10989  | #11038 | #11077 | 
| 🟢 | ✔️ | Active Response |  #10994  | #11061 | #11074 | 
| 🟢 | ✔️ | Syscollector | #11000  | #11037 | #11072 | 
| 🟢 | ✔️ | Docker,Ciscat,Osquery,Azure,Openscap | #11004 | #11034 |#11066 | 
| 🔴 | ✔️ | All-except-Logcollector | #10996 |  #11062 | #11076 | 
| 🔴 | ✔️ | All-except-Rootcheck | #11057 |  #11040 | #11080 | 
| 🔴 | ✔️ | All-except-SCA | #11056 |  #11045 |  #11063 | 
| 🟢 | ✔️ | All-except-Syscheck  | #10998 |  #11043 | #11071 | 
| 🔴 | ✔️ | All-except-Active Response | #10990 |  #11035 | #11073 | 
| 🔴 | ✔️ | All-except-Syscollector |  #10992  |  #11046 | #11068 | 
| 🔴 | ✔️ | All-except-Docker,Ciscat,Osquery,Azure,Openscap | #10993 |  #11033 |  #11064 | 
| 🟢 | ✔️ | Logcollector-Syscollector | #10999 |  #11042 | #11067 | 
| 🟢 | ✔️ | Logcollector-SCA |  #11002 |  #11030 | #11069 | 
| 🔴 | ✔️ | Logcollector-Syscheck | #11003 |  #11032 |  #11065 |
| ⚫ | ⚫ | macOS-All | --- |  --- | --- | 
| ⚫ | ⚫ | Solaris-All | --- |  --- | --- | 

Result legend:
⚫ - Not launched
🕐 - Pending/In progress
✔️ - Results Ready
⚠️ - Review required

Status legend:
⚫ - None
🔴 - Rejected
🟢 - Approved

## Auditors validation

In order to close and proceed with release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @santiago-bassett 
- [ ] @alberpilot 
- [ ] @okynos 
- [ ] @rauldpm

**Comment by rauldpm** [comment]
### 1d stress test report

The errors found are common in some tests, the most serious one causes the windows agent's service to stop.

`wazuh-agent: CRITICAL: (1102): Could not acquire memory due to [(12)-(Not enough space)].`

Este mensaje suele ir acompañado de:

![image](https://user-images.githubusercontent.com/14913942/143658051-b4c19598-2165-4f8a-bb06-b00210611667.png)

Este error ha sido detectado en varios tests: [All, All-except-AR, All-except-docker(...), All-except-Rootcheck, All-except-SCA, All-except-syscollector, Syscheck, All-except-SCA

La seccion de Lorem Ipsum solo ha sido detectada en All-except-syscollector

----

Tambien se han encontrado errores comunes a los tests de logcollector y syscheck:

```
2021/11/25 15:27:09 wazuh-agent: ERROR: (6716): Could not open handle for 'c:\tmp\syscheck_test\files\fimstress.243523'. Error code: 2
2021/11/25 15:27:09 wazuh-agent: WARNING: At get_user(c:\tmp\syscheck_test\files\fimstress.243523): CreateFile(): The system cannot find the file specified. (2)
wazuh-agent: INFO: (1141): Glob error. Invalid pattern: 'C:\tmp\logcollector_test\flood*.log' or no files found.
wazuh-agent: INFO: (1141): Glob error. Invalid pattern: 'C:\tmp\logcollector_test\date*.log' or no files found.
```

----

Encontrados errores de SecurityInfo en All-except-AR, All-except-sca, All-except-rootcheck y all

```
2021/11/25 12:23:52 wazuh-agent: ERROR: GetSecurityInfo error = 0
2021/11/25 12:23:52 wazuh-agent: ERROR: GetSecurityInfo error = 183
2021/11/25 12:23:52 wazuh-agent: ERROR: GetSecurityInfo error = 183
```
----

Encontrados errores de cis-cat en  :

**Comment by okynos** [comment]
Hello!

Referring to https://github.com/wazuh/wazuh/issues/11019#issuecomment-980453570 we have found the following lines inside 4.2.5 logs:

- `wazuh-agent: ERROR: (6716): Could not open handle for`
- `wazuh-agent: WARNING: At get_user(c:\tmp\syscheck_test\files\fimstress.12649748): CreateFile(): The system cannot find the file specified. (2)`
- `wazuh-agent: ERROR: GetSecurityInfo error = 0`
- `wazuh-agent: ERROR: GetSecurityInfo error = 183`
- `wazuh-agent: ERROR: GetSecurityInfo error = 122`
- `wazuh-modulesd:ciscat: ERROR: Failed reading scan results for policy '/var/ossec/wodles/cis-cat/benchmarks/CIS_Google_Chrome_Benchmark_v1.2.0-xccdf.xml` and with other CIS files.
- `wazuh-modulesd:ciscat: ERROR: Timeout expired executing 'C:\cis-cat\benchmarks\CIS_Microsoft_Windows_Server_2016_Benchmark_v1.0.0-xccdf.xml`


Logs NOT found on 4.2.5:
- `wazuh-agent: CRITICAL: (1102): Could not acquire memory due to [(12)-(Not enough space)]`
- `wazuh-agent: INFO: (1141): Glob error. Invalid pattern:`
- `WARNING: Error found while parsing file: 'C:\Program Files (x86)\ossec-agent\ruleset\sca\stress_files_policy.yml'. Skipping it.`
- `WARNING: Error found while parsing file: 'C:\Program Files (x86)\ossec-agent\ruleset\sca\stress_registers_policy.yml'. Skipping it.`
- `WARNING: Error found while parsing file: 'C:\Program Files (x86)\ossec-agent\ruleset\sca\cis_win2019.yml'. Skipping it.`
- `wazuh-agent: ERROR: (6704): Couldn't get path of '[x32] HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\SharedAccess\\Parameters\\FirewallPolicy\\RestrictedServices\\Configurable\\System:bed48bf0-5e43-4a13-9ab0-968e4b3ec414'`
- `wazuh-agent: ERROR: (6704): Couldn't get path of '[x32] HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\SharedAccess\\Parameters\\FirewallPolicy\\RestrictedServices\\Configurable\\System:fbfcc1a9-2ff6-4779-a59a-7f370d97910e'`
- `wazuh-agent: ERROR: (6704): Couldn't get path of '[x32] HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\SharedAccess\\Parameters\\FirewallPolicy\\RestrictedServices\\Configurable\\System:{9EA4BB8E-A899-4E3D-B32E-E6111D6A19EE}'`
