### ISSUE TITLE
Prevent Wazuh agents from connecting to a lower Wazuh manager version

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#11011]
Hello team,

I'm opening this issue because although we don't support Wazuh agents with a higher version than the Wazuh server, they are able to register and connect.

We should implement a mechanism to prevent this informing that the Wazuh server is in a version and the agent should be in a version equal to or below that one.

Regards,

Miguel Casares

**Comment by sdvendramini** [comment]
# To check before continuing:
- Optional setting in ossec.conf.
- What does rejection mean?
- Is an alert created saying that an agent has been rejected?
- Does anything show up in the app?
- New State: Denied.
- What does higher version mean? This include patch?

**Comment by sdvendramini** [comment]
# Comments after meeting

- **Optional setting in ossec.conf.**  
It's proposed to define a behavior that is not optional since it is a scenario that we want to avoid.

- **What does rejection mean?** 
This means that the agent complete the registration process but will not connect.

- **Is an alert created saying that an agent has been rejected?**
It is proposed to log a message because generating alerts can cause flooding. Taking into account that the agents keep trying to connect.

- **Does anything show up in the app?**
Yes, denied agents can be showed up in the app, both in the inventory and in the agent panel.

- **New State: Denied.** 
"Denied" state it's defined instead hold in "Never connected" state those agents who cannot connect. This new state will be saved in database with the agent version.

- **What does higher version mean? This include patch?**
Can be supported agents with higger patch version. But it's important to keep in mind that it can generate problems by futures features backports.

- Should also take into account the upgrade module to support patchs upgrades.
