### ISSUE TITLE
No Wazuh Alerts after oversharding

### ISSUE THREAD

**Issue by naysoft** [wazuh/wazuh#11060]
Afternoon All,

Apologies I'm on a steep learning curve - My first wazuh deployment and it oversharded!  

I've implemented ILM so it can't happen again and now have a functioning deployment except no alerts are coming in.  I think this is because I deleted all the alert indices and now don't know how to restart or recreate the process.  Any help would be greatly appreciated.

**Comment by palaciosjeremias** [comment]
Hello @naysoft,
Sorry for this late response. This issue has been misplaced somehow.
I agree that the most possible reason for your missing alerts is that the indices have been deleted.
If you are still working on a test environment, the first suggestion is to fresh install the whole solution, so you can continue easily with your learning curve.

On the other hand, if you want to continue with your installation (or in case you have a similar problem with a production environment), we have a [script ](https://wazuh.com/blog/recover-your-data-using-wazuh-alert-backups/)that will allow you to re-feed your logs back to Kibana using the events backups.

Here is an example of the script usage:

```
usage: recovery.py [-h] [-eps eps] -min min_timestamp -max max_timestamp -o
                      output_file [-log log_file] [-w wazuh_path]
                      [-sz max_size]
 
  -eps eps, --eps eps                                                                                        Events per second. Default: 400
  -min min_timestamp, --min_timestamp min_timestamp                        Min timestamp. Example: 2019-11-13T08:42:17
  -max max_timestamp, --max_timestamp max_timestamp                    Max timestamp. Example: 2019-11-13T23:59:06
  -o output_file, --output_file output_file                                                        Alerts output file.
  -log log_file, --log_file log_file                                                                      Logs output.
  -w wazuh_path, --wazuh_path wazuh_path                                              Path to Wazuh. By default:/var/ossec/
  -sz max_size, --max_size max_size                                                           Max output file size in Gb. Default: 1Gb. Example: 2.5
```

Usage example:

`nohup ./recovery.py -eps 500 -min 2019-07-21T13:59:30 -max 2019-07-24T22:00:00 -o /tmp/recovery.json -log ./recovery.log -sz 2.5 &`

(nohup is not mandatory, but recommended in order to execute the script in the background and keep it running after the session is closed.)

The script unzips the .gz logs and dumps them into a file, next, you have to provide the file to filebeat.
(Keep in mind you need to modify /usr/share/filebeat/module/wazuh/alerts/manifest.yml by adding the directory alerts will unzip into.)

```
filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
      input:
        paths:
          - /var/ossec/logs/alerts/alerts.json
          - /tmp/recovery.json
```

Then restart Filebeat to apply the changes.


You may also want to check the [documented ](https://wazuh.com/blog/recover-your-data-using-wazuh-alert-backups/)procedure for more information.

Let me know if this helps you.
If you have further doubts please don´t hesitate to ask.
Best regards.

**Comment by palaciosjeremias** [comment]
We are closing this issue now.
@naysoft, if you need to, you can re-open it for further questions.
Best regards.

**Comment by mostwanted5** [comment]
Hii @palaciosjeremias 
I run that script, add the path in filebeat still it is not shipping logs. I checked both indexer and dashboard, no logs are showing from that path.
