### ISSUE TITLE
Windows agent service crashes with `Could not acquire memory` error

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#11084]
As reported in https://github.com/wazuh/wazuh/issues/11019#issuecomment-980453570, several errors have been found when testing the Windows agent. The errors are produced in several different test scenarios including logcollector, syscollector and syscheck stress tests.

Some of the failures cause the Agent's service to stop, as we can also observe in the data and plots for the Windows agent in https://github.com/wazuh/wazuh/issues/11070.

We need to further investigate the issue and propose a valid fix.

**Comment by Dwordcito** [comment]
Hi team, a little help here!

this issue is a memory leak on FIM.

RCA:
The function
https://github.com/wazuh/wazuh/blob/defc93defc45508e8d99fcb6d56aef1bdc5f8866/src/shared/syscheck_op.c#L981
allocate memory for account_name and domain_name, https://github.com/wazuh/wazuh/blob/defc93defc45508e8d99fcb6d56aef1bdc5f8866/src/shared/syscheck_op.c#L852 these pointers are passed as function parameters from here, which are never released.


Leak evidence:

[leakfim.txt](https://github.com/wazuh/wazuh/files/7623730/leakfim.txt)

**Comment by chemamartinez** [comment]
Fixed at #11118. Thanks, @Dwordcito!
