### ISSUE TITLE
wazuh 3.5 Vulnerabilities Severity level is Unknown  why?

### ISSUE THREAD

**Issue by myh0st** [wazuh/wazuh#1109]
![1](https://user-images.githubusercontent.com/26624320/44199285-3dcf2a80-a176-11e8-8146-1427c7daaa93.png)

wazuh server can not get online and wazuh server ossec.conf config below：

```
<ossec_config>
<wodle name="vulnerability-detector">
  <disabled>no</disabled>
  <interval>1d</interval>
  <run_on_start>yes</run_on_start>
  <feed name="redhat-6">
    <disabled>no</disabled>
    <path>/home/Red_Hat_Enterprise_Linux_6.xml</path>
    <update_interval>1h</update_interval>
  </feed>
  <feed name="redhat-7">
    <disabled>no</disabled>
    <path>/home/Red_Hat_Enterprise_Linux_7.xml</path>
    <update_interval>1h</update_interval>
  </feed>
</wodle>
</ossec_config>
```

How can the alarm level appear Unknown?

**Comment by crolopez** [comment]
Hi @myh0st,

This is a bug that has been introduced in Wazuh 3.5 by which some packages show their severity as unknown when actually known. It affects Red Hat / CentOS agents. 

It has been fixed in https://github.com/wazuh/wazuh/pull/1118, and will be released in the next release.

Thank you for reporting it.

Best regards.
