### ISSUE TITLE
4.3.0 installers and installation sizes must be analyzed due to its increments

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh#11093]
We have been analyzing the weight of installers and installations and have reached the following conclusions:

Installers:
Type | OS | 4.2.5 | 4.3.0 | Differences
-- | -- | -- | -- | --
manager | centos | 111.08M | 120.37M | 8.36%
agent | centos | 6.38M | 8.08M | 26.65%
manager | debian | 110.74M | 119.64M | 8.04%
agent | debian | 6.58M | 7.76M | 17.93%
agent | win | 5.08M | 5.55M | 9.25%
agent | macos | 4.78M | 5.20M | 8.79%
agent | solaris 10 | 13.98M | 14.34M | 2.58%
agent | solaris 11 | 5.76M | 5.93M | 2.95% 

Installations:

Type | OS | 4.2.5 | 4.3.0 | Differences
-- | -- | -- | -- | --
manager | centos | 474.46M | 499.74M | 5.33%
agent | centos | 18.67M | 22.75M | 21.85%
manager | debian | 457.33M | 489.89M | 7.12%
agent | debian | 17.37M | 20.27M | 16.70%
agent | win | 24.58M  |  31.99M | 30.15%
agent | macos | 13.24M | 14.17M | 7.02%
agent | solaris 10 | 17.09M | 16.40M | -4.04%
agent | solaris 11 | 18.27M | 18.57M | 1.64%

We consider that an increase greater than 5 percent should be studied in each case.

Also analyze the case of Solaris 10, where after the upgrade to 4.3.0 the size decreases

**Comment by MarcelKemp** [comment]
## Analysis 4.2.5 vs 4.3.0 - Installation sizes

After analyzing the managers and agents that grow more than 5%, I have obtained and shelled the following information:

### General conditions
- The information has been obtained after Wazuh has been installed but has **not started** yet.
  - Wazuh has not been started or connected between agent and manager, because depending on the information they share at the moment, it can unstable file sizes.
- Wazuh has been installed using the production (`4.2.5`) and pre-release (`4.3`) packages.
- The size difference is between the _4.3.0-rc1_ to _4.2.5_ `WAZUH_HOME` files (only those with a relevant difference in size are shown).

### CentOS

> **Manager**

Folder | Files | Size diff | Related changes
-- | -- | -- | --
_WAZUH_HOME_/var/db | mitre.db | ~10M | #7607
_WAZUH_HOME_/ruleset | SCA policies, rules, and decoders | ~3M | [Changelog - Ruleset](https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md#ruleset)
_WAZUH_HOME_/lib | Libraries | ~3M | [Changelog - Lib changes](https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md#other)
_WAZUH_HOME_/bin | Binaries | ~2M | [Changelog - Binaries](https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md#added)

> **Agent**

Folder | Files | Size diff | Related changes
-- | -- | -- | --
_WAZUH_HOME_/lib | Libraries | ~1M | [Changelog - Lib changes](https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md#other)
_WAZUH_HOME_/bin | Binaries | ~0.3M | [Changelog - Binaries](https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md#added-1)

The difference in size between the files for CentOS manager and agent makes sense according to the changes that have been made to the code.

### Debian

> **Manager**

Folder | Files | Size diff | Related changes
-- | -- | -- | --
_WAZUH_HOME_/var/db | mitre.db | ~10M | #7607
_WAZUH_HOME_ | restore-permission.sh | 4.7M | # ?
_WAZUH_HOME_/ruleset | SCA policies, rules, and decoders | ~3M | [Changelog - Ruleset](https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md#ruleset)
_WAZUH_HOME_/lib | Libraries | ~1M | [Changelog - Lib changes](https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md#other)

> **Agent**

Folder | Files | Size diff | Related changes
-- | -- | -- | --
_WAZUH_HOME_/lib | Libraries | ~4M | [Changelog - Lib changes](https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md#other)
_WAZUH_HOME_/tmp | SCA tmp | ~0.7M | [Changelog - Ruleset](https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md#ruleset)
_WAZUH_HOME_/bin | Binaries | ~0.3M | [Changelog - Binaries](https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md#added-1)

The difference in size between the files for Debian agent makes sense, however for the manager, there is a new file `restore-permission.sh` that occupies 4.7M and only appears in the installation of manager 4.3.0 for Debian.

### Windows

> **Agent**

Folder | Files | Size diff | Related changes
-- | -- | -- | --
_WAZUH_HOME_/lib | libwazuhext.dll | ~0.4M | [Changelog - Lib changes](https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md#other)
_WAZUH_HOME_/ruleset | SCA policies | ~0.4M | [Changelog - Ruleset](https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md#ruleset)
_WAZUH_HOME_/bin | Binaries | ~0.3M | [Changelog - Binaries](https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md#added-1)

With the agent stopped, the same differences as shown in the description of the issue have not been obtained, and the greater differences shown in the table make sense according to the changes made in _4.3_.

### MacOS

> **Agent**

Folder | Files | Size diff | Related changes
-- | -- | -- | --
... | ... | ... | ...

**Comment by c-bordon** [comment]
I add some tables in greater detail:


Installed without start |   |   |   |  
-- | -- | -- | -- | --
Type | OS | 4.2.5 | 4.3.0 |  
manager | centos | 474.73M | 488.91M | 2.99%
agent | centos | 18.66M | 23.77M | 27.38%
manager | debian | 457.32M | 473.53M | 3.54%
agent | debian | 16.22M | 18.14M | 11.84%
agent | win | 17.66M | 18.61M | 5.38%



Installed and started and 10 min sleep |   |   |   |  
-- | -- | -- | -- | --
Type | OS | 4.2.5 | 4.3.0 |  
manager | centos | 477.72M | 495.05M | 3.63%
agent | centos | 18.69M | 23.01M | 23.11%
manager | debian | 460.84M | 479.98M | 4.15%
agent | debian | 17.77M | 19.62M | 10.41%
agent | win | 29.52M | 32M | 8.40%

**Comment by alberpilot** [comment]
Agree with this issue analysis. The growth is justified.
