### ISSUE TITLE
Error when trying to import wazuh-kibana5-dashboards.json

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh#111]
`Wazuh 2.0` and `kibana 5.3.1`

This is the error:

![image](https://cloud.githubusercontent.com/assets/2720787/25487994/bce9eb6a-2b5d-11e7-89bc-e9cc88347fec.png)

Visualizations work, but the dashboards give an error. 

![image](https://cloud.githubusercontent.com/assets/2720787/25489411/a68caed0-2b61-11e7-87a3-fa33ee2cf3c8.png)

**Comment by snaow** [comment]
Hi @rossengeorgiev,

The error you are getting is in general related with Kibana latest versions behavior, you can't not add a visualization / dashboard which uses fields which are not present on the Elastic data (documents).

Check here some references to official Elastic repositories / forums:

- https://discuss.elastic.co/t/saved-field-parameter-is-now-invalid-please-select-a-new-field-visualize-field-is-a-required-parameter/70034
- https://discuss.elastic.co/t/saved-field-parameter-is-now-invalid-please-select-a-new-field/71044
- https://discuss.elastic.co/t/saved-field-parameter-is-now-invalid-please-select-a-new-field-visualize-field-is-a-required-parameter/70667

Your issue have been discussed in our Mailing List and in another issues:

- https://github.com/wazuh/wazuh/issues/94#issuecomment-291173921
- https://groups.google.com/forum/#!msg/wazuh/BC2VzbUc6MI/nIv8OPiPBwAJ


From Wazuh, what we did is a work around to force index-pattern, you could solve your problem by opening Wazuh App, after loading the App, check the index-pattern in your Kibana tab Management, you should have all the fields checked as "aggregatable" and "searchable", finally try to import the Dashboards again.

We are working/waiting in fix this for good, but we have our hands tied until Kibana release a solution for this.

Thanks for your feedback,
Pedro.

**Comment by rossengeorgiev** [comment]
> From Wazuh, what we did is a work around to force index-pattern, you could solve your problem by opening Wazuh App, after loading the App, check the index-pattern in your Kibana tab Management, you should have all the fields checked as "aggregatable" and "searchable", finally try to import the Dashboards again.

Not all of them are check after openning the app.

**Comment by rossengeorgiev** [comment]
Not all of the filed are ticked

![image](https://cloud.githubusercontent.com/assets/2720787/25523953/80940d82-2c00-11e7-8060-c22e0c1fb628.png)

**Comment by leandrojmp** [comment]
Hello,

Is there any other workaround for this issue?

> From Wazuh, what we did is a work around to force index-pattern, you could solve your problem by opening Wazuh App, after loading the App, check the index-pattern in your Kibana tab Management, you should have all the fields checked as "aggregatable" and "searchable", finally try to import the Dashboards again.

I'm having the same problem and the above workaround does not work.

**Comment by leandrojmp** [comment]
Hello again,
 
I've found another workaround. 

Since the problem is that Kibana visualizations won't work if a field in the visualization has no data and the dashboards won't load if some of the visualizations have erros, I manually created a dummy document with the fields that had no data and now I can see the dashboard populated.

I will now try to generate a dummy document with all the mapping fields so I can see the other dashboards that were showing errors, It's not the best solution, but it solved the problem till the fields got some real data.

**Comment by snaow** [comment]
Hi @leandrojmp,

Since this is the same issue we are discussing on the mailing list, let me quote here my own answer from the email list:

> Hi Leandro,
> 
> It makes total sense in fact, we did the same thing some weeks ago, sorry to not update this email thread with the solution we took.
> Please take a look into our documentation, we have a "sample document" covering all the fields that dashboards are going to use later.
> 
> https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/elastic_server_rpm.html#elasticsearch
> Command to insert the sample alert:
> 
> curl https://raw.githubusercontent.com/wazuh/wazuh-kibana-app/master/server/startup/integration_files/alert_sample.json | curl -XPUT "http://localhost:9200/wazuh-alerts-"`date +%Y.%m.%d`"/wazuh/sample" -H 'Content-Type: application/json' -d @- 
> 
> URL to sample alert:
> 
> https://github.com/wazuh/wazuh-kibana-app/blob/master/server/startup/integration_files/alert_sample.json
> 
> 
> Please feel free to review it and compare it with yours, we keep having some issues in certain installations I am sure you can help us improving it.
> 
> Thanks for the feedback, interest and contributions, they are too much appreciated.
> 
> Best,
> Pedro. 

Link to the email thread: 

- [https://groups.google.com/forum/#!msg/wazuh/BC2VzbUc6MI/q-v4Bwe9BgAJ](https://groups.google.com/forum/#!msg/wazuh/BC2VzbUc6MI/q-v4Bwe9BgAJ)

Thanks again for the feedback. 
It is great we thought same solution, until Kibana/Elastic release some changes or capabilities in _field_mapping API we can't do much more (but still we will work in a better solution).

Please come back to us if you have more ideas or for some reason current "alert sample" or "dummy alert" is not working.

Best,
Pedro.

**Comment by rossengeorgiev** [comment]
@leandrojmp try the steps from https://github.com/wazuh/wazuh-kibana-app/issues/24#issuecomment-319284108
