### ISSUE TITLE
Pass host to active-response

### ISSUE THREAD

**Issue by marinovgit** [wazuh/wazuh#11125]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| wazuh-manager-4.2.5-1.x86_64 | Manager | Manager | Packages/Sources | centos7 |

In the rules file (0375-web-accesslog_decoders.xml), there is an example log: 
10.11.12.13 domain.com - [05/Nov/2006:00:46:56 -0500] "GET / HTTP/1.1" 302 -

This is matched like this:
```
**Phase 2: Completed decoding.
	name: 'web-accesslog'
	parent: 'web-accesslog'
	id: '302'
	protocol: 'GET'
	srcip: 'domain.com'
	srcip2: '10.11.12.13'
	url: '/'

```

But when this must be passed to the agent this error pop up in the manager:
`wazuh-analysisd: WARNING: (1271): Invalid IP Address '"domain.com"'. Possible logging attack.`

Is there any way to pass the Host to the active-response script?

**Comment by vikman90** [comment]
Hi @marinovgit,

Indeed, the manager filters fields `srcip` and `dstuser` when triggering an Active Response. `srcip` allows alphanumeric characters plus symbols `.`, `:`, `_` and `-` ([analysisd.c](https://github.com/wazuh/wazuh/blob/15bb33d03a4612ee084f7fdcbe096f8513c21882/src/analysisd/analysisd.c#L2091)).

I'm afraid that the input log that produced that warning is a bit different from the one you show. As we see in the warning log:
```
wazuh-analysisd: WARNING: (1271): Invalid IP Address '"domain.com"'. Possible logging attack.
                                                      ^          ^
```
The host is enclosed in double-quotes (`"`), that's why the manager is rejecting to send the Active Response.

If I test your input log, I get the same result as you:
```
10.11.12.13 domain.com - [05/Nov/2006:00:46:56 -0500] "GET / HTTP/1.1" 302 -

**Phase 2: Completed decoding.
	name: 'web-accesslog'
	parent: 'web-accesslog'
	id: '302'
	protocol: 'GET'
	srcip: 'domain.com'
	srcip2: '10.11.12.13'
	url: '/'
```

However, I managed to send an Active response.

On the other hand, this other log (enclosing `domain.com` in double-quotes) produces this result and the same warning in the manager:
```
10.11.12.13 "domain.com" - [05/Nov/2006:00:46:56 -0500] "GET / HTTP/1.1" 302 -
**Phase 2: Completed decoding.
        name: 'web-accesslog'
        parent: 'web-accesslog'
        id: '302'
        protocol: 'GET'
        srcip: '"domain.com"'
        srcip2: '10.11.12.13'
        url: '/'
```
Note that `srcip` now contains double-quotes.

Could you check this difference in your logs? Perhaps the web server prints the host in different formats.

Hope this helps.
Best regards.

**Comment by marinovgit** [comment]
@vikman90 
Gosh, you are right. I removed the quotes and everything is OK now. The "host" is passed as srcip
This is from the active response on the agent.
```
     "data": {
        "protocol": "HEAD",
        "srcip": "domain.com",
        "id": "404",
        "url": "test.php",
        "srcip2": "10.11.12.13"
      },

```

Thank you ;)

**Comment by vikman90** [comment]
@marinovgit My pleasure!

Let me close this issue as it seems to be solved. Should you have further questions, feel free to reopen it.

Best regards.
