### ISSUE TITLE
enabling recent versions of Linux CVE ?

### ISSUE THREAD

**Issue by commandline-be** [wazuh/wazuh#11157]
|Wazuh version|Component|Install type|Install method|Platform|
|v4.2.5|CVEDB|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

For Ubuntu there are no CVE found for the more recent releases, how can this be enabled ?

This given there are at least three releases following Ubuntu Focal which does have CVE listed

Thinking here of Ubuntu Hirsute Hippo and more recent ones

**Comment by commandline-be** [comment]
okay, if i had the power to delete this issue, i would, sorry for wasting quanta of energy on this.

**Comment by MiguelazoDS** [comment]
Hello @commandline-be 

That's a good question. I have some workaround for that. 

The operating system you mentioned is not supported. The matrix of supported OSs can be found here. 

https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/compatibility-matrix.html

If you attempt to scan the OS, out of the box you will find the following log.

`2021/12/01 21:12:22 wazuh-modulesd:vulnerability-detector[8539] wm_vuln_detector.c:4936 at wm_vuldet_set_agents_info(): DEBUG: (5434): Agent '001' has an unsupported OS version: 'Ubuntu'`

So the trick was to configure the OS as follows in the `vulnerability-detector` tag in your manager. Specifically, in `<provider name="canonical">` section, you should put something like this. 

```xml
  <provider name="canonical">
    <enabled>yes</enabled>
    <os allow="Ubuntu-21">focal</os>
    <update_interval>1h</update_interval>
  </provider>
```
Basically forcing to use the `focal feed` to do the scan. 

For more information, you could check the following link. 

https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/allow-os.html

In that link, there's a line that states that... 
`those distributions are not scanned by default since there are not pre-defined feeds for them`

But I think that is not totally true, because there's an OVAL file for Hirsute flavor. So I would need to talk to my team to give you more accurate information. 

After that, you should be able to perform the scan on that OS as shown below

![image](https://user-images.githubusercontent.com/13010397/144337441-5e168dd5-7aef-4ce5-83f2-8b780e0a06b6.png)

![image](https://user-images.githubusercontent.com/13010397/144337178-c723d35e-5446-408b-a3ab-05318391f919.png)

As you can see in the previous image, now the vulnerability inventory has detected some vulnerabilities for the Ubuntu 21 OS. But as the link informs, it is possible to have some false positives. 

I hope this was useful. Regards!

**Comment by commandline-be** [comment]
Thanks for this. I consider the exact approach as i had mapped ZorrinOS to focal before.

I hope with version 4.3 there are vast improvements in CVE detection because at this point it is hit or miss really, for what is really just a match of OVAL data.

There is also this page https://ubuntu.com/security/oval which already offers hirsute oval data, i don't see what 'supported version' could ever mean here. It are just data feeds.

**Comment by MiguelazoDS** [comment]
Hi @commandline-be,

I'm afraid that it is not possible to include changes for this in 4.3, since it is on the way right now. But I also notice there's an OVAL file for Hirsute available to get the CVE information from that flavor. I'll be back once I get more information about this behavior. 

Sorry for the inconvenience. Regards!

**Comment by MiguelazoDS** [comment]
@commandline-be I created an issue to track this, you could check it here https://github.com/wazuh/wazuh/issues/11169 
Take into account that those distributions are supported for a short period until the new LTS version is released. In this case, it should be in April 2022. So we probably need to analyze the convenience to apply this enhancement. Regards!

**Comment by commandline-be** [comment]
Thanks. This should be a feature which is developed in Wazuh.

In the meantime  i wrote a simple script do the the CVE checking myself. it works fine, no Wazuh required. I can now run this on Debian, CentOS, RedHat, Ubuntu and get all the CVE, matched with the most recent CPE in under five minutes. The script even autoselects the matching distro and downloads the matching oval file(s).

To be honest, Wazuh is a bit of a mess when it comes to CVE checking. 

There is also lackluster QA apparently. This as I've also had to report on erroneous SCA value checks etc. 

This is really dissapointing and not favourable to consider Wazuh commercially. Unless there is a considerable delta between Wazuh in open source and commercial Wazuh offerings that it. That would be total shame as it only does a disgrace to Wazuh.

**Comment by MiguelazoDS** [comment]
Thanks for your feedback, we are going to consider your comments to improve our capabilities. Regards!
