### ISSUE TITLE
Handle FIM DB specific limits

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh#11162]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| [9103-replace-fim-db-dbsync](https://github.com/wazuh/wazuh/tree/9103-replace-fim-db-dbsync) | FIMDB | Manager/Agent | Packages/Sources | OS version |

Hello team!

While developing the issue https://github.com/wazuh/wazuh/issues/9103, we have added new options for setting the limits in Windows. Now the user can specify the maximum number of registry values and files (separately) that can be stored.

The purpose of this issue is to implement these changes in order to replicate the actual behavior:

- Make the needed functions to return the number of entries. In Windows, we can return a struct with the number of values in the `registry_value` table and in the `file` table.
- Make sure that an alert is raised when the file limit is near to be reached (function `fim_check_db_state`)
- Expand this functionality to registry value table.
- The limit functionality is handled by dbsync

https://github.com/wazuh/wazuh/blob/8478c682ea4836ddae25e4c15e55fdb84bc0e3e6/src/syscheckd/create_db.c#L596-L685

**Comment by jotacarma90** [comment]
Hi @Deblintrake09 
Indeed, this error in Windows was due to the fact that some information and debug messages were moved to organize them. And there was a failure to move this one of the file limits in the database. They were moved to a Linux-only part of the code. In this issue, which is part of the fimdb epic with DBSync, the block of these messages has been moved back to a part of code common to Windows and Linux:
https://github.com/wazuh/wazuh/blob/021973337e3d4ad4eafedab6db4062fd423d400b/src/syscheckd/src/run_check.c#L253-L260

In addition, there are now two different messages for Windows, one for the file table and one for the registry table.
