### ISSUE TITLE
Retrieving NVD files for syscollector

### ISSUE THREAD

**Issue by dgray161** [wazuh/wazuh#11166]
Good afternoon,

I am having issues finding the location in Wazuh to update the websites the syscollect wodle uses to download the NVD files after initial setup. The issue appears to be the web link changed and I can't find the location to update it. We're using Wazuh 3.13 and I see this is updated in a later version, but trying to make the change for this version.

Wazuh web address: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2010.meta

Actual web address: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2010.meta

Any help in locating the file location to make this change would be appreciated.

**Comment by chemamartinez** [comment]
Hi @dgray161,

The NVD is downloaded by the Vulnerability Detector module in the manager in order to fill the vulnerability database and correlate that data with the package inventory retrieved by Syscollector in each agent.

As you discovered, the links changed because the NVD feeds 1.0 were deprecated, the URLs have to be updated to 1.1 in order to work properly. You have several options here to make it work.

### Workaround based on the configuration

You can tune the Vulnerability Detector configuration to pull the NVD data from a custom source, this can be used to correct the URL as follows:

```xml
<provider name="nvd">
    <enabled>yes</enabled>
    <url start="2002" end="2020">https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-[-].json.gz</url>
    <update_interval>1h</update_interval>
</provider>
```

That block should replace the original block located in the manager's ossec.conf file.

Reference: https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/offline-update.html#national-vulnerability-database

### Modify the source code and rebuild the manager

This solution consists on change the URL predefined in the source code. https://github.com/wazuh/wazuh/blob/196d222a0d499faa4cc97a75e2918026db6293b5/src/wazuh_modules/vulnerability_detector/wm_vuln_detector.h#L56

After that, you'd have to rebuild the manager and update it by sources. 

Reference: https://documentation.wazuh.com/current/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-server/index.html

### Update the manager

Without a doubt, this is the best solution. Wazuh is currently in 4.2.5 and we have included lots of improvements and fixes from 3.13.0.

For example, this issue was solved in Wazuh v3.13.2 (https://github.com/wazuh/wazuh/pull/6056).

I encourage you to upgrade your manager and agents to solve this and other issues.

I hope this information helps!

Best regards,
Chema.

**Comment by dgray161** [comment]
Great! Thank you so much for the feedback! I'll be looking into which option works the best for us in the coming days. Have a great weekend.

**Comment by dgray161** [comment]
Good morning,

I was able to successfully put the suggested information in and I can see the CVE being downloaded, however, I am still seeing this error.

16:24:46 wazuh-modulesd:vulnerability-detector: ERROR: (5582): Unavailable vulnerabilities at the NVD database. The scan is aborted.

Any help would be appreciated.

Doug Gray
Security Platform Engineer
SIEMantix™
***@***.***
Cell: 502-758-2649
[signature_631721802]
