### ISSUE TITLE
Auditd + wazuh agent questions

### ISSUE THREAD

**Issue by a108a108** [wazuh/wazuh#11205]
|Version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.3-1 | Whodata| Agent | Packages | Ubuntu 20.04 |

Hi guys,

When auditd is installed on the host with the agent and whodata is enabled, the default auditd rules set by wazuh are:

> -w /boot -p wa -k wazuh_fim
> -w /etc -p wa -k wazuh_fim
> -w /home -p wa -k wazuh_fim
> -w /usr/bin -p wa -k wazuh_fim
> -w /usr/sbin -p wa -k wazuh_fim

Is it possible to change it from somewhere? Can i manage the rules from the wazuh manager?

**Comment by jnasselle** [comment]
Hi @a108a108 ,
Those rules are generated based on `syscheck` configuration section, especially `directory` options with `whodata` attribute enabled, from agent configuration file (ossec.conf and agent.conf if centralized configuration is being used). Those auditd rules mean that Wazuh agents it's looking at it.
In order to change audits rules, you should change it in `ossec.conf`. For example, to watch `/var/test` directory, you should add the next option into your `syscheck` section

```xml
    <directories check_all="yes" whodata="yes">/var/test</directories>
```
After restarting the agent , auditctl shows the new rule
```
auditctl -l | grep wazuh_fim                                                                                                                                                                     
-w /bin -p wa -k wazuh_fim
-w /boot -p wa -k wazuh_fim
-w /etc -p wa -k wazuh_fim
-w /sbin -p wa -k wazuh_fim
-w /usr/bin -p wa -k wazuh_fim
-w /usr/sbin -p wa -k wazuh_fim
-w /var/test -p wa -k wazuh_fim
```

Here's a nice User Manual description about [Auditing Whodata](https://documentation.wazuh.com/current/user-manual/capabilities/auditing-whodata/who-linux.html).

You could use [Centralized Configuration capability](https://documentation.wazuh.com/current/user-manual/reference/centralized-configuration.html?highlight=centralized) to deploy this configuration from the manager

Hope this helps!
Regards,
Nico

**Comment by a108a108** [comment]
Hi @jnasselle,
that is cool, but what about rules that are not integrity related like:
`auditctl -a exit,always -F euid>=1000 -F arch=b64 -S execve -k audit-wazuh-c`

Can I push it from the manager to agents or do I have to use another way to set it up ?

**Comment by jnasselle** [comment]
Hi @a108a108,

Oh, I see now, you are following the [Auditing commands run by a user](https://documentation.wazuh.com/current/proof-of-concept-guide/audit-commands-run-by-user.html) PoC. 
Wazuh does not provide a mechanism to deploy such rules but allows to deploy `localfile` configuration to ingest audit logs.

Regards,
Nico

**Comment by a108a108** [comment]
Hi @jnasselle,
thank you!
