### ISSUE TITLE
[Alerts index pattern] listValidIndexPatterns.find is not a function

### ISSUE THREAD

**Issue by b4b857f6ee** [wazuh/wazuh#11216]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5-1 | Wazuh component | Manager | Appliance | CentOS 7 |

Hello, i've just update from 4.1.5 to the last version and i got this message 

"[Alerts index pattern] listValidIndexPatterns.find is not a function"

Any idea how to fix?

I got it just after upgrading the kibana app doing this : https://documentation.wazuh.com/current/upgrade-guide/upgrading-wazuh.html#upgrade-the-wazuh-kibana-plugin
The section : "Upgrade the Wazuh Kibana plugin"

Thank you :)

![image](https://user-images.githubusercontent.com/36012515/144860590-9ecf939d-4971-47e1-b247-8b4ae692dfc4.png)

**Comment by Desvelao** [comment]
Hi @b4b857f6ee 

There is a related issue with this problem https://github.com/wazuh/wazuh-kibana-app/issues/3695. This is happening because there is some index pattern that has no the `attributes.fields` field of the Kibana saved object for the index pattern.

You could check the saved objects for the index pattern and verify if exists the `attributes.fields` field in all saved objects of index patterns.
1. In a browser, login into Kibana
2. Open a new tab of the same browser, and put the next URL in the URL bar:
```
<KIBANA_HOST_ADDRESS>/api/saved_objects/_find?type=index-pattern&fields=title&fields=fields&per_page=9999
```
where:
- `<KIBANA_HOST_ADDRESS>` is the address of Kibana.

> The result of this endpoint is a JSON with the information about the saved object of the index patterns.

To fix this, you could try to refresh the `fields` for the index patterns.

Steps:
1. Go to `Stack management/Index patterns`
2. Select the index pattern and click on the button to refresh the index pattern. See the screenshot.
![image](https://user-images.githubusercontent.com/34042064/145399542-ad413374-bd88-49e6-a790-ddbf7df5c37b.png)
**Important: Do this with each index pattern you have.**
3. Refresh the browser tab and access the Wazuh app

If the steps to solve the problem don't work, share the output of the endpoint I mentioned before. Share the text or a file with the text, not a screenshot because the data could be so extensive.

**Comment by Desvelao** [comment]
Hi @b4b857f6ee ,

What version of Kibana are you using?

Did you check the fields for each index pattern as I mention in the previous [message](https://github.com/wazuh/wazuh/issues/11216#issuecomment-989832245), share the output?

> You could check the saved objects for the index pattern and verify if exists the `attributes.fields` field in all saved objects of index patterns.
> 1. In a browser, login into Kibana
>2. Open a new tab of the same browser, and put the next URL in the URL bar:
> ```
> <KIBANA_HOST_ADDRESS>/api/saved_objects/_find?type=index-pattern&fields=title&fields=fields&per_page=9999
> ```
> where:
> - `<KIBANA_HOST_ADDRESS>` is the address of Kibana.
> > The result of this endpoint is a JSON with the information about the saved object of the index patterns.

Another thing you could do is check the responses that failed:
1. In a browser, open the browser dev tools (F12) and go to the `Network` tab.
2. Navigate to the Wazuh app for Kibana and if the health check is displayed where you have the error you posted in the issue, you could see that some requests failed in the `Network` tab of browser dev tools. The failed requests could have a red color. I would need you to share the responses to the requests that failed.

You could give a try to remove all the index patterns you have and try to navigate to the Wazuh app, the default index patterns used by the Wazuh app should be created. If the problem persists, share the output I mentioned previously.

**Comment by Desvelao** [comment]
I will close this due to inactivity.
