### ISSUE TITLE
How to down grade wazuh agent version

### ISSUE THREAD

**Issue by sulaiman35** [wazuh/wazuh#1125]
Hi,

Currently I am using 'v3.3.1' and a new machine is having 'v3.5.0', and they both can't communicate.

Is there any way to resolve this issue or install older version.

**Comment by crolopez** [comment]
Hi @sulaiman35,

The lower version of Wazuh is from a manager or an agent? Agents can have a lower version than the manager.

If the lower version corresponds to the manager, I recommend you to update it instead of downloading the agents' version. However, if you want to download the version of the agents I recommend you to backup the configuration files, the client.keys file, uninstall, install the desired version and restore everything.

Note that may not be able to apply a newer configuration to an older agent/manager.

Best regards.

**Comment by sulaiman35** [comment]
Thanks, I have downloaded old version of wazuh-agent from.

https://github.com/wazuh/wazuh/releases
https://github.com/wazuh/wazuh/archive/v3.3.1.tar.gz

Thanks for your help.
