### ISSUE TITLE
 "Incorrect Kibana version in plugin [wazuh]. Expected [5.3.2]

### ISSUE THREAD

**Issue by infolookup** [wazuh/wazuh#113]
While going through the setup guide and attempting step #2 /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip is giving me the following error. 

I can see this always being an issue if one version is out of wack, what's the recommended approach to fix this?

**Comment by infolookup** [comment]
Resolved. 

I specified the exact version number and while it didnt work at first after created this ticket it work an hour or so after.

 /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-2.0_5.3.2.zip
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp-2.0_5.3.2.zip
Transferring 16638105 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles

**Comment by alberpilot** [comment]
Hello inforlookup

  When a release occurs in Kibana, an update is needed in our Wazuh app. Thats why the the step that you have described sometimes give an error. It's enough to see Readme:

https://github.com/wazuh/wazuh-kibana-app

And take the last version added as you did it. 
Thanks to use the Wazuh App repository in order to open new Wazuh App related issues :)

Best regards, 
Alberto

**Comment by infolookup** [comment]
@alberpilot Thank you makes sense.
