### ISSUE TITLE
How to Integrate MySQL DB in an Existing Wazuh Install Base

### ISSUE THREAD

**Issue by musfeqsaleheen** [wazuh/wazuh#11315]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

**Comment by musfeqsaleheen** [comment]
Hi

I have an existing WAZUH install base where alertlogs are being written to the jason file. I have installed mysql database and created Alerts_DB schema ( taken from github). Followed config documentation to add Mysql DB. But when i am restarting the wazuh manager - it's erroring out with wazuh-dbd service Mysql module not compiled. Could someone help how to manage this without recompiling everything from the scratch because i have more 800 agents installed and i dont want any mess up. 

thanks

**Comment by MiguelazoDS** [comment]
Hello @musfeqsaleheen, 

At this moment it is not possible to configure the database output (MySQL or PostgreSQL) without recompiling the source code. On the other hand, I discourage you to use Wazuh-DBD as this is not under development, hence it is not fully tested and I can't guarantee the proper behavior of this module. 
Our default tool to store and check the alerts is Elasticsearch and Kibana.

Also, we recently found a bug that affects Wazuh-DB (our daemon in charge to manage the internal databases) unable to start due to Wazuh-DBD. https://github.com/wazuh/wazuh/issues/10690 
The issue is fixed and targeted for 4.3.0. 

Regards!

**Comment by MiguelazoDS** [comment]
Hi @musfeqsaleheen, 

Thank you for understanding, we are discussing the future of this module with the team and I let them know that the documentation wrongly says that the module is new in our version 4.2. 

https://documentation.wazuh.com/current/user-manual/reference/daemons/wazuh-dbd.html 

Have a good day!
