### ISSUE TITLE
Review Try, Except, Pass used in `wazuh-clusterd.py`

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#11343]
## Description

With the test created in the issue wazuh/wazuh-qa#1615, some possible code flaws were found by Bandit.

This issue is part of #10125.

In this issue we specify a flaw regarding a Try, Except, Pass clause.

The flaw tells that we are using a try, except, pass block, which is known to be a bad practice.

More information about the possible flaw: https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

Report done by the tool:

```json
{
            "code": "             child.kill()\n         except Exception:\n             pass\n \n",
            "filename": "framework/scripts/wazuh-clusterd.py",
            "issue_confidence": "HIGH",
            "issue_severity": "LOW",
            "issue_text": "Try, Except, Pass detected.",
            "line_number": 46,
            "line_range": [
                46,
                47
            ],
            "more_info": "https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html",
            "test_id": "B110",
            "test_name": "try_except_pass"
        },
```

Function where the code appears:

```python
def terminate_child_processes(parent_pid):
    """Stop the execution of all cluster child processes.

    Parameters
    ----------
    parent_pid : int
        Parent process ID.
    """
    for child in Process(parent_pid).children(recursive=True):
        try:
            child.kill()
        except Exception:
            pass
```

We should review this result and see if it is a real vulnerability. 

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Kondent** [comment]
## Update
After the merge from `4.3` to `master`, the `wazuh-clusterd.py` file was refactored.

Now, the following code block is in charge of the termination of a group of child process:
https://github.com/wazuh/wazuh/blob/dacf07da9930c4445ea55b1e5cdf6c7baea9a8d6/framework/wazuh/core/pyDaemonModule.py#L82-L96

Currently, Bandit is not capable of recognize this block as a possible flaw since it's not using `except Exception`.
https://github.com/wazuh/wazuh/blob/dacf07da9930c4445ea55b1e5cdf6c7baea9a8d6/framework/wazuh/core/pyDaemonModule.py#L88-L89
However, it should be managing this exception as a log entry.
We should consider the fact this module is being used in `wazuh-apid.py` as well, so it should be able to write into both log files.

I'm doing a few tests regarding this capability and the usage of `debug` mode to properly verify its tracebacks.
