### ISSUE TITLE
Memory error detected when starting Wazuh

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#11348]
|Wazuh version|Component|
|---|---|
| 4.3.0-rc1 | Wazuh API/Cluster/Framework |

## Description
In our internal tests, we have detected an error that kept recurring over a period of time. The error is as follows:

```
Traceback (most recent call last):
  File "/var/ossec/api/scripts/wazuh-apid.py", line 11, in <module>
    from wazuh.core import common, utils
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/__init__.py", line 10, in <module>
    from wazuh.core import common
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1414, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1386, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1517, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1560, in _fill_cache
OSError: [Errno 12] Cannot allocate memory: '/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh'
wazuh-apid: Configuration error. Exiting
```

I suspect it may be related to multiprocessing as we are running several API and Cluster instances with their respective interpreters. Due to this, memory consumption may increase and produce this error.

As for the system memory data at the time of this error:

```
root@wazuh-master:/# free -m
              total        used        free      shared  buff/cache   available
Mem:           7658        1512         387         119        5759        5734
Swap:          2048         499        1548
```

This output does not give any indication that there is a problem. Let's see how the memory usage is distributed in our development environment:

```
root@wazuh-master:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         251G   17G  222G   7% /
tmpfs            64M     0   64M   0% /dev
tmpfs           3.8G     0  3.8G   0% /sys/fs/cgroup
shm              64M     0   64M   0% /dev/shm
/dev/sdd        251G   17G  222G   7% /etc/hosts
tmpfs           3.8G     0  3.8G   0% /proc/acpi
tmpfs           3.8G     0  3.8G   0% /sys/firmware
```

My suspicion is that there is a possibility that those 64MB of `/dev/shm` may not be enough in certain scenarios. We need to investigate this bug further. To try to replicate it we can run an X script with significant memory usage and restart Wazuh. The idea is to force the memory shortage and compare it to `4.2.5`.

In case we determine that this only happens in `4.3`, we should control this exception and warn the user or find an alternative.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Selutario** [comment]
## Issue update

I have added a process pool to the worker. Both creation and use are identical to what is currently done on the master node:
https://github.com/wazuh/wazuh/blob/7aa2d817586f108539247e8f24a72661f2fbf9bb/framework/wazuh/core/cluster/master.py#L966-L967
https://github.com/wazuh/wazuh/blob/7aa2d817586f108539247e8f24a72661f2fbf9bb/framework/wazuh/core/cluster/master.py#L999-L1001

However, unlike what happens in the master, the process pool will have only one child. For this reason, it will not be configurable in the cluster.json as in the master:
https://github.com/wazuh/wazuh/blob/7aa2d817586f108539247e8f24a72661f2fbf9bb/framework/wazuh/core/cluster/cluster.json#L104

The reason that only one child is used in this `process_pool` is that its work will only be tied to the Integrity task/thread. The initial idea was to prevent what is described in the original post of the issue: that the worker does not respond while it is busy processing files that came from the master. Therefore, such processing will now be performed in the process pool while the parent process can take over other tasks. 

In fact, in my testing this already works fine after the changes suggested here. For example, if I make a distributed API request from the master node, the worker is able to respond even though files are being processed at the same time.

It has been necessary to add a flag in the worker so that when files are being processed in the process pool, new integrity synchronizations are not started (which the master would allow since its permission flag is released after sending files to the worker). I am still studying all the possible use cases to avoid problems derived from this new flag.

Also, taking advantage of the fact that the process_pool is only used in the integrity thread, I found it appropriate to also use it when calculating the files MD5 in the worker. As it is a heavy and blocking task, and the process_pool is not being used anywhere else during this stage of the integrity thread, it might be useful to use it instead of keeping it idle.
![worker_mp](https://user-images.githubusercontent.com/23361101/146011494-101beb38-0fe9-42f2-9ed5-834642561012.jpg)

**Comment by AdriiiPRodri** [comment]
## Status update

After multiple attempts to reproduce the error described in this issue we have not been able to replicate it. In our tests we have noticed that when a process occupies more than X of RAM it is killed by the system, so we cannot control this case.

On the other hand, we found this error, which is not controlled:

```
2021/12/16 15:05:23 INFO: [Master] [Local integrity] Starting.
2021/12/16 15:05:25 ERROR: [Master] [Local integrity] Error calculating local file integrity: A process in the process pool was terminated abruptly while the future was running or pending.
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/master.py", line 1013, in file_status_update
    testing_b = await asyncio.wait_for(task, timeout=None)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
2021/12/16 15:05:25 INFO: [Master] [Local integrity] Finished in 1.790s. Calculated metadata of 34 files.
2021/12/16 15:05:33 INFO: [Master] [Local integrity] Starting.
2021/12/16 15:05:33 ERROR: [Master] [Local integrity] Error calculating local file integrity: A child process terminated abruptly, the process pool is not usable anymore
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/master.py", line 1009, in file_status_update
    task = self.loop.run_in_executor(self.task_pool, wazuh.core.cluster.cluster.get_files_status)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/base_events.py", line 814, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/process.py", line 681, in submit
    raise BrokenProcessPool(self._broken)
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
2021/12/16 15:05:33 INFO: [Master] [Local integrity] Finished in 0.004s. Calculated metadata of 34 files.
```

This error occurs when a child of the main process occupies more memory than allowed. In this case the process is killed by the system and the process_pool becomes unusable. The problem with this error is that it can occur for several reasons, it is quite generic so getting the error trace is useful when debugging. So right now it remains uncontrolled because even if it is controlled the system can not continue unless it is restarted.

We will perform multiple performance/load/memory tests in RC2 to rule out any kind of failure. In addition, we think that the minimum requirements of Wazuh are outdated after all the changes to the API and Cluster, so a revision of these is pending.
