### ISSUE TITLE
NetFlow with Wazuh

### ISSUE THREAD

**Issue by Sharjeel914** [wazuh/wazuh#11360]
Hi there,

I would like to know if I can enable NetFlow with Wazuh or if there is a guide to that. My goal is to just capture and analyze the traffic passing through my router. Any alternative app would also be appreciated! 

Kind regards,
Sharjeel

P.S. Apologies for posting my thread in the wrong section, please move it to its appropriate location. Thanks!

**Comment by FrancoRivero** [comment]
Hello @Sharjeel914, 
Thank you for using Wazuh! 
Wazuh is a Host IDS rather than a Network IDS, so I'm afraid it does not support Netflow nor any kind of packet analysis technique. However, and being that said, we do have a great integration with a few famous NIDS such as Snort or Suricata. 
For more information you can check the [OwlH project](https://www.owlh.net/). 
I hope this information will be usefull to you !
Regards

**Comment by Sharjeel914** [comment]
Hello @FrancoRivero !

Thank you for getting back to me! Could you please explain further about those NIDS? I am only concerned about network traffic monitoring and analyzing (like Wireshark but from my router), do you think those would fit my need?

Another question, Wazuh has integration from Elastic, can I use Filebeat with Netflow integration from Elastic? Please elaborate on this as well. 

Looking forward to your reply!

Kind regards,
Sharjeel

**Comment by FrancoRivero** [comment]
Hi @Sharjeel914, 
OK, one thing at a time. There are some ways to detect a intrusion, the most important systems are NIDS (Network intrusion detection system)  and HIPS (Host-based intrusion detection system). The first one are placed at a strategic point or points within the network to monitor traffic to and from all devices on the network.  It performs an analysis of passing traffic on the entire subnet, and matches the traffic that is passed on the subnets to the library of known attacks. For other side a HIPS is an intrusion detection system that is capable of monitoring and analyzing the internals of a computing system as well as the network packets on its network interfaces. Wazuh is a HIDS however we can use suricata to integrate NID inside Wazuh.

Regarding the second question, I think this functionality could be useful for you because this is a way to [detect Network Intrusion with suricata ](https://documentation.wazuh.com/current/learning-wazuh/suricata.html) Suricata is one such NIDS solution, which is open source and can be quickly deployed either on dedicated hardware for monitoring one or more transit points on your network, or directly on existing Unix-like hosts to monitor just their own network traffic, this is similar to wireshark but besides monitoring a network also generate JSON events which can be integrate beautifully with Wazuh.

Wazuh has integration from Elastic, can I use Filebeat with Netflow integration from Elastic? 
Yes, Wazuh has Elastic integration and uses Filebeat maybe if you could integrate Netflow with [Filebeat](https://documentation.wazuh.com/current/learning-wazuh/build-lab/install-wazuh-manager.html) it can do whatever you want to do.  
You can personalize FileBeat following [this guide](https://documentation.wazuh.com/current/deploying-with-ansible/roles/wazuh-filebeat.html) .

Hope this is useful.
Regards

**Comment by Sharjeel914** [comment]
Hello @FrancoRivero !

Thank you so much for providing such details! Yes, it sure is helpful. 

Would you recommend Suricata or Netflow (by using Filebeat, if it is possible)? Which one of these would be easy to deploy and monitor my router's traffic? 

Looking forward to your reply.

Kind regards,
Sharjeel

**Comment by FrancoRivero** [comment]
Hello @Sharjeel914 !
I am happy to be helpful, I would recommend Suricata because you can follow [this guide](https://documentation.wazuh.com/current/learning-wazuh/suricata.html) and you would have more help from Wazuh. 
We have a channel in slack which you could ask about Wazuh problems https://wazuh.slack.com/archives/C0A933R8E, this is a good place to ask about it.

Best Regards,
Franco

**Comment by Sharjeel914** [comment]
Thank you @FrancoRivero ! It's been helpful!
