### ISSUE TITLE
Review possible flaws in our embedded python

### ISSUE THREAD

**Issue by Kondent** [wazuh/wazuh#11397]
## Description
After using [Dependencies Scanner](https://github.com/wazuh/wazuh-qa/tree/master/tests/scans/dependencies) we found out that there are a few possible flaws in our embedded python that should be reviewed.

## Dependencies Scanner Results: 
* `/var/ossec/framework/python/bin/python3 -m pytest test_dependencies.py --repo wazuh --branch master`
```json
{
    "report_date": "2021-12-20T02:11:41.929316",
    "vulnerabilities_found": 5,
    "packages": [
        {
            "package_name": "python",
            "package_version": "3.9.6",
            "package_affected_version": ">0",
            "vuln_description": "Lib/zipfile.py in Python allows remote attackers to cause a denial of service (resource consumption) via a ZIP bomb.\r\nhttps://bugs.python.org/issue36260",
            "safety_id": "37832"
        },
        {
            "package_name": "python",
            "package_version": "3.9.6",
            "package_affected_version": ">0",
            "vuln_description": "In difflib module, table header in output of difflib.HtmlDiff.make_table is not escaped and can be rendered as code in the browser, leading potentially to XSS.\r\nhttps://bugs.python.org/issue35603\r\nhttps://github.com/python/cpython/commit/44e36e80456dabaeb59c6e2a93e0c1322bfeb179",
            "safety_id": "42393"
        },
        {
            "package_name": "python",
            "package_version": "3.9.6",
            "package_affected_version": ">=3.9.0a0,<3.9.7",
            "vuln_description": "Python versions 3.6.15, 3.7.12, 3.8.12, 3.9.7 and 3.10.0rc2 fix a smtplib multiple CRLF injection vulnerability.\r\nhttps://bugs.python.org/issue43124",
            "safety_id": "42379"
        },
        {
            "package_name": "aiohttp",
            "package_version": "3.7.4",
            "package_affected_version": "<3.8.0",
            "vuln_description": "Aiohttp 3.8.0 adds validation of HTTP header keys and values to prevent header injection.\r\nhttps://github.com/aio-libs/aiohttp/issues/4818",
            "safety_id": "42692"
        },
        {
            "package_name": "werkzeug",
            "package_version": "1.0.1",
            "package_affected_version": "<2.0.2",
            "vuln_description": "Werkzeug version 2.0.2 improves the security of the debugger cookies. \"SameSite\" attribute is set to \"Strict\" instead of \"None\", and the secure flag is added when on HTTPS.",
            "safety_id": "42050"
        }
    ]
}
```

**Comment by AdriiiPRodri** [comment]
## Status update

### ID: 37832
This vulnerability will not be fixed because it must be the program itself that validates the external ZIP files: [1800749 – (CVE-2019-9674) CVE-2019-9674 python: Nested zip file (Zip bomb) vulnerability in Lib/zipfile.py (redhat.com)](https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-9674)


### ID: 42393
Already fixed: [Issue 35603: table header in output of difflib.HtmlDiff.make_table is not escaped and can be rendered as code in the browser - Python tracker](https://bugs.python.org/issue35603)


### ID: 42379
Already fixed in Python 3.9.7.


### ID: 42692
Already fixed in aiohttp 3.8.0. The Wazuh API is not affected due to format validation: `{"title": "Bad Request", "detail": "'\\r\\nLocation: https://malware.host/' is not a 'alphanumeric'. Failed validating 'format' in schema: {'format': 'alphanumeric', 'type': 'string'}. On instance: '\\r\\nLocation: https://malware.host/'"}`


### ID: 42050
Already fixed in 2.0.2.
