### ISSUE TITLE
Vulnerability detection on Windows

### ISSUE THREAD

**Issue by tarekkilani** [wazuh/wazuh#11470]
Hello,

I just configured the wazuh vulnerability detector and i would like to know if there is any way to limit the vulnerability detection results on windows hosts to return just the windows OS related CVEs.  I don't want to recieve results of CVEs related to the installed packages in the host.
Thanks in advance.

**Comment by alromeros** [comment]
Hi, @tarekkilani 

Thank you for opening this issue!

Since the sources used for diagnosing _OS_ and _package_-related CVEs are different ([MSU](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/offline-update.html#msu) and [cpe_helper](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/cpe-helper.html) respectively), what you are requesting is perfectly doable Wazuh.

In order to do that, you can simply delete or modify the `cve_helper` to avoid your manager using is package information during the vulnerability scan.

For example, a simple but clean way to do it would involve changing its name or extension:

```bash
# Adding the .disabled extension to the cpe_helper to avoid using it in the scan
$ mv /var/ossec/queue/vulnerabilities/dictionaries/cpe_helper.json /var/ossec/queue/vulnerabilities/dictionaries/cpe_helper.json.disabled
````

As said, this would avoid vulnerability detector to use `cpe_helper`, thus detecting only OS-related vulnerabilities.

One more thing! Mind that, in some cases, Windows-related packages such as Microsoft Office are also considered OS-related vulnerabilities by Microsoft itself, so, unless prevented by custom rules, these vulnerabilities will be scanned even when the `cpe_helper` is disabled.

Hope that helps!

**Comment by alromeros** [comment]
Hi, @tarekkilani 

I hope your question was solved! Let me know If you have any further questions and, if everything is okay, I'll proceed to close the issue.

Regards,
Álvaro Romero.

**Comment by tarekkilani** [comment]
Hi, @alromeros 

I didn't test the solution yet but i'll do it ASAP and will let you know if the problem is solved or not.
Thanks for your help.

**Comment by chemamartinez** [comment]
Hi @tarekkilani,

Let me close this issue due to inactivity. Don't hesitate to reopen it if further assistance is needed.

Thanks for your feedback.

Regards.
