### ISSUE TITLE
Wazuh manager behavior when remoted is stressed

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#11485]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.4 | remoted | Manager | Packages/Sources | Any |

Hello,

we've seen a strange behavior in the Wazuh manager when remoted is stressed.

Apparently, the number of TCP connections reported both by the OS and remoted.state files far surpass the reported number of active agents.

When looking at global.db last keepalives, the earliest one was already hours old, most probably ruling out scenarios where we are:
- Missing control messages.
- TCP sessions rotate.

Disconnected agents weren't generating alerts.

The purpose of this issue is to understand the behavior of the Wazuh manager at different levels when remoted is stressed. 

This is a shortlist of checks that we can expand during research:
- Agents connectivity.
- Control messages handling.
- Remoted buffer status (and how it is shown in remoted.state).
- Remoted response to agents vs remoted writing last keep alive to DB.
- Effects of NLB configurations/load on remoted.

Regards,

Javier.

**Comment by vikman90** [comment]
@havidarou we've managed to reproduce this problem and explain its cause.

## Context

- `netstat` showed about 7140 established connections, but both send and receive queues were empty.
- Remoted was using 30% CPU.
- Some agents did not manage to complete the handshake: they kept trying to connect again and again, and they didn't appear as connected.
- This problems stops appearing if we restart the manager.

### Remoted state

```sh
# Queue size
queue_size='1'

# Total queue size
total_queue_size='131072'

# TCP sessions
tcp_sessions='7147'

# Events sent to Analysisd
evt_count='1321250969'

# Control messages received
ctrl_msg_count='403418603'

# Discarded messages
discarded_count='665449343'

# Messages sent
msg_sent='404422610'

# Total number of bytes received
recv_bytes='850974844879'

# Messages dequeued after the agent closes the connection
dequeued_after_close='21781619'
```

### Agent log

The affected agents printed a log like this:

```
2022/01/27 13:07:56 wazuh-agentd: INFO: Trying to connect to server (172.27.169.161:1514/tcp).
2022/01/27 13:09:11 wazuh-agentd: INFO: Closing connection to server (172.27.169.161:1514/tcp).
2022/01/27 13:09:11 wazuh-agentd: INFO: Trying to connect to server (172.27.169.161:1514/tcp).
...
```

## Hypotheses considered

1. The number of connections with available data exceeded `MAX_EVENTS` (1024), and the agents connected to the highest socket numbers would be suffering from starvation.

This idea was discarded when we made a PoC showing that _epoll_ notifies all pending connections after multiple calls, even with a very small queue. In addition, the [`epoll_wait()` manual](https://man7.org/linux/man-pages/man2/epoll_wait.2.html) confirms this behavior:

> _If more than `maxevents` file descriptors are ready when `epoll_wait()` is called, then successive `epoll_wait()` calls will round robin through the set of ready file descriptors. This behavior helps avoid starvation scenarios, (...)_

2. Unexpected behavior due to race conditions, already fixed by #10421 for 4.3.0.

The defects addressed by the PR above were detected by ThreadSanitizer, we were not reported an actual issue caused by them. @TomasTurina found that the potential impact is that Remoted may select a wrong agent when closing a connection, which would prevent the manager from sending data to the client. This problem would be solved by reconnecting the agent.

3. The message counter that marks old connections to prevent Remoted from getting data from disconnected agents is misinterpreted by an integer overflow.

This is the problem we reproduced and addressed.

## Bug found

Remoted uses a message counter to invalidate data stored in the queue when the source agent gets disconnected. There is an array that maps socket descriptors to counters. The initial value of such counters is 0. Remoted assigns a unique incremental value to each message received and enqueued. When a client (agent) is disconnected, its socket's counter is set to the last value assigned to a message. This way, if the queue consumers find that a message counter is less than its socket's counter, such message is dropped, and `dequeued_after_close`.

The main problem here is that the global counter is a 64-bit unsigned integer (`size_t`), while the mapped socket counter is a 32-bit signed integer (`int`). The assignation operation that invalidates old messages for a socket has an **integer overflow hazard**. And what is worse, the signed value is casted back to `size_t` before performing the comparison. Thus, values whose 32rd bit is 1, get converted into a huge number, so valid messages are mistakenly dropped.

For this to impact the manager, two conditions must meet:
1. The global counter must reach a value between `(n + 1) × 2³²` and `n × 2³² - 1`.
2. Any client must be disconnected from Remoted.

When this occurs, **the socket gets tainted**, and it will keep dropping messages until any client gets disconnected from that socket while the global counter is between `n  × 2³²` and `(n + 1) × 2³² - 1`.

This bug is a regression caused by PR #3602 (v3.9.4).

## How to reproduce

We added an endpoint to set the message counter value (for testing purposes only). Then, we sent this payload to the `requests` socket to set `global_counter` to `3000000000`:

```
set_counter 3000000000
```

- Agents already connected kept working.
- New agents could also connect.
- If we restarted any agent, then it became unable to connect, and Remoted increased `dequeued_after_close`.

Later, we set the counter back to a low number, and all agents connected back.

## Proposed fix

This undesired behavior could be fixed by simply storing the socket counters in a 64-bit unsigned integer, just like the global counter.
