### ISSUE TITLE
Documentation: are alert levels 1-16 or 0-16?

### ISSUE THREAD

**Issue by pillarsdotnet** [wazuh/wazuh#1149]
The documentation for [`email_alerts.level`](https://documentation.wazuh.com/2.0/user-manual/reference/ossec-conf/email_alerts.html#level) says:

> The `level` option should be set at or above the [email_alert_level](https://documentation.wazuh.com/2.0/user-manual/reference/ossec-conf/alerts.html#reference-ossec-alerts-ea) in the `<alerts>` section of the configuration.

Default value    | n/a
---------------------|--------------------------------------------
Allowed values | Any alert level 0 to 16 is allowed.

However, [`alerts.email_alert_level`](https://documentation.wazuh.com/2.0/user-manual/reference/ossec-conf/alerts.html#reference-ossec-alerts-ea) says:

Default value    | 12
---------------------|-----------------------------
Allowed values | Any level from 1 to 16

It seems counter-intuitive that [a number from 0 to 16](https://documentation.wazuh.com/2.0/user-manual/reference/ossec-conf/email_alerts.html#level) "should be set at or above" [a number from 1 to 16](https://documentation.wazuh.com/2.0/user-manual/reference/ossec-conf/alerts.html#reference-ossec-alerts-ea).

What happens if [`level`](https://documentation.wazuh.com/2.0/user-manual/reference/ossec-conf/email_alerts.html#level) is set to 0?

**Comment by cristgl** [comment]
Hello @pillarsdotnet,

Answering your question, you can see at the [email alerts configuration](https://documentation.wazuh.com/2.0/user-manual/manager/output-options/manual-email-report/index.html?highlight=smtp) the following:

> Remember, if the level here is less than the email_alert_level configured on the previous section, this will not be sent.

Referring to the `email_alerts.level`, so, if you configure this attribute to be 0, it won't be considered, since this level is reserved for ignored alerts, this means that you cannot receive emails from alerts with level 0.

Kind regards
