### ISSUE TITLE
FIM doesn't support long file paths on Windows

### ISSUE THREAD

**Issue by RamiroRD** [wazuh/wazuh#11583]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5 | syscheck | agent | - | Windows |

The FIM module does not support watching directories trees whose lengths are close to 256. Even though Windows [removed the 256 characters limitation on Windows 10](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd), the code continues to check lengths against `PATH_MAX`, which on Windows takes the value of 256:
https://github.com/wazuh/wazuh/blob/d9bdabd771d70933276754fbab02c6939292065e/src/syscheckd/fim_diff_changes.c#L513-L516

We should implement a way to get the max path at runtime since the longest valid path depends on whether the `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled` registry exists and is set to 0x1.

**Comment by dami-nicastro** [comment]
Hi team!
Do we have the fix for this issue in the roadmap? In which version will be solved? 
Thanks!

**Comment by chemamartinez** [comment]
Hi @dami-nicastro,

We have already included it in the backlog and we will update you as soon as we have more information.

Regards.

**Comment by jotacarma90** [comment]
## Analysis
Hello team!

I am going to make a brief summary of everything I have found related to this issue.

- On the one hand, related to report_changes is the problem of the paths of files created by syscheck itself, because when using the real path of the original file, it could be the case that although the file does not exceed the limit of 260, the one created by syscheck does, generating the error:
`The path of the file monitored '%s' is too long to compute differences`

   Therefore we are going to modify report_changes to save the file names with a hash.

We also have the real problem of the long paths, I have been investigating how they work, to begin with, the long paths are only available in windows 10 onwards.
To be able to handle long paths we must have the registry enabled:
`Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled`

- On the other hand, testing what happens in FIM when long paths are used, I have verified that no alerts of any type are generated. Some functions like lstat, GetFullPathName, CreateFile... doesnt work correctly.
Since they do not accept long paths.

    I have found a strange behavior in Windows, generating false positives in the folders with long path, it seems that Windows creates some temporary files with the name:
Actual file:path: `c: \test\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`
Fim alert: `c:\\test\\aaaaaaaa~1\\aaaaaa~1\file1test`

These alerts do not correspond correctly with the creation or deletion of the original file.

**Comment by jotacarma90** [comment]
# Progress updates

In the course of researching this issue, I have encountered 4 different problems at this moment:

## Problem with "augmented" report_changes paths :green_circle: 

- This problem is fixed, I have modified the way of handling the paths in `fim_diff_changes`. Now a hashed name is used to save the necessary files.



## Problem with PATH_MAX limit in windows :yellow_circle: 

- I tried to set by hand the maximum path limit to 4096 (it could be increased to 32 767, which is the maximum supported by the long paths):

```
#ifdef WIN32
#if PATH_MAX < 4096
#define PATH_MAX 4096
#endif
#endif
```

- But it doesn't solve the last main problem.



## The functions that process filenames fail with long paths :red_circle: 

- I have encountered multiple problems in the code to process the long paths. For example:
  - If you configure in FIM a directory with a long path, the function `GetFullPathName` does not work correctly (it is necessary to modify it by `GetFullPathNameW` and adapt the code).

  - During the scan, each directory, subdirectory and file are processed with the Windows lstat function. That directly does not find the file if it is a long path:

(Debug messages created by me)
```
2022/06/02 10:04:00 wazuh-agent[4912] create_db.c:294 at fim_checker(): ERROR: fim_checker. path: c: \test\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
2022/06/02 10:04:00 wazuh-agent[4912] create_db.c:302 at fim_checker(): ERROR: lstat error: No such file or directory, n: 2
```

  - Probably other functions to delete or read the file with long path, also give problems.
  - I am still investigating possible workarounds or function modifications.



## Temporary files created with aliases of long paths :red_circle: 

- Finally, during the tests I have done, I have encountered a strange behavior in the handling of long paths. When generating one of these files and accessing it with Windows Explorer, at the time of access, a temporary file is generated with an alias of the long path. Steps:
  - I create this file, monitored in realtime: 
```
c: \test\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\file1test
```
  - No FIM alert is generated
  - When I access with Windows Explorer to that path, two FIM alerts are generated in realtime, an added and a deleted of the file with the alias of the long path (`c:\\test\\aaaaaa~1\\aaaaaa~1\\file1test`):
```
2022/06/02 10:09:37 wazuh-agent[4912] run_check.c:127 at send_syscheck_msg(): DEBUG: (6321): Sending FIM event: {"type":"event","data":{"path":"c:\\test\\aaaaaa~1\\aaaaaa~1\\file1test","version":2,"mode":"realtime","type":"added","timestamp":1654164577,"attributes":{"type":"file","size":0,"perm":{"S-1-5-32-544":{"name":"Administrators","allowed":["delete","read_control","write_dac","write_owner","synchronize","read_data","write_data","append_data","read_ea","write_ea","execute","read_attributes","write_attributes"]},"S-1-5-18":{"name":"SYSTEM","allowed":["delete","read_control","write_dac","write_owner","synchronize","read_data","write_data","append_data","read_ea","write_ea","execute","read_attributes","write_attributes"]},"S-1-5-32-545":{"name":"Users","allowed":["read_control","synchronize","read_data","read_ea","execute","read_attributes"]},"S-1-5-11":{"name":"Authenticated Users","allowed":["delete","read_control","synchronize","read_data","write_data","append_data","read_ea","write_ea","execute","read_attributes","write_attributes"]}},"uid":"S-1-5-32-544","user_name":"Administrators","inode":0,"mtime":1654160577,"hash_md5":"d41d8cd98f00b204e9800998ecf8427e","hash_sha1":"da39a3ee5e6b4b0d3255bfef95601890afd80709","hash_sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","attributes":"ARCHIVE","checksum":"3ab5f7e6ae5ac6709a7f450dd7f91afeecdedd09"}}}
2022/06/02 10:09:42 wazuh-agent[4912] run_check.c:127 at send_syscheck_msg(): DEBUG: (6321): Sending FIM event: {"type":"event","data":{"path":"c:\\test\\aaaaaa~1\\aaaaaa~1\\file1test","version":2,"mode":"scheduled","type":"deleted","timestamp":1654164577,"attributes":{"type":"file","size":0,"perm":{"S-1-5-32-544":{"name":"Administrators","allowed":["delete","read_control","write_dac","write_owner","synchronize","read_data","write_data","append_data","read_ea","write_ea","execute","read_attributes","write_attributes"]},"S-1-5-18":{"name":"SYSTEM","allowed":["delete","read_control","write_dac","write_owner","synchronize","read_data","write_data","append_data","read_ea","write_ea","execute","read_attributes","write_attributes"]},"S-1-5-32-545":{"name":"Users","allowed":["read_control","synchronize","read_data","read_ea","execute","read_attributes"]},"S-1-5-11":{"name":"Authenticated Users","allowed":["delete","read_control","synchronize","read_data","write_data","append_data","read_ea","write_ea","execute","read_attributes","write_attributes"]}},"uid":"S-1-5-32-544","user_name":"Administrators","inode":0,"mtime":1654160577,"hash_md5":"d41d8cd98f00b204e9800998ecf8427e","hash_sha1":"da39a3ee5e6b4b0d3255bfef95601890afd80709","hash_sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","attributes":"ARCHIVE","checksum":"3ab5f7e6ae5ac6709a7f450dd7f91afeecdedd09"}}}
```

**Comment by werewolf-65** [comment]
Hi is the fix for this limitation released? If so, what is the fix version?

**Comment by vampig** [comment]
Guys, hello! Can someone confirm whether the issue with the "maximum path length" problem has been fixed, or if it will be fixed in the future?
With win-agent 4.13.0 beta 2 on Windows Server 2022 Standard 10.0.20348.4052, and with the LongPathsEnabled parameter set in the Windows registry, the agent still shows warnings (6720) :(
Thanks in advance for your reply!

**Comment by jhonatandpreis** [comment]
Estou com o mesmo problema is too long. The maximum length is 260 characters

Agente 4.13 windows server 2019

**Comment by ibtissem2018** [comment]
I face the same problem, is there a solution for it?

**Comment by HamzaG-ui** [comment]
Same problem here with Wazuh 4.14 / OSSEC on Windows — long path warnings prevent monitoring deep folders.

LongPathsEnabled is set to 1 in the registry, but monitoring folders with deep nested directories still triggers: 

WARNING: (6720): The path <Path> is too long. The maximum length is 260 characters.
