### ISSUE TITLE
The agent will be disconnected for some time after deployment

### ISSUE THREAD

**Issue by hantiger** [wazuh/wazuh#11595]
|Wazuh version|Install according to official documentation|Install method|Platform|
|-|-|-|-|-|
|4.2.1|almost all|Manager|Install using the package manager according to the official documentation|ubuntu 18.04

    Agents disconnect from manager without reason,Here are some of my descriptions and problems. Please help me to see whether this is correct and whether the remaining problems can be effectively handled. Thank you

    Most of the previously deployed agents often appear in the disconnect state during operation. After checking the agent and wazuh manage logs, the problem is not found.
    In order to solve this problem, I refer to the official document to use ossec Conf modified < force_ Insert > value is yes, < force_ Time > value is 10

The ossec auth part is configured as follows:
<auth>
    <disabled>no</disabled>
    <port>1515</port>
    <use_source_ip>yes</use_source_ip>
    <force_insert>yes</force_insert>
    <force_time>10</force_time>
    <purge>yes</purge>
    <use_password>no</use_password>
    <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
    
    <ssl_verify_host>no</ssl_verify_host>
    <ssl_manager_cert>/var/ossec/etc/sslmanager.cert</ssl_manager_cert>
    <ssl_manager_key>/var/ossec/etc/sslmanager.key</ssl_manager_key>
    <ssl_auto_negotiate>no</ssl_auto_negotiate>
  </auth>

After the above operations, the problem has been improved, but there are still two problems as follows:
1. A large number of agents will still appear in the disconnect state after running for a period of time
2、agent_ The ID will continue to increase
I extracted some logs as follows:
2021/12/28 05:36:11 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2021/12/28 05:36:11 wazuh-remoted: INFO: (1410): Reading authentication keys file.
2021/12/28 05:36:11 wazuh-authd: INFO: Duplicated IP 'xxx.xx.22.15' (187838). Removing old agent.
2021/12/28 05:36:11 wazuh-authd: INFO: Agent key generated for 'bj-hdfs115.xxx.cn' (requested by xxx.xx.22.15)
2021/12/28 05:36:11 wazuh-authd: INFO: New connection from xxx.xx8.9.21
2021/12/28 05:36:11 wazuh-authd: INFO: Received request for a new agent (tjdata11.xxx.cn) from: xxx.xx8.9.21
2021/12/28 05:36:11 wazuh-authd: INFO: Duplicated IP 'xxx.xx8.9.21' (189336). Removing old agent.
2021/12/28 05:36:11 wazuh-authd: INFO: Agent key generated for 'tjdata11.xxx.cn' (requested by xxx.xx8.9.21)
2021/12/28 05:36:11 wazuh-authd: INFO: New connection from xxx.xx.23.19
2021/12/28 05:36:11 wazuh-authd: INFO: Received request for a new agent (bj-hdfs169.xxx.cn) from: xxx.xx.23.19
2021/12/28 05:36:11 wazuh-authd: INFO: Duplicated IP 'xxx.xx.23.19' (188622). Removing old agent.
2021/12/28 05:36:11 wazuh-authd: INFO: Agent key generated for 'xxxdfs169.xxx.cn' (requested by xxx.xx.23.19)
2021/12/28 05:36:11 wazuh-authd: INFO: New connection from xxx.xx.15.24
2021/12/28 05:36:11 wazuh-authd: INFO: Received request for a new agent (gpu424.xxx.cn) from: xxx.xx.15.24
2021/12/28 05:36:12 wazuh-authd: INFO: Duplicated IP 'xxx.xx.15.24' (189521). Removing old agent.

**Comment by pereyra-m** [comment]
Hello @hantiger !

When the agents can't connect to the manager in the port 1514 after several attempts, they will try to request a new key automatically ([Auto-enrollment](https://documentation.wazuh.com/4.2/user-manual/registering/agent-enrollment.html#registration-using-the-enrollment-method)) in the 1515 port. This is why you see the agents re-registering many times and the ID increasing.

Are you sure you need the [use_source_ip](https://documentation.wazuh.com/4.2/user-manual/reference/ossec-conf/auth.html?highlight=use_source_ip#use-source-ip) option? This is only useful when the agents have a static IP during all their life cycle. If they will be connected to the manager from a dynamic IP or if you have many of them with the same public IP, you should disable this option.

First, I'd upgrade the manager and agents to the last version because since [v4.2.2](https://github.com/wazuh/wazuh/releases/tag/v4.2.2) the manager will not generate new keys for agents that hold a valid one. This will stop the re-registering cycle.

To solve the disconnection issue, please confirm the agents can reach the manager in the 1514 port  (use **ping** command for example). If this is the case, upload the full `ossec.log` file for both manager and agents so we can analyze them properly.

Regards.

**Comment by hantiger** [comment]
Thank you for your assistance.
I will upgrade according to your suggestions. If the agent is still disconnected after the upgrade, continue to check. Thank you

**Comment by pereyra-m** [comment]
Thanks to you!
Remember, the upgrade will only stop the re-registering process for the agents that are unable to connect.
To solve the connection issue, the **ping** test and the logs are required.

Regards.

**Comment by hantiger** [comment]
After upgrading to version 4.2.5, I encountered a large number of offline agents again. Some log information is as follows:

Jan 20, 2022 @ 15:35:54.000 wazuh-authd INFO  New connection from 10.233.70.0
Jan 20, 2022 @ 15:35:54.000 wazuh-authd INFO  Received request for a new agent (xxx.xxx.com) from: 10.233.70.0
Jan 20, 2022 @ 15:35:54.000 wazuh-authd INFO  Duplicate name 'xxx.xxx.com' (021).
Jan 20, 2022 @ 15:35:54.000 wazuh-authd INFO  Agent '021' key already exists on the manager.
Jan 20, 2022 @ 15:35:53.000 wazuh-authd INFO  Duplicate name 'xxx.xxx.com' (095).
Jan 20, 2022 @ 15:35:53.000 wazuh-authd INFO  Agent '095' key already exists on the manager.
Jan 20, 2022 @ 15:35:52.000 wazuh-authd INFO  Received request for a new agent (xxx.xxx.com) from: 10.233.70.0
Jan 20, 2022 @ 15:35:52.000 wazuh-authd INFO  Duplicate name 'xxx.xxx.com' (209).
Jan 20, 2022 @ 15:35:52.000 wazuh-authd INFO  Agent '209' key already exists on the manager.

The configuration information of wazuh authentication part is as follows:
<auth>
    <disabled>no</disabled>
    <port>1515</port>
    <use_source_ip>no</use_source_ip>
    <force_insert>yes</force_insert>
    <force_time>0</force_time>
    <purge>yes</purge>
    <use_password>no</use_password>
    <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
    
    <ssl_verify_host>no</ssl_verify_host>
    <ssl_manager_cert>/var/ossec/etc/sslmanager.cert</ssl_manager_cert>
    <ssl_manager_key>/var/ossec/etc/sslmanager.key</ssl_manager_key>
    <ssl_auto_negotiate>no</ssl_auto_negotiate>
  </auth>

**Comment by hantiger** [comment]
Is it convenient to help you look at this problem? When the number of agents is small, there is no problem in the test. When the number is large, the above log will be reported, and the number of agents will also have problems. Occasionally, all normal phenomena will appear, and the reason is not found.

**Comment by palaciosjeremias** [comment]
Hello hantiger,
Matias Pereyra is on PTO right now, but I will continue with this issue.
As we can observe on the logs that you provided, the new mechanism that avoids re-registrations is working correctly, because now Authd is rejecting the re-registration of the agents as they already exist in the manager.
`Jan 20, 2022 @ 15:35:52.000 wazuh-authd INFO Agent '209' key already exists on the manager.`

On the other hand, as Matías explained [here ](https://github.com/wazuh/wazuh/issues/11595#issuecomment-1002673281) we need to confirm that you really need the **use_source_ip** option as enabled. Keep in mind that this option is disabled by default, and what it does is:
Every new agent can be registered with a specific IP or with "any". Registering an agent with a specific IP makes that this agent can ONLY connect with the manager if the agent IP matches with the one specified during the registration. The default registration option is "any", allowing the agent to connect the manager from any IP address, but, enabling **use_source_ip** on the manager makes that the IP of the key request is used as a specific IP and the agent is registered in a way that after the registration it can only establish connection with the manager if they connect from the same IP of the registration process.
This will lead to problems (agents being rejected when trying to connect) if the host of the Wazuh Agent changes the IP (if the host is a notebook changing from networks, or if the host connects thru a VPN, etc).
Is it possible that this is your case and your agents are changing the IP address? If this is the case you should disable **user_source_ip** option and re-register the agents. You can confirm how your agents are registered checking the **client.keys** file. i.e. this is the key of an agent registered with "any":
`001 ubuntu1.test any fc5131f9c0b967f543817824342f86520669df469d7ae5f3b936e877df5e157b`

If this isn´t the case, and the agents are guaranteed to connect always from the same IP, the most possible reason for the disconnection is network problems. If you can share with us the complete **ossec.log** file from the manager and from the problematic agent, we can check to confirm if the hosts are having network problems.
If there are connectivity problems we can work to identify the reason, probably by creating cron jobs with ping or telnet commands to collect more information.

Please, confirm if the detailed scenarios match your environment and let me know how the tests go.

Best regards!

**Comment by alyvusal** [comment]
Hi, I have same issue. Also `source_ip` not used. Still many agent disconnects. Increased api timeout, restarted manager service. worked 1-2 day, then started to disconnect agents
```
2022/01/28 08:53:49 wazuh-authd: INFO: Received request for a new agent (XXX) from: 192.168.xx.xx
2022/01/28 08:53:49 wazuh-authd: INFO: Duplicate name 'XXX' (099).
2022/01/28 08:53:53 wazuh-authd: INFO: Agent '099' key already exists on the manager.
```

**Comment by palaciosjeremias** [comment]
Hello Alyvusal.
Thank you for using Wazuh.
Can you bring us more details of your problem?:
- Which version of Wazuh Manager and Agent are you using?
- Did your disconnected keeps always as disconnected or they can reconnect with your manager?
- Are always the same agents having this problem?
- Did you test the network connectivity (like using a **ping** or **telnet** command) when the problem occurred?
- How many agents are connected with your manager and how many are disconnected?
- Can you share with us your manager and agents configuration (**ossec.conf** file) and the logs from both of them (**ossec.log**)

The [recommendation](https://github.com/wazuh/wazuh/issues/7604#issuecomment-787464545) extends the time after the agent is considered as disconnected if stops sending events. It can help, but we need to identify first why are your agents stoping communicating with the manager.

Best regards.

**Comment by alyvusal** [comment]
HI @palaciosjeremias , regarding your questions:

1. installed with wazuh-ansible, branch 4.2
2. They reconnect again, but a lot of `reconnecting again, ID already exists, locked` messages. Agent does not use source ip, uses `any`
3. all agents periodically has issues. I use nginx in front of agents and api. extended timeout to 180s
4. network is normal, on same LAN and hypervisor also has same issue
5. 150 agent connected, up to 30-40 being disconnected. But connects again
6. example agent log

```
2022/02/01 08:13:06 wazuh-agentd: WARNING: Server unavailable. Setting lock.
2022/02/01 08:13:06 wazuh-agentd: INFO: Closing connection to server (xx:1514/tcp).
2022/02/01 08:13:06 wazuh-agentd: INFO: Trying to connect to server (xx:1514/tcp).
2022/02/01 08:13:48 wazuh-syscheckd: WARNING: Process locked due to agent is offline. Waiting for connection...
2022/02/01 08:14:11 wazuh-agentd: INFO: Closing connection to server (xx:1514/tcp).
2022/02/01 08:14:11 wazuh-agentd: INFO: Trying to connect to server (xx:1514/tcp).
2022/02/01 08:15:16 wazuh-agentd: INFO: Closing connection to server (xx:1514/tcp).
2022/02/01 08:15:16 wazuh-agentd: INFO: Trying to connect to server (xx:1514/tcp).
2022/02/01 08:15:29 wazuh-agentd: INFO: (4102): Connected to the server (xx:1514/tcp).
2022/02/01 08:15:29 wazuh-agentd: INFO: Server responded. Releasing lock.
2022/02/01 08:15:33 wazuh-syscheckd: INFO: Agent is now online. Process unlocked, continuing...
2022/02/01 08:17:31 wazuh-agentd: WARNING: Server unavailable. Setting lock.
```

example manager logs, y.y.y.y is nginx load balancer ip

```
2022/02/01 08:12:31 wazuh-authd: INFO: Duplicate name 'YYY' (098).
2022/02/01 08:12:31 wazuh-authd: INFO: Agent '098' key already exists on the manager.
2022/02/01 08:12:51 wazuh-authd: INFO: New connection from y.y.y.y
2022/02/01 08:12:51 wazuh-authd: INFO: Received request for a new agent (node-name) from: y.y.y.y
```

client node config part

```
  <client>
    <server>
      <address>y.y.y.y</address>
      <port>1514</port>
      <protocol>tcp</protocol>
      <max_retries>5</max_retries>
      <retry_interval>5</retry_interval>
    </server>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
    <crypto_method>aes</crypto_method>

    <enrollment>
      <enabled>yes</enabled>
      <port>1515</port>
      <authorization_pass_path>/var/ossec/etc/authd.pass</authorization_pass_path>
      <auto_method>no</auto_method>
      <delay_after_enrollment>20</delay_after_enrollment>
      <use_source_ip>no</use_source_ip>
    </enrollment>

  </client>

```

**Comment by alyvusal** [comment]
Hi @palaciosjeremias 

Thank you for checking config files. 
I don't use auth, auth file also is empty.
I checked with telnet, results are:

- telnet through nginx is disconnecting after [10m default timout](http://nginx.org/en/docs/stream/ngx_stream_proxy_module.html#proxy_timeout)

- telnet directly to master, worker nodes does not disconnect

May be your team can improve wazuh agent connection process based on these results
For logs you wanted is same and repeated as [above](https://github.com/wazuh/wazuh/issues/11595#issuecomment-1026583728)

**Comment by palaciosjeremias** [comment]
Hello Alyvusal.
We think this isn´t a problem with the agent connection process. Probably it´s an error in the system environment where Wazuh is deployed.
Regarding the tests performed:
- Did run the **telnet** command on your agent host to ping the worker of the connection? Did you maintain the telnet **command** open during an agent disconnection? The command didn´t show a disconnection?
- You mention that there are timeouts on one of the tests, can you provide more info regarding this test? How and where did you execute the command?

Regarding the logs:
The actually provided logs aren´t complete and don´t show any message from Remoted. We are trying to identify which is the problematic host, maybe the manager host is getting disconnected from your network and all the agents will be seen as disconnected simultaneously. Or maybe we can find a time pattern of the disconnection that helps you to find the problem behind this.

Best regards.

**Comment by hantiger** [comment]
@palaciosjeremias @alyvusal Thank you for your support. Due to some personal reasons, I didn't reply to the test in time. During this period, I have been paying attention to your discussion. The scenarios I encountered before are almost the same as those encountered by alyvusal, and I tested according to the test method you gave.
-The agent end in active state pings the wazuh master. During this period, the wazuh agent changes from active state to disconnect state without packet loss.
-The agent end in the disconnected state pings the wazuh master. During this period, the wazuh agent changes from the disconnected state to the active state without packet loss.
I also checked the logs of agent and master. There is no log information of disconnection during this time period, but the wazuh GUI does show the status change. I started the test at 07:30 on February 7, 2022. Some logs are provided here for reference
-Before that, a large number of the same logs were found on the agent side. After I started the test, such problems also occurred. The nmap test port was opened normally, and there was no packet loss during the Ping test. Is there any other available troubleshooting method in this place.
2022/02/07 05:17:07 wazuh-agentd: INFO: Requesting a key from server: manager_ip
2022/02/07 05:17:09 wazuh-agentd: INFO: No authentication password provided
2022/02/07 05:17:09 wazuh-agentd: INFO: Using agent name as: test-master
2022/02/07 05:17:09 wazuh-agentd: INFO: Waiting for server reply
2022/02/07 05:17:09 wazuh-agentd: ERROR: Duplicate agent name: test-master (from manager)
2022/02/07 05:17:09 wazuh-agentd: ERROR: Unable to add agent (from manager)
2022/02/07 05:17:19 wazuh-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: 'manager_ip'.
2022/02/07 05:17:19 wazuh-agentd: WARNING: Unable to connect to any server.
2022/02/07 05:17:19 wazuh-agentd: INFO: Closing connection to server (manager_ip:1514/tcp).
2022/02/07 05:17:19 wazuh-agentd: INFO: Trying to connect to server (manager_ip:1514/tcp).
2022/02/07 05:18:29 wazuh-agentd: INFO: Closing connection to server (manager_ip:1514/tcp).
2022/02/07 05:18:29 wazuh-agentd: INFO: Trying to connect to server (manager_ip:1514/tcp).
2022/02/07 05:19:39 wazuh-agentd: INFO: Closing connection to server (manager_ip:1514/tcp).
2022/02/07 05:19:39 wazuh-agentd: INFO: Trying to connect to server (manager_ip:1514/tcp).
2022/02/07 05:20:49 wazuh-agentd: INFO: Closing connection to server (manager_ip:1514/tcp).
2022/02/07 05:20:49 wazuh-agentd: INFO: Trying to connect to server (manager_ip:1514/tcp).
2022/02/07 05:21:59 wazuh-agentd: INFO: Closing connection to server (manager_ip:1514/tcp).
2022/02/07 05:21:59 wazuh-agentd: INFO: Trying to connect to server (manager_ip:1514/tcp).

![image](https://user-images.githubusercontent.com/63154152/152709905-51532991-1819-48da-8b18-a4f7a8854fdb.png)
[ossec_info.zip](https://github.com/wazuh/wazuh/files/8011644/ossec_info.zip)

**Comment by alyvusal** [comment]
Hi @palaciosjeremias, as @hantiger explained, there is no detailed logs for disconnect. 
Check with wazuh-ansible and use almost most default variables. I think you should see same logs

**Comment by mark260486** [comment]
Hi, guys! We have the same issue as @hantiger last post. We can provide some information or logs, if you need.

**Comment by palaciosjeremias** [comment]
Hello @mark260486, @alyvusal, @hantiger.
Can you:
- Enable DEBUG logs in remoted -> write **remoted.debug=2** in **local_internal_options.conf** file.
- Restart Wazuh manager (the worker where the agent is getting connected).
- Reproduce the issue.
- Share with us the logs from both, agent and manager (the worker where the agent is getting connected).

We want to confirm if your problem is with this [bug ](https://github.com/wazuh/wazuh/issues/11485) found that is already [fixed ](https://github.com/wazuh/wazuh/pull/11974)for 4.3.
This issue was observed on managers with high amount of packages received from the agents ( (**n + 1) × 2³²** ), and the problem is bypassed after a manager restart. So, it doesn´t really seem to be the problem that you express.
But, with the requested logs we will be able to confirm if this is related with your problem or start investigating the problem.
Best regards,

**Comment by hantiger** [comment]
I follow the steps below
1. Execute echo "remote. Debug = 2" > > / var / ossec / etc / local on the test agent_ internal_ options. conf
2. Restart wazuh agent, systemctl restart wazuh agent
3. Restart wazuh manager, systemctl restart wazuh master and systemctl restart wazuh worker
4. Wait for the problem to reappear
After restarting the agent, the status of wazuh agent is disconnected by default. The phenomenon and the previously reported situation have been, and the network and services are checked to be normal.
! [image]( https://user-images.githubusercontent.com/63154152/152906706-cccbde26-3b8b-4f08-bcdd-fb3af7e853e8.png )
5. The log during the test has been provided, and no redundant debug information has been found. Is there an error in the intermediate operation process? If there is a problem, please correct it in time. I will provide more detailed information at the first time. Thank you
[ossec_info.zip](https://github.com/wazuh/wazuh/files/8020266/ossec_info.zip)

After reading the vulnerability repair report you sent, the phenomenon is very similar. At present, my environment is deployed in the form of kubernetes, and I am trying to upgrade to 4.3 X version to see if the problem can still be reproduced.

**Comment by mark260486** [comment]
Hi, @palaciosjeremias! Thanks for the reply. Report is below.

1) Agent looks working properly, but it have Never connected state. After manual installation it appears in Kibana with Any IP address and Never connected status. Agent restart does not help. Then, after several attempts to reconnect, agent re-register thyself and in some cases fall into infinite cycle of re-register tries. Worker node redirect these register requests to Master node, as it should be. But then we see strange things in Worker logs.
Agent log is attached.

Worker in debug mode shows this. Looks like registration was not performed correctly and worker doesn't know about registered agent and actively refuses agent connections for 1514 port.
We suppose problem is on Master node, cause new and clear Worker node reproduce this errors with agent registration and connection.

```
2022/02/08 00:00:10 wazuh-monitord: INFO: Starting new log after rotation.
2022/02/08 00:34:29 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/02/08 00:34:29 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2022/02/08 01:34:30 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/02/08 01:34:30 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2022/02/08 02:13:36 wazuh-authd: INFO: New connection from AGENT_IP
2022/02/08 02:13:36 wazuh-authd: INFO: Received request for a new agent (AGENT_NAME) from: AGENT_IP
2022/02/08 02:13:36 wazuh-authd: INFO: Dispatching request to master node
2022/02/08 02:14:31 wazuh-authd: INFO: Agent key generated for 'AGENT_NAME' (requested by any)
2022/02/08 02:14:32 wazuh-remoted: WARNING: (1408): Invalid ID 3474 for the source ip: 'AGENT_IP' (name 'unknown').
2022/02/08 02:14:35 wazuh-remoted: WARNING: (1408): Invalid ID 3474 for the source ip: 'AGENT_IP' (name 'unknown').
2022/02/08 02:14:45 wazuh-remoted: WARNING: (1408): Invalid ID 3474 for the source ip: 'AGENT_IP' (name 'unknown').
2022/02/08 02:14:55 wazuh-remoted: WARNING: (1408): Invalid ID 3474 for the source ip: 'AGENT_IP' (name 'unknown').
2022/02/08 02:15:05 wazuh-remoted: WARNING: (1408): Invalid ID 3474 for the source ip: 'AGENT_IP' (name 'unknown').
2022/02/08 02:15:15 wazuh-remoted: WARNING: (1408): Invalid ID 3474 for the source ip: 'AGENT_IP' (name 'unknown').
2022/02/08 02:15:15 wazuh-authd: INFO: New connection from AGENT_IP
2022/02/08 02:15:15 wazuh-authd: INFO: Received request for a new agent (AGENT_NAME) from: AGENT_IP
2022/02/08 02:15:15 wazuh-authd: INFO: Dispatching request to master node
2022/02/08 02:16:48 wazuh-authd: INFO: Agent key generated for 'AGENT_NAME' (requested by AGENT_IP)
2022/02/08 02:17:08 wazuh-remoted: WARNING: (1213): Message from 'AGENT_IP' not allowed. Cannot find the ID of the agent. Source agent ID is unknown.
```

On Master node we see tons of repeating requests for registration from failed agents. And for some reason they all have balancer IP. Before the failure it works well.
```
2022/02/08 09:02:41 wazuh-authd: INFO: New connection from BALANCER_IP
2022/02/08 09:02:41 wazuh-authd: INFO: Received request for a new agent (AGENT_NAME_1) from: BALANCER_IP
2022/02/08 09:02:41 wazuh-authd: INFO: Duplicate name 'AGENT_NAME_1' (1677).
2022/02/08 09:02:41 wazuh-authd: INFO: Agent '1677' key already exists on the manager.
2022/02/08 09:02:42 wazuh-authd: INFO: New connection from BALANCER_IP
2022/02/08 09:02:42 wazuh-authd: INFO: Received request for a new agent (AGENT_NAME_2) from: BALANCER_IP
2022/02/08 09:02:42 wazuh-authd: INFO: Duplicate name 'AGENT_NAME_2' (1693).
2022/02/08 09:02:42 wazuh-authd: INFO: Agent '1693' key already exists on the manager.
2022/02/08 09:02:42 wazuh-authd: INFO: New connection from BALANCER_IP
2022/02/08 09:02:42 wazuh-authd: INFO: Received request for a new agent (AGENT_NAME_3) from: BALANCER_IP
2022/02/08 09:02:42 wazuh-authd: INFO: Duplicate name 'AGENT_NAME_3' (1668).
2022/02/08 09:02:42 wazuh-authd: INFO: Agent '1668' key already exists on the manager.
2022/02/08 09:02:42 wazuh-authd: INFO: New connection from BALANCER_IP
2022/02/08 09:02:42 wazuh-authd: INFO: Received request for a new agent (AGENT_NAME_4) from: BALANCER_IP
2022/02/08 09:02:42 wazuh-authd: INFO: Duplicate name 'AGENT_NAME_4' (1664).
2022/02/08 09:02:42 wazuh-authd: INFO: Agent '1664' key already exists on the manager.
2022/02/08 09:02:42 wazuh-authd: INFO: New connection from BALANCER_IP
2022/02/08 09:02:42 wazuh-authd: INFO: Received request for a new agent (AGENT_NAME_5) from: BALANCER_IP
2022/02/08 09:02:42 wazuh-authd: INFO: Duplicate name 'AGENT_NAME_5' (1666).
2022/02/08 09:02:42 wazuh-authd: INFO: Agent '1666' key already exists on the manager.
2022/02/08 09:02:44 wazuh-authd: INFO: New connection from BALANCER_IP
```
Also we see bunch of such errors too:
```
2022/02/08 09:05:19 wazuh-remoted[4244] manager.c:842 at c_files(): DEBUG: Couldn't add multigroup 'default,windows,prod' to hash table 'm_hash'
```
As we discovered for some reason all created groups have similar checksum (see attached screenshots). It is actual for Wazuh 4.2.5 nd not actual for old Wazuh 3.13.1 we still have in use.
Just before the failure we add a bunch of different groups and add agents to it. This error from log was also discovered on every Worker node we have. We delete all groups on Master, and error disappear on Master node, but do not disappear on Worker nodes. Is it normal? Can it be the reason for failure?
Can we clear it somehow everywhere? We restarted all cluster several times after clening groups from Master node. Is it cached somewhere in Wazuh DB?

For now any new agent trying to register, have registration and works as service, but cannot connect to any 1514 and have Never connected state.

[agent_cleaned.log](https://github.com/wazuh/wazuh/files/8024266/agent_cleaned.log)
![wazuh_4](https://user-images.githubusercontent.com/49118755/153000374-ac4d8230-0b43-407e-8ac9-e3c0db25ca2a.png)
![wazuh_3](https://user-images.githubusercontent.com/49118755/153000380-cd190f63-2b60-4f19-be13-c86d7f3cf6e7.png)

**Comment by palaciosjeremias** [comment]
Hello @hantiger,
It was identified that the [bug ](https://github.com/wazuh/wazuh/issues/11485) I shared with you can be reproduced in the short term, and is not only occuring on environments with big amount of agents and packages.
The issue occurs exactly as you mention: After an agent restart is when the agent and manager package counter mismatch due to the overflow, leading to the manager droping the agent packages. And this lead to the agent disconnection.
Restarting the manager is a way to bypass this situation.
As I mention, this fix was targeted directly to 4.3 because it will be formarly released shortly.
Were you able to move to this version? (It will require an installation by source code ([link](https://documentation.wazuh.com/current/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-server/index.html)).)

**Comment by palaciosjeremias** [comment]
Hello @mark260486,
This seems to be a different issue. Do you agree if we handle it in a separate issue to keep this one clean with the original problem?
Meanwhile: I observe that the logs from the worker manager shows that the agent key is being generated on each request, while the master logs shows that the key isn´t being generated because the agent already exists on the manager (as expected). This logs differ on time, can we check if this is occurring on the same time too? Because it looks like your worker manager is connected to a different master manager. Is this possible?

Regarding the `Couldn't add multigroup 'default,windows,prod' to hash table` log, this is expected. Remoted periodically updates a hash table with groups, if the group is already updated, it isn´t re-inserted and this DEBUG log is generated.

The cluster logs with messages like `Error in synchronization process ` aren´t expected and they must be the reason of the imposibility of synchronizing the agents' keys and unchains the rejection of the newly registered agents.
Can you execute the following command on the master to check the cluster health?
`/var/ossec/bin/cluster_control -i more`
Also, can you collect and share with us the complete **cluster.log** file for further investigation?

If you open a new issue, please let me know about it and I can follow up with it.

Best regards.

**Comment by hantiger** [comment]
@palaciosjeremias 
Thank you for your reply. First, I will use the source code to conduct installation test and observe to confirm whether there will be other problems.
Thank you very much for your support!

**Comment by mark260486** [comment]
Hi, @palaciosjeremias ! Thanks a lot!
I created separate issue to not interrupt in this - https://github.com/wazuh/wazuh/issues/12126

**Comment by hantiger** [comment]
@palaciosjeremias There are no problems on my side for the time being. I haven't continued testing in the near future. I plan to continue testing after version 4.3 is officially released

**Comment by alyvusal** [comment]
@palaciosjeremias I also stopped testing. I will check also after upgrading

**Comment by hantiger** [comment]
@palaciosjeremias Except 4.2 Does this problem exist in other versions other than version x?

**Comment by palaciosjeremias** [comment]
Hello @hantiger,
This is a legacy problem that exist since Wazuh 3.9. It seems that is more reproducible now but we haven´t identified the reason.

**Comment by palaciosjeremias** [comment]
@mark260486, @alyvusal, @hantiger, we are closing this issue now. If you have further doubts, you can re-open it.
Best regards.
