### ISSUE TITLE
Analyze the feasibility of migrating the groups management made by the `shared_download` module within the `wazuh-db` daemon

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#11592]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/10771, we are migrating the information saved in the `agent-group` files to the `global.db` in the Wazuh DB module. As the `shared_download` module is one of the modules that could set information related to the groups to with an agent is assigned, we should evaluate how it will work now.

One of the approaches that we thought it is to migrate some of the actions taken by the `shared_download` module to Wazuh DB. This would include:

- Migrating the `shared_download` module to Wazuh DB.
- Migrate the `shared_download` settings and add a new one to enable or disable it.
- Create a thread within Wazuh DB that will run only if the module is active.
- The thread will periodically look for files and if it finds them, it will add the information to the database.
- The hash table used by the shared download in `remoted` should be deprecated.
- The daemons that could set groups information, should do it only if the `shared_download` module is disabled.

As part of this issue, we should evaluate the feasibility of implementing these changes.

**Comment by san1526** [comment]
Wazuh currently has the capability of using [Centralized configurations](https://documentation.wazuh.com/current/user-manual/reference/centralized-configuration.html). To setup this configurations the docs point to use a `files.yaml` file which describes how this feature is set up. The yaml file contain a list of config files that belong to a group, the 'interval' on which each group should be poll to download new configs and lastly a list of agents assigned to groups. This last list is the issue here as it can 'stomp' on the already assigned groups in the db at any moment when the yml changes.

The original idea was to try to separate the reading of the yaml and updating of the agent groups to the `wb_database` module and let remoted just query the database to get the groups always (instead of a mix of yaml and db).  After some investigation this does not seem possible without some extensive rework of how the yaml is read and where the configs are downloaded.

Currently remoted has a '[shared_download](https://github.com/wazuh/wazuh/blob/master/src/remoted/shared_download.c)' module but this module only does the reading/parsing of the yaml and creates the folders in `shared` for the groups mentioned in the file as well as creating a hashmap with the information read from the file (config files and groups). Is important to note that this module does not download the configs itself but rather just has the info.

Remoted will make use of this module and the info that parses inside a [thread](https://github.com/wazuh/wazuh/blob/master/src/remoted/manager.c#L1331) that looks for that file update on a configured interval and kicks off the rest of the process for the shared configs.
Inside the `c_files` it will call two functions called [c_groups](https://github.com/wazuh/wazuh/blob/master/src/remoted/manager.c#L316) and `c_multigroups` that will actually make use of the parsed info from the yaml (by calling `w_parser_get_group`) to actually make the config downloads and merge them if the option is set. They will also update the `f_sum` with the md5 of the downloaded (and merged) config to later send that information to the agents. This depends also on `shared_download` previously creating the corresponding folders for the configs to be downloaded in or else the download will fail.

A special case for the multigroup part is that `shared_download` _will not_ create the folder structure for multigroups but instead `c_files`[ will do that ](https://github.com/wazuh/wazuh/blob/master/src/remoted/manager.c#L882) and it will call `c_multigroups` that will use the downloaded configs from c_groups and will also [call](https://github.com/wazuh/wazuh/blob/master/src/remoted/manager.c#L654) `c_groups` again to do fill the s_sum data

All of this crossed dependencies in the code makes it so that if we want to move `shared_download` we have two possibilities. Extract all the reading of the yaml and downloading of the  shared configs into a separated module and let remoted just poll for existing configs and fill the `f_sum` structure that it needs with hashes periodically, which will require extensive rewrite of the current code. 
The other option is just try to extract the parsing of the 'agents' (and the groups assigned to them) to the database module. Currently that information is used by remoted in [lookfor_agent_group](https://github.com/wazuh/wazuh/blob/master/src/remoted/manager.c#L1051) and its changed to update the db with the information read. The downside with this approach is that we would be reading and parsing the yaml file from two different modules which would lead to ~some~ code duplication and could lead to more coupling later as two diffrerent modules would 'own' the same file.

**Comment by DProvinciani** [comment]
With the analysis exposed in the previous comment, we close this issue.
