### ISSUE TITLE
Add windows process start_time

### ISSUE THREAD

**Issue by LubinLew** [wazuh/wazuh#11641]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.4.0|syscollector | Agent | Sources | Windows |

## Description

Hi,

This is a PR https://github.com/wazuh/wazuh/pull/11640 to add windows process start_time.
Please review it.

Thanks.

**Comment by Dwordcito** [comment]
Hi @LubinLew 

It is good to have this data, since in our roadmap it is that the data provider feeds kernel events and the process creation time is a key, since windows do reuse PID.

@jnasselle please follow the next DoD to merge this.

# DoD
- [ ] Validate change.
- [ ] Manual e2e
- [ ] Add/change unit test.
- [ ] RTR Pass
