### ISSUE TITLE
An important part of Debian packages come without evaluable condition in its OVAL

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#1169]
The OVAL file has some entries like this:

```
    <dpkginfo_state id="oval:org.debian.oval:ste:7562" version="1" xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#linux">
      <evr datatype="evr_string" operation="less than">0:0</evr>
    </dpkginfo_state>
```

This means that the package versions cannot be checked against 0, and debug messages like the following will appear:

`2018/08/28 10:35:06 wazuh-modulesd:vulnerability-detector: DEBUG: (5467): The 'gcc-4.9' package from agent 5 is vulnerable to CVE-2017-11671. Condition: package version (4.9.2-10+deb8u1) less than 0:0.`

In other words, packages that are checked with 0:0 are marked as non-vulnerable.

**Comment by JcabreraC** [comment]
This problem has been solved in the next version, which will be released soon.

This version has a new vulnerability detection engine more robust, reliable, and complete. Within it, the version comparator has been improved so that these bugs cannot happen.

Check out our channels to keep updated about new features.
