### ISSUE TITLE
Is it possible to allert when wazuh agent disconnected ?

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh#1171]
I noticed that when ever ossec or maybe wazuh agen started, there is an alert that were produce. But there is no information when wazuh agent disconnected from wazuh alert, only in wazuh monitoring. Is it possible to alert when wazuh agent disconnected or connected from wazuh aler t index ?

**Comment by jesusgn90** [comment]
Hi @gagantous ,

We are generating alerts once the agent is disconnected and the Wazuh manager advices it. Take a look at this rule (https://github.com/wazuh/wazuh-ruleset/blob/a49a09fef7c3b7ad692b5002f015776a4e286bc0/rules/0015-ossec_rules.xml#L41):

```xml
  <rule id="504" level="3">
    <if_sid>500</if_sid>
    <options>alert_by_email</options>
    <match>Agent disconnected</match>
    <description>Ossec agent disconnected.</description>
    <group>pci_dss_10.6.1,pci_dss_10.2.6,gpg13_10.1,gdpr_IV_35.7.d,</group>
  </rule>
```

Now take a look at this alert that I've just generated:

```js
{
"timestamp":"2018-08-28T15:24:32.974+0000",
"rule":{"level":3,"description":"Ossec agent disconnected.","id":"504","firedtimes":1,"mail":true,"groups":["ossec"],"pci_dss":["10.6.1","10.2.6"],"gpg13":["10.1"],"gdpr":["IV_35.7.d"]},
"agent":{"id":"000","name":"localhost.localdomain"},
"manager":{"name":"localhost.localdomain"},
"id":"1535469872.69237","cluster":{"name":"wazuh","node":"node01"},"full_log":"ossec: Agent disconnected: 'jesus-msi-192.168.1.65'.","decoder":{"name":"ossec"},"predecoder":{"hostname":"localhost"},"location":"ossec-monitord"
}
```

From the `alerts.log`:
```
Rule: 504 (level 3) -> 'Ossec agent disconnected.'
ossec: Agent disconnected: 'jesus-msi-192.168.1.65'.
```
The main key here is that an agent disconnected alert is generated once the Wazuh manager review the keep alives from the agents, so it could take about __30 minutes__ after the agent was disconnected. That's why you are not seeing it just after disconnecting the agent.

I hope it helps, regards!

**Comment by gagantous** [comment]
Thanks for the reply @jesusgn90 and confirmation!

**Comment by jesusgn90** [comment]
You are welcome @gagantous !

**Comment by thekozak** [comment]
Is there a way to receive the alert sooner than 30 minutes after?

**Comment by vikman90** [comment]
Hi @thekozak,

Yes, there is a way, although it currently requires recompiling the manager.

The manager considers an agent is disconnected when more than 30 minutes (1800 seconds) passed since the last agent's "notify" message.

You can change the waiting time modifying two parameters:
- The constant `DISCON_TIME`. https://github.com/wazuh/wazuh/blob/master/src/headers/defs.h#L90.
- The value of `limit_seconds` in the framework: https://github.com/wazuh/wazuh/blob/master/framework/wazuh/common.py#L97

Please note that agents use the option `<notify_time>` to set the interval between "notify" messages. The default value has changed between versions:
- 600 seconds (10 minutes) in OSSEC, Wazuh 1.x and Wazuh 2.x.
- 60 seconds (1 minute) from Wazuh 3.0 to 3.3.
- 10 seconds from Wazuh 3.4 to the current version (3.6).

On the other hand, the manager is checking the agent status every 2 minutes: https://github.com/wazuh/wazuh/blob/master/src/monitord/monitord.c#L80.

So you can change the waiting time and recompile the manager. I suggest you set 120 seconds (2 minutes) as minimum. On the other hand,

**Comment by NitroCao** [comment]
> Hi @thekozak,
> 
> Yes, there is a way, although it currently requires recompiling the manager.
> 
> The manager considers an agent is disconnected when more than 30 minutes (1800 seconds) passed since the last agent's "notify" message.
> 
> You can change the waiting time modifying two parameters:
> 
> * The constant `DISCON_TIME`. https://github.com/wazuh/wazuh/blob/master/src/headers/defs.h#L90.
> * The value of `limit_seconds` in the framework: https://github.com/wazuh/wazuh/blob/master/framework/wazuh/common.py#L97
> 
> Please note that agents use the option `<notify_time>` to set the interval between "notify" messages. The default value has changed between versions:
> 
> * 600 seconds (10 minutes) in OSSEC, Wazuh 1.x and Wazuh 2.x.
> * 60 seconds (1 minute) from Wazuh 3.0 to 3.3.
> * 10 seconds from Wazuh 3.4 to the current version (3.6).
> 
> On the other hand, the manager is checking the agent status every 2 minutes: https://github.com/wazuh/wazuh/blob/master/src/monitord/monitord.c#L80.
> 
> So you can change the waiting time and recompile the manager. I suggest you set 120 seconds (2 minutes) as the minimum.
> 
> Hope it helps.
> Best regards.

Hi @vikman90, could you please help offer the two permanent links about `DISCON_TIME` and `limit_seconds`? Or how can I change the timeout in the latest version v4.1?
Another suggestion, can we make this option configurable?

**Comment by vikman90** [comment]
Hi @NitroCao,

Finally, the agent disconnection time margin is configurable: [`<agents_disconnectiontime>`](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#agents-disconnection-time) and [`<agents_disconnection_alert_time>`](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#agents-disconnection-alert-time).

Agents send a heart-beat to the manager every `<notify_time>` seconds. The new options, which work like the previous constant, define the following time margins:

- `<agents_disconnection_time>` sets the time span without receiving the agent's heart-beat to mark it as disconnected.
- `<agents_disconnection_alert_time>` sets an additional time spam since the agent was marked as disconnected to produce a disconnection alert.

For instance, the default configuration is:
```xml
<agents_disconnection_time>20s</agents_disconnection_time>
<agents_disconnection_alert_time>100s</agents_disconnection_alert_time>
```

That means that the API and the Kibana App will show the agent as disconnected when it failed to send a heart-beat for more than 20 seconds. If the agent still does not connect for 100 more seconds (2 minutes in total), the manager will produce an agent disconnection alert.

Bear in mind that `<agents_disconnection_time>` (in the manager) must be greater than `<notify_time>` (in agents), otherwise, the agents' status will be continuously fluctuating.

Hope that helps.

**Comment by NitroCao** [comment]
Thanks for your help @vikman90, I'll try it later.

**Comment by vikman90** [comment]
@NitroCao I'm glad to help you. Let me close this issue as it's answered. Should you have further questions or run into any trouble, please reopen it.

Best regards.
