### ISSUE TITLE
POC: improve the data transfer mechanism between `wazuh-db` and the clients

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#11729]
### Description

The `wazuh-db` daemon exposes a socket as an interface for the clients that want to query the databases that it manages. This socket has a strict limit of data to be transferred from `wazuh-db` to the clients as a response.

The limit for the data size defined in `wazuh-db` lead us multiple times to implement a mechanism to allow the clients to request the daemon the remaining data that it wasn't able to transfer through the socket.

As part of this POC, we should implement a new and generic mechanism to transfer data between `wazuh-db` and the clients without having a limit, but in some ways, taking care of the system resources to avoid high memory consumption having at the same time a good performance.

**Comment by san1526** [comment]
Currently in Wazuh the mechanism to do IPC mainly consist in opening a socket at the moment a daemon want's to do some communication
with another component, send a single request and wait for the response of the other side blocking the execution of the program until it arrives.
On the other side, any application that needs to work as a server basically opens a thread and wait for connections on in to be able to serve the requests with a select/poll call. Examples of this can be seen in the Wazuh-db (wazuh_db/main.c) or Wazuh-authd (os_auth/local-server.c)

Not having a set way to wrap the server/client behavior for IPC communication creates some problems:
- There's no standard way to manage server/client connections. Although both examples mentioned above have _similar_ code to handle server connection they are not exactly the same, creating more maintenance burden and 'cognitive load' as each component implements their own client/server format.
- Limits the size of the data sent to the max a single write call accepts (configured to 65kb currently). This creates multiple issues in itself. Performance can be a concern in many cases when you need to ask for 'large' datasets (like asking for agent's information when you often have a list of ids to ask) because you need to ask for them one at the time, and is made even worse by the fact that some daemons (like monitord for example) will fully open/connect/send/recv/close on _every_request that it needs to do making much more context switches to kernel than really needed.
Moreover there's some data can already be bigger than 65kb so the wazuh-db implements a basic chunking mechanism for a set of queries which complicates the code even more. You have to know beforehand which are the calls that are going to be chunked, and have to add the special de-chunking code on the receiving end. Without this calls documented or previous knowledge of the code you have to read one by one to know which query will receive a chunked response an which ones won't.
- There's no standard reconnect/timeout/message dropping mechanisms, each daemon manages it in their own way.

**Comment by san1526** [comment]
A POC implementation can be checked out at https://github.com/wazuh/wazuh/tree/dev-ipc-poc

**Comment by san1526** [comment]
The stand-alone implementation can also be seen in
[ipc.tar.gz](https://github.com/wazuh/wazuh/files/7849267/ipc.tar.gz)
