### ISSUE TITLE
Vulnerabilities Detector explain 

### ISSUE THREAD

**Issue by themeswordpress** [wazuh/wazuh#11750]
Dears,

Hope all is well.

Can you explain how the Vulnerabilities detector works I mean after getting the installed package from the agent what wazuh exactly do ? In technical level and how use this packages in nvd database.

Thank you for helping me

**Comment by DProvinciani** [comment]
Hi @themeswordpress ! Thanks for using Wazuh!

Some time ago, I wrote the next blog post https://wazuh.com/blog/detecting-vulnerable-software-on-linux-systems/. In this blog post, I explain in detail how the Vulnerability Detector module works correlating the next three sources of data to trigger CVE alerts:

- The data related to the inventory of packages installed on the endpoint.
- The data related to the vulnerabilities that affect the packages provided by the different OS vendors.
- The data related to the vulnerabilities that affect the packages provided by the VND.

I suggest you read this blog post, especially the **Analysis workflow** section, and share with me all the particular questions that you may have.

I'll be waiting for your comments. Thanks!

**Comment by themeswordpress** [comment]
Hey Boss,

amazing thank you for your blog, but what about Microsoft how you can know that this cve-xxxxxx effected this win 10 or not and if patched or not ? can you provide me the exactly code can do this step??

**Comment by themeswordpress** [comment]
@DProvinciani

**Comment by DProvinciani** [comment]
Hi @themeswordpress , sorry because of the delay in the response.

Well, the process is more or less the same. Basically, the Vulnerability Detector module will query the NVD database looking for all the particular CVEs that affect the Windows version that is being scanned. After having the list it will evaluate whether the CVEs are patched by taking into account the list of installed Hotfixes.

In order to know which CVEs are fixed by each Windows hotfix, Wazuh generates the Microsoft Software Update feed (also known as MSU) by getting information from Microsoft. You can check the MSU file [here](https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.json.gz).

Going now to the code, the kick-off for a Windows system scan starts [here](https://github.com/wazuh/wazuh/blob/master/src/wazuh_modules/vulnerability_detector/wm_vuln_detector_nvd.c#L1816). Then it will take information from the database based in the CPE of the operating system [here](https://github.com/wazuh/wazuh/blob/master/src/wazuh_modules/vulnerability_detector/wm_vuln_detector_nvd.c#L1967). The next step will be to evaluate this information together with the hotfixes [here](https://github.com/wazuh/wazuh/blob/master/src/wazuh_modules/vulnerability_detector/wm_vuln_detector_nvd.c#L2101). The last step will be to report all the vulnerabilities [here](https://github.com/wazuh/wazuh/blob/master/src/wazuh_modules/vulnerability_detector/wm_vuln_detector_nvd.c#L2134).

I hope this could clarify your questions. Thanks!

**Comment by DProvinciani** [comment]
As the Vulnerability Detector workflow was explained, we close this issue.
