### ISSUE TITLE
many false postive  in vulnerability detector feature  

### ISSUE THREAD

**Issue by themeswordpress** [wazuh/wazuh#11761]
i got the following cve's however my server full patched and I updated it yesterday !!

23506 | CVE-2019-1182 affects Windows Server 2016 | 1
-- | -- | --
23506 | CVE-2019-1365 affects Windows Server 2016 | 1
23506 | CVE-2019-1384 affects Windows Server 2016 | 1
23506 | CVE-2020-0609 affects Windows Server 2016 | 1
23506 | CVE-2020-0610 affects Windows Server 2016 | 1
23506 | CVE-2020-0690 affects Windows Server 2016 | 1

**Comment by alromeros** [comment]
Hi @themeswordpress,

Thank you for opening this issue!

I've been doing some research about the vulnerabilities you've shared, and they seem to share a common, unexpected behavior: Each one of the hotfixes meant to solve these vulnerabilities on Windows Server 2016 seem to be deleted from **Microsoft**'s own **[catalog](https://www.catalog.update.microsoft.com)**, which conflicts with the information presented in their **[MSRC](https://msrc.microsoft.com)**.

Considering that these two are the sources used by Wazuh to determine Window's vulnerabilities, these inconsistencies tend to introduce unexpected behavior in the scan until they are solved.

You can find more information about these vulnerabilities and hotfixes in the next links:

[KB4512517](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4512517) for [CVE-2019-1182](https://msrc.microsoft.com/update-guide/en-US/vulnerability/CVE-2019-1182).
[KB4525236](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4525236) for [CVE-2019-1384](https://msrc.microsoft.com/update-guide/en-US/vulnerability/CVE-2019-1384).
[KB4540670](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4540670) for [CVE-2020-0609](https://msrc.microsoft.com/update-guide/en-US/vulnerability/CVE-2020-0609).
[KB4534271](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4534271) for [CVE-2020-0610](https://msrc.microsoft.com/update-guide/en-US/vulnerability/CVE-2020-0610) and [CVE-2020-0690](https://msrc.microsoft.com/update-guide/en-US/vulnerability/CVE-2020-0690).

Since they are no longer available in the catalog, your system probably lacks the hotfixes specified by the **MSRC**, which conflicts with the information present in our most recent  **MSU** feed. That said, we hope that once our **MSU** feed is updated next Wednesday, this inconsistency will be solved in your scan.

One last thing! I've also noticed that [CVE-2019-1182](https://nvd.nist.gov/vuln/detail/CVE-2019-1182) seems to be under reanalysis by the NVD, as specified by their own website:

>Modified
>This vulnerability has been modified since it was last analyzed by the NVD. It is awaiting reanalysis which may result in further changes to the information provided.

So this behavior might be related to the recent lack of hotfixes in Microsoft's catalog.

That said, we'll keep you updated if we find something relevant and, in the meantime, we hope that your vulnerabilities will be correctly displayed after our **MSU** feed is updated next Wednesday. 

Hope that helps!

**Comment by jareddewitt** [comment]
I'm seeing the same behavior with these CVEs.  I don't believe this issue is resolved.  Can we please open it up and reinvestigate?
