### ISSUE TITLE
Vulnerability Detector memory increase during stress tests

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#11773]
|Related issues|
|---|
|https://github.com/wazuh/wazuh/issues/11679|
|https://github.com/wazuh/wazuh/issues/11661|
|https://github.com/wazuh/wazuh/issues/11314|

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0-rc2 | Vulnerability detector | Manager | Sources | Linux |

## Description

Hi team!

In the results of the Footprint metrics (which are part of the Release Candidate Protocol), an unexpected result was found. It is that the _RSS_ memory grows substantially in periods of approximately _6-8_ hours, coinciding with the memory leak behavior.

This behavior was observed in several stress tests:
- https://github.com/wazuh/wazuh/issues/11679

![image](https://user-images.githubusercontent.com/37207742/148944384-d51fabd3-5eb7-4b6c-9734-f4fa411c5412.png)

- https://github.com/wazuh/wazuh/issues/11661

![image](https://user-images.githubusercontent.com/37207742/148944337-978fed21-d085-450e-85cd-b7b5fccb1305.png)

- https://github.com/wazuh/wazuh/issues/11314

![image](https://user-images.githubusercontent.com/37207742/148944306-ae6ebc71-1c9a-4711-ab59-26c86ef0201f.png)

Also, it may be related to issue #11305.

**Comment by MarcelKemp** [comment]
**_Update_**

To contrast the information found in the Footprint tests, several builds with different parameters have been executed to solve the problems when scanning the agents and debugging the code to limit the memory problem:

- [Build 2902](https://ci.wazuh.info/view/Tests/job/Test_stress/2902/) [4.2.5][VULNERABILITY-DETECTOR][24h]. Custom configuration using the same time `intervals` as in the 4.3.0 tests, and offline configuration `<os url>`.
- [Build 2903](https://ci.wazuh.info/view/Tests/job/Test_stress/2903/) [4.3.0-rc2][VULNERABILITY-DETECTOR][12h]. Stress test 4.3.0 with `DEBUG` active.
- [Build 2904](https://ci.wazuh.info/view/Tests/job/Test_stress/2904/) [4.3.0-rc2][VULNERABILITY-DETECTOR][12h]. Stress test 4.3.0 with the _buffer fix for agent synchronization_.
- [Build 2905](https://ci.wazuh.info/view/Tests/job/Test_stress/2905/) [4.3.0-rc2][VULNERABILITY-DETECTOR][18h]. Stress test with the _agent sync fix_ and active `DEBUG`.

With the stress tests performed, the memory leak seems to be found in the feed parse, although the cause is not yet known...

**Comment by alromeros** [comment]
**#11773 update:**

Hi team,

After performing intensive testing and executing the builds described in the previous comment, we have come to reach several conclusions regarding the memory leak described in this issue.

Currently, our main conclusions are:

- Though the configuration used for each test seems to contrast with this timing, **the memory leak seems to be always occurring between periods of 6-8 hours**. We have yet to identify the cause of this behavior.
- **The permanent increase in memory seems to be happening during the feed-parsing process**, instead of the vulnerability scan. As seen in builds [2907](https://ci.wazuh.info/view/Tests/job/Test_stress/2906/) and [2908](https://ci.wazuh.info/view/Tests/job/Test_stress/2907/), the memory leak is missing in tests centered around the vulnerability scan, while it's always been present in tests centered around the feed-parsing process, leaving us to discard a large amount of code as part of the problem.
- **The memory leak is not present when scanning _Canonical_ and _NVD_ feeds**, as seen in [2908](https://ci.wazuh.info/view/Tests/job/Test_stress/2908/). This leads us to discard several functions and code that is exclusive to the parsing process of these feeds, meaning that the leak will likely be found in specific functions for other vendors. Subsequent tests have just been launched to test if the leak is present when activating only each one of the remaining vendors.
- Though not as prominent as in other tests, **build [2906](https://ci.wazuh.info/view/Tests/job/Test_stress/2906/) presents a memory increase that could contradict our theory about the leak being in the feed-scanning process**.
- **The memory leak seems to be present also in v4.2.5**. Following build [2910](https://ci.wazuh.info/view/Tests/job/Test_stress/2910/), the permanent memory increase can also be seen ~7 hours after the beginning of the scan, which leads us to discard the changes introduced in v4.3.0 as the source of the leak.

That said, we expect that the recently executed builds  [2913](https://ci.wazuh.info/view/Tests/job/Test_stress/2913/),  [2914](https://ci.wazuh.info/view/Tests/job/Test_stress/2914/) and  [2916](https://ci.wazuh.info/view/Tests/job/Test_stress/2916/) will allow us to define to which exact feeds are triggering the memory leak. We will update his issue with more information once we analyze the test results.

Best regards.

**Comment by MarcelKemp** [comment]
#11773 **_Update_**

In addition to the data mentioned above, a memory leak has been found after executing `valgrind` to custom feeds, to analyze the parsing of each OS. Specifically, the memory leak has been found in the MSU parser, where the memory of the `check_type` variable was not freed, thus causing memory increments each time the `w_tolower_str()` function was used within `wm_vuln_check_msu_type()`. This problem is only found in **_v4.3.0_**, because the changes that have caused the memory leak have been added for this version.

This memory leak is already fixed by the following PR: https://github.com/wazuh/wazuh/pull/11817

In addition, with the fix of the previous PR, a centos manager package has been generated to launch a new stress test and check the new results: [Build 2912](https://ci.wazuh.info/view/Tests/job/Test_stress/2912)

It is expected that there will be no memory spike except for the _6-8h_ one that also appears in _v4.2.5_.

We will update the issue as we obtain the results of the stress tests...

**Comment by MarcelKemp** [comment]
[#11773](https://github.com/wazuh/wazuh/issues/11773) _**Update**_

### List of stress tests:
- [Build 2908](https://ci.wazuh.info/view/Tests/job/Test_stress/2908): Run the **Ubuntu** feed on the **_4.3-no-fix_** branch (4.3-no-fix means it does not contain the fix mentioned above).
- [Build 2913](https://ci.wazuh.info/view/Tests/job/Test_stress/2913): Run the **Debian** feed on the **_4.3-no-fix_** branch.
- [Build 2914](https://ci.wazuh.info/view/Tests/job/Test_stress/2914): Run the **RedHat** feed on the **_4.3-no-fix_** branch.
- [Build 2916](https://ci.wazuh.info/view/Tests/job/Test_stress/2916): Run the **MSU** feed on the **_4.3-no-fix_** branch.
---
- [Build 2912](https://ci.wazuh.info/view/Tests/job/Test_stress/2912): Execution of **all feeds** in the **_4.3_** branch **_with_** the **_fix_** included.
- [Build 2918](https://ci.wazuh.info/view/Tests/job/Test_stress/2918): Execution similar to [2912](https://ci.wazuh.info/view/Tests/job/Test_stress/2912), but substituting all the `wazuh-modulesd` **`mallocs`** for those found in the **`jemalloc`** library ([link to the repository](https://github.com/jemalloc/jemalloc)).

### Conclusions:

In progress...

**Comment by chemamartinez** [comment]
We can confirm that the fixes solve the memory leak after the last [footprint test](https://github.com/wazuh/wazuh/issues/11917) for `4.3.0-RC3`.

![image](https://user-images.githubusercontent.com/29475387/150987429-73604957-4f08-4f35-8424-bd78c9e933e9.png)
