### ISSUE TITLE
Remove or deactivate extra-valid task

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#11787]
### Description

Since there are no more `agent-groups` files, we should investigate if it is necessary to keep the extra-valid files task which is part of the integrity task.

Currently, the only use of this extra-valid files task was the agent groups files, so we should investigate whether to remove or keep, although disabled, this functionality, which in the future may be useful.

https://github.com/wazuh/wazuh/blob/af0014f0f753bd1beb29afd985e1402aea95e1c5/framework/wazuh/core/cluster/worker.py#L540-L579

**Comment by yanazaeva** [comment]
## Issue update - List of deactivated functions

- In the [`cluster.py`](https://github.com/wazuh/wazuh/blob/master/framework/wazuh/core/cluster/cluster.py) file, we can find the following occurrence: 
https://github.com/wazuh/wazuh/blob/3f1d4aaf52d2fa82e1b55773d7c8d37014b47f46/framework/wazuh/core/cluster/cluster.py#L409-L429
In order to not modify the function, as it could be useful in the future, we will change `extra_valid` and `extra_valid_files` variables for underscores. Other variables were changes for placeholders, and comments were added indicating this. Also, the `extra_valid` key was removed from the following dictionary:
https://github.com/wazuh/wazuh/blob/3f1d4aaf52d2fa82e1b55773d7c8d37014b47f46/framework/wazuh/core/cluster/cluster.py#L451-L453

- In the [`cluster_control.py`](https://github.com/wazuh/wazuh/blob/master/framework/scripts/cluster_control.py) file, we find another reference to the `extra_valid` files:
https://github.com/wazuh/wazuh/blob/3f1d4aaf52d2fa82e1b55773d7c8d37014b47f46/framework/scripts/cluster_control.py#L147-L152
The `n_extra_valid` variable was removed along with the reference to it in `msg2`.

- In the [`worker.py`](https://github.com/wazuh/wazuh/blob/master/framework/wazuh/core/cluster/worker.py) file, we changed every mention to `extra_valid` and `agent-groups` for placeholders and named the no longer used variables with an underscore. Basically, the changes were made in two methods, the [`sync_extra_valid`](https://github.com/wazuh/wazuh/blob/3f1d4aaf52d2fa82e1b55773d7c8d37014b47f46/framework/wazuh/core/cluster/worker.py#L547) one and [`process_files_from_master`](https://github.com/wazuh/wazuh/blob/3f1d4aaf52d2fa82e1b55773d7c8d37014b47f46/framework/wazuh/core/cluster/worker.py#L588). 

- In [`master.py`](https://github.com/wazuh/wazuh/blob/master/framework/wazuh/core/cluster/master.py) file, we the [`sync_integrity`](https://github.com/wazuh/wazuh/blob/b75a070673ee6d4c0f27ea0e54c9e59f9fa7687c/framework/wazuh/core/cluster/master.py#L460) method.

**Comment by yanazaeva** [comment]
## Tes
[test_results.zip](https://github.com/wazuh/wazuh/files/8004362/test_results.zip)

## Test results

---
| | | | | | |
|--|--|--|--|--|--|
| **Test name** | **Pass** | **XFail/Skip** | **Fail** | **Issues Ref.** | **Status** |
| framework/wazuh/core/cluster/dapi/tests/test_dapi.py | 25 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/cluster/tests/test_cluster.py | 19 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/cluster/tests/test_common.py | 7 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/cluster/tests/test_control.py | 5 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/cluster/tests/test_local_client.py | 1 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/cluster/tests/test_utils.py | 7 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/cluster/tests/test_worker.py | 6 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_active_response.py | 14 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_agent.py | 142 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_cdb_list.py | 38 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_common.py | 7 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_configuration.py | 36 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_database.py | 13 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_decoder.py | 16 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_exception.py | 3 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_input_validator.py | 3 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_logtest.py | 2 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_manager.py | 15 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_mitre.py | 13 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_pyDaemonModule.py | 5 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_results.py | 40 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_rootcheck.py | 13 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_rule.py | 22 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_sca.py | 12 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_security.py | 12 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_stats.py | 12 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_syscheck.py | 7 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_syscollector.py | 3 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_task.py | 8 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_utils.py | 228 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_vulnerability.py | 1 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_wazuh_queue.py | 18 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_wazuh_socket.py | 20 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_wdb.py | 24 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_wlogging.py | 8 | 0 | 0 |  | :green_circle: |
| framework/wazuh/rbac/tests/test_auth_context.py | 2 | 0 | 0 |  | :green_circle: |
| framework/wazuh/rbac/tests/test_decorators.py | 105 | 0 | 0 |  | :green_circle: |
| framework/wazuh/rbac/tests/test_default_configuration.py | 55 | 0 | 0 |  | :green_circle: |
| framework/wazuh/rbac/tests/test_orm.py | 54 | 0 | 0 |  | :green_circle: |
| framework/wazuh/rbac/tests/test_preprocessor.py | 11 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_active_response.py | 12 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_agent.py | 117 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_cdb_list.py | 53 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_ciscat.py | 33 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_cluster.py | 7 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_decoder.py | 35 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_group.py | 8 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_logtest.py | 6 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_manager.py | 36 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_mitre.py | 7 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_rootcheck.py | 50 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_rule.py | 56 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_sca.py | 7 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_security.py | 73 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_stats.py | 7 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_syscheck.py | 25 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_syscollector.py | 12 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_task.py | 28 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_vulnerability.py | 31 | 0 | 0 |  | :green_circle: |
