### ISSUE TITLE
Review safe_move function usage in wazuh/manager.py and other functions

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#11803]
This issue reports a wrong behavior found when investigating issue #10931.

The issue aims to review the usage of `safe_move` in the `update_ossec_conf` function of `wazuh/manager.py`. In that function, the ownership parameter of the `safe_move` function must be used. Right now, we are using the default value of ownership (non-positional parameter) and the `ossec.conf` backup is always being copied with `wazuh:wazuh` ownership (its original ownership is `root:wazuh`).

The `safe_move` function is also used in other framework modules such as `cdb_list.py` or `core/agent.py`. We should also review all the `safe_move` occurrences to see if we are doing a good usage of the function.

This behavior was found due to a manual investigation. This means that the unit tests do not cover this case. We should add and modify the unit test to cover these cases and modify others properly.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by vicferpoy** [comment]
# Issue update

Development has been finished and all the manual testing has passed.

## Current code
### Wazuh API with root privileges

```shellsession
Original status

root@wazuh-master:/var/ossec/etc# ll ossec*
-rw-rw----. 1 root wazuh 8608 Feb 15 10:22 ossec.conf

Between the code execution

root@wazuh-master:/var/ossec/etc# ll ossec*
-rw-rw----. 1 root wazuh 8608 Feb 15 10:22 ossec.conf
-rw-r--r--. 1 root root  8608 Feb 15 10:24 ossec.conf.backup

Once an exception has been raised and we recover the ossec.conf using the backup

root@wazuh-master:/var/ossec/etc# ll ossec*
-rw-r--r--. 1 wazuh wazuh 8608 Feb 15 10:24 ossec.conf
```

## After the changes
### Wazuh API with root privileges

```shellsession
Original status

root@wazuh-master:/var/ossec/etc# ll ossec*
-rw-rw----. 1 root wazuh 8618 Feb 15 10:30 ossec.conf

Between the code execution

root@wazuh-master:/var/ossec/etc# ll ossec*
-rw-rw----. 1 root wazuh 8618 Feb 15 10:30 ossec.conf
-rw-rw----. 1 root wazuh 8618 Feb 15 10:30 ossec.conf.backup

Once an exception has been raised and we recover the ossec.conf using the backup

root@wazuh-master:/var/ossec/etc# ll ossec*
-rw-rw----. 1 root wazuh 8618 Feb 15 10:30 ossec.conf
```

As it can be seen, in comparison with the current code, both backup and the restored `ossec.conf` preserve file metadata.

### Wazuh API with default privileges

If the Wazuh API is not running as `root`, it cannot set the backup ownership to `root:wazuh` as it does not have permissions to do so. The main issue with this is that we are overwriting the original file with a backup file if anything goes wrong or if the content cannot be validated. If this is the case, the backup file will preserve all its metadata but the ownership, changing to `wazuh:wazuh` instead of `root:wazuh`:

```shellsession
root@wazuh-master:/# ll /var/ossec/etc/ossec.conf 
-rw-rw----. 1 root wazuh 8618 Feb 15 11:23 /var/ossec/etc/ossec.conf

After trying to update the content and raising an exception

root@wazuh-master:/# ll /var/ossec/etc/ossec.conf 
-rw-rw----. 1 wazuh wazuh 8618 Feb 15 11:23 /var/ossec/etc/ossec.conf

```

Ideally, the framework would simply validate the new content with the socket and THEN modify the original file. Related issues https://github.com/wazuh/wazuh/issues/3686, https://github.com/wazuh/wazuh/issues/3731.
