### ISSUE TITLE
Wazuh agent eps limit to 1000

### ISSUE THREAD

**Issue by truncet** [wazuh/wazuh#11813]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5 | EPS | Agent | Sources | Windows |

Hi,
I see that in buffer.c file , 
   =>  nanosleep(&ts_timeout, NULL);
is used in delay. 
If this is the case, why is there 1000 eps limit in wazuh.
I changed the restriction from 1000 to 2000 in buffer_config.c file and could achieve eps > 1200 in my windows agent.
Is there any reason 1000 is the limit as of now?

**Comment by Dwordcito** [comment]
Hi, @truncet I hope you are well!

Undoubtedly the upper level can be raised, I will discuss with the team to make this change. Understand that this change can cause the footprint to increase and there to be more congestion in the queues, since it makes use of calls to functions that are blocking, such as network calls.

I understand that this is discussed here, but I will refloat the subject.
https://github.com/wazuh/wazuh/issues/3766

**Comment by vikman90** [comment]
We're closing this issue as we will be working on a new communication mechanism: 
- https://github.com/wazuh/wazuh/issues/22677

Best regards.
