### ISSUE TITLE
 WARNING: (5500): The 'Red Hat Enterprise Linux 5/6/7/8' database could not be fetched on a machine with a slower network.

### ISSUE THREAD

**Issue by hustliyilin** [wazuh/wazuh#11814]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| master | Wazuh component | Manager | Packages | Centos 7.9 |

The `master branch` has a warning when enabling `vulnerability-detector` while the `v4.2.5` branch is ok.

```shell
2022/01/14 17:18:32 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Red Hat Enterprise Linux 5' database update.
2022/01/14 17:18:42 wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'Red Hat Enterprise Linux 5' database could not be fetched.
2022/01/14 17:18:42 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Red Hat Enterprise Linux 6' database update.
2022/01/14 17:18:52 wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'Red Hat Enterprise Linux 6' database could not be fetched.
2022/01/14 17:18:52 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Red Hat Enterprise Linux 7' database update.
2022/01/14 17:19:02 wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'Red Hat Enterprise Linux 7' database could not be fetched.
2022/01/14 17:19:02 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Red Hat Enterprise Linux 8' database update.
2022/01/14 17:19:13 wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'Red Hat Enterprise Linux 8' database could not be fetched.
2022/01/14 17:19:13 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'JSON Red Hat Enterprise Linux' database update.
```

Currently I can use the `v4.2.5` branch to work around this problem, but it would be better if the community can fix it in the `master` branch in the future, thanks.

**Comment by hustliyilin** [comment]
I changed to a machine with a faster network, and this problem is gone. So maybe the warning is about the machine network.  Is there a good way to solve this problem on a machine with a slower network? Thanks a lot.

**Comment by alromeros** [comment]
Hi, @hustliyilin 

Thank you for opening this issue!

The logic involved in the process for fetching vulnerability feeds hasn't changed from **v4.2.5** to **v4.3.0** (master) so, as you've proposed, I suspect that your error must be some kind of network-related issue. Mind that even the RHEL server could've been momentarily down during your vulnerability scan, so it'll be recommended to try downloading them again with your slower machine.

That said, Vulnerability Detector precisely includes a mechanism to avoid network issues with environments that are unable to download the feeds directly: The [Offline Update](https://documentation.wazuh.com/4.0/user-manual/capabilities/vulnerability-detection/offline_update.html) feature.

As explained in our documentation:

>If the manager does not have a direct connection to the Internet, it is possible to keep the vulnerability feeds updated by fetching the database files from your local environment or network. To achieve this, specific vulnerability files must be downloaded and Wazuh configured to locate them.

Since Red Hat vulnerabilities are fetched from two different sources, with both of them being necessary for the proper functioning of the scanner, the Offline Update should be configured to fetch offline both feeds: One OVAL file for each supported Red Hat version, and a JSON feed with global information of the affected packages for each distribution.

For more information about downloading the feeds and enabling _Offline Update_ for Red Hat feeds, you can check [our dedicated documentation](https://documentation.wazuh.com/4.0/user-manual/capabilities/vulnerability-detection/offline_update.html#red-hat).

At the end, the Red Hat provider block in your `ossec.conf` should closely resemble to one like this:

```xml
<provider name="redhat">
    <enabled>yes</enabled>
    <os path="/local_path/com.redhat.rhsa-RHEL5.xml.bz2">5</os>
    <os path="/local_path/rhel-6-including-unpatched.oval.xml.bz2">6</os>
    <os path="/local_path/rhel-7-including-unpatched.oval.xml.bz2">7</os>
    <os path="/local_path/rhel-8-including-unpatched.oval.xml.bz2">8</os>
    <path>/local_path/rh-feed/redhat-feed.*json$</path>
    <update_interval>1h</update_interval>
</provider>
```


Hope that helps! Let me know if you have more related questions.

**Comment by hustliyilin** [comment]
> the feeds

Hi, @alromeros 
Thank you very much for your detailed reply. I will download the CVE feeds of Red Hat on my slower network machine in advance and config the `/var/ossec/etc/ossec.conf` as you suggested above next week.  If the problem is solved by then, I will close this issue.

**Comment by hustliyilin** [comment]
Hi @alromeros 

I have another question. `Wazuh` can support to scan vulnerabilities on unsupported systems. When I configured the following fields on a machine with a slower network, I found that the newly added `os allow` configuration seemed to conflict with the `os path` in the `ossec.conf`.  Do you have any good solutions for this?

This is my configuration in `ossec.conf`.

```XML
    <provider name="redhat">
      <enabled>yes</enabled>
      <os path="/root/Redhat-cve-feeds/com.redhat.rhsa-RHEL5.xml.bz2">5</os>
      <os path="/root/Redhat-cve-feeds/rhel-6-including-unpatched.oval.xml.bz2">6</os>
      <os path="/root/Redhat-cve-feeds/rhel-7-including-unpatched.oval.xml.bz2">7</os>
      <os path="/root/Redhat-cve-feeds/rhel-8-including-unpatched.oval.xml.bz2">8</os>
      <path>/root/Redhat-cve-feeds/redhat-feed.*json$</path>
      <os allow="Centos Linux-7">7</os>
      <os allow="Centos Linux-8">8</os>
      <update_interval>1h</update_interval>
    </provider>
```

And the result is the following
- Redhat 5 and 6 CVE Feeds can be configured to fetch offline.
- **Redhat 7 and 8 CVE Feeds can't be configured to fetch offline because I add the `os allow`  configuration**.
 
```shell
2022/01/17 11:56:30 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'Red Hat Enterprise Linux 5' feed finished successfully.
2022/01/17 11:56:30 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Red Hat Enterprise Linux 6' database update.
2022/01/17 11:56:44 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'Red Hat Enterprise Linux 6' feed finished successfully.
2022/01/17 11:56:44 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Red Hat Enterprise Linux 7' database update.
2022/01/17 11:56:51 rootcheck: INFO: Ending rootcheck scan.
2022/01/17 11:56:54 wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'Red Hat Enterprise Linux 7' database could not be fetched.
2022/01/17 11:56:54 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Red Hat Enterprise Linux 8' database update.
2022/01/17 11:57:05 wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'Red Hat Enterprise Linux 8' database could not be fetched.
2022/01/17 11:57:05 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'JSON Red Hat Enterprise Linux' database update.
2022/01/17 11:57:06 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'JSON Red Hat Enterprise Linux' feed finished successfully.
2022/01/17 11:57:20 wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.
2022/01/17 11:57:20 wazuh-modulesd:vulnerability-detector: INFO: (5431): Starting vulnerability scan.
2022/01/17 11:57:20 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '000' vulnerabilities.
2022/01/17 11:57:20 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '000'
2022/01/17 11:57:20 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '001' vulnerabilities.
2022/01/17 11:57:20 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '001'
2022/01/17 11:57:20 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '002' vulnerabilities.
2022/01/17 11:57:20 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '002'
```

**Comment by alromeros** [comment]
Hi, @hustliyilin!

I'm glad my previous response was useful.

Regarding your last question, since both systems are built alike, Wazuh directly uses **Red Hat** feeds to scan **Centos** agents without additional tweaking, so you shouldn't worry about using the [allow](https://documentation.wazuh.com/4.0/user-manual/capabilities/vulnerability-detection/allow_os.html) feature when scanning **Centos** agents with **Red Hat** feeds. Your older configuration should work more than fine.

For more information about compatibility between agents and vulnerability feeds, you can check [this section](https://documentation.wazuh.com/4.0/user-manual/capabilities/vulnerability-detection/compatibility_matrix.html) of our documentation.

That said, if you'd ever want to scan other, non-supported OS with Red Hat feeds with our [allow](https://documentation.wazuh.com/4.0/user-manual/capabilities/vulnerability-detection/allow_os.html) feature , such as **Oracle Linux**, you could do it by merging the two tags in the same configuration line, as shown in this next example:

```xml
    <provider name="redhat">
      <enabled>yes</enabled>
      <os allow="Oracle Linux-7" path="/var/ossec/rh-feed/rhel-7-including-unpatched.oval.xml.bz2">7</os>
      <path>/var/ossec/rh-feed/redhat-feed.*json$</path>
      <update_interval>1h</update_interval>
    </provider>
```

But, as I said, this shouldn't be necessary with **Centos** systems.

Hope that helps!

**Comment by hustliyilin** [comment]
> Hi, @hustliyilin!
> 
> I'm glad my previous response was useful.
> 
> Regarding your last question, since both systems are built alike, Wazuh directly uses **Red Hat** feeds to scan **Centos** agents without additional tweaking, so you shouldn't worry about using the [allow](https://documentation.wazuh.com/4.0/user-manual/capabilities/vulnerability-detection/allow_os.html) feature when scanning **Centos** agents with **Red Hat** feeds. Your older configuration should work more than fine.
> 
> For more information about compatibility between agents and vulnerability feeds, you can check [this section](https://documentation.wazuh.com/4.0/user-manual/capabilities/vulnerability-detection/compatibility_matrix.html) of our documentation.
> 
> That said, if you'd ever want to scan other, non-supported OS with Red Hat feeds with our [allow](https://documentation.wazuh.com/4.0/user-manual/capabilities/vulnerability-detection/allow_os.html) feature, such as **Oracle Linux**, you could do it by merging the two tags in the same configuration line, as shown in this next example:
> 
> ```
>     <provider name="redhat">
>       <enabled>yes</enabled>
>       <os allow="Oracle Linux-7" path="/var/ossec/rh-feed/rhel-7-including-unpatched.oval.xml.bz2">7</os>
>       <path>/var/ossec/rh-feed/redhat-feed.*json$</path>
>       <update_interval>1h</update_interval>
>     </provider>
> ```
> 
> But, as I said, this shouldn't be necessary with **Centos** systems.
> 
> Hope that helps!

Hi, @alromeros
Thank you very much for your detailed reply. I config the `/var/ossec/etc/ossec.conf` as you suggested above, this issue is fixed.
