### ISSUE TITLE
Difficulty in searching events due to the large amount of modifying Windows registries in relation to file modifications on Linux

### ISSUE THREAD

**Issue by mradaszewski92** [wazuh/wazuh#11871]
|Wazuh version|Component|
|---|---|
| 4.1.2| Wazuh FIM|

Hello Wazuh team,

For a long time I see a problem with the readability of the FIM-triggered event module from the elasticsearch level. First and foremost, the Windows server environment generates a much greater number of events (triggered by registry modifications, e.g. by automatic users) compared to Linux systems. I think
the ratio of 100,000 changes to Windows registries to 1,000 changes to Linux systems is a good example.

I think the solution to this problem would be to add another field in the FIM module that will distinguish the operating system the module is running on. Thanks to this, it will be easier to get out of such a large number of "hits" from the elasticsearch level and you will not miss any suspicious changes in Linux systems

**Comment by jotacarma90** [comment]
Hello @mradaszewski92
In order to improve the display of alerts in elastic, we have multiple tools that could help you:

- First of all, you could use the elasticsearch filter to better organize the display. There are classifications of rules by level, by ruleid, even by the number of agent to which they correspond, so that you could separate that Windows agent and that Linux agent to be able to see them independently. The classification by level could help you not to lose the most significant or urgent alerts.

- Apart from improving the alert visualization itself, another method could be to better specify the agent configuration in order to reduce the alert flooding that they generate. For example, if in your case you have too many Windows log alerts, you could use the configuration tools offered by the FIM module, they are very good options to have the alerts very customized to your personal interests. You can see them in our documentation, and ask any questions about them:
https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html

If you need more information or any help, don't hesitate to ask for it!
Greetings

**Comment by mradaszewski92** [comment]
case close, it was helpful :)
