### ISSUE TITLE
active response integration with ipabusedb

### ISSUE THREAD

**Issue by irfaanaikagjee** [wazuh/wazuh#11892]
Hello wazuh team,

Active response is a good feature to use. However, we have some clients which hesitates to implement it because clean IP may get blocked and it happened some times in our case. Is it possible to integrate active response with ipabusedb.com to check the reputation of the IP before blocking it? we know we can create a custom cdb list of malicious IP but it is not real time.

Thanking you in advance

Kind regards,
Irfaan

**Comment by chemamartinez** [comment]
Hi @irfaanaikagjee,

Sorry for the late response.

Could you tell me more about the fact of clean IPs are being blocked in your environments? IP addresses should not be blocked if they are specified in a black CDB list or in a rule explicitly. 

Unfortunately, right now custom CDB lists are the most simple way of achieving that goal without any development.

However, there exists a way to integrate [abuseipdb](https://www.abuseipdb.com/) with Wazuh to check for the reputation of reported IPs. We could create an integration as it already exists for [Virustotal](https://documentation.wazuh.com/current/user-manual/capabilities/virustotal-scan/index.html).

The most important requirement is that the service has an API to run queries to it, _abuseipdb_ meets that requirement (https://www.abuseipdb.com/api). Once we know that, we can create an integration as it is explained at [Integration with external APIs](https://documentation.wazuh.com/current/user-manual/manager/manual-integration.html).

Briefly, these are the steps you would have to follow to get your integration running:
1. Create a script that receives the alerts from the Analysis daemon's socket and run the query to the external API. [Here](https://github.com/wazuh/wazuh/blob/master/integrations/virustotal) you can see the one for Virustotal.
2. Obtain an API key from the external service
3. Add the needed configuration to the manager's ossec.conf
```xml
<!--Custom external Integration -->
<integration>
  <name>abuseIP</name>
  <level>10</level>
  <group>authentication_failures</group>
  <api_key>APIKEY</api_key>
  <alert_format>json</alert_format>
</integration>
```
You can apply all the filters you need to the configuration in order to forward the desired alerts. https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/integration.html#optional-filters

I hope this information helps!

**Comment by irfaanaikagjee** [comment]
Hello,

There is a new blog for its implementation. Thank you.

I close the case

**Comment by irfaanaikagjee** [comment]
https://wazuh.com/blog/detecting-known-bad-actors-with-wazuh-and-abuseipdb/

**Comment by dpinse** [comment]
Is there a way to preserve the data.srcip field? Active response firewall-drop gives an error "Cannot read 'srcip' from data". That field is missing and abuseipdb.source.srcip replaces it
