### ISSUE TITLE
[4.3.0][RC3] Windows agent Logcollector + Syscheck stops reporting on specific conditions

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#12036]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.3.0-RC3 | Unknown | Agent | Packages | Windows Server 2019 |

Hello,

We come from https://github.com/wazuh/wazuh/issues/11915, where we have observed that the Windows agent stops from reporting events to the manager with specific configuration and stress.
![image](https://user-images.githubusercontent.com/10661307/151790052-86b6de48-e272-447a-af06-be816956aaba.png)
After about one day and a half, the agent stops and, it only keeps working the manager connectivity.

We have taken a look at the log from the agent but, it seems to suddenly stop logging.
We could provide any requested data or relaunch the test with specific conditions to detect and fix such a problem.
The configuration and logs are stored on the main footprint issue.

We are trying to determine the given problem we could assume that the error comes from Syscheck or Logcollector due to this issue https://github.com/wazuh/wazuh/issues/11923 where the agent stops reporting sooner.
![image](https://user-images.githubusercontent.com/10661307/151791131-7dec2b3a-641a-4e92-bb75-3010eac4d552.png)

Any requests don't hesitate to ask!

**Comment by vikman90** [comment]
This bug is a regression caused by PR #11735 (4.3.0-RC2). It's located in function `get_registry_permissions()` at [syscheck_op.c](https://github.com/wazuh/wazuh/blob/3a833c142983b83081d8208a6cbbab0620178f1d/src/shared/syscheck_op.c#L1119-L1123).

In this case, [`RegGetKeySecurity()`](https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-reggetkeysecurity) is returning an error different from `ERROR_INSUFFICIENT_BUFFER`, which causes `get_registry_permissions` to return an error code by `GetLastError()` without allocating `output_acl`. Since the error was reported by `RegGetKeySecurity()`, `GetLastError()` returns `0` (no error). Thus, the caller (at [registry.c:465](https://github.com/wazuh/wazuh/blob/4df56e714374a2ecc7b686a9fa629223df0f50ea/src/syscheckd/registry/registry.c#L465)) gets `0` but `key->perm_json` remains NULL. This causes the agent crash at [registry.c:472](https://github.com/wazuh/wazuh/blob/4df56e714374a2ecc7b686a9fa629223df0f50ea/src/syscheckd/registry/registry.c#L472).

## Proposed fix

We simply need to call `RegGetKeySecurity()` like the second time: getting the return value as an error code.

## Evidences

We launched the following tests:

|Input|Fix|Result|Reference|
|---|---|---|---|
|Files + Registry keys|No|🔴|https://github.com/wazuh/wazuh/issues/11915#issuecomment-1025209665|
|Files|No|🟢|https://github.com/wazuh/wazuh/issues/11915#issuecomment-1025210370|
|Files + Registry keys|Yes|🟢|https://github.com/wazuh/wazuh/issues/11915#issuecomment-1025218751|

### Conclusions

- The bug is definitely located in the Windows Registry scan.
- The proposed fix got validated by the third test.
