### ISSUE TITLE
Any plans on supporting Multi-account Inspector2 with wazuh?

### ISSUE THREAD

**Issue by antonisnyc94** [wazuh/wazuh#12081]
Hello,

We have a mutli-account deployment of inspector, and I was wondering whether you'd going to support aggregated inspector data from multiple accounts as well as inspector2?

Thanks,
Tony

**Comment by noise-kngdm** [comment]
Hi!
We support fetching Inspector classic data from multiple accounts. For example, you could add this to your `ossec.conf` file to collect the findings of two different AWS accounts.

```
<wodle name="aws-s3">
  <disabled>no</disabled>
  <interval>1m</interval>
  <run_on_start>yes</run_on_start>
  <skip_on_error>yes</skip_on_error>
  <service type="inspector">
     <access_key>ACCESS_KEY_ACCOUNT_1</access_key>
     <secret_key>SECRET_KEY_ACCOUNT_1</secret_key>
  </service>
  <service type="inspector">
     <access_key>ACCESS_KEY_ACCOUNT_2</access_key>
     <secret_key>SECRET_KEY_ACCOUNT_2</secret_key>
  </service>
</wodle>
```
I added the access and secret keys to the configuration just for clarification, but you could use any of the other [AWS login methods](https://documentation.wazuh.com/current/amazon/services/prerequisites/credentials.html) explained in our documentation.

As for the second question, we are not currently planning on adding support for Inspector 2 soon since the team is focused on other priorities at the moment, but if there is demand for this integration we will study adding it. If you find it interesting, you could open a [feature request issue](https://github.com/wazuh/wazuh/issues/new?assignees=&labels=external_integrations&template=external-integrations.md&title=) for Inspector 2.

Also, since Wazuh is an open-source project, we are always open to add contributions from our community.

**Comment by noise-kngdm** [comment]
We're closing this issue because we got no answer in two weeks. Feel free to reopen it if you have any more doubts regarding this, @antonisnyc94.

**Comment by antonisnyc94** [comment]
@noise-kngdm  I managed to solve this by editing `aws-s3.py` and the current inspector module. I tried to create an inspector2 module of which we can define in ossec.conf but failed. Any idea how to do that?

**Comment by CarlosRS9** [comment]
I'm afraid that's not an easy task @antonisnyc94.

To add Inspector v2 compatibility to our AWS module it would not only be necessary to modify the `aws-s3.py` but also the Core code that parses the `ossec.conf` and invokes the module, which is written in C and involves among other things the recompilation and reinstallation of Wazuh.

You could try to modify the Inspector integration in `aws-s3.py` to completely replace it with Inspector v2, without having to update the C parser code, but it is still not an easy task and we cannot recommend it.

**Comment by antonisnyc94** [comment]
Hey @CarlosRS9,

I'd like doing it the proper way while also contributing to the project. Do you have any documentation you can direct me to by any chance?

Best
Tony
