### ISSUE TITLE
Investigate cpu and memory usage of modulesd and syscheckd modules in stress test

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#12093]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0-rc3 | Syscheckd/Modulesd | Agent | Packages | Centos 8 |

Analyzing the https://github.com/wazuh/wazuh/issues/12010 issue, I have found the following behavior in the centos agent plots

- CPU usage shows less syscheck usage during the first half of the Full Load stage (stress + scripts)
- Memory usage shows low usage of modulesd and a big surge 45 minutes after the syscheckd cpu change.
- There have been cases in which the start of the Full Load period is lower to a certain extent in a few tests, but it is suspicious that at almost the same instant of time, this sudden cpu/memory change is shown in these two modules
- CPU usage could have an explanation related to system resources, but modulesd's memory rise is too abrupt.

Syscheckd CPU usage:

![image](https://user-images.githubusercontent.com/14913942/152398796-15df54ce-d2ef-47bf-9747-ed31c8c10fdc.png)

Modulesd memory usage:

![image](https://user-images.githubusercontent.com/14913942/152398892-f8d6cfef-037d-4e54-bf78-bd92b6e33a3f.png)

Observing the PSS graph, it can be seen that syscheckd has more activity in the period in which its CPU usage is lower, which changes when modulesd memory goes up, where syscheckd decreases memory drops, even so, modulesd's memory rise is very abrupt.

![image](https://user-images.githubusercontent.com/14913942/152400144-d8965c43-f9de-4c61-a7bd-8aa73b45b5c5.png)

This memory change in modulesd could be similar to the one observed in the Ubuntu agent, where it can be seen as it goes down and then goes up to go down again, which in centos8 does not happen

![image](https://user-images.githubusercontent.com/14913942/152400597-81e2b0d6-15d4-48a9-bac6-44ed797d8ced.png)

**Comment by vikman90** [comment]
## Memory usage bump

This is due to a Syscollector scan:

```
2022/01/29 01:01:29 wazuh-modulesd:syscollector: INFO: Module started.
2022/01/29 01:01:29 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/01/29 01:01:29 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2022/01/29 13:01:29 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/01/29 13:01:31 wazuh-modulesd:syscollector: INFO: Evaluation finished.
```

In fact, the Syscollector scan interval is set to 12 hours.

## CPU usage behavior

I'm sure that is not related to the Syscollector scan as the high plateau we see in the Modulesd CPU usage happens about 30 minutes later. Such plateau corresponds perfectly to a rising slope of disk usage.

I guess this behavior is related to the CIS-CAT module, which performs disk writes when pre-parsing a result by the CIS-CAT tool. However, I have no data enough (mainly logs) to prove that.

### This test

- CPU:
![](https://user-images.githubusercontent.com/14913942/152398796-15df54ce-d2ef-47bf-9747-ed31c8c10fdc.png)
- Disk written:
![](https://camo.githubusercontent.com/25c4735e08ea93c7a925e421bc4fdbfc28396b7422ff3a78a0d044ef4ea0ad7a/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e332e302f42323938332d313434306d2f42323938335f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42323938335f63656e746f732d7072652d72656c656173655f4469736b5f5772697474656e2e706e67)

### Test with all components running

- Issue: #12026.
- CPU:
![](https://camo.githubusercontent.com/d12563c473e9e1eb21dedadc0575bbda810ff4180e708c4fe700f3c2259fff5f/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e332e302f42323937392d313434306d2f42323937395f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42323937395f63656e746f732d7072652d72656c656173655f4350552e706e67)
- Disk written:
![](https://camo.githubusercontent.com/bafa01bea040eed27641eb998fbfb781f1135c199085cff821abd204bd3463ce/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e332e302f42323937392d313434306d2f42323937395f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42323937395f63656e746f732d7072652d72656c656173655f4469736b5f5772697474656e2e706e67)

### 4.3.0-RC2

- Issue: #11667.
- CPU:
![](https://camo.githubusercontent.com/d8ae53a83f959490b64c04aa1a37ed5136913192fa0d5c036ebe6e5bdc6077be/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e332e302f42323334382d313434306d2f42323334385f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42323334385f63656e746f732d7072652d72656c656173655f4350552e706e67)
- Disk written:
![]()https://camo.githubusercontent.com/c13d8d3d67b583000d2daf4acb80fcdaec8ceaa8b1a08486978f21b0220d9ad7/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e332e302f42323334382d313434306d2f42323334385f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42323334385f63656e746f732d7072652d72656c656173655f4469736b5f5772697474656e2e706e67

### 4.2.4-RC2

- Issue: #10590.
- CPU:
![](https://camo.githubusercontent.com/f8826594aadd13102ae13d11b144ddeee2a51d2239a5a945a355ec07e7a2c7cf/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e322e342f42323538302d3732306d2f42323538305f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42323538305f63656e746f732d7072652d72656c656173655f4350552e706e67)
- Disk written:
- ![](https://camo.githubusercontent.com/54b9aa9c6bec0bca3100aab0c8ac8ac4d26bccaba959359381aaedb20ff696fe/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e322e342f42323538302d3732306d2f42323538305f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42323538305f63656e746f732d7072652d72656c656173655f4469736b5f5772697474656e2e706e67)
