### ISSUE TITLE
Analysis of the processing and use of disk in the generation of groups and multigroups

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#12110]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0 | wazuh-remoted | Manager | Packages/Sources | Linux |

### Description

According to https://github.com/wazuh/wazuh/issues/11054, a new mechanism will be developed to improve the efficiency of multigroup generation, reducing processing and disk usage.

The objective of this number is to generate benchmarks to justify the improvements introduced related to:

- Disk usage.
- Time of processing.

Two benchmarks needs to be created: 

- One before the implementation of the new mechanism (branch master).
- One after the implementation of the new mechanism (branch https://github.com/wazuh/wazuh/tree/dev-improve-multi-groups).

All the results will be uploaded to this issue.

**Comment by Nicogp** [comment]
# Test: Old multigroup mechanism

The goal of this test is to analyze the performance, in terms of time, of the old mechanism for creating groups and multigroups.

## Group folder with default agent.conf file

The following table shows the times measured for the different numbers of groups, in this first test the groups contain only the default agent.conf file

| N° of Groups | Time |
| ---- | --- |
| 10 | 0.045s |
| 20| 0.069s |
| 50| 0.073s |
| 150 | 0.097s |

## Group folder with files found in `shared/default` folder

The following table shows the times measured for the different numbers of groups, in this second test the files in the `ossec/etc/shared/default` folder were copied into each group folder

| N° of Groups | Time |
| ---- | --- |
| 10 | 0.368s |
| 20| 0.699s |
| 50| 1.361s |
| 150 | 3.473s |

## Groups + Multigroups

The following table shows the times measured for the different numbers of groups and multigroups, for this test we created multigroups containing the `default `group and 3 more groups

| N° of Groups + Multigroups | Time |
| ---- | --- |
| 10 groups | 0.368s |
| 20 groups | 0.699s |
| 50 groups | 1.361s |
| 150 groups  | 3.473s |
| 150 groups + 10 multigroups | 4.052s |
| 150 groups + 20 multigroups | 4.635s |
| 150 groups + 50 multigroups | 6.257s |
| 150 groups + 150 multigroups | 12.083s |

**Comment by Nicogp** [comment]
# Test: Disk writing: Comparison between the old and the new method

The purpose of this test is to analyze the disk write performance of the new multigroup creation method and compare it with the previous one.

For these tests we created an environment with the following characteristics
shared_reload=60 (Number of seconds between reloads of shared files).
Agent groups -> 150
Multigroup = default + 3 groups

In the following graphs we can see the comparison of both methods for each of the different test cases.
🟦 Old method
🟧 New method

## 10 Multigroups
![image](https://user-images.githubusercontent.com/13004400/153927225-7335c470-2a5e-4b47-a132-c859569dea3d.png)

[DiskStatus-10-multigroups.xlsx](https://github.com/wazuh/wazuh/files/8063225/DiskStatus-10-multigroups.xlsx)

## 50 Multigroups
![image](https://user-images.githubusercontent.com/13004400/153927667-88d57a68-1ec2-41b1-9925-5629d11b38d6.png)

[DiskStatus-50-multigroups.xlsx](https://github.com/wazuh/wazuh/files/8063242/DiskStatus-50-multigroups.xlsx)

## 150 Multigroups
![image](https://user-images.githubusercontent.com/13004400/153927812-3a3d1aa7-912c-464d-a6b4-06d9f32aa8c2.png)

[DiskStatus-150-multigroups.xlsx](https://github.com/wazuh/wazuh/files/8063249/DiskStatus-150-multigroups.xlsx)

## 500 Multigroups
For this test, the `shared_reload` time was increased to `120s`
![image](https://user-images.githubusercontent.com/13004400/153927938-19a23254-0c53-4a34-a9f8-37f2ae7d5e76.png)

[DiskStatus-500-multigroups.xlsx](https://github.com/wazuh/wazuh/files/8063261/DiskStatus-500-multigroups.xlsx)

## Conclusion
In all cases, we can see how the first time the multigroup files are created is similar in both methods, but once the files are created, in the following scans the new method has no disk usage because it only recreates the multigroup files if a file in a group has changed, while the previous method always regenerates all files.

**Comment by Nicogp** [comment]
# Test: Processing time: Comparison between the old and the new method

The purpose of this test is to analyze the processing time performance of the new multigroup creation method and compare it with the previous one.

For these tests we created an environment with the following characteristics
shared_reload=60 (Number of seconds between reloads of shared files).
Agent groups -> 150

The following table shows the times measured for the different numbers of multigroups, for this test we created multigroups containing the `default `group and 3 more groups

| N° of  Multigroups | Old method | New method - initial iteration | New method - next iterations | 
| ---- | --- | --- | --- |
| 10 multigroups | 4.052s | 5.035s | 3.049s |
| 50 multigroups | 6.257s | 7.094s | 3.701s |
| 150 multigroups | 14.044s | 13.296s | 5.592s |
| 500 multigroups | 76.207s | 70.892s | 12.753s |

## Conclusion
We can see how in the initial iteration the processing time of the new method is similar to the time of the old method, but in the following iterations a substantial improvement is noticed, achieving the following time reduction percentages

| N° of  Multigroups | Time reduction % | 
| ---- | --- |
| 10 multigroups | 24,74 % |
| 50 multigroups | 40,85 % |
| 150 multigroups | 60,18 % |
| 500 multigroups | 83,26 % |
