### ISSUE TITLE
macOS incorrect CPU information and non-transparent architecture values

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#12341]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.X | Data Provider | Agent | Packages/Sources | macOS |

# Description
It was found based on manual testing (@alberpilot ), that when running Wazuh (compiled as x86_64) on the new M1 MAC processors, strange and incorrect values ​​are reported.

![image](https://user-images.githubusercontent.com/14300208/154405804-364a6b8d-9f27-41cf-8068-93ffeea87537.png)

## Actual 
Arch: x86_64

## Expected
Arch: arm64

# DoD
- [x] ~Get Arch value from the file system, so that the virtualization of rosseta does not interfere.~
- [x] QA coverage. https://github.com/wazuh/wazuh-qa/issues/3009
- [x] PR CI Pass.

**NOTE**

Global.db agent information fix will be treated in https://github.com/wazuh/wazuh/issues/13897

**Comment by jnasselle** [comment]
Hi @Dwordcito ,

Expected CPU: Apple M1 seems to be wrong, since CPU field currently indicate the platform where Wazuh Agent is running on. Changing this to Apple M1 will cause to change already existing behavior.

On the other hand, retrieving machdep.cpu.brand_string during rosseta translation environment will retrieve x86_64 since Wazuh is only compiled in that architecture.
The only available way to check if we are running on arm64 over rosseta is using Apple proposal example https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment

This approach will need to be changed if, in the future:
- Rosetta translation layer support more than amd64 architecture
- Wazuh compiled natively on Apple's amd64
