### ISSUE TITLE
Agent IP is not being stored in global.db

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#12349]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5-40220 | Enrollment/Wazuh DB | Manager/Agent | Packages | CentOS 8 |

## Description

We have observed that there are two fields in the `agent` table in `global.db`:

- `ip`: stores the current IP of the agent when the agent was registered with IP "any"
- `registered_ip`: stores the IP with which the agent registers

Testing with a vagrant, we have seen that, although the agent registers with any or with an IP (172.17.1.12 in our case), the IP field is filled with the NAT IP (10.0.2.15). However, the agent and the manager are not communicating through that interface, what's more, if we drop that interface and restart, now the `ip` field will appear empty, and the communication between manager and agent is not affected.

I attach some examples of the keep-alive message and the `global.db`:

### NAT interface up

   **keep-alive message**

```
2022/02/17 11:45:43 wazuh-agentd[3574] notify.c:188 at run_notify(): DEBUG: Sending keep alive: #!-Linux |localhost.localdomain |4.18.0-348.2.1.el8_5.x86_64 |#1 SMP Tue Nov 16 14:42:35 UTC 2021 |x86_64 [CentOS Linux|centos: 8.5] - Wazuh v4.2.5 / ab73af41699f13fdd81903b5f23d8d00
2c45c95db2954d2c7d0ea533f09e81a5 merged.mg
#"_agent_ip":10.0.2.15
```

   **`global.db`**

   - Registered using "any" IP

```
[root@localhost vagrant]# sqlite3 /var/ossec/queue/db/global.db "SELECT * FROM agent"
0|localhost.localdomain|127.0.0.1|127.0.0.1||CentOS Linux|8.5|8|5|||centos|Linux |localhost.localdomain |4.18.0-240.1.1.el8_3.x86_64 |#1 SMP Thu Nov 19 17:20:08 UTC 2020 |x86_64|x86_64|Wazuh v4.2.5|||localhost.localdomain|node01|1645097952|253402300799||synced|active
1|centos_agent|10.0.2.15|any|58cf9c523cf1d88b981ecf9ca51ce2c149f738feee1c377bdafe052a84e0918a|CentOS Linux|8.5|8|5|||centos|Linux |localhost.localdomain |4.18.0-348.2.1.el8_5.x86_64 |#1 SMP Tue Nov 16 14:42:35 UTC 2021 |x86_64|x86_64|Wazuh v4.2.5|ab73af41699f13fdd81903b5f23d8d00|2c45c95db2954d2c7d0ea533f09e81a5|localhost.localdomain|node01|1645098113|1645098583|default|synced|active

```
  
   - Registered using "172.17.1.12" 

```
[root@localhost vagrant]# sqlite3 /var/ossec/queue/db/global.db "SELECT * FROM agent"
0|localhost.localdomain|127.0.0.1|127.0.0.1||CentOS Linux|8.5|8|5|||centos|Linux |localhost.localdomain |4.18.0-240.1.1.el8_3.x86_64 |#1 SMP Thu Nov 19 17:20:08 UTC 2020 |x86_64|x86_64|Wazuh v4.2.5|||localhost.localdomain|node01|1645097952|253402300799||synced|active
3|centos_agent|10.0.2.15|172.17.1.12|5519d7b77c29fabe19b1d664ebdc5fa9203a50f592af97e6ae6c53b89ce48957|CentOS Linux|8.5|8|5|||centos|Linux |localhost.localdomain |4.18.0-348.2.1.el8_5.x86_64 |#1 SMP Tue Nov 16 14:42:35 UTC 2021 |x86_64|x86_64|Wazuh v4.2.5|ab73af41699f13fdd81903b5f23d8d00|2c45c95db2954d2c7d0ea533f09e81a5|localhost.localdomain|node01|1645099819|1645099899|default|synced|active
``` 

### NAT interface down

   **keep-alive message**

```
2022/02/17 12:29:49 wazuh-agentd[27998] notify.c:188 at run_notify(): DEBUG: Sending keep alive: #!-Linux |localhost.localdomain |4.18.0-348.2.1.el8_5.x86_64 |#1 SMP Tue Nov 16 14:42:35 UTC 2021 |x86_64 [CentOS Linux|centos: 8.5] - Wazuh v4.2.5 / ab73af41699f13fdd81903b5f23d8d00
2c45c95db2954d2c7d0ea533f09e81a5 merged.mg
```

   **`global.db`**

   - Registered using "any" IP

```
[root@localhost vagrant]# sqlite3 /var/ossec/queue/db/global.db "SELECT * FROM agent"
0|localhost.localdomain|127.0.0.1|127.0.0.1||CentOS Linux|8.5|8|5|||centos|Linux |localhost.localdomain |4.18.0-240.1.1.el8_3.x86_64 |#1 SMP Thu Nov 19 17:20:08 UTC 2020 |x86_64|x86_64|Wazuh v4.2.5|||localhost.localdomain|node01|1645097952|253402300799||synced|active
2|centos_agent||any|987b5428ee9006192eb999ecdc25a68661d6b7cbb197eb40f8e06a552a4bdd52|CentOS Linux|8.5|8|5|||centos|Linux |localhost.localdomain |4.18.0-348.2.1.el8_5.x86_64 |#1 SMP Tue Nov 16 14:42:35 UTC 2021 |x86_64|x86_64|Wazuh v4.2.5|ab73af41699f13fdd81903b5f23d8d00|2c45c95db2954d2c7d0ea533f09e81a5|localhost.localdomain|node01|1645099160|1645099240|default|synced|active

```
  
   - Registered using "172.17.1.12" 

```
[root@localhost vagrant]# sqlite3 /var/ossec/queue/db/global.db "SELECT * FROM agent"
0|localhost.localdomain|127.0.0.1|127.0.0.1||CentOS Linux|8.5|8|5|||centos|Linux |localhost.localdomain |4.18.0-240.1.1.el8_3.x86_64 |#1 SMP Thu Nov 19 17:20:08 UTC 2020 |x86_64|x86_64|Wazuh v4.2.5|||localhost.localdomain|node01|1645097952|253402300799||synced|active
4|centos_agent||172.17.1.12|6a3e3fae66d8b0f23985f97795e476e0487a7fd0cfb2353e668c700f1ffc5055|CentOS Linux|8.5|8|5|||centos|Linux |localhost.localdomain |4.18.0-348.2.1.el8_5.x86_64 |#1 SMP Tue Nov 16 14:42:35 UTC 2021 |x86_64|x86_64|Wazuh v4.2.5|ab73af41699f13fdd81903b5f23d8d00|2c45c95db2954d2c7d0ea533f09e81a5|localhost.localdomain|node01|1645100019|1645100099|default|synced|active
```

**Comment by Damian-Mangold** [comment]
## Creating the environment to reproduce the error

To reproduce the error, the network configuration must have specific settings. The following images show the network settings:

![Screenshot from 2022-12-22 15-00-18](https://user-images.githubusercontent.com/106940255/209198458-7133f2b5-250c-45ad-a220-59b48171d437.png)
![Screenshot from 2022-12-22 15-00-58](https://user-images.githubusercontent.com/106940255/209198422-8d604b62-4722-4c19-8fc4-38f1fc23ad4d.png)
![Screenshot from 2022-12-22 15-01-43](https://user-images.githubusercontent.com/106940255/209198429-9fc3baae-ca27-41d7-81bf-54546b4cc2f7.png)



## Error analysis
Started analysis on wazuh-authd as it was suspected that the error could be generated during agent registration.
- [main-server.c](https://github.com/wazuh/wazuh/blob/4.4/src/os_auth/main-server.c) in line [#572](https://github.com/wazuh/wazuh/blob/4.4/src/os_auth/main-server.c#L572) of the `run_dispatcher` function, the IP of the agent is obtained correctly.
- In line [#629](https://github.com/wazuh/wazuh/blob/4.4/src/os_auth/main-server.c#L629) the IP value is replaced by any, since the agent does not set an IP address
- Agent registration ends and the database is not updated in this sequence.

Seconds after agent registration is finished, we can see information being written to the database.
```
4|centos-agent||any|077d4f46510662c51612aea54852dd895b90a350582840fca51ad7c9efa4b207||||||||||||||unknown|1671514909||||synced|synced|never_connected|0|not synced**
```
After waiting a few more seconds, we can see that the database is filled.
```
4|centos-agent|10.0.2.15|any|077d4f46510662c51612aea54852dd895b90a350582840fca51ad7c9efa4b207|CentOS Linux|8.4|8|4|||centos|Linux |centos-agent |4.18.0-305.12.1.el8_4.x86_64 |#1 SMP Wed Aug 11 01:59:55 UTC 2021 |x86_64|x86_64|Wazuh v4.3.10|ab73af41699f13fdd81903b5f23d8d00|4a8724b20dee0124ff9656783c490c4e|wazuh-worker|node01|1671514909|1671516046|default|37a8eec1|synced|synced|active|0|synced**
```
This behavior assumes that the data is populated by two different processes.

Taking into account the previous analysis, it was decided to analyze the [global DB helper](https://github.com/wazuh/wazuh/blob/4.4/src/wazuh_db/helpers/wdb_global_helpers.c) to understand how the data is stored in the database.
- The [wdb_insert_agent](https://github.com/wazuh/wazuh/blob/4.4/src/wazuh_db/helpers/wdb_global_helpers.c#L44) function is responsible for storing the data in the database in the first instance.
- This function is called from the [run_writer](https://github.com/wazuh/wazuh/blob/4.4/src/os_auth/main-server.c#L801) (wazuh-authd) function, but the `IP` field is not stored in this call.
- Finally, we can see that the `IP` field is set in the [wdb_update_agent_data](https://github.com/wazuh/wazuh/blob/4.4/src/wazuh_db/helpers/wdb_global_helpers.c#L196) function.
- This function is called from the `save_controlmsg` function (wazuh-remoted) on line [#572](https://github.com/wazuh/wazuh/blob/4.4/src/remoted/manager.c#L572). Probably every time a keepalive is received from the agent.
- The variable of interest `agent_data` contains parsed information from the [msg](https://github.com/wazuh/wazuh/blob/4.4/src/remoted/manager.c#L514) parameter.
- it is identified that the section of the message associated with the IP contains the word `**#\"_agent_ip\**`

Concluding that the IP error comes from the agent, the analysis continues how the agent creates and sends the message.
- The agent creates the message in the [run_notify](https://github.com/wazuh/wazuh/blob/4.4/src/client-agent/notify.c#L85) function.
- Line [#182](https://github.com/wazuh/wazuh/blob/4.4/src/client-agent/notify.c#L182) completes the portion of the message related to the IP.
- The IP is obtained in [get_agent_ip](https://github.com/wazuh/wazuh/blob/4.4/src/client-agent/notify.c#L43) by requesting it through a [socket](https://github.com/wazuh/wazuh/blob/4.4/src/shared/agent_op.c#L850).
- The return of this request is the IP of the NAT network instead of the real IP of the machine.

Finally, the [getPrimaryIP](https://github.com/wazuh/wazuh/blob/4.4/src/wazuh_modules/wm_control.c#L52) function is responsible for obtaining the IP and sending it over the socket. This function returns the IP that has a valid gateway.
An extra analysis of the [JSON](https://github.com/wazuh/wazuh/blob/4.4/src/wazuh_modules/wm_control.c#L57) containing the system data allows verifying that all the information about the network connections is available. This would allow modifying the current logic to obtain the corresponding IP address.

<details><summary>JSON data</summary>

```json
"networks": {
  "iface": [
    {
      "IPv4": [
        {
          "address": "10.0.2.15",
          "broadcast": "10.0.2.255",
          "dhcp": "unknown",
          "metric": "100",
          "netmask": "255.255.255.0"
        }
      ],
      "IPv6": [
        {
          "address": "fe80::2336:8ed1:c701:d6ca",
          "broadcast": "",
          "dhcp": "unknown",
          "metric": "",
          "netmask": "ffff:ffff:ffff:ffff::"
        }
      ],
      "adapter": "",
      "gateway": "10.0.2.2",
      "mac": "52:54:00:27:8b:50",
      "mtu": 1500,
      "name": "eth0",
      "rx_bytes": 21086905,
      "rx_dropped": 0,
      "rx_errors": 0,
      "rx_packets": 64045,
      "state": "up",
      "tx_bytes": 10294927,
      "tx_dropped": 0,
      "tx_errors": 0,
      "tx_packets": 47842,
      "type": "ethernet"
    },
    {
      "IPv4": [
        {
          "address": "192.168.56.18",
          "broadcast": "192.168.56.255",
          "dhcp": "disabled",
          "metric": "101",
          "netmask": "255.255.255.0"
        }
      ],
      "IPv6": [
        {
          "address": "fe80::a00:27ff:fe0c:17b",
          "broadcast": "",
          "dhcp": "unknown",
          "metric": "",
          "netmask": "ffff:ffff:ffff:ffff::"
        }
      ],
      "adapter": "",
      "gateway": " ",
      "mac": "08:00:27:0c:01:7b",
      "mtu": 1500,
      "name": "eth1",
      "rx_bytes": 502752,
      "rx_dropped": 0,
      "rx_errors": 0,
      "rx_packets": 4686,
      "state": "up",
      "tx_bytes": 1591436,
      "tx_dropped": 0,
      "tx_errors": 0,
      "tx_packets": 6584,
      "type": "ethernet"
    }
  ]
}
```

</details>

**Comment by pereyra-m** [comment]
Related issue #3457

**Comment by Dwordcito** [comment]
This issue will be covered by this other one, in which we have a new definition for this field.

https://github.com/wazuh/wazuh/issues/16985
