### ISSUE TITLE
[Documentation] POST /groups - Wrong request body

### ISSUE THREAD

**Issue by sylmarch** [wazuh/wazuh#12443]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5-1 | Wazuh API | Manager | Install wazuh-manager via APT | Debian 11 (bullseye) |

Request body in API documentation is wrong to create a new agent group (endpoint: `POST /groups`)

___

In [documentation](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.post_group), agent group should be set using `name`.

```json
{
    "name": "NewGroup_1"
}
```

I try it:
- the API returns 400

___

Looking the source code up on master branch ([controller](https://github.com/wazuh/wazuh/blob/master/api/api/controllers/agent_controller.py#L938) and [model](https://github.com/wazuh/wazuh/blob/master/api/api/models/group_added_model.py)), the agent group should be set using `group_id` :

```json
{
    "group_id": "NewGroup_1"
}
```

I try it : 
- the API returns 200
- the agent group is created on the Wazuh server in `/var/ossec/etc/shared/NewGroup_1`

**Comment by vikman90** [comment]
Hi @sylmarch,

Indeed, there is a contradiction in the documentation. While the request body schema states that the right parameter is `group_id`, the example wrongly reads `name`.

This has been already detected and fixed in the sources (d2fa3e578c9d1b022531fbbfa367fbbd232644d6). The documentation for the upcoming version 4.3 will reflect the correct parameter.

Thank you for reporting this issue. Let me close the ticket as it is already fixed.

Best regards.
