### ISSUE TITLE
Debian 10 - Broken CIS Benchmark

### ISSUE THREAD

**Issue by pagey101** [wazuh/wazuh#12493]
Hello

Rule 2576 instructs to disable ipv6 via grub configuration, which I have done.

This then causes the following rules to fail (all of which check for ipv6 parameters).

2578, 2579, 2580, 2581, 2588.

I believe this may be because the above rules use sysctl to check whether the ipv6 parameters are correctly configured, and fails as ipv6 is not actually available on the system.

I think additional logic is required to make the ipv6 parameter configurations 'not applicable' if ipv6 is correctly disabled via grub.

Thanks

**Comment by FrancoRivero** [comment]
Hi @pagey101,
Thank you for using Wazuh! 
SCA currently has some limitations because it doesn't detect if any application is available before testing a rule, SCA strictly checks that some configuration is set without checking our context, so we are working to improve this behavior. If you want to pass to green, you should apply a correct setting even though IPv6 has been disabled.
To better deal with this limitation the idea is to add fields to test if any app is installed before testing the rule. 
We are working to add new features to SCA in order to test or avoid testing depends on the context, in this case if IPv6 is available before test a rule. [this is the issue named above] (https://github.com/wazuh/wazuh/issues/11488).
Regards

**Comment by pagey101** [comment]
Sounds good, thaks for the quick response!
