### ISSUE TITLE
Refactor the Vulnerability Detector main thread to have now a tasks queue and a scanner `worker` thread - Design

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#12802]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/9220 we are implementing a mechanism to manually trigger Vulnerability Detector scans. This will make the module have two sources of tasks: the ones requested by the Wazuh API, and the ones periodically scheduled. Considering this, we should define the new behavior for these different types of tasks.

### Requirements

We have to consider the following items in the design:
- There has to be a working thread, in charge of running the tasks scheduled
- There has to be a task manager thread, in charge of scheduling tasks and talking with the task manager
- There is one tasks queue where the task manager thread writes the tasks and the working thread consumes them
- There is one messages queue where the working thread writes messages and the task manager threads consumes them
- A set of flags will prevent the task manager thread for scheduling more than one type of task at the same time
- If the task manager thread fails to receive a task ID from the task manager for a scheduled task, the working thread will execute it anyway but no messages will be generated

### Risks analysis

All the posible scenarios should be considered to make sure the pre-existent functionality will be preserved. 

### DoD

The definitive design is at the end of the issue
https://github.com/wazuh/wazuh/issues/12802#issuecomment-1092161491

- [x] Propose a design that fulfills all the requirements. It should reflect the interaction between the working thread and the queues.
- [x] Discuss with the team the design and get the approval.

**Comment by pereyra-m** [comment]
### Proposal 

We have the following components in the vulnerability detector proposal:
- Queue: it will store in order the next scan and update tasks to be performed by the module
- Working thread: it is in charge of reading the queue regularly and execute any task it founds
- Scan scheduler: it writes in the queue a full/partial scan task when the interval expires
- Feed update scheduler: it writes in the queue a scan update task when the interval expires
- Task manager thread: it will regularly talk to the master to request the pending tasks (scan/update)

The working thread only can perform one task at the time, so any agent requested to be scaned on demand will have to wait the local scan/update tasks to run. These tasks can't be seen nor cancelled by the user unless we decide to register them also in the master. Also, it could happen that the same agents get scanned many times because the vulnerability detector module is unable to determine if the agent's inventory has changed or not.

The following diagram summarizes the proposed design

[diagram.zip](https://github.com/wazuh/wazuh/files/8354263/diagram.zip)

![diagram](https://user-images.githubusercontent.com/65046601/160214269-6830ed43-6695-4ae9-be8d-e9a89b5cdcf7.png)

**Comment by DProvinciani** [comment]
### Proposal 2

We have the following components in the vulnerability detector proposal:
- Working thread: it is in charge of pulling tasks from the Task Manager regularly and executing any task it founds. It also sets the status of the tasks.
- Scan scheduler: it writes in the Task Manager a full/partial scan task when the interval expires.
- Feed update scheduler: it writes in the Task Manager a feed update task when the interval expires.

This proposal has the next advantages:

- The user has visibility of the tasks performed by interval in the Vulnerability Detector module.
- The user could cancel/remove tasks periodically scheduled by the Vulnerability Detector module.
- This reduces the number of required threads in the module.
- This removed the need of having a queue in memory.

The following diagram summarizes the proposed design

[diagram2.zip](https://github.com/wazuh/wazuh/files/8362562/diagram2.zip)

![image](https://user-images.githubusercontent.com/5703274/160396918-bec8b73d-a635-46dc-8fc1-661f5cb20b94.png)

**Comment by pereyra-m** [comment]
### Proposal 3

The team reviewed the proposals and a new version was necessary. 
The following aspects are the most interesting ones:
- The local queue will have the scheduled tasks and those requested on-demand
- The Task Manager will show the scheduled scans and feed updates, but the scans will be a general task without details of the agents.
- The vulnerability detector module during a scheduled scan will check after every agent if the task is still valid
- A scheduled feed update will be have more priority than other tasks in the queue. This will not happen with an on-demand feed update
- The task manager thread won't request another task if there is at least one in progress in the queue  

[diagram3.zip](https://github.com/wazuh/wazuh/files/8413167/diagram3.zip)
 
![plantuml](https://user-images.githubusercontent.com/65046601/161633197-f7f97b7d-5274-40b2-8bf1-dfe3dd7a163f.png)

**Comment by MiguelazoDS** [comment]
# Cases

## Scan by interval

### Queue - Working thread interaction

- The working thread always pics the first task in the queue. Doesn't need a task ID.
- Every time it changes the queue task status, notifies the task manager thread.
- Working thread has agent information. Doesn't extract from queue task.
- The working thread can schedule multiple scans by interval.

<details> 
<summary> Click to expand!</summary>

```puml
@startuml
' Elements
collections Queue_Worker #lightgreen
control WorkingThread_Worker #orange

' Sequence
note over Queue_Worker #lightblue: Empty queue
WorkingThread_Worker <--] : Scan by interval\ntriggered
note right of WorkingThread_Worker #lightblue : Interval time expires
WorkingThread_Worker -> Queue_Worker : Schedule NEW task \n(scan by interval)
note right #lightblue : The working thread\ncan not assign\na task ID.
[<- WorkingThread_Worker : Wakes up task manager thread
loop <active agents number> times
  WorkingThread_Worker -> Queue_Worker : Reads first task.
  Queue_Worker --> WorkingThread_Worker : Returns task
  alt new task
    WorkingThread_Worker -> Queue_Worker : Set task as in progress
    [<- WorkingThread_Worker : Wakes up task manager thread
    WorkingThread_Worker -> WorkingThread_Worker : Starts scan \non agent
    note over WorkingThread_Worker #lightblue : Finishes scan
  else in progress task
      WorkingThread_Worker -> WorkingThread_Worker : Starts scan \non agent
      note over WorkingThread_Worker #lightblue : Finishes scan
    alt last agent
      WorkingThread_Worker -> Queue_Worker : Set task as finished
      [<- WorkingThread_Worker : Wakes up task manager thread
    end
  else cancelled task
    WorkingThread_Worker -> WorkingThread_Worker : Skips no \nscanned agents
    WorkingThread_Worker -> Queue_Worker : Set task as finished
    [<- WorkingThread_Worker : Wakes up task manager thread
  end
end
WorkingThread_Worker -> WorkingThread_Worker : Sleeps
@enduml
```

</details>

![image](https://user-images.githubusercontent.com/13010397/162023342-cd4767dd-a1a2-41c3-9ce3-2abd5e98b9b9.png)

## Scan on-demand

### Queue - Working thread interaction

- Does the working thread need to know whether is a task on-demand or not?
Because for the first case it will need to get the agent ID and collects information before attempting the scan.

<details> 
<summary> Click to expand!</summary>

```puml
@startuml
' Elements
collections Queue_Worker #lightgreen
control WorkingThread_Worker #orange

' Sequence
note over Queue_Worker #lightblue: Empty
[--> Queue_Worker : New task 1 scheduled
note right #lightblue : As many tasks \nas many scans \nrequested
[--> Queue_Worker : New task 2 scheduled
… …
[--> Queue_Worker : New task 100 scheduled
[--> WorkingThread_Worker : Wakes up
loop
  WorkingThread_Worker -> Queue_Worker : Reads first task
  Queue_Worker --> WorkingThread_Worker : Returns task
  WorkingThread_Worker -> Queue_Worker : Set task as in progress
  WorkingThread_Worker -> WorkingThread_Worker : Parse agent ID
  WorkingThread_Worker -> WorkingThread_Worker : Gets agent info
  WorkingThread_Worker -> WorkingThread_Worker : Starts scan on agent
  note over WorkingThread_Worker #lightblue : Finishes scan
  WorkingThread_Worker -> Queue_Worker : Set task as finished
  [<-WorkingThread_Worker : Wakes up task manager thread
end
WorkingThread_Worker -> WorkingThread_Worker : Sleeps
@enduml
```

</details>

![image](https://user-images.githubusercontent.com/13010397/162023416-2cc72bbe-e89b-4260-b406-2b0c5a002505.png)

## Feeds update by interval

### Queue - Working thread interaction

- Feeds update is an atomic action. It can't be canceled once started.
- The working thread can schedule multiple feeds update. They may be different every time.

<details> 
<summary> Click to expand!</summary>

```puml
@startuml
' Elements
collections Queue_Worker #lightgreen
control WorkingThread_Worker #orange

' Sequence
note over Queue_Worker #lightblue: Empty queue
WorkingThread_Worker <--] : Feeds update by interval\ntriggered
note right of WorkingThread_Worker #lightblue : Update time expires
WorkingThread_Worker -> Queue_Worker : Schedule NEW task \n(feeds update by interval)
note right #lightblue : The working thread\ncan not assign\na task ID.
[<- WorkingThread_Worker : Wakes up task manager thread
WorkingThread_Worker -> Queue_Worker : Reads first task.
Queue_Worker --> WorkingThread_Worker : Returns task
WorkingThread_Worker -> Queue_Worker : Set task as in progress
[<- WorkingThread_Worker : Wakes up task manager thread
WorkingThread_Worker -> WorkingThread_Worker : Starts feeds update
note over WorkingThread_Worker #lightblue : Finishes feeds update
WorkingThread_Worker -> Queue_Worker : Set task as finished
[<- WorkingThread_Worker : Wakes up task manager thread
WorkingThread_Worker -> WorkingThread_Worker : Sleeps
@enduml
``` 

</details>

![image](https://user-images.githubusercontent.com/13010397/162023441-e6593829-da8a-4d39-9b69-cb7398f3bcd9.png)

## Feeds update on-demand

### Queue - Working thread interaction

- Updates only feed information from enabled providers.

<details> 
<summary> Click to expand!</summary>

```puml
@startuml
' Elements
collections Queue_Worker #lightgreen
control WorkingThread_Worker #orange

' Sequence
note over Queue_Worker #lightblue: Empty
[--> Queue_Worker : New task 1 scheduled
note right #lightblue : Is not possible to schedule\nmore than one feeds\nupdate on demand.
[--> WorkingThread_Worker : Wakes up
WorkingThread_Worker -> Queue_Worker : Reads first task
Queue_Worker --> WorkingThread_Worker : Returns task
WorkingThread_Worker -> Queue_Worker : Set task as in progress
WorkingThread_Worker -> WorkingThread_Worker : Starts feeds update
note over WorkingThread_Worker #lightblue : Finishes feeds update
WorkingThread_Worker -> Queue_Worker : Set task as finished
[<-WorkingThread_Worker : Wakes up task manager thread
WorkingThread_Worker -> WorkingThread_Worker : Sleeps
@enduml
```

</details>

![image](https://user-images.githubusercontent.com/13010397/162023486-94e7800d-346d-46bc-bc9d-456714cac869.png)

**Comment by pereyra-m** [comment]
### Proposal 4

This the last and definitive version of the diagram

<details> 
<summary> Click to expand!</summary>

```puml
@startuml

' Elements
collections Tasks_Queue #lightgreen
control WorkingThread_Worker #orange
collections Messages_Queue #lightgreen

' Sequence
[->Tasks_Queue: TaskID1\n Scan on demand
[->Tasks_Queue: TaskID2\n Feed update on demand
[->Tasks_Queue: Interval scan (missing TaskID)

WorkingThread_Worker -> Tasks_Queue : Reads task
Tasks_Queue --> WorkingThread_Worker : Receveis task (TaskID1)

WorkingThread_Worker -> Messages_Queue : New message (TaskID1 in progress)
WorkingThread_Worker -> WorkingThread_Worker : Run task (TaskID1)
note over WorkingThread_Worker #lightblue : Task completed

WorkingThread_Worker -> Messages_Queue : New message (TaskID1 finished)

WorkingThread_Worker -> Tasks_Queue : Reads task
Tasks_Queue --> WorkingThread_Worker : Receveis task (TaskID2)
WorkingThread_Worker -> Messages_Queue : New message (TaskID2 in progress)

note over Tasks_Queue #lightblue : Only one type of\n on demand task allowed\n at the same time
[->Tasks_Queue: TaskID3\n Scan on demand

WorkingThread_Worker -> WorkingThread_Worker : Run task (TaskID2)
note over WorkingThread_Worker #lightblue : Task completed
WorkingThread_Worker -> Messages_Queue : New message (TaskID2 finished)

WorkingThread_Worker -> Tasks_Queue : Reads task
Tasks_Queue --> WorkingThread_Worker : Receveis task (interval scan)
note over WorkingThread_Worker #lightblue : Missing TaskID\nDon't generate messages
WorkingThread_Worker -> WorkingThread_Worker : Run task (interval scan)
note over WorkingThread_Worker #lightblue : Task completed
note over WorkingThread_Worker #lightblue : Missing TaskID\nDon't generate messages

WorkingThread_Worker -> Tasks_Queue : Reads task
Tasks_Queue --> WorkingThread_Worker : Receveis task (TaskID3)
WorkingThread_Worker -> Messages_Queue : New message (TaskID3 in progress)
WorkingThread_Worker -> WorkingThread_Worker : Run task (TaskID3)
note over WorkingThread_Worker #lightblue : Task completed
@enduml

```

</details>

![diagram4](https://user-images.githubusercontent.com/65046601/162288433-3aaadbf4-f24f-4c77-b28d-36ba84321512.png)

**Comment by DProvinciani** [comment]
With the last proposal, we close this issue.

**Comment by MiguelazoDS** [comment]
# Update 04 May 2022

Due to some requirements changes, it is worth mentioning some aspects to take into account when reviewing the design.

- The task message queue is fixed to a maximum value. 
- The working thread will block on write if the message queue is full. 
- The scan by interval can be canceled at any time. It will finish the current scan on an agent. 
- There's a retry logic for scan by interval if the agent is not available due to the sync with Syscollector is not finished. For scan by demand sole agent will be unlinked and pushed into the queue to retry.
