### ISSUE TITLE
KVDB performance tests design

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#12818]
As part of https://github.com/wazuh/wazuh/issues/12481 we need to implement a Key-Value DB engine capable to search for keys and return values with high performance. 
For this, we must design a set of performance tests to be developed together with KVDB library in order to have a good baseline for future improvements. Also, we must compare this new functionality with the legacy CDB list currently working on analysis.
The main goal of this issue is to have:
- [x] Which tests are required to validate the new implementation.
- [x] Which tests are required to compare this implementation with the old one.
- [x] A design of how this tests will be implemented
- [x] An analysis of the correct options used by our RocksDB wrapper to achieve the best performance. And which options are considered important to test and compare using the already defined tests.

**Comment by san1526** [comment]
After some reading some guides about RockDB, being that we don't have a really well defined use case or data set (because it can be defined by each user) the tuning recommendation of the guides it's to just use the default configuration and go from there.
https://github.com/EighteenZi/rocksdb_wiki/blob/master/RocksDB-Tuning-Guide.md

Being that we are more concerned with the read performance of the KVDB the only setting that could help directly with this and its simple enough to set is the Bloom filters https://github.com/facebook/rocksdb/wiki/RocksDB-Bloom-Filter
Once again this also depends on the size and type of data that's stored in the db so performance and memory consumption is hard to really tune/measure

The problem that we have here is that we could tune the db (or just get performance metrics) with a _demo_ database but this numbers could vary greatly (and thus loose meaning) with a different dataset. 

That being said we should try to measure the amount of read queries that both our wrapper and the 'raw' db implementation can perform with different amount of threads hitting the DBs in a set ammount of time.
This metric is intended to be compared (at least for the time being) to the current implementation of the cdb lists in the Old wazuh Analysisd.

Additionally there are some tool and statistics for RocksDB that can provide extra performance information:
https://github.com/facebook/rocksdb/wiki/Statistics
https://github.com/facebook/rocksdb/wiki/Perf-Context-and-IO-Stats-Context
https://github.com/facebook/rocksdb/wiki/Benchmarking-tools
While this can provide very detailed statistics and info about the performance they are more suited to tune specific datasets to specific hardware, a case that we don't really have here. We mostly list this tools because they could probably help to tune client specific cases in the future so it's worth to know they exists and lay a foundation on how they could be integrated or used in our case in the future

**Comment by LucioDonda** [comment]
**Creating and Ingesting SST files**

There's a functionality that allows a DB to be filled with a file, the only potential problem that I cold found is that this file needs to be created with a specific method from the RocksDB library, which makes it hard to move from an old (legacy) file. So in the worst-case scenario, we should compare how much does it take to fill a DB with the normal methods ( _[put](https://github.com/facebook/rocksdb/wiki/Transactions#transactiondb) to transaction_ ) versus creating a file and then ingesting it to a DB.
For more information, there's some [official documentation](https://github.com/facebook/rocksdb/wiki/Creating-and-Ingesting-SST-files).

**Comment by san1526** [comment]
After reviewing the Analisisd code we concluded that the only comparative test that we can do that's meaningful is the read/val-compare speed of the current CBD implementation against the new rocksdb based implementation  being that the initialization and write/update of both this approaches are vastly different.
To do this we are isolating the `OS_DBSearch` function in analisysd which actually performs the db search and value comparison and doing multiple iterations to try to get some baseline to compare against.

**Comment by san1526** [comment]
Doing some small testing with analisysd we set up two customs rules with a custom cbd look up:
```
 <group name="myList">
<rule id="110700" level="1">
  <list field="user" lookup="match_key_value" check_value="^action">etc/lists/myList</list>
  <description>IP blacklisted in LIST ONE</description>
  <group>myList</group>
</rule>

<rule id="110701" level="1">
  <list field="user" lookup="match_key">etc/lists/myList</list>
  <description>IP blacklisted in LIST ONE</description>
  <group>myList</group>
</rule>
</group>
```
One rule performs the key lookup and a value comparison (with regex) and the other rule just does the Key lookup.
With this set up we get the following output

> /var/ossec/bin/wazuh-analysisd -f
> cp: overwrite '/var/ossec/bin/wazuh-analysisd'? y
> 2022/03/30 18:15:04 wazuh-analysisd: INFO: Total rules enabled: '6353'
> 2022/03/30 18:15:04 wazuh-analysisd: INFO: Started (pid: 148090).
> **Performing [100000] iterations.**
> 2022/03/30 18:15:04 wazuh-analysisd: INFO: (7200): Logtest started
> **[recurseRules:Key + val] = 11762.342000us**
> **Performing [100000] iterations.**
> **[recurseRules:Key only] = 7380.032000us**
> 
As a note we need to take into account that the value comparison will vary **greatly** as it can be any valid regex (in this case is just matching a single word) so we need to take this 'performance metrics' we a grain of salt.

**Comment by palaciosjeremias** [comment]
After this analysis, the below performance tests will be implemented:
- Read from legacy CDB.
  - Implemented by modifying the source code of analysis to print reference logs.
- Read from new KVDB implementation. 
- Direct write from new KVDB implementation. 
- Transactioned write from new KVDB implementation.
