### ISSUE TITLE
Add a mechanism to avoid a brute-force attack at port 1516

### ISSUE THREAD

**Issue by yanazaeva** [wazuh/wazuh#12828]
|Wazuh version|Component|
|---|---|
| master | Wazuh cluster |

## Description

As it was seen here https://github.com/wazuh/wazuh/issues/11492, if we sent a huge amount of requests to the port used by the Wazuh cluster daemon (1516), this process will end unexpectedly due to the number of requests. In order to avoid this, we should implement a mechanism that will prevent this. 

To do so, we will need to establish a threshold, which could be based on the number of requests the master is capable of correctly processing before failing. Also, we will need to classify the received requests by IPs, and if some IP has exceeded the established threshold block it for a certain amount of time. 

## Reproduce the behaviour

To reproduce this situation, we will need a running cluster. From any other node, we can run the following script:
```PYTHON3
import socket
HOST = <master node IP from networkB>
PORT = 1516
while True:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.connect((HOST, PORT))
        s.send(b'hello value value value 4.4.0')
```
and in less than a minute the `wazuh-clusterd` will fail.

**Comment by Selutario** [comment]
## Status update

In case of a DDoS attack, the cluster server cannot reject connections before being received since that would require some external element. At least, we could close the transport after establishing the connection, in case some conditions are met (yet to be determined). That would be done here:
https://github.com/wazuh/wazuh/blob/e840c6451b6be89a1fefaaa6e5a31de3ba46dcc4/framework/wazuh/core/cluster/server.py#L65-L76

Some of those conditions could be:
- Same IP making a connection and not sending `hello` command. 
- Multiple connections made from the same IP (if some workers are behind a NAT, this could block real connections in some scenarios).
- Multiple unsuccessful connections attempts from the same IP in a short period of time.

I am still however investigating if there are real use cases in which this development could be effective or necessary.

**Comment by Selutario** [comment]
## Status update

I created a simple system that accepts up to N incomplete connection attempts. An incomplete connection happens when a client connects to the Master socket but does not send the `hello` command with valid information (client name, version, cluster name, etc). 

If more than N incomplete connection attempts from the same IP happens in less than Y seconds, new connections would be closed for Y seconds:
```
2022/04/21 09:57:27 INFO: [Worker] [Main] Connection from ('172.21.0.5', 39432)
2022/04/21 09:57:37 WARNING: [Worker] [Main] Too many incomplete connection attempts from 172.21.0.5 in less than 60 seconds. Cancelling this connection...
2022/04/21 09:57:37 ERROR: [Worker] [Main] Error during handshake with incoming connection.
2022/04/21 09:57:37 INFO: [Worker] [Main] Cancelling pending tasks.
```

This would increase the time needed to saturate the server or succeed in the DoS attack. However, the first N (incomplete) connections remain and the server would fail eventually. 

As I mentioned in the las issue update, there is not a real use case where the master could be attacked since it is not intended to accept connections from unknown clients. Once a connection reaches the master node, it is already using its resources (Network card, socket space, RAM, CPU, etc), so it is too late. The cluster port always needs to be protected with, at least, a firewall. 

Anyway, I will re-focus this issue after talking with the team. I will check if the [bind_addr](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/cluster.html#bind-addr) cluster option works with a list of addresses (other than 0.0.0.0) and what is its behaviour. I will also check how SSL is being handled in the cluster connections and any related topic.

**Comment by Selutario** [comment]
# Issue update

## 1. SSL & Fernet Key

Despite not being listed in the [documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/cluster.html) nor supporting the option in the `ossec.conf`, the Wazuh master is able to encrypt its communication with workers using TLS. In fact, the `wazuh-clusterd` binary does let specifying whether to enable SSL or not:
https://github.com/wazuh/wazuh/blob/577982963bd4f21995b10447fbc7f5790445bc16/framework/scripts/wazuh-clusterd.py#L133

If enabled, the certificates used are those located in `/var/ossec/etc/sslmanager.cert` and `/var/ossec/etc/sslmanager.key`:
https://github.com/wazuh/wazuh/blob/577982963bd4f21995b10447fbc7f5790445bc16/framework/wazuh/core/cluster/server.py#L391-L392

The problem is that those files are owned by `root:root` so the master, who is `wazuh:wazuh`, cannot read it. If cluster binary is run with `-r` option, it would execute as root and therefore SSL could be used. 

Below you can see the packets captured during the communication between a master node and its worker node when using different forms of encryption.

### 1.1. SSL: no | Fernet key: no
As expected, it is possible to see all the communication between both nodes when not using encryption. That includes the commands used by the cluster and their payload/data:
![image](https://user-images.githubusercontent.com/23361101/164715686-f08411d7-8c74-43a1-a607-6bcfb8c08b18.png)

### 1.2. SSL: no | Fernet key: yes
Fernet is a symmetric key encryption implementation. This is currently the default configuration in the cluster, since it is mandatory to specify a Fernet key and it is not possible to activate SSL for the cluster in `ossec.conf`.

As shown below, the header in the cluster communications (which includes the command used) is not encrypted with the Fernet key. Only the data is:
https://github.com/wazuh/wazuh/blob/577982963bd4f21995b10447fbc7f5790445bc16/framework/wazuh/core/cluster/common.py#L346-L354

Therefore, and as shown in the captured trace, the commands and other header information would be visible:
![image](https://user-images.githubusercontent.com/23361101/164716443-e3e74729-ea63-4ff3-97d9-cb0b76c0c783.png)

### 1.3. SSL: yes | Fernet key: no
If we enable SSL encryption, the workers negotiate the key with the master at the beginning of the communication and, from then on, everything is encrypted (including the headers). Nothing legible can be seen in the image:
![image](https://user-images.githubusercontent.com/23361101/164717954-5bd986c3-9755-4840-bd29-ee56945fb3d6.png)

### 1.4 Conclusion
In the future, it is intended to make it easier to configure the connection of workers and master and one way to achieve this would be to eliminate (at least the obligation) to use a fernet key.

However, it will be necessary to fix the problem mentione above: Master can't read certificates without being root user.

## 2. Bind_addr option
The [bind_addr](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/cluster.html#bind-addr) option does not allow the master to decide which IPs can connect to it (a firewall must take care of that). This option is used to determine which network interfaces the master node should listen on.

For example, let's imagine a master node that has these 2 IPs in different interfaces:
- 172.16.1.10
- 192.168.59.12

Then, we have 2 workers with these IP:
- **Worker A:** 172.16.1.11
- **Worker B:** 192.168.59.14

If the master sets the bind_address as follows:
```XML
<bind_addr>0.0.0.0<bind_addr>
```

It would accept connections from any interface. It means that both `Worker A` and `Worker B` could connect even if each of them are in a different network/interface. However, if we set a specific IP in the master's bind_addr:
```XML
<bind_addr>172.16.1.10<bind_addr>
```

Only `Worker A`, whose IP is `172.16.1.11` could connect. The master would not be listening on the 172.168.59.X interface so `Worker B` wouldn't connect. However, we are not limiting which workers can connect. Any worker that is on the same network as the one specified in the master bind_addr (`172.16.1.X`), could connect.

In any case, [asyncio.create_server](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_server) accepts a list of IPs in the host/bind_address parameter, while we are denying that possibility in the Wazuh configuration. We should update it so it accepts a list of specific IPs where the master should be listening since now, only two options are allowed:
- All interfaces.
- Only one interface.

https://github.com/wazuh/wazuh/blob/577982963bd4f21995b10447fbc7f5790445bc16/framework/wazuh/core/cluster/server.py#L397-L401
