### ISSUE TITLE
Release 4.3.0 - Manual tests - Deployment with Puppet

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#12877]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |Deployment with Puppet|
| **Category**            |Installation|
| **Deployment option**   |Deployment with Puppet|
| **Main release issue**  |#10954|
| **Release candidate #** |RC5|

## Test description

Test distributed deployment with Wazuh manager cluster and Wazuh indexer cluster via Puppet.
Test deployment of the agent via Puppet.

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results must be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found [here]().

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🔴  | Wazuh cluster deployment | documentation | Multiple issues listed here https://github.com/wazuh/wazuh-documentation/issues/4997 |
| 🔴  | Wazuh indexer deployment | documentation | No instructions provided in the documentation https://github.com/wazuh/wazuh-documentation/issues/4997 |
| 🔴  | Wazuh manager and agent deployment | Wazuh Puppet module | Setting `ossec_service_provider` not working. https://github.com/wazuh/wazuh-puppet/issues/468 |
| 🔴  | Wazuh manager and agent deployment | Wazuh Puppet module | Misc variables with no effect. https://github.com/wazuh/wazuh-puppet/issues/467 |
| 🔴  | Wazuh manager and agent deployment | Wazuh Puppet module | Multiple variables with no effect. https://github.com/wazuh/wazuh-puppet/issues/459 |
| 🔴  | Wazuh manager deployment | Wazuh Puppet module | Multiples errors in syscheck variables. https://github.com/wazuh/wazuh-puppet/issues/464 |
| 🔴  | Wazuh manager deployment | Wazuh Puppet module | Vulnerability Detector variables with no effect. https://github.com/wazuh/wazuh-puppet/issues/465 |
| 🔴  | Wazuh agent deployment | Wazuh Puppet module | SCA variables with no effect. https://github.com/wazuh/wazuh-puppet/issues/466 |
| 🔴  | Windows agent deployment | Wazuh Puppet module | Errors in internal variables of the module. https://github.com/wazuh/wazuh-puppet/issues/469 |
| 🔴  | Windows agent deployment | Wazuh Puppet module or Windows Installer | Service not started after the deployment. https://github.com/wazuh/wazuh-puppet/issues/470 |
| 🔴  | Wazuh agent deployment on Ubuntu 20.10 | Wazuh Puppet module | The module doesn't support Ubuntu 20.10. https://github.com/wazuh/wazuh-puppet/issues/460 |
| 🔴  | PuppetDB deployment | Wazuh Puppet module | Incorrect version of PostgreSQL. https://github.com/wazuh/wazuh-puppet/issues/461 |

All tests have passed and the fails have been reported or justified. Therefore, I conclude that this issue is finished and OK for this release candidate.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @alberpilot
- [x] @davidjiglesias

**Comment by DProvinciani** [comment]
### Installing puppet master

The hostname was set with the next command.

```
hostname -b centos7
```

And also editing the `/etc/hosts` file.

```
192.168.0.152 centos7
127.0.0.1 puppet
```

The installation was performed in Centos7 by using the version 6 of puppet.

```
rpm -ivh https://yum.puppetlabs.com/puppet6-release-el-7.noarch.rpm
yum install puppetserver
ln -s /opt/puppetlabs/bin/puppet /bin
```

The file `/etc/puppetlabs/puppet/puppet.conf` was edit with the next setting

```
[main]
dns_alt_names = centos7
```

### Installing puppet agent

The systems used were centos8 and ubuntu 2004. In both systems I set the centos7 hostname in `/etc/hosts`

```
192.168.0.152 centos7
```

For the centos8 server I installed the agent following the next steps

```
rpm -ivh https://yum.puppetlabs.com/puppet6-release-el-8.noarch.rpm
yum -y install puppet-agent
ln -s /opt/puppetlabs/bin/puppet /bin
```

For the ubuntu server I installed the puppet agent following the next steps.

```
apt update
apt upgrade
apt install curl apt-transport-https lsb-release
wget https://apt.puppetlabs.com/puppet6-release-focal.deb
dpkg -i puppet6-release-focal.deb
apt update
apt install puppet-agent
ln -s /opt/puppetlabs/bin/puppet /bin
```

Then both server were configured in the file `/etc/puppetlabs/puppet/puppet.conf` with:

```
[main]
server = centos7
```

And the puppet service was restarted:

```
sudo puppet resource service puppet ensure=stopped
sudo puppet resource service puppet ensure=running
```

### Setting up Puppet certificates

On each agent I run the next command:

```
puppet agent -t
```

Then on the server:

```
puppetserver ca list --verbose
```

In this case I always got the next error:

![image](https://user-images.githubusercontent.com/5703274/160702728-ec4ee836-7d4a-4cfe-8e85-3fc7d90658fd.png)

After doing some research, the only thing that resolved the issue was regenerating the certificates by following the instructions in the next link:

https://puppet.com/docs/puppet/7/ssl_regenerate_certificates.html#clear_regenerate_certs_on_primary_server

![image](https://user-images.githubusercontent.com/5703274/160703091-18af27b1-7d9d-4bf8-95a2-01f23f29f9b5.png)

And then also on each agent

![image](https://user-images.githubusercontent.com/5703274/160703223-860ab4ec-a708-4b14-91a9-c237d501d500.png)

And finally I signed the certificates requested for each agent

```
puppetserver ca sign --all
```

And on the agents...

![image](https://user-images.githubusercontent.com/5703274/160703679-81fa5029-ac3e-48f2-b626-bf93243ffcbc.png)

![image](https://user-images.githubusercontent.com/5703274/160703719-21369b36-5627-40b2-9226-16a43eaac58b.png)

**Comment by MiguelazoDS** [comment]
# Wazuh-Cluster deployment with Puppet

## Puppet environment

- Puppet master: Centos 8
- Puppet agents: Centos 7, Debian Buster, Ubuntu Focal

## Wazuh environment

- Wazuh manager master: Centos 8
- Wazuh manager worker: Centos 7
- Wazuh agent: Debian Buster (Connected to Centos 8)
- Wazuh agent: Ubuntu Focal (Connected to Centos 7)

## Steps for provisioning

### Install Puppet
#### Centos 8
- `rpm -ivh https://yum.puppetlabs.com/puppet5/puppet5-release-el-8.noarch.rpm`
- `yum -y install puppetserver`
- Edit `/etc/puppetlabs/puppet/puppet.conf` with `dns_alt_names = puppet` in [master]
- `ln -s /opt/puppetlabs/bin/puppet /bin`
#### Centos 7
- `rpm -ivh https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm`
- `yum -y install puppet-agent`
- Edit `/etc/puppetlabs/puppet/puppet.conf` with `server = puppet` in [master]
- `ln -s /opt/puppetlabs/bin/puppet /bin`
- `puppet resource service puppet ensure=running enable=true`
#### Debian Buster
- `apt-get update`
- `apt-get install curl apt-transport-https lsb-release`
- `wget https://apt.puppetlabs.com/puppet5-release-buster.deb`
- `dpkg -i puppet5-release-buster.deb`
- `apt update`
- `apt-get install -y puppet-agent`
- Edit `/etc/puppetlabs/puppet/puppet.conf` with `server = puppet` in [master]
- `ln -s /opt/puppetlabs/bin/puppet /bin`
#### Ubuntu Focal
- `apt-get update`
- `apt-get install curl apt-transport-https lsb-release`
- `wget https://apt.puppetlabs.com/puppet5-release-xenial.deb`
**Note: It wasn't a specific version for Focal so Xenial was used instead**
- `dpkg -i puppet5-release-xenial.deb`
- `apt update`
- `apt-get install -y puppet-agent`
- Edit `/etc/puppetlabs/puppet/puppet.conf` with `server = puppet` in [master]
- `ln -s /opt/puppetlabs/bin/puppet /bin`
### Edit /etc/hosts file in all nodes.
Adding `<puppet_master_address> <dns_alt_names>`
For this case `192.168.33.11 puppet`
### Certs configuration
- `puppet agent -t` for all nodes
- `puppetserver ca list` for puppet master node (it will list all certs that need approval)
- `puppet cert sign --all` for puppet master node
- `puppet agent -t` for all nodes
- `puppetserver ca list` should now return an empty list
![image](https://user-images.githubusercontent.com/13010397/160881545-ef3ce4e0-cd48-4386-a761-2a4b10cee48d.png)
### Install PDK on Puppet master node
- `sudo rpm -Uvh https://yum.puppet.com/puppet-tools-release-el-8.noarch.rpm`
- `sudo yum install pdk`
### Install Wazuh 4.3.0 module on Puppet master node
- `git clone --branch 4.3 https://github.com/wazuh/wazuh-puppet.git`
- `cd wazuh-puppet`
- `pdk build` (It generates a wazuh_version.tar.gz package)
- `puppet module install path/tar.gz`
### Configure repo.pp for testing
Replace the following:
- `packages.wazuh.com` by `packages-dev.wazuh.com`
- `4.x` by `pre-release`
- `release => 'stable'` by `release => 'unstable'`
#### repo.pp file
[repo.txt](https://github.com/wazuh/wazuh/files/8382287/repo.txt)
### Configure managers and agents manifests
#### wazuh-agent.pp file
[wazuh-agent.txt](https://github.com/wazuh/wazuh/files/8382296/wazuh-agent.txt)
#### wazuh-manager.pp file
[wazuh-manager.txt](https://github.com/wazuh/wazuh/files/8382297/wazuh-manager.txt)
## Provisioning with Puppet findings

**Comment by pereyra-m** [comment]
# Deploying Wazuh Cluster 4.3.0 with puppet

These are the results of the testing of the puppet module for Wazuh.

## Environment

The following system was deployed:
- Ubuntu 20.04: Puppet Master
- Ubuntu 20.04: Wazuh Manager master - puppet agent
- CentOS 8: Wazuh Manager worker - puppet agent
- Ubuntu 20.10: Wazuh Agent - puppet agent
- Ubuntu CentOS 7: Wazuh Agent - puppet agent

## Pre-release testing

In order to test a Wazuh version that still isn't published in Puppet Forge, the following steps were neccesary

- Install [pdk](https://puppet.com/docs/pdk/1.x/pdk_install.html#:~:text=choco%20upgrade%20pdk-,Download%20and%20install%20the%20package,PDK%20available%20to%20your%20PATH)
- Then clone the repo: `git clone --branch 4.3 https://github.com/wazuh/wazuh-puppet.git`
- Create the package: `cd wazuh-puppet && pdk  build`
- Install the module: `puppet module install /path/to/module`

Also, the `repo.pp` file must be modified:
- All the references to `packages.wazuh.com` were replaced with `packages-dev.wazuh.com`
- The `4.x` references were replaced with `pre-release`
- The `stable` request was changed to `unstable`

[repo.pp.zip](https://github.com/wazuh/wazuh/files/8383560/repo.pp.zip)

Also, if the `/etc/hosts` file isn't updated with the IP of the puppet server using the **puppet** name the agents can't find the master.

## Tests evidence

The manager worker and master were properly deployed with these files

[wazuh-manager-worker.zip](https://github.com/wazuh/wazuh/files/8384144/wazuh-manager-worker.zip)
[wazuh-manager-master.zip](https://github.com/wazuh/wazuh/files/8384145/wazuh-manager-master.zip)

![wazuh_manager_successfull](https://user-images.githubusercontent.com/65046601/160932559-b1e634cd-3fdb-4c7b-8b24-ae91ba36255b.png)

The cluster works as expected

![cluster_working](https://user-images.githubusercontent.com/65046601/160933135-e10283a3-5e13-4c75-8fa6-6c1c7f7c7566.png)

The agents got connected successfully
 
[wazuh-agent-2.zip](https://github.com/wazuh/wazuh/files/8384158/wazuh-agent-2.zip)
[wazuh-agent-1.zip](https://github.com/wazuh/wazuh/files/8384160/wazuh-agent-1.zip)

![agents_properly_connected_to_cluster2](https://user-images.githubusercontent.com/65046601/160933387-91267ddc-aeaa-4891-9acc-ba4de798086f.png)

![agents_connected_succesfully_](https://user-images.githubusercontent.com/65046601/160933381-f9debcfc-1ed1-42d2-a76d-8e9f5b2c00e6.png)

## Issues found

### Puppet version

Following the documentation steps to install puppet (for both master and agent) could generate a version problem, installing puppet 7 when it is stated that the Wazuh module is only compatible with version 5/6. If we change the distribution name according to the host, we should change

```
wget https://apt.puppetlabs.com/puppet5-release-xenial.deb
```

To 

```
wget https://apt.puppetlabs.com/puppet5-release-focal.deb
```

But this package doesn't exist for that distribution in that location. If we use [puppet-release-focal.deb](https://apt.puppetlabs.com/puppet-release-focal.deb) or [puppet6-release-focal.deb](https://apt.puppetlabs.com/puppet6-release-focal.deb) and we don't specify the version we want it may end up installing the version 7 of puppet

```
apt update
apt-get install -y puppetserver
```

One of the problems with this version is that some commands used later, like `puppet cert list` are deprecated. 

### Deprecated/incorrect settings

Many variables defined for both Wazuh clases weren't recognized by the puppet module.

**Wazuh Manager class**
The settings were tested with the following configuration

[wazuh_manager_testing_variables.zip](https://github.com/wazuh/wazuh/files/8384182/wazuh_manager_testing_variables.zip)

The following settings don't work:
- ossec_auth_force_insert
- ossec_auth_force_time
- ossec_rootcheck_windows_disabled
- ossec_rootcheck_windows_windows_apps
- ossec_rootcheck_windows_windows_malware

![master_deprecated_Settings](https://user-images.githubusercontent.com/65046601/160931195-1c4d79da-9b3e-4453-921c-10debdc3d98e.png)

- Also, the `ossec_emailnotification` isn't properly described. The module expects a Boolean (true/false), but the documentation describes it like a String (yes/no)

![master_failed_type_ossec_emailnotification](https://user-images.githubusercontent.com/65046601/160931688-02ab4763-8794-4df4-93e8-8073880b7ff0.png)

- The `ossec_local_files` is named but it can't be used. To configure the **localfiles** section it names the `params_manager.pp` but this isn't properly described in the documentation. Also, the changes in  `params_manager.pp` are only detected by the Ubuntu manager

![master_failed_ossec_local_files](https://user-images.githubusercontent.com/65046601/160932047-deb162cf-5185-401d-bef5-9296143d0c03.png)

- The `ossec_auth_ssl_manager_cert` has an incorrect default value in the documentation (yes)

- The `ossec_auth_ssl_manager_key` has an incorrect default value in the documentation (yes)

- The `ossec_remote_connection` variable can't be set to **syslog** because the default value of **queue_size** generates a configuration error 
![master_queue_size_fails_when_ossec_remote_connection_is_set](https://user-images.githubusercontent.com/65046601/160942314-1592b52d-142c-4223-a714-2e4b2885ae51.png)

The following variables never appear in the **ossec.conf** file:
- ossec_smtp_server
- ossec_emailto
- ossec_emailfrom
- ossec_email_maxperhour
- ossec_email_log_source
- ossec_email_idsname


**Wazuh agent class**
The settings were tested with the following configuration

[wazuh_agent_testing_variables.zip](https://github.com/wazuh/wazuh/files/8384186/wazuh_agent_testing_variables.zip)

The following settings don't work (many of them should't be available for agents):
- active_response_disabled
- active_response_ca_verification
- active_response_location
- active_response_level
- active_response_agent_id
- active_response_rules_id
- active_response_timeout
- active_response_repeated_offenders
- ossec_config_profiles

![agent_not_supported_configs](https://user-images.githubusercontent.com/65046601/160934138-93611eee-694f-4ab1-9005-859b290b458c.png)

- The `ossec_local_files` variable presents the same issue than the manger: it isn't available, the reference to `params_agent.pp` isn't clear and the changes are only detected in Ubuntu 

![default_localfile_works_for_agent_ubuntu_and_not_for_centos](https://user-images.githubusercontent.com/65046601/160934833-54512d16-967f-4498-9108-581f3244df0b.png)

- The variable `wazuh_register_endpoint` must be defined but it isn't written in the **ossec.conf** file, so it isn't clear where/how it's used

![agent_wazuh_register_endpoint](https://user-images.githubusercontent.com/65046601/160934914-a57d08cb-f20b-480b-881b-7dded1faebc5.png)

- The variable `configure_active_response` when is activated in the agent class, tries to read the `params_manager.pp` file.

- All the **Agent enrollment variables** were ignored and none of them was applied to the configuration
 
- The variable `configure_rootcheck` doesn't correspond to any variable of Wazuh and it should explained properly 

Also, the typo `This files` was found.

### Distribution not supported

The connection of the Ubuntu 20.10 agent failed because the distribution code-name **Groovy** wasn't recognized by the module and it had to be added manually

![agent_groovy_not_supported_2](https://user-images.githubusercontent.com/65046601/160935252-df647a08-3b29-4d62-951b-2eba4ea7db69.png)

![agent_groovy_not_supported](https://user-images.githubusercontent.com/65046601/160935248-e9f17fbb-ce5e-4330-b1f9-48d480e1f2e5.png)

### PuppetDB installation failed

The documentation steps for this section are outdated.
The requested PostgreSQL version (9.4) is no longer supported by PuppetDB

```
Mar 28 16:45:29 ubuntu-focal puppetdb[13650]: PostgreSQL 9.4 is no longer supported. Please upgrade to 11.0.
```

Also, it wasn't clear what is the real IP that `/etc/puppetlabs/puppet/puppetdb.conf` should contain

**Comment by alberpilot** [comment]
After analyzing the puppet issues described in the Conclusion section, we add the following information:

- The following issues are present on 4.2 branch, so they are not 4.3.0 stoppers:

  - https://github.com/wazuh/wazuh-puppet/issues/468 
  - https://github.com/wazuh/wazuh-puppet/issues/467
  - https://github.com/wazuh/wazuh-puppet/issues/459
  - https://github.com/wazuh/wazuh-puppet/issues/464
  - https://github.com/wazuh/wazuh-puppet/issues/466
  - https://github.com/wazuh/wazuh-puppet/issues/469
  - https://github.com/wazuh/wazuh-puppet/issues/460
  - https://github.com/wazuh/wazuh-puppet/issues/461
  
- The following issues are prioritized to be completed before 4.3.0 release:
  - https://github.com/wazuh/wazuh-puppet/issues/465
  - https://github.com/wazuh/wazuh-puppet/issues/470
