### ISSUE TITLE
Release 4.3.0 - Manual tests - Configuration assessment

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#12889]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                       |                                            |
|-----------------------|--------------------------------------------|
| **Test name**         |  Configuration assessment                                        |
| **Category**          | Installation                                           |
| **Deployment option** | Offline installation                                     |
| **Main release issue** | https://github.com/wazuh/wazuh/issues/10954                                           |
| **Release candidate #** | RC5                                           |

### Scenario: 

![man2](https://user-images.githubusercontent.com/34478747/161250274-e28d032f-a229-4332-91b5-5a3e5306afb1.png)

Deploy the following systems:
- Diode system. The system needed to download all packages.
- Offline Manager. Wazuh All-in-one over Amazon Linux 2 server simulating Offline networking. 
- Offline Agent. Amazon Linux 2 system with Nginx and wazuh-agent simulating Offline networking. 

- After full installation is done and wazuh-agent is registered then:  
    - SCA policy for amazon Linux 2.
    - SCA policy Nginx.

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed to check. |
| :yellow_circle:  | There is at least one expected to fail or skipped test and no failures. |

## Conclusions

- The offline installing process can/should be improved by providing customers with a single offline installer script in both the download system and offline system.

- The transfer of packages from the download system to the offline system should be improved by creating a single tar.gz file as output from the download process. it is easier to copy between offline systems.

- [#wazuh-packages/1422](https://github.com/wazuh/wazuh-packages/issues/1422)

All tests have been executed and here are the results: 

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|                |             |                     |                |
|:green_circle:| Download software on diode system | ||
|:green_circle:| Transfer to destination offline system ||| 
|:green_circle:| Install Manager on offline system |||
|:green_circle:| Install wazuh-indexer on offline system |||
|:green_circle:| Install Filebeat on offline system |||
|:green_circle:| Install wazuh-dashaboard on offline system |||
|:green_circle:| Install wazuh-agent on amazon linux 2 system (suppose to be offline) |||
|:green_circle:| Wazuh-agent SCA runs cis_amazon_linux_2||Check IDs: 20592 and 20553 should be reworked - #13030  |
|:green_circle:| Deploy manually cis_nginx_1 and verify it is executed||Check IDs: 23000, 23001, 23002, 23019, 23024 should be reworked, related to issue #12347  |
****

Related issues affected or created during this test
- #12347 
- [#wazuh-packages/1422](https://github.com/wazuh/wazuh-packages/issues/1422)
- #13030 

## Auditors' validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @davidjiglesias

**Comment by fabamatic** [comment]
## Issues during manager installation:

### Section: Download the packages and configuration files

#### Step: **3. Create the certificates and move them to the wazuh-offline/ directory.**

When executing wazuh-cert-tools.sh an error message is generated. Not clear if the process will work

```
./wazuh-certs-tool.sh --all
28/03/2022 20:51:04 INFO: Admin certificates created.
28/03/2022 20:51:04 ERROR: The given information does not match with an IP address or a DNS.
```


`mv wazuh-certificates/ wazuh-offline/` instructions are incorrect as wazuh-certs-tool.sh creates cert files in `/tmp/wazuh-certificates`

### Section: Installing Wazuh indexer

#### Step: 2. Remove the demo certificates.

```
rm /etc/wazuh-indexer/certs/admin-key.pem /etc/wazuh-indexer/certs/admin.pem /etc/wazuh-indexer/certs/demo-indexer-key.pem /etc/wazuh-indexer/certs/demo-indexer.pem /etc/wazuh-indexer/certs/root-ca.pem -f 
```

Missing `#` indicating that it's a single command

For the mopment can't continue with installation steps because of missing cert files

**Comment by fabamatic** [comment]
Installation of wazuh-manager seems to be ok:

![image](https://user-images.githubusercontent.com/7738867/160503960-c23dec17-27e8-4cf5-a8a2-ea70c6fdd8ae.png)

**Comment by AwwalQuan** [comment]
## Issues resolved in manager installation
The following changes were made to [Installation alternatives- Offline installation](https://docs.google.com/document/d/1W_Yp-jScuVitrej3GR6FJVPVtkWW7-qKofbmhgnLCxU/edit?usp=sharing)
### Section: Installing Wazuh indexer
- The missing `#` has been added to the command in step 2:
```# rm /etc/wazuh-indexer/certs/admin-key.pem /etc/wazuh-indexer/certs/admin.pem /etc/wazuh-indexer/certs/demo-indexer-key.pem /etc/wazuh-indexer/certs/demo-indexer.pem /etc/wazuh-indexer/certs/root-ca.pem -f ```

- The command `mkdir /etc/wazuh-indexer/certs` has been added to step 3 in order to create the directory before the certificates are moved in.

### Section: Installing Wazuh dashboard
- The command `mkdir /etc/wazuh-dashboard/certs` has been added to step 2 in order to create the directory before the certificates are moved in.

- The step to edit `/etc/wazuh-dashboard/opensearch_dashboards.yml` and change the certificate path has been removed. The configuration file now has the correct value by default and the user doesn't need to make any changes.

filebeat.yml template is still not available in 4.3 repository as noted in the [comment](https://docs.google.com/document/d/1W_Yp-jScuVitrej3GR6FJVPVtkWW7-qKofbmhgnLCxU/edit?disco=AAAAW9lEmT8).

**Comment by fabamatic** [comment]
Installed agent using this guide: https://documentation-dev.wazuh.com/3865_installation_guide_rework/installation-guide/wazuh-agent/wazuh-agent-package-linux.html

Using this rpm:  https://packages-dev.wazuh.com/pre-release/yum/wazuh-agent-4.3.0-1.x86_64.rpm

No issues were found during agent installation

**Comment by fabamatic** [comment]
CIS Benchmark for Amazon Linux 2 seems to execute correctly. Will do an in depth analysis.
It's not clear how to enable nginx SCA policy (beyond manually enabling it, treating it like a custom SCA)

**Comment by fabamatic** [comment]
### CIS Benchmark for Amazon Linux 2
Results:
![image](https://user-images.githubusercontent.com/7738867/160705685-73cae948-ff57-400d-89fa-5a21acb85f63.png)

**Comment by fabamatic** [comment]
### CIS benchmark Nginx

Installed nginx using this guide: https://comtechies.com/how-to-install-and-configure-nginx-on-amazon-ec2-rhel-and-ubuntu-instances.html

Manually deployed SCA file into agent. There is no clear process on how to deploy application SCAs included with Wazuh into agents. Documentation is focused in custom SCAs.

Initial outcome seems correct:
![image](https://user-images.githubusercontent.com/7738867/160908393-ae659abe-b68a-4712-9be5-f5a1de508892.png)
