### ISSUE TITLE
Grouping agents

### ISSUE THREAD

**Issue by christiaanvanaken** [wazuh/wazuh#129]
Is there a possibility to add agents to a group? For example: I want to group agents from one customer to a group.

**Comment by jlruizmlg** [comment]
Hi @christiaanvanaken, we have not this possibility, instead of that, you can create group by name make easier your searches like:

For costumer1 agents:

```
costumer1-agent-1
costumer1-agent-2
```

----

For costumer2 agents:

```
costumer2-agent-1
costumer2-agent-2
```

Then you can apply profiles and agent.conf in order to deploy specific configurations to each groups, agents or OS:

```
<agent_config name=”agent01”>
...
<agent_config os="Linux">
...
<agent_config profile="UnixHost">
```

https://documentation.wazuh.com/current/user-manual/reference/centralized-configuration.html

**Comment by christiaanvanaken** [comment]
Can you please explain it a little further? :$

**Comment by jlruizmlg** [comment]
Well, we don't have an option to group the agents but you can do something similar in a different way:

Because the agent name doesn't need to be the hostname, you can add your agents with a prefix.

For example if we have two customers : ```customer1``` and ```customer2```, you can add the agents with the customer name before the agent name:

For costumer1 agents:

```
customer1-agent-1
customer1-agent-2
```
---

For customer2 agents:

```
customer2-agent-1
customer2-agent-2
 ```

this way, is easy to search in Elasticsearch, you can do something like: agent.name: customer1-*

---


Now, how can we send specific configurations to different groups?, for that we can use ```agent.conf```.

https://documentation.wazuh.com/current/user-manual/reference/centralized-configuration.html

When you have one agent installed you can add to this agent one or multiple profiles:

https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html

So for customer1 you can add a profile called ```customer1``` in your agents in the ```ossec.conf``` file:

```
<client>
      <config-profile>customer1</config-profile>
</client>
```

And for the agents in the customer2 we can add the following profile:

```
<client>
      <config-profile>customer2</config-profile>
</client>
```

Then you can create a file called agent.conf in the shared, in /var/ossec/etc/shared with the specific configuration for this profiles, something like:

```
<agent_config profile="customer1">
    <localfile>
        <location>/var/log/mysql.log</location>
        <log_format>syslog</log_format>
    </localfile>
</agent_config>
```

```
<agent_config profile="customer2">
    <localfile>
        <location>/var/log/postgresql.log</location>
        <log_format>syslog</log_format>
    </localfile>
</agent_config>
```

Wazuh will send this agent.conf to each agent, and will apply the configurations based on the profiles, so, all agents with profile ```customer1``` will have the log path ```/var/log/mysql.log``` and the agents with the profile ```customer2``` will have the log path ```/var/log/postgresql.log```.


I hope now it's a little bit more clear :)

**Comment by crolopez** [comment]
Agents can be grouped into groups from Wazuh 3.0.

More information: https://documentation.wazuh.com/current/user-manual/reference/centralized-configuration.html?highlight=groups
