### ISSUE TITLE
VD: Alerts do not generate when a vulnerable package is removed

### ISSUE THREAD

**Issue by CamiRomero** [wazuh/wazuh#12927]
# Description 

Working on Issue [#12902](https://github.com/wazuh/wazuh/issues/12902) with case number 10, we detected that the alerts are not generated when a package with a vulnerability was uninstalled/upgraded.

## Details: 

|Wazuh version |Install type| OS type |
|---|---|---|
| 4.3 | Manager | [AMI - Wazuh_v4.3.0](https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#ImageDetails:imageId=ami-0e062a80bd73a63b6)|

|Wazuh version |Install type |Platform|
|---|---|---|
| 4.2.6 | Agent| CentOS 8 |

### Local_internal_options

> wazuh_modules.debug=2
> monitord.rotate_log=0

------------

## Steps to reproduce

1. In the manager, edit /`var/ossec/etc/ossec.conf` vulnerability detection section with [Ossec.conf - VD - Manager.txt](https://github.com/wazuh/wazuh/files/8381886/Ossec.conf.-.VD.-.Manager.txt).
2. Registered and connected agent with the manager.
3. Restart Agent and Manager.
4. We detected a vulnerability alert with a package `nss-utils` on `/var/ossec/logs/alerts/alerts.log` on Manager. 
    Attach: [alert-nss-utils-found.log](https://github.com/wazuh/wazuh/files/8383006/alert-nss-utils.log)
 
5. Deleted packages with the vulnerability `nss-util` on the Agent: 
    > sudo dnf remove nss-util-3.53.1-17.el8_3.x86_6

6. Verify in the agent that the package was removed: 
    > rpm -qa | grep nss-util

7. Restart the Agent.
8. Wait for a new scan of VD in the manager.

## Results

  -  `Current Results:` The alert was not generated.
  -  `Expected Results:` An alert is generated with an explanation that the vulnerability package is solved.

---

## Evidence
We will attach logs with databases.

| ossec.log Manager | Database the agent | database manager|
|--|--|--|
|[ossec.log](https://github.com/wazuh/wazuh/files/8383082/manager.zip)|[001.db](https://github.com/wazuh/wazuh/files/8383079/001.zip)| [global.db](https://github.com/wazuh/wazuh/files/8383080/global.zip)

## Notes
- Check the database `sync_info` on the Manager using this [script](https://github.com/wazuh/wazuh/files/8382982/wdb.zip).
  
    > **Query**:     python3 wdb.py 001 'SELECT * FROM sync_info'
        **Output**: [Results-query-from-sys_info.log](https://github.com/wazuh/wazuh/files/8383028/Results-query-from-sys_info.log)

- Check the database `sys_programs` on the Manager using this script.
  
    > **Query**:     python3 wdb.py 001 'SELECT * FROM sys_programs'
        **Output**: [Results-query-from-sys_programs.log](https://github.com/wazuh/wazuh/files/8383051/Results-query-from-sys_programs.log)
  
- Check the database   vuln_cves on the Manager using this script.
    >  **Query**:     python3 wdb.py 001 'SELECT * FROM vuln_cves WHERE cve ="CVE-2021-43527"'
    **Output**: We note that the vulnerabilities status was OBSOLETE

**Comment by damarisg** [comment]
We try to reproduce but we detect that the problem was the environment setup.

This issue is closed.

**Comment by DProvinciani** [comment]
I spent some time trying to reproduce this issue without having success. The test was done with the next configurations:

|Manager OS|Manager Version|Agent OS|Agent Version|
|-|-|-|-|
|Cento 8 x64|4.3|Centos 7 x64|4.3|
|Cento 8 x64|4.3|Centos 7 x64|4.2.6|

And we used the next set of settings:

|Combination Number|VD interval|VD min_full_scan_interval|Syscollector Interval|
|-|-|-|-|
|1|1h|6h|1h|
|2|2m|1m|10m|
|3|1m|30s|10m|
|4|1m|30s|5m|
|5|30s|10s|1m|

For all the configurations and all the set of settings we got the next results:

- After finalizing the vulnerability detector scan we checked whether we had `OBSOLETE` vulnerabilities:

```
[root@localhost ~]# python3 wdb-query.py 002 'SELECT name,version,architecture FROM vuln_cves WHERE status="OBSOLETE"'
[]
```

- Then we uninstalled the `git` package in the agent as we already knew that it was vulnerable:

<img width="669" alt="image" src="https://user-images.githubusercontent.com/5703274/163064048-56b26598-6b19-4a69-b4d3-f1750727a5d8.png">

- We verified again the presence of `OBSOLETE` vulnerabilities:

```
[root@localhost ~]# python3 wdb-query.py 002 'SELECT name,version,architecture FROM vuln_cves WHERE status="OBSOLETE"'
[
    {
        "name": "git",
        "version": "1.8.3.1-23.el7_8",
        "architecture": "x86_64"
    },
    {
        "name": "git",
        "version": "1.8.3.1-23.el7_8",
        "architecture": "x86_64"
    }
]
```

And also we verified the syscollector alert of the package removed:

<img width="675" alt="image" src="https://user-images.githubusercontent.com/5703274/163064241-6420a58a-42e3-40e4-948c-279e42abf7dd.png">

- After waiting for the Vulnerability Detector scan, we confirmed the alert generation:

<img width="673" alt="image" src="https://user-images.githubusercontent.com/5703274/163064326-45cbf47f-bd38-4fd0-9585-f6f9a83f1d21.png">

The procedure was repeated multiple times by installing and uninstalling the `git` package and the issue was never reproduced.

**Comment by damarisg** [comment]
I tried to reproduce this issue, but I couldn't get the same results reported.

The configuration was: 

|Manager OS|Manager Version|Agent OS|Agent Version|
|-|-|-|-|
|AMI - Amazon Linux 2 |4.3|Centos 7 x64|4.2.6|

And we used the next set of settings:

|VD interval|VD min_full_scan_interval
|-|-|
|1m|30s|
--- 

I tested :

- [ ] Case 1:  Install a vulnerable package (in this case nss-tools):
       Case 1 - Output: The alert is generated.

- [ ] Case 2: Remove the vulnerable package (in this case nss-tools):
       Case 2 - Output: The alert generated is reported that is solved.
       ![imagen](https://user-images.githubusercontent.com/3978434/163251964-99e56bd6-d372-4363-a7a7-f5734211d98a.png)


**Conclusion:** 

Unfortunately, I was unable to reproduce this error. We have to be careful when we start testing this to see if it plays again.
For now, I think the best option is to close this issue.
