### ISSUE TITLE
Engine - Wazuhdb support

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh#13038]
| Wazuh version | Component | Install type | Install method   | Platform   |
| ------------- | --------- | ------------ | ---------------- | ---------- |
| 5.0.0         | Engine    | Manager      | Packages/Sources | OS version |

Because the current analysisd stores some events into wazudb, the new
engine versions need to support this feature.

We need to create a wazudb client, and then use it to build an output
of the engine, which will store events into the wazudb as defined in
that output.

The parameter list to support depends on the current capabilities of
analysisd.

- [x] Analyze wazudb usage by analysis:
    - #13518 

- [x] Implement the wazudb client:
    - #13519
    - #13520
    - #13521 
    - #13522 
    - #13523 
    - #13524
    - Implement tests and benchmarks

|             Devel branch                  |
| ------------------------------------------ |
| 13038-engine-wazuhdb-support |

**Comment by juliancnn** [comment]
# Interaction between Wazuh-DB & Wazuh-Analaysisd

Wazuh-Analysisd communicates on demand with Wazuh-DB. Analysysd receives events/logs from the agents, through its socket [queue/sockets/queue](https://github.com/wazuh/wazuh/blob/dacf07da9930c4445ea55b1e5cdf6c7baea9a8d6/src/analysisd/analysisd.c#L1156). 
Events comply with the standard[ OSSEC message format](https://documentation.wazuh.com/current/development/message-format.html):

`<Queue>:<Location>:<Message>`

- **Queue**:  1-byte event type. It defines the decoding mode for Analysis daemon.
- **Location**: Origin, Log source/module src + Agent ID
- **Message**: Content of the log.

## DBSync (Manager)
**Queue: `'5'` / `0x35` / `DBSYNC_MQ`**

![image](https://user-images.githubusercontent.com/1891958/168679974-820b4476-1fc7-4e10-81e7-7305806871fa.png)


At the moment, the agents' and managers' databases synchronization is performed inside wazuh-analysisd. DBSync messages are received through the same queues as the unprocessed log messages, but they don't go through the decoding and rule matching stages. DBSync events are identified with the queue id 5 ([DBSYNC_MQ](https://github.com/wazuh/wazuh/blob/dacf07da9930c4445ea55b1e5cdf6c7baea9a8d6/src/analysisd/analysisd.c#L1337)), which allows analysisd to identify such messages to be treated in a specific way by using the [DispatchDBSync()](https://github.com/wazuh/wazuh/blob/dacf07da9930c4445ea55b1e5cdf6c7baea9a8d6/src/analysisd/decoders/dbsync.c#L257) method.

When synchronizing the [databases of the manager and its embedded agent, ](https://github.com/wazuh/wazuh/blob/dacf07da9930c4445ea55b1e5cdf6c7baea9a8d6/src/analysisd/decoders/dbsync.c#L104)as they don't use the same databases, wazuh-analysisd establishes direct communication with the syscollector and syscheck modules through their queues. On the other hand, when synchronizing a remote agent, the queue to be used is the remoted one ([queue/alerts/ar](https://github.com/wazuh/wazuh/blob/dacf07da9930c4445ea55b1e5cdf6c7baea9a8d6/src/analysisd/decoders/dbsync.c#L64)).


- Queries to the wazuhdb have the format `<component> <query>`, and the messages protocol uses the same header as the secureTCP communication, where the message size is specified.
- Messages can be 64K long at most.

## Syscollector
**Queue: `'d'` / `0x64` / `SYSCOLLECTOR_MQ`**

The [DecodeSyscollector()](https://github.com/wazuh/wazuh/blob/1aebe7d6806786e544044a69f633555036400465/src/analysisd/decoders/syscollector.c#L216) method is in charge of handling the syscollector events, which are identified by the queue id `0x64` ([SYSCOLLECTOR_MQ](https://github.com/wazuh/wazuh/blob/59b90c7a0cf585e01b3f915900adfd5faea499e5/src/headers/mq_op.h#L32)). Every hour, by default, the agents send to the manager information related to their systems which are processed by this decoder. As in SCA, this method receives a json object from where it obtains the event `/type` to determine what to do with it and how to create the wazuhdb query.

Up to Wazuh 4.3, the wazuhdb queries related to syscollector do not enrich the event but its only purpose is to keep the database synchronized. Legacy functions:
- `decode_port`
- `decode_package`
- `decode_hotfix`
- `decode_hardware`
- `decode_osinfo`
- `decode_netinfo`
- `decode_process`

From Wazuh 4.4, the [Decode_dbsync() ](https://github.com/wazuh/wazuh/blob/1aebe7d6806786e544044a69f633555036400465/src/analysisd/decoders/syscollector.c#L2071)method was developed to enrich the incoming event by querying the wazuhdb. The received event only includes the new/modified fields (deltas) instead of the whole data. When doing an Update or Delete operation, the data is fully retrieved to be processed.

## Syscheck/FIM
**Queue: `'8'` / `0x38` / `SYSCHECK_MQ`**

In this case, it is identified by the id `'8'` (SYSCHECK_MQ) and will push to the rules queue after being decoded. 
If the agent has 3.1.1 version or older, the event received will be in .log format and handled by "DecodeSyscheck". If not it will be taken by "decode_fim_event".
The format is used to determine the event version, being the later FIM messages on .json.

### New F.I.M. module:
This is the only one that has a well-documented event format.
Functions used by the wdb module:

- `Fim_db_search`: interactive query mode, it can use previous query results data on new ones, e.g. by using fim_update_date.
- `Fim_get_scantime`: Searchs for scan-time from db.
- `Fim_control_msg`: Query without using the returned value (e.g. delete). 
- `Fim_update_date`: DITTO
- `Fim_database_clean`: DITTO
- `Wdbc_query_ex`: DITTO

<details>
<summary>Message format CLICK ME</summary>

```json
{
   "type":                  "event"
   "data": {
     "path":                string
     "hard_links":          array
     "mode":                "scheduled"|"realtime"|"whodata"
     "type":                "added"|"deleted"|"modified"
     "timestamp":           number
     "changed_attributes": [
       "size"
       "permission"
       "uid"
       "user_name"
       "gid"
       "group_name"
       "mtime"
       "inode"
       "md5"
       "sha1"
       "sha256"
     ]
     "tags":                string
     "content_changes":     string
     "old_attributes": {
       "type":              "file"|"registry"
       "size":              number
       "perm":              string
       "user_name":         string
       "group_name":        string
       "uid":               string
       "gid":               string
       "inode":             number
       "mtime":             number
       "hash_md5":          string
       "hash_sha1":         string
       "hash_sha256":       string
       "win_attributes":    string
       "symlink_path":      string
       "checksum":          string
     }
     "attributes": {
       "type":              "file"|"registry"
       "size":              number
       "perm":              string
       "user_name":         string
       "group_name":        string
       "uid":               string
       "gid":               string
       "inode":             number
       "mtime":             number
       "hash_md5":          string
       "hash_sha1":         string
       "hash_sha256":       string
       "win_attributes":    string
       "symlink_path":      string
       "checksum":          string
     }
     "audit": {
       "user_id":           string
       "user_name":         string
       "group_id":          string
       "group_name":        string
       "process_name":      string
       "cwd":               string
       "audit_uid":         string
       "audit_name":        string
       "effective_uid":     string
       "effective_name":    string
       "parent_name":       string
       "parent_cwd":        string
       "ppid":              number
       "process_id":        number
     }
   }
 }

Scan info "events":
{
  "type":                  "scan_start"|"scan_end"
  "data": {
    "timestamp":           number
  }
}

```

</details>

### Legacy Syscheck module:
The event is pre-processed before using fim_db_search and fim_control_msg

<details>
<summary>Legacy message format. CLICK ME</summary>

```
Every syscheck message must be in the following format (OSSEC - Wazuh v3.10):
'checksum' 'filename'
 or
 'checksum'!'extradata' 'filename'
 or
                                             |v2.1       |v3.4  |v3.4         |v3.6  |v3.9               |v1.0
                                             |->         |->    |->           |->   |->                  |->
 "size:permision:uid:gid:md5:sha1:uname:gname:mtime:inode:sha256!w:h:o:d:a:t:a:tags:symbolic_path:silent filename\nreportdiff"
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^checksum^^^^^^^^^^^^^^^^^^^^^^^^^^^!^^^^^^^^^^^^^^extradata^^^^^^^^^^^^^^^^ filename\n^^^diff^^^
```

</details>

## CIS-CAT
**Queue: `'e'` / `0x65` / `CISCAT_MQ`**

DecodeCiscat, idetified by the decoder ID 'e' (CISCAT_MQ). Shares the same thread with syslog.
CIS-CAT json logs are first parsed, if that results ok and the event contains a non-null `/type` field then it will be delivered to the rule stage without previously passing through decoders.
When field `/type` matches `scan_info` it will query that scan to wazuh db.
DB query format has this format:

```
agent <agent_id> ciscat save PARAM1 | PARAM2 | PARAM3 ….
```

## SCA
**Queue: `'p'` / `0x70` / `CISCAT_MQ`**

The [DecodeSCA()](https://github.com/wazuh/wazuh/blob/dacf07da9930c4445ea55b1e5cdf6c7baea9a8d6/src/analysisd/decoders/security_configuration_assessment.c#L168) method is in charge of handling the SCA events, which are identified by the queue id 0x70 (SCA_MQ). Each new incoming message triggers the wazuhdb synchronization and retrieves its previous state to enrich the event.

It seems that only the `FillScanInfo()` and `FillCheckEventInfo()` modify the original event.
When enriching the event, the previous scan is stored on a new field called "sca.check.previous_result". This previous state is then matched with the rules to look for changes.
