### ISSUE TITLE
Wazuh DB: the previous group does not assign when guess mechanism is active

### ISSUE THREAD

**Issue by CamiRomero** [wazuh/wazuh#13054]
# Description 

If an agent with a group is removed and registered again and the guess mechanism is active, if you check the group that the agent is registered you can note that the group is `default`.

------------------------------------------------------------------------------------------------------------------------------------------------

# Details: 

|Wazuh version|Install type| Branch| Platform|
|---|---|---|---|
| 4.4 | Manager | dev-10771-agent-groups-files-to-wazuh-db | Centos8 |

------------
## Steps to reproduce

1. Edit /var/ossec/etc/local_internal_options.conf on manager and workers with:

      > remoted.guess_agent_group=1

2. Restart the manager and workers in order to apply the configuration

3. Register an agent with `agent-auth`:

      > /var/ossec/bin/agent-auth -m {manager_ip} -A {agent_name} -I {agent_ip}

4. Assign group to agent:

      > /var/ossec/bin/agent_groups -q -a -g {id_group}
      > /var/ossec/bin/agent_groups -q -a -i {id_agent} -g {id_group}

5. Check with `agent group` if the agent registered in step 3 assign to `group group` test

      > var/ossec/bin/agent_groups -s -i {agent_id}

7. Delete agent with `manage_agents`:

     > var/ossec/bin/manage_agents -r {agent_id}

8. Remove `client.keys` on agent

9. Repeat step 3
 
10. Check with `agent_group` if the agent registered in step 3 assign to `group_test` test

### Results

  -  `Current Results:` The agent assign to group `default`
  -  `Expected Results:` The agent assign to group `group_test`

--- 
### Evidence

- [Master log](https://github.com/wazuh/wazuh/files/8420925/mater.log)

- [Worker log](https://github.com/wazuh/wazuh/files/8420928/worker1.log)

- [Cluster log](https://github.com/wazuh/wazuh/files/8420932/cluster.log)

![imagen](https://user-images.githubusercontent.com/37776796/161825937-fc9a7841-d338-4d7c-94ed-3f7ed55a5697.png)
![imagen](https://user-images.githubusercontent.com/37776796/161826237-32259423-0bc3-4e40-a57b-b728246664c1.png)
![imagen](https://user-images.githubusercontent.com/37776796/161826448-eb38b317-e0ac-44bf-a9b6-1c66c03697f4.png)

**Comment by pereyra-m** [comment]
### Update

It was found that the group guess feature isn't working in the `master` branch.
We can see in the images that even when there is MD5 match, the groups **default** is assigned.

![guess_1](https://user-images.githubusercontent.com/65046601/162000723-1ce26591-dd61-487e-912e-00129abbb437.png)

![guess_2](https://user-images.githubusercontent.com/65046601/162000751-8bbf81bd-7393-4a76-a00d-f874219c837d.png)

After the fix is solved and merged in the development branch, we should run these tests again.

**Comment by DProvinciani** [comment]
As the fix for https://github.com/wazuh/wazuh/issues/13071 was implemented in **master** and then ported to the **dev-10771-agent-groups-files-to-wazuh-db** branch, we executed the tests again over the last one and now, all the tests are passing successfully.

[tests-results-13054.zip](https://github.com/wazuh/wazuh/files/8451084/tests-results-13054.zip)

Having said that, we close this issue.
