### ISSUE TITLE
Failures in API Integration tests when a response is unordered

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#13069]
|Wazuh version|Component|
|---|---|
| Master | Wazuh API integration tests |

## Description

Sometimes a test can fail when the order of the answer is not the expected one. For instance, this `GET /agents/upgrade_result` failed because the agents in the response were `006`, `005`, `007` instead of  `005`, `006`, `007`:
```
AssertionError: assert [{'agent': '006', 'task_id': 1},\n {'agent': '005', 'task_id': 2},\n {'agent': '007', 'task_id': 3}] == [{'agent': '005',\n  'task_id': <tavern.util.loader.IntSentinel object at 0x7ff520fac280>},\n {'agent': '006',\n  'task_id': <tavern.util.loader.IntSentinel object at 0x7ff520fac1c0>},\n {'agent': '007',\n  'task_id': <tavern.util.loader.IntSentinel object at 0x7ff520fac130>}]
```

It would be necessary to investigate why `tavern` considers this incorrect. It could be related to the fact that the answer is a list, which does preserve the order, unlike dictionaries.

It should also be studied if it is an error when the socket does not return the expected order or if, on the contrary, it is an expected/acceptable behavior.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by mcarmona99** [comment]
## Issue update

`tavern` is raising an assertion error because we are comparing 2 lists of dictionaries that contain the same dictionaries but in a different order. If list **A** contains dictionaries `dikt1` and `dikt2` (in that order); and list **B** contains dictionaries `dikt2` and `dikt1` (in that order), **list A is not equal to list B**. If we were talking about comparing dictionaries, 2 dictionaries would be equal if the items were the same, independently of their order.

In conclusion, this assertion error is correct and the test needs to be fixed.


First of all, I am going to verify that for the "upgrade agents" action, the response is sorted by `task_id`. For the "get upgrade results" action, the response is sorted by `agent`. 

When sending the message to the upgrade socket, we have 2 possibilities:

- Upgrade agents
- Get agents upgrade results





**Upgrading agents:**

MSG sent

`{'version': 1, 'origin': {'module': 'api'}, 'command': 'upgrade','parameters': {'agents': [5, 6], 'version': 'v4.4.0', 'force_upgrade': False, 'use_http': False}}`

MSG received

`{'error': 0, 'data': [{'error': 0, 'message': 'Success', 'agent': 5, 'task_id': 25}, {'error': 0, 'message': 'Success', 'agent': 6, 'task_id': 26}], 'message': 'Success'}`



MSG sent

`{'version': 1, 'origin': {'module': 'api'}, 'command': 'upgrade','parameters': {'agents': [8, 7, 6, 5], 'version': 'v4.4.0', 'force_upgrade': False, 'use_http': False}}`

MSG received

`{'error': 0, 'data': [{'error': 0, 'message': 'Success', 'agent': 5, 'task_id': 29}, {'error': 0, 'message': 'Success', 'agent': 6, 'task_id': 30}, {'error': 0, 'message': 'Success', 'agent': 7, 'task_id': 31}, {'error': 0, 'message': 'Success', 'agent': 8, 'task_id': 32}], 'message': 'Success'}`


**Get agents upgrade results:**

MSG sent

`{'version': 1, 'origin': {'module': 'api'}, 'command': 'upgrade_result','parameters': {'agents': [5, 6, 7, 8]}}
`

MSG received

`{'error': 0, 'data': [{'error': 0, 'message': 'Success', 'agent': 5, 'task_id': 29, 'node': 'master-node', 'module': 'upgrade_module', 'command': 'upgrade', 'status': 'Error', 'error_msg': 'The WPK file does not exist', 'create_time': '2022/04/12 09:32:49', 'update_time': '2022/04/12 09:33:01'}, {'error': 0, 'message': 'Success', 'agent': 6, 'task_id': 33, 'node': 'master-node', 'module': 'upgrade_module', 'command': 'upgrade', 'status': 'Error', 'error_msg': 'The version of the WPK does not exist in the repository', 'create_time': '2022/04/12 10:03:54', 'update_time': '2022/04/12 10:03:55'}, {'error': 0, 'message': 'Success', 'agent': 7, 'task_id': 31, 'node': 'master-node', 'module': 'upgrade_module', 'command': 'upgrade', 'status': 'Error', 'error_msg': 'The version of the WPK does not exist in the repository', 'create_time': '2022/04/12 09:32:49', 'update_time': '2022/04/12 09:32:49'}, {'error': 0, 'message': 'Success', 'agent': 8, 'task_id': 32, 'node': 'master-node', 'module': 'upgrade_module', 'command': 'upgrade', 'status': 'Error', 'error_msg': 'The version of the WPK does not exist in the repository', 'create_time': '2022/04/12 09:32:49', 'update_time': '2022/04/12 09:32:49'}], 'message': 'Success'}`




**Conclusion**: for the "upgrade agents" action, the response is sorted by `task_id`; for the "get upgrade results" action, the response is sorted by `agent`. _UPDATE_: I have found a response example for the "upgrade agents" action where the result is sorted by agent: `[{'agent': '005', 'task_id': 1}, {'agent': '006', 'task_id': 3}, {'agent': '007', 'task_id': 2}]`. This means that the results are not ordered (from the socket) and neither `task_id` nor `agent` are the fields the response is sorted by.

The problem then is a lack of sorting in the framework itself.

**Comment by mcarmona99** [comment]
## Issue update

After this investigation, we have added the sort feature to the framework functions in charge of upgrading agents and getting agents upgrade results.

Before creating the pull request, we have decided to make profiling of these functions with the new changes added.

These changes consist of removing the sort done to the agents list before sending the message to the upgrade socket; and adding it at the end of the function, in the affected items. 

When the upgrade endpoints were refactored to add filters and remove limitations, we did a few tests to see how much time the agents were taking to be upgraded.

These tests can be seen here: https://github.com/wazuh/wazuh/issues/9504#issuecomment-933409583

There was a linear tendency, and we saw that for the actual API default timeout (10s), we could upgrade 3000 agents in the same request. As it was said in the issue, this depends on the host machine so for the new profiling, I will use the same machine I used to measure times.

### Before changes

We will use the following table as a reference to see if the times taken after the changes done for this issue (sort at the end instead of at the beginning) are better, worse or equal. (This table was obtained by measuring again. This way, times in both sections (before and after) are measured in the same machine)

| N° of agents | Time |
| ---- | --- |
| 1000 | 3.159s |
| 2500 | 7.881s |
| 3000 | 13.171s |
| 4000 | 17.254s |
| 5000 | 23.339s |


### After changes




| N° of agents | Time |
| ---- | --- |
| 1000 | 3.726s |
| 2500 | 9.451s |
| 3000 | 12.453s |
| 4000 | 19.974s |
| 5000 | 25.271s |


As we can see, times are slighlty higher. This could be due to the fact that sorting a list of dicitonaries is more complex (in time) than sorting a list of integers. Anyway, this little difference will not highly affect the endpoint performance, as the machine used for these tests has really low specifications.

Therefore, I will add this change and its respective API integration tests changes (and unittests).

**Comment by mcarmona99** [comment]
Blocked by https://github.com/wazuh/wazuh/pull/13201
