### ISSUE TITLE
[feature request] Create functionality that allows you to ignore directories/files created by ansible

### ISSUE THREAD

**Issue by mradaszewski92** [wazuh/wazuh#13075]
|Wazuh version|Component|
|---|---|
| 4.5 | FIM |

it's about Red Hat 7 and Red Hat 8 systems
Due to the fact that in large environments we use Ansible, which generates a lot of changes in the system (very often it leads to exhaustion of inotify limits), there was a need for the wazuh agent to be able to ignore directories/files through regular expressions

for example:
`
<ignore>/home/regex_for_username/.ansible</ignore>
`
Ansible is generating so much change, which leads to a huge amount of noise and clutter in your FIM.

thanks to this solution it will save a lot of computing power, because ansible creates temporary files (especially in /home directories) and then deletes them, so Wazuh has to suddenly add a whole bunch of new files, and then has to delete it, because after the playbook is finished, ansible cleans up after itself

**Comment by FrancoRivero** [comment]
Hi @mradaszewski92, 
Thank you for using Wazuh! 
We have a way to ignore files  if you don't know you can read [here](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/fim-configuration.html#configuring-ignoring-files-via-rules).
To write the rules you should have some considerations, for instance, you should follow [the next format](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html) to write the rules and [the next format](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html) to write regex syntax.
For other side, we have a [issue](https://github.com/wazuh/wazuh/issues/7230) to modify real-time monitoring because we are adding watches inside `Inotify` though some file does not be monitoring.
Hope to work for you !
Regards

**Comment by mradaszewski92** [comment]
Hello @FrancoRivero 

I think this is not the same case. In this case, the idea is not to ignore alerts at the rule level, but to ignore directories at the vase / operating system level. I already know that you can ignore certain alerts at the rule level, but in this case the point is that the number of changes generated by ansible is so huge that we cannot predict how many there will be, so ignoring certain directories will help reduce the load on the systems

**Comment by FrancoRivero** [comment]
Hello @mradaszewski92,
We are concerned about this limitation, in future versions we are working to solve it. 
You can follow this development in[ the above mentioned issue](https://github.com/wazuh/wazuh/issues/7230). 
Regarding to your question we don't have a solution right now, as I said before we are working in solved it. I recommend to set more specific directories for your configuration to avoid the Ansible files at the moment that can be a solution, I mean FIM is a module to monitor critical files then it must avoid to add in the configuration volatile folders and add important files which shouldn't change.
Regards
