### ISSUE TITLE
SPIKE - Pacman debuginfo packages

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#13080]
| Epic |
|---|
| wazuh/wazuh#9913|

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| dev-debug-symbols| Packages generation | Manager/Agent | Packages | Arch Linux |

## Description

This issue aims to get a better understanding of what is needed for generating Pacman debuginfo packages.
Ref: https://github.com/wazuh/wazuh-packages/tree/master/arch

## DoD
- [ ] Understand Arch Linux packages generation
- [ ] Research about debug info approach taken on Arch Linux package manager (Pacman)
- [ ] In case Pacman support debuginfo packages, this approach will be taken
- [ ] Otherwise, tar.gz with debug symbols approach will be taken
- [ ] Post in this issue every R&D step and conclusions

**Comment by RamiroRD** [comment]
The package build process is broken for 4.2 and 4.3 and there is an existing issue to fix this: https://github.com/wazuh/wazuh-packages/issues/1273. 
Therefore, we cannot yet work on creating a debug package until this issue is solved.
However, as part of this spike, it should be noted that Arch only recently [started supporting debug packages](https://archlinux.org/news/debug-packages-and-debuginfod/). More info about this [here](https://wiki.archlinux.org/title/Debugging/Getting_traces#Install_debug_packages).

Also, debugging symbols generation and installation when compiling from sources is working correctly on Arch. Evidence here:
![Screen Shot 2022-04-26 at 16 41 38](https://user-images.githubusercontent.com/6182640/165379400-1a344ebb-0b86-4928-93f7-65e94a1d36aa.png)
![Screen Shot 2022-04-26 at 16 47 22](https://user-images.githubusercontent.com/6182640/165380291-bdae5b15-5235-490c-8ca7-473855deb426.png)
