### ISSUE TITLE
VirusTotal integration - Delay in response

### ISSUE THREAD

**Issue by mingo-devsec** [wazuh/wazuh#13205]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.6 | Integrator | Manager/Agent | AWS with Kubernetes | Centos 7 |

Not always, but often we see some delay between the FIM syscheck event and VirusTotal response. Attached are the respective alerts. 

```
{"timestamp":"2022-04-14T13:10:19.744+0000","rule":{"level":12,"description":"File added.",......,"location":"syscheck"}

{"timestamp":"2022-04-14T13:16:15.977+0000","rule":{"level":12,"description":"VirusTotal....,"location":"virustotal"}

```
This found on `integration.log`
```
Thu Apr 14 13:10:19 UTC 2022 /tmp/virustotal-1649941819--565426041.alert api_key   > /dev/null 2>&1
```
About integrator debug
![image](https://user-images.githubusercontent.com/74078426/164558903-e75b82da-5990-46ac-88d0-43da47a2ace2.png)

**Comment by TomasTurina** [comment]
## Update

### Environment:

- Wazuh manager.
- OS: Ubuntu 20.04.
- RAM: 8192MB.
- CPU: 4 processors.
- Disk: SSD

### Tests

I have tested VirusTotal's delays by generating `syscheck` alerts every 0.1 seconds for the following scenarios:

#### Scenario 1

Default VirusTotal `integratord` script:
- For 100 alerts, the integration has a delay of about 80 seconds (0.80s per alert)
- For 500 alerts, the integration has a delay of about 390 seconds (0.78s per alert)

#### Scenario 2

Modified VirusTotal `integratord` script so that it does not call the VirusTotal API and returns a hardcoded response:
- For 100 alerts, the integration has a delay of around 24 seconds (0.24s per alert)
  - Comparing with scenario 1, it is observed that around 71% of the time is consumed by the VirusTotal API request.
- For 500 alerts, the integration has a delay of around 105 seconds (0.21s per alert)
  - Comparing with scenario 1, it is observed that around 73% of the time is consumed by the VirusTotal API request.

#### Scenario 3

VirusTotal AR script (based on the one from `integratord`):
- For 100 alerts, the AR has a delay of around 74 seconds (0.74s per alert)
  - Comparing with scenario 1, it can be seen that `integratord` consumes around 7% of the time for its disk operations.
- For 500 alerts, the AR has a delay of around 360 seconds (0.72s per alert)
  - Comparing with scenario 1, it can be seen that `integratord` consumes around 8% of the time for its disk operations.

#### Scenario 4

Modified VirusTotal AR script so that it does not call the VirusTotal API and returns a hardcoded response:
- For 100 alerts, the AR has a delay of around 19 seconds (0.19s per alert)
  - Comparing with scenario 2, it can be seen that `integratord` consumes around 18% of the time for its disk operations.
  - Comparing with scenario 3, it is observed that around 73% of the time is consumed by the VirusTotal API request.
- For 500 alerts, the AR has a delay of around 80 seconds (0.16s per alert)
  - Comparing with scenario 2, it can be seen that `integratord` consumes around 24% of the time for its disk operations.
  - Comparing with scenario 3, it is observed that around 77% of the time is consumed by the VirusTotal API request.

### Results

Based on the results, it is clear that the large delay time is consumed by the VirusTotal API call itself (about 75% of the time), so parallelizing these could be a solution as currently both `integratord` and AR are single threaded.
On the other hand, improvements of around 10% can be seen using AR instead of `integratord`, added to the fact that in AR there would be no problem with `alerts.json` file since the alerts are not consumed from there.

### Configuration and scripts

#### AR configuration:

```
<command>
    <name>virustotal</name>
    <executable>virustotal.py</executable>
    <extra_args>cfa079dd7c7c8ba311638fda953f46597957318c999324bfd3582d5f1fd50>
    <timeout_allowed>no</timeout_allowed>
</command>

<active-response>
    <disabled>no</disabled>
    <command>virustotal</command>
    <location>server</location>
    <rules_group>syscheck</rules_group>
</active-response>
```

#### AR script:

[virustotal.txt](https://github.com/wazuh/wazuh/files/8567643/virustotal.txt) -> rename to `virustotal.py` and make it executable.

**Comment by maumrsms** [comment]
Hello team,

Apparently the issue was due to a customization in the VirusTotal script that would make it run a query to Splunk related to the alert. After removing such customization, the VirusTotal integration worked withou any delays as expected.
