### ISSUE TITLE
in ubuntu 22.02 jammy vulnerability detection

### ISSUE THREAD

**Issue by luruibu** [wazuh/wazuh#13219]
Provides compatibility，please

**Comment by MarcelKemp** [comment]
Hi @luruibu,

Until today, we couldn't support it because there was no OVAL for **_Ubuntu 22_**, however they just uploaded the OVAL skeleton ([link](https://security-metadata.canonical.com/oval/com.ubuntu.jammy.cve.oval.xml.bz2)), so we can start developing the support in Vulnerability Detector, which is in the next issue: 
- https://github.com/wazuh/wazuh/issues/13162

We will try to support it as soon as possible, in the meantime, a workaround to use _Vulnerability Detector_ for _Ubuntu 22_ is to use the `os allow` option in the configuration, where you can configure other Ubuntu feeds (like `Focal`) to try to detect vulnerabilities. Although you have to take into account that since it is not its corresponding feed, it can produce some false positives.

Below I share the guide for the `os allow` option (OS not officially supported):
https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/allow-os.html

If you have any questions, don't hesitate to ask.

**Comment by luruibu** [comment]
thanks bro
https://user-images.githubusercontent.com/45596591/165547008-5fd3bb3e-fba8-4a48-820d-ea51eeaba1f8.MOV

**Comment by chemamartinez** [comment]
Hi @luruibu,

Let me close this issue since the development to support Ubuntu 22.04 has been already merged https://github.com/wazuh/wazuh/pull/13263.

Thanks for your feedback!
