### ISSUE TITLE
Release 4.3.0 - Manual test - Amazon Cloudtrail integration

### ISSUE THREAD

**Issue by mauceballos** [wazuh/wazuh#13242]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                       |                                            |
|-----------------------|--------------------------------------------|
| **Test name**         |  Amazon Cloudtrail integration Quickstart - on Ubuntu                                      |
| **Category**          | Cloud security                                        |
| **Deployment option** | Quickstart - on Ubuntu                                           |
| **Main release issue** | https://github.com/wazuh/wazuh/issues/10954                                           |
| **Release candidate #** | RC6                                          |

## Test description

Test that the following proof of concept cases work in 4.3.0:
- Use the new WUI for quickstart to Install on Ubuntu with the Amazon Cloudtrail integration.

## Test report procedure

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results must be attached as a zip or txt. Please attach any documents, screenshots or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|:green_circle:|Manager installation|||
|:green_circle:|Agent installation|||
|:green_circle:|AWS dashboard in Wazuh||

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @davidjiglesias
- [x] @CarlosRS9

**Comment by mauceballos** [comment]
# Test results
## 1. Manager installation

### 1.1 
I created a virtual machine with these specs:
- **RAM:** 8 GB
- **CPU cores:** 4
- **Disk space:** 10 GB
- **SO:** Ubuntu 20.04

After that, I run this:
```
curl -sO https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/4.3/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
```

![Screenshot from 2022-04-26 15-43-34](https://user-images.githubusercontent.com/76791841/165370132-ef6ff662-8d86-48ca-af0d-a17fa8bdcb78.png)

**Comment by mauceballos** [comment]
We need access credentials to set the S3 bucket

I add this [issue](https://github.com/wazuh/wazuh/issues/13245)

**Comment by Mayons** [comment]
# Test results
## 1. Manager installation

### 1.1 First attempt (Installation OK :green_circle:)
I created a virtual machine with these specs:
- **RAM:** 4 GB
- **CPU cores:** 2
- **Disk space:** 30 GB
- **SO:** Ubuntu 18.04

After that, I run this:
```
curl -sO https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/4.3/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
```


<details>
  
![Screenshot from 2022-04-27 12-25-59](https://user-images.githubusercontent.com/33849347/165595545-9e62dd09-23d3-470c-a8fe-26690e1358b9.png)


</details>

**Comment by Mayons** [comment]
## 2. Agent installation
- **RAM:** 2 GB
- **CPU cores:** 1
- **Disk space:** 20 GB
- **SO:** Ubuntu 20.04

### 2.1 First attempt (from sources :green_circle: )
I followed the Linux -> APT steps listed [here](https://documentation-dev.wazuh.com/3865_installation_guide_rework/deployment-options/wazuh-from-sources/wazuh-agent/index.html) to install a Wazuh agent from sources. 
I have to use the package: https://github.com/wazuh/wazuh/archive/v4.3.0-rc6.tar.gz

<details>

 
![Screenshot from 2022-04-27 15-11-38](https://user-images.githubusercontent.com/33849347/165596362-9a49c2f3-0031-42e3-99d3-ebb579eaff62.png)

![Screenshot from 2022-04-27 15-11-16](https://user-images.githubusercontent.com/33849347/165596264-c1f9bb48-b93a-4104-bca8-0e420977ad02.png)
![Screenshot from 2022-04-27 15-13-10](https://user-images.githubusercontent.com/33849347/165596314-97747721-708a-467f-95e4-74e480666103.png)



</details>

**Comment by Mayons** [comment]
## 3. Cloudtrail
### 3.1 Configuring an S3 Bucket :red_circle: 
I followed the instructions in this section: [Configuring an S3 Bucket](https://wazuh.com/blog/integrating-aws-cloudtrail-in-wazuh). 
I can't perfom this settings, I found the following error message: 


### 3.2 Configuring AWS credentials :black_circle: 
Not tested because my AWS account does not have permissions to do this. Anyway, it is not the main part of cloudtrail testing.

I added the credentials I was given to a file inside `~/.aws/credentials` as explained in the documentation.

### 3.3 Installing dependencies :green_circle: 
These instructions worked correctly: [Installing dependencies](https://documentation-dev.wazuh.com/4.3-rc/amazon/services/prerequisites/dependencies.html).

### 3.4 Amazon configuration :yellow_circle: 
I followed the instructions on this section: [Amazon configuration](https://documentation-dev.wazuh.com/4.3-rc/amazon/services/supported-services/cloudtrail.html#amazon-configuration).

The screenshots are outdated, the AWS interface is different now. However, the fields to fill in are very similar so this should not be a problem.

I was unable to finish cloudtrail activation due to lack of permissions on my account, although I was able to follow the instructions easily.

### 3.5 Cloudtrail/agent configuration :green_circle: 
I followed the instructions on this section: [Wazuh configuration](https://documentation-dev.wazuh.com/4.3-rc/amazon/services/supported-services/cloudtrail.html#wazuh-configuration).

1. Added this configuration block to the `ossec.conf`:
```
  <wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>10m</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>yes</skip_on_error>
    <bucket type="cloudtrail">
      <name>aws-cloudtrail-logs-XXXX</name>
      <aws_profile>default</aws_profile>
      <regions>us-east-1</regions>
    </bucket>
  </wodle>
```

2. Restarted Wazuh service.
3. Events showed up at `/var/ossec/logs/archives/archives.log` and alerts were created at `alerts.log`

### 3.6 Dashboard :yellow_circle:
- The AWS module in the Wazuh App is disabled by default and its existence is not mentioned in the documentation, at least in the AWS section. Users might not get the full potential of the AWS integration if they don't enable it.
  ![image](https://user-images.githubusercontent.com/23361101/160775759-971d9aa9-229a-49ec-9313-16deeeb9fba6.png)
 
  The steps to activate it should be explained, for example in the [Considerations for configuration](https://documentation-dev.wazuh.com/4.3-rc/amazon/services/prerequisites/considerations.html) section of the documentation.

- The AWS dashboard is not showing information about accounts or regions (maybe related with using only Cloudtrail).
![image](https://user-images.githubusercontent.com/23361101/160782296-de41b54f-53f0-4c7b-a318-93b71e9afb0f.png)

### 3.7 Events/alerts :green_circle:
These are the alerts that cloudtrail has already captured during the current day, before I take any action.
![image](https://user-images.githubusercontent.com/23361101/160781228-8414ac8a-5faa-4112-810e-ebaeda63a59e.png)

I will try different use cases and check if new alerts are raised:

#### 3.7.1 Multiple failed logins
I tried to login multiple times using wrong credentials (password and MFA code) and alerts were created in the AWS integration, as shown below:
![image](https://user-images.githubusercontent.com/23361101/160803102-a5bce21f-59da-4206-bd46-cefbc8f59ef8.png)

Within the alerts there is information about the user with whom the login was attempted, among other details. There is a level 10 alert for `Possible break in attempt`. 

#### 3.7.2 Delete S3 bucket
After deleting a bucket, the corresponding alert is shown:

![image](https://user-images.githubusercontent.com/23361101/160808927-ce7696bc-1415-49fd-a306-f60a706a6703.png)
![image](https://user-images.githubusercontent.com/23361101/160809029-2cf82d59-b71c-44b0-b59b-907fcb4fda58.png)

#### 3.7.3 List groups
When I try to list IAM groups, an alert is created with my user name:
![image](https://user-images.githubusercontent.com/23361101/160812556-a5f33e2e-3c96-4201-ba34-4d3769892574.png)

#### 3.7.4 Login using TOR
I logged in through the TOR network. A `login successful` alert appears although it is not reported whether it is from an unusual location or from a tor exit node, as it is suggested in [the eighth use case](https://trainnix.com/resources/f/threat-hunting-in-aws-part-ii---important-and-critical-use-cases). 
![image](https://user-images.githubusercontent.com/23361101/160815945-ebce34ce-43f8-4b32-9235-1d83e619da78.png)
 
#### 3.7.5 Create role (no permissions)
I tried to create a role without having permissions for it.
![image](https://user-images.githubusercontent.com/23361101/160818555-b4858c46-4230-43e6-873d-b8e7afd727a5.png)

When that happens, the alert 80250 (`CreateRole. Error: AccessDenied`) is created:
![image](https://user-images.githubusercontent.com/23361101/160819309-70294389-48a8-4773-8197-49a291a9294c.png)

The same happens if I try to create the Role using the TOR network.

## 4. Blogpost :yellow_circle: 
I was able to follow the steps in the blogpost with ease and Cloudtrail works fine after that. Instructions are still up to date. 

However, there is an image explaining how to enable the AWS Dashboard in the Wazuh UI but the way to activate it is different now. It should be updated as part of [this issue](https://github.com/wazuh/wazuh-documentation/issues/4988).

# Conclusions
1. **[Manager installation :yellow_circle:](https://github.com/wazuh/wazuh-documentation/issues/4982):** It is not specified what minimum size must be available. On a VM with a 10 GB disk the installation could not be completed.
2. **[Agent installation :red_circle:](https://github.com/wazuh/wazuh-documentation/issues/4983):** There is an error following the steps to install an agent from sources. The error appears when trying to install CMake. It seems that Openssl is a requirement for it, but it is not mentioned among the dependencies in the documentation.
3. **Cloudtrail documentation:** 
  3.1 **[AWS module :red_circle:](https://github.com/wazuh/wazuh-documentation/issues/4988):** The existence of an AWS module/dashboard in the Wazuh UI is not mentioned. The user may not know of its existence. Perhaps, inside [Considerations for configuration](https://documentation-dev.wazuh.com/4.3-rc/amazon/services/prerequisites/considerations.html), an explanation of how to enable it should be added.
  3.2 **[Screenshots outdated :yellow_circle:](https://github.com/wazuh/wazuh-documentation/issues/4990):** The screenshots show an outdated AWS interface. The AWS interface will change again on April so it might be a good time to replace those screenshots.  Despite this, the steps can still be easily followed.
  3.3 **Cloudtrail Amazon configuration :green_circle::** The documentation to activate Cloudtrail seems correct and easy to follow.
  3.4 **Cloudtrail Wazuh configuration :green_circle::** The steps to configure the Cloudtrail integration in Wazuh are correct and easy to understand.
4. **Cloudtrail wodle/integration :green_circle::** The Cloudtrail integration works fine, fetching events from AWS and sending them to analysisd for alert creation.
5. **[AWS dashboard :yellow_circle:](https://github.com/wazuh/wazuh-kibana-app/issues/3931):** The AWS dashboard in the Wazuh UI was not showing information about regions or account IDs.
6. **Wazuh AWS alerts :green_circle::** Alerts for relevant events are generated for all tested use cases.

**Comment by Mayons** [comment]
Testing done with the help of @gdiazlo.
