### ISSUE TITLE
Upgrade the Wazuh embedded Python to 3.10

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#13265]
With the new Python 3.10, several things have changed. In this version some things that we currently use in the code have been deprecated.

An example of this is the following:

```
framework/wazuh/core/cluster/tests/test_local_client.py:7: in <module>
    from collections import Callable
E   ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

As we can see, now to import `Callable`, it is necessary to do it in the following way:

```
from collections.abc import Callable
```

Instead of:

```
from collections import Callable
```

Another failure is the following:

```
/usr/lib/python3.10/asyncio/locks.py:168: in __init__
    super().__init__(loop=loop)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <[AttributeError("'Event' object has no attribute '_value'") raised in repr()] Event object at 0x7f40340856f0>

    def __init__(self, *, loop=_marker):
        if loop is not _marker:
>           raise TypeError(
                f'As of 3.10, the *loop* parameter was removed from '
                f'{type(self).__name__}() since it is no longer necessary'
            )
E           TypeError: As of 3.10, the *loop* parameter was removed from Event() since it is no longer necessary
```

Another error is the following: These are just two examples, in this epic we will investigate, update and fix all the issues related to the update.

Development branch: [feature/13265-upgrade-python-to-3.10.11](https://github.com/wazuh/wazuh/tree/feature/13265-upgrade-python-to-3.10.11)

**Comment by fdalmaup** [comment]
# Issue Update

Resuming the epic, the latest CPython interpreter version for 3.10 is `v3.10.11`. It has been already developed for the `amd64` architecture and tested in a fresh Wazuh installation successfully and is in the process to have it for the `aarch64` architecture.

**Comment by fdalmaup** [comment]
# Issue Update

The installation of the Wazuh embedded interpreter `v3.10.11` was carried out successfully for the `aarch64` architecture after the modifications.

**Comment by fdalmaup** [comment]
# Issue Update

When getting some dependencies wheels to be `manylinux` via `auditwheel`, the `2.4+ kernel w/o ELF notes? -- report this` warning message appeared in the Wazuh installations for Ubuntu. To avoid the use of `.tar.gz` files for the `multidict`, `psutil`, and `yarl` dependencies, which makes the installation from sources time longer, it was decided to update these to the following versions, which provide official Python 3.10 manylinux wheels, avoiding the mentioned warning message.:
```
multidict==5.2.0
psutil==5.9.0
yarl==1.7.0
```

A successful installation has been performed on CentOS 7 and Ubuntu 18.04 after the update.

**Comment by fdalmaup** [comment]
# Issue Update

After making the necessary modifications for `aarch64`, a successful installation has been performed on CentOS 7. 
The sources and preinstalled files are ready to be uploaded to the `21-13265` dependencies.

**Comment by fdalmaup** [comment]
# Issue Update 

On June 6, 2023, the patch version `3.10.12` was released. The Cpython sources and preinstalled packages were made for `amd64` and `aarch64`, carrying out successful installations for both architectures.

**Comment by fdalmaup** [comment]
# Issue Update

Due to the latest patch of Python 3.10 (`v3.10.13`) and the need for dependencies update, the embedded interpreter is being rebuilt.
Firstly, the modifications were tested for the `amd64` architecture. After the necessary modifications to the source `CPython` files and updating certain dependencies, a successful installation was carried out and the API, Framework, Wodles, and Integrations UTs passed.

The following dependencies have been updated following the considerations of the related issues:
- Due to vulnerabilities
  - `aiohttp==3.8.5` https://github.com/wazuh/wazuh/issues/18213
  - `certifi==2023.7.22` https://github.com/wazuh/wazuh/issues/18214
  - `cryptography==41.0.4` https://github.com/wazuh/wazuh/issues/17734
  - `grpcio==1.58.0` https://github.com/wazuh/wazuh/issues/18215
  - `numpy==1.26.0` https://github.com/wazuh/wazuh/issues/17282
  - `requests==2.31.0` https://github.com/wazuh/wazuh/issues/17283
- Due to compatibility
  - `pyarrow==13.0.0` https://github.com/wazuh/wazuh/issues/18984 based on https://github.com/wazuh/wazuh-documentation/issues/6470#issuecomment-1721411097 

Although the installation did not raise any issues, the AITs and system tests must be executed to discard any risk of misbehavior.

**Comment by fdalmaup** [comment]
# Issue Update

The `connexion` dependency has been updated to the latest stable release: `2.14.2`. No problems were found in the `amd` or `aarch` installations.

**Comment by dpetiz** [comment]
When it will be released in the wazuh stable version? Since the python 3.9 has a lot of vulnerabilities?

**Comment by fdalmaup** [comment]
Hi @dpetiz. We are actively working on this upgrade to deliver it as part of the Wazuh `4.8.0` version with the most number of updated dependencies. Also, the team has open issues in order to patch some dependencies with known vulnerabilities for Wazuh patch versions.
