### ISSUE TITLE
Cisco Umbrella logs

### ISSUE THREAD

**Issue by mirceacroitoru** [wazuh/wazuh#13316]
hi guys

I have cisco umbrella configured and an s3 bucket active.
in wazuh logs i see 

2022/05/02 18:11:33 wazuh-modulesd:aws-s3: INFO: Starting fetching of logs.
2022/05/02 18:11:33 wazuh-modulesd:aws-s3: INFO: Executing Bucket Analysis: (Bucket: cisco-managed-eu-central-1, Path: 7964sd880_9351aa82absd533c9638b61eea2db9371f/dnslogs, Type: cisco_umbrella)
2022/05/02 18:11:36 wazuh-modulesd:aws-s3: INFO: Fetching logs finished.

However i don't see any alert in wazuh. Alerts are visible in umbrella dashboard and my ossec config is as follows ( path and keys are not the real ones )

<wodle name="aws-s3">

        <disabled>no</disabled>
        <interval>1m</interval>
        <run_on_start>yes</run_on_start>
        <skip_on_error>yes</skip_on_error>

        <bucket type="cisco_umbrella">
                <name>cisco-managed-eu-central-1</name>
                <path>7964880_935421827d32d82abc153713c9638b633sa1eea2db9371f/dnslogs</path>
                <access_key>AKIKWVasdasZQY6NGHC</access_key>
                <secret_key>MJQozHUnasdasdFOnXBIj7sJ42htRQlZlyagV2</secret_key>
        </bucket>
</wodle>

How exactly its supposed to look an alert? under what ID?

**Comment by CarlosRS9** [comment]
Hi @mirceacroitoru 

First of all, sorry for the delay in replying.

I'm afraid that the reason you don't see these logs, even though the integration is working properly, is because Wazuh doesn't include Cisco Umbrella rules by default at the moment. In future revisions we will include them, but until then you will have to create your own custom rules to be able to see these alerts.

Check our official documentation to learn how to create your custom rules. In particular, you may find these links useful:

- [Custom rules and decoders](https://documentation.wazuh.com/current/user-manual/ruleset/custom.html)
- [Testing decoders and rules](https://documentation.wazuh.com/current/user-manual/ruleset/testing.html)

I hope you find this useful. Let us know if you need further assistance.
