### ISSUE TITLE
Default Value of alert_new_files changed from 'no' to 'yes'

### ISSUE THREAD

**Issue by juergenc** [wazuh/wazuh#1335]
Hello,

the default value of the tag `<alert_new_files>` seems to have changed from _no_ to _yes_. At least this what the [documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html?highlight=alert_new_files#alert-new-files) says. There it is still _no_ and should be changed to _yes_. If the  `<alert_new_files>` tag is not explicitly defined within the `<syscheck>` tag, new files will be alerted.

Please update the documentation accordingly.

Thanks,
Jürgen

**Comment by JuanjiJG** [comment]
Hello @juergenc,

We've checked the source code, and the default value for `<alert_new_files>` is `no`. We've also tested it removing the tag from the configuration file and the default behaviour is to not alert for new files.

Please, check carefully your `ossec.conf` to see if the option is already defined on another section, and if you have registered agents, check that they don't have that option on its own `ossec.conf` or in the group's `agent.conf` file.

Regards,
Juanjo

**Comment by juergenc** [comment]
Yes, it is as you said, my bad sorry. 
**But**, the `<alert_new_files>` tag was set to `yes` on the **local** `ossec.conf` on the manager side and **only there**. If I remove the entire entry from the manager's `ossec.conf` and restart it no new files are reported. If re-insert the entry there and **only there** and restart the manager, new files are reported from any arbitrary agent.

Tell me, didn't got the basics of Wazuh or is it really a bug?

**Comment by bah07** [comment]
Hi all,

I'll try to clarify this a bit. @juergenc  what you have commented is correct. The tag `<alert_new_files>` is an option that is applied in the decoder of _Syscheck_ alerts _(Analisisd)_ discarding the alerts of new files when activated. This is the most confusing part because it is not a _Syscheck_ option. 

For historical reasons and compatibility with OSSEC agents, this configuration has been maintained this way. In our default configuration we decided to activate this option, but if the tag is not defined the assigned value is "no".

In our roadmap we have planned a change in this respect, it is not yet decided whether to add a block to define the global settings of the manager for each module or choose some other possibility.
I hope I helped. Don't hesitate to keep posting if you need more clarity.

Regards.

**Comment by juergenc** [comment]
Hello @bah07 ,

thanks for shedding more light to it. If this is an `ossec-analysisd` parameter, every agent is affected by this option - indeed confusing. But this is a documentation issue. The documentation is in some parts unclear and ambiguous. 
One thing, if I cite you: "_global settings_", what does that mean, are the parameters in manager's `ossec.conf` basically global options and not the ones for the local agent running on the manager host or did you refer to the `internal_options.conf`?

If I have on whish free I would like to opt for the following: `<alert_new_files>` is global and can be overwritten by the local `ossec.conf` or `agent.conf`.

**Comment by bah07** [comment]
Hi @juergenc.

Sorry about that, we are working to make the application simpler and the documentation less confusing.

When I said _global options_,  I referred specifically to the manager configuration, concretely, tag `<global>`, but I want to clarify this is not decided yet. We always value the opinions of the community and will consider the possibility of adding this option in agents configuration. Thank you for the feedback, we will keep you informed.

Regards.

**Comment by bah07** [comment]
Hi @juergenc

We have changed the default values to match the default values of the configuration. In version 3.8 the option `<alert_new_files>` will be *YES*. And if this configuration is omitted it will remain *YES*.

Regards.
