### ISSUE TITLE
Wrong OS name reported from Solaris 11

### ISSUE THREAD

**Issue by elwali10** [wazuh/wazuh#13370]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.5 | Syscollector | Agent | Packages/Sources | Solaris 11 |

The OS name is reported as `-` from a Solaris 11 as mentioned below  agent with the following specs: 

![image](https://user-images.githubusercontent.com/16334770/166919207-af9303e2-504d-483e-a6b4-4850c9d9fbae.png)

```
uname -a
SunOS test 5.10 Generic_150401-64 i86pc i386 i86pc
uname -r
5.10
uname -v
Generic_150401-64
 uname -s
SunOS
```
![image](https://user-images.githubusercontent.com/16334770/166919550-6da57901-be1d-407a-8985-d4b0e4570e13.png)

Keep Alive debug message: 

```
2022/05/12 16:50:43 ossec-agentd[15933] notify.c:171 at run_notify(): DEBUG: Sending keep alive: #!-SunOS bdouruw01 5.10 Generic_150401-64 i86pc - Wazuh v4.1
.5 / ab73af41699f13fdd81903b5f23d8d00
```

Regards,
Elwali

**Comment by mangolddamian** [comment]
After executing a series of tests, the following conclusions and possible causes of the problem reported in this issue were reached:

- Solaris 10 takes the OS information from the etc/release file.
  - If the content of this file is corrupt, the problem is observed. Activating the DEBUG mode of the agent shows an error message in the ossec.log file.
  - If the file does not exist, the problem is observed. Activating the DEBUG mode of the agent does NOT show an error message in the ossec.log file.

- Solaris 11 takes OS information from two files etc/release and etc/os-release
  - If the content of both files is corrupt, the problem is observed. Activating the DEBUG mode of the agent shows an error message in the ossec.log file.
  - If both files do not exist, the problem is observed. Activating the DEBUG mode of the agent does NOT show an error message in the ossec.log file.

By "problem" we mean that the agent's OS field is not visible on the dashboard.

**Comment by mangolddamian** [comment]
To continue with the analysis, we ask the user for the following information:

If the OS is Solaris 10, the information we need is:
- Verify the existence of the etc/release file.
- Give us the content of the etc/release file.
- Give us all the log files. A backup of the log files is made daily, giving us all that exist.
- If possible, restart the agent and give us the log file. To restart the agent, execute the following command ./ossec-control restart inside the var/ossec/bin/ folder.


If the OS is Solaris 11, the information we need is:
- Verify the existence of the etc/release file.
- Give us the content of the etc/release file.
- Verify the existence of the etc/os-release file.
- Give us the content of the etc/os-release file.
- Give us all the log files. A backup of the log files is made daily, giving us all that exist.
- If possible, restart the agent and give us the log file. To restart the agent, execute the following command ./wazuh-control restart inside the var/ossec/bin/ folder.

**Comment by Dwordcito** [comment]
@elwali10 We took this issue out of the sprint, when you can provide us with information on this problem, we will attack it.
