### ISSUE TITLE
Suppress new File Alert on initial FIM Inventory avoiding Alert Flooding

### ISSUE THREAD

**Issue by juergenc** [wazuh/wazuh#1338]
### User Story
When a new agent is registered and configured and the syscheck is started an alert is generated for **every** individual inode found below the directory to be monitored defined by the `<directory>` tag. This leads to alert flooding and reporting **false-positives** which is not desired.

### User Acceptance Criteria
1. Suppress the _new-file_ alert on `syscheck` run even if the value `alert_new_files` is set to `yes`
1.1 if an agent is newly configured and `syscheck` runs for the very first itme
1.2 if another directory is added later to the `<directory>` tag
1.3 after the deletion of the FIM database with the next `syscheck` run

**Comment by crolopez** [comment]
Hi @juergenc,

It makes sense that if alert_new_files is disabled no new file are reported, even if it is the first time. It will be included in a future release.

Best regards.

**Comment by bah07** [comment]
Hi all, we added this feature for new release, 3.7.

Henceforth the alert behavior for new files is as follows.:
 - New files are no reported if runs agent's first scan.
 - After the first scan is finished, no new file alerts are generated if the `alert_new_files` option is set to `no`. Otherwise, all add alerts are reported, even if new directories are added to the configuration.
 - Any previously deleted file will report an added alert if `alert_new_files` is set to `yes`

Regards.
