### ISSUE TITLE
Feature request: Log an event when the MSU VD feed is not available

### ISSUE THREAD

**Issue by maumrsms** [wazuh/wazuh#13440]
|Wazuh version|Component|
|---|---|
| 4.2.6 | Manager |

Hello team,

Based on issue [#13254](https://github.com/wazuh/wazuh/issues/13254), we need Wazuh to log an event whenever it is not capable of fetching MSU data because of external issues.

Regards.

**Comment by chemamartinez** [comment]
Hi @maumrsms,

We have some doubts regarding this issue:
- Mentioned issue [#13254](https://github.com/wazuh/wazuh/issues/13254) is about the internal process of generating the MSU. This is not related to the Wazuh operation since it is an internal procedure in Jenkins. The official MSU is always available at feed.wazuh.com, which is validated before publishing it.
- If the manager is not able to fetch the MSU from the repository, it already logs the error in the `ossec.log` file as done for the rest of the feeds.
```
2022/09/15 12:16:28 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Microsoft Security Update' database update.
2022/09/15 12:16:40 wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'Microsoft Security Update' database could not be fetched.
2022/09/15 12:16:40 wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.
```
- The consequence of the failure when fetching the MSU is that the scanner continues working properly with the latest version of the MSU indexed in the vulnerability database. In case no data is stored in the database, the scan fails.

Having the considerations above into account. Do you need to generate an alert when the MSU fails to be downloaded? In that case, would it make sense to apply this to the rest of the feeds?

**Comment by maumrsms** [comment]
Hello @chemamartinez!
The feature request was created because the problem was that the MSU feed was actually being fetched by Wazuh, but since the Microsoft web was not available, it scrapped a wrong web page, thus not reporting errors when fetching MSU feed.

In any case, if this "web scrapping" is now being done by Wazuh team for the new [MSU feed](https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.json.gz) worked [here](https://github.com/wazuh/wazuh-tools/pull/193), my guess is that this situation should not happen anymore.
