### ISSUE TITLE
Crash in syscollector hardware scan while parsing SMBIOS table

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#13547]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5 | syscollector| Agent | all | Windows |

## Description
Hello team,

Following a community that reported a crash in the Windows agent:
https://groups.google.com/u/1/g/wazuh/c/Cy0ypo1wnV4/m/6OaiFWsZAQAJ

I have detected a malfunction in the syscollector module in a specific case with a **Windows server 2008**.
It occurs in the hardware scan, when the information is extracted from the SMBIOS table. When parsing it in the **parseRawSmbios** function, a crash occurs and the agent shuts down.
In the google groups thread you can see more information. I created a custom package for the user with that code in the parse function:

```c++
static std::string parseRawSmbios(const BYTE* rawData, const DWORD rawDataSize)
{
    std::string serialNumber;
    DWORD offset{0};
    std::cout << "Starting parsing in function 'parseRawSmbios':" << std::endl;
    while (offset < rawDataSize && serialNumber.empty())
    {
        SMBIOSStructureHeader header{};
        memcpy(&header, rawData + offset, sizeof(SMBIOSStructureHeader));
        if (BASEBOARD_INFORMATION_TYPE == header.Type)
        {
            std::cout << "First type." << std::endl;
            SMBIOSBasboardInfoStructure info{};
            memcpy(&info, rawData + offset, sizeof(SMBIOSBasboardInfoStructure));
            offset += info.FormattedAreaLength;
            for (BYTE i = 1; i < info.SerialNumber; ++i)
            {
                const char* tmp{reinterpret_cast<const char*>(rawData + offset)};
                std::cout << "New SMBIOS table line: '";
                std::cout << tmp << "'" << std::endl;
                const auto len{ strlen(tmp) };
                offset += len + sizeof(char);
            }
            serialNumber = reinterpret_cast<const char*>(rawData + offset);
            std::cout << "Serial number: '";
            std::cout << serialNumber << "'" << std::endl;
        }
        else
        {
            std::cout << "Second type." << std::endl;
            offset += header.FormattedAreaLength;
            bool end{false};
            while(!end)
            {
                const char* tmp{reinterpret_cast<const char*>(rawData + offset)};
                std::cout << "New SMBIOS table line: '";
                std::cout << tmp << "'" << std::endl;
                const auto len{strlen(tmp)};
                offset += len + sizeof(char);
                end = !len;
            }
        }
    }
    return serialNumber;
}
```

So that he could print the lines of the SMBIOS table, here you can see how they are parsed and where the crash occurs:
[log.txt](https://github.com/wazuh/wazuh/files/8737537/log.txt)

**Comment by HanesSciarrone** [comment]
## Status

After reading the report and the community conversation I could suppose that the problem was caused by the `strlen()` function on line 309 or 323 of the `parserRawSmbios` function (sysInfoWIn.cpp). 

![image](https://user-images.githubusercontent.com/58960358/170174302-50202110-d560-459c-ba25-45b86b92a77d.png)

I have read the **System Management BIOS (SMBIOS) Reference Specification** to understand the data format of the SMBIOS structure and I have looked for another way to get the serial number where we don't use the `strlen()` function. I found two implementations on these repositories, one of them is an official Microsoft implementation.

- Repository 1: https://github.com/microsoft/Windows-universal-samples/blob/main/Samples/CustomCapability/Service/Client/smbios.cpp

- Repository 2: https://github.com/KunYi/DumpSMBIOS/blob/master/DumpSMBIOS/smbios.cpp

I'm working to implement a merge solution between two repositories. I did some tests to get the motherboard table from SMBIOS and then get the serial number from the data in Windows 10 but I wasn't able to get the serial number yet.
