### ISSUE TITLE
Wazuh 4.3.1 | Server 2008 R2 | MSSQL Server 2008 | Application Event Log | I can't see mssql application logs (33205) on wazuh.

### ISSUE THREAD

**Issue by g-sezen** [wazuh/wazuh#13546]
Hello.
Have a good Friday
I cannot see the MSSQL application logs (**Event ID: 33205**) on Wazuh.
Because, incoming logs are written directly to the **archives.json** file.
How can i solve this problem.

![alerts-log-1](https://user-images.githubusercontent.com/105906123/169470438-5141fead-eb24-4bd5-b1ca-901decb9d983.png)
![archives-log-1](https://user-images.githubusercontent.com/105906123/169470444-7206003c-254a-41d1-b2dd-6e6c0d14f89c.png)

**Comment by nmkoremblum** [comment]
Hi g-sezen,

As for the `archives.json`, as you have activated the `logall_json` option on your manager's `ossec.conf` file, every single log that arrives at the manager is stored on it. On the other hand, in the `alerts.json` file, only the logs that have a threat level higher than the one set under the `log_alert_level` option on your manager's `ossec.conf` file (by default, "3") will be stored.

In this case, the event that you are displaying has a level equal to 0:
![image](https://user-images.githubusercontent.com/75255206/169905176-6bd81242-9afe-44e5-923a-a7370999b887.png)
so it won't be stored in the `alerts.json` file.

Please, take a look at the following links to have a better understanding of the situation:
- https://documentation.wazuh.com/current/user-manual/manager/alert-threshold.html
- https://documentation.wazuh.com/current/user-manual/ruleset/rules-classification.html
- https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/alerts.html
- https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#logall

I hope that my answer helps you, please let us know!

Best Regards,

Mariano Koremblum

**Comment by yildirimorhan** [comment]
Hello Friends,

I was able to solve the problem by setting the audit_failure and audit_success level below to 3 in the 0585-win-application_rules.xml file. initial value was 0.

  <rule id="61069" **level="3"**>
    <if_sid>60003</if_sid>
    <field name="win.system.severityValue">^AUDIT_FAILURE$</field>
    <options>no_full_log</options>
    <description>Windows application audit failure event.</description>
    <group>gpg13_4.12,</group>
  </rule>

  <rule id="61070" **level="3"**>
    <if_sid>60003</if_sid>
    <field name="win.system.severityValue">^AUDIT_SUCCESS$</field>
    <options>no_full_log</options>
    <description>Windows application audit success event.</description>
    <group>gpg13_4.12,</group>
  </rule>

I think there may be a bug here. Because the level value coming to the audit log is always 0. You can see it below.
{"providerName":"MSSQLSERVER","eventID":"33205",**"level":"0"**,"task":"4","keywords":"0x90000000000000",

If this is a bug, it needs to be fixed. As I said, there was no such thing before the update.

Kind regards and stay healthy,
Orhan

**Comment by nmkoremblum** [comment]
Hi @yildirimorhan,

There are two different things here.

First, you are getting logs on the `archives.json` file because you have enabled the `logall_json` option on your manager's `ossec.conf` file. Take a look at the following link please:
https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#logall-json

The only difference between the `archives.json` and the `alerts.json` is that in the alerts file only the events that have an alert level equal to or higher than the one you have set under the label `log_alert_level` on your manager's `ossec.conf` file, which by default is "3". If the logs come with an alerting level equal to 0 is because such logs are usually of no relevance. In case that you want to see them in the alerts file, and in the dashboard, you can create child rules of "61069" and "61070" to only raise the alerting level, for example as follows:
```xml
<group name="windows,windows_application,">
    <rule id="100100" level="3">
        <if_sid>61069</if_sid>
        <description>Windows application audit failure event.</description>
    </rule>
</group>
```
If you inspect the file `/var/ossec/ruleset/rules/0585-win-application_rules.xml` you can see there are many different alert levels.

I hope that my answer helps you!

**Comment by yildirimorhan** [comment]
Hi @nmkoremblum

I noticed something. I updated the level values of some xml files under /var/ossec/ruleset/rules/. But now I see wazuh reverting to old level values after update. Wazuh reloads xml files after update?

Thank you,
Orhan

**Comment by nmkoremblum** [comment]
Hi again @yildirimorhan,

Yes, when upgrading the manager the whole `/var/ossec/ruleset` directory is overwritten, that is why it is not recommended to directly modify the ruleset but adding new rules and decoders to `/var/ossec/etc/rules` or  `/var/ossec/etc/decoders` respectively.

Regards,

Mariano Koremblum

**Comment by yildirimorhan** [comment]
Hi @nmkoremblum,

Thank you for the information. 

For example, I want to make the following rule level value 7 in the 0085-pam_rules.xml file content.
And there are many rules like this where I need to set the level to 7.
In this case, I will have to write each rule to my local.xml file, where I need to set the level value to 7. Is this true?

```
<rule id="5501" level="3">
     <if_sid>5500</if_sid>
     <match>session opened for user </match>
     <description>PAM: Login session opened.</description>
     <mitre>
       <id>T1078</id>
     </mitre>
     <group>authentication_success,pci_dss_10.2.5,gpg13_7.8,gpg13_7.9,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,tsc_CC6.8,tsc_CC7.2, $
   </rule>
```
With best regards,
Orhan

**Comment by nmkoremblum** [comment]
Yes, that is correct.

Every single rule that you want to rise its level will have a format similar to the following one:
```xml
<rule id="NEW_RULE_ID_HIGHER_THAN_100k" level="7">
    <if_sid>ORIGINAL_RULE_ID</if_sid>
    <description>ORIGINAL_DESCRIPTION</description>
</rule>
```

Where you should replace the "NEW_RULE_ID_HIGHER_THAN_100k", "ORIGINAL_RULE_ID" and "ORIGINAL_DESCRIPTION" for their corresponding values.

For example, in the rule you have shown, it could be like:
```xml
<rule id="105501" level="7">
    <if_sid>5501</if_sid>
    <description>PAM: Login session opened.</description>
</rule>
```

Best Regards,

Mariano Koremblum

**Comment by yildirimorhan** [comment]
Hi @nmkoremblum 

I understand better now with this example. 
Thank you so much for this information you provided.

Stay healthy,
Orhan

**Comment by nmkoremblum** [comment]
You are welcome @yildirimorhan!

Do not hesitate to reach out again, through any of our [official community channels](https://wazuh.com/community/), whenever you need us!

Best regards,

Mariano Koremblum
