### ISSUE TITLE
Agent stop on restart, RHEL 9

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#13602]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0-40400 | wazuh-control | Agent | Packages | RHEL 9 |

Hello team,

We have detected a problem related with RHEL9 service management.
The Wazuh agent after start and register, restart with new agent.conf and it keeps stopped.
Error found:
```
Killing wazuh-modulesd...
Killing wazuh-logcollector...
Killing wazuh-syscheckd...
Killing wazuh-agentd...
Killing wazuh-execd...
Wazuh v4.4.0 Stopped
Redirecting to /bin/systemctl restart wazuh-agent.service
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```
Using `active-response/bin/restart.sh` script

active-response.log
```
2022/05/27 09:19:53 active-response/bin/restart-wazuh: Ended
2022/05/27 09:20:07 active-response/bin/restart-wazuh: Starting
2022/05/27 09:20:07 active-response/bin/restart-wazuh: {"version":1,"origin":{"name":"","module":"wazuh-execd"},"command":"add","parameters":{"extra_args":[],"alert":{"data":{"srcip":"null"}},"program":"active-response/bin/restart-wazuh"}}

2022/05/27 09:20:16 active-response/bin/restart-wazuh: Ended
Fri May 27 09:21:20 UTC 2022 active-response/bin/restart.sh agent
```

Data:
```
# /var/ossec/bin/wazuh-control status
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...

# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.4.0"
WAZUH_REVISION="40400"
WAZUH_TYPE="agent"
```

**Comment by vikman90** [comment]
Hi @okynos, I checked this issue and I saw that:

- `agent_control -R -u 001` works.
- Auto-restart after shared configuration change won't work.

## Rationale

### On-demand restart

This method uses the new C implementation of the restart command ([restart-wazuh.c](https://github.com/wazuh/wazuh/blob/fc69a3b24a402b5c105e924723160fc021fa56fc/src/active-response/restart-wazuh.c)), which simply runs `wazuh-control restart`.

### Auto restart due to configuration change

This method uses the script [restart.sh](https://github.com/wazuh/wazuh/blob/fc69a3b24a402b5c105e924723160fc021fa56fc/src/active-response/restart.sh), which tries:
- `systemctl` (if available)
- `service` (if available)
- `wazuh-control` (otherwise)

On RHEL 9, `service` is implemented as a link to `systemctl`, although Systemd is not available on containers. So, `restart.sh` raises this error:

```
Killing wazuh-modulesd...
Killing wazuh-logcollector...
Killing wazuh-syscheckd...
Killing wazuh-agentd...
Killing wazuh-execd...
Wazuh v4.4.0 Stopped
Redirecting to /bin/systemctl restart wazuh-agent.service
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

## Proposed fix

Let `restart.sh` behave like `restart-wazuh`: simply call `wazuh-control restart`. This will allow the agent run in the same way it was running previously.
