### ISSUE TITLE
[FR] It is not possible to scan selected directories in a specific period / time interval

### ISSUE THREAD

**Issue by mradaszewski92** [wazuh/wazuh#13601]
|Wazuh version|Component|
|---|---|
| X.Y.Z-rev | SYSCHECK|

Hello Wazuh Team

This is a Feature request

At the moment you are giving the possibility to schedule scans for the "syscheck" module by following the link from the documentation: https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/fim-configuration.html#configuring-scheduled-scans. Unfortunately, it does not include the scan for selected directories, but only for the whole.

The point is that when I set real-time monitoring to e.g. the directory '/home/some_user', after releasing the playbook from ansible, a directory is created: /home/some_user/.ansible/tmp. Currently directory: ".ansible/tmp" (cannot be ignored in any way)

More importantly, if we set up real-time monitoring (for the above directory), inotify comes into play. When I play ansible, a very large number of temporary files are created - reaching very large numbers, e.g. 2,000 to 10,000 files, **which leads to exhaustion of inotify for system resources (this leads to errors like: "no space left" on weaker systems), because one moment the files exist, and 15 seconds later the files are deleted (because Ansible has finished its work).** By the way, Wazuh alerts newly added files, and a moment later alerts about deleting them, which leads to queues overflow and makes log analysis much more difficult and consumes a lot of space on Elasticsearch

The idea is as follows. Adding a parameter to the **\<directory\>** parameter in the **syscheck** module, which, for example, will allow a scan to be performed every 10 minutes. Thanks to this, we will get an effect similar to real-time monitoring, and changes that are made on the indicated resource (by ordinary users) will not be ignored. With this approach, ansible will have time to clean up before the syscheck is done, intoify won't be consumed, and the only side effect will be more CPU usage.

I hope I wrote it understandably :)

**Comment by FrancoRivero** [comment]
Hi @mradaszewski92, 
Thank you for using Wazuh! 
We have a way to ignore files  if you don't know you can read [here](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/fim-configuration.html#configuring-ignoring-files-via-rules).
To write the rules you should have some considerations, for instance, you should follow [the next format](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html) to write the rules and [the next format](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html) to write regex syntax.
For other side, we have a [issue](https://github.com/wazuh/wazuh/issues/7230) to modify real-time monitoring because we are adding watches inside `Inotify` though some file does not be monitoring.
We are working in solve this limitation, in future versions we are working to solve it.
You can follow this development inhttps://github.com/wazuh/wazuh/issues/7230.
I recommend to set more specific directories for your configuration to avoid to add directories with temporal files, I mean FIM is a module to monitor critical files then it must avoid to add in the configuration volatile folders and add important files which shouldn't change.
Hope to work for you !
Regards

**Comment by mradaszewski92** [comment]
Are you human or bot? I wrote this thread again because I decided that the previous one did not describe the problem I was facing well enough. You could, at least out of respect for the client, not copy / paste the same replies from another thread. It is derogatory to human intelligence.

I have said many times that alerting is not the problem !!

**Comment by FrancoRivero** [comment]
Hi @mradaszewski92, 
I am not a bot, however this issue has not been fixed yet. We are working on it, however your problem is a known issue for us and I am trying to help you to fix your case until the solution is ready in the next release. 
You are right about critical files, from my point of view a critical file is a file that can modify or trick your system, at the moment I need your configuration to review it and try to give you a solution. 
Let me see if I understand correctly, you want to protect the `/scripts/someUser/somePlaybook.yml` folder and avoid that when generating temporary files in `/scripts/someUser/.ansible `generate many alerts about these temporary files?
Please give me that information to try to help you!
Regards

**Comment by FrancoRivero** [comment]
Closed after waiting 1 month for a reply!
