### ISSUE TITLE
Release 4.3.4 - Release Candidate 1 - E2E UX tests - Splunk installation

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#13671]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           | Splunk installation                                           |
| **Category**            | Installation                                           |
| **Main E2E UX test issue**  | https://github.com/wazuh/wazuh/issues/13670                                          |
| **Release candidate #** | RC1                                          |

## Installation procedure
Wazuh indexer:
- Installation: [Splunk All-in-one](https://documentation.wazuh.com/current/deployment-options/splunk/splunk-basic.html)
- Type: -
- OS: CentOS 8

Wazuh manager:
- Installation: [Splunk All-in-one](https://documentation.wazuh.com/current/deployment-options/splunk/splunk-basic.html)
- Type: -
- OS: CentOS 8

Wazuh dashboard:
- Installation: [Splunk All-in-one](https://documentation.wazuh.com/current/deployment-options/splunk/splunk-basic.html)
- OS: CentOS 8

Wazuh agent:
- Installation: Wazuh WUI one-liner deploy FQDN GROUP (created beforehand)
- OS: Ubuntu 18.04

## Test description
Try latest version of Splunk supported by our interface (Splunk app).
Check that documentaiton steps work as intended.
Check the WUI for any error or incorrect data.
Check that creation of new rules from the WUI works correctly.
Check that configuration of the manager from the WUI works correctly.
Check that the configuration/assignment of agent groups from the WUI works correctly .
## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results can be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found in the issue updates.

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ]

**Comment by cborla** [comment]
# Check that documentaiton steps work as intended.
The objective of this test is to review the documentation.

## Review documentation. :red_circle:
The explanation is clear and it works as expected, but some documentation notes about using minor packages are wrong.

Issue to wazuh-documentation: [5320](https://github.com/wazuh/wazuh-documentation/issues/5320) 

<details><summary>evidence</summary>

![image_5](https://user-images.githubusercontent.com/41765669/172474571-ad1d5a39-5470-40c0-92b7-8c23e99764b7.png)

![image_4](https://user-images.githubusercontent.com/41765669/172474579-c834ba11-1b88-4901-ac6e-967736f1d8ca.png)

</details>


# Check the WUI for any error or incorrect data.
The objective of this test is review the WUI behavior.

## Review WUI. :green_circle:
The WUI looks smooth, clear and easy to navigate, we couldn't find a label or naming error.

<details><summary>evidence</summary>

![initial-wazuh-app](https://user-images.githubusercontent.com/41765669/172475253-f5936223-d92e-4c38-90cb-ed4d27d5f09b.JPG)

![versions](https://user-images.githubusercontent.com/41765669/172478356-0e8000e0-535f-4db7-aabf-0f5b8942736f.JPG)

![image_wui](https://user-images.githubusercontent.com/41765669/172478705-0e62a7ad-32c9-4a50-bde4-cf0f9c3f619a.png)

</details>


# Check that creation of new rules from the WUI works correctly.
The objective of this test is create and modify rules and decoders from WUI.

## Review creation of new rules from the WUI. :green_circle:
It's possible create and modify rules and decoders without any problem.

<details><summary>evidence</summary>

![new-rule](https://user-images.githubusercontent.com/41765669/172479176-351a23cd-89fd-4f70-882c-f0e8a07f4305.JPG)

</details>


# Check that configuration of the manager from the WUI works correctly.
The objective of this test is modify and check manager configuration (ossec.conf) from WUI.

## Review manager configuration from the WUI. :green_circle:
It's possible modify manager configuration without any problem.

<details><summary>evidence</summary>

![edit-manager-config](https://user-images.githubusercontent.com/41765669/172479992-fd1fbb68-d5cb-4d6c-abd4-01c1e9984fce.JPG)

![manager-config-test](https://user-images.githubusercontent.com/41765669/172480057-00b317da-92c3-496f-ac65-cf07748bbf26.JPG)

</details>


# Check that the configuration/assignment of agent groups from the WUI works correctly.
The goal of this test is create, delete and assign agents to agent group from WUI.

## Review configuration/assignment of agent groups from the WUI. :red_circle:
The feature works, but there is a bug related filtering available agents in management group. 

Issue to wazuh-splunk: [1335](https://github.com/wazuh/wazuh-splunk/issues/1335)  

<details><summary>evidence</summary>

![Selección_01](https://user-images.githubusercontent.com/41765669/172483818-96510a2c-9d93-4ff7-9050-e98b3b354507.png)

![Selección_02](https://user-images.githubusercontent.com/41765669/172483830-90ec44fa-9d69-4db4-beb8-c5c7b6936ad0.png)

![Selección_03](https://user-images.githubusercontent.com/41765669/172483835-b843983a-33f4-4996-898d-3365456854ce.png)

</details>

## Installation: Wazuh WUI one-liner deploy FQDN GROUP (created beforehand) :red_circle:
It's not possible an one-liner deploy FQDN GROUP because it's not available group option selection.

Issue to wazuh-splunk: [1334](https://github.com/wazuh/wazuh-splunk/issues/1334) 

<details><summary>evidence</summary>

Wazuh APP for Splunk
![image_2](https://user-images.githubusercontent.com/41765669/172483236-0ba36a7f-9c40-40a0-8870-da26de0e6043.png)

Wazuh APP for Kibana
![image_3](https://user-images.githubusercontent.com/41765669/172483251-532bfe2e-0041-44db-97ef-d4bf5604db2f.png)

</details>
