### ISSUE TITLE
Release 4.3.4 - Release Candidate 1 - E2E UX tests - Office 365 Integration

### ISSUE THREAD

**Issue by Mayons95** [wazuh/wazuh#13691]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           | Office365 integration               |
| **Category**            | Cloud Security                                           |
| **Main E2E UX test issue**  | https://github.com/wazuh/wazuh/issues/13670                                          |
| **Release candidate #** | RC1                                          |

## Installation procedure
Wazuh indexer:
- Installation: [Offline Installation](https://documentation.wazuh.com/current/deployment-options/offline-installation.html)
- Type: Single Node
- OS: Ubuntu 18.04

Wazuh manager:
-- Installation: [Offline Installation](https://documentation.wazuh.com/current/deployment-options/offline-installation.html)
- Type: Single Node
- OS: Ubuntu 18.04

Wazuh dashboard:
- Installation: [Offline Installation](https://documentation.wazuh.com/current/deployment-options/offline-installation.html)
- Type: Single Node
- OS: Ubuntu 18.04

Wazuh agent:
- Installation: Wazuh WUI one-liner deploy IP GROUP (created beforehand)
- OS: CentOs 7

Test Steps:
- Test should be executed: [Test Steps](https://documentation-dev.wazuh.com/4.3-rc/office365/monitoring-office365-activity.html
)

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|----------------------------|-------------------------------------|
| :green_circle:           | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results can be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found in the issue updates.

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |
| :green_circle:  | Offline installation | Minor documentation issues  | [1] [2] [3] [4]  |
| :green_circle:  | Agent installation | Minor documentation issues  | [5] |
| :green_circle:  | Office 365 documentation | Minor documentation issues  |  [6] |
| :green_circle:  | Office 365 configuration | Minor documentation issues | [6] |
| :green_circle:  | Office 365 dashboards  | | |

1.  Becasue my host system is unsupported by wazuh, I needed to use the -i option to make the wazuh-installer.sh script download the files. Probably the system check could be avoided when just downloading, or at leas show it as a warning but still execute the download.
    * https://github.com/wazuh/wazuh-packages/issues/1633
2. This script sets the credentials admin:admin the documentation should state this fact clearly and recommend changing it ASAP. 
Or the script should use a random password and let the user knwo which password was generated.
    * https://github.com/wazuh/wazuh-packages/issues/1634
3. This step fails as the wazuih-indexer command moved the certificates previously, on a multi-machine installation this would not had happend, but it fails in a single-node installation.
    * https://github.com/wazuh/wazuh-documentation/issues/5329
4. Documentation suggest checking the dashboard by connecting to it, i would suggest to do a systemctl status first to check it started without errors
    * https://github.com/wazuh/wazuh-documentation/issues/5330
5. No offline agent installation instructions **Update**: the documentation mention this at the end**
6. At no point in the documentation we instruct the user to enable the Office365 module in the Settings section of the Wazuh UI. The instructions are vague in some details:
    - screenshots text  too small to be readable comfortably
    -  should recommend the user enable all subscriptions
    -  should tell the user how exactly restart the manager or agent to enable the configuration
    -  to know the module is enabled succesfully user must search the logs in /var/ossec/logs/ossec.log
    - the documentation shouldt tell you how to enable the office365 setting in the UI to have access to the UI office365 module
    * https://github.com/wazuh/wazuh-documentation/issues/5331
## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @davidjiglesias 
- [x] @alberpilot

**Comment by mauceballos** [comment]
[documentation](https://documentation.wazuh.com/current/deployment-options/offline-installation.html) issue:

It should be specified in step 3 c if it is a worker or a master

**Comment by mauceballos** [comment]
# Office 365 configuration

<details>

<summary>details</summary>

![Screenshot from 2022-06-03 16-11-10](https://user-images.githubusercontent.com/76791841/171935735-06fc43b8-2f98-4ff7-a171-8fed92346417.png)

![Screenshot from 2022-06-03 16-11-49](https://user-images.githubusercontent.com/76791841/171935748-f1c91cbc-055b-458c-9146-de8e8e114eb0.png)

![Screenshot from 2022-06-03 16-12-52](https://user-images.githubusercontent.com/76791841/171935751-0f534d73-070f-4cfa-8c97-aa0a60e5d335.png)

![Screenshot from 2022-06-03 16-13-11](https://user-images.githubusercontent.com/76791841/171935753-8cf4cc5c-45f9-496a-b8a6-d5c33da9e298.png)

![Screenshot from 2022-06-03 16-13-30](https://user-images.githubusercontent.com/76791841/171935755-3f8fe118-9b48-4656-a2da-9813622d0a48.png)

![Screenshot from 2022-06-03 16-14-04](https://user-images.githubusercontent.com/76791841/171935757-57161e81-f2a7-4b9a-b59e-b69443a964c4.png)

![365-1](https://user-images.githubusercontent.com/76791841/171935816-d67b7f84-b638-40c3-b311-1797f0066681.gif)

</details>

**Comment by mauceballos** [comment]
# Office 365 configuration

[Test Steps
](https://documentation-dev.wazuh.com/4.3-rc/office365/monitoring-office365-activity.html)
<details>

<summary>details</summary>

![Screenshot from 2022-06-06 11-24-47](https://user-images.githubusercontent.com/76791841/172215815-c9bcd2e6-a04f-4dfc-8272-b1646311198e.png)

![Screenshot from 2022-06-06 11-26-00](https://user-images.githubusercontent.com/76791841/172215900-9ff7f052-d6a2-4a51-b33e-858bacdc956d.png)

![Screenshot from 2022-06-06 11-27-04](https://user-images.githubusercontent.com/76791841/172215958-ac461982-30f7-4ec5-b237-bda7e4c579b6.png)

![Screenshot from 2022-06-06 11-34-49](https://user-images.githubusercontent.com/76791841/172216013-491eb86c-32f1-4c4b-8aeb-04dbc6332a29.png)

![Screenshot from 2022-06-06 11-36-00](https://user-images.githubusercontent.com/76791841/172216037-70d9403f-1c65-4353-bcdd-1df1262fbee8.png)

</details>

# Office 365 - Testing Dashboard

<details>

<summary>details</summary>
![Screenshot from 2022-06-06 12-18-47](https://user-images.githubusercontent.com/76791841/172216083-5bc91dc2-5926-4407-92ec-5bb87b9ceff3.png)

![Screenshot from 2022-06-06 13-34-36](https://user-images.githubusercontent.com/76791841/172216097-c5ba360d-53b3-4f02-97ea-fbf81bba8719.png)

![Screenshot from 2022-06-06 13-34-48](https://user-images.githubusercontent.com/76791841/172216112-fb8e3fb6-2f46-42f6-aa9c-bbcbf87271d5.png)

![Screenshot from 2022-06-06 13-39-14](https://user-images.githubusercontent.com/76791841/172216192-fc62206d-2aa4-4665-a94d-4266c03d0a60.png)

![Screenshot from 2022-06-06 13-38-55](https://user-images.githubusercontent.com/76791841/172216171-da62a7a2-451f-42ba-a517-8ca2aa0561c3.png)

![Screenshot from 2022-06-06 13-36-55](https://user-images.githubusercontent.com/76791841/172216125-03dfdf9e-c42a-49d0-a38e-0ca3b621478c.png)

</details>

**Comment by gdiazlo** [comment]
### Prepare offline files

* Follow the procedure to execute an offline installation from:

https://documentation.wazuh.com/current/deployment-options/offline-installation.html

1. Download the packages and configuration files

**Becasue my host system is unsupported for wazuh, I needed to use the -i option to make the wazuh-installer.sh script download  the files. Probably the system check could be avoided when just downloading, or at leas show it as a warning but still execute the download.**

2. Prepare the certificate config file
3. Generate the certificate for an all-in-one intannation usin 127.0.0.1
4. Move the files to the destination 

### Create virtual environment for wazuh all-in-one offline install

<details>
We created a VM using vagrant with the following configuration:

```
Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu1804"

        config.vm.hostname = "wazuh-aio"
        config.vm.synced_folder "/home/gdiazlo", "/vagrant"
        config.vm.provider "libvirt" do |vm|
            vm.qemu_use_session = false
            vm.cpus = 8
            vm.memory = 8192
        end
        config.vm.define :net do |net|
	    net.vm.network :private_network, :ip => "10.20.30.40"
        end

    config.ssh.forward_agent = true

    config.vm.provision "packages", type: "shell", inline: <<-SHELL
        apt update -y
        apt upgrade -y 
        curl -sO https://packages-dev.wazuh.com/4.3/wazuh-install.sh
        bash wazuh-install.sh -a
    SHELL
end
```
</details>

### Execute offline installation

1. Extract files
2. Install indexer deb
3. copy&past all the commands 
4. Edit /etc/wazuh-indexer/opensearch.yml
5. Enable and start the service wazuh-indeser
6. init security for indexer running script indexer-security-init.sh

**This script sets the credentials admin:admin the documentation should state this fact clearly and recommend changing it ASAP. Or the script should use a random password and let the user knwo which password was generated.**

7. Install wazuh-manager
8. Enable and start the wazuh-manager service
9. Check the status of the wazuh-manager

<details>
```
systemctl status wazuh-manager
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2022-06-07 15:15:49 UTC; 50s ago
  Process: 19601 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
    Tasks: 174 (limit: 4915)
   CGroup: /system.slice/wazuh-manager.service
           ├─19671 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─19710 /var/ossec/bin/wazuh-authd
           ├─19723 /var/ossec/bin/wazuh-db
           ├─19746 /var/ossec/bin/wazuh-execd
           ├─19760 /var/ossec/bin/wazuh-analysisd
           ├─19860 /var/ossec/bin/wazuh-syscheckd
           ├─19876 /var/ossec/bin/wazuh-remoted
           ├─19901 /var/ossec/bin/wazuh-logcollector
           ├─19917 /var/ossec/bin/wazuh-monitord
           ├─19923 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─19926 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           └─19950 /var/ossec/bin/wazuh-modulesd

Jun 07 15:15:41 wazuh-aio env[19601]: Started wazuh-db...
Jun 07 15:15:42 wazuh-aio env[19601]: Started wazuh-execd...
Jun 07 15:15:43 wazuh-aio env[19601]: Started wazuh-analysisd...
Jun 07 15:15:44 wazuh-aio env[19601]: Started wazuh-syscheckd...
Jun 07 15:15:45 wazuh-aio env[19601]: Started wazuh-remoted...
Jun 07 15:15:45 wazuh-aio env[19601]: Started wazuh-logcollector...
Jun 07 15:15:46 wazuh-aio env[19601]: Started wazuh-monitord...
Jun 07 15:15:47 wazuh-aio env[19601]: Started wazuh-modulesd...
Jun 07 15:15:49 wazuh-aio env[19601]: Completed.
Jun 07 15:15:49 wazuh-aio systemd[1]: Started Wazuh manager.
```
</details>

10. Install filebeat
11. copy&paste commands
12. Ediit /etc/filebeat/wazuh-template.json, set the shards to 1
13. Edit /etc/filebeat/filebeat.yml and set the credentials to the deault ones
14. Install wazuh module for filebeat
15. Install certificated for filebeat

**This step fails as the wazuih-indexer command moved the certificates previously, on a multi-machine installation this would not had happend. Copied the certificates from wazuh-indexer**

16. Enable and start filebeat service
17. Test filebeat output

<details>
```
# filebeat test output
elasticsearch: https://127.0.0.1:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 127.0.0.1
    dial up... OK
  TLS...
    security: server's certificate chain verification is enabled
    handshake... OK
    TLS version: TLSv1.3
    dial up... OK
  talk to server... OK
  version: 7.10.2
```
</details>

18. Checked the number of shards

<details>
```
curl -k -u admin:admin "https://localhost:9200/_template/wazuh?pretty&filter_path=wazuh.settings.index.number_of_shards"
{
  "wazuh" : {
    "settings" : {
      "index" : {
        "number_of_shards" : "1"
      }
    }
  }
}
```
</details> 

19. Install wazuh-dashboard package
20. copied&pasted the commands

** the same problem with the certificates as with filebeat,copied the ones from the indexer again**

21. Edit /etc/wazuh-dashboard/opensearch_dashboards.yml - default values were good to go
22. Enable and start wazuh-dashboard service

** the documentation state to go and check the dashboard by connecting to it, i would suggest to do a systemctl status first to check it started without errors**

23. at log in something like basic-auth form appeared in firefox instead of the log-in welcome page

### Create virtual environment for wazuh agent offline install

<details>
```
Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
        config.vm.hostname = "wazuh-aioagent"
        config.vm.synced_folder '.', '/vagrant', type: "sshfs"
        
        config.vm.provider "libvirt" do |vm|
            vm.qemu_use_session = false
            vm.cpus = 8
            vm.memory = 8192
        end
        config.vm.define :net do |net|
	    net.vm.network :private_network, :ip => "10.20.30.41"
    end

    config.ssh.forward_agent = true

    config.vm.provision "packages", type: "shell", inline: <<-SHELL
        yum update -y
        yum upgrade -y 
    SHELL
end
```
</details>

**The offline installation documentation does not include instructions to install the agent. **

24. Install agent using the command from the wazuh previously installed, but selecting the devel package

<details>
```
sudo WAZUH_MANAGER='10.20.30.40' yum install https://packages-dev.wazuh.com/pre-release/yum5/x86_64/wazuh-agent-4.3.4-1.el5.x86_64.rpm
```
</details>

25. Enable and start the agent service
26. Agent connects

### Create office 365 access

**Documentation screenshots contains text which is too small to be readable comfortably**

We've created the office365 access using the instructions in the [documentation](https://documentation-dev.wazuh.com/4.3-rc/office365/monitoring-office365-activity.html).

1. Register your app
2. Certificates & secrets
3. API permissions

**Permissions need admin constent, but my user was unable to perform the consent so the set up might not work.
The procedure seems to work overall, but the admin consent workflow was not fully tested.**


### Wazuh agent configuration

At no point in the documentation we instruct the user to enable the Office365 module in the Settings section of the Wazuh UI
The instructions are vague in some details:
* do not recommend the user enable all subscriptions
* do not tell the user how exactly restart the manager or agent to enable the configuration
* to know the module is enabled succesfully user must search the logs in /var/ossec/logs/ossec.log
* the UI does not enable the office365 in settings after the manager restart with the office365 integration has been enabled

1. Modified configuration file with the auth data from the previous phase in the agent previously installed in centos/7
2. Added additional subscription following the linked module reference

<details>
```
<!--
  Wazuh - Manager - Default configuration for ubuntu 20.04
  More info at: https://documentation.wazuh.com
  Mailing list: https://groups.google.com/forum/#!forum/wazuh
-->

<ossec_config>

<office365>
    <enabled>yes</enabled>
    <interval>1m</interval>
    <curl_max_size>1M</curl_max_size>
    <only_future_events>yes</only_future_events>
    <api_auth>
        <tenant_id>...........................</tenant_id>
        <client_id>....................................</client_id>
        <client_secret>............................</client_secret>
    </api_auth>
    <subscriptions>
        <subscription>Audit.SharePoint</subscription>
        <subscription>Audit.AzureActiveDirectory</subscription>
        <subscription>Audit.Exchange</subscription>
        <subscription>Audit.General</subscription>
        <subscription>DLP.All</subscription>
    </subscriptions>
</office365>
[...]
```

3. Restat the agent
4. Generated authentication office activity

Error with credentials found due to admin consent procedure. Obtained pre-generated credentials with apropriate permissions.

<details>

Tested the activity rception in Security Events panel

Got error in security events: 
```
	{"error":{"code":"AF10001","message":"The permission set () sent in the request does not include the expected permission."}}
```
Thnis seems related the office365 error found when creating the permissions

The second try with new credentials the process wordked and login / logoff events started appearing in the event manager

</details>

5. Rules for office 365 

The default rules included with wazuh worked:
- 91545 - captured the IP adress of the client logging in 
- 91539 - captured activity
- 91648 - this rule captured the error message


6. The office 365 panel, dashboard and events tabs showed information correctly

<details>
![image](https://user-images.githubusercontent.com/2181918/172437373-16c99363-3bbb-4cbf-a524-63486db679f3.png)

![image](https://user-images.githubusercontent.com/2181918/172437297-c7c154de-503e-4448-ad37-c452fc994b0b.png)

![image](https://user-images.githubusercontent.com/2181918/172437431-413225a7-4755-4bc9-836b-896623e1a859.png)
</details>

**Comment by gdiazlo** [comment]
Reviewed by @davidjiglesias & @alberpilot created some issues to be considered in the future.
