### ISSUE TITLE
SPIKE - Alpine Package Keeper (APK) packages retrieving support

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#13703]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| master | Syscollector - Sysinfo (data_provider) | Manager - Agent | Sources | Alpine Linux |

## Description

Currently, Alpine Package Keeper (APK) software packages used in Alpine Linux distribution, are not being  retrieved by syscollector, and therefore not shown on the Inventory

It's desirable to estimate the effort to support this.

## DoD
- [x] Research about internal APK package storage. DB-based or plain-text?
- [x] Check if there's any constraint to obtaining such information
- [x] Quick overview of Syscollector inventory for Alpine Linux
- [x] Estimate effort for its development with @wazuh/data-pirates

**Comment by MiguelazoDS** [comment]
# Research on Alpine Linux
## Environment
Wazuh Agent: Alpine Linux 3.8
## System packages inventory
### Package manager and packages db review
The package information is located at **/lib/apk/db/installed**. It is a plain text file that has the following format.

<details>
<summary>Click to expand</summary>

```
C:Q1EgTVKKsOpHAzjIZ/WGq6Ey9cX/g=
P:musl
V:1.1.19-r11
A:x86_64
S:372284
I:602112
T:the musl c library (libc) implementation
U:http://www.musl-libc.org/
L:MIT
o:musl
m:Timo Teräs <timo.teras@iki.fi>
t:1565162604
c:4ab7eba8eb2d8ab2ce3b54a8dc9fe958a8685d1d
p:so:libc.musl-x86_64.so.1=1
F:lib
R:libc.musl-x86_64.so.1
a:0:0:777
Z:Q17yJ3JFNypA4mxhJJr0ou6CzsJVI=
R:ld-musl-x86_64.so.1
a:0:0:755
Z:Q1lUgQ+IQG9688iKiZSRz3ITg7h/Y=
F:usr
F:usr/lib
```

</details>

**Note: The file was compared in Alpine Linux 3.8, 3.10, 3.12, and 3.17. It is the same format for all versions. Currently v2.
v3 is under development**

> The APKINDEX file contains a set of records extracted from the PKGINFO file of each package in the repository. Each line is prefixed with a letter, colon, and is followed by the value of the field. Lines are newline (\n) terminated and there is one blank line between records for a package. 

> The PKGINFO file contains the package metadata.

The APKINDEX has the following fields.

<details>
<summary>Click to expand</summary>

```
- C: - file checksum, see below
- P: - package name (corresponds to pkgname in PKGINFO)
- V: - package version (corresponds to pkgver in PKGINFO)
- A: - architecture (corresponds to arch in PKGINFO), optional
- S: - size of entire package, integer
- I: - installed size, integer (corresponds to size in PKGINFO)
- T: - description (corresponds to pkgdesc in PKGINFO)
- U: - url (corresponds to url in PKGINFO)
- L: - license (corresponds to license in PKGINFO)
- o: - origin (corresponds to origin in PKGINFO), optional
- m: - maintainer (corresponds to maintainer in PKGINFO), optional
- t: - build time (corresponds to builddate in PKGINFO), optional
- c: - commit (corresponds to commit in PKGINFO), optional
- k: - provider priority, integer (corresponds to provider_priority in PKGINFO), optional
- D: - dependencies (corresponds to depend in PKGINFO, concatenated by spaces into a single line)
- p: - provides (corresponds to provides in PKGINFO, concatenated by spaces into a single line)
- i: - install if (corresponds to install_if in PKGINFO, concatenated by spaces into a single line)
```

</details>

The INSTALLED database uses the APKINDEX and adds some more fields

<details>
<summary>Click to expand</summary>

```
- r: - packages which this package replaces, space-separated list
- q: - replaces priority, integer, optional
- s: - repository tag, optional, this will be set if the package is tagged to a repository in the world file (ex: linux@testing)
- f: - indicates broken items, space separated (f=files, s=scripts, x=xattrs, S=file hashes)

The following fields are repeated in groups consisting of a set of mutations made to the system to install the package.
ACL lines are specified as uid, colon, gid, colon, and mode.

- F: - directory name that was created by package, repeated
- M: - directory ACL, only if different than the default of 0:0:0755
- R: - file name, relative to preceding directory name
- a: - file ACL
- Z: - file checksum, if the checksum in the package is not none, a Q1 prefix indicates this will be a SHA1 hash in base64 format
```

</details>

### Syscollector package fields.

<details>
<summary>Click to expand</summary>

name
version
vendor
install_time
location
architecture
groups
description
size
priority
multiarch
source
format
checksum
item_id
db_status_field_dm

</details>

### Translation

<details>
<summary>Click to expand</summary>

|Syscollector package field|Installed database line|
|-|-|
|name|P: - package name (corresponds to pkgname in PKGINFO)|
|version|V: - package version (corresponds to pkgver in PKGINFO)|
|vendor|*|
|install_time|*|
|location|F: - directory name that was created by package, repeated|
|architecture|architecture (corresponds to arch in PKGINFO), optional|
|groups|*|
|description|T: - description (corresponds to pkgdesc in PKGINFO)|
|size|I: - installed size, integer (corresponds to size in PKGINFO)|
|priority|*|
|multiarch|*|
|source|*|
|format|*|
|checksum|-|
|item_id|-|
|db_status_field_dm|-|

**Note: Some fields are for internal use ("-"). The format field is hard coded for other systems (we can use "apk")**
**Note: install_time, location, multiarch, and source may be not present in Ubuntu systems**
**Note: vendor is hard coded for Arch Linux systems. The same approach could be used for Alpine Linux (Vulnerabilities feed: https://security.alpinelinux.org/)**
**Note: priority may be not present in Centos systems (rpm)**
**Note: groups may be set as "unspecified" in Centos systems (rpm). So we can ignore this information for Alpine Linux**

![image](https://user-images.githubusercontent.com/13010397/207930148-56a22eba-7689-449c-9c66-f540620d7254.png)
![image](https://user-images.githubusercontent.com/13010397/207934877-57ab4b99-1644-47d3-b8bf-da8d4c4c3de3.png)

</details>

### References

https://wiki.alpinelinux.org/wiki/Apk_spec

## System inventory overview on Alpine Linux
### Hardware

<details>
<summary>Click to expand</summary>

```json
{
  "hw": {
    "board_serial": "0",
    "cpu_cores": 4,
    "cpu_mhz": 2592.0,
    "cpu_name": "Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz",
    "ram_free": 3958008,
    "ram_total": 4042300,
    "ram_usage": 3
  }
}
```

</details>

### Network

<details>
<summary>Click to expand</summary>

```json
{
  "networks": {
    "iface": [
      {
        "IPv4": [
          {
            "address": "10.0.2.15",
            "broadcast": "10.0.2.15",
            "dhcp": "enabled",
            "metric": "202",
            "netmask": "255.255.255.0"
          }
        ],
        "IPv6": [
          {
            "address": "fe80::a00:27ff:fe19:e156",
            "broadcast": "",
            "dhcp": "enabled",
            "metric": "",
            "netmask": "ffff:ffff:ffff:ffff::"
          }
        ],
        "adapter": "",
        "gateway": "10.0.2.2",
        "mac": "08:00:27:19:e1:56",
        "mtu": 1500,
        "name": "eth0",
        "rx_bytes": 57912172,
        "rx_dropped": 0,
        "rx_errors": 0,
        "rx_packets": 42060,
        "state": "up",
        "tx_bytes": 399211,
        "tx_dropped": 0,
        "tx_errors": 0,
        "tx_packets": 4862,
        "type": "ethernet"
      },
      {
        "IPv4": [
          {
            "address": "192.168.56.146",
            "broadcast": "192.168.56.255",
            "dhcp": "unknown",
            "metric": "0",
            "netmask": "255.255.255.0"
          }
        ],
        "IPv6": [
          {
            "address": "fe80::a00:27ff:fe40:91e6",
            "broadcast": "",
            "dhcp": "unknown",
            "metric": "",
            "netmask": "ffff:ffff:ffff:ffff::"
          }
        ],
        "adapter": "",
        "gateway": " ",
        "mac": "08:00:27:40:91:e6",
        "mtu": 1500,
        "name": "eth1",
        "rx_bytes": 9989,
        "rx_dropped": 0,
        "rx_errors": 0,
        "rx_packets": 55,
        "state": "up",
        "tx_bytes": 1480,
        "tx_dropped": 0,
        "tx_errors": 0,
        "tx_packets": 12,
        "type": "ethernet"
      }
    ]
  }
}
```

</details>

### Processes

[processes.txt](https://github.com/wazuh/wazuh/files/10237114/processes.txt)

### Ports

<details>
<summary>Click to expand</summary>

```json
{
  "ports": [
    {
      "inode": 6602,
      "local_ip": "0.0.0.0",
      "local_port": 68,
      "pid": 2429,
      "process": "dhclient",
      "protocol": "udp",
      "remote_ip": "0.0.0.0",
      "remote_port": 0,
      "rx_queue": 0,
      "state": "",
      "tx_queue": 0
    },
    {
      "inode": 6495,
      "local_ip": "10.0.2.15",
      "local_port": 59917,
      "pid": 2031,
      "process": "ntpd",
      "protocol": "udp",
      "remote_ip": "162.159.200.123",
      "remote_port": 123,
      "rx_queue": 0,
      "state": "",
      "tx_queue": 0
    },
    {
      "inode": 7756,
      "local_ip": "10.0.2.15",
      "local_port": 53947,
      "pid": 2031,
      "process": "ntpd",
      "protocol": "udp",
      "remote_ip": "168.96.251.197",
      "remote_port": 123,
      "rx_queue": 0,
      "state": "",
      "tx_queue": 0
    },
    {
      "inode": 6496,
      "local_ip": "10.0.2.15",
      "local_port": 38116,
      "pid": 2031,
      "process": "ntpd",
      "protocol": "udp",
      "remote_ip": "168.96.251.195",
      "remote_port": 123,
      "rx_queue": 0,
      "state": "",
      "tx_queue": 0
    },
    {
      "inode": 6493,
      "local_ip": "10.0.2.15",
      "local_port": 54821,
      "pid": 2031,
      "process": "ntpd",
      "protocol": "udp",
      "remote_ip": "162.159.200.1",
      "remote_port": 123,
      "rx_queue": 0,
      "state": "",
      "tx_queue": 0
    },
    {
      "inode": 4732,
      "local_ip": "0.0.0.0",
      "local_port": 22,
      "pid": 2049,
      "process": "sshd",
      "protocol": "tcp",
      "remote_ip": "0.0.0.0",
      "remote_port": 0,
      "rx_queue": 0,
      "state": "listening",
      "tx_queue": 0
    },
    {
      "inode": 8349,
      "local_ip": "10.0.2.15",
      "local_port": 22,
      "pid": 2351,
      "process": "sshd",
      "protocol": "tcp",
      "remote_ip": "10.0.2.2",
      "remote_port": 46594,
      "rx_queue": 0,
      "state": "established",
      "tx_queue": 0
    },
    {
      "inode": 4734,
      "local_ip": "::",
      "local_port": 22,
      "pid": 2049,
      "process": "sshd",
      "protocol": "tcp6",
      "remote_ip": "::",
      "remote_port": 0,
      "rx_queue": 0,
      "state": "listening",
      "tx_queue": 0
    }
  ]
}
```

</details>

**Verified the implementation as part of this issue: https://github.com/wazuh/wazuh/issues/3859**

Port 2049 NFS seems to be in use but the service is not active. 

![image](https://user-images.githubusercontent.com/13010397/207870233-399e10a3-de1e-4f77-9e49-ee07dee8fa46.png)

Anyways, the behavior is expected since it was not possible to obtain that information during the implementation of that issue.

### Os

<details>
<summary>Click to expand</summary>

```json
{
  "os": {
    "architecture": "x86_64",
    "hostname": "alpine38.localdomain",
    "os_name": "Alpine Linux",
    "os_platform": "alpine",
    "release": "4.14.167-0-virt",
    "sysname": "Linux",
    "version": "#1-Alpine SMP Thu Jan 23 10:58:18 UTC 2020"
  }
}
```

</details>

Here we have missing information: 
- os_version
- os_codename
- os_major
- os_minor
- os_patch
- os_build
- os_release
- os_display_version

At least it would be desirable to have **os_version** and by consequence **os_major** and **os_minor**. That lack of information may affect the vulnerability detector scan.

## Misc findings 

### Wrong OS information UI 

![image](https://user-images.githubusercontent.com/13010397/207873692-54d84d19-278d-4102-b331-f3fb3209c3dc.png)

### Missing handle for openRC init system 

![image](https://user-images.githubusercontent.com/13010397/207875080-e45526a1-c989-45cb-8465-b6e678c2e657.png)

### It does not detect the previous installation. 

The following prompt is never shown. (Image from Ubuntu agent)
![image](https://user-images.githubusercontent.com/13010397/207875372-518144a8-cb5d-459e-89c7-1d0e146c7fe7.png)

### Grep/Egrep warning during installation for Alpine 3.17

![2022-12-14_15-28](https://user-images.githubusercontent.com/13010397/207873238-4cb9a6e0-e80f-448e-beca-3a2bc6fb59ec.png)

### Wazuh-execd won't start on newer Alpine Linux versions (>3.9)

![2022-12-14_16-05_1](https://user-images.githubusercontent.com/13010397/207873260-681beb11-5aa0-4f82-93c8-4707485c9fd5.png)

### Packages size mismatch on different systems.

Ubuntu
![image](https://user-images.githubusercontent.com/13010397/207935107-2c948cb0-f05b-425c-8192-e31e83818cd0.png)
Centos
![image](https://user-images.githubusercontent.com/13010397/207935140-93304eb8-e704-4c58-9724-c8c9e370b101.png)
Alpine
![image](https://user-images.githubusercontent.com/13010397/207937108-7dc700a8-0eb3-46da-8706-382ef9303cb3.png)
