### ISSUE TITLE
Vulnerability detector for MacOS agents works erratically

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#13758]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.x | Vulnerability detector | Manager | Packages/Sources | macOS |

## Description

This issue in the first place is to identify what is happening with the module, and what makes it unstable when it comes to detecting something in this system.

To do this, you must first define and search for packages (minimum 10) that we know are vulnerable.

Then we must add a test that shows the problem and then give it the pertinent solution so that this does not happen again.

This should be tested and proven on macOS 10.14, 10.15, 11 and 12.

TARGET VERSION 4.4

## DoD
- [ ] RCA (Root cause analysis)
- [ ] Add test, find a systematic way to reproduce this issue.
- [ ] Fix the issue.
- [ ] Exploratory test.

**Comment by MiguelazoDS** [comment]
# Manual test macOS 10.14.3 (Mojave)

### Global DB 
![1](https://user-images.githubusercontent.com/13010397/172456759-b56c4daf-1cdb-4420-8ed4-9a3dd06917e5.png)

- Related to the `os_build` field, it is set here but is unused, although it won't cause a misbehave if it is NULL.

  ```c
  int wm_vuldet_collect_agents_to_scan(wm_vuldet_t *vuldet) {
    /* ... */
   agents->build = agti_build;
   /* ... */ 
   }
  ```
### Vulnerabilities found and alerted 
![2](https://user-images.githubusercontent.com/13010397/172456766-03e4f36a-8d1b-4514-82a3-7a3d4f0c95fe.png)

### Packages inventory 

![3](https://user-images.githubusercontent.com/13010397/172458741-451565a8-78ac-4869-81b5-04301fa94771.png)

### Logs and alert files.

[alerts.log](https://github.com/wazuh/wazuh/files/8855756/alerts.log)
[ossec.log](https://github.com/wazuh/wazuh/files/8855686/ossec.log)

**Comment by pereyra-m** [comment]
### Synchronization delay

The above comment has shown that Vulnerability Detector is able to properly scan the MacOS agents.
But there are times where a recently registered agents isn't able to send its data (OS and packages) in the first **syscollector** scan.
This situation generates the following messages because Vulnerability Detector can't scan an agent if its **sys_osinfo** table (in the individual DB in the manager) is empty

```
2022/06/07 19:06:15 wazuh-modulesd[5609] wdb_agents_helpers.c:37 at wdb_get_agent_sys_osinfo(): INFO: Agents DB (2): No OS information available.

2022/06/07 19:06:15 wazuh-modulesd[5609] wdb_agents_helpers.c:37 at wdb_get_agent_sys_osinfo(): INFO: Agents DB (3): No OS information available.
```

If a new scan of **syscollector** is performed by restarting the agent or waiting the corresponding interval, the information is sent and the vulnerabilities are found.
