### ISSUE TITLE
CentOS manager shows wazuh-db memory increase

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#13750]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.4-rc1 | wazuh-db | Manager | Packages | Centos7 |

Analyzing the stress test https://github.com/wazuh/wazuh/issues/13737, I have observed that the manager shows a higher memory usage of wazuh-db than the one shown in 4.3.1.

In 4.3.1, the memory usage in the RSS graph was ~25MB while in 4.3.4-rc1, this usage has gone up to ~40MB and seems to be going up

- https://github.com/wazuh/wazuh/issues/13737

![image](https://user-images.githubusercontent.com/14913942/172211867-adb7d8ad-72c9-4790-ad0c-36ffca6aafb1.png)

- https://github.com/wazuh/wazuh/issues/13464

![image](https://user-images.githubusercontent.com/14913942/172211792-c9f3bc46-fb2e-445d-a4e3-24d47c420fa3.png)

- Looking at the Read_ops plot, it can be seen that wazuh-db has a higher use than 4.3.1

![image](https://user-images.githubusercontent.com/14913942/172213699-9de12bbb-6e3d-451a-bef0-3835bb9d54c7.png)
![image](https://user-images.githubusercontent.com/14913942/172213679-e5a3ad74-580f-4a65-9982-a504a0398db0.png)

- Write_ops plots

![image](https://user-images.githubusercontent.com/14913942/172214059-9b0ccc77-0800-47a7-b961-9f8dde88d737.png)
![image](https://user-images.githubusercontent.com/14913942/172214076-147cb4ce-6f7f-4c67-9e24-6fa2aeaeae83.png)

**Comment by chemamartinez** [comment]
### RSS increase in `wazuh-modulesd`

This is due to memory fragmentation when executing SCA scans as it is explained in this comment, https://github.com/wazuh/wazuh/issues/10107#issuecomment-1015496635, where we can see the same graphics. This problem is solved in 4.4.0 with the use of `jemalloc` for `wazuh-modulesd` in the manager.

This problem was reported because we detected two similar tests (apparently) with different behavior:
- https://github.com/wazuh/wazuh/issues/13736
- https://github.com/wazuh/wazuh/issues/13737
The main difference between both tests is that #13736 runs macOS and Solaris agents, and the second one is for Linux and Windows agents. For the first case, the manager runs SCA, unlike in the second one. 

@wazuh/cicd why does the manager have different configurations if the purpose of having both tests is to run different agent OSs?

### RSS increase in `wazuh-db`

On the other hand, the RSS graphs of `wazuh-db` show more usage than the same test for 4.3.1. In this case, we need further analysis to determine the cause.

So far we can draw the following conclusions from the analysis made:
- Once analyzed logs and configurations from both managers compared in this issue, they have the same operation during the whole test, working as expected and having the same load in `wazuh-db`.
- Changes introduced in the latest patch versions (from 4.3.1 to 4.3.4) don't affect `wazuh-db` or modules related to it.
- No memory leak is appreciated. The memory usage gets stable under 40MB. We can see that this threshold is the normal value for example in the latest test for 4.3.0-RC7 where the RSS for `wazuh-db` remains at 40MB during the whole test as well. https://github.com/wazuh/wazuh/issues/13288

*RSS usage for the same test in 4.3.0-RC7*
![image](https://user-images.githubusercontent.com/29475387/172663185-d7407580-ebf5-445e-9e50-463f784cbd4a.png)
