### ISSUE TITLE
Vulnerability detector for Windows agents not detect operating system vulnerabilities.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#13759]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.x | Vulnerability detector | Manager | Packages/Sources | Windows |

## Description
This issue aims to first identify what causes this problem in agents that are windows, basically the reported problem is that vulnerable systems (both because they are old versions or because of unapplied patches) are not marked as vulnerable, as appropriate.

This needs to be tested with BlueKeep (RDP Vulnerability) as an example or any other known issues.

It is important in the procedure to add a test to prevent this from happening again, this is vital for the fix.

TARGET VERSION 4.3.5

## DoD
- [ ] RCA
- [ ] Add test to reproduce this issue.
- [ ] Fix the incorrect behavior.

**Comment by HanesSciarrone** [comment]
## First investigation of the problem

Currently, in Wazuh, we have some issues that may be related to the problem:

- #13768 
- #13259 (Apparently fixed in 4.3)
- #8434

**Comment by pereyra-m** [comment]
## Analysis of ignored vulnerabilities

In the comment above we can see that Vulnerability Detector is ignoring some vulnerabilities because these CVE's don't have the corresponding patch in the MSU. 
This scanner takes that decision but it seems that in some cases the fix does exists.

## Windows server 2019


**CVE-2019-1183**

<details>
<summary>
Analysis
</summary>


The NVD reports the OS as vulnerable
https://nvd.nist.gov/vuln/detail/CVE-2019-1183

The Microsoft Catalog says that this vulnerability was covered covered by the fixes of **CVE-2019-1194**
https://msrc.microsoft.com/update-guide/vulnerability/CVE-2019-1183

If we check the details of https://msrc.microsoft.com/update-guide/vulnerability/CVE-2019-1194, we can see that there is a patch for this OS (**KB4511553**). 
![1194](https://user-images.githubusercontent.com/65046601/172653460-84b8a016-0aa7-4d0c-afe9-5d90c58f49e9.png)

Analyzing the `cve.db`:
- The MSU table doesn't have any entry related to `CVE-2019-1183`
- The MSU table has an entry related to `CVE-2019-1194`

</details>

**Conclusion**: link both `CVE-2019-1183` and `CVE-2019-1194` vulnerabilities to avoid this false negative

**Comment by HanesSciarrone** [comment]
# Analysis of ignored vulnerabilities for Windows 2010 Home (version 10.0.19043)

After we have done the **Testing over Windows**  we can see that Vulnerability Detector has ignored some vulnerabilities because these CVE's don't have the corresponding patch in the MSU.
The Vulnerability Detector scanner takes that decision but it seems that in some cases a more detailed analysis is required

#### [CVE-2021-34481](https://github.com/advisories/GHSA-6m3c-jc2v-9h92)

<details>
<summary>Analysis</summary>

On the NDV WIndows 10 appear as vulnerability for this CVE

![CVE-2021-34481](https://user-images.githubusercontent.com/58960358/172533305-609f4014-ca52-44e6-a188-a0fe9ee3bf87.png)

[NVD CVE-2021-34481](https://nvd.nist.gov/vuln/detail/CVE-2021-34481)

On the Microsoft catalog indicate that this vulnerability was fixed with the security update [KB5005652](https://support.microsoft.com/en-us/topic/kb5005652-manage-new-point-and-print-default-driver-installation-behavior-cve-2021-34481-873642bf-2634-49c5-a23b-6d8e9a302872)

[Microsotf Catalog CVE-2021-34481](https://msrc.microsoft.com/update-guide/en-US/vulnerability/CVE-2021-34481)

![image](https://user-images.githubusercontent.com/58960358/172894406-6ed9b354-a9ff-4991-8f40-ea6a637ca934.png)

![CVE-win](https://user-images.githubusercontent.com/58960358/172907995-1f379420-e51b-4dc7-91b4-fdb4aa9505f4.png)

On the MSU isn't a CVE and path combination 

**Conclusion**: There are data missed on the Wazuh MSU database. 

</details>

**Comment by Dwordcito** [comment]
@santiago-bassett
