### ISSUE TITLE
AWS Waf logs

### ISSUE THREAD

**Issue by usmanaa10** [wazuh/wazuh#13847]
### Discussed in https://github.com/wazuh/wazuh/discussions/13812

<div type='discussions-op-text'>

<sup>Originally posted by **usmanaa10** June 10, 2022</sup>
Hi Friends,
             Wazuh is successfully fetching logs from bucket with no error or warning, I run wodle  manually too and got the following result shown in the image
![image](https://user-images.githubusercontent.com/66419518/173047792-a00a02cb-3625-41c8-bf97-90d9dcbf86a5.png)
 

But unfortunately i am not seeing any result on dashboard

![image](https://user-images.githubusercontent.com/66419518/173048006-d9566133-45e0-4035-ac96-6c0825b0648f.png)

Kindly help me out in resolving this issue ASAP... my project is not moving forward</div>

**Comment by CarlosRS9** [comment]
Hi @usmanaa10,

The output screenshot you have attached does not tell us if the module is fetching logs successfully or not. The `Skipping file with another prefix` messages mean that during execution logs were found inside the S3 bucket but they are being ignored because they are in a different path than the one you have configured.

Verify that you have correctly configured the path where your WAF logs are located. The default path follows the format `<bucket_name>/<year>/<month>/<day>/<hh>`. It is possible to alter this path and process logs that are in custom folders inside your S3, as long as they follow this format: `<bucket_name>/<PREFIX>/<year>/<month>/<day>/<hh>`. In this case, it is necessary to specify this prefix via the [path](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#bucket-path) tag.

Regarding the supported WAF logs, please note that you need to configure WAF as described in our [official documentation](https://documentation.wazuh.com/current/amazon/services/supported-services/waf.html#amazon-configuration). That is, you must make use of Kinesis. We are aware that WAF offers an option to store logs directly in S3 without the need for Kinesis. This option is not supported by Wazuh. Our integration with AWS will only process your WAF logs if they have been stored into S3 by Kinesis.


That being said, if you need further assistance from us, please confirm the following:

1. The Wazuh version you are using.
2. An example of the path where you have WAF logs that you want Wazuh to process. Remove any sensitive information.
3. The configuration you are applying in ossec.conf, so that I can check it for errors. Don't forget to remove any sensitive information, such as secret and access keys if present.

**Comment by hitman28594** [comment]
Can I add 1 thing here please:

the bucket type=“waf” option basically just supports JSON formatted logs. But officially the aws-s3 Wodle doesn’t support them. 


If we’re making updates to this Wodle, Can we add ‘official’ support for json formatted data into the aws-s3 Wodle and update the wazuh-docs?… I believe this needs to be hard coded and then compiled (copy and paste of the aws-dw.py code for the ‘waf’ block didnt work, lol ).

**Comment by hitman28594** [comment]
And if it’s not too time consuming, maybe adding support for CSV formatted data too? With an option to specify the csv delimiter? 

This would allow wazuh to integrate with tons of other logsources which use pre-defined data structures like json and csv.

**Comment by CarlosRS9** [comment]
> the bucket type=“waf” option basically just supports JSON formatted logs. But officially the aws-s3 Wodle doesn’t support them.

It is true that when you configure `bucket type="waf"` the module is processing logs in JSON format. However, this cannot be used to process any JSON-formatted log. The integration in this case is looking for some WAF specific fields within that JSON. If the fields are not present, the log will not be processed correctly. Therefore, it cannot be used to process generic JSON logs unless major modifications are applied to the module.


> If we’re making updates to this Wodle, Can we add ‘official’ support for json formatted data into the aws-s3 Wodle and update the wazuh-docs?… I believe this needs to be hard coded and then compiled (copy and paste of the aws-dw.py code for the ‘waf’ block didnt work, lol ).

It is not necessary to change anything in the C code, so it is not necessary to compile anything. The changes would be limited to the `aws-s3.py` file. However, the changes needed are somewhat tricky, so this is not a simple modification.

We realize how useful it would be to be able to process custom logs in JSON format regardless of their origin. This would allow for example to process WAF or Config logs that have been stored directly in S3 by their respective services, instead of relying on Kinesis as our documentation states. That is why we proposed such development, which you can follow from [here](https://github.com/wazuh/wazuh/issues/13577). Keep in mind one thing, and that is that the development is still a proposal. Currently we have more priority tasks in our roadmap, so do not expect this can be addressed in the short or medium term. However, you can use this issue in the future to keep you informed of updates.


> And if it’s not too time consuming, maybe adding support for CSV formatted data too? With an option to specify the csv delimiter?

this is an interesting proposal that we have not taken into consideration for the moment. If you really think that would be useful feel free to open an issue requesting such a development [here](https://github.com/wazuh/wazuh/issues/new?assignees=&labels=external_integrations&template=external-integrations.md&title=). Our team will evaluate its impact and determine the possibility of adding it to our roadmap.
