### ISSUE TITLE
Wazuh-db could delete the 'queue/diff' directory completely

### ISSUE THREAD

**Issue by Nicogp** [wazuh/wazuh#13875]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4/4.5 | wazuh-db | Manager/Agent | Sources | Ubuntu 20.04 |

Hello team, 

I found a condition where the `wm_clean_agent_artifacts()` function is calling the `delete_diff()` function without the `agent_name `which causes the entire `queue/diff/` directory to be deleted and due to this I get errors like
```
2022/06/14 14:48:10 wazuh-analysisd: ERROR: (1107): Could not create directory 'queue/diff/ubuntu-bionic' due to [(2)-(No such file or directory)].
2022/06/14 14:48:10 wazuh-analysisd: ERROR: Unable to create last file: queue/diff/ubuntu-bionic
2022/06/14 14:48:10 wazuh-analysisd: ERROR: (1107): Could not create directory 'queue/diff/ubuntu-bionic' due to [(2)-(No such file or directory)].
2022/06/14 14:48:10 wazuh-analysisd: ERROR: Unable to create last file: queue/diff/ubuntu-bionic
```
Environment:

- agent version: 4.4/4.5 
- manager version: 4.4/4.5.

## Steps to reproduce:

Force the agent to stay trying to register:
To do this, I set local_ip in the remote section of the manager:
```
<remote>
    <connection>secure</connection>
    <port>1514</port>
    <protocol>tcp</protocol>
    <queue_size>131072</queue_size>
    <local_ip>192.168.0.12</local_ip>
  </remote>
```
To do this, I set local_ip, in the remote section of the admin, to the ip of the second network interface.

In the address section of the server block of the agent configuration, I configured the ip of the first interface of the manager, in this way the agent will be able to register but not connect

```
<server>
    <address>10.0.0.2</address>
    <port>1514</port>
    <protocol>tcp</protocol>
  </server>
```

Let the agent register for the first time.

Then when the agent tries to connect and fails, it will ask for a new password, when the manager logs the message:
`WARNING: Duplicate name 'agent-ubuntu', rejecting enrollment. Agent 'xxx' doesn't comply ....`
remove the agent using the manage-agent tool

Then when the agent requested the key again the queue/diff directory will be deleted.

In the following image you can see this situation, I added some error logs to understand what was happening
![image](https://user-images.githubusercontent.com/13004400/173632245-b5da8dd5-21b0-4749-86c0-d5fa01ba7060.png)

**Comment by MiguelazoDS** [comment]
# Analysis
## Steps to reproduce (similar to the ones described above)

- Let the agent register for first time
- Stop Wazuh service
- Delete entry in global database for the agent
- Delete entry in client.keys for the agent
- Start Wazuh service

### Logs 

[ossec.log](https://github.com/wazuh/wazuh/files/8922082/ossec.log)

The diff directory was deleted.
![1](https://user-images.githubusercontent.com/13010397/174154521-f680c563-3c5d-40b6-be84-46c6752da07b.png)
Database not deleted due to a name mismatch.
![2](https://user-images.githubusercontent.com/13010397/174154531-75b4d4af-6d1e-4b1e-8681-b100ccd9da00.png)

## Findings
The issue occurs in the function `sync_agents_artifacts_with_wdb` where we try to clean the artifacts for an agent that has not an entry in the global database. 

```c
if (*agent_name == '\0') {
    // Agent not found. Removing agent artifacts
    wm_clean_agent_artifacts(agent_id, agent_name);
}
```

But the function `wm_clean_agent_artifacts` internally requires a non-empty string as agent_name to remove legacy databases in `/var/ossec/var/db/agents` and files under `/var/ossec/queue/diff`

So, when the agent is not found in the global DB the function in charge to clean the artifacts receives an empty string with the consequences already mentioned.

## Proposal

A check before attempting to remove the database and the agent diff was added to avoid undesired behavior when the agent name is empty. 

The artifacts are not removed though, we should evaluate how to get the agent name information from other sources than the global database. 

The function `wdb_remove_agent_db` is similar to `delete_sqlite`
