### ISSUE TITLE
Investigate performance issues with `PUT /agents/group` API endpoint

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#13872]
After the changes made in https://github.com/wazuh/wazuh/issues/10771, we have run the Workload tests for an environment with 50000 agents and 25 worker nodes.

![image](https://user-images.githubusercontent.com/15522808/173555525-3af2cac8-542f-4eb9-855d-5a17e97f61be.png)

In the results of these tests we have noticed that all the performance problems have disappeared except the ones related to the `PUT /agents/group` endpoint. Therefore, in this issue we are going to investigate the issues with the endpoint and try to improve it in order to avoid this kind of problems.

**Comment by GGP1** [comment]
## Update

The performance of this endpoint is poor because we are performing two operations for evert agent that is assigned to a group

1. Get agent's groups
2. Set new agent-group relationship

For each one of these two we are opening a new socket connection to wazuh-db, meaning that if we were to assign 10 agents, 20 socket connections would be opened to wazuh-db.

Furthermore, the updates are performed sequentially and one by one, there's no batching or concurrency.

I tried reusing the same socket connection to avoid creating a new one for each query but there doesn't seem to be any performance improvement.

<details><summary>Logs</summary>

### 2 socket connections per agent

```console
2024/05/24 13:33:16 INFO: wazuh 172.18.0.1 "PUT /agents/group" with parameters {"wait_for_complete": "true", "group_id": "default2"} and body {} done in 321.521s: 200
```

### 1 socket connection for all

```console
2024/05/24 14:11:54 INFO: wazuh 172.19.0.1 "PUT /agents/group" with parameters {"wait_for_complete": "true", "group_id": "default2"} and body {} done in 329.028s: 200
```

</details>

I think we should try to batch the updates to perform many operations in a single query instead of creating one query per update.

**Comment by fdalmaup** [comment]
# Review

The code related to the endpoint was correctly analyzed, explaining where the low-performance issue comes from. The `set new agent-group relationship` might be the one with a higher cost to execute in terms of database processing, that's why modifying the number of sockets used did not represent an improvement.

As correctly mentioned in the last update, the `global.db` will be removed in version `5.0`, so we should consider that before the release of said version the endpoint's performance will continue being low but be careful that it does not get worse.

LGTM!
