### ISSUE TITLE
HA and Auto-scaling in AWS

### ISSUE THREAD

**Issue by toniblyx** [wazuh/wazuh#139]
Hi guys,
I still working on a CloudFormation template to deploy a Wazuh infrastructure totally scalable and in high availability using VPC with public and private subnets, bastion host, ELB and multiple Availability Zones for better reliability. I already have tried with around 100 agents and definitely I need an autoscaling config for our production accounts.

Key point in this deployment is not only to have automated the server side deployment and scaling but also clients (agents) auto-provisioning and a "Satellite" to forward traffic from each AWS account or VPCs to the Wazuh infrastructure. Having Satellites to forward traffic to the server, I can better control what IP can connect to the Wazuh API (55000) for auto-provisioning and to the Wazuh data (1514TCP in my case) to send the actual OSSEC agent data. 

This is the rough diagram of what I have working right now:

```
Agent ---> Satellite ---> ELB ---> Wazuh Server ---> Logstash ---> ElasticSearch <--- Kibana
```
FYI: each Satellite, is an EC2 instance that has automated installed and configured haproxy to forward traffic from agents to ELB, then to Wazuh. I will provide the script I use to build it, very straightforward.

What I want to use is the AWS Elasticsearch service to forget about manage or even install those instances and have them in HA. I don't need Kibana in HA (not 100% mandatory for me). And I will create a Logstash autoscaling group as well.

Now, my questions are as follow:

1.  **Clustering** of Wazuh server (OSSEC): can I configure two or more EC2 instances using /var/ossec as shared file system between wazuh server nodes? With EFS would be very easy, and autoscaling would be also straightforward. Wouldn't need to replicate client.keys in that case. Do I need to set remoted.verify_msg_id=0 even if I use ELB as load balancer and unique inbound IP?
2. **Agent auto-provisioning**: since in AWS we may have hundreds or thousands of instances up or down (elasticity is important here), auto-provisioning is key for us. I found that using curl with Wazuh API is a very helpful and easy way to do so, but it is not secure because I have to provide the API password on each agent. If an agent is compromised, I might have Wazuh compromised as well. Wazuh API authorization system seems to be black or white, there are not permissions or roles definitions for users. Is there a plan to improve that part? Other recommendation to make the auto-provisioning more secure? 
3. **Satellite**: considering that when an agent losts connection with the server (or anything in between), data gets lost. Could I use something different to haproxy to use it as cache or queue in addition to be a mere traffic forwarder? Recommendations? We would add more resilience there.

Note about our auto-provisioning script: when a new instance spin up, it runs this command:
`curl -s https://s3.amazonaws.com/sample-bucket/installation-wazuh-agent-mode.sh | bash -s --`
so no files with password keep in the instance but evidences might be founded using forensics mechanisms (RAM dump, etc).

Thanks guys for the great work you are putting on Wazuh and I'm really looking forward to finish this project to contribute it back to the community behind Wazuh.

**Comment by vikman90** [comment]
Hi @toniblyx,

sorry for late response. I will try to answer your questions:

1. I haven't worked with AWS in order to reach HA but I did some experiments using Docker. I don't recommend you to share the entire folder `/var/ossec` since logs at `/logs` and sockets or databases at `/queue` may be corrupted. We worked on making the `/etc/client.keys` file shareable by multiple instances, so you should only share `/var/ossec/etc` and export alerts using a tool such Filebeat (forwarding to a shared Logstash server).

2. You can use Wazuh API to register new agents on the server, but if you do not want to share a key you may take a look to other methods. For example, you may use Auth with SSL certificates for manager to verify agents. Please take a look at [Wazuh documentation: Registering agents](https://documentation.wazuh.com/current/user-manual/agents/registering-agents/index.html).

3. When agents detect that connection to manager is lost, they stop sending information. You may lose data until this condition is detected, or if a monitored log is rotated before communication is reestablished. You may also lose some logs due to the communication protocol (UDP), that does not guarantee message delivery. Maybe you want to try to use TCP [Wazuh documentation: Client reference](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html). This mode has two advantages: every log is guaranteed to arrive to the manager, and disconnection detection is immediate.

Thank you for your words, and I hope these answers are helpful for you.

Best regards.

**Comment by mathieupythian** [comment]
@toniblyx   I'm currently considering whether I should attempt HA on AWS for the Wazuh Server or not.  Any insights you have from your experience would be greatly appreciated.

Some questions:

1. Since your last post, have you stayed with active-passive, or were you able to have more than one Wazuh Server active at the same time (sharing parts of the file system using EFS?)?  I'm wondering if that's at all possible... considering some alerts would be trigger only if some event happen X times.

2. Assuming you stayed with only one Wazuh Server active at a time, how has been the performance with X agents?

3. What type of EC2 instances are you using for the Wazuh Server to support X agents?

Thanks in advance.

**Comment by toniblyx** [comment]
Hi @mathieupythian, 
First of all, I still working on it (busy with other tasks). At this time I think the best way to perform HA with Wazuh manager is having it active-passive syncing configuration between the active node and the failover node (using a S3 bucket). Using EFS doesn't work since you can't open loop files on a NFS (EFS) shared volume. In my case I have tested with around 150 agents and performed well in a t2.medium, but remember I only have Wazuh manager installed on that instance. I'm working on a CloudFormation template with every service separated by tier, so it makes it easier to scale in and out and also requires smaller instance type per tier, you will be also able to chose the instance type at launch once the template is ready.

**Comment by mgmacias95** [comment]
Hello @toniblyx and @mathieupythian,

It's been almost a year since the last comment on this issue, so I'm closing it.

Don't hesitate to open a new one if you still have questions or problems.

Best regards,
Marta
