### ISSUE TITLE
"scan_on_start no" doesn't work the first time

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh#1394]
On Windows agents, the wodle-command with _scan_on_start_ to _no_ doesn't work the first time.

```
 <wodle name="command">
    <disabled>no</disabled>
    <tag>my_tag</tag>
    <command>/bin/bash /var/ossec/etc/shared/my_script.sh</command>
    <run_on_start>no</run_on_start>
    <interval>5m</interval>
 </wodle>
```

The first time, it runs the command. The proper behavior is: 
- Use the start time as reference.
- Run the command after the interval (Ex: reference + 5 min).

Why is this important?
- It doesn't do what it should do: Avoid execution on the start.
- Infinite loop of restarts if the script restart the agent.
  - In the example, we want to change the ossec.conf and restart the agent every hour.
  - If during the start, the command is executed (even with _scan_on_start no_), the script restarts the agent. Then, in the start the command is executed again ...

This should be fixed in every component.
Localfile should have the _run_on_start_ setting too.

**Comment by juan70** [comment]
Testing.
==
- Install a fresh manager.
- Install a Windows agent.
- On the agent:
  - In `local_internal_options.conf`: add `wazuh_command.remote_commands=1`
  - In `ossec.conf`, add
    ```
    <!-- TEST a kind of equivalent for Linux's `touch` command -->
    <wodle name="command">
      <disabled>no</disabled>
      <tag>my_test</tag>
      <command>cmd /c "type nul > c:\ztesting\zzz.txt"</command>
      <run_on_start>no</run_on_start>
      <interval>2m</interval>
      <ignore_output>yes</ignore_output>
    </wodle>
    ```
    With `<run_on_start>no</run_on_start>`.
- Register the agent
- Start the agent
- Result:
  - after `2m`, as specified in `ossec.conf <interval>` , an empty file named `zzz.txt` is created in the directory `C:\ztesting`.
  - after 2 more minutes, the file is written again, so that the modification time is modified.
  - etc.


For example, when the agent starts, `ossec.log` receives:
```
2018/11/19 14:01:16 wazuh-modulesd:command: INFO: Module command:my_test started
2018/11/19 14:01:16 wazuh-modulesd:command: INFO: my_test: Waiting for turn to evaluate.
(...)
2018/11/19 14:01:50 wazuh-modulesd:command: INFO: Module command:my_test started
2018/11/19 14:01:50 wazuh-modulesd:command: INFO: my_test: Waiting for turn to evaluate.
```
(Starts twice? In `ossec.log` on the manager: 1. 'New ossec agent connected', and 2. 'Ossec agent started')
 
On the Windows agent, the file is created 2 minutes later:
```
PS C:\ztesting>   dir


    Directory: C:\ztesting


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---        19/11/2018  14:03:50          0 zzz.txt
```
And modified 2 minutes later:
```
PS C:\ztesting>   dir


    Directory: C:\ztesting


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---        19/11/2018  14:05:50          0 zzz.txt  
```
Etc.
