### ISSUE TITLE
Create Wazuh rules based on agent group criteria

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#1395]
It would be really helpful if that information were included in the alerts as it would allow to search alerts regarding one specific group.

The main objective here is to be able to create rules based on the group that agents belong to.

**Comment by jesusgn90** [comment]
We must use an array due to multi-groups so the alert must be as follow:

`agent.groups: [group-01, group-02, ...]`

**Comment by Leamsy** [comment]
I have managed to show groups in the agent-info files, like this:

```
Linux |agent-centos |3.10.0-957.1.3.el7.x86_64 |#1 SMP Thu Nov 29 14:49:43 UTC 2018 |x86_64 [CentOS Lin$
4367402604bdb28dfcf19f77d5e25b71 merged.mg
#"_agent_ip":10.0.2.15

#"_manager_hostname":localhost.localdomain
#"_node_name":node01
#"_agent_groups":default,group1
```
Right now working on adding the groups label into the json files so it shows on the alerts log.

**Comment by Leamsy** [comment]
Agent groups label added to json file, but as a single string. Working on separating them into an array and also adding them to the elasticsearch template.

**Comment by chemamartinez** [comment]
Hi all,

After further discussions about this issue, we have decided to redesign its implementation by making Wazuh-DB be the module in charge of managing the agents' metadata (such as groups, IP addresses, keys, etc.).

This issue is blocked as long as those responsibilities are transferred to `wazuh-db`.

Regards.
