### ISSUE TITLE
Improve and fix agent multi-group

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1396]
- [x] Prevent new groups from inheriting the default group files.
We should simply create the agent.conf file from a template.
- [x] Let's introduce a comment into the merged _agent.conf_, indicating the source file for each chunk:
```xml
<!-- Source file: group-X/agent.conf -->
```
This will also be helpful for the App to show each setting origin.
- [x] This message is not very clear:
```sh
# agent_groups -a -i 001 -g syscheck
Do you want to set the group 'syscheck' to the agent '001'? [y/N]:
```
This message should appear with option `-e` (replace). Instead, the default message should ask if we want to **add** an agent to a group.
- [x] Assigning three or more groups to an agent seems not to work.
The agent keeps the old configuration.
- [x] Authd does not accept a request from _agent-auth_ to add an agent to a multigroup. It should scan these two folders:
  - etc/shared/*
  - var/multigroup/*
- [x] This message appears when we add an agent to another group:
```
2018/09/24 18:27:02 ossec-remoted: ERROR: No such group 'buffer-syscollector-localfile' for agent '001'
```

- [ ] Use a hash table in Authd as group cache.
- [ ] Remoted: clear group hash table periodically.

**Comment by jesuslinares** [comment]
Is there group validation for preventing "-" in the group name (API and agent_groups)?

**Comment by TJOSERAFAEL** [comment]
Hi @vikman90 ,

this branch https://github.com/wazuh/wazuh/tree/dev-37-multigroup-improvement fixes the problems except the first point.

Regards.

**Comment by TJOSERAFAEL** [comment]
The following changes will be applied:
- [ ] Move the multi-group folder creation from the **API** to **Remoted** 
- [ ] Move the multi-group folder deletion from the **API** to **Remoted** 

If the **remoted** daemon is not running, no multi-group folders will be created or deleted. It's entirely up to the **remoted** daemon doing the **sync**.

**Comment by TJOSERAFAEL** [comment]
Hi team,

we need a different approach for handling **multigroups**. The operating system has a file/directory name limit of 256 characters. Multigroups could be bigger than this so the new approach should solve this problem.

### Proposed solution

- Create a hidden file named `.metadata` on `/var/ossec/var/multigroups/` containing:
  - group1-group2-group3
  - anothergroup1-anothergroup2
  - ...

#### Python (Framework)
When we delete/add a group instead of deleting the folder in `/var/multigroups/` we delete/add it from the `metadatafile`.

All the operations that affects `/var/multigroups` now will affect **.metadata** file.


#### C (Manager)
When generating the `merged.mg` file for every **multigroup** instead of reading the `/var/multigroups` we will read the `.metadata` file, generate a **hash** for every multigroup and generate the merged.mg file with the hash name.

**Authd** will create/remove the **multigroup** reading the `.metadata` file.

This will remove the limitations we have now.

Regards

**Comment by TJOSERAFAEL** [comment]
Hi team,

let's implement the code with the following restrictions:
- Groups names are allowed within the regular expression ` [A-Za-z0-9,\.;:-_=\+!@\(\)][A-Za-z0-9,;:-_=\+!@\(\)]{0,254}`
- The maximum limit is **65535 bytes** for a **multigroup** meaning:
  - 256 groups * 255 b/group * 255 bytes (separators) = 65535 bytes

So the maximum groups in a **multigroup** composed of 255 bytes long names is 256 groups.

Regards.

**Comment by TJOSERAFAEL** [comment]
This branch implements the features from above: https://github.com/wazuh/wazuh/tree/dev-37-multigroup-improvement-hashing

**Comment by TJOSERAFAEL** [comment]
The issues for implementing the hash tables (remoted and authd) are:
https://github.com/wazuh/wazuh/issues/1544
https://github.com/wazuh/wazuh/issues/1545

Regards.
