### ISSUE TITLE
Enable O365 event collection from MS GCC/GCCH

### ISSUE THREAD

**Issue by communitycyber** [wazuh/wazuh#14029]
Need to be able to consume O365 event activity from MS/Azure Government Community Cloud (GCC) and Government Community Cloud High (GCCH).
https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc

The endpoints for GCC/GCCH are different from the commercial and public cloud endpoints

**Comment by vikman90** [comment]
Hello @communitycyber, thank you for opening this request.

I guess this issue comes from a related question on Slack. I wonder if changing the endpoints is enough, or if there are further changes in the content.

Let us add this issue to the roadmap, investigate the Azure API for GCC/GCCH and extend the support of the Office365 integration for these instances.

Best regards,
