### ISSUE TITLE
Wazuh manager not in agent list

### ISSUE THREAD

**Issue by ctagithub** [wazuh/wazuh#14135]
4.3.4 | Wazuh Dashboard | Manager and agent | installed via DNF https://packages.wazuh.com/ | RHEL 8.6
Fresh build and install.

The manager server is not in the list of agents from the dashboard.  There are no errors.  It appears that the server thinks it is registered and is working.  The problem is the manager itself is not in the agent list and we need to manage this server too.

There are no errors and the system is working outside of the manager missing from the Dashboard.

Results of 
/var/ossec/bin/agent_control -l
Wazuh agent_control. List of available agents:
   ID: 000, Name: XXXXXXX (server), IP: 127.0.0.1, Active/Local
Appears the manager agent registered and checked in and is active.  From the Gui in the dashboard under Agents, the manager server itself is not in the list.

Please let me know what else is needed to troubleshoot.

**Comment by pereyra-m** [comment]
Hello @ctagithub !

When installing the Wazuh manager you also have an agent in that host but with some differences from a regular one. Currently, this behavior can't be changed.
This means that you may receive alerts in the manager **as** if it were a normal agent, but it isn't listed in the `Agents` tab intentionally. 

The manager doesn't need to register or generate a key. Also, the state you see in `/var/ossec/bin/agent_control` is in fact hardcoded.
I apologize for the confusion.

What you can do is filter the events and alerts with the special ID = 000. This also works in the Dashboards, here you have two snapshots where I applied this filter 

![dashboard_Manager](https://user-images.githubusercontent.com/65046601/177418737-090a5a11-e031-414b-973f-4cdd31283381.png)

![manager_security_events](https://user-images.githubusercontent.com/65046601/177418745-559da1d2-2b8a-48d4-b0a6-14152c9a2dd7.png)


If you still have problems with the manager's events, please let us know.
Regards.

**Comment by pereyra-m** [comment]
Hello @jsiemek !

In a cluster scenario, we would have an agent 000 for every manager node and this would generate synchronization issues.
That's why this approach was taken.

The definitive solution is proposed here https://github.com/wazuh/wazuh/issues/8695. If the agent and the manager are two separate components we wouldn't have these types of troubles.

I don't have an estimated date for the issue I shared, but as I was saying before, all the events generated in the manager can be seen with no problems.

Regards.
