### ISSUE TITLE
Research on the relation between cumulative Windows updates

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#14134]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.5 | Vulnerability Detector | Manager | Packages/Sources | Windows Server 2019 |

## Description

After running a Vulnerability Detector scan on a relatively new _Windows Server 2019_ agent (as it only contains one system hotfix - `KB5014692`), we have observed that it reports many old vulnerabilities. All reported vulnerabilities are listed in the attached file _`vulns_result_4.3.json`_.

These vulnerabilities appear as it seems that the following list of hotfixes is not available in the agent:
- `KB4464330|KB4467708|KB4471332|KB4480116|KB4487044|KB4489899|KB4503327|KB4493509|KB4511553|KB4494441|KB4507469|KB4512578`

All of these reported hotfixes are cumulative updates, however none of them can be found in the Catalog. Examples:
- [KB4464330](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4464330): We did not find any results for _"KB4464330"_.
- [KB4467708](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4467708): Same.

This means that the only way to check if they have supersedences is to look in the most recent hotfixes to see if they appear in the superseded list.

In this case, as the only hotfix on the system is [KB5014692](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5014692), then we look for that hotfix in the Catalog, and get the following list of patches it replaces:
- `KB5007206|KB5008218|KB5009557|KB5010351|KB4520062|KB4534321|KB4537818|KB5006672|KB4501835|KB4501371|KB5005102|KB5005625|KB5006744|KB5012636|KB5015018|KB5014022|KB5005568|KB5011503|KB4598296|KB4601383|KB5000822|KB5001568|KB5001638|KB5000854|KB5001342|KB5001384|KB5003171|KB5003217|KB5003703|KB5004947|KB5004244|KB5004308|KB4541331|KB4550969|KB4559003|KB4571748|KB4577069|KB4577668|KB4580390|KB4586793|KB4586839|KB4495667|KB4505056|KB4497934|KB5005394|KB4464455|KB4469342|KB4476976|KB4482887|KB4490481|KB5005030|KB4509479|KB5008602|KB5007266|KB5010196|KB5010791|KB5010427|KB5011551|KB5003646|KB5012647|KB5013941|KB4554354|KB4567513|KB4505658|KB4512534|KB5009616|KB4594442`

> It can also be seen in the MSU, where none of the hotfixes contains KB5014692 as supersedence (I attach the file _`hotfixes_fix_vulns_msu.json`_, with the current supersedences contained in the list of reported hotfixes).

As none of the hotfixes in the list appear, we don't have enough information from the Catalog to know if any of these hotfixes are replaced by **`KB5014692`**, and that is why this list of old vulnerabilities is reported.

As `KB5014692` is also a cumulative update hotfix. It would be necessary to research if this is a real lack of information provided by Microsoft (Catalog), or if the information is really correct, and we can confirm that the agent is vulnerable to this list of vulnerabilities.

> In addition, I attach the log file obtained from the scan and the MSU that is currently in production.

[WS2019_scan_results_4.3.zip](https://github.com/wazuh/wazuh/files/9047346/WS2019_scan_results_4.3.zip)

**Comment by rmcclint** [comment]
Forgive my interjection, but - 
c.f. https://www.catalog.update.microsoft.com/Search.aspx?q=KB4469342  click on one of the update links to open a popup and look at the Package Details tab where it lists "This update has been replaced by the following updates" links.

**Comment by pereyra-m** [comment]
## Update

This issue seems to be related to a [Slack](https://wazuh.slack.com/archives/C0A933R8E/p1658751609809059) community question.

The user receives the **CVE-2022-26901** alert for `Microsoft Office Home and Business 2016 - en-us` because `KB5002143` isn't found. But this patch can't be manually installed, so it might be superseded by another one.

I've discarded the following possibilities:
- Syscollector isn't collecting all the security patches: even when the updates history doesn't match exactly with the agent's inventory, we can conclude that when a patch is installed and it founds there is another one superseded by the new patch, the registry only saves the information about the most recent
- The Wazuh MSU script fails in getting all the required information: even when we know that many KBs aren't available in the Microsoft Update Catalog, the dependency chain generated seems correct. 

So there must be another source of information we are missing.

Both Microsoft Update Catalog and WSUS don't show that `KB5002143` is superseded by any update.
But the following sequence shows the problem:

- Microsoft lists what KBs fix this CVE: https://msrc.microsoft.com/update-guide/vulnerability/CVE-2022-26901

- We see that for Microsoft Office 2016, the patch is `KB5002143`: https://support.microsoft.com/kb/5002143

- The Wazuh MSU also has this information 

![cve_26901_2143](https://user-images.githubusercontent.com/65046601/181417638-dc517c0d-0b36-4b52-891d-227007b0c859.png)

- In that article, Microsoft shows that the monthly cumulative update of April 2022 `KB5012926` is related


![more_information](https://user-images.githubusercontent.com/65046601/181419429-90e4c846-d801-4f4c-acc4-6607034b95d8.png)
 --

- There we have the patch only for Microsoft Office 2016 `KB5002143` and for Windows 10 21H2 `KB5012599`

![office_5002143](https://user-images.githubusercontent.com/65046601/181416148-bd1a70be-299f-4dd6-a6a3-42871e9c2a9d.png)

![windows_5012599](https://user-images.githubusercontent.com/65046601/181416314-9174b8fe-8710-4354-85a8-a010eefb474a.png)

- There is another source, the release notes for that monthly update https://msrc.microsoft.com/update-guide/releaseNote/2022-Apr, that confirms that the CVE-2022-26901 is related to the patch `KB5012599`

![release_notes](https://user-images.githubusercontent.com/65046601/181416651-7a2162ba-b885-456f-9b76-fe05d6ab152b.png)

- Finally, we know that the user has installed `KB5014699` and  `KB5013942` and that both supersed `KB5012599`

![msu_super](https://user-images.githubusercontent.com/65046601/181417275-31729f58-944e-4456-af16-8b2905c4642b.png)

- And `KB5012599` isn't related to CVE-2022-26901 in the Wazuh MSU

![5012599_not_related](https://user-images.githubusercontent.com/65046601/181417627-1bcf1e51-cf39-4430-a2f6-c41b78367fee.png)

We need to include these extra sources into the MSU to properly discard the false positives for Vulnerability Detector.

**Comment by pereyra-m** [comment]
## Update: another example

The same analysis was repeated with the alert the user receives about CVE-2022-22003 because `KB5002140` isn't found.

- Microsoft lists what KBs fix this CVE: https://msrc.microsoft.com/update-guide/vulnerability/CVE-2022-22003

- We see that for Microsoft Office 2016, the patch is KB5002143: https://support.microsoft.com/kb/5002140

- The Wazuh MSU also has this information

![msu_5002140](https://user-images.githubusercontent.com/65046601/181679259-d28bf98f-2ca1-44e0-a1cc-afb2c3d3b46a.png)

- In that article, Microsoft shows that the monthly cumulative update of February 2022 `KB5010644` is related

![feb_2022_KB5010644](https://user-images.githubusercontent.com/65046601/181679468-5d49e8cc-20a6-4457-9445-769c07b7a09e.png)

- There we have the patch only for Microsoft Office 2016 `KB5002140` and for Windows 10 21H2 `KB5010342`

![KB5002140](https://user-images.githubusercontent.com/65046601/181679611-c7e430bd-54a6-410b-8422-3410e922b8a8.png)

![KB5010342](https://user-images.githubusercontent.com/65046601/181679789-bb62b904-538e-4db2-9816-388c9fda4447.png)

- There is another source, the release notes for that monthly update https://msrc.microsoft.com/update-guide/releaseNote/2022-Feb, that confirms that the CVE-2022-22003 is related to the patch `KB5010342`

![feb_2022_release](https://user-images.githubusercontent.com/65046601/181680238-10c298dc-d50f-47d2-9112-9386cc1332b5.png)

- Finally, we know that the user has installed `KB5013942` that superseds `KB5010342`

![supersedence](https://user-images.githubusercontent.com/65046601/181680383-cb8caf92-8526-4b7c-b48a-e1cb9928cbf6.png)

- And `KB5010342` isn't related to CVE-2022-22003 in the Wazuh MSU

![CVE-2022-220003](https://user-images.githubusercontent.com/65046601/181680535-4dac51de-30bb-4357-90ae-d9b609987c78.png)

We can conclude again that we need more information in the Wazuh MSU feed.

**Note**: the user tried to install manually the patch `KB5002140` and succeeded. But it isn't strange for a system to have two patches at the same time when one supersedes the other. From the previos example, this same user has `KB5014699` that is supersedence of `KB5013942` and both are installed at the same time

![super_patch_installed](https://user-images.githubusercontent.com/65046601/181680895-d056f233-c35a-4da5-9555-00f74130646d.png)

## Update: another example

With the CVE-2022-33632 the situation is slightly different.
The user receives the alert related to Office 2016 because `KB5002112` isn't installed. 

We can see in https://msrc.microsoft.com/update-guide/en-US/vulnerability/CVE-2022-33632 that this patch solves the vulnerability, but in https://support.microsoft.com/kb/5002112 the message about the deployment is different

![deployment_information](https://user-images.githubusercontent.com/65046601/181681594-1f6f26be-d800-45b8-8e73-d4bc1cf7f49a.png)

We only have a generic link.
Using the release date of the patch, we can find the related note where the CVE is named, but we don't have the direct connection like the previous cases

https://msrc.microsoft.com/update-guide/releaseNote/2022-Jul

This seems to be like this because the current month is the same than the note and it hasn't ended yet.
The release note names the `KB5015807` for Windows 10, version 21H2 and the user has this patch installed

![5015807](https://user-images.githubusercontent.com/65046601/181682358-293c2cf6-6f5f-4928-ab9f-ae00d95745eb.png)

The `KB5002112` update couldn't be installed manually in that system, so we can think that this is a false positive again.

**Comment by MarcelKemp** [comment]
## Research findings

After an analysis of the relation between the patches obtained from the Catalog, the following information has been obtained:

- According to the problem mentioned in the description, it has been possible to obtain that the [Catalog](https://www.catalog.update.microsoft.com/home.aspx) is not providing all the information correctly of the relation between its new patches with the old patches (missing such information). This can be seen in the following relation between patches:
  We start from the premise: `KB5014692` which has no link to `KB4464330` according to the [Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5014692).
  Then by checking the cumulative patches that replace `KB4464330`, and the patches of which KB5014692 is supersedence, we can see that there is a list of hotfixes that correlate to both patches. 
  - Descriptive example:
`KB4464330` is replaced by `KB5011503`. And `KB5011503` is replaced by `KB5014692`. 
[[KB4464330](https://support.microsoft.com/en-us/topic/october-9-2018-kb4464330-os-build-17763-55-4c374837-5de0-2ccf-9226-43b293d360f5) -> [KB5011503](https://support.microsoft.com/en-au/topic/march-8-2022-kb5011503-os-build-17763-2686-ccb25c67-8994-41c9-bff2-4903f9a4721d) ([Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5011503)) -> [KB5014692](https://support.microsoft.com/en-gb/topic/june-14-2022-kb5014692-os-build-17763-3046-62fe56c1-a8c0-40e8-a901-677ab9538bf8)]
  So, as these are cumulative patches of type B ([Microsoft's explanation](https://docs.microsoft.com/en-us/windows/deployment/update/quality-updates)), we can conclude that **`KB4464330`** should be replaced by **`KB5014692`**.
  
  More examples:
  - [[KB4464330](https://support.microsoft.com/en-us/topic/october-9-2018-kb4464330-os-build-17763-55-4c374837-5de0-2ccf-9226-43b293d360f5) -> [KB5004947](https://support.microsoft.com/en-us/topic/july-6-2021-kb5004947-os-build-17763-2029-out-of-band-71994811-ff08-4abe-8986-8bd3a4201c5d) ([Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5004947)) -> [KB5014692](https://support.microsoft.com/en-gb/topic/june-14-2022-kb5014692-os-build-17763-3046-62fe56c1-a8c0-40e8-a901-677ab9538bf8)]
  - [[KB4489899](https://support.microsoft.com/en-us/topic/march-12-2019-kb4489899-os-build-17763-379-2a91a5c5-f351-f181-5501-510308a4030f) -> [KB5012647](https://support.microsoft.com/en-au/topic/april-12-2022-kb5012647-os-build-17763-2803-9a10c5c9-e65f-4ae1-a9c4-2db9a8eca4fc) ([Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5012647)) -> [KB5014692](https://support.microsoft.com/en-gb/topic/june-14-2022-kb5014692-os-build-17763-3046-62fe56c1-a8c0-40e8-a901-677ab9538bf8)]
  - [[KB4512578](https://support.microsoft.com/en-us/topic/september-10-2019-kb4512578-os-build-17763-737-695c1350-93dc-40dc-72c3-5af9743c6340) -> [KB5010351](https://support.microsoft.com/en-us/topic/february-8-2022-kb5010351-os-build-17763-2565-f895d43b-d855-4f6e-b0cc-52c079ae9056) ([Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5010351)) -> [KB5014692](https://support.microsoft.com/en-gb/topic/june-14-2022-kb5014692-os-build-17763-3046-62fe56c1-a8c0-40e8-a901-677ab9538bf8)]

  **Thus, we can conclude that this is a lack of information from the Catalog, but we can fix it thanks to the information and the connection we have between the different cumulative patches.**

> Different solutions to fix the problem are currently being considered. Once they are ready, they will be discussed in the issue. 

- As in the case of the Office package discussed in the issue, it is not possible to confirm that there is actually missing data among the list of hotfixes for Office packages. To check this, the following has been checked:

  First, it has been checked whether the sequence shown in the comment is correct, where it concludes with [KB5002143](https://support.microsoft.com/en-gb/topic/description-of-the-security-update-for-office-2016-april-12-2022-kb5002143-fc2032e9-b064-457e-90ee-c1770737c7cd) being replaced by the system patch (in this case Windows 10), [KB5012599](https://support.microsoft.com/en-au/topic/april-12-2022-kb5012599-os-builds-19042-1645-19043-1645-and-19044-1645-548cc67c-7f12-46fd-878e-589ba81ac2f5) or any supersedence of `KB5012599`. 
  However, such a link does not seem to be entirely true, as the only possible official link would be that `KB5002143` is replaced by [KB5012926](https://support.microsoft.com/en-gb/topic/security-update-deployment-information-april-12-2022-kb5012926-a9545214-b8aa-450d-87d1-26a2199c7e75) (but as this is only a _deployment information KB_, it means that no such hotfix exists).
  At this point, even if the Office patch and the Windows 10 system patch were updated in the same month and the release note shows the list of fixed vulnerabilities next to the list of deployed patches, this does not mean that they are related.
  For more information, please refer to the following links:
  - https://msrc.microsoft.com/update-guide/deployments
  - https://support.microsoft.com/en-gb/office/install-office-updates-2ab296f3-7f03-43a2-8e50-46de917611c5
  - https://docs.microsoft.com/en-gb/officeupdates/office-updates-msi

  In addition, in order to verify that there is really no relation between OS patches and package patches, the following manual tests have been performed:

  An old Windows 11 VM (not recently upgraded) with an Office 2016 package was installed.
  - A snapshot was taken, and it was tested to install several patches for Office 2016, of which, [KB5002112](https://support.microsoft.com/en-gb/topic/description-of-the-security-update-for-office-2016-july-12-2022-kb5002112-214149c3-42cc-4012-b408-1c8e7c0b2f3e) and [KB5002140](https://support.microsoft.com/en-us/topic/description-of-the-security-update-for-office-2016-february-8-2022-kb5002140-78c20f6b-b2de-4b5b-8305-5926266ad070) were successfully installed, although in the case of [KB5002143](https://support.microsoft.com/en-gb/topic/description-of-the-security-update-for-office-2016-april-12-2022-kb5002143-fc2032e9-b064-457e-90ee-c1770737c7cd), it showed an error where it did not allow installing the patch because it was not applicable for the version of the package.
  - Then, the VM was reverted to the snapshot without any updates, and first the OS was updated with the latest patches, leaving the machine updated with all the system patches. After that, an attempt was made to install the Office 2016 patches and the results were exactly the same, `KB5002112` and `KB5002140` were successfully installed while `KB5002143` showed the same error.

  One theory is that it depends on the version of Office 2016, it may already have the fix internally and therefore does not allow installing some patches, however as we do not know the patches that have been applied internally, then we cannot rule out vulnerabilities related to those patches, so it shows those vulnerabilities.

  **To conclude, further investigation is needed to find out what is really happening to prevent the patches that fix the reported vulnerabilities from being installed, and if necessary fixed.**

**Comment by MarcelKemp** [comment]
## Possible solutions `[A -> B -> C]`

Two different solutions are proposed to check and correct that two hotfixes are related via an intermediate hotfix.

- The first solution would be implemented in the MSU generator, and would consist in obtaining the supersedence of a patch (`A`), applying a difference with the supersedence found (`B`), so that when applying the difference from the list of supersedence of the expanded patch, if any new supersedence appears (`C`) it would mean that it is a supersedence of `B` and therefore should be supersedence of `A`, thus adding it to the list of supersedence of `A`.
  
  ```
  patchCnotA = supersedenceB.difference(supersedenceA)
  supersedenceA.add(patchCnotA)
  ```

- The second solution would be implemented directly in the _Vulnerability Detector_ code, specifically by parsing the MSU feed. In this case, having the patches inserted in the DB, we can make use of queries that provide us with the necessary information to correlate these patches. For this, a Select query would be applied, in which consulting one by one the supersedences of each patch, if we obtain a `SQLITE_ROW` then we will add the patch to that supersedence list.

  ```
  select b.SUPER as patchC from MSU_SUPERSEDENCE b LEFT JOIN MSU_SUPERSEDENCE a ON (a.super=b.super and a.patch='patchA') where a.super is null and b.patch='patchB';
  ```

The problem with these solutions is the number of patches to check, so we have to find the best way to try to avoid some nodes and perform as few operations as possible covering all cases.

**Comment by chemamartinez** [comment]
Finished research and development. GJ @MarcelKemp!
