### ISSUE TITLE
error 6715, path too long

### ISSUE THREAD

**Issue by eglyn** [wazuh/wazuh#14197]
Hi, 

I want to activate files monitoring on a few servers, but I have an issue with path: 

In the ossec log I have this error: 

`2022/07/11 08:52:19 wazuh-agent: ERROR: (6715): The path of the file monitored 'c:\path\....\file.pdf'' is too long to compute differences.`

How monitor files with long path ? Why this limit ? 

Wazuh version: 4.2.5

thx !

**Comment by antoniomanuelfr** [comment]
Hello @eglyn.

When FIM monitors files using `report_changes`, it copies those files to a shared location in order to be able to calculate the difference between two snapshots of the file. On Windows, the path length is fixed 256. 
When FIM tries to copy the file to the private location (`C:\Program Files (x86)\ossec-agent\queue\diff\file`) it recreates the entire file tree (if you are monitoring the file `c:\test\file.txt` using report changes, you will find a zipped copy in `C:\Program Files (x86)\ossec-agent\queue\diff\file\c\test\`) and if the destination path is longer than 256, this error is raised.

Fortunately, this issue was reported and fixed by the team in this PR and it will be ready in the next versions

**Comment by eglyn** [comment]
ok thx for your answer :)

**Comment by antoniomanuelfr** [comment]
Let me close this issue. 
You can check the progress of the fix in the PR that I shared previously.

Kind regards.
