### ISSUE TITLE
Share MSU-generator script

### ISSUE THREAD

**Issue by amankumarchagti** [wazuh/wazuh#14413]
Wazuh Version - 4.3.6
Issue:
Like, wazuh have a script to generate NVD database;
https://github.com/wazuh/wazuh/blob/master/tools/vulnerability-detector/nvd-generator.sh
Can anyone please share the MSU-generator script as well? to generate a database for Microsoft Updates

**Comment by FrancoRivero** [comment]
HI @amankumarchagti, 
Thanks for using Wazuh!
You need a script that downloads from [this link](https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.json.gz) the MSU updates so you can download these files with `wget` or `curl`.
The sources from which all the information used to generate the MSU is obtained:
First of all, we get the vulnerability information from [Microsoft Security Response Center,](https://msrc.microsoft.com) where they have a section with all vulnerabilities affecting Microsoft OSes and programs.

Here you can see the vulnerability information visually: https://msrc.microsoft.com/update-guide/vulnerability
We make use of the API offered by Microsoft, from which all the information I have mentioned can be obtained:
https://github.com/microsoft/MSRC-Microsoft-Security-Updates-API

Then, to complement the information on the patches that fix the vulnerabilities, we make use of the [Microsoft Update Catalog](https://www.catalog.update.microsoft.com/home.aspx), from which we obtain by web scraping, the list of patches for which we have information to know the patches that 'replaces' and 'replaced by', in this way, detecting a recent cumulative patch that contains an old patch, we avoid alerting about the old vulnerability since the recent patch is replaced of the old patch.
Regards

**Comment by amankumarchagti** [comment]
hey @FrancoRivero, thanks for sharing the Database(MSU-updates.json.gz). i want to go deeper and know how wazuh is finding vulnerable KBIDs for one windows system (some command references). and how are you finding CVEs for that vulnerable KBID?
