### ISSUE TITLE
Investigate and test AWS load balancer for agent's TCP balancing

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#14426]
As part of the development and implementation of a [mechanism to balance agents' TCP sessions in a clustered environment #13195](https://github.com/wazuh/wazuh/issues/13195) we need to test the behavior of the principal load balancers in the market, as well as the required configurations to ensure a proper behavior with the new functionality.

We need to test and validate the usage of AWS LBs as the load balancer to balance agent's TCP sessions in the current development. 

We know a primary pre-requisite for the current development is the availability of a least-connections algorithm for the external load balancer. We also need to test the different configurations and document them accordingly.

**Comment by vicferpoy** [comment]
# Issue update

## Summary

AWS Network Load Balancers can only use one algorithm and it is not compatible with this development. 🔴 

## Configuration

### Environment

- Wazuh cluster with 3 nodes (1 master and 2 workers)
- 6 Wazuh agents
- AWS Network Load Balancer

### NLB configuration

Since [Classic Load Balancers will be retired on August 15, 2022](https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/migrate-classic-load-balancer.html), our only option was to use Network Load Balancers, which quoting from the [official documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html):

> For TCP traffic, the load balancer selects a target using a flow hash algorithm based on the protocol, source IP address, source port, destination IP address, destination port, and TCP sequence number. The TCP connections from a client have different source ports and sequence numbers, and can be routed to different targets. Each individual TCP connection is routed to a single target for the life of the connection.

## Manual test

![image](https://user-images.githubusercontent.com/37274979/181244781-832d2ca5-e053-47a7-b18b-141e4e48854f.png)

1. As the Wazuh workers' services were stopped, all agents connected to the master node.
2. Wazuh workers' services started and then, a request to the `PUT /agents/reconnect` API endpoint was made to reconnect the last 4 agents.
3. After a while, only one of the agents reconnected to another cluster node.
