### ISSUE TITLE
Research wazuh-maild behavior when the alert.json file does not exist

### ISSUE THREAD

**Issue by Phandora** [wazuh/wazuh#14431]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.4-40316 | wazuh-maild| Manager | Packages | CentOS Linux release 7.9.2009 |

Hi team!

We have found the following `wazuh-maild` error logs:

```
2022/07/26 00:00:15 wazuh-maild: ERROR: (1118): Could not retrieve information of file 'logs/alerts/alerts.json' due to [(2)-(No such file or directory)].
2022/07/26 00:12:15 wazuh-maild: ERROR: (1118): Could not retrieve information of file 'logs/alerts/alerts.json' due to [(2)-(No such file or directory)].
2022/07/26 00:22:53 wazuh-maild: ERROR: (1118): Could not retrieve information of file 'logs/alerts/alerts.json' due to [(2)-(No such file or directory)].
2022/07/26 00:33:14 wazuh-maild: ERROR: (1118): Could not retrieve information of file 'logs/alerts/alerts.json' due to [(2)-(No such file or directory)].
2022/07/26 00:45:15 wazuh-maild: ERROR: (1118): Could not retrieve information of file 'logs/alerts/alerts.json' due to [(2)-(No such file or directory)].
2022/07/26 01:09:14 wazuh-maild: ERROR: (1118): Could not retrieve information of file 'logs/alerts/alerts.json' due to [(2)-(No such file or directory)].
...
2022/07/26 07:07:45 wazuh-maild: ERROR: (1118): Could not retrieve information of file 'logs/alerts/alerts.json' due to [(2)-(No such file or directory)].
2022/07/26 07:18:15 wazuh-maild: ERROR: (1118): Could not retrieve information of file 'logs/alerts/alerts.json' due to [(2)-(No such file or directory)].
2022/07/26 07:42:14 wazuh-maild: ERROR: (1118): Could not retrieve information of file 'logs/alerts/alerts.json' due to [(2)-(No such file or directory)].
2022/07/26 08:06:14 wazuh-maild: ERROR: (1118): Could not retrieve information of file 'logs/alerts/alerts.json' due to [(2)-(No such file or directory)].
...
```

However, the `/var/ossec/logs/alerts/alerts.json` file is in place:

```
# ll /var/ossec/logs/alerts/
total 12
drwxr-x---. 4 wazuh wazuh 4096 Jul  1 09:19 2022
-rw-r-----. 2 wazuh wazuh 6517 Jul 26 09:22 alerts.json
-rw-r-----. 2 wazuh wazuh    0 Jul 26 00:00 alerts.log
```

> The rotate interval is set to 10 minutes

We think this may be caused by file rotation. When `wazuh-analysisd` rotates a log, it updates the file `alerts.json` (which is actually a hard link to `alerts/2022/Jul/ossec-alerts-*.json`) and therefore there is a minimum period of time in which the `alerts.json` file does not exist.

Also, it seems that removing the file causes an infinite log (100% CPU usage is continuous).

Since `wazuh-maild` tries to read alerts in an infinite loop without waiting, it is necessary to research the actual impact of this issue considering:
- The `wazuh-maild` consumption
- The potential alert loss

Best regards.

**Comment by vikman90** [comment]
## Rationale

wazuh-maild uses two internal libraries to parse alerts:
- `file-queue` to read _alerts.log_.
- `json-queue` to read _alerts.json_.

The former performs a one-second delay when _alerts-log_ has no new alerts since the last call, while the latter does nothing. This makes wazuh-maild run into a busy-looping when monitoring _alerts.json_. This behaviour explains the high CPU usage:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 1339 wazuh     20   0   22512   4916   3880 R 100.0   0.0   3:25.47 wazuh-maild
```

wazuh-analysisd needs to update the hard link _alerts.json_ when rotating the alerts file. This operation is very fast, but wazuh-maild may find that _alerts.json_ is missing for an instant.

## PoC

Let's move and restore _alerts.json_ on Bash. This is very fast, but quite a bit slower than wazuh-analysisd (native implementation):

```sh
cd /var/ossec/logs/alerts
mv alerts.json{,.2}; mv alerts.json{.2,}
```

That makes wazuh-maild produce 60 logs:

```
2022/07/26 09:34:35 wazuh-maild: ERROR: (1118): Could not retrieve information of file 'logs/alerts/alerts.json' due to [(2)-(No such file or directory)].
2022/07/26 09:34:35 wazuh-maild: ERROR: (1103): Could not open file 'logs/alerts/alerts.json' due to [(2)-(No such file or directory)].
  (... 57 times more ...)
2022/07/26 09:34:35 wazuh-maild: ERROR: (1103): Could not open file 'logs/alerts/alerts.json' due to [(2)-(No such file or directory)].
```

## Proposed fix

1. Let wazuh-maild perform a one-second call when _alerts.json_ has no new alerts.
2. Let the file reader perform an extra call to `stat` if _alerts.json_ is missing.
3. Replace the error log 1118 with a warning.
