### ISSUE TITLE
agent_auth.exe is missing configuration options compared with Linux version

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#1452]
## Bug report

**OS**
_Windows_

**Wazuh version**
_3.x_

**Install type**
_agent_

**Install method**
_packages_

Bug description
----------------

agent_auth.exe is missing configuration options compared with Linux version.

These are the options available on a Linux system:

```shellsession
# /var/ossec/bin/agent-auth -h

Wazuh v3.4.0 - Wazuh Inc. (info@wazuh.com)
http://www.wazuh.com
  agent-auth: -[Vhdt] [-g group] [-D dir] [-m IP address] [-p port] [-A name] [-c ciphers] [-v path] [-x path] [-k path] [-P pass]
    -V          Version and license message
    -h          This help message
    -d          Execute in debug mode. This parameter
                can be specified multiple times
                to increase the debug level.
    -t          Test configuration
    -g <group>  Group to run as (default: ossec)
    -D <dir>    Directory to chroot into (default: /var/ossec)
    -m <addr>   Manager IP address
    -p <port>   Manager port (default: 1515)
    -A <name>   Agent name (default: hostname)
    -c          SSL cipher list (default: HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH)
    -v <path>   Full path to CA certificate used to verify the server
    -x <path>   Full path to agent certificate
    -k <path>   Full path to agent key
    -P <pass>   Authorization password
    -a          Auto select SSL/TLS method. Default: TLS v1.2 only.
```
And these are the ones available on a Windows system:

```powershell
PS C:\Program Files (x86)\ossec-agent> .\agent-auth.exe -h

Wazuh agent-auth: Connects to the manager to extract the agent key.
Available options:
        -h                  This help message.
        -m <manager ip>     Manager IP Address.
        -p <port>           Manager port (default 1515).
        -A <agent name>     Agent name (default is the hostname).
        -P <pass>           Authorization password.
```

**Comment by vikman90** [comment]
Hi @havidarou,

This issue is related to #1451 given that there are two different versions of Agent Auth clients:
- UNIX version, using OpenSSL library and supporting certificate validation.
- Windows version, using the native Windows Secure Channel (Schannel), no certificate validation support.

The proposed solution is making the UNIX version of Agent Auth (`agent-auth`) work on Windows. This would let the Windows agent support the same features that the UNIX version.

Working on branch [dev-agent-auth-win](https://github.com/wazuh/wazuh/tree/dev-agent-auth-win). So far, we have implemented a PoC that seems to request agent keys and present client certificates for validation.

Will keep working on this.
Best regards.

**Comment by cristgl** [comment]
I have been checking if this adapted Linux version is working for old and new Windows machines, this is registering the agents correctly for Windows XP, Windows 8.1 and Windows 10. Reminds pending testing it on a Windows Server 2019.

**Comment by cristgl** [comment]
Also tested on Windows Server 2003 (32 bit) and Windows Server 2008 (32 bit).

**Comment by cristgl** [comment]
Tested the certificate's verification on attended and unattended installations, options `CERTIFICATE`, `PEM` and `KEY`. This options have been tested with absolute and relative paths to the `.cert`, `.pem` and `.key` files.
Working also upgrading to a new version with an unattended installation.
