### ISSUE TITLE
CDB list: error when uploading files with `/` and `\`

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh#14531]
|Wazuh version|Component|
|---|---|
| X.Y.Z-rev | Wazuh component |

## Description

When you try to upload a file to CDB lists that contains `/` or `\` you are getting an error.

`"https://wazuh":"wazuh"` or `"wazuh":"https://wazuh"`

**Current behavior:**

Does not allow this file to be uploaded

![image](https://user-images.githubusercontent.com/63758389/183858375-0ec25a65-29b7-4eb9-a83f-19d68297f78b.png)
 or
![image](https://user-images.githubusercontent.com/63758389/183858580-9cfbca1c-32a3-44da-9ed3-00c9776aee27.png)

**Comment by davidjiglesias** [comment]
We have decided not to implement this change. The API should not validate uploaded files' content due to security issues. In this case, we have already had problems with the content of CDB lists, so allowing extra parameters like `/` and `\` could be potentially dangerous.

We delegate the validation of ruleset files to developing the new Engine.
