### ISSUE TITLE
Numerous False Positives in Vulnerability Detector

### ISSUE THREAD

**Issue by mthbrown** [wazuh/wazuh#14560]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.6-40318 | Wazuh Manager | [Single Node Installation](https://documentation.wazuh.com/current/quickstart.html) | [Single Node Installation](https://documentation.wazuh.com/current/quickstart.html) | Ubuntu 22.04 |

Hi,

While testing Wazuh's vulnerability detector, I was surprised to find that an agent running on a fully updated Ubuntu 22.04 showed almost 30 critical findings and over 300 high findings as shown below. Some of the vulnerabilities are for software from 2013 and 2016

![wazuh_vulnerability_detector_3](https://user-images.githubusercontent.com/22183215/184800533-00d37a47-f06f-453b-8e93-509ea0192e45.png)

I searched and ran into someone who had similar issues but for a Windows box [here](https://github.com/wazuh/wazuh/issues/11155). So I followed the steps mentioned there and I stopped the Wazuh Manager and then deleting the CVE DB:

```
rm /var/ossec/queue/vulnerabilities/cve.db
```

and then restarted it so that the DB is re-downloaded. After waiting for about 30 minutes for it to download it and for the agent to re-run the scan, I still ended up with the same result. I thought that perhaps there was a problem with the agent-related SQLite table so I ran:

```
systemctl stop wazuh-manager.service
```

and then:

```
sqlite3 001.db;
001.db> delete from vuln_cves;
Query OK, 522 rows affected
Time: 0.024s
001.db> delete from vuln_metadata;
Query OK, 1 row affected
Time: 0.009s
001.db> vacuum;
Query OK, 0 rows affected
Time: 0.075s
```

to delete the previous records and then re-started the Wazuh Manager:

```
systemctl start wazuh-manager.service
```

and after a few minutes, I ended up with the exact same result (29 critical findings, etc.). This is the related configuration on my Wazuh Manager:

```xml
  <vulnerability-detector>
    <enabled>yes</enabled>
    <interval>5m</interval>
    <min_full_scan_interval>6h</min_full_scan_interval>
    <run_on_start>yes</run_on_start>

    <!-- Ubuntu OS vulnerabilities -->
    <provider name="canonical">
      <enabled>yes</enabled>
      <os>trusty</os>
      <os>xenial</os>
      <os>bionic</os>
      <os>focal</os>
      <os>jammy</os>
      <update_interval>1h</update_interval>
    </provider>

....

    <!-- Aggregate vulnerabilities -->
    <provider name="nvd">
      <enabled>yes</enabled>
      <update_from_year>2010</update_from_year>
      <update_interval>1h</update_interval>
    </provider>

  </vulnerability-detector>
```

The sub-sections for the other distros are disabled. Any suggestions? Thanks

**Comment by chemamartinez** [comment]
Hi @mthbrown,

First of all, your configuration is correct and the Vulnerability Detector module is working as expected.

Regarding the report for your Ubuntu 22.04 agent, I understand seems weird that an updated OS reports that amount of vulnerabilities. However, there exists an explanation for that.

The Vulnerability Detector module evaluated the installed packages against several vulnerability sources to provide the most reliable results possible. In the case of Ubuntu agents, these sources are the Canonical OVAL feeds and the NVD database.

These vulnerabilities are shown because of the Canonical source, let's analyze some of the vulnerabilities that are being reported according to the screenshot you provided.

**CVE-2013-4235 (medium severity)**
https://ubuntu.com/security/CVE-2013-4235

Regarding the link above, Canonical marks the `shadow` package (same for related ones like `login` and `password`) as `Needed`. This means it is a known issue that still needs a fix.

This is the reason why the vulnerability is reported.

**CVE-2016-1585 (critical severity)**
https://ubuntu.com/security/CVE-2016-1585

In this case, for Ubuntu Jammy the package `Apparmor` is marked as `Deferred`. This means it is a known vulnerability that is not going to be addressed. It has been postponed but that doesn't mean the vulnerability is fixed or doesn't exist.

**CVE-2018-6952 (high severity)**
https://ubuntu.com/security/CVE-2018-6952

The same case as the previous one, the fix is deferred for the `patch` package.

Please notice that the severity doesn't match between the Canonical website and the Wazuh report. This is why we are defining the severity according to the CVSS score which is a more generic measurement.

Please have this into account when reviewing vulnerability reports from Wazuh, the module reports all the vulnerabilities according to the official sources. In addition, a fresh and updated OS doesn't mean it doesn't contain known vulnerabilities that have not been fixed by the vendors for any reason. In that sense, the module will report them trying to avoid false positives.

Don't hesitate to ask if you have further concerns.

Best regards,
Chema.

**Comment by mthbrown** [comment]
Thank you @chemamartinez for the explanation. However, there are some problems with this IMHO:

- this shows me a lot of non-actionable information and makes determining what I should be worried about and what I shouldn't be worried about a lot more difficult. If I did have a single critical or medium issue that was patchable, I wouldn't be able to see it
- if I show this dashboard to an auditor, they probably won't accept the explanation and will simply ask me to fix it or mark me down

Is there any way to somehow toggle this behavior so that it only shows me:

- issues where a patch is available (this is actionable)
- CVEs released in a given period of time such as the last 3 months (as these may indicate issues that the distro is working on patching but still hasn't released them)

Thanks

**Comment by chemamartinez** [comment]
I agree with you @mthbrown. The vulnerability scanner should provide a more configurable interface that is able to filter the vulnerabilities according to the user's needs.

We will open a new issue to address that feature request and I will discuss with the team to include it as soon as possible.

Currently, there is no way to filter vulnerabilities in the `Inventory` tab (where all the found vulnerabilities are inventoried). The only way to do this is to review all of them manually, and solve those what the condition field is not `Unfixed` but a condition such as `Package less than X.Y.Z` which means a patched version is available.

We are sorry for the inconvenience.

**Comment by ossie-git** [comment]
Thanks @chemamartinez

**Comment by chemamartinez** [comment]
Hi @mthbrown, @ossie-git,

I have opened the issue https://github.com/wazuh/wazuh-kibana-app/issues/4403 and talked to the team about it. We can track the progress there.

Please, let me close this issue since there no exists any false positive in our vulnerability detector. Feel free to open it again if you find any false positives.

Thanks!
