### ISSUE TITLE
whodata Results in Broad auditd Rule

### ISSUE THREAD

**Issue by mthbrown** [wazuh/wazuh#14686]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.6| FIM | Agent | Packages | Ubuntu 22.04 |

Hi,

While experimenting with the FIM component, I wanted to monitor **all** modifications of sensitive files such as `~/.ssh/authorized_keys` so I added the following rule:

```xml
<directories realtime="yes" check_all="yes" whodata="yes"  recursion_level="2" restrict="^authorized_keys$">/home</directories>
```

When I then looked at the `auditd` rule that was generated, I was surprised to find that Wazuh had generated this excessively broad rule that could result in a ton of auditd traffic, overhead, and unnecessary logging:

```
-w /home -p wa -k wazuh_fim
```

Would it be possible for it to generate watches only for the files of interest? It could re-generate this list if needed when it stops / starts. Thanks

**Comment by vikman90** [comment]
Hi @mthbrown,

There are two reasons why the agent needs to set a broad rule:

1. Your configuration asks the agent to monitor any event on any file called "authorized_keys", but a user may create a file like this in any folder. If the agent created a rule set like:
```
-w /home/user1/.ssh/authorized_keys -p wa -k wazuh_fim
-w /home/user2/.ssh/authorized_keys -p wa -k wazuh_fim
```
Then it would be unable to detect when a file with that name gets created in any other folder. Should you want this, try out this option:
```xml
<directories whodata="yes" recursion_level="1" restrict="/authorized_keys$">/home/*/.ssh</directories>
```
This way, the agent will create this narrower audit rule:
```
-w /home/vikman/.ssh -p wa -k wazuh_fim
```

2. There are some cases in which Audit cannot provide the path to a watched file (see #1714). When this happens, the agent uses the file inode reported by Audit to find the path in the internal database. Because of this, we need to watch the container folder.

Hope this helps. Should you have any proposal to optimize the audit rules the agent sets up, please share it with us. However, the Linux Audit subsystem has proved to be really performant, and the agent runs a log pre-parsing to skip logs with:
- A key different from `wazuh_fim`.
- Unsuccessful events.
- Files that don't belong to the configuration.
Which provides good performance, even when the Audit is configured with many rules (like [Neo23x0/audit.rules](https://github.com/Neo23x0/auditd/blob/master/audit.rules)).

Best regards.
