### ISSUE TITLE
Vulnerability Detector Reporting false Positives

### ISSUE THREAD

**Issue by jareddewitt** [wazuh/wazuh#14724]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|7.17.4|Vulnerability Detector|Script|Script|CentOS|

There seems to be an issue with Vulnerability detector detecting hotfix supersedence on Windows 2016/2019.  For example, all my 2019 servers are reporting Critical vulnerabilities because KB4511553 is not installed.  But that KB doesn't exist anymore in the Microsoft Update Catalog.  It's been superseded in the following way: KB4511553 -> KB4512534 -> KB5004947. 

KB5004947 is installed on the server, but Wazuh doesn't seem to know about the supersedence.  

Let me know what I can do to help get this resolved.  Thanks.

**Comment by pereyra-m** [comment]
Hello @jareddewitt !

Thank you very much for reporting this issue.

First of all, I'd like to know what is the Wazuh version of both the agent and manager.
Then, it would be really useful if you could share the hotfixes list and the OS information from the **Inventory** tab in the UI for that agent. Also, please upload the complete list of detected CVEs from the **Vulnerabilities** tab.

This information will allow us to properly analyze the case.
I'd like to know if we are in presence of this issue or not https://github.com/wazuh/wazuh/issues/14523

Regards.

**Comment by jareddewitt** [comment]
Thanks @pereyra-m

The Manager is running 7.17.4, and the agent is 4.3.4. 

Here's the list of hotfixes in the inventory tab. 
`KB2468871
KB2478063
KB2533523
KB2544514
KB2600211
KB2600217
KB4502496
KB4523204
KB4535680
KB4535684
KB4535685
KB4539571
KB4549947
KB4558997
KB4562562
KB4566424
KB4570332
KB4577586
KB4577667
KB4587735
KB4589208
KB4598480
KB4601393
KB5000859
KB5001404
KB5003243
KB5003711
KB5005112
KB5005701
KB5006754
KB5008287
KB5009642
KB5011574
KB5012675
KB5014031
KB5014692
KB5013892
KB5014797
KB5015811
KB5012170
KB5015736
KB5015896
KB5016623`

And here's the CVEs being detected.  

`CVE-2019-1226
CVE-2019-1222
CVE-2019-1182
CVE-2019-1181
CVE-2019-0786
CVE-2019-0785
CVE-2019-0725
CVE-2019-0626
CVE-2018-8626
CVE-2018-8476
CVE-2019-0726
CVE-2019-0698
CVE-2019-0697`

It's very possible this is the same issue listed in #14523

**Comment by pereyra-m** [comment]
Thanks for the information @jareddewitt !

But I think you are reporting the Wazuh version for another component in the manager. You can run simply `/var/ossec/bin/wazuh-control info`. It should be similar to `v4.3.x`, not `v7.17.x`.
Also, please don't forget to share the OS information of the agent exactly as it appears in the agent's inventory.

What I can see is that, for example, the [CVE-2019-1226](https://msrc.microsoft.com/update-guide/vulnerability/CVE-2019-1226) is fixed by `KB4511553` according to the MSRC.

The [KB4511553](https://www.catalog.update.microsoft.com/Search.aspx?q=4511553) isn't found in the MSU, but the Wazuh vulnerabilities database has that patch. 
Vulnerability detector knows that it's superseded by `KB4512534` and `KB5004947` as we can see in the images

![super1](https://user-images.githubusercontent.com/65046601/186908265-96de7680-63ae-419f-a490-b72ef28cdfed.png)

![super2](https://user-images.githubusercontent.com/65046601/186908281-8442eb56-455c-4baf-8307-12a2cc97cc25.png)

The problem is that in the inventory of KBs you've reported, you haven't installed `KB4512534` nor `KB5004947` but other patches that superseded them.

In the MSU results for [KB4512534](https://www.catalog.update.microsoft.com/Search.aspx?q=4512534), I can find the following patches that superseded it and you do have.
- `KB5014692`
- `KB5015811`
- `KB5016623`

But any of these are listed as a `SUPER` for `KB4511553` in the `MSU_SUPERSEDENCE` table.

Doing the same for [KB5004947](https://www.catalog.update.microsoft.com/Search.aspx?q=5004947), these are the patches that you have and superseded it (the same as before)
- `KB5014692`
- `KB5015811`
- `KB5016623`

So it's a lack of depth in the correlation of Microsoft patches.

 I apologize for the inconvenience and the team is working in solving this issue as soon as possible.
 
 Regards.

**Comment by chemamartinez** [comment]
Hi @pereyra-m @jareddewitt,

The fix that solves this issue was already merged https://github.com/wazuh/wazuh-tools/pull/193. In addition, a new MSU feed has been published including the missing Microsoft updates, so once the managers update the MSU feed and scan the Windows agents again, the false positives should be removed.

Thanks for your feedback!

**Comment by jareddewitt** [comment]
Can confirm.  After the MSU was published, the supersedence is working correctly and no false positives are detected.  Closing this issue.
