### ISSUE TITLE
How to manage array of objects in the decoder.

### ISSUE THREAD

**Issue by Waseem-farooqui** [wazuh/wazuh#14732]
Hi,

I am creating a decoder for the Sangfor EDR but don't know how to handle array of object.

`Jul 29 15:25:02 localhost EDR.[23007]: anti_bfa : [{"_id":"1d2acc5fbb75e174f850fa20ac5128cb107bb403","found_time":1659090256,"att_src":"x.x.x.x","agent_id":"2697870754","att_times":21,"state":"Fixed","time":1659079449,"event_type":"Brute-Force Attack","host_name":"VDR","iplist":"x.x.x.x"},{"_id":"88f3ffecaf2ce3a7f816a6df07fbb080096be8f5","found_time":1659088909,"att_src":"x.x.x.x","agent_id":"2697870754","att_times":357,"state":"Fixed","time":1659079449,"event_type":"Brute-Force Attack","host_name":"VDR","iplist":"x.x.x.x"}]`
Here you can observe after the **anti_bfa:** there is an array of object that repeats again at with the **_id** key.

What would be regex for it and what would be the order I don't even guess the size of the array.

    <decoder name="sangfor-edr-generic">
       <program_name>EDR</program_name>
    </decoder>
    <decoder name="sangfor-edr-antiBFA">
       <parent>sangfor-edr-generic</parent>
       <regex offset="after_parent">\s*(\w*)\s+:\s+\p+"_id":"(\w+)","found_time":(\d+),"att_src":"(\d+.\d+.\d+.\d+)","agent_id":"(\d+)","att_times":(\d+),"state":"(\w+)","time":(\d+),"event_type":"(\.+)","host_name":"(\w+)","iplist":"(\d+.\d+.\d+.\d+)"</regex>
       <order>type, id, foundTime, attackSource, agentId, attackTime, state, time, eventType, hostName, ipList</order>
    </decoder>

Any help would be really appreciable.

**Comment by FrancoRivero** [comment]
Hi @Waseem-farooqui,
Thank you for using Wazuh!
Wazuh has some problems handling arrays, because it is impossible to define the length in advance. So we must add a regex to take this information, with this decoder we can never detect this log because the pre-decoder doesn't have any way to detect the `program name`, I mean we need a father decoder which take the program name after that we can detect any log with a decoder similar to your decoder using regex for instance.
Well I would like that you share me the `archive.json` in order to make a decoder which work for you.
You can read more about the decoders ([here](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/decoders.html#decoder)).
I hope to hear from you soon.
Regards

**Comment by FrancoRivero** [comment]
Hi @Waseem-farooqui,
Have you been able to solve your problem?
After two weeks without replies we closed the old issues, if you need to reopen it, let me know.
Regards
