### ISSUE TITLE
CIS Benchmark Wazuh 4.3.7

### ISSUE THREAD

**Issue by DanielleG1982** [wazuh/wazuh#14748]
i am not sure if there is an issue with the new release or its just how the new windows 10 21h2 CIS benchmark is 

but after i updated yesterday to wazuh 4.3.7 the CIS score went way down from 89% to 51%  . a day ago most of the failed ones were not applicable. after the update all the not applicable are marked as failed.

![2](https://user-images.githubusercontent.com/112184840/186943871-ccd2bd95-f3e8-4f0d-b24c-069f0198370c.PNG)
![old](https://user-images.githubusercontent.com/112184840/186943873-03904b27-3df7-4000-830a-9287af8c4418.PNG)

**Comment by smokentar** [comment]
Hey, I'm not from Wazuh team however I could try to provide some insight while they come back to you.

This behaviour is the result of commit [26c96b2](https://github.com/wazuh/wazuh/commit/26c96b22b6617a3e7cd3c33896b1ea521684d410).
We can observe that additional keys were added to most rules for a more accurate evaluation.

Taking for example `id: 15541`

Before the update
---
```
condition: all
    rules:
      - 'r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa -> LmCompatibilityLevel -> 5'
```
As per [conditions](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/creating-custom-policies.html?highlight=applicable) documentation:
`all: the check will be evaluated as Passed if all of its rules are satisfied and as Failed as soon as one rule is not satisfied`

`all: If any rule returns Not applicable, and no rule returns Failed, the result will be Not applicable`

`If the target of a rule that checks for contents does not exist, the result will be Not applicable as it could not be checked.`

 When the rule got evaluated and the registry path wasn't found, the engine returned **Not Applicable** (because it's not evaluating the existence of the path, rather than content inside it)

After the update
---
```
condition: all
    rules:
      - 'r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa'
      - 'r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa -> LmCompatibilityLevel '
      - 'r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa -> LmCompatibilityLevel -> 5'
```
Now when the new rules get evaluated the engine first checks for the existence of the registry path.
- if it doesn't exist the rule returns **Failed**.

It then checks for the existence of a key inside that path.
- if it doesn't exist but the registry path exists, the rule returns **Failed**.
- if it doesn't exist and the registry path doesn't exist, the rule returns **Not applicable**.

Finally it does the original check of the value of the key in that path.
- if the value doesn't exist and the registry path doesn't exist, the rule returns **Not applicable**.

Since we now have that additional rule which first checks for the existence of the registry path and the **all** condition, the engine reports **Failed** instead of **Not applicable**.

I stumbled across this issue two days ago while I was testing some functionality and was going to raise this to Wazuh team however I can see they are already working on resolving this.

You are now receiving more accurate checks and the fact that your CIS compliance dropped significantly is a good thing - this means more actual checks were evaluated instead of being reported as **Not applicable**.

This boils down to the following logic (in my opinion):
**Missing path in registry is an indication of missing configuration and should be reported. It should not be marked as not applicable.**

I hope these changes get propagated to the other Windows CIS Benchmarks as well.

**Comment by fabamatic** [comment]
Thanks @smokentar , your analysis is spot on.
@DanielleG1982 , as smokentar said, the lower score on Windows 10 CIS benchmarks is caused  by increased accuracy in most checks. You should update endpoints and policies to correct the missing checks.
I will be closing this issue. Feel free to reopen it if needed.
