### ISSUE TITLE
GCP module does not support logs outside a projectID

### ISSUE THREAD

**Issue by noxit0** [wazuh/wazuh#14773]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.3.7 | GCP Services | Improve |

## Description
We are in the need to retrieve Google Workspace (formerly G suite) logs.
Our current GCP module does not support logs outside a projectID, making it difficult to obtain these logs.
[Documentation related.](https://documentation.wazuh.com/current/gcp/prerequisites/credentials.html)

### Service
Provide the ability to access logs without the need to insert a projectID, so then we can offer official rules to manage Google Workspace log information.

### Current results

- The input of a project ID is requested in the ossec.conf file.

```
<gcp-pubsub>
     <pull_on_start>yes</pull_on_start>
     <interval>1m</interval>
     <project_id>wazuh-dev-123456</project_id>   <---------PROJECT_ID
     <subscription_name>wazuh-subscription</subscription_name>

     <credentials_file>/var/ossec/wodles/gcloud/credentials.json</credentials_file>
 </gcp-pubsub>

 <gcp-bucket>
     <run_on_start>yes</run_on_start>
     <interval>1m</interval>
     <project_id>wazuh-dev-123456</project_id>
     <subscription_name>wazuh-subscription</subscription_name>

     <credentials_file>/var/ossec/wodles/gcloud/credentials.json</credentials_file>
 </gcp-bucket>
 ```
 

- No Google Workspace rules or decoders.

### Expected results
To be able to retrieve and analyze Google Workspace logs, raising alerts whenever it's needed.

### Issues related
[Create rules for Google Workspace/Google Suite](https://github.com/wazuh/wazuh/issues/10776)

**Comment by nico-stefani** [comment]
# Issue Update

Actually, the `project_id` field is required because to [pull](https://cloud.google.com/python/docs/reference/pubsub/2.7.1/google.cloud.pubsub_v1.subscriber.client.Client#google_cloud_pubsub_v1_subscriber_client_Client_pull) messages from a subscription, is needed to use internally the format `projects/{project}/subscriptions/{sub}`. And there isn't a way to do without this field.

Saying that, it is possible to support [Google Workspace Logs](https://cloud.google.com/logging/docs/audit/gsuite-audit-logging) routing the logs to a `Cloud Storage` instead of using `Pub/Sub`. This is possible by configuring a [sink](https://cloud.google.com/logging/docs/export/configure_export_v2) to send logs, in JSON format, to a bucket and then configure `gcp-bucket` to search these logs.

## Conclusion
If we choose this way of support, is needed to make a POC for configurations and add documentation explaining the use case.

**Comment by nico-stefani** [comment]
# Issue Update

In order to validate the integration, I was working on the creation of the sinks(pubsub and storage) to route the logs generated from **Google Workspace**.

![image](https://user-images.githubusercontent.com/7127104/195933312-379511c0-1512-46aa-9a49-6d1a0f60e7f1.png)

![image](https://user-images.githubusercontent.com/7127104/195933349-94dfb124-c9eb-47a5-9813-8a9ab137f7f3.png)

**Comment by Nexus2k** [comment]
Do you happen to have some custom rules you'd be willing to share? I'm currently also looking into integrating Workspace logs to Wazuh.

**Comment by nico-stefani** [comment]
> Do you happen to have some custom rules you'd be willing to share? I'm currently also looking into integrating Workspace logs to Wazuh.

The scope of this issue is to write some documentation explaining the use case and how to make the configurations. 
For the rules, we have #10776 already open.

**Comment by davidjiglesias** [comment]
We are currently able to process all logs using Storage or Pub/Sub, closing this.
