### ISSUE TITLE
Offline MSU not working

### ISSUE THREAD

**Issue by martinzeifang** [wazuh/wazuh#14883]
Version 4.3.7 

because of a Proxy Server we have to use offline files for the vulnerability scanner. for MSU the offline file can be downloaded but it doesn't find any vulnerabilities. searching the database, the metadata are missing for msu: 

```
[root@fxxxxx ossec]# sqlite3 /var/ossec/queue/vulnerabilities/cve.db "select * from metadata;"
CPEW|Wazuh CPE dictionary|1.0|1.0|2019-10-02T10:56Z||0|0|1663065863
TRUSTY|Canonical CVE OVAL Generator|1.1|5.11.1|2021-11-16T15:30:29||0|0|1663142542
XENIAL|Canonical CVE OVAL Generator|1.1|5.11.1|2021-11-16T15:30:34||0|0|1663142580
BIONIC|Canonical CVE OVAL Generator|1.1|5.11.1|2021-11-16T15:30:33||0|0|1663142619
FOCAL|Canonical CVE OVAL Generator|1.1|5.11.1|2021-11-16T15:30:28||0|0|1663142651
STRETCH|Debian||5.11.2|2022-09-14T03:36:17.188-04:00||0|0|1663142670
BUSTER|Debian||5.11.2|2022-09-14T03:36:52.188-04:00||0|0|1663142677
RHEL5|Red Hat OVAL Patch Definition Merger|3|5.10|2022-09-13T18:34:24||0|0|1663142702
RHEL6|Red Hat OVAL Patch Definition Merger|3|5.10|2022-09-13T14:25:20||0|0|1663142730
RHEL7|Red Hat OVAL Patch Definition Merger|3|5.10|2022-09-13T14:24:49||0|0|1663142771
RHEL8|Red Hat OVAL Patch Definition Merger|3|5.10|2022-09-13T18:21:41||0|0|1663142811
JREDHAT|Red Hat Security Data|1.0||2022-09-14 10:07:14||0|0|1663142835
```

if I use the online mode (on an other system (same Version) it works: 

```
[root@txxxxx test]# sqlite3 /var/ossec/queue/vulnerabilities/cve.db "select * from metadata;"
CPEW|Wazuh CPE dictionary|1.0|1.0|2019-10-02T10:56Z||0|0|1655818436
MSU|Microsoft Security Update|1|1|2022-09-02T16:33:06-00|4588989d60b0bb12ea015b1a923c5c4a6a9101699034e6fafadcdf27a4ce75be|98423482|0|1662989339
RHEL6|Red Hat OVAL Patch Definition Merger|3|5.10|2022-09-13T14:25:20||0|0|1663080079
```

I checked the hash of the file: 
4588989d60b0bb12ea015b1a923c5c4a6a9101699034e6fafadcdf27a4ce75be  msu-updates.json.gz

after enabling the debug log we get: 
```
2022/09/14 11:34:36 wazuh-modulesd:vulnerability-detector[20363] wm_vuln_detector.c:4285 at wm_vuldet_index_feed(): DEBUG: (5427): Refresh of 'Microsoft Security Update' database finished.
2022/09/14 11:34:36 wazuh-modulesd:vulnerability-detector[20363] wm_vuln_detector.c:4290 at wm_vuldet_index_feed(): DEBUG: remove(tmp/vuln-temp): No such file or directory
2022/09/14 11:34:36 wazuh-modulesd:vulnerability-detector[20363] wm_vuln_detector.c:4296 at wm_vuldet_index_feed(): DEBUG: remove(tmp/vuln-temp.bz2): No such file or directory
2022/09/14 11:34:36 wazuh-modulesd:vulnerability-detector[20363] wm_vuln_detector.c:4618 at wm_vuldet_check_feed(): INFO: (5430): The update of the 'Microsoft Security Update' feed finished successfully
```

**Comment by MarcelKemp** [comment]
Hi @martinzeifang,

The problem of missing MSU metadata when using a custom path is normal, because MSU has its metadata information in a different file ([msu-updates.meta](https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.meta)) than the one containing the feed ([msu-updates.json.gz](https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.json.gz)). 
So when using the [online mode](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/vuln-detector.html#example-of-configuration), it automatically downloads both files and stores them in the DB, while in [offline mode](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/offline-update.html#msu), since it only indicates the path containing the feed with the patches and vulnerabilities, and does not have the metadata, it stores the content of the feed in the DB (`MSU` and `MSU_SUPERSEDENCES` tables) but not the metadata.

However, even without metadata, the MSU is always updated using the offline update mode, so the DB should contain the MSU content and work correctly. In my case, the log lines in debug to know that the content has been parsed and stored correctly are the following:
```
wazuh-modulesd:vulnerability-detector[1571] wm_vuln_detector.c:4950 at wm_vuldet_check_feed(): INFO: (5400): Starting 'Microsoft Security Update' database update.
wazuh-modulesd:vulnerability-detector[1571] wm_vuln_detector.c:4843 at wm_vuldet_fetch_feed(): DEBUG: (5484): Cleaning metadata for target 'MSU'
wazuh-modulesd:vulnerability-detector[1571] wm_vuln_detector.c:4858 at wm_vuldet_fetch_feed(): DEBUG: (5403): Fetching feed from '/share/msu-updates.json.gz'
wazuh-modulesd:vulnerability-detector[1571] wm_vuln_detector.c:7717 at wm_vuldet_index_json(): DEBUG: (5408): Updating from '/share/msu-updates.json.gz'
wazuh-modulesd[1571] file_op.c:3408 at w_uncompress_bz2_gz_file(): DEBUG: The file '/share/msu-updates.json.gz' was successfully uncompressed into 'tmp/vuln-temp-fitted'
wazuh-modulesd:vulnerability-detector[1571] wm_vuln_detector.c:4616 at wm_vuldet_index_feed(): DEBUG: (5414): Refreshing 'Microsoft Security Update' databases.
wazuh-modulesd:vulnerability-detector[1571] wm_vuln_detector.c:3130 at wm_vuldet_insert(): DEBUG: (5415): Inserting vulnerabilities.
wazuh-modulesd:vulnerability-detector[1571] wm_vuln_detector.c:3157 at wm_vuldet_insert(): DEBUG: (5418): Inserting Microsoft Security Update dictionary.
wazuh-modulesd:vulnerability-detector[1571] wm_vuln_detector.c:4622 at wm_vuldet_index_feed(): DEBUG: (5427): Refresh of 'Microsoft Security Update' database finished.
wazuh-modulesd:vulnerability-detector[1571] wm_vuln_detector.c:4627 at wm_vuldet_index_feed(): DEBUG: remove(tmp/vuln-temp): No such file or directory
wazuh-modulesd:vulnerability-detector[1571] wm_vuln_detector.c:4633 at wm_vuldet_index_feed(): DEBUG: remove(tmp/vuln-temp.bz2): No such file or directory
wazuh-modulesd:vulnerability-detector[1571] wm_vuln_detector.c:4973 at wm_vuldet_check_feed(): INFO: (5430): The update of the 'Microsoft Security Update' feed finished successfully.
```

So looking at the same last lines where you see that the MSU has been updated correctly, there doesn't seem to be any problem with the MSU update.

To make sure, you can try to check if the `MSU` and `MSU_SUPERSEDENCES` tables contain information in the **`cve.db`**. And also with the `debug` enabled, you can connect a Windows agent and see how a full scan is performed, finding or discarding the corresponding vulnerabilities according to the agent hotfixes.
> Keep in mind that vulnerabilities may not appear if the agent is fully updated.

If you have any questions, don't hesitate to ask.
