### ISSUE TITLE
"Incorrect Kibana version in plugin [wazuh]. Expected [6.3.2]; found [6.3.0]"

### ISSUE THREAD

**Issue by eriknorthrop** [wazuh/wazuh#1490]
This issue started after Yum updated everything. I started receiving the following error in Kibana: "Invalid 'wazuh-app-version' header. Expected version '3.7.x', and found '3.5.x'."

I attempted the update and get stuck after running the following command... 

/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.3.1_6.3.0.zip

Thank you for your help.

**Comment by JuanjiJG** [comment]
Hello @eriknorthrop,

This is weird. What Wazuh repository do you have configured? Could you please paste it here?
```
cat /etc/yum.repos.d/wazuh.repo
cat /etc/ossec-init.conf
cat /usr/share/kibana/plugins/wazuh/package.json | grep version
```

Your error means that your Wazuh API is v3.7.0 (unofficial release of Wazuh) and your Wazuh app is for Wazuh v3.5.0.

The other error message on this issue's title, `"Incorrect Kibana version in plugin [wazuh]. Expected [6.3.2]; found [6.3.0]"` means that you're currently using Kibana v6.3.2 and you tried to install a package for Kibana v6.3.0 ([more info](https://documentation.wazuh.com/current/installation-guide/compatibility_matrix/index.html#api-and-app)).

Regards,
Juanjo

**Comment by eriknorthrop** [comment]
Hello, 

As requested: 

cat /etc/yum.repos.d/wazuh.repo

[wazuh_repo]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=Wazuh repository
baseurl=https://packages.wazuh.com/3.x/yum/
protect=1
 
cat /etc/ossec-init.conf

DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.7.0"
REVISION="3702"
DATE="Tue Sep 25 13:41:16 UTC 2018"
TYPE="server"

cat: /usr/share/kibana/plugins/wazuh/package.json:

No such file or directory

**Comment by JuanjiJG** [comment]
Hi again @eriknorthrop,

You're using an unreleased version of Wazuh. Did you install it from sources? Your current Wazuh repo is the stable one, so the latest available version that you should have from packages is v3.6.1.

You need to use our latest stable release in order to use the latest compatible app version. This is our [installation guide](https://documentation.wazuh.com/current/installation-guide/index.html). Please check it out to properly install Wazuh manager, API and app.

If you have registered agents an a custom configuration on your manager, maybe you want to back up the `ossec.conf` and `client.keys` files before trying to install a stable Wazuh release.

Let us know if you have more questions or problems.

Regards,
Juanjo

**Comment by eriknorthrop** [comment]
I will reinstall and go from there. I do want to raise the issue that updating via yum did produce the same error as described. Should this happen again then I will update this thread with the error code. 

Thanks.

**Comment by JuanjiJG** [comment]
Hi @eriknorthrop,

We do not recommend updating packages using `yum` or `apt` without checking our [upgrading guide](https://documentation.wazuh.com/current/installation-guide/upgrading/latest_wazuh3_minor.html#upgrading-latest-minor). In fact, when installing the Elastic Stack, the last step is to disable the repository in order to avoid undesired upgrades, because the Wazuh app requires full and same version compatibility in order to install it.

Let us know if you need more help.

Regards,
Juanjo
