### ISSUE TITLE
Segmentation fault in Analysisd

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#14923]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| Since 4.4 | Analysisd | Manager | Any | Any |

# Description
During PR #14138 validation, it was found that Analysisd segfault during a log evaluation using wazuh-logtest.

![image](https://user-images.githubusercontent.com/1791430/190514700-41e2a2d5-132b-4696-87d4-da4b68c1b8e7.png)

![image](https://user-images.githubusercontent.com/1791430/190515819-b8c69c27-89cb-4d00-9293-3b77cba7d0f1.png)

This seems to be related with changed decoder [here](https://github.com/wazuh/wazuh/pull/14138/files#diff-edf0d4994471b4b1bd3b7a783aeff83b936c895359916285619a8e01c6797fb4)
![image](https://user-images.githubusercontent.com/1791430/190514882-ed61b3a2-b213-4351-a881-d34fa29d4e6b.png)

Despite PR #14138 aims to 4.5 (master), it was traced that this also happens in 4.4 branch

## DoD
- [x] RCA @juliancnn @jnasselle 
- [ ] Propose a fix and UT (code and ruleset test)
- [ ] CI Checks
- [ ] QA coverage

**Comment by juliancnn** [comment]
The segfault occurs under very specific conditions.
It can be produced only at the decoding stage and other places in the Wazuh code.

The commit https://github.com/wazuh/wazuh/commit/90d839e712f6e5e580fb5e11b5d3bba3789f9cbb associated with the PR https://github.com/wazuh/wazuh/pull/11195, introduces a false fix (there is nothing to fix), forcing the `matching_regex` structure to an incorrect `prts_str_alloc_size` value.
`prts_str_alloc_size` determines the size of the `prts_str_size` vector causing the code to crash under certain conditions.

### Conditions:
- The `regex_matching` structure must be shared or used by more than 1 regex execution (i.e. decode stage)
- You must first execute a regex containing at least 3 capturing groups and succeed in extracting. (this added to the general match, are 4 groups, (ie at least 16 bytes), (i.e `Disconnect(ed|ing) (from )?(invalid )?user`)
- Second and in a row, a regex containing at least 3 groups (but not more than the previous regex) must be executed and succeeded. (i. e. `^(\S+) (\S+) port (\d+)`)

In `os_regex_execute` the structure increases its size if necessary, it never decreases, that is why the logtest session is restarted for tests.

The fix should be simple, revert the commit https://github.com/wazuh/wazuh/commit/90d839e712f6e5e580fb5e11b5d3bba3789f9cbb.
This generates another problem, the following line fails (And it should):
https://github.com/wazuh/wazuh/blob/527fbaa42402e94c23ceeeca54f8afff12aa491f/src/shared/validate_op.c#L433-L434
The reason is that `d_size.prts_str_alloc_size` is not necessary in PCRE2, also that operation does not give the size of the extracted groups, but the maximum number of groups that were ever extracted with the `regex_match` structure.

To fix this, you need to count the elements of the `regex_match->sub_strings array`.


I made this change in my local enviroment and seem be works fine.
