### ISSUE TITLE
Missing vulnerabilities dashboard listing all (critical, high, medium, low) vulnerabilities for all agents

### ISSUE THREAD

**Issue by atlantsecurity** [wazuh/wazuh#14951]
In the latest versions of Wazuh, there is no dashboard showing all vulnerabilities for all agents in one place. 

Checking agent by agent is ... not a very wise method if you have hundreds or thousands of them.

**Comment by Dwordcito** [comment]
Hi, @atlantsecurity I hope you are well!

I understand your point, but it's also important to mention that the information shown previously was not reliable.

It is very important to emphasize that we are already working on a refactor for the entire vulnerability detector, which will allow you, among other things, to have aggregated and centralized information so that this information is useful. We will also improve the efficiency, robustness, and flow of execution to make it more natural.

I hope you find this information useful and understand that in future versions we will give you many improvements.

https://github.com/wazuh/wazuh/issues/14153
