### ISSUE TITLE
CoreOS agent

### ISSUE THREAD

**Issue by rogeduardo** [wazuh/wazuh#1501]
It is possible create a agent for CoreOS system? I dont know how I can use Wazuh for monitor CoreOS

**Comment by juan70** [comment]
Hi, @rogeduardo,

There are four possibilities:
1. A wodle `docker-listener` exists, and allows monitoring Docker servers: https://documentation.wazuh.com/current/docker-monitor/index.html. 
2. Since CoreOS is designed for containers and has Docker out of the box, it is possible to run a supported Operating System within a Docker container within CoreOS, and install an agent in the container.
3. CoreOS contains a toolbox that installs a stock Fedora set of tools `/bin/toolbox`. This performs a chroot, and it is possible to install some software directly on CoreOS, that is not in a Docker container: https://unix.stackexchange.com/questions/203606/is-there-any-way-to-install-nano-on-coreos. It is possible to install the RPM Wazuh agent package.
4. With this toolbox, it is also possible to install the tools needed to install the agent from sources.

For the third and fourth cases, I made a quick test. It is necessary to run the said `/bin/toolbox` to install everything as described in the documentation (be it installation from package or from sources) for a Fedora system (`yum` can be installed too).
Some things must be taken into account: it will be necessary to run this toolbox every time some action is needed on the agent such as stopping, restarting, and so on, in order for the utilities to see the correct paths, because the toolbox runs in a chroot environment. These actions should be performed using `ossec-control` because `systemctl` seems to not be usable in a chroot environment.


Regards.
Juan.

**Comment by Lopuiz** [comment]
Hi @rogeduardo,
I hope your doubts have been solved. I'll close this issue. If you have any other questions lets us know.
Kind regards, Eva
