### ISSUE TITLE
Engine - Adaptation of current modules to support the API 

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#15026]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0| Engine| Manager| Packages/Sources | OS version |

The purpose of this issue is to prepare the new engine for the construction of an API. It is necessary to adapt our code before working on this new API.

The changes to be made are:
- [x] Catalog
The Catalog rework brings back the Driver interface, splitting the public Interface, the Catalog, from the backend implementation details, the Drivers. This allows us to use a simple file DB to manage the ruleset now, and gracefully improve on the future to more robust and performance techniques.
Additionally improvements such as the Name handling and the Asset concept has been adapted to better suit the current Engine architecture.
- [x] Server

**Comment by juliancnn** [comment]
## Update server

The server was limited to  2 endpoints, API endpoint and Event endpoint, both unix sockets but with different transport and application layer protocols.
Event endpoint was adapted from datagram socket endpoint, eliminating the procol handler.
A new type of enpoint was created, for the API: stream datagram sockets endpoint using the TCP secure protocol.
Also isolate the server, separating it in a static library as best as possible with this architecture, exposing only the basic functionalities.
Fixed minor problems in the API and separated the event parser from ossec to base, so it can be used from logtest without having a server.
Fixed event loop start and stop problems and also added so that both use the same thread.
