### ISSUE TITLE
Engine - Analyze analysisd API behavior

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#15025]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0| Engine| Manager| Packages/Sources | OS version |

It is necessary to analyze the current analisysd API and document it. 
 
Once all the queries that are made from the API to analysisd have been documented, it is necessary to study which of these must be implemented for the new engine, which must be adapted and which new queries can be made.

**Comment by JavierBejMen** [comment]
## Update

Analysisd API listens to requests in the socket `queue/sockets/analysis`. Through this socket analysis exposes metrics and internal configuration APIs. 

In the Engine we will set up a new socket following the Wazuh internal protocol. Since metrics will be implemented later and the ruleset API is currently done through external python scripts, we ignore the current analysisd API socket.

The new socket is `queue/sockets/engine-api`, and we are going to implement the API for:
- Catalog, ruleset management.
- Environment, manage environments in runtime.
