### ISSUE TITLE
`wazuh-modulesd` shows a considerable amount of Agents DB/Bad response after agent removal

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh#15037]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.8 | wazuh-modulesd | Manager | Packages | OS version |

Our daily demo environment monitoring reported a new issue regarding `wazuh-modulesd`. 

## Chronology
A new test agent was added, according to the following log:
```
2022/09/28 07:38:40 wazuh-authd: INFO: New connection from 36.67.76.114
2022/09/28 07:38:40 wazuh-authd: INFO: Received request for a new agent (be75a0e27a46) from: 36.67.76.114
2022/09/28 07:38:40 wazuh-authd: INFO: Agent key generated for 'be75a0e27a46' (requested by any)
2022/09/28 07:38:41 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2022/09/28 07:38:41 wazuh-remoted: INFO: (1410): Reading authentication keys file.
2022/09/28 07:40:34 wazuh-modulesd:vulnerability-detector: INFO: (5431): Starting vulnerability scan.
2022/09/28 07:40:34 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '000' vulnerabilities.
2022/09/28 07:40:34 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '000'
2022/09/28 07:40:34 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '005' vulnerabilities.
```
After adding it, a vulnerability scan started. Then, the agent was manually removed using `manage_agent` tool. 
```
2022/09/28 07:41:17 wazuh-authd: INFO: Agent '005' (be75a0e27a46) deleted (requested locally)
2022/09/28 07:41:21 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2022/09/28 07:41:21 wazuh-remoted: INFO: (1410): Reading authentication keys file.
```
After a minute, the following messages are repeated 225 times:
```
2022/09/28 07:42:20 wazuh-modulesd: ERROR: Bad response from wazuh-db: Agent not found
2022/09/28 07:42:20 wazuh-modulesd: ERROR: Agents DB (5) Error querying Wazuh DB to insert vuln_cves
2022/09/28 07:42:20 wazuh-modulesd: ERROR: Bad response from wazuh-db: Agent not found
2022/09/28 07:42:20 wazuh-modulesd: ERROR: Agents DB (5) Error querying Wazuh DB to insert vuln_cves
...
...
+200 times the same log
...
...
2022/09/28 07:42:28 wazuh-modulesd: ERROR: Bad response from wazuh-db: Agent not found
2022/09/28 07:42:28 wazuh-modulesd: ERROR: Agents DB (5) Error querying Wazuh DB to insert vuln_cves 
```
the last one at `2022/09/28 07:42:28`. 225 messages in 8 seconds.

[ossec-28.log](https://github.com/wazuh/wazuh/files/9675661/ossec-28.log)

**Comment by Dwordcito** [comment]
Hi, @pereyra-m evaluate the change to solve this issue.

**Comment by MiguelazoDS** [comment]
# Overview 

Before the vulnerability detector scan starts, it collects all active agents in a linked list. Specifically in the function `wm_vuldet_collect_agents_to_scan`. After that, the function `wm_vuldet_check_agent_vulnerabilities` will be in charge to perform the correlation between the CVE database and the Syscollector inventory iterating over the agent list. 

Inside `wm_vuldet_check_agent_vulnerabilities` multiple tasks are performed, and some of them take time to be finalized. Any agent deletion after collecting the agents while executing some of those tasks will lead to errors since it will attempt to query an unexistent agent database. 

Evaluating how much time the tasks on `wm_vuldet_check_agent_vulnerabilities` take for one agent 

![image](https://user-images.githubusercontent.com/13010397/193898128-3e3af82b-ab44-433e-9c9e-2f3d8a440416.png)

The times in the red box are part of the `wm_vuldet_find_agent_vulnerabilities`

If we consider the time for that function (34585630us ~= 34s) we can see that at the moment to scan the second agent, we have an active agent list 34 seconds outdated, and that value increases the more agents we have.

Also, if we have just one agent (and we are not scanning the manager) the issue although less probable, is also possible because we have approx 12 seconds from the start to the `wm_vuldet_process_agent_vulnerabilities` function where the error mentioned in the issue occurs. 

The reason why the logs file is flooded with those error messages is that it will attempt to insert each vulnerability found for agent 5 and none of those will be successfully inserted since the agent database no longer exists. 

As mentioned before it is needed to evaluate the possible errors not shown on this issue.

## Conclusion 

Some improvement that could be done in these situations is to add checks prior to querying the agent databases for example in the `wm_vuldet_process_agent_vulnerabilities` to not iterate over all vulnerabilities found. Be sure that errors don't stop the scan over the next agents and do not continue with an agent if it is not possible due to a non-existent agent database. Evaluate if those errors should be moved to warnings because they are inevitable under the agent deletion in the middle of a scan.

**Comment by MiguelazoDS** [comment]
The approach is implemented as part of https://github.com/wazuh/wazuh/pull/17020. On hold waiting for definition.

**Comment by sebasfalcone** [comment]
This behaviour won't be present in the architecture proposed for the new vulnerability detector: 
- https://github.com/wazuh/wazuh/issues/14156
