### ISSUE TITLE
Taking Screenshot

### ISSUE THREAD

**Issue by shahr8888** [wazuh/wazuh#15041]
Hi, I needed to ask if there was any way of making a rule that gives alerts when a screenshot is taken by any agent. I needed to know if there was any rule of this type, and if there is how can I make it.

I'm new to this so kindly help me with that.

Thanks.

**Comment by FrancoRivero** [comment]
Hi @shahr8888, how are you?
We don't have a direct way to capture when someone takes a screenshot on some agent, however, I will try to help you to do it !
Using Wazuh we can use [FIM](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/index.html) to detect in the folder where are saved the screenshots.
So when a new file is added, using [realtime mode](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/fim-configuration.html#configuring-real-time-monitoring) you can detect when some change was done in the folder and generate events in your manager.

You can also do that without using Wazuh, we can detect when any screenshot was taken using DLP because usually the data loss protection software takes care of it. They include all inputs and outputs from/to the computer, so they track screenshots, clipboard, emails, every downloaded file or every upload, etc.
If you don't have [DLP](https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-learn-about-dlp?view=o365-worldwide), then this is impossible. You may have to write a custom service for it. You need something that hooks OS events and generates a custom event. What you need to capture is (according to a [SO reply](https://stackoverflow.com/questions/37233917/can-i-listen-for-the-print-screen-event/37234076#37234076)):

1. Press the print screen key.
2. Check what type of clipboard data it is via code.
3. With this information, code something that clears or knows what the last value of this type of clipboard data is.
4. When the print screen key is pressed, search the clipboard until this data type changes and then grab it.

I hope that work for you !
Regards

**Comment by FrancoRivero** [comment]
Hello @shahr8888 
I hope these suggestions help you.
After some weeks without replies we should close the issue, if you need to reopen this issue let me know.
Regards
