### ISSUE TITLE
FIM limitations

### ISSUE THREAD

**Issue by Luanpablo100** [wazuh/wazuh#15044]
| 4.3.8 | FIM | Windows |
|---|---|---|---|---|
Wazuh Agent | Windows Server 2012+ |

Hello, I'm having some problems using Wazuh's FIM functionality in environments that have large file servers.
My company is in charge of monitoring the servers, and we need to have the information in case the files are changed by users.

I believe that this problem can be quite present in forums and here, in Github issues, but I searched a lot and couldn't find a way to solve my problem.

I found information about the <file_limit> option of the Wazuh Agent, which can be modified to define the maximum limit of files monitored by Syscheck, however, if the database (which I believe is the fim.db file inside the queue folder of the Wazuh Agent ) becomes full, new files will be ignored. Despite having changed this option, new files did not appear in the Wazuh Dashboard logs.

What I need is just to know if it is possible to monitor, for example, 2 million files from a file server, and what would be the impacts of that. And of course, if possible, to be told which settings I should apply in Wazuh Server and Wazuh Agent, so that it works.

Thanks in advance for your attention.

**Comment by FrancoRivero** [comment]
Hi @Luanpablo100, how are you?
[You can disable the database limit](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html#file-limit), however, it is not recommended because depending on the mode you are using you will have different problems. 
For instance, if you are using the scheduled mode you will take a lot of time to generate the database, you will also use a lot of memory and disk and to search for changes in the monitored folders. 
Therefore, we recommend using the FIM only with specific folders and important files, as you may miss an important change among the large number of files and you will lose performance by monitoring many files.
I hope that work for you !
Regards

**Comment by Luanpablo100** [comment]
Hi @FrancoRivero.
Thanks for your attention.
I will try to reduce my scope for monitoring, after some tests, I managed to monitor many of the files I wanted, but in fact, the performance, especially of the Wazuh Server, was harmed, I believe that the API was not able to handle so many events, ideally I would prefer that I could increase the performance of the API as my server has the hardware resources for this, but I will follow everyone's recommendation to try not to monitor so many files at the same time.
