### ISSUE TITLE
Wazuh AWS module with unknown fields 

### ISSUE THREAD

**Issue by leo8034** [wazuh/wazuh#15059]
Wazuh manager Version
[{"WAZUH_VERSION":"v4.3.6"},
{"WAZUH_REVISION":"40318"},
{"WAZUH_TYPE":"server"}]}

Hi, I'm currently working on the data visualize , but have some issuse about the AWS module, I have two Wazuh manager server receiving AWS cloudtrail logs , and I'd like to have some visualize setup while waiting the log analyze , and just notice that some filed in server 1 are defined as String filed , but the same field in server 2 has defined as Unknown filed , cause those fields can't be used in visualization setting, I've to wait for analyzation about 2-3 days and setting debug mode ,but still the same , ,just curious does this also need some time for log analyze? Or is it a bug?

Thanks

![image](https://user-images.githubusercontent.com/37360931/193513510-18347c74-9c76-443d-8f1d-eff0aad7ef42.png)

**Comment by CarlosRS9** [comment]
Hi @leo8034 

That structure is generated based on the data received. The explanation for this behaviour would be that one manager received alerts with `aws_account_id` values and has therefore been defined as a string, while the other has no values and has been defined as unknown.

Regarding the `aws_account_id` field itself there are 2 minor bugs that were reported on https://github.com/wazuh/wazuh-kibana-app/issues/3931 and https://github.com/wazuh/wazuh-kibana-app/issues/2260 that might be related to the behaviour you are experiencing. These have been fixed in the future release `4.4`.
