### ISSUE TITLE
Prevent creating rules/decoders when their name exists on the default ruleset

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#15066]
|Component|
|---|
| Wazuh API |

## Description

When trying to create new custom rules or decoders files (inside `/var/ossec/etc/`) using the API, it does not check whether the name does already exist in the default ruleset (`/var/ossec/ruleset`). For example, here we can see how a file named `0017-wazuh-api_rules.xml` exists:
``` 
# ls -lh /var/ossec/ruleset/rules/0017-wazuh-api_rules.xml 
-rw-r----- 1 root wazuh 6.5K Oct  3 09:48 /var/ossec/ruleset/rules/0017-wazuh-api_rules.xml
```

But when we upload a new one through `PUT /rules/files/0017-wazuh-api_rules.xml`, it is also created, this time in `etc/rules/0017-wazuh-api_rules.xml`:
```
{
  "data": {
    "affected_items": [
      "etc/rules/0017-wazuh-api_rules.xml"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Rule was successfully uploaded",
  "error": 0
}
```
```
# ls -lh /var/ossec/etc/rules/
total 12K
-rw-rw---- 1 wazuh wazuh 6.5K Oct  4 07:26 0017-wazuh-api_rules.xml
-rw-rw---- 1 wazuh wazuh  497 Oct  3 09:48 local_rules.xml
```

The API should check if a file exists not only in `/var/ossec/etc/` but also inside `/var/ossec/ruleset` before allowing a new one to be created.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by jctello** [comment]
It is critical here to allow to add files with the same filename as long as they are initially excluded with [<rule_exclude>](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/ruleset.html#rule-exclude) or [<decoder_exclude>](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/ruleset.html#decoder-exclude) as of Wazuh 4.3.10 the API still incorrectly provides them as part of the [GET /rules](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.rule_controller.get_rules) endpoint. 
As an out of the box example you may see the 0215-policy_rules.xml file which is excluded by default (as a good example).

Note that [our documentation on how to change an existing decoder](https://documentation.wazuh.com/current/user-manual/ruleset/custom.html#changing-an-existing-decoder) specifically instructs users to create a file with the same name as the original, and this is a good approach that should not be broken because of this issue.

**Comment by jctello** [comment]
Additionally, even by fixing the `GET /rules`, `GET /rules/files`, `GET /decoders` and `GET /decoders/files` endpoints it is important to allow users to create a new file before restarting the manager after excluding a stock ruleset file.

So this should allow the creation of the file with a duplicate name taking into consideration the configuration (and not what the manager has in memory).

**Comment by davidjiglesias** [comment]
After evaluating the issue with @vicferpoy and taking into account the recommendations from @jctello, we have decided to approach the issue in https://github.com/wazuh/wazuh/issues/15994.
