### ISSUE TITLE
`segfault` using API when upgrading agents

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh#15172]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.9-1 | wazuh-modulesd | Manager | Packages | Amazon Linux 2 |

## Environment
Configured an All-in-One Wazuh server. The AWS VM type: `c5.xlarge`. After that, I registered and connected 34 agents (v4.3.8):
- 10 hosts Ubuntu 22.04.
- 11 hosts Windows Server 2016 Datacenter.
- 13 hosts Windows Server 2019 Datacenter. 

## Steps
Going to `API Console`, the query used was:
```
PUT /agents/upgrade?agents_list=all
```
It returned a list of created tasks. Then:
```
GET /agents/upgrade_result
```
This last query returned a message about the `wazuh-modulesd` daemon missing. The daemon was not up/running. 

### Files checked
- `/var/log/messages`:
```
[root@ip-172-31-88-159 ec2-user]# cat /var/log/messages | grep -i segfault
Oct 14 16:17:25 ip-172-31-88-159 kernel: wazuh-modulesd[7496]: segfault at 6e88 ip 00007f2d878c9377 sp 00007f2d3effc300 error 4 in libc-2.26.so[7f2d8784f000+1a4000]
```
- The `/var/ossec/logs/ossec.log` file had no error, critical, or warning messages. 

## Post-segfault actions
After the Wazuh manager restarted, some update tasks were pending finish. I run again the upgrade query, including the check after PUT, without segfault.

**Comment by chemamartinez** [comment]
After a first research, conclusions are:
- It has not been reproduced again after several tries
- It is not related to https://github.com/wazuh/wazuh/issues/15060 since this is crashing in the `libc-2.26.so` instead of `libwazuhext.so`. In addittion, Vulnerability Detector was not enabled when happened.
- Evaluating the offset `7A377` to find the offending instruction. Here the results:
  - No match obtained from `objdump`
  - `addr2line` points to `malloc`
```
[root@ip-x.x.x.x ~]# objdump -DCgl /usr/lib64/libc-2.26.so | grep "7A377"
[root@ip-x.x.x.x ~]#
[root@ip-x.x.x.x ~]# addr2line -e /usr/lib64/libc-2.26.so 7A377
malloc.c:?
```

**Comment by chemamartinez** [comment]
After that first research, we tried to reproduce the issue again under the following conditions:

### Test 1

- Manager v4.3.9 (Ubuntu 22.04)
- Manual WPK upgrade from v4.3.8 to v4.3.9 through the Wazuh API for the following agents:
  - Ubuntu 20.04
  - Windows Server 2019
  - macOS 12.3

The `wazuh-modulesd` was running over `valgrind` in all the cases to detect any memory issue that could lead to a segmentation fault during the upgrade procedure.

All the upgrades were successful and `valgrind` didn't report any access to invalid memory.

### Tests 2

The `agent-simulator` tool has been used to deploy around 50 Windows agents at the same time. After that, the upgrade request has been launched while monitoring `wazuh-modulesd` with `valgrind` again.

The result is the same as before, the daemon doesn't crash and `valgrind` doesn't report any issues.

### Research

Changes related to the WPK upgrade procedure have been reviewed since the new `upgrade module` and `task module` were added in v4.2.0:

- https://github.com/wazuh/wazuh/pull/5856
- https://github.com/wazuh/wazuh/pull/15023
- https://github.com/wazuh/wazuh/pull/13662

Didn't find any clue to debug this crash.
