### ISSUE TITLE
POC: API webhook 

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#15325]
| **Working branch** |
| - |
| [poc/15325-api-webhook](https://github.com/wazuh/wazuh/tree/poc/15325-api-webhook) |

This issue aims to develop and test a quick POC for an API endpoint that will be in charge of ingesting events for analysisd.

The POC will add a new son process for wazuh-apid that will be exclusively in charge of executing the hook. We will use [locust](https://locust.io/) tool to do a load performance test for the endpoint.

We can use any kind of event for testing purposes as long as it is accepted by analysisd. Measuring the performance with events of different size is also important.

**Comment by vicferpoy** [comment]
# Issue update

A new endpoint has been implemented to allow forwarding security events to `analysisd`.

![image](https://user-images.githubusercontent.com/37274979/200801036-e443e7d9-9d6a-441c-82f2-993688df3b2a.png)

This endpoint is subject to change, but it will allow performing benchmark tests for the POC.

**Comment by vicferpoy** [comment]
# Issue update

Locust tests have been performed. Important to note that they have been performed over the same machine that was hosting the Wazuh API. 

## AWS log (1252B)

### POST /events

#### 1 user (sequential)

![image](https://user-images.githubusercontent.com/37274979/200809010-7170b2d5-31d5-4846-8247-b3d3a9ecb1bb.png)

[Full report](https://github.com/wazuh/wazuh/files/9970055/1252B-event-single.zip)

---------------------

#### 50 users (sequential)

![image](https://user-images.githubusercontent.com/37274979/200810913-65e83f8d-cf95-458e-aa96-5cc0a898224b.png)

[Full report](https://github.com/wazuh/wazuh/files/9970105/1252B-event-50-users.zip)

**Comment by vicferpoy** [comment]
## AWS log (46300B)

### POST /events

#### 1 user (sequential)

![image](https://user-images.githubusercontent.com/37274979/200814032-75559511-ecbf-462b-b793-4b02113e7c61.png)

[Full report](https://github.com/wazuh/wazuh/files/9970297/46KB-event-single.zip)

#### 50 users (sequential)

![image](https://user-images.githubusercontent.com/37274979/200814582-a78c34b5-39a5-4ad6-8e5f-1c055945169a.png)

[Full report](https://github.com/wazuh/wazuh/files/9970337/46KB-event-50-users.zip)

### POST /events and GET /agents (5:1)

#### 50 users (asynchronous)

![image](https://user-images.githubusercontent.com/37274979/200815255-2fb29c05-f9c2-494b-bc75-b501228cefae.png)

[Full report](https://github.com/wazuh/wazuh/files/9970384/46KB-event-agents-50-users.zip)

**Comment by vicferpoy** [comment]
# Issue update

In order to get an idea of what we could achieve splitting this endpoint into its own API, a really simple API has been implemented using `FastAPI` and `uvicorn`, running along the Wazuh API. This API has the exact endpoint to forward security events but it listens to another port instead. 

Same environment considerations must be taken into account. The same "small" event from above was used for this comparison.

Number of requests and the latest RPS statistics from previous reports will be used.

## Comparison

|                     | **Number of users** | **# Requests** | **Average (ms)** | **RPS** |
|:-------------------:|:-------------------:|:--------------:|:----------------:|:-------:|
|    **Wazuh API**    |          1          |      4860      |         8        |   110   |
|                     |          50         |      5700      |        407       |   95.5  |
| **Implemented API** |          1          |      33164     |         1        |  552.8  |
|                     |          50         |      56646     |         6        |  943.7  |


It is important to note that the implemented API does not have any kind of authentication procedure (as opposed to the Wazuh API with the JWT decoding, RBAC) and distribution algorithm (check if the request must be executed locally or be distributed to another cluster node).

Also, we cannot ensure that the Wazuh API performance would not be affected at all having another API implemented listening to this specific endpoint (and possibly more related ones), as they would share resources in the same machine, but its performance would be way better than implementing this endpoint into it (sharing request queue), as long as each API would have at least one CPU core available.

[FastAPI Locust reports](https://github.com/wazuh/wazuh/files/9982451/fastapi-report.zip)

<details>

<summary>Implemented API code</summary>

```python
import socket

import uvicorn
from fastapi import FastAPI
from pydantic import BaseModel


class LogEvent(BaseModel):
    event: str


app = FastAPI()


@app.post("/events")
async def events(log_event: LogEvent):
    event = log_event.event
    msg_header = "1:Wazuh-AWS:"
    s = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
    try:
        s.connect("/var/ossec/queue/sockets/queue")
        s.send(f"{msg_header}{event}".encode())
        return {'message': 'ok'}
    except Exception as e:
        return {'error': str(e)}
    finally:
        s.close()


if __name__ == "__main__":
    uvicorn.run(
        "api:app",
        host="0.0.0.0",
        port=9999
    )

```

</details>
