### ISSUE TITLE
Windows agent enrollment configuration block overindented

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#15324]
| Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0-0 | Install | Agent | Packages | Windows Server 2016 |

### Description
Using deployment variables in Windows agent installation, the enrollment configuration block provisioned is over-indented.

### Steps to reproduce
- Download the Wazuh Windows agent package
- Install Windows agent using enrollment deployment variables, for example: `./wazuh-agent-4.3.9-1.msi /q WAZUH_REGISTRATION_SERVER="10.0.0.2"`
- Check enrollment configuration
```
    <enrollment>
      	<enabled>yes</enabled>
        <manager_address>10.0.0.2</manager_address>
    </enrollment>
```
Expected
```
    <enrollment>
      <enabled>yes</enabled>
      <manager_address>10.0.0.2</manager_address>
    </enrollment>
```

**Comment by davidcr01** [comment]
# Update Report

## Analysis

It seems that the problem is in the `src/win32/InstallerScripts.vbs` file, in the following lines:

https://github.com/wazuh/wazuh/blob/48e49b12ecafb2ce9566329fe97d7892bf931d3d/src/win32/InstallerScripts.vbs#L155-L202

It can be observed that the `enrollment` tag contains 4 spaces of separator, whereas the contained subtags contain 8 spaces (should be 4+2 spaces)

```
"    <enrollment>"
"....<>"
"        <enabled>yes</enabled>"
"        <manager_address>"
"........<>"
```

## Development

To fix this, the solution is just to remove two spaces of the enrollment subtags (manager_address, port, authorization_pass_path, server_ca_path, agent_certificate_path, agent_key_path, agent_name, groups, delay_after_enrollment)

To check this, it's necessary to create a Windows package and check if the Windows agent enrollment configuration is not overidented.
