### ISSUE TITLE
Old distros can't use SSLv3 to agent-auth

### ISSUE THREAD

**Issue by kreon** [wazuh/wazuh#154]
JFYI: ubuntu 12, centos 5, old debian can't use SSLv3 to obtain clients.key via ossec-authd.
In my environment I changed SSL protocols to SSLv12 as we have a lot of frozen projects.

**Comment by vikman90** [comment]
Hi @kreon,

we are aware of this, `ossec-authd` uses the system's SSL library. This library has not been updated in old systems and lacks modern methods such SSLv3 or TLSv1.2.

I recommend you to install the manager in a modern system (Ubuntu Trusty+ or CentOS 6+). As of Wazuh v2.0, `ossec-authd` (manager) is able to force to use TLSv1.2 (default) or allow the most secure common method.

You can enable this feature to "relax" the TLSv1.2 using constraint by option `-a`:

> `/var/ossec/bin/ossec-authd -a`

With this option the manager will accept whatever method since SSLv2.3.

Hope it help.
Best regards.

**Comment by kreon** [comment]
It's not about the manager, it's about the agents. centos5 agents can't get key via agent-auth because of SSL. I would be nice if there were an automatic protocol downgrade for old agents e.g. 'try modern TLS1.2, go down to sslv2 if failed'.

**Comment by vikman90** [comment]
Agents will always try to use the best common method. For example:

- If agent supports SSLv2.3, SSLv3.0, TLSv1.0 and TLSv1.2: it will always connect using TLSv1.2.
- If agent supports SSLv2.3, SSLv3.0 and TLSv1.2: it won't connect unless manager runs `ossec-authd -a`. With this option it will use TLSv1.0 (the most modern common method).
- If agent supports SSLv2.0 and SSLv2.3: the same condition as above, it will use SSLv2.3.
- If agent only supports SSLv2.0: it will never be able to connect.

This is the designed behavior. If it doesn't follow this schema please let us know.
