### ISSUE TITLE
CMD popup when installing MSI

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#15414]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0| Wazuh MSI | Agent | Packages | Windows |

We have found that when installing the MSI package a CMD window pops up for a short time. By using a machine with low resources we were able to extend this time and find which task was creating the pop-up, and we gound that it was a `taskkill.exe` execution.

Knowing this we can say that the  cause of this comes from here:
https://github.com/wazuh/wazuh/blob/b99a2dd76bfe7b88c3ef8127cf5521f5fad3833a/src/win32/wazuh-installer.wxs#L105

We need to make this execution silent to avoid this popup.

**Comment by verdx** [comment]
When trying to upgrade with an open GUI, error 2349 is shown again:
![error2349](https://user-images.githubusercontent.com/61122643/202753266-6be4a536-da74-45c6-82b9-220c24dc1aa1.png)
The Restart Manager doesn't appear, so line:
```
        <Property Id="MSIRESTARTMANAGERCONTROL" Value="Disable"/>
```
is working properly, but it seems the script function with which we have substituted the custom action is not correctly killing the GUI.

**Comment by verdx** [comment]
To test if the function was called correctly from the MSI, I tried several options.
1- Trying to call `WshShell.run` with the option to open a terminal showed a terminal, but too fast to see.
```
Public Function KillGUITask()
    Set WshShell = CreateObject("WScript.Shell")

    taskkill = "taskkill /f /im win32ui.exe"
    WshShell.run taskkill, 3, True

End Function
```
2- The next test was to redirect the output of `taskkill` to a file, but the file is not created.
```
Public Function KillGUITask()
    Set WshShell = CreateObject("WScript.Shell")

    taskkill = "taskkill /f /im win32ui.exe > Z:\taskkill.txt"
    WshShell.run taskkill, 0, True

End Function
```
3- To see if the function was being called, I tried adding a popup, which appeared:
```
Public Function KillGUITask()
    Set WshShell = CreateObject("WScript.Shell")

    taskkill = "taskkill /f /im win32ui.exe"
    WshShell.run taskkill, 0, True
    WshShell.popup "Test 1"

End Function
```
![testpopup](https://user-images.githubusercontent.com/61122643/202773607-4132b0f2-1fb6-42c9-8628-59ac29b16bee.png)

Finally, as a summary, it seems the function is running but the command isn't.

**Comment by verdx** [comment]
After talking with @DFolchA , the problem seems to be how the Custom Action was being called, as it wasn't called as an administrator. For the action to be called as an administrator, the `Execute` property must be set as `deferred` and not `immediate`, as it has been until now. The call to the Custom Action is now:
```
        <CustomAction Id="CloseGUI" BinaryKey="InstallerScripts" VBScriptCall="KillGUITask" Return="check" Execute="deferred" Impersonate="no"/>
```

The new package has been tested in various Windows environments:
## Tests


Tests needed:
- Windows Server 2016
 - [x] Fresh installation
 - [x] Upgrade without open GUI
 - [x] Upgrade with open GUI
- Windows Server 2019
 - [x] Fresh installation
 - [x] Upgrade without open GUI
 - [x] Upgrade with open GUI
- Windows Server 2022
 - [x] Fresh installation
 - [x] Upgrade without open GUI
 - [x] Upgrade with open GUI
- Windows 10
 - [x] Fresh installation
 - [x] Upgrade without open GUI
 - [x] Upgrade with open GUI
- Windows 11
 - [x] Fresh installation
 - [x] Upgrade without open GUI
 - [x] Upgrade with open GUI

**Comment by verdx** [comment]
Blocked: https://github.com/wazuh/wazuh-qa/issues/3625
