### ISSUE TITLE
FIM DB Development status update and testing

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#15425]
|EPIC|Component|
|---|---|
| https://github.com/wazuh/wazuh/issues/9103 | FIM |

### Description
Hello team, we are close to close this FIM DB development. This issue is to gather all the tests that can help us to leave a clean state of development after the last changes.

### To do

- [x] Manual testing (ITs, UTs, RTR, etc)
- [x] Exploratory testing if needed
  - Previous issue: https://github.com/wazuh/wazuh/issues/11935
  - [x] Linux
  - [x] Windows
  - [x] MacOS
- [x] Compilation and testing in HP-UX
- [x] Coverity
  - Last state: https://github.com/wazuh/wazuh/issues/12785
- [x] Stress tests
  - Comparative: https://github.com/wazuh/wazuh/issues/10223

**Comment by jotacarma90** [comment]
# Exploratory Testing Windows

- [ ] Compile the agent without warnings in FIM project

### Scan

- [ ] Run a baseline and check it is properly synced with the manager
- [ ] Run a scheduled scan forcing an insertion/modification/deletion
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with realtime to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with whodata to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Run a registry scan forcing an insertion/modification/deletion (for Windows only)
 - [ ] Every alert has the correct fields
 - [ ] The database is properly updated for every change

### Synchronization

- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Force an inconsistency by modifying an entry in the manager database. Check that the next sync restores the data.
- [ ] Force an inconsistency by deleting the whole `fim_entry` table on the manager side. Check that the next sync restores the data

### Retrocompatibility

For this section install an agent 4.2.x and run the following tests. The goal is to verify the sync process before the development (in charge of FIM) is working with the manager after the change.
- [ ] The baseline is properly stored in the manager database
- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Test sync: check both databases are synced, stop agent, add/modify/delete some monitored files, start agent. Databases should be synced again.

**Comment by MarcelKemp** [comment]
## Coverity

## Summary

|Build ID|Coverity version|Platform|New defects found|Defects eliminated|
|---|---|---|---|---|
|496474|2022.11.0|Ubuntu 22.04|6|3|

## Results

### New defects

|Status|CID|Type|Impact|Date|Component|
|:-:|---|---|---|---|---|
|🟢|300029|Waiting while holding a lock|Medium|Nov 25, 2022|Syscheck|
|🟣|300028|Use of 32-bit time_t|High|Nov 25, 2022|Syscheck|
|🟣|300027|Use of 32-bit time_t|High|Nov 25, 2022|Syscheck|

### Status legend

🔴 Fix pending
🟡 Untriaged
🟢 Intentional
🔵 Ignore
🟣 Fixed
⚪ False positive

### New defects explanation

- **Use of 32-bit `time_t` [[300027]](https://scan9.scan.coverity.com/reports.htm#v42681/p12779/fileInstanceId=105346362&defectInstanceId=8959675&mergedDefectId=300027) [[300028]](https://scan9.scan.coverity.com/reports.htm#v42681/p12779/fileInstanceId=105346373&defectInstanceId=8959654&mergedDefectId=300028)** - 🟣
  The variable `m_time`, is being assigned to the `unsigned int` `->mtime` variable of the `fim_file_data` and `fim_registry_key` structures. This will cause data truncation as of 2106 (for `unsigned int`).
  To fix this problem, the type of variable `->mtime` has been changed from `unsigned int` to `time_t`.

- **Waiting while holding a lock (SLEEP) [[300029]](https://scan9.scan.coverity.com/reports.htm#v42681/p12779/fileInstanceId=105346385&defectInstanceId=8959665&mergedDefectId=300029&eventId=8959665-5)** - 🟢
We have two flows that cause this problem. Both flows are intentional, because if we didn't have the lock, it could cause a race condition (which was fixed in the next commit https://github.com/wazuh/wazuh/commit/dd8adb4547b9409d8afb66b2888bda2882356c00):
  - `fim_send_sync_state` -> `w_mutex_lock` -> `fim_send_msg` -> `SendMSGPredicated` -> `os_wait_predicate` (where `sleep` is applied). 
  > According to `os_wait_predicate`, it was introduced due to the following PR: https://github.com/wazuh/wazuh/pull/11425
  
  - `fim_send_sync_state` -> `w_mutex_lock` -> `fim_sync_check_eps` -> `if (++n_msg_sent == syscheck.sync_max_eps)` -> `sleep(1)` 
  > The sleep is added by the following PR: https://github.com/wazuh/wazuh/pull/4604

**Comment by MarcelKemp** [comment]
# Test ubuntu20 agent
- [ ] Compile the agent without warnings in FIM project
```
/wazuh/src/syscheckd/src/fim_diff_changes.c: In function 'initialize_file_diff_data':
/wazuh/src/syscheckd/src/fim_diff_changes.c:497:35: warning: '/file/' directive output may be truncated writing 6 bytes into a region of size between 0 and 4096 [-Wformat-truncation=]
  497 |     snprintf(buffer, PATH_MAX, "%s/file/%s", abs_diff_dir_path, encoded_path);
      |                                   ^~~~~~
/wazuh/src/syscheckd/src/fim_diff_changes.c:497:5: note: 'snprintf' output between 7 and 4143 bytes into a destination of size 4096
  497 |     snprintf(buffer, PATH_MAX, "%s/file/%s", abs_diff_dir_path, encoded_path);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Scan

- [x] Run a baseline and check it is properly synced with the manager
- [x] Run a scheduled scan forcing an insertion/modification/deletion
  - [x] Every alert has the correct fields
  - [x] The database is properly updated for every change
- [x] Monitor a folder with realtime to generate an insertion/modification/deletion (if supported)
  - [x] Every alert has the correct fields
  - [x] The database is properly updated for every change
- [x] Monitor a folder with whodata to generate an insertion/modification/deletion (if supported)
  - [x] Every alert has the correct fields
  - [x] The database is properly updated for every change
 
### Synchronization

- [x] The sync process runs every interval
- [x] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Test sync: check both databases are synced, stop agent, add/modify/delete some monitored files, start agent. Databases should be synced again.

**Comment by jotacarma90** [comment]
# Test macOS

- [ ] Compile the agent without warnings in FIM project


### Scan

- [x] Run a baseline and check it is properly synced with the manager
- [x] Run a scheduled scan forcing an insertion/modification/deletion
  - [x] Every alert has the correct fields
  - [x] The database is properly updated for every change
- [ ] Monitor a folder with realtime to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with whodata to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Run a registry scan forcing an insertion/modification/deletion (for Windows only)
 - [x] Every alert has the correct fields
 - [ ] The database is properly updated for every change

### Synchronization

- [x] The sync process runs every interval
- [x] When databases are synced, the sync process is just a message with the checksum verification
- [x] Force an inconsistency by modifying an entry in the manager database. Check that the next sync restores the data.
- [x] Force an inconsistency by deleting the whole `fim_entry` table on the manager side. Check that the next sync restores the data
