### ISSUE TITLE
`wazuh-analysisd` shows `bad load query` messages

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#15455]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| Found in: 4.4.0 | wazuh-analysisd | Manager | Packages | CentOS 7 |

In the analysis of the 3 days stress test: https://github.com/wazuh/wazuh-jenkins/issues/4423#issuecomment-1320984282, the following error was found in the CentOS Wazuh server:

```
ossec-18.log:2022/11/18 09:08:29 wazuh-analysisd: ERROR: Bad load query: 'agent 001 rootcheck save 1668762503 Ending CIS-CAT scan. File: /var/ossec/wodles/cis-cat/benchmarks/CIS_CentOS_Linux_7_Benchmark_v2.1.1-xccdf.xml. '.
ossec-18.log:2022/11/18 09:08:29 wazuh-analysisd: ERROR: Rootcheck decoder unexpected result: ''
```

Note that there is a whitespace character at the end of the first error message, after the period of the file extension:

- 1-xccdf.xml.` `'.

It is necessary to determine if this whitespace character can be the cause of the bad query or if it is caused by another behavior, in the latter case, it would also be necessary to consider whether or not to eliminate the whitespace character.

In addition, it is necessary to determine if the second error message is caused by the first message and if it is not, it is necessary to open another issue to investigate it.

---

The following errors have also been found:

```
ossec-18.log:2022/11/18 09:22:41 wazuh-analysisd: ERROR: Bad load query: 'agent 001 rootcheck save 1668763355 File '/tmp/test_active_response.log' is owned by root and has written permissions to anyone.'.
```

```
ossec-18.log:2022/11/18 09:40:01 wazuh-analysisd: ERROR: Bad load query: 'agent 001 rootcheck save 1668764395 Anomaly detected in file '/var/lib/docker/overlay2/c769de22bf8ce911af66f7378c5083b0ee2f99dfecf4ea06850e461db492c336-init/merged'. Hidden from stats, but showing up on readdir. Possible kernel level rootkit.'.
```

```
ossec-18.log:2022/11/18 09:58:39 wazuh-analysisd: ERROR: Bad load query: 'agent 003 rootcheck save 1668765513 Starting rootcheck scan.'.
```

**Comment by chemamartinez** [comment]
Hi team,

The errors reported in this issue happen at the same timestamp as the manager reaches the limit of opened descriptors due to the descriptor leak. In [this comment](https://github.com/wazuh/wazuh-jenkins/issues/4423#issuecomment-1322499647), we can see more context as well as other errors that help to understand the situation.

```
2022/11/18 09:08:29 wazuh-db: ERROR: at run_dealer(): accept(): Too many open files in system
2022/11/18 09:08:29 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 09:39:59 wazuh-analysisd: ERROR: FIM decoder: Bad response from database: Cannot save Syscheck
2022/11/18 15:27:30 wazuh-db: ERROR: sqlite3_step(): unable to open database file
2022/11/18 21:13:34 wazuh-remoted: ERROR: (1242): Couldn't accept TCP connections: Too many open files in system (23)
```

We have to take into account that these errors appear in a footprint test when debugging a descriptor leak, they didn't appear in the same tests with the pre-release version of 4.4.0.

The reason for the errors is that Analysisd and Wazuh DB don't have available descriptors to open the Rootcheck and FIM databases. Therefore, when trying to load a query in the database, it throws these errors.

We can close this issue since this is a consequence of the bug reported at https://github.com/wazuh/wazuh/issues/15386 which is already fixed in v4.4.0-alpha2.

Regards.
