### ISSUE TITLE
The agent 000 obsolete vulnerability could not be processed

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#15456]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| Found in: 4.4.0 | wazuh-modulesd:vulnerability-detector | Manager | Packages | CentOS 7 |

Related: https://github.com/wazuh/wazuh/pull/8080#discussion_r608288234
  - Message introduced in `4.3.0` version, `40301` revision

In the analysis of the 3 days stress test: https://github.com/wazuh/wazuh-jenkins/issues/4423#issuecomment-1320984282, the following error was found in the CentOS Wazuh server:

```
ossec-18.log:2022/11/18 09:38:00 wazuh-modulesd:vulnerability-detector: ERROR: The agent '000' obsolete vulnerability could not be processed
```

It is necessary to investigate the cause of this error.

**Comment by mjcr99** [comment]
Hi team,

The reported error in this issue is happening in a time interval near the following log:
```
2022/11/18 09:08:04 wazuh-modulesd:azure-logs: INFO: Starting Log Analytics collection for the domain 'wazuh.onmicrosoft.com'.
2022/11/18 09:08:29 wazuh-db: ERROR: at run_dealer(): accept(): Too many open files in system
2022/11/18 09:08:29 wazuh-db: ERROR: at run_dealer(): accept(): Too many open files in system
2022/11/18 09:08:29 wazuh-db: ERROR: at run_dealer(): accept(): Too many open files in system
2022/11/18 09:08:29 wazuh-db: ERROR: at run_dealer(): accept(): Too many open files in system
2022/11/18 09:08:29 wazuh-db: ERROR: at run_dealer(): accept(): Too many open files in system
2022/11/18 09:08:29 wazuh-db: ERROR: at run_dealer(): accept(): Too many open files in system
2022/11/18 09:08:29 wazuh-db: ERROR: at run_dealer(): accept(): Too many open files in system
2022/11/18 09:08:29 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'.
```

This log is reported due to the limit opened descriptors reached in the manager during the Footprint test. So this behavior is expected and it seems to work fine.

The reported error is a collateral effect of the test. Analysisd and Wazuh DB do not have available descriptors, so when calling this [function](https://github.com/wazuh/wazuh/blob/0824af89e8a448866197751e867c8b3ad980dd0b/src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c#L2757), performing the agents scan, when a query is run, the error is thrown.

**Comment by vikman90** [comment]
Fixed by [15467](https://github.com/wazuh/wazuh/pull/15467).
