### ISSUE TITLE
Linux agent cannot stablish IPv6 link-local connection with Wazuh Manager

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#15481]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.4 | Wazuh component | Agent | Any | Linux |

# Description

During #15407 validation, it was found that it was not possible to connect a Linux agent to a Manager using IPv6 link-local addresses.

As far as we have checked, this is currently working for global IPv6 addresses, but there're scenarios where Managers do not have a global IPv6, leading to an incomplete implementation of IPv6 connection.

# Steps to reproduce
## Preconditions
- Wazuh Manager from branch 4.4
- Wazuh Manager with IPv6 in both auth and remote blocks. See #11268
- Wazuh Agent from branch 4.4 running on GNU/Linux distro
- Wazuh Agent has the manager's IPv6 as `server_ip` on ossec.conf
- Both agent and manager in the same network and with IPv6 link-local addresses (automatically assigned)

## Expected result
- Agent is able to register and send information to the manager

## Actual result
-  Agent is not able to register into the manager, showing the next log
```
2022/11/17 11:51:29 wazuh-agentd: ERROR: (1208): Unable to connect to enrollment service at '[FE80:0000:0000:0000:0A00:27FF:FE89:5D9D]:1515'
```

**Comment by Nicogp** [comment]
To use `link-local` interfaces, `API` sockets must be explicitly provided with the interface through which to connect, this data is provided through the `sin6_scope_id` field of the `struct sockaddr_in6` structure, without this information, when the agent tries to establish a connection, the operating system cannot assign an interface, so the connection fails.

### Proposal
To mitigate the problem, the user must provide the name of the interface over which the connection should be established. To do this, we propose to add a new tag to the configuration, for example:  `<interface>eth1</interface>`.

**`<interface>:`** Name of the interface through which the `IPv6` connection must be established. If an `IPv4` is configured and an interface is indicated, it will not be taken into account when making the connection. The name can be obtained, for example, through the `ifconfig `command:
![image](https://user-images.githubusercontent.com/13004400/205643781-2c296e36-7091-4f16-b9cc-03e3e498802b.png)

#### Components involved in the changes
This new tag should be added to:

- the configuration of the <server> block of the <client> section

```
    <client>
     <server>
       <address>fe80::f827:ee49:cf2f:e5d4</address>
       <interface>eth1</interface>
       ……..
     </server>
     ……..
    </client>
```

- the <enrollment> section of the <client> block
```

     <client>
       <enrollment>
         <enabled>yes</enabled>
         <manager_address>fe80::f827:ee49:cf2f:e5d4</manager_address>
         <interface>eth1</interface>
         ......
       </enrollment>
       ......
     </client>
```

- also, the `agent-auth` tool must be allowed to accept the interface indication as a parameter, for example: `-n <network-interface>` (“i” and “I” are already in use)
`
     agent-auth -m fe80::f827:ee49:cf2f:e5d4 -n eth1`

**Comment by cborla** [comment]
## Update description

Because in windows it is difficult to get the name of the interface that uses the `if_nametoindex` function, the new proposal is use the index of the interface, to maintain a common configuration in all operating systems.
The new interface index label will looks as :  `<interface_index>`

## Configuration

- the configuration of the `<server>` block of the `<client>` section

```
    <client>
     <server>
       <address>fe80::f827:ee49:cf2f:e5d4</address>
       <interface_index>7</interface_index>
       …
     </server>
     ….
    </client>
```

- the `<enrollment>` section of the `<client>` block
```

     <client>
       <enrollment>
         <enabled>yes</enabled>
         <manager_address>fe80::f827:ee49:cf2f:e5d4</manager_address>
         <interface_index>4</interface_index>
         ...
       </enrollment>
       ...
     </client>
```

- also, the `agent-auth` tool must be allowed to accept the interface indication as a parameter, for example: `-n <network-interface>` (“i” and “I” are already in use)
`
     agent-auth -m fe80::f827:ee49:cf2f:e5d4 -n 5`
     
## How to find the interface index

### Unix OS
Command: `ip add`
The interface index is the number situate before interface name.
for example the index `2` is from `2: enp0s3: <BROADCAST....`
![image](https://user-images.githubusercontent.com/41765669/208089639-438df857-cfa5-440d-b314-befe6068729d.png)

### Windows OS
Command: `ipconfig`
The interface index is the number situate at the end of the ip, after `%` symbol.
for example the index `3` is from `fe80::e02a:e858:7b02:3529%3`
![image](https://user-images.githubusercontent.com/41765669/208090050-e9b625cd-551e-4377-8197-fb0fa676ef3f.png)

### Mac OS
Command: `ifconfig`
The interface index is the number situate in `secured scopeid` .
for example the index `6` is from `secured scopeid 0x6`
![image](https://user-images.githubusercontent.com/41765669/208090540-fe1a07dd-bc6c-4cf2-94ca-8161185fb8f6.png)
