### ISSUE TITLE
The Manager keeps the last IP configured in the agent in the global database

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#15491]
|Wazuh version|Component|
|---|---|
| 4.3.10 | Wazuh Agent |

## Description

The Manager keeps the last IP configured in the agent even if an IP address is configured in the network interface. This occurs when no gateway is configured in any interface. The stored IP is the one that existed when the gateway was configured. The cases where this behavior occurs are the following:

- Interface with no gateway and IPv4 address configured
- Interface with no gateway and IPv6 address configured
- Interface with no gateway and both types of IP addresses

## Steps to reproduce

<details><summary>Interface with no gateway and IPv4 address configured</summary>

<br>

1. Configure the network interface in the Agent
```
[root@3611-centos vagrant]# ip a show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:4d:77:d3 brd ff:ff:ff:ff:ff:ff
    inet 172.17.1.10/24 brd 172.17.1.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever

[root@3611-centos vagrant]# ip r | grep default
```
2. Restart the agent
```
# systemctl restart wazuh-agent.service
```
3. Check the `global.db` database in the Manager
```
sqlite> select ip from agent where id=9;
10.0.2.15
```
4. Check the keepalive message in the Agent
```
2022/11/25 00:52:22 wazuh-agentd[28346] notify.c:204 at run_notify(): DEBUG: Sending keep alive: #!-Linux |3611-centos |3.10.0-1127.el7.x86_64 |#1 SMP Tue Mar 31 23:36:51 UTC 2020 |x86_64 [CentOS Linux|centos: 7.8] - Wazuh v4.4.0 / ab73af41699f13fdd81903b5f23d8d00
2022/11/25 00:52:22 wazuh-agentd[28346] receiver.c:97 at receive_msg(): DEBUG: Received message: '#!-agent ack '
```
5. Check the dashboard
![image](https://user-images.githubusercontent.com/39094716/203879720-9ced8582-3484-4083-b0b3-a27c47010d4f.png)

> **Conclusion**: The IP stored in the DB is the previous one. Even though I configured the same IP, it is not present in the Keep-Alive message and the database keeps the old IP.

</details>

**Comment by Damian-Mangold** [comment]
The behavior is expected and coherent according to the implementation, that is to say, if the agent cannot send an IP address, it will not update it and it will keep the previous one.

The [exact point](https://github.com/wazuh/wazuh/blob/master/src/wazuh_db/wdb_global.c#L168) where this decision is made is when the agent information is requested ([here](https://github.com/wazuh/wazuh/blob/master/src/remoted/manager.c#L517) -> [here](https://github.com/wazuh/wazuh/blob/master/src/wazuh_db/helpers/wdb_global_helpers.c#L249)). If the agent could not send the IP address, the query [WDB_STMT_GLOBAL_UPDATE_AGENT_VERSION](https://github.com/wazuh/wazuh/blob/master/src/wazuh_db/wdb.c#L171) is used, otherwise, [WDB_STMT_GLOBAL_UPDATE_AGENT_VERSION_IP](https://github.com/wazuh/wazuh/blob/master/src/wazuh_db/wdb.c#L172) is used. It can be seen that one of them explicitly contains the IP information while the other one does not.

In case this behavior is not considered correct, a feature request should be made as the current behavior cannot be considered a bug.
