### ISSUE TITLE
Clone of wazuh agent

### ISSUE THREAD

**Issue by mathiaslegrand1** [wazuh/wazuh#15565]
Hi,

I would like to be able to clone a VM with Wazuh installed and configured on it. During my tests I notice that the Wazuh agent of the two servers is the same. I would like to be able to have a different agent for each cloned server.

Is it possible ?

Regards,
Mathias

**Comment by vikman90** [comment]
Hi @mathiaslegrand1,

This issue is related to #10172. The agent (and its clones) will try to connect with the same identification each time it starts unless multiple connection attempts fail (either server unavailable or key invalid).

The agent needs an ID (located in _/var/ossec/etc/client.keys_). If that file is empty at the agent's start, or if the key becomes invalid, the agent will request a new one.

As of v4.4.0 (which implements the fix to #10172), the clones will be rejected to connect if the source VM has the agent connected to the manager. So, the clones will renew their keys and get new IDs, without you having to do anything. Until then, I suggest you clear or delete _/var/ossec/etc/client.keys_ before copying the VM or just after running the new VMs. Another workaround would be manually running `/var/ossec/bin/agent-auth` in the new VMs.

Hope that helps.
Best regards.

**Comment by mathiaslegrand1** [comment]
Hi !

Thank you for the answer.

Under Linux it works. Can you tell me where the file is located on a Windows Server?

Regards,
Mathias

**Comment by vikman90** [comment]
Hi @mathiaslegrand1,

The file is located at _C:\Program Files (x86)\ossec-agent\client.keys_.

Best.

**Comment by mathiaslegrand1** [comment]
Hi @vikman90

I test in the week. I'll come back to you to confirm that it works properly under Windows.

**Comment by mathiaslegrand1** [comment]
Hello, sorry I couldn’t answer earlier. On Windows, everything works.
