### ISSUE TITLE
Timeout when upgrade fails via WPK from 3.x

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#15587]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.6 | WPK Upgrade | Manager/Agent | Packages | All |

## Description

An error was thrown while upgrading a Wazuh agent from `3.13.6` to `4.4.0` expecting a failure with a custom WPK. This is the source issue: https://github.com/wazuh/wazuh/issues/15529

- **Manager side:** During the test of the upgrade WPK failure, we see that the script hangs after finishing the whole process, until a few minutes later, it jumps a timeout.
- **Agent side:** Everything seems to have gone correctly, the upgrade fails, the backup runs without problems and the agent restarts as expected.

It seems that it is a problem in the sending of the upgrade result from the agent to the manager, which is waiting indefinitely until the timeout occurs. But the process in the agent seems to be carried out correctly.

## Steps to reproduce the error

- In the Wazuh manager:
  1. Upgrade the agent via WPK: `/var/ossec/bin/agent_upgrade -a xyz -f /tmp/myagent.wpk`

## Current result

<details><summary>Logs in: <code>upgrade.log</code></summary>

```
2022/12/01 15:53:38 - Generating Backup.
tar: ./var/ossec/queue/alerts/execq: socket ignored
tar: ./var/ossec/queue/alerts/cfgaq: socket ignored
tar: ./var/ossec/queue/ossec/com: socket ignored
tar: ./var/ossec/queue/ossec/queue: socket ignored
tar: ./var/ossec/queue/ossec/syscheck: socket ignored
tar: ./var/ossec/queue/ossec/logcollector: socket ignored
tar: ./var/ossec/queue/ossec/control: socket ignored
tar: ./var/ossec/queue/ossec/wmodules: socket ignored
2022/12/01 15:53:39 - Upgrade started.

 Wazuh v4.4.0 (Rev. 40401) Installation Script - https://www.wazuh.com

 You are about to start the installation process of Wazuh.
 You must have a C compiler pre-installed in your system.

  - System: Linux amazonlinux 4.14.198-152.320.amzn2.x86_64 (amzn 2.0)
  - User: root
  - Host: amazonlinux


  -- Press ENTER to continue or Ctrl-C to abort. --

 - You already have Wazuh installed. Do you want to update it? (y/n): 
    - Installation will be made at  /var/ossec .

4- Installing the system

DIR="/var/ossec"
 - Running the Makefile

Stopping Wazuh...
Wait for success...
success
Removing old SCA policies...
Installing SCA policies...


Wait for success...
success
Starting Wazuh...

 - Configuration finished properly.

 - To start Wazuh:
      /var/ossec/bin/wazuh-control start

 - To stop Wazuh:
      /var/ossec/bin/wazuh-control stop

 - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


   Thanks for using Wazuh.
   Please don't hesitate to contact us if you need help or find
   any bugs.

   Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

   More information can be found at:
          - http://www.wazuh.com

    ---  Press ENTER to finish (maybe more information below). ---

 - Update completed.

2022/12/01 15:53:49 - Installation result = 1
2022/12/01 15:53:50 - Waiting connection... Status = connected. Remaining attempts: 29.
2022/12/01 15:53:50 - Upgrade failed. Restoring...
Killing wazuh-modulesd... 
Killing wazuh-logcollector... 
Killing wazuh-syscheckd... 
Killing wazuh-agentd... 
Killing wazuh-execd... 
Wazuh v4.4.0 Stopped
2022/12/01 15:53:51 - Deleting upgrade files...
2022/12/01 15:53:51 - Restoring ossec group.
2022/12/01 15:53:51 - Restoring ossec user.
2022/12/01 15:53:51 - Restoring backup....
2022/12/01 15:53:56 - Wazuh SELinux module installation skipped (SELinux is disabled).
Starting Wazuh v3.13.6...
Started ossec-execd...
Started ossec-agentd...
Started ossec-syscheckd...
Started ossec-logcollector...
Started wazuh-modulesd...
Completed.
```

</details>

Screenshot from manager side

![image](https://user-images.githubusercontent.com/27935340/205629812-44b06419-d4f0-41b2-80e1-676a55313784.png)
(The process has to be killed to resume control of the terminal.)

## Expected result

The upgrade procedure should return once the agent is completed the rollback. However, no signal is received from the agent so the script gets stuck.

**Comment by chemamartinez** [comment]
Hi team,

After further investigation we have determined the following:
- This issue also happens in previous versions of Wazuh. In particular we tested with a manager v4.3.0, upgrading an agent from v3.13.6 to v4.3.0 with the same result. We though that this issue was a regression since it is not reported in the [WPK upgrade testing for v4.3.0](https://github.com/wazuh/wazuh/issues/12820), but is not the case.
- The problem appears when the new [upgrade module](https://github.com/wazuh/wazuh/issues/5387) and [task manager](https://github.com/wazuh/wazuh/issues/5386) were introduced in v4.1.0. A new communication protocol was also introduced to handle the upgrade between manager and agent. That protocol introduces a new message format to request the upgrade result once the upgrade has been launched, but this new format is not compatible with older agents, so when a rollback occurs, the old agent thas is restored is not able to send the upgrade result to the manager.
- The fix should be applied in the task manager module, we should look for a way to send the upgrade result request in both formats. The new one that works when the upgrade is successfully, and also the old format for those cases that the agent was restored to a 3.x version.
