### ISSUE TITLE
Wazuh : Random agents got disconnected with Managers

### ISSUE THREAD

**Issue by skhanum** [wazuh/wazuh#15644]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.9 | Wazuh agent | Manager | Sources | Ubuntu 18.04 |

Hello Team,

We have been facing issues every now and then where the Wazuh Agents get disconnected with Wazuh Managers. And in order to recover, we end up logging into hundreds of endpoint machines and restarting the Wazuh Agents

More details: We have a 3 node cluster, with above 2500+ agents enrolled 
Wazuh agent version : 4.3.6

Below are some observations:
1) Wazuh Manager 1 and Wazuh Manager 2 has below errors in ossec.json

```
{"timestamp":"2022/12/02 09:29:27","tag":"wazuh-authd","level":"info","description":"Client timeout from 40.122.204.179"}
{"timestamp":"2022/12/02 09:29:28","tag":"wazuh-authd","level":"info","description":"New connection from 20.26.48.55"}
{"timestamp":"2022/12/02 09:29:29","tag":"wazuh-authd","level":"info","description":"Client timeout from 20.26.48.55"}
{"timestamp":"2022/12/02 09:29:30","tag":"wazuh-authd","level":"info","description":"New connection from 52.180.67.247"}
{"timestamp":"2022/12/02 09:29:31","tag":"wazuh-authd","level":"info","description":"Client timeout from 52.180.67.247"}
{"timestamp":"2022/12/02 09:29:32","tag":"wazuh-authd","level":"info","description":"New connection from 20.31.214.55"}
{"timestamp":"2022/12/02 09:29:33","tag":"wazuh-authd","level":"info","description":"Client timeout from 20.31.214.55"}
{"timestamp":"2022/12/02 09:29:35","tag":"wazuh-authd","level":"info","description":"New connection from 20.72.108.198"}
{"timestamp":"2022/12/02 09:29:36","tag":"wazuh-authd","level":"info","description":"Client timeout from 20.72.108.198"}
{"timestamp":"2022/12/02 09:29:37","tag":"wazuh-authd","level":"info","description":"New connection from 40.120.50.94"}
{"timestamp":"2022/12/02 09:29:38","tag":"wazuh-authd","level":"info","description":"Client timeout from 40.120.50.94"}
{"timestamp":"2022/12/02 09:29:39","tag":"wazuh-authd","level":"info","description":"New connection from 20.205.241.73"}
{"timestamp":"2022/12/02 09:29:40","tag":"wazuh-authd","level":"info","description":"Client timeout from 20.205.241.73"}
{"timestamp":"2022/12/02 09:29:41","tag":"wazuh-authd","level":"info","description":"New connection from 40.74.177.113"}
{"timestamp":"2022/12/02 09:29:42","tag":"wazuh-authd","level":"info","description":"Client timeout from 40.74.177.113"}
{"timestamp":"2022/12/02 09:29:44","tag":"wazuh-authd","level":"info","description":"New connection from 20.27.178.114"}
{"timestamp":"2022/12/02 09:29:45","tag":"wazuh-authd","level":"info","description":"Client timeout from 20.27.178.114"}
{"timestamp":"2022/12/02 09:29:46","tag":"wazuh-authd","level":"info","description":"New connection from 40.119.6.104"}
{"timestamp":"2022/12/02 09:29:47","tag":"wazuh-authd","level":"info","description":"Client timeout from 40.119.6.104"}
{"timestamp":"2022/12/02 09:29:48","tag":"wazuh-authd","level":"info","description":"New connection from 20.44.227.89"}
{"timestamp":"2022/12/02 09:29:49","tag":"wazuh-authd","level":"info","description":"Client timeout from 20.44.227.89"}
{"timestamp":"2022/12/02 09:29:50","tag":"wazuh-authd","level":"info","description":"New connection from 20.210.57.248"}
{"timestamp":"2022/12/02 09:29:51","tag":"wazuh-authd","level":"info","description":"Client timeout from 20.210.57.248"}
{"timestamp":"2022/12/02 09:29:53","tag":"wazuh-authd","level":"info","description":"New connection from 51.104.172.171"}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"info","description":"Client timeout from 51.104.172.171"}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
{"timestamp":"2022/12/02 09:29:54","tag":"wazuh-authd","level":"error","description":"Too many connections. Rejecting."}
```

Same logs were seen on Wauzh Manager 2 as well due to which 50% of total enrolled agents went to disconnected state

On the agent side 

```
{"timestamp":"2022/12/02 07:44:46","tag":"wazuh-agentd","level":"info","description":"Requesting a key from server: monitor.horizon.vmware.com/20.230.232.150"}                                                      
{"timestamp":"2022/12/02 07:44:47","tag":"wazuh-agentd","level":"info","description":"Verifying manager's certificate"}                                                                                              
{"timestamp":"2022/12/02 07:44:47","tag":"wazuh-agentd","level":"error","description":"Unable to verify server certificate"}                                                                                         
{"timestamp":"2022/12/02 07:44:57","tag":"wazuh-agentd","level":"warning","description":"(4101): Waiting for server reply (not started). Tried: 'monitor.horizon.vmware.com/20.230.232.150'."}                       
{"timestamp":"2022/12/02 07:44:57","tag":"wazuh-agentd","level":"warning","description":"Unable to connect to any server."}                                                                                          
{"timestamp":"2022/12/02 07:44:57","tag":"wazuh-agentd","level":"info","description":"Closing connection to server (monitor.horizon.vmware.com/20.230.232.150:1514/udp)."}                                           
{"timestamp":"2022/12/02 07:44:57","tag":"wazuh-agentd","level":"info","description":"Trying to connect to server (Manager_IP:1514/tcp)."}                                                                       
{"timestamp":"2022/12/02 07:46:07","tag":"wazuh-agentd","level":"info","description":"Closing connection to server (Manager_IP:1514/tcp)."}                                                                      
{"timestamp":"2022/12/02 07:46:07","tag":"wazuh-agentd","level":"info","description":"Trying to connect to server (Manager_IP:1514/tcp)."}                                                                       
{"timestamp":"2022/12/02 07:46:22","tag":"wazuh-agentd","level":"info","description":"(4102): Connected to the server (Manager_IP:1514/tcp)."}                                                                   
{"timestamp":"2022/12/02 07:46:22","tag":"wazuh-agentd","level":"info","description":"Server responded. Releasing lock."}                                                                                            
{"timestamp":"2022/12/02 07:46:24","tag":"wazuh-syscheckd","level":"info","description":"Agent is now online. Process unlocked, continuing..."}                                                                      
{"timestamp":"2022/12/02 07:46:24","tag":"wazuh-logcollector","level":"info","description":"Agent is now online. Process unlocked, continuing..."}                                                                   
{"timestamp":"2022/12/02 07:47:23","tag":"wazuh-agentd","level":"warning","description":"Server unavailable. Setting lock."}  
```    

The agents remained disconnected unless Wazuh Agent was restarted

Requesting possible cause and guidance to avoid this in future

**Comment by skhanum** [comment]
In order to mitigate the issue
1) Wazuh managers' services were restarted on Wazuh Manager 1 and Wazuh Manager 2
2) The Wazuh agent's services on endpoints are being restarted

**Comment by pereyra-m** [comment]
Hello @skhanum !

As far as I can see, this seems a connectivity issue. It shouldn't be required to restart your agents frequently. 
When the agents are unable to connect with a manager for a long time, we can find messages like this one

```
"Server unavailable. Setting lock."
```

Then, by default, the agent tries to get a new key just in case it isn't registered ([auto-enrollment](https://documentation.wazuh.com/4.3/user-manual/agent-enrollment/via-agent-configuration/index.html) feature).
There are many agents requesting keys at the same time, so we see that `wazuh-authd` is unable to manage all these requests

```
"Too many connections. Rejecting."
```

There also seems to be a CA issue, because when these requests are able to be processed the certificate verification fails

```
"Requesting a key from server: monitor.horizon.vmware.com/20.230.232.150"
"Verifying manager's certificate"
"Unable to verify server certificate"
```

But the CA is only used during the registration, not during normal communication.
The agents only are getting a successful connection for a short period of time

```
{"timestamp":"2022/12/02 07:46:24","tag":"wazuh-logcollector","level":"info","description":"Agent is now online. Process unlocked, continuing..."}                                                                   
{"timestamp":"2022/12/02 07:47:23","tag":"wazuh-agentd","level":"warning","description":"Server unavailable. Setting lock."}  
``` 

Can you please do the following?
- Share the full `ossec.conf` and `ossec.log` files from both the manager and agent?
- Comment on some details of your environment and network configuration: are the agents behind a proxy, firewall, etc.? 
- Verify the communication from the agents to the managers 

```
nc -zv <MANAGER_IP> 1515 1514
ping <MANAGER_IP>
```

Regards.

**Comment by pereyra-m** [comment]
Hello again @skhanum!

Glad to help.

Thank you for the logs provided. Could you attach the configuration file `ossec.conf` of both the agent and manager?

> There is no CA issue as after restarting the agents, the issue has been mitigated

Just to be clear: when you restart the agent, it tries to connect with the configured manager through the load balancer. In this process, the CA isn't required. I can see from the logs that it remains connected for some time, but suddenly it loses the connection. Then it tries to register again (even when it's already registered, the agent requests a new key just in case it has an invalid one) and then we see the CA related errors.
In the manager
```
"wazuh-authd","level":"error","description":"SSL Error (0)"
```
And in the agent
```
"tag":"wazuh-agentd","level":"info","description":"Verifying manager's certificate"
"tag":"wazuh-agentd","level":"error","description":"Unable to verify server certificate"
```

That's why I recommended checking the certificates. But this isn't causing the disconnection issue.

I think that maybe the LB is causing the connectivity issue and disconnecting the agents. Could you connect some agents directly to a cluster's node so we can discard that possibility?
There is also interesting information related in this blogpost about an LB configuration: [NGINX Load balancer for a Wazuh cluster](https://wazuh.com/blog/nginx-load-balancer-in-a-wazuh-cluster/)

Regards.

**Comment by skhanum** [comment]
Thanks @pereyra-m 

Please let me know if you need specific info in ossec.conf for agents and managers like auth/enrollment so that I can hide sensitive details and share them here

We have azure LB sitting in front of the Manager cluster and yes, the enrollment goes via LB>Master node
Unfortunately, we cannot bypass LB and directly connect to Master node as per the way it is designed
But the issue here is with Random agents and not all agents get disconnected, and by restarting the agent services, everything is back to normal so I do not think its a certificate issue yet

Please let me know about the ossec.conf part so that I can attach the requested details

**Comment by pereyra-m** [comment]
Hi @skhanum !

> Please let me know if you need specific info in ossec.conf

It would be useful to have the full `ossec.conf` file of both the manager and agent. Please, remove any sensitive data. 

> Unfortunately, we cannot bypass LB and directly connect to Master node

It would have been a valuable test so we can be sure if the LB is missing random packets. Can you share the LB configuration?
I am not aware of any current Wazuh bug that causes a random disconnection until the service is restarted but it might happen, so we need all the information you can provide. 

>  I do not think its a certificate issue yet

I know that we don't have a certificate issue with these disconnected agents because they are already registered. I just mention it because it could be a problem for registering new agents in the future. 

Also, please share the **full** `ossec.log` file for one of your Wazuh managers. You've just shared a section in [this](https://github.com/wazuh/wazuh/issues/15644#issuecomment-1359527367) message.

Regards.

**Comment by skhanum** [comment]
Thanks @pereyra-m 

I am waiting for the approval from Security team if the logs and conf files can be shared.
I will share them as soon I hear from them

Thanks,
Saniya

**Comment by skhanum** [comment]
Hello @pereyra-m 
We have the log format in json, I do not see much difference between plain and json, I will share the ossec.json file at the time of the issue reported shortly
