### ISSUE TITLE
`osquery` wodle fails if `run_daemon` is enabled

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#15654]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.10 | osquery  wodle | Manager/Agent | Packages/Sources | CentOS 7 |

## Description

We have noticed that when using the `osquery` wodle if the `run_daemon` option is enabled the following errors appear in the `ossec.log `file of the agent:
```
2022/12/12 11:52:15 wazuh-modulesd:osquery: INFO: Following osquery results file '/var/log/osquery/osqueryd.results.log'.
2022/12/12 11:52:15 wazuh-modulesd:osquery: WARNING: E1212 11:52:15.300118  6585 init.cpp:506] osqueryd Pidfile check failed: Pidfile::Error::Busy
2022/12/12 11:52:15 wazuh-modulesd:osquery: ERROR: Osquery exited with code 1. Closing module.
2022/12/12 11:52:16 wazuh-modulesd:osquery: INFO: Closing module.
```

This error appears because `osquery` stores the `pidfile` in a different location: `/var/run/osqueryd.pidfile`. If we change the location of the pidfile by editing the service file, `/usr/lib/systemd/system/osqueryd.service`, by adding the following flag `--pidfile=/var/osquery/osqueryd.pidfile` we can force `osquery` to store the `pidfile` in the location expected by Wazuh.

However, even after this we obtain this error in the `ossec.log`:
```
2022/12/12 10:39:39 wazuh-modulesd:osquery: INFO: Following osquery results file '/var/log/osquery/osqueryd.results.log'.
2022/12/12 10:39:44 wazuh-modulesd:osquery: WARNING: E1212 10:39:44.549837 26193 shutdown.cpp:79] IO error: While lock file: /var/osquery/osquery.db/LOCK: Resource temporarily unavailable
2022/12/12 10:39:45 wazuh-modulesd:osquery: WARNING: E1212 10:39:45.455935 26192 shutdown.cpp:79] Worker returned exit status
2022/12/12 10:39:45 wazuh-modulesd:osquery: ERROR: Osquery exited with code 78. Closing module.
```

## How to reproduce

1. Install and configure `osquery`.
2. Start `osquery`.
3. Install Wazuh agent.
4. Enable the `osquery wodle` and `run_daemon` .
5. Check logs.

**Comment by y0d4a** [comment]
hi, what happening with this? i have issue with starting osquery with wazuh...

**Comment by JoseMiguelGD** [comment]
We have realized that the WARNING you are receiving is due to a conflict between the main service and the run_daemon, as a subprocess.

The way to solve the problem would be to stop `osqueryd.service` manually, because from the code it can't be done, because the user may have the service activated for some specific reason, so we could not deliberately stop the service. We have been investigating various instances but so far we have not found anything related to it.

It makes them Incompatible because wazuh tries to launch osqueryd, but it is already active `osqueryd.service`, that's why it gives busy error, if you stop osquery.service, it doesn't give error when you set run_daemon to `yes` because osquery is not activated. These are the tests that we have recreated:

|OSQUERY|RUN_DAEMON|RESULT
|---|---|---|
|0|0|No WARNING(error busy), Moduled started  
|0|1|No WARNING(error busy), INFO: run_daemon disabled
|1|0|INFO: Module started, WARNING: Execute_Osquery OK
|1|1|osqueryd Pidfile check failed: Pidfile::Error::Busy

<br>

***

<br>

**0 - 0**
```vim
2023/04/27 13:49:21 wazuh-modulesd:osquery: INFO: Module started.
2023/04/27 13:49:21 wazuh-modulesd:osquery: INFO: run_daemon disabled, finding detached osquery process results.
2023/04/27 13:49:21 wazuh-modulesd:osquery: INFO: Following osquery results file '/var/log/osquery/osqueryd.results.log'.
```

<br>

**0 - 1**
```vim
2023/04/27 13:51:00 wazuh-modulesd:osquery: INFO: Module started.
2023/04/27 13:51:00 wazuh-modulesd:osquery: INFO: run_daemon disabled, finding detached osquery process results.
2023/04/27 13:51:00 wazuh-modulesd:osquery: INFO: Following osquery results file '/var/log/osquery/osqueryd.results.log'.
```

<br>

**1 - 0**
```vim
2023/04/27 13:52:39 wazuh-modulesd:osquery: INFO: Module started.
2023/04/27 13:52:39 wazuh-modulesd:osquery: INFO: Following osquery results file '/var/log/osquery/osqueryd.results.log'.
2023/04/27 13:52:39 wazuh-modulesd:osquery: WARNING: Execute_Osquery
2023/04/27 13:52:39 wazuh-modulesd:osquery: WARNING: osqueryd_path /opt/osquery/bin/osqueryd
2023/04/27 13:52:39 wazuh-modulesd:osquery: WARNING: config_path --config_path=/etc/osquery/osquery.conf
2023/04/27 13:52:39 wazuh-modulesd:osquery: WARNING: config_path 818462
2023/04/27 13:52:39 wazuh-modulesd:osquery: WARNING: buffer0 I0427 13:52:39.931416 818481 eventfactory.cpp:156] Event publisher not enabled: BPFEventPublisher: Publisher disabled via configuration
2023/04/27 13:52:39 wazuh-modulesd:osquery: WARNING: buffer1 I0427 13:52:39.931416 818481 eventfactory.cpp:156] Event publisher not enabled: BPFEventPublisher: Publisher disabled via configuration
2023/04/27 13:52:39 wazuh-modulesd:osquery: WARNING: buffer0 I0427 13:52:39.931490 818481 eventfactory.cpp:156] Event publisher not enabled: auditeventpublisher: Publisher disabled via configuration
2023/04/27 13:52:39 wazuh-modulesd:osquery: WARNING: buffer1 I0427 13:52:39.931490 818481 eventfactory.cpp:156] Event publisher not enabled: auditeventpublisher: Publisher disabled via configuration
2023/04/27 13:52:39 wazuh-modulesd:osquery: WARNING: buffer0 I0427 13:52:39.931500 818481 eventfactory.cpp:156] Event publisher not enabled: inotify: Publisher disabled via configuration
2023/04/27 13:52:39 wazuh-modulesd:osquery: WARNING: buffer1 I0427 13:52:39.931500 818481 eventfactory.cpp:156] Event publisher not enabled: inotify: Publisher disabled via configuration
2023/04/27 13:52:39 wazuh-modulesd:osquery: WARNING: buffer0 I0427 13:52:39.931509 818481 eventfactory.cpp:156] Event publisher not enabled: syslog: Publisher disabled via configuration
2023/04/27 13:52:39 wazuh-modulesd:osquery: WARNING: buffer1 I0427 13:52:39.931509 818481 eventfactory.cpp:156] Event publisher not enabled: syslog: Publisher disabled via configuration
```

<br>

**1 - 1**
```vim
2023/04/27 13:56:48 wazuh-modulesd:osquery: INFO: Module started.
2023/04/27 13:56:48 wazuh-modulesd:osquery: INFO: Following osquery results file '/var/log/osquery/osqueryd.results.log'.
2023/04/27 13:56:48 wazuh-modulesd:osquery: WARNING: Execute_Osquery
2023/04/27 13:56:48 wazuh-modulesd:osquery: WARNING: osqueryd_path /opt/osquery/bin/osqueryd
2023/04/27 13:56:48 wazuh-modulesd:osquery: WARNING: config_path --config_path=/etc/osquery/osquery.conf
2023/04/27 13:56:48 wazuh-modulesd:osquery: WARNING: config_path 824505
2023/04/27 13:56:48 wazuh-modulesd:osquery: WARNING: buffer0 E0427 13:56:48.336176 824505 init.cpp:520] osqueryd Pidfile check failed: Pidfile::Error::Busy
2023/04/27 13:56:48 wazuh-modulesd:osquery: WARNING: buffer1 E0427 13:56:48.336176 824505 init.cpp:520] osqueryd Pidfile check failed: Pidfile::Error::Busy
2023/04/27 13:56:48 wazuh-modulesd:osquery: WARNING: E0427 13:56:48.336176 824505 init.cpp:520] osqueryd Pidfile check failed: Pidfile::Error::Busy
2023/04/27 13:56:48 wazuh-modulesd:osquery: ERROR: Osquery exited with code 1. Closing module.
```

**Comment by laurathaqi968** [comment]
Dear @Smjert 

Please find the details as following on the Pidfile check failed: Pidfile: :Error::Busy 

wazuh plugin version: 4.x-2023.09.12
wazuh agent version: 4.5.1-1
wazuh app for Kibana manager version:  7.17.9 
osquery version: 5.9.1 

At the beggining, this error was eliminated via the above mentioned approach: 1. stop the osquery, 2.start the wazuh-agent, 3.start the osquery. However, after restart of the computer, the error is back. It gets fixed with the mentioned approach, but I can't keep doing this manually to every computer, after every restart. 

Can you please support in this issue. 

Thank you,
Laura
