### ISSUE TITLE
Wazuh Manager not reachable if specified as FQDN instead IP only by agent deployed under linux 

### ISSUE THREAD

**Issue by valmivi** [wazuh/wazuh#15684]
Wazuh Agent v4.3.1 Linux: CentOS 7,8,9 - Ubuntu 20,22 - Debian 9

if manager address in /var/ossec/etc/ossec.conf is specified as FQDN (manager.domain.com)
- the agent status appear as "never connected"
- the status in agent log is "pending"
- in agent log appear wazuh-agentd: ERROR: (1216): Unable to connect to 'manager.domaincom:1514/tcp': 'Network is unreachable'.

if the FQDN will be replaced with IP the problem disappear.

Under Windows Agent there is no issue with FQDN

**Comment by valmivi** [comment]
Just to clarify: the Linux hosts are correctly able to solve the FQDN "manager.domain.com" using nslookup but the agent is not.

**Comment by pereyra-m** [comment]
Hello @valmivi !

This issue was already reported here https://github.com/wazuh/wazuh/issues/13583. As you can see in this comment https://github.com/wazuh/wazuh/issues/13652#issuecomment-1143228005, pull requests https://github.com/wazuh/wazuh/pull/13644 and https://github.com/wazuh/wazuh/pull/13642 solved it for Wazuh **v.4.3.3** and above.

The thing is that deploying an agent with enrollment variables generated a duplication of the `<client>` configuration block in `ossec.conf` making the agent unable to resolve FQDN.

It is solved in recent versions if you register a new agent, but **there is a workaround** for your already deployed agent (see also https://github.com/wazuh/wazuh/issues/13583#issuecomment-1141994629): simply move the `<enrollment>` section from the second  `<client>` block to the first `<client>` block and erase the second one in `ossec.conf`. This should allow the agent to properly resolve the address.

Regards.
