### ISSUE TITLE
Bug: syscollector detects wrong version of docker

### ISSUE THREAD

**Issue by fernandogont** [wazuh/wazuh#15743]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.8 | syscollector | Agent | Packages | Mac OS 13.1 |

Recently, I found a problem where vulnerability-detector was incorrectly reporting a vulnerability in docker for a Mac OS workstation, even when the workstation was running the latest version of docker. After some analysis, it seems that at least part of the problem resides in syscollector incorrectly detecting the version of docker currently in use.

**Details**

A docker installation may have multiple components, for example:

```
% docker version
Client:
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:18 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.15.0 (93002)
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:41 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

In this case, *Docker Desktop* is 4.15.0, while the *docker engine* is 20.10.21. However, syscollector will detect this deployment as having "docker version 4.15.0"

Thus, vulnerabilities such as:

- CVE-2021-21285 (condition: Package less than 19.03.15)
- CVE-2019-13509 (condition: Package less than 18.09.8)
- CVE-2019-16884 (condition: Package less or equal than 19.03.2)
- CVE-2019-5736 (condition: Package less than 18.09.2)
- CVE-2019-13139 (condition: Package less than 18.09.4)

which clearly refer to the docker engine, will be perceived by vulnerability-detector as affecting the aforementioned deployment -- because vulnerability-detector will assume that the docker package detected by syscollector refers to the "docker engine", when it in fact refers to the "Docker Desktop".

Proposed solution:
In the aforementioned deployment (Docker Desktop deployment on a Mac OS 13.1, using the standard Docker Desktop package for Mac OS), syscollector should separately detect all the different components of Docker Desktop -- in particular, "Docker Desktop 4.15.0 (93002)" and "Docker Engine 20.10.21". This will hopefully help eliminate the incorrect vulnerability reports in Mac OS.

Thanks!

**Comment by Dwordcito** [comment]
@pereyra-m RCA please.

**Comment by jnasselle** [comment]
@pereyra-m this could be also related with https://github.com/wazuh/wazuh/pull/14100

**Comment by pereyra-m** [comment]
# Analysis

## Summary

The current information obtained by **syscollector** isn't enough or isn't accurate to allow the Vulnerability Detector module to differentiate between `Docker` and `Docker Desktop`. Also, macOS doesn't provide a security feed and the NVD isn't always an accurate source of information because it provides too large versions ranges for the vulnerabilities.

After a deep analysis, the proposed solution consists of two well-defined stages:
- **Stage 1**: in macOS, **syscollector** isn't making a recursive search in the bundled folder to look for more applications (`.app`). In the particular case of `Docker`, there is a `Docker Desktop` application with its own `.plist` file inside the `Docker` folder that contains the required information.
- **Stage 2**: after making **syscollector** more accurate for macOS bundles, many applications that weren't visible will be available in the agent's inventory. One of them will be `Docker Desktop`. But the Vulnerability Detector will have to create the correct CPE for this and also "ignore" the invalid package `Docker` with the range version of the `Desktop` application. This feature isn't available currently in the module and could be partially covered by a custom rule.

In conclusion:
 - New packages that weren't visible will be available in the inventory
 - The `Docker Desktop` application will be correctly scanned by Vulnerability Detector
 - The false positives **won't** be removed without a custom rule. It isn't possible to differentiate between a real `Docker` engine package with an old version (4.x for example) and a recent `Docker Desktop` if the `.plist` file doesn't have the required information for the name and the NVD can't define the exact version when that vulnerability was first introduced

## Details

### Current state

The installation of `Docker Desktop` is currently shown as `Docker` by the system

![docker_macOS](https://user-images.githubusercontent.com/65046601/212151759-b54af370-dbe6-425f-8363-8995ee4f429b.png)

This is the same information that we see in the agent's DB
![docker_agentDB_macOS](https://user-images.githubusercontent.com/65046601/212152383-6212669b-9c12-4785-bcc5-11458a9b6304.png)

And this will cause a false positive in vulnerability detector because of it's version and name. 
Here is an example with CVE https://nvd.nist.gov/vuln/detail/CVE-2019-13139
![docker_macOS_false_positive](https://user-images.githubusercontent.com/65046601/212152753-3eedb2b3-bf7b-4481-9a58-6c48b814f4b3.png)

The CPE in the NVD for this CVE is ` cpe:2.3:a:docker:docker:*:*:*:*:enterprise:*:*:*` **Up to (excluding)
18.09.4**.
But the `Docker Desktop` application should in fact match with a CPE similar to ` cpe:2.3:a:docker:desktop:*:*:*:*:windows:*:*:*` (it's just an example, ignore the `windows` section) in https://nvd.nist.gov/vuln/detail/CVE-2021-37841.

Consider that a wide range like **Up to (excluding) 18.09.4** isn't accurate because it isn't capable of telling when the vulnerability was first introduced. This is a defect of the NVD feed for this CPE.

In a vulnerability like https://nvd.nist.gov/vuln/detail/CVE-2019-13509 we can see that some CPEs do have a defined version
- `cpe:2.3:a:docker:docker:17.03.2:1:*:*:enterprise:*:*:*`
-  `cpe:2.3:a:docker:docker:*:*:*:*:enterprise:*:*:*` **From (including) 18.09.0 Up to (excluding)18.09.8**

But some CPE don't 
- `  cpe:2.3:a:docker:docker:*:*:*:*:community:*:*:*` **Up to (excluding)18.09.8**

### Stage 1

The first part of the proposed solution consists in adding a recursive search in each sub-folder found in a `.app` bundle. 
The `Docker` application has a `Info.plist` file located in `/Applications/Docker.app/Contents/Info.plist`
 with no information that helps to figure out we are talking about the `Desktop` version and not the `Engine` itself

<details>
<summary>
Info.plist of Docker
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>BuildMachineOSBuild</key>
    <string>22A400</string>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleDisplayName</key>
    <string>Docker</string>
    <key>CFBundleExecutable</key>
    <string>Docker</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundleIconName</key>
    <string>AppIcon</string>
    <key>CFBundleIdentifier</key>
    <string>com.docker.docker</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>Docker</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>4.15.0</string>
    <key>CFBundleSupportedPlatforms</key>
    <array>
      <string>MacOSX</string>
    </array>
    <key>CFBundleURLTypes</key>
    <array>
      <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLName</key>
        <string>docker-desktop</string>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>docker-desktop</string>
        </array>
      </dict>
    </array>
    <key>CFBundleVersion</key>
    <string>93002</string>
    <key>DTCompiler</key>
    <string>com.apple.compilers.llvm.clang.1_0</string>
    <key>DTPlatformBuild</key>
    <string>14B47b</string>
    <key>DTPlatformName</key>
    <string>macosx</string>
    <key>DTPlatformVersion</key>
    <string>13.0</string>
    <key>DTSDKBuild</key>
    <string>22A372</string>
    <key>DTSDKName</key>
    <string>macosx13.0</string>
    <key>DTXcode</key>
    <string>1410</string>
    <key>DTXcodeBuild</key>
    <string>14B47b</string>
    <key>GitCommit</key>
    <string>edb830d237baed81db424449290ec28577916262</string>
    <key>LSApplicationCategoryType</key>
    <string>public.app-category.developer-tools</string>
    <key>LSMinimumSystemVersion</key>
    <string>10.15</string>
    <key>LSMultipleInstancesProhibited</key>
    <false/>
    <key>LSUIElement</key>
    <true/>
    <key>NSHumanReadableCopyright</key>
    <string>Copyright © 2015-2022 Docker Inc.All Rights Reserved.</string>
    <key>NSMainNibFile</key>
    <string>MainMenu</string>
    <key>NSPrincipalClass</key>
    <string>DockerApplication</string>
    <key>NSUserNotificationAlertStyle</key>
    <string>alert</string>
    <key>SMPrivilegedExecutables</key>
    <dict>
      <key>com.docker.vmnetd</key>
      <string>identifier &#34;com.docker.vmnetd&#34; and anchor apple generic and certificate leaf[subject.CN] = &#34;Developer ID Application: Docker Inc (9BNSXJN65R)&#34;</string>
    </dict>
    <key>SUAllowsAutomaticUpdates</key>
    <true/>
    <key>SUAutomaticallyUpdate</key>
    <true/>
    <key>SUEnableAutomaticChecks</key>
    <false/>
    <key>SUEnableSystemProfiling</key>
    <false/>
    <key>SUHideAutomaticallyInstallUpdates</key>
    <true/>
    <key>SUHideLaterButton</key>
    <true/>
    <key>SUHideSkipButton</key>
    <true/>
    <key>SUPublicEDKey</key>
    <string>xPiMc+MatfYLz6ZfZPNpCsd9vnxDuIdnHAT7mw4A+jE=</string>
    <key>SUScheduledCheckInterval</key>
    <integer>86400</integer>
    <key>SUShowReleaseNotes</key>
    <false/>
    <key>VmnetdVersion</key>
    <string>67</string>
    <key>channelID</key>
    <string>main</string>
  </dict>
</plist>%

```

</details>

Now, inside that folder, we can find another `.app` that contains another `Info.plist` with the right name in `/Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/Info.plist`


<details>
<summary>
Info.plist of Docker Desktop
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>CFBundleDisplayName</key>
        <string>Docker Desktop</string>
        <key>CFBundleExecutable</key>
        <string>Docker Desktop</string>
        <key>CFBundleIconFile</key>
        <string>icon.icns</string>
        <key>CFBundleIdentifier</key>
        <string>com.electron.dockerdesktop</string>
        <key>CFBundleInfoDictionaryVersion</key>
        <string>6.0</string>
        <key>CFBundleName</key>
        <string>Docker Desktop</string>
        <key>CFBundlePackageType</key>
        <string>APPL</string>
        <key>CFBundleShortVersionString</key>
        <string>4.15.0</string>
        <key>CFBundleVersion</key>
        <string>4.15.0.9</string>
        <key>DTCompiler</key>
        <string>com.apple.compilers.llvm.clang.1_0</string>
        <key>DTSDKBuild</key>
        <string>12.3</string>
        <key>DTSDKName</key>
        <string>macosx12.3</string>
        <key>DTXcode</key>
        <string>1331</string>
        <key>DTXcodeBuild</key>
        <string>13E500a</string>
        <key>ElectronAsarIntegrity</key>
        <dict>
            <key>Resources/app.asar</key>
            <dict>
                <key>algorithm</key>
                <string>SHA256</string>
                <key>hash</key>
                <string>a66e07fd1aef567d0da22673e803551a9283284979abe685324259e97c359602</string>
            </dict>
        </dict>
        <key>LSApplicationCategoryType</key>
        <string>public.app-category.developer-tools</string>
        <key>LSEnvironment</key>
        <dict>
            <key>MallocNanoZone</key>
            <string>0</string>
        </dict>
        <key>LSMinimumSystemVersion</key>
        <string>10.11.0</string>
        <key>NSAppTransportSecurity</key>
        <dict>
            <key>NSAllowsArbitraryLoads</key>
            <true/>
            <key>NSAllowsLocalNetworking</key>
            <true/>
            <key>NSExceptionDomains</key>
            <dict>
                <key>127.0.0.1</key>
                <dict>
                    <key>NSIncludesSubdomains</key>
                    <false/>
                    <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                    <true/>
                    <key>NSTemporaryExceptionAllowsInsecureHTTPSLoads</key>
                    <false/>
                    <key>NSTemporaryExceptionMinimumTLSVersion</key>
                    <string>1.0</string>
                    <key>NSTemporaryExceptionRequiresForwardSecrecy</key>
                    <false/>
                </dict>
                <key>localhost</key>
                <dict>
                    <key>NSIncludesSubdomains</key>
                    <false/>
                    <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                    <true/>
                    <key>NSTemporaryExceptionAllowsInsecureHTTPSLoads</key>
                    <false/>
                    <key>NSTemporaryExceptionMinimumTLSVersion</key>
                    <string>1.0</string>
                    <key>NSTemporaryExceptionRequiresForwardSecrecy</key>
                    <false/>
                </dict>
            </dict>
        </dict>
        <key>NSBluetoothAlwaysUsageDescription</key>
        <string>This app needs access to Bluetooth</string>
        <key>NSBluetoothPeripheralUsageDescription</key>
        <string>This app needs access to Bluetooth</string>
        <key>NSCameraUsageDescription</key>
        <string>This app needs access to the camera</string>
        <key>NSHighResolutionCapable</key>
        <true/>
        <key>NSHumanReadableCopyright</key>
        <string>Copyright © 2022 Docker Desktop</string>
        <key>NSMainNibFile</key>
        <string>MainMenu</string>
        <key>NSMicrophoneUsageDescription</key>
        <string>This app needs access to the microphone</string>
        <key>NSPrincipalClass</key>
        <string>AtomApplication</string>
        <key>NSQuitAlwaysKeepsWindows</key>
        <false/>
        <key>NSRequiresAquaSystemAppearance</key>
        <false/>
        <key>NSSupportsAutomaticGraphicsSwitching</key>
        <true/>
    </dict>
</plist>

```

</details>

This situation is common in macOS bundles. 
For example, the `AirDrop` application is found inside the `Finder.app`
![airdrop_macOS](https://user-images.githubusercontent.com/65046601/212157470-c90cf8cb-297d-4083-8552-aa7adfde8475.png)

But **syscollector** isn't obtaining these applications, only the root ones
![airdrop_not_found](https://user-images.githubusercontent.com/65046601/212157823-dab4fd01-612d-4296-9e97-6b19bcc9da6b.png)

The information can be obtained also with `system_profiler SPApplicationsDataType` to be compared with the **syscollector** results.

### Stage 2

Vulnerability detector should create the right CPE for this `Docker Desktop` application inside the root `Docker` app.
Here we have the example of how the package would look like in the DB

![macOS_docker_test](https://user-images.githubusercontent.com/65046601/212379898-c938ae9f-fab8-4292-b432-191c2d14a192.png)

And we can see that `electron` isn't appropriate and the package won't match the CPE  `cpe:2.3:a:docker:desktop`

### Notes

- This approach may cause repeated entries in the **syscollector** DB and that situation should be handled with caution. Consider the example of `iCloud`, the system is able to find the same `.app` in different folders

![macOS_icloud](https://user-images.githubusercontent.com/65046601/212439796-9fe13678-0cbd-4174-8250-3ed15355bf85.png)

- The subfolders should be selected carefully. For example, `Contents/MacOS` or `Contents/Applications` are good candidates, but `Contents/Frameworks` might generate too many entries

### Sources

- [Bundle Structures](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW19)

**Comment by pereyra-m** [comment]
Related issue:
- https://github.com/wazuh/wazuh/issues/15798

**Comment by Dwordcito** [comment]
#15798 

This issue will improve the power of syscollector since more folders are seen that were not monitored before.
