### ISSUE TITLE
Wazuh-db delete agent database incoherence

### ISSUE THREAD

**Issue by cristgl** [wazuh/wazuh#1598]
## Bug report

**OS**
_Ubuntu18_

**Wazuh version**
_3.7.0-3705_

**Install type**
_managet_

**Install method**
_packages_

Bug description
----------------
An agent database should be recreated after deleting it and sending a new scan. As this is not working, for recreating the agent database it is necessary to restart the manager, which creates it but not everytime, being necessary to reinstall the manager and register the agent to get this database.

**Comment by Skeptor** [comment]
Hi @cristgl 
After deleting the database of an agent I get it restored after the next scan.
It is solved, at least in the last dev packages afaik.
Regards.
Pablo

**Comment by Skeptor** [comment]
Hi @cristgl 
There are news about the issue:
The expected behavior when you delete the db of an agent is to keep receiving the scans, which is done cause the db is still opened, but not to recreate the file.
In case of the db file was deleted by error, the solution is to restart the manager, and the file will be created again.
Regards,
Pablo.
