### ISSUE TITLE
Rework `PUT /active-response` endpoint behavior

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#15990]
|Wazuh version|Component|
|---|---|
| 4.3.10 | Wazuh API |

## Description
The current `PUT /active-response` endpoint needs a rework, since it has mixed logic for current and legacy agents that does not follow a consistent behavior with custom commands:

https://github.com/wazuh/wazuh/blob/89530f11c9e592cd2e551432209b0080f08ff8e5/framework/wazuh/core/active_response.py#L132-L138

In addition, we need to investigate if the communication with the active-response socket could be bidirectional, in which case we need to adapt the code to parse and validate the response:

https://github.com/wazuh/wazuh/blob/89530f11c9e592cd2e551432209b0080f08ff8e5/framework/wazuh/core/wazuh_queue.py#L84-L162

Finally, a documentation update will be necessary after the changes to improve this endpoint behavior and expected responses understanding.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by RamosFe** [comment]
# Update

Reading documentation about the Legacy and Current logic of the endpoint `PUT active-response`.

**Comment by RamosFe** [comment]
# Update
## Bidirectional Sockets and the Active Response Thread
### How the Socket `queue/alerts/ar` is used

The socket `queue/alerts/ar` is used for sending a message containing the data of an `AR command`, as shown below:

https://github.com/wazuh/wazuh/blob/e958b3c818a25ad1405db11bd17032f8970e1881/framework/wazuh/active_response.py#L43-L51

Then this data is consumed by a thread parsing the message and sending it to their respective agent.

https://github.com/wazuh/wazuh/blob/e958b3c818a25ad1405db11bd17032f8970e1881/src/remoted/ar-forward.c#L20-L39C28

### Can this Socket be bidirectional?

Yes, this socket can be bidirectional, but some problems arise from this:

#### 1. How the AR Thread knows to which worker to send the agent response?
Imagine the case where we have **worker 1** and **worker 2**, and **agent 1**, * *agent 2**. The **worker 1** receives a request for sending a command to **agent 1** and **worker 2** receives a request for sending a command to **agent 2**, the AR Thread processes the two messages, sends them to their respective agents and sends the result to the `AR Queue`. How **worker 1** knows the incoming message is for him and not for **worker 2**?

To solve this we can have a socket for each worker and make the thread wait for a msg with a `select`, but it goes out of the scope of checking if we can use the same `AR Queue` for sending and receiving messages.

#### 2. A command was sent to an Agent but the Agent didn't give a response
Returning to `Python` code:

https://github.com/wazuh/wazuh/blob/e958b3c818a25ad1405db11bd17032f8970e1881/framework/wazuh/active_response.py#L43-L51

We would have to change this code to be asynchronous. Image the case where the first agent we send the command does not respond due to an error (it could be a connection error, running another command that takes more time, etc). We can change the code to use `async io` and wait for all the responses to solve this.

#### 3. The AR Thread doesn't wait for a response from the Agent

Another problem is that the AR Thread does not expect a response from the Agent after sending the command, so there is needed to change the *c* code to expect a response and then send it back to the worker and change the code of the Agent to send the status after the command to the AR Thread.

### Final Comments

There are other changes we must consider besides the ones mentioned previously. Trying to use the `queue/alerts/ar` to get the responses from the agents is possible but it implies making a lot of changes to the data flow of the AR commands, including changing parts of the `core` and `framework` modules and is out of the scope of this Issue.

**Comment by RamosFe** [comment]
## Update

Created the `ARMessageBuilder` base class: The `create_message` function, which was originally part of the main code, has been moved to the ARMessageBuilder base class. This allows for a more modular and flexible approach to message creation.

https://github.com/wazuh/wazuh/blob/db89a53beeec0c4411f86abcd48a63894eda8cb7/framework/wazuh/core/active_response.py#L55-L92

Two subclasses, ARStrMessage and ARJsonMessage, have been introduced. They override the create_message function in the base class to provide their specific implementations based on the agent version.

https://github.com/wazuh/wazuh/blob/db89a53beeec0c4411f86abcd48a63894eda8cb7/framework/wazuh/core/active_response.py#L121-L230

The ARMessageBuilder class now includes a choose_builder method that dynamically selects the appropriate message builder class based on the agent version. This ensures that the correct implementation is used for generating the active-response message.

https://github.com/wazuh/wazuh/blob/13cdb8331565a09fdf0401f2baf2fffab94947d6/framework/wazuh/core/active_response.py#L94-L118

The tests for the module have been updated to reflect the changes in the code. New tests have been added to cover the functionality of the message builder classes and the dynamic selection of the appropriate builder based on the agent version.

https://github.com/wazuh/wazuh/blob/13cdb8331565a09fdf0401f2baf2fffab94947d6/framework/wazuh/core/tests/test_active_response.py#L72-L88

**Comment by davidjiglesias** [comment]
I think the original intention of this issue has been misinterpreted. We should discuss it further @Selutario and @RamosFe.

**Comment by RamosFe** [comment]
## Update

The `custom` parameter was deleted and the functionality was maintained for the commands that start with !

**Comment by RamosFe** [comment]
## Update

After some bug fixes all checks passed.
