### ISSUE TITLE
Add the RTR to the engine project

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#16013]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0-1 | Wazuh engine | Manager | Packages/Sources | OS version |

This issue aims to incorporate as a method of evidence and check, both local and remote(jenkins executiuon), a series of tests to validate that a pull request is apt/valid to incorporate in the main branch of the engine development.

The tool must be the one specified below that is adaptable to the type of engine project, and that is currently used in other projects.

Ex:
https://github.com/wazuh/wazuh-http-request/tree/main/.rtr

**Comment by pereyra-m** [comment]
## Update

The working branch is https://github.com/wazuh/wazuh/tree/dev-16013-add-rtr-to-engine.

**The following tasks have been done so far:**
- The corresponding initial commits for the RTR and its files were taken from the https://github.com/wazuh/wazuh-http-request/ repository
- Some minor changes were done in the Docker image and the execution process
- The first step **build** has been added

**Current state:**
There is an error during the CMake configuration stage that is being analyzed. It only occurs in the Docker environment, it isn't present in the host

![rtr_build_error_2](https://user-images.githubusercontent.com/65046601/219059478-7ca59c0c-40b3-4585-b2ed-5f0a61a404aa.png)

![rtr_build_error_1](https://user-images.githubusercontent.com/65046601/219059523-2efc9be8-6e13-43b1-a40f-6b5a1cb18c08.png)

**Comment by pereyra-m** [comment]
## Update

The working branch is https://github.com/wazuh/wazuh/tree/dev-16013-add-rtr-to-engine.

**Tasks completed**:
- The compilation inside the container was fixed. The repository had to be added as a safe directory in the git configuration.
- The UT step was added.

**Current state**:
- There are some compilation warnings that generate an output in the STDERR, causing a `fail` message in the building step when it was succesfull

![2023-02-22_11-29](https://user-images.githubusercontent.com/65046601/220651823-0139400e-9a5d-40e0-b516-75bfe7a8d8a0.png)

![2023-02-22_11-32](https://user-images.githubusercontent.com/65046601/220653123-d8dcefdd-7155-42fd-a047-33d0412e82c0.png)

- The UT step fails inside the container. The reason is still being analyzed

![2023-02-22_11-30](https://user-images.githubusercontent.com/65046601/220652197-38973e3d-1539-42f9-bc5d-db6de32c2da9.png)

![2023-02-22_11-30_1](https://user-images.githubusercontent.com/65046601/220652577-8f396887-7ba9-46f6-80e2-957f4f2910cb.png)

<details>

<summary>
The following tests FAILED:
</summary>

	931 - opBuilderWdbQuery.completeFunctioningWithtDBresponseNotOk (Failed)
	932 - opBuilderWdbQuery.completeFunctioningWithtDBresponseWithPayload (Failed)
	933 - opBuilderWdbQuery.QueryResultCodeOkPayloadEmpty (Failed)
	934 - opBuilderWdbQuery.QueryResultCodeOkNotPayload (Failed)
	941 - opBuilderWdbUpdate.completeFunctioningWithBadResponse (Failed)
	942 - opBuilderWdbUpdate.completeFunctioningWithOkResponse (Failed)
	943 - opBuilderWdbUpdate.completeFunctioningWithOkResponseWPayload (Failed)
	944 - opBuilderWdbUpdate.QueryResultCodeNotOkWithPayload (Failed)
	945 - opBuilderWdbUpdate.QueryResultCodeOkPayloadEmpty (Failed)
	981 - Parse_date.Build (Failed)
	982 - Parse_date.Build_opt_param (Failed)
	985 - Parse_date.Match_value (Failed)
	986 - Parse_date.Match_fail (Failed)
	987 - Parse_date.Match_ref (Failed)
	1067 - opBuilderSendARTestSuite.Send (Failed)
	1068 - opBuilderSendARTestSuite.SendFromReference (Failed)
	1131 - opBuilderSCAdecoder_Functions.DeletePolicyCheckDistinct_ResultOk (Failed)
	1132 - opBuilderSCAdecoder_Functions.DeletePolicyCheckDistinct_ResultTrueWithQueryError (Failed)
	1133 - opBuilderSCAdecoder_Functions.DeletePolicyCheckDistinct_ResultFalseWithRandomAnswer (Failed)
	1134 - opBuilderSCAdecoder_Functions.FindCheckResults_ResultOkFound (Failed)
	1135 - opBuilderSCAdecoder_Functions.FindCheckResults_ResultOkNotFound (Failed)
	1136 - opBuilderSCAdecoder_Functions.FindCheckResults_ResultError (Failed)
	1157 - checkTypeDecoderSCA.FindEventcheckUnexpectedAnswer (Failed)
	1158 - checkTypeDecoderSCA.FindEventcheckOkFoundWithoutComplianceNorRules (Failed)
	1159 - checkTypeDecoderSCA.FindEventcheckOkFoundWithResultEqualResponse (Failed)
	1160 - checkTypeDecoderSCA.FindEventcheckOkFoundWithoutResultAndStatusEqualResponse (Failed)
	1161 - checkTypeDecoderSCA.FindEventcheckOkNotFoundWithoutComplianceNorRules (Failed)
	1162 - checkTypeDecoderSCA.SaveACompliance (Failed)
	1163 - checkTypeDecoderSCA.SaveCompliances (Failed)
	1164 - checkTypeDecoderSCA.SaveFileRule (Failed)
	1165 - checkTypeDecoderSCA.SaveDirectoryRule (Failed)
	1166 - checkTypeDecoderSCA.SaveRegistryRule (Failed)
	1167 - checkTypeDecoderSCA.SaveCommandRule (Failed)
	1168 - checkTypeDecoderSCA.SaveProcessRule (Failed)
	1169 - checkTypeDecoderSCA.SaveNumericRule (Failed)
	1170 - checkTypeDecoderSCA.InvalidRules (Failed)
	1171 - checkTypeDecoderSCA.SaveRules (Failed)
	1186 - summaryTypeDecoderSCA.AllUnexpectedAnswers (Failed)
	1187 - summaryTypeDecoderSCA.FindScanInfoOkFound (Failed)
	1188 - summaryTypeDecoderSCA.scoreFloatFindScanInfoOkFound (Failed)
	1189 - summaryTypeDecoderSCA.FindScanInfoOkFoundSameHashNoForced (Failed)
	1190 - summaryTypeDecoderSCA.scoreFloatFindScanInfoOkFoundSameHashNoForced (Failed)
	1191 - summaryTypeDecoderSCA.FindScanInfoOkNotFoundFirstScan (Failed)
	1192 - summaryTypeDecoderSCA.FindScanInfoOkNotFoundNotFirstScan (Failed)
	1193 - summaryTypeDecoderSCA.FindPolicyInfoOkNotFound (Failed)
	1194 - summaryTypeDecoderSCA.FindPolicyInfoOkFoundFindPolicySHA256UnexpectedAnswer (Failed)
	1195 - summaryTypeDecoderSCA.FindPolicyInfoOkFoundFindPolicySHA256OkNotFound (Failed)
	1196 - summaryTypeDecoderSCA.FindPolicyInfoOkFoundFindPolicySHA256OkFoundSameHashFile (Failed)
	1197 - summaryTypeDecoderSCA.FindPolicyInfoOkFoundFindPolicySHA256OkFoundDeletePolicyUnexpectedAnswer (Failed)
	1198 - summaryTypeDecoderSCA.FindPolicyInfoOkFoundFindPolicySHA256OkFoundDeletePolicyErr (Failed)
	1199 - summaryTypeDecoderSCA.FindPolicyInfoOkFoundFindPolicySHA256OkFoundDeletePolicyOk (Failed)
	1200 - summaryTypeDecoderSCA.FindCheckResultsUnexpectedAnswer (Failed)
	1201 - summaryTypeDecoderSCA.FindCheckResultsOkNotFoundFirstScan (Failed)
	1202 - summaryTypeDecoderSCA.FindCheckResultsOkNotFoundNotFirstScan (Failed)
	1203 - summaryTypeDecoderSCA.FindCheckResultsOkFoundSameHash (Failed)
	1204 - summaryTypeDecoderSCA.FindCheckResultsOkFoundDifferentHashFirstScan (Failed)
	1205 - summaryTypeDecoderSCA.FindCheckResultsOkFoundDifferentHashNotFirstScan (Failed)
	1207 - policiesTypeDecoderSCA.FindPoliciesIdsUnexpectedAnswer (Failed)
	1208 - policiesTypeDecoderSCA.FindPoliciesIdsOkNotFound (Failed)
	1209 - policiesTypeDecoderSCA.FindPoliciesIdsOkFoundSamePolicy (Failed)
	1210 - policiesTypeDecoderSCA.FindPoliciesIdsOkFoundSamePolicies (Failed)
	1211 - policiesTypeDecoderSCA.FindPoliciesIdsOkFoundDifferentPolicyError (Failed)
	1212 - policiesTypeDecoderSCA.FindPoliciesIdsOkFoundDifferentPolicyUnexpectedAnswer (Failed)
	1213 - policiesTypeDecoderSCA.FindPoliciesIdsOkFoundDifferentPolicyOkDeletePolicyCheck (Failed)
	1214 - policiesTypeDecoderSCA.FindPoliciesIdsOkFoundDifferentPoliciesDeletePolicyCheckI (Failed)
	1215 - policiesTypeDecoderSCA.FindPoliciesIdsOkFoundDifferentPoliciesDeletePolicyCheckII (Failed)
	1216 - policiesTypeDecoderSCA.FindPoliciesIdsOkFoundDifferentPoliciesDeletePolicyCheckIII (Failed)
	1221 - dumpEndTypeDecoderSCA.DeletePolicyCheckDistinctUnexpectedAnswerFindCheckResultsUnexpectedAnswer (Failed)
	1222 - dumpEndTypeDecoderSCA.DeletePolicyCheckDistinctUnexpectedAnswerFindCheckResultsOkNotFound (Failed)
	1223 - dumpEndTypeDecoderSCA.DeletePolicyCheckDistinctErrFindCheckResultsOkNotFound (Failed)
	1224 - dumpEndTypeDecoderSCA.DeletePolicyCheckDistinctOkFindCheckResultsUnexpectedAnswer (Failed)
	1225 - dumpEndTypeDecoderSCA.DeletePolicyCheckDistinctOkFindCheckResultsOkNotFound (Failed)
	1226 - dumpEndTypeDecoderSCA.DeletePolicyCheckDistinctUnexpectedAnswerFindScanInfoUnexpectedAnswer (Failed)
	1227 - dumpEndTypeDecoderSCA.DeletePolicyCheckDistinctUnexpectedAnswerFindScanInfoOkNotFound (Failed)
	1228 - dumpEndTypeDecoderSCA.DeletePolicyCheckDistinctErrFindScanInfoUnexpectedAnswer (Failed)
	1229 - dumpEndTypeDecoderSCA.DeletePolicyCheckDistinctErrFindScanInfoOkNotFound (Failed)
	1230 - dumpEndTypeDecoderSCA.DeletePolicyCheckDistinctOkFindScanInfoOkNotFound (Failed)
	1231 - dumpEndTypeDecoderSCA.DeletePolicyCheckDistinctOkFindScanInfoUnexpectedAnswer (Failed)
	1232 - dumpEndTypeDecoderSCA.DeletePolicyCheckDistinctUnexpectedAnswerStrcmpIsZero (Failed)
	1233 - dumpEndTypeDecoderSCA.DeletePolicyCheckDistinctErrStrcmpIsZero (Failed)
	1234 - dumpEndTypeDecoderSCA.DeletePolicyCheckDistinctOkStrcmpIsZero (Failed)
	1235 - dumpEndTypeDecoderSCA.DeletePolicyCheckDistinctUnexpectedAnswerStrcmpIsNotZero (Failed)
	1236 - dumpEndTypeDecoderSCA.DeletePolicyCheckDistinctErrStrcmpIsNotZero (Failed)
	1237 - dumpEndTypeDecoderSCA.DeletePolicyCheckDistinctOkStrcmpIsNotZero (Failed)
	1245 - opBuilderHelperNetInfoTest.Correct_execution_with_event (Failed)
	1246 - opBuilderHelperNetInfoTest.Correct_execution_with_single_address_event (Failed)
	1247 - opBuilderHelperNetInfoTest.Correct_execution_with_seccond_failed_event (Failed)
	1248 - opBuilderHelperNetInfoTest.Correct_execution_with_signle_address_ipv6_event (Failed)
	1249 - opBuilderHelperNetInfoTest.Correct_execution_with_various_addres_none_others (Failed)
	1250 - opBuilderHelperNetInfoTest.Correct_execution_with_various_addres_others_wrong_type (Failed)
	1251 - opBuilderHelperNetInfoTest.Correct_execution_without_broadcast_netmask (Failed)
	1536 - DateParser.formatDateFromSample_knownFormat (Failed)
	1539 - DateParser.parser (Failed)

</details>

**Comment by pereyra-m** [comment]
## Update

The working branch is https://github.com/wazuh/wazuh/tree/dev-16013-add-rtr-to-engine.

**Tasks completed**:
- The UTs step was fixed by adding some language configurations in the Dockerfile and creating a directory tree to allow the sockets to be created. 
- The clang-format step was added.
- The cppcheck step was added.
- The Doxygen documentation step was added.

**Current state**:

![2023-02-23_21-09](https://user-images.githubusercontent.com/65046601/221060721-71639565-4703-419d-9f2d-08f2a1964fa7.png)


- The clang-format step is failing due to the generated warnings. This error return code is temporarily bypassed.

[clangformat.stderr.log](https://github.com/wazuh/wazuh/files/10819541/clangformat.stderr.log)

- The cppcheck step is failing due to the generated warnings. This error return code is temporarily bypassed.

[cppcheck.stderr.log](https://github.com/wazuh/wazuh/files/10819544/cppcheck.stderr.log)


- The Doxygen step is failing due to the generated warnings. This error return code is temporarily bypassed.

[docs.stderr.log](https://github.com/wazuh/wazuh/files/10819546/docs.stderr.log)

**Comment by pereyra-m** [comment]
## Update

The working branch is https://github.com/wazuh/wazuh/tree/dev-16013-add-rtr-to-engine.

**Tasks completed:**
- Some return codes of the steps were fixed.
- The clang-tidy step was added.
- The coverage step was added.
- The clean step was added.
- Some extra options were added, like selecting the compilation threads, the build flags and auto-fix. Also, now the script can be run with any folder as input/output and individual steps can be selected.

**Current state:**

- The clang-tidy step takes almost 30 minutes to end, and it fails because of the unfixed warnings.
- The coverage step fails because the tests don't cover the expected 95% of the code

![coverage](https://user-images.githubusercontent.com/65046601/222006308-d29f3472-46e4-4509-8ebb-b758dc009179.png)
![coverage2](https://user-images.githubusercontent.com/65046601/222006743-0dd009e7-da2e-46fe-81a3-42bcea0327b5.png)

**Comment by pereyra-m** [comment]
## Update 

The working branch is https://github.com/wazuh/wazuh/tree/dev-16013-add-rtr-to-engine.

**Tasks completed:**

- The valgrind step was added.
- The ASAN, TSAN and UBSAN steps were added.

**Current state:**

- The valgrind step is temporarily skipped because it contains errors. Also, the tests in `hlp2_test` fail only in valgrind (not using ctest)

[valgrind.stderr.log](https://github.com/wazuh/wazuh/files/10874928/valgrind.stderr.log)

[valgrind.stdout.log](https://github.com/wazuh/wazuh/files/10874927/valgrind.stdout.log)

- The ASAN step is temporarily skipped because it contains errors.

[asan.stdout.log](https://github.com/wazuh/wazuh/files/10874941/asan.stdout.log)

- The TSAN step is temporarily skipped because it contains errors during the build stage

[tsan-build.stderr.log](https://github.com/wazuh/wazuh/files/10874950/tsan-build.stderr.log)
