### ISSUE TITLE
on update agent\manager always overwrites internal_options.conf

### ISSUE THREAD

**Issue by dmitrijn** [wazuh/wazuh#161]
Hi,

Always when updating wazuh-agent\wazuh-manager it's overwrites internal_options config. After each update i need to make changes in this file. Could you ask for diff of this file when agent\manager updates?   

I'm using debian packages jessie\stretch

**Comment by vikman90** [comment]
Hi @dmitrijn,

this behavior is normal: the `internal_options.conf` must be overwritten by updates. This is so because new versions use to introduce new options, if any option is not present in the `internal_options.conf` .

In fact, this text appears in the file header:

> DO NOT TOUCH THIS FILE. The default configuration
> is at ossec.conf. More information at:
> https://documentation.wazuh.com

The file documentation is at: https://documentation.wazuh.com/current/user-manual/reference/internal-options.html.

If you want to change any value in the internal options, please copy the line from the `internal_options.conf` and write it into `local_internal_options.conf` with the desired value.

The file `local_internal_options.conf` is not modified by upgrades.

Hope it help.
Best regards.
