### ISSUE TITLE
Using an API endpoint that is already used breaks that instance

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#16106]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh-qa/issues/3888   |     https://github.com/wazuh/wazuh/issues/15939 |

# Description

During the configuration module testing, you can provide an already used API socket by another engine's instance.

For example using the default socket with multiple instances
```
./build/main server --api_endpoint /var/ossec/queue/sockets/engine-api start 
```

It will make that the instance that had the socket can't receive API requests anymore till it is restarted.

```
Socket communication error: no such file or directory
```

> This issue is also happening with the events one.

> The socket is deleted when the engine is terminated (expected), but this is not happening with the event's socket.

## Considerations

More details in the comment within the testing issue https://github.com/wazuh/wazuh-qa/issues/3888#issuecomment-1419570939.

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
The problem you're encountering is expected behavior due to a configuration conflict. When multiple instances attempt to use the same API socket, it leads to communication errors because the socket can only be accessed by one instance at a time.

Regarding the event socket not being deleted as expected, this might be a separate issue that requires further investigation. The socket should be removed when the engine terminates to prevent such conflicts. Please check the engine's shutdown process and ensure that it properly cleans up the socket.
