### ISSUE TITLE
Fresh install of Wazuh can't connect to API, fresh installed twice different systems - on completely fresh ubuntu servers

### ISSUE THREAD

**Issue by mmxpy** [wazuh/wazuh#16112]
| Wazuh version   | Component | Install type                 | Install method   | Platform |
| --------------- | --------- | ---------------------------- | ---------------- | -------- |
| I assume 4.3.10 | Indexer   | Wazuh installation assistant | | Ubuntu LTS 22.04 |

I am getting can't connect to API error after a fresh install of wazuh using the installation assistant on a fresh install of ubuntu 22.04 - error 3309 invalid credentials.
I have attempted twice and same result both times. Attempted to put in credentials in wazuh.yml for both wazuh user and wazuh-wui user. Both failed.

Really all I need is a clear guide on how to implement custom certs via docker so the dashboard can be internet facing and I could just use docker because that works.....I get the persistence and how that would be done but not the certs....

**Comment by mmxpy** [comment]
Not shocked by the lack of response after looking at the other open issues, well guess that answers the question, this is not a viable option for a production environment because of lack of attention to issues and responding, Moving off of Wazuh. Bind9 responded in 20 minutes, Duo in less then 6, and OpenCanary in like 3, all can be used in production because they actually address the users....

**Comment by sultanovich** [comment]
Hi @mmxpy , it's a pity we couldn't read your comment earlier. Wazuh has several community contact channels and maybe this query would have been more suitable for the [Slack](https://join.slack.com/t/wazuh/shared_invite/zt-1lgu531ur-7M_k_ZQbpdo4QCn_pHee3w) `#community` channel. They're all queries that try to be answered within the day (usually in less than a couple of hours). We also have a new `#community` channel on [Discord](https://discord.gg/75JBUfKSEW) that follows the same line as the Slack `#community` channel.

In addition to those channels which are the [official community channels](https://wazuh.com/community/), you also have options available if you would like to get to know the product in depth or just try it out quickly without the need for an installation.

Wazuh has the [Wazuh Cloud service](https://wazuh.com/cloud/). Wazuh Cloud is designed so that Wazuh manages the platform and you only manage your agents. It also has different levels of support so you can use the most appropriate for your needs. This service has many benefits that you can find [here](https://wazuh.com/cloud/) and that you may find interesting. But you can also [request a free trial](https://console.cloud.wazuh.com/sign-up?landing=trial) that allows you to test the complete tool, you just need to deploy an agent on your server and everything will be working.

If you think your use case or your need is more complex, you can [contact our sales team](https://wazuh.com/contact-us/) to coordinate a POC and clarify all your doubts.


Regarding the query you have made, if you want to change the default password for internal users you can do it by following the [official documentation](https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#change-the-password-of-an-existing-user) available for Docker. In case you want to change the certificates you can also see the documentation by going to the [single-node](https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#single-node-deployment) or [multi-node](https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#multi-node-deployment) section of the docker section.


If you have any other questions or if we can still help you with the test you wanted to perform, do not hesitate to contact us through the `#community channels`.

**Comment by sultanovich** [comment]
Hi @mmxpy, As a follow up on this inquiry you have sent us, is there anything else we can help you with to resolve this?
