### ISSUE TITLE
Windows Server vulnerabilities - KB supersedence

### ISSUE THREAD

**Issue by sgetech** [wazuh/wazuh#16126]
Hello,

We are encountering a problem that we are not able to solve :
Some of my Windows Servers show critical vulnerabilities due to missing Windows server updates, even if these updates have been installed by a more recent KB that supersedes them.
What is more problematic is that some of these Windows Servers, which benefit from the same updates through SCCM, do not show these vulnerabilities. The agent is in the same version, with the same configuration. 
To sum it up, even if they have the same configuration and have been updated with the same KBs from the same source, some servers are fine, some have critical alerts.
I just don’t understand what could cause this difference in results and how can I get rid of these false negatives on the long run.

What I have tried :
-	Remove the path of MSU catalog in ossec.conf
-	Force the URL of the MSU catalog in ossec.conf
-	Specify the hotfixes tag in ossec.conf
I think Wazuh does not take in account the supersedence of Windows KBs.

Example :
For a given Windows server, the CVE 2022 41128 shows up in Wazuh, which is triggered when KB5019964 patch is not installed. But when I go on the server, I see that the KB5022289 has been installed, and that KB5022289 supersedes the KB mentioned above in the CVE.

![1](https://user-images.githubusercontent.com/63371468/217859468-a372f8ce-d87d-4bf8-8654-c6f42be45845.png)
![2](https://user-images.githubusercontent.com/63371468/217859473-e939c50b-ff52-425f-884e-cc518fc6d3d6.png)
![3](https://user-images.githubusercontent.com/63371468/217859474-b166a52a-968a-4140-9c81-d33f83123dd0.png)

So, according to me, something is wrong with KBs that replace other KBs. But why do some servers show a critical alert when other do not ?

Thanks for your help
Sam

Wazuh manager  v4.3.10 on CentOS
Wazuh agents v4.3.10 on Windows Server

**Comment by MiguelazoDS** [comment]
Hi @sgetech 

Let's try to understand this issue. Some questions

> The agent is in the same version, with the same configuration.

- Are those agents connected to the same manager? 
- Is the vulnerabilities report for those agents from the same scan? I mean your manager started the scan and during the same execution scanned those agents? 

I'm trying to ensure the agent packages were correlated with the same feed information. 

> even if they have the same configuration and have been updated with the same KBs from the same source, some servers are fine, some have critical alerts.

Can we validate that? Please share the output of the agent databases from an agent that works as expected and one that doesn't

`sqlite3 /var/ossec/queue/db/<agent_id>.db 'select * from sys_hotfixes'`

Replace <agent_id> with the right number. 

> Specify the hotfixes tag in ossec.conf

Did you mean Syscollector hotfixes setting? where did you do that? that is a specific agent configuration. 

I tried to replicate this without success but didn't try it with Windows Server 2016. 

> I think Wazuh does not take in account the supersedence of Windows KBs.

Our feed for Windows takes into account supersedence KBs, but maybe some adjustments may be needed for this case if we found a real issue. 

On the other hand, sometimes the lack of information to properly detect vulnerabilities is due to Windows sources that we rely on to get the data. Although this seems to not be the case since some agents are working as expected. 

The Windows feed is obtained from there https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.json.gz

And according to what I see here, the information of supersedence information is properly obtained. 

![image](https://user-images.githubusercontent.com/13010397/218198121-24ee045b-cfec-46c0-84ba-1c32e35811d9.png)

The array indicates all the KBs that supersede the `KB5019964`

So many we just need to figure out what is happening with some of your agents. 

Regards!

**Comment by sgetech** [comment]
Hello,

Thanks for your feedback.
I will look into the information you asked for in a few days, as I am not available right now. I will then come back to you and I will try to be as precise and thorough as I can.
I hope we will be able to find what is going on here. Thanks a lot for help. 

Best regards,

**Comment by sgetech** [comment]
Hello @MiguelazoDs

Sorry again for the delay in my answer, I was away for a few days.

I will try to answer your questions in order :
-	Yes, those agents are connected to the same manager.
-	Yes, those results came from the same planned scan exécution

However this morning, I can’t find a server that brings up no vulnerabilities at all. But when I check in detail, there are some false positives again. 
For example, the server with agent 018. On this one, Wazuh shows up « CVE-2022-41128X : KB5019964 patch is not installed »
However, KB5022838 is installed on this server, which is a KB that supersedes it.

Here is the agent database for this server :
[root@wazuh-server etc]# sqlite3 /var/ossec/queue/db/018.db 'select * from sys_hotfixes'
0|2022/10/27 13:49:08|KB2293053|0045d3d5cfabf8668cbb996ef324e422c34ea9b2
0|2022/10/27 13:49:08|KB2450801|1987e0213d90b2a5bae0ec76dc9b14e95a53c5cc
0|2022/10/27 13:49:08|KB2468871|8f99821b9e79bc2258cb56cd14cfcaf9bbeda8e5
0|2022/10/27 13:49:08|KB2478063|8511235ae3ab3b642d8ba429599092634fdde3a8
0|2022/10/27 13:49:08|KB2533523|b8c4cb9a2aeb6a64269e88f6116765420a65cd80
0|2022/10/27 13:49:08|KB2544514|8e468309f00c0f31b8a0f12a6a79d2658652e9e9
0|2022/10/27 13:49:08|KB2549864|e9b073ede01e00e31f5de94878db2e1350be5e54
0|2022/10/27 13:49:08|KB2600211|cb13c01ba11045aabbb074fc3e61b0a3b2d88dd4
0|2022/10/27 13:49:09|KB2600217|8253af775746f8545784d27edb852281c9a06955
0|2022/10/27 13:49:09|KB4048953|1f0bd1bd12b44f50fc76702fb05955fb0fa7e897
0|2022/10/27 13:49:09|KB4049065|e036cc469309f3cce3a8a8566d0b4a5236803703
0|2022/10/27 13:49:09|KB4486129|c2bd04f767cc0e2a84c726563ef36b25f0e9323d
0|2022/10/27 13:49:09|KB4502496|da329a5d2df4e3ea154bff232470706ae246966b
0|2022/10/27 13:49:09|KB4535680|340b2e0ff49767b4480a22d33057060775819a49
0|2022/10/27 13:49:09|KB4535684|355eb0f25123d339c52c5b8e36901c5615622b11
0|2022/10/27 13:49:09|KB4535685|2c79074bc49855299b61d9fe5ebcb0dba7b06fe6
0|2022/10/27 13:49:09|KB4550994|de7e1ba088ea87cd240a90b802dbcd2e487990d8
0|2022/10/27 13:49:09|KB4562561|e419813d535b28b096d8ff126e9763a61ba7c480
0|2022/10/27 13:49:10|KB4565912|1dde8e4c4c42d9bcbe97f4a7199157209ed8deb9
0|2022/10/27 13:49:10|KB4576750|fcd90dba72db2624e018b7f006c4f0bcc56f2427
0|2022/10/27 13:49:10|KB4589210|81cd2ad453144fb122370351da6f3337d886c2a0
0|2022/10/27 13:49:10|KB5001078|5beb7fa2487efa6a004789569e1d348d88dca7ac
0|2022/10/27 13:49:10|KB5001402|0e8a27259e5665bb4e171638c1f09b6114a8a611
0|2022/10/27 13:49:10|KB5005698|7e5cfd25d1c07b54b06520e4a53294711eda894c
0|2022/10/27 13:49:10|KB5011570|a7558c501a96dc0b81f60d7d94a62e66616396bc
0|2022/10/27 13:49:10|KB5012170|d9e49825d14b5bbbf4b4aa4c499ae7f8121389a3
0|2022/10/27 13:49:10|KB5014026|85301e441a0856254496b9694669c69aa4b66403
0|2022/10/27 13:49:10|KB5016058|1f302da6b23203ebd23003be53fb10c4493f021c
0|2022/10/27 13:49:11|KB5017095|9a6e0b2660bdc11309806f3270ca2214baa91b59
0|2022/10/27 13:49:11|KB5017396|690aac925e5a7970290c4df8c4f414041259ab7a
0|2022/12/15 00:20:16|KB5020873|be49b8e2cd2b1ca8d6490749abe0a87de877a534
0|2023/01/12 00:40:58|KB5022289|854f8cb9b72849dc59b50242eaec5c205df07bc3
0|2023/02/16 00:10:11|KB5022503|7729c6b2661575d0f1f523e3e052c8904824a3cb
0|2023/02/16 00:53:34|KB5022838|76aa41d0611a9e0571e3405a9466e88af99ab61c

These snippets are from the configuration of the ossec file on the wazuh master, where I specifies « yes » on the « hotfixes » tag :

  
  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>1h</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>yes</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <processes>yes</processes>
    <hotfixes>yes</hotfixes>

    
    <synchronization>
      <max_eps>10</max_eps>
    </synchronization>
  </wodle>

….

  
    <provider name="msu">
      <enabled>yes</enabled>
      <path>/var/ossec/queue/vulnerabilities/dictionaries/msu-updates\.json\.gz$</path>
      #<url>https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.json.gz</url>
      <update_interval>1h</update_interval>
    </provider>

I tried to put the URL tag instead of path but I commented it as it did not improved results.

I hope these informations can help solve the issue.
Thanks a lot for your help and your patience.

Regards

**Comment by MiguelazoDS** [comment]
HI @sgetech, 

The configuration for Syscollector as I mentioned is specific for agents, so it has no effects on the Linux server, but besides that, I don't think your config is wrong. 

The path won't help, and it is better to have the latest updated feed from the web. 

And regarding that, I checked the MSU feed at this moment and there's information about that supersedence. 

Starting from the KB5019964 we can see that the KB5022838 is listed as supersedence, so the scan should recognize that. 

![image](https://user-images.githubusercontent.com/13010397/221977011-26723d1d-4235-4923-9af0-bd614960a41d.png)

But if you take a look at the image I shared before here: https://github.com/wazuh/wazuh/issues/16126#issuecomment-1426355100 the information at that moment was 

![image](https://user-images.githubusercontent.com/13010397/221977280-46acff25-e179-4664-ac42-fd5e830f2009.png)

With this command you can see the date the MSU feed was updated

`sqlite3 /var/ossec/queue/vulnerabilities/cve.db 'select * from metadata where target = "MSU"'`

![image](https://user-images.githubusercontent.com/13010397/221978223-bf2e0d93-91bc-41fe-a4d4-a85ed10ab370.png)

The last update was February 15. 

So, I think that this specific case is because of that missing KB due to a an out of date MSU, and probably that is consequence of using the PATH option in the vulnerability detector configuration. 

Let me know how it goes.

Regards!

**Comment by MiguelazoDS** [comment]
The `cve.db` database is located in the manager since the module run in the manager. The query is ok and should return an output similar to this. 

![image](https://user-images.githubusercontent.com/13010397/222426817-ff15aecd-4983-462d-912c-e966447c78a2.png)

Please use the default configuration for MSU. 

Is this the manager you used to scan those Windows agents?

**Comment by sgetech** [comment]
What is the default configuration in ossec.conf for MSU ? This one :

```
 <!-- Windows OS vulnerabilities -->
    <provider name="msu">
      <enabled>yes</enabled>
      <update_interval>1h</update_interval>
    </provider>
```
    
The cve.db file is located where it should be, but the command brings up no output.

![image](https://user-images.githubusercontent.com/63371468/222457200-1345d459-4213-4e5f-87a6-d25fe1fff723.png)

I only use one manager to scan all my clients, so this is the one and only.

**Comment by MiguelazoDS** [comment]
Yes, that's the default one. Delete the cve.db database and configure debug mode as described below:

Please enable `wazuh_modules.debug=2` in your `/var/ossec/etc/internal_options.conf` file so we can see what is happening with more details.

Finally, restart your manager and share the logs regarding the update of the vulnerabilities database. If the module is enabled it should populate the database with all the enabled providers. 

I just did that to show you what I want to see. 

`grep "Refreshing 'Microsoft Security" -A 10 /var/ossec/logs/ossec.log `

![image](https://user-images.githubusercontent.com/13010397/222471825-2117bfdd-a1d4-4e40-84f9-7c5f5cccabff.png)

All this information should be available now 

![image](https://user-images.githubusercontent.com/13010397/222472700-1d334fe4-1592-41c0-a070-1f4f306d05fd.png)

**Comment by sgetech** [comment]
Hello,

Thanks for your help.
The MSU database was successfully updated :

![image](https://user-images.githubusercontent.com/63371468/222679197-b540242b-0367-46f6-9cb4-409baeeac461.png)

I will now check if the alerts regarding vulnerabilites evolved in Wazuh.
I will come back to you when all my agents have been rescanned.

Thanks a lot

**Comment by sgetech** [comment]
Hello,

Thank you very much for your help. These false negative on the Windows Server machines just disappeared ! That is brilliant, thanks a lot.

However, we still have Windows vulneraibilties showing up on Windows 11 laptops, even if these KBs have been applied.
Is this specific to Windows 11 ? Perhaps Wazuh does not fully support W11 for now ?

Thanks

**Comment by MiguelazoDS** [comment]
That's great! 

Windows 11 should work, if there're some false positives they are unintended and we may need to apply some fixes. Please give me the cases you found so that I can evaluate them. 

Please take into account that as of now the update of the MSU feed is manual, so it can take some delay as we experienced with Windows 10. 

Thanks for this feedback!

**Comment by MiguelazoDS** [comment]
Hi @sgetech, 

Thanks for all the information provided! 

As far as I saw, everything seems to be ok regarding the information to properly correlate the vulnerabilities. 

We have the CVE information and the patch that fixes it (the one you mentioned).

![image](https://user-images.githubusercontent.com/13010397/223167009-7e343d24-9197-44b5-bc38-f591f0d7a6d2.png)

The supersedence KB of 5006674.

![image](https://user-images.githubusercontent.com/13010397/223167616-1ae87696-ee57-4346-97fb-b0b7d60f5d4b.png)

In fact, the list of supersedence KBs is big. 

![image](https://user-images.githubusercontent.com/13010397/223168229-04bce4f4-7868-417d-a6b6-d95bfe9b41aa.png)

So do you have installed one of those KBs right? 

If you do this query, what is the output? 
`sqlite3 /var/ossec/queue/db/<agent_id>.db 'select * from sys_hotfixes'` (replace <agent_id> for the right one)

In my case, the vulnerability is solved for one of those other KBs that supersedes 5006674

![image](https://user-images.githubusercontent.com/13010397/223169692-e9a52715-429f-4eb8-8834-9a4823989177.png)

**Comment by sgetech** [comment]
Hello,

Thanks for your help.
On the given example, the laptop has the KB5010386 installed (which supersedes KB5006674), however CVE-2021-38672 is still showing up in the vulnerability scan.

When I type the commande you gave me, here is the result :

```
[root@wazuh-server wazuh-user]# sqlite3 /var/ossec/queue/db/036.db 'select * from sys_hotfixes'
0|2022/11/21 15:05:16|KB2468871|8f99821b9e79bc2258cb56cd14cfcaf9bbeda8e5
0|2022/11/21 15:05:16|KB2478063|8511235ae3ab3b642d8ba429599092634fdde3a8
0|2022/11/21 15:05:17|KB2533523|b8c4cb9a2aeb6a64269e88f6116765420a65cd80
0|2022/11/21 15:05:17|KB2544514|8e468309f00c0f31b8a0f12a6a79d2658652e9e9
0|2022/11/21 15:05:17|KB2600211|cb13c01ba11045aabbb074fc3e61b0a3b2d88dd4
0|2022/11/21 15:05:17|KB2600217|8253af775746f8545784d27edb852281c9a06955
0|2022/11/21 15:05:17|KB5015734|fac133c04dfa75496851c21c9f3baf7e0c79c2bb
0|2022/12/14 10:06:34|KB5020880|8a818d3e4436241f88581776da7e5749aa47f311
0|2023/01/23 08:49:26|KB5022303|b68cdd4dc754c7aee6dc64848f6868aa38ffe4cf
0|2023/02/27 09:06:42|KB5022610|6bf815572982efbaf600668b2daab5dadff7540a
0|2023/02/27 09:06:42|KB5022845|30ebdd12bda80b37ca89e676d3b0745c07bd7182
0|2023/02/27 09:06:42|KB5022497|8d8360100a60d1430dd33259f1f62cc1b168f07f
```

This is just an example, a lot of other vulenrabilities populate my Wazuh reports for this host. This is common to all Windows 11 laptops.

![image](https://user-images.githubusercontent.com/63371468/223369807-124fa5ee-5e3e-4416-9ca8-1cc6311c926c.png)

What could cause these results ?

Thanks a lot

**Comment by MiguelazoDS** [comment]
Hi @sgetech, 

None of the KBs you have installed in your agent, mentioned in the `sys_hotfixes` inventory, supersede the `KB5006674`, that's why the vulnerabilities are correctly reported. 

Please show what happens when you try to install the `KB5010386`. 

Vulnerability detector relies on the information provided by Syscollector, and the `sys_hotfixes` table does not contain that KB. If didn't already, restart your agent so the Syscollector scan will run in case it needs to update some information.

**Comment by sgetech** [comment]
Hello,

I downloaded the .msu file in order to install KB5010386 but I got this error :

![wazuh1](https://user-images.githubusercontent.com/63371468/223436365-04aa376e-5d35-40c6-8155-080954eb82be.png)

The Windows 11 laptop says that this KBs is well and truly installed :

![image](https://user-images.githubusercontent.com/63371468/223435894-f2c58bbb-020e-4bca-96a0-3f8e75da1c44.png)

But I still have CVE-2021-38972 showing up in my reports. All of the vulnerabilties for the W11 devices come from KBs supposedly not installed, something is probably off in the config or in the way information is collected I guess

![image](https://user-images.githubusercontent.com/63371468/223436790-327e0639-7e18-420d-8aff-7e13772c2e81.png)

I stopped and started the Wazuh service on the Windows 11 laptop, so far nothing changed.

**Comment by MiguelazoDS** [comment]
So the issue is in the Syscollector module, which apparently is not gathering all the installed KBs in your system. Let me check what Syscollector does to obtain those KBs, pretty much the information is stored in the Registry, and for some reason is not getting that information in your case.

**Comment by sgetech** [comment]
Do you want me to share some conf file or any other elements with you that could help solving this case ?

**Comment by MiguelazoDS** [comment]
Hello,

As I mentioned before the KB that fixes the vulnerability in my case was this `KB5013943`, so I took a look at the Windows registry to see where it reads that value. 

And that KB supersedes the `KB5010386` you have.

That specific `KB5013943` is obtained from: 
`HKEY_LOCAL_MACHINE/SOFTWARE/Microsoft/Windows/CurrentVersion/Component Based Servicing/Packages`

Please show what you have there that starts with `Package_`

This is my case.
![image](https://user-images.githubusercontent.com/13010397/223786424-3b9711a4-f75d-4282-ad12-c1057c269c83.png)

Then click on `Package_for_RollupFix` and check what you have in `installLocation`
![image](https://user-images.githubusercontent.com/13010397/223787076-3a862cdc-bcca-4fc2-88a9-e51292117f72.png)

Also what Windows 11 version are you using? mine is 21H2. We need to cover all possibilities.

**Comment by sgetech** [comment]
Hello,

Thanks for coming back to me with those informations.

You will below my system info :
```
Édition	Windows 11 Professionnel
Version	22H2
Installé le	‎17/‎10/‎2022
Build du système d’exploitation	22621.1265
Expérience	Windows Feature Experience Pack 1000.22638.1000.0
```
Here is a screenshot from my registry : 

![image](https://user-images.githubusercontent.com/63371468/223975350-9df4e78a-e250-40da-b16a-11393e8b94a5.png)

As, you can see, I have two "Package_for_RollupFix" entries in my registry.

![image](https://user-images.githubusercontent.com/63371468/223975710-67f269b3-b762-4aee-bf74-bc5da350766d.png)
![image](https://user-images.githubusercontent.com/63371468/223975800-24cb98e4-d26e-4bf8-b7d0-6852288e3c5f.png)

I hope this can help.

**Comment by MiguelazoDS** [comment]
Hello,

There are other two registries where we collect the information about KBs but is so tedious to do it manually, I will try to replicate the case with the same Windows version you have. If there's not something easier that I'm not considering everything seems to point to a registry we are not currently parsing.

Thanks for the information. I'll keep you updated regarding this behavior. Regards!

**Comment by sgetech** [comment]
Hello,

Thanks for coming back to me.
So, If I sum it up, we have to deal with those false positives until Microsoft takes action in order to relate the new KBs with the old ones ?
Is there some kind of workaround ?

**Comment by MiguelazoDS** [comment]
If Microsoft does not take action to address this, yes, we have to think of a way to fix it. There's no WA for this.
