### ISSUE TITLE
The manager is not starting on system boot on AIX

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#16121]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.1.0 | Manager | Packages| AIX 7.1 |

The manager is expected to start on the system boot. However, we found that it was not running after rebooting:

```sh
reboot -l -q
# (...)
/var/ossec/bin/ossec-control status
```

```
ossec-monitord not running...
ossec-logcollector not running...
ossec-syscheckd not running...
ossec-analysisd not running...
ossec-maild not running...
ossec-execd not running...
wazuh-modulesd not running...
ossec-csyslogd not running...
```

### Installer

- wazuh-local-3.1.0-1.aix7.1.power7.ppc.rpm

### RC files

No RC files have been found:

```sh
find /etc/rc.d -name "*wazuh*"
```

### Proposed initial research

1. Check whether the sources installation does install the RC files.
2. Check whether the package does install the RC files.

**Comment by MarcelKemp** [comment]
## Research
After checking the problem in the different versions available, we have obtained the following information:

### Sources installation
Installing via sources a `v3.1` manager from the [15502-AIX-fixes](https://github.com/wazuh/wazuh/tree/15502-AIX-fixes) branch:
- The _init_ script for AIX (`/etc/rc.d/init.d/wazuh-manager`) is being generated correctly, however it is empty due to a lack of space in the partition corresponding to '**_/etc_**', so it does not work properly. The error that appears after executing the command (in this case _manually_), is the following:
```sh
cp: /etc/rc.d/init.d/ossec-hids-aix.init: No space left on device
```

- To fix this problem, it is necessary to increase the size of the '**/**' partition (which is the one corresponding to '**/etc**'), so that it has enough space to copy the file correctly.

### Local package installation - v3.1
- It appears that the package installation is not generating the _init_ script ([ossec-hids-aix.init](https://github.com/wazuh/wazuh/blob/v3.1.0/src/init/ossec-hids-aix.init)) corresponding to the path `/etc/rc.d/init.d/${service}`. This problem seems to be related to the limited size of the '**/**' partition, as SPECS provides for the installation of this file:
https://github.com/wazuh/wazuh-packages/blob/3.1.0-AIX-packages/aix/SPECS/3.1.0/wazuh-agent-3.1.0-aix.spec

- So the solution to this issue is the same as for the source installation, i.e. increase the size of the '**/**' partition.

### Agent package installation - v4.3.10
- The agent correctly generates the _init_ script with its corresponding code, so it works as it should.
