### ISSUE TITLE
Investigate AIT errors on vulnerability endpoints test

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#16137]
|Wazuh version|Component|
|---|---|
| 4.4 | API |

## Description
During #13373 it was found that the `GET /vulnerability/{agent_id}` test was failing. Since it was part of the #13265 Python 3.10 upgrade, a check to verify that the test was only failing for the `4.5` branch using the new embedded interpreter was carried out. To compare results, the `test_vulnerability_endpoints.tavern.yaml` tests were launched for the `4.4` branch and also for `4.3.10` and the results were the same.

### Test results
`4.4` results 
[4.4-results.txt](https://github.com/wazuh/wazuh/files/10707932/4.4-results.txt)

`v4.3.10` results
[v4.3.10-results.txt](https://github.com/wazuh/wazuh/files/10707931/v4.3.10-results.txt)

The first hypothesis is that the vulnerability feeds may have suffered a change, therefore, breaking the preexistent tests. 
The `4.4` tests were carried out by removing the `update` field from the test since an API request to the deployed environment returned that this field was not present and it was assumed that the origin of the failure could be related to it but it failed again.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by pereyra-m** [comment]
## Update

To find the cause of this error, some tests were carried out.

### Manual test of the API endpoint

The Wazuh manager `v4.4.0` was installed and Vulnerability Detector was configured. 
After the scan, the vulnerabilities were retrieved using the corresponding API endpoint

```
curl -k -X GET "https://localhost:55000/vulnerability/001/" -H  "Authorization: Bearer $TOKEN"
```

This verifies that DB and the API endpoint work successfully.

### Running the API integration tests

The `test_vulnerability_endpoints.tavern.yaml` was run locally and the same errors were found.
The received data doesn't match with expected

```
Full diff:
    [
  -  {'architecture': <tavern.util.loader.StrSentinel object at 0x7f4c5d798970>,
  -   'condition': <tavern.util.loader.StrSentinel object at 0x7f4c5d798b20>,
  -   'cve': <tavern.util.loader.StrSentinel object at 0x7f4c5d798610>,
  -   'cvss2_score': <tavern.util.loader.FloatSentinel object at 0x7f4c5d798a30>,
  -   'cvss3_score': <tavern.util.loader.FloatSentinel object at 0x7f4c5d798a60>,
  -   'detection_time': <tavern.util.loader.StrSentinel object at 0x7f4c5d798a90>,
  -   'external_references': <tavern.util.loader.ListSentinel object at 0x7f4c5d798af0>,
  -   'name': <tavern.util.loader.StrSentinel object at 0x7f4c5d7989a0>,
  -   'published': <tavern.util.loader.StrSentinel object at 0x7f4c5d798b80>,
  -   'severity': <tavern.util.loader.StrSentinel object at 0x7f4c5d798ac0>,
  -   'status': <tavern.util.loader.StrSentinel object at 0x7f4c5d798a00>,
  -   'title': <tavern.util.loader.StrSentinel object at 0x7f4c5d798b50>,
  -   'type': <tavern.util.loader.StrSentinel object at 0x7f4c5d7989d0>,
  -   'updated': <tavern.util.loader.StrSentinel object at 0x7f4c5d798bb0>,
  -   'version': <tavern.util.loader.StrSentinel object at 0x7f4c5d7985e0>},
  +  {'architecture': 'amd64',
  +   'condition': 'Package less than 2.34-6ubuntu1.4',
  +   'cve': 'CVE-2022-38533',
  +   'cvss2_score': 0,
  +   'cvss3_score': 5.5,
  +   'detection_time': '2023-02-10T18:31:56+00:00',
  +   'external_references': ['https://sourceware.org/bugzilla/show_bug.cgi?id=29482',
  +                           'https://sourceware.org/bugzilla/show_bug.cgi?id=29482#c2',
  +                           'https://security.netapp.com/advisory/ntap-20221104-0007/',
  +                           'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6AKZ2DTS3ATVN5PANNVLKLE5OP4OF25Q/',
  +                           'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7MTEHT3G6YKJ7F7MSGWYSI4UM3XBAYXZ/',
  +                           'https://nvd.nist.gov/vuln/detail/CVE-2022-38533',
  +                           'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-38533',
  +                           'https://ubuntu.com/security/CVE-2022-38533',
  +                           'https://ubuntu.com/security/notices/USN-5762-1'],
  +   'name': 'binutils-common',
  +   'published': '2022-08-26',
  +   'severity': 'Medium',
  +   'status': 'VALID',
  +   'title': 'CVE-2022-38533 affects binutils-common',
  +   'type': 'PACKAGE',
  +   'updated': '2022-12-08',
  +   'version': '2.34-6ubuntu1.1'},
    ]
```

We can see that really odd values were received instead of real data, like:
```
 {'architecture': <tavern.util.loader.StrSentinel object at 0x7f4c5d798970>, ...
```

But if we query directly to the same Docker container of the tests, the API endpoint retrieves the expected data

![api_success](https://user-images.githubusercontent.com/65046601/218173209-3b94e962-4c0f-41cf-9380-53edaa0d9f99.png)

## Conclusion

All the evidence suggests that the integration tests are retrieving incorrect information from the Wazuh API.
Probably, the cause is the tavern plugin, the `test_expected_value()` function in `tavern_utils.py` or the test file `api/test/integration/test_vulnerability_endpoints.tavern.yaml`.

**Comment by pereyra-m** [comment]
## Update

Analyzing the error logs, we found the following message related to the difference between the response and the expected values

```
Left contains 1 more item:
  {'message': 'All selected vulnerabilities were returned'}
...
```

It was added in the file `api/test/integration/test_vulnerability_endpoints.tavern.yaml` but some other errors were found.
The field `cvss2_score` is stored in the DB as `0.0` but returned by Wazuh-DB as `0`, causing a type mismatch error in the test.
This situation was reflected in the issue https://github.com/wazuh/wazuh/issues/16207.

Another possible solution would be making Vulnerability Detector to insert `NULL` instead of `0.0` when a score is missing.
