### ISSUE TITLE
Too Many "ossec-analysisd: WARNING: Missing file entry."

### ISSUE THREAD

**Issue by demantos** [wazuh/wazuh#1617]
**OS**
CentOS7

**Wazuh version**
3.6.1

**Wazuh API version**
3.6.1

**Install type**
manager

**Install method**
packages

**Log sample**

```
2018/10/10 21:57:54 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/CMDAudit/cmdlog'.
2018/10/10 21:57:54 ossec-logcollector: INFO: Started (pid: 125711).
2018/10/10 21:57:55 ossec-analysisd: WARNING: Missing file entry.
2018/10/10 21:57:55 ossec-analysisd: WARNING: Missing file entry.
2018/10/10 21:57:56 ossec-analysisd: WARNING: Missing file entry.
2018/10/10 21:57:56 ossec-analysisd: WARNING: Missing file entry.
2018/10/10 21:57:56 ossec-analysisd: WARNING: Missing file entry.
2018/10/10 21:57:57 ossec-analysisd: WARNING: Missing file entry.
2018/10/10 21:57:58 ossec-analysisd: WARNING: Missing file entry.
2018/10/10 21:57:58 ossec-analysisd: WARNING: Missing file entry.
2018/10/10 21:57:58 ossec-analysisd: WARNING: Missing file entry.
2018/10/10 21:57:59 ossec-analysisd: WARNING: Missing file entry.
2018/10/10 21:57:59 ossec-analysisd: WARNING: Missing file entry.
2018/10/10 21:58:00 ossec-analysisd: WARNING: Missing file entry.
2018/10/10 21:58:01 ossec-analysisd: WARNING: Missing file entry.
2018/10/10 21:58:01 ossec-analysisd: WARNING: Missing file entry.
2018/10/10 21:58:01 ossec-analysisd: WARNING: Missing file entry.
2018/10/10 21:58:01 ossec-analysisd: WARNING: Missing file entry.
```

When I restart wazuh manager, too many "Missing file entry." log is shown.

Anyone know why?

**Comment by DaveVG1** [comment]
This message denotes a deleted file in the database.
A "delete file" alert is arriving and that file is not found in the database. Is it possible that you had deleted the agent database? This database can be found in `/var/ossec/queue/syscheck`.

Anyway, you may resolve this problem cleaning the databases using `/var/ossec/bin/syscheck_control -u AGENT_ID` to clean the AGENT_ID database or  `/var/ossec/bin/syscheck_control -u all` to clean all databases.

We strongly suggest that you update to 3.7 version. The FIM management has changed considerably (this warning is not even on that version). If you decide to update and you want to preserve the databases you should migrate them.

In this link you will find all the info in order to do that: https://documentation.wazuh.com/current/user-manual/reference/tools/fim_migrate.html

Sorry for the late response.

**Comment by DaveVG1** [comment]
I hope the advice helped. I'm closing this issue. If you still have problems don't hesitate to re-open it.

Regards, 
David.
