### ISSUE TITLE
Do I need to restart wazuh-manager after manually adding an agent to client.keys?

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh#162]
If I edit the clients.keys, would wazuh pick up the key, or do I need to restart wazuh-manager?

**Comment by vikman90** [comment]
Hi @rossengeorgiev,

no, you don't need to restart Wazuh manager. But I recommend you to use utilities such `manage_agents`, `ossec-authd` or the Wazuh API to manage agents instead of manually adding agents.

If you need to edit the file `client.keys`, I recommend you to copy it into a temporary file, modify it and move it into the `client.keys`. If you modify directly that file, the manager could crash.

Hope it help.
Best regards.

**Comment by rossengeorgiev** [comment]
Thanks for the info. I'm using saltstack to manage the `client.keys` file and I wasn't sure. I've seen the code for some of the tools and I didn't quite get why they do the file replace.
