### ISSUE TITLE
wazuh-syscheckd stopped generating events

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#16203]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| At least 4.4.0-rc1 | wazuh-syscheckd | Agent | Packages | CentOS 7 |

In the analysis of the `v4.4.0-rc1` Syscheck (2.5d) stress test, an anomalous behavior has been found in the Wazuh CentOS agent, where a drop in CPU usage can be seen (compared to the same `Beta1` and `Alpha2` graphs), furthermore, it is possible to see that at the same timestamp where the CPU has dropped, a small RSS memory increase of `wazuh-syscheckd` occurs, along with a stop event generation.

![image](https://user-images.githubusercontent.com/14913942/218828713-d35d4714-3be3-40da-b21f-59cda0f1933f.png)
![image](https://user-images.githubusercontent.com/14913942/218828735-06ecb35d-44b1-4bf7-95b4-ab7954134668.png)
![image](https://user-images.githubusercontent.com/14913942/218828764-b16c5e6c-2114-4fe7-a7a4-ec6315fc99d2.png)

<details><summary>Alpha2 and Beta1 CPU graphs</summary>

Alpha 2
![image](https://user-images.githubusercontent.com/14913942/218828853-7095c36e-82c8-4ebc-bfaf-a734e5561941.png)

Beta 1
![image](https://user-images.githubusercontent.com/14913942/218828866-c1ff6c40-7500-4e19-9dc8-11d573deb23d.png)

</details>

<details><summary>Alpha2 and Beta1 generated events graphs</summary>

Alpha 2
![image](https://user-images.githubusercontent.com/14913942/218830777-f4f35319-111e-4419-af37-dfe7f210a985.png)

Beta 1
![image](https://user-images.githubusercontent.com/14913942/218830809-28784719-adbe-4061-980d-0ec8c60e0534.png)

</details>

Related: 
- https://github.com/wazuh/wazuh/issues/16164
- https://github.com/wazuh/wazuh/issues/15780
- https://github.com/wazuh/wazuh/issues/15928

**Comment by jotacarma90** [comment]
## Research

Hello team,

after investigating this strange behavior, I have found that syscheck has stopped generating events because the test has stopped running, so syscheck did not find any event (syscheck has continued to launch scans without problems).

The stress test tried to read the `ossec.log` file during a daily rotation, and when it could not read it, an exception was raised, `fimError.log`:

```
[2023-02-12_00:00:10] Error launching stress functions, Exception: [Errno 2] No such file or directory: '/var/ossec/logs/ossec.log'
```

And it has stopped running. These are the last lines found in the test log file, `fim.log`:
```
[2023-02-12_00:00:09] [INFO] (create_delete): Creating files from 8185000 to 8190000.
[2023-02-12_00:00:10] [INFO] (create_delete): From 8185000 to 8190000 files successfully created.
[2023-02-12_00:00:10] [INFO] (create_delete): Creating directories from 0 to 5000.
[2023-02-12_00:00:10] [INFO] (create_delete): From 8185000 to 8190000 directories successfully created.
```

I have found that there is a parameter for the stress test itself that controls these readings of the ossec.log, `--check-log`.
