### ISSUE TITLE
we have enabled vulnerability feature today and its flooding alerts on jira and slack. is this vulnerabilities are legitimate? or should we disable the vulnerability opttion?

### ISSUE THREAD

**Issue by Kprince-k** [wazuh/wazuh#16224]
we have enabled vulnerability feature today and its flooding alerts on jira and slack. is this vulnerabilities are legitimate? or should we disable the vulnerability option?

AZUH Alert
CVE-2021-31872 affects libklibc
Agent
(014) - [aims.stg.sboxdc.com](http://aims.stg.sboxdc.com/)
Location
vulnerability-detector
Rule ID
23506 (Level 13)
Today at 5:25 PM
[5:32](https://sboxnw.slack.com/archives/C03QD9LBF41/p1676548962238769)
WAZUH Alert
CVE-2021-31873 affects klibc-utils
Agent
(014) - [aims.stg.sboxdc.com](http://aims.stg.sboxdc.com/)
Location
vulnerability-detector
Rule ID
23506 (Level 13)
Today at 5:25 PM
[5:32](https://sboxnw.slack.com/archives/C03QD9LBF41/p1676548964845939)
WAZUH Alert
CVE-2021-31873 affects klibc-utils
Agent
(014) - [aims.stg.sboxdc.com](http://aims.stg.sboxdc.com/)
Location
vulnerability-detector
Rule ID
23506 (Level 13)
Today at 5:25 PM
[5:32](https://sboxnw.slack.com/archives/C03QD9LBF41/p1676548967636799)
WAZUH Alert
CVE-2021-31873 affects libklibc
Agent
(014) - [aims.stg.sboxdc.com](http://aims.stg.sboxdc.com/)
Location
vulnerability-detector
Rule ID
23506 (Level 13)

**Comment by MarcelKemp** [comment]
Hi @Kprince-k,

[Vulnerability Detector](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/index.html) is a legitimate Wazuh module, which checks for vulnerabilities based on the packages collected by Syscollector and existing vulnerabilities in the [official feeds](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/how-it-works.html#compatibility-matrix), cross-correlating this information to warn of vulnerabilities affecting the agent.

Note that at the beginning, when running the `baseline` scan, it is normal that an alert appears for each vulnerability detected in each agent, however, once they have been alerted for the first time, it will only alert of new vulnerabilities that affect the system or vulnerabilities that have been fixed. In addition, the vulnerabilities that will appear in the _Jira_ and _Slack_ alerts will normally be the ones with the highest severity (so their alert will have a high level, such as _13_) and this will cause it to be shown in both integrations (although it will depend on the configuration of these two integrations).

More information, in the [Scan types](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/scan-types.html) shown in the documentation.

In this case, the alerts you have shared indicate that the agent is vulnerable to the vulnerabilities `CVE-2021-31872` and `CVE-2021-31872`, due to the `klibc` component being out of date. To fix this vulnerability in the agent, you simply need to update the component to a version higher than `2.0.9` (on most OSes)  or uninstall the component.

This information is usually displayed in the **`condition`** field of the vulnerability, where it will tell you which condition causes the agent to be vulnerable. On the other hand, you can also check the official links that refer to the vulnerability, such as the following ones:
- NVD: https://nvd.nist.gov/vuln/detail/CVE-2021-31873
- Debian: https://security-tracker.debian.org/tracker/CVE-2021-31873
- Ubuntu: https://ubuntu.com/security/CVE-2021-31873

I hope this helps you to understand how Vulnerability Detector works.
If you have any questions, don't hesitate to ask.

**Comment by Kprince-k** [comment]
Hi @MarcelKemp 

Thank you for the update. yeah now the alerts are not triggering.

**Comment by Kprince-k** [comment]
Hey @MarcelKemp 

Just wanted to know, where can i find the **conditions** of vulnerabilities?

**Comment by MarcelKemp** [comment]
Hi again @Kprince-k,

The `<condition>` field can be found in the following areas:
- In the case of alerts, it is found in the section: `data.vulnerability.package.condition`, telling you why that package is vulnerable.
  - JSON alert:
  ```JSON
  "data": {
      "vulnerability": {
        "severity": "High",
        "package": {
          "condition": "Package unfixed",
  ...
  ```
  - Dashboard alert image:
  ![image](https://user-images.githubusercontent.com/37207742/220582247-be6fdf2c-5237-48ce-b249-3406203d3485.png)

- If you want to see it in the dashboard inventory, simply clicking on a vulnerability, it should show you more information about that vulnerability, and among that information, the `Condition` field will be indicated.
  - Inventory image:
  ![image](https://user-images.githubusercontent.com/37207742/220581365-619e134c-d96a-41b5-bb6e-bcbc88e94b12.png)


> You can see both examples in the following link of the documentation: https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/configuring-scans.html

I hope you find it useful.

**Comment by Kprince-k** [comment]
Hi @MarcelKemp 

Thanks alot of this informations. it helps me alot in the analysis.

Thanks 
Prince

**Comment by MarcelKemp** [comment]
@Kprince-k I am closing this issue. Feel free to reopen it if you still have any other doubts about this.
