### ISSUE TITLE
`wazuh-modulesd` shows high CPU usage momentarily

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#16234]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| At least v4.4.0 | wazuh-modulesd | Agent | Packages | CentOS 7 |

- In a second review of the Vulnerability Detector stress tests with @alberpilot and @okynos, a small variation in the behavior of CPU usage of the `wazuh-modulesd` daemon has been observed. This daemon has usage peaks of `10%` throughout the test, except at a specific time when usage reaches the value of `70%`
- This behavior is observed in RC1, Beta1, and Alpha2 but not in Alpha1

RC1
![image](https://user-images.githubusercontent.com/14913942/219436339-f84afad5-d05f-4c70-b7aa-17d562937c6a.png)

Beta1
![image](https://user-images.githubusercontent.com/14913942/219436389-8c8b4722-21d7-492a-a07e-71a2f1714139.png)

Alpha2
![image](https://user-images.githubusercontent.com/14913942/219436453-b90a1651-dc7c-46e2-bc6b-9c0f008e3e09.png)

Alpha1
![image](https://user-images.githubusercontent.com/14913942/219437335-12d2cbb3-6e12-4c60-833d-10271ba26b98.png)

- This behavior has not always been observed but there are traces of similar behavior in 4.3.x, with lower values:

![image](https://user-images.githubusercontent.com/14913942/219438754-a89667f7-b830-4a07-8c0d-c98255fabb3e.png)

Related:
- https://github.com/wazuh/wazuh/issues/16161
- https://github.com/wazuh/wazuh/issues/15927
- https://github.com/wazuh/wazuh/issues/15789
- https://github.com/wazuh/wazuh/issues/15589
- https://github.com/wazuh/wazuh/issues/14384

It is necessary to determine if this behavior is acceptable or not.

**Comment by vikman90** [comment]
## Comparing CPU time

![CPU time](https://user-images.githubusercontent.com/10536251/219453542-60fa6209-badb-468c-91b0-d399db5c1548.png)

### Configuration

- Vuln Detector enabled, NVD + Ubuntu Jammy.
- Syscollector & SCA disabled.

### Monitoring command

```shell
while true
do 
    echo -n "`date +%R:%S`;"
    ps aux | grep -v grep | grep wazuh-modulesd | awk {'print $3 ";" $10'}
    sleep 1
done
```

**Comment by vikman90** [comment]
Hi, I have repeated the test under the same conditions, but this time I've read the data directly from _/proc_.

## Setup

### Settings

- Vulnerability Detector enabled, NVD + Ubuntu Jammy.
- Syscollector & SCA disabled.

### Monitoring command

```shell
unset pid

while [ -z "$pid" ]
do 
    pid=`cat /var/ossec/var/run/wazuh-modulesd-*.pid`
done 2>/dev/null

while true
do 
    echo -n "`date +%R:%S`;"    
    awk {'print $14 ";" $15'} /proc/$pid/stat
    sleep 1
done
```

## Results

### Instant CPU usage

![CPU usage](https://user-images.githubusercontent.com/10536251/219584085-52ce9db1-59bc-4f3e-91f5-566eaeb63b44.png)

### Total CPU time

![Total CPU time](https://user-images.githubusercontent.com/10536251/219584141-06b4d18c-775b-4158-a322-754e1348e9d5.png)

|Alpha 1|RC 1|Percentage difference|
|---|---|---|
|238.7 s|240.42 s|0.72 %|

## Conclusion

I think these peaks have been circumstantial and may be caused by two threads doing some little work. I don't think this is a problem.
