### ISSUE TITLE
Wazuh Managers : High CPU observed due to wazuh-syscheckd module

### ISSUE THREAD

**Issue by skhanum** [wazuh/wazuh#16250]
Hello Team,

We have agents and Managers with below version
Wazuh Managers : 4.3.9
Wazuh Agents: 4.3.6

We have a business critical VM on which Wazuh Agent is installed. Due High CPU consumption on the VM, other process went down that caused the VM to crash
After investigation, it was observed that Wazuh-syscheckd module consumed High CPU that remain constant for 30-40 mins
As a test, Wazuh agent services were disabled and the VM was back to its working stable condition

Because it was a bussiness critical VM, we had to uninstall Wazuh agent as it was impacting production.

As the Wazuh agent was uninstalled, we do not have the available logs 
We are looking for recommendations that could be a config change etc that can be configured to delay wazuh-syscheckd scan so that it does not overwhelm the VM

Please let us know if any questions. Happy to answer them.

**Comment by sultanovich** [comment]
Hi @skhanum , initially I will ask you if you can share with us more information about the agent with problems in order to analyze the error. Would it be possible for you to complete the following table with the information on the type of installation and the platform?


|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.6 | Wazuh-syscheckd | Agent | Packages/Sources ? | OS version ?  |


Also, I will ask you if you can share with us how you have identified the Wazuh-syscheckd process as the cause of the high CPU consumption and if you can verify if the Wazuh logs still exist on the computer even if you have uninstalled the agent (on this path in linux: `/var/ossec/logs/ossec.log`). One special comment in this case, have you tried to leave the agent down before uninstalling it?.

If you had logs from the virtual machine at the time of the problem that you could share with us they would also be very useful (please remember to remove any private or sensitive information from the events you send us before doing so).

**Comment by skhanum** [comment]
Hi @sultanovich 

Thanks a lot for looking into this for me
Install method : From Wazuh Packages
Platform : Ubuntu 18.04 

At the time of the issue, "Top" command was issued and we observed wazuh-syscheckd module was taking up the highest CPU
The VM was in this state for more than 30 mins until we forcefully had to stop wazuh-agent services on the VM
Post this, the CPU was freed and other processes that crashed were recovered 

Yes, the agent was down for close to 1hr and the VM remained stable during this time. We did a final test by uninstalling the wazuh agent packages and monitored for a day. Wazuh agent was installed after a day and 5 days of close monitoring, we have not observed the issue yet.
As this was a business critical VM, there was an impact on business until we identified it

Unfortunately, we do not have the logs at the time of issue, but if the issue reoccurs , please let me know what logs/details you will be needing so that I can collect them
Also, if you could please help with the best practices for wazuh-syscheckd module so that the CPU can be made more stable

**Comment by skhanum** [comment]
Hello @sultanovich 
I wanted to followup on this to check if you got a chance to review my comment above

**Comment by sultanovich** [comment]
Hi @skhanum ,

Thanks for the information, glad to see that you have been able to install the agent again and it is behaving properly at this point.

Just to confirm and update the first comment, did you install the agent using the [Ubuntu repository](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html) or by downloading the [.deb package](https://documentation.wazuh.com/current/installation-guide/packages-list.html#linux) and installing it manually?

Regarding the steps to follow in case you have a new problem with an agent, I could share general recommendations because then, depending on the type of error and component, surely the information and necessary tests could vary a little bit. But in general, in case of a problem with an agent, you could perform the following steps.

#### - If you can afford to take additional data before restoring the service:

 - Enable agent log to debug mode: 
   - Set `agent.debug=2` in the `/var/ossec/etc/internal_options.conf` file ([documentation](https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#agent)). 
 - Enable affected component log to debug mode (taking `syscheck` component as an example): 
   - Set `syscheck.debug=2` in the `/var/ossec/etc/internal_options.conf` file ([documentation](https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#syscheck)).
 - Restart the agent to apply the changes: `systemctl restart wazuh-agent` 
 - Replicate the issue or wait for the identified event 
 - Copy the Wazuh log file located in the path: `/var/ossec/logs/ossec.log` to a backup location. 
 - If you consider that there may be relevant information in the operating system logs at the time the incident occurred, copy the file to a backup location. In the case of ubuntu, by default, they are located in this path: `/var/log/syslog` 
 - Disable agent log debug mode: 
   - Set `agent.debug=0` in the `/var/ossec/etc/internal_options.conf` file.
 - Disable the debug mode of the affected component's registry (using `syscheck` as an example): 
   - Configure `syscheck.debug=0` in the file `/var/ossec/etc/internal_options.conf`. 
 - Stop the Wazuh agent and disable it from automatic startup: `systemctl disable wazuh-agent; systemctl stop wazuh-agent` .


#### - If you need to restore the service as soon as possible:

 - Copy the Wazuh log file located at the path: `/var/ossec/logs/ossec.log` to a backup location. 
 - If you think there may be relevant information in the operating system logs at the time the incident occurred, copy the file to a backup location. In the case of ubuntu, by default, they are located in this path: `/var/log/syslog` 
 - Stop the Wazuh-agent and disable it from automatic startup: `systemctl disable wazuh-agent; systemctl stop wazuh-agent` .


In both cases, _**remember to verify that the log files you will share do not include credentials or sensitive information before including it in an issue**_.

Although it depends on several factors (such as computing power, permissions, confidentiality of information, etc.), if possible you could also clone the virtual machine at the time of the error and then take additional data. Although this last point is generally not feasible and is somewhat cumbersome, it is worth mentioning.

If for some reason it is necessary to uninstall the agent, you can create a backup of your Wazuh agent installation to restore the agent information when you install it again with [this documentation](https://documentation.wazuh.com/current/user-manual/files-backup/wazuh-agent.html).

**Comment by sultanovich** [comment]
Hi @skhanum,

Yes, you can modify the [frequency](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html?highlight=Syscheck#frequency) with which syscheck is executed by modifying the frequency option in its section of the `ossec.conf` file.

```
<frequency>43200</frequency>
```


Depending on your needs you could also analyze the option of [scheduling the scans](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/fim-configuration.html#configuring-scheduled-scans) or [lowering the priority](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/fim-configuration.html#configuring-syscheck-process-priority) of this task to consume less CPU resources. 
Here what you should analyze in your environment to find the right configuration is how fast you need to have this information available and how many resources you want to allocate for it.

You may also find useful the other examples given in the syscheck documentation, [here](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/fim-configuration.html#configuration) you will be able to find the list of them.

**Comment by skhanum** [comment]
Thanks a lot for all your suggestions @sultanovich 
We can close this ticket.
Will reach out for help in future

**Comment by sultanovich** [comment]
Hi @skhanum , perfect. If you have any other questions or queries feel free to drop us a line again.

[Our community comes first](https://wazuh.com/community/), and we are proud to have one of the fastest growing open source communities in the world. 
Wazuh has several community contact channels, the first one is the [Slack](https://join.slack.com/t/wazuh/shared_invite/zt-1lgu531ur-7M_k_ZQbpdo4QCn_pHee3w) `#community` channel. All queries made here we try to answer them within the day (usually in less than a couple of hours). 
We also have a new `#community` channel on [Discord](https://discord.gg/75JBUfKSEW) which follows the same line as the Slack `#community` channel.

If you want to find out about new releases, technical articles on our blog, ask questions or share your experience with other wazuh users these are the right channels.
