### ISSUE TITLE
How to add white list to the Vulnerabilities module

### ISSUE THREAD

**Issue by PhuketIsland** [wazuh/wazuh#16269]
I want to add the ultra-high-risk vulnerabilities in the Vulnerabilities module to the white list. How do I do this?
![image](https://user-images.githubusercontent.com/28825226/220855135-334b00bf-58a1-4519-bf78-5014e24b02d4.png)
As shown in the figure above, I don't want this warning to exist. How can I add a white list?

**Comment by PhuketIsland** [comment]
![image](https://user-images.githubusercontent.com/28825226/220856432-2178a8ed-ecb6-4f3f-8578-73d31edd4bf0.png)
As shown in the figure above, I want to ignore this alarm or I want to mark it as processed. What should I do?

**Comment by MarcelKemp** [comment]
Hi @PhuketIsland,

Sorry, but it is not yet possible to hide a vulnerability reported by Wazuh with a whitelist by the user, although we are working on it so that in future versions the user will be able to indicate the vulnerability as _“not vulnerable”_ or hide it.

Here is the issue where we are working to add these options so that you can follow its progress:
- https://github.com/wazuh/wazuh/issues/14153

In the case of SCA, I am afraid that it is currently not possible to ignore a check from the configuration or from the WUI. However, we already have an opened issue included in our roadmap to be able to ignore checks that don’t apply to specific situations like yours:
- https://github.com/wazuh/wazuh/issues/3596
- https://github.com/wazuh/wazuh/issues/12394

I hope we can handle it ASAP.

In the meantime, you can create a **[custom SCA policy](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/creating-custom-policies.html)** where removing the undesired checks and apply that custom policy to your agents.

Sorry for the inconvenience.
