### ISSUE TITLE
Engine - Research on integrations and engine policies

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#16261]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
During our implementation of the first decoders, we identified we needed a way for users to interact with their decoders, rules and environments by device supported, instead of by single decoder or rule.

It is necessary to make an investigation on this, with emphasis on:
### Engine policy
An engine policy is a set of decoders, rules and outputs bound by a name and a version.
A user should be able to interact with engine policies easily. We want to offer our user:
- The ability to add or remove an integration into an engine policy
- The ability to add or remove a single decoder / rule to an engine policy
- The ability to customize parts of an integration
- The ability to select which events go to each engine policy

### Integration
An integration comprehends the security policy, schema, configuration and documentation on how to integrate an events source into Wazuh.
We want a clear way for our users to interact with these integrations, and a clear way for our community to develop and maintain them.
- An integration must ensure a user is able to configure Wazuh end-to-end to:
- Acquire events from a supported device or system
- Transform these events to the ECS based events
- Enrich these events with security related information
- Index the events, making them available for further analysis
- Ensure all fields generated are present in the schema and has a corresponding data mapping
- Ensure all fields generated can be validated by our development tools before sending the implementation of the integration into the engine

**Comment by JcabreraC** [comment]
## Univocal identification of logs
According to the issue, we need to study how to uniquely identify an event.

For this, we are working on an issue that will allow the log generated in the agent to reach the engine in json format with a tag that identifies it. You can read more information about this [here](https://github.com/wazuh/wazuh/issues/16263).

On the other hand, we need to check if we have a field to identify the logs of the wazuh wodles.

### Supported services

<details><summary>Github</summary>

`"location":"github"`

```
{
    "timestamp":"2021-04-29T16:40:33.955+0000",
    "rule": {
        "level":5,
        "description":"GitHub Team add member.",
        "id":"91393",
        "firedtimes":8,
        "mail":false,
        "groups": ["github","git"]
    },
    "agent": {
        "id":"000",
        "name":"ubuntu"
    },
    "manager": {
        "name":"ubuntu-bionic"
    },
    "id":"1619714433.146108",
    "decoder": {
        "name":"json"
    },
    "data": {
        "github": {
            "action":"team.add_member",
            "actor":"member_name",
            "@timestamp":"1619031743300.000000",
            "org":"org_name",
            "created_at":"1619031743300.000000",
            "user":"User",
            "_document_id":"9Z1pUC7N0GBf4ZzZFQEXpA",
            "source":"github"
        }
    },
    "location":"github"
}
```
</details>

<details><summary>Office 365</summary>

`"location":"office_365"`

```
{
    "agent":
    {
        "name": "eridu",
        "id": "000"
    },
    "manager":
    {
        "name": "eridu"
    },
    "data":
    {
        "office_365":
        {
            "OrganizationName": "wazuh.onmicrosoft.com",
            "ResultStatus": "True",
            "ObjectId": "EURPR04A010.prod.outlook.com/Microsoft Exchange Hosted Organizations/wazuh.onmicrosoft.com/PeopleDirectoryShard_eur_replica_2",
            "UserKey": "NT AUTHORITY\\SYSTEM (w3wp)",
            "ExternalAccess": "true",
            "Operation": "New-Mailbox",
            "OrganizationId": "sanitized",
            "ClientIP": "sanitized",
            "Workload": "Exchange",
            "RecordType": "1",
            "OriginatingServer": "sanitized",
            "Version": "1",
            "UserId": "NT AUTHORITY\\SYSTEM (w3wp)",
            "CreationTime": "2020-03-19T15:32:02",
            "Id": "sanitized",
            "UserType": "3"
        }
    },
    "rule":
    {
        "firedtimes": 26,
        "mail": false,
        "level": 5,
        "description": "Exchange New-Mailbox operation.",
        "groups":
        [
            "office_365"
        ],
        "id": "100002"
    },
    "location": "office_365",
    "decoder":
    {
        "name": "json"
    },
    "timestamp": "2020-03-20T12:19:08.694+0000"
} 
```

</details>

</details>

<details><summary>AWS-s3</summary>

`"location":"aws-s3"`

```
{
  "timestamp": "2022-08-19T06:23:54.940+0000",
  "agent": {
    "id": "***",
    "name": "",
    "ip": "**"
  },
  "manager": {
    "name": "wazuh-manager-worker-1"
  },
  "id": "1660****",
  "cluster": {
    "name": "j***",
    "node": "wazuh-manager-worker-1"
  },
  "full_log": "DEBUG: Getting data from DB for log stream \"*****8\" in log group \"/aws/co****/us******/us-east-1_******/Re***\"",
  "decoder": {},
  "location": "aws-s3"
}
```
</details>

**Comment by JavierBejMen** [comment]
## Research rsyslog
We want to label messages coming from the agent to identify the Integration without force brute parsing. Rsyslog allows specifying the facility and the tag in the configuration:
```
$ModLoad imfile
$InputFileName /tmp/integration_test.log
$InputFileTag my_program
$InputFileStateFile program_file
$InputFileSeverity info
$InputFileFacility local7
$InputRunFileMonitor
```

The facility is mixed in the [PRI](https://www.rfc-editor.org/rfc/rfc5424#section-6.2.1) code of the syslog header, as we can see on the message received on remoted:
```
# tcpdump -i any port 514 -AA | grep INTEGRATION
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked v1), capture size 262144 bytes
.......}d.......E..{..@.?......*...@.....g.s<190>Feb 24 09:59:19 ubuntu-agent my_program message repeated 4 times: [INTEGRATION TEST LOG 2]
.......}d.......E.._..@.?......*...@.....K..<190>Feb 24 09:59:19 ubuntu-agent my_program INTEGRATION TEST LOG 3
.......}d.......E..{..@.?......*...@.....g.r<190>Feb 24 09:59:19 ubuntu-agent my_program message repeated 3 times: [INTEGRATION TEST LOG 3]
.......}d.......E.._..@.?......*...@.....K..<190>Feb 24 09:59:19 ubuntu-agent my_program INTEGRATION TEST LOG 4
.......}d.......E.._..@.?......*...@.....K..<190>Feb 24 09:59:29 ubuntu-agent my_program INTEGRATION TEST LOG 5
```
But this field is not forwarded to the engine on a first preview:
![image](https://user-images.githubusercontent.com/32262972/221153422-079c7ac2-cf56-4c25-a915-4a866eded3d7.png)

Also, as specified in the syslog protocol, there are only 7 custom facilities, limiting the number we can use for our integrations, and does not support the multi-labeling approach researched in #16087.

The TAG field of the message part is correctly set and received by the Engine. This can be used to identify the integration, though it is usually the program name, as specified in the [RFC](https://www.rfc-editor.org/rfc/rfc3164#section-4.1.3), added it won't support the multi-label approach we are researching in #16087 without a tricky parsing or some other workaround.

### Remoted
remoted removes the syslog header here:
https://github.com/wazuh/wazuh/blob/bc0b67dc1affdc8838d23eaaa72478d215a3fd22/src/remoted/syslog.c#L89-L99

### TAG approach
Trying to embed a JSON in the TAG using the [legacy](https://www.rsyslog.com/doc/v7-stable/configuration/modules/imfile.html#legacy-configuration-directives) configuration file (currently used in our [blog](https://wazuh.com/blog/how-to-configure-rsyslog-client-to-send-events-to-wazuh/)):
```
$ModLoad imfile
$InputFileName /tmp/integration_test.log
$InputFileTag {"integration": "my_integration", "version": 1.0.0} 
$InputFileStateFile program_file
$InputFileSeverity info
$InputFileFacility local7
$InputRunFileMonitor
```
Rsyslog truncates it after the double colon character:
```
# tcpdump -i any port 514 -AA | grep INTEGRATION
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked v1), capture size 262144 bytes
.......}d.......E..e..@.?......*...@.....Q..<190>Feb 24 10:44:30 ubuntu-agent '{"integration": INTEGRATION TEST LOG 0
.......}d.......E..f..@.?......*...@.....R.m<190>Feb 24 10:44:30 ubuntu-agent '{"integration": INTEGRATION TEST LOG 01
.......}d.......E..g..@.?......*...@.....S.k<190>Feb 24 10:44:30 ubuntu-agent '{"integration": INTEGRATION TEST LOG 012
.......}d.......E..h..@.?......*...@.....T.6<190>Feb 24 10:44:30 ubuntu-agent '{"integration": INTEGRATION TEST LOG 0123
.......}d.......E..i..@.?......*...@.....U.4<190>Feb 24 10:44:40 ubuntu-agent '{"integration": INTEGRATION TEST LOG 01234
```

The TAG has a limited length and is truncated, defining the same on `rsyslog.conf` results in the same behavior.

## Conclusion
If we want to use an arbitrary JSON further research is needed, otherwise, the TAG field could be used.
To use the facility code we need to modify the referenced code to not eliminate the syslog's header and decode the PRI code.

**Comment by JavierBejMen** [comment]
## Update
We have researched and made a proposal for the integrations as a concept.

It is documented in the [design document](https://docs.google.com/document/d/125d8tpj192MNdggLcNjk_R0tQWEuhjBEmtjONHbUkHo/edit#bookmark=id.fue8eqwczqiu) and the [user manual](https://docs.google.com/document/d/1N0p7pd7XszQwFU9HBjpB7txIw2DCcAsV-BKfEZSLixw/edit#bookmark=id.5fvve2a4qcwm)

The following steps would be to adapt the current ruleset and tooling to work with integrations.
