### ISSUE TITLE
wazuh-dbd: ERROR: (5207): Wazuh not compiled with support for 'mysql'.

### ISSUE THREAD

**Issue by v1per4llbl4ck** [wazuh/wazuh#16278]
2023/02/24 11:01:37 wazuh-dbd: ERROR: (5207): Wazuh not compiled with support for 'mysql'.
2023/02/24 11:01:37 wazuh-dbd: CRITICAL: (1202): Configuration error at 'etc/ossec.conf'.
wazuh-dbd: Configuration error. Exiting
wazuh-manager.service: Control process exited, code=exited, status=1/FAILURE
![Screenshot_20](https://user-images.githubusercontent.com/82314915/221151777-decaff7f-a627-40d1-b868-6e9bc597b81c.png)

**Comment by chemamartinez** [comment]
Hi @v1per4llbl4ck,

**Comment by chemamartinez** [comment]
Hi @v1per4llbl4ck,

Unfortunately, the support for the database output of alerts is not included in Wazuh by default. I am afraid you have to recompile your manager from sources in order to enable this support and reinstall it.

Please, take a look at [this guide](https://documentation.wazuh.com/current/user-manual/manager/manual-database-output.html) about how to configure the database output.

I hope this helps! Don't hesitate to ask if you have any other questions.

**Comment by chemamartinez** [comment]
Hi @v1per4llbl4ck,

I am closing this issue. Feel free to reopen it if you still have any other doubts about this.
