### ISSUE TITLE
Apt update & upgrade breaks install

### ISSUE THREAD

**Issue by Untangled5132** [wazuh/wazuh#16287]
Not sure what I'm missing here.  Installed the all in one packages on both debian and ubuntu server.  I did both unattended and step by step which both work out just fine and the WUI is accessible and all, but running an apt update & upgrade completely breaks everything and last time i tried re-installing it just created a broken install and a bigger mess.  I wiped everything and restarted from scratch and the same thing happens.

I can't find this anywhere online or in the guide.  I'm assuming I don't have to go into detail in my findings as i'm sure this is something that's known since it's done it on 2 systems and i must be missing something that i can't figure out.  Am i supposed to remove the packages from apt package manager after installation so that they don't update when i run apt update and upgrade on the system?

Thanks

**Comment by sultanovich** [comment]
Hi @Untangled5132 ,

From what I understand you have started Wazuh environments using the [quickstart](https://documentation.wazuh.com/current/quickstart.html) documentation and the [step by step](https://documentation.wazuh.com/current/installation-guide/index.html) on Debian and ubuntu with no problems. But then you have encountered an error while upgrading. 
Could you please confirm the following details of any of the environments where you have tested it to identify what may be the problem?. 


|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager | Packages/Sources | OS version |



Additionally, can you tell us if you see any error message and if the problem is when upgrading the Wazuh installation or when upgrading the operating system?

**Comment by sultanovich** [comment]
Hi @Untangled5132, Don't worry. I understand that if you have made a new installation you do not have this information to share with us. Could you please confirm which version of Wazuh you installed to try to replicate the error?

The upgrade process as such is really simple and transparent as indicated in the documentation if you [upgrade Wazuh from 4.3.0](https://documentation.wazuh.com/current/upgrade-guide/upgrading-central-components.html) onwards. Before that version, you will have to perform [some additional steps](https://documentation.wazuh.com/current/upgrade-guide/index.html#upgrade-the-wazuh-central-components) as the new [Wazuh-indexer and Wazuh-dashboard](https://wazuh.com/blog/introducing-wazuh-4-3-0/) components did not exist yet and should replace Elasticsearch and Kibana.

Anyway, although the upgrade process is simple, it is a good measure in a productive environment to prevent the upgrade from being performed automatically by the system and you can perform it in a scheduled outage. This way you could avoid someone tries to access the wazuh web console and finding it unavailable or the registration of a new agent failing for the same reason. 

In Ubuntu/Debian you have several ways to do this using the various administrative tools available (for example using [apt-mark hold](https://manpages.debian.org/stretch/apt/apt-mark.8.en.html)). 
You could also choose to move the Wazuh repository file (`/etc/yum.repos.d/wazuh.repo`) out of the `/etc/yum.repos.d` directory or delete it and recreate it before upgrading.
