### ISSUE TITLE
How to add white list to the Vulnerabilities module？

### ISSUE THREAD

**Issue by PhuketIsland** [wazuh/wazuh#16288]
I want to add the ultra-high-risk vulnerabilities in the Vulnerabilities module to the white list. How do I do this?
![image](https://user-images.githubusercontent.com/28825226/221460338-e4d43c45-ba57-42eb-882d-7f4fb6a57415.png)
As shown in the figure above, I don't want this warning to exist. How can I add a white list?
![image](https://user-images.githubusercontent.com/28825226/221460453-31b20bce-742d-40ea-bf57-c50566b64be1.png)
As shown in the figure above, I want to ignore this alarm or I want to mark it as processed. What should I do?

**Comment by Dwordcito** [comment]
Hi.

Currently, Wazuh does not support excluding detections in the vulnerability detection module. However, it is possible to exclude certain alerts that are generated as a result of those detections. The exclusion feature in Wazuh allows users to suppress alerts for specific hosts, IP addresses, services, or other attributes that are known to be non-critical or otherwise not useful for the organization.

The tab shown in the GitHub issue that you linked is specifically related to the detections made by the vulnerability detection module. It displays the number of vulnerabilities detected for each host, as well as other information such as the severity of the vulnerability. However, at this time, it is not possible to exclude detections from this module.

As I mentioned earlier, the exclusion feature for detections in the vulnerability detection module is not currently supported in Wazuh. However, the good news is that a refactor of the module is currently underway, which will include the addition of exclusion functionality.

The refactor will improve the overall efficiency and accuracy of the module, as well as make it easier to customize and configure for specific use cases. The exclusion feature will allow users to exclude certain detections.

We appreciate your interest and contribution to the Wazuh community, and we look forward to being able to offer the exclusion functionality in future releases of Wazuh.

Refactor issue: https://github.com/wazuh/wazuh/issues/14153

**Comment by PhuketIsland** [comment]
Thanks!
