### ISSUE TITLE
how cluster work to deal with failure?

### ISSUE THREAD

**Issue by vochanhdai-016** [wazuh/wazuh#1628]
_Originally posted by @mgmacias95 in https://github.com/wazuh/wazuh/issues/391#issuecomment-366084834_
In the example "...If node 2 is stopped, then agent B would start reporting to node 1, if node 2 recovers, the agent will still report to node 2..." that @mgmacias95 gave, how Wazuh cluster work to do that?

**Comment by mgmacias95** [comment]
Hello @vochanhdai-016,

Wazuh agents can be configured with multiple [`server`](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#server) configuration blocks like the following one:
```xml
    <server>
      <address>192.168.185.4</address>
      <port>1514</port>
      <protocol>udp</protocol>
    </server>
```
These blocks define how the agent will connect with the Wazuh manager. When multiple blocks are defined, the agent will try to connect to every manager in the list until it finally connects to one of them. Once connected, it won't switch to another manager until it's disconnected again.

The cluster can't do load balancing using this approach since it can't control how servers are defined in agent configurations. That's why it's recommended to use a [load balancer](https://documentation.wazuh.com/current/user-manual/manager/wazuh-cluster.html#pointing-agents-to-the-cluster-with-a-load-balancer) instead.

Best regards,
Marta

**Comment by vochanhdai-016** [comment]
thank you @mgmacias95. I've got it.
I have one more question: These configuration blocks are defined based on ALL worker nodes of the master which the agent registers to, do they?

**Comment by mgmacias95** [comment]
Hello @vochanhdai-016,

There must be one block for each worker in the master. But I insist in the load balancing solution since the cluster doesn't do load balancing by itself.

Best regards,
Marta

**Comment by mgmacias95** [comment]
Yes, that's correct.

**Comment by vochanhdai-016** [comment]
@mgmacias95 thanks a lot

**Comment by mgmacias95** [comment]
You're welcome @vochanhdai-016 ! Don't hesitate to reach us again if you need something else 😄 !
