### ISSUE TITLE
CVE-2022-26635 false positive

### ISSUE THREAD

**Issue by xl32** [wazuh/wazuh#16283]
|Wazuh version| Component | Action type |
|---| --- | --- |
| v4.3.10| Rules| Error |

## Description

I got a critical issue in php5-memcached lib on AlmaLinux 8 server: CVE-2022-26635 affects memcached; 
Condition: Package less or equal than 2.2.0
Version: 0:1.6.18-1.el8.remi

```
# rpm -qa| grep  memcached
memcached-selinux-1.6.18-1.el8.remi.x86_64
remi-libmemcached-awesome-1.1.3-1.el8.remi.x86_64
libmemcached-1.0.18-17.el8.x86_64
libmemcached-libs-1.0.18-17.el8.x86_64
memcached-1.6.18-1.el8.remi.x86_64
php-pecl-memcached-3.2.0-1.el8.remi.8.0.x86_64
```

I see that detection is made against latest memcached-1.6.18 package, not php5-memcached package. Please note that memcached pecl package version is 3.2.0 > 2.2.0.

### Current results

Critical vulnerability reported

### Expected results

Critical vulnerability should not be reported

**Comment by MiguelazoDS** [comment]
Hi @xl32, 

Thanks for the information, I'm afraid that this undesired behavior is expected since we do not support AlmaLinux natively yet. 
You can follow the state of the implementation here [https://github.com/wazuh/wazuh/issues/15980](url)

Could you please share your configuration? How did you configure the module to get vulnerabilities from Alma Linux. 
Maybe this? [https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/allow-os.html](url)

Take into account that Alma Linux is based on RHEL so the configuration should be inside that block. But since we are using a feed that is not exactly provided by Alma Linux, false positives are expected. 

Regards!

**Comment by xl32** [comment]
Hi @MiguelazoDS!

Thanks for your reply. We did it simple:
```
/var/ossec/etc/ossec.conf: 
<!-- RedHat OS vulnerabilities -->
<provider name="redhat">
<enabled>yes</enabled>
<os>5</os>
<os>6</os>
<os>7</os>
<os>8</os>
<os>9</os>
<os allow="Rocky Linux-8">8</os>
<os allow="Rocky Linux-9">9</os>
<os allow="AlmaLinux-9">9</os>
<update_interval>1h</update_interval>
</provider>
```

Also we use extremely popular Remi repository with php-related packages and want to have vulnerabilities management with Alma Linux and Rocky Linux OSes, as I believe they will be much more popular than rolling release CentOS.
If you need more specific configuration, please let me know.

Thank you for your work!

**Comment by MiguelazoDS** [comment]
Hi @xl32, 

Regardless of the false positives that may occur due to using the `os allow` option, I think you're right. I didn't find anything related to that vulnerability in the RHEL feeds so it is detecting vulnerabilities using the NVD feeds and as you mentioned it should be fine using a version above 2.2.0. 

What is the output of this to queries?

`sqlite3 /var/ossec/queue/vulnerabilities/cve.db 'select * from cpe_helper_source where term like "%memcache%"' --line`
`sqlite3 /var/ossec/queue/vulnerabilities/cve.db 'select * from cpe_helper_translation where term like "%memcache%"' --line`

 According to the NVD one package is:
 - `cpe:2.3:a:php:memcached:*:*:*:*:*:*:*:*`
 and the other is:
 - `cpe:2.3:a:memcached:memcached:*:*:*:*:*:*:*:*`
 
 So the detection should be fine, but it may be wrong about how the package is trying to match. 
 
 In the meantime, I will try to reproduce this. 
 
 Regards!

**Comment by xl32** [comment]
Thanks for your help @MiguelazoDS,

The output is empty:
```
# sqlite3 /srv/wazuh/volumes/wazuh_queue/vulnerabilities/cve.db 'select * from cpe_helper_source where term like "%memcache%"' --line
# sqlite3 /srv/wazuh/volumes/wazuh_queue/vulnerabilities/cve.db 'select * from cpe_helper_translation where term like "%memcache%"' --line
```

**Comment by xl32** [comment]
The output is:

```
     scan_id = 0
   scan_time = 2023/02/28 12:30:42
      format = rpm
        name = php-pecl-memcache
    priority =
     section = Unspecified
        size = 329174
      vendor = Remi's RPM repository <https://rpms.remirepo.net/>
install_time = 1645808738
     version = 8.0-1.el8.remi.8.0
architecture = x86_64
   multiarch =
      source =
 description = Extension to work with the Memcached caching daemon
    location =
     triaged = 1
         cpe =
    msu_name =
    checksum = 9aeae07597ea4fa3601721f68ac87ba6436f483d
     item_id = 62046401c93a2f25a58c4b7c41f20403ea3db6f1

     scan_id = 0
   scan_time = 2023/02/28 12:31:15
      format = rpm
        name = php-pecl-memcached
    priority =
     section = Unspecified
        size = 359242
      vendor = Remi's RPM repository <https://rpms.remirepo.net/>
install_time = 1665505444
     version = 3.2.0-1.el8.remi.8.0
architecture = x86_64
   multiarch =
      source =
 description = Extension to work with the Memcached caching daemon
    location =
     triaged = 1
         cpe =
    msu_name =
    checksum = b3a6578abed163af0ab4801efd454aa5d7125e64
     item_id = afbd1537617d2cabd6cd4fb54e415eb22bd2015e
```

I will rerun the scan and return with the log lines.

**Comment by MiguelazoDS** [comment]
Hi @xl32, 

Well, this output is what I expected. 

This is the information used to match vulnerabilities against NVD 
```
  name = php-pecl-memcached
  vendor = Remi's RPM repository <https://rpms.remirepo.net/>
```

And since you don't have any information in the tables `cpe_helper_source/translation` I don't see how vulnerability detector found a match for that package. 

And according to the agent 003 database, you're package `php-pecl-memcached` is not vulnerable (or in this case was not scanned)

Where did you notice that the package `php-pecl-memcached` was vulnerable? 

In addition, I forgot to tell you, I would like to see the logs in debug. 

Modify this `wazuh_modules.debug=0` to this `wazuh_modules.debug=2` in your `/var/ossec/etc/internal_options.conf` file and restart your manager
