### ISSUE TITLE
I encountered a problem when integrating enterprise WeChat

### ISSUE THREAD

**Issue by PhuketIsland** [wazuh/wazuh#16329]
First, paste my configuration
![image](https://user-images.githubusercontent.com/28825226/223030272-c51ed5ce-b87c-442a-9efd-5dc6e56f93e0.png)
**#!/usr/bin/env python

import sys
import json
import requests
from requests.auth import HTTPBasicAuth

# Read configuration parameters
alert_file = open(sys.argv[1])
user = sys.argv[2].split(':')[0]
api_key = sys.argv[2].split(':')[1]
hook_url = sys.argv[3]

# Read the alert file
alert_json = json.loads(alert_file.read())
alert_file.close()

# Extract issue fields
alert_level = alert_json['rule']['level']
ruleid = alert_json['rule']['id']
description = alert_json['rule']['description']
agentid = alert_json['agent']['id']
agentname = alert_json['agent']['name']
path = alert_json['syscheck']['path']

# Set the project attributes ===> This section needs to be manually configured before running!
project_key = 'WT'     # You can get this from the beggining of an issue key. For example, WS for issue key WS-5018
issuetypeid = '10002'  # Check https://confluence.atlassian.com/jirakb/finding-the-id-for-issue-types-646186508.html. There's also an API endpoint to get it.

# Generate request
headers = {'content-type': 'application/json'}
issue_data = {
    "update": {},
    "fields": {
        "summary": 'FIM alert on [' + path + ']',
        "issuetype": {
            "id": issuetypeid
        },
        "project": {
            "key": project_key
        },
        "description": {
            'version': 1,
            'type': 'doc',
            'content':  [
                    {
                      "type": "paragraph",
                      "content": [
                        {
                          "text": '- State: ' + description + '\n- Rule ID: ' + str(ruleid) + '\n- Alert level: ' + str(alert_level) + '\n- Agent: ' + str(agentid) + ' ' + agentname,
                          "type": "text"
                        }
                      ]
                    }
                  ],
        },
    }
}

# Send the request
response = requests.post(hook_url, data=json.dumps(issue_data), headers=headers, auth=(user, api_key))
#print(json.dumps(json.loads(response.text), sort_keys=True, indent=4, separators=(",", ": "))) # <--- Uncomment this line for debugging

sys.exit(0)**
I want to know how to see whether this script has been executed or reported an error, or can you help me solve the problem of how I can configure to allow enterprise WeChat to alarm

**Comment by jnasselle** [comment]
Hi @PhuketIsland,

Despite the fact I was not able to find WeChat API documentation (but as I can see you already did this), here is a step-by-step guide to developing your own custom integration

- **Make sure that you can push a "Hello World!" message to WeChat API**: Try to push a simple message to WeChat API using some simple tool like cURL command line tool or Postman. This way, you will be sure that the communication is working as expected
- **Troubleshoot the integration script**: Testing the script independently and manually will save you a lot of time. To make this possible you should provide the expected parameters
  - Parameters:
    - An temporary file that contains a single JSON alert: you can pick some alert from `alerts.json`  i.e /tmp/myexamplealert.json
    - API key: empty string if unused (seems to be your case)
    - API hook URL
    - Debug flag: empty string or "debug" string if you need to toggle debug log generation
  -  Example : python3 custom-integration "/tmp/myexamplealert.json" "" "https://REDACTED.api.weixin.qq.coREDACTED" "debug" 
- **Make sure that integration has the proper privileges and location**: the script should be located at `/var/ossec/integrations` with `750` and `root:wazuh`
- **Enable `wazuh-integratord` debug logs**: see https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#integrator

## Recommendations
- Create the new integration based on someone provided by default. For example, Slack integration. Copy that one and customize it. I assume you are following https://wazuh.com/blog/how-to-integrate-external-software-using-integrator/, which is outdated.
- WeChat API surely has a specific schema to provide the messages. Is mandatory to meet this schema in order to make the integration work
- Improve custom integration script name: `custom-wechat` could be a good one (remember that should always have `custom-` prefix)

**Comment by PhuketIsland** [comment]
Hi @jnasselle,
Thank you very much for your reply.
This debug log appears after I start the debugging function
![image](https://user-images.githubusercontent.com/28825226/223298326-186d4070-eef1-4a45-9cf1-0c6f548e1b30.png)

I can send a hello world to enterprise WeChat
![image](https://user-images.githubusercontent.com/28825226/223298673-f99f1b0e-8806-43bd-ad3a-15e308077356.png)
![image](https://user-images.githubusercontent.com/28825226/223298729-76c4c60d-82e1-4428-8e0b-71b9e6c9747b.png)
My script was not triggered. I don't know what I should do next

**Comment by jnasselle** [comment]
Hi @PhuketIsland,

Regarding `jqueue-next()`-like debug messages, they show the polling of alerts from `alerts.json`, so don't worry about them since they are expected.

We are trying to find logs that evidence the attempt and result of executing your integration. They should look like `2023/03/06 17:42:37 wazuh-integratord[416176] integrator.c:394 at OS_IntegratorD(): DEBUG: Running: integrations` and then follow some integration info.

If this kind of message doesn't appear, probably is related to the filters on your `integration` block that could not match any generated alert i.e no alert with level 7 or higher was created meaning that the integration will not be executed

I look forward to your comments

**Comment by PhuketIsland** [comment]
thanks
