### ISSUE TITLE
Study the use case, access patterns, and documentation for Amazon Security Lake subscribers

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#16330]
# Description

As part of the [integration of Wazuh as a subscriber in Amazon Security Lake](https://github.com/wazuh/wazuh/issues/16326), it is necessary to study the use case, access patterns, and documentation for other subscribers to identify best practices and potential challenges.

# Requirements
- Review and analyze the use case, access patterns, and [documentation for other Amazon Security Lake subscribers](https://docs.aws.amazon.com/security-lake/latest/userguide/integrations-third-party.html).
- Specify which data Wazuh will be consuming as a subscriber.
- Identify any potential limitations or challenges that may arise during integration.
- Document any lessons learned or best practices from other subscribers.

# Conclusion
Studying the use case, access patterns, and documentation for other Amazon Security Lake sources is an important step in integrating Wazuh as a source. By identifying potential limitations and best practices, we can ensure a successful integration that meets the requirements of the system. The result of this task will be a report that documents the lessons learned, best practices, and potential limitations or challenges that may arise during integration.

**Comment by Selutario** [comment]
## Status update

Work is still in progress. Most third-party subscribers listed [here](https://docs.aws.amazon.com/security-lake/latest/userguide/integrations-third-party.html#third-party-subscribers) do not share any specific documentation about how to integrate their product with Amazon Security Lake. These are the exceptions:
- **[Datadog](https://atos.net/en/about-us/partners-and-alliances/amazon-web-services):** They have their own AWS account. An `ExternalID` is created and shared for each customer to send ASL data to Datadog. HTTPS endpoint (EventBridge) is used in order to get notified when new parquet files are available.
- **[Splunk](https://github.com/splunk/splunk-add-on-for-amazon-security-lake/blob/main/Splunk%20Add-on%20for%20Amazon%20Security%20Lake.pdf):** The customer's account is used for fetching ASL data. An SQS queue is proposed and the Splunk addon is in charge of processing parquet files and ingesting the data.
- **[Rapid7](https://docs.rapid7.com/insightidr/aws-security-lake/):** As for Splunk, in Rapid7 the customer's account is used to fetch data. Parquet files are not processed in Rapid7, an AWS lambda function takes care of it. SQS queue is used.
- **[SumoLogic](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/amazon-security-lake-source/):** Very similar to Datadog case. They have an AWS account that gives an individual `ExternalID` for each customer. HTTPS endpoint is enabled to get notified when new data is available. 

WIP
