### ISSUE TITLE
Maximum buffer length reached error with `GET /agents/{agent_id}/stats/{component}` endpoint

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#16379]
# Description

A community user has reported an issue where the agent stats cannot be adequately fetched through the API.

![image](https://user-images.githubusercontent.com/48716145/224955576-51869cb4-747f-485c-8ee0-d426fda703f7.png)

The error occurs when accessing the stats dashboard from the agents in the UI, but only for some registered agents. The error message is:

![image](https://user-images.githubusercontent.com/48716145/224955863-14024d34-708a-425a-b4c3-9aedd41b1f8a.png)

# Steps to reproduce

We received help from @vikman90, who took the following steps to reproduce the error:

1. Wazuh API endpoint call -X GET https://localhost:55000/agents/005/stats/logcollector works properly:

```
{
  "data": {
    "affected_items": [
      {
        "global": {
          "start": "2023-03-14 08:34:13",
          "end": "2023-03-14 08:36:13",
          "files": [
            {
              "location": "last -n 20",
              "events": 1,
              "bytes": 870,
              "targets": [
                {
                  "name": "agent",
                  "drops": 0
                }
              ]
            },
            .
            .
            .
            {
              "location": "df -P",
              "events": 0,
              "bytes": 0,
              "targets": [
                {
                  "name": "agent",
                  "drops": 0
                }
              ]
            }
          ]
        }
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Statistical information for each agent was successfully read",
  "error": 0
}
```

2. To force the error, run the following command to create a large number of log files. The localfile XML configuration is necessary to ensure that all the log files are processed:

```
<localfile>
  <log_format>syslog</log_format>
  <location>/root/logs/*.log</location>
</localfile>
```

`for i in {0..900}; do touch /root/logs/my-log-for-any-thing-example-$i.log; done
`

3. Wazuh API endpoint call -X GET https://localhost:55000/agents/005/stats/logcollector now fails:
```
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 1,
    "failed_items": [
      {
        "error": {
          "code": 1117,
          "message": "Unable to connect with component. The component might be disabled.: Maximum buffer length reached"
        },
        "id": [
          "005"
        ]
      }
    ]
  },
  "message": "Could not read statistical information for any agent",
  "error": 1
}
```

4. The agent log shows the following error message:
```
2023/03/14 08:47:59 wazuh-agentd[9033] os_net.c:701 at OS_RecvSecureTCP(): ERROR: msgsize > size: 176462 > 65536
2023/03/14 08:47:59 wazuh-agentd[9033] request.c:309 at req_receiver(): DEBUG: Maximum buffer length reached.
```

**Comment by thejbte** [comment]
Hi @vikman90 , regarding this [issue](https://github.com/wazuh/wazuh/issues/16379), what do you think of the solution?

Problem: 
When you want to get the stats of an API agent, it returns a "Maximum buffer length reached" error
when configured to monitor all files in a folder, if many files are created even less than the maximum file size allowed in internal_options, the error is thrown.
Analysis: The error occurs because the lccom module returns all the json data with the statistics, which for the case of 900 files have an approximate length of 176000 and req_receiver:OS_RecvSecureTCP receives a maximum of 64k (65536), that's why it shows the error , if you increase the length of the buffer, it reads it, but already throws an error when encrypting.

Solutions:
1: lccom sends a maximum of 64k and displays a warning saying that X number of Y's have been read in total, the rest cannot be displayed.

Alternative solution:
2: segment the json into 64k pages, from the api you can check how many pages there are according to the number of files existing at that time and be able to send the stats query which page you want to observe.

**Comment by vikman90** [comment]
@thejbte This is a classic problem in the product, and I think we'll have to fix it with pagination.

For example: let the system return the ordinal number (or the ID) of the last element, and in the next input we enter that data so that it continues returning the rest of the elements.

To calculate the ideal number of elements per page, we can limit each page to the number of elements we know will not exceed the 64-bit payload, or build the JSON up to the limit. I lean towards the 1st option.

This would be worth a chat with @wazuh/framework to get us in sync with the API.

Cheers!
