### ISSUE TITLE
Configuration validation accepting invalid format

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#16386]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.10 | Manager | Manager | Sources | Any, tested in Pop!_OS 22.04 |

## Description

During the development of the issue https://github.com/wazuh/wazuh/issues/16341, we have found that the manager is returning a 'success' response when requested to validate a non-xml formatted configuration file (`ossec.conf`).

### Steps to reproduce

1. Edit a manager's ossec.conf configuration file with the following payload:

```json
{"body": {"<ossec_config></ossec_config>"}}
```

2. Send a **check-manager-configuration** command through a `WCOM_SOCKET` (`{wazuh_path}/queue/sockets/com`) to the manager. Just like in https://github.com/wazuh/wazuh/blob/78bbd9f8e923c1a588b198ce2d0fe530659973dd/framework/wazuh/core/manager.py#L160

Actual response: OK
Expected response: Invalid configuration

**Comment by TomasTurina** [comment]
Reopening this issue as its solution has to be reverted: https://github.com/wazuh/wazuh/pull/19967

We need to find a proper solution that also works with Windows events.

**Comment by LucioDonda** [comment]
After analyzing some different approaches, and discarding some options we have decided to move this fix to the `_ReadElem` function (the one that parses and validates the XMLs). With this fix it will be discarded any XML that doesn't start with `'<'`.
Besides that, all the spaces, tabs and new lines at the start won't be taken into account.
Although the change is simple we're consuming time trying to eliminate any possible consequence as the one we suffered earlier.
This implies new Unit Tests and also manual testing with manager, agents and windows agents generating events.

**Comment by cborla** [comment]
Let's put this issue on-hold until we complete 4.7.1 tasks.

**Comment by vikman90** [comment]
## Proposal

- Do not modify the XML parser, thus `OS_ReadXML ()` will return `0` (OK).
- Check that the parsed XML contains at less one element at config.c: `node != NULL && node[0] != NULL`.

https://github.com/wazuh/wazuh/blob/96a21591ee01d24caa7283620af286c1adefd5c7/src/config/config.c#L319-L322

## Objective

- Apply the expected behavior (fail if _ossec.conf_ does not contain `<ossec_config>`).
- Do not modify the XML parser.

**Comment by nmkoremblum** [comment]
This issue is set "on hold" in favor of https://github.com/wazuh/wazuh/issues/21385 which has a higher priority

**Comment by LucioDonda** [comment]
The proposed [solution](https://github.com/wazuh/wazuh/issues/16386#issuecomment-1885111166) is not working.
After creating an additional UT for testing I've found that the **_node_** itself is returning only the valid part of the XML part of the file.
It doesn't change if the file itself starts with anything else.
That's why I think that the original approach of resolving this issue on a lower level (character by character) is the best (or perhaps only) one.
