### ISSUE TITLE
Compilation on Ubuntu adduser.sh group 'ossec' already exists

### ISSUE THREAD

**Issue by garyfeltham** [wazuh/wazuh#164]
I'm compiling Wazuh manually to enable mysql support by running `make TARGET=server DATABASE=mysql install`

The installation stops at 

```Done building server

./init/adduser.sh ossec ossecm ossecr ossec /var/ossec
Wait for success...
groupadd: group 'ossec' already exists
make: *** [install-common] Error 9```

A version of Wazuh is already installed on the server, so this is an upgrade.

To pass this error, the adduser.sh script can be adhorned with -f to force. i.e.
`        GROUPADD=$(sys_acct_chk "/usr/sbin/groupadd -f")`

**Comment by erseco** [comment]
We are trying to reproduce your error in Ubuntu Server 16.04.2 LTS and it works correctly, which ubuntu version are you using? Thanks

**Comment by garyfeltham** [comment]
Sure this is on 14.04.5 LTS

**Comment by erseco** [comment]
Hi again, 

We tried to reproduce the error in a fresh install of Ubuntu 14.04.5 LTS and it was impossible.

We appreciate your suggest of adding the -f parameter, but first we want to see whats happening in your installation because the adduser.sh script first check if the group "ossec" exists before adding it.

Please, can you give us the steps that are you following to get this error?

Also please indicate your current version of wazuh/ossec and the version (git,release) are you trying to update

Thanks!

**Comment by garyfeltham** [comment]
Hi,

I think I know what has happened here - The ossec user and group have been centralised to an ldap server rather than being a local group/account. Therefore the OS is preventing a duplicate group. Hence the -f works.

I grabbed the latest branch for building.

It isn't standard practice however would be nice from my side at least to have the -f for future builds.

Many thanks!.. G

**Comment by erseco** [comment]
Yes, is not an standard practice but seems interesting the fix for ldap servers.

We will check the option in our testing system and if it works we will add the -f parameter to groupadd in the next release.

Thank you for contribution and best regards!

**Comment by vikman90** [comment]
Hi @garyfeltham,

we made the change that you proposed for Linux: https://github.com/wazuh/wazuh/commit/deb7a7a8460c8cdbf0430e86b447415aced273ae

We have tested this change in some Linux-based OS including Debian, Ubuntu, RedHat, CentOS and Fedora, and it seems to work properly.

Thank you very much for your contribution.
Best regards.
