### ISSUE TITLE
Add some i_calc missing building errors to the User Manual

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#16512]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh/issues/15485   |     https://github.com/wazuh/wazuh/pull/16094 |

# Description

Currently, we only have the runtime errors within the User Manual. We should also add the errors that the User could obtain when building the decoders.

Here we have a couple samples:

- `An error occurred while trying to validate "decoder/custom-json/0": Stage block "map" building failed: An error occurred while building the helper function "i_calc": "helper.i_calc[/~0result, div, 1, 2, 10, 0]" function: Division by zero`

- `An error occurred while trying to validate "decoder/custom-json/0": Stage block "map" building failed: An error occurred while building the helper function "i_calc": "helper.i_calc[/~0result, sum, 100, 20000, 300000000, 2147483648]" function: Could not convert parameter "2147483648" to int: stoi`. This one seems too generic. It is the same for integers that are not within the supported range, strings, etc. (overflow, underflow, not supported type, etc.)

## Considerations

More details in the comment within the testing issue that use references https://github.com/wazuh/wazuh-qa/issues/4010

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
The error has been fixed. Also, the function helper has changed since this issue.

In the case of `i_calc`, it is now:

### int_calculate
#### Signature:
```yml
- field: int_calculate([sum|sub|mul|div], [value1|$ref1], …,[valueN|$refN])
```

field → the input value field
Operator → 
        sum → add operator (field + [value1|$ref1] + … + [valueN|$refN])
        sub → subtract operator (field - [value1|$ref1] - … - [valueN|$refN])
        mul → multiply operator (field * [value1|$ref1] * … * [valueN|$refN])
        div → divisor operator (field / [value1|$ref1] / … / [valueN|$refN])
$refX → reference to a numeric value
value → a numeric value

#### Operation:
Apply the basic arithmetic operation by iterating over the arguments. The result of applying the operand to the first 2 arguments will be the left operand of the third argument. The result “field” is a integer and will be replaced. In case of errors “field” will not be modified.


This helper function is typically used in the [map](https://docs.google.com/document/d/1N0p7pd7XszQwFU9HBjpB7txIw2DCcAsV-BKfEZSLixw/edit#heading=h.m0xlackygltw) stage

#### Errors:

- If field is not a integer → Failure: Target field reference not found
- If field does not exist → Failure: Target field reference not found
- If a reference is not a integer →Failure: Parameter is not integer.
- If a reference does not exist → Failure: Reference not found.
- If a value is not a integer →Failure: Parameter is not integer.
- If the dividend ([value|$ref]) is zero in the division operation → Failure: Parameter value makes division by zero
- If any of the results surpasses superior type limit -> Failure: operation result in integer Overflown.
- If any of the results surpasses inferior type limit -> Failure: operation result in integer Underflown.

#### Example:
Given the event.
```json
{
   "sum": 4,
   "sub": 4,
   "mul": 4,
   "div": 4
}
```

The operation:
```yml
- sum: int_calculate(sum, $sum, 2)
- sub: int_calculate(sub, $sub, 2)
- mul: int_calculate(mul, $mul, 2)
- div: int_calculate(div, $div, 2)
```


Will evaluate to true and the final event will be:
```json
{
   "sum": 6,
   "sub": 2,
   "mul": 8,
   "div": 2
}
```
