### ISSUE TITLE
Review calls to Handler.log_exceptions use on cluster classes

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh#16510]
The coroutine Handler.log_exceptions handles the exception received from the coroutine called. 

It is important to review and define if it's correct to handle the exception on this coroutine on several places of the source code where this coroutine is being called, because sometimes there are callback that expect an exception as one of its possible return values.

**Comment by mhamra** [comment]
Blocked until #16509 merge

**Comment by Selutario** [comment]
This could be causing in certain places a very similar problem (although with a different origin) to the one that was already reported and solved here:
- https://github.com/wazuh/wazuh/issues/19686

However, due to the way communication works in the cluster (a timeout may occur waiting for confirmation of receipt, but not on sending, which occurs sooner or later), this does not seem likely to be a problem. In other words:
- Client (e.g. Auhtd in worker) sends message to Master.
- Master sends a message (a response) to client (authd in worker). 

None of them can fail due to timeout, even if the confirmation of receipt of each one is canceled due to timeout.

**Comment by Selutario** [comment]
Closing for now. We will reopen the issue if we find any related errors.
