### ISSUE TITLE
Feature request: server-side wazuh packages for Alpine

### ISSUE THREAD

**Issue by flyn-org** [wazuh/wazuh#16532]
I am interested in installing the server components of Wazuh on Alpine. I do not yet see Alpine packages for Wazuh's indexer, server, or dashboard. I have come across some GitLab issues related to the musl C library, though. Has anyone made an attempt at this? I could try, but I didn't want to duplicate effort. If I understand "make EXTERNAL_SRC_ONLY=yes deps", then I might have a chance at this.

A related question: has there ever been talk of making use of system libraries during the build instead of these pre-built/re-built libraries?

**Comment by pereyra-m** [comment]
Hello @flyn-org !

As you can see in the [Packages list](https://documentation.wazuh.com/current/installation-guide/packages-list.html#wazuh-manager-and-wazuh-agent), Alpine Linux has packages only for the Wazuh agent.

You'll need to build the manager by yourself.
There are detailed instructions in [Installing the Wazuh manager from sources
](https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-server/index.html), you'll find the compilation requirements, etc.

The project doesn't rely on system libraries to make the product more robust. This way, we can test everything works as expected after we update the external dependencies we manage. 

Please, try the Wazuh manager build and share any error you find. In the first attempt don't use the `EXTERNAL_SRC_ONLY` flag, because all the external libraries will be compiled from scratch. The default behavior for the `make deps` target is to download all the pre-compiled libraries if available for the current OS and architecture.

Regards.
