### ISSUE TITLE
hybrid will not compile on FreeBSD (libidn2 issue)

### ISSUE THREAD

**Issue by parena1979** [wazuh/wazuh#1658]
## Bug report

**OS**
FreeBSD 11.2

**Wazuh version**
3.6.1

**Install type**
hybrid

**Install method**
sources

**Log sample**

```
gmake[1]: Entering directory '/usr/ports/security/wazuh3-hids-hybrid/work/wazuh3-3.6.1/src'
gmake ossec-maild - ossec-csyslogd - ossec-agentlessd - ossec-execd - ossec-logcollector - ossec-remoted ossec-agentd manage_agents utils ossec-syscheckd ossec-monitord ossec-reportd ossec-authd ossec-analysisd ossec-logtest ossec-makelists ossec-dbd - ossec-integratord wazuh-modulesd wazuh-db
gmake[2]: Entering directory '/usr/ports/security/wazuh3-hids-hybrid/work/wazuh3-3.6.1/src'
    CC libwazuhext.so
    CC ossec-maild
libwazuhext.so: undefined reference to `idn2_free'
libwazuhext.so: undefined reference to `idn2_check_version'
libwazuhext.so: undefined reference to `idn2_strerror'
libwazuhext.so: undefined reference to `idn2_lookup_ul'
collect2: error: ld returned 1 exit status
gmake[2]: *** [Makefile:1017: ossec-maild] Error 1
gmake[2]: Leaving directory '/usr/ports/security/wazuh3-hids-hybrid/work/wazuh3-3.6.1/src'
gmake[1]: *** [Makefile:561: hybrid] Error 2
gmake[1]: Leaving directory '/usr/ports/security/wazuh3-hids-hybrid/work/wazuh3-3.6.1/src'
*** Error code 2

Stop.
make: stopped in /usr/ports/security/wazuh3-hids-hybrid
```

Bug description
----------------
I'm trying to create a FreeBSD package for Wazuh 3 and I'm getting libidn2 issues. This particular FreeBSD installation has the latest libidn2. Mind you, an attempt to do it the regular way (download wazuh sources and compile that without trying to do it in a specific "let's build a FreeBSD port" way) results in the same issue. I'm in no way an expert in solving these kinds of issues so I might be missing something obvious.

**Comment by crolopez** [comment]
Hi @parena1979,

The compilation failure may be due to the fact that you do not have the developer version of libidn2 installed, which I have not found for FreeBSD.

You should not have problems if you uninstall the library, or if you specify to libcurl that you do not want to compile with it. To do this, replace this line in the Makefile:

https://github.com/wazuh/wazuh/blob/65e044e7ffd27566bd268d0d0b9984cb4210adc7/src/Makefile#L738

with

`cd $(EXTERNAL_CURL) && CPPFLAGS="-fPIC -I${ROUTE_PATH}/${EXTERNAL_OPENSSL}include" LDFLAGS="-L${ROUTE_PATH}/${EXTERNAL_OPENSSL}" LIBS="-ldl -lpthread" ./configure --disable-ldap --without-libidn2`

I hope this works.

Best regards.

**Comment by parena1979** [comment]
Thanks, @crolopez !

I had been looking at that, but I think in the wrong location. It now builds for me. :)
