### ISSUE TITLE
Bug about labels and alerts size 

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#1659]
Reported at the "Communication" test of 3.7 (https://github.com/wazuh/wazuh/issues/1616).

It seems the size of labels and printed alerts is being truncated to a size less than 64KB. Particularly, labels have a limitation of 20501 characters for the key and 20477 for the value. In addition, alerts printed in the `alerts.log` file is truncated to 17KB more or less instead of the 64KB required.

**Comment by Skeptor** [comment]
This issue has been labeled as stall because we need more info to replicate some fails.
The labels max size is: 20501 characters for the key and 20477 characters for the value as it is said in https://github.com/wazuh/wazuh/issues/1616#issuecomment-428982391 https://github.com/wazuh/wazuh/issues/1616#issuecomment-428991866
However, in the alerts I get 45 KB as log size in Kibana and the full log in alerts.log and in archives.log
