### ISSUE TITLE
Services and files persist after uninstall wazuh manager

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh#1660]
### Installation test

- OS: Centos 7
- version: 3.7.0

**Check uninstall (services / files / users)**

Removing the manager the service  isn't remove and the configuration files persists as `.rpmsave` extension:

```
[root@cent7 vagrant]# ls /etc/systemd/system/wazuh-manager.service 
/etc/systemd/system/wazuh-manager.service
[root@cent7 vagrant]# systemctl start wazuh-manager
Job for wazuh-manager.service failed because a configured resource limit was exceeded. See "systemctl status wazuh-manager.service" and "journalctl -xe" for details.
[root@cent7 vagrant]# journalctl -xe
...
...
...
Oct 16 08:20:16 cent7 polkitd[309]: Registered Authentication Agent for unix-process:24159:410355 (system bus name :1
Oct 16 08:20:16 cent7 systemd[1]: Failed to load environment files: No such file or directory
Oct 16 08:20:16 cent7 systemd[1]: wazuh-manager.service failed to run 'start' task: No such file or directory
Oct 16 08:20:16 cent7 polkitd[309]: Unregistered Authentication Agent for unix-process:24159:410355 (system bus name 
Oct 16 08:20:16 cent7 systemd[1]: Failed to start Wazuh manager.
-- Subject: Unit wazuh-manager.service has failed
...
...
...
```

```
[root@cent7 vagrant]# ls /var/ossec/etc/
client.keys.rpmsave  ossec.conf.rpmsave  shared  sslmanager.cert  sslmanager.key
[root@cent7 vagrant]# 

```

**Comment by BraulioV** [comment]
Hi @adri9valle,

with the rpm packages for Wazuh v3.7.0, several files are marked as *configuration* files with the atribute `noreplace` using `%config(noreplace)` macro in the RPM spec. This macro set the file as a configuration file and the rpm package will preserve it when you upgrade the package. But, when you remove the package, the files marked with `%config(noreplace)` will be preserved as `.rpmsave` files, so that's a expected behaviour. 

Regarding to the services, I made this PR https://github.com/wazuh/wazuh-packages/pull/77 to solve this issue in .deb and .rpm packages.

Regards,
Braulio.
