### ISSUE TITLE
Possible anomaly in `wazuh-modulesd` disk usage

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh#16600]
## Description

In the testing for Release 4.4.1-RC1, some anomalies have been observed in the **Disk** graph of the CentOS manager (wazuh-modulesd) compared to the 4.4.0-RC2. The new graph shows more disk usage during a longer period of time.

4.4.1-RC1, https://github.com/wazuh/wazuh/issues/16585.:
![image](https://user-images.githubusercontent.com/72193239/229540372-5dd83147-29c7-4e14-abb6-76bb76b11d33.png)

4.4.0-RC2, https://github.com/wazuh/wazuh/issues/16454:
![image](https://user-images.githubusercontent.com/72193239/229540480-a1a97d94-2b04-4a1d-90db-62ee1a67d548.png)

The 4.4.1-RC1 shows a higher and wider curve at the beginning with no peaks, and a second curve smaller than the previous one, but not seen in 4.4.0-RC2

It is necessary to investigate this behavior and discuss if we can tolerate this difference.

**Comment by jotacarma90** [comment]
# Research

Hello team,
I have been reviewing the changes introduced for 4.4.1 difference with 4.4.0.
I have found two PRs that make changes to the wazuh_modules database:
https://github.com/wazuh/wazuh/pull/16233
https://github.com/wazuh/wazuh/pull/11753

Also, I have been looking at this same MacOS and Solaris test in previous footprints and you can see some fluctuations in the disk graphs with this 50-70 % disk usage range:

<details><summary>Disk usage 4.3.9 - RC1</summary>

![1-439-RC1](https://user-images.githubusercontent.com/60003131/229780132-4c16e5c6-f4a3-4236-b814-05456739fa19.png)

</details>

<details><summary>Disk usage 4.3.10 - RC1</summary>

![2-4310-RC1](https://user-images.githubusercontent.com/60003131/229780305-f1d650e1-4a32-4ef4-a449-a0ea6f06120d.png)

</details>

<details><summary>Disk usage 4.4.0 - alpha1</summary>

![3-440-alpha1](https://user-images.githubusercontent.com/60003131/229780446-d8383b5a-d342-47a9-9024-d20af09da3fa.png)

</details>

<details><summary>Disk usage 4.4.0 - alpha2</summary>

![4-440-alpha2](https://user-images.githubusercontent.com/60003131/229780596-1c43d4eb-fdeb-4c2b-a761-ada49d834740.png)

</details>

<details><summary>Disk usage 4.4.0 - beta1</summary>

![5-440-beta1](https://user-images.githubusercontent.com/60003131/229781004-5757200b-b4ca-4f4b-9ec9-8df0738eae01.png)

</details>

<details><summary>Disk usage 4.4.0 - RC1</summary>

![6-440-RC1](https://user-images.githubusercontent.com/60003131/229781229-6a2e9dd1-0a94-4f1f-ad26-0684a6536980.png)

</details>

<details><summary>Disk usage 4.4.0 - RC2</summary>

![7-440-RC2](https://user-images.githubusercontent.com/60003131/229782249-b8b7dc24-95af-4e74-b23a-155081897cd6.png)

</details>

<details><summary>Disk usage 4.4.1 - RC1</summary>

![8-441-RC1](https://user-images.githubusercontent.com/60003131/229782321-cf3ac9c8-b1b1-4c4e-b666-732b778ab38b.png)

</details>

# Conclusion

Since the changes should not have a significant impact on disk usage, and the fluctuations from one test to another, I do not consider this to be a cause for concern.
