### ISSUE TITLE
Create SCA Policy for Rocky Linux 9

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#16618]
|Wazuh version| Component | 
|---| --- |
| 4.8.1 | SCA | 

| Component | Action type           | Main Issue 
| --- | --- | ---
| SCA       | Create |  #18306

## Main tasks

- [x] Use the latest CIS benchmark PDF - CIS Rocky Linux 9 Benchmark v1.0.0
- [x] Verify IDs numbers.
- [x] Verify texts are correct: Title, Description, Rationale and Remediation.
- [x] Verify Compliance: CIS, CIS_CSC.
- [x] Verify condition and rules:
  - [x] To Pass.
  - [x] To Fail.

### Syntax and semantic

- [x] a) ID of each policy must be contiguous.
- [x] b) The order and format set in [Documentation](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/creating-custom-policies.html) must be respected.
- [x] c) YML must be valid to avoid errors.

### Content

- [x] a) Compare each check with its analog from CIS Benchmark.
- [x] b) Try maintaining each rule as similar as possible with the `Audit` section from the CIS check.
- [x] c) Check that the commands provide the expected output.
- [x] d) When a failure is discovered, check similar policies to avoid repetition of the issue.

### Unit testing

- [x] a) Output from `ossec.log` after the SCA scan and a raw output of the result of the checks.
<details><summary>Tests results</summary>
<p>

```
2024/01/12 15:19:48 sca[6681] wm_sca.c:2598 at wm_sca_send_summary(): DEBUG: Sending summary event for file: 'cis_rocky_linux_9.yml'
2024/01/12 15:19:48 sca[6681] wm_sca.c:271 at wm_sca_send_alert(): DEBUG: Sending event: {"type":"summary","scan_id":1977732514,"name":"CIS Rocky Linux 9 Benchmark v1.0.0","policy_id":"cis_rocky_linux_9","file":"cis_rocky_linux_9.yml","description":"This document provides prescriptive guidance for establishing a secure configuration posture for Rocky Linux 9 systems running on x86_64 platforms.This document was tested against Rocky Linux 9.","references":"https://www.cisecurity.org/cis-benchmarks/","passed":82,"failed":84,"invalid":1,"total_checks":167,"score":49.397590637207031,"start_time":1705072781,"end_time":1705072785,"hash":"54d0827e4927f9f12a65de21fb3b4fb8a10a32fb699285f04220a4f869810c5b","hash_file":"82060e37211b4f0b1fc9c05951b9469f0557094cddc594106c3989b2c12b1ab5","first_scan":1}
```

#### Analysisd (server or local)
analysisd.debug=2

#### Auth daemon debug (server)
authd.debug=0

#### Exec daemon debug (server, local, or Unix agent)
execd.debug=0

#### Monitor daemon debug (server, local, or Unix agent)
monitord.debug=0

#### Log collector (server, local or Unix agent)
logcollector.debug=0

#### Integrator daemon debug (server, local, or Unix agent)
integrator.debug=0

#### Unix agentd
agent.debug=2

</p>
</details>

### Deployment

- [ ] a) If the policy it's new, it must be added to the `sca.files` templates.
- [ ] b) If the OS has many supported SCA policies, a policy must be set as the default policy. ([as example](https://github.com/wazuh/wazuh/blob/master/etc/templates/config/centos/sca.files))

### Documentation

- [x] a) Ensure documentation SCA list includes the created or updated SCA.

**Comment by ooniagbi** [comment]
Added default policy for Rocky Linux OS: [Add default policy for RL9](https://github.com/wazuh/wazuh/pull/17810/commits/95be135fc1c4cf844c367dc7e28082d9d59af07c)

**Comment by IsExec** [comment]
# Rocky Linux 9 SCA testing report
**Condition**: Since there is no old Rocky Linux 9 SCA, the test was benchmarked against RHEL8 SCA.  

## Agent running on old SCA (RHEL8)

###  Endpoint spec

<details>
<summary>CPU</summary>

````console
[root@agentb sca_footprint]# lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  2
  On-line CPU(s) list:   0,1
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    CPU family:          6
    Model:               142
    Thread(s) per core:  1
    Core(s) per socket:  2
    Socket(s):           1
    Stepping:            10
    BogoMIPS:            4223.99
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtr
                         r pge mca cmov pat pse36 clflush mmx fxsr sse s
                         se2 ht syscall nx rdtscp lm constant_tsc rep_go
                         od nopl xtopology nonstop_tsc cpuid tsc_known_f
                         req pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2
                          movbe popcnt aes rdrand hypervisor lahf_lm abm
                          3dnowprefetch invpcid_single pti fsgsbase bmi1
                          bmi2 invpcid rdseed clflushopt md_clear flush_
                         l1d arch_capabilities
Virtualization features:
  Hypervisor vendor:     KVM
  Virtualization type:   full
Caches (sum of all):
  L1d:                   64 KiB (2 instances)
  L1i:                   64 KiB (2 instances)
  L2:                    512 KiB (2 instances)
  L3:                    16 MiB (2 instances)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0,1
````

</details>

<details>
<summary>RAM</summary>

````console
[root@agentb sca_footprint]# free -g -h -t
               total        used        free      shared  buff/cache   available
Mem:           3.7Gi       523Mi       2.9Gi        16Mi       589Mi       3.2Gi
Swap:          2.0Gi          0B       2.0Gi
Total:         5.8Gi       523Mi       4.9Gi
````

</details>

<details>
<summary>Disk</summary>

````console
[root@agentb sca_footprint]# df -h
Filesystem                  Size  Used Avail Use% Mounted on
devtmpfs                    4.0M     0  4.0M   0% /dev
tmpfs                       1.9G     0  1.9G   0% /dev/shm
tmpfs                       767M   17M  750M   3% /run
/dev/mapper/rl_rocky9-root   70G  2.8G   68G   4% /
/dev/sda1                   960M  177M  784M  19% /boot
tmpfs                       384M     0  384M   0% /run/user/1000
````
</details>


### Footprint test results
<details>
<summary>Metrics</summary>

![cpu_percent_plot](https://github.com/wazuh/wazuh/assets/121132106/21104134-f6ac-442d-a4e0-099d5e044054)
![disk_percent_plot](https://github.com/wazuh/wazuh/assets/121132106/7743a9e1-1356-4b06-9374-26ccc4e85523)
![disk_used_(mb)_plot](https://github.com/wazuh/wazuh/assets/121132106/94f3502b-f852-4725-a619-1a15e688cbb0)
![memory_percent_plot](https://github.com/wazuh/wazuh/assets/121132106/15356dfa-946e-4d09-90b7-c1aec01dc96e)
![memory_used_(mb)_plot](https://github.com/wazuh/wazuh/assets/121132106/c6273bb8-4717-4aad-a248-20357822ad52)
![ProcessesCPU](https://github.com/wazuh/wazuh/assets/121132106/50324354-f271-4e40-a2a6-9514415f9028)
![ProcessesCPU_Change_Point](https://github.com/wazuh/wazuh/assets/121132106/c4b6b5fc-bec3-4d86-89c6-cc66e3c7d953)
![ProcessesCPUlegend](https://github.com/wazuh/wazuh/assets/121132106/e4ac0c66-209b-4694-8dba-a7ec17efbf67)
![ProcessesRAM](https://github.com/wazuh/wazuh/assets/121132106/12cf8f06-c13c-44aa-97c3-6613904c1de8)
![ProcessesRAM_Change_Point](https://github.com/wazuh/wazuh/assets/121132106/bc34fb5f-633f-4686-b05f-1791a29cf27f)
![ProcessesRAMlegend](https://github.com/wazuh/wazuh/assets/121132106/545a0417-8fd5-4e6c-a0a4-0cad117782f1)
![swap_percent_plot](https://github.com/wazuh/wazuh/assets/121132106/b536e227-117e-41ba-8e19-c2e5012ffabb)
![swap_used_(mb)_plot](https://github.com/wazuh/wazuh/assets/121132106/a517e061-e091-439b-90ee-215867b7bed1)
</details>

<details>
<summary>SCA logs</summary>

````console
[root@agentb sca_footprint]# tail /var/ossec/logs/ossec.log
2024/07/11 05:19:06 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_rhel8_linux.yml'
2024/07/11 05:19:06 sca: INFO: Security Configuration Assessment scan finished. Duration: 8 seconds.
2024/07/11 05:23:58 sca: INFO: Starting Security Configuration Assessment scan.
2024/07/11 05:23:58 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_rhel8_linux.yml'
2024/07/11 05:24:12 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_rhel8_linux.yml'
2024/07/11 05:24:12 sca: INFO: Security Configuration Assessment scan finished. Duration: 14 seconds.
2024/07/11 05:28:58 sca: INFO: Starting Security Configuration Assessment scan.
2024/07/11 05:28:58 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_rhel8_linux.yml'
2024/07/11 05:29:06 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_rhel8_linux.yml'
2024/07/11 05:29:06 sca: INFO: Security Configuration Assessment scan finished. Duration: 8 seconds.
````

</details>

[metrics.zip](https://github.com/user-attachments/files/16172175/metrics.zip)


## Agent running on new SCA (Rocky Linux 9)

### Endpoint spec
<details>
<summary>CPU</summary>

````console
[root@agenta sca_footprint]# lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  2
  On-line CPU(s) list:   0,1
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    CPU family:          6
    Model:               142
    Thread(s) per core:  1
    Core(s) per socket:  2
    Socket(s):           1
    Stepping:            10
    BogoMIPS:            4223.99
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtr
                         r pge mca cmov pat pse36 clflush mmx fxsr sse s
                         se2 ht syscall nx rdtscp lm constant_tsc rep_go
                         od nopl xtopology nonstop_tsc cpuid tsc_known_f
                         req pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2
                          movbe popcnt aes rdrand hypervisor lahf_lm abm
                          3dnowprefetch invpcid_single pti fsgsbase bmi1
                          bmi2 invpcid rdseed clflushopt md_clear flush_
                         l1d arch_capabilities
Virtualization features:
  Hypervisor vendor:     KVM
  Virtualization type:   full
Caches (sum of all):
  L1d:                   64 KiB (2 instances)
  L1i:                   64 KiB (2 instances)
  L2:                    512 KiB (2 instances)
  L3:                    16 MiB (2 instances)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0,1
````

</details>

<details>
<summary>RAM</summary>

````console
[root@agenta sca_footprint]# free -g -h -t
               total        used        free      shared  buff/cache   available
Mem:           3.7Gi       524Mi       2.9Gi        16Mi       592Mi       3.2Gi
Swap:          2.0Gi          0B       2.0Gi
Total:         5.8Gi       524Mi       4.9Gi
````

</details>

<details>
<summary>Disk</summary>

````console
[root@agenta sca_footprint]# free -g -h -t
               total        used        free      shared  buff/cache   available
Mem:           3.7Gi       524Mi       2.9Gi        16Mi       592Mi       3.2Gi
Swap:          2.0Gi          0B       2.0Gi
Total:         5.8Gi       524Mi       4.9Gi
[root@agenta sca_footprint]# df -h
Filesystem                  Size  Used Avail Use% Mounted on
devtmpfs                    4.0M     0  4.0M   0% /dev
tmpfs                       1.9G     0  1.9G   0% /dev/shm
tmpfs                       767M   17M  750M   3% /run
/dev/mapper/rl_rocky9-root   70G  2.8G   68G   4% /
/dev/sda1                   960M  177M  784M  19% /boot
tmpfs                       384M     0  384M   0% /run/user/1000

````
</details>


### Footprint test results
<details>
<summary>Metrics</summary>

![cpu_percent_plot](https://github.com/wazuh/wazuh/assets/121132106/bb3c631e-4a93-4020-ba72-e8d86b58c6d2)
![disk_percent_plot](https://github.com/wazuh/wazuh/assets/121132106/18578761-8ba5-4c7d-9ffd-d21be2df33a3)
![disk_used_(mb)_plot](https://github.com/wazuh/wazuh/assets/121132106/a9a1c1a2-340b-41c5-b8f9-a66c1baf96d6)
![memory_percent_plot](https://github.com/wazuh/wazuh/assets/121132106/f2ad3c39-99f0-434a-8700-b093230857ca)
![memory_used_(mb)_plot](https://github.com/wazuh/wazuh/assets/121132106/1fb09370-c301-4924-9e71-dc2a6b5ab190)
![ProcessesCPU](https://github.com/wazuh/wazuh/assets/121132106/8d02289c-978b-4cee-aa3f-7e1f64761d54)
![ProcessesCPU_Change_Point](https://github.com/wazuh/wazuh/assets/121132106/5b8e349a-97dd-4645-a613-104ebc50e2b8)
![ProcessesCPUlegend](https://github.com/wazuh/wazuh/assets/121132106/96bff687-e5eb-4fb6-a1e9-78d3ea66e192)
![ProcessesRAM](https://github.com/wazuh/wazuh/assets/121132106/efdc9d26-99b2-4067-85b9-707612453ad8)
![ProcessesRAM_Change_Point](https://github.com/wazuh/wazuh/assets/121132106/3cc2e038-53ed-4050-b1b1-176cfc686e00)
![ProcessesRAMlegend](https://github.com/wazuh/wazuh/assets/121132106/dbe6f4f8-8022-41be-a423-fe9315ee8f3a)
![swap_percent_plot](https://github.com/wazuh/wazuh/assets/121132106/6762e720-d91c-4370-84fb-4087eed8d606)
![swap_used_(mb)_plot](https://github.com/wazuh/wazuh/assets/121132106/af2d77ad-aa68-44a4-bbd5-7acea1e1d2c8)
</details>

<details>
<summary>SCA logs</summary>

````console
[root@agenta sca_footprint]# tail /var/ossec/logs/ossec.log
2024/07/11 05:24:20 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_rocky_linux_9.yml'
2024/07/11 05:24:20 sca: INFO: Security Configuration Assessment scan finished. Duration: 7 seconds.
2024/07/11 05:29:13 sca: INFO: Starting Security Configuration Assessment scan.
2024/07/11 05:29:13 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_rocky_linux_9.yml'
2024/07/11 05:29:47 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_rocky_linux_9.yml'
2024/07/11 05:29:47 sca: INFO: Security Configuration Assessment scan finished. Duration: 34 seconds.
2024/07/11 05:34:13 sca: INFO: Starting Security Configuration Assessment scan.
2024/07/11 05:34:13 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_rocky_linux_9.yml'
2024/07/11 05:34:22 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_rocky_linux_9.yml'
2024/07/11 05:34:22 sca: INFO: Security Configuration Assessment scan finished. Duration: 9 seconds.
````

</details>


[metrics.zip](https://github.com/user-attachments/files/16172227/metrics.zip)


## Analysis


  | Benchmark   (Rhel8) | New SCA   (rocky_linux9) | Difference
-- | -- | -- | --
CPU |   |   |  
wazuh-modulesd average CPU percent | 0.92 | 0.77 | -0.15
Overall   average CPU percent | 1.33 | 0.56 | -0.77
Overall peak   CPU percent | 38.1 | 15.5 | -22.60
Memory |   |   |  
wazuh modulesd average memory (MB) | 0.02 | 0.02 | 0.00
Overall   average memory used (MB) | 287.82 | 272.81 | -15.01
Overall peak   memory used peak (MB) | 314.65 | 356.27 | 41.62
Disk |   |   |  
Overall   average disk used (MB) | 2837.94 | 2844.84 | 6.90
Overall peak   disk used (MB) | 2838.05 | 2844.93 | 6.88
Overall   average disk read bytes | 606.99 | 600.34 | -6.65
Overall peak   disk read bytes | 606.99 | 600.35 | -6.64
Overall   average disk write bytes | 435.59 | 472.54 | 36.95
Overall peak   disk write bytes | 442.08 | 479.21 | 37.13

**Comment by jk-olaoluwa** [comment]
LGTM!

**Comment by jk-olaoluwa** [comment]
SCA Test is approved by @havidarou 

Closing issue.
