### ISSUE TITLE
Active disconnected agent in wazuh

### ISSUE THREAD

**Issue by uchi888** [wazuh/wazuh#16651]
wazuh agent is up and running agent installed servers, but from the wazuh management server dashboard showing all agent has been disconnected. 
If I login all server one by one and restart the  wazuh service then only its showing active status. 
can some one tell me how can I activate all agent at a one time. 

WAZUH manager running on ubuntu 

Thank you.
uchi.

**Comment by niek1992** [comment]
You sure the wazuh-service is enabled? What does the logs say of the agent when the manager shows disconnected state? Which OS are you running (both manager and agents)?

**Comment by uchi888** [comment]
Yes, I checked the running services on the agent server.  the agent runs on both Linux and Windows environments, and the Wazuh manager is running on Linux (Ubuntu) 

when I restart the service on the agent server, It's become an active state on Wazuh Dashboard.

**Comment by pereyra-m** [comment]
Hello @uchi888 !

It isn't a normal situation that you need to restart the agents every time to connect them to the manager.

To find the reasons why your agents are getting disconnected, please share the full **ossec.log** file of both agent and manager (please remove first any sensitive information). There we'll find more details, but one possibility is that the agents can't reach the manager in the required ports (1514/1515 by default).

Also, have you checked that the agents' version is equal to or lower than the manager's? What is their version? They won't be able to communicate with the manager if they have a greater one.

Finally, is this a fresh installation or an upgrade? Did it work properly before? Has there been any infrastructure change before these issues?

Regards.

**Comment by uchi888** [comment]
Hi @pereyra-m 

This is fresh installation. I have notice that wazuh-indexer.service was failed, I increased the Xms and XmX now it's working fine. the problem I facing is how to start or restart all agent service at one time from wazuh dashboard or wazuh management server.

**Comment by pereyra-m** [comment]
Hi again @uchi888 !

I'm glad your indexer is working now. But you can't interact with a disconnected agent, so it isn't possible to restart them remotely.
Also, this isn't required in a normal situation. Please share the requested logs so we can find out why your agents are losing the connection with the manager.

Regards.

**Comment by pereyra-m** [comment]
Hello @uchi888 !
I didn't see your reply. 

Thanks to you.

> I'll share the logs. please let me know If there is any possibility to start all disconnected agents at once.

The manager can't send any restart command to a disconnected agent, you'll have to do it manually.

Regards.

**Comment by Dwordcito** [comment]
Closed due to inactivity, please if you need more help with this issue, please re-open.

Thanks for being part of this community.

**Comment by angelo-conti** [comment]
Hello Wazuh team,

I am experiencing the same issue as user @uchi888 in this post. All my wazuh agents are working. My server is running Ubuntu server 2022.04. I have allow ports 1415 and 1415 and port 443. Everything was working fine since the installation. I have the wazuh manager 44 AlmaLinux 9.4 agents and I add 4 Windows 10 Enterprise on the afternoon before the problem happen. 

On the next morning June 20, 2024 I checked the status  on Wazuh dashboard and all agents were disconnect at the same time. I checked their status in several computers. 

I ran the following commands to check 
#**systemctl daemon-reload && systemctl enable wazuh-agent && systemctl start wazuh-agent**  

 All was good. I also checked in that Ubuntu server by running the command: 
**sudo systemctl status wazuh-indexer.service** 
and it's active and running. 

Also I checked the status of manager with the command: 
**sudo systemctl status wazuh-manager.service** and it's active and running. 

Also I checked the status of dashboard with the command: 
**sudo systemctl status wazuh-dashboard.service** and it's active and running. 

**But all client are not connected when I look in the wazuh dashboard on my browser.
Could someone help me please?**

**Comment by pereyra-m** [comment]
Hi @angelo-conti 

Please create another issue with all the details of your problem.
Upload your `ossec.log` file so we can analyze it, because there we can find logs related to this situation.

> On the next morning June 20, 2024 I checked the status on Wazuh dashboard and all agents were disconnect at the same time. I checked their status in several computers.

If all the agents got disconnected at the same time, maybe one of the **wazuh-server** daemons had a problem. You could share in the new issue the result of `/var/ossec/bin/wazuh-control status` and restart your manager to verify if anything changes.

**Comment by mihir8474** [comment]
hi i have an issue my wazuh is on windows it is in virtual box enviorment when i start the wazuh and i type Ip a command in wazuh termial it shows the ip ad it is running on it but when my internet is dissconnected and connect to the other network my ip address is changed on wazuh server and all the agent shos dissconnected on the wazuh-dashboard. Plz help me to resolve this problem?
