### ISSUE TITLE
vulnerability detector ignores Windows 11 version

### ISSUE THREAD

**Issue by marklh9** [wazuh/wazuh#16708]
|v4.3.10| Wazuh Manager|Packages|Ubuntu 22.04.2 LTS|

While I've updated my Windows to 22H2 latest, it still shows 13 critical and 295 high vunerabilities.

Vulnerabilities like CVE-2022-30133 is sitll listed.

Use sqlite to inspect MSU table of cve.db shows:

select * from MSU where CVEID = "CVE-2022-30133" AND PRODUCT like "Windows 11%" AND PRODUCT LIKE "%x64%";
CVEID|PRODUCT|PATCH|TITLE|URL|SUBTYPE|RESTART_REQUIRED|CHECK_TYPE
CVE-2022-30133|Windows 11 version 21H2 for x64-based Systems|5016629|Windows Point-to-Point Protocol (PPP) Remote Code Execution Vulnerability|https://support.microsoft.com/help/5016629|||1

Where CHECK_TYPE is set to 1 ( instead 21H2 ).

I believe it's because vulnerability detector only set checktype for Windows 10.

https://github.com/wazuh/wazuh/blob/master/src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c#L8746

It should set checktype also for Windows 11.

**Comment by lsayanes** [comment]
Wazuh gets the patch information from the official Microsoft source and we have seen that in the new Windows 11 version `22H2` the new patch information is not related to the old Windows 11 patches and we cannot currently confirm it with the available information gathered by Wazuh.

In this case, you can see the patch link where we get our `MSU` from, in the official Microsoft [feed.](https://msrc.microsoft.com/update-guide/vulnerability)
This lack of relation between patches for different versions, makes that all old vulnerabilities affecting Windows 11 are shown and reported as vulnerable for Windows 11, although they really shouldn't be, as they are cumulative patches.

You can check it in the following [issue](https://github.com/wazuh/wazuh/issues/15160#issuecomment-1282284070)

Apparently, the problem is due to the change of `CPE` that has been applied in the `NVD`, as before the `CPE` of Windows 11 was:

[cpe:2.3-o:microsoft:windows_11:21h2:*:*:*:*:*:*:*](https://nvd.nist.gov/products/cpe/detail/1197858?namingFormat=2.3&orderBy=CPEURI&keyword=cpe%3A2.3%3Ao%3Amicrosoft%3Awindows_11_21h2%3A-%3A*%3A*%3A*%3A*%3A*%3Ax64%3A*&status=FINAL%2CDEPRECATED)
However, it seems that they have deprecated it and now it is:
[cpe:2.3-o:microsoft:windows_11_21h2:-:*:*:*:*:*:x64:*](https://nvd.nist.gov/products/cpe/detail/1291403?namingFormat=2.3&orderBy=CPEURI&keyword=cpe%3A2.3%3Ao%3Amicrosoft%3Awindows_11_21h2%3A-%3A*%3A*%3A*%3A*%3A*%3Ax64%3A*&status=FINAL%2CDEPRECATED)
This results in a mismatch with the corresponding vulnerability and therefore no reporting.
Examples:

> Old CPE: https://nvd.nist.gov/vuln/detail/CVE-2022-44698#vulnConfigurationsArea
> New CPE: https://nvd.nist.gov/vuln/detail/CVE-2023-28250#vulnConfigurationsArea
