### ISSUE TITLE
Vulnerability detection not detecting

### ISSUE THREAD

**Issue by eXqusic** [wazuh/wazuh#16729]
|v4.4.0|Vulnerability detector|AIO|Ubuntu|
All agent versions are currently v4.4.0 (Same as manager). All are windows devices and showing the same issue. This is not just this vulnerability, it has occurred with windows patches and other software.

I have been experiencing issues with CVE's not showing as detected within the webui even though they are definetly vulnerable.

An example of one is [CVE-2023-2033](https://nvd.nist.gov/vuln/detail/CVE-2023-2033) which effects Google Chrome prior to 112.0.5615.121.
Vulnerability is definitely in the cve.db
![sqlitecve](https://user-images.githubusercontent.com/7236050/232424440-59e09e38-3c63-478d-89e5-bbcd1dbb61b9.png)

The version of Chrome is definitely vulnerable. It also says the last full and partial scan was today April 17th and the vulnerability was released on NVD  04/14/2023
![Packagelist](https://user-images.githubusercontent.com/7236050/232424578-5cc80c88-8543-4566-96c1-9c28371a245b.png)

The "wazuh-modulesd:vulnerability-detector" logs show no errors, only Infos like below.
Analyzing agent 'AGENT' vulnerabilities.
Finished vulnerability assessment for agent 'AGENT'

Any help or troubleshooting steps would be great.

Thanks

**Comment by GabrielEValenzuela** [comment]
Hi @eXqusic ! How are you ?

The vulnerability  [CVE-2023-2033](https://nvd.nist.gov/vuln/detail/CVE-2023-2033) is under `AWAITING ANALYSIS / UNDERGOING ANALYSIS`, that means, this vulnerability is currently undergoing analysis and not all information is available. Please check back soon to view the completed vulnerability summary.

For this reason, the NVD feed this is the same as unknown (because in the nodes array should appear something like "vulnerable" : true/false, with his corresponding CPE). For this reason, the vulnerability is not detected due to the lack of information and CPE, so we cannot relate it to the package.

When they finish investigating it, they will add the corresponding CPE and since we have it added in the CPE Helper, then the vulnerability should be found.

If you need anything more, please don't dub to ask.

We're here to help
Have a nice day!

**Comment by eXqusic** [comment]
Hi @GabrielEValenzuela 
Thank you for the quick response and explaining as to why its not showing up. This does answer my question very well.

Is it possible for myself to add the CPE manually to my instance? Are you able to provide instructions to do so or a link?

Thanks, have a nice day!
