### ISSUE TITLE
Mariadb Log not matching with the wazuh ruleset

### ISSUE THREAD

**Issue by aravindcyberfort** [wazuh/wazuh#16769]
{"timestamp":"2023-04-20T10:12:35.853+0530","agent":{"id":"001","name":"ubuntu-mariadb","ip":"192.168.40.62"},"manager":{"name":"wazuh-ML"},"id":"1681965755.78761","full_log":"20230420 10:12:35,ubuntu-mariadb,root,localhost,33,60,QUERY,mysql,'DROP DATABASE Desvelao',0","decoder":{},"location":"/var/log/mysql/mariadb-audit.log"}

I have been trying to get Mariadb DML DDL command logs to be indexed to wazuh dashboard but it doesnot matching any of the ruleset given in the wazuh repository. So it fails at the log test using  /var/ossec/bin/wazuh-logtest
Help me sort out this.

**Comment by vikman90** [comment]
Hi @aravindcyberfort, indeed, it is possible that some ruleset configuration is missing. We should start looking for the decoder, since it appears empty: `"decoder":{}`.

First of all, can you confirm that the Logcollector configuration is in _mysql_log_ mode? Something like this:

```xml
<localfile>
  <log_format>mysql_log</log_format>
  <location>/var/log/mysql/mariadb-audit.log</location>
</localfile>
```

This is so because the MySQL (and MariaDB) logs need a previous transformation so that the manager can decode them.

Second, if you could send us an example set of logs from your system we could verify the ruleset with them.

Best regards.

**Comment by aravindcyberfort** [comment]
Thank you @vikman90 for the reply, actually i need a decoder and a rule set for that log, I'm struggling to create those regex, so can anyone help me?

**Comment by vikman90** [comment]
@aravindcyberfort Absolutely, I'll be happy to help you. That is why I commented that a few lines of your _mariadb-audit.log_ file would allow us to define the decoders or the necessary rules.

Greetings!

**Comment by aravindcyberfort** [comment]
Hi @vikman90 
Here are the sample log for which i need decoder and rulesets.

CREATE Command log from /var/logs/archives/archives.json

{"timestamp":"2023-04-24T12:43:30.559+0530","agent":{"id":"003","name":"ubuntu-mariadb","ip":"192.168.40.62"},"manager":{"name":"wazuh-ML"},"id":"1682320410.220555","full_log":"MySQL log: 230424 12:43:29 34 Query\tCREATE DATABASE dhamo12345","decoder":{"name":"mysql_log"},"location":"/var/log/mysql/mariadb-audit.log"}


This log is from the path /var/ossec/logs/archives/archives.json and due to no decoder matched it's not reflecting at /var/ossec/logs/alerts/alerts.json so i can't see on the dashboard.

![image](https://user-images.githubusercontent.com/130983319/233936934-1a774367-7ddf-4623-89b9-22596c259bc9.png)


![image](https://user-images.githubusercontent.com/130983319/233937128-ad9cbdc6-957a-4af0-a022-a71a53f565ee.png)

Same logs from mariadb server /var/log/mysql/mariadb-audit.log

20230424 12:43:29,ubuntu-mariadb,root,localhost,34,65,QUERY,,'CREATE DATABASE dhamo12345',0

**Comment by vikman90** [comment]
Hi @aravindcyberfort,

According to this log, we can proceed in many ways.

This is the default behavior:

```shell
echo 'MySQL log: 230424 12:43:29 34 Query\tCREATE DATABASE dhamo12345' | /var/ossec/bin/wazuh-logtest
```

<details><summary>Logtest output</summary>

```
Starting wazuh-logtest v4.4.1
Type one log per line


**Phase 1: Completed pre-decoding.
        full event: 'MySQL log: 230424 12:43:29 34 Query\tCREATE DATABASE dhamo12345'

**Phase 2: Completed decoding.
        name: 'mysql_log'

**Phase 3: Completed filtering (rules).
        id: '50107'
        level: '0'
        description: 'MySQL: query.'
        groups: '['mysql_log']'
        firedtimes: '1'
        mail: 'False'
```
</details>

There is a basic default ruleset:
- [0150-mysql_decoders.xml](https://github.com/wazuh/wazuh/blob/v4.4.1/ruleset/decoders/0150-mysql_decoders.xml)
- [0295-mysql_rules.xml](https://github.com/wazuh/wazuh/blob/v4.4.1/ruleset/rules/0295-mysql_rules.xml)

In this example, I'm editing _/var/ossec/etc/rules/local_rules.xml_ and _/var/ossec/etc/decoders/local_decoders.xml_.

### Option 1: Alert about all queries

We can redefine rule 50107 to always trigger an alert. Simply increase the rule level to 3 or more.

<details><summary>local_rules.xml</summary>

```xml
<group name="mysql_log,">
  <rule id="50107" level="3" overwrite="yes">
    <if_sid>50100</if_sid>
    <regex>^MySQL log: \d+ \S+ \d+ Query</regex>
    <description>MySQL: query.</description>
  </rule>
</group>
```
</details>


<details><summary>Logtest output</summary>

```
**Phase 2: Completed decoding.
        name: 'mysql_log'
        query: 'CREATE DATABASE dhamo12345'

**Phase 3: Completed filtering (rules).
        id: '50107'
        level: '3'
        description: 'MySQL: query.'
        groups: '['mysql_log']'
        firedtimes: '1'
        mail: 'False'
**Alert to be generated.
```

</details>

### Option 2: Trigger an alert when a schema is created

In this case, we're creating a child rule under 50107, and matching the "CREATE DATABASE" query.

<details><summary>local_rules.xml</summary>

```xml
<group name="mysql_log,local,">
  <rule id="100002" level="5">
    <if_sid>50107</if_sid>
    <regex>Query\\tCREATE DATABASE</regex>
    <description>A database has been created</description>
  </rule>
</group>
```
</details>

<details><summary>Logtest output</summary>

```
**Phase 2: Completed decoding.
        name: 'mysql_log'
        query: 'CREATE DATABASE dhamo12345'

**Phase 3: Completed filtering (rules).
        id: '100002'
        level: '5'
        description: 'A database has been created'
        groups: '['mysql_log', 'local']'
        firedtimes: '1'
        mail: 'False'
**Alert to be generated.
```
</details>

### Option 3: Extend the decoder

Another option is to let the decoder catch the query, and then create a child rule under 50107 that matches the `query` field instead of the full log.

<details><summary>local_decoders.xml</summary>

```xml
<decoder name="mysql_log_query">
  <parent>mysql_log</parent>
  <regex>Query\\t(\.+)</regex>
  <order>query</order>
</decoder>

<decoder name="mysql_log_query">
  <parent>mysql_log</parent>
  <regex>CREATE DATABASE (\S+)</regex>
  <order>schema</order>
</decoder>
```
</details>

<details><summary>local_rules.xml</summary>

```xml
<group name="mysql_log,local,">
  <rule id="100002" level="5">
    <if_sid>50107</if_sid>
    <field name="query">^CREATE DATABASE</field>
    <description>A database has been created: $(schema).</description>
  </rule>
</group>
```
</details>

<details><summary>Logtest output</summary>

```
**Phase 2: Completed decoding.
        name: 'mysql_log'
        query: 'CREATE DATABASE dhamo12345'
        schema: 'dhamo12345'

**Phase 3: Completed filtering (rules).
        id: '100002'
        level: '5'
        description: 'A database has been created: dhamo12345.'
        groups: '['mysql_log', 'local']'
        firedtimes: '1'
        mail: 'False'
**Alert to be generated.
```

</details>

You can combine these options and also define your own solution based on these examples.

Hope it helps.

Best regards.

**Comment by aravindcyberfort** [comment]
Hi @vikman90 
This is not the log format  I'm getting
'MySQL log: 230424 12:43:29 34 Query\tCREATE DATABASE dhamo12345'
echo 'MySQL log: 230424 12:43:29 34 Query\tCREATE DATABASE dhamo12345' | /var/ossec/bin/wazuh-logtest

**Comment by vikman90** [comment]
@aravindcyberfort According to the archive you wrote above:

```json
{
  "timestamp": "2023-04-24T12:43:30.559+0530",
  "agent": {
    "id": "003",
    "name": "ubuntu-mariadb",
    "ip": "192.168.40.62"
  },
  "manager": {
    "name": "wazuh-ML"
  },
  "id": "1682320410.220555",
  "full_log": "MySQL log: 230424 12:43:29 34 Query\tCREATE DATABASE dhamo12345",
  "decoder": {
    "name": "mysql_log"
  },
  "location": "/var/log/mysql/mariadb-audit.log"
}
```

That's not the original input (_/var/log/mysql/mariadb-audit.log_), but I assume you've set up a `<localfile>` stanza with format `mysql_log` which performs a previous transformation on the log.

Anyway, the `full_log` field of the archives matches the exact input that the decoder receives from the agent. That's why I've used:

```
MySQL log: 230424 12:43:29 34 Query\tCREATE DATABASE dhamo12345
```

as the Logtest utility (_/var/ossec/bin/wazuh-logtest_). This method emulates how _wazuh-analysisd_ will decode the logs and match the events with a rule.

You can set up the rules to your liking and test them with wazuh-logtest. When you're ready, simply restart the manager to apply the new ruleset, and from then on new MySQL logs should show up as alerts.

Sorry if I didn't understand something.

Best.

**Comment by aravindcyberfort** [comment]
Hi @vikman90 
Help me fix this issue.

![image](https://user-images.githubusercontent.com/130983319/234772834-f1acbe42-c0ec-4ebf-8195-7d92c28f12e9.png)

**Comment by vikman90** [comment]
@aravindcyberfort The first error means that wazuh-analysisd could not expand the resource limit. This usually happens in systems inside containers or parsers (such as Valgrind). That's not impact except on high-loaded production environments.

The rest of the errors are due to:
- Regexes don't support substrings (`|`) inside captures (`()`).
- `\b` is not recognized.

Please refer to the [Regex syntax](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html#regex-os-regex-syntax) documentation.

You may prefer to use [PCRE2](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/pcre2.html) to capture what you are looking for:

```xml
<regex type="pcre2">...</regex>
```

On the other hand, this is contradictory:
```xml
<prematch>^MariaDB Audit Plugin</prematch>
```
> The log must start with "MariaDB ...".

```xml
<regex>^Query\p\s+(\S+)</regex>
```
> The log must start with "Query" ¿?

If you want to match the regex **after** the prematch,, use:
```xml
<regex offset="after_parent">^\pQuery...</regex>
```

Refer to the [regex option](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/decoders.html#regex-decoders) documentation.

For instance:

```xml
<decoder name="mariadb-audit-query">
  <parent>mariadb-audit</parent>
  <regex offset="after_parent">^\p\s+Query\p\s+(\S+)</regex>
  <order>query_type</order>
</decoder>
```

PCRE version:

```xml
<decoder name="mariadb-audit-query">
  <parent>mariadb-audit</parent>
  <regex offset="after_parent" type="pcre2">^[[:punct:]]\s+Query[[:punct:]]\s+(SELECT|INSERT|UPDATE|DELETE) \b</regex>
  <order>query_type</order>
</decoder>
```

Lastly, I recommend using `wazuh-logtest` to test your ruleset, since each run loads a temporary ruleset, and restarting the manager only when it's running, so that it applies to incoming logs.

Best.
