### ISSUE TITLE
Timeout from socket when using check-manager-configuration

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#16996]
### Nightly 

| **Date** | **Commit** | **Execution** |
| --- | --- | --- |
| 2023-05-04 | https://github.com/wazuh/wazuh/commit/94916de |https://github.com/wazuh/wazuh/runs/13218697002|

The `test_cluster_endpoints` test failed during the nightly for 4.4, however, this test passed during release testing for 4.4.2-rc1. We need to investigate what could cause this error.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by davidjiglesias** [comment]
Adding the test results in txt:

[Test-results.txt](https://github.com/wazuh/wazuh/files/11396968/Test-results.txt)

**Comment by fdalmaup** [comment]
# Issue Update

The failed tests are:
- `test_cluster_endpoints.tavern.yaml::GET /cluster/configuration/validation`
- `test_cluster_endpoints.tavern.yaml::PUT /cluster/{node_id}/configuration`

Both endpoints make use of the `validate_ossec_conf` method implemented in `wazuh/core/manager.py` which is the trigger of the failure.

The shown error in the logs is a code status `500` due to the `Timeout executing API request` error in the master and workers.
This timeout error in `GET /cluster/configuration/validation` was investigated in #6746 and [here](https://github.com/wazuh/wazuh/issues/6746#issuecomment-1077452699) was described the relation with the `PUT /cluster/{node_id}/configuration` endpoint. After further investigation, it was determined that it was not directly related to the endpoints themselves, but to a race condition related to analysisd.

**Comment by TomasTurina** [comment]
The modules involved will be refactored, so this issue will not be addressed.
