### ISSUE TITLE
Anomaly on Disk plot for Footprint Metrics tests - Active-response 4.4.2 RC1

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh#17012]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.2-rc1 | --- | Manager | --- | CentOS Manager |

Related: https://github.com/wazuh/wazuh/issues/16941

An anomaly has been found in the `DISK` plot for the Manager. Whereas in versions `4.4.0` and `4.4.1` the peaks are in 5 and 3 respectively, here there is a peak at 10 for the `wazuh-integradord` module.

<details>
  <summary>Releases comparison</summary>

#### 4.4.2
![image](https://user-images.githubusercontent.com/61122643/236414747-ea6a37c0-b172-4f2c-beb5-9b3b795bc99d.png)

#### 4.4.1 (https://github.com/wazuh/wazuh/issues/16572)
![image](https://user-images.githubusercontent.com/61122643/236414901-2eb7e6f4-dbdc-4e0d-8be5-689755c5ded6.png)

#### 4.4.0 RC2 (https://github.com/wazuh/wazuh/issues/16160)
![image](https://user-images.githubusercontent.com/61122643/236414990-fdafcbcc-8b52-4cde-a34e-9429e83aca09.png)

</details>

The logs can be found and downloaded in issue https://github.com/wazuh/wazuh/issues/16941 but they don't have any error or warning that could prompt the peak.

Complete logs for day 30:

```
2023/04/30 00:00:10 wazuh-monitord: INFO: Starting new log after rotation.
2023/04/30 22:46:49 wazuh-db: INFO: Created Global database backup "backup/db/global.db-backup-2023-04-30-22:46:49.gz"
2023/05/01 00:00:10 wazuh-monitord: INFO: Running daily rotation of log files.
```

**Comment by Nicogp** [comment]
**Questions:**
What does Disk mean? Disk write/read?
Could we get the alert.json or alert.logs of the three tests?

### Analysis:
First of all we notice that the module that makes the peaks is `wazuh-analysisd` instead of `wazuh-integratord` and after reviewing the [Changelog ](https://github.com/wazuh/wazuh/blob/v4.4.2-rc1/CHANGELOG.md#v442)we see that no changes related to `wazuh-analysisd` have been introduced.

Analyzing the graphs we see that the lines for `wazuh-analysisd`, `wazuh-remoted` and `wazuh-db` copy exactly the same pattern, this is due to the events sent by the agents:
`wazuh-remoted` receives them, `wazuh-analysisd` processes them and `wazuh-db` stores the info. 

That said, we assume that the increase may be due to a higher number of events processed by `wazuh-manager`, since if we compare the three graphs the increase is proportional:

DISK
|| 4.4.2 | 4.4.1 | 4.4.0 |
|---|---|---|---|
|wazuh-analysisd|10|3|5.6|
|wazuh-remoted|4|1.3|2.2|
|wazuh-db|3.5|1.1|1.8|


in all 3 graphs the peak of wazuh-analysisd is slightly more than twice that of wazuh-remoted

Therefore, we conclude that the agents sent a higher number of events to the wazuh-manager for analysis, this may be related to the [added changes](https://github.com/wazuh/wazuh/blob/v4.4.2-rc1/CHANGELOG.md#agent) in the wazuh-agents (**Added:**
Added a new module to integrate with Amazon Security Lake as a subscriber. ([#16515](https://github.com/wazuh/wazuh/pull/16515))
Added support for localfile blocks deployment. ([#16847](https://github.com/wazuh/wazuh/pull/16847))
Added macOS 13.0 Ventura SCA policy. ([#15566](https://github.com/wazuh/wazuh/pull/15566))
)
 and/or an increase of agents in the test.

**Comment by verdx** [comment]
As for the questions:

1.- The Disk graph shows the following metric: (Readings + Writings from Wazuh)/(Total Readings and writings)
2.- I'm afraid the alerts files for the tests are not stored, so it is not possible to look at them. 

Apart from that, your analysis does explain this behaviour and this issue could be closed on it.
