### ISSUE TITLE
Wazuh API Syscollector

### ISSUE THREAD

**Issue by thanvantrong** [wazuh/wazuh#17039]
Hi,

I use Wazuh version 4.3.10
Wazuh api now support get process of agent from last scan.
How Wazuh api can run syscollector when send request to agent (all or agent_lists) and get new update results like syscheck api with scan and get result?

Best Regards,

**Comment by Dwordcito** [comment]
Hi @thanvantrong I hope you are well.

We are currently working on the vulnerability detector refactor(https://github.com/wazuh/wazuh/issues/14153), in which we want to drive to events.

To make this possible, we plan to make parts of SysCollector event-driven so you can have such data in real time.

Apart from this, we seek to bring such information to the wazuh indexer. To have fast navigability on this data, allowing you to get the most out of it!

By achieving this objective, what you are looking for could be realized, and the on-demand update you propose will lose meaning since you can see everything in real-time.
