### ISSUE TITLE
The non-existing item error is skipped during catalog update

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#17042]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh/issues/16156   |     https://github.com/wazuh/wazuh/pull/16235 |
# Description
During the reorganization API testing the `catalog.resource/put`, the request does not fail when you use a non-existing item when it should.
When you try to update a non-existing item
```
{'version': 1, 'origin': {'name': 'engine', 'module': 'api'}, 'command': 'catalog.resource/put', 'parameters': {'name': 'decoder/wazuh/0', 'format': 'json', 'content': '{}'}}
```
As the item is not loaded, the content is no relevant and it should fail before verify the content
The error obtained is the following one
```
{"data":{"status":"ERROR","error":"Field 'name' is missing in content"},"error":0}
```
> This also happens when updating them by version.
## Considerations
More details in the dev-testing report https://github.com/wazuh/wazuh-qa/issues/4041
| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 
> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
This is not an error.

You attempted to update a decoder that does not exist. However, the system first validates the content before checking the existence of the decoder. Since the name of the decoder is missing, the validation process does not proceed to check if the decoder exists.

The API query requires two parameters: the content and the name of the decoder to update. Because the content is invalid, the second parameter (the name of the decoder) is not verified.
