### ISSUE TITLE
Detected growth in decoded events in 4.4.2 RC2 vulnerability detector footprint test

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#17137]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.2| vulnerability detector | Manager | Packages | Linux |

We have noticed an increase in the events decoded by the manager in 4.4.2 RC2 with an increase of almost 1000 events:
**RC2**
![image](https://github.com/wazuh/wazuh/assets/19505384/3ae1b101-2a8c-4e07-92e9-b27432891f9f)
**RC1**
![image](https://github.com/wazuh/wazuh/assets/19505384/ea915a80-8709-41c6-9396-8d6927a3b265)

Footprint issue:
https://github.com/wazuh/wazuh/issues/17111

**Comment by MarcelKemp** [comment]
Hi team!

This increase in Vulnerability Detector events in the manager may be normal, due to some change in the feeds, such as the addition of new vulnerabilities.

For example, on `10/May/2023`, in the MSU 200 CVEs were added corresponding to 6 different months that were not correctly received by the MSRC API (including around 100 CVEs corresponding to vulnerabilities from 2022 and 2023), which would explain this increase, since the first test (RC1) was performed on `30/Apr/2023` and the second (RC2) on `12/May/2023`.

Also, if the agent has been able to receive more information from Syscollector about _packages_ or _hotfixes_ that are vulnerable, it is normal that more vulnerability events appear.
