### ISSUE TITLE
Manager failed to issue the upgrade wpk package command！

### ISSUE THREAD

**Issue by wzyhay** [wazuh/wazuh#17132]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.8 | Wazuh component | Manager | Sources（build on Linux bxv-dsecuritywazuhmanager-01 3.10.0-514.26.2.el7.x86_64 https://github.com/wazuh/wazuh/pull/1 SMP Tue Jul 4 13:29:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux） | Linux bxv-dsecuritybasvulnhub-02 5.16.16-1.el7.elrepo.x86_64 https://github.com/wazuh/wazuh/pull/1 SMP PREEMPT Fri Mar 18 09:42:46 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux |

Hello, dear Wazuh team!
I have a wazuh cluster, and its manager and agent versions are both 4.3.8. Currently, I have encountered an error while using the master node to issue command line commands to upgrade the agent on the agent node
The command is as follows:
/var/ossec/bin/agent_ upgrade-a 14454-f/root/priv/wazuh-agent_ v4.3.11 linux x86_ 64.wpk-x upgrade.sh
The error message is: WPK file does not exist.
But this file does exist. I downloaded it from the official manual and tried changing the name, but it didn't work either
I am certain that the command was not issued to the agent node because I did not see the upgrade. log generation on the agent node. I speculate that the problem is on the manager side, but I cannot find the cause.
![bosshi-20230516090549-2](https://github.com/wazuh/wazuh/assets/104085895/5a961d24-b840-42f4-8c79-9472f4f1b6bc)
![______2023-05-15_20 41 18](https://github.com/wazuh/wazuh/assets/104085895/c39cab0c-d079-4fa5-b4ee-6d77ab47793c)

**Comment by wzyhay** [comment]
I made a few changes to the script
/var/ossec/framework/scripts/agent_upgrade.py
The local_master parameter in send_commande was changed to true, and the error message was:
Send lock restart error
![______2023-05-15_18 07 40](https://github.com/wazuh/wazuh/assets/104085895/69956ca0-f8e3-4e7b-99ea-c8a560cdc090)
![______2023-05-15_17 19 44](https://github.com/wazuh/wazuh/assets/104085895/e1a34094-3b09-4bc1-aea5-0f5408a66e59)

**Comment by jftuduri** [comment]
Hello @wzyhay!

What I believe is going on here is that the agent that you are trying to upgrade is connected to one of the worker nodes, and the custom WPK file is only located on the master node.

Take a look a [this](https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/agent-upgrade-module.html#agent-upgrade-module):
![image](https://github.com/wazuh/wazuh/assets/7939712/714cc595-a74e-487c-b99c-8a23bbadd6cc)

Could that be the case?
You can try copying the custom WPK to all the required nodes and send the command again.

On another note, if you are trying to upgrade to the official 4.3.11 version you can use the normal upgrade [indicating the version with the -v option](https://documentation.wazuh.com/current/user-manual/reference/tools/agent-upgrade.html).
And, if I understand correctly, you are using a manager with version 4.3.8 to upgrade an agent to v4.3.11. In order to ensure compatibility the version of the manager must always be newer than or equal to the agent's versions: [https://documentation.wazuh.com/current/user-manual/reference/tools/agent-upgrade.html
](https://documentation.wazuh.com/current/user-manual/reference/tools/agent-upgrade.html)
So it is recommended that you upgrade the manager first, and only then upgrade the agents.

Regards!

**Comment by wzyhay** [comment]
Thank you for your reply. I have deployed a manager cluster and managed the agent through nginx load balancing. Initially, I only deployed wpk files on the master node. Just now, I also deployed the same wpk files on all worker nodes in the same path. However, when upgrading on the master node, I still reported the same error, WPK file does not exist

**Comment by jftuduri** [comment]
Could you try again upgrading one of the agents on the master node but this time use an absolute path instead of a relative one?
(I understand that at first you tried with an absolute path, but that was on an agent on a worker node before copying the wpk to that node)

Here I have a WPK file on the root dir. First I try with a relative path and I get the same error, then, using an absolute path the upgrade completes correctly:
![image](https://github.com/wazuh/wazuh/assets/7939712/cf32ce00-4fdf-481a-b025-98231ba7a279)

Let's see if this solves the upgrade on the master node first. Let me know how it goes.
Regards!

**Comment by wzyhay** [comment]
Thank you very much for your suggestion!After modifying it to an absolute path, there will no longer be such errors. In fact, it still brings new problems. Some machines have been successfully upgraded, but there are still new errors
Failed upgrades:
Agent 14454 status: Send upgrade command error
![截屏2023-05-18 14 52 11](https://github.com/wazuh/wazuh/assets/104085895/03da2818-e9e8-41c0-a148-c01f1432812e)
I checked the ossec.log on the agent machine and found that I have received the corresponding upgrade log, but I don't know why this error occurred
![截屏2023-05-18 14 45 59](https://github.com/wazuh/wazuh/assets/104085895/0c0b60a9-f1d4-4422-97c4-7bfeb9f74762)

**Comment by wzyhay** [comment]
Hi @jftuduri Thank you again for your reply. I think I just solved the problem.
I think I encountered two issues throughout the entire process, namely the file does not exist and the upgrade command failed to be issued
Based on your suggestion, I resolved it as follows:
Firstly, I deployed about 20 worker nodes, which together with the master to form a manager cluster. Through nginx, I managed an agent cluster. Initially, I wanted to use the master node to control an agent upgrade to version 4.3.11 (official version), but I failed. The error I reported was that the file did not exist. I made two modifications to resolve this error, but I don't know if it meets the expectations of the Wazuh team
1. I modified the path of the wpk file from relative to absolute, and the command was changed to
/var/ossec/bin/agent_upgrade -a 14454 -f /root/wazuh_agent_v4.3.11_linux_x86_ 64.wpk
2. I did not place the wpk file on the worker node before reporting an error, wazuh_ agent_ v4.3.11_ linux_ x86_ 64. The wpk only exists in the master node, and in the future, I will store a copy of the same wpk file under/root/for each worker node
After the above modifications were completed, I executed the upgrade command again, which skipped the error message 'File does not exist'.
But when I was locating and troubleshooting the above issues, I had modified the WPK_ Root.pem (of course I remember to backup), but later I forgot to rollback the backup. I found the cause of the error in the ossec.log of the agent node. When I rollback the backup and execute the upgrade command, this time it was successful.
![截屏2023-05-18 15 18 08](https://github.com/wazuh/wazuh/assets/104085895/1e3757f7-6137-4e09-adc3-5e9eabce4e23)
![截屏2023-05-18 21 23 03](https://github.com/wazuh/wazuh/assets/104085895/d98491d9-07df-42d1-804c-287d9614549b)

**Comment by jftuduri** [comment]
Hi @wzyhay!
It's great that you got it to work!
I think it is clear now. 
The '`send upgrade command error`' was caused by using the wrong certificate, as you discovered.
About relative/absolute paths, the working dir for the upgrade module (and I'd say for every Wazuh binary) is the install directory (`/var/ossec/` by default), so when you use a relative path with the agent_upgrade tool the upgrade module tries to find the file relative to its working directory and results in 'WPK file does not exist'.


Regards!
