### ISSUE TITLE
Difference in memory usage between 4.4.2 RC2 and RC1 in vulnerablility detector footprint test

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#17136]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.2 | Vulnerablility detector | Agent | Packages | Windows |

We have noticed a difference in behaviour in the footprint metrics between 4.4.2 RC2 and RC1 as showed in the graphs:
**RC2**
![image](https://github.com/wazuh/wazuh/assets/19505384/8dcd6a14-b9da-4ec8-b663-7fdef6addf8d)

**RC1**
![image](https://github.com/wazuh/wazuh/assets/19505384/3823de29-b539-470d-8744-ef82690c988d)

Footprint issue:
https://github.com/wazuh/wazuh/issues/17111

**Comment by vikman90** [comment]
## Agent memory in different versions

### 4.4.0

![image](https://camo.githubusercontent.com/7f0c772907c7b707bb5908243f23a2ac9f601db8b83f5cc72d108618c07141b0/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e302f42333830332d333630306d2f42333830335f6167656e745f77696e646f77732f706c6f74732f6d6f6e69746f722d77696e6167656e742d546573745f7374726573735f42333830335f77696e646f77732d7072652d72656c656173655f5253535f4d41584d494e2e706e67)


### 4.4.1

![image](https://camo.githubusercontent.com/943424648c5373b31049037c9a01ba937e7bd129d241533214f3a63c985b34da/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e312f42333836332d333630306d2f42333836335f6167656e745f77696e646f77732f706c6f74732f6d6f6e69746f722d77696e6167656e742d546573745f7374726573735f42333836335f77696e646f77732d7072652d72656c656173655f5253535f4d41584d494e2e706e67)

### 4.4.2 RC1

![image](https://user-images.githubusercontent.com/19505384/238620614-3823de29-b539-470d-8744-ef82690c988d.png)

### 4.4.2 RC2

![image](https://user-images.githubusercontent.com/19505384/238620492-8dcd6a14-b9da-4ec8-b663-7fdef6addf8d.png)

## Table

|Version|Issue|Max memory|
|---|---|
|4.4.0|https://github.com/wazuh/wazuh/issues/16450|17.850 MB|
|4.4.1|https://github.com/wazuh/wazuh/issues/16578|17.890 MB|
|4.4.2 RC1|https://github.com/wazuh/wazuh/issues/16940|18.050 MB|
|4.4.2 RC2|https://github.com/wazuh/wazuh/issues/17111|18.200 MB|

## Conclusion

4.4.2 seems to be ocuppying ~235 KB more than 4.4.1. There is a 150 KB difference between 4.4.2 RC1 and RC2. This must be due to any circumstance in the host or the test, but it does not necessarily mean there is a bug.
