### ISSUE TITLE
Vulnerability scanner report KB not applicable

### ISSUE THREAD

**Issue by eglyn** [wazuh/wazuh#17133]
Hi, 

I have an issue with the vulnerability scanner, wiith Windows 11 agent (Wazuh 4.4.1)

It report a KB not intalled: 
![image](https://github.com/wazuh/wazuh/assets/24936778/f2f39308-cbe3-44f9-a861-af2fa15d6df7)

But, Windows Update says there is no update, PC is up to date. When I try to install the KB manually, Windows say that the KB is not applicable.

Why this KB is report on Wazuh ?

**Comment by MarcelKemp** [comment]
Hi @eglyn,

This is a known issue that we are working to fix ASAP.

The following issue is being worked on:
- https://github.com/wazuh/wazuh/issues/15160

And the issue is due to the CPE change that has been applied to the NVD, as it used to be the Windows 11 CPE:
- [`cpe:2.3:o:microsoft:windows_11:-:*:*:*:*:*:x64:*`](https://nvd.nist.gov/products/cpe/detail/46138D1E-853D-4899-9D8F-E1B0E8D484D0?namingFormat=2.3&orderBy=CPEURI&keyword=cpe%3A2.3%3Ao%3Amicrosoft%3Awindows_11%3A-%3A*%3A*%3A*%3A*%3A*%3A*%3A*&status=FINAL%2CDEPRECATED)
However, it seems to have been deprecated and is now:
- [`cpe:2.3:o:microsoft:windows_11_22h2:-:*:*:*:*:*:x64:*`](https://nvd.nist.gov/products/cpe/detail/E4604687-B03E-478C-B119-226D2BF51448?namingFormat=2.3&orderBy=CPEURI&keyword=cpe%3A2.3%3Ao%3Amicrosoft%3Awindows_11_22h2%3A-%3A*%3A*%3A*%3A*%3A*%3A*%3A*&status=FINAL%2CDEPRECATED)

This results in a mismatch with the corresponding vulnerability and therefore the version 21H2 patch is reported, instead of version 22H2. 

> Examples:
> - Old CPE: https://nvd.nist.gov/vuln/detail/CVE-2022-44698#vulnConfigurationsArea
> - New CPE: https://nvd.nist.gov/vuln/detail/CVE-2023-28250#vulnConfigurationsArea

Sorry for the inconvenience.

**Comment by eglyn** [comment]
Thx for your answer :)

**Comment by MarcelKemp** [comment]
Hi @pillbug22,

We can't offer you an ETA, but we will try to get it ASAP, which will probably be one of the next patch releases (`v4.4.3` or higher).

**Comment by pillbug22** [comment]
Thanks for the response; didn’t think you had a specific release in mind, but had to ask…Thank you for the work you guys are doing!On May 18, 2023, at 4:26 AM, Marcel Kemp Muñoz ***@***.***> wrote:﻿
Hi @pillbug22,
We can't offer you an ETA, but we will try to get it ASAP, which will probably be one of the next patch releases (v4.4.3 or higher).

**Comment by paglia1968** [comment]
any news?

**Comment by MarcelKemp** [comment]
The PR is merged, now we just need to get the next patch release out:
- https://github.com/wazuh/wazuh/pull/17178
- https://github.com/wazuh/wazuh/issues/17520
