### ISSUE TITLE
Upgrade to v4.4.0 on Windows fails to start agent service

### ISSUE THREAD

**Issue by jftuduri** [wazuh/wazuh#17141]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0 | WPK upgrade | Agent | Packages | Windows |

# Description

On occasions, the upgrade to agent v4.4.0 on Windows systems fails when the upgrade script attempts to start the newly installed service and [waits to detect the new process](https://github.com/wazuh/wazuh/blob/2477e9fa50bc1424e834ac8401ce2450a5978e75/src/win32/do_upgrade.ps1#L255-L265) id.
When the following line is found on the upgrade.log file it indicates that the Wazuh agent process was not found:

```
2023-05-16 13:25:23Z - Process ID: .
```

One possible reason for this is that service corresponding to the new version got installed incorrectly. Further research must be done to narrow down the cause of this and to determine if this is a problem of the WPK upgrade or the MSI installer.

# Sample logs
<details>
<summary>
Case 1:

</summary>
Partial upgrade.log

```
2023-05-16 10:58:54Z - Trying to stop Wazuh service.
2023-05-16 10:58:56Z - Starting upgrade processs.
2023-05-16 10:59:03Z - Restarting Wazuh-Agent service.
2023-05-16 10:59:03Z - Installation finished.
2023-05-16 10:59:23Z - Process ID: .
2023-05-16 11:00:34Z - Reading status file: status=''.
2023-05-16 11:00:34Z - Upgrade failed: Restoring former installation.
2023-05-16 11:00:34Z - Trying to stop Wazuh service.
2023-05-16 11:00:36Z - Wazuh-Agent uninstall command was not found.
2023-05-16 11:00:36Z - Restoring former Wazuh-Agent home files.
2023-05-16 11:00:36Z - Current version: v4.3.10.
2023-05-16 11:00:36Z - Installing Wazuh service.
2023-05-16 11:00:37Z - Starting Wazuh-Agent service.
```

Relevant ossec.log lines:
```
2023/05/16 10:58:54 wazuh-agent[8888] win_service.c:256 at OssecServiceCtrlHandler(): INFO: Received exit signal. Starting exit process.
2023/05/16 10:58:54 wazuh-agent[8888] win_service.c:260 at OssecServiceCtrlHandler(): INFO: Set pending exit signal.
...
2023/05/16 10:58:54 wazuh-agent[8888] win_service.c:268 at OssecServiceCtrlHandler(): INFO: Exit completed successfully.
2023/05/16 10:58:54 wazuh-agent[8888] win_execd.c:41 at WinExecd_Shutdown(): INFO: (1314): Shutdown received. Deleting responses.
2023/05/16 11:00:37 wazuh-agent: INFO: Service does not exist (WazuhSvc) nothing to remove.
2023/05/16 11:00:37 wazuh-agent: INFO: Successfully added to the service database.
2023/05/16 11:00:37 wazuh-agent[14120] win_utils.c:89 at local_start(): DEBUG: Reading agent configuration.
```
In this case, the agent receives the exit signal at `10:58:54` matching the `Trying to stop Wazuh service` log from the upgrade log.
Then there are no logs until `11:00:37` when the upgrade scripts restarts the service after aborting the upgrade and restoring the previous version.
</details>

[case1.zip](https://github.com/wazuh/wazuh/files/11490840/case1.zip)

<details>
<summary>
Case 2:
</summary>

Partial upgrade.log
```
2023-05-16 13:24:47Z - Backing up Wazuh-Agent cached MSI: "C:\Windows\Installer\73d2e.msi".
2023-05-16 13:24:48Z - Trying to stop Wazuh service.
2023-05-16 13:24:53Z - Starting upgrade processs.
2023-05-16 13:24:55Z - Restarting Wazuh-Agent service.
2023-05-16 13:24:55Z - Installation finished.
2023-05-16 13:25:23Z - Process ID: .
2023-05-16 13:26:34Z - Reading status file: status=''.
2023-05-16 13:26:34Z - Upgrade failed: Restoring former installation.
2023-05-16 13:26:34Z - Trying to stop Wazuh service.
2023-05-16 13:26:37Z - Performing the Wazuh-Agent uninstall using: "MsiExec.exe /X{F2DEA62A-978B-49E5-9CFA-CCC66142C99A} /quiet".
2023-05-16 13:26:43Z - Excecuting former Wazuh-Agent MSI: ".\backup\73d2e.msi".
2023-05-16 13:26:44Z - Restoring former Wazuh-Agent home files.
2023-05-16 13:26:46Z - Current version: v4.3.10.
2023-05-16 13:26:46Z - Installing Wazuh service.
2023-05-16 13:26:46Z - Starting Wazuh-Agent service.
```

Relevant ossec.log lines
```
2023/05/16 13:24:48 wazuh-agent: INFO: Received exit signal. Starting exit process.
2023/05/16 13:24:48 wazuh-agent: INFO: Set pending exit signal.
2023/05/16 13:24:48 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2023/05/16 13:24:48 wazuh-modulesd:syscollector: INFO: Module finished.
2023/05/16 13:24:48 wazuh-agent: INFO: Exit completed successfully.
2023/05/16 13:24:48 wazuh-agent: INFO: (1314): Shutdown received. Deleting responses.
2023/05/16 13:26:46 wazuh-agent: INFO: Found (WazuhSvc) service is not running.
2023/05/16 13:26:46 wazuh-agent: INFO: Successfully removed (WazuhSvc) from the service database.
2023/05/16 13:26:46 wazuh-agent: INFO: Successfully added to the service database.
2023/05/16 13:26:46 wazuh-agent: INFO: Using notify time: 10 and max time to reconnect: 60
2023/05/16 13:26:46 wazuh-agent: INFO: (1410): Reading authentication keys file.
2023/05/16 13:26:47 wazuh-agent: INFO: Started (pid: 3812).
2023/05/16 13:26:47 wazuh-agent: INFO: Server IP Address: 192.168.31.231
```
In this case, the agent receives the exit signal at `13:24:48` matching the `Trying to stop Wazuh service` log from the upgrade log.
Then there are no logs until `13:26:46` when the upgrade scripts restarts the service after aborting the upgrade and restoring the previous version.
</details>

[case2.zip](https://github.com/wazuh/wazuh/files/11490851/case2.zip)

**Comment by tsarquis88** [comment]
I'm having a similar behavior when the Windows upgrade script performs a rollback (due to an upgrade failure).
It happened on Windows 10 64 bits english version and french version.

Apparently, after the rollback, the Wazuh Agent service is not found, being impossible to relaunch the agent.

### Steps to reproduce

- Install Wazuh Agent
- Start remote upgrade, specifying the WPK file (manager-side)
- Force upgrade failure (In my case, I stopped the connection between agent and manager)

### Expected behavior

Rollback is performed without any problem. The agent remains in its before-upgrade version and it can continue running.

### Actual behavior

The agent remains in its before-upgrade version but it can't continue running.

#### Logs right after the failed upgrade (english Windows - agent v4.4.4)

Upgrade log:
![image](https://github.com/wazuh/wazuh/assets/42682247/c975f1ae-7e35-4cc6-b5e7-4308cd4cf031)

Ossec log:
![image](https://github.com/wazuh/wazuh/assets/42682247/5d1ef94c-20bb-4ab3-83fd-b51c5b29433c)

Start agent manually:
![image](https://github.com/wazuh/wazuh/assets/42682247/f038c59b-cf8d-4bdd-be37-cd3cc7374235)

#### Logs right after the failed upgrade (french Windows - agent v4.0.0)

Upgrade log:
![image](https://github.com/wazuh/wazuh/assets/42682247/65e158e4-bc1a-4a97-b5c1-795261404caf)

Ossec log:
![image](https://github.com/wazuh/wazuh/assets/42682247/68781f82-64df-4ab9-8ca7-8a2683672f2c)

**Comment by jftuduri** [comment]
Hi @tsarquis88!
Do you happen to have the `installer.log` file of this installation?
Thanks!
