### ISSUE TITLE
Community - Search a given string on all events via dashboard

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#17145]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.1 | Dashboard | Manager | Packages | Ubuntu 22.04 |

The userwants to search a given string across all events on the dashboard. 

Some of the fields that contain the information it wants to search are not indexed by default, so in order to do so it needs to modify the indexed fields and re-index the data

Link to the community: https://wazuh.slack.com/archives/C0A933R8E/p1684232655036209 
Conversation in txt (Backup in case the thread is deleted): [conversation.txt](https://github.com/wazuh/wazuh/files/11516509/conversation.txt)

**Comment by captainido** [comment]
Helo,
Please update.

**Comment by Tostti** [comment]
The Wazuh Dashboard uses a template that contains the fields to be mapped. If an alert has a field that is not included in the template, there may be some limitations in the use, such as searching and using the data to create visualizations. 

If that is the case, it will be necessary to add the field to the template, with the following steps: 

- Identify the required fields.
- Download the [template](https://raw.githubusercontent.com/wazuh/wazuh/v4.4.2/extensions/elasticsearch/7.x/wazuh-template.json)
``` console
# curl -so /etc/filebeat/wazuh-template.json https://raw.githubusercontent.com/wazuh/wazuh/v4.4.2/extensions/elasticsearch/7.x/wazuh-template.json
# chmod go+r /etc/filebeat/wazuh-template.json
```
- Add the field to the template. It should go in the `settings/index.query.default_field` section, and also in `mapping/properties` to specify the data type. 
- Verify that the `setup.template.json.path` property in `/etc/filebeat/filebeat.yml` is pointing to the location of the modified template.
- Apply the template with `filebeat setup --index-management -E output.logstash.enabled=false` and restart Filebeat. 
- From the dashboard, navigate to `Stack Management/Index patterns`, open `wazuh-alerts-*` and confirm if the field appears as searchable. In case it doesn't, navigate to `Stack Management/Saved Objects` and remove the object `wazuh-alerts-*`. This will not cause any data loss, and the index pattern will be recreated the next time that the Wazuh Plugin section is opened. 
![imagen](https://github.com/wazuh/wazuh/assets/42900763/31f684df-e2b8-4e6d-a3ce-163b7c4bd1a0)


This will apply the template to all the new generated indices. By default, Wazuh generates alerts indices daily, so it will apply from the following day. In case that the information from current and previous indices is needed, it will be necessary to reindex all of them in order to apply the template correctly.

**Comment by captainido** [comment]
Hello all the steps done and I can see the fields in dashboard and waiting 8 hours for new events and still cannot be search string over the field data.message and others:
<img width="956" alt="image" src="https://github.com/wazuh/wazuh/assets/133489572/344a7ca7-ab16-4713-a475-047ab094dccf">

**Comment by captainido** [comment]
Hello,
Still not working.
Please your advice.

**Comment by captainido** [comment]
Problem solved. 
Thanks for your great support.
