### ISSUE TITLE
Wazuh is detecting critical vulnerability in  snappy, but its pointing to another package

### ISSUE THREAD

**Issue by e-massaad** [wazuh/wazuh#17182]
|Wazuh version|Component|Install type|Install method|Platform|
4.4.1|Vulnerability Detector|On Prem|Installation Assistance|Linux
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

I have Snappy installed on one of our Linux machines

yum info snappy-1.1.8-3.el8.x86_64

Summary     : Fast compression and decompression library

URL         : https://github.com/google/snappy

Wazuh is detecting a critical vulnerability on that server about snappy, but it is pointing to anther package

CVE: CVE-2023-28115

Condition: Package less than 1.4.2

References: https://github.com/KnpLabs/snappy/releases/tag/v1.4.2
 
Only the package name is similar

However the installed Snappy that we have is not vulnerable

How wazuh got confused ? and how can we sort that issue without adding the CVE to the white list ?

**Comment by MarcelKemp** [comment]
Hi @e-massaad, 

The problem is because the vulnerability is not found in the OVAL, so we look for this vulnerability in the NVD feed, however the difficulty appears in the search for vulnerabilities, as on Linux, we "generate the CPE" according to the `name`, `source`, and `version` of the package, so that by not adding the `vendor`, it matches these vulnerabilities causing the false positive.

On the other hand, we have a difficulty with this type of false positives, because we cannot add the `vendor` to the CPE for Linux cases, as it would cause many vulnerabilities not to be checked due to the lack of normalization in the vendor names of the package and would generate false negatives.

After a little research, I have been able to determine that the problem is probably to be found in the following two queries: 
- https://github.com/wazuh/wazuh/blob/b2901d5086e7a073d89f4f72827e070ce3abd8e8/src/wazuh_modules/vulnerability_detector/wm_vuln_detector_db.h#L300
- https://github.com/wazuh/wazuh/blob/b2901d5086e7a073d89f4f72827e070ce3abd8e8/src/wazuh_modules/vulnerability_detector/wm_vuln_detector_db.h#L312

In which, as I mentioned, the `vendor` is not being checked and this is causing the match with the vulnerability. This change was made in the following PR:
- https://github.com/wazuh/wazuh/pull/6290

So we would have to check if it is possible to use the old query (or the ones currently used for macOS) for all OSes and see the difference in results:
- https://github.com/wazuh/wazuh/blob/b2901d5086e7a073d89f4f72827e070ce3abd8e8/src/wazuh_modules/vulnerability_detector/wm_vuln_detector_db.h#L346
- https://github.com/wazuh/wazuh/blob/b2901d5086e7a073d89f4f72827e070ce3abd8e8/src/wazuh_modules/vulnerability_detector/wm_vuln_detector_db.h#L352

Sorry for the inconvenience.

**Comment by MarcelKemp** [comment]
## Research with the proposed fix

After researching the problem and testing the proposed fix, the following information has been found:

The proposed fix added back the condition for the `vendor` to be checked, however it has been found that on Linux it is a bit contradictory, because the `vendors` assigned to packages by some OSes when downloading via the main repository are specific. Examples:
- Ubuntu: The `vendor` for packages is `Ubuntu Developers`.
- CentOS: The `vendor` of the packages is `CentOS`.

So you have seen three scenarios:
- Only the vulnerability appears in the `OVAL`. 
  - For this case, it would not affect the fix, as it would match the OVAL condition.
  - Ex: [OVAL](https://access.redhat.com/security/cve/CVE-2023-2222)
- Only the vulnerability appears in the `NVD`. 
  - In case the `vendor` is not in the official vendor list (`wm_vuldet_linux_rm_nvd_not_affected_packages`) for its corresponding OS (i.e. the package is downloaded from a third party) and only the vulnerability exists in the NVD, which meets the versioning condition, then it would appear as vulnerable, and in case it does not correspond to its original vendor, it would cause a false positive (without the fix).
  - Ex: [NVD google](https://nvd.nist.gov/vuln/detail/CVE-2018-7577) - [NVD knplabs](https://nvd.nist.gov/vuln/detail/CVE-2023-28115)
- The vulnerability is found in both `OVAL` and `NVD.`
  - In case the OVAL condition is `Package unfixed`, if we apply the fix and check the `vendor` in the NVD, all packages that are installed by an original repository would be discarded, because they will have the `vendor` of the corresponding OS, so it would cause many false negatives (especially in older OS versions where the vast majority of conditions are `Package unfixed`).
  - Ej: [NVD](https://nvd.nist.gov/vuln/detail/CVE-2023-1972) + [OVAL](https://access.redhat.com/security/cve/CVE-2023-1972) (Package unfixed)

**Comment by andyjhull** [comment]
Any updates? we're getting this exact false positive as well.

**Comment by sycured** [comment]
Same with Wazuh 4.7.3

**Comment by FocusOnTheCell** [comment]
Getting the same false positive aswell. Any updates?

**Comment by sebasfalcone** [comment]
This issue no longer persists in 4.8.0

I've tested a centos8 and a centos9 agents
