### ISSUE TITLE
Windows Hotfixes and Vulnerabilities

### ISSUE THREAD

**Issue by shawarma-man** [wazuh/wazuh#17213]
I'm building a minimal script that detects Windows CVEs using the MSU json feed `https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.json.gz`

I wrote a code that builds the MSU, MSU_SUPERSEDENCE tables and they are identical to the ones you find in cve.db

I wrote the code that extracts the installed hotfixes on the system and it's also identical to the one wazuh finds (i tested it on a wazuh server)

I wrote a recursive code that takes the installed hotfixes and finds all the patches they superseded, it uses this sql statement `SELECT PATCH FROM msu_supersedence WHERE Super = ?` recursively.

finally it selects all CVEs where the product is "Windows 10 Version 22H2 for x64-based Systems" and the patch is not installed.

but when I compare the result of my script with wazuh's result mine has way more CVEs (289 vs 70)

**Comment by ashish-181** [comment]
Hi @shawarma-man 
> I wrote a code that builds the MSU, MSU_SUPERSEDENCE tables and they are identical to the ones you find in cve.db
Could you share how you built these tables? Specifically, how did you pull all this information from the Microsoft catalog? I believe there's no API available for this.

**Comment by ashish-181** [comment]
Hi @MarcelKemp,

Could you please explain how the file https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.json.gz is generated or created?

**Comment by MarcelKemp** [comment]
Hi @ashish-181, 

The MSU feed is generated by collecting the following information:

We get the vulnerability information from [Microsoft Security Response Center](https://msrc.microsoft.com/update-guide/vulnerability), where they have a section with all vulnerabilities affecting Microsoft OSes and programs.
 
Here, you can see the vulnerability information visually: https://msrc.microsoft.com/update-guide/vulnerability
 
In our case, we make use of the API offered by Microsoft, from which all the information I have mentioned can be obtained:
- https://github.com/microsoft/MSRC-Microsoft-Security-Updates-API

Then, to complement the information on the patches that fix the vulnerabilities, we make use of the [Microsoft Update Catalog](https://www.catalog.update.microsoft.com/home.aspx), from which we obtain by web scraping, the list of patches for which we have information to know the patches that '`replaces`' and '`replaced by`', in this way, detecting a recent cumulative patch that contains an old patch, we avoid alerting about the old vulnerability since the recent patch is supersedence of the old patch.
 
You can see more information here:
- https://github.com/wazuh/wazuh/issues/6525
- https://github.com/wazuh/wazuh/issues/13254

In the following issue, you can see some extra information:
- https://github.com/wazuh/wazuh/issues/16247#issuecomment-2332206617

However, note that the core code part of Wazuh has changed since `4.8.0`, so it works differently (the _MSU_ is currently still generated the same).

I hope this helps.

**Comment by ashish-181** [comment]
Thank you, @MarcelKemp for providing such detailed and comprehensive information.

**Comment by mai1x9** [comment]
> Hi [@ashish-181](https://github.com/ashish-181),
> 
> The MSU feed is generated by collecting the following information:
> 
> We get the vulnerability information from [Microsoft Security Response Center](https://msrc.microsoft.com/update-guide/vulnerability), where they have a section with all vulnerabilities affecting Microsoft OSes and programs.
> 
> Here, you can see the vulnerability information visually: https://msrc.microsoft.com/update-guide/vulnerability
> 
> In our case, we make use of the API offered by Microsoft, from which all the information I have mentioned can be obtained:
> 
> * https://github.com/microsoft/MSRC-Microsoft-Security-Updates-API
> 
> Then, to complement the information on the patches that fix the vulnerabilities, we make use of the [Microsoft Update Catalog](https://www.catalog.update.microsoft.com/home.aspx), from which we obtain by web scraping, the list of patches for which we have information to know the patches that '`replaces`' and '`replaced by`', in this way, detecting a recent cumulative patch that contains an old patch, we avoid alerting about the old vulnerability since the recent patch is supersedence of the old patch.
> 
> You can see more information here:
> 
> * [Improve the MSU generation and deployment #6525](https://github.com/wazuh/wazuh/issues/6525)
> * [Occasionally the MSU generator web scraping fails without collecting any Catalog hotfixes #13254](https://github.com/wazuh/wazuh/issues/13254)
> 
> In the following issue, you can see some extra information:
> 
> * [Vulnerability Detector Windows help #16247 (comment)](https://github.com/wazuh/wazuh/issues/16247#issuecomment-2332206617)
> 
> However, note that the core code part of Wazuh has changed since `4.8.0`, so it works differently (the _MSU_ is currently still generated the same).
> 
> I hope this helps.

@MarcelKemp 


I think the wazuh is missing some data points. For instance lets take `KB5043124` as an example. As per ms catalog for `KB5043124` https://catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=15592d8f-31eb-4f04-9f60-666d4a928c74#PackageDetails checking the **This update has been replaced by the following updates:** we have

```
2025-03 Servicing Stack Update for Windows Server 2016 for x64-based Systems (KB5054006)
2025-01 Servicing Stack Update for Windows Server 2016 for x64-based Systems (KB5050109)
2025-04 Servicing Stack Update for Windows Server 2016 for x64-based Systems (KB5055661)
```
- Clearly the KB5054006, KB5050109, KB5055661 supercedes the old patch `KB5043124`.

- Now lets take a patch from wazuh feed at: https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.json.gz as example I took: `KB5017396` which looks like

```
          "KB5017396": [
               "KB5039334",
               "KB5030504",
               "KB5034862",
               "KB5043124",
               "KB5037016",
               "KB5041576",
               "KB5040562",
               "KB5023788",
               "KB5032391",
               "KB5035962"
          ],
```
- Clearly `KB5043124` is in the array indicating that `KB5043124` supersedes the `KB5017396`. I cross validated with ms catalog at: https://catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=64441b6c-46bf-496f-9c2d-0c6192610215#PackageDetails which clearly says `KB5043124` replaces `KB5017396`

<img width="781" alt="Image" src="https://github.com/user-attachments/assets/2c47b2a4-dc21-4be3-9cb8-98083695a7c2" />

- Now my question is, why is the entry for `KB5043124` as Key missing in wazuh, all the KBs that supercedes the `KB5043124` is missing from wazuah, for instance something like
```
"KB5043124" : [ KB5054006, KB5050109, KB5055661  ]
```
- Cleary wazuh is missing this as a result, even if I have this KB installed `KB5054006` and a CVE vulnerability is fixed in `KB5043124`, still the vulnerability is detected though the supercedes `KB5054006` address the CVE.


@ashish-181 looping you for convo.
