### ISSUE TITLE
alerts.log does not exist on agent

### ISSUE THREAD

**Issue by andyjsmith** [wazuh/wazuh#1726]
## Bug report

**OS**
Debian 9.1

**Wazuh version**
3.6.1

**Wazuh API version**
3.6.1

**Install type**
agent

**Install method**
packages

Bug description
----------------
The Wazuh agent sends the alerts to the Wazuh API and Manager endpoint, and I can view them in Kibana. However, on the agent itself, there is no `alerts.log` file nor an alerts directory. So the agent is sending the logs without storing them locally.
```
Wazuh Agent Endpoint:
root@andys:/var/ossec# ls logs
active-responses.log  ossec  ossec.log
```
Is this an intended feature? I have been trying all options, such as setting `<log_alert_level>` and `<alerts_log>`, but neither have made the logs save locally to the agent. My specific use case needs the logs to stay local on the agent side for assurance purposes because they need to be sent to our log server as well as being sent to the Wazuh manager/API.

I appreciate the work you all are doing, sorry if this has been submitted before.

**Comment by cristgl** [comment]
Hello @andyjsmith,

The Wazuh agent is not intended to have an `alerts.log` file. This is only contemplated on the manager side. The process for receiving an alert is the next one:
- The agent gathers information about its system and applications.
- The agent proceeds to send this collected data to the manager through an authenticated channel, built when registering the agent.
- The server processes the received data and generates an alert when an agent's event matches with a predefined rule.

The `alerts` field options, such as `<log_alert_level>` or `<alerts_log>` are meant to be configured at the manager side, since it is at this side where the alerts are being created.

How do you need to store this logs? 

Hope this can clarify your question and if you have anymore don't hesitate to ask us again.

Best regards

**Comment by cristgl** [comment]
Maybe this can help: [Syslog output](https://documentation.wazuh.com/current/user-manual/manager/manual-syslog-output.html?highlight=syslog)
Syslog can send the alerts generated at the manager to a syslog server, you can also modify the attributes to filter the alerts you need to store. If you need to clasify them by agent id, we will provide it for you for the next Wazuh release.

Kind regards

**Comment by andyjsmith** [comment]
Thanks for the response.
We are currently using a regular OSSEC installation on each of our endpoints, so each has their own alerts.log. I did not realize that upgrading to a Wazuh installation would mean that they are no longer stored locally on the agent and instead just on the manager, I think that answers my question. In our configuration, each endpoint already streams other logs like syslog and auth.log to our AWS CloudWatch instance for logging, so I was hoping there would be a way to keep the local alerts.log so that it could still be streamed as well. I will have to do some deliberation about whether I will switch over to Wazuh and upload the logs from the manager, if another solution like perhaps the syslog output you mentioned above would work, or if I will just stay with OSSEC.

Thanks again for your help.
