### ISSUE TITLE
`HP-UX` skips `SCA` policy if `bastille` is not installed

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#17278]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| At least 4.4.3-rc1 | SCA | Agent | Packages | HPUX |

During the analysis of the [HP-UX v4.4.3-rc1 package](https://github.com/wazuh/wazuh/issues/17241#issuecomment-1563036232), the following log was found:

```
2023/05/25 09:27:25 sca: INFO: Skipping policy '/var/ossec/ruleset/sca/cis_hpux_11i_bastille.yml': 'Check HPUX version, bastille is installed and a bastille report is present.'
2023/05/25 09:27:26 sca: INFO: Skipping policy '/var/ossec/ruleset/sca/cis_hpux_11i.yml': 'Check HPUX version and bastille is not installed.
```

Consideration should be given to changing this message from INFO to WARNING, as a dependency is not required for full SCA functionality and impacts user usage

**Comment by vikman90** [comment]
@rauldpm As I understand it, I don't think it should be a warning, it's not a SCA core malfunction.

The `requirements` part represents the set of conditions to proceed to analyze a policy. For example, we scan the configuration of a program if it is installed, since running the `checks` without it being installed would produce false positives.

A different case would be that we hope that _bastille_ is installed on HP-UX. So I would not do it as a requirement but as a check. In this way, a failure would be reported.
