### ISSUE TITLE
The alarm log data is too large, how to output it to another disk

### ISSUE THREAD

**Issue by PhuketIsland** [wazuh/wazuh#17302]
![image](https://github.com/wazuh/wazuh/assets/28825226/4d0dc68d-fe1f-4b61-8b8c-44657cdb2701)
Can I change the alarm logs in /var/ossec/logs/alerts/  this path to a different directory?

**Comment by PhuketIsland** [comment]
![image](https://github.com/wazuh/wazuh/assets/28825226/1ceb739d-9ce5-4a0a-9f84-eea4932a2363)
At present, the file is almost 20GB long.Can this file be deleted?

**Comment by matias-braida** [comment]
Hello,

For the wazuh alert files ("/var/ossec/logs/alerts/alerts.json" and file "/var/ossec/logs/alerts/alerts.log") the path is not possible to change.

But if you are trying to change the directory because of storage size issues, maybe you can try a different approach:

    Try to mount a different partition on this directory path.
    Try using a symbolic link for this path.

Let me know if this helps.

Regards

**Comment by PhuketIsland** [comment]
thanks
