### ISSUE TITLE
Splunk Forwarder error parsing archives.json

### ISSUE THREAD

**Issue by agentsofshield** [wazuh/wazuh#1749]
Hello, I'm using a splunk forwarder to gather logs from archives.json.
I used to have 10 agents and everything was fine, the logs from the computers were saved in archives.json and then the splunk forwarder moved everything to splunk.
Recently I deployed the agent to about 600 computers and splunk stopped forwarding the logs, after a quick look at the splunk log I saw an Error saying: 

> ERROR JsonLineBreaker - JSON .... had parsing error:Unexpected character while parsing backslash escape: 'x' - data_source="/var/ossec/logs/archives/archives.json"

Any idea why that happens?
Thanks in advance.

**Comment by TJOSERAFAEL** [comment]
Hi @agentsofshield ,

there must be some unscaped character inside the **archives.json** file. For example take this wrong json:

`{
	"name": "\"
}`

Its a malformed **json** because we are escaping the **"** character but not closing the string. I don't know the size of your **archives.json** log but you can try to validate it with some json validators that are available online.

Best regards.

**Comment by agentsofshield** [comment]
How can I fix this? I didn't write the logs, if something arrives like that to the server I can't change it.

**Comment by Zenidd** [comment]
Hello @agentsofshield,

first of all, sorry for the late reply.

If you still have the problem of log formatting, please copy here some logs from your archives.json or archives.log so that we can see what the situation is.
<br></br>
Kind regards,

Juan Pablo Sáez

**Comment by Zenidd** [comment]
Hi @agentsofshield,

I'm closing this ticket due to inactivity, please, feel free to reopen this one or a new issue in case you need it.

Regards,

Juan Pablo Sáez
