### ISSUE TITLE
[Windows SCA Policy]  powershell query returns wrong value

### ISSUE THREAD

**Issue by StefanSa** [wazuh/wazuh#17598]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.4 | Wazuh component | Agent | Packages | OS version Windows |

Hi there,
this query returns a "failed" although it should be "passed".

```
ID 26004 Ensure 'Password must meet complexity requirements' is set to 'Enabled'.
c:powershell Get-ADDefaultDomainPasswordPolicy -Current LoggedOnUser -> r:ComplexityEnabled\s+: True
```
![image](https://github.com/wazuh/wazuh/assets/6105075/8505136f-c115-444d-b81a-bb0da41bcbcb)

The same query in cmd box:
```
powershell Get-ADDefaultDomainPasswordPolicy -Current LoggedOnUser


ComplexityEnabled           : True
DistinguishedName           : DC=group,DC=local
LockoutDuration             : 00:15:00
LockoutObservationWindow    : 00:15:00
LockoutThreshold            : 10
MaxPasswordAge              : 00:00:00
MinPasswordAge              : 1.00:00:00
MinPasswordLength           : 8
objectClass                 : {domainDNS}
objectGuid                  : eef83fd4-bb15-467b-bf90-ca3859b07021
PasswordHistoryCount        : 12
ReversibleEncryptionEnabled : False
```

**Comment by StefanSa** [comment]
any news here?

**Comment by ooniagbi** [comment]
### Plan

- Confirm whether the check is still the same and if the bug is present/valid.

**Comment by IsExec** [comment]
## Update - 06/02/2024

### The status of the check in the different windows version is as shown below:

- Windows 10 (CIS v2.0.0) - Not Implemented
- Windows 11 (v2.0.0)  - Not Implemented
- Windows Server 2016 (CIS v2.0.0) - Not Implemented
- Windows server 2019 (CIS v1.1.0) - Implemented -> The rule is the same (powershell Get-ADDefaultDomainPasswordPolicy -Current LoggedOnUser)
- Windows server 2022 (CIS v2.0.0) - Implemented -> The rule is the same (powershell Get-ADDefaultDomainPasswordPolicy -Current LoggedOnUser)


The check from the CIS document is meant to be for both standalone and AD environment by navigating to the GP path `Computer Configuration\Policies\Windows Settings\Security Settings\Account Policies\Password Policy\Password must meet complexity requirements` (GUI).

However, this rule `powershell Get-ADDefaultDomainPasswordPolicy -Current LoggedOnUser` will only work in AD environment hence not applicable to standalone servers. 
This check does not have a **known registry key** and a **straight forward command in cmd** 

**Is the bug valid? No, because it passed in an AD environment as shown below:**

![image](https://github.com/wazuh/wazuh/assets/121132106/d6f99aaf-52ba-460b-b0cb-67914d202a43)

So if it passed in cmd as shown by the user (beacuse it is an AD environment, it should pass in SCA as well).

### Recommendation: This check should remain 'not implemented' across all windows version until there is a better way of getting the check to work on both standalone and AD environment.

**Comment by IsExec** [comment]
This check will be 'Not Implemented' across the windows SCA to ensure high quality of SCAs and avoid confusion due to dependencies.

2022 - https://github.com/wazuh/wazuh/issues/17339
2019 - https://github.com/wazuh/wazuh/issues/16724
