### ISSUE TITLE
sudo and dirmngr missing in Debian installation manual

### ISSUE THREAD

**Issue by HermanusF** [wazuh/wazuh#1763]
To succesfully install Wazuh on Debian you need sudo and dirmngr. Those are not always installed in new servers, so you might want to add them to the installation manual. (apt install sudo dirmngr -y)

**Comment by juan70** [comment]
Hello, @HermanusF,


Actually, `sudo` is not required to install Wazuh, because you can do it as user `root`, although doing things as `root` may be considered bad practice. Installing and using `sudo` is up to you and/or the sysadmins, but not required.

On the other hand, `dirmngr` is not needed either if you follow the install instructions.
For example, on a Debian 9.0 box, this kind of instruction works:
```
# curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
OK
```
And the `wazuh-agent` package, for example, installs fine.


But this other kind of instruction gives, indeed, a `dirmngr`-related error:
```
# apt-key adv --keyserver keyring.debian.org --recv-keys 0x1827364554637281
Executing: /tmp/apt-key-gpghome.4JtSTfJf2m/gpg.1.sh --keyserver keyring.debian.org --recv-keys 0x1827364554637281
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.4JtSTfJf2m/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
```


Kind regards.

**Comment by cristgl** [comment]
Hello @HermanusF,

Thanks for your suggestion, I am going to proceed to close this issue since the instructions described at the documentation do not need `sudo` or `dirmngr` packages to be installed as Juan said. Please don't hesitate to reopen it or create a new one if you have any doubts.

Kind regards,
Cristina
