### ISSUE TITLE
Increasing use of disk in footprint tests

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#17927]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-40600 | - | Manager/Agent | Packages | - |

## Description

During the analysis of the [footprint tests for 4.6.0 Pre-Alpha 1](https://github.com/wazuh/wazuh/issues/17717), it could be seen that in most cases the disk usage has increased compared to the [last 3-day footprint test](https://github.com/wazuh/wazuh/issues/16947), which was 4.4.2-rc1.

For example, in pre-alpha, Solaris has a lower number of messages and events generated but the disk and related plots are higher. 

The curve is the same, but we should analyze if the growth is expected and what would be the threshold at which disk usage is acceptable.

> Detailed info within each footprint metric review, in the `Analysis report: Graphs` comment

**Comment by JorgeMarinoDev** [comment]
### Increasing use of disk in footprint tests #17927 

#### Initial Analysis

* Disk usage (DU) comparisson was made between 4.6.0 Pre Alpha 1 and 4.4.2 RC1 stress tests.
* DU Increase is reported in agents.  https://github.com/wazuh/wazuh/issues/17848#issuecomment-1632701682

The main known data volume increase from 4.4 to 4.5 (therefore vs 4.6) was the increase of vulnerabilities checked from NVD sources.
First intention was to check a Reductio ad absurdum to relate this increase to this. But after

**Checking ossec.conf** in both agent versions

Both managers have vulnerability-detector enabled with nvd source.

Therefore the cause is not only limited to this known possible cause.


**Next steps followed**

Identify which daemons report an increase.

**CSV Analysis**

![image](https://github.com/wazuh/wazuh/assets/117848458/01770960-9a28-4586-8af3-5292ef3e3edf)

In general terms, Disk Usage % shows no direct correlation between Disk Read and Disk Written changes among daemons. 
A clear example is wazuh-execd. Even though There are no changes in RW ops and RW bytes, the DU % shows a 18.10% of increase. 

#### Further steps ####

Perform local stress tests and obtain more than 1 sample to discard metrics scatters and relate metrics to processed events.

#### Key aspects on the next steps ####

* Execute periodic analysis on the running agents of different versions.
  Key aspect, perform data gathering under same circumstances as the automated quality stress test. @Rebits .
* Circumscribe  possible source code changes in stages. From 4.4.2 to 4.5. Then From 4.5 to 4.6. 
A guideline to explore relevant changes is to check 4.6 issues https://github.com/orgs/wazuh/projects/36/views/1?filterQuery=release%3A%224.6.0%22

#### Actual tasks in progress ####
* Perform local stress tests and obtain more than 1 sample to discard metrics scatters and relate metrics to processed events.

**Comment by nmkoremblum** [comment]
Possibly related to https://github.com/wazuh/wazuh/issues/17928#issuecomment-1671252008

**Comment by vikman90** [comment]
Let's put this issue on-hold until we tag 4.6.0-alpha1.

**Comment by jnasselle** [comment]
Since we'll wait until v4.6.0-alpha1, we agreed with @havidarou to move this issue to v4.6.0-alpha2

**Comment by havidarou** [comment]
This will be fixed in Alpha 1

**Comment by vikman90** [comment]
This issue is **blocked** until 4.6.0-alpha1 tests are ready (https://github.com/wazuh/wazuh/issues/17712).

**Comment by nbertoldo** [comment]
@wazuh/qa, please could you confirm if this problem persists after the footprint test for 4.6.0-alpha1.
Do you have any comments about the results? Since no new issues have been created.

**Comment by verdx** [comment]
@nbertoldo 

No issue has been created, but this issue has been mentioned in 9 Footprint tests, where similar behaviour has been found.

The list of tests on which this has been seen is:
- https://github.com/wazuh/wazuh/issues/18930
- https://github.com/wazuh/wazuh/issues/18912
- https://github.com/wazuh/wazuh/issues/18926
- https://github.com/wazuh/wazuh/issues/18911
- https://github.com/wazuh/wazuh/issues/18923
- https://github.com/wazuh/wazuh/issues/18920
- https://github.com/wazuh/wazuh/issues/18910
- https://github.com/wazuh/wazuh/issues/18917
- https://github.com/wazuh/wazuh/issues/18921

**Comment by JorgeMarinoDev** [comment]
@verdx Wow, really good job with your latest comment! It's now much more clear what to compare. Much appreciated!

As a consequence, we've noticed that this issue could be considered as a root issue even though now different modules or processes are showing these differences. Therefore after meeting with the team, we came up with a plan of action.

1. Create one comment per test on which diff were seen.
2. Extract and attach the corresponding plot graphics.
3. Isolate the module or process under review.
4. Ask the teams and or research logs and source code looking for any major change justifying the difference (maybe more data in VD DBs, added caches, etc).

Without analyzing each of the tests, we can't correlate them or determine if something is clearly wrong or not.

Thank you!
6.

**Comment by JorgeMarinoDev** [comment]
- https://github.com/wazuh/wazuh/issues/18930

**Comment by JorgeMarinoDev** [comment]
- https://github.com/wazuh/wazuh/issues/18912

**Comment by JorgeMarinoDev** [comment]
- https://github.com/wazuh/wazuh/issues/18926

**Comment by JorgeMarinoDev** [comment]
- https://github.com/wazuh/wazuh/issues/18911

**Comment by JorgeMarinoDev** [comment]
- https://github.com/wazuh/wazuh/issues/18923

**Comment by JorgeMarinoDev** [comment]
- https://github.com/wazuh/wazuh/issues/18920

**Comment by JorgeMarinoDev** [comment]
- https://github.com/wazuh/wazuh/issues/18910

**Comment by JorgeMarinoDev** [comment]
- https://github.com/wazuh/wazuh/issues/18917

**Comment by JorgeMarinoDev** [comment]
- https://github.com/wazuh/wazuh/issues/18921

**Comment by vikman90** [comment]
If we think this might be due to the new FIM implementation, please refer to https://github.com/wazuh/wazuh/issues/10223.

**Comment by cborla** [comment]
We will continue working on this issue to find the root problem, since the behavior is the same in 4.5.2 but repeats less frequently we can advance to 4.6.0-beta1.

**Comment by cborla** [comment]
Related issue [19074](https://github.com/wazuh/wazuh/issues/19074)

**Comment by mauromalara** [comment]
Hi team, @nbertoldo @JorgeMarinoDev 

We did not observe this behavior on the **Manager** while analyzing https://github.com/wazuh/wazuh/issues/19535 (`4.6.0-rc1` | **Case**: ALL-EXCEPT-SYSCHECK _2.5d_)

cc @pro-akim

**Comment by cborla** [comment]
The changes in db-sync did not modify the test behavior, so we requested to [re-launch](https://github.com/wazuh/internal-devel-requests/issues/364) a group of tests by changing the test configuration.

**Comment by JorgeMarinoDev** [comment]
After analysis of 

We have some doubts of this result also.
There is a metric for Disk Usage, that is a percentage and it can't be more than 100.
![image](https://github.com/wazuh/wazuh/assets/117848458/e5c7460f-56f5-4e19-b477-c670c5ceba7e)

This is obtained in monitor.py

https://github.com/wazuh/wazuh-jenkins/blob/7c59dc04b5f787d51f8987356cdcfa3a6df5ba25/quality/python-packages/jenkins_utils/jenkins_utils/monitor.py#L560C74-L560C84

See this issue for more details
https://github.com/wazuh/wazuh-jenkins/issues/5656
 

We can't rely on these new metrics either. I'd suggest waiting for validation of new test launch. https://github.com/wazuh/wazuh/issues/19579#issuecomment-1760187738

**Comment by cborla** [comment]
Waiting for https://github.com/wazuh/wazuh/issues/19074.

**Comment by cborla** [comment]
## Description

Since the present issue was opened on the results obtained in the footprint test for 4.6.0 Alpha 1, I consider it necessary to compare the results obtained again but with 4.6.0 RC 2. 
The descriptive table is shown below, using the results obtained in version 4.4.2 as a basis.

### Comparison

|  Module | TEST | Measure | 4.4.2 | 4.6.0-rc2 |
|--|--|--|--|--|
| Manager | ALL | Disk | ![1](https://camo.githubusercontent.com/639bb17f5c9364b2b0e561787660b0c10266c9bb3a016ed5bab3d63fd062be0e/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e322f42333933332d343332306d2f42333933335f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42333933335f6d616e616765722d7072652d72656c656173655f4469736b2e706e67) | ![2](https://camo.githubusercontent.com/5ec5749f653d692758b3cb3ad3b98b6b88ba92846e02bb53d81184aedb1b0174/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531312d333630306d2f42343531315f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343531315f6d616e616765722d7072652d72656c656173655f4469736b2e706e67) |
| Manager | ALL | Disk_Read | ![1](https://camo.githubusercontent.com/7fff1dc1514ad6f2e599f15fdc8b6012e55084bbcc932369d6eb95d24e5d4f9e/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e322f42333933332d343332306d2f42333933335f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42333933335f6d616e616765722d7072652d72656c656173655f4469736b5f526561642e706e67) | ![2](https://camo.githubusercontent.com/79bc0b400b202ef941d9509fe5498f9481c29848e98ac4ad3f56ffdae5edee98/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531312d333630306d2f42343531315f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343531315f6d616e616765722d7072652d72656c656173655f4469736b5f526561642e706e67) |
| Manager | ALL | Disk_Written | ![1](https://camo.githubusercontent.com/9173ee40caa011a58a3b48f8e66f78487f90d56e4a7c348a90192ae94849c1d6/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e322f42333933332d343332306d2f42333933335f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42333933335f6d616e616765722d7072652d72656c656173655f4469736b5f5772697474656e2e706e67) | ![2](https://camo.githubusercontent.com/3893fb833e512072c72fe5162a3aac1b7b86268d490f9670daac1e3f764c020d/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531312d333630306d2f42343531315f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343531315f6d616e616765722d7072652d72656c656173655f4469736b5f5772697474656e2e706e67) |
||||||
| Centos Agent | ALL | Disk | ![1](https://camo.githubusercontent.com/bcc102d701466f8f4aae2c09e0cf805c067a76bfbea667b716aaa396404272ff/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e322f42333933332d343332306d2f42333933335f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42333933335f63656e746f732d7072652d72656c656173655f4469736b2e706e67) | ![2](https://camo.githubusercontent.com/69939e32ee8836d453793c8f15c7443456153418acaa9ab2a6ce7dd6aeffb8af/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531312d333630306d2f42343531315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343531315f63656e746f732d7072652d72656c656173655f4469736b2e706e67) |
| Centos Agent | ALL | Disk_Read | ![1](https://camo.githubusercontent.com/ed18fe7c62aa93c1d02f49ac3d2933480efdfd29777356de68e5dfcc3afa21a4/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e322f42333933332d343332306d2f42333933335f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42333933335f63656e746f732d7072652d72656c656173655f4469736b5f526561642e706e67) | ![2](https://camo.githubusercontent.com/3f4c4c3f6a8801e416cffaa642a8c0c55afcfffab0ecbcf5ed56094873ca081d/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531312d333630306d2f42343531315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343531315f63656e746f732d7072652d72656c656173655f4469736b5f526561642e706e67) |
| Centos Agent | ALL | Disk_Written | ![1](https://camo.githubusercontent.com/e9cf2f4a917ceab8fb0f375ee369000376b986324521237326c187408438d684/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e322f42333933332d343332306d2f42333933335f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42333933335f63656e746f732d7072652d72656c656173655f4469736b5f5772697474656e2e706e67) | ![2](https://camo.githubusercontent.com/63e3197177f2a59a8bdaf44a77fc0b1a486f9bc7c15293b372439f962c046e50/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531312d333630306d2f42343531315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343531315f63656e746f732d7072652d72656c656173655f4469736b5f5772697474656e2e706e67) |
||||||
| Ubuntu Agent | ALL | Disk | ![1](https://camo.githubusercontent.com/8514e67f1ab6fd082f6fe1a989af8a62bf6028e4e4765ebe42d40084591a8d34/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e322f42333933332d343332306d2f42333933335f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42333933335f7562756e74752d7072652d72656c656173655f4469736b2e706e67) | ![2](https://camo.githubusercontent.com/4af648f46ab0c1a4cd7455092099105cd8352d20f360fac3cf249af445763b16/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531312d333630306d2f42343531315f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343531315f7562756e74752d7072652d72656c656173655f4469736b2e706e67) |
| Ubuntu Agent | ALL | Disk_Read | ![1](https://camo.githubusercontent.com/eb53cd41085e6ed5b68955d78e21052e2a8865bd8bf34e76db759c595615f332/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e322f42333933332d343332306d2f42333933335f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42333933335f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) | ![2](https://camo.githubusercontent.com/9a826bca659d1651984a9942c4abc6a8c4e66f80f72c23ea22c59aee2740f615/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531312d333630306d2f42343531315f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343531315f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) |
| Ubuntu Agent | ALL | Disk_Written | ![1](https://camo.githubusercontent.com/b1c66f23f548daac41c8330ae7359b0332a585933531c41cbfd64ddadb0106b3/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e322f42333933332d343332306d2f42333933335f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42333933335f7562756e74752d7072652d72656c656173655f4469736b5f5772697474656e2e706e67) | ![2](https://camo.githubusercontent.com/f48eb86a5a30f74924b263cc64ba2f91ebb8799296cac08bd6b996d1f0d20bb5/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531312d333630306d2f42343531315f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343531315f7562756e74752d7072652d72656c656173655f4469736b5f5772697474656e2e706e67) |
||||||
| Windows Agent | ALL | Disk | ![1](https://camo.githubusercontent.com/260a1c3a80e323b375d2eb615ce735d91a1a761aac22b6c982c105296a5912a1/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e322f42333933332d343332306d2f42333933335f6167656e745f77696e646f77732f706c6f74732f6d6f6e69746f722d77696e6167656e742d546573745f7374726573735f42333933335f77696e646f77732d7072652d72656c656173655f4469736b2e706e67) |![2](https://camo.githubusercontent.com/bc742095544fc49595b9a3c2395def4539f2adbb12a79eb347bb6a3ad428528a/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531312d333630306d2f42343531315f6167656e745f77696e646f77732f706c6f74732f6d6f6e69746f722d77696e6167656e742d546573745f7374726573735f42343531315f77696e646f77732d7072652d72656c656173655f4469736b2e706e67)|
| Windows Agent | ALL | Disk_Read | ![1](https://camo.githubusercontent.com/e1916e6da0e932bff8f7c51ead7d0354099322ab6a16f14102f0d3278307c3f3/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e322f42333933332d343332306d2f42333933335f6167656e745f77696e646f77732f706c6f74732f6d6f6e69746f722d77696e6167656e742d546573745f7374726573735f42333933335f77696e646f77732d7072652d72656c656173655f4469736b5f526561642e706e67) | ![2](https://camo.githubusercontent.com/6767cd9d478dc7973bc029dbcacfa9efd140f83183deb25b57f527d7dedf7a2d/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531312d333630306d2f42343531315f6167656e745f77696e646f77732f706c6f74732f6d6f6e69746f722d77696e6167656e742d546573745f7374726573735f42343531315f77696e646f77732d7072652d72656c656173655f4469736b5f526561642e706e67) |
| Windows Agent | ALL | Disk_Written | ![1](https://camo.githubusercontent.com/b7a9998a136e78dc6161d25e5ef70150aa2be09fb137b6f98b8cad1612440f2f/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e322f42333933332d343332306d2f42333933335f6167656e745f77696e646f77732f706c6f74732f6d6f6e69746f722d77696e6167656e742d546573745f7374726573735f42333933335f77696e646f77732d7072652d72656c656173655f4469736b5f5772697474656e2e706e67) | ![2](https://camo.githubusercontent.com/c17dba7e3daaa5d9b3af86eb480b05887d3c4eaa3cbc044db19c413165184723/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531312d333630306d2f42343531315f6167656e745f77696e646f77732f706c6f74732f6d6f6e69746f722d77696e6167656e742d546573745f7374726573735f42343531315f77696e646f77732d7072652d72656c656173655f4469736b5f5772697474656e2e706e67) |
||||||
