### ISSUE TITLE
Client keys file change owner after upgrading using WPK for macOS agents

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#17963]
| Wazuh Version | OS
| ------------- | ------------- |
| `4.6.0`       | `macOS High Sierra`

### Description

During the investigation of issue https://github.com/wazuh/wazuh/issues/17720, it was observed that macOS endpoints change the owner of the `/Library/Ossec/etc/client.keys` file from "wazuh:wazuh" to "root:wazuh" when upgrading from version 4.4.5 to 4.6.0.

Further analysis has confirmed that this ownership alteration is specific to macOS and does not occur on other systems. For instance, Ubuntu agents maintain the expected ownership of the file.

### Evidences

- [checkfiles_macos1013.zip](https://github.com/wazuh/wazuh/files/12094154/checkfiles_macos1013.zip)

**Comment by TomasTurina** [comment]
Hi @Rebits,

Together with @Nicogp we have tested in a macOS Sierra an upgrade from Wazuh v4.3.11 to v4.4.3 and we saw the same behavior.

Installing Wazuh v4.3.11:
```
/Library/Ossec/bin/wazuh-control info 
WAZUH_VERSION="v4.3.11"
WAZUH_REVISION="40324"
WAZUH_TYPE="agent"
```

File permissions and ownership:
```
ls -l /Library/Ossec/etc/client.keys
-rw-r-----  1 wazuh  wazuh  89 Jul 25 09:42 /Library/Ossec/etc/client.keys
```

Upgrade to v4.4.3:
```
/Library/Ossec/bin/wazuh-control info 
WAZUH_VERSION="v4.4.3"
WAZUH_REVISION="40409"
WAZUH_TYPE="agent"
```

New file permissions and ownership:
```
ls -l /Library/Ossec/etc/client.keys
-rw-r-----  1 root  wazuh  89 Jul 25 09:55 /Library/Ossec/etc/client.keys
```

Since this behavior wasn't introduced in v4.6.0, I suggest to remove this issue from release v4.6.0 and reduce its priority.

cc @davidjiglesias @vikman90
