### ISSUE TITLE
Agent info file changed permissions after WPK upgrade for macOS agent

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#17972]
| Wazuh Version | OS
| ------------- | ------------- |
| `4.6.0`       | `macOS High Sierra`

### Description

During the investigation of issue https://github.com/wazuh/wazuh/issues/17720, it was observed that macOS endpoints change the permissions of the `/Library/Ossec/queue/sockets/.agent_info` file from "-rw-r--r-- " to "-rwxr-x---" when upgrading from version 4.4.5 to 4.6.0:
```
Expected
-rw-r--r--   1 wazuh  wazuh   46 Jul 19 03:22 .agent_info
Found
-rwxr-x---   1 wazuh  wazuh   46 Jul 19 03:28 .agent_info
```

### Evidences

- [checkfiles_macos1013.zip](https://github.com/wazuh/wazuh/files/12094154/checkfiles_macos1013.zip)

**Comment by TomasTurina** [comment]
Hi @Rebits,

Together with @Nicogp we have tested in a macOS Sierra an upgrade from Wazuh v4.3.11 to v4.4.3 and we saw the same behavior.

Installing Wazuh v4.3.11:
```
/Library/Ossec/bin/wazuh-control info 
WAZUH_VERSION="v4.3.11"
WAZUH_REVISION="40324"
WAZUH_TYPE="agent"
```

File permissions and ownership:
```
ls -l /Library/Ossec/queue/sockets/.agent_info
-rw-r--r--  1 wazuh  wazuh  51 Jul 25 09:43 /Library/Ossec/queue/sockets/.agent_info
```

Upgrade to v4.4.3:
```
/Library/Ossec/bin/wazuh-control info 
WAZUH_VERSION="v4.4.3"
WAZUH_REVISION="40409"
WAZUH_TYPE="agent"
```

New file permissions and ownership:
```
ls -l /Library/Ossec/queue/sockets/.agent_info
-rwxr-x---  1 wazuh  wazuh  51 Jul 25 09:55 /Library/Ossec/queue/sockets/.agent_info
```

Since this behavior wasn't introduced in v4.6.0, I suggest to remove this issue from release v4.6.0 and reduce its priority.

cc @davidjiglesias @vikman90

**Comment by vikman90** [comment]
Thanks @TomasTurina, let's set the objective to _Low impact bugs_.
