### ISSUE TITLE
Vulnerability detector events decoded for Footprint tests drastically decrease for 4.5.0

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#18171]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.0 | Modulesd | Manager | Packages | centOS 7 |

### Description
During [footprint testing](https://github.com/wazuh/wazuh/issues/18148) it has been detected a big decrease of the amount of VD events decoded in the environment.
Comparing with the 4.4.4 results, the number of decoded events have decrease from 1200~ to 220~.

This could be directly related with https://github.com/wazuh/wazuh/issues/18168

### 4.5.0

![450](https://github.com/wazuh/wazuh/assets/11089305/90a1f0b1-19b9-44ee-9e8a-618550fa1184)

### Evidences
**CSV**: [Test_stress_B4216_manager_analysisd_events.csv](https://github.com/wazuh/wazuh/files/12217111/Test_stress_B4216_manager_analysisd_events.csv)
**Build**: https://ci.wazuh.info/job/Test_stress/4216/

### 4.4.4

![444](https://github.com/wazuh/wazuh/assets/11089305/a473fda7-0d1c-4665-a508-1d3d936f39ae)

### Evidences
**CSV**: [Test_stress_B4042_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4042-360m/B4042_manager_centos/data/Test_stress_B4042_manager_analysisd_events.csv)
**Build**: https://ci.wazuh.info/job/Test_stress/4042/

**Comment by vikman90** [comment]
I'm pretty sure this issue is related to https://github.com/wazuh/wazuh/issues/18168 (fixed in RC1).

**Comment by JorgeMarinoDev** [comment]
Hello @Rebits . Is it possible to get the exact procedure QA is using to obtain the sample data?
I mean, where's it collected from. Interval. Processing. Units. Any thresholds used. 
Even get a basic grasp of the stress environment the target's under.
Thank you

**Comment by JorgeMarinoDev** [comment]
**Trace**
* Issue related to https://github.com/wazuh/wazuh/issues/18168 (fixed in RC1).
* Launch footprint tests for Vulnerability Detector was requested : [here](https://github.com/wazuh/internal-devel-requests/issues/113)
* Results here : https://ci.wazuh.info/job/Test_stress/4224/console

**Analysis of Events**

|                                      | 4.4.4 | 4.5.0 Before Fix (#18168) | 4.5.0 After Fix (#18168) |
| ------------------------------------ | ----- | ---------------- | --------------- |
| *Events from Vulnerability Detector* | 1056 | 194              | 2494            |

**Related Files**
analysisd_events before Fix in 4.5.0 : [here](https://github.com/wazuh/wazuh/files/12217111/Test_stress_B4216_manager_analysisd_events.csv)
analysisd_events after Fix in 4.5.0 : [Test_stress_B4224_manager_analysisd_events.zip](https://github.com/wazuh/wazuh/files/12244273/Test_stress_B4224_manager_analysisd_events.zip)

**Final Plot**
![Test_stress_B4224_manager_analysisd_events_Decoded_events](https://github.com/wazuh/wazuh/assets/117848458/97869ba2-abd8-49c6-9259-1c04f66d0ce3)

**Comment by vikman90** [comment]
## Conclusion

After the fix related to #18168, we see that the count of events is back to normal, even greater due to the better CVE support (explained at #18165).

We can close this issue.
