### ISSUE TITLE
Vulnerability Module not showing vulnerabilities for some apps

### ISSUE THREAD

**Issue by ksmosna** [wazuh/wazuh#18348]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.5| Wazuh component | Manager| Packages| Ubuntu OS 22 |

Hello,
I have a question about the vulnerability module. I have configured the config file as recommended. Agents read vulnerabilities and needed windows updates to install. I also get information about vulnerabilities in Thunderbird, firefox, mysql and ms office. However, I do not see information about the need to update e.g. JDK, mongodb, acrobat reader, libre office and several other applications, even though I see these applications on the list in inventory data.

**Comment by MiguelazoDS** [comment]
Hi @ksmosna, 

If I'm not misunderstanding the issue, you are referring to Windows agent, not Linux, right? 
What we can do is set the debug logs for modulesd, edit your `/var/ossec/etc/internal_options.conf` file changing 0 by 2 in the line 
`wazuh_modulesd.debug=0`, restart and check if the manager is considering those packages, they may have no vulnerabilities so, there's nothing to show. 

Please share the information for those packages, because another issue may be related to the cpe_helper 

https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/cpe-helper.html

**Comment by Dwordcito** [comment]
Thank you for being part of the community, we closed the issue due to inactivity, in case you return please reopen the issue! We are very interested in your question!
