### ISSUE TITLE
Release 4.5.1 - Release Candidate RC 1 - System tests

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh#18384]
The following issue aims to run all `system tests` for the current release candidate, report the results, and open new issues for any encountered errors.

## System tests information
|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release candidate issue**     |https://github.com/wazuh/wazuh/issues/18366|
| **Version**                          |4.5.1|
| **Release candidate #**              |RC 1|
| **Tag**                              |https://github.com/wazuh/wazuh/tree/v4.5.1-rc1/|
| **Previous system tests issue**      |https://github.com/wazuh/wazuh/issues/18288|

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions :red_circle: 

All tests have been executed and the results can be found  in comment https://github.com/wazuh/wazuh/issues/18384#issuecomment-1676899407

All tests passed, with the exception of the following:

| **Test**    | **Failure type**    | **Notes**      |
|-------------|---------------------|----------------|
| test_cluster/test_integrity_sync/test_integrity_sync.py             | Known Issue            | https://github.com/wazuh/wazuh-qa/issues/4407                |
|test_agent_auth/test_agent_auth.py | Known issue | https://github.com/wazuh/wazuh-qa/issues/4410
| test_enrollment/test_enrollment.py | Known issue | https://github.com/wazuh/wazuh/issues/16664
|  test_cluster/test_agent_groups/test_agent_groups.py |New Issue - Flaky test | https://github.com/wazuh/wazuh-qa/issues/4426

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @fcaffieri 
- [x] @damarisg

**Comment by pro-akim** [comment]
Working with @verdx on this issue

@verdx 

- enrollment_cluster
- basic_environment
- agentless_cluster
- manager_agent

@pro-akim 

- one_manager_agent
- basic_cluster
- four_manager_disconnected_node
- big_cluster_40_agents

**Comment by pro-akim** [comment]
## Test results
    
<details> 
<summary><b>Reports</b></summary>   
<br> 

- [agentless_cluster_env.zip](https://github.com/wazuh/wazuh/files/12291806/report.zip)
- [basic_cluster_env.zip](https://github.com/wazuh/wazuh/files/12279687/report.zip)
- [basic_environment_env.zip](https://github.com/wazuh/wazuh/files/12291141/report.zip)
- [basic_four_manager_disconnected_node_env.zip](https://github.com/wazuh/wazuh/files/12280293/report.zip)
- [big_cluster_40_agents_env.zip](https://github.com/wazuh/wazuh/files/12290402/report.zip)
- [enrollment_cluster.zip](https://github.com/wazuh/wazuh/files/12289462/report_enr_cluster.zip)
- [manager_agent_env.zip](https://github.com/wazuh/wazuh/files/12291712/manager_agent.zip)
- [one_manager_agent_env.zip](https://github.com/wazuh/wazuh/files/12274302/report.zip)

 
## Notes



- basic_cluster was tested 3 times. This is because of environmental contamination between tests.

    part 1
    test_cluster/test_agent_key_polling/test_agent_key_polling.py
    test_multigroups/test_multigroups.py

    part 2
    test_cluster/test_agent_files_deletion/test_agent_files_deletion.py
    test_cluster/test_agent_groups/test_agent_groups_forced_change.py

    part 3
    test_cluster/test_agent_info_sync/agent_info_sync


- Unstable Test: `test_cluster/test_agent_enrollment/test_agent_enrollment`. It seems this test is unstable failing erratically probably due to a timeout. [Pass report for agent_enrollment.zip](https://github.com/wazuh/wazuh/files/12291586/agent_enrollment.zip)

</details>


***

| | | | | | | |
|--|--|--|--|--|--|--|
| | **Test name** |  **Status** | **Pass** | **XFail/Skip** | **Fail** | **Issues Ref.** |
| | *One Manager Agent* | 
|1| test_fim/test_files/test_files_cud.py | :green_circle:  | 9 | 0 | 0 |
|2| test_fim/test_synchronization/test_synchronization.py | :green_circle: | 6| 0 | 0 |  
| | *Four Manager Disconnected Node* |
|3| test_cluster/test_agent_groups/test_agent_groups_new_cluster_node.py | :green_circle: | 2 | 0 | 0 |  
| | *Agentless Cluster* |
|4| test_cluster/test_integrity_sync/test_integrity_sync.py | :green_circle:  | 4 | 0 | 0 |  
|5| test_cluster/test_ruleset_sync_status/test_ruleset_sync_status.py |  :green_circle: | 1 | 0 | 0 | 
|6| test_jwt_invalidation/test_change_rbac_mode.py |  :green_circle: | 4 | 0 | 0 |  
|7| test_jwt_invalidation/test_change_security_resources.py | :green_circle: | 4 | 0 | 0 |  
|8| test_jwt_invalidation/test_disconnected_nodes.py |  :green_circle: | 1 | 0 | 0 |   
|9| test_jwt_invalidation/test_revoke_endpoint.py | :green_circle: | 6  | 0 | 0 |   
|10| test_jwt_invalidation/test_update_password.py |  :green_circle: | 4 | 0 | 0 |  
| | *Enrollment Cluster* |
|10| test_cluster/test_agent_enrollment/test_agent_enrollment.py | :red_circle: |  0 | 1 | 0 |   https://github.com/wazuh/wazuh-qa/issues/4407|
|11| test_cluster/test_agent_groups/test_agent_default_group_added.py | :green_circle:  | 3  | 0 | 0 |  
|12| test_cluster/test_agent_groups/test_assign_agent_group_with_enrollment.py  |  :green_circle: | 1  | 0 | 0 |  
|13| test_cluster/test_agent_groups/test_assign_agent_never_connected_to_group.py | :green_circle: |  2  | 0 | 0 |   
|14| test_cluster/test_agent_groups/test_assign_agent_to_a_group_api.py | :green_circle: | 4 | 0 | 0 |   
|15| test_cluster/test_agent_groups/test_assign_agent_to_a_group_by_tool.py |  :green_circle: | 2  | 0 | 0 
|16| test_cluster/test_agent_groups/test_assign_agent_to_a_group.py | :green_circle: | 4 | 0 | 0 |   
|17| test_cluster/test_agent_groups/test_assign_groups_guess.py |  :green_circle: | 12  | 0 | 0 |   
|18| test_cluster/test_agent_groups/test_agent_groups.py | :green_circle: | 1 | 0 | 0 |  
|19| test_cluster/test_agent_groups/test_remove_group.py | :green_circle: | 2  | 0 | 0 | 
| | *Manager Agent* |
|20| test_active_response_log_format/test_active_response_log_format.py | :green_circle: | 3  | 0 | 0 |   
|  | *Basic Cluster*   |
|21| test_cluster/test_agent_info_sync/test_agent_info_sync.py |  :green_circle:  | 2 | 0 | 0 |   
|22| test_cluster/test_agent_key_polling/test_agent_key_polling.py |   :green_circle: | 1 | 0 | 0 |  
|23| test_cluster/test_agent_files_deletion/test_agent_files_deletion.py |:green_circle: | 1 | 0 | 0 |  
|24| test_multigroups/test_multigroups.py | :green_circle: | 4 | 0 | 0 | 
|25| test_cluster/test_agent_groups/test_agent_groups_forced_change.py |   :green_circle: | 3 | 0 | 0 |  
| | *Big Cluster 40 Agents* |
|26| test_cluster/test_agent_groups/test_groups_sync_default.py | :green_circle: | 2 |0| 0 |   
|27| test_cluster/test_agent_groups/test_groups_sync_time.py | :green_circle: | 2 | 0 | 0 | 
| | *Basic Environment* |
|28| test_agent_auth/test_agent_auth.py | :green_circle: | 20  | 0 | 0 |
|29| test_enrollment/test_enrollment.py | :red_circle: | 0 | 0 | 20  | https://github.com/wazuh/wazuh/issues/16664|

**Comment by damarisg** [comment]
LGTM!
