### ISSUE TITLE
FIM events are not reported after following the ransomeware guide

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh#18429]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.1-rc1 | FIM | Manager/Agent | apt | Ubuntu 22.04|

Issue related: https://github.com/wazuh/wazuh/issues/18417

https://wazuh.com/blog/preventing-and-detecting-ransomware-with-wazuh/

The tests are carried out following the guide and everything works correctly, I only have a few observations to update the blog to our current version (Wazuh indexer and dashboard)

### Tests:

![Screenshot_20230814_145056](https://github.com/wazuh/wazuh/assets/64099752/edd4d50c-eb39-4c0c-8bfd-76c76f4e23c0)
![Screenshot_20230814_155951](https://github.com/wazuh/wazuh/assets/64099752/19d5fa55-10b4-45ca-9a88-e8e802547b8b)

I ran into some errors when trying to repeat the test.

- Delete the directories created by the script
- I ran the script again: `python3 wazuh-ransomware-poc.py prepare`
- The files were created successfully
- run the script: `python3 wazuh-ransomware-poc.py attack`
- After this I checked and all these changes were not reported in the events, although they are seen in the inventory

- Create additional files like: `/home/vagrant/test/new-file-to-test.txt`
- Changed their permissions, edit then delete and these events didn't show up on the dashboard in events

- Create a new directory to run a new test: `/home/vagrant/test2`
- Add the rule in the agent's `ossec.conf`
- Modify the script and execute the 2 stages of the script again, and all these events do not appear in the dashboard, although they do appear in the inventory

![Screenshot_20230814_160800](https://github.com/wazuh/wazuh/assets/64099752/0307956b-c499-4472-b510-2bb843d83c88)
![Screenshot_20230814_161043](https://github.com/wazuh/wazuh/assets/64099752/cebb6f13-6455-45c6-83b8-de65f6a520b2)
![Screenshot_20230814_161116](https://github.com/wazuh/wazuh/assets/64099752/8182c55d-8af5-4a24-982b-abd29b7de062)
![Screenshot_20230814_161148](https://github.com/wazuh/wazuh/assets/64099752/a6be6dc6-53f7-47f3-8921-b166bdd09ff0)

**Comment by vikman90** [comment]
@c-bordon I've not managed to reproduce this issue.

<details><summary><code>python3 wazuh-ransomware-poc.py prepare</code></summary>

** Alert 1692169831.240044: - ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Aug 16 09:10:31 (lunar) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/home/vagrant/test/Directory_07/File_19.txt' added
Mode: whodata

Attributes:
 - Size: 1024
 - Permissions: rw-r--r--
 - Date: Wed Aug 16 09:10:26 2023
 - Inode: 823255
 - User: root (0)
 - Group: root (0)
 - MD5: 0fb749f21e310628d44f4ad12f76d61b
 - SHA1: 5aa3994c0e9f845ca1a31b5e50aeaa536cd87664
 - SHA256: 735e07f57832d61dbfac2ffc4731beec2b2638f62c3ea7061811b801db23ed7f
 - (Audit) User name: root
 - (Audit) Audit name: root
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 4348
 - (Audit) Process name: /usr/bin/python3.11
 - (Audit) Process cwd: /home/vagrant
 - (Audit) Parent process name: /usr/bin/bash
 - (Audit) Parent process id: 4002
 - (Audit) Parent process cwd: /home/vagrant

</details>

<details><summary><code>python3 wazuh-ransomware-poc.py attack</code></summary>

** Alert 1692169900.335362: - ossec,syscheck,syscheck_entry_deleted,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Aug 16 09:11:40 (lunar) any->syscheck
Rule: 553 (level 7) -> 'File deleted.'
File '/home/vagrant/test/Directory_05/File_05.txt' deleted
Mode: whodata

Attributes:
 - Size: 1024
 - Permissions: rw-r--r--
 - Date: Wed Aug 16 09:10:26 2023
 - Inode: 823083
 - User: root (0)
 - Group: root (0)
 - MD5: e90107eda9b184e99d5a1d809dcdb4dc
 - SHA1: c053e6d76ee9ffde1afbfcb31fd4945d769b883a
 - SHA256: b102b0095069f7e7be9481303ed5a462089a4ccdcca5292084b28928403f7b33
 - (Audit) User name: root
 - (Audit) Audit name: root
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 4352
 - (Audit) Process name: /usr/bin/python3.11
 - (Audit) Process cwd: /home/vagrant
 - (Audit) Parent process name: /usr/bin/bash
 - (Audit) Parent process id: 4002
 - (Audit) Parent process cwd: /home/vagrant

** Alert 1692169900.336412: - ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Aug 16 09:11:40 (lunar) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/home/vagrant/test/Directory_05/File_00.txt.encrypted' added
Mode: whodata

Attributes:
 - Size: 1464
 - Permissions: rw-r--r--
 - Date: Wed Aug 16 09:11:39 2023
 - Inode: 823083
 - User: root (0)
 - Group: root (0)
 - MD5: c714cdad5ab0248be10e1f943a50b368
 - SHA1: 59be055a88698be23e6cc6855a636138df86f416
 - SHA256: dca9f01f2d46990bf66d4f53f2b6a16f9264ae141a17de5f588f9b972e69ec50
 - (Audit) User name: root
 - (Audit) Audit name: root
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 4352
 - (Audit) Process name: /usr/bin/python3.11
 - (Audit) Process cwd: /home/vagrant
 - (Audit) Parent process name: /usr/bin/bash
 - (Audit) Parent process id: 4002
 - (Audit) Parent process cwd: /home/vagrant

</details>

<details><summary><code>touch /home/vagrant/test/new-file-to-test.txt</code></summary>

** Alert 1692170035.664702: - ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Aug 16 09:13:55 (lunar) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/home/vagrant/test/new-file-to-test.txt' added
Mode: whodata

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Wed Aug 16 09:13:54 2023
 - Inode: 823237
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 - (Audit) User name: root
 - (Audit) Audit name: root
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 4446
 - (Audit) Process name: /usr/bin/touch
 - (Audit) Process cwd: /home/vagrant
 - (Audit) Parent process name: /usr/bin/bash
 - (Audit) Parent process id: 4002
 - (Audit) Parent process cwd: /home/vagrant

</details>

<details><summary><code>chmod 400 /home/vagrant/test/new-file-to-test.txt</code></summary>

** Alert 1692170169.823943: - ossec,syscheck,syscheck_entry_modified,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Aug 16 09:16:09 (lunar) any->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/home/vagrant/test/new-file-to-test.txt' modified
Mode: whodata
Changed attributes: permission
Permissions changed from 'r--------' to 'r--r-----'

Attributes:
 - Size: 0
 - Permissions: r--r-----
 - Date: Wed Aug 16 09:13:54 2023
 - Inode: 823237
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 - (Audit) User name: root
 - (Audit) Audit name: root
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 13688
 - (Audit) Process name: /usr/bin/chmod
 - (Audit) Process cwd: /home/vagrant
 - (Audit) Parent process name: /usr/bin/bash
 - (Audit) Parent process id: 4002
 - (Audit) Parent process cwd: /home/vagrant

</details>

### Change to "test2"

```shell
mkdir /home/vagrant/test2
sed -i 's-"/home/vagrant/test"-"/home/vagrant/test2"-' wazuh-ransomware-poc.py
sed 's->/home/vagrant/test<->/home/vagrant/test2<-' /var/ossec/etc/ossec.conf
service wazuh-agent restart
```

<details><summary><code>python3 wazuh-ransomware-poc.py prepare</code></summary>

** Alert 1692170677.1036254: - ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Aug 16 09:24:37 (lunar) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/home/vagrant/test2/Directory_00/File_19.txt' added
Mode: whodata

Attributes:
 - Size: 1024
 - Permissions: rw-r--r--
 - Date: Wed Aug 16 09:24:31 2023
 - Inode: 1280171
 - User: root (0)
 - Group: root (0)
 - MD5: 5e8f0f8d20ea7e90270b87b017e7c17f
 - SHA1: b95bdc8a8e75f490be1389a05e0ab646b6e8f8ca
 - SHA256: cc17103a7a3c46ca5543701df3a5222faacc0afed67a8933c17ddef4594a1caa
 - (Audit) User name: root
 - (Audit) Audit name: root
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 13796
 - (Audit) Process name: /usr/bin/python3.11
 - (Audit) Process cwd: /home/vagrant
 - (Audit) Parent process name: /usr/bin/bash
 - (Audit) Parent process id: 4002
 - (Audit) Parent process cwd: /home/vagrant

</details>

<details><summary><code>python3 wazuh-ransomware-poc.py attack</code></summary>

** Alert 1692170854.1138310: - ossec,syscheck,syscheck_entry_deleted,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Aug 16 09:27:34 (lunar) any->syscheck
Rule: 553 (level 7) -> 'File deleted.'
File '/home/vagrant/test2/Directory_05/File_14.txt' deleted
Mode: whodata

Attributes:
 - Size: 1024
 - Permissions: rw-r--r--
 - Date: Wed Aug 16 09:24:31 2023
 - Inode: 1280066
 - User: root (0)
 - Group: root (0)
 - MD5: 1527b257e74dde8e2160ba6562b5364f
 - SHA1: ebe2f74b5553985ddbdad977474a640a67a827f7
 - SHA256: fa7241035b45dc82d06371555affee58a334f5f8a91b70b4868f4752b57dc875
 - (Audit) User name: root
 - (Audit) Audit name: root
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 13808
 - (Audit) Process name: /usr/bin/python3.11
 - (Audit) Process cwd: /home/vagrant
 - (Audit) Parent process name: /usr/bin/bash
 - (Audit) Parent process id: 4002
 - (Audit) Parent process cwd: /home/vagrant

** Alert 1692170854.1139364: - ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Aug 16 09:27:34 (lunar) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/home/vagrant/test2/Directory_05/File_03.txt.encrypted' added
Mode: whodata

Attributes:
 - Size: 1464
 - Permissions: rw-r--r--
 - Date: Wed Aug 16 09:27:32 2023
 - Inode: 1280066
 - User: root (0)
 - Group: root (0)
 - MD5: ff4619f7ee4f8e08b4d6f66d3cea1a01
 - SHA1: 81c56f6a1b509038bcbd23daaa82e96883ca326e
 - SHA256: e0586433d2ec402bc432a72830d5de6ae12acac06c230d4e695291c6474308e5
 - (Audit) User name: root
 - (Audit) Audit name: root
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 13808
 - (Audit) Process name: /usr/bin/python3.11
 - (Audit) Process cwd: /home/vagrant
 - (Audit) Parent process name: /usr/bin/bash
 - (Audit) Parent process id: 4002
 - (Audit) Parent process cwd: /home/vagrant

</details>

### Repeat

```shell
rm -r test2/Directory_0*
python3 wazuh-ransomware-poc.py prepare
python3 wazuh-ransomware-poc.py attack
```

This produces similar results.

## Possible issues

- Restart the agent before creating directory _test2_:
> 2023/08/16 09:17:41 wazuh-syscheckd: WARNING: (6926): Unable to add audit rule for '/home/vagrant/test2'
- Remove _test2_ instead of its contents only: this would remove the who-data watch.

**Comment by c-bordon** [comment]
Todavia tengo el ambiente arriba por si quieres revisar algo.

agregue un nuevo directorio a syscheck, cree el directorio, reinicie el agente y cree un archivo, el archivo aparece en el inventario, pero no registra los cambios, edite el archivo y lo elimine y nada.

```console
  <!-- File integrity monitoring -->
  <syscheck>
    <disabled>no</disabled>

    <!-- Frequency that syscheck is executed default every 12 hours -->
    <frequency>300</frequency>

    <scan_on_start>yes</scan_on_start>

    <!-- Directories to check  (perform all possible verifications) -->
    <directories>/etc,/usr/bin,/usr/sbin</directories>
    <directories>/bin,/sbin,/boot</directories>
    <directories check_all="yes" report_changes="yes" realtime="yes">/root</directories>
    <directories check_all="yes" report_changes="yes" realtime="yes" whodata="yes">/home/vagrant/test/</directories>
    <directories check_all="yes" report_changes="yes" realtime="yes" whodata="yes">/home/vagrant/test2/</directories>
    <directories check_all="yes" report_changes="yes" realtime="yes" whodata="yes">/home/vagrant/test3/</directories>
```
![Screenshot_20230816_104751](https://github.com/wazuh/wazuh/assets/64099752/53968669-4450-4bcf-b681-39e5627535c6)
![Screenshot_20230816_104804](https://github.com/wazuh/wazuh/assets/64099752/c5bddd07-be06-4a78-959e-cb0222ae8d4d)
![Screenshot_20230816_104813](https://github.com/wazuh/wazuh/assets/64099752/5c247365-9167-46a7-8e5b-6747b7e764af)

**Comment by jotacarma90** [comment]
@c-bordon 
Hello,
Does the problem still exist? If possible, we can go into a meeting to see it and try to analyze in depth the reasons.
