### ISSUE TITLE
Vulnerability Detector warning in Footprint test. Bullseye database not found

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh#18447]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.1-rc1 | Vulnerability detector | Manager | Packages/Sources | OS version |

A new warning has appeared in the stress tests for the Vulnerability Detector in the RC 1 stage of the `4.5.1` release. It appears on all tests that include the vulnerability detector. 

The warning is the following:
```
wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'Debian Bullseye' database could not be fetched.
```

The warning appears in the following issues:
- https://github.com/wazuh/wazuh/issues/18403
- https://github.com/wazuh/wazuh/issues/18396
- https://github.com/wazuh/wazuh/issues/18400
- https://github.com/wazuh/wazuh/issues/18408
- https://github.com/wazuh/wazuh/issues/18401
- https://github.com/wazuh/wazuh/issues/18392

An example of the logs and configuration for the manager on which the warning has appeared:

[ossec_Test_stress_B4254_manager_2023-08-14.zip](https://github.com/wazuh/wazuh/files/12359073/ossec_Test_stress_B4254_manager_2023-08-14.zip)

**Comment by vikman90** [comment]
@verdx In this case, all fetches worked:

> 2023/08/16 16:29:15 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Debian Buster' database update.
2023/08/16 16:29:20 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'Debian Buster' feed finished successfully.
2023/08/16 16:29:20 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Debian Bullseye' database update.
2023/08/16 16:29:24 wazuh-modulesd:vulnerability-detector: INFO: (5430): **The update of the 'Debian Bullseye' feed finished successfully.**
2023/08/16 16:29:24 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'National Vulnerability Database' database update.
2023/08/16 16:31:17 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'National Vulnerability Database' feed finished successfully.
2023/08/16 16:31:17 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Microsoft Security Update' database update.
2023/08/16 16:31:23 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'Microsoft Security Update' feed finished successfully.

**Comment by pro-akim** [comment]
## Update
The issue was reopened again because the log has been found once more at https://github.com/wazuh/wazuh/issues/18672. (Release 4.5.2-rc1)

Log of the manager is attached [here](https://github.com/wazuh/wazuh/files/12466031/ossec_Test_stress_B4271_manager_2023-08-28.zip).

**Comment by MarcelKemp** [comment]
## Research

The problem starts appearing after the changes made to the VD configuration of the stress tests (`4.5.0`), because previously it was getting the feeds from a local URL (_S3_) that had these feeds (although they were not updated). 
And with the changes made in the following PR, it downloads the feeds from the official servers:
- https://github.com/wazuh/wazuh-jenkins/pull/5475

This means that if there is a server downtime, it causes a `warning` or `error`.

### Evidence

Based on the results of the VD stress tests of the issue: 
> - https://github.com/wazuh/wazuh/issues/18513
-----
- **Day 17 and 18, there is no failure.**

- **Day 19**, problems with the download appear:

  - `2023/08/19 11:26:35` - Buster (occasional failure)
> In between there are no errors
  - `2023/08/19 13:12:12` - Bullseye (occasional failure)

> No other error until the next one:
  - From `2023/08/19 14:45:55` - Bullseye fails
    - Buster + Bullseye still fail (temporary failure)
  - Until `2023/08/19 16:33:34` - Last Buster + Bullseye failure

> From the next error onwards, it seems to be a temporary server failure:
  - As of 2023/08/19 18:04:15
    - Buster + Bullseye (temporary failure)
  - Until 2023/08/20 06:26:57

> And last temporary bug:
  - 2023/08/20 08:06:15 - Bullseye (occasional failure)
-----

And well the following _error_, it is always caused by the failure when trying to download the Debian feed:
`ERROR: (5513): CVE database could not be updated.`


The same problem is repeated here: 
> - https://github.com/wazuh/wazuh/issues/18672

### Conclusion
The problem seems to come from the Debian servers, since in the great majority of cases it has worked, but it has begun to fail on the 19th and 20th, punctual in some cases, and then they seem temporary falls of the server, since they fail both (Buster + Bullseye) during an interval of time, and then they begin to work.

https://www.isitdownrightnow.com/debian.org.html -> `0ms = Server Down`

- Issue: https://github.com/wazuh/wazuh/issues/18513
```
19.Aug.2023 19:55 0 ms. 19.Aug.2023 21:56 0 ms.
20.Aug.2023 00:04 0 ms. 20.Aug.2023 02:55 0 ms.
20.Aug.2023 04:59 0 ms. 20.Aug.2023 08:17 0 ms.
20.Aug.2023 11:13 0 ms. 20.Aug.2023 19:35 29.16 ms.
```
- Issue: https://github.com/wazuh/wazuh/issues/18672
![Screenshot from 2023-08-30 12-34-23](https://github.com/wazuh/wazuh/assets/37207742/611b7f82-209d-4af1-9db7-fc7441a91b2d)


> Note: In previous versions this did not happen because an _offline configuration_ was used, downloading the feeds via `url` that were uploaded to S3.
