### ISSUE TITLE
Modulesd and Agentd disk read activity pattern changed compared to previous footprint tests

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#18446]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.1-RC1 | Modulesd and Agentd | Agent | Packages | Ubuntu |

Running 4.5.1 RC1 - Footprint test - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (https://github.com/wazuh/wazuh/issues/18394#issuecomment-1680386377), it was possible to see a different pattern of disk activity of Modulesd and Agentd compared to 4.4.2-RC1 and 4.4.1-RC1.

No abnormalities were detected in logs and Ubuntu Agent activity, however, further research should be performed.

Attached:
[CSVs](https://github.com/wazuh/wazuh/files/12359848/csv.zip)
[Logs](https://github.com/wazuh/wazuh/files/12359838/ossec_Test_stress_B3868_ubuntu_2023-04-03.zip)

**Comment by LucioDonda** [comment]
Based on the analysis made on the logs and graphics we can assume that:
- Agentd daemon has a very similar behavior compared to previous releases. Same values of Disk Read in bytes at Full Load (low and high), just a slight difference on when that value gets near 8000.
- Disk read of Modulesd daemon on the other side has no value on the whole test. 
- Same thing is happening on all the other daemons (except for agentd).
- That sounds strange, especially analyzing the row related to _Read_ops_ which does have non zero values.
That's why the graphic doesn't look alike compared to other versions.
IMO this could be rechecked on RC2. 
c.c. @pro-akim @TomasTurina

**Comment by TomasTurina** [comment]
As @LucioDonda said, there seems to be a problem with this particular test since it wasn't able to read correctly the disk read information for almost all modules. Let's close this issue and repeat it again in RC2.
