### ISSUE TITLE
Investigate AWS ITs race conditions and mitigations

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#18478]
| Affected integration |
|---|
| AWS |

## Description
During the development of the AWS ITs migration being carried out in #17788, it was found that these tests have a potential bug that could affect multiple parallel test runs.

Since these tests modify cloud resources while running, if another user or PR process runs them, a race condition is generated making the test prone to fail due to the addition or removal of a specific test log by one of the executors.
Example of failure:
```
assert bucket_name in data.bucket_path
>       assert metadata['uploaded_file'] == data.log_key
E       AssertionError: assert 'AWSLogs/8197...03785917.json' == 'AWSLogs/8197...59225774.json'
E         Skipping 87 identical leading characters in diff, use -v to show
E         - 20230815T1357Z_3007284625459225774.json
E         + 20230815T1406Z_2511407128003785917.json
```

We should analyze possible solutions in order to avoid false positive errors in the upcoming PR checks.

**Comment by nico-stefani** [comment]
# Issue Update

I was analyzing which are the tests that fail when there are parallel executions.
These are the findings:
* Buckets
  * *_without_only_logs_after
  * *_with_only_logs_after
  * *_only_logs_after_multiple_calls
  * *_remove_from_bucket
* Services
  * cloudwatchlogs_remove_from_buckets
  * cloudwatchlogs_with_only_logs_after
  * cloudwatchlogs_log_groups_with_data

**Comment by nico-stefani** [comment]
# Issue Update

Regarding the bucket tests, that I mentioned below, a possible solution could be to generate truly random *account_id* for each execution and pass it as a parameter to the AWS module, using the option `--aws_account_id`. In order to only modify the files within the path `s3://bucket_name/AWSLogs/account_id/bucket_type/region/YYYY/MM/DD/file`.


The value to replace in [qa-integration-framework](https://github.com/wazuh/qa-integration-framework/blob/55f0ff7406786eef94355498215c5c846b619ee9/src/wazuh_testing/modules/aws/__init__.py#L10).

**Comment by nico-stefani** [comment]
## Issue Update

Regarding the setup error of `cloudwatchlogs_remove_from_bucket` and `cloudwatchlogs_log_groups_with_data` the problem comes when the fixture `fixture_create_log_stream`
tries to create a log group that already exists.

```
root@ubuntu-jammy:/home/vagrant/wazuh-qa/tests/integration/test_aws# pytest --disable-warnings --tb=line -s -k cloudwatchlogs_remove_from_bucket
================================================================================================ test session starts ================================================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/vagrant/wazuh-qa/tests/integration, configfile: pytest.ini
plugins: metadata-2.0.4, html-3.1.1, testinfra-5.0.0
collected 198 items / 197 deselected / 1 selected

test_remove_from_bucket.py 2023-09-19 14:25:01,586 - wazuh_testing - DEBUG - Creating log group: temporary-log-group
E

====================================================================================================== ERRORS =======================================================================================================
____________________________________________________________________ ERROR at setup of test_remove_log_stream[cloudwatchlogs_remove_from_bucket] ____________________________________________________________________
E   botocore.errorfactory.ResourceAlreadyExistsException: An error occurred (ResourceAlreadyExistsException) when calling the CreateLogGroup operation: The specified log group already exists
------------------------------------------------------------------------------------------------ Captured log setup -------------------------------------------------------------------------------------------------
DEBUG    wazuh_testing:conftest.py:90 Creating log group: temporary-log-group
============================================================================================== short test summary info ==============================================================================================
ERROR test_remove_from_bucket.py::test_remove_log_stream[cloudwatchlogs_remove_from_bucket] - botocore.errorfactory.ResourceAlreadyExistsException: An error occurred (ResourceAlreadyExistsException) when callin...
=================================================================================== 197 deselected, 6 warnings, 1 error in 2.98s ====================================================================================
```

To solve this we need to use a random log group name for each test execution. 
Also, we need to find a way to use dynamic values in the test cases yaml's, by example:

https://github.com/wazuh/wazuh/blob/4010b4217d40e2dc962102f658f1bac0187f1dd1/tests/integration/test_aws/data/test_cases/remove_from_bucket_test_module/cases_remove_log_streams.yaml#L5

**Comment by Selutario** [comment]
ETA postponed to 28/10/23. Reason:
- https://github.com/wazuh/wazuh/issues/18725

**Comment by nico-stefani** [comment]
# Update

I've retaken the issue and set up the environment to execute the tests. Also, I've tried to find the failed reason for the `cloudwatchlogs_with_only_logs_after` test.

**Comment by nico-stefani** [comment]
# Summary

The race conditions we faced came with the cases that generated resources on demand to execute the test.

After the investigation, I found two possible solutions for these problems:

## 1. Generate isolated resources for each test

For the buckets tests we need to use a randomly created [account_id](https://github.com/wazuh/qa-integration-framework/blob/55f0ff7406786eef94355498215c5c846b619ee9/src/wazuh_testing/modules/aws/__init__.py#L10) and call the module with the `--aws_account_id`.

For the cloudwatch ones, occurs something similar in this case the problem is the log group that these tests share. To fix it we need to use a unique value generated for the test execution of https://github.com/wazuh/wazuh/blob/4010b4217d40e2dc962102f658f1bac0187f1dd1/tests/integration/test_aws/data/test_cases/remove_from_bucket_test_module/cases_remove_log_streams.yaml#L5.

For twice fixes, we need to figure out how to use variable values in the test cases yaml's to isolate the different executions.


## 2. Mock AWS Services

During the investigation, I found a very interesting tool, [moto](https://docs.getmoto.org/en/latest/index.html), that I would like to mention as an alternative.

The [Proxy Mode](https://docs.getmoto.org/en/latest/docs/proxy_mode.html) allows us to intercept the calls to the AWS API and make them more self-contained and less dependent on the remote resources and in consequence a bit faster.

As a con, we'll need fixtures to create the resources for the cases that only consume logs that already are in the S3 and CloudWatch.

Another issue is the lack of support for the `inspector` API. The other API's that currently we consume are supported [S3](https://docs.getmoto.org/en/latest/docs/services/s3.html), [CloudWatch](https://docs.getmoto.org/en/latest/docs/services/logs.html) and even [SQS](https://docs.getmoto.org/en/latest/docs/services/sqs.html) for future developments.
So if we consider this approach we can think of a mix of mocked and real API calls.

**Comment by GGP1** [comment]
## Review

The investigation identified the tests affected and the reason behind the failures successfully.

As far as the proposed solutions, the mocking library could be a great alternative. We would avoid connection or service availability issues, it won't require creating "real" resources that may incur a cost in the future and the tests would take less time to execute.

Regarding the missing APIs, we should check if the library is updated regularly and well maintained, but I agree with the approach of using the real APIs or even creating custom mocks ourselves if that's feasible.

**Comment by Selutario** [comment]
LGTM. In my opinion, we should go for option 1. (`Generate isolated resources for each test`) since I wouldn't mock anything outside unit tests.
