### ISSUE TITLE
Wazuh agent fails to calculate database checksum in Windows

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh#18522]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.1-rc2 | Wazuh agent | Agent | Packages | Windows |

The footprint test done for the Release Candidate 2 of version `4.5.1` in https://github.com/wazuh/wazuh/issues/18514 has encountered a new error, not previously seen, on the Windows agent.

The error seen is the following:

```
wazuh-agent ERROR: (6707): Failed to calculate database checksum.
```

**Comment by vikman90** [comment]
@verdx Are there signs of a full disk or file corruption?

This seems to be due to some internal error in SQLite, possibly accessing the database file.

However, this has not been modified in previous versions for a long time.

On the other hand, I see that the agent recovers from the problem since the synchronization is done continuously and the error appears only once.

- If there are signs of disk issues: close this issue.
- Otherwise: set as a low impact bug.

**Comment by verdx** [comment]
@vikman90 In the footprint test plots there doesn't seem to be signs of disk or file corruption, or at least, any new one, all problems with files are the same as in previous tests, where this error did not appear.
