### ISSUE TITLE
New Vulnerability feed missing configuration

### ISSUE THREAD

**Issue by STRATEC-IT** [wazuh/wazuh#18550]
Hello,

I've investigated why some new CVEs regarding Zoom are not showing up in the system. I've noticed that the new feed is missing configuration information for new CVEs:

![image](https://github.com/wazuh/wazuh/assets/141937661/15b441dc-192b-419e-ac0d-fa0c5f5d566f)

Source: https://feed.wazuh.com/vulnerability-detector/NVD/generated-feeds/complete_nvd_feed.json.gz

Old feed:

![image](https://github.com/wazuh/wazuh/assets/141937661/84ac9733-5239-44b0-89c1-7ebf5a5997a3)

Source: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2023.json.gz

Best regards,
Manuel

**Comment by MarcelKemp** [comment]
Hi @STRATEC-IT,

After investigating the issue you mentioned, I confirm that there is a problem when updating the NVD feed (created via the _API_), where the vulnerability information is not correctly overwritten once they are updated in the NVD, causing them to be outdated (no _`configurations`_, no _`references`_, etc).

We are checking why it is not updating correctly, in order to fix it ASAP.

Even so, we will try to update the feed today to have all the information available.

Sorry for the inconvenience, and thank you very much for informing us about the issue!
