### ISSUE TITLE
Add option to hide traceback from `WazuhInternalError`

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#18560]
## Description

There are multiple types of errors in the framework. Some of them are `WazuhError`, which is returned as a `400 Bad Request` in the API:
https://github.com/wazuh/wazuh/blob/2960662dcf23c88ea73eefdd2c330028426957aa/framework/wazuh/core/exception.py#L784-L790

and `WazuhInternalError`, which is returned as a `500 Internal Server Error`:
https://github.com/wazuh/wazuh/blob/2960662dcf23c88ea73eefdd2c330028426957aa/framework/wazuh/core/exception.py#L733-L739

When a `WazuhInternalError` is raised, the `dapi` module logs the error trace:
https://github.com/wazuh/wazuh/blob/2960662dcf23c88ea73eefdd2c330028426957aa/framework/wazuh/core/cluster/dapi/dapi.py#L188-L193

Printing the error trace is useful in the `api.log`, but it looks bad when printed as the output of a CLI:
```
# /var/ossec/bin/agent_upgrade -a 001 -f /home/ubuntu/wazuh_agent_v4.5.1_macos_x86_64.wpk -F
The WPK package used does not fit with the agent's architecture
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.5.1-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 247, in run_local
    data = f(**f_kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.5.1-py3.9.egg/wazuh/rbac/decorators.py", line 423, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.5.1-py3.9.egg/wazuh/agent.py", line 989, in upgrade_agents
    raise WazuhInternalError(error_code, cmd_error=True, extra_message=agent_result['message'])
wazuh.core.exception.WazuhInternalError: Error 1836 - The WPK package used does not fit with the agent's architecture
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.5.1-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 292, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
wazuh.core.exception.WazuhInternalError: Error 1836 - The WPK package used does not fit with the agent's architecture
Error 500: The WPK package used does not fit with the agent's architecture
```

## To do
We need to refactor or implement a way to set whether the traceback should be logged or not in the `WazuhInternalError`s, or at least hide it for CLI's. 

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by RamosFe** [comment]
## Update

Started analyzing the code for `WazuhInternalError`. Passed to `on-hold` due to the higher priority of Issue https://github.com/wazuh/wazuh/issues/18844.

**Comment by RamosFe** [comment]
## Update

The traceback is printed due to the `exec_info` option in `logger.error`:
https://github.com/wazuh/wazuh/blob/b8e5c4beebdf2d5ec7bed1bb41227273588780cb/framework/wazuh/core/cluster/dapi/dapi.py#L188-L196

We can create a logic similar to this one for checking if the logger prints to a file or to the CLI based on his handlers (if it has no handlers, the default configuration is to print the output to CLI):
https://github.com/wazuh/wazuh/blob/b8e5c4beebdf2d5ec7bed1bb41227273588780cb/framework/wazuh/core/cluster/dapi/dapi.py#L392-L397

**Comment by RamosFe** [comment]
## Update

After checking the changes made in https://github.com/wazuh/wazuh/issues/20748 and testing the multiple error cases (User related errores and Internal Errors) to validate the need of this Issue, I continue with the design of the `hide traceback` option.

**Comment by RamosFe** [comment]
## Update
There are possible solutions that can be made to fix this problem. The first 2 are, in my opinion, the best solution because it abstracts the logic behind the `Logger` class utilities, but they also are the most time-consuming. The other is simpler but difficult to extend and can have unexpected side effects in the future.

### Solution 1: Using the `Filter` object from `Logger` library.

We can create a `Filter` object to filter all the logs related to `WazuhInternalError` and only configuring it on the `loggers` that are used in the scripts or that doesn't have a file `Handler` attached to them. This solutions needs to check each `logger` configuration in the code and check that is used correctly and evenly between all scripts that logs directly to `CLI`. This solution also abstracts the developer of this logics and deletes creating repeated code in all code snippets that handles logging and `WazuhInternalError`.

### Solution 2: Configuring the `Handler` object to ignore `WazuhInternalErrors`.

This solutions focuses on adding a new level of logs (in this case `critical`) to handle the errors related to internal errors of the system only. This way we can configure different logics for each logger present in the system. The problem with this solution is that it needs to change all code snippets where the logger and `WazuhInternalError` is used in conjunction, and change it to the respective `Logger` level method.

### Solution 3: Add `if` statement to check if the logger has `Handlers` attached.

This is the simpler solution but has some problemas. This solution consist of checking with an if statement if the `logger` has any handlers, and depending of this to log or not the `WazuhInternalError`. The problem is that a `Handler` isn't equivalent to "dropping the log to a file" it can also redirect the logs to the CLI and still be a `Handler` attached to the logger. We need to check this cases and the only way is knowing exactly what `Handlers` are we expecting. This is ok but the code makes a lot of abstractions in the configuration of the `logger` to hide this implementation details, and adding this logic make it pointless.

**Comment by RamosFe** [comment]
## Update

After discussing it with the team, we choose to continue with the implementation of `Solution 1`. I continue with the development of the `Filter` object and apply it to all the all the loggers used in scripts.

**Comment by RamosFe** [comment]
## Update

Added the `Solution 1`. After recreating the example, no traceback was found:

```bash
root@wazuh-master:/var/ossec/bin# ./agent_upgrade -a 002 -f /var/ossec/bin/wazuh_agent_v4.7.5_windows.wpk -F

Upgrading...

Failed upgrades:
	Agent 002 status: Send upgrade command error

```

**Comment by GGP1** [comment]
## Reopening

During https://github.com/wazuh/wazuh/issues/23218, it was found that the traceback is still appearing when there's an internal error in a distributed function.

Even if the exception is correctly captured, the trace is not hidden after the changes from this issue.

```console
root@wazuh-master:/# /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/agent_upgrade.py -a 001 -f /wpk_file
Agent information not found in database
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/dapi/dapi.py", line 239, in run_local
    data = f(**f_kwargs)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/decorators.py", line 494, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/agent.py", line 1139, in upgrade_agents
    raise WazuhInternalError(1816, 'Agent information not found in database')
wazuh.core.exception.WazuhInternalError: Error 1816 - Agent information not found in database
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/dapi/dapi.py", line 285, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
wazuh.core.exception.WazuhInternalError: Error 1816 - Agent information not found in database
Internal error: Error 1816 - Agent information not found in database
```

The filter was applied to the `logger` variable but it isn't used, the errors are printed directly with `print()`.

**Comment by Selutario** [comment]
Since this issue was aimed at 5.0 but most of the binaries/CLIs will be removed (https://github.com/wazuh/wazuh/issues/22888), this won't be necessary.
