### ISSUE TITLE
NVD feed integration broken?

### ISSUE THREAD

**Issue by gituser28910** [wazuh/wazuh#18603]
|Wazuh version|Component|Install type|Install method|Platform|
|4.5.0+|wazuh-manager|---|---|Linux|

Periodic error message in ossec.log on manager on both 4.5.0 and 4.5.1. Unfortunately can't tell if it was there before - first time I noticed it.

> 2023/08/24 01:03:13 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'National Vulnerability Database' database update.
> 2023/08/24 01:03:18 wazuh-modulesd:vulnerability-detector: ERROR: (5503): SQL error: 'table NVD_CVE has 9 columns but 10 values were supplied'
> 2023/08/24 01:03:18 wazuh-modulesd:vulnerability-detector: ERROR: (5503): SQL error: 'table NVD_CVE has 9 columns but 10 values were supplied'
> 2023/08/24 01:03:18 wazuh-modulesd:vulnerability-detector: ERROR: (5506): Could not refresh the 'NVD' DB.
> 2023/08/24 01:03:20 wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.

Scanning appears to work, although I feel there are many more 'untriaged' vulnerabilities being shown now (but don't have data to compare/proof/disproof). I searched for "NVD" and "NVD_CVE" in prior issues, but couldn't find anything relevant.

Debug logging doesn't seem to help much (not me, at least):

> 2023/08/24 01:08:18 wazuh-modulesd:vulnerability-detector[10455] wm_vuln_detector.c:5612 at wm_vuldet_json_parser(): DEBUG: (5414): Refreshing 'National Vulnerability Database' databases.
> 2023/08/24 01:08:23 wazuh-modulesd:vulnerability-detector[10455] wm_vuln_detector.c:3243 at wm_vuldet_insert(): DEBUG: (5415): Inserting vulnerabilities.
> 2023/08/24 01:08:23 wazuh-modulesd:vulnerability-detector[10455] wm_vuln_detector.c:3282 at wm_vuldet_insert(): DEBUG: (5419): Inserting NVD vulnerabilities section.
> 2023/08/24 01:08:23 wazuh-modulesd:vulnerability-detector[10455] wm_vuln_detector_nvd.c:1380 at wm_vuldet_insert_nvd_cve(): ERROR: (5503): SQL error: 'table NVD_CVE has 9 columns but 10 values were supplied'
> 2023/08/24 01:08:23 wazuh-modulesd:vulnerability-detector[10455] wm_vuln_detector.c:2850 at wm_vuldet_sql_error(): ERROR: (5503): SQL error: 'table NVD_CVE has 9 columns but 10 values were supplied'
> 2023/08/24 01:08:23 wazuh-modulesd:vulnerability-detector[10455] wm_vuln_detector.c:5615 at wm_vuldet_json_parser(): ERROR: (5506): Could not refresh the 'NVD' DB.
> 2023/08/24 01:08:24 wazuh-modulesd:vulnerability-detector[10455] wm_vuln_detector.c:4864 at wm_vuldet_index_feed(): DEBUG: remove(tmp/vuln-temp.bz2): No such file or directory

**Comment by MarcelKemp** [comment]
Hi @gituser28910,
The first SQL error is due to the fact that the `cve.db` database has not been updated correctly (to update it, it must be purged and recreated). 
> This usually happens when you try to replace the `cve.db` database with one that is backed up from a previous version.

To fix the problem, simply **delete the DB** and **restart the manager**, as explained in the following comment:
- https://github.com/wazuh/wazuh/issues/5306#issuecomment-648694565

The good news, is that we are already working on the next issue, to avoid having to manually delete the DB if the schema or version is not correct.
- https://github.com/wazuh/wazuh/issues/16699

According to the problem of more vulnerabilities appearing in _`untriaged`_ status, it may be related to this other issue that we are investigating and want to fix ASAP:
- https://github.com/wazuh/wazuh/issues/18550#issuecomment-1693177204

I hope you find it useful. If you have any other questions, don't hesitate to ask.

**Comment by gituser28910** [comment]
Thank you @MarcelKemp for the guidance.
Deleting and re-creating the /var/ossec/queue/vulnerabilities/cve.db file solves the issue that I originally raised (NVD feed not working).

The only downside / additional question is that NVD vulnerabilities for Debian (if they exist - according to https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/how-it-works.html they should) seem not to be taken into account. 
The Debian feed update servers seem to be down at the moment, so in the absence of vulnerability data, Debian endpoints are skipped from the scan.  I suppose this is an unrelated matter, hence closing this particular issue.
