### ISSUE TITLE
Warning in Windows Agent in footprint test WARNING: (1214): Problem receiving message 

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#18678]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2-rc1 | Wazuh Agent Log | Agent | Packages | Windows |

Running Footprint test [VULNERABILITY-DETECTOR-REGISTER (2.5d)](https://github.com/wazuh/wazuh/issues/18653)
Build: https://ci.wazuh.info/job/Test_stress/4272/

The following new warning was found:

```
WARNING: (1214): Problem receiving message from '172.31.13.241'
```

It was found only once.
Further research is required.

**Comment by vikman90** [comment]
@pro-akim It would be interesting to know the log in its context:

>2023/08/26 09:58:19 wazuh-agent: INFO: (4102): Connected to the server ([172.31.13.241]:1514/tcp).
2023/08/26 09:58:19 rootcheck: INFO: Rootcheck disabled.
2023/08/26 09:58:19 wazuh-agent: INFO: Windows version is 6.0 or newer. (Microsoft Windows Server 2019 Datacenter [Ver: 10.0.17763.1999] - Wazuh v4.5.2).
2023/08/26 09:58:19 wazuh-modulesd:agent-upgrade: INFO: (8153): Module Agent Upgrade started.
2023/08/26 09:58:19 sca: INFO: Module disabled. Exiting.
2023/08/26 09:58:19 wazuh-modulesd:syscollector: INFO: Module disabled. Exiting...
2023/08/26 09:58:19 wazuh-modulesd:osquery: INFO: Module disabled. Exiting...
2023/08/26 09:58:19 wazuh-modulesd:ciscat: INFO: Module disabled. Exiting...
2023/08/26 09:58:19 wazuh-agent: INFO: Started (pid: 4928).
2023/08/26 09:58:39 wazuh-agent: WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '839' at 'any'.
1️⃣ **2023/08/26 09:58:39 wazuh-agent: WARNING: (1214): Problem receiving message from '172.31.13.241'.**
2023/08/26 09:59:19 agent-auth: INFO: Started (pid: 3044). 
2023/08/26 09:59:19 agent-auth: INFO: Requesting a key from server: 172.31.13.241
2023/08/26 09:59:19 agent-auth: INFO: No authentication password provided
2023/08/26 09:59:19 agent-auth: INFO: Using agent name as: EC2AMAZ-L273KKC-17067-132812
2023/08/26 09:59:19 agent-auth: INFO: Waiting for server reply
2023/08/26 09:59:19 agent-auth: INFO: Valid key received
2023/08/26 09:59:20 wazuh-agent: INFO: Received exit signal. Starting exit process.
2023/08/26 09:59:20 wazuh-agent: INFO: Set pending exit signal.
2023/08/26 09:59:20 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2023/08/26 09:59:20 wazuh-agent: INFO: Exit completed successfully.
2️⃣ 2023/08/26 09:59:20 wazuh-agent: INFO: Using notify time: 10 and max time to reconnect: 60
2023/08/26 09:59:20 wazuh-agent: INFO: (1410): Reading authentication keys file.
2023/08/26 09:59:20 wazuh-agent: INFO: (1905): No file configured to monitor.
2023/08/26 09:59:20 wazuh-agent: INFO: (1350): Active response disabled.
2023/08/26 09:59:20 wazuh-agent: INFO: Using AES as encryption method.
2023/08/26 09:59:20 wazuh-agent: INFO: Trying to connect to server ([172.31.13.241]:1514/tcp).
2023/08/26 09:59:20 wazuh-agent: INFO: (6678): No directory provided for syscheck to monitor.
2023/08/26 09:59:20 wazuh-agent: INFO: (6001): File integrity monitoring disabled.
2023/08/26 09:59:20 rootcheck: INFO: Rootcheck disabled.
2023/08/26 09:59:30 wazuh-agent: INFO: Closing connection to server ([172.31.13.241]:1514/tcp).
2023/08/26 09:59:30 wazuh-agent: INFO: Trying to connect to server ([172.31.13.241]:1514/tcp).
3️⃣ 2023/08/26 09:59:30 wazuh-agent: INFO: (4102): Connected to the server ([172.31.13.241]:1514/tcp).

1. The agent printed that error as a **consequence** of a partially received message (warning above), because **the agent was stopped or restarted.
2. The agent started again later.
3. The agent was able to connect to the manager. No warnings appeared since then.

## Conclusion

I don't think this is a problem.
