### ISSUE TITLE
Multiple AgentD_status drops in the second half of the test in Footprint test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#18681]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2-rc1 | Wazuh Agent |Agent | Packages | CentOS, Ubuntu, Windows |

Build: https://ci.wazuh.info/job/Test_stress/4277/
Test: [Release Candidate RC1 - Footprint Metrics - ALL (2.5d)](https://github.com/wazuh/wazuh/issues/18655)

Read_Ops: The 'read_ops' decreases its usage in 'modulesd' throughout the testing process to approximately one-third of the value.

Centos
![image](https://github.com/wazuh/wazuh/assets/125690423/60a046b9-30e3-48f7-aa25-b0f68b3a1c64)

Ubuntu
![image](https://github.com/wazuh/wazuh/assets/125690423/bef8cef9-8c64-49d8-9d0f-501fd62d6fb3)

Windows
![image](https://github.com/wazuh/wazuh/assets/125690423/23481862-55a5-46aa-aabf-1073d3c8df6b)

Further research should be done

**Comment by cborla** [comment]
# AgentD_status drops
According to the data found, the disconnection of the agents reported in the issue is due to expected behavior.
The problem seems to be on the manager's side.

## Ubuntu agent findings:

It is possible to start the analysis by focusing on a particular period of disconnection, finding this period of time in the CSV file.

![image](https://github.com/wazuh/wazuh/assets/41765669/be40b5c4-65da-4e22-81d4-bae5d27f46e4)

Disconnection starts at 18:11 until 18:12. Searching for the agent's status in that time range, the following log is found:

```
2023/08/27 18:10:48 wazuh-agentd: INFO: Agent buffer is under 70 %. Working properly again.
2023/08/27 18:10:49 wazuh-agentd: WARNING: Agent buffer at 90 %.
2023/08/27 18:10:49 wazuh-agentd: WARNING: Agent buffer is full: Events may be lost.
2023/08/27 18:10:50 wazuh-modulesd:ciscat: INFO: Evaluation finished.
2023/08/27 18:10:52 rootcheck: INFO: Starting rootcheck scan.
2023/08/27 18:10:57 wazuh-syscheckd: INFO: (6008): File integrity monitoring scan started.
2023/08/27 18:10:59 wazuh-agentd: WARNING: Agent buffer is full: Events may be lost.
2023/08/27 18:11:10 wazuh-agentd: WARNING: Agent buffer is full: Events may be lost.
2023/08/27 18:11:13 rootcheck: INFO: Ending rootcheck scan.
2023/08/27 18:11:15 wazuh-agentd: WARNING: Server unavailable. Setting lock.
2023/08/27 18:11:15 wazuh-agentd: INFO: Closing connection to server ([172.31.4.158]:1514/tcp).
2023/08/27 18:11:15 wazuh-agentd: INFO: Trying to connect to server ([172.31.4.158]:1514/tcp).
```

Where you can see 2 important points, first the agent reports that the buffer is at 90%, after a few seconds the agent decides to disconnect from the server and try to connect again.

What is the reason for this behavior?
This is because the agent has configured the time-reconnect functionality in 60 seconds. Which indicates that in case the manager does not answer during 60 seconds the ACK of the keepalive messages sent by the agent, people will be restarted.

Achieving reconnection at 18:12:25
`2023/08/27 18:12:25 wazuh-agentd: INFO: (4102): Connected to the server ([172.31.4.158]:1514/tcp).
`

ossec.conf configuration:
```
  <client>
    <server>
      <address>172.31.4.158</address>
      <port>1514</port>
      <protocol>tcp</protocol>
    </server>
    <config-profile>ubuntu, ubuntu18, ubuntu18.04</config-profile>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>                                 <-------------------- time-reconnect
    <auto_restart>yes</auto_restart>
    <crypto_method>aes</crypto_method>
  </client>
```
Therefore, we can conclude that the problem is not on the agents' side, and it also applies to the fact that the error occurs in 3 different agents in 3 different operating systems.
Therefore, we can rule out a problem on the agent side.

## Manager findings:
On the manager side the situation is a bit different, there is no specific event that indicates the disconnection of the agent, or the reason why it does not send the ACK to the received keepalive.

The evidence found is that before each agante disconnection the following message appears:
`2023/08/27 18:11:37 wazuh-syscheckd: WARNING: Real-time inotify kernel queue is full. Some events may be lost. Next scheduled scan will recover lost data.  
`
So we can assume that the queue where the events are inserted is full, not receiving new events to be processed, also at the beginning of the test we find the message that the queue is full:

`2023/08/25 22:52:23 wazuh-remoted: WARNING: Message queue is full (10). Events may be lost.`

The above message is printed only once, unless the test is run in DEBUG mode the message would be printed each time remoted has a full buffer.

# Conclusion

- The disconnection of the agents is due to the lack of response from the manager.
- The manager reports problems storing new events, so it is very likely that the keepalive events as well as other events are discarded, as we can see in the following [graph](https://camo.githubusercontent.com/24a8e4efdc414c635ad83a52763564f9c9f10f810d48ae09f9a482556f47e112/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e322f42343237372d333630306d2f42343237375f6d616e616765725f63656e746f732f706c6f74732f546573745f7374726573735f42343237375f6d616e616765725f616e616c79736973645f6576656e74735f44726f707065645f6576656e74732e706e67), [test link](https://github.com/wazuh/wazuh/issues/18655), which would cause the agent to disconnect after 60 seconds.
- There is also an issue reported which has the same behavior, Realted [issue](https://github.com/wazuh/wazuh/issues/17928).
