### ISSUE TITLE
VD alerts generation delay

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh#18682]
### Description
During the `Demo use cases` test for `4.5.2 RC1` ([issue](https://github.com/wazuh/wazuh/issues/18676)) a delay was found for the VD alerts. More info here: ([comment](https://github.com/wazuh/wazuh/issues/18676#issuecomment-1695593900))

The automatic VD use case test failed, but the alerts were generated 1:30 hours after the test execution.

### Logs
VD logs:
[vd.log](https://github.com/wazuh/wazuh/files/12455201/vd.log)

**Comment by mauromalara** [comment]
## Update

Also, when patching a vulnerability it is marked as solved after an hour or even more. Found in this issue: https://github.com/wazuh/wazuh/issues/18679

**Comment by mauromalara** [comment]
## Update

Also, when patching a vulnerability it is marked as solved after an hour or even more. Found in this issue: https://github.com/wazuh/wazuh/issues/18679

cc @MarcelKemp @teddytpc1

**Comment by MarcelKemp** [comment]
## Research

Hi @teddytpc1 and @mauromalara,

The delay in the generation of alerts according to the VD log that has been shared in this issue, seems to be related to a timeout problem in the feed download due to a slow connection with the server (or a failure in the _SUSE_ server), which causes the following _warnings_:
```
2023/08/25 20:46:10 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'SUSE Linux Enterprise Server 15' database update.
2023/08/25 21:16:20 wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'SUSE Linux Enterprise Server 15' database could not be fetched.
2023/08/25 21:16:20 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'SUSE Linux Enterprise Desktop 15' database update.
2023/08/25 21:46:30 wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'SUSE Linux Enterprise Desktop 15' database could not be fetched.
2023/08/25 21:46:30 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'SUSE Linux Enterprise Server 12' database update.
2023/08/25 22:16:40 wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'SUSE Linux Enterprise Server 12' database could not be fetched.
2023/08/25 22:16:40 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'SUSE Linux Enterprise Desktop 12' database update.
2023/08/25 22:21:29 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'SUSE Linux Enterprise Desktop 12' feed finished successfully.
2023/08/25 22:21:29 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'SUSE Linux Enterprise Server 11' database update.
2023/08/25 22:51:39 wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'SUSE Linux Enterprise Server 11' database could not be fetched.
...
2023/08/25 22:58:17 wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.
```

In these _warnings_, you can see that the update of the feed lasts exactly 30 minutes until it shows the `WARNING` (probably due to reaching the established time limit).
In the case of this known problem for slow feed download connections, we have the following issue to fix the problem:
- https://github.com/wazuh/wazuh/issues/18593

On the other hand, to confirm 100% that it is this problem, it would be necessary to have the complete VD log to make sure that the alerts are generated just after having analysed the agents, and that it is the download and update of feeds the reason for the delay.

#### Expected steps:
1. Downloading and updating feeds.
2. Scan start for each agent.
3. At the moment of finishing the scan of an agent, the corresponding alerts should start to appear.

**Comment by MarcelKemp** [comment]
@mauromalara for your specific case, it seems to be related to the following issue:
- https://github.com/wazuh/wazuh/issues/18447

Since it seems that lately the Debian servers are down, causing then the delay of 30 min for each download attempt (finally appearing its respective `warning`).

- https://www.isitdownrightnow.com/debian.org.html
![Screenshot from 2023-08-30 12-34-47](https://github.com/wazuh/wazuh/assets/37207742/840edae8-29b3-4995-8e23-1c9e5ef7833c)

**Comment by mauromalara** [comment]
@MarcelKemp I've downloaded the Debian feeds and used them offline to discard what you mentioned. This happens consistently for all agents in the issue I mentioned.

**Comment by MarcelKemp** [comment]
@mauromalara okay, in that case I need you to share the logs from the manager when testing the agents that have been scanned to verify what is happening, please.

**Comment by mauromalara** [comment]
@MarcelKemp we've found that the delay was because of what you mentioned [here](https://github.com/wazuh/wazuh/issues/18682#issuecomment-1698917701).
