### ISSUE TITLE
[Suggestion] Update Rootcheck and Ruleset with latest OSSEC additions

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh#1876]
## Feature request

**Compatibility**
_both_

**Component involved**
_Syscheck/Rootcheck/Decoders/Rules_

## Description

As we can see on OSSEC's [project changelog](https://github.com/ossec/ossec-hids/blob/master/CHANGELOG), several updates for the Ruleset and Rootcheck have been added. Maybe we can update the rules and scans files with this new additions.

Regards,
Juanjo

**Comment by chemamartinez** [comment]
This is the list of PR from OSSEC candidates to be imported: 1461, 1495, 1496, 1510, 1511, 1521, 1531, 1543, 1547, 1549.

**Comment by chemamartinez** [comment]
This issue is into developing at the branch [update-ruleset-ossec](https://github.com/wazuh/wazuh/tree/update-ruleset-ossec).

## Remaining tasks

- [ ] Check the size of the new `merged.mg` file with the new rootcheck files.
- [ ] Integrate included rules into the Wazuh rules files.
- [ ] Test every rule carefully.
- [ ] Test every policy monitoring check.
- [ ] Ruleset unit tests.
- [ ] Mapping rules with PCI_DSS

**Comment by chemamartinez** [comment]
Hi,

This issue is outdated. It has been working on it in other issues like https://github.com/wazuh/wazuh/issues/2629 as well as in the ruleset repository.

Regards.
