### ISSUE TITLE
agent_control - 'syscheck last started at' Date/Time Not Always Updating

### ISSUE THREAD

**Issue by Justangatang** [wazuh/wazuh#1883]
| Version | Revision | Branch |
| 3.7 | 01  | --- |

Hello,

When running the agent_control binary in 3.7.0, some of my "Syscheck last started  at:" times are not updating correctly, even though the syscheck started and ended on the agents. The syscheck is getting into the DBs, and it's even showing the proper times in the Splunk app. I couldn't find a similar bug write-up in the issues list.

Example 1:
![image](https://user-images.githubusercontent.com/41699624/48504449-649b0c80-e80a-11e8-8e16-e98c13ffac73.png)

Example 2:
![image](https://user-images.githubusercontent.com/41699624/48504485-872d2580-e80a-11e8-8c15-fce8a075e32a.png)

**Comment by bah07** [comment]
For version 3.7 the FIM database has been restructured. These changes include where the data from the latest scans are obtained. 

The problem is `syscheck_control` keeps getting them from the old database.
Many thanks for the feedback. Let's fix this ASAP.

Please, from now use `wazuh-API` to obtain these results.

You can find all the options in:
https://documentation.wazuh.com/current/user-manual/api/reference.html#syscheck

Specifically to get the latest FIM scans:
https://documentation.wazuh.com/current/user-manual/api/reference.html#get-last-syscheck-scan

Regards.
