### ISSUE TITLE
Waiting while holding a lock at FIM

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#18895]
|Wazuh version|Component|CID|Source|
|---|---|---|---|
| 4.6.0 r40600 (dev) | FIM |1567833|#9103|

1. Call to `fim_send_msg` might sleep while holding lock `sync_eps_mutex`:
https://github.com/wazuh/wazuh/blob/f05d708c7f319fc774c6854c9c6b08760a502014/src/syscheckd/src/run_check.c#L112
2. Call to `fim_sync_check_eps` might sleep while holding lock `sync_eps_mutex`:
https://github.com/wazuh/wazuh/blob/f05d708c7f319fc774c6854c9c6b08760a502014/src/syscheckd/src/run_check.c#L114

**Comment by jotacarma90** [comment]
## Conclusion

After analyzing the error displayed by coverity, I have come to the conclusion that this is the expected behavior of the code. The lock it refers to is a control structure to limit the number of events per second among several threads, so a sleep (which will block all the other threads) is necessary as soon as the configured maximum eps limit is detected. This lock is only used in this situation, so it is not dangerous to be blocked.

**Comment by jotacarma90** [comment]
After some more analysis we have decided to create a new issue to improve the event control structure by seconds to stop using a lock containing a sleep.
For the fix we have considered using the limits.c library used in analysisd and the agent bucket.

@vikman90 
For the moment we can mark the coverity error as "known".

**Comment by vikman90** [comment]
As we're seeing that this issue has no impact in FIM, and the fix might do, we're marking the issue as a **false positive** (because we do want threads to wait for another to finish sleeping) and set this issue as an enhancement.
