### ISSUE TITLE
Quickstart install missing support for O.S. without systemd package support, like  Amazon Linux 1 

### ISSUE THREAD

**Issue by tdrauncieal** [wazuh/wazuh#18904]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.6.0-alpha1 | Quickinstall | Install | Amazon Linux 1 (2018.03) |

The following error happened at the installation step ([Quickstart](https://documentation-dev.wazuh.com/v4.6.0-alpha1/quickstart.html)) of `Deployment requirements` in issue #18854, due to missing support for `systemd` package on the OS referred.

```shell
[vagrant@localhost ~]$ sudo bash wazuh-install.sh -a
08/09/2023 13:23:50 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
08/09/2023 13:23:50 INFO: Verbose logging redirected to /var/log/wazuh-install.log
08/09/2023 13:23:51 INFO: --- Dependencies ---
08/09/2023 13:23:51 INFO: Installing systemd.
08/09/2023 13:24:03 ERROR: Cannot install dependency: systemd.
```

**Comment by code-kungfu** [comment]
This problem also exists when using Devuan Linux (Debian, without systemd).
The quick install script makes the assumption the target distro uses systemd.
However, there are many cases where systemd is undesired or outright banned in production due to security concerns and thus this script should be able to install on a non-systemd distribution.

Is this script auto generated and if so, is the script responsible for the generation available in the respository?
