### ISSUE TITLE
Modify Makefile and adapt code to integrate the new OpenSSL 3.0.x library.

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#19058]
## Description

As part of https://github.com/wazuh/wazuh/issues/17295, we need to update our OpenSSL dependency from 1.1.1 to 3.0.x since it has reached its EOL.

This issue aims to apply all the changes necessary to pull the new OpenSSL 3.0.x dependency from the new path (in the Makefile) and make the necessary changes in the code to adapt it to this new version.

**Comment by jr0me** [comment]
### Update

Migrated several uses of `[MD5|SHA1|SHA256|SHA512]_[Init|Update|Final]` functions to the new OpenSSL 3.0 ones.

Branch: https://github.com/wazuh/wazuh/tree/dev-19058-upgrade-to-openssl3

**Comment by jr0me** [comment]
# Update

On https://github.com/wazuh/wazuh/pull/20778 most deprecated functions are replaced. During review a memory leak from these changes was found and fixed. Some unit tests which failed were also fixed.

It was also found that there are some building problems when using EXTERNAL_SRC_ONLY and TEST flags together, see https://github.com/wazuh/wazuh/issues/20919

Currently working on Blowfish cipher changes, Wazuh's usage of the deprecated api (`BF_*` functions) may not accommodate directly to the newer EVP functions.

Functions in `sha1_op.h/c` that use deprecated OpenSSL functions will be done in a separate task, since the changes require further research and understanding. All deprecated functions continue to work as expected in OpenSSL 3.0, so we can safely move forward with the migration and solve those deprecations at a later stage.

**Comment by jr0me** [comment]
### Update

The PR is ready for merging. It was decided to not include the changes to Blowfish since it wasn't backwards compatible and generated connection issues with older versions.
