### ISSUE TITLE
client.keys file not present in Windows agent fresh installation

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#1921]
## Bug report

**OS**
_Windows_

**Wazuh version**
_3.7.0_

**Install type**
_agent_

Bug description
----------------

Unlike Linux systems, a fresh Wazuh agent installation on Windows doesn't include an empty `client.keys` file.

**Comment by chemamartinez** [comment]
We have to take into account to check the permissions when trying to create/write the `client.keys` file. If the MSI is in charge to create the file, there is no problem when creating it because the MSI has to be executed with elevated permissions. But after that, the `manage_agent` tool and `agent-auth.exe` have to be able to write it.
