### ISSUE TITLE
wazuh-remoted ERROR: socket, send fail Error in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#19215]
Description

It has been detected an unexpected ERROR in the footprint release testing https://github.com/wazuh/wazuh/issues/19176:

`wazuh-remoted ERROR: socket: 14, send fail"`

It has appeared only once, requires further investigation, and will be observed to see if it reoccurs in another test.

**Comment by cborla** [comment]
## Socket send fail analysis

The reported error message is generated at 2023/09/22 21:26:33, which is in the vulnerability detector register test overload process.

Simple Log:
`2023/09/22 21:26:33 wazuh-remoted: ERROR: socket: 14, send fail`

Analyzing the manager log, we can see connections and disconnections of the 3 agents every 1 minute, opening and closing sockets for communication.

Section:
```
2023/09/22 21:26:19 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2023/09/22 21:26:19 wazuh-remoted: INFO: (1410): Reading authentication keys file.
2023/09/22 21:26:33 wazuh-authd: INFO: New connection from 172.31.14.237
2023/09/22 21:26:33 wazuh-authd: INFO: Received request for a new agent (EC2AMAZ-L273KKC-74598-126470) from: 172.31.14.237
2023/09/22 21:26:33 wazuh-authd: INFO: Agent key generated for 'EC2AMAZ-L273KKC-74598-126470' (requested by any)
2023/09/22 21:26:33 wazuh-remoted: ERROR: socket: 14, send fail                                         <-- Error message
2023/09/22 21:26:34 wazuh-remoted: WARNING: (1408): Invalid ID 1129 for the source ip: '172.31.14.237' (name 'unknown').
2023/09/22 21:26:39 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2023/09/22 21:26:39 wazuh-remoted: INFO: (1410): Reading authentication keys file.
2023/09/22 21:26:45 wazuh-modulesd:vulnerability-detector: INFO: (5431): Starting vulnerability scan.

```

The same can be confirmed by viewing the [graph](https://camo.githubusercontent.com/3cf0124994da772ee68e799218ae6185f509bfc53a5ecd8967f012b0fa31b087/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343332302d333630306d2f42343332305f6167656e745f63656e746f732f706c6f74732f546573745f7374726573735f42343332305f63656e746f735f6167656e74645f73746174655f4167656e74445f5374617475732e706e67) of any of the connected agents. Part of the test consists of restarting the agents.

Focusing on the section of the code where the message is generated, we can determine that the function that returns the error is the [send](https://man7.org/linux/man-pages/man2/send.2.html
) function:

``` c
sent_bytes = send(socket, (const void *)data, peeked_bytes, MSG_DONTWAIT);
```

Section code:
``` c

        ssize_t peeked_bytes = bqueue_peek(buffer->buffers[socket].bqueue, data, send_chunk, BQUEUE_NOFLAG);
        if (peeked_bytes > 0) {
            // Asynchronous sending
            sent_bytes = send(socket, (const void *)data, peeked_bytes, MSG_DONTWAIT);
        }

        if (sent_bytes > 0) {
            bqueue_drop(buffer->buffers[socket].bqueue, sent_bytes);
        } else if (sent_bytes < 0) {
            switch (errno) {
            case EAGAIN:
    #if EAGAIN != EWOULDBLOCK
            case EWOULDBLOCK:
    #endif
                break;
            default:
                merror("socket: %d, send fail", socket);
            }
        }
```

The send function can return a positive number or a negative number. The positive number represents the number of bytes it was able to send, and if it returns a negative number it represents an error code:

Possible error codes:
  - -1: This is the most common value returned by send in case of an error. It can indicate a variety of issues, such as connectivity problems, network errors, socket problems, buffer full conditions, and more.
  - -EAGAIN or -EWOULDBLOCK: These values indicate that the non-blocking send operation couldn't be performed because the socket wasn't ready to send data at that moment. These errors typically occur in non-blocking send operations when the socket doesn't have space to accept more data or isn't in a suitable state for sending at that moment.
  - -ECONNRESET or -EPIPE: These values indicate that the socket connection has been reset or unexpectedly closed before or during the send attempt. This can happen when the other end of the connection has abruptly closed the socket.
    
Clearly the error is caused by an unavailability of the operating system at that time or because the agent was restarting when the manager tries to send the message. 
Unfortunately with the current code it is not possible to identify what kind of error happened, which did not allow the message to be sent, but it can be observed that the manager does not confirm the extraction of the message, so it will retry to send it in the future if the connection to that socket is still active.

In my opinion this issue is not relevant, the error can occur and is contemplated, and it can also be considered expected since there were 6879 reconnections of agents throughout the test.

**Comment by vikman90** [comment]
@cborla Thanks for the report! Let's change the log to print the error code next time.
