### ISSUE TITLE
High memory usage in wazuh-modulesd

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#19222]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.3 RC1 | wazuh-modulesd | Manager | Packages | CentOS 7 |

A significant increase has been found in the memory usage of wazuh-modulesd compared to 4.5.2, going from a maximum of 275MB to 600MB, although the memory usage seems stable, it is necessary to justify this increase

Issue: https://github.com/wazuh/wazuh/issues/19179

- 4.5.3 RC 1

![image](https://github.com/wazuh/wazuh/assets/14913942/042c47e3-655d-43ab-8ee9-1807744aae0b)

- 4.5.2 RC 1

![image](https://github.com/wazuh/wazuh/assets/14913942/34b523dc-0267-4e84-b6f2-c28b2b3fc3c8)

It is also necessary to check the increment of wazuh-modulesd in the VMS plot, which shows an increase in memory without stabilizing

![image](https://github.com/wazuh/wazuh/assets/14913942/db6283ad-095c-4223-90bf-fa0291010cb0)

**Comment by MarcelKemp** [comment]
## Research

About the increase of memory used in the _wazuh-modules_ daemon, this is to be expected, because the new OSes supported by **_Vulnerability Detector_** have been added to the stress test configuration.
- https://github.com/wazuh/wazuh-jenkins/pull/5601

So when downloading, parsing and inserting any of these new feeds (`SUSE`, `Amazon Linux`, `Arch Linux`...), the memory is increased. 
> This increase did not appear in the previous _stage_ of `4.5.3` because of the following problem: 
> - https://github.com/wazuh/wazuh-jenkins/issues/5628#issuecomment-1714067809

### Evidence

The two plots are shown below. One using VD and the other without VD:

| https://github.com/wazuh/wazuh/issues/19190 | https://github.com/wazuh/wazuh/issues/19187 |
|-|-|
| ![image](https://github.com/wazuh/wazuh/assets/37207742/b4387917-1c92-4a54-8458-45412064dd6a) | ![image](https://github.com/wazuh/wazuh/assets/37207742/10e3b682-8019-4435-9e63-06998efde844) |

> - https://github.com/wazuh/wazuh/issues/19190
> - https://github.com/wazuh/wazuh/issues/19187

**Comment by rauldpm** [comment]
Maybe related: https://github.com/wazuh/wazuh/issues/19221

**Comment by vikman90** [comment]
Per our chat, the change that introduces this difference is:

- https://github.com/wazuh/wazuh/issues/7171
- https://github.com/wazuh/wazuh/pull/9962

Therefore, this is not a 4.5.3 stopper. Let's mark it as a high-priority bug.

**Comment by verdx** [comment]
# Update

Checkint Footprint test for Vulnerability-Detector on Release Candidate 2 of release 4.5.3, the memory usage of `wazuh-modulesd` has been decreased , almost to the point of `4.5.2`.

- 4.5.3 RC2:
  ![68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343336342d333630306d2f42343336345f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d6](https://github.com/wazuh/wazuh/assets/61122643/154169de-303f-4fbf-83f1-9acb4caed116)

- 4.5.3 RC1:
  ![68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343331392d333630306d2f42343331395f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d6](https://github.com/wazuh/wazuh/assets/61122643/d4725e19-d195-4743-be25-768f184e599d)

**Comment by pro-akim** [comment]
In https://github.com/wazuh/wazuh/issues/19361 seems solved in rc2 but still there are some big peaks at the initial stage of the test

**Comment by MarcelKemp** [comment]
The first memory spike seems to be met when downloading, parsing and inserting the vulnerabilities from the SUSE feed for the first time.
- Related issue: https://github.com/wazuh/wazuh/issues/19127

After that, it seems to stabilize because it does not seem to update the feeds again.

**Comment by havidarou** [comment]
This will not be necessary considering the vulnerability detector module refactor.
