### ISSUE TITLE
Azure Storage Integration Alerts

### ISSUE THREAD

**Issue by thony4uu** [wazuh/wazuh#19282]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.6.0-Beta1	|Server|Amazon Machine Images (AMI)|Amazon Machine Images (AMI)|Amazon Machine Images (AMI)||

### Description

During E2E testing on #19156, integration with Microsoft Azure Storage failed to generate alerts either in alerts. logs or on the Wazuh dashboard when the configuration includes the path variable following the example given in the documentation. 
There is no clarity on what to specify for the path variable. I initially used what was defined in the example in the documentation, but it was not working. I tried using the path of the storage blob, but it was not working. After several hours of troubleshooting, I removed the path variable from the configuration, and everything worked perfectly.  There was no error from the ossec.log file.

**Comment by javiersanchz** [comment]
## Update 

We have been investigating this. We reviewed the information regarding the reported issue in the E2E, and we searched for the problem in the Wazuh Documentation.

It was found that this issue has already been resolved at https://github.com/wazuh/wazuh-documentation/pull/6835 where the `<path>` variable is removed among the changes

![image](https://github.com/wazuh/wazuh/assets/96108386/010c33e6-bd2c-4471-b0e0-834ebfb88689)

**- Therefore, this issue is considered closed**

**Comment by GGP1** [comment]
## Review

The conclusion is correct, the error was caused by the configuration documentation showing a container name that was outdated.

The issue where it was fixed https://github.com/wazuh/wazuh-documentation/issues/6563 was created by the same user, the same day so it's likely to be a duplicate.
