### ISSUE TITLE
The wazuh-modulesd daemon increased its amount of disk read

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#19383]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.3-rc2 | wazuh-modulesd | Manager | - | - |

## Description

Compared with the [last test session](https://github.com/wazuh/wazuh/issues/19186) (4.5.3-rc1) `wazuh-modulesd` seems to increase its amount of disk read during the testing session.

### Evidence

**`4.5.3-rc1` (last test session)**

<img src="https://camo.githubusercontent.com/b593203f6f5f984946e776cb348a9f0fb6f05b4fe4094845c8af9a8a3f5f1fbf/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343333312d333630306d2f42343333315f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343333315f6d616e616765722d7072652d72656c656173655f4469736b5f526561642e706e67">

**`4.5.3-rc2` (current test session)**

<img src="https://camo.githubusercontent.com/0299b63e7385f075feb78f111af0e2acdd05aec672af0a72e5e5257b2c816310/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343337372d333630306d2f42343337375f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343337375f6d616e616765722d7072652d72656c656173655f4469736b5f526561642e706e67">

- The configuration hasn’t changed since the last testing session.
- [manager_logs_and_config.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4377-3600m/B4377_manager_centos/logs/ossec_Test_stress_B4377_manager_2023-10-01.zip)
- CSVs:
  - [monitor-manager-Test_stress_B4377_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4377-3600m/B4377_manager_centos/data/monitor-manager-Test_stress_B4377_manager-pre-release.csv)
  - [Test_stress_B4377_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4377-3600m/B4377_manager_centos/data/Test_stress_B4377_manager_analysisd_events.csv)
  - [Test_stress_B4377_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4377-3600m/B4377_manager_centos/data/Test_stress_B4377_manager_analysisd_state.csv)
  - [Test_stress_B4377_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4377-3600m/B4377_manager_centos/data/Test_stress_B4377_manager_remoted_state.csv)

**Comment by mauromalara** [comment]
## Update

Also, the percentage of disk used by `wazuh-modulesd` seems to be increased in CentOS and Ubuntu agents.

### CentOS

**Before**

<img src="https://camo.githubusercontent.com/0f3e59188ad55bc8d0c26175136e42472a4679c36d8c7488b974d1ee75c41124/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343333312d333630306d2f42343333315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343333315f63656e746f732d7072652d72656c656173655f4469736b2e706e67">

**After**

<img src="https://camo.githubusercontent.com/e1c5f80b2d8e9a87427b85e58a49a109f3a5bc763d1831c044e06a1459d6b297/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343337372d333630306d2f42343337375f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343337375f63656e746f732d7072652d72656c656173655f4469736b2e706e67">

### Ubuntu


**Before**

<img src="https://camo.githubusercontent.com/742d54cfff83d72960d40e659e5932cbc67c5e47ffabc4f3fbdd6edf6bda6687/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343333312d333630306d2f42343333315f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343333315f7562756e74752d7072652d72656c656173655f4469736b2e706e67">

**After**

<img src="https://camo.githubusercontent.com/f8afc00281024dff1654d5d8fdc56ed44eda276fdd633492e9033d3feeb17321/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343337372d333630306d2f42343337375f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343337375f7562756e74752d7072652d72656c656173655f4469736b2e706e67">

**Comment by LucioDonda** [comment]
Based on the analysis made in the last hours we can conclude that:
* There's definitely an increase of disk read of **modulesd** (approx 57% more on the full load peak, and near test ending a 47% more).
* Comparing the logs of RC1 vs RC2 we could see that all the `CVE database could not be updated.` messages didn't appear anymore. This is a consequence of #19217 being merged.
* After the fix (_Vulnerability Detector fetching the SLES 15 feed_) an increase in the disk read graph of the test is not strange or a bug-related behavior.

Besides that, and comparing this test with the previous one ( https://github.com/wazuh/wazuh/issues/18664 )
**Disk read 4.5.2:**

![4 5 2-RC1](https://github.com/wazuh/wazuh/assets/95248059/d5d17b2d-8dcb-4b3b-a884-74542d845483)

This increase is much more important and we assume that is due to [Vulnerability Detector now fetches the SUSE feeds in Gzip compressed format](https://github.com/wazuh/wazuh/pull/18783). Maybe that could shed some light on what's happening in this one. 
c.c. : @cborla @nbertoldo

**Comment by MarcelKemp** [comment]
### Manager
The [analysis made](https://github.com/wazuh/wazuh/issues/19383#issuecomment-1745679630) according to the increase in disk reading, I think it is accurate, because before it did not complete the reading of the `SLES 15` and `SLED 15` feeds (which occupy _323 MB_ and _209 MB_ respectively), and now when updating the feeds, it performs the complete reading of both.

### Agents
According to the [disk usage of the agents](https://github.com/wazuh/wazuh/issues/19383#issuecomment-1744084519), it seems to be due to the synchronization between the agent and the manager of the SCA results in the database. 

So it doesn't seem to be an increase, but rather, that it is divided between the peaks that appear in the graphs, and in the end it synchronizes the same amount of events.

This can be corroborated with this other case, where we see the same pattern but in reverse (i.e. in `RC1` there is a higher peak than in `RC2`):
- https://github.com/wazuh/wazuh/issues/19182
  - CentOS: 
![image](https://github.com/wazuh/wazuh/assets/37207742/ae32cff8-674a-4579-bb3c-834d6fea4b90)

- https://github.com/wazuh/wazuh/issues/19362
  - CentOS: 
![image](https://github.com/wazuh/wazuh/assets/37207742/c097179f-23bc-4e48-8a9e-1bd0d8892831)

### Conclusion
So in both cases, the results would be expected.
