### ISSUE TITLE
Increased memory usage in wazuh-analysisd

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#19386]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.3 RC2 | wazuh-analysisd | Manager | Packages | CentOS 7 |

An increase has been found in the memory usage of wazuh-analysisd compared to 4.5.3 RC1, going from a maximum of 100MB to 120MB, although the memory usage seems stable, it is necessary to justify this increase

Issue: https://github.com/wazuh/wazuh/issues/19352

- 4.5.3 RC 2

![image](https://github.com/wazuh/wazuh/assets/80041853/63569271-03f1-4d26-88ff-749f84bf125d)

- 4.5.3 RC 1
![image](https://github.com/wazuh/wazuh/assets/80041853/6921a937-48cb-40b4-b1cf-a33ca803b0e1)

- 4.5.2 RC1

![image](https://github.com/wazuh/wazuh/assets/80041853/eaefc0bc-4a06-48e6-ac80-5c647dca4988)

We can also see an increase in the agents.

**Comment by nmkoremblum** [comment]
Despite increasing the RSS memory, no degradation in performance or general functionality of Wazuh has been observed. After analyzing the code changes, the only potential factor linked to a memory increase in the configuration load is the modifications introduced in issue #19217. However, these changes seem to be related to `vulnerability-detector`, which is disabled in this test. We have been unable to identify a definitive cause that justifies the memory increase.

**Comment by mjcr99** [comment]
Hi team,

We have been reviewing other tests metrics in order to find if this behavior is present in similar situations. Specifically, we have compared the following tests:

ALL-EXCEPT-LOGCOLLECTOR
RC1 https://github.com/wazuh/wazuh/issues/19209
RC2 https://github.com/wazuh/wazuh/issues/19358

ALL-EXCEPT-VULN-DECT
RC1 https://github.com/wazuh/wazuh/issues/19187
RC2 https://github.com/wazuh/wazuh/issues/19371

ALL-EXCEPT-SYSCHECK
RC1 https://github.com/wazuh/wazuh/issues/19287
RC2 https://github.com/wazuh/wazuh/issues/19368

None of them show this increase of RSS in analysisd and this behavior should be observable in these cases if it would be a persistent problem. 

It's worth mentioning, that the increased RSS is about the initial point, not in the test run itself, since in RC1 the metric starts at around 30k and reaches +100k, and in RC2 starts at around 40K and reaches 120K which shows the memory consumption during the test run is actually the same.

On the other side, the merged PR's between these tests in wazuh/wazuh are just https://github.com/wazuh/wazuh/pull/19217
and https://github.com/wazuh/wazuh/pull/19259. These PR's should not have any effects in these reported tests.

**Comment by nmkoremblum** [comment]
After analyzing and consulting other teams, the code changes introduced in issue #19217, specifically related to vulnerability-detector (VD), seem unlikely to be the cause, especially since VD is disabled in our test scenario.

The comparison of various tests indicates that the reported memory increase in analysisd is unique to this scenario (of RC2). It is important to notice that this increment is observed in the starting memory point and not during the stress test itself.

Regarding the PRs, only #19217 and #19259 were merged between these tests, and #19217 is the only one relevant to XML parsing in VD. However, since VD is inactive, its impact on other components is limited.

Upon consulting with @MarcelKemp, the XML parsing changes primarily affect VD and should not directly impact other modules, including analysisd. The increased memory usage in analysisd during the stress test may be related to enhanced alert generation, possibly due to improved agent connections or increased event processing.

While the specific cause remains unclear, the stress test's behavior suggests a potential casual relationship. We recommend further monitoring and analysis in future tests to assess the memory behavior consistently.

**Comment by ncvicchi** [comment]
This seems to be generated by something inherent to the test itself. By rescalating and overlapping both RC1 & RC2 graphics, it is clear that the extra memory consumptions occurs at the very beginning of the test, not at the stress state:

![image](https://github.com/wazuh/wazuh/assets/69121070/b561e7f4-d825-43c6-88c8-4393bda07788)

This offset is constant over the whole test, but it becomes more evident with the image overlapping.

While I agree with @nmkoremblum on recommending further monitoring and analysis, I suggest that it should be focused on process start, not the process stress, since there are no differences on the graphic behavior, but just on its offset.

**Comment by JcabreraC** [comment]
@vicferpoy initiates a brief test to verify any memory spikes before proceeding with the stress test.

**Comment by Rebits** [comment]
Launched stress tests for 10 minutes: https://ci.wazuh.info/job/Test_stress/4416/console

**Comment by JcabreraC** [comment]
A 15-minute stress test was requested to verify the allocated resources before the actual test, as the output during it appeared as expected.

RSS plot:
![image](https://github.com/wazuh/wazuh/assets/39765143/8fcc27c3-f429-4393-aa98-20fb46cd2a5a)


As we can see in this test, the memory allocated before the stress test is 20,000, rising during the test to just over 100,000, as expected.

With this result, we consider the issue concluded, and it is deemed that there is no problem.
