### ISSUE TITLE
No alert from syslog input

### ISSUE THREAD

**Issue by dnexsoc** [wazuh/wazuh#1938]
Hi,

Remote syslog enabled with the following config

`<remote>`
 `<connection>syslog</connection>`
  `<port>514</port>`
 `<protocol>udp</protocol>`
  `<allowed-ips>0.0.0.0/0</allowed-ips>`
`</remote>`

then, 

`<logall>yes</logall>` enabled

and,

log alert level changed to 1. `<log_alert_level>1</log_alert_level>`.

When I run  tail  `-f /var/ossec/logs/archives/archives.log | grep "syslog" `, I can see all logs from my remote device (Cylance Console).

But no alert in Wazuh dashboard. Any ideas?

Thanks in advance!

**Comment by TJOSERAFAEL** [comment]
Hi @dnexsoc ,

In order to have Wazuh alerts from syslog devices, you need to write your own rules and decoders. Here you have an example on how to do this: https://documentation.wazuh.com/current/user-manual/ruleset/custom.html

If you need help, you can post your syslog logs and we can help you writing rules for those events.

Best regards.
