### ISSUE TITLE
Active vulnerabilities are not shown correctly

### ISSUE THREAD

**Issue by micsinyei** [wazuh/wazuh#19417]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2 | Vulnerability detector | AWS AMI | AWS AMI | Amazon linux |

The issue is in the vulnerability window, Wazuh also shows solved vulnerabilities. Basically, there is no way to know how many active vulnerabilities you have. Therefore this module not helping at all.

![image](https://github.com/wazuh/wazuh/assets/19818513/9e28df4a-a380-4bd0-b07c-d6f59a688c69)
![image](https://github.com/wazuh/wazuh/assets/19818513/f1a06418-79be-414a-a8d2-7e9e10e27cd5)

**Comment by MiguelazoDS** [comment]
Hi @micsinyei, 

You should be able to use the `data.vulnerability.status` to filter out the vulnerabilities you don't want to see. If you set the value of that field to "Active", only active vulnerabilities should be visible. 

You can also verify that by querying the agent database since it only stores active vulnerabilities for a particular agent. 

`sqlite3 /var/ossec/queue/db/<agent_id>.db 'select count(*) from vuln_cves'`

**Comment by micsinyei** [comment]
Dear @MiguelazoDS,

Maybe I did not explain the problem well. When you use the `data.vulnerability.status` filter, it gives the vim active vulnerabilities because the alerts were fired some time ago, but the filter could not consider if they were solved or not. The example I gave shows this. The vim is shown as an active vulnerability when in reality it was solved.

The user does not have an option to know which vulnerabilities have not been solved, therefore active/currently affecting the system. When the vulnerability is solved it just creates a new alert with solved status but leaves the active vulnerability alert. So when you filter the active status you will get vulnerabilities/alerts that were solved. You cannot see the state of the system.

For example, if you want to create a dashboard/report about your state/active vulnerabilities, you cannot make one or it will be false, since the filtering option does not have an option like this.

**Comment by MiguelazoDS** [comment]
Mmm I get it, the agent database in the manager has the current state of the vulnerabilities. Currently, the team is refactoring the module and we'll take into account this behaviour. 
https://github.com/wazuh/wazuh/issues/14153
https://github.com/wazuh/wazuh-dashboard-plugins/issues/5763

**Comment by Dwordcito** [comment]
We hope we have helped you, your collaboration with the community is very important, if you have another question/problem we hope for a new issue!

As for your concern, we will attack it in the epic that happened to you.

**Comment by aw11** [comment]
I'm exploring Wazuh for the first time and noticed this behavior as well. With the thread being a year old, I feel like it's worth resurrecting because the issue essentially renders Vulnerability Detection useless for finding active issues (without unnecessarily complicated queries like "active not solved"

I'm also a bit confused by the verbiage, and don't see an explanation documented anywhere: does "Solved" mean "The developers have fixed the issue, there is a fix ready to be applied to this device" (which is actionable), or "The developers have fixed the issue and the vulnerability has been mitigated on this device because the fix has been applied" (which is not actionable)?
