### ISSUE TITLE
Vulnerability Detector should be fully tested in Alpine Linux 3.18.4

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh#19416]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2| Vulnerability Detector | Agent | Packages| Alpine Linux 3.18.4 |

During https://github.com/wazuh/wazuh/issues/17680 issue tests, it was impossible to determine if Vulnerability Detector works as expected because of Syscollector is not working properly ([issue 
 19415](https://github.com/wazuh/wazuh/issues/19415) ).

Once Syscollector is fixed, Vulnerability Detector should be tested.

**Comment by Dwordcito** [comment]
Blocked by https://github.com/wazuh/wazuh/issues/19415

**Comment by MarcelKemp** [comment]
I can tell in advance that VD does not work on _Alpine Linux_, because it is not officially supported.

To support it, research and development would need to be done, taking into account the following repository where the fixed packages seem to be available for each version:
- https://secdb.alpinelinux.org/

**Comment by ncvicchi** [comment]
@MarcelKemp, should these issues not be created for this situation for any OS Check? Currently, we are making a "go/no go" approach. If functionality is not achieved, then we raise an issue. We can make the distinction to verify if it is in the supported list (currently ignored on purpose) to avoid generating this kind of issues.
