### ISSUE TITLE
Release 4.6.0 - RC 1 - E2E UX tests - RBAC

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#19469]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.6.0-rc1/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the CICD team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the CICD team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing/publication` objective and `Very high` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/framework team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Oct, 10 and notify the @wazuh/framework team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/framework team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Oct, 11 (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Oct, 12.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Step by step](https://documentation-dev.wazuh.com/v4.6.0-rc1/installation-guide/wazuh-indexer/step-by-step.html) | Single node | Alma Linux 8 x86_64 |
| Server | [Step by step](https://documentation-dev.wazuh.com/v4.6.0-rc1/installation-guide/wazuh-server/step-by-step.html) | Multi node | Alma Linux 8 x86_64 |
| Dashboard | [Step by step](https://documentation-dev.wazuh.com/v4.6.0-rc1/installation-guide/wazuh-dashboard/step-by-step.html) | - | Alma Linux 8 x86_64 |
| Agent | [Wazuh WUI one-liner deploy using IP](https://documentation-dev.wazuh.com/v4.6.0-rc1/_images/deploy-new-agent-from-ui1.png) | - | Alma Linux 8 x86_64 |

## Test description

Follow and complete the documentation steps and the examples, ensuring the access is adequate based on each requirement:

https://documentation-dev.wazuh.com/v4.6.0-rc1/user-manual/user-administration/rbac.html?highlight=RBAC

## Known issues

There are no known issues.

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below, removing current examples:

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟢 | Wazuh indexer installation | NA | NA |
| 🟢 | Wazuh server installation | NA | NA |
| 🟢 | Wazuh dashboard installation | NA | NA |
| 🟢 | Wazuh agent installation | NA | NA |
| 🟢 | Creating and setting a Wazuh admin user | NA | NA |
| 🟢 | Creating and setting a Wazuh read-only user | NA | NA |
| 🟢 | Creating an internal user and mapping it to Wazuh | NA | NA |
| 🟢 | Use case: Give a user permissions to read and manage a group of agents | NA | NA |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities? All clear
- Did you face any challenges not covered by the guideline? None
- Suggestions for improvement: None

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [x] @davidjiglesias
- [x] @wazuh/framework

**Comment by SamsonIdowu** [comment]
## Infrastucture:
Wazuh dashboard - 192.168.186.90
Wazuh indexer - 192.168.186.91
Wazuh server 1- 192.168.186.92
Wazuh server 2 - 192.168.186.93
Wazuh agent - 192.168.186.95

## OS Verification

<details>
<summary>Wazuh indexer:</summary>
<pre>
[samson@wazuh-indexer ~]$ cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.8 (Sapphire Caracal)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.8 (Sapphire Caracal)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.8"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
</pre>
</details>

<details>
<summary>Wazuh server 1:</summary>
<pre>
[samson@wazuh-server1 ~]$  cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.8 (Sapphire Caracal)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.8 (Sapphire Caracal)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.8"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
</pre>
</details>

<details>
<summary>Wazuh server 2:</summary>
<pre>
[samson@wazuh-server2 ~]$  cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.8 (Sapphire Caracal)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.8 (Sapphire Caracal)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.8"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
</pre>
</details>

<details>
<summary>Wazuh dashboard:</summary>
<pre>
[samson@wazuh-dashboard ~]$ cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.8 (Sapphire Caracal)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.8 (Sapphire Caracal)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.8"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
</pre>
</details>

<details>
<summary>Wazuh agent:</summary>
<pre>
[samson@almalinux-agent ~]$ cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.8 (Sapphire Caracal)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.8 (Sapphire Caracal)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.8"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
</pre>
</details>


## Wazuh components installation

<details>
<summary>Wazuh indexer:</summary>
<pre>
[samson@wazuh-indexer ~]$ curl -sO https://packages-dev.wazuh.com/4.6/wazuh-certs-tool.sh
[samson@wazuh-indexer ~]$ curl -sO https://packages-dev.wazuh.com/4.6/config.yml
[samson@wazuh-indexer ~]$ nano ./config.yml
[samson@wazuh-indexer ~]$ bash ./wazuh-certs-tool.sh -A
09/10/2023 14:07:37 INFO: Admin certificates created.
09/10/2023 14:07:38 INFO: Wazuh indexer certificates created.
09/10/2023 14:07:38 INFO: Wazuh server certificates created.
09/10/2023 14:07:38 INFO: Wazuh dashboard certificates created.
[samson@wazuh-indexer ~]$ tar -cvf ./wazuh-certificates.tar -C ./wazuh-certificates/ .
tificates./
./root-ca.key
./root-ca.pem
./admin-key.pem
./admin.pem
./node-1-key.pem
./node-1.pem
./wazuh-1-key.pem
./wazuh-1.pem
./wazuh-2-key.pem
./wazuh-2.pem
./dashboard-key.pem
./dashboard.pem
[samson@wazuh-indexer ~]$ scp ./wazuh-certificates.tar samson@192.168.186.90:/home/samson/
The authenticity of host '192.168.186.90 (192.168.186.90)' can't be established.
ECDSA key fingerprint is SHA256:baLo3y96MKGPS7EY0+mkcfFLcfzkRCZsIN31on8JywY.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '192.168.186.90' (ECDSA) to the list of known hosts.
samson@192.168.186.90's password:
wazuh-certificates.tar                                                                        100%   30KB   6.2MB/s   00:00
[samson@wazuh-indexer ~]$ scp ./wazuh-certificates.tar samson@192.168.186.92:/home/samson/
The authenticity of host '192.168.186.92 (192.168.186.92)' can't be established.
ECDSA key fingerprint is SHA256:baLo3y96MKGPS7EY0+mkcfFLcfzkRCZsIN31on8JywY.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '192.168.186.92' (ECDSA) to the list of known hosts.
samson@192.168.186.92's password:
wazuh-certificates.tar                                                                        100%   30KB   5.9MB/s   00:00
[samson@wazuh-indexer ~]$ scp ./wazuh-certificates.tar samson@192.168.186.93:/home/samson/
The authenticity of host '192.168.186.93 (192.168.186.93)' can't be established.
ECDSA key fingerprint is SHA256:baLo3y96MKGPS7EY0+mkcfFLcfzkRCZsIN31on8JywY.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '192.168.186.93' (ECDSA) to the list of known hosts.
samson@192.168.186.93's password:
wazuh-certificates.tar                                                                        100%   30KB   6.3MB/s   00:00
[samson@wazuh-indexer ~]$ yum install coreutils
Error: This command has to be run with superuser privileges (under the root user on most systems).
[samson@wazuh-indexer ~]$ clear
[samson@wazuh-indexer ~]$ sudo su
[sudo] password for samson:
[root@wazuh-indexer samson]# yum install -y coreutils
Last metadata expiration check: 1:32:47 ago on Mon 09 Oct 2023 12:43:11 PM MSK.
Package coreutils-8.30-15.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[root@wazuh-indexer samson]# rpm --import https://packages.wazuh.com/key/GPG-KEY-WAZUH
[root@wazuh-indexer samson]# echo -e '[wazuh]\ngpgcheck=1\ngpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH\nenabled=1\nname=EL-$releasever - Wazuh\nbaseurl=https://packages.wazuh.com/4.x/yum/\nprotect=1' | tee /etc/yum.repos.d/wazuh.repo
[wazuh]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=EL-$releasever - Wazuh
baseurl=https://packages.wazuh.com/4.x/yum/
protect=1
[root@wazuh-indexer samson]# yum -y install wazuh-indexer
EL-8 - Wazuh                                                                                     13 MB/s |  19 MB     00:01
Last metadata expiration check: 0:00:12 ago on Mon 09 Oct 2023 02:16:40 PM MSK.
Dependencies resolved.
================================================================================================================================
 Package                            Architecture                Version                        Repository                  Size
================================================================================================================================
Installing:
 wazuh-indexer                      x86_64                      4.5.2-1                        wazuh                      675 M

Transaction Summary
================================================================================================================================
Install  1 Package

Total download size: 675 M
Installed size: 931 M
Downloading Packages:
wazuh-indexer-4.5.2-1.x86_64.rpm                                                                 32 MB/s | 675 MB     00:21
--------------------------------------------------------------------------------------------------------------------------------
Total                                                                                            32 MB/s | 675 MB     00:21
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                        1/1
  Running scriptlet: wazuh-indexer-4.5.2-1.x86_64                                                                           1/1
  Installing       : wazuh-indexer-4.5.2-1.x86_64                                                                           1/1
  Running scriptlet: wazuh-indexer-4.5.2-1.x86_64                                                                           1/1
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore

  Verifying        : wazuh-indexer-4.5.2-1.x86_64                                                                           1/1

Installed:
  wazuh-indexer-4.5.2-1.x86_64

Complete!
[root@wazuh-indexer samson]# nano /etc/wazuh-indexer/opensearch.yml
[root@wazuh-indexer samson]# NODE_NAME=node-1
[root@wazuh-indexer samson]# mkdir /etc/wazuh-indexer/certs
ar -xf ./wazuh-certificates.tar -C /etc/wazuh-indexer/certs/ ./$NODE_NAME.pem ./$NODE_NAME-key.pem ./admin.pem ./admin-key.pem ./root-ca.pem
mv -n /etc/wazuh-indexer/certs/$NODE_NAME.pem /etc/wazuh-indexer/certs/indexer.pem
mv -n /etc/wazuh-indexer/certs/$NODE_NAME-key.pem /etc/wazuh-indexer/certs/indexer-key.pem
chmod 500 /etc/wazuh-indexer/certs
chmod 400 /etc/wazuh-indexer/certs/*
chown -R wazuh-indexer:wazuh-indexer /etc/wazuh-indexer/certs[root@wazuh-indexer samson]# tar -xf ./wazuh-certificates.tar -C /e ./admin.pem ./admin-key.pem ./root-ca.pem/$NODE_NAME-key.pem
[root@wazuh-indexer samson]# mv -n /etc/wazuh-indexer/certs/$NODE_NAME.pem /etc/wazuh-indexer/certs/indexer.pem
[root@wazuh-indexer samson]# mv -n /etc/wazuh-indexer/certs/$NODE_NAME-key.pem /etc/wazuh-indexer/certs/indexer-key.pem
[root@wazuh-indexer samson]# chmod 500 /etc/wazuh-indexer/certs
[root@wazuh-indexer samson]# chmod 400 /etc/wazuh-indexer/certs/*
[root@wazuh-indexer samson]# chown -R wazuh-indexer:wazuh-indexer /etc/wazuh-indexer/certs
[root@wazuh-indexer samson]# systemctl daemon-reload
l enable wazuh-indexer
systemctl start wazuh-indexer[root@wazuh-indexer samson]# systemctl enable wazuh-indexer
Synchronizing state of wazuh-indexer.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable wazuh-indexer
Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-indexer.service → /usr/lib/systemd/system/wazuh-indexer.service.
[root@wazuh-indexer samson]# systemctl start wazuh-indexer
[root@wazuh-indexer samson]# /usr/share/wazuh-indexer/bin/indexer-security-init.sh
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
Security Admin v7
Will connect to 192.168.186.91:9200 ... done
Connected as "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
OpenSearch Version: 2.6.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Clustername: wazuh-cluster
Clusterstate: GREEN
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index does not exists, attempt to create it ... done (0-all replicas)
Populate config from /etc/wazuh-indexer/opensearch-security/
Will update '/config' with /etc/wazuh-indexer/opensearch-security/config.yml
   SUCC: Configuration for 'config' created or updated
Will update '/roles' with /etc/wazuh-indexer/opensearch-security/roles.yml
   SUCC: Configuration for 'roles' created or updated
Will update '/rolesmapping' with /etc/wazuh-indexer/opensearch-security/roles_mapping.yml
   SUCC: Configuration for 'rolesmapping' created or updated
Will update '/internalusers' with /etc/wazuh-indexer/opensearch-security/internal_users.yml
   SUCC: Configuration for 'internalusers' created or updated
Will update '/actiongroups' with /etc/wazuh-indexer/opensearch-security/action_groups.yml
   SUCC: Configuration for 'actiongroups' created or updated
Will update '/tenants' with /etc/wazuh-indexer/opensearch-security/tenants.yml
   SUCC: Configuration for 'tenants' created or updated
Will update '/nodesdn' with /etc/wazuh-indexer/opensearch-security/nodes_dn.yml
   SUCC: Configuration for 'nodesdn' created or updated
Will update '/whitelist' with /etc/wazuh-indexer/opensearch-security/whitelist.yml
   SUCC: Configuration for 'whitelist' created or updated
Will update '/audit' with /etc/wazuh-indexer/opensearch-security/audit.yml
   SUCC: Configuration for 'audit' created or updated
Will update '/allowlist' with /etc/wazuh-indexer/opensearch-security/allowlist.yml
   SUCC: Configuration for 'allowlist' created or updated
SUCC: Expected 10 config types for node {"updated_config_types":["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"],"updated_config_size":10,"message":null} is 10 (["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"]) due to: null
Done with success
[root@wazuh-indexer samson]# curl -k -u admin:admin https://<WAZUH_INDEXER_IP>:9200
bash: WAZUH_INDEXER_IP: No such file or directory
[root@wazuh-indexer samson]# curl -k -u admin:admin https://192.168.186.91:9200
{
  "name" : "node-1",
  "cluster_name" : "wazuh-cluster",
  "cluster_uuid" : "CcsN4u0cQOi9_beQf5Es8A",
  "version" : {
    "number" : "7.10.2",
    "build_type" : "rpm",
    "build_hash" : "7203a5af21a8a009aece1474446b437a3c674db6",
    "build_date" : "2023-02-24T18:57:04.388618985Z",
    "build_snapshot" : false,
    "lucene_version" : "9.5.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
[root@wazuh-indexer samson]# curl -k -u admin:admin https://192.168.186.91:9200/_cat/nodes?v
ip             heap.percent ram.percent cpu load_1m load_5m load_15m node.role node.roles
 cluster_manager name
192.168.186.91           37          94   7    0.20    0.21     0.15 dimr      cluster_manager,data,ingest,remote_cluster_client *               node-1
[root@wazuh-indexer samson]#
</pre>
</details>


<details>
<summary>Wazuh server 1:</summary>
<pre>


</pre>
</details>


<details>
<summary>Wazuh server 2:</summary>
<pre>


</pre>
</details>


<details>
<summary>Wazuh dashboard:</summary>
<pre>


</pre>
</details>


<details>
<summary>Wazuh agent:</summary>
<pre>


</pre>
</details>

**Comment by davidjiglesias** [comment]
LGTM!
