### ISSUE TITLE
Error message in stress test : `wazuh-db ERROR: at run_worker(): at recv()`

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#19532]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.3-rc3 | Wazuh Manager | Manager| Packages| CentOS |

Running footprint [test Footprint Metrics - SCA (2.5d)](https://github.com/wazuh/wazuh/issues/19489)
 the following error message was observed:

```
wazuh-db ERROR: at run_worker(): at recv(): Connection reset by peer (104)
```

It could be related to: 
- https://github.com/wazuh/wazuh/issues/15665

Further investigation is required.

**Comment by cborla** [comment]
## Error analysis 
The error in question occurs before the start of the test, exactly at the moment when the manager is restarted to start the test.

Single line log:

`2023/10/06 07:25:04 wazuh-db: ERROR: at run_worker(): at recv(): Connection reset by peer (104)`


Section log:

``` log
2023/10/06 07:25:03 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2023/10/06 07:25:03 wazuh-modulesd:syscollector: INFO: Module finished.
2023/10/06 07:25:03 wazuh-monitord: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2023/10/06 07:25:03 wazuh-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2023/10/06 07:25:04 wazuh-remoted: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2023/10/06 07:25:04 wazuh-db: ERROR: at run_worker(): at recv(): Connection reset by peer (104)                               <------------ 
2023/10/06 07:25:04 wazuh-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2023/10/06 07:25:04 wazuh-analysisd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2023/10/06 07:25:04 wazuh-execd: INFO: (1314): Shutdown received. Deleting responses.
2023/10/06 07:25:04 wazuh-execd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2023/10/06 07:25:04 wazuh-db: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...                                <------------
2023/10/06 07:25:05 wazuh-authd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2023/10/06 07:25:05 wazuh-authd: INFO: Exiting...

```
Due to the context I understand that it is a race condition at the moment when wazuh-db detects the `wnotify_get` flag high, indicating that it has events to output, then it calls `OS_RecvSecureTCP` which ends up calling [recv](https://man7.org/linux/man-pages/man2/recv.2.html) from the OS, The recv() is used to receive messages from a socket. 

os_net.c
``` c
/* Receive a message from a stream socket, full message (MSG_WAITALL)
 * Returns size on success.
 * Returns -1 on socket error.
 * Returns 0 on socket disconnected or timeout.
 */
ssize_t os_recv_waitall(int sock, void * buf, size_t size) {
    size_t offset;
    ssize_t recvb;

    for (offset = 0; offset < size; offset += recvb) {
        recvb = recv(sock, buf + offset, size - offset, 0);

        if (recvb <= 0) {
            return recvb;
        }
    }

    return offset;
}
```

Return Value: These calls return the number of bytes received, or `-1` if an error occurred.  In the event of an error, [errno](https://man7.org/linux/man-pages/man3/errno.3.html) is set to indicate the error. In this case the errno is `Connection reset by peer (104)`

“Connection reset by peer” is an error message that typically occurs in network communication when one device (referred to as the “peer”) abruptly terminates the connection with the other device. The term “peer” refers to the remote device or entity with which the connection was established.

Analyzing the API logs at the same date and time that the error message appears in the manager:

```
2023/10/06 07:21:27 INFO: Listening on 0.0.0.0:55000..
2023/10/06 07:25:30 INFO: Listening on 0.0.0.0:55000..
```

According to the analysis performed and the evidences presented, I consider that the ERROR message only shows a fault condition between the wazuh modules, at the moment of shutdown or reset of the application, without generating data loss or alteration in the behavior of the application. It is a possible condition in any environment that uses socket communication.

**Comment by Dwordcito** [comment]
Cosmetic log issue, we move it to future releases.
