### ISSUE TITLE
"wazuh-agentd did not start" on macOs Ventura

### ISSUE THREAD

**Issue by Lganador** [wazuh/wazuh#19587]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.5.2|Wazuh agent|Agent|packages|macOs|

I have an issue on macOs Ventura where it is impossible to start the agent on this computer even with all privileges granted on users and directories, the configuration is already tested on another computer macOs Sonoma wich worked perfectly.

There is no logs produced in the ossec.log file and ossec.conf was tested and validated.

The architecture of this computer is arm64 with M2 Apple Pro processor.

![image](https://github.com/wazuh/wazuh/assets/123946284/1dc2658d-0ce8-4cea-a69c-d0ec0370d151)

**Comment by davidcr01** [comment]
Hello.

I attempted to replicate the issue you encountered, but regrettably, I couldn't reproduce it. To assist you further, I would appreciate it if you could answer a few questions to provide additional context about the problem you're facing.

- Did you follow the [installation steps](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-macos.html)?
- Could you check if the `wazuh-agentd` is running by using the `ps` command or the `/Library/Ossec/bin/wazuh-control status` command? Maybe the service is running and you need to stop this process to not get this error.
- Did you download the ARM package instead of the Intel package?
- Could you share the `ossec.conf` file located at the `/Library/Ossec/etc/` path? Please, be careful about sensitive information.
- Please try the following steps:
  -  Stop the agent
  - Set this `agent.debug=2` in `/Library/Ossec/etc/internal_options.conf`
  - Start the agent
  - Share the logs for `wazuh-agentd `

Hope it helps. Regards, 
David.

**Comment by Lganador** [comment]
Hello.

The issue was resolved by upgrading the agent after installing it.

Thank you.
