### ISSUE TITLE
Increase of Disk read of monitord, syscheckd and wazuhdb

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#19596]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-rc1 | Wazuh Manager | Manager | Packages | CentOS  |

Testing [ALL-EXCEPT-VULNERABILITY-DETECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/19536)

Reviewing Manager Plots it was detected the following increase of disk read of monitord, syscheckd and wazuhdb comparing 4.6.0-rc1 to 4.5.3-rc3. 
Comparing to 4.6.0-beta1, wazuhdb decrease its value

<details><summary> Plots </summary>

4.6.0-rc1
![image](https://github.com/wazuh/wazuh/assets/125690423/18025ccc-655e-4ea1-980d-15582fd48fd9)

4.5.3-rc3
![image](https://github.com/wazuh/wazuh/assets/125690423/15bba0c2-b607-4250-ba26-95f6ef873df8)

4.6.0-beta1
![image](https://github.com/wazuh/wazuh/assets/125690423/e44d836a-fea0-41a8-8316-18984cda98d3)

</details>

Further analysis should be done.

**Comment by DFolchA** [comment]
## Update

After investigating past releases this seems to have been introduced in 4.6.0-alpha1 so it shouldn't be caused by a fix introduced in the later stages:

- Alpha 1: https://github.com/wazuh/wazuh/issues/18921
- Beta 1: https://github.com/wazuh/wazuh/issues/19243
- RC1: https://github.com/wazuh/wazuh/issues/18926

This behavior cannot be appreciated in the tests for the individual modules:

<details><summary> Test links</summary>

- SYSCHECK
  - https://github.com/wazuh/wazuh/issues/19550
  - https://github.com/wazuh/wazuh/issues/19500

- LOGCOLLECTOR
  - https://github.com/wazuh/wazuh/issues/19547
  - https://github.com/wazuh/wazuh/issues/19495
  
- SCA
  - https://github.com/wazuh/wazuh/issues/19549
  - https://github.com/wazuh/wazuh/issues/19489

- ROOTCHECK
  - https://github.com/wazuh/wazuh/issues/19555
  - https://github.com/wazuh/wazuh/issues/19490
</details>

This same increase in the `syscheck` and `wazuh-db` daemons can also be observed in the `ALL`, `ALL-EXCEPT-ROOTCHECK`, `ALL-EXCEPT-SCA`, `ALL-EXCEPT-ACTIVE-RESPONSE`, `ALL-EXCEPT-SYSCOLLECTOR`, and `ALL-EXCEPT-DOCKER,CISCAT,OSQUERY,AZURE,OPEN-SCAP` tests:

<details><summary> Test links</summary>

- https://github.com/wazuh/wazuh/issues/19537
- https://github.com/wazuh/wazuh/issues/19508
- https://github.com/wazuh/wazuh/issues/19556
- https://github.com/wazuh/wazuh/issues/19501
- https://github.com/wazuh/wazuh/issues/19546
- https://github.com/wazuh/wazuh/issues/19493
</details>

But cannot be observed in the tests that exclude `logcollector` and `syscheck`, so we may conclude that an interaction between these two modules causes this behavior.

After investigating the developments made for 4.6.0 that directly affect `wazuh-db`, `syscheck` or `logcollector` we find:

<details><summary> Test links</summary>

- https://github.com/wazuh/wazuh/pull/12745
- https://github.com/wazuh/wazuh/pull/14953
- https://github.com/wazuh/wazuh/pull/14782
- https://github.com/wazuh/wazuh/pull/12745
- https://github.com/wazuh/wazuh/pull/13264
- https://github.com/wazuh/wazuh/pull/15852
- https://github.com/wazuh/wazuh/pull/13264
- https://github.com/wazuh/wazuh/pull/13588
</details>

Additionally, this issue seems to have the same cause as this one: 

- https://github.com/wazuh/wazuh/issues/19583
