### ISSUE TITLE
Wazuh aggregation rules are not working as intended

### ISSUE THREAD

**Issue by MeetET** [wazuh/wazuh#19634]
# Aggregation Rules Not Working with Time Gaps

### Problem

I've encountered an issue with aggregation rules in our system, and I believe they are not working as intended when there is a time gap between logs/alerts.

### Details

- **Rule Setup:** We have a sample rule (as shown below) with a time condition (timeframe="180"), and it should aggregate alerts if they occur within 3 minutes.

```xml
<rule id="3" level="7" frequency="3" timeframe="180">
<if_matched_sid>2</if_matched_sid>
<description>Aggregation Rule</description>
</rule>
```

- **Base Rule:** Here is the sample base rule (just for reference):

```xml
<rule id="2" level="5">
<if_sid>1</if_sid>
<field name="text">Canary</field>
<description>Base Rule</description>
</rule>
```

- **Issue:** When the logs/alerts are instantaneous and occur one after the other, the aggregation rule works as expected. However, when there's a time gap of, for example, 1 minute between logs/alerts, the aggregation rule fails to work.

## Expected Behavior
The aggregation rule should be able to group and trigger alerts within the specified timeframe, even if there's a time gap between the alerts.

### Steps to Reproduce
1. Set up a similar aggregation rule with a timeframe condition.
2. Generate alerts with a time gap of 1 minute or more.
3. Observe that the aggregation rule does not work as expected.

### Additional Information
- Include any error messages or log output that you've encountered.
- Attach any relevant configuration files or code snippets.
- Describe the impact of this issue on your system and any potential workarounds you've tried.

### Expected Resolution
Please investigate this issue and provide a fix or guidance on how to configure the aggregation rules to work correctly with time gaps.

**Comment by vikman90** [comment]
Hi @MeetET,

This behavior brings issue #962 to mind. Can you tell us how many alerts the manager produces between these two events?

The most common cause of this behavior is that the internal event history gets full. There is an 8192-event history:

https://github.com/wazuh/wazuh/blob/dd354194d55f4ad116631cadf5399808a8034613/src/analysisd/config.c#L50

When the manager considers a composite rule (`<if_matched_sid>` or `<if_matched_group>`) it scans that history. If more than the mentioned number of alerts were produced between these two logs, the manager will be unable to compute the composite rule.

This is a known issue. On the other hand, we're working on a new rule engine (#11334) that will not support this type of rules. We propose to use queries to the Indexer to achieve this use case.

Hope it helps.

Best regards.

**Comment by raftergithub** [comment]
Hello @vikman90, 

Hope you're doing well.

I trie what you had suggested i.e., writing queries to the indexer.
I'm able to search and get the respective output. I leveraged devtools

In our case, I'm able to monitor a particular rule id followed by the field that needs aggregation ~ srcip.
This returns me a list of all the values that matched the criteria.

For example in the below screenshot, I'm performing aggregation on ruleid '81618' having same srcip with a minimum count of 2. You can see I get a list of IPs with the count as the output.  
<img width="1427" alt="Screenshot 2023-10-21 at 12 38 57 AM" src="https://github.com/wazuh/wazuh/assets/105353324/2e593957-382f-42e1-95b8-d09590a82ccb">

By setting the size to a value at the starting of my query, I'll be able to pull every record that match the criteria.

**I need more insights on the following:

- Since this is still a search function, How do I create an alert on this usecase?
- Since I'll have many queries, what is the best way to implement this to get detections in real time?**

Look forward for your response.

Regards,
Rafter

**Comment by vikman90** [comment]
Hi @raftergithub, we've not defined how we will provide similar functionality with the new engine. You can try to approach it with monitors and triggers:

- [Monitors](https://opensearch.org/docs/latest/observing-your-data/alerting/monitors)
  - Define a monitor to match your target documents.
- [Triggers](https://opensearch.org/docs/latest/observing-your-data/alerting/triggers)
  - Set a trigger to produce an action when the `COUNT` of documents is above 3.
- [Actions](https://opensearch.org/docs/latest/observing-your-data/alerting/actions)
  - Create an action to export the newly generated alert.

This is not real-time but you can set the query interval to one minute.

Other things we're exploring to reach this are:
- [Anomaly detection](https://opensearch.org/docs/latest/observing-your-data/ad/index)
  - It's not included in the current version of Wazuh Indexer yet.
- [Security Analytics](https://opensearch.org/docs/latest/security-analytics/index)

But, as I mentioned, we haven't defined it yet.

Best regards.
