### ISSUE TITLE
Minor version difference broke the cluster

### ISSUE THREAD

**Issue by zbalkan** [wazuh/wazuh#19870]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2/4.5.3 | Wazuh manager | Manager | N/A | N/A |

This week we encountered an issue with the cluster. An admin accidentally updated packages along with Wazuh, even though Wazuh repo was disabled. The manager was on version 4.5.3 and all of the other components were in 4.5.2. The indexer and dashboard were okay. But the workers were inaccessible for the manager itself.

Sinxe the difference is so minor, I would assume the backward compatibility could tolerate this difference and the cluster would continue working. But it was not the case.

Thisnalso means that using an upgrade, the cluster is broken due to the version difference until all the cluster members are upgraded. That's not a proper cluster management choice.

## Expected

Wazuh cluster members to work if the major patch number is the same, i.e. 4.x.x.

## Observed

Cluster is broken when version number is different.

## Proposed

An official statement on backward compatibility between Wazuh components.

**Comment by vikman90** [comment]
@zbalkan here is the statement: [**Compatibility matrix**](https://documentation.wazuh.com/current/upgrade-guide/compatibility-matrix/index.html).

- The **cluster nodes** must be in the **same version** (including the patch number). Otherwise, they will print a log in _cluster.log_ and reject the connection.
- Same for Wazuh indexer and Wazuh dashboard.
- The **agents** must have either:
  - The same version as the manager, or earlier.
  - The same _major.minor_ numbers and a higher patch number (yes, it's allowed for agents).

The manager does not officially support agents with newer versions. As of 4.6.0, a new option in the manager will allow banning agents with versions higher than the manager. Anyway, the behavior when connecting agents more modern than the manager is not defined.

Hope that helps.

Best regards.

**Comment by zbalkan** [comment]
I know that it is that way. I am trying to tell that it should not be as is from a user perspective.

I see that it is acceptable for you to lose the capability of Wazuh during an upgrade. But if Wazuh is our single point of truth when it comes to security events, it is not acceptable to lose the availability for a regular operation like an upgrade. An upgrade is not an incident and service disruption should not be the approved way of operations.

Anyway, thanks for the information. It's good to know the decision making process.
