### ISSUE TITLE
Changes in resource usage of syscheckd and modulesd observed during stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#19916]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-rc2 | Wazuh component | Agent | Packages/Sources | CentOS, Ubuntu |

In test [Footprint Metrics - SYSCHECK (2.5d)](https://github.com/wazuh/wazuh/issues/19891)
In Ubuntu and CentOS agents:

PSS, RSS, USS: Increase in syscheck, decrease in modulesd
Write_Ops: Decrease in syscheck

PSS
4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19891
![image](https://github.com/wazuh/wazuh/assets/125690423/fbe3d26b-8ae2-44c3-9a43-66081ad9a4b6)
4.5.3-rc3 https://github.com/wazuh/wazuh/issues/19500
![image](https://github.com/wazuh/wazuh/assets/125690423/6b54c7c6-9f62-4858-9313-729ce7d05d4a)

RSS
4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19891
![image](https://github.com/wazuh/wazuh/assets/125690423/a5742d2d-ae0a-4243-a2f5-9ea47c5dfc5b)
4.5.3-rc3 https://github.com/wazuh/wazuh/issues/19500
![image](https://github.com/wazuh/wazuh/assets/125690423/3cfd4792-7c1e-4753-b981-acdc6e9bdd68)

USS
4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19891
![image](https://github.com/wazuh/wazuh/assets/125690423/a84a752e-b9e5-4f11-9c13-4fd3c3286810)
4.5.3-rc3 https://github.com/wazuh/wazuh/issues/19500
![image](https://github.com/wazuh/wazuh/assets/125690423/e9cdd199-a6ac-42d5-95f8-3407eda73ab6)

Write_Ops: https://github.com/wazuh/wazuh/issues/19891
![image](https://github.com/wazuh/wazuh/assets/125690423/84ae53f9-31ae-4c10-a086-2359850cf801)
4.5.3-rc3 https://github.com/wazuh/wazuh/issues/19500
![image](https://github.com/wazuh/wazuh/assets/125690423/e16c0ef9-221f-4207-929c-3a7d2e3b3fa8)

Comparing to 4.6.0-rc1
It is possible to see that syscheck was already increased however, modulesd did not decrease as in rc2

**Comment by nmkoremblum** [comment]
Hi @pro-akim,

What do you mean with:

>  It is possible to see that syscheck was already increased however, modulesd did not decrease as in rc2

**Comment by nmkoremblum** [comment]
After analyzing the issue, we haven't found any reason to suspect there is a bug or a malfunction on the agent. In the case of `modulesd` the memory is reduced on version `4.6.0` which should not bring any trouble as the module is actually disabled, so in fact, it should be 0. In the case of `syscheck` the increase in memory usage might be related to changes in the code, which are difficult to track as there have been many changes since `4.5.x`, we suspect it might be related to the fixes of issue #19074.
The variation in disk usage is probably related to the change in the EPS of `syscheck`, which has been reduced in the configuration from 100 to 50.
