### ISSUE TITLE
RSS increase in Rootcheck at the end of the test

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#19922]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0 | wazuh-agent | Agent | Packages| Windows 2019 |

Related: https://github.com/wazuh/wazuh/issues/19898#issuecomment-1783204665

In the analysis of https://github.com/wazuh/wazuh/issues/19898 it has been detected that the Rootcheck RSS plot ascends in the form of a staircase, in previous versions of 4.6.0 it has been growing since Alpha 1, no issue has been found that reports the change in behavior since 4.5.3

<details><summary>Windows - RSS </summary>

RC2 vs 4.5.3

![image](https://github.com/wazuh/wazuh/assets/14913942/0430185d-cf76-45b3-8994-20f17cc88227)
![image](https://github.com/wazuh/wazuh/assets/14913942/01a33010-c22e-4bf5-a09a-98ab055a3aa3)

RC1: Change linked to https://github.com/wazuh/wazuh/issues/19310 but the plot is not specifically reported

![image](https://github.com/wazuh/wazuh/assets/14913942/e5a5d9a9-27ee-4779-b485-e6d562c2537d)

Beta 1: Not linked to an issue

![image](https://github.com/wazuh/wazuh/assets/14913942/44d62a74-1bc6-47ce-a523-977dfa51772d)

Alpha 1: Not linked to an issue

![image](https://github.com/wazuh/wazuh/assets/14913942/2d21f31e-b52e-4d09-9781-eb69f58af2d1)

</details>

The main change comes in the last stage of the test, where RC2 has an extra climb from RC1

![image](https://github.com/wazuh/wazuh/assets/14913942/35257a0e-fa38-4b45-a803-64df4f0bd1d3)
![image](https://github.com/wazuh/wazuh/assets/14913942/94e9bfa3-6c73-4d05-980c-5870a52d18bd)
![image](https://github.com/wazuh/wazuh/assets/14913942/bf433519-9ac9-4678-9fc3-eae138e2dd91)

It is necessary to validate this behavior

**Comment by LucioDonda** [comment]
Narrowing the cases the RSS increase after the full load is just noticeable on the plots of windows agent in the rootcheck test. 
This behavior isn't shown in the All test [plot](https://camo.githubusercontent.com/c76fa6a69372069dee3b77446a4ab356d0d1fe4496cf6d5bc4bb6de726a46a62/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531312d333630306d2f42343531315f6167656e745f77696e646f77732f706c6f74732f6d6f6e69746f722d77696e6167656e742d546573745f7374726573735f42343531315f77696e646f77732d7072652d72656c656173655f5253532e706e67), [all except logcollector](https://camo.githubusercontent.com/a75bac266887bb317c0e3717fb6352a6489c12636985535a08e457d2d551ccf2/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531322d333630306d2f42343531325f6167656e745f77696e646f77732f706c6f74732f6d6f6e69746f722d77696e6167656e742d546573745f7374726573735f42343531325f77696e646f77732d7072652d72656c656173655f5253532e706e67), [All except syscheck](https://camo.githubusercontent.com/e87448340ed05e5e7a8555a61889ad2ae0442be4ee0b95ade3a5943ccb67d735/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531332d333630306d2f42343531335f6167656e745f77696e646f77732f706c6f74732f6d6f6e69746f722d77696e6167656e742d546573745f7374726573735f42343531335f77696e646f77732d7072652d72656c656173655f5253532e706e67), [All except SCA](https://camo.githubusercontent.com/8c06038b8698bf813bcbd13858b671b960e2ab95afc37c5989b0d2bc026878e2/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531352d333630306d2f42343531355f6167656e745f77696e646f77732f706c6f74732f6d6f6e69746f722d77696e6167656e742d546573745f7374726573735f42343531355f77696e646f77732d7072652d72656c656173655f5253532e706e67)

By this, we can say that the behavior is not strictly related to the presence of the rootcheck module and that it could had been caused by a strange condition during testing. 

Besides that, it worth mentioning that the RSS increase after the full load is of 200Kb o memory (from 16000 to 16200 approximately).

Another thing about that increase, is that it shouldn't be strange because the events of root check are still being receive in the manager after the full load:
Total events:
![EventsInManager](https://github.com/wazuh/wazuh/assets/95248059/df7c9b41-9d84-46cf-b4d9-e3dbc4ed7640)
Divided by source:
![EventsBySource](https://github.com/wazuh/wazuh/assets/95248059/61c55bfe-452c-4b7e-aae5-ec5c5146e322)

Checking the changelog there's a change regarding rootcheck, I'll continue on checking it but IMO this shouldn't be an issue
