### ISSUE TITLE
RSS memory usage increased in `wazuh-modulesd`

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#19923]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-rc2 | wazuh-modulesd| Manager | Packages | CentOS |

Testing  [ALL-EXCEPT-VULNERABILITY-DETECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/19904)
the wazuh-modulesd increases resources usage gradually (both in trend and fluctuation amplitude) in stress test

<details><summary>Plot comparison - 4.6.0-rc2 vs 4.5.3-rc2</summary>

PSS
4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19904
![image](https://github.com/wazuh/wazuh/assets/125690423/4892ae49-4ceb-42d1-8610-6bf890d74fc7)

4.5.3-rc3 https://github.com/wazuh/wazuh/issues/19507
![image](https://github.com/wazuh/wazuh/assets/125690423/c0f627ea-f33f-4c09-ad92-20533bc728c2)

RSS
4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19904
![image](https://github.com/wazuh/wazuh/assets/125690423/5bb50d4b-13f8-4a92-a376-03eb5d58892e)

4.5.3-rc3 https://github.com/wazuh/wazuh/issues/19507
![image](https://github.com/wazuh/wazuh/assets/14913942/d99d2568-8948-4cd9-9443-d891bd8df408)

USS
4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19507
![image](https://github.com/wazuh/wazuh/assets/125690423/dc6f47ec-bd2e-44d2-b89a-77fffed4ac35)

4.5.3-rc3 https://github.com/wazuh/wazuh/issues/19904
![image](https://github.com/wazuh/wazuh/assets/125690423/e264ed19-1e7c-43c6-9a42-bea31a53f254)

</details>

---

This behavior has been observed previously but classified with what was reported in the issue https://github.com/wazuh/wazuh/issues/18693

Apparently, there are signs that this behavior started appearing in 4.4.0, perhaps in 4.3.11, but since the duration is 6h it cannot be guaranteed

[4.4.0](https://github.com/wazuh/wazuh/issues/15793)

![image](https://github.com/wazuh/wazuh/assets/14913942/28746ef3-dbf1-4af6-b6a4-42070d2a33e2)

[4.3.11](https://github.com/wazuh/wazuh/issues/16827)

![image](https://github.com/wazuh/wazuh/assets/14913942/0cad1cc0-dd8c-4c60-900d-a94d6eabe50f)

[4.3.10](https://github.com/wazuh/wazuh/issues/15357)

![image](https://github.com/wazuh/wazuh/assets/14913942/5cdccf52-8ee1-453e-bdbf-d82415fb1b9e)

---

We need to confirm that:
- This behavior is acceptable in 4.6.0
- Find out why 4.5.3 differs from the behavior shown in the rest of the versions

**Comment by vikman90** [comment]
Let's take a look at the memory usage by components:

### 4.6.0 RC 2

|Component|Plot|Notes|
|---|---|---|
|[Syscollector](https://github.com/wazuh/wazuh/issues/19908)|![](https://camo.githubusercontent.com/3e2b082fe81e1cc45b7892a4427a2912b8d7a3c421750be422a05a488e0c250d/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343530342d333630306d2f42343530345f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343530345f6d616e616765722d7072652d72656c656173655f5253532e706e67)|Good memory allocation|
|[SCA](https://github.com/wazuh/wazuh/issues/19905)|![](https://camo.githubusercontent.com/a0717b215fa047f51c9cc88971e65bd55caffa7b797d359c1de8ee08854e8d40/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343530322d333630306d2f42343530325f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343530325f6d616e616765722d7072652d72656c656173655f5253532e706e67)|Good progress|
|[Integrations](https://github.com/wazuh/wazuh/issues/19895)|![](https://camo.githubusercontent.com/c241081fb89ebc1596446f91a3150f3cea5b4b03ea2f1f65262a02f801cd3cac/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531302d333630306d2f42343531305f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343531305f6d616e616765722d7072652d72656c656173655f5253532e706e67)|Low allocation|
|[All but Vuln Det](https://github.com/wazuh/wazuh/issues/19904)|![](https://camo.githubusercontent.com/3fcc0b3cbb2ab0f5d375a0163b6174bd3af1688846ed6bb6b3ed3448f429fb7c/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531392d333630306d2f42343531395f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343531395f6d616e616765722d7072652d72656c656173655f5253532e706e67)|≈ Syscollector + SCA<br>Peaks of ~100 MB ⚠️|

### All but Vulnerability Detector

|Component|Plot|RSS peak|
|---|---|---|
|[4.5.3 RC3](https://github.com/wazuh/wazuh/issues/19507)|![](https://camo.githubusercontent.com/02ae273531eb0bfc68c9888a3e4b48b85c24e7c51a6af16eadafc7ab4d234fd8/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343433382d333630306d2f42343433385f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343433385f6d616e616765722d7072652d72656c656173655f5253532e706e67)|~70 MB|
|[4.6.0 Beta 1](https://github.com/wazuh/wazuh/issues/19243)|![](https://camo.githubusercontent.com/eb4167073009c1fd8d9636af0b895ffc29483e0bd066fa8c7e80e51530fae22c/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573735f56616772616e742f7072652d72656c656173652f342e362e302f423136392d333630306d2f423136395f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f56616772616e745f423136395f6d616e616765722d7072652d72656c656173655f5253532e706e67)|~65 MB|
|[4.6.0 RC 1](https://github.com/wazuh/wazuh/issues/19557)|![](https://camo.githubusercontent.com/22905c8a1465ab0abc1878d8309f63c60f7d9094c0c7cf74cf69e83d2a22a766/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573735f56616772616e742f7072652d72656c656173652f342e362e302f423138312d333630306d2f423138315f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f56616772616e745f423138315f6d616e616765722d7072652d72656c656173655f5253532e706e67)|~70 MB|
|[4.6.0 RC2 @ t3a](https://github.com/wazuh/wazuh/issues/19904)|![](https://camo.githubusercontent.com/3fcc0b3cbb2ab0f5d375a0163b6174bd3af1688846ed6bb6b3ed3448f429fb7c/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343531392d333630306d2f42343531395f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343531395f6d616e616765722d7072652d72656c656173655f5253532e706e67)|~100 MB ⚠️|
|[4.6.0 RC2 @ c5a](https://github.com/wazuh/wazuh-jenkins/issues/5876)|![](https://camo.githubusercontent.com/45f813561ce6123584f79bf747013356ab634ac5dbe7d8b144c886fd844ebb2b/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343534302d333630306d2f42343534305f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343534305f6d616e616765722d7072652d72656c656173655f5253532e706e67)|~100 MB ⚠️ |

## Comments

- The chart evolution may be due to memory fragmentation.
- The peak has increased notably from RC 1 to RC 2.

**Comment by vikman90** [comment]
## Changes from RC 1 to RC 2
* Updating Windows tests with new libfimdb.dll by @pereyra-m in https://github.com/wazuh/wazuh/pull/19461
* Fix AWS Security Lake memory leak when setting the wrong configuration by @fdalmaup in https://github.com/wazuh/wazuh/pull/19521
* Fix to generate the CPE for Windows systems without the os_release field by @MarcelKemp in https://github.com/wazuh/wazuh/pull/19595
* Remove timeout error log in sendsync forward method by @Selutario in https://github.com/wazuh/wazuh/pull/19629
* Fix win32 compilation after incomplete bump by @Dwordcito in https://github.com/wazuh/wazuh/pull/19714
* Fix to generate the CPE for Windows systems without the os_release field (backport) by @MarcelKemp in https://github.com/wazuh/wazuh/pull/19706
* Logcollector module memory leaks in Windows agents by @lsayanes in https://github.com/wazuh/wazuh/pull/19705
* Break local server connections when connection with master is broken by @Selutario in https://github.com/wazuh/wazuh/pull/19702
* Fix RSYNC infinite synchronization by @Dwordcito in https://github.com/wazuh/wazuh/pull/19715
* Add timeout to clusterd requests by @TomasTurina in https://github.com/wazuh/wazuh/pull/19729
* Update references to `wazuh-kibana-app` repo by @AlexRuiz7 in https://github.com/wazuh/wazuh/pull/19697
* Update changelog and revision for 4.5.4 by @vikman90 in https://github.com/wazuh/wazuh/pull/19737
* Reduce the EPS limit default value for FIM by @ncvicchi in https://github.com/wazuh/wazuh/pull/19758
* Update workflow to run only the required test by @pereyra-m in https://github.com/wazuh/wazuh/pull/19749
* Merge 4.5.4 into 4.6.0 by @TomasTurina in https://github.com/wazuh/wazuh/pull/19783
* Update changelog for 4.6.0 by @vikman90 in https://github.com/wazuh/wazuh/pull/19796
* Update revision to 40603 by @TomasTurina in https://github.com/wazuh/wazuh/pull/19812

**Comment by vikman90** [comment]
## Conclusion

- The anomaly comes from previous versions (4.4.0, where we introduced jemalloc).
  - https://github.com/wazuh/wazuh/issues/10107
- The odd footprint result is 4.5.3.
