### ISSUE TITLE
Strange debug message debian 9

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh#2003]
# Vulnerability Detector test

| Version | 
| --- | 
| 3.7.1 |

- Check that there are no false positives in Debian.

`2018/11/29 11:06:01 wazuh-modulesd:vulnerability-detector[7450] wm_vuln_detector.c:585 at wm_vulnerability_detector_report_agent_vulnerabilities(): DEBUG: (5456): The 'libxml2' package from agent 3 is not vulnerable to CVE-2017-18258. Condition: package version (2.9.4+dfsg1-2.2+deb9u2) less than 0:0.`

The package version is compared with a strange version (0:0), always is bigger and set as not vulnerable.

Is it normal?

Regards,

**Comment by crolopez** [comment]
Hi,

If we look at CVE-2017-18258 in the NVD, it says: 

> The xz_head function in xzlib.c in libxml2 before 2.9.6...

This means that it is a false positive derived from a bug in the generation of Debian's OVAL, which gives **0:0** instead of a valid version. If we included the NVD as an alternative feed, this problem would be solved.

Related issue: https://github.com/wazuh/wazuh/issues/1164.

Best regards.
