### ISSUE TITLE
Increase of disk use in Windows Agent in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#20102]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0-alpha2 | Wazuh | Agent| Packages | Windows |

In [Footprint Metrics - ALL-EXCEPT-ROOTCHECK (2.5d)](https://github.com/wazuh/wazuh/issues/20068)

Checking Disk use of Windows and comparing it with 4.6.0-rc2 it is possible to see a big increase of the initial peak size (reaching 2500 vs 500 in [4.6.0](https://github.com/wazuh/wazuh-jenkins/issues/5870))

4.7.0-alpha2 (left) vs 4.6.0-rc2 (right)
![image](https://github.com/wazuh/wazuh/assets/125690423/39487c2a-41b9-42d2-a600-42315b2b1afb)

Further research should be done.

**Comment by LucioDonda** [comment]
While still searching for changes in the code that can be causing this significant increase, there are two points that needs to be cleared:
* the peak only happens at the start which is an usual behavior.
* During the full load and after the disk usage remains the same as in previous cases.

**Comment by LucioDonda** [comment]
Based on the code research (difference between **4.7.0-alpha2** and **4.6.0**) I was able to find a [commit](https://github.com/wazuh/wazuh/commit/c4051bd60a03cc58d10cbb6250576367ce3f450c) with some changes on the agent side that could have impact on this behavior.

![Screenshot from 2023-11-08 15-50-46](https://github.com/wazuh/wazuh/assets/95248059/3752068b-bdf8-424c-b0b1-f01d0d26dbef)

It seems that, in order to limit the EPS, it must be started a new thread on the agent side. Actually, according to the test, this new feature is being used right before the spike occurs:
```
$ cat logs/2023/Nov/ossec-0*.log  | grep "EPS limit"
2023/11/03 12:58:12 wazuh-agent: INFO: EPS limit enabled, EPS: '500', timeframe: '1'
2023/11/03 12:58:46 wazuh-agent: INFO: EPS limit enabled, EPS: '500', timeframe: '1'
```
But IMHO there's no 100% certainty that this can increase the Disk usage this way.
Besides that, I could notice some differences in the number of events in both tests but that shouldn't impact the start of the procedure.
I think that although the increase is considerable it isn't causing any additional issues on the system, especially taking notice that during the full load stage, it remains as it did in previous tests.

**Comment by LucioDonda** [comment]
Additional comment, analysis on all the test of the same main issue, which of them show that peak increase:


Peak  | Modules 
-- | -- 
   ☑️  | All 
❌    | Vulnerability-detector 
❌   | Vulnerability-detector-Register 
   ☑️  | All-except-Vulnerability-detector 
 NO Graph  | ALL-EXCEPT-OSQUERY,VULNERABILITY-DETECTOR 
  ❌ | Logcollector 
   ❌ | Syscheck 
   ❌ | Rootcheck 
❌    | SCA 
 ❌   | Active Response 
❌   | Syscollector 
❌   | Docker,Ciscat,Osquery,Azure,Openscap 
   ☑️  | All-except-Logcollector 
❌   | All-except-Syscheck 
   ☑️  | All-except-Rootcheck 
   ☑️  | All-except-SCA 
   ☑️  | All-except-Active Response 
   ☑️  | All-except-Syscollector 
   ☑️  | All-except-Docker,Ciscat,Osquery,Azure,Openscap 
❌   | Logcollector-Syscollector 
❌   | Logcollector-SCA 
❌   | Logcollector-Syscheck

**Comment by LucioDonda** [comment]
Based on this [issue](https://github.com/wazuh/wazuh-jenkins/issues/5656) we must take into account that, for this and all the future tests that implies **Disk%**, the conclusions should be handled carefully.
Digging into what **DIsk%** means (or how it's calculated) we could change the focus to Read and write bytes.

That being said, there's still a major increase but now we know that it's due to Read processes:
* 4.7.0
![ReadWrite4 7 0StartScaled](https://github.com/wazuh/wazuh/assets/95248059/399ec1d0-fe2b-459d-adbd-ef879f980fd6)

* 4.6.0
![ReadWrite4 6 0StartScaled](https://github.com/wazuh/wazuh/assets/95248059/f519f749-e428-45ad-a2e6-a40392efb5ff)

**Comment by cborla** [comment]
The agent conditions have changed with respect to 4.6.0, the comparison is not quite correct, this behavior will be analyzed in the next stress test of 4.7.0.
