### ISSUE TITLE
Syscheck stress test increased dropped events significantly

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#20118]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0-alpha2| wazuh-syscheckd | Manager | Packages | CentOS 7 |

In the analysis of the issue https://github.com/wazuh/wazuh/issues/20060 it has been detected that the Wazuh manager has a significant increase in dropped events throughout the test compared to 4.6.0, reaching up to 6k lost events, increasing during the test

![image](https://github.com/wazuh/wazuh/assets/14913942/2eaca972-c617-4beb-b576-f643635302b8)
![image](https://github.com/wazuh/wazuh/assets/14913942/fec1f55b-3300-433c-8c2c-b9efbaab422a)

It is possible that the increase in generated events is related since it has increased from a maximum of `1.4e7` in 4.6.0 to `2e7` in 4.7.0

![image](https://github.com/wazuh/wazuh/assets/14913942/3df6cd09-be78-465c-9e27-5cef9b3ed2fd)
![image](https://github.com/wazuh/wazuh/assets/14913942/151c41e4-1efc-427a-9e42-4b54adcd9373)

**Comment by nbertoldo** [comment]
Analysing the reports, we can see that in `4.6.0` the manager receives a total of `1.4e7` syscheck events.
While in `4.7.0` the manager receives 50% more events, reaching a total of `2.1e7` events.

<details><summary>4.6.0</summary>

![image](https://github.com/wazuh/wazuh/assets/117279646/9f41c91f-cf93-4d5a-a022-b6b5997fd8ba)

</details>

<details><summary>4.7.0</summary>

![image](https://github.com/wazuh/wazuh/assets/117279646/bd2fed56-d552-4462-87b8-da8cbf57b49c)

</details>

This increase is also seen in the decoded events graphs.

<details><summary>4.6.0</summary>

![image](https://github.com/wazuh/wazuh/assets/117279646/f80a5269-cab9-4cdf-909d-17bd785d0086)

</details>

<details><summary>4.7.0</summary>

![image](https://github.com/wazuh/wazuh/assets/117279646/78067951-5d09-47d6-a8d3-8303770df72c)

</details>

This causes the `syscheck queue` to work more overloaded in `4.7.0` and occasionally `analysisd` cannot process the full volume of events and starts to drop them.

<details><summary>4.6.0</summary>

![image](https://github.com/wazuh/wazuh/assets/117279646/0ae938e1-982a-4944-a0a4-773ba5d7bb7f)

</details>

<details><summary>4.7.0</summary>

![image](https://github.com/wazuh/wazuh/assets/117279646/57d6134a-b34d-4e03-8bc8-d220afc9e925)

</details>

Finally, I understand that the increase in the number of events received is due to the improvements in EPS limits implemented in  #16346.
