### ISSUE TITLE
`wazuh-db` increased the RSS usage in the Syscheck stress test

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#20122]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0-alpha2 | wazuh-db | Manager | Packages | CentOS 7 |

In the analysis of the issue https://github.com/wazuh/wazuh/issues/20060, an increase of `~20MB` has been detected in `wazuh-db` in the RSS plot, it is necessary to determine if this increase in usage is expected or not

![image](https://github.com/wazuh/wazuh/assets/14913942/ba242dc0-b586-49c5-b616-6f996b7b0693)
![image](https://github.com/wazuh/wazuh/assets/14913942/f2b3d27b-d6fe-4fda-8416-5ef2629cab60)

**Comment by vikman90** [comment]
## Stats

### CPU

|Version|CPU time|Average|Max|
|---|---|---|---|
|[4.6.0-rc2](https://github.com/wazuh/wazuh/issues/19891)|2027.98 sec |5.59 %|63.90 %|
|[4.7.0-alpha2](https://github.com/wazuh/wazuh/issues/20060)|1938.30 sec. ⬇️|4.99 % ⬇️|22.00 % ⬇️|


### RSS memory
|Version|Average|Max|
|---|---|---|
|[4.6.0-rc2](https://github.com/wazuh/wazuh/issues/19891)|20928.32 KiB |23528.00 KiB|
|[4.7.0-alpha2](https://github.com/wazuh/wazuh/issues/20060)|34970.77 KiB ⬆️|36212.00 KiB ⬆️|

**Comment by vikman90** [comment]
## Stats

### Decoded events

|Version|Decoded events|
|---|---|
|[4.6.0-rc2](https://github.com/wazuh/wazuh/issues/19891)|1.4 · 10⁷ |
|[4.7.0-alpha2](https://github.com/wazuh/wazuh/issues/20060)|2.1 · 10⁷ (50 % ⬆️)|

## Conclusion

We believe that excess memory is related to a higher event load. This is possibly due to more threads working concurrently and memory fragmentation.
