### ISSUE TITLE
aiohttp-cache use in rules controllers functions.

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh#20245]
|Wazuh version|Component|
|---|---|
| 4.9 | API |

## Description
Define if the aiohttp-cache package should be removed or maintained by investigating the behavior of the controllers found in api.controllers.rules_controller.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by RamosFe** [comment]
## Introduction - Rule Controllers and `aiohttp-cache`

The rule controllers use the package `aiohtpp-cache` for some endpoints to create a cache of the returned data, as shown here:

https://github.com/wazuh/wazuh/blob/c6412e52263bdce7b8be0e4625466b63b43aa65e/api/api/controllers/rule_controller.py#L23-L29

It uses the configuration `["cache"]["time"]` to define the time the cache is alive. This value is saved here:
https://github.com/wazuh/wazuh/blob/c6412e52263bdce7b8be0e4625466b63b43aa65e/api/api/configuration.py#L62-L64

The `time` value is in seconds.

## Performance based on the `time` value

I was investigating the response time of the endpoint by varying the value of `time`. For this use `Locust` and create the following test in which you only create a user and make a request to rules:

```
# WazuhAPIUser is an abstract class used for inheriting the login
# Methods for the authentication
class RuleListUser(WazuhAPIUser):
    # The time to wait between tasks
    wait_time = between(1, 5)

    @task
    def first_rule_request(self):
        headers = {}
        headers = self.add_token_to_headers(headers)
        self.client.get("/rules", headers=headers)

    @task
    def second_rule_request(self):
        headers = {}
        headers = self.add_token_to_headers(headers)
        self.client.get("/rules", headers=headers)
```

### Performance test results
I tested two scenarios:
- **Run 1**: The time value is 4 minutes (240 seconds).
- **Run 2** The time value is 0.750 seconds (The value used in the newest version of Wazuh)
![response_times_(ms)_1709580025 97](https://github.com/wazuh/wazuh/assets/37565679/d6457620-7336-4ba8-a2bc-0efe4a43274e)

As you can see, there is a big performance difference between using cache or not. If we want to maintain this functionality, we should consider keeping `aiohttp-cache` and validating whether it is okay for time to be such a low value, since it is difficult to find a use for a cache that lasts less than 1 second.

## `aiohttp-cache` and alternatives

Because aiohttp-cache is a plugin that only works if an `aiohttp` server is used, we have to look for alternatives when switching to `starlette`. 2 alternatives were found that support *ASGI* and at the same time have the same structure of using a decorator for the cache:
- `asgi-cache` - [Homepage](https://florimondmanca.github.io/asgi-caches/)
- `aiocache` - [Homepage](https://github.com/aio-libs/aiocache?tab=readme-ov-file#how-does-it-work)

The most suitable for our needs is `aiocache` because `asgi-cache` is in an "alpha" status. Several features still need to be implemented, and you should expect breaking API changes across minor versions.

## Conclusions
Although the cache brings performance improvements, today with the value we are using for the `time` field, these performance improvements are only noticeable for particular cases in which the same request is made in a period of less than 1s. If it is known that in the next major version, the logic of this endpoint will be changed, and with what I described above, I believe that the work of adding and maintaining a new package as well as refactoring the code is not worth maintaining.

**Comment by RamosFe** [comment]
## Update

After talking about it with the team, we decided to deprecate the `cache` API configuration in `4.9` and created the following [Issue](https://github.com/wazuh/wazuh/issues/22372) for the task.

**Comment by nico-stefani** [comment]
Good analysis!

**Comment by Selutario** [comment]
I agree! Gj.
