### ISSUE TITLE
Increase of Disk use in Manager and Windows Agent in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#20328]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0-rc1| Wazuh | Manager & Agent | Packages | CentOS Manager/ Windows Agent |

During the analysis of [Footprint Metrics - ALL-EXCEPT-VULNERABILITY-DETECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/20300)

- Manager 4.7.0-rc1 https://github.com/wazuh/wazuh/issues/20300

![image](https://github.com/wazuh/wazuh/assets/125690423/9bac56c9-634a-4735-b780-b0746e909fc3)

- Manager 4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5876
![image](https://github.com/wazuh/wazuh/assets/125690423/97b09e41-b1eb-460d-8028-e7fc42f17fe0)

Modulesd: 17.5 vs 10

- Windows Agent 4.7.0-rc1 https://github.com/wazuh/wazuh/issues/20300
![image](https://github.com/wazuh/wazuh/assets/125690423/18623f00-ff74-4b96-8fd2-1bea2f436ede)

- Windows Agent 4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5876
![image](https://github.com/wazuh/wazuh/assets/125690423/2a63633c-e2bb-43f4-bc13-dce99e209671)

Agent.exe: 3000 vs 2500

Further research should be done

**Comment by JavierBejMen** [comment]
### Log Analysis
Upon examining the logs from both RCS, we found no significant differences that could pinpoint the root cause of the issue.

**Comment by JavierBejMen** [comment]
## Configuration Analysis
The configuration review identified changes in the DB sync fragmentation settings, as documented in [PR #19956](https://github.com/wazuh/wazuh/pull/19956) and [Issue #17928](https://github.com/wazuh/wazuh/issues/17928). These modifications might be related to the observed peak in disk usage. However, it is challenging to establish a definitive connection with the current data. A more in-depth analysis of the metrics and tests mentioned in the issue is necessary to determine any potential correlations.

**Comment by JavierBejMen** [comment]
Regarding the windows agent the issue referenced at [Issue #20102](https://github.com/wazuh/wazuh/issues/20102) exhibited similar behavior during startup in the alpha-2 version. The analysis concluded that there was an increase in read operations. However, a comparison between the actual results of RC7 and RC6 shows no significant difference in the number of read operations. While there may be a connection, the results are currently inconclusive, indicating the need for further investigation to determine the underlying cause.

**Comment by JavierBejMen** [comment]
## Brief Code Analysis

A quick examination of the changes from version 4.6.0 to RC7 reveals several modifications that might impact disk operations:

- [PR #16683](https://github.com/wazuh/wazuh/pull/16683): This update introduced a retry mechanism in the agent-upgrade module's synchronization. Since this feature is specific to cluster configurations and the stress test under review does not involve a cluster environment, its impact on the observed disk operation issues is considered unlikely.

- [PR #16919](https://github.com/wazuh/wazuh/pull/16919): This pull request added a retry function for scenarios where the Wazuh module is not ready, particularly for Windows agents. This modification could potentially influence the disk operation irregularities and requires further analysis to determine its effect.

- [PR #17982](https://github.com/wazuh/wazuh/pull/17982): This change introduces new I/O and file system functionalities to the shared folder, mainly utilized by the vulnerability detector. Given that the vulnerability detector is not part of the tests being conducted, it is unlikely that this modification is contributing to the disk behavior observed in the test scenarios.

**Comment by JavierBejMen** [comment]
Direct comparison of results between versions 4.7.0-alpha-1 and 4.7.0-alpha-2 is not possible, as the test was skipped for these versions. To conduct a comprehensive analysis, the test should be executed for both versions when feasible.

**Comment by JavierBejMen** [comment]
## Simple statistical analysis

The statistical analysis of the "Disk(%)" metric for the wazuh-db and modulesd daemons across three different Wazuh versions (4.6, 4.7-alpha-2, and 4.7-rc1) reveals the following trends:

Version 4.6
```
Count: 23,184 observations
Mean: Average disk usage is approximately 0.31%
Standard Deviation: 0.64%, indicating moderate variability
Minimum: Lowest disk usage is about 0.02%
Median (50th Percentile): Median disk usage is around 0.024%
Maximum: Highest disk usage recorded is around 3.99%
```
Version 4.7-alpha-2
```
Count: 32,137 observations
Mean: Average disk usage increases slightly to about 0.32%
Standard Deviation: 0.73%, similar variability as in version 4.6
Minimum: Slightly lower minimum disk usage at around 0.014%
Median: Median disk usage increases to about 0.033%
Maximum: Higher maximum disk usage at approximately 4.63%
```
Version 4.7-rc1
```
Count: 31,808 observations
Mean: Average disk usage further increases to about 0.41%
Standard Deviation: 1.02%, indicating increased variability
Minimum: Minimum disk usage is around 0.018%
Median: Median disk usage increases to about 0.037%
Maximum: Significantly higher maximum disk usage at approximately 6.03%
```
These statistics indicate a gradual increase in both the average and maximum disk usage percentages for the wazuh-db and modulesd daemons from version 4.6 to 4.7-rc1. The increasing mean and maximum values, along with the rising standard deviation, suggest a trend of growing disk usage over these versions, particularly evident during the startup process.

The output of the t-test comparing the disk usage between versions 4.7-alpha-2 and 4.7-rc1 is as follows:
```
T-statistic: -13.51415271878688
P-value: 1.4929816987554988e-41
```
This statistical output indicates a significant difference in disk usage between the two versions, with the negative t-statistic suggesting higher disk usage in 4.7-rc1 compared to 4.7-alpha-2. The extremely low p-value strongly suggests that this difference is statistically significant and not just a result of random variation.

It's important to note that the results for version 4.6 do not utilize the same database fragmentation configuration as seen in the later versions, 4.7-alpha-2 and 4.7-rc1.  For a more accurate and clear comparison, it is necessary to perform the tests across all these versions under the same database fragmentation configuration.

**Comment by JavierBejMen** [comment]
# Simple statistical analysis for windows agent

The analysis of the "Disk(%)" metric for the wazuh-agent.exe daemon across Windows agent versions 4.6, 4.7-alpha-2, and 4.7-rc1 reveals significant fluctuations and unusually high values.

Version 4.6
```
Count: 39,030 observations
Mean: Average disk usage is approximately 647.82%
Standard Deviation: 325.35%, indicating significant variability
Minimum: Lowest disk usage is about 1.19%
Median (50th Percentile): Median disk usage is around 565.07%
Maximum: Highest disk usage recorded is around 2171.99%
```
Version 4.7-alpha-2
```
Count: 39,113 observations
Mean: Average disk usage decreases to about 276.22%
Standard Deviation: 352.75%, suggesting high variability
Minimum: Significantly higher minimum disk usage at around 9.63%
Median: Median disk usage is around 140.06%
Maximum: Lower maximum disk usage at approximately 1734.85%
```
Version 4.7-rc1
```
Count: 39,113 observations
Mean: Average disk usage increases again to about 633.06%
Standard Deviation: 472.09%, indicating even greater variability
Minimum: Minimum disk usage is around 9.51%
Median: Median disk usage increases to about 472.00%
Maximum: Significantly higher maximum disk usage at approximately 3073.23%
```

The key points to consider:
- High Variability Across Versions: The data shows substantial variations in disk usage metrics between different versions. While version 4.6 and 4.7-rc1 exhibit notably high average disk usage, version 4.7-alpha-2 demonstrates a considerable decrease.

- Unusually High Maximum Values: The maximum disk usage values recorded are above 100%, which is atypical and suggests either a data collection/reporting anomaly

In conclusion, while the data indicates notable trends and changes in disk usage across versions, the presence of anomalously high values and fluctuations necessitates a careful review of the data collection methods and metric definitions to draw definitive conclusions about system performance and behavior. Adding also that 4.6 tests do not utilize the same fragmentation configuration.
