### ISSUE TITLE
Changes in memory usage in CentOS and Ubuntu agents

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#20329]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0-rc1 | Multiple | Agent | Packages| CentOS/Ubuntu |

## Description

While analyzing the [results of the footprint tests in `4.7.0-rc1`](https://github.com/wazuh/wazuh/issues/20306) we've found some differences compared to this issue: https://github.com/wazuh/wazuh-jenkins/issues/5872 (production version)

- CentOS Agent
  - PSS
    - Logcollector decreased ~40% 📉
    - Syscheckd decreased ~25% 📉
    - Agentd decreased ~30% 📉
    - Modulesd increased ~40% 📈
  - RSS
    - Logcollector decreased ~35% 📉
    - Syscheckd decreased ~25% 📉
    - Agentd decreased ~25% 📉
    - Modulesd increased ~20%📈
  - VMS
    - Modulesd increased ~40%📈
- Ubuntu Agent
  - VMS
    - Modulesd decreased ~40% 📉

Also, there are no remarkable differences in the number of generated/decoded/dropped events.

### CentOS Agent

| Variable | 4.6.0 (current production version) | 4.7.0-rc1 |
|--|--|--
| PSS | <img src="https://camo.githubusercontent.com/c2165826515d1ff40d270b116c9fc1270dabec11c9ae5515bc6ffd99336da1e6/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343533302d333630306d2f42343533305f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343533305f63656e746f732d7072652d72656c656173655f5053532e706e67"/>  | <img src="https://camo.githubusercontent.com/a108470bfcbcaefbd71692636837ccbda220616e145a464f5f3e5dad0cb3665e/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e302f42343538362d333630306d2f42343538365f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343538365f7562756e74752d7072652d72656c656173655f5053532e706e67"/>
| RSS | <img src="https://camo.githubusercontent.com/ed24a05b8370ec6b1fb617a9ec9ea90872d2ca39d1fba5b35c2925275e9536a7/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343533302d333630306d2f42343533305f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343533305f63656e746f732d7072652d72656c656173655f5253532e706e67"/> | <img src="https://camo.githubusercontent.com/ddaed9c5536c96d7ec03e9c9d897c0dbe90b3dbee6be85591d70c9738e73ff4b/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e302f42343538362d333630306d2f42343538365f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343538365f7562756e74752d7072652d72656c656173655f5253532e706e67"/>
| VMS | <img src="https://camo.githubusercontent.com/d5ef74300967a4fc80db7ca3ed37461440a61803a18b6ca042f91874c438ce4b/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343533302d333630306d2f42343533305f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343533305f63656e746f732d7072652d72656c656173655f564d532e706e67"/> | <img src="https://camo.githubusercontent.com/a445e47352cf143040b4f71f3786a14b1ae3abf8f70aff388be53721b4594a44/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e302f42343538362d333630306d2f42343538365f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343538365f7562756e74752d7072652d72656c656173655f564d532e706e67"/>

### Ubuntu Agent

| Variable | 4.6.0 (current production version) | 4.7.0-rc1 |
|--|--|--
| VMS | ![image](https://github.com/wazuh/wazuh/assets/39094716/94322228-af22-4c8e-85da-a6fd04978bdf) | ![image](https://github.com/wazuh/wazuh/assets/39094716/9044eddd-8b0b-4de8-b0cd-02c229dea4ea)

**Comment by MarcelKemp** [comment]
## Research
After looking at all the graphs, I have been able to confirm that on the CentOS agent - `4.7.0-rc1`, the memory of most of the processes has decreased according to `4.6.0-rc2`, as indicated in the description. 
Also, there is a wrong report, as **_wazuh-modulesd_** does not increase, but keeps the same pattern and memory as `v4.6.0`.

### Changelog
Checking for changes made between `v4.6.0-rc2` and `v4.7.0-rc1` that could cause this event, we find the following:
- #16346, but it no longer affects because it is reverted in the next PR:
  - #20167
- #19956

The rest of the developments do not seem to directly affect Linux agents.

### Conclusion
So based on the decrease in memory of the _logcollector_, _agentd_ and _syscheckd_ processes, it seems to be closely related to the changes in the internal configuration of _wazuh-db_, because they seem to be the only difference between `v4.6.0-rc2` and `v4.7.0` for the agent:
- #19956

To confirm this, it would be necessary to stress test _Logcollector_ and _Syscheck_ for `v4.6.0` with such a development, as `v4.6.0-rc2` does not have that change.
