### ISSUE TITLE
Remove Kaspersky executables from Wazuh installation packages and images

### ISSUE THREAD

**Issue by kkovaletp** [wazuh/wazuh#20324]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0 | Active response | Manager, Agent | Any | *nix |

### Proposal \ request

I browsed the Wazuh agent’s folder and unexpectedly found 2 Kaspersky executable files in the active-response/bin folder. then I found the same on the server as well. I discovered that this is an optional integration module with the Kaspersky Endpoint Protection and is executed only when configured. This means that the files can be safely removed and should be excluded from the default installation \ shipping packages, as only a small part of users actually use them (most users don’t use it, as they don’t have the Kaspersky endpoint security solution) and could easily download and deploy executables as part of the integration configuration when needed.

I was notified that 1 of these executables is written in C and has to be compiled together with the product. However, for me it doesn't mean that it has to be packaged and shipped inside of it: while you could configure the pipeline to build the code and produce an executable, you could later package and publish it independently, so later it could be published on some add-ons portal, where users able to download it and integrate following a guide, provided together with the package.

### Why is this a problem? Context clarification

Kaspersky company is a russian big cybersecurity company, which automatically means that they cooperate with russia’s government (because it is not possible for any big company in russia to not cooperate with the government), but I know for sure that they intentionally participate in a worldwide malicious activity of russia for many years (and receive a lot of money from kremlin for that). Kaspersky products have been officially forbidden to be installed even on personal devices of US government workers for the last few years - which means that it is malware or at least software with an extremely low level of trust. Shipping this module as part of the default installation definitely triggers some serious questions from security audit and potentially result in restriction for usage in highly regulated environments.

Here is the [Slack](https://wazuh.slack.com/archives/C0A933R8E/p1700081719643739) thread about this issue.

**Comment by vikman90** [comment]
Dear,

We appreciate your thoughtful proposal. This executable file is part of the agent, which consists of various components. The source code can be found at https://github.com/wazuh/wazuh/blob/8cbe309cdd4577853f257183d84ab87b8eff90e6/src/active-response/kaspersky.c and it does not contain any Kaspersky functionality, it is only a connector between the agent and Kaspersky antivirus, for those who want to initiate an analysis from the agent.

This is a 23 KiB file that comes with the agent but is activated from the manager. It would be difficult for a user to install it separately on each of their agents. Moreover, since it has no connection to the Kaspersky product, we don't think it should pose a security issue.

Therefore, we are going to maintain this integration in the agent for now.

Thank you and best regards.
