### ISSUE TITLE
Relevant Increase of Use of Disk of Windows Agent in Stress Test

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#20347]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0-rc1 | Wazuh | Agent | Packages | Windows |

Testing: [Release 4.7.0 - RC 1 - Footprint Metrics - SYSCOLLECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/20291)

It was possible to evidence a significant increase (Around 280%) of Disk & Disk_Read in Windows Agent

4.7.0-rc1 https://github.com/wazuh/wazuh/issues/20291

![image](https://github.com/wazuh/wazuh/assets/54536265/d667ff33-f979-40cf-b2ee-9a88c8714087)

![image](https://github.com/wazuh/wazuh/assets/54536265/75409d20-c694-4cc4-8efa-7854ee64f4c0)

4.6.0-rc2  https://github.com/wazuh/wazuh-jenkins/issues/5866

![image](https://github.com/wazuh/wazuh/assets/54536265/d1152b3c-a42f-425d-b09a-c74e2805d717)

![image](https://github.com/wazuh/wazuh/assets/54536265/4615603f-6e4f-4698-9d66-79174876f539)

Further research should be done

**Comment by JorgeMarinoDev** [comment]
Just a brief update on this. 

Work in progress. 

- [ ] Checking CSV
- [ ] Checking Rates of RW size and Ops
- [ ] Checking FDs
- [ ] Checking ChangeLog
- [ ] Checking Tests run settings.

**Comment by JorgeMarinoDev** [comment]
**An interesting finding**

Instead of analyzing overall metrics for READ, we will review from a differential calculus POV.
Therefore we checked 4.6.0 and 4.7.0 DELTA changes between samples.

**4.6.0**

![image](https://github.com/wazuh/wazuh/assets/117848458/9874b124-5197-46bd-8c1d-cc28eebc3521)

![image](https://github.com/wazuh/wazuh/assets/117848458/bd981377-456b-4b41-a94e-dac79a64d967)

![image](https://github.com/wazuh/wazuh/assets/117848458/325b36bc-8ee3-474f-b10a-e672d1e26748)

**4.7.0**

![image](https://github.com/wazuh/wazuh/assets/117848458/597298a7-a49b-4faf-8120-4a53cb7eaa28)

![image](https://github.com/wazuh/wazuh/assets/117848458/2df061f2-8868-4b87-bef6-8c4ba797fddd)

![image](https://github.com/wazuh/wazuh/assets/117848458/593c1205-dad6-4fdc-874b-e97dd6a5bc31)

** RESULTS ***

1. Syscollector works at 10 seconds frequency. (sample span 5 secs)
2. In 4.6.0 Every time Syscollector is run, the agent increases in 3 read ops and 80 bytes. 
3. In 4.7.0 Every time Syscollector is run, the agent increases in 3 read ops + 867 read ops and 80 bytes + 394200 bytes.

It looks like there is an additional step in syscollector that performs many more ops and bytes transfers from disk.

Possible guess: 
Recursion bug in https://github.com/wazuh/wazuh/pull/17982

**Comment by vikman90** [comment]
@JorgeMarinoDev Amazing research! I've not managed to reproduce this behaviour. These are my results:

|Version|Max read Δ|
|---|---|
|4.7.0 RC1|7 ops|
|4.7.0 / no-packages|7 ops|
|4.6.0|9 ops|

However, I wonder if the problem might be related to this line: 
https://github.com/wazuh/wazuh/blob/617f54f855e29457f4c92d39b08be08356dc7bb5/src/data_provider/src/sysInfoWin.cpp#L847

On the other hand, we have been reported that the disk usage increases by 280% (in stressed conditions). Taking into account that a Syscollector scan runs once per hour and lasts ~2 seconds, the average increment would be:

![equation](https://github.com/wazuh/wazuh/assets/10536251/72699a2e-538a-4b9f-afc8-d2a65ac38a07)

## Conclusion

The new Syscollector implementation to collect the PYPI and NPM packages has increased the disk read operations. However, However, outside the context of stress tests, the average increase is imperceptible.
