### ISSUE TITLE
Differences in the pattern of USS, PSS, RSS in Agents in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#20342]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0-r1 | Wazuh component | Agent | Packages | CentOS, Ubuntu, Windows |

In the test [Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/20298)

CentOS
Decrease of syscheckd, agentd, execd, modulesd, logcollector
4.7.0-rc1 https://github.com/wazuh/wazuh/issues/20298
![image](https://github.com/wazuh/wazuh/assets/125690423/ce00c8c6-d0f5-4603-ba57-932ed7631e08)
![image](https://github.com/wazuh/wazuh/assets/125690423/94e578da-3e25-4c7a-94b3-5732f656263b)
![image](https://github.com/wazuh/wazuh/assets/125690423/19832063-c0e6-494c-84c5-5fc62dbf7ee2)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5867
![image](https://github.com/wazuh/wazuh/assets/125690423/5556ded5-676c-4063-be31-f236f6111942)
![image](https://github.com/wazuh/wazuh/assets/125690423/d78d9b36-8947-44da-88ac-edfece47499c)
![image](https://github.com/wazuh/wazuh/assets/125690423/90bde599-3d9c-43b9-a75d-ed2359dd583a)

Ubuntu
Less decrease (remainded more stable) of syscheckd, agentd, execd, modulesd, logcollector
4.7.0-rc1 https://github.com/wazuh/wazuh/issues/20298
![image](https://github.com/wazuh/wazuh/assets/125690423/9fbd0bb3-52cd-4ccd-aaac-9dd12e4ce019)
![image](https://github.com/wazuh/wazuh/assets/125690423/c7efe6b7-0429-43a5-8c34-9ceaf3dc71c3)
![image](https://github.com/wazuh/wazuh/assets/125690423/830f72cc-0434-4e53-9aef-0b383f92c72a)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5867
![image](https://github.com/wazuh/wazuh/assets/125690423/a3b92a27-1c71-4d21-8451-48c40306b200)
![image](https://github.com/wazuh/wazuh/assets/125690423/c724b513-f6a2-4ee6-94ba-5d11861f17e3)
![image](https://github.com/wazuh/wazuh/assets/125690423/9009cf75-9f20-4796-a9e9-4485a2ea930d)

Windows
Small differences in the values of the ascending (both) steps.
4.7.0-rc1 https://github.com/wazuh/wazuh/issues/20298
![image](https://github.com/wazuh/wazuh/assets/125690423/2cd7e713-7315-420c-bc69-54244786a004)
![image](https://github.com/wazuh/wazuh/assets/125690423/d863561e-90b0-4cf6-a28f-3da8a6c87b82)
![image](https://github.com/wazuh/wazuh/assets/125690423/8a9f9129-2c17-44c7-b10f-63f84b93f64f)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5867
![image](https://github.com/wazuh/wazuh/assets/125690423/01cca594-1aa6-4050-b484-601c98b03a78)
![image](https://github.com/wazuh/wazuh/assets/125690423/d16b2f3e-7e51-4f9a-ae5c-0a5779f39943)
![image](https://github.com/wazuh/wazuh/assets/125690423/f9adaf09-e258-4a64-8b03-a3cd281faa9c)

**Comment by jotacarma90** [comment]
# Conclusions

Hello team, we have been analyzing in depth this pattern change in the graphs.
For this, we have only seen necessary to review the `RSS` graphs, since all the rest indicate similar values and there are hardly any relevant changes. We do not directly manage the memory, some similar variations can be observed within limits that could be considered normal.

We have reviewed all the latest `RSS` graphs for `CentOS` and `Ubuntu`, and we have detected oscillations in the values that show that this behavior is normal.

We can see this in the examples of stress test graphs above:

<details><summary>CentOS</summary>

[Release 4.6.0 - Alpha 1 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/18916) 
![1-centos](https://github.com/wazuh/wazuh/assets/60003131/1f6b7283-d5bf-4daa-b652-928bd0d849b3)

[Release 4.6.0 - Beta 1 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/19229)
![2-centos](https://github.com/wazuh/wazuh/assets/60003131/8e376a49-28f4-427e-a089-9b19ace6eee9)

[Release 4.6.0 - Revision 1 - Release Candidate RC1 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/19539)
![3-centos](https://github.com/wazuh/wazuh/assets/60003131/845a366e-867f-4510-8923-a9a09c9bfcbf)

[Release 4.6.0 - Revision 1 - Release Candidate RC2 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/19895)
![4-centos](https://github.com/wazuh/wazuh/assets/60003131/18e4075e-ad91-4810-aeb2-0ed78df9df4a)

[Release 4.6.0 - Revision 1 - Release Candidate RC2 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh-jenkins/issues/5867)
![5-centos](https://github.com/wazuh/wazuh/assets/60003131/f6081d0a-eac0-4b20-9a26-49ed8c4e33f9)

[Release 4.7.0 - Alpha 2 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/20061)
![6-centos](https://github.com/wazuh/wazuh/assets/60003131/d855ad49-4bcb-418b-a403-a64ad059315c)

[Release 4.7.0 - RC 1 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/20298)
![7-centos](https://github.com/wazuh/wazuh/assets/60003131/073fedcc-5dd7-4c59-847d-12f447410955)

</details>

<details><summary>Ubuntu</summary>

[Release 4.6.0 - Alpha 1 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/18916) 
![1-ubuntu](https://github.com/wazuh/wazuh/assets/60003131/68aa5e32-c86c-456b-b8e2-b81b290f72a2)

[Release 4.6.0 - Beta 1 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/19229)
![2-ubuntu](https://github.com/wazuh/wazuh/assets/60003131/edf97538-d0ba-479f-a925-d3d3c9501697)

[Release 4.6.0 - Revision 1 - Release Candidate RC1 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/19539)
![3-ubuntu](https://github.com/wazuh/wazuh/assets/60003131/a34e06b5-041f-4b7d-82ec-63c973c3cd5c)

[Release 4.6.0 - Revision 1 - Release Candidate RC2 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/19895)
![4-ubuntu](https://github.com/wazuh/wazuh/assets/60003131/ea25df9b-535e-4a20-80ea-65fe089fe528)

[Release 4.6.0 - Revision 1 - Release Candidate RC2 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh-jenkins/issues/5867)
![5-ubuntu](https://github.com/wazuh/wazuh/assets/60003131/4b50e9a6-92f4-4871-8c2b-15a6fa4c4f5c)

[Release 4.7.0 - Alpha 2 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/20061)
![6-ubuntu](https://github.com/wazuh/wazuh/assets/60003131/5571d0ef-d24a-4fa7-b7a2-59ff86b0f3a9)

[Release 4.7.0 - RC 1 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/20298)
![7-ubuntu](https://github.com/wazuh/wazuh/assets/60003131/9c9cb351-88e6-4dac-a984-544f17094c42)


</details>


## Observations
We can even see that in two different builds for the same release (`Release 4.6.0 - Revision 1 - Release Candidate RC2`), we observe different values and that strange downward pattern at the end of the stress zone of the test. Which leads us to deduce what we said at the beginning, we do not directly manage the memory and therefore these small variations may be part of the management of the operating system itself.

Finally, the Windows graphs do not show a very relevant change in the pattern, the average remains practically the same.
