### ISSUE TITLE
Syscollector JSON exception invalid UTF-8 character

### ISSUE THREAD

**Issue by misss13** [wazuh/wazuh#20344]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.10/4.4.5/4.6.0 | Syscollector | Agent | Packages | Microsoft Windows Server 2012 R2 Standard - 6.3.9600.21563 |

# Description
We have 5 windows in same version  Microsoft Windows Server 2012 R2 Standard - 6.3.9600. The servers language is english. But only one of them is not fully working. As I suspect there is issue in syscollector with some non UTF-8 character. We are not getting full list of processes in wazuh inventory as well as from API. There are ~120services running, but wazuh shows only 15. Agent logs the following error in every mentioned version of wazuh agent:

```
2023/11/20 13:56:01 wazuh-modulesd:syscollector: ERROR: [json.exception.type_error.316] invalid UTF-8 byte at index 40: 0xBF
```
This issue is (I think) linked to:
https://github.com/wazuh/wazuh/issues/16682
https://github.com/wazuh/wazuh/issues/16652

# Steps to reproduce
Probably there is something installed with name containing non UTF-8 charter and cannot be easily reproduced, we couldn't find any process with non UTF-8 character as well as file. So my question is how to debug such an error. Are there any tools or versions of agent to allow printing out the content when this exception occurs? Which element should we check also for those characters?

**Comment by pereyra-m** [comment]
Hello @misss13 !
This issue is indeed similar to those you've shared.

The debugging process in this case consists in compiling the agent by sources to generate a test tool. The required steps are detailed here https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-agent/index.html (you can skip the package generation for Windows, only the compiling phase is required).

I'm including the binary here if this helps you:
[testSysinfo.zip](https://github.com/wazuh/wazuh/files/13426838/testSysinfo.zip)

Then, please copy all the files to the failing machine and start executing one type of scan at a time until one of them fails, we'll know the type of data that is causing the problem

```
        ./sysinfo_test_tool --hardware
        ./sysinfo_test_tool --networks
        ./sysinfo_test_tool --packages
        ./sysinfo_test_tool --processes
        ./sysinfo_test_tool --ports
        ./sysinfo_test_tool --os
        ./sysinfo_test_tool --hotfixes
        ./sysinfo_test_tool --processes
        ./sysinfo_test_tool --packages
```

If you find that the problem is during the `processes` scan as you suspect, please share the output of the tool and a capture of the running processes.
Have you noticed that this happens after a specific package installation or upgrade?

Regards.

**Comment by misss13** [comment]
Unfortunately I don't have direct access to this host, wazuh after first installation had problem with this system only. The process of compiling wazuh will be conducted tomorrow, I hope.

**Comment by Dwordcito** [comment]
closed due to inactivity, thank you for being part of the community, if you want to continue consulting the thread please reopen it and we can continue with what you need!
