### ISSUE TITLE
Remove TLS versions options from the API `ssl_protocol` configuration

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#20484]
|Wazuh version|Component|
|---|---|
| 4.9.0 | Wazuh API |

## Description
In #20396, the team added the new `auto` option for the SSL/TLS version in the API configuration and a deprecation message for when it is defined with `TLS`, `TLSv1`, `TLSv1.1` or `TLSv1.2`. These options will be removed for the next minor in favor of the new one for the client and server to auto-negotiate the highest protocol version supported, and configure the context server-side connections.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Removed the `ssl_protocol` configuration key and added `ssl_minimum_version` and `ssl_maximum_version`.

However, we are still discussing which TLS versions we are going to support, since all versions other than `TLSv1.2` and `TLSv1.3` are deprecated. Furthermore, in the case of [TLSv1.3](https://docs.python.org/3/library/ssl.html#tls-1-3) it behaves differently that the currently used versions and we may not accept it. In that case, it wouldn't make sense to add the `min` and `max` versions since there's only one available.

**Comment by GGP1** [comment]
## Update

Removed the `ssl_protocol` configuration key and added `ssl_minimum_version` and `ssl_maximum_version`.

However, we are still discussing which TLS versions we are going to support, since all versions other than `TLSv1.2` and `TLSv1.3` are deprecated. Furthermore, in the case of [TLSv1.3](https://docs.python.org/3/library/ssl.html#tls-1-3) it behaves differently that the currently used versions and we may not accept it. In that case, it wouldn't make sense to add the `min` and `max` versions since there's only one available.

**Comment by GGP1** [comment]
## Update

- Updated the deprecated SSL protocol message to show it only when tlsv1 or tlsv1.1 are used.
- Tested different configurations with multiple versions on the client and server side.
