### ISSUE TITLE
Investigate the use and performance of orjson

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh#20494]
|Wazuh version|Component|
|---|---|
| master | API, Framework |

## Description
The [orjson](https://pypi.org/project/orjson/1.3.0/) package is a fast JSON library for Python. The documentation shows a faster serialization and deserialization compared to other libraries like rapidjson and json.

Most API endpoints generate and return JSON responses. Improving the serialization could improve the overall server performance.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Research

I tried modifying all the calls to the standard `json` package but given that the APIs are not compatible, that requires changes all over the source code to work. I opted to just modify the response serialization, since most endpoints use JSON to parse the responses only.

Branch: [fix/20494-orjson-benchmarks](https://github.com/wazuh/wazuh/tree/fix/20494-orjson-benchmarks)

## Serialization benchmarks

> [!Note]
> Time measured in milliseconds

<details><summary>orjson version</summary>

```console
root@wazuh-master:/# /var/ossec/framework/python/bin/pip3 freeze | grep orjson
orjson==3.9.13
```

</details>

<details><summary>GET /lists</summary>

### Raw

21.68 KB response

| | json | orjson |
| --- | --- | --- |
| 1 | 20 | 20 |
| 2 | 20 | 23 |
| 3 | 21 | 23 |
| 4 | 67 | 47 |
| 5 | 39 | 21 |
|  |  |  |
| Median | **33** | **27** |

### Pretty

58 KB response

| | json | orjson |
| --- | --- | --- |
| 1 | 32 | 35 |
| 2 | 22 | 27 |
| 3 | 57 | 19 |
| 4 | 26 | 32 |
| 5 | 24 | 32 |
|  |  |  |
| Median | **32** | **29** |

</details>

<details><summary>GET /decoders</summary>

### Raw

172 KB response

| | json | orjson |
| --- | --- | --- |
| 1 | 289 | 275 |
| 2 | 362 | 248 |
| 3 | 225 | 247 |
| 4 | 221 | 228 |
| 5 | 223 | 219 |
| |  |  |
| Median | **264** | **243** |

### Pretty

275 KB response

| | json | orjson |
| --- | --- | --- |
| 1 | 233 | 299 |
| 2 | 232 | 241 |
| 3 | 264 | 217 |
| 4 | 271 | 227 |
| 5 | 226 | 221 |
|  |  |  |
| Mean | **245** | **241** |

</details>

> [!Note]
> Deserialization results were almost identical, the objects received by the Wazuh API aren't big enough to notice a performance gain.

## Conclusion

After having analyzed the library documentation, the changes required and the impact that it would cause, I consider it's not worth to replace the standard library as `orjson` has more disadvantages than advantages for our use case. 

### Pros

- Slightly better performance. The results obtained were closer than the ones showcased in https://github.com/ijl/orjson#performance. A difference in latency becomes noticeable only on larger responses, Wazuh supports a maximum number of 500 items per request and does not handle particularly large objects.
 
### Cons

- Requires package maintenance, although it's not likely to release versions too often (at least once every Python major release).
- Does not support indenting with 3 spaces, only 2 or 4 (default).
- Requires changes throughout all the code. Encodes to bytes instead of strings and has different parameters (see point below).
- Has a different API, does not support parameters like `object_hook`, `separators`, `indent` (has to be replaced with an option code), `cls` (has to be replaced with `default`).

**Comment by fdalmaup** [comment]
# Review

After reading the `orjson` docs and the analysis made in this issue, I agree with the conclusion of not dedicating efforts to migrate from the standard `json` package. Here are some considerations complementing the analysis:
  - The maintenance of the package could trigger other necessary modifications and an upgrade of it could not be so direct since the source code is partly made with Rust, depending on the availability of the wheels by the maintainers to avoid generating it ourselves, with the risks it involves in terms of compatibility.
  - The `orjson` package is maintained by a smaller community than the one that maintains the Python language and, therefore, the standard `json` library. Any security vulnerability not addressed in time could mean having to roll back all the changes made or being exposed to security breaches until it is fixed.
  - We can take this alternative into account for any issues that present a bottleneck in the standard library. Nevertheless, we cannot risk modifying every `json` package usage given the changes required in our code and the differences in the package's API, which involve a thorough analysis of all the changes and the expected behavior.

LGTM!

**Comment by Selutario** [comment]
Interesting research. I agree, the benefits it provides do not compensate for the additional effort that using `orjson` would entail in our case, at least for the moment, since there are other much larger bottlenecks. I'm closing the issue.
