### ISSUE TITLE
Feature proposal: support for libpcre (Perl-compatible) regular expressions

### ISSUE THREAD

**Issue by fuhry** [wazuh/wazuh#205]
|**Working branch**|
|---|
|dev-205-regex-pcre2|

The `OS_regex` library is fast, but lacks support for basic regex tenets such as character classes and bounded repetition (`{n,m}`). This necessitates writing broader and/or uglier rules than necessary, and also perpetuates maintenance of a reinvention-of-the-wheel subproject. I presume that the historical reason for this is that PCRE did not exist (at least not in its current stable form) in ~2005 when this code was originally authored.

I'm not proposing a wholesale replacement of the `<regex>` tag or the OS_regex library, as that would break every existing ruleset out there. Perhaps the eventual goal could be reimplementing OS_regex as a thin wrapper around PCRE. Full support for Perl-compatible regular expressions would likely need to be implemented as a new `<pregex>` tag or so.

Is there significant interest in this feature? I'm charged with deploying Wazuh by my employer. They have indicated interest in allocating my time to this feature if it's something that could benefit the community at large.

Obvious disclaimer: Nothing is certain at this point, currently just gauging interest.

**Comment by vikman90** [comment]
Hi @fuhry,

I totally agree, the OSSEC regexes and sregexes are fast but not as powerful as POSIX or Perl regexes. In fact we are thinking of moving to POSIX regexes in a future version. But POSIX regexes don't seem to be compatible with Windows. Perl regexes is another great option!

We have introduced dynamic fields that support `key:value` form and nested fields, but no array indexes. This would be necessary since we have added JSON input support in version 3.0. So we would need to design a new form to declare rules conditions.

Of course, every idea or contribution would be very welcome! Keeping support for all regex types would be ideal.

Thank you for your proposal!
Best regards.

**Comment by branchnetconsulting** [comment]
I am very interested in full regex functionality in Wazuh rules and decoders, especially if it can be achieved in a way that does not multiply CPU load for existing rules that only use the simple OS_regex stuff.

**Comment by vikman90** [comment]
|Related mailing list post|
|---|
|[Questions about regex](https://groups.google.com/forum/#!msg/wazuh/r_zll6D5U6g/esdWCXQqEwAJ)|

In this post, Brian Candler suggests using PCRE for rules and decoders:

```xml
<decoder name="test">
  <regex offset="after_prematch">^ \S+ for (?<user>\S+) from (?<srcip>\S+) port </regex>
</decoder>
```

**Comment by iasdeoupxe** [comment]
With https://github.com/ossec/ossec-hids/pull/1652 it seems that OSSEC introduced PCRE2 support with https://github.com/ossec/ossec-hids/releases/tag/3.3.0

**Comment by vikman90** [comment]
@iasdeoupxe thank you, this is definitely a great enhancement.

Currently, we're focusing our effort on improving the performance of the manager, simplify its architecture (to join some daemons) and make the installation easier. However, we will extend the features of the ruleset with PCRE and support any kind of data field (static and dynamic fields together) as soon as possible.

Thank you again.
Best regards.
