### ISSUE TITLE
Prevent simultaneous WPK upgrades

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#20545]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0| Upgrade | Agent | Packages | Rocky Linux 8.9 |

### Description

A user has encountered unexpected behavior while upgrading a Rocky Linux agent, manifesting in several critical issues:
- **CLI Upgrade Stalling**:

When attempting to upgrade the agent remotely using the CLI, the process gets stuck, failing due a Timeout while waiting for the response of the agent:
```
	Agent 013 status: Timeout reached while waiting for the response from the agent
```
- **File Attribute Error in Upgrade Logs:**

 The upgrade logs reveal a recurring error, exemplified by the following entry:

```   
chmod: failed to get attributes of '/var/ossec/queue/diff/..': No such file or directory
```

This log is repeated multiple times for different files in `/var/ossec/queue/diff/local/` directory.

Finally, we can see the following errors in the upgrade
```
tar: tmp_bkp: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
2023/11/30 18:11:01 - Upgrade started.
./var/upgrade/src/init/pkg_installer.sh: line 193: ./var/upgrade/install.sh: No such file or directory
2023/11/30 18:11:01 - Installation result = 127
./var/upgrade/src/init/pkg_installer.sh: line 204: ./var/run/wazuh-agentd.state: No such file or directory
2023/11/30 18:11:02 - Waiting connection... Status = pending. Remaining attempts: 29.
./var/upgrade/src/init/pkg_installer.sh: line 204: ./var/run/wazuh-agentd.state: No such file or directory
2023/11/30 18:11:03 - Waiting connection... Status = pending. Remaining attempts: 28.
```

- **RAM Consumption Surge:**

RAM consumption surges from 2GB to 6GB during the upgrade process, potentially leading to performance issues and system instability.

- **Incomplete Agent Removal**:

Following a manual halting of the agent, a subsequent observation indicates that the agent was removed by the upgrade process.

**Comment by TomasTurina** [comment]
## Update

### Problem description

The user has configured many entries to monitor with `syscheck` in his agent with the `report_changes` flag enabled. This results in a `diff` folder very big, probably some gigabytes of size.

When the upgrade is launched, before executing it a backup is created in the agent to recover it if any problem happens during the upgrade. This backup includes all the important information from the `/var/ossec` folder, including the `diff` folder. Since this folder is very big, it takes a lot of time to generate the backup.

The [default timeout](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/task-manager.html#task-timeout) for an upgrade to complete is 15 minutes. In the user case, the backup is taking more than 15 minutes to complete, so the timeout expires and shows that the upgrade failed.

When the user launched the second upgrade (we confirmed that he did this manually), what the script does first is to clean the `backup` folder. This is why the error logs started to appear in the `upgrade.log` since the first upgrade was in the middle of the process. This also happens with the third try of the user.

Looking at the logs, it takes almost 40 minutes to generate the backup. So, the first upgrade finished successfully but after 40 minutes. However, the second upgrade finished some minutes after, and since it couldn't execute successfully (because when the previous upgrade finished it deleted the upgrade files that weren't needed anymore), it proceeded to restore the backup. This backup is malformed (it was cleaned in the middle of its generation), so when the restore finished the Wazuh installation stopped working and many folders disappeared, they didn't exist in the backup.

The user also confirmed that this only affected the Wazuh installation and nothing else in its machine.

**Comment by TomasTurina** [comment]
## Update

We have been working on the solution proposed. This is the draft PR: https://github.com/wazuh/wazuh/pull/20598

We will proceed with the testing and enhancements of the solution if necessary. @Nicogp is working with me on this.

@vikman90 feel free to review the solution and propose any change you consider.

**Comment by Nicogp** [comment]
## Update
I have done the review of the proposed code, it looks good.
I have proceeded to create wpk packages locally to start testing.

**Comment by vikman90** [comment]
The problem definitely relates to https://github.com/wazuh/wazuh/issues/20490.

**Comment by Nicogp** [comment]
During the day different tests and modifications were performed
Results of the tests on Ubuntu 22 with the latest proposed changes: 🟢 

```
2023/12/04 20:40:50 - Generating Backup.
2023/12/04 20:44:54 - There is an upgrade in progress. Aborting...
tar: ./var/ossec/queue/sockets/upgrade: socket ignored
tar: ./var/ossec/queue/sockets/logcollector: socket ignored
tar: ./var/ossec/queue/sockets/syscheck: socket ignored
tar: ./var/ossec/queue/sockets/queue: socket ignored
tar: ./var/ossec/queue/sockets/com: socket ignored
tar: ./var/ossec/queue/sockets/control: socket ignored
tar: ./var/ossec/queue/sockets/wmodules: socket ignored
tar: ./var/ossec/queue/alerts/execq: socket ignored
tar: ./var/ossec/queue/alerts/cfgaq: socket ignored
2023/12/04 21:21:56 - Upgrade started.

 Wazuh v4.7.1 (Rev. 40706) Installation Script - https://www.wazuh.com/

 You are about to start the installation process of Wazuh.
 You must have a C compiler pre-installed in your system.

  - System: Linux vagrant 5.15.0-83-generic (ubuntu 22.04)
  - User: root
  - Host: vagrant


  -- Press ENTER to continue or Ctrl-C to abort. --

 - You already have Wazuh installed. Do you want to update it? (y/n): 
    - Installation will be made at  /var/ossec .

4- Installing the system

DIR="/var/ossec"
 - Running the Makefile

Stopping Wazuh...
agent
Wait for success...
success
Removing old SCA policies...
Installing SCA policies...


Wait for success...
success
Starting Wazuh...

 - Configuration finished properly.

 - To start Wazuh:
      /var/ossec/bin/wazuh-control start

 - To stop Wazuh:
      /var/ossec/bin/wazuh-control stop

 - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


   Thanks for using Wazuh.
   Please don't hesitate to contact us if you need help or find
   any bugs.

   Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

   More information can be found at:
          - http://www.wazuh.com/

    ---  Press ENTER to finish (maybe more information below). ---

 - Update completed.

2023/12/04 21:22:06 - Installation result = 0
2023/12/04 21:22:07 - Waiting connection... Status = connected. Remaining attempts: 29.
2023/12/04 21:22:07 - Connected to manager.
2023/12/04 21:22:07 - Upgrade finished successfully.
```

[upgrade.log](https://github.com/wazuh/wazuh/files/13551935/upgrade.log)

We are waiting for the creation of the packages for windows and macOS to continue with the tests.
