### ISSUE TITLE
Agent event queue is flooded. Check the agent configuration.

### ISSUE THREAD

**Issue by borbelyau** [wazuh/wazuh#206]
Hi guys!
How I solve this?
Agent event queue is flooded. Check the agent configuration.

**Comment by borbelyau** [comment]
syslog is sending about 1000 logs per second

**Comment by vikman90** [comment]
Hi,

there is indeed a recommended limit of 500 EPS per agent. You may increase it in `ossec.conf` but I'd recommend you to review your configuration, maybe you are monitoring some noisy files.

Best regards.

**Comment by kashif-bokhari** [comment]
@borbelyau Hi I'm having the same issue with my Wazuh Agents. Can you guide me how you resolved or identified the root cause of what is causing it?? @vikman90 Need assistance please. Thanks.

**Comment by vikman90** [comment]
Hello @kashif-bokhari,

Depending on your setup, having more than 500 EPS may be normal or acceptable, but maybe we can optimize the agent configuration. On Windows agents, `<localfile>` for [Eventchannel](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/how-to-collect-wlogs.html#monitor-the-windows-event-channel-with-wazuh) may be noisy, but we can filter the important events with [`<query>`](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html?highlight=eventchannel#query).

First, we need to sample which kind of events the agent is sending. We can do that by analyzing the alerts in Kibana (index `wazuh-alerts-*`. The manager produces an average of 1 alert for every 10 events it receives from the agent. In order to consider every event the manager receives, enable the archives:

```xml
<ossec_config>
  <global>
    <logall_json>yes</logall_json>
  </global>
</ossec_config>
```

Restart the manager. This way, it will fill the archives file (_/var/ossec/logs/archives/archives.log_), and their events will appear at the index `wazuh-archives-*` on Kibana.

This will let you know which events are potentially flooding the agent. With this information, we can decide:
- If these events are not important for you, we can set up the agent configuration to prevent it from collecting them.
- Should these events be important, we will need to increase the agent throughput limit:

```xml
<ossec_config>
  <client_buffer>
    <events_per_second>2000</events_per_second>
  </client_buffer>
</ossec_config>
```

Regarding the client buffer, it's a leaky-bucket buffer that prevents the agent from:
- Flooding the manager and starving other agents that produce fewer events.
- Flooding the network (UDP only).

I strongly recommend you leave the buffer enabled if your agent connects to the manager in UDP mode. If you are using TCP mode, you can disable the buffer as TCP implements end-to-end flow control, but the agent may flood the manager's buffer so that Remoted will drop events that exceed its load.

Hope it helps.
Best regards.
