### ISSUE TITLE
No Read Disk operations for logcollector

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#20618]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 4.7.1-rc1 |  Agent | Packages | Ubuntu  |

### Description

It has been detected during https://github.com/wazuh/wazuh/issues/20567, that the logcollector module has no perform any Disk read operation for the Ubuntu Agent

### Comparison

| Version | Image |
|---------|-------|
| 4.7.1   | ![IMAGE](https://camo.githubusercontent.com/64c1ee37d338828970226d70e0dd239889963ca8555209cc2e7c9756c03d8a4f/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e312f42343630352d333630306d2f42343630355f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343630355f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) |
| 4.7.0   | ![IMAGE](https://camo.githubusercontent.com/9c2b787b013e24b260cbcd74e08a3ca3a5410b5072c927656b3e575f4e25256b/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e302f42343538342d333630306d2f42343538345f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343538345f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) |

### Evidences

- [Agentd State](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.1/B4605-3600m/B4605_agent_ubuntu/data/Test_stress_B4605_ubuntu_agentd_state.csv)
- [Metrics](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.1/B4605-3600m/B4605_agent_ubuntu/data/monitor-agent-Test_stress_B4605_ubuntu-pre-release.csv)
- [Logs and configurations](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.1/B4605-3600m/B4605_agent_ubuntu/logs/ossec_Test_stress_B4605_ubuntu_2023-11-30.zip)

**Comment by LucioDonda** [comment]
After a couple of hours of analysis, it can be said that the value `0` (**Disk Read Bytes**) during all the test procedures could have been caused by a problem on the `monitor.py` and not by a problem with the agent itself. While checking the csv file linked above the column related to read operations has a natural increase making it even more difficult for the agent to read 0 bytes.
Besides that, it must be said that this kind of error has occurred in previous tests.
Tomorrow I'll continue digging deeper into the logs.
c.c. @cborla
