### ISSUE TITLE
Custom cpe-helper.json

### ISSUE THREAD

**Issue by manuchi55** [wazuh/wazuh#20637]
Great option to add custom file for cpe-helper.json 
Benefits: save original cpe-helper.json, inventory custom detection application

**Comment by jnasselle** [comment]
Hi @manuchi55 ,

Thanks for filling this feature request, but it seems to be duplicated/related to this older one https://github.com/wazuh/wazuh/issues/15974.

We are working on https://github.com/wazuh/wazuh/issues/14153, which deprecates the CPE Helper since the vulnerability information a.k.a feed will be already sanitized.
