### ISSUE TITLE
Windows Agent 4.8.0 permission errors on Windows 11 after uprade

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#20727]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha1 | Wazuh component |Agent | Packages | Windows 11 |

## Description

During testing of Issue https://github.com/wazuh/wazuh/issues/20675, it was found that the Windows Agent on Windows 11 does not open the UI after upgrade from `4.7.0`. When trying to open the UI manually a permission error is shown.

## Evidence

![image](https://github.com/wazuh/wazuh/assets/14501079/c0789572-221c-41f6-9239-35b89f8a9c91)
![image](https://github.com/wazuh/wazuh/assets/14501079/95431613-7274-4dbd-a0b2-5168c058ef7b)
![image](https://github.com/wazuh/wazuh/assets/14501079/83aeaeaa-ee6a-4e4e-811d-32adf7566cdd)
![image](https://github.com/wazuh/wazuh/assets/14501079/3b811449-9d82-4b62-82c4-536217e4c3d4)

**Comment by vikman90** [comment]
Possibly related to #12906.

**Comment by vikman90** [comment]
I think the problem is that the permissions are applying for "**this folder only**":

![image](https://github.com/wazuh/wazuh/assets/10536251/acce5eb8-78ef-43c8-8c39-cc3b79b6bf93)


This is preventing the contained files from inheriting the permissions.

**Comment by Deblintrake09** [comment]
- The permission Issue is present also when updating through WPK from a lower version to `4.8.0`
- When Force Updating `4.8.0 -> 4.8.0` the permission bug is not present.

**Comment by ncvicchi** [comment]
UPDATE:

A series of tests were carried out to narrow down the possibilities.

Progressive updates were made from version 4.2.3 to 4.8.0, without ever uninstalling the previous version.

In these cases, the behavior described in the issue was not observed.

However, when installing one version, upgrading to the next, and then uninstalling it before performing the next test, some different behaviors were observed:

#### Changing the test: Install, upgrade, uninstall:

<details><summary>Tests</summary>

|Test|Install|Permissions|Upgrade|Permissions|
|--|--|--|--|--|
|4.2.3 -> 4.2.4|OK|OK|OK|OK|
|4.2.4 -> 4.2.5|OK|OK|OK|OK|
|4.2.5 -> 4.2.6|OK|OK|OK|OK|
|4.2.6 -> 4.2.7|OK|OK|OK|OK|
|4.2.7 -> 4.3.0|OK|OK|OK|UI error. Ejecuta ok manualmente|
|4.3.0 -> 4.3.1|OK|UI error. Ejecuta ok manualmente|OK|UI error. Ejecuta ok manualmente|
|4.3.1 -> 4.4.0|OK|UI error. Ejecuta ok manualmente|OK|UI error. Ejecuta ok manualmente|
|4.4.0 -> 4.5.4|OK|UI error. Ejecuta ok manualmente|OK|UI error. Ejecuta ok manualmente|
|4.5.4 -> 4.6.0|OK|UI error. Ejecuta ok manualmente|OK|UI error. Ejecuta ok manualmente|
|4.6.0 -> 4.7.0|OK|UI error. Ejecuta ok manualmente|OK|OK|
|4.7.0 -> 4.7.1|OK|OK|OK|OK|
|4.7.1 -> 4.7.2|OK|OK|OK|OK|
|4.7.2 -> 4.8.0|OK|OK|OK|OK|

</details>

#### Changing the test: Install, upgrade, uninstall, delete folder:

<details><summary>Tests</summary>

|Test|Install|Permissions|Upgrade|Permissions|
|--|--|--|--|--|
|4.2.3 -> 4.2.4|UI error. Manually executed (with elevated rights)|OK: Folders & subfolders (manually granted)|OK (with elevated rights)|OK: Folders & subfolders|
|4.2.4 -> 4.2.5|UI error. Manually executed (with elevated rights)|OK: Folders & subfolders (manually granted)|OK (with elevated rights)|OK: Folders & subfolders|
|4.2.5 -> 4.2.6|UI error. Manually executed (with elevated rights)|OK: Folders & subfolders (manually granted)|OK (with elevated rights)|OK: Folders & subfolders|
|4.2.6 -> 4.2.7|UI error. Manually executed (with elevated rights)|OK: Folders & subfolders (manually granted)|OK (with elevated rights)|OK: Folders & subfolders|
|4.2.7 -> 4.3.0|UI error. Manually executed (with elevated rights)|OK: Folders & subfolders (manually granted)|UI error. Manually executed (with elevated rights)|OK: Folders & subfolders|
|4.3.0 -> 4.3.1|UI error. Manually executed (with elevated rights)|OK: Folders & subfolders (manually granted)|UI error. Manually executed (with elevated rights)|OK: Folders & subfolders|
|4.3.1 -> 4.3.3|UI error. Manually executed (with elevated rights)|OK: Folders & subfolders (manually granted)|UI error. Manually executed (with elevated rights)|OK: Folders & subfolders|
|4.3.3 -> 4.4.0|UI error. Manually executed (with elevated rights)|OK: Folders & subfolders (manually granted)|UI error. Manually executed (with elevated rights)|OK: Folders & subfolders|
|4.4.0 -> 4.5.4|UI error. Manually executed (with elevated rights)|OK: Folders & subfolders (manually granted)|UI error. Manually executed (with elevated rights)|OK: Folders & subfolders|
|4.5.4 -> 4.6.0|UI error. Manually executed (with elevated rights)|OK: Folders & subfolders (manually granted)|UI error. Manually executed (with elevated rights)|OK: Folders & subfolders|
|4.6.0 -> 4.7.0|UI error. Manually executed (with elevated rights)|OK: Folders & subfolders (manually granted)|OK (with elevated rights)|OK: Folders & subfolders|
|4.7.0 -> 4.7.1|OK (with elevated rights)|Just this folder (for user)|UI error. Not allowed|OK: Only this folder. UI runs when manually changed to "folders & subfolders & files"|

</details>

_**At this point the criteria for the error was found, so no more tests were performed.**_

#### Conclusion

From version 4.7.0 onwards, the permissions applied were modified to solve the problem of launching the UI from the installer.
These permissions are applied to the current user and as "only for this folder". Since it applies it to all folders and files, it works correctly, which made the bug go unnoticed.
When upgrading from any version 4.7.x to any other version, files are upgraded but permissions are not applied to them, as in versions prior to 4.7.0 these were inherited. Because of this, access to the folder is maintained, but no files are accessible.

A solution is being analyzed, but it is expected that applying the permissions, if changed from "only this folder" to "this folders, subfolders & archives" will resolve the error.

**Comment by ncvicchi** [comment]
Update:

The issue was finally traced to the following line:

https://github.com/wazuh/wazuh/blob/037ede2424c1c4402068bc0a1651836f732ccc70/src/win32/InstallerScripts.vbs#L348C28-L348C28

`setPermsInherit = "icacls """ & install_dir & """ /inheritancelevel:d /q"`

It explicitly removes recursive inheritance of permissions.

To confirm this, the following test was performed:

A clean install of version 4.7.0 was performed, and before performing an upgrade, the command was run:

icacls 'C:\Program Files (x86)\ossec-agent' /iinheritance:e /T /C

Then, version 4.7.2 is installed. The upgrade is performed without problems and the UI runs normally and the permissions are verified to be correct.

**Comment by ncvicchi** [comment]
UPDATE:

A PR with the proposed fixed was implementated and a [custom MSI ](https://packages-dev.wazuh.com/warehouse/test/4.7/windows/wazuh-agent-4.7.2-0.0.0.todelete.msi)from its branch was created.

With it, a test where the custom 4.7.2 MSI installer was used for a clean install and the current 4.8.0 MSI installer to upgrade was performed.

In both cases, the UI launched successfully, and the permissions inheritance was present.

**Comment by lchico** [comment]
Thank you, @ncvicchi. Could you please provide a screenshot showing the final permissions?

**Comment by ncvicchi** [comment]
#### Test 1
Original 4.7.2 MSI installer clean install

![image](https://github.com/wazuh/wazuh/assets/69121070/f60fd156-dde7-487b-851d-3fe1c4d9c0be)

Original 4.8.0 MSI installer upgrade

![image](https://github.com/wazuh/wazuh/assets/69121070/8e4555b6-6593-4206-b0b8-d714288d5a9c)

#### Test 2
Fixed 4.7.2 MSI installer clean install
![image](https://github.com/wazuh/wazuh/assets/69121070/f4d5b30a-db5b-41ef-b0b0-ee402f390710)

Original 4.8.0 MSI installe upgrade
![image](https://github.com/wazuh/wazuh/assets/69121070/4dd4d040-f006-419f-b5eb-8d55ab642f9c)

**Comment by Deblintrake09** [comment]
## Review testing

<details><summary>Update with custom package - run with normal permissions</summary>
- Install Oficcial 4.7.1 windows agent

<img width="163" alt="image" src="https://github.com/wazuh/wazuh/assets/14501079/278b88c1-1621-40b2-b1da-87280485951f">
<img width="385" alt="image" src="https://github.com/wazuh/wazuh/assets/14501079/42aa8b5a-bb58-422c-bcb3-670feb010d25">

```
# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: DESKTOP-AQ2R8SM
   IP address: any
   Status:     Active

   Operating system:    Microsoft Windows 11 Pro
   Client version:      Wazuh v4.7.1
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1704442410

   Syscheck last started at:  Fri Jan  5 08:13:29 2024 (Scan in progress)
   Syscheck last ended at:    Unknown
```

- Update custom fixed 4.7.2 agent

<img width="361" alt="image" src="https://github.com/wazuh/wazuh/assets/14501079/e484980d-6371-4067-96ed-ea5b9fef3337">
<img width="252" alt="image" src="https://github.com/wazuh/wazuh/assets/14501079/0ed2d88a-01e5-40a7-a396-dfc4e67c6f4c">
<img width="387" alt="image" src="https://github.com/wazuh/wazuh/assets/14501079/ab9a0997-a084-4abd-8d61-dce2d8c60b1a">
<img width="457" alt="image" src="https://github.com/wazuh/wazuh/assets/14501079/6abd9c9a-8f23-4e81-843a-415856653aff">

```
# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: DESKTOP-AQ2R8SM
   IP address: any
   Status:     Active

   Operating system:    Microsoft Windows 11 Pro
   Client version:      Wazuh v4.7.2
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1704442771

   Syscheck last started at:  Fri Jan  5 08:16:00 2024
   Syscheck last ended at:    Fri Jan  5 08:16:13 2024
```
</summary>

**Comment by ncvicchi** [comment]
Several attemps were made, successfully working from PowerShell but not from the upgrade script. Trying to figure out why

**Comment by ncvicchi** [comment]
Analyzing Wix code to find the proper place to include the permission's modification. No attempt was successful yet.

**Comment by ncvicchi** [comment]
I have struggle creating an MSI with the proposed changes to fix the permissions on the upgrade. Hopefully will be able to test them tomorrow.

**Comment by ncvicchi** [comment]
Looking for reasons for the MSI not generating. Still not finding a solution

**Comment by ncvicchi** [comment]
Finally fixed MSI generation from Jenkinks. Testings fixes, non working yet.

**Comment by ncvicchi** [comment]
Moving ETA for higher priority issues

**Comment by Leoquicenoz** [comment]
## Update

Gain knowledge and replicate issue in local environment.

**Comment by Leoquicenoz** [comment]
## Update

Modify the code according to what you think will work to grant permissions during the update and generate the package that will be used to test it.

**Comment by Leoquicenoz** [comment]
## Update

We are testing with different modifications in the upgrade area, the last test was performed with the following change in the `wazuh-installer.wxs` file:

```
<Component Id="PERMISSIONS_COMPONENT" Guid="74B05634-A6C8-43B3-AFB3-83955F7A332A">
                <CreateFolder />
                <util:PermissionEx User="Everyone" GenericAll="no" GenericExecute="yes" GenericWrite="yes" GenericRead="yes" />
                <util:PermissionEx User="[LogonUser]" Domain="[ComputerName]" GenericAll="yes" />
</Component>
``` 

The update is being tested with the packages generated in Jenkins, but for the moment the issue persists.
![image](https://github.com/wazuh/wazuh/assets/106568370/fbcfdbf4-4e38-492e-a4ab-1e61816fa970)

**Comment by Leoquicenoz** [comment]
## Update

I tested adding permissions in the `InstallerScripts.vbs` file, which is used by several actions inside `wazuh-installer.wxs` to execute functions, with this change was able to generate the `.msi` installer without errors, but after upgrading with this, the issue is still present.

**Comment by Leoquicenoz** [comment]
## Update

Because it is still not clear why the permission is not being enabled in the `ossec-agent` folder, I have been analyzing the `InstallerScripts.vbs` and `wazuh-installer.wxs` files to try to identify if in some later step of the installation these permissions are being overridden, I have tried deleting some parts of the file (which I know should not be deleted, but to be clear if that is where the problem lies), but so far has not generated an effective solution.

**Comment by Leoquicenoz** [comment]
## Update

The `SetPermissions.ps1` file is generated which is executed from the `wazuh-installer.wxs` file, this `.ps1` file contains the commands: 
```powershell
$existingAcl = Get-Acl -Path 'C:\Program Files (x86)\ossec-agent'.
$permissions = $env:username, 'Read,Modify', 'ContainerInherit,ObjectInherit', 'None', 'Allow'
$rule = New-Object -TypeName System.Security.AccessControl.FileSystemAccessRule -ArgumentList $permissions
$existingAcl.SetAccessRule($rule)
$existingAcl | Set-Acl -Path 'C:\Program Files (x86)\ossec-agent'
``` 
Running them manually we found that they solve the issue, as we have not been able to get this result when running the `.msi` file, we tried 2 things: 

1. Generate from `SetPermissions.ps1` a file that would be saved on the desktop and that would serve us to be sure that if you managed to run the script in powershell. (**no success**)
2. Generate an installation log with the command `msiexec /i "installer.msi" /l*v "log.log"` (successful).
In this log I could observe that I have an error in the form in which I am executing the `SetPermissions.ps1` file, since it is taking as location the folder `C:\Program Files (x86)\ossec-agent` and evidently this file is not in this location.

**Comment by Leoquicenoz** [comment]
## Update

The necessary modifications are made so that the permissions are granted when the Windows agent is upgraded.

The PR and the review are pending

**Comment by Leoquicenoz** [comment]
The ETA is delayed because the review of the proposed solution was not completed on time.

**Comment by Leoquicenoz** [comment]
The ETA is delayed because the proposed solution is not adequate and a higher priority issue is being worked on.

**Comment by aritosteles** [comment]
Gathering knowledge and replicating issue in local environment

**Comment by aritosteles** [comment]
- _Identified probable cause of the issue:_ files are inheriting folder's permissions at the time they are created. Folder permissions are being set in the last moment before finishing the installation process.
- _Tentative solution to be evaluated_: set folder permissions right at the beginning of the installation process and remove condition to bypass this step if the application is already installed or being upgraded.

**Comment by aritosteles** [comment]
## Implemented solution:

Modified InstallerScripts.vbs and wazuh-installer.wxs.

- Added a custom function that sets file permissions.
- Added function SetPermissions() to InstallerScripts.vbs. This function enables inheritance for the installation folder and sets Read and Execute permission for the folder and all its files and subfolders.
