### ISSUE TITLE
cant add a windows 11 agent

### ISSUE THREAD

**Issue by jdpbofficial** [wazuh/wazuh#20765]
trying to add a windows 11 agent but it wont register, linux in the other hand work's

**Comment by davidcr01** [comment]
Hello. I would like to know more information about your problem in order to help you as best as possible. A few questions here:
- What specific OS is the Linux manager?
- What specific version of Wazuh are you installing?
- What specific OS is the Windows 11 agent?
- Are you following the [Wazuh agent installation on Windows endpoints](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-windows.html)?
- Both machines can connect to each other? Did you try to execute a telnet command from the Windows agent to the Linux manager to check if they can connect through the network?

If your Windows 11 is the Sandbox version, we have a known issue that we are currently working on: https://github.com/wazuh/wazuh/issues/15586
