### ISSUE TITLE
Vulnerability detection

### ISSUE THREAD

**Issue by Piyush1786** [wazuh/wazuh#20770]
Can we remove the implicit query which is by default in the wazuh, So that we can see the vulnerability detection on the wazuh dashboard for the more clear picture of the vulnerabilities in the wazuh-manager

**Comment by Piyush1786** [comment]
Hello Pereyra,

As you can see in the screenshot I shared, On the filter tab there is an implicit query which is by default filters out the id of wazuh-manager. 
that is id!=000 --> this is wazuh-manager's id.
When I see raw logs on wazuh-manager (ossec.logs) in that log file i can see agent with id 000 is also being scanned for any vulnerabilities, If it is getting scanned then it should show on the dashboard as well.
There is no option to filter the agent with id 000 on vulnerability detection dashboard and agent dashboard.
It would be really great if we can see the vulnerabilities on wazuh-manager server as this will help us keep the enviroment safe and we can keep the attack surface to the minimal.

**Comment by Piyush1786** [comment]
![image](https://github.com/wazuh/wazuh/assets/69197372/d5caaa96-39c8-4f5e-a6b8-f1d7fb3973be)

**Comment by pereyra-m** [comment]
Hi @Piyush1786 !
Thank you for the clarification.

As you point out, the manager is being scanned by vulnerability detector. However, the agent ID `000` is being intentionally left out because in cluster configuration there would be many managers with the same ID.

Remember that any package that is inserted in the inventory generates an alert that you can look for (https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/how-it-works.html#alert-generation) and that you can query the agents' vulnerability inventory with the API if you have Wazuh up to v4.6 (https://documentation.wazuh.com/4.6/user-manual/api/reference.html#operation/api.controllers.vulnerability_controller.get_vulnerability_agent).

**Comment by Piyush1786** [comment]
Hello pereyra,

I want to see the logs on the wazuh dashboard only, i want this implicit query to get removed. If there is any way.

**Comment by pereyra-m** [comment]
@Piyush1786 , that isn't possible.
That's why I offered some alternatives.

You always can create a new issue to request that feature, the team will analyze it as soon as possible
https://github.com/wazuh/wazuh/issues/new?assignees=&labels=&projects=&template=default.md&title=

Regards.
