### ISSUE TITLE
wazuh-agent-4.7.0-1.msi fails to install

### ISSUE THREAD

**Issue by dMailonG** [wazuh/wazuh#20775]
|4.7.0-1|Agent|MSI|Windows 11 22H2 and Windows 10 1809|

Installing the agent via GUI or CLI fails, even though it reports otherwise.
("Fails": no files are copied, no service is created etc.)

I've attached the output of `msiexec.exe /i wazuh-agent-4.7.0-1.msi /q WAZUH_MANAGER='redacted.local' WAZUH_REGISTRATION_SERVER='redacted.local' /l*v log_wzh.txt /qf`.

[log_wzh.zip](https://github.com/wazuh/wazuh/files/13660957/log_wzh.zip)

**Comment by vikman90** [comment]
@dMailonG Thank you for reporting this issue, and my apologies for the delay in addressing it.

Our testing for version 4.7.0 included clean installations and upgrades on Windows Server. Additionally, I have tested a clean installation on Windows 11 23H2, which completed successfully.

Since we have released newer versions, I’d like to ask if you’ve had a chance to try a more recent release, such as 4.9.2 or 4.10.0.

Based on your comment in issue https://github.com/wazuh/wazuh-agent/issues/341, it seems possible that remnants of a previous installation might be causing this problem. Cleaning the Windows Registry might help resolve the issue.

Regarding the errors in the log:
```
SchedSecureObjectsRollback:  Error 0x8007007b: Unable to schedule rollback for object:
SchedSecureObjectsRollback:  Failed to store ACL rollback information with error 0x8007007b - continuing
```
and
```
DEBUG: Error 2896:  Executing action LaunchUI failed.
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2896. The arguments are: LaunchUI, ,
```

These errors suggest that folder and file permissions may be causing the issue. This aligns with a known issue fixed in 4.9.0 regarding permission assignments for the `ossec-agent` folder and the `ossec.conf` file:
- https://github.com/wazuh/wazuh/issues/20727

Furthermore, in version 4.10.0, we implemented an updated installation directory permission scheme:
- https://github.com/wazuh/wazuh/issues/24078

To address the issue, I recommend the following steps:

1. **Verify Folder and User Permissions**
   - Ensure that the folder `C:\Program Files (x86)\ossec-agent` does not exist.
   - Confirm that the `SYSTEM` user account has full-control permissions for subfolders under `C:\Program Files (x86)`.
2. **Perform a Clean Installation**
   - Delete the folder `C:\Program Files (x86)\ossec-agent` if it exists.
   - Check for existing Wazuh Agent installations by running this PowerShell command:
     ```powershell
     Get-CimInstance -Class Win32_Product -Filter "Name = 'Wazuh Agent'" | Format-Table -AutoSize
     ```
   - If any installations are found, manually remove related registry keys using `regedit.exe`. Look for keys under:
     ```
     HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\<GUID>
     ```

Finally, if possible, please try installing Wazuh Agent version 4.9.2 or later and let us know if the issue persists. These versions include fixes that might resolve the problem you’re experiencing.

Thank you for your patience and for helping us improve!

Best regards,
