### ISSUE TITLE
Increased VM usage by `wazuh-modulesd` and `wazuh-syscheckd` in CentOS Agent

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#20861]
|Wazuh version|Component|Type|Platform|
|---|---|---|---|
| 4.8.0-alpha1| modulesd| Agent| Centos |

# Description

 During Footprint tests https://github.com/wazuh/wazuh/issues/20819, an increase in VMs usage by `wazuh-modulesd` and `wazuh-syscheckd` has been found in the CentOS agent, in comparison with [4.7.0-rc1](https://github.com/wazuh/wazuh/issues/20288)
 
_Note: No anomalies were found in the logs._
 
I have attached plots with versions.
 
![imagen](https://github.com/wazuh/wazuh/assets/3978434/ae8f6fd8-66e4-4794-8756-798b44d52a46)

**Comment by LucioDonda** [comment]
The VMS change is seen in **_wazuh-modulesd_** (**_syscheckd_** doesn't grow significantly) going from **330K** to **600K** (average values as seen in plots).
But checking the previous footprint tests, it can be seen a similar behavior.

4.7.0 Alpha 2 (**620K**)  
![VMS470Alpha2](https://github.com/wazuh/wazuh/assets/95248059/9a9455d3-b5cb-4ca6-9662-fc44b3ef890e)

4.6.0 RC2 (**370K**)
![VMS460Rc2](https://github.com/wazuh/wazuh/assets/95248059/83bc682b-d8ac-42d8-880c-aa5b473c4835)

4.6.0 RC1 (**500K**)
![VMS460RC1](https://github.com/wazuh/wazuh/assets/95248059/41065a7b-1401-4b69-8ed3-95824e43aeab)

We should check if the “Virtual Memory Size” ( `the total amount of virtual memory used by the process. On UNIX, it matches “top“‘s VIRT column` According to [psutil documentation](https://psutil.readthedocs.io/en/latest/#psutil.Process.io_counters)) can be directly compared for each version change.
Besides the above, I'll continue digging deeper into the code changes.

**Comment by vikman90** [comment]
**RSS is a measure of how much memory a process is consuming in our physical RAM**, to load all of its pages after its execution. This includes memory allocated from shared libraries (given they are still present in memory), all heap, and stack memory. However, RSS is not an accurate measure of the total memory processes are consuming, because it does not include memory consumed by libraries that were swapped out.

On the other hand, **VSZ is a measure of how much memory a process can access after its execution**. This includes swapped memory, the memory from external libraries, and allocated memory that’s not used. Most modern Linux-based OSes utilize demand paging which means they only bring pages into memory once a program attempts to use them. VSZ is not an accurate measure of how much memory is being consumed, but rather an estimation of the total amount of memory a process can consume within its life cycle.

Therefore, please **ignore the VMS** if RSS is coherent.

## Reference

- [Difference Between Resident Set Size and Virtual Memory Size](https://www.baeldung.com/linux/resident-set-vs-virtual-memory-size)
