### ISSUE TITLE
Stepped movements in event graphs and a big increase of vulnerability in dropped events

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#20879]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha1 | Wazuh component | Manager | Packages | CentOS |

Testing [Footprint Metrics - VULNERABILITY-DETECTOR-REGISTER (2.5d)](https://github.com/wazuh/wazuh/issues/20810)

It could be detected a big decrease of vulnerability in dropped events graph comparing it to 4.7.0

4.8.0-alpha1 https://github.com/wazuh/wazuh/issues/20810
![image](https://github.com/wazuh/wazuh/assets/125690423/6ed516bc-1fa1-4f86-a1e3-6b5acb0083d2)

4.7.0-rc1 https://github.com/wazuh/wazuh/issues/20295
![image](https://github.com/wazuh/wazuh/assets/125690423/1017394a-5bbd-4a56-9ee6-1afb60218f21)

On the other hand, it is possible to see big differences in the number and stepped shaped movements in written stats and number_events plots:
4.8.0-alpha1 https://github.com/wazuh/wazuh/issues/20810
![image](https://github.com/wazuh/wazuh/assets/125690423/50b72d28-2b6c-410c-8de0-e79cf8f0108b)
![image](https://github.com/wazuh/wazuh/assets/125690423/96384be0-c451-408d-a38e-6178c42200f5)

4.7.0-rc1 https://github.com/wazuh/wazuh/issues/20295
![image](https://github.com/wazuh/wazuh/assets/125690423/9a2f7ed1-3ae2-4335-9000-3437d5dbbdfe)
![image](https://github.com/wazuh/wazuh/assets/125690423/348f7f76-96dd-4be3-9444-778c2fbee3f7)

Further research should be done

**Comment by LucioDonda** [comment]
Regarding dropped events, there's no difference between the last footprint tests and this one; in both cases, this is zero, so I guess that there's a typo in the title of the issue.
Analyzing decoded events, there's a significant change:
4.8.0 reaches 32.000 events processes and 4.7.0 just reaches 3.000
But as pointed out on another [issue](https://github.com/wazuh/wazuh/issues/20875) of this footprint test, I guessed that the best way to continue would be to wait for the next release (especially waiting for this [epic ](https://github.com/wazuh/wazuh/issues/14153)to finish) because there's a significant change involving a vulnerability detector and any bug found will be outdated because of it.
More info [here](https://github.com/wazuh/wazuh/issues/20875) 
c.c. @cborla
