### ISSUE TITLE
Agentd buffered events spike in Centos Agent

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#20873]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha1 | Wazuh component | Agent| Packages | Centos|

Testing:

Footprint Metrics - [Release 4.8.0 - Alpha 1 - Footprint Metrics - SCA (2.5d)](https://github.com/wazuh/wazuh/issues/20815)

A large spike in Agentd buffered events is detected going from 2 to 5.

- 4.8.0 agent 
 ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4669-3600m/B4669_agent_centos/plots/Test_stress_B4669_centos_agentd_state_AgentD_Number_of_events_buffered.png)
- [4.7.0 agent](https://github.com/wazuh/wazuh/issues/20309)
 ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.1/B4600-3600m/B4600_agent_centos/plots/Test_stress_B4600_centos_agentd_state_AgentD_Number_of_events_buffered.png)

**Comment by LucioDonda** [comment]
Based on what can be seen in the logs, although there are more buffered events in that specific moment:
![image](https://github.com/wazuh/wazuh/assets/95248059/b8372ff8-fd54-41ed-8331-63654a3d7fc6)
There are no dropped events in the whole test.
Buffering events is a [normal behavior](https://documentation.wazuh.com/current/user-manual/agents/antiflooding.html), the agent cannot send them to the manager so it saves a convenient time for sending them. This can happen when the agent is occupied while doing something else or when the OS has no resources for the service. Sadly there's no message, warning, log, or status event during the whole test that can shed some light on what happened at that exact moment.
Besides that, I wouldn't say this is due to a bug or malfunction.  

Additional comment:
During the test of [4.7.0 RC1](https://github.com/wazuh/wazuh/issues/20305) it can be seen that the buffered events reach 6 not causing any issue either, but during the same test, dropped events are deeply analyzed.
![4 7 0](https://github.com/wazuh/wazuh/assets/95248059/b440093d-cdec-4d11-afb2-e0f97214bea6)

c.c. @cborla
