### ISSUE TITLE
Wazuh WinAgent.exe is being flagged as Malware by many AV vendors

### ISSUE THREAD

**Issue by spaceB0x** [wazuh/wazuh#210]
We were having problems with the Windows agent 2.1.1. and 2.0.1 have been flagged and quarantined as malware by many AV providers including Windows Defender. A link for the Virus total hash can be found here: https://www.virustotal.com/#/file/7d07ab015432e62301e46be75842a6f73b9fb2f2b0892cc43b021a16ffaa6e7c/detection

Windows Defender is not actually in this list, but we can verify that it is analyzing the agent as a Trojan. The same for version 2.0.1 as well.

**Comment by vikman90** [comment]
Hi @spaceB0x,

We are aware of this problem. We are sure this is a false positive and have reported it to some antivirus companies. In fact, we analyzed the latest v2.1.1-2 version just after compiling it and it reported 0 viruses. Some days later it reported 3 viruses.

If you have downloaded the Wazuh Windows Agent installer from the link at https://documentation.wazuh.com/current/installation-guide/packages-list/index.html, you are able to check its MD5 hash with the sum that appears next to the link.

We are investigating why some companies detect the Wazuh installer as a virus and working on a new installation system in order to prevent this problem in the future.

Thanks for reporting.
Kind regards.

**Comment by spaceB0x** [comment]
Great Thank you :)

**Comment by erseco** [comment]
Hello, we generated a new **msi based** installer that should solve all these problems and will not show false AV positives

You can download it from this URL: http://packages.wazuh.com/windows/wazuh-agent-2.1.1-1.msi

Please tell us if it solves your problem.

Best regards!
