### ISSUE TITLE
[Feature Request] Autoremove agents after a period of time

### ISSUE THREAD

**Issue by bremoi** [wazuh/wazuh#21029]
Hi,

It could be interesting to autoremove agents after a, ideally configurable, period of time.

Regards

**Comment by bremoi** [comment]
Hi @MiguelazoDS,

I mean after a period of time that the agent doesn't communicate with Wazuh, it is automatically removed from Wazuh, not from the endpoint. If the endpoint is up againt it reappears again in Wazuh.
Actually, this is a functioning in particular for products under licence, but in the Wazuh contexte it could help to have a clearer inventory.

Don't hesitate if you need more details.

**Comment by bremoi** [comment]
Hi @MiguelazoDS,

I'm not sur this may in conflict. You could add a option to automatically delete agents from Manager and livening the possibility to re-registering again or not the agent.

**Comment by MiguelazoDS** [comment]
Hi Bremoi, 

With the options I mentioned before we want to avoid re-registering the agent, take a look at https://github.com/wazuh/wazuh/issues/9549. Giving the user such control may override this behavior, we don't want agents re-registering just because it was disconnected for some time. We want to prevent the agent from changing its ID often giving duplicate databases and triggering database synchronization, without mentioning that in a cluster environment, this may be worse. 
I mean it's not a trivial implementation, this will be evaluated and if needed it will be in our road map for future implementation.

**Comment by bremoi** [comment]
Hi @MiguelazoDS,

Indeed, that's it :) Thanks

If I correctly understand, after at most 6 days a disconnected agent is automatically removed from Wazuh, but if the agent tries to reconnect after this period, it automatically reappears in Wazuh. Is it right?

**Comment by MiguelazoDS** [comment]
Thanks for your patience, have a good day!

**Comment by bremoi** [comment]
Hi @MiguelazoDS,

I'm sorry, I juste reopen to ask if it could be interesting to increase the avaiable value of `monitord.delete_old_agents` to more days or months?

Thank you

**Comment by bremoi** [comment]
UP

**Comment by MiguelazoDS** [comment]
Wow, I overlooked this completely. Creating a feature request to increase the limit will make you wait even longer. The easier way is to modify the option yourself according to your needs and install it from sources. 

The line you need to change is here 
https://github.com/wazuh/wazuh/blob/5d1857bf41f0bfffe9ccd5c1c8d2c35aca9e8b8a/src/monitord/monitord.c#L218

This is the section details the steps to compile and install the Wazuh manager 
https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-server/index.html

**Comment by bremoi** [comment]
Hi,

Thanks a lot for your reply.

Have a nice day.

**Comment by MiguelazoDS** [comment]
Let us know how it goes. Regards!
