### ISSUE TITLE
Increase use of resources of agentd and modulesd in ROOTCHECK stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#21115]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---| 
| 4.7.2-rc1 | Wazuh component | Agent  | Packages | CentOS Agent  |

Testing [Footprint Metrics - ROOTCHECK (2.5d) (2.5d)](https://github.com/wazuh/wazuh/issues/21076)

Manager

PSS, RSS, USS: increase of agentd and modulesd
VMS: decrease of modulesd

4.7.2-rc1 https://github.com/wazuh/wazuh/issues/21076
![image](https://github.com/wazuh/wazuh/assets/125690423/a3749690-76b2-4efc-8790-c649c157c258)
![image](https://github.com/wazuh/wazuh/assets/125690423/52c2c5c2-12e5-4d4e-9575-889cdb07a5f9)
![image](https://github.com/wazuh/wazuh/assets/125690423/7f732f75-c7e9-493f-b82a-e2aae0c631c1)
![image](https://github.com/wazuh/wazuh/assets/125690423/b4f0fc54-fea0-4b89-b69f-61bb96fb293e)

4.7.1-rc2 https://github.com/wazuh/wazuh/issues/20840
![image](https://github.com/wazuh/wazuh/assets/125690423/79ce3b45-019d-4974-993b-5aeead5efd61)
![image](https://github.com/wazuh/wazuh/assets/125690423/ade54311-9f4c-46f3-a8f6-83b9fc270534)
![image](https://github.com/wazuh/wazuh/assets/125690423/2a37528b-c7b6-4d20-8556-3741d69b9152)
![image](https://github.com/wazuh/wazuh/assets/125690423/8f26cb69-de1d-4f04-b07b-3a9e0ce66b02)

Further research is required

**Comment by nbertoldo** [comment]
### Conclusion
The reports have been analysed, and although there is a clear increase in the use of `agentd` and `modulesd` resources, the values remain constant within reasonable values and there are no anomalies in the operation of the modules. Neither have there been any changes between versions that could cause these differences. Therefore, it is assumed that this is a circumstantial behaviour that does not affect the agent's performance.

**Comment by cborla** [comment]
**RSS is a measure of how much memory a process is consuming in our physical RAM**, to load all of its pages after its execution. This includes memory allocated from shared libraries (given they are still present in memory), all heap, and stack memory. However, RSS is not an accurate measure of the total memory processes are consuming, because it does not include memory consumed by libraries that were swapped out.

On the other hand, **VSZ is a measure of how much memory a process can access after its execution**. This includes swapped memory, the memory from external libraries, and allocated memory that’s not used. Most modern Linux-based OSes utilize demand paging which means they only bring pages into memory once a program attempts to use them. VSZ is not an accurate measure of how much memory is being consumed, but rather an estimation of the total amount of memory a process can consume within its life cycle.

Therefore, please **ignore the VMS** if RSS is coherent.

## Reference

- [Difference Between Resident Set Size and Virtual Memory Size](https://www.baeldung.com/linux/resident-set-vs-virtual-memory-size)

**Comment by Dwordcito** [comment]
closed based on the comment: https://github.com/wazuh/wazuh/issues/21115#issuecomment-1870570563
