### ISSUE TITLE
create deb or rpm agent packet from source code 

### ISSUE THREAD

**Issue by niodess** [wazuh/wazuh#21302]
Hi
I want to create deb agent packet from source code. Is it possible?
I've tried to use make but it doesn't help for me

**Comment by juliancnn** [comment]
Hello!

Absolutely, you can create a `.deb` package for the Wazuh agent from the source code. We have a comprehensive guide that explains the process of assembling each package locally. This guide will walk you through the steps and allow you to compile any branch of any package.

You can find the detailed instructions here: [Packaging Wazuh - Assembling Packages Locally](https://documentation.wazuh.com/current/development/packaging/index.html).

This guide includes an example for Ubuntu, which should be quite helpful: [Generate DEB Package](https://documentation.wazuh.com/current/development/packaging/generate-deb-package.html).

If you encounter any issues or have specific questions during the process, please don't hesitate to reach out. We're here to help!

**Comment by niodess** [comment]
Hi, ty for answer
Unfortunately, I 've tried this method and I got an errors
For example I used a command: sudo ./generate_debian_package.sh -b v4.5.4 --sources "/root/wazuh-4.5.4/" -t agent -a amd64
In txt you can see log
[install.txt](https://github.com/wazuh/wazuh/files/13886044/install.txt)

**Comment by juliancnn** [comment]
Hello,

Thank you for sharing the log file from your attempt to create the `.deb` package. It seems there might be some issues specific to the version you are working with.

To ensure we're on the same page, could you please confirm the branch of the `wazuh-packages` repository you are using? For version 4.5, you should be working with the `v4.5.4` tag/branch of the `wazuh-packages` repository. This is important because each version of Wazuh may have specific packaging requirements or dependencies.

Here is the documentation tailored for version 4.5, which might provide more relevant guidance for your scenario: [Generate DEB Package for 4.5](https://documentation.wazuh.com/4.5/development/packaging/generate-deb-package.html).

Additionally, you can switch between different versions of the documentation by clicking on the version number in the top right corner of the Wazuh documentation website.


![image](https://github.com/wazuh/wazuh/assets/1891958/ef84ae44-6ac4-45ef-a648-6ff55ea1838b)

If you continue to encounter errors, it would be helpful if you could provide more details about the specific errors you're facing. Sometimes, the error messages can give us clues about missing dependencies or configuration issues (OS version, docker, etc)

Please let me know if this solves your problem

**Comment by niodess** [comment]
Hi @juliancnn,
mistake was in incorrect command which I use for building deb package
Shoud use this syntax
 ./generate_debian_package.sh -b v4.5.4 -t agent --packages-branch v4.5.4 --sources %your path% -a amd64 -s /tmp
 instead
 ./generate_debian_package.sh -b v4.5.4 --sources "%your path%" -t agent -a amd64
 These problem was solved, ty
