### ISSUE TITLE
The router module can't process some agent messages due to flatbuffer schema constraint

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#21340]
## Description

A Jenkins test failed showing that there is a field in the schema that doesn't support a negative value
https://github.com/wazuh/wazuh/pull/21329/checks?check_run_id=20360576822

```
2024/01/10 20:51:56 :router: ERROR: Error sending message to provider: Error parsing message, 1: 605: error: invalid number: "-1", constant does not fit [0; 4294967295]
```

The error message doesn't give enough details and this isn't the first time it happens.
We might consider making all the numeric constraints more flexible.

## DoD

- [x] Identify the problematic fields
- [x] Make the required changes
- [x] Add UT
- [x] CI Pass

**Comment by MiguelazoDS** [comment]
# Analysis 

The issue is related to the MTU field. We can see that the field is type INTEGER in the syscollector schema database, 

![image](https://github.com/wazuh/wazuh/assets/13010397/fadb7751-036d-4c9a-8d78-74cb1afdd756)

but the value obtained during Syscollector scan is stored in a uint32 variable, so when the binding occurs it binds a uint32 into a field causing overflow due to int size < uint32 size.
