### ISSUE TITLE
Ossec.conf checksum failed in upgrade tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#21452]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha2 | Wazuh component | Agent | Packages | Linux |

## Description

During the issue https://github.com/wazuh/wazuh/issues/21390, multiple Linux OSs tests failed in the `upgrade_manager_test.py::test_check_ossec_conf `.

- In the listed OSs failed:
   - Tumbleweed
   - Redhat 7, 8
   - Amazon Linux 1 and 2
   - Ubuntu Trusty, Xenial, Focal, Bionic
   - Centos 8, 7
   - Debian Buster, Stretch
   - Fedora 36, 35, 34, 32, 31
   - Oracle Linux 8

## Evidence example from OpenSUSE Tumbleweed

```
============================= test session starts ==============================
platform linux -- Python 3.8.2, pytest-5.4.1, py-1.9.0, pluggy-0.13.1 -- /usr/testing/bin/python3.8
cachedir: .pytest_cache
rootdir: /upgrade_manager
collecting ... collected 19 items

upgrade_manager_test.py::test_check_version PASSED                       [  5%]
upgrade_manager_test.py::test_check_process_clusterd PASSED              [ 10%]
upgrade_manager_test.py::test_check_process_modulesd PASSED              [ 15%]
upgrade_manager_test.py::test_check_process_monitord PASSED              [ 21%]
upgrade_manager_test.py::test_check_process_logcollector PASSED          [ 26%]
upgrade_manager_test.py::test_check_process_remoted PASSED               [ 31%]
upgrade_manager_test.py::test_check_process_syscheckd PASSED             [ 36%]
upgrade_manager_test.py::test_check_process_analysisd PASSED             [ 42%]
upgrade_manager_test.py::test_check_process_maild PASSED                 [ 47%]
upgrade_manager_test.py::test_check_process_execd PASSED                 [ 52%]
upgrade_manager_test.py::test_check_process_wazuhdb PASSED               [ 57%]
upgrade_manager_test.py::test_check_log_errors PASSED                    [ 63%]
upgrade_manager_test.py::test_check_system_ossec_conf PASSED             [ 68%]
upgrade_manager_test.py::test_check_ossec_conf FAILED                    [ 73%]
upgrade_manager_test.py::test_check_client_keys_conf PASSED              [ 78%]
upgrade_manager_test.py::test_check_local_internal_options_conf PASSED   [ 84%]
upgrade_manager_test.py::test_check_local_decoder_conf PASSED            [ 89%]
upgrade_manager_test.py::test_check_local_rules_conf PASSED              [ 94%]
upgrade_manager_test.py::test_check_agent_conf PASSED                    [100%]

=================================== FAILURES ===================================
____________________________ test_check_ossec_conf _____________________________
upgrade_manager_test.py:194: in test_check_ossec_conf
    assert hashlib.sha256(conf_file_data).hexdigest() == checksums['ossec_conf'], assert_description['files']['check_ossec_conf_checksum']
E   AssertionError: The checksum file don't match with the checksum generated before upgrading
E   assert '4e720108a8d9...6149d6fc28b7d' == '56f49d68839b...30865515d843c'
E     - 56f49d68839bbc53c8a0816dad0e92bb3db63d975086ad786d530865515d843c
E     + 4e720108a8d9690a6858bd2e66840b9b0e1820aa751da184c1a6149d6fc28b7d
=============================== warnings summary ===============================
upgrade_manager_test.py:127
  /upgrade_manager/upgrade_manager_test.py:127: DeprecationWarning: invalid escape sequence \w
    daemonRegex = '\w+-\w+:'

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=========================== short test summary info ============================
FAILED upgrade_manager_test.py::test_check_ossec_conf - AssertionError: The c...
=================== 1 failed, 18 passed, 1 warning in 0.12s ====================
```

Further research is needed

**Comment by LucioDonda** [comment]
After some analysis and checking with other teammates, I was able to conclude that the main cause of this test failure is this change in the [postinst script](https://github.com/wazuh/wazuh-packages/blob/1c427881420a56d0170006d0f90984e3cfb8146d/debs/SPECS/wazuh-manager/debian/postinst#L245:L248):

```
    # Ensure that the 'Indexer' is configured
    CONFIG_INDEXER_TEMPLATE="${SCRIPTS_DIR}/etc/templates/config/generic/wodle-indexer.manager.template"
    . ${SCRIPTS_DIR}/src/init/update-indexer.sh
    updateIndexerTemplate "${DIR}/etc/ossec.conf" $CONFIG_INDEXER_TEMPLATE
```

This was implemented due to the new vulnerability detector fields (`<indexer>`) on the _**ossec.conf**_ (4.8.0). [Link](https://github.com/wazuh/wazuh-packages/issues/2683) to the _.deb_ issue and [link](https://github.com/wazuh/wazuh-packages/issues/2706) to the _.rpm_ one.

The base idea of [this test](https://github.com/wazuh/wazuh-jenkins/blob/750e25b5b81ad66cbebd6ccfb3dae96e7c6f094d/quality/tests/generic/03-upgrade/linux/test/upgrade_manager_test.py#L189) is to compare both **_ossec.conf_** files (before and after the upgrade), if the checksums are equal then the file didn't suffer any change. Adding the above-mentioned block will make a change and differ the result of the comparison but this doesn't mean that the change is causing any issues.

If, as I think, this change isn't causing any other issue, modifying the test with an exception will be the fastest way of solving this.

**Comment by LucioDonda** [comment]
Hi @Damian-Mangold 
Do we have an update on this issue? Is it possible to add an exception on the tests?
TIA!

**Comment by cborla** [comment]
Related https://github.com/wazuh/wazuh-jenkins/issues/6179

**Comment by Damian-Mangold** [comment]
It was decided to close the issue since the analysis was concluded. A decision has been made regarding the proposed changes, and these will be implemented in issue: [Add version exception: test_check_ossec_conf](https://github.com/wazuh/wazuh-jenkins/issues/6179#top)
