### ISSUE TITLE
App loading logo and wazuh dashboard home logo in Wazuh 4.8.0 - Alpha 2 - E2E UX tests - Change custom logos 

### ISSUE THREAD

**Issue by IsExec** [wazuh/wazuh#21469]
### Describe the bug

During `4.8.0-alpha2` UX testing issue https://github.com/wazuh/wazuh/issues/21369, the following issues were discovered:  

1. The dashboard GUI customization.logo.app doesn't change the app loading logo as expected.
2. Modifying the OpenseacrhDashboards.branding in opensearch_dashboards.yml changes the logo of the loading and Wazuh dashboard home logo together and with the same image

### To reproduce

1. Launch the 4.8.0 Alpha 2 dashboard
2. Log in
3. Indexer/dashboard management > App Settings
4. Custom branding > App main logo
5. Upload an image that fits the specification under customization.logo.app
6. App logo remains unchanged

### Evidence

![image](https://github.com/wazuh/wazuh/assets/121132106/88183d05-6fb4-44eb-9003-7406953e2f85)

### The App loading logo remains unchanged

![image](https://github.com/wazuh/wazuh/assets/121132106/e373f4d6-2686-4444-84cc-7575f6275a8d)

### To Reproduce

1. Install and config Wazuh dashboard
2. Edit the /etc/wazuh-dashboard/opensearch_dashboards.yml file
3. Specify the source of the image opensearchDashboards.branding:
4. Restart the Wazuh dashboard service
5. App loading logo and wazuh dashboard home logo changes instead of just the wazuh dashboard home logo from the documentation https://documentation-dev.wazuh.com/v4.8.0-alpha2/user-manual/wazuh-dashboard/custom-branding.html

### Editing the opensearch_dashboards.yml changes both the App loading logo and the Wazuh dashboard home logo

```
root@dashboard:/home/wazuh# nano /etc/wazuh-dashboard/opensearch_dashboards.yml
root@dashboard:/home/wazuh# grep -A4 "opensearchDashboards.branding:" /etc/wazuh-dashboard/opensearch_dashboards.yml
opensearchDashboards.branding:
   mark:
      defaultUrl: "https://anydomain.com/logo.svg"
      darkModeUrl: "https://anydomain.com/logo.svg"
root@dashboard:/home/wazuh#
```

**Comment by Desvelao** [comment]
Hi, the `customization.logo.app` setting that can be configured through the `App Settings` application or `wazuh.yml` lets to customize the logo that is only displayed in applications related to Wazuh. This can be more confusing in 4.8.0 because the `Wazuh` plugin was split into multiple applications.

The logo you wanted to change, is the loading logo of the Wazuh dashboard, which can be changed through the `opensearch_dashboards.yml`
https://github.com/wazuh/wazuh/assets/121132106/e373f4d6-2686-4444-84cc-7575f6275a8d
