### ISSUE TITLE
All Vulnerabilites "untriaged" on Debian 

### ISSUE THREAD

**Issue by eglyn** [wazuh/wazuh#21473]
Hi all :)

Don't know if it's since the last update, but all vulverabilitites on Debian 11 / 12 are shown as "untriaged", it looks like this: 

![image](https://github.com/wazuh/wazuh/assets/24936778/1f4e1757-bf7f-4768-b98e-28c1f392cdff)

Does last update break something in configuration ? 

I'm on the 4.7.2 release, 

Thx :)

**Comment by MarcelKemp** [comment]
Hi @eglyn,

This problem is not a bug. It happens because _Debian_ doesn't have any fix for that component (because it's not supported anymore, or simply because they don't have the fix yet). So all the vulnerabilities that affect the agent, but that still doesn't have any patch (_`Unfixed`_), appear with the `Untriaged` condition.

Here is the first example:
- https://security-tracker.debian.org/tracker/CVE-2023-38470
![Screenshot from 2024-02-05 12-40-53](https://github.com/wazuh/wazuh/assets/37207742/80573e7c-d945-4c0f-bcbf-bb30eac5e98c)

> You can check with OVAL all vulnerabilities to find out why.

I hope it will be helpful for you.

**Comment by MarcelKemp** [comment]
I proceed to close the issue, as it seems to be resolved. 
If not, please feel free to reopen it and I will try to help you.

**Comment by Berensek** [comment]
hello,
i'm facing the same issue and i found a post in the forum saying that Wazuh is supposed to use the NVD severity score https://groups.google.com/g/wazuh/c/gLHgJg9ACDo
which seems to be a very good idea. it allow users to have a clear view on the impact on the system.
