### ISSUE TITLE
How to send wazuh log on  splunk Dashboard 

### ISSUE THREAD

**Issue by gyanprakashsahu** [wazuh/wazuh#2150]
Hi Wazuh Team,

We are using wazuh in cluster and all wazuh application are running on docker. 
We want to forward all wazuh log to Splunk Dashboard.
Let us know how to we do that it technically.

**Comment by manuasir** [comment]
Hello @gyanprakashsahu ,

The main idea is to monitor the `alerts.json` file on each `manager` node of your cluster. That is, the `master` node and the `workers` must have a Splunk Forwarder installed and configured on them in order to send the data to the Splunk Indexer or the Splunk Search Head if you have a clustered Splunk architecture.You can check [this guide](https://documentation.wazuh.com/current/installation-guide/installing-splunk/splunk_forwarder.html) for more details.

Just be sure of the connectivity between instances is correct, and also that all the used ports are properly opened. According to the [documentation](https://documentation.wazuh.com/current/getting-started/architecture.html#splunk), the involved ports are the following:

![image](https://user-images.githubusercontent.com/10210567/50344830-02ca7280-052d-11e9-957e-f023402408c1.png)


Let me know if you have any doubt about the process.

Cheers,
Manuel

**Comment by gyanprakashsahu** [comment]
Thanks for update
