### ISSUE TITLE
Decrease and changes in the pattern of modulesd in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#21521]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha2 | Wazuh | Manager | Packages | CentOS Manager |

Testing: [Footprint Metrics - VULNERABILITY-DETECTOR-REGISTER ](https://github.com/wazuh/wazuh/issues/21487)

The following significant changes were observed in a context where VD Register modules have undergone dramatic changes. In most cases, a significant decrease in modules in the Manager was detected, and their pattern has changed.

### CPU, Disk, W/R Ops
CPU: **Big decrease of modulesd** fluctuation values (compared to 4.7.2-rc2 and 4.8.0-alpha1)
Disk: **Big decrease of modulesd** (compared to 4.7.2-rc2 and 4.8.0-alpha1)
Disk_read: **Big decrease of modulesd** value, little increase of db (compared to 4.7.2-rc2 and 4.8.0-alpha1)  
Disk_written: **Big decrease of modulesd** value (compared to 4.7.2-rc2 and 4.8.0-alpha1)
Write_Ops: **Big decrease of modulesd** 
Read_Ops: **Big decrease of modulesd**

[v4.8.0-alpha2](https://github.com/wazuh/wazuh/issues/21487) 
![image](https://github.com/wazuh/wazuh/assets/125690423/eb6360ba-f6ba-4174-a5e6-7e6d62f74958)
![image](https://github.com/wazuh/wazuh/assets/125690423/900c1511-0cb4-409c-a6df-518fd714d868)
![image](https://github.com/wazuh/wazuh/assets/125690423/aba84478-e63f-4160-9d35-3af0d324e5a9)
![image](https://github.com/wazuh/wazuh/assets/125690423/182bd575-c3c3-4a83-861a-f83d66ea1850)
![image](https://github.com/wazuh/wazuh/assets/125690423/17eaaee5-a79c-4fee-a542-7391132de666)
![image](https://github.com/wazuh/wazuh/assets/125690423/e4701f77-5c8b-4e90-a0d0-16f9ba6fc1db)

[v4.7.2-rc2](https://github.com/wazuh/wazuh/issues/21277) 
![image](https://github.com/wazuh/wazuh/assets/125690423/05bbb933-1fc3-4ef0-98d1-bd43929892a4)
![image](https://github.com/wazuh/wazuh/assets/125690423/4e662bbb-ae65-4228-9f51-6af359923622)
![image](https://github.com/wazuh/wazuh/assets/125690423/3855e41e-06bb-48da-88c0-bfe54219a9f8)
![image](https://github.com/wazuh/wazuh/assets/125690423/9cef8c5d-a2fc-45b3-962c-e0dfdf5b285e)
![image](https://github.com/wazuh/wazuh/assets/125690423/8141772e-5240-42f5-b766-98bbaebe8e75)
![image](https://github.com/wazuh/wazuh/assets/125690423/a8a57e74-f4b9-44b0-bbad-164dd46d9b2d)

[v4.8.0-alpha1](https://github.com/wazuh/wazuh/issues/20810) 
![image](https://github.com/wazuh/wazuh/assets/125690423/99af70f2-7fa6-407e-a203-743010229b9f)
![image](https://github.com/wazuh/wazuh/assets/125690423/7f8788a9-09ed-4a5c-9728-d224c0de7d79)
![image](https://github.com/wazuh/wazuh/assets/125690423/fcaf7f30-cb10-4183-bb58-e5c1dea6eb7e)
![image](https://github.com/wazuh/wazuh/assets/125690423/d452ca3b-9dc5-4192-839f-c50048d7c200)
![image](https://github.com/wazuh/wazuh/assets/125690423/2d532576-df18-4982-8201-a0806718a20f)
![image](https://github.com/wazuh/wazuh/assets/125690423/d0fa8761-39a8-40d6-b252-5a78384b4959)

### RSS, PSS, USS, VMS
PSS, RSS, USS: modulesd **pattern has changed** dramatically, however, its level is similar (4.8.0-alpha1) or a little bit lower (4.7.2-rc2), analysisd has decreased its value (4.8.0-alpha1) and it is similar to (4.7.2-rc2)

[v4.8.0-alpha2](https://github.com/wazuh/wazuh/issues/21487) 
![image](https://github.com/wazuh/wazuh/assets/125690423/968b04a1-e23a-41f9-906a-c0b07301d491)
![image](https://github.com/wazuh/wazuh/assets/125690423/29a63fbb-a520-400f-80ba-fc95b39e76ff)
![image](https://github.com/wazuh/wazuh/assets/125690423/bb73ef56-3226-4757-a415-838a9eea92e7)

[v4.7.2-rc2](https://github.com/wazuh/wazuh/issues/21277) 
![image](https://github.com/wazuh/wazuh/assets/125690423/994d4ddd-101b-4ece-852d-46b298faf12a)
![image](https://github.com/wazuh/wazuh/assets/125690423/91857217-ba04-4916-a858-8a9259c37017)
![image](https://github.com/wazuh/wazuh/assets/125690423/52ce20ce-aea0-4553-99fa-12422eb6ea3c)

[v4.8.0-alpha1](https://github.com/wazuh/wazuh/issues/20810) 
![image](https://github.com/wazuh/wazuh/assets/125690423/c4500d83-18ad-438e-9cc1-3b80909719cc)
![image](https://github.com/wazuh/wazuh/assets/125690423/97722d4f-7464-486b-b0c0-53a450ba8cd6)
![image](https://github.com/wazuh/wazuh/assets/125690423/d5e39570-1f2e-4b74-a5b1-294846ef6073)

### Decoded Events

Decoded_events: **big decrease in decoded events from vulnerability**

[v4.8.0-alpha2](https://github.com/wazuh/wazuh/issues/21487) 
![image](https://github.com/wazuh/wazuh/assets/125690423/1cea2265-4918-48f8-ac71-f55794317160)

[v4.7.2-rc2](https://github.com/wazuh/wazuh/issues/21277) 
![image](https://github.com/wazuh/wazuh/assets/125690423/75d8087b-15c0-4e68-8bbe-3225fc57b36b)

[v4.8.0-alpha1](https://github.com/wazuh/wazuh/issues/20810) 
![image](https://github.com/wazuh/wazuh/assets/125690423/a3212f40-5637-4ffb-8e36-7b6988c47f57)

It should be assessed whether this behavior is expected and whether it affects the proper functioning of the product or not.

**Comment by Dwordcito** [comment]
@wazuh/data-pirates Timebox of 2 days for the ETA.

**Comment by pereyra-m** [comment]
# Analysis

The new vulnerability detector has a different internal behavior and this explains most of the differences found. 
I'll make a brief comparison.

## Modules summary

### Legacy module

**Scan**:
- The module asks Wazuh-DB for the packages and OS data every time and inserts them in the `cve.db`. Then it performs some inner join queries and the results are the vulnerabilities to report.
- The `interval` and `min_full_scan_interval` options trigger partial and full scans regularly, and even if there aren't new packages to scan, the queries to Wazuh-DB are performed.

**Feed**:
- The module doesn't have initial content at startup, and it requires downloading all the feeds and inserting them in the `cve.db` before starting the scan.

### Refactored module

**Scan**:
- The OS data is stored in a cache and the synchronization events of **syscollector** are scanned on the fly, so it isn't required to ask Wazuh-DB every time for the agent data. The scan is performed on memory and not over `cve.db`.
- The module is event driven, so no actions are taken if there aren't new packages installed/removed.

**Feed**:
- The module has initial content at the first startup so it isn't required to download, process and store all the feeds.

## Comparison

According to these main differences, we expect the following parameters to change in the stress tests:

- **Memory:** The RAM memory that the module uses might be higher because now RocksDB is used for all the DB management and this library manages the data in memory before storing it in disk. But we see a strong decrease because now every package is analyzed using callbacks for each vulnerability candidate and we never have in memory all the packages at the same time.

- **Disk**: it is expected that the HDD usage will decrease because the module doesn't work without new events, and the scan of the package doesn't need to query Wazuh-DB or use the `cve.db`.

- **CPU**: the stress test doesn't generate new agent events, so no scans are triggered. The changes in the content should generate new scans but this isn't yet implemented. It is expected to see less usage.

- **Decoded events**: the alerts sent to `analysisd` indicate the vulnerabilities found by the module. It seems that now we have much less than before and we must keep researching about this.

## Conclusion

It is expected that the module consumes less resources in general (RAM, CPU, HDD). It is known that the scanner still has some accuracy issues to solve and that the updates of content still don't trigger scans.

But the important change in decoded events means that there has been a decrease in the total amount of vulnerabilities and this should be investigated. 
Now, it is impossible to analyze the detection differences without the debug logs of the scans. 

@pro-akim , I have some requests for the QA team when this type of issue is created that could help a lot in the analysis:

- The charts aren't colorblind friendly.
- The developers only have the charts, and the numeric data that generated them isn't available. We need the exact numbers.

**Comment by Dwordcito** [comment]
LGTM
