### ISSUE TITLE
Decrease of modulesd pattern in the CPU plot for ALL_EXCEPT_SYSCHECK stress test

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh#21523]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha2 | Wazuh | Manager | Packages | CentOS manager |

During the analysis of [Release 4.8.0 - Alpha 2 - Footprint Metrics - ALL-EXCEPT-SYSCHECK (2.5d)](https://github.com/wazuh/wazuh/issues/21501#top) it has been detected a relevant decrease in the CPU usage for modulesd (not even visible in the graph), compared with the same test in 4.7.2-rc2 https://github.com/wazuh/wazuh/issues/21266:

- 4.8.0-alpha2

![2024-01-18_12-23](https://github.com/wazuh/wazuh/assets/101177239/50f222a7-b03e-43f0-973e-f4a9b4fa3822) 

- 4.7.2-rc2

![2024-01-18_12-23_1](https://github.com/wazuh/wazuh/assets/101177239/7556a7cf-1925-4f2d-b1cd-16179425f052)

It should be assessed whether this behavior is expected and whether it affects the proper functioning of the product or not.

**Comment by mauromalara** [comment]
I think this is duplicated: https://github.com/wazuh/wazuh/issues/21521

**Comment by nmkoremblum** [comment]
@mauromalara This is a different test

**Comment by nmkoremblum** [comment]
After comparing the number of events processed by `modulesd` we can see the following:

| Version       | Modulesd Events Decoded | Modulesd Events Dropped | Decoded from vulnerability | EDPS from Modulesd  |
|-----------------|-------------------------|-------------------------|-----------------------------|---------------------|
| 4.8.0-alpha1   | 41966517              | 124354                 | 373852                      | 194         |
| 4.8.0-alpha2   | 41207654              | 79604                 | 4925                         | 190          |
| % Change (alpha2/alpha1 - 1) * 100 | -1.81% | -35.99% | -98.68% | -1.81% |

![Normalized performance comparison](https://github.com/wazuh/wazuh/assets/75255206/b40b1563-8af2-4b97-8b45-ba134c6e2fe4)

Modulesd processes almost the same amount of events as in the previous test, but it drops much fewer. The number of decoded events from `Vulnerability Detector` has decreased considerably, this is due to its code refactor but I cannot tell if this is the expected behavior or not, maybe @Dwordcito can confirm so.

So, if no other unexpected behavior is observed, then I don't think this is something we should be worried about.

**Comment by Dwordcito** [comment]
Yes, it is expected because the tests do not perform the insertion or deletion of packages regularly.
When the vulnerability detector works reactively and is not re-scheduled the amount decreases.

In any case, we are working on efficacy for beta2 which may modify this number a little, but not in the substantial way seen here.

**Comment by cborla** [comment]
The drop in the number of events processed by the new vulnerability detector is due to the fact that it does not stress in the same way as the previous version, so the following [issue](https://github.com/wazuh/wazuh-qa/issues/4882) is created to request the adaptation of the stress test for this module.
I consider that there is nothing more to analyze of this issue and it can be closed.
