### ISSUE TITLE
Increased Disk activity in manager during stress tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#21522]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha2 | Wazuh component | Manager | Packages | Centos |

## Description

During Footprint tests for `4.8.0-alpha2` https://github.com/wazuh/wazuh/issues/21492 the following discrepancies were detected:

- Decreased Disk Read maximum
  - 4.7.2
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.2/B4746-3600m/B4746_manager_centos/plots/monitor-manager-Test_stress_B4746_manager-pre-release_Disk_Read.png)
  - 4.8.0
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4777-3600m/B4777_manager_centos/plots/monitor-manager-Test_stress_B4777_manager-pre-release_Disk_Read.png)

- Increased Disk Written maximum value
  - 4.7.2
 ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.2/B4746-3600m/B4746_manager_centos/plots/monitor-manager-Test_stress_B4746_manager-pre-release_Disk_Written.png)
  - 4.8.0
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4777-3600m/B4777_manager_centos/plots/monitor-manager-Test_stress_B4777_manager-pre-release_Disk_Written.png)

- Increased ReadOPS maximum value
  - 4.7.2
 ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.2/B4746-3600m/B4746_manager_centos/plots/monitor-manager-Test_stress_B4746_manager-pre-release_Read_Ops.png)
  - 4.8.0
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4777-3600m/B4777_manager_centos/plots/monitor-manager-Test_stress_B4777_manager-pre-release_Read_Ops.png)

- Increased Write_Ops maximum value
  - 4.7.2
 ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.2/B4746-3600m/B4746_manager_centos/plots/monitor-manager-Test_stress_B4746_manager-pre-release_Write_Ops.png)
  - 4.8.0
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4777-3600m/B4777_manager_centos/plots/monitor-manager-Test_stress_B4777_manager-pre-release_Write_Ops.png)

**Comment by juliamagan** [comment]
This behavior has also been observed in https://github.com/wazuh/wazuh/issues/21491

**Comment by nbertoldo** [comment]
The reports have been reviewed and the analysis can be divided into two parts.

1. Decreased `Disk Read` maximum value in `monitord`: the increases in the curve occur at 00:00 hs when `monitord` performs the log rotation process. Since the tests have been launched at different times, the log files have different sizes and therefore the values are expected to be different.
2. Increased `Disk Written`,  `Read OPS` and `Write OPS` maximum values in `modulesd`: this behaviour has been previously analysed in #20874, concluding that the increase is due to the changes in `SCA` merged in `4.8.0-alpha1`.
