### ISSUE TITLE
Increase - USS - by wazuh-agentd.exe - on Windows agent

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#21531]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha2 | Wazuh | Windows | Packages | CentOS Manager |

Testing: [Release 4.8.0 - Alpha 2 - Footprint Metrics - ALL-EXCEPT-SCA (2.5d)](https://github.com/wazuh/wazuh/issues/21496)

### Windows

v4.8.0-alpha2 https://github.com/wazuh/wazuh/issues/21496

![image](https://github.com/wazuh/wazuh/assets/89791732/4fc33664-987b-417e-8849-84884ba50ad6)

v4.7.2-rc2 https://github.com/wazuh/wazuh/issues/21274

![image](https://github.com/wazuh/wazuh/assets/89791732/83883ff4-b276-4d9c-a048-66e95d9c7aa8)

**Comment by nbertoldo** [comment]
This issue is not correctly reported as it compares the `RSS` graph of `v4.8.0-alpha2` with the `USS` graph of `v4.7.2-rc2`.
However, the graphs for both parameters have been analysed and no problems have been detected.

### USS
- v4.7.2-rc2
![image](https://github.com/wazuh/wazuh/assets/117279646/cedb8f19-35a4-4f6d-83df-6305e6eb7684)

- v4.8.0-alpha2
![image](https://github.com/wazuh/wazuh/assets/117279646/32f73c88-c3c6-4323-8153-f6bd7c12cb8e)

### RSS
- v4.7.2-rc2
![image](https://github.com/wazuh/wazuh/assets/117279646/f702e017-01ee-4a6f-8a66-f9983b234877)

- v4.8.0-alpha2
![image](https://github.com/wazuh/wazuh/assets/117279646/54121c36-62eb-4d4a-82b2-b209d0ca2476)

 
Please disregard this issue.
