### ISSUE TITLE
RSS,PSS - dsecrease - on agent on - 4.8.0-Alpha2

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#21534]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha2 | Wazuh | Manager| Packages | centOS Manager |

### Description

During [All-Except-Logcollector footprint testing](https://github.com/wazuh/wazuh/issues/21499#) it has been detected an increase in the usage of memory for the CentOS agent.

| Metric | 4.8.0 | 4.7.2-RC1 |
| --- | --- | --- |
| PSS | ![IMAGE](https://camo.githubusercontent.com/faf050746fe36d7811b041b06da21c0f5be3ecf6e31c9526d91bb576915775ac/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343738312d333630306d2f42343738315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343738315f63656e746f732d7072652d72656c656173655f5053532e706e67) | ![IMAGE](https://camo.githubusercontent.com/fbafd32b518db1e5f07c4f6c4faa27ab5ea6477f5b76db28ec535ba6e888fb9c/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343732382d333630306d2f42343732385f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343732385f63656e746f732d7072652d72656c656173655f5053532e706e67) |
| RSS | ![IMAGE](https://camo.githubusercontent.com/c1e15422b9bad296c8a6b5eb1f4b959ab5c5265af2f702568f5976c0cf30be9f/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343738312d333630306d2f42343738315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343738315f63656e746f732d7072652d72656c656173655f5253532e706e67) | ![IMAGE](https://camo.githubusercontent.com/15b7f1946e603fdf4d1a36a82b1412249aec03cc177829f1f52fd8cb753da324/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343732382d333630306d2f42343732385f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343732385f63656e746f732d7072652d72656c656173655f5253532e706e67) |

### Evidences

- [Configurations and Logs](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4781-3600m/B4781_agent_centos/logs/ossec_Test_stress_B4781_centos_2024-01-17.zip)
- [Monitoring Data](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4781-3600m/B4781_agent_centos/data/monitor-agent-Test_stress_B4781_centos-pre-release.csv)

**Comment by cborla** [comment]
This issue is probably related to the following [comment](https://github.com/wazuh/wazuh/issues/21523#issuecomment-1909438946). In which it is determined that fewer vulnerability detector events are processed, due to the way in which the module is attempted to be stressed. We have opened an [issue](https://github.com/wazuh/wazuh-qa/issues/4882) requesting to adapt the new vulnerability detector test.
In general, no memory ramps or other behavior that compromises the Manager are observed.

**Comment by cborla** [comment]
## Analysis 4.7.2 RC2 vs 4.8.0 Alpha 2

### Events generated
![image](https://github.com/wazuh/wazuh/assets/41765669/626d85dc-fd98-42da-a3a5-8a7b5a983f93)
There is no significant difference between the two versions. Version 4.8.0 generated approximately 1% more events.

### Graphical analysis
Next we compare version 4.8.0 alpha 2 with version 4.7.2 RC2, instead of 4.7.2 RC1 from which this issue is generated. 

| Metric | 4.8.0-Alpha1 | 4.7.2-RC2 |
| --- | --- | --- |
| PSS | ![IMAGE](https://camo.githubusercontent.com/faf050746fe36d7811b041b06da21c0f5be3ecf6e31c9526d91bb576915775ac/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343738312d333630306d2f42343738315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343738315f63656e746f732d7072652d72656c656173655f5053532e706e67) | ![IMAGE](https://camo.githubusercontent.com/43742219b7a49c14f93d500abd2659b8db4756c07e7f4e5d868cdcac02e95e03/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343733362d333630306d2f42343733365f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343733365f63656e746f732d7072652d72656c656173655f5053532e706e67) |
| RSS | ![IMAGE](https://camo.githubusercontent.com/c1e15422b9bad296c8a6b5eb1f4b959ab5c5265af2f702568f5976c0cf30be9f/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343738312d333630306d2f42343738315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343738315f63656e746f732d7072652d72656c656173655f5253532e706e67) | ![IMAGE](https://camo.githubusercontent.com/10148a4efc72b6cb39490884b5b0b4eeeb08959b300631845ec5420b2f2e5d6d/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343733362d333630306d2f42343733365f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343733365f63656e746f732d7072652d72656c656173655f5253532e706e67) |


### Agent statistics
There are no significant differences between the versions.
![image](https://github.com/wazuh/wazuh/assets/41765669/c9f372fe-a600-49a9-a357-1c958569eb59)

## Conclusion
I believe this issue should be dismissed due to the following points:
- The comparison was made with version 4.7.2 RC1 which was not the last release of 4.7.2.
- Comparing version 4.8.0 Alpha 2 with version 4.7.2 RC2 there are no considerable differences.
