### ISSUE TITLE
PSS, RSS_MAXMIN, RSS, USS - Increase, Pattern Change - Manager On 4.8.0-Alpha2

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#21545]
| Wazuh Version | Install Type | Install Method | Platform |
| --- | --- | --- | --- |
| 4.8.0-alpha2 | Manager | Packages | CentOS |

## Description

During the analysis carried out in the following stress tests:

- [Footprint Metrics - ALL-EXCEPT-DOCKER,CISCAT,OSQUERY,AZURE,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/21500)
- [Footprint Metrics - ALL (2.5d)](https://github.com/wazuh/wazuh/issues/21495)

It has been observed that, compared to the same tests in 4.7.2-rc2, the values of `wazuh-modulesd` have increased and that the pattern of the graphs has changed.

The behavior is similar to what we found in the issue [Increase of RSS/FSS/USS in the manager](https://github.com/wazuh/wazuh/issues/21517) but, in this case, the pattern also changes.

### Footprint Metrics - ALL-EXCEPT-DOCKER,CISCAT,OSQUERY,AZURE,OPEN-SCAP (2.5d)

<details>
  <summary>4.8.0-alpha2</summary>
  <br/>

> https://github.com/wazuh/wazuh/issues/21500

![image](https://github.com/wazuh/wazuh/assets/54536265/e5cb45b7-40b2-47b4-bf52-b7be5f0ede93)

![image](https://github.com/wazuh/wazuh/assets/54536265/e3691019-ca26-4392-bb5d-36a09eaacc61)

![image](https://github.com/wazuh/wazuh/assets/54536265/8a420231-6187-4705-82f1-3e772ec469e9)

![image](https://github.com/wazuh/wazuh/assets/54536265/7333b2c0-7b3a-47a2-b333-ee7e1cbc4cfa)

</details>

<details>
  <summary>4.7.2-rc2</summary>
  <br/>

> https://github.com/wazuh/wazuh/issues/21265

![image](https://github.com/wazuh/wazuh/assets/54536265/62ea8e62-3639-4d3b-8d7e-fe498faa46c0)

![image](https://github.com/wazuh/wazuh/assets/54536265/1ae6d2a4-8f29-485f-b931-2b0e80d03e53)

![image](https://github.com/wazuh/wazuh/assets/54536265/25b9b329-b32d-441d-baa9-e15a2e0bbf26)

![image](https://github.com/wazuh/wazuh/assets/54536265/5dfb6fd2-fef7-4947-a2f4-7c9c9b31c13c)

</details>

### Footprint Metrics - ALL (2.5d)

<details>
  <summary>4.8.0-alpha2</summary>
  <br/>

> https://github.com/wazuh/wazuh/issues/21495

![image](https://github.com/wazuh/wazuh/assets/54536265/3dbfd38c-e286-4b4a-8103-9441ba4d27d9)

![image](https://github.com/wazuh/wazuh/assets/54536265/63a51b70-532d-4c1e-a2b1-90444397ae8e)

![image](https://github.com/wazuh/wazuh/assets/54536265/d9bc49df-6e5f-4417-8bb3-0bde53cd1894)

![image](https://github.com/wazuh/wazuh/assets/54536265/11e1077c-02e0-4160-b910-7be5d94abb4b)

</details>

<details>
  <summary>4.7.2-rc2</summary>
  <br/>

> https://github.com/wazuh/wazuh/issues/21280

![image](https://github.com/wazuh/wazuh/assets/54536265/ce4c372d-eeef-44bc-a534-2ead4c494034)

![image](https://github.com/wazuh/wazuh/assets/54536265/42dfce60-8dd5-4bd7-a519-d3a2731bd0c1)

![image](https://github.com/wazuh/wazuh/assets/54536265/467c2f0d-f6c1-407f-b1ce-0b5bc3213399)

![image](https://github.com/wazuh/wazuh/assets/54536265/d57a874f-fc6e-4609-98d1-fa04af02b419)

</details>

**Comment by nbertoldo** [comment]
After analysing the test reports, it can be seen that in all the mentioned parameters there is an increase of the average value in 4.8.0-alpha2 compared to 4.7.2-rc2. However, in 4.7.2-rc2 there are peaks with higher values, which occur every hour due to the update of the Vulnerability Detector databases.

### Footprint Metrics - ALL-EXCEPT-DOCKER,CISCAT,OSQUERY,AZURE,OPEN-SCAP (2.5d)

<google-sheets-html-origin>
Version | RSSavg | RSSmin | RSSmax | USSavg | USSmin | USSmax | PSSavg | PSSmin | PSSmax
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
4.7.2 | 80151.8 | 67608 | 243800 | 71288.22 | 1164 | 232928 | 74659.5 | 33896 | 234087
4.8.0 | 133493.31 | 123164 | 155964 | 120893.38 | 2496 | 146416 | 126410.62 | 62518 | 149320
Increase % | 66.55 | 82.17 | -36.03 | 69.58 | 114.43 | -37.14 | 69.32 | 84.44 | -36.21

### Footprint Metrics - ALL (2.5d)

<google-sheets-html-origin>
Version | RSSavg | RSSmin | RSSmax | USSavg | USSmin | USSmax | PSSavg | PSSmin | PSSmax
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
4.7.2 | 74668.12 | 62220 | 374212 | 68692.25 | 936 | 365660 | 72086.27 | 22501 | 368091
4.8.0 | 139734.23 | 130880 | 161200 | 124465.08 | 2156 | 149896 | 130408.06 | 46496 | 152714
Increase % | 87.14% | 110.35% | -56.92% | 81.19% | 130.34% | -59.01% | 80.91% | 106.64% | -58.51%

These differences in pattern and values are mainly due to the changes made in the [Vulnerability Detector refactor](https://github.com/wazuh/wazuh/issues/14153), where the mode of operation of the module changes completely. For this reason, we consider that the comparison between these two versions is not appropriate.

**Comment by sebasfalcone** [comment]
The main suspect is the configurations for the rocksDB, more specifically the memtables

## memtables
RocksDB writes go first to Memtables, a data structure that resides in the memory. These tables are then flushed to the L0 level in the DB. Smaller memtables in the will reduce the memory consumption, but increase the frequency of flushes (disk I/O).

### Options
There are many fields on the configuration which can be tweaked to improve this scenario

#### write_buffer_size
This is the maximum size of each memtable that RocksDB can create. Beyond this size, a new memtable is created, and the existing one is queued up for flushing to the disk. The default value is 64MB.

#### max_write_buffer_number
These are the maximum number of memtables that can exist in the memory before a flush is triggered. The default is two so that when the first memtable is flushed, the writes can continue on the second memtable.

#### min_write_buffer_number_to_merge
The minimum number of memtables that will be merged before a flush is triggered. The merge operation happens in memory. This can help you reduce disk io for flushes, especially if memtables contain a lot of duplicate keys or deletes. The default is one, so no memtables are merged.

#### db_write_buffer_size
This is the max size of all memtables combined across column families. The default is -1, which means there is no global limit on memtables. If you set it to a value > 0, RocksDB will initialize a WriteBufferManager that keeps track of all memtables sizes across column families.


> [!NOTE]
> We can grep for flush_reason stats in the RocksDB Log file to check the size of the column family before getting flushes as well as the reason it flushed.

This is the case where the buffer was full:
```json
{
    "time_micros": 1706557130373507,
    "job": 107,
    "event": "flush_started",
    "num_memtables": 1,
    "num_entries": 5255,
    "num_deletes": 0,
    "total_data_size": 63509497,
    "memory_usage": 66730176,
    "flush_reason": "Write Buffer Full"
}
```
See that the memory usage was about 63MB

**Comment by sebasfalcone** [comment]
Update:
- Tests performed where not conclusive, memory consumption seems to improve but not in the percentage expected

**Comment by MiguelazoDS** [comment]
# Analysis (WIP) 

Taking a look at the documentation and to complement the information provided above, the option `write_buffer_size` is the size of the memtable for a single column family and it can be set in `rocksdb::Options` or in a specific column family with `ColumnFamilyOptions::write_buffer_size`. 

`max_write_buffer_number` option is not recommended above 3 (default 2) defined at `AdvancedColumnFamilyOptions` as explained above is the max number of write buffers built in memory. But taking into account that this is per column family.

So considering the previous options with a default size of 64MB for `write_buffer_size` and 2 buffers, we have 128MB per column family.

The option `db_write_buffer_size` disabled by default is defined in rocksdb::Options and consider all the memtables associated with all column families.

**Comment by sebasfalcone** [comment]
Amazing analysis @MiguelazoDS!

@Dwordcito Seems like this is the cost of rocksDB

PS: I've moved the ETA but the analysis is concluded

**Comment by Dwordcito** [comment]
In addition to the analysis described in this issue, I also add this other one, which shows a transfer from disk use to memory use to avoid the use of less efficient resources and be able to use more efficient resources.

https://github.com/wazuh/wazuh/issues/21521#issuecomment-1915920299

Closed, this increase is by design.

**Comment by MiguelazoDS** [comment]
Hi @sebasfalcone. 

We should keep investigating this for sure and be cautious as we keep getting used to RocksDB library. I found some related issues that mention some similar behavior but for those cases is clear that the memory was growing continuos in time. In our case after some time (almost 3 days according to the testing in the issue description) the memory consumption is not leaking. 

As far as I know, we shouldn't see any noticeable increment related to the agent number, since each event is processed sequentially and memory allocations for that event are freed when new context data is processed. 

According to the test, I performed all the configs were useless or the changes were not easy to see with the naked eye. I think we should leave this untouched.
