### ISSUE TITLE
False Positive Vulnerability for CVE-2021-3711 affects libssl1.1

### ISSUE THREAD

**Issue by davkastheranger19** [wazuh/wazuh#21596]
Client running Ubuntu server  20.04.3 LTS Wazuh Client version 4.7.2-1
Server running Ubuntu server  20.04.3 LTS Wazuh Server version 4.7.0-1
Client and Server are separate machines.

Vulnerability Scan shows CVE-2021-3711 affects libssl1.1

Client shows libssl1.1 is already the newest version (1.1.1f-1ubuntu2.16)
https://ubuntu.com/security/notices/USN-5051-1 
Shows the problem can be corrected by updating to the following package versions: 
Ubuntu 20.04 libssl1.1 - 1.1.1f-1ubuntu2.8

**Comment by MarcelKemp** [comment]
Hi @davkastheranger19,

As you point out, version `1.1.1f-1ubuntu2.16` of `libssl1.1`, fixes the vulnerability CVE-2021-3711:
- OVAL: https://ubuntu.com/security/CVE-2021-3711

It is possible, that one of the affected components is still installed on the client, so that the vulnerability is still reported.

To avoid this, check the component that shows you in the `condition` with an older version and update it, or remove it to mitigate the vulnerability.

If even with the above, you are still having problems, I would need you to share the following information with me:
From the API (which you can run in the WUI tool: `Modules` -> `Tools` -> `API console`):
- The agent's [hotfixes](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_hotfix_info)
`GET /syscollector/{agent_id}/hotfixes`
- And the agent's [vulnerabilities](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.vulnerability_controller.get_vulnerability_agent)
`GET /vulnerability/{agent_id}`

I look forward to your response.

**Comment by MarcelKemp** [comment]
Sorry, I made a mistake when I asked for `hotfixes`, instead of `packages`, which is what I needed. But well, the list of vulnerabilities should be enough.

As far as I can see, the agent must be an Ubuntu 22 (_Jammy_), because the condition is that the `libssl1.1` package is _less than_ version: `1.1.1l-1ubuntu1`.

![image](https://github.com/wazuh/wazuh/assets/37207742/bb9c8ab4-55a0-4d47-b206-30dd7a3f3f54)

This means that the `libssl1.1` component is being detected by _Syscollector_ with a vulnerable version, so it would be necessary to update it, or in case it is not being used, remove it to mitigate that vulnerability.

My recommendation is to uninstall this component, as it is deprecated in _Jammy_. The current version for _OpenSSL_ is `3.0.2-0ubuntu1.13`.

**Comment by davkastheranger19** [comment]
> My recommendation is to uninstall this component, as it is deprecated in _Jammy_. The current version for _OpenSSL_ is `3.0.2-0ubuntu1.13`.

Sorry for not doing enough research about the issue before opening this ticket.
This server has software that has to use 1.1.1f and is symlink to 3.0.2. Unfortunately, we can't get around using this old openssl version.
