### ISSUE TITLE
Vulnerability Detector is reporting vulnerabilities for Windows 11 that cannot be fixed

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#21621]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.2-40711 | Vulnerability Detector | Manager/Agent | Packages | Windows 11 22621.3007 |

## Description

A community user has reported that Vulnerabiliy Detector reports over 450 missing KB updates. However, when he tries to install the recommended hotfixes, he gets the message that they are not available for his system.

Attached is the list of detected hotfixes and the list of detected vulnerabilities:

- [Hotfixes list](https://github.com/wazuh/wazuh/files/14050853/syscollector.txt)

- [Vulnerabilities list](https://github.com/wazuh/wazuh/files/14050855/logvulnW11.json)

We can see that the vulnerability CVE-2024-20700 is reported, however if we look in [NVD](https://nvd.nist.gov/vuln/detail/CVE-2024-20700), it is specified that the user version is excluded:

![image](https://github.com/wazuh/wazuh/assets/80041853/557d8a32-2f39-4bbf-9ef2-811487a8c608)

**Comment by MarcelKemp** [comment]
## Problem
The root of the problem lies in the lack of hotfixes collected by _Syscollector_, because if we look at the list of [hotfixes](https://github.com/wazuh/wazuh/files/14050853/syscollector.txt), we can see that there is no hotfix related to the security of the system, so that not having any hotfix of the system, it reports all existing vulnerabilities for that system.

### Reason

There are two possible reasons that could be causing this issue:
- The first reason, would be due to the fact that the OS has just been installed on that machine and no updates have been applied to the system yet. This could mean that no system hotfixes are shown because they have not been stored in the registries, as they are implicit in the installed system, and therefore we cannot get them with _Syscollector_ either.
  - To check if this is the problem, we have asked the user to run Windows commands to see if it is possible to obtain them ([request](https://wazuh.slack.com/archives/C0A933R8E/p1706183489711849?thread_ts=1706023955.782669&cid=C0A933R8E)). If they are displayed, but we can't get them, then we will move on to the second possible reason.
- The second reason would be due to the fact that the registry path where the hotfixes are stored in this system has been modified, which would mean that we would not be able to obtain the hotfixes because we would not be looking in the new path. If this is the case, we should open a new issue to fix it and be able to collect hotfixes from that system.

### Fix

Currently, this problem is intended to be fixed in the VD refactor, because we are going to generate a CPE with the added version, which will match the CPEs found in the NVD, thus avoiding that versions older than the installed one are reported:
- https://github.com/wazuh/wazuh/issues/14153
  - https://github.com/wazuh/intelligence-data/issues/30
    - `"Microsoft Windows 11": "microsoft:windows_11_$(DISPLAY_VERSION):$(VERSION):::::",`
    - Ex: - [cpe:2.3:o:microsoft:windows_11_*:\*:\*:\*:\*:\*:\*:\*:\*](https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cpe%3A2.3%3Ao%3Amicrosoft%3Awindows_11_*%3A*%3A*%3A*%3A*%3A*%3A*%3A*%3A*)

Since it will be fixed in the next release, I will close the issue, and in case the problem is due to the registry path change, we can reopen this issue to implement the fix in _Syscollector_, or open a new issue.
