### ISSUE TITLE
Filter Cases When VD Must Not Send Reports

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#21659]
### Problem Description
Currently, the VD (Vulnerability Detection) is sending reports in scenarios where it is not necessary or appropriate. This behaviour can lead to information overload, unnecessary processing, and potential confusion. It is crucial to implement filters to prevent the VD from sending reports in specific cases, enhancing the overall efficiency and relevance of the reporting system.

### Expected Behavior
The VD should intelligently filter out scenarios where sending reports is unnecessary. This includes situations where reports would be redundant, irrelevant, or where the information is already known or anticipated.

### Steps to Reproduce
1. Set up the VD in a standard operational environment.
2. Observe the reporting behaviour of the VD under various scenarios.
3. Identify specific cases where the VD sends unnecessary or redundant reports.

### Possible Solutions
A possible solution is to implement a set of rules or criteria within the VD's reporting logic that checks the relevance and necessity of a report before sending it. Machine learning algorithms could also be explored to dynamically adapt these filters based on ongoing system behaviour and feedback.

### Definition of Done Checklist
- [x] Identify specific scenarios where the VD should not send reports.
- [x] Develop and implement filtering logic to prevent unnecessary reporting.
- [x] Test the updated VD in various scenarios to ensure it only sends relevant reports.

**Comment by sebasfalcone** [comment]
@pereyra-m
I would like some examples of the reports that need filtering

**Comment by pereyra-m** [comment]
Hi @sebasfalcone !

After the #21446 development, the re-scan of the agents was implemented. We were analyzing all the different types of scan triggers and only the **syscollector** events should generate alerts because those are things that are happening at the moment.

The re-scan (due to an upgrade for example) would flood with alerts that aren't related to things that are happening in the monitored environment but are related to a maintenance event. It's preferred to consider that initial scan as a "baseline" and then alert all the vulnerabilities that are found in the future.

**Comment by Dwordcito** [comment]
In accordance with what @pereyra-m says in: https://github.com/wazuh/wazuh/issues/21659#issuecomment-1944542595

1- Skip alerts report for:
scanContext->m_messageType != MessageType::Delta; (Add getter for that private member)

2- Dont report rsync delete events as dbsync/delta events, use the appropriated messaged under rsync queue.
https://github.com/wazuh/wazuh/blob/076d22b3e3f0f8bed7a5fbeef48cb5199adaed90/src/wazuh_db/main.c#L208
