### ISSUE TITLE
Implementing Filters for Agent Analysis Based on Connection and Reporting Node

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#21660]
### Problem Description
There is a redundancy in the analysis of agents by multiple workers, each with different synchronization states of their databases. This results in inefficiencies and potential inconsistencies in agent management. Agents are currently analyzed many times, regardless of their connection status or the specific node they report to. A more intelligent filtering system is needed to ensure that each agent is analyzed appropriately, considering its current state and assigned node.

### Expected Behavior
The system should be able to filter agents based on their connection status (e.g., connected, disconnected) and the specific node they are reporting to. This will ensure that each agent is analyzed only once and by the appropriate worker, based on the current synchronization state of the worker's database.

### Steps to Reproduce
1. Deploy multiple workers.
2. Monitor the analysis process of agents by these workers.
3. Note instances where the same agent is analyzed multiple times by different workers.

### Possible Solutions
One potential solution is to create a dynamic filtering system that assigns agents to workers based on real-time data about their connection status and the node they report to. Implementing a check-and-balance mechanism to verify the synchronization state of a worker's database before assigning an agent for analysis could also be explored.

---

### Definition of Done Checklist
- [ ] Develop a filtering mechanism for agents based on their connection status and reporting node.
- [ ] Implement the filter within the system's agent analysis process.
- [ ] Test the system to ensure each agent is analyzed only once by the appropriate worker.

**Comment by sebasfalcone** [comment]
@pereyra-m 
Before finishing the triage of this issue I would like some examples of the reports that need filtering

**Comment by pereyra-m** [comment]
Hi @sebasfalcone !

This issue was created because in this development #21446, there were some situations where all the agents are requested and scanned. Now, the `global.db` contains **all** the registered agents and some of them aren't reporting to the current node that is about to launch a re-scan. Some of them might be disconnected or inactive. If we don't filter out the agents in the query, we'll end up scanning the same agents in more than one worker, but with different packages inventory (it isn't synced across the cluster); or we'll scan agents that aren't active.

We could instead only scan the current active agents of that node. But the implementation should carefully consider all the race conditions involved. For example: the request of active agents arrives before some agents' states are updated and they get out of the scan, etc.

**Comment by Dwordcito** [comment]
I understand this is when a configuration changes from off to on.

It is a cost that we must pay, if an agent is disconnected and they change the vd state from off to on, and that agent reconnects it will partially synchronize the syscollector inventory, therefore some elements may be left out.

To avoid "rare" situations we will leave it like this in 4.8.0 and we will improve it in the future.

**Comment by sebasfalcone** [comment]
This issue will be addressed at:
- https://github.com/wazuh/wazuh/issues/22867
