### ISSUE TITLE
Abnormally vulnerability detector database size during re-downloading. 

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#21663]
# Description 

It was found that after interrupting and resuming the feed processing the size of the database is too big. It is required to evaluate this behavior because the database may be corrupted, and this can unravel the entire scanning process. 

# Expected behavior 

As of now, the database feed size is around 4.5GB. Interrupting and resuming the feed processing shouldn't exceed that value. 

![image](https://github.com/wazuh/wazuh/assets/13010397/0cc23921-e231-4c12-8bae-2b9f0e0fd6ec)

![image](https://github.com/wazuh/wazuh/assets/13010397/aade7813-ba2f-4f9f-9c1b-83099073eb9e)

# Actual behavior 

After interrupting and resuming the feed processing the database feed size grows beyond 4.5GB

# Steps to reproduce 

- Install manager 4.8.0 (62a5a6752bfcf934a7c7bdf3609f89d5bea0f462) 
- Let the processing start 
![image](https://github.com/wazuh/wazuh/assets/13010397/cf032f67-93b3-4f69-bad7-fcbb6f1f83d6)
- Interrupt the process before it ends (wazuh-control stop)
![image](https://github.com/wazuh/wazuh/assets/13010397/c3b194ac-0cdf-4182-9e20-8d8dddfb293f)
The logs do not say how the process is going. 
![image](https://github.com/wazuh/wazuh/assets/13010397/828cb3d7-7ae6-498d-9664-152d5f0f2c6d)
- Restart manager. It will re-download the feed.
![image](https://github.com/wazuh/wazuh/assets/13010397/8841ef9e-3266-48fa-a560-931dad72654c)
![image](https://github.com/wazuh/wazuh/assets/13010397/1f54734c-7e5d-48c1-a252-5cbefe57d825)
At 89k the size is almost 4.5GB
![image](https://github.com/wazuh/wazuh/assets/13010397/8d24c9b4-5d91-41de-bda8-c09b55bcda9f)
![image](https://github.com/wazuh/wazuh/assets/13010397/31222352-6d4b-4a55-8b54-8e86e87a2731)
At 200k the size is 5.0GB
![image](https://github.com/wazuh/wazuh/assets/13010397/71ce0551-22a3-4f0e-a48b-1818ff8c8f8e)
![image](https://github.com/wazuh/wazuh/assets/13010397/a8003b3f-cba0-4d44-949c-4acd39075893)
At the end the size is 5.6GB
![image](https://github.com/wazuh/wazuh/assets/13010397/822c3d20-1753-42ae-9fa1-115fbb299620)
![image](https://github.com/wazuh/wazuh/assets/13010397/6c2829b9-9e2c-4ae4-b492-138bafccb2e6)

# DoD 

- [ ] Analyze the root cause of this behavior.
- [ ] Identify the reason.
- [ ] Propose a fix if needed.

**Comment by sebasfalcone** [comment]
Moved ETA
- Issue requires more investigation

**Comment by sebasfalcone** [comment]
On hold

This issue has more depth than expected, seems like rocksDB has some issues regarding the deletion of DBs with high volume of data

@GabrielEValenzuela Will append a report with all this findings to the issue

**Comment by GabrielEValenzuela** [comment]
# Investigation of disk space management issue in RocksDB

## Abstract

This report investigates a concerning issue observed in RocksDB, a popular embedded database library developed by Facebook. The issue pertains to the ineffective management of disk space, wherein the delete operation fails to free up disk space, consequently leading to an increase in the database size. This report aims to analyze the root cause of the issue and propose potential solutions to mitigate its impact.

## Introduction

RocksDB is a high-performance, persistent key-value store designed for fast storage systems such as flash drives and hard disk drives. It is widely utilized in various applications ranging from web servers to distributed systems due to its efficiency and reliability. However, recent observations have revealed a critical issue regarding disk space management within RocksDB, for example, questions made in StackOverflow like [[1]] that uses Apache Kafka as a service, are proof of this issue.

## Problem Statement

The primary problem identified in RocksDB involves the inefficiency of the delete operation in reclaiming disk space. Despite deleting data entries from the database, the corresponding disk space occupied by these entries remains allocated, leading to an accumulation of unused space and an increase in the overall database size over time. Furthermore, when new data is inserted into the database, appears to not overwrite the previously deleted data, exacerbating the disk space utilization issue.

## Findings

Based on the provided findings, it seems the issue with inefficient disk space management in RocksDB may be attributed to several factors, including suboptimal delete operations, inefficient compaction strategies, and potential limitations in managing disk space utilization. Here's a summary of the key findings and potential solutions:

1. **Use of `DeleteRange` Function**: Utilizing the `DeleteRange` function instead of performing range scans for deleting a range of keys can significantly improve write performance by creating range tombstones as a single key-value pair. This native operation speeds up the deletion process and enhances write performance, making it a preferable solution for performance-sensitive write paths. Currently throws `CF not supported`

2. **Compaction Strategies**: Implementing trigger compaction on deletes can help mitigate the performance skew caused by excessive tombstones in SST files. By tracking long close-by tombstones and triggering compaction when necessary, the database can efficiently manage tombstone cleanup and improve range scan performance.

3. **Explicit Deletion of Iterators**: Ensuring that iterators are explicitly deleted when they go out of scope can prevent memory leaks and optimize resource utilization within the database. [[2]] [[3]]

4. **Management of `max_bytes_for_level_base` Variable**: Adjusting the `max_bytes_for_level_base` variable to optimize space and write amplification during compactions can improve overall performance and prevent excessive compactions that degrade performance over time. [[4]]

5. **Consideration of Probability in Delete Operations**: Since the issue occurs with low probability, using standard delete operations in C++ may serve as a reliable alternative, considering the potential trade-offs in performance and resource utilization.

## Conclusion

In conclusion, this report provides an analysis of this critical problem, addressing disk space management in RocksDB possibly requires a combination of optimizing delete operations, refining compaction strategies, and fine-tuning database configuration parameters to balance space utilization and performance. Implementation of the suggested solutions can help mitigate the observed issues and improve RocksDB's overall disk space management efficiency and reliability. While this is being addressed, we continue our research by bringing this issue to Meta's team of developers so that we can get a first-hand answer.

-------

[1]: https://stackoverflow.com/questions/66543704/rocksdb-is-not-freeing-up-space-after-a-delete
[2]: https://github.com/facebook/rocksdb/issues/8041
[3]: https://www.confluent.io/blog/how-to-tune-rocksdb-kafka-streams-state-stores-performance/
[4]: https://scholar.dgist.ac.kr/bitstream/20.500.11750/16691/1/200000364341.pdf

**Comment by sebasfalcone** [comment]
@GabrielEValenzuela 

Lets re-try this investigation with this changes https://github.com/wazuh/wazuh/pull/22360/commits/7714e2a87218e3bb5bc93d59bb2b640737a5a2d0

**Comment by sebasfalcone** [comment]
Great analysis Gabi! Good to know this issue was solved 😅 

### Conclusion
- Issue solved [here](https://github.com/wazuh/wazuh/pull/22360/commits/7714e2a87218e3bb5bc93d59bb2b640737a5a2d0)

### Issues generated from the analysis
- https://github.com/wazuh/wazuh/issues/22526
