### ISSUE TITLE
Analyzing the Risk of Simultaneous Access to m_inventoryDatabase

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#21719]
### Problem Description
There is a potential risk associated with multiple processes or threads accessing `m_inventoryDatabase` simultaneously. Such concurrent access can lead to data corruption, inconsistent states, or race conditions, affecting the integrity and reliability of the database. It is essential to analyze this risk comprehensively to implement necessary safeguards and ensure the database's stability and security.

### Expected Behavior
The system should be designed to handle simultaneous access to `m_inventoryDatabase` safely, without risk of data corruption or inconsistencies. This may involve implementing locking mechanisms, queueing access requests, or adopting an atomic operation approach to maintain database integrity.

### Steps to Reproduce
N/A - This issue focuses on risk analysis and system design rather than reproducing a specific behavior.

### Possible Solutions
- Implementing a locking mechanism to control access to `m_inventoryDatabase`.
- Using transactional database operations to ensure atomicity of data changes.
- Adopting a more robust concurrency control model, such as optimistic or pessimistic locking, depending on the use case and performance requirements.

---

### Definition of Done Checklist
- [ ] Conduct a thorough risk analysis of simultaneous access to `m_inventoryDatabase`.
- [ ] Identify specific scenarios where concurrent access could lead to issues.
- [ ] Implement mechanisms to safely handle simultaneous database access.
- [ ] Test the system under conditions of concurrent access to ensure stability.
- [ ] Document the approach and mechanisms for safe concurrent access in the developer guidelines.

**Comment by Dwordcito** [comment]
1- Corruptions are already handled internally by rocksdb.

2- The issue does not show a clear example or case in which this occurs.

It is dismissed.

**Comment by pereyra-m** [comment]
Hi @Dwordcito 

This issue was initially created after analyzing different situations at #21911.
There isn't a corruption risk but an inconsistency one.

We have normally two subscriptions for events, `m_syscollectorRsyncSubscription` and `m_syscollectorDeltasSubscription`. Both access the `m_inventoryDatabase` DB and store the new events accordingly. Also, now there is a thread (`m_rebootThread`) that is in charge of collecting all packages from all agents and analyzing them (the `m_inventoryDatabase` is also accessed).

The danger comes with `m_performReScanSubscription`, because it was meant to remove any previous invalid data of an agent and to re-scan it completely. What if some vulnerabilities from the other threads/subscriptions already have been stored and now get removed?  We could miss real events.

Another situation involves the race condition between `m_rebootThread` and  `m_syscollectorRsyncSubscription`/`m_syscollectorDeltasSubscription`. The first one takes a snapshot of the existing agents, and then iterates over all the packages of each one of them. While those packages are in memory waiting to be scanned, a delete event might arrive and remove one. When finally the scan ends, we would end up with an indexed vulnerability of a non-existing package.
