### ISSUE TITLE
Modify the installer process to include a dump generation option.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#21737]
NOTE: this is still a WIP

## Description

This issue aims to include in every installer process an option that will enable users and contributors to allow the generation of a core dump whenever a crash occurs, as well as to allow them to share this core dump with Wazuh automatically.

## Goals
For every platform, these goals must be achieved:

- Modify the installer process to include an option for the user to enable or disable the generation of the core dump whenever a crash occurs
- Implement the necessary modification to create the core dumps if the option is enabled
- It must be possible to disable or enable the core dump generation after the installation finished
- Test & verify that these behaviors are satisfied

## Plan:

- [x] Modify the installer process to include a dump generation option (RPM)
- [x] Modify the installer process to include a dump generation option (DEB)
- [ ] Modify the installer process to include a dump generation option (Windows)
- [x] Modify the installer process to include a dump generation option (macOS)

## DoD

For every platform (RPM, DEB, Windows & macOS):

- An option is present in the installer that will enable or disable core dump generation
- Core dump is generated if enabled, and it is not generated if it is disabled
- Core dump generation can be enabled or disabled after installation
- Core dumps can be analyzed using the associated debug symbols
- Verification of process and core dumps are passed successfully

## Approval

DRI Name: @ncvicchi
Objective: Generate debug symbols

**Comment by tdrauncieal** [comment]
### Update
* Compilation of information about the creation of `debian packages` and their options.
* Use and processing of `debconf` for interactive user options.
* Examples of use, testing

**Comment by tdrauncieal** [comment]
### Update
* Dowload and test `debconf` demo
* Evaluate `coredump` processing alternatives
* Testing piping output

**Comment by tdrauncieal** [comment]
### Update
* The change in `/proc/sys/kernel/core_pattern` is discarded because it is too invasive for the user
* A more limited alternative is being searched without success.
* For the moment it will be limited to informing the user of the changes that must be made, in case they want to collaborate.

**Comment by tdrauncieal** [comment]
### Update
* The change in `/proc/sys/kernel/core_pattern` is discarded because it is too invasive for the user
* A more limited alternative is being searched without success.
* For the moment it will be limited to informing the user of the changes that must be made, in case they want to collaborate.

**Comment by tdrauncieal** [comment]
### Update
* make a `coredumper` app to test on built VM
* testing the different options available to generate `coredumps` and evaluating the differences and similarities with Linux
* Research based on the new code available for MacOS, detecting points of chages to be made, compilation of an MacOS agent
* Acquiring knowledge of the tools necessary to modify the installer project files (.`pkgproj` files)

**Comment by tdrauncieal** [comment]
### Spike

Due to the development requested in this issue, it was necessary to investigate the necessary processes according to the platforms where they must be applied (Linux, MacOS, Windows) and which can be divided into:
* enable/disable to generate `coredumps`
* Add the user authorization query in the respective installation packages

To attack the developments in an orderly manner, they are divided into the different available agents.

#### Linux 
* `coredump` (.deb and .rpm)
The steps necessary to enable/disable the generation of coredumps are common in supported distributions and depend on the version of Linux applied.
Since Linux version 2.41 onwards, a template is implemented to define the location and name of the coredumps that are generated in the system, [here the reference](https://manpages.ubuntu.com/manpages/noble/man5/core.5.html).
Unlike the previous treatment, which, if enabled, generated the core file next to the location of the file that caused the error.
**Warning!.** As a result of this, it is necessary to make changes to the OS configuration files. with the possibility of deleting/overwriting any possible configuration made by the user.

* Debian packages
The use of `debconf` allows you to efficiently customize any necessary iteration with the user, along with the respective actions that arise from them.

#### MacOS
The generation of `coredump` in the MacOS environment aims to be more unified and possible to be used to be exported and/or analyzed, generating these in a specific location and related to the `PID` of the process that generates them.

* Packages (.pkg)
For the installation package, the [Packages tool](http://s.sudre.free.fr/Software/documentation/Packages/en/index.html) is used, which is distributed free of charge as part of the elementary development environment. This tool allows to creation of installation packages in a basic way. It will then be necessary to add to this tool the necessary plugins to allow the user to incorporate the aforementioned query. These plugins are not available as such and must be developed specifically, [reference](http://s.sudre.free.fr/Software/documentation/Packages/en/Distribution_UI_Customization.html#7)

**Comment by ncvicchi** [comment]
By management decision, no modifications to Linux environment installers will be made. Steps to generate core dumps will be added to the documentation as was planned, but no option in the installer to enable it will be made.
Macos installer was found to be a more difficult than expected to modify. It will be left unchanged until more analysis and time to implement it is available.
Windows is still WIP and it will be address next week.

**Comment by ncvicchi** [comment]
ETA was modified to allow Windows analysis. Both Linux and macOS required a lot more effort than expected and left no room to work on Windows installer.

**Comment by Leoquicenoz** [comment]
## Update

Start modifying the code in the `wazuh-installer.wxs` file to enable a checkbox to enable dump generation on windows agent installation.

**Comment by Leoquicenoz** [comment]
## Update

Currently Jenkins is being used to generate the `.msi` packages and verify if the changes in the code are generating the checkbox that is required to activate the automatic generation of the dump, we wanted to have a local environment for the generation of this file so we built a VM with the requirements that are requested in the [documentation](https://documentation.wazuh.com/current/development/packaging/generate-windows-package.html)

So far I have not been able to generate the `.msi` file and I am getting this output in powershell:

```powershell
.\generate_wazuh_msi.ps1

-OPTIONAL_REVISION empty. Using default value.
MSI_NAME = wazuh-agent-4.9.0-1.msi
Building MSI installer...
wazuh-installer.wxs
C:\Users\wazuh\Desktop\windows_agent\wazuh-21737-dump-option-windows\src\win32\wazuh-installer.wxs(67) : warning CNDL1077 : The 'WixShellExecTarget' Property contains '[APPLICATIONFOLDER]' in its value which is an illegal reference to another property.  If this value is a string literal, not a property reference, please ignore this warning.  To set a property with the value of another property, use a CustomAction with Property and Value attributes.
Windows Installer XML Toolset Linker version 3.14.1.8722
Copyright (c) .NET Foundation and contributors. All rights reserved.

C:\Users\wazuh\Desktop\windows_agent\wazuh-21737-dump-option-windows\src\win32\wazuh-installer.wxs(117) : warning LGHT1076 : ICE03: String overflow (greater than length permitted in column); Table: CustomAction, Column: Target, Key(s): SetCustomActionDataValue
C:\Users\wazuh\Desktop\windows_agent\wazuh-21737-dump-option-windows\src\win32\wazuh-installer.wxs(253) : warning LGHT1076 : ICE30: The target file 'ekhl4joq.exe|wazuh-agent.exe' might be installed in '[ProgramFilesFolder]\ossec-agent\' by two different conditionalized components on an LFN system: 'WAZUH_AGENT_EVENTCHANNEL.EXE' and 'WAZUH_AGENT.EXE'. If the conditions are not mutually exclusive, this will break the component reference counting system.
C:\Users\wazuh\Desktop\windows_agent\wazuh-21737-dump-option-windows\src\win32\wazuh-installer.wxs(247) : warning LGHT1076 : ICE30: The target file 'ekhl4joq.exe|wazuh-agent.exe' might be installed in '[ProgramFilesFolder]\ossec-agent\' by two different conditionalized components on an LFN system: 'WAZUH_AGENT_EVENTCHANNEL.EXE' and 'WAZUH_AGENT.EXE'. If the conditions are not mutually exclusive, this will break the component reference counting system.
C:\Users\wazuh\Desktop\windows_agent\wazuh-21737-dump-option-windows\src\win32\wazuh-installer.wxs(691) : warning LGHT1076 : ICE61: This product should remove only older versions of itself. No Maximum version was detected for the current product. (WIX_UPGRADE_DETECTED)
C:\Users\wazuh\Desktop\windows_agent\wazuh-21737-dump-option-windows\src\win32\wazuh-installer.wxs(115) : warning LGHT1076 : ICE68: Even though custom action 'CheckSvcRunning' is marked to be elevated (with attribute msidbCustomActionTypeNoImpersonate), it will not be run with elevated privileges because it's not deferred (with attribute msidbCustomActionTypeInScript).
```

**Comment by Leoquicenoz** [comment]
## Update

To add an additional checkbox in the graphical installation interface of the Wazuh Windows agent, you must modify the `<UI>` section in the `wazuh-installer.wxs` file, at this point you have the following structure:

```
<UI>
            <UIRef Id="WixUI_Advanced" />
            <Publish Dialog="InstallDirDlg" Control="Next" Event="NewDialog" Value="VerifyReadyDlg" Order="4"><![CDATA[WIXUI_DONTVALIDATEPATH OR WIXUI_INSTALLDIR_VALID="1"]]></Publish>
            <Publish Dialog="VerifyReadyDlg" Control="Back" Event="NewDialog" Value="InstallDirDlg" />
            <Publish Dialog="ExitDialog" Control="Finish" Event="DoAction" Value="LaunchUI">WIXUI_EXITDIALOGOPTIONALCHECKBOX = 1 and NOT Installed</Publish>
</UI>
``` 

I am facing a challenge because using `<UIRef Id="WixUI_Advanced" />` limits the actions that can be executed since it depends on the `WixUI_Advanced.wxs` file and to make it customizable you would have to modify this file and copy it directly into the project, which would not allow it to be updated independently if Wix generates any updates.

**Comment by Leoquicenoz** [comment]
## Update

The following custom dialog is added:

```
    <Fragment>
        <UI>
            <Dialog Id="CustomCheckDialog" Width="370" Height="270" Title="Custom Checkbox Dialog">
                <Control Id="GenerateDumpCheckbox" Type="CheckBox" X="20" Y="100" Width="330" Height="17"
                    Property="GENERATE_DUMP" CheckBoxValue="1"
                    Text="Enable automatic dump generation" />

                <Control Id="Next" Type="PushButton" X="236" Y="243" Width="75" Height="23" Default="yes" Text="Next">
                    <Publish Event="NewDialog" Value="NextDialog">1</Publish>
                </Control>

                <Control Id="Back" Type="PushButton" X="156" Y="243" Width="75" Height="23" Text="Back">
                    <Publish Event="NewDialog" Value="PreviousDialog">1</Publish>
                </Control>
            </Dialog>
        </UI>
    </Fragment>
``` 

```
        <UI>
            <UIRef Id="WixUI_Advanced" />
            <Publish Dialog="InstallDirDlg" Control="Next" Event="NewDialog" Value="CustomCheckDialog" Order="4"><![CDATA[WIXUI_DONTVALIDATEPATH OR WIXUI_INSTALLDIR_VALID="1"]]></Publish>
            <Publish Dialog="VerifyReadyDlg" Control="Back" Event="NewDialog" Value="CustomCheckDialog" />
            <Publish Dialog="ExitDialog" Control="Finish" Event="DoAction" Value="LaunchUI">WIXUI_EXITDIALOGOPTIONALCHECKBOX = 1 and NOT Installed</Publish>
            <Publish Dialog="CustomCheckDialog" Control="Next" Event="NewDialog" Value="VerifyReadyDlg" />
            <Publish Dialog="CustomCheckDialog" Control="Back" Event="NewDialog" Value="InstallDirDlg" />
        </UI>
``` 

![Screenshot from 2024-05-05 22-35-37](https://github.com/wazuh/wazuh/assets/106568370/6e03855b-6dcc-4bb0-a1ca-3aef9e039e35)

**Comment by Leoquicenoz** [comment]
## Update

I'm trying to modify the existing screens of the windows agent installer, but when using `WixUI_Advanced`, which already has predefined screens, it has not been possible to include the checkbox in any of the screens, the solution for the moment would be to generate an additional screen containing the checkbox and could even add an explanation of what is the core dump, is a solution to evaluate (the additional screen with the checkbox to enable and disable the core dump is already implemented).

Also I'm investigating how to enable the dump from the application installer (`.wxs` file), apparently we would have to generate some permissions from a powershell script and execute it from the installation sequence, but we need to investigate further to identify other alternatives.

**Comment by Leoquicenoz** [comment]
## Update

The following configuration is added to try to set up the dump:

```
    <Fragment>
        <CustomAction Id="SetWERLocalDumps" Property="QtExecCmdLine"
                    Value="reg add &quot;HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\wazuh-agent.exe&quot; /v DumpFolder /t REG_EXPAND_SZ /d &quot;%LOCALAPPDATA%\WazuhDumps&quot; /f" />
        <CustomAction Id="QtExecSetWERLocalDumps" BinaryKey="WixCA" DllEntry="CAQuietExec" Execute="deferred" Return="ignore" Impersonate="no" />

        <Binary Id="WixCA" SourceFile="$(sys.CABINETSDK_PATH)WixCA.dll" />
    </Fragment>


            <Custom Action="SetWERLocalDumps" Before="InstallFinalize">(GENERATE_DUMP = "1") AND NOT Installed</Custom>
            <Custom Action="QtExecSetWERLocalDumps" After="SetWERLocalDumps">(GENERATE_DUMP = "1") AND NOT Installed</Custom>
``` 

With the condition that it will only be executed when the core dump generation checkbox is checked

**Comment by Leoquicenoz** [comment]
## Update

According to the established guidelines, the Key of the registers for the dump must be generated from the existing `InstallerScripts.vbs` file, for which it is necessary to modify what was previously done since this used the cmd to access the registers, the following was established to follow up on what is executed:

```
Public Function VerifyOrCreateRegistryKey()
    On Error Resume Next

    Dim strKeyPath, oReg, lngResult
    Dim fso, logFile

    ' Set the registry key path that you want to check and/or create
    strKeyPath = "SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps"

    ' Registry object
    Set oReg = GetObject("winmgmts:{impersonationLevel=impersonate}!\\" & _
                        ".\root\default:StdRegProv")

    ' Check if the key exists
    lngResult = oReg.EnumKey(&H80000002, strKeyPath, Nothing)

    ' Create FileSystemObject
    Set fso = CreateObject("Scripting.FileSystemObject")
    ' Create or open the log file
    Set logFile = fso.OpenTextFile("C:\Users\wazuh\Desktop\logfile.txt", 8, True)

    If lngResult <> 0 Then
        ' The key does not exist, proceed to create it
        oReg.CreateKey &H80000002, strKeyPath
        WScript.Echo "Key created: " & strKeyPath
        logFile.WriteLine "Key created: " & strKeyPath

        ' Set values within the key
        ' Configure the dump directory
        oReg.SetStringValue &H80000002, strKeyPath, "DumpFolder", "C:\Dumps"
        ' Configure the type of dump (2 for full dump)
        oReg.SetDWORDValue &H80000002, strKeyPath, "DumpType", 2
        ' Set the limit on the number of dumps to save
        oReg.SetDWORDValue &H80000002, strKeyPath, "DumpCount", 10

        WScript.Echo "Registry values set correctly."
        logFile.WriteLine "Registry values set correctly."
    Else
        WScript.Echo "The key already exists, no changes made: " & strKeyPath
        logFile.WriteLine "The key already exists, no changes made: " & strKeyPath
    End If

    ' Close the log file
    logFile.Close

    VerifyOrCreateRegistryKey = 0
End Function
``` 

This is executed through a Custom Action in the `wazuh-installer.wxs` file, at the moment it is executed but it does not generate the necessary Key in the registry, according to the test messages that were established it can be verified that if it is executed but the message that comes out is: The key already exists, no changes made: SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps`, but when checking the registry manually, it is seen that the registry does not exist.

**Comment by Leoquicenoz** [comment]
## Update

It was identified that when trying to generate the Key from the `.msi` installer, it was generated in the registry `HKEY_LOCAL_MACHINE_MOW6432NodeMicrosoft Windows Error Reporting` which is the registry used for 32-bit software running on 64-bit, this was a problem because Wazuh when crashing, generates the dump file in the 64-bit registry which is `HKEY_LOCAL_MACHINE_SOFTWARE\Microsoft\Windows\Windows Error Reporting,` after the research done, a way was found to force the generation of the registry in 64-bit, so the function in the `.vbs` file is as follows:

Translated with DeepL.com (free version)

```
Public Function VerifyOrCreateRegistryKey()
    On Error Resume Next
    Dim strKeyPath, oReg
    Dim objCtx, objLocator, objServices
    Const HKEY_LOCAL_MACHINE = &H80000002

    Set objCtx = CreateObject("WbemScripting.SWbemNamedValueSet")
    objCtx.Add "__ProviderArchitecture", 64
    objCtx.Add "__RequiredArchitecture", True

    Set objLocator = CreateObject("WbemScripting.SWbemLocator")
    Set objServices = objLocator.ConnectServer(".", "root\default", "", "", , , , objCtx)
    Set oReg = objServices.Get("StdRegProv")

    strKeyPath = "SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\wazuh-agent.exe"

    oReg.CreateKey HKEY_LOCAL_MACHINE, strKeyPath
    oReg.SetStringValue HKEY_LOCAL_MACHINE, strKeyPath, "DumpFolder", "C:\Dumps"
    oReg.SetDWORDValue HKEY_LOCAL_MACHINE, strKeyPath, "DumpType", 2
    oReg.SetDWORDValue HKEY_LOCAL_MACHINE, strKeyPath, "DumpCount", 10

    Set objCtx = Nothing
    Set objLocator = Nothing
    Set objServices = Nothing
    Set oReg = Nothing

    VerifyOrCreateRegistryKey = 0
End Function
``` 

The Key is successfully generated and it is verified that when the crash is generated in the `wazuh-agent.exe` file, the `.dmp` file is automatically generated.
