### ISSUE TITLE
Improve AIT conftest.py script by adding a new parameter

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh#21775]
|Component|
|---|
| API |

## Description
Add a new parameter `--build-managers-only` to avoid building all the docker environment images. By using this parameter, only the manager image will be built.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by javiersanchz** [comment]
## Update

I was solving issues caused by `/var/lib/docker/overlay2` when I deleted it, which was preventing me from launching the AITs to work on the issue.

I was modifying the conftest.py to add the new parameter. It successfully launches the `integration_test_wazuh-manager` image, but it throws an error when launching the managers' containers. I'll take a closer look at it tomorrow.
