### ISSUE TITLE
False positive in CVE-2001-0718 vulnerability for VD

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#21825]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| Manager: 4.7.2, Agent: 4.7.2 | Wazuh component | Manager/Agent | Packages/Sources | macOS Sonoma 14.3 |

![image](https://github.com/wazuh/wazuh/assets/89791732/bb338d93-5887-4760-86f9-d5122eb47ab0)

![image](https://github.com/wazuh/wazuh/assets/89791732/9f35f10b-b048-4ed3-a537-0dd0589c3ee9)

A user reports a false positive where having found vulnerability CVE-2001-0718 in their vulnerability detector (VD).
There seems to be a problem in generating the CPE for that package, since as we can look at the condition, it is checking the version field (16.81), against the version that is set in the CPE, which would be 2002, then that condition is met and that's why it appears.

Further research should be done.

**Comment by snaow** [comment]
Reported again in community Slack channel. 
Issue: https://github.com/wazuh/wazuh/issues/22512 (close as it is a duplicated of this one)

**Comment by pereyra-m** [comment]
## Update

The following environment was used to reproduce the issue:
- Wazuh Manager v4.8.0 
- macOS Agent Ventura 13.3.1
- Microsoft Excel for macOS 16.83

It was found that now this type of false positive has become a false negative instead, because of:
- The difference between the type of version
- The lack of a proper version range

The first issue can be seen in the logs, we have two completely different formats that simply can't be compared. This is a feature of the new scanner that prevents an invalid comparison

```
2024/04/12 12:39:19 wazuh-modulesd:vulnerability-scanner[8174] packageScanner.hpp:328 at operator()(): DEBUG: Scanning package - 'excel' (Installed Version: 16.83, Security Vulnerability: CVE-2001-0718). Identified vulnerability: Version: 0. Required Version Threshold: . Required Version Threshold (or Equal): 2002.

2024/04/12 12:39:19 wazuh-modulesd:vulnerability-scanner[8174] versionMatcher.hpp:157 at createVersionObject(): DEBUG: Error creating VersionObject (CalVer). Version string doesn't match the specified type. Version string: 16.83

2024/04/12 12:39:19 wazuh-modulesd:vulnerability-scanner[8174] packageScanner.hpp:493 at operator()(): DEBUG: Failed to scan package: 'excel', CVE Numbering Authorities (CNA): 'nvd', Error: 'Unable to compare versions (16.83 vs 2002).'
```

The second issue refers to the fact that there isn't currently in the NVD feed an adequate version range that is suitable for Microsoft products on macOS.
There are have CPEs in the NVD that name this OS, but the related versions still are wrong or missing so a translation won't work

`cpe:2.3:a:microsoft:excel:2016:*:*:*:*:mac_os_x:*:*` ([Example CVEs](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&isCpeNameSearch=true&seach_type=all&query=cpe:2.3:a:microsoft:excel:2016:*:*:*:*:mac_os_x:*:*))

`cpe:2.3:a:microsoft:excel:2016:*:*:*:*:macos:*:*` ([Example CVEs](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&isCpeNameSearch=true&seach_type=all&query=cpe:2.3:a:microsoft:excel:2016:*:*:*:*:macos:*:*))

`cpe:2.3:a:microsoft:excel:2019:*:*:*:*:macos:*:*` ([Example CVEs](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&isCpeNameSearch=true&seach_type=all&query=cpe:2.3:a:microsoft:excel:2019:*:*:*:*:macos:*:*))

`cpe:2.3:a:microsoft:excel_for_mac:2011:*:*:*:*:*:*:*` ([Example CVEs](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&isCpeNameSearch=true&seach_type=all&query=cpe:2.3:a:microsoft:excel_for_mac:2011:*:*:*:*:*:*:*))

`cpe:2.3:a:microsoft:excel_for_mac:2016:*:*:*:*:*:*:*` ([Example CVEs](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&isCpeNameSearch=true&seach_type=all&query=cpe:2.3:a:microsoft:excel_for_mac:2016:*:*:*:*:*:*:*))

Considering the information reported by **syscollector**
<details><summary>Details</summary>
<p>

```
sqlite> SELECT * from sys_programs where name like "%excel%";
     scan_id = 0
   scan_time = 2024/04/12 15:39:18
      format = pkg
        name = Excel
    priority =  
     section = public.app-category.productivity
        size = 0
      vendor = microsoft
install_time =  
     version = 16.83
architecture =  
   multiarch = 
      source = utilities
 description = com.microsoft.Excel
    location = /Applications/Microsoft Excel.app/Contents/Info.plist
         cpe = 
    msu_name = 
    checksum = 3902b3d8788c33ce53e7fc9aa2f0189e6431678e
     item_id = 556e3cd212c77e67665d7f35830e56f831ba550d
```

</p>
</details> 

Currently only the CVEs of the this CPE will be considered (CVE-2001-0718 is one of them)

`cpe:2.3:a:microsoft:excel:-:*:*:*:*:*:*:*` ([Example CVEs](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&isCpeNameSearch=true&seach_type=all&query=cpe:2.3:a:microsoft:excel:-:*:*:*:*:*:*:*))

To fix this, we need to search in the Microsoft catalog for more detailed information about the affected versions of the packages released for macOS. This can be done with an automatic feed migration or inserted manually. For example

https://learn.microsoft.com/en-us/security-updates/securitybulletins/2001/ms01-050

<details><summary>Details</summary>
<p>

![2024-04-12_21-17](https://github.com/wazuh/wazuh/assets/65046601/e96fc43d-f117-4c2b-9177-548c8d4a2d58)

</p>
</details> 

## Conclusion

The new vulnerability detector won't produce this type of false positives, but version information is missing to detect vulnerabilities of Microsoft products in macOS. We should include the Microsoft security bulletins in the feed or introduce the required versions manually.

**Comment by sebasfalcone** [comment]
We may want to start using the vendor field from syscollector to filter packages.


On the feed we could obtain this information from two places:
- cpes array
- vendor field

```json
        {
          "cpes": [
            "cpe:2.3:a:microsoft:excel:*:*:*:*:*:*:*:*"
          ],
          "defaultStatus": "unaffected",
          "product": "excel",
          "vendor": "microsoft",
          "versions": [
            {
              "lessThanOrEqual": "2002",
              "status": "affected",
              "version": "0",
              "versionType": "custom"
            }
          ]
        }
```

I think that the cpes array is more robust given that it is a known cpe for a product, and the vendor field is sometimes obtained from the vendor feed itself (not sanitized or cross checked)


@Damian-Mangold What do you think about the cpe field? Is a good source of information for the vendor of the product?

CC: @Dwordcito

**Comment by pereyra-m** [comment]
It was confirmed that this false positive no longer occurs in v4.8.0.

The proper scanning of this type of packages continues at https://github.com/wazuh/intelligence-platform/issues/1472

CC @sebasfalcone @Dwordcito
