### ISSUE TITLE
Bug/flaw when analyzing vulnerability status of package bsdutils for ubuntu (jammy)

### ISSUE THREAD

**Issue by fernandogont** [wazuh/wazuh#21887]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.2-1   |  | Manager | Packages | Ubuntu |

I'm using Wazuh for vulnerability management. Wazuh is incorrectly reporting the vulnerabilities in the package bsdutils.

It seems Wazuh is confusing two different packages, bsdutils and util-linux, which, in my case, have the following versions:

- util-linux                       2.37.2-4ubuntu3                         amd64        miscellaneous system utilities
- bsdutils                         1:2.37.2-4ubuntu3                       amd64        basic utilities from 4.4BSD-Lite

Wazuh is incorrectly reporting the following vulnerabilities:

- CVE-2013-0157
- CVE-2016-5011
- CVE-2014-9114
- CVE-2021-37600
- CVE-2016-2779
- CVE-2021-3995
- CVE-2021-3996

For example, for CVE-2021-3995, it says:

- Name: bsdutils
- Version: 2.37.2-4ubuntu3
- Condition: Package less than 1:2.37.2-4ubuntu2

So it seems it is checking the version against util-linux, rather than against bsdutils?
(Note: according to [this](https://ubuntu.com/security/CVE-2021-3995), CVE-2021-3995 would apply to utl-linux, rather than bsdutils.
  
Thanks!

Regards,
Fernando

**Comment by mkkce** [comment]
Hi,

Any updates regarding this issue, because there is still not fixed and I have the same issue. Did you manage to resolve this issue?

Regards,
Mirco

**Comment by pereyra-m** [comment]
Hello @fernandogont !

What is your Ubuntu version?
I was able to reproduce this issue in Wazuh v4.7.4 in Ubuntu Jammy.

The scanner might seem to mix the packages because they are related. At https://packages.ubuntu.com/jammy/bsdutils, the sources of  `util-linux` are shown. See also this example
https://ubuntu.com/security/cves/CVE-2016-5011.json

<details><summary>Details</summary>
<p>

```
...
          {
            "is_source": false,
            "is_visible": false,
            "name": "bsdutils",
            "pocket": "esm-infra",
            "source_link": "https://launchpad.net/ubuntu/+source/util-linux",
            "version": "1:2.27.1-6ubuntu3.10+esm2",
            "version_link": null
          },
...
```

</p>
</details> 

But the main problem with `bsdutils` is that the version reported used in the scan doesn't contain an epoch and the feed does.

For example:

```
DEBUG: (5468): The 'bsdutils' package (2.37.2-4ubuntu3.4) from agent '001' is vulnerable to 'CVE-2014-9114'. Condition: 'Package less than 1:2.36.1-8ubuntu1'

DEBUG: (5468): The 'bsdutils' package (2.37.2-4ubuntu3.4) from agent '001' is vulnerable to 'CVE-2021-37600'. Condition: 'Package less than 1:2.37.2-4ubuntu2'
```

This behavior is the same that we would see with `dpkg` 

```
root@502c89ad8144:/var/ossec# dpkg --compare-versions 2.37.2-4ubuntu3.4 lt 1:2.37.2-4ubuntu2
root@502c89ad8144:/var/ossec# echo $?
0
``` 

It seems that the epoch is removed during the scan, because it's properly reported by **syscollector**
```
sqlite> SELECT name,version from sys_programs where name like "%bsdutils%";
   name = bsdutils
version = 1:2.37.2-4ubuntu3.4
```

Soon, the new vulnerability scanner will be released in Wazuh v4.8.0.
Here we can see that the `bsdutil` package is analyzed with the proper epoch in the version, but in fact, the version comparison stage isn't reached because the CVEs are marked as not vulnerable by their OS version

<details><summary>Details</summary>
<p>

```
DEBUG: Translation for package 'bsdutils' in platform 'ubuntu' not found. Using provided packageName.
DEBUG: Initiating a vulnerability scan for package 'bsdutils' (deb) (ubuntu developers <ubuntu-devel-discuss@lists.ubuntu.com>) with CVE Numbering Authorities (CNA) 'canonical' on Agent '982bdac73f35' (ID: '002', Version: 'v4.7.4').
DEBUG: The platform is not in the list for Package: bsdutils, Version: 1:2.37.2-4ubuntu3.4, CVE: CVE-2016-5011, OS CPE: , OS code name: jammy
DEBUG: The platform is not in the list for Package: bsdutils, Version: 1:2.37.2-4ubuntu3.4, CVE: CVE-2018-7738, OS CPE: , OS code name: jammy
DEBUG: The platform is not in the list for Package: bsdutils, Version: 1:2.37.2-4ubuntu3.4, CVE: CVE-2021-3995, OS CPE: , OS code name: jammy
DEBUG: The platform is not in the list for Package: bsdutils, Version: 1:2.37.2-4ubuntu3.4, CVE: CVE-2021-3995, OS CPE: , OS code name: jammy
DEBUG: The platform is not in the list for Package: bsdutils, Version: 1:2.37.2-4ubuntu3.4, CVE: CVE-2021-3996, OS CPE: , OS code name: jammy
DEBUG: The platform is not in the list for Package: bsdutils, Version: 1:2.37.2-4ubuntu3.4, CVE: CVE-2021-3996, OS CPE: , OS code name: jammy
DEBUG: Vulnerability scan for package 'bsdutils' on Agent '002' has completed.
```

</p>
</details> 


We shouldn't see this issue in the next minor release.

**Comment by sebasfalcone** [comment]
## Conclusion
Issue solved in 4.8.0, no backport expected for 4.7.x

**Comment by Dwordcito** [comment]
Please add efficacy tests for this specific case, target release 4.9.0

**Comment by sebasfalcone** [comment]
## Update
- Upward merge done
- Rebase needed
