### ISSUE TITLE
Proposal for enhancements in wazuh-db to improve efficiency and concurrency

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#21919]
This task aims to propose some enhancements for our database engine, _wazuh-db_, which serves as a wrapper for _SQLite_ with added multi-threading support. Our main goal is to enhance the efficiency, concurrency, and overall performance of _wazuh-db_. Below are the key areas we have identified for potential improvements:

1. **Improving Thread Concurrency**: We've noticed opportunities to optimize how threads manage concurrent access. Enhancing concurrency could lead to significant performance gains, especially in high-load scenarios.

2. **Dedicating Threads to Specific Databases**: We propose to reserve certain threads for specific databases, such as _global.db_. This approach could improve the responsiveness and reliability of database operations by ensuring dedicated resources for high-priority tasks.

3. **Efficiency Drop in Synchronization Algorithm (Rsync)**: We have observed areas where the current synchronization algorithm, based on Rsync, could be optimized. Identifying and addressing these inefficiencies could significantly improve data synchronization speed and reliability.

Our objective with these improvements is not just to enhance the performance of _wazuh-db_ but also to ensure it can scale effectively and maintain high levels of reliability and consistency across all operations.

## Definition of done

- We must write each proposal into a different comment.
- Every proposal must include an estimation of the impact and the complexity of the fix.
- Proposals should also refer to the related code.

**Comment by Dwordcito** [comment]
### Performance Analysis and Optimization Suggestions

#### Summary

We have identified several areas where performance can be improved through adjustments in our code and database operations. Below are the details of our findings and suggestions for enhancements.

1. **Mutex Operations Overhead**: We observed a high frequency of lock/unlock operations over a span of 10 minutes, indicating excessive mutex syscall usage. This area warrants a closer look to optimize the usage of mutexes and reduce the overhead.
```
dwordcito-MS-7D25# strace -c -fp $(pgrep -n wazuh-db)                                                    
strace: Process 823022 attached with 12 threads                                                          
^Cstrace: Process 823022 detached                                                                        
strace: Process 823023 detached                                                                          
strace: Process 823024 detached                                                                          
strace: Process 823025 detached                                                                          
strace: Process 823026 detached                                                                          
strace: Process 823027 detached                                                                          
strace: Process 823028 detached                                                                          
strace: Process 823029 detached                                                                          
strace: Process 823030 detached                                                                          
strace: Process 823031 detached                                                                          
strace: Process 823032 detached                                                                          
strace: Process 823034 detached                                                                          
% time     seconds  usecs/call     calls    errors syscall                                               
------ ----------- ----------- --------- --------- ----------------                                      
 59,06   44,129227         358    123089      1752 futex                                                 
 19,23   14,366425        7432      1933           clock_nanosleep                                       
  9,63    7,192260        6902      1042           pselect6                                              
  7,72    5,767334         132     43512           epoll_wait                                            
  1,60    1,196290           3    333274           write                                                 
  0,43    0,323274           4     80040           recvfrom                                              
  0,43    0,321497           3     99782      1934 newfstatat                                            
  0,42    0,315164           6     48638         1 openat                                                
  0,39    0,289176           3     80217           epoll_ctl                                             
  0,36    0,267778           1    192772           lseek                                                 
  0,26    0,194698           1     98703           read                                                  
  0,16    0,123023           3     39971           sendto                                                
  0,15    0,109371           2     48733           close                                                 
  0,06    0,045768          28      1618           fsync                                                 
  0,05    0,040107           7      5698           madvise                                               
  0,02    0,015190          38       397           unlink                                                
  0,02    0,012562           1      6839           fcntl                                                 
  0,00    0,002286        1143         2           restart_syscall                                       
  0,00    0,001959           7       248           mprotect                                              
  0,00    0,001608           9       177           accept                                                
  0,00    0,000580           1       399           getpid                                                
  0,00    0,000523           1       398           geteuid                                               
  0,00    0,000003           3         1           getcwd                                                
------ ----------- ----------- --------- --------- ----------------                                      
100,00   74,716103          61   1207483      3687 total 
```
2. **Inefficient Timeout Handling in wnotify_wait**: The `wnotify_wait` function is set to timeout every 100ms, leading to a significant number of lock and unlocks. Strace reveals an overuse of these operations in standby mode. We should consider removing the timeout and seek alternative approaches for managing mutual exclusion more efficiently.

3. **Global Checksum Removal Operation for FIM Tables**: Attempts to remove elements outside the bounds of a global checksum for FIM tables on an i9 system with an SSD were found to take 25 milliseconds, even though in most cases, nothing is actually removed. For 2500 agents every 5 minutes, this equates to 62500ms (1 minute), meaning we spend 1 minute every 5 minutes just on this operation.

#### Database Optimization

We discovered that while there are indexes for `file` and `full_path`, we lack a composite index, leading to unnecessary read operations.

**SQL Query Performance Before Index Optimization**:
```sql
EXPLAIN QUERY PLAN DELETE FROM fim_entry WHERE (file < ? OR file > ?) AND type = 'file';
-- Result: Utilizes MULTI-INDEX OR with individual fim_file_index.

EXPLAIN QUERY PLAN DELETE FROM fim_entry WHERE (type='registry_key' OR type='registry_value') AND (full_path < ? OR full_path > ?);
-- Result: Utilizes MULTI-INDEX OR with individual fim_full_path_index.
```


**Optimization Steps:**

1. Created a composite index for file and type to optimize deletion operations involving these columns.
2. Similarly, created a composite index for full_path and type.
```sql
SQL Query Performance After Index Optimization:
-- After creating fim_file_type_index:
EXPLAIN QUERY PLAN DELETE FROM fim_entry WHERE (file < ? OR file > ?) AND type = 'file';
-- Result: Now uses a COVERING INDEX, significantly improving efficiency.

-- After creating fim_full_path_type_index:
EXPLAIN QUERY PLAN DELETE FROM fim_entry WHERE (type='registry_key' OR type='registry_value') AND (full_path < ? OR full_path > ?);
-- Result: Again, uses a COVERING INDEX, enhancing performance.
```

**Conclusion**

Creating these indexes introduces a covering index, meaning SQLite can perform the delete operation more efficiently, using fewer resources and completing faster. This is indicative of a well-thought-out index design, especially for queries involving multiple conditions and requiring access to several columns.

**Comment by jotacarma90** [comment]
## Parameterize the depth value of the synchronization algorithm

Another possible improvement proposal regarding the synchronization of the databases could be to parameterize the maximum depth value we want the synchronization algorithm to reach.

In summary, the algorithm works by dividing the DB in half and resending the checksum, until it reaches a single entry, where if it is still checksum_fail, that single entry is sent. We could parameterize the depth value to make, for example, that when reaching a value of 16, instead of continuing dividing the DB, all the remaining entries are sent, since it could be less expensive than the remaining checksum operations. And by parameterizing this value, we could modify it to shuffle and optimize the synchronization in each particular case.

I am in the process of testing this process to try to give a practical value of the cost of operations in each situation.

I continue to look for other improvements and situations related to FIM in particular that may affect this optimization.

**Comment by TomasTurina** [comment]
### Dedicated threads to execute queries to the global DB

The main source of agent disconnections has always been the `wazuh-db` daemon, since the `wazuh-remoted` daemon needs to update the agent state in the DB when processing keep-alives. If the `wazuh-db` daemon is overloaded or blocked for some reason, this can cause `wazuh-remoted` to also block, causing agents to disconnect from the manager.

It has also been observed that the place where `wazuh-db` usually blocks (where it has the longest delays) is when running queries against _agent_ databases, such as when synchronizing information from _FIM_, _rootcheck_ or some other agent module that synchronizes information with the manager.

Generally, queries that are directed to the _global_ database are executed faster, since this database is much simpler than those that store agent information. Within these queries are those performed by `wazuh-remoted` to update agent states.

This proposal consists of investigating the possibility of implementing dedicated threads in `wazuh-db` that only handle queries directed to the _global_ DB, while, on the other hand, there are other threads that handle the rest of the queries. Maintaining the state of agents and their connection is of greater importance than processing the rest of the information, so this design would avoid the loss of agents when `wazuh-db` is heavily loaded executing agent-specific queries. Additionally, if these other queries fail due to overload issues in `wazuh-db`, they can recover on their own in future syncs with the manager.

**Comment by jotacarma90** [comment]
# FIM synchronization, flow and important settings

To try to optimize the FIM sync, it is necessary to understand the behavior it has and how it interacts with both `wazuh-db` and the agent's buffer.

When we start FIM, the first `baseline` scan occurs, which generates the entire agent database. When the scan finishes, the first synchronization starts. In the ideal case that the agent buffer does not exist (disabling `client_buffer`), and that the manager can handle all the message flow, we would have a clean and fast synchronization, in which the agent sends all the data of the DB without the need of any algorithm (Testing 40000 entries of registers synchronized in about 12 seconds).

However, in a real environment, by default the `client_buffer` has a `queue_size` of 5000, and an eps of 500. This directly implies that some of the synchronization messages are going to be lost in the sending. Therefore this first sync will be incomplete. This is where the [FIM sync settings](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html#synchronization) come into play:

- `interval`: Value in seconds in which the FIM sync is re-executed.
- `max_interval`: Maximum value to which we can increase the previous interval. The `interval` is doubled every time a new sync is tried to be executed (for reaching the expected interval), but it is avoided due to the detection that there is still communication with the manager.
- `response_timeout`: Value in seconds that refers to how much time the agent must pass without receiving any message from the manager to consider that the communication has finished.

This last setting needs clarification. The agent is not able to know if a synchronization has finished. Therefore, we take as a reference the time of the last message sent by the manager to proceed to start another synchronization.
In this way, if messages have been lost (and therefore the DB of the manager is still incomplete or erroneous), the manager will finish the communication with the agent, and it will be necessary to wait for the next interval to start the algorithm again.

Here we can see the code in charge of re-executing the synchronizations, increasing the interval and checking if the manager has sent any message in the last `response_timeout` seconds:

https://github.com/wazuh/wazuh/blob/c6cceb9424dfbc7efeba7ffce84c77085eef3353/src/syscheckd/src/db/src/fimDB.cpp#L48-L78

In the practice, this can become very costly, because each time a sync is executed, many of the messages can be lost and therefore the efficiency of the algorithm will be very bad.

## Testing

Testing, with a DB of 40000 log entries, I have been able to verify that the sending of all the messages without impediments, remains in about 12 seconds:

[ossec_nobucket.zip](https://github.com/wazuh/wazuh/files/14373615/ossec_nobucket.zip)

However, if any of the messages is lost (due to `client_agent` or `wazuh-db`), the process will be restarted multiple times until a complete synchronization is achieved, which can take up to 15-17 minutes in this case (depend on multiples setting, but it is a heavy process).

Understanding this, it can be seen that the complexity and cost of synchronization increase dramatically the more events that are lost, as it ends up starting over and over again.

Looking at practical examples with the following tests:

I have used an environment with manager (ubuntu 23) and agent (Windows 11), disabling all possible modules except FIM. Agent configuration (`client_buffer` and `syscheck`):
```
  <!-- Agent buffer options -->
  <client_buffer>
    <disabled>no</disabled>
    <queue_size>10000</queue_size>
    <events_per_second>1000</events_per_second>
  </client_buffer>

  <!-- File integrity monitoring -->
  <syscheck>

    <disabled>no</disabled>

    <!-- Frequency that syscheck is executed default every 12 hours -->
    <frequency>43200</frequency>

    <windows_registry arch="both">HKEY_LOCAL_MACHINE\SOFTWAREtest</windows_registry>

    <!-- Frequency for ACL checking (seconds) -->
    <windows_audit_interval>60</windows_audit_interval>

    <!-- Nice value for Syscheck module -->
    <process_priority>10</process_priority>

    <!-- Maximum output throughput -->
    <max_eps>0</max_eps>

    <!-- Database synchronization settings -->
    <synchronization>
      <enabled>yes</enabled>
      <interval>10</interval>
      <max_interval>10</max_interval>
      <max_eps>0</max_eps>
      <response_timeout>10</response_timeout>
    </synchronization>
  </syscheck>
```

Note: The sync settings used, are oriented to always have an active synchronization (you can play with them to try to increase the time between each sync, so you don't try to do multiple `integrity_check_global` during the same sync, increasing the total time in which the databases end up synchronized, but reducing the load for the manager).

I have used about 40000 registry entries:
```
2024/02/22 03:32:34 wazuh-agent[9044] create_db.c:1822 at fim_print_info(): DEBUG: (6335): Fim file entries count: '0'
2024/02/22 03:32:34 wazuh-agent[9044] create_db.c:1823 at fim_print_info(): DEBUG: (6354): Fim registry entries count: '8122'.
2024/02/22 03:32:34 wazuh-agent[9044] create_db.c:1824 at fim_print_info(): DEBUG: (6371): Fim registry values entries count: '32242'.
```

I have taken the time measurements taking into account the time from the beginning of the first synchro, until the last message needed to have both databases synchronised.
- Using the updated 4.7.3 branch after the index changes:
| 4.7.3 | Agent | Manager |
|-------|-------|---------|
| 1 try | 16:34 | 16:36   |
| 2 try | 16:55 | 16:57   |

- Using branch `21919-add-parameter-max-depth-sync` where I implement a change in the algorithm to have a maximum depth of 8 in the algorithm:
| 8 depth | Agent | Manager |
|---------|-------|---------|
| 1 try   | 14:52 | 16:00   |
| 2 try   | 14:31 | 15:14   |



# Conclusions

- There is a minor improvement by not reaching the maximum depth of the algorithm. **The change is not very complex**, I show it in the previous message, it would only be necessary to parameterize that value to include it as an internal setting, for example.
- In order to **reduce the load** in wazuh-db, we can increase the `interval`, `max_interval` and `response_timeout` (especially in the cases in which it is necessary to launch multiple times the algorithm to end up matching the databases). (The disadvantage is that it takes longer overall to achieve synchronization.)
- **The most critical and costly point of the synchronization is the loss of messages after the initial FIM scan**, since it tries to send the entire database, and when losing a large number of messages it is necessary to re-launch the algorithm multiple times. This algorithm is optimized to find small differences between both DBs, but not to end up sending an entire database. **One option would be to try to implement a different algorithm that only works for this first synchronization** (after the scan baseline), for example, sending the database in chunks until it is complete.

**Comment by TomasTurina** [comment]
### Add a new input socket or query preprocessing

A new input socket or query preprocessing phase could be introduced to redirect queries entering `wazuh-db` to different thread pools depending on their purpose.

Queries that aim to update information or query such information should continue to be handled by the current thread pool, but there are other types of queries that should have their own dedicated threads as they can be more expensive to process and reduce performance of the rest of the queries.

Some types of queries that could be moved to a new processing pool:

#### General:
- All those that enter through the `wdbcom_dispatch` function.

#### Agent databases:
- `remove`.
- `begin`, `commit` and `close`.
- `vacuum` and `get_fragmentation`.
- `sleep`.

#### Global databases:
- `backup`.
- `vacuum` and `get_fragmentation`.
- `sleep`.

#### Wazuhdb type queries:
- `remove`.

All of these queries perform tasks that can slow down the processing of the rest of the queries and should be treated separately.

In addition, the type of queries `sql` (associated with all DBs) could also be taken into account to be treated separately since they can contain any type of queries and also slow down the processing of the rest.

> Note: A lot of code has also been identified that could be simplified when processing each type of query. This perhaps also has a positive effect on `wazuh-db` performance, for example by removing validations that slow down processing.

**Impact**: Medium/Small
**Complexity**: Medium

**Comment by TomasTurina** [comment]
We also need to improve the way databases are updated, especially agent databases. It is very inefficient to have a thread (`run_up` function) that loads each database into memory every time Wazuh DB is restarted just to check if that database needs to be updated. Additionally, and to make this behavior worse, it loads 1 DB into memory per second, while we have another thread (function `run_gc`) that starts to close them when the limit is exceeded (which is something easy to achieve in big environments).
