### ISSUE TITLE
NVD - CVE-2018-19666

### ISSUE THREAD

**Issue by pillarsdotnet** [wazuh/wazuh#2195]
Bug description
----------------

[CVE-2018-19666](https://nvd.nist.gov/vuln/detail/CVE-2018-19666) has received a "High" rating:

* [CVSS v3.0=7.8](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?name=CVE-2018-19666&vector=AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H)
* [CVSS v2.0=7.2](https://nvd.nist.gov/vuln-metrics/cvss/v2-calculator?name=CVE-2018-19666&vector=AV:L/AC:L/Au:N/C:C/I:C/A:C)

For many organizations, this rating means that we cannot ignore this report with impunity, no matter how misguided we feel it may be.

See upstream issue [ossec/ossec-hids#1585](https://github.com/ossec/ossec-hids/issues/1585).

**Comment by vikman90** [comment]
Hi @pillarsdotnet,

Thank you so much for opening this issue. If I understand it correctly, it points a directory traversal vulnerability in the Active Response component.

We already fixed this vulnerability in Wazuh v3.0 (a4a2d60). If we set up the vulnerable configuration in a Wazuh system, the agent will refuse to launch AR commands because the path at the `<executable>` option references a parent folder.

We tested this configuration:
```xml
<command>
  <name>win_route-null</name>
  <executable>..\..\..\..\Users\Public\malware.exe</executable>
  <expect></expect>
  <timeout_allowed>yes</timeout_allowed>
</command>

<active-response>
  <command>win_route-null</command>
  <rules_id>503</rules_id>
  <location>local</location>
</active-response>
```

And we see this log in the agent:

```
2019/01/02 16:36:58 ossec-agent: ERROR: Active response command '..\..\..\..\Users\Public\malware.exe' vulnerable to directory transversal attack. Ignoring.
```

This issue also applies to UNIX agents, so that fix solves the problem on all platforms.

Hope it helps.
Cheers.

**Comment by vikman90** [comment]
Hi,

Only to clarify this issue: there are three main points where the user may request a command execution:

1. Active response (the object of this issue): option `<command>`
2. Logcollector through log formats _command_ and _full_command_: `<localfile><command>`
3. Module _command_: `<wodle name="command">`

According to the documentation ([AR command](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/commands.html)], the eligible AR scripts must be in _/var/ossec/active-response/bin_. On the other hand, scheduled commands —(2) and (3)— allow running any executable in the system. However, these scheduled commands are allowed in the local configuration (_ossec.conf_) only, unless we enable [remote commands](https://documentation.wazuh.com/current/user-manual/reference/internal-options.html?highlight=remote_commands#logcollector).

This is a fundamental difference, and that's why allowing path traversal in AR is considered a vulnerability IMHO.

Best regards.

**Comment by pillarsdotnet** [comment]
Thanks very much.  Is there any way to notify MITRE that Wazuh 3.0 and later is unaffected by this bug?

**Comment by vikman90** [comment]
Hi,

I've just sent them a mail to clarify that point.

Thanks.
