### ISSUE TITLE
issue in viewing the browser screen 

### ISSUE THREAD

**Issue by sundarrdeveloper** [wazuh/wazuh#21990]
Steps 1:  I'm using the cmd install.sh 
Step 2:  after that showing  message in terminal 

 - Update completed
 
Step 3:  Running this cmd in particular folder. 

/var/www/html/xwiki/wazuh#          /var/ossec/bin/wazuh-control start

Starting Wazuh v5.0.0...
wazuh-execd already running...
wazuh-agentd already running...
wazuh-syscheckd already running...
wazuh-logcollector already running...
wazuh-modulesd already running...
Completed.  

After this completed message how to see the output the screen in browser. Help me to see the output.

**Comment by jftuduri** [comment]
Hello sundarrdeveloper!
I understand that you want to access the Wazuh Dashboard.

The Wazuh solution is comprised by 4 main components:

- Wazuh Indexer
- Wazuh Server
- Wazuh Dashboard
- Wazuh Agents

The first three (Indexer, Server and Dashboard) are the central components.
In order to be able to acces the web interface (the Dashboard) you need to install the three central components.
This current repository (wazuh/wazuh) only hosts the Wazuh Server (or Manager) and the Wazuh Agents.

You can find more details about these components [here](https://documentation.wazuh.com/current/getting-started/components/index.html) and about the general architecture [here](https://documentation.wazuh.com/current/getting-started/architecture.html).

There are several ways to deploy Wazuh, I recommend that you follow this quickstart guide to have a full instance of Wazuh running in just a few minutes: https://documentation.wazuh.com/current/quickstart.html

Alternatively, consider the other deployment alternatives that are listed here: https://documentation.wazuh.com/current/deployment-options/index.html

Regards!

**Comment by Damian-Mangold** [comment]
This issue is being closed due to inactivity. We appreciate your participation in our community and your valuable contributions that help us improve every day. If you have any questions or concerns in the future, feel free to reach out to us.

Best regards!
