### ISSUE TITLE
Unexpected results in vulnerability detection module on Ubuntu 22.04 agent using alternative packages

### ISSUE THREAD

**Issue by santipadilla** [wazuh/wazuh#22017]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta1 | Vulnerability Detection Feed | Agent | Packages | Ubuntu 22 |

## Description

During the development of [this issue](https://github.com/wazuh/wazuh-qa/issues/4943) investigating vulnerable packages in 4.8.0-beta1 on different operating systems.

It was noticed unexpected results with Ubuntu 22.04 agent with the following features:

<details><summary>System information</summary></br>

```console
root@ip-172-31-3-1:/home/qa# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy


```

</details>

<details><summary>Agent version</summary></br>

```console
root@ip-172-31-3-1:/home/qa# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.8.0"
WAZUH_REVISION="40803"
WAZUH_TYPE="agent"

```
</details>

<details><summary>Agent status</summary></br>

```console
root@ip-172-31-3-1:/home/qa# systemctl status wazuh-agent -l
● wazuh-agent.service - Wazuh agent
     Loaded: loaded (/lib/systemd/system/wazuh-agent.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-02-19 11:23:06 UTC; 2h 1min ago
    Process: 10830 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/S>
      Tasks: 32 (limit: 4623)
     Memory: 20.3M
        CPU: 47.476s
     CGroup: /system.slice/wazuh-agent.service
             ├─10852 /var/ossec/bin/wazuh-execd
             ├─10863 /var/ossec/bin/wazuh-agentd
             ├─10877 /var/ossec/bin/wazuh-syscheckd
             ├─10891 /var/ossec/bin/wazuh-logcollector
             └─10908 /var/ossec/bin/wazuh-modulesd

Feb 19 11:22:59 ip-172-31-3-1 systemd[1]: Starting Wazuh agent...
Feb 19 11:22:59 ip-172-31-3-1 env[10830]: Starting Wazuh v4.8.0...
Feb 19 11:23:00 ip-172-31-3-1 env[10830]: Started wazuh-execd...
Feb 19 11:23:01 ip-172-31-3-1 env[10830]: Started wazuh-agentd...
Feb 19 11:23:02 ip-172-31-3-1 env[10830]: Started wazuh-syscheckd...
Feb 19 11:23:03 ip-172-31-3-1 env[10830]: Started wazuh-logcollector...
Feb 19 11:23:04 ip-172-31-3-1 env[10830]: Started wazuh-modulesd...
Feb 19 11:23:06 ip-172-31-3-1 env[10830]: Completed.
Feb 19 11:23:06 ip-172-31-3-1 systemd[1]: Started Wazuh agent.
```
</details>

With Ubuntu 22.04 vulnerabilities are detected with the default "apt install" installation such as "sudo apt install openssl" or "sudo apt install samba". But when downloading and installing a package from an official repository it does not detect any vulnerability with any of the tested packages except with [mysql](https://downloads.mysql.com/archives/community/) and [wireshark](https://launchpad.net/ubuntu/+source/wireshark).

By default, vulnerabilities appear as is the case with Vim but when downloading and installing those packages individually from its official repository, no vulnerability appears. Ubuntu does detect the installation and configuration of the packages but not the vulnerabilities.

It has been tested with versions that have vulnerabilities. To see the vulnerabilities information we have used [this website](https://www.cvedetails.com/) and to check if they are known by ubuntu [its official website](https://ubuntu.com/security/cves). The download and installation has been from the official repositories of each package:

> openssl https://www.openssl.org/source/old/index.html
```console
root@ubuntu-agent:/home/vagrant# openssl version
OpenSSL 3.0.1 14 Dec 2021 (Library: OpenSSL 3.0.2 15 Mar 2022)
```
> libreoffice https://www.libreoffice.org/download/download-libreoffice/
```console
root@ubuntu-agent:/home/vagrant# /usr/local/bin/libreoffice6.2 --version
LibreOffice 6.2.1.1 757c58e8cb70b2982843211a54750fb3cd79acd5
```
> postgresql https://www.postgresql.org/download/
```console
root@ubuntu-agent:/home/vagrant# /usr/local/pgsql/bin/psql --version
psql (PostgreSQL) 12.0
```
> nodejs https://nodejs.org/dist/
```console
root@ubuntu-agent:/home/vagrant# node -v
v18.5.0
```
> vim https://www.vim.org/download.php#unix
```console
root@ubuntu-agent:/home/vagrant# vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Feb 26 2024 09:45:19)
```

**Comment by Dwordcito** [comment]
@santipadilla Could you share the syscollector inventory? This information is not crucial to be able to reproduce it and add it to our tests.

**Comment by Dwordcito** [comment]
Based on the information given, the problem is in the information collection, not in the vulnerabilities module, the issue is moved to 4.8.2 and categorized as a high-impact bug in syscollector.

openssl, it's a dpkg/apt package, but it is another version.
![image](https://github.com/wazuh/wazuh/assets/14300208/83e914c4-9240-4015-813b-8d07a9410372)

LibreOffice, not collected.
![image](https://github.com/wazuh/wazuh/assets/14300208/14fb2420-46f5-4792-b2a3-26d684a385e3)

psql, not collected
![image](https://github.com/wazuh/wazuh/assets/14300208/e2ef567a-3431-40c0-894f-81778205e497)

Node, not collected
![image](https://github.com/wazuh/wazuh/assets/14300208/b9ed3dea-0adc-47bc-9399-9f67e90a6dd5)

vim, it's a dpkg/apt package, but it is another version.
![image](https://github.com/wazuh/wazuh/assets/14300208/e49eaa61-88e8-4752-8fa2-10b5f1c69723)

**Comment by pereyra-m** [comment]
## Update

After some clarifications from @santipadilla about the tests carried out, it was determined that the missing packages by **syscollector** were installed by sources and it's expected that they aren't shown.

We can confirm this if we, for example, install **vim** by sources 

```bash
root@2023430c3aba:/home/vim73# apt list --installed | grep vim

root@2023430c3aba:/home/vim73# /usr/local/bin/vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Apr 11 2024 18:57:04)
Compiled by root@2023430c3aba
```

The **syscollector** module won't find the package if **apt** isn't aware of its existence, we can't scan the whole file-system looking for custom installations.
I'd close the issue because this is the expected behavior.
cc @sebasfalcone
