### ISSUE TITLE
[4.7.2] /app/alerting#/create-monitor : Impossible to add `Data filter`  (save button missing)

### ISSUE THREAD

**Issue by Vinalti** [wazuh/wazuh#22027]
|Wazuh version|Component|
|---|---|
| 4.7.2-docker | single-node-wazuh.manager |

## Description
I am trying to add a monitor for `data.alert.severity = 1`.
When creating the monitor (`/app/alerting#/create-monitor`) I want all documents matching the filter `data.alert.severity is 1`, nevertheles there is no button `save` so whenever I click elsewhere the filter is removed
![image](https://github.com/wazuh/wazuh/assets/22568112/ebd39ebf-2e48-4dc1-8e88-8c62e5c25b9c)
After I pressed ENTER and click elsewhere, the filter is gone:
![image](https://github.com/wazuh/wazuh/assets/22568112/fce03523-b3f5-4f25-83e5-a73e757b4134)

The options I selected previously:
- Per query monitor
- Visual Editor
- By interval: 1 minute
- Index: `wazuh-alerts-*`
- Time filed `@timestamp`
- Time range for the last : `1` `hour(s)`

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Tostti** [comment]
Hi @Vinalti, thank you for reporting this issue.
The problem comes from Opensearch Dashboard and has been already reported https://github.com/opensearch-project/alerting-dashboards-plugin/issues/558 and resolved for OSD 2.9. 

The latest version of Wazuh (4.7.2) is based on OSD 2.8, and future release 4.8.0 will be based on OSD 2.10, meaning that this issue will be resolved for that version.

I hope you find this information helpful.

Regards
