### ISSUE TITLE
Vuls.io integration. 

### ISSUE THREAD

**Issue by necrose99** [wazuh/wazuh#2205]
Might be of use .. as an optional addition. 
For the manual go build it will do nicely on even on 
IoT class devices ie Rock64/Arm64.  
And 2.5 megs scanner is quite fast. 
I have yet to build the web ui addon
Scanner already has feeds to many CVE feed repos. 
Any case might be useful on the Wazuh server. 

As the project goes even for Red or Blue Teams..
Looking like a portable vulscan.. that's fast. 
Nexpose while nice is bound to amd64.., vuls is in golang.  Validation of suricata rules etc.. 

Outputs json files as is.

**Comment by crolopez** [comment]
Hi @necrose99,

We know Vuls, it is a very good project with which we have already made an integration. You can read about this integration in an old version of [our documentation](https://documentation.wazuh.com/3.4/user-manual/capabilities/vuls.html).

However, due to the dependencies of this project, its decentralized character and other characteristics that did not fit well to Wazuh, we decided to deprecate this integration and make an own and native vulnerability detector.

Our [vulnerability detector,](https://documentation.wazuh.com/3.9/user-manual/capabilities/vulnerability-detection.html) which we are constantly improving and expanding, does not require extra dependencies and frees servers agents from processing and searching for vulnerabilities.

If you have any questions, do not hesitate to ask them.

Best regards.

**Comment by crolopez** [comment]
I'm going to close this issue. If you have more questions feel free to re-open it.

Best regards.
