### ISSUE TITLE
Develop a PoC for Integrating `journald` Logs into Logcollector

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#22056]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine| Manager | Packages/Sources | OS version |

### Description

As part of our initiative to enhance Logcollector's capabilities by integrating `journald` logs, this issue marks the first stage in our development plan. The goal is to create a Proof of Concept (PoC) that demonstrates the feasibility and effectiveness of collecting logs directly from `journald`, leveraging the `journald` API for log retrieval.

### Objectives

- **PoC Development**: Develop a Proof of Concept that can successfully retrieve logs from `journald` and process them for further analysis.
- **API Utilization**: Ensure the PoC makes efficient use of the `journald` API for log collection, avoiding reliance on external tools like `journalctl` wherever possible.
- **Log Processing**: Demonstrate basic processing of `journald` logs, including filtering based on priority, transport, and other relevant fields.

### Tasks

- [x] Research the `journald` API and identify the most efficient methods for log retrieval and processing.
- [x] Develop a small, standalone application or script that can collect logs from `journald` using the API.
- [x] Implement basic log processing features in the PoC, focusing on key `journald` fields that are most relevant to Wazuh users.
- [x] Document the development process, challenges encountered, and potential solutions for integrating `journald` log collection into Logcollector.

### Acceptance Criteria

- A functional PoC that can collect and process logs from `journald`.
- Documentation of the PoC's development process, including any limitations or challenges identified and how they were addressed or could be in future development.
- Recommendations for integrating `journald` log collection into Logcollector based on the PoC's findings.

### Additional Considerations

- **Performance**: Evaluate the performance impact of log collection via the `journald` API, aiming for minimal overhead.
- **Compatibility**: Ensure the PoC is compatible with different Linux distributions that use `systemd` and `journald`.
- **Scalability**: Consider the scalability of the solution, especially for environments with high log volumes.

**Comment by juliancnn** [comment]
**Daily Progress Update:**

- Successfully ran the PoC locally as a standalone application, enabling real-time observation of `journald` logs.
- Currently developing a feature within the PoC to fetch logs from a specified date (`only-future-event` option), aiming to seamlessly transition to real-time log collection post-initial retrieval.

Further updates on the second item's development will follow as progress is made.

**Comment by juliancnn** [comment]
**Daily Progress Update:**

- Successfully enhanced the PoC to fetch `journald` logs in real-time starting from a specific timestamp, rather than from the program's launch time.
- Conducted an analysis to decide between generating our own syslog message or sending all field information in JSON format. The analysis, available [here](https://wazuh-team.slack.com/archives/C01FB4H42DQ/p1708974798241869?thread_ts=1708733195.876809&cid=C01FB4H42DQ), suggests that JSON format offers significant advantages for the Wazuh-Engine in terms of ease of processing and decoder/rules tree establishment. However, parsing logs in Wazuh-Analyzed post-JSON decoding presents challenges due to the current decoder hierarchy limitations.
- Initiated development on log filtering capabilities to exclude unwanted logs. Encountered a limitation with PCR2 integration in the PoC, prompting a pivot to explore how these filters could be incorporated into Logcollector. The main challenges identified are:
  - Maintaining a single `journald` context to prevent log duplication.
  - Managing the connection (creation, usage, and destruction) exclusively within a single thread (`w_input_thread`) in Logcollector to ensure consistency and avoid conflicts.

Further updates will follow as we navigate these challenges and continue development.

**Comment by juliancnn** [comment]
**Daily Progress Update:**

- Conducted an in-depth review of the `systemd/sd-journal.h` library code to gain a better understanding of its filtering (matching) mechanisms. Successfully implemented these internal filters within the PoC.
- Achieved integration of `journal_log`, our custom library, into the Logcollector module. This integration is aimed at facilitating the PoC's execution within a unit test environment, specifically adapting it to support PCRE2 type regular expressions for log filtering. The integration compiles successfully, though testing is pending.

Further updates on testing and any adjustments will be provided as progress continues.

**Comment by juliancnn** [comment]
**Daily Progress Update:**

- Successfully integrated the PCRE2 filters into our PoC within the unit tests, demonstrating the feasibility of local implementation.
- Addressed and resolved several issues, including memory leaks, enhancing the stability and efficiency of our solution.
- This marks the completion of this investigative stage, setting a solid foundation for further development.

Looking forward to moving onto the next phase with these foundational elements in place.
