### ISSUE TITLE
Review API performance after switching to connexion

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#22131]
|Component|
|---|
| Wazuh component |

## Description
As part of the changes carried out in https://github.com/wazuh/wazuh/issues/20748, we need to review the API performance and compare it between 4.9.0 and this epic.
We need to compare two different aspects:
- Measure the time it takes for the API to respond to requests both before and after the transition.
- Monitor the usage of system resources like CPU and memory by the API.

We do not expect to find performance improvements since that was not the goal of this development. That will be done in a future issue. What we intend is to make sure that there has not been a worsening of performance or not a significant one.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

I performed some tests with the `vegeta` command line tool doing 50 requests per second for 30 seconds.

```console
gasti@pop-os:~/$ echo "GET https://localhost:55050/agents" | vegeta attack -insecure -header "Authorization: Bearer $TOKEN" -duration=30s -rate=50 | tee results.bin | vegeta report && vegeta report -type=json results.bin > metrics.json && cat results.bin | vegeta plot > plot.html && cat results.bin | vegeta report -type="hist[0,100ms,200ms,300ms]"
 ```

To profile the wazuh-apid CPU performance I used `cProfile` and `tuna`. I added the following lines inside `api/scripts/wazuh-apid.py`.

```py
import cProfile
import pstats

...

	with cProfile.Profile() as profile:
             ...
             start()
             ...

	results = pstats.Stats(profile)
        results.sort_stats(pstats.SortKey.TIME)
        results.print_stats()
        results.dump_stats('/cpu.prof')

```

To serve the CPU profiling use `tuna` and the `cpu.prof` file inside the artifacts below: `pip install -y tuna && tuna cpu.prof`

### 4.9.0 results

Results: [results.zip](https://github.com/wazuh/wazuh/files/14485259/results.zip)

| Total requests | Total time | Mean | 50th | 90th | 95th | 99th  | Max | Min | Rate |  Throughput |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
| 1500 | 29.992s | 12.935ms | 11.144ms | 15.258ms | 16.905ms | 35.178ms | 225.254ms | 10.079ms | 50.032 | 50.013 |

```
Requests      [total, rate, throughput]         1500, 50.03, 50.01
Duration      [total, attack, wait]             29.992s, 29.98s, 11.335ms
Latencies     [min, mean, 50, 90, 95, 99, max]  10.079ms, 12.935ms, 11.144ms, 15.258ms, 16.905ms, 35.178ms, 225.254ms
Bytes In      [total, mean]                     2260500, 1507.00
Bytes Out     [total, mean]                     0, 0.00
Success       [ratio]                           100.00%
Status Codes  [code:count]                      200:1500  
Error Set:
Bucket           #     %       Histogram
[0s,     100ms]  1492  99.47%  ##########################################################################
[100ms,  200ms]  6     0.40%   
[200ms,  300ms]  2     0.13%   
[300ms,  +Inf]   0     0.00%
```

#### Plot

![plot](https://github.com/wazuh/wazuh/assets/51374959/b8552c98-fa7d-4735-a490-d141f1bb11b7)

#### CPU profiling

![cpu_prof](https://github.com/wazuh/wazuh/assets/51374959/c15bbef8-dc65-4452-8ffc-be405602d214)

**Comment by GGP1** [comment]
## Update

I performed some tests with the `vegeta` command line tool doing 50 requests per second for 30 seconds.

```console
gasti@pop-os:~/$ echo "GET https://localhost:55050/agents" | vegeta attack -insecure -header "Authorization: Bearer $TOKEN" -duration=30s -rate=50 | tee results.bin | vegeta report && vegeta report -type=json results.bin > metrics.json && cat results.bin | vegeta plot > plot.html && cat results.bin | vegeta report -type="hist[0,100ms,200ms,300ms]"
 ```

To profile the wazuh-apid CPU performance I used `cProfile` and `tuna`. I added the following lines inside `api/scripts/wazuh-apid.py`.

```py
import cProfile
import pstats

...

	with cProfile.Profile() as profile:
             ...
             start()
             ...

	results = pstats.Stats(profile)
        results.sort_stats(pstats.SortKey.TIME)
        results.print_stats()
        results.dump_stats('/cpu.prof')

```

To serve the CPU profiling use `tuna` and the `cpu.prof` file inside the artifacts below: `pip install -y tuna && tuna cpu.prof`

### 4.9.0 results

Results: [results.zip](https://github.com/wazuh/wazuh/files/14485259/results.zip)

| Total requests | Total time | Mean | 50th | 90th | 95th | 99th  | Max | Min | Rate |  Throughput |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
| 1500 | 29.992s | 12.935ms | 11.144ms | 15.258ms | 16.905ms | 35.178ms | 225.254ms | 10.079ms | 50.032 | 50.013 |

```
Requests      [total, rate, throughput]         1500, 50.03, 50.01
Duration      [total, attack, wait]             29.992s, 29.98s, 11.335ms
Latencies     [min, mean, 50, 90, 95, 99, max]  10.079ms, 12.935ms, 11.144ms, 15.258ms, 16.905ms, 35.178ms, 225.254ms
Bytes In      [total, mean]                     2260500, 1507.00
Bytes Out     [total, mean]                     0, 0.00
Success       [ratio]                           100.00%
Status Codes  [code:count]                      200:1500  
Error Set:
Bucket           #     %       Histogram
[0s,     100ms]  1492  99.47%  ##########################################################################
[100ms,  200ms]  6     0.40%   
[200ms,  300ms]  2     0.13%   
[300ms,  +Inf]   0     0.00%
```

#### Plot

![plot](https://github.com/wazuh/wazuh/assets/51374959/b8552c98-fa7d-4735-a490-d141f1bb11b7)

#### CPU profiling

![cpu_prof](https://github.com/wazuh/wazuh/assets/51374959/c15bbef8-dc65-4452-8ffc-be405602d214)

### Connexion 3.0 results

[pending]

I'm moving the issue to on hold since the connexion tests must be performed after the first stage is finished.

**Comment by GGP1** [comment]
## Update

Previous tests were performed on the `GET /agents` endpoint which accesses the database, to complete the comparison I did some tests on the `GET /lists` endpoint.

### 4.9.0

Results: [results_lists.zip](https://github.com/wazuh/wazuh/files/14497285/lists.zip)

| Total requests | Total time | Mean | 50th | 90th | 95th | 99th  | Max | Min | Rate |  Throughput |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
| 1500 | 29.991s | 11.639ms | 11.2ms | 13.124ms | 13.852ms | 16.754ms | 57.951ms | 10.046ms | 50.03 | 50.01 |


![lists](https://github.com/wazuh/wazuh/assets/51374959/41a4c48d-1495-4b33-bbda-58e67bfdb75f)

### Connexion 3.0 results

Results: [results_lists_2.zip](https://github.com/wazuh/wazuh/files/14497031/results_lists_2.zip)

| Total requests | Total time | Mean | 50th | 90th | 95th | 99th  | Max | Min | Rate |  Throughput |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
| 1500 | 29.994s | 15.079ms | 14.386ms | 15.808ms | 16.846ms | 34.027ms | 79.412ms | 13.606ms | 50.03 | 50.01 |

![lists_2](https://github.com/wazuh/wazuh/assets/51374959/5f65915b-4381-4fe4-bbeb-407d40195026)

**Comment by GGP1** [comment]
## Conclusion

The upgrade to connexion 3.0 has meant a slight degradation in performance with a difference between 15 and 25 percent in the mean response times. The new version seems to be focused on connexion's modularity, compatibility and pluggability rather than performance. In fact, there are no performance improvements mentioned in the [3.0 release notes](https://github.com/spec-first/connexion/discussions/1775) nor in the [documentation](https://connexion.readthedocs.io/en/stable/index.html).

The difference between the two is slightly higher than I expected and I think we should dedicate some time to get them closer. Nevertheless, considering the main reason why we are moving to the new framework is to avoid several vulnerabilities in `aiohttp`, I think it is appropriate to continue with the migration.

### Summary

### GET /agents

| | 4.9.0 | Connexion 3.0 |
| -- | -- | -- |
| Min | 10.079 | 13.401 |
| Max | 225.254 | 76.559 |
| **Mean** | **12.935** | **15.111** |
| 50th | 11.144 | 14.482 |
| 90th | 15.258 | 15.779 |
| 95th | 16.905 | 16.182 |
| 99th | 35.178 | 36.744 |

15.51% mean value difference

### GET /lists

| | 4.9.0 | Connexion 3.0 |
| -- | -- | -- |
| Min | 10.046 | 13.606 |
| Max | 57.951 | 79.412 |
| **Mean** | **11.639** | **15.079** |
| 50th | 11.2 | 14.386 |
| 90th | 13.124 | 15.808 |
| 95th | 13.852 | 16.846 |
| 99th | 16.754 | 34.027 |

25.75% mean value difference

**Comment by fdalmaup** [comment]
# Review

- The analysis was carried out in great detail, following the lineups mentioned in the issue's description. 
- I agree with the given conclusion to the issue since the priority is to avoid any vulnerabilities in the used modules, nevertheless, we could consider opening a new issue to carry out a thorough investigation into what might be the cause of the degradation in performance: is it something that we could manage from our side or is it purely due to the latest `connexion` package? If it is the second option, it will surely be considered in future versions of the module.

**Comment by Selutario** [comment]
Very good analysis @GGP1. I agree with you and @fdalmaup: since the Wazuh framework has remained the same after the changes, the small loss of performance must be found either in the Connexion 3.0 framework itself, or in one or more of the [changes applied by us](https://github.com/wazuh/wazuh/compare/4.9.0...epic/20748-upgrade-to-connexion-3).

Let's open an issue (can you do it @GGP1?) to do a deeper profiling of a specific endpoint (for example `GET /manager/api/config`, which is not affected by communication with other services or by disk access). The key will be to check if there is an increase in execution time in the controller, middlewares or error handlers, which are the most significant changes compared to 4.9.0.
