### ISSUE TITLE
Multiple errors on wazuh cluster in Demo Environment for 4.8.0 Beta 2

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh#22146]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta2| cluster | Manager | Demo Environment | Amazon Linux 2 |

## Description 
During the testing [Release 4.8.0 - Beta 2 - E2E UX tests - Demo environment](https://github.com/wazuh/wazuh/issues/22111) several errors on the `wazuh-cluster` were found. The entire errors count is **10367**. These seems to be this same error repeated:

```shellsession
2024/02/26 16:51:56 ERROR: [Worker] [Main] 'Agent-info sync'
2024/02/26 16:52:02 ERROR: [Worker] [Main] 'Integrity check'
2024/02/26 16:52:02 ERROR: [Worker] [Main] Unhandled error processing request 'b'new_file'': [Errno 2] No such file or directory: '/var/ossec/queue/cluster/worker_01/worker_01-1708966322.762772-b1c11fa6a60b46d69ab83f5deb9e2f38.zip'
FileNotFoundError: [Errno 2] No such file or directory: '/var/ossec/queue/cluster/worker_01/worker_01-1708966322.762772-b1c11fa6a60b46d69ab83f5deb9e2f38.zip'
2024/02/26 16:52:02 ERROR: [Worker] [Main] Unhandled error processing request 'b'file_upd'': b'/queue/cluster/worker_01/worker_01-1708966322.762772-b1c11fa6a60b46d69ab83f5deb9e2f38.zip'
KeyError: b'/queue/cluster/worker_01/worker_01-1708966322.762772-b1c11fa6a60b46d69ab83f5deb9e2f38.zip'
2024/02/26 16:52:02 ERROR: [Worker] [Main] Unhandled error processing request 'b'file_end'': b'/queue/cluster/worker_01/worker_01-1708966322.762772-b1c11fa6a60b46d69ab83f5deb9e2f38.zip'
KeyError: b'/queue/cluster/worker_01/worker_01-1708966322.762772-b1c11fa6a60b46d69ab83f5deb9e2f38.zip'
2024/02/26 16:52:02 ERROR: [Worker] [Main] Internal error processing request 'b'syn_i_w_m_e'': Error 3027 - Unknown received task name:e3a19e8f-7abe-4495-92e6-c08fe5bc491d
```

Here is a [more complete log](https://github.com/wazuh/wazuh/files/14409377/master_env1_errors.log) 
> _Cannot capture more of the output and can't directly ssh into the demo system_

**Comment by teddytpc1** [comment]
## Update
I have made some validations:
- Cluster status:

```
./cluster_control -i
Cluster name: wazuh1

Last completed synchronization for connected nodes (1):
    worker_01 (x.x.x.x): Integrity check: 2024-02-29T12:27:01.133073Z | Integrity sync: n/a | Agents-info: 2024-02-29T12:27:06.872358Z | Agent-groups: n/a | Agent-groups full: n/a | Last keep alive: 2024-02-29T12:26:36.722301Z.
```

- Cluster nodes:

```
/cluster_control -l
NAME       TYPE    VERSION  ADDRESS
master     master  4.8.0    x.x.x.x
worker_01  worker  4.8.0    x.x.x.x
```

- Logs: the last error log was 2 days ago:
```
FileNotFoundError: [Errno 2] No such file or directory: '/var/ossec/queue/cluster/worker_01/worker_01-1709044438.339353-2b133b90409148518b7833f55c4149ba.zip'
2024/02/27 14:34:07 ERROR: [Worker] [Main] Unhandled error processing request 'b'new_file'': [Errno 2] No such file or directory: '/var/ossec/queue/cluster/worker_01/worker_01-1709044447.368678-647d6ee1380e4e6ab22d31f546383129.zip'
FileNotFoundError: [Errno 2] No such file or directory: '/var/ossec/queue/cluster/worker_01/worker_01-1709044447.368678-647d6ee1380e4e6ab22d31f546383129.zip'
```

**Comment by Selutario** [comment]
| Branch |
|--|
| [bug/22146-reproduce-cluster-error](https://github.com/wazuh/wazuh/tree/bug/22146-reproduce-cluster-error) |

## Update

I managed to reproduce the problem in the branch attached above. What that branch does is forcing a worker disconnection only once (the number of times it disconnects does not affect the result, but it makes it easier to debug if it only happens once):
https://github.com/wazuh/wazuh/blob/4d339667f79d582479b2bd51680eb07cb75a3774/framework/wazuh/core/cluster/client.py#L308

It would be necessary to see the full logs of the demo environment, from the point where the error first occurred, to confirm that the problem is the same. In any case, it seems that when the worker (client) disconnects doing a [transport.close()](https://docs.python.org/3/library/asyncio-protocol.html#asyncio.BaseTransport.close), the master (server) does not detect this disconnection:
<details>
<summary>Worker logs</summary>

```
2024/03/04 17:06:21 INFO: [Worker worker1] [Main] The master closed the connection
2024/03/04 17:06:21 INFO: [Worker worker1] [Main] All tasks closed !!
2024/03/04 17:06:21 DEBUG: [Worker worker1] [Main] Removing '/var/ossec/queue/cluster/worker1'.
2024/03/04 17:06:21 DEBUG: [Worker worker1] [Main] Removed '/var/ossec/queue/cluster/worker1'.
```

</details>

<details>
<summary>Master logs</summary>

```
2024/03/04 17:06:20 DEBUG: [Worker worker1] [Integrity check] Received file from worker: '/var/ossec/queue/cluster/worker1/worker1-1709571980.38992-ce86aa92eab141bb87d3e48c32fa1700.zip'
2024/03/04 17:06:20 INFO: [Worker worker1] [Integrity check] Finished in 0.010s. Received metadata of 35 files. Sync not required.
2024/03/04 17:06:21 DEBUG: [Worker worker1] [Main] Command received: b'syn_a_w_m_p'
2024/03/04 17:06:21 DEBUG: [Worker worker1] [Main] Command received: b'echo-c'
2024/03/04 17:06:21 DEBUG: [Worker worker1] [Main] Command received: b'new_str'
2024/03/04 17:06:23 INFO: [Worker] [Main] Connection from ('192.168.192.2', 51230)
```

</details>


Since the master did not detect the disconnection, the worker who did `transport.close()` still appears in its list of worker names. This means that, when the worker tries to connect again, this error appears in the master log:
```
2024/03/04 17:06:23 INFO: [Worker] [Main] Connection from ('192.168.192.2', 51230)
2024/03/04 17:06:23 DEBUG: [Worker] [Main] Command received: b'hello'
2024/03/04 17:06:23 ERROR: [Worker] [Main] Internal error processing request 'b'hello'': Error 3028 - Worker node ID already exists: worker1
```

Typically, when this occurs, the worker connection breaks and is retried every 10 seconds. In 4.8.0 however, the worker considers that the connection has been established correctly, and begins to perform its usual tasks:
```
2024/03/04 17:06:23 INFO: [Worker worker1] [Main] Successfully connected to master.
2024/03/04 17:06:28 INFO: [Worker worker1] [Keep Alive] Successful response from master: keepalive
2024/03/04 17:06:28 INFO: [Worker worker1] [Keep Alive] Test attempts: 0, previous disconnected: False
2024/03/04 17:06:32 DEBUG: [Worker worker1] [Integrity check] Permission to synchronize granted.
2024/03/04 17:06:32 INFO: [Worker worker1] [Integrity check] Starting.
```

If the `hello` logic does not succeed (because the name was duplicated), there are many variables left uninitialized (name, version, loggers, cluster file folder, etc):
https://github.com/wazuh/wazuh/blob/4d339667f79d582479b2bd51680eb07cb75a3774/framework/wazuh/core/cluster/master.py#L354-L405

All tasks in the cluster have a logger that is initialized in the hello method shown above. When trying to use a logger that does not exist, as seen for example in the `integrity_check` task:
https://github.com/wazuh/wazuh/blob/4d339667f79d582479b2bd51680eb07cb75a3774/framework/wazuh/core/cluster/master.py#L712-L729

It fails with a keyError as the one shown in the issue description:
```
2024/02/26 16:52:02 ERROR: [Worker] [Main] 'Integrity check'
```

Other errors also show up as a consequence of this function not being run. 

### To do
Ideally, when a worker does [transport.close()](https://docs.python.org/3/library/asyncio-protocol.html#asyncio.BaseTransport.close), the connection should break completely and be detected immediately by the master, just as it happens when the worker's `wazuh-clusterd` service is stopped or restarted. However, the reason why this does not work has already been investigated in the past without success, although we should likely reopen to the investigation:
- https://github.com/wazuh/wazuh/issues/14996

However, for the moment, the most striking behavior change has been that the worker establishes a connection despite the master responding that the name is in use. I will analyze what the reason is.
