### ISSUE TITLE
Cluster file descriptors exceeding thresholds in performance tests

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#22179]
|Wazuh version|Component|
|---|---|
| 4.8.0 | Cluster |

## Description

During https://github.com/wazuh/wazuh/issues/22126, the cluster performance test failed because some of the nodes exceeded the file descriptor mean and max thresholds.

We should investigate what is causing this unexpected behavior and apply the corresponding fix.

<details><summary>Logs </summary>

```console
(venv) gasti@pop-os:~/work/wazuh-qa$ python3 -m pytest tests/performance/test_cluster/test_cluster_performance/test_cluster_performance.py --artifacts_path='/home/gasti/Downloads/archive/artifacts' --n_workers=25 --n_agents=50000 --html=report.html --self-contained-html
================================================================== test session starts ==================================================================
platform linux -- Python 3.9.18, pytest-7.1.2, pluggy-1.4.0
rootdir: /home/gasti/work/wazuh-qa/tests, configfile: pytest.ini
plugins: metadata-3.1.1, html-3.1.1, testinfra-5.0.0
collected 1 item                                                                                                                                        

tests/performance/test_cluster/test_cluster_performance/test_cluster_performance.py F                                                             [100%]

======================================================================= FAILURES ========================================================================
_______________________________________________________________ test_cluster_performance ________________________________________________________________

artifacts_path = '/home/gasti/Downloads/archive/artifacts', n_workers = 25, n_agents = 50000

    def test_cluster_performance(artifacts_path, n_workers, n_agents):
    	...
    
        try:
>           assert not exceeded_thresholds, 'Some thresholds were exceeded:\n- ' + '\n- '.join(
                '{stat} {column} {value} >= {threshold} ({node}, {file}, {phase})'.format(**item) for item in
                exceeded_thresholds)
E               AssertionError: Some thresholds were exceeded:
E                 - mean FD 73.23255813953489 >= 70 (worker_2, wazuh-clusterd, setup_phase)
E                 - max FD 76.0 >= 72.6 (worker_25, wazuh-clusterd, setup_phase)
E                 - mean FD 130.6030534351145 >= 103.4 (master, wazuh-clusterd, setup_phase)
E                 - max FD 161.0 >= 160 (master, wazuh-clusterd, setup_phase)
E                 - mean FD 73.0 >= 72 (worker_25, wazuh-clusterd, stable_phase)
E                 - max FD 73.0 >= 72.6 (worker_17, wazuh-clusterd, stable_phase)
E                 - mean FD 133.0 >= 59 (master, wazuh-clusterd, stable_phase)
E                 - max FD 133.0 >= 70.5 (master, wazuh-clusterd, stable_phase)
E               assert not [{'column': 'FD', 'file': 'wazuh-clusterd', 'node': 'worker_2', 'phase': 'setup_phase', ...}, {'column': 'FD', 'file':...table_phase', ...}, {'column': 'FD', 'file': 'wazuh-clusterd', 'node': 'worker_17', 'phase': 'stable_phase', ...}, ...]

tests/performance/test_cluster/test_cluster_performance/test_cluster_performance.py:85: AssertionError
================================================================ short test summary info ================================================================
FAILED tests/performance/test_cluster/test_cluster_performance/test_cluster_performance.py::test_cluster_performance - AssertionError: Some thresholds...
============================================================= 1 failed, 1 warning in 0.61s ==============================================================
```

</details>

Artifacts: [artifacts.zip](https://github.com/wazuh/wazuh/files/14419772/artifacts.zip)
Report: [report.zip](https://github.com/wazuh/wazuh/files/14419697/report.zip)

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by fdalmaup** [comment]
# Issue Update

**- Analysis of the attached artifacts and the module in charge of calculating the statistics from these**
The values to compare with the established thresholds (defined in `wazuh-qa/tests/performance/test_cluster/test_cluster_performance/data/25w_50000a_thresholds.yaml`) are the result of adding the statistics from the three cluster processes (`wazuh_clusterd`, `wazuh_clusterd_1`, `wazuh_clusterd_2`)  with the `ClusterCSVParser._add_child_process_to_parent_process` method found in `wazuh-qa/deps/wazuh_testing/wazuh_testing/tools/performance/csv_parser.py` last modified two years ago.

**Comment by fdalmaup** [comment]
# Issue Update
The statistics obtained from the Workload pipeline executioned were originally designed to have two differentiated stages: `setup` and `stable` which are determined with the start and end of the `integrity_sync` and `integrity_check` processes. Due to the simoultaneous execution of the API Performance tests in the pipeline, which involve continous restarts in the manager, the limits of the mentioned stages are affected and thus the tasks and resources values to be obtained from each one.

Another point to be addresed is that using the artifacts attached in the issue where the actual threshold values were stablished gives a successful result when executing the tests. Nevertheless, when using [the artifacts from the tests for `v4.3.0-rc3`](https://github.com/wazuh/wazuh/issues/11859#issuecomment-1020034737), the performance test fails:
```
 E               AssertionError: Some thresholds were exceeded:
E                 - reg_cof USS(KB) 1303.2432597193467 >= 332.64 (master, wazuh-clusterd, setup_phase)
E                 - mean CPU(%) 9.495333333333333 >= 9.35 (worker_15, wazuh-clusterd, setup_phase)
E                 - mean CPU(%) 84.17142857142856 >= 79.42 (master, wazuh-clusterd, setup_phase)
E                 - reg_cof CPU(%) 0.5302452841039799 >= 0.12 (master, wazuh-clusterd, setup_phase)
E                 - reg_cof FD 0.06226161164482535 >= 0.02 (worker_22, wazuh-clusterd, setup_phase)
E                 - mean FD 110.26708074534162 >= 103.4 (master, wazuh-clusterd, setup_phase)
E                 - mean CPU(%) 53.3734756097561 >= 53 (master, wazuh-clusterd, stable_phase)
E                 - mean FD 69.71341463414635 >= 59 (master, wazuh-clusterd, stable_phase)
E                 - max FD 121 >= 70.5 (master, wazuh-clusterd, stable_phase)
E               assert not [{'column': 'USS(KB)', 'file': 'wazuh-clusterd', 'node': 'master', 'phase': 'setup_phase', ...}, {'column': 'CPU(%)', ...': 'setup_phase', ...}, {'column': 'FD', 'file': 'wazuh-clusterd', 'node': 'master', 'phase': 'setup_phase', ...}, ...]

wazuh-qa/tests/performance/test_cluster/test_cluster_performance/test_cluster_performance.py:85: AssertionError
```
After analyzing the processing of the `binaries` files, it was found that the calculated values ​obtained do not correspond to the sum of the resources of the three cluster processes of the master node:
```
mean ('master', 52.33198380566802)
max ('master', 62)
```

An issue will be opened to analyze the behavior of the used methods in `wazuh-qa/deps/wazuh_testing/wazuh_testing/tools/performance/csv_parser.py` since there could be an edge case not being contemplated that triggers the miscalcultation.

## Resources statistics from previous versions testing

Took the artifacts of versions [`4.7.3`](https://github.com/wazuh/wazuh/issues/22023) and [`4.8.0`](https://github.com/wazuh/wazuh/issues/22126#issuecomment-1965093634) release candidates testing to determine new thresholds values.



<details><summary>4.8.0</summary>

- Setup phase
<table class="default"> 
  <tr>
    <th colspan="3"></th>
    <td style="text-align:center"><b>Real value</b></td>
  </tr>
  <tr>
    <th rowspan="6">USS(KB)</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td>51417.614</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>81460</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>197.974</td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td>51988.342</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>89600</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>102.179</td>
  </tr>
<tr>
    <th rowspan="6">CPU(%)</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td>1.361</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>4.6</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>-0.00419</td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td>33.558</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>159.2</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>-0.169</td>
  </tr>
<tr>
    <th rowspan="6">FD</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td>72.2436</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>76</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>0.0031</td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td>129.9925</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>159</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>-0.021</td>
  </tr>
</table>

- Stable phase

<table class="default"> 
  <tr>
    <th colspan="3"></th>
    <td><b>Real value</b></td>
  </tr>
  <tr>
    <th rowspan="6">USS(KB)</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td>30825.76</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>35064.0</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>579.6092</td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td>74189</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>88036</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>253.3252</td>
  </tr>
<tr>
    <th rowspan="6">CPU(%)</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td>0.56</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>2.2</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>0.0115</td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td>7.4916</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>20.4</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>-0.0995</td>
  </tr>
<tr>
    <th rowspan="6">FD</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td>72.68</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>75</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>0.8728</td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td>135.125</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>138</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>-0.076</td>
  </tr>
</table>

</details>

<details><summary>4.7.3-rc1</summary>

- Setup phase
<table class="default"> 
  <tr>
    <th colspan="3"></th>
    <td style="text-align:center"><b>Real value</b></td>
  </tr>
  <tr>
    <th rowspan="6">USS(KB)</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td>66134.164</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>84572</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>118.61</td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td>50613.982</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>76240</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>107.47</td>
  </tr>
<tr>
    <th rowspan="6">CPU(%)</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td>1.6155</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>10.2</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>-0.008</td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td>37.395</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>140.8</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>-0.182</td>
  </tr>
<tr>
    <th rowspan="6">FD</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td>74.5</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>76</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>0.013</td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td>133.10</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>161</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>-0.003</td>
  </tr>
</table>

- Stable phase

<table class="default"> 
  <tr>
    <th colspan="3"></th>
    <td><b>Real value</b></td>
  </tr>
  <tr>
    <th rowspan="6">USS(KB)</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td>79203.884</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>83228</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>607.414</td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td>98324.222</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>102912</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>188.282</td>
  </tr>
<tr>
    <th rowspan="6">CPU(%)</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td>0.467</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>15</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>0.00096</td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td>2.1638</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>34.4</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>-0.0746</td>
  </tr>
<tr>
    <th rowspan="6">FD</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td>76.028</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>77</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>0.5849</td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td>132.194</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td>136</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td>0.2557</td>
  </tr>
</table>

</details>

**Comment by nico-stefani** [comment]
During #23268 we detected new thresholds exceeded. 

![image](https://github.com/wazuh/wazuh/assets/7127104/d12fa2da-a98a-488b-a9f7-4e8976672bb1)

**Comment by Selutario** [comment]
In this case, the reason is not that the test is too strict, but rather that the tasks really took too long to complete. We will need to investigate why it happened, but the test should not be updated this time.
