### ISSUE TITLE
Decrease in Decoded_events, EDPS on 4.8.0 Beta 2

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh#22191]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta2 | Wazuh Manager | Manager | Packages | CentOS |

## Description

During the analysis [Release 4.8.0 - Beta 2 - Footprint Metrics - ALL (2.5d)](https://github.com/wazuh/wazuh/issues/22164) we detected a decrease in logcollector on `decoded_events` and EDPS compared to [4.7.2](https://github.com/wazuh/wazuh/issues/21280).

- Decoded_events (decrease mainly in logcollector events)
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  | ![image](https://github.com/wazuh/wazuh/assets/44633633/85d4ab4b-3eae-4269-a748-f08accecb0e3) |![image](https://github.com/wazuh/wazuh/assets/44633633/2dd5cbe9-5915-4b66-ad1a-51178a9d5501) |

- EPS (decrease in logcollector, increase in sca)
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  | ![image](https://github.com/wazuh/wazuh/assets/44633633/d75d4a8f-f18c-4852-99b2-b712baa33f64) | ![image](https://github.com/wazuh/wazuh/assets/44633633/e7a21454-9f1e-4376-a580-b40701785a72) |

**Comment by QU3B1M** [comment]
The same happens for the agents


- `AgentD_Number_of_events_buffered`
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  | ![image](https://github.com/wazuh/wazuh/assets/44633633/cbc41028-3749-4726-b037-e54bde22faf9)|![image](https://github.com/wazuh/wazuh/assets/44633633/4c881f97-2baf-486d-884c-cbe765717a64) |

**Comment by QU3B1M** [comment]
Something similar is detected in [Release 4.8.0 - Beta 2 - Footprint Metrics - VULNERABILITY-DETECTOR-REGISTER (2.5d)](https://github.com/wazuh/wazuh/issues/22165)


- `Decoded_events` (Major decrease in all modules)
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  | ![image](https://github.com/wazuh/wazuh/assets/44633633/19b34120-6e8d-4be4-bdd7-846e0fbaad71)|![image](https://github.com/wazuh/wazuh/assets/44633633/951e2dd6-346b-4533-965b-792816cef4f8)|



- `EDPS` (Pattern changed)
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  | ![image](https://github.com/wazuh/wazuh/assets/44633633/07d6aec8-17f5-4158-a2e5-d2fc6032becb)|![image](https://github.com/wazuh/wazuh/assets/44633633/7d3a6f85-b403-4f5d-b535-75c1f8aae5ee) |



- `Number_Events` (Major decrease)
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  | ![image](https://github.com/wazuh/wazuh/assets/44633633/f1686874-9b21-420b-b20a-5c8799fb8aef)|![image](https://github.com/wazuh/wazuh/assets/44633633/f30efb09-1412-4078-b78c-e1439b306270) |

**Comment by QU3B1M** [comment]
Also related to the issue [Release 4.8.0 - Beta 2 - Footprint Metrics - VULNERABILITY-DETECTOR-REGISTER (2.5d)](https://github.com/wazuh/wazuh/issues/22165). The agents seems to have a fluctuations increase in the events related plots


- `AgentD_Number_of_events_buffered` 
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  |![image](https://github.com/wazuh/wazuh/assets/44633633/fa31c012-afbe-4aad-b583-61411979640f)|![image](https://github.com/wazuh/wazuh/assets/44633633/0026a3ad-c6a6-441f-85c8-0d840db5d343)|



- `AgentD_Number_of_generated_events`
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  |![image](https://github.com/wazuh/wazuh/assets/44633633/2ba7a49e-0b65-4f31-a853-8464c6923d62)|![image](https://github.com/wazuh/wazuh/assets/44633633/483e3e9b-a2e0-4b91-8901-2030cff15161)|



- `AgentD_Number_of_messages` (Major decrease)
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  |![image](https://github.com/wazuh/wazuh/assets/44633633/4f61d503-6909-49b6-9c86-e54da8b4452b)|![image](https://github.com/wazuh/wazuh/assets/44633633/1bc0295b-60ac-4698-9eb5-5a679758260a)|

**Comment by LucioDonda** [comment]
Based on the plot analysis and the csv, and as said in the comments above the base cause is the agent's events:
![image](https://github.com/wazuh/wazuh/assets/95248059/a8fe89f0-63c0-44d5-8f84-14896ff4976d)

This comparison was made between **4.8.0 Beta2** vs **4.8.0 Alpha2**. Those are the nearest versions that shows a jump in the events.

* That can be caused by flooding on the agent's buffer. 
```
~/Doc/T/D/A/ossec_Test_stress_B4780_centos_2024-01-17  cat var/ossec/logs/ossec.log | grep "Agent buffer is full" | wc -l 
1100
~/Doc/T/D/A/ossec_Test_stress_B4780_centos_2024-01-17  cat var/ossec/logs/wazuh/2024/Jan/ossec-*.log | grep "Agent buffer is full" | wc -l
3450
```
* comparing centos agent in the 2 versions. 
**4550 lines of agent flooding are printed**
The same analysis on the newer version throws **313189 messages printed**

What is particularly strange is that the first message in the most flooded execution is printed just a a minute after the agent starts:

``` log
2024/02/24 20:59:06 wazuh-execd: INFO: Started (pid: 14466).
2024/02/24 20:59:07 wazuh-agentd: INFO: (1410): Reading authentication keys file.
2024/02/24 20:59:07 wazuh-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
...
2024/02/24 20:59:59 wazuh-agentd: INFO: Server responded. Releasing lock.
2024/02/24 20:59:59 wazuh-modulesd: INFO: Agent is now online. Process unlocked, continuing...
...
2024/02/24 21:00:04 wazuh-agentd: WARNING: Agent buffer is full: Events may be lost.
```

Either way I'm still checking for [changes ](https://github.com/wazuh/wazuh/compare/v4.8.0-beta1...v4.8.0-beta2)that could have impact in this behaviour.

**Comment by LucioDonda** [comment]
Checking the configurations on both versions, it can be seen that the agent buffer full at the beginning is due to the client's buffer size change:
![image](https://github.com/wazuh/wazuh/assets/95248059/5ce29f88-ccba-491d-973f-011aa74e9432)
4.7.2's size is the same as in Alpha 2.

Conclusions:

Adjusting `queue_size` **1/500** times and `events_per_second` y **1/5** will have a significant impact on the decoded events and EPS, making comparisons between them less meaningful.
To prevent additional inquiries, it is necessary to identify the causes of the change and, in certain situations, provide notice prior to implementation.
c.c. @cborla @vikman90
