### ISSUE TITLE
Windows Server Compatibility Agent Side

### ISSUE THREAD

**Issue by Sascories** [wazuh/wazuh#22319]
Hello, I'd like to ask about the compatibility vulnerability scanning of wazuh for Windows Server. I've installed and tested on Windows Server 2019, 2012 R2, 2008, 2008 R2. 

All of the above are working fine but I can't seem to do vulnerability scan on Windows Server 2003. Is it not supported? I can't find any documentation regarding the agent compatibility.

**Comment by vikman90** [comment]
@Sascories Windows Server 2003 is indeed supported by Wazuh ([Compatibility Matrix](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/how-it-works.html#compatibility-matrix)). However, due to its end-of-life status since 2015, there might not be many vulnerabilities reported for it.

Wazuh's Vulnerability Detector functions by comparing the agent's operating system version and installed packages with a list of Common Vulnerabilities and Exposures (CVEs). It only displays vulnerabilities for which a patch (hotfix) has been published but not installed. If a CVE does not have a corresponding hotfix available, it won't be shown in the scan results.

For the detection process, Wazuh relies on official sources such as the [Catalog](https://www.catalog.update.microsoft.com/Home.aspx) for hotfixes and [MSRC (Microsoft Security Response Center)](https://msrc.microsoft.com/update-guide/vulnerability) for vulnerabilities.

Hope that helps.

Best regards.
