### ISSUE TITLE
Duplicate Agent 

### ISSUE THREAD

**Issue by taylorwalton** [wazuh/wazuh#22395]
hey everyone! Hoping someone here can help with me an issue regarding duplicate agent....I've noticed that when agents go offline (due to machine powering off) or when an agent is restarted, I am often running into an issue where it appears the agent attempts to re register with the manager (even though it already has a client key), and the manager rejects it stating that duplicate agent name already exists.
Im curious as to why the agent feels the need to re register even when it has a client key. I have also applied to the below auth settings with the force but is not resulting in the manager allowing the duplicate agent name to re register.

```
<auth>
    <disabled>no</disabled>
    <port>1515</port>
    <use_source_ip>no</use_source_ip>
    <purge>yes</purge>
    <use_password>yes</use_password>
    <force>
      <enabled>yes</enabled>
      <disconnected_time enabled="no">0</disconnected_time>
      <after_registration_time>0</after_registration_time>
      <key_mismatch>yes</key_mismatch>
    </force>
    <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
    <!-- <ssl_agent_ca></ssl_agent_ca> -->
    <ssl_verify_host>no</ssl_verify_host>
    <ssl_manager_cert>etc/sslmanager.cert</ssl_manager_cert>
    <ssl_manager_key>etc/sslmanager.key</ssl_manager_key>
    <ssl_auto_negotiate>no</ssl_auto_negotiate>
  </auth>
  ```
  
 utimately id desire for the agent to just reconnecnt without feeling the need to re register with the manager. has anyone else noticed this issue? am i missing something simple? I am running 4.7.2 btw...thanks for any help in advance :slightly_smiling_face:
I know i could solve with removing the agent from the manager but id like to avoid getting a new agent id if possible

I set the below in the ossec.conf of the agent as a temporary workaround, but I believe this need a more permanent approach.
```
<enrollment>
    <enabled>no</enabled>
```

Thanks for the help!

**Comment by thejbte** [comment]
@taylorwalton It should be noted that problems with agent re-registration are usually caused by:
- has agents with duplicate names.
- the environment is functioning poorly, possibly saturated.

It is advisable to update to the new version 4.7.3 where we fix the performance of the manager which makes it work faster and lose fewer agent connections. Please update and let us know if the issue is resolved or not.

**Comment by taylorwalton** [comment]
hey @thejbte thanks for the response. My main concern is way does the agent try to re register with the manager even though it already has a client key?

Sometimes when the agent lose connection to the manager (I.E adding a new rule and forcing a restart of the manager service), it attempts to re register with the manager rather than just re connecting

**Comment by thejbte** [comment]
@taylorwalton If the environment is saturated, the connection attempt messages sent by the agent may not be processed by the manager and, after 5 failed attempts (by default), it tries to register again. This is the default and expected behavior.

**Comment by taylorwalton** [comment]
hey @thejbte Im seeing this even when the environment is not saturated (i.e only one agent connected).

Regardless, why is a re registration attempted because the agent temporarily cannot establish a connection result in a re register attempt even though the agent already has a client key? In my opinion it would make more sense to just to continue to attempt to establish a connection rather than going through the registration process again. But curious to hear your thoughts.

Thanks!

**Comment by thejbte** [comment]
This is the behavior, if you try to connect 5 times and the manager does not respond then the agent tries to register again. This is because it may happen that your password is no longer valid (for example), so if you keep trying to connect again you will never get out of that loop.

However, you can regulate the number of connection attempts (which by default is 5) with this setting: [max -retries](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#max-retries)
