### ISSUE TITLE
Feature Request: Alpine Linux Vulnerability Detection official support

### ISSUE THREAD

**Issue by mintyhippoxyz** [wazuh/wazuh#22426]
Ref: https://github.com/wazuh/wazuh/issues/19416#issuecomment-1758162262

I'd like to suggest official support for Alpine Linux Vulnerability Detection.

Wazuh already has support for agents on Alpine so this seems like a logical next step to feature completeness for that OS.

After a week of research into vulnerability scanning tools, I think this would put Wazuh even further ahead of the pack. There are some options out there for scanning Alpine containers but those of us using Alpine beyond containers seem to be lacking a good vulnerability scanning solution.

**Comment by davidcr01** [comment]
Hello.

This is the list of information providers that we use to generate the VD content
OSs that don't have an official provider could:
- Relay on another provider feed (for example, centOS uses RedHat feed)
- Use the NVD as a fallback (this is the case for Alpline Linux)

![image](https://github.com/wazuh/community/assets/72193239/ff331307-65bb-4c69-98c7-53fd11b96db0)


It is supported but given that the information is not 100% tied to the OS itself there is the possibility of having false positives (sometimes OSs fix vulnerabilities for themselves, and this is not reported on the NVD).
So, we can not "official support" for Alpine Linux because there is no official cloud provider, but we can support it with the NVD feed.

**Comment by staticfrost** [comment]
how do we get the NVD feed support for Alpine enabled?

**Comment by davidcr01** [comment]
Hello.

To perform a Vulnerability detection scan to a non-supported OS, we have the related documentation that explains this: https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/allow-os.html.

Related documentation to configure VD: https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/configuring-scans.html

**Comment by mintyhippoxyz** [comment]
The NVD feed works but its rather sub-par in comparison to Trivy for example which uses that feed.

Alpine does have their own feed/database that could potentially be utilized. https://secdb.alpinelinux.org/

My company does have an open source donations budget, it wouldn't be much but would a little financial incentive help bring this forward?
