### ISSUE TITLE
Fix error in API tier 0 & 1 bruteforce tests

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#22434]
|Component|
|---|
| Wazuh API IT |

## Description
The [test_bruteforce_blocking_system](https://github.com/wazuh/wazuh/blob/master/tests/integration/test_api/test_config/test_bruteforce_blocking_system/test_bruteforce_blocking_system.py) has failed a couple of times at least in the last few weeks. The error doesn't always occur, with what seems like a race condition:
```
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.4.0
rootdir: /home/runner/work/wazuh/wazuh/tests/integration, configfile: pytest.ini
plugins: metadata-3.1.1, html-3.1.1
collected 69 items / 3 deselected / 66 selected

test_api/test_config/test_DOS_blocking_system/test_DOS_blocking_system.py . [  1%]
                                                                         [  1%]
test_api/test_config/test_bruteforce_blocking_system/test_bruteforce_blocking_system.py F [  3%]
                                                                         [  3%]
test_api/test_config/test_cache/test_cache.py ..                         [  6%]
test_api/test_config/test_cors/test_cors.py x.                           [  9%]
test_api/test_config/test_drop_privileges/test_drop_privileges.py ..     [ 12%]
test_api/test_config/test_experimental_features/test_experimental_features.py . [ 13%]
.                                                                        [ 15%]
test_api/test_config/test_host_port/test_host_port.py ....               [ 21%]
test_api/test_config/test_https/test_https.py ..                         [ 24%]
test_api/test_config/test_jwt_token_exp_timeout/test_jwt_token_exp_timeout.py . [ 25%]
.                                                                        [ 27%]
test_api/test_config/test_limit_eps/test_limit_eps.py ......             [ 36%]
test_api/test_config/test_logs/test_logs_format.py ........              [ 48%]
test_api/test_config/test_rbac/test_rbac_mode.py ..                      [ 51%]
test_api/test_config/test_request_timeout/test_request_timeout.py .      [ 53%]
test_api/test_config/test_upload_configuration/test_upload_configuration.py . [ 54%]
.                                                                        [ 56%]
test_api/test_middlewares/test_response_postprocessing.py ....           [ 62%]
test_api/test_middlewares/test_set_secure_headers.py .                   [ 63%]
test_api/test_rbac/test_add_old_resource.py ....                         [ 69%]
test_api/test_rbac/test_manage_admin_resource.py .......                 [ 80%]
test_api/test_rbac/test_policy_position.py .                             [ 81%]
test_api/test_rbac/test_remove_resource.py ....                          [ 87%]
test_api/test_rbac/test_remove_resources_relation.py ...                 [ 92%]
test_api/test_statistics/test_statistics_format.py .....                 [100%]

=================================== FAILURES ===================================
``` 

A connection refused is returned when it fails:
```
>           raise ConnectionError(e, request=request)
E           requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=55000): Max retries exceeded with url: /security/user/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe03ad993f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Here is the full log: [bruteforce_error.log](https://github.com/wazuh/wazuh/files/14557519/bruteforce_error.log)

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Executed the workflow 10 times to try and reproduce the error:

1. https://github.com/wazuh/wazuh/actions/runs/9176367665
2. https://github.com/wazuh/wazuh/actions/runs/9176369209
3. https://github.com/wazuh/wazuh/actions/runs/9176371276
4. https://github.com/wazuh/wazuh/actions/runs/9176373406
5. https://github.com/wazuh/wazuh/actions/runs/9176376513
6. https://github.com/wazuh/wazuh/actions/runs/9176995949
7. https://github.com/wazuh/wazuh/actions/runs/9176998256
8. https://github.com/wazuh/wazuh/actions/runs/9176999285
9. https://github.com/wazuh/wazuh/actions/runs/9177000644
10. https://github.com/wazuh/wazuh/actions/runs/9177002363

**Comment by GGP1** [comment]
Only two of the ten tests failed, and interestingly they were the two that took longer to complete. The remaining run was successful but kept running indefenitely

![runs](https://github.com/wazuh/wazuh/assets/51374959/d00125ae-e5a4-4d25-93ef-5e4222081551)

**Comment by GGP1** [comment]
## Update

Executed the workflow 10 times using the branch `4.9.0` to try and reproduce the error:

1. https://github.com/wazuh/wazuh/actions/runs/9176367665
2. https://github.com/wazuh/wazuh/actions/runs/9176369209
3. https://github.com/wazuh/wazuh/actions/runs/9176371276
4. https://github.com/wazuh/wazuh/actions/runs/9176373406
5. https://github.com/wazuh/wazuh/actions/runs/9176376513
6. https://github.com/wazuh/wazuh/actions/runs/9176995949
7. https://github.com/wazuh/wazuh/actions/runs/9176998256
8. https://github.com/wazuh/wazuh/actions/runs/9176999285
9. https://github.com/wazuh/wazuh/actions/runs/9177000644
10. https://github.com/wazuh/wazuh/actions/runs/9177002363

Only two of the ten tests failed, and they were the two that took longer to complete. The remaining run was successful but kept running indefinitely.

![runs](https://github.com/wazuh/wazuh/assets/51374959/d00125ae-e5a4-4d25-93ef-5e4222081551)

If we take a look at the code that appears in the error trace, we can observe that the failure is caused by the server failing to respond to the request in time and the maximum amount of retries being exceeded.

https://github.com/psf/requests/blob/v2.32.1/src/requests/adapters.py#L512-L616

This is partly because in this test we are not retrying the requests (I think because it caused issues before the refactor to the framework `login()` function), this has been corrected to make sure to try again up to three times before exiting with an error.

Furthermore, I have decreased the maximum login attempts from the test case from 10 to 3, so we have fewer requests that could fail.

After the modifications, I executed the test ten more times

1. https://github.com/wazuh/wazuh/actions/runs/9177858127
2. https://github.com/wazuh/wazuh/actions/runs/9177862234
3. https://github.com/wazuh/wazuh/actions/runs/9177862234
4. https://github.com/wazuh/wazuh/actions/runs/9177863871
5. https://github.com/wazuh/wazuh/actions/runs/9177865388
6. https://github.com/wazuh/wazuh/actions/runs/9177865388
7. https://github.com/wazuh/wazuh/actions/runs/9177894192
8. https://github.com/wazuh/wazuh/actions/runs/9177895754
9. https://github.com/wazuh/wazuh/actions/runs/9177897115
10. https://github.com/wazuh/wazuh/actions/runs/9177898760

And all the executions passed

![runs](https://github.com/wazuh/wazuh/assets/51374959/d990580a-2ca8-42b5-b8e9-945f8b293d68)

> There is [one](https://github.com/wazuh/wazuh/actions/runs/9177892713) that appears as running but if we access it we can see that it finished successfully.
