### ISSUE TITLE
Investigate about different package managers

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#22520]
### Description

Related to https://github.com/wazuh/wazuh/issues/21152.

The aim of this issue is to investigate and test the different package managers features:

- Downgrade of packages.
- Pre and post install scripts.
- Rollbacks.

We need to include in this investigation the following OSs:

- Linux: RPM and DEB.
- MacOS: PKG.
- Windows: MSI.

**Comment by jr0me** [comment]
# Conclusion

The current approach to remote upgrades involves installing Wazuh from sources, which overwrites an existing installation and leads to discrepancies if the original was installed using a package manager.

To achieve this, the WPK features a script that backs up the current version before upgrading. This script also ensures that the new version connects to the Wazuh manager; if the upgrade fails, it reverts to the previous version by restoring the backup.

The script, not utilizing package management, replicates certain package logic, particularly in creating or altering file ownership, reinstating the SELinux policy, and managing the agent service's stoppage and restart.

## Automatic rollbacks

Although package systems such as RPM, DEB, and PKG allow for the inclusion of arbitrary shell scripts during the installation and uninstallation processes, adhering to standard package management practices and guidelines is strongly recommended. Consequently, it is advised not to attempt rolling back an installed or upgraded package to its previous version based solely on post-installation performance outcomes, such as the ability to connect to the Wazuh manager.

## Possible WPK improvements

### RPM, DEB

By utilizing standard package management features, it's possible to simplify the WPK upgrade script significantly for RPM and DEB packages, retaining only the functionality to verify the agent's connection to the manager after an upgrade and the rollback in case of error. The streamlined process would involve:

1. Initiate the upgrade using package management `(e.g., rpm -Uvh wazuh-agent-4.7.2-x86_64.rpm)`. If this step fails, proceeds to step 3.
1. Test the agent's connection. If successful, the process concludes.
1. If necessary, revert to the previous version using package management `(e.g., rpm -Uvh --oldpackage wazuh-agent-4.0.4-x86_64.rpm)`.

Note: It is not possible to achieve this with PKG packages on OSX since they don't have run uninstall scripts when the package is being upgraded or downgraded.

### MSI

Our MSI relies heavily on many `CustomActions` which require their own specific `RollbackCustomActions` to be able to perform automatic rollbacks. Since no such rollback actions are currently in place, we should first implement these, and then assess if WPK improvements can be made.

* [Windows Installer Best Practices](https://learn.microsoft.com/en-us/windows/win32/msi/windows-installer-best-practices)
* [Using Custom Actions](https://learn.microsoft.com/en-us/windows/win32/msi/using-custom-actions)
* [Rollback Custom Actions](https://learn.microsoft.com/en-us/windows/win32/msi/rollback-custom-actions)
* [Installation Phases and In-Script Execution Options for Custom Actions in Windows Installer
](http://www.installsite.org/pages/en/isnews/200108/)


### PKG

As there are no [pre|post][uninstall|upgrade] scripts in PKG packages, we cannot downgrade installations by means of a package install. Moreover, a recommended best practice is to include an uninstall script, which we currently do not provide. A necessary first step would be to provide such uninstall script, and let the WPK levarage it if necessary.

* [Managed Installs](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/SoftwareDistribution4/Managed_Installs/Managed_Installs.html)
* [macOS Application Packaging Best Practices](https://developer.jamf.com/developer-guide/docs/macos-application-packaging-best-practices)
* [The Commandments of Packaging in OSX](https://www.afp548.com/2010/06/03/the-commandments-of-packaging-in-os-x/)
* [Packaging guidelines for MacOs](https://themacwrangler.wordpress.com/2017/04/28/packaging-guidelines-for-mac-os/)
