### ISSUE TITLE
Inconsistent Vulnerability reports for agents registered during feed processing

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#22584]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta4 | Vulnerability Detection | Manager | Packages |Any |

### Description

During the [Vulnerability Detector comparison test extension](https://github.com/wazuh/wazuh-qa/issues/5113), it was observed that agents registered during feed processing fail to generate expected vulnerabilities in the environment. Additionally, the manager reports significantly fewer vulnerabilities than anticipated (probably due to the same issue), impacting the overall reliability of vulnerability assessments.

### Steps to reproduce

-  Deploy an All-In-One (AIO) environment with default configuration.
 - Start the environment.
 - Immediately after the start, register an agent in the environment.
 - Wait until feeds are processed, then register a new agent (identical to the first one).
 - Compare the vulnerability reports between the new and old agent to observe any differences.
 - Additionally, verify that the manager's vulnerability report is either empty or contains significantly fewer vulnerabilities than expected.

### Evidences

- Logs: [oracle_logs.zip](https://github.com/wazuh/wazuh/files/14638947/oracle_logs.zip)
- Configuration: [oracle_conf.zip](https://github.com/wazuh/wazuh/files/14638946/oracle_conf.zip)
- Syscollector packages: [packages.csv](https://github.com/wazuh/wazuh/files/14639100/packages.csv)
- Syscollector Report: [wazuh-agent-inventory-001-1710777515.zip](https://github.com/wazuh/wazuh/files/14639099/wazuh-agent-inventory-001-1710777515.zip)
- Vulnerabilities: [vulnerabilities_inventory-2024-03-18T15 54 55.263Z.csv](https://github.com/wazuh/wazuh/files/14639094/vulnerabilities_inventory-2024-03-18T15.54.55.263Z.csv)

#### Screenshot

![oraclelinux1](https://github.com/wazuh/wazuh/assets/11089305/08b5742a-9c05-43c9-ad7f-630267073bf9)

> [!NOTE]
> oraclelinux1 is the manager and it is the same AMI as oraclelinux2. It was expected to have at least the same vulnerabilities than oraclelinux2

**Comment by MARCOSD4** [comment]
Something similar has also happened to me during the testing in https://github.com/wazuh/wazuh-qa/issues/5113, in this case, with a Ubuntu Jammy manager and with a single RHEL 9 agent. In my case, it seems that the agent restarts due to a change in the configuration once the manager has already started processing the feed. The result is that only one vulnerability is detected. After performing the test avoiding this problem, the number of vulnerabilities obtained is 615, so the difference is quite significant.

### Evidences

First case with one vulnerability detected:

Logs: [manager_ossec.log](https://github.com/wazuh/wazuh/files/14639924/ossec.log)
  [agent_ossec.log](https://github.com/wazuh/wazuh/files/14639928/agent_ossec.log)
Vulnerabilities: [vulnerabilities_inventory-2024-03-18T12_30_20.168Z.csv](https://github.com/wazuh/wazuh/files/14639938/vulnerabilities_inventory-2024-03-18T12_30_20.168Z.csv)


Second case with 615 vulnerabilities detected:

Logs: [manager_ossec_log.zip](https://github.com/wazuh/wazuh/files/14639977/manager_ossec_log.zip)
[ossec_agent.log](https://github.com/wazuh/wazuh/files/14639999/ossec_agent.log)
Vulnerabilities: [vulnerabilities_inventory-2024-03-18T16_16_06.178Z.csv](https://github.com/wazuh/wazuh/files/14639989/vulnerabilities_inventory-2024-03-18T16_16_06.178Z.csv)

**Comment by sebasfalcone** [comment]
This will be solved after implementing:
- https://github.com/wazuh/wazuh/pull/22693

https://github.com/wazuh/wazuh/blob/7321fb44055805de60e6eb76ffffabf0ca6bfeb8/src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/databaseFeedManager.hpp#L111-L112
