### ISSUE TITLE
Scanning Unsupported Systems: Doesn't Scan Fedora 39

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#22589]
| Wazuh Version | Component | Install Type | Install Method | Platform |
|---|---|---|---|---|
| 4.7.3-rc2 | Vulnerability Detection | Manager | Packages (AIO) | Ubuntu 22 |

## Description

During the issue [Vulnerability Detector comparison test extension](https://github.com/wazuh/wazuh-qa/issues/5113) we were able to verify that vulnerability scanning in `Fedora 39` is not working. However, this occurs only for `4.7.3-rc2`, in `4.8.0-beta4` the scanning does take place.

```xml
<!-- RedHat OS vulnerabilities -->
<provider name="redhat">
  <enabled>yes</enabled>
  <os>5</os>
  <os>6</os>
  <os>7</os>
  <os>8</os>
  <os>9</os>
  <os allow="Fedora Linux-39">9</os>
  <os allow="Oracle Linux-9">9</os>
  <update_interval>1h</update_interval>
  </provider>
```

We have also tried 

```xml
<os allow="Fedora Linux-3">39</os> 

<os allow="Fedora Linux|3">39</os> 
```

but they have not worked either. These are the manager's logs [ossec.zip](https://github.com/wazuh/wazuh-qa/files/14640279/ossec.zip). This is the information of the `Fedora 39` VM where the Agent is installed.

![image](https://github.com/wazuh/wazuh/assets/54536265/5e3ffee7-d07e-4bba-9a46-de27ef2a0f56)

![image](https://github.com/wazuh/wazuh/assets/54536265/49cdcd40-f929-4ef7-b842-300bb8970d41)

```console
[root@fedora39 vagrant]# uname -r
6.5.6-300.fc39.x86_64
[root@fedora39 vagrant]# cat /etc/os-release 
NAME="Fedora Linux"
VERSION="39 (Thirty Nine)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (Thirty Nine)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-05-14
```

**Comment by MarcelKemp** [comment]
Hi @rafabailon,

The problem is in the configuration used for _Vulnerability Detector_, in which when writing several `<os ...>9</os>` fields, it currently stays with the last option defined because it performs an overwrite.
- Similar case: https://github.com/wazuh/wazuh/issues/17649#issuecomment-1894019768

This is known and commented in the documentation:
- https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/allow-os.html#configuring-vulnerability-detector-to-include-unsupported-systems

To make it work, you would simply need to modify the configuration as follows: 
```xml
<!-- RedHat OS vulnerabilities -->
<provider name="redhat">
  <enabled>yes</enabled>
  <os>5</os>
  <os>6</os>
  <os>7</os>
  <os>8</os>
  <os allow="Fedora Linux-39,Oracle Linux-9">9</os>
  <update_interval>1h</update_interval>
  </provider>
```

- Could you check it? And if there are no problems, we could close this issue.

**Comment by rafabailon** [comment]
Hi @MarcelKemp 

I have tried the configuration you mentioned and it has worked without problems. We can now see vulnerabilities in Fedora 39. Thanks! I think the issue can be closed.
