### ISSUE TITLE
Scanning unsupported systems: Invalid element in the configuration: 'os' 

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#22592]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta4 | Vulnerability Detection | Manager | Packages | Any |

### Description

Regarding [Scanning unsupported systems](https://documentation-dev.wazuh.com/v4.8.0-beta4/user-manual/capabilities/vulnerability-detection/allow-os.html) documentation, is possible to detect vulnerabilities in unsupported operating systems using the `os` option. However, the use of this option produces the following warning

```
2024/03/18 16:14:39 wazuh-modulesd[52420] wmodules-vulnerability-detection.c:54 at wm_vulnerability_detection_subnode_read(): WARNING: (1230): Invalid element in the configuration: 'os'.

```

In addition, this [option](https://documentation-dev.wazuh.com/v4.8.0-beta4/user-manual/reference/ossec-conf/vuln-detector.html) is not included in the vuln detection module documentation

### Steps to reproduce

- Deploy a manager
- Configure the manager in other to allow the scanning of unsupported OS. For example POP-OS:

```
<vulnerability-detection>
   <enabled>yes</enabled>
   <index-status>yes</index-status>
   <feed-update-interval>60m</feed-update-interval>
   <os allow="Linux Mint-19,Pop!_OS-18">canonical</os>
</vulnerability-detection>
```
- Restart the manager
- Check in the logs that unexpected warning appear

**Comment by sebasfalcone** [comment]
## Description
Currently, we map operating systems to specific vendor feeds through the [feed-global map](https://github.com/wazuh/intelligence-data/blob/main/base-rules/feed-global.json). OSs that have no mapping will default to the NVD feed, which is more generic and could lead to a decrement in the detection performance

To solve it, [this feature](https://documentation-dev.wazuh.com/v4.8.0-beta4/user-manual/capabilities/vulnerability-detection/allow-os.html#configuring-vulnerability-detection-module-to-include-unsupported-systems) must be implemented.

This will ensure that the system is more dynamic and that the user shouldn't wait until we update the content

## Notes
- Remember to update the valid_paths for the configuration
  - https://github.com/wazuh/wazuh/pull/21951
- Follow the documentation as a guide

## DoD
- [ ] The feature is implemented
- [ ] The feature is tested

**Comment by sebasfalcone** [comment]
## Affected modules
- https://github.com/wazuh/wazuh/blob/4.8.0/src/config/wmodules-vulnerability-detection.c
- https://github.com/wazuh/wazuh/blob/4.8.0/src/wazuh_modules/vulnerability_scanner/src/policyManager/policyManager.hpp

## Attack plan
- Decide:
  - The format for the `os` tag
    - I've propose that each tag represents one OS to feed pair (eg. `<os allow="Linux Mint-19">canonical</os>`)
  - How we are going to save it
    - We may want to follow and idea similar to the one in the [feed-global-map](https://github.com/wazuh/intelligence-data/blob/main/base-rules/feed-global.json)

**Comment by sebasfalcone** [comment]
It was decided that this feature will be deprecated, the documentation must be updated accordingly

**Comment by GabrielEValenzuela** [comment]
# Design Proposal: Allow support to scan custom OS

## 1. Introduction
This proposal outlines the introduction of an `os allow` option in our system configuration to manage and restrict the scanning process to supported operating systems. This enhancement is aimed at increasing the efficiency of our vulnerability detection module and reducing errors caused by attempts to scan unsupported systems with the default NVD.

## 2. Background
Currently, our VD scans all connected systems, regardless of their operating system, but when there is not an official feed, the default option is to use the NVD database to make the scan of the packages. This leads to unnecessary processing and potential errors when unsupported systems are encountered. There is a need to implement a filtering mechanism to avoid these issues and focus our resources more effectively.

## 3. Proposal
The proposed solution involves the addition of an `os allow` option within the scanning section configuration. This new feature provides an option to decide the scanning action for systems running non-supported operating systems. Users can specify to use a default scanning feed tailored for generic assessments.


### 3.1 Design Details
- **Configuration Syntax:**
  - The configuration will be specified in XML format, making it both human-readable and easy to parse programmatically.
  - Each `OS` tag represents an operating system along with optional version information and a required feed for scanning. Here are the specifics:

```xml
<!-- Configuration example for specifying operating systems and their scanning feeds -->
<OsAllow>
  <!-- Specify OS with optional version and required feed. If the version is omitted, all versions are assumed. -->
  <OS name="Linux Mint" version="19">canonical</OS>
  <OS name="Ubuntu" version="*">ubuntu_main</OS> <!-- Wildcard for all versions -->
  <OS name="CentOS" version="7,8">centos_stream</OS> <!-- Comma-separated for specific versions -->
</OsAllow>
```

### 3.2 Expected Benefits
- **Precision in Scanning:** By specifying operating systems and their versions, users can precisely target their scans, reducing unnecessary processing.
- **Flexibility:** The ability to use wildcards or specify multiple versions allows for flexible configuration suited to diverse environments.
- **Ease of Configuration:** The XML format is straightforward for users to edit and for systems to parse, facilitating easy updates and maintenance.

- **Implementation Considerations:**
  - During initialization, the VD will parse and validate the `OsAllow` list and the child directives.
  - Scans will be conducted on supported systems as per the `OsAllow` list.
 

## 5. Impact Analysis
### 5.1 Technical Impact
- The introduction of the `OsAllow` option requires changes in the configuration parsing and scanning modules of the tool.
- Additional testing will be necessary to ensure that new functionality does not interfere with existing features.

## 6. Sequence Diagram

_WIP_

## 6. Conclusion
This enhancement not only optimizes the efficiency of the scanning operations by preventing unnecessary processing on unsupported systems but also ensures ease of use and adaptability, allowing users to specify system versions and scanning feeds with granularity and flexibility. 

## 7. Approval and Feedback
- **Approval Process:** Upon gathering feedback, revisions will be made as necessary, followed by formal approval of leads.

- [ ] Design approved by @sebasfalcone 
- [ ] Design approved by @Dwordcito

**Comment by sebasfalcone** [comment]
Great proposal @GabrielEValenzuela!

Some questions:

---

> If the version is omitted, all versions are assumed.

Wouldn't this make the wildcard option redundant?

---

> version="19"

This refers to the major version right? How would you match this on the different systems? (windows, macOS, etc)

**Comment by GabrielEValenzuela** [comment]
Thanks @sebasfalcone ! I update to v1.0.2 of the document 😃

**Comment by GabrielEValenzuela** [comment]
@sebasfalcone 

I think we should change the target branch or leave this issue on hold until `4.8.0` merges into `4.9.0` because we need 

- #23223

And it's in `4.8.0`

**Comment by sebasfalcone** [comment]
## Issue blocked
To implement this issue, the following configuration structure was proposed:
```xml
<!-- Configuration example for specifying operating systems and their scanning feeds -->
<os-allow>
  <os>
    <name>Linux Mint</name>
    <version-list>
      <version>19</version>
    </version-list>
    <feed>canonical</feed>
  </os>
  <os>
    <name>Windows</name>
    <version-list>
      <version>10</version>
      <version>11</version>
    </version-list>
    <feed>canonical</feed>
  </os>
  <os>
    <name>Ubuntu</name>
    <version-list> <!-- Empty list to apply for all versions -->
    </version-list>
    <feed>ubuntu_main</feed>
  </os>
  <os>
</os-allow>
```

This is due to the fact that the current configuration loader is unable to read the text labels so this would make the parsing process much easier and the changes more scoped

### Extra
I think this feature will greatly impact the user experience because it gives a false sense of compatibility with non tested OSs

**Comment by davidjiglesias** [comment]
The approach will be to properly support new OS adding them to the specific VD feed.
