### ISSUE TITLE
Syscollector is not detecting NPM packages installed locally

### ISSUE THREAD

**Issue by jftuduri** [wazuh/wazuh#22609]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0 | Syscollector | Agent | - | - |

# Description

While conducting functional [tests on version 4.8.0 of VulnDet](https://github.com/wazuh/wazuh/issues/22406), it was observed that when `npm` packages are installed using the standard method (`npm install <package_name>`), they fail to be detected by `syscollector`. Conversely, packages installed globally (`npm install -g <package_name>`) are correctly identified by syscollector.

## Example
![image](https://github.com/wazuh/wazuh/assets/7939712/b3fa7ced-43d8-46dc-9aca-936d5ee55fdb)

- socket.io was installed locally -> Not present in packages inventory
![image](https://github.com/wazuh/wazuh/assets/7939712/bc0ca229-5ae1-4928-aee8-660f54f4dace)

- passport was installed globally -> Present in packages inventory
![image](https://github.com/wazuh/wazuh/assets/7939712/e531b7de-a20c-488d-b21b-a94a143e6de4)

Related issue: https://github.com/wazuh/wazuh/issues/21855

**Comment by sebasfalcone** [comment]
The solution may be to update this list:
https://github.com/wazuh/wazuh/blob/aa3759b8600cdbea6d68b434bc7ec421075f84f0/src/data_provider/src/sharedDefs.h#L125-L135

**Comment by pereyra-m** [comment]
The non-global installation installs the modules in the current project folder.
The recursive search is resource and time demanding, so we can't add too many custom paths.

@sebasfalcone , we should determine if we are going to add more paths to the `UNIX_NPM_DEFAULT_BASE_DIRS` set you've shared and what will be.

**Comment by GabrielEValenzuela** [comment]
# Analysis of Syscollector's Failure to Detect Locally Installed NPM Packages

## Introduction:
Syscollector, is encountering challenges in detecting locally installed NPM (Node Package Manager) packages. Despite NPM packages being installed within the project folder rather than globally, Syscollector's current setup fails to recognize these local installations. This analysis aims to explore the reasons behind this issue and propose potential solutions.

## Non-Global Installation:
When NPM packages are installed locally, they are stored within the project folder rather than globally. This decentralized approach complicates detection, as packages are not installed in standard directories. Consequently, Syscollector's default search mechanism may overlook these locally installed packages.

## Resource and Time Demands of Recursive Search:
A recursive search, a common method for detecting installed software, entails traversing through directory structures to locate relevant files. However, this process is resource-intensive and time-consuming, especially in large and complex systems. As such, incorporating extensive custom paths into Syscollector's search algorithm could exacerbate these challenges without guaranteeing comprehensive detection. As @pereyra-m says in https://github.com/wazuh/wazuh/issues/22609#issuecomment-2057873807

## Proposal for Enhancement:
To address the limitations of Syscollector's NPM package detection, a viable solution involves introducing a new configuration parameter. This parameter would empower users to specify custom paths for Syscollector to scan, thereby targeting specific directories where local NPM packages are likely to reside. By allowing users to define these paths, Syscollector can tailor its search scope to the relevant areas, mitigating the resource and time burdens associated with exhaustive recursive scanning.  Implementing an automatic inclusion of custom paths may present challenges due to the vast number of directories potentially containing local NPM packages. **Each folder within the system represents a potential project directory, making indiscriminate scanning impractical.**

## Conclusion:
While the addition of custom path configurations holds promise for enhancement, careful consideration is required to strike a balance between thoroughness and efficiency in implementation. Also, this approach could be hard to use for the user side and involves refactoring a lot of syscollector's code.

CC @sebasfalcone

**Comment by sebasfalcone** [comment]
@GabrielEValenzuela, thanks for the analysis! 

## Conclusion
We decided that only the default paths are going to be scanned, if new default paths arise we will add them to the mentioned list

**Comment by sebasfalcone** [comment]
@GabrielEValenzuela, thanks for the analysis! 

## Conclusion
We decided that only the default paths are going to be scanned, if new default paths arise we will add them to the mentioned list
