### ISSUE TITLE
WAZUH active-response

### ISSUE THREAD

**Issue by qwsysadmin** [wazuh/wazuh#22635]
In WAZUH i have added active-response for specific rule.id i.e when specific rule.id will get hit by the attacker, the active-response route-null will get trigger & stop/block the user from attacking my server. Its it working perfectly.  But now the route-null active-response is blocking the IP's of legit user of my organization. Is it possible that I can allow a user to hit a specific rule.id for a specific number of times & then it will block that user instead of adding their IP's to the whitelist. 
  NOTE:- Here I have not provided any <timeout> to block the user directly if the attack matches the rule.id "31101"

**Comment by nmkoremblum** [comment]
Hi @qwsysadmin, the attack will be blocked by banning the User's IP, there is no default way to ban a User instead of an IP. You can set a timeout for that IP to be unblocked or you can create your own Active Responses, please, take a look at the following links:

https://documentation.wazuh.com/current/user-manual/capabilities/active-response/ar-use-cases/blocking-ssh-brute-force.html

https://documentation.wazuh.com/current/user-manual/capabilities/active-response/custom-active-response-scripts.html

Best regards,

Mariano Koremblum
