### ISSUE TITLE
Agent IP

### ISSUE THREAD

**Issue by zizii1** [wazuh/wazuh#22647]
Hello, I enrolled a debian agent to wazuh, and the registered IP of the agent is a public IPv4 IP, while all the other agents(windows, macs) are registered with private IP, does anyone know the fix?
Note: server is on cloud.

**Comment by Enaraque** [comment]
Hello zizii1,

When enrolling a Debian agent to Wazuh, if the registered IP of the agent is showing as a public IPv4 while other agents (Windows, Macs) are registered with private IPs, there could be several factors at play. This situation is indeed peculiar, especially since it shows differences within the same environment. To troubleshoot this, we need to consider a few things:

1. **Manager Configuration**:
	- **Manager Configuration**: Check the configuration of your Wazuh manager. Specifically, look at the setting for `use_source_ip` in the `ossec.conf` file. If this option is enabled (`<use_source_ip>yes</use_source_ip>`), the agent’s IP will be registered as the source IP seen by the manager, which could be the public IP if the agent is communicating over the internet. https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/auth.html#use-source-ip
2. **Agent Configuration**:
    - **Agent Version and Configuration**: Ensure that the agent is properly configured and check the version to ensure compatibility.
    - **Agent Address**: You can specify the agent’s address in the agent’s `ossec.conf` file using the `<agent_address>` tag. This explicitly sets the address used by the agent, which might resolve the issue if the public IP is being incorrectly registered. https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#agent-address
    - **Use Source IP**: Similar to the manager setting, the agent also has a `use_source_ip` option. If enabled, it might affect how the IP is reported. https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#use-source-ip
3.  **Network Environment**:
    - Since your server is on the cloud, ensure that the network setup is consistent for all agents. Differences in network configurations, such as NAT or firewall rules, might cause variations in how IP addresses are reported. 

Feel free to share more details about your configuration if you need further assistance.

Best regards.
