### ISSUE TITLE
Vulnerability False Positive

### ISSUE THREAD

**Issue by HQuest** [wazuh/wazuh#22645]
Wazuh OVA 4.7.2 updated to 4.7.3 as per [Upgrade guide](https://documentation.wazuh.com/current/upgrade-guide/index.html)

A vulnerability scan on a pair of fully patched test Windows Server 2022 Datacenter 21H2 systems found a potential vulnerability that, as per Microsoft, applies to Windows Server 2022 Core 23H2 and Windows 11 (KB5032202), according to the referenced [CVE-2023-36046 @ MSRC](https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-36046).

As I understand from Wazuh's [User Manual / Capabilities / Vulnerability detection / How it works](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/how-it-works.html), Microsoft feeds are parsed by Wazuh feed service, so I would think this would be a web parser error/limitation outside my local Wazuh install.

Happy to provide any required information for troubleshoot (directions welcome, I'm still navigating thru this tool).

**Comment by jftuduri** [comment]
Hello @HQuest!
Thanks for reaching out and sorry for the late response.

This problem that you mention is being worked on here: https://github.com/wazuh/wazuh/issues/21127
It will be fixed in the upcoming 4.8.0 release, together with the Vulnerability Detector refactor: https://github.com/wazuh/wazuh/issues/14153#top

Sorry for the inconvenience.
Regards!
