### ISSUE TITLE
Check Wazuh agent compatibility with the new version of Amazon Linux 2023 version 2023.4.20240319

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#22663]
# Description
Hello team, this issue is to check the full compatibility of Wazuh on the newfound version of Amazon Linux 2023 version 2023.4.20240319 operating system.

OSs checks issue: https://github.com/wazuh/wazuh/issues/22662

- Release notes: https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.4.20240319.html

For this, it is necessary to perform the following tests to check that everything works as expected:

- [x] Agent and server (if possible) installations.
- [x] O.S. reporting in the interface.
- [x] WPK  upgrade.
- [x] Enrollment and connectivity with the manager.
- [x] FIM: Real-time and who-data [NOT WORKING #19399]  engines (if available).
- [X] SCA: Policy support.
- [X] Vulnerability Detector: Vulnerability support.
- [X] Syscollector: Complete inventory.
- [X] Active Response: port blocking.
- [X] Log capture.

**Comment by lchico** [comment]
# Testing

## :green_circle: Agent and server, (enrollment and connectivity with the manager)
<details>
<summary>Dashboard</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/d7b4bc4d-56fa-4afd-b07a-26b70622ef5e" alt="dashboard">
</details>

<details>
<summary>Agent Log</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/edbf9eb4-216a-4903-8ff5-d69b588f176f" alt="Console">
</details>

### :green_circle: FIM scheduled

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/8801b5b2-0c7d-4eae-8d00-2f5a5ca9e02b">
</details>

## :green_circle: FIM Real-time
<details>
<summary>Configuration on the agent</summary>

  ```
    <frequency>4</frequency>
    <directories realtime="yes">/var/log/testrealtime</directories>
  ```
</details>

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/22db329b-225b-4111-85a2-ec85250766c7">
</details>



## :green_circle: Upgrade using WPK
From the manager run:
  ```
     /var/ossec/bin/agent_upgrade -a 003
  ```

<details>
<summary>The agent required tar package installed</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/f84fe1cf-3eb2-411a-bb6e-78166348e76c">
</details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/21783107-e15f-4d75-8b4f-fc1809ab27c1">
</details>


## :yellow_circle: SCA support

No official SCA policies are available ( [check](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/available-sca-policies.html) this list).

Since it is not listed at [CIS Benchmarks](https://downloads.cisecurity.org/#/), no issue will be created.

SCA module is tested anyway, with a custom policy.

Configuration

[This usecase](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/use-cases.html#detecting-keyword-in-a-file) is used to test SCA module.

<details>
<summary>Manager log:</summary>

```
** Alert 1712843076.7121: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
2024 Apr 11 13:44:36 (51134f7211d3) any->sca
Rule: 19007 (level 7) -> 'SCA use case: Keyword check: Ensure password is disabled in the test configuration file'
{"type":"check","id":108372854,"policy":"SCA use case: Keyword check","policy_id":"keyword_check","check":{"id":10000,"title":"Ensure password is disabled in the test configuration file","description":"Password is enabled in the test configuration file.","rationale":"Password is considered weak for the custom test application. Threat actors can brute-force your password.","remediation":"Disable password by setting the value of the password_enabled option to no.","rules":["f:/usr/share/testfile.txt -> r:^password_enabled: yes$"],"condition":"none","file":"/usr/share/testfile.txt","result":"failed"}}
sca.type: check
sca.scan_id: 108372854
sca.policy: SCA use case: Keyword check
sca.check.id: 10000
sca.check.title: Ensure password is disabled in the test configuration file
sca.check.description: Password is enabled in the test configuration file.
sca.check.rationale: Password is considered weak for the custom test application. Threat actors can brute-force your password.
sca.check.remediation: Disable password by setting the value of the password_enabled option to no.
sca.check.file: ["/usr/share/testfile.txt"]
sca.check.result: failed

```

</details>
<details>
<summary>Agent log:</summary>

```
35542:2024/04/11 18:30:05 sca[9142] wm_sca.c:152 at wm_sca_main(): INFO: Module started.
35544-2024/04/11 18:30:05 sca[9142] wm_sca.c:191 at wm_sca_main(): INFO: Loaded policy '/var/ossec/ruleset/sca/cis_amazon_linux_1.yml'
35545-2024/04/11 18:30:05 sca[9142] wm_sca.c:191 at wm_sca_main(): INFO: Loaded policy '/var/ossec/etc/custom-sca-files/keywordcheck.yml'

```

</details>

<details>
<summary>Inventory:</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/2ebe3594-ab9e-421d-8f55-3ff2a745ddb7">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/7a8bce42-7c51-41e6-b1ac-bd91d21bed95">
</details>

## :green_circle: Vulnerability detector
<details>
<summary>Installed curl on wazuh-agent for vulnerability detection</summary>

  ```
     yum install curl-minimal-7.87.0-2.amzn2023.0.2.x86_64
  ```
</details>

<details>
<summary>Dashboard</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/56b4e0eb-30b8-4936-af23-6aa3c359113c">
</details>


## :green_circle: Active response

<details>
<summary>Manager configuration:</summary>

```
<ossec_config>
  <active-response>
    <disabled>no</disabled>
    <command>restart-wazuh</command>
    <location>defined-agent</location>
    <agent_id>003</agent_id>
    <level>7</level>
  </active-response>
</ossec_config>
```
</details>

<details>
<summary>Result:</summary>
<img src="https://github.com/wazuh/wazuh/assets/21695385/1bfd2de4-bdf8-4b56-9f5b-9126ed3a595f">
</details>


## :green_circle: Log Capture

<details>
<summary>Agent configuration:</summary>

```
  <localfile>
    <location>/var/log/log_capture.log</location>
    <log_format>syslog</log_format>
  </localfile>
```
</details>

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/e2e6a0a3-d466-4581-a98a-1fd8e78a1e91">
</details>


## :green_circle:  Syscollector


<details>
<summary>Inventory</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/21c2ea7d-0965-4ff8-9747-62788bb1b774">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/2a1f07c2-970f-4017-bb49-eddab240bded">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/dce8c2ca-51b9-4178-96ca-612f8761c445">
</details>

**Comment by MarcelKemp** [comment]
LGTM.
