### ISSUE TITLE
Create GitHub workflows to generate WPK files with new structure

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#22673]
### Description

As the epic https://github.com/wazuh/wazuh/issues/21152 requires, we need to improve the WPK process for every OS.

This issue will cover the changes we need to apply in the new GitHub workflows:

- Ensure the GitHub workflows use the new Dockerfiles created as part of this issue: https://github.com/wazuh/wazuh/issues/22400
- Ensure that the WPK files are uploaded to S3 following the paths structure defined as part of this issue: https://github.com/wazuh/wazuh/issues/22672

**Comment by jr0me** [comment]
### Update

https://github.com/wazuh/wazuh-agent-packages/pull/5 brings changes to the WPK generation workflow. As discussed, due to the requirement of signing packages prior to creating WPKs, the generation of the latter will remain on a separate workflow, which we update in the linked PR to remain compatible with the latest changes brought by the epic: WPKs no longer build from sources and use the existing packages (deb, rpm, msi, pkg). Nomenclature changes have also been applied.
