### ISSUE TITLE
Refactor and migrate FIM test_tags suite

### ISSUE THREAD

**Issue by sdvendramini** [wazuh/wazuh#22762]
|Related Epic   |
|-----------------------|
|  wazuh/wazuh#17881            |

As part of https://github.com/wazuh/wazuh/issues/17881, we need to refactor and migrate test_tags suite from the QA repository to the Core repository.

**Comment by Nicogp** [comment]
Test completely [skipped ](https://github.com/wazuh/wazuh-qa/blob/master/tests/integration/test_fim/test_files/test_tags/test_tags.py#L116)due to the issue https://github.com/wazuh/wazuh/issues/9298

Tests were run on linux but most of them failed
![image](https://github.com/wazuh/wazuh/assets/13004400/72a37375-83c4-4db3-a769-0d0339eee08a)

so they should be completely redone.

**Comment by TomasTurina** [comment]
Not working tests. Won't be migrated.
