### ISSUE TITLE
Cluster disabled in ossec.conf, can't be enabled.

### ISSUE THREAD

**Issue by zapa11** [wazuh/wazuh#22783]
Hello team,
I am using Wazuh 4.7, i just installed it. I am trying to send logs from a Fortigate Firewall into the Wazuh and i am receiving this errors:
Ip 10.20.20.1 is the Fortigate ip.

Apr 6, 2024 @ 10:54:33.000 wazuh-remoted WARNING  (1213): Message from '10.20.20.1' not allowed. Cannot find the ID of the agent. Source agent ID is unknown.

Checking online for solutions , it seems that is related to the cluster config in ossec.conf. I tried to comment the line disabled to YES, but is not working, i am receiving the error below.  Please help.

  <cluster>
    <name>wazuh</name>
    <node_name>node01</node_name>
    <node_type>master</node_type>
    <key></key>
    <port>1516</port>
    <bind_addr>0.0.0.0</bind_addr>
    <nodes>
        <node>NODE_IP</node>
    </nodes>
    <hidden>no</hidden>
    <disabled>yes</disabled>
  </cluster>

-------------------------------Error-----------------
Error: Could not update configuration (1908) - Error validating configuration 
    at Function.returnErrorInstance (https://10.20.20.7/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:186528)
    at Function._callee2$ (https://10.20.20.7/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:184748)
    at tryCatch (https://10.20.20.7/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:786910)
    at Generator.invoke [as _invoke] (https://10.20.20.7/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:790926)
    at Generator.next (https://10.20.20.7/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:788105)
    at asyncGeneratorStep (https://10.20.20.7/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:178377)
    at _next (https://10.20.20.7/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:178688)

Best regards,
Radu

**Comment by zapa11** [comment]
this is the ossec.conf cluster conf:

  <cluster>
    <name>wazuh</name>
    <node_name>node01</node_name>
    <node_type>master</node_type>
    <key></key>
    <port>1516</port>
    <bind_addr>0.0.0.0</bind_addr>
    <nodes>
        <node>NODE_IP</node>
    </nodes>
    <hidden>no</hidden>
    <disabled>yes</disabled>
  </cluster>

**Comment by zapa11** [comment]
![image](https://github.com/wazuh/wazuh/assets/94761321/6c8ff66f-497f-4662-a999-257c9bb83764)

**Comment by pereyra-m** [comment]
Hi again @zapa11 !
Glad to know it's working.

About your question, this type of log collection you are using didn't require an agent installation, so there isn't a real agent sending those logs.
This also happens when you configure the Agentless monitoring (https://documentation.wazuh.com/current/user-manual/capabilities/agentless-monitoring/index.html#agentless-monitoring) and provide the required credentials to the manager to log into some system and extract information without installing and registering an agent.

If the logs collected this way can't be filtered in some other way that fits your needs, it's possible to install an agent in a host and make it receive and forward these logs. This way, you'd have the logs coming from a "real" agent. Although this can be inconvenient in some environments.

Regards.

**Comment by sebasfalcone** [comment]
Inactive thread, feel free to re-open it if needed it
