### ISSUE TITLE
Pattern change in CPU by Wazuh-modulesd

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh#22830]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-Beta5 | Wazuh manager | Manager | Packages | CentOS |

During testing in [Release 4.8.0 - Beta 5 - Footprint Metrics - VULNERABILITY-DETECTOR-REGISTER (2.5d)](https://github.com/wazuh/wazuh/issues/22798), it has been detected a rare change in the pattern of modulesd on the CPU plot.  This behavior has not been detected in the previous version, only in [4.8.0 - Beta 2](https://github.com/wazuh/wazuh/issues/22165) and it was reported [here](https://github.com/wazuh/wazuh/issues/22205) but was not analyzed.

The plots are compared to https://github.com/wazuh/wazuh/issues/22306.

| 4.8.0 | 4.7.3 |
| --- | --- | 
| ![image](https://github.com/wazuh/wazuh/assets/101177239/32e1ddeb-5356-45a1-922b-5984ee8033fc) |  ![image](https://github.com/wazuh/wazuh/assets/101177239/38918870-1e47-4145-9422-665207b174f2) | 

4.8.0 - Beta 2 plot:

![image](https://github.com/wazuh/wazuh/assets/101177239/ccdd4da7-4b62-4495-8360-77f59ec547ea)

**Comment by sebasfalcone** [comment]
> Check the delay sleep time in the delayed queue.

I've asked for the possibility of repeating the tests with a custom branch so we can test what happens if we reduce the delay time

**Comment by sebasfalcone** [comment]
Blocked, awaiting for new tests to be performed over [custom branch](https://github.com/wazuh/wazuh/tree/test/reduce-delayed-events-delay)

**Comment by sebasfalcone** [comment]
Issue updated, investigating impact of changes

**Comment by sebasfalcone** [comment]
## Analysis
The same test was performed in a [custom branch](https://github.com/wazuh/wazuh/compare/4.8.0...test/reduce-delayed-events-delay)

We reduced the time between retries of delayed events, which means that the EPS processed by the scanner increased. This allowed the module to "relax" and dispatch more events than the ones arriving, thus not stalling on 100% CPU consumption

- 4.7.3
![image](https://github.com/wazuh/wazuh/assets/34063881/a13b7ac7-c2e1-444e-a130-e3809eba137e)

- 4.8.0 Beta 5
![image](https://github.com/wazuh/wazuh/assets/34063881/4c6bc57a-b944-4f2f-b1d7-f1b42573b1e9)

- Custom Branch
![image](https://github.com/wazuh/wazuh/assets/34063881/c2446334-3d01-4ff2-8e2a-748447816f98)
![image](https://github.com/wazuh/wazuh/assets/34063881/97c1e700-cd99-4acc-852f-704b304658fc)


## Conclusion
The implementation of 4.8.0 is completely different from the one in 4.7.3 we have to decide if this new CPU consumption profile is acceptable or not

We may have some more tweaking possible but further investigation is needed

**Comment by sebasfalcone** [comment]
## Analysis
After further analysis, we suspect that the same situation wasn't replicated in the new execution

To validate this we need to re-run the original tests and see if the pattern is the same or not

**Comment by sebasfalcone** [comment]
## Analysis

### Re-launch Beta 5
We see a change on the CPU stress pattern:
![Image](https://github.com/wazuh/wazuh/assets/34063881/b290313b-4ac7-494d-a899-a296af276f32)

No events where dropped:


![Image](https://github.com/wazuh/wazuh/assets/34063881/fd72f14a-aa9c-4bba-98e8-c4736c460716)

Files descriptors are released:


![Image](https://github.com/wazuh/wazuh/assets/34063881/c7d2e2f7-3863-4986-b492-b9bdd0824c15)


### Test branch
The changes on the test branch reflect an improvement on the CPU stress pattern:

![Image](https://github.com/wazuh/wazuh/assets/34063881/2382d9e6-1c5b-47f8-a82d-4b079dae765b)

Also no events are dropped:


![Image](https://github.com/wazuh/wazuh/assets/34063881/e3a4ad5b-7e57-4237-b8b0-7b78fa21bd53)


Files descriptors are more stable and less:


![Image](https://github.com/wazuh/wazuh/assets/34063881/2357ce5a-8dd8-439a-99c8-41b9b1eb1310)

## Conclusion
We should further investigate this tweaking and define its best value

The module is working as expected and no comparison can be made against 4.7.3, due to:
- https://github.com/wazuh/wazuh-jenkins/pull/6201
