### ISSUE TITLE
Investigate API IT fails after connexion package migration

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#22846]
|Wazuh version|Component|
|---|---|
| 4.9.0 | API |

## Description

In updating the Connexion and Uvicorn dependencies, errors were found in some of the API integration tests. This issue aims to investigate possible causes of error.

PR: https://github.com/wazuh/wazuh/actions/runs/8575924926/job/23505921844?pr=22680
Archive: [logs_22479587040.zip](https://github.com/wazuh/wazuh/files/14911009/logs_22479587040.zip)

**Comment by GGP1** [comment]
## Update

I've been debugging the error locally and I've found two strange behaviors:

1. Every 2 restarts, the API is not logging anything to the `api.log` file
2. Even though there's no logs in the file, the API is still running and if I try to send a request it returns `Timeout executing API request immediately`

It seems to be related to the `wazuh-apid` processes not being handled correctly, I continue investigating the root cause.

**Comment by GGP1** [comment]
## Update

Removed the `wait_for_api_start` fixture that was causing the test to fail when the logging level was set to `error`.
