### ISSUE TITLE
CVE vulnerabilities in 7-zip prorgam are not shown

### ISSUE THREAD

**Issue by BooopLJ** [wazuh/wazuh#22904]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.3 | Vulnerability Scanning | Manager/Agent | Packages/Sources | Windows 10 22h2:10.0.19045.4291 |

Hi All,
I'm having issues with vulnerability scanning, i added an entry to the 7-zip program in CPE Helper and installed Windows 10 and 7-zip version 19.00 on a virtual machine for testing. According to the entries in NVD, 2 CVEs should be visible: CVE-2023-31102 and CVE-2022-29072, but they are not visible, what could be the reason?

I have enabled the extended logging option and below is a fragment of the log:
2024/04/12 10:29:14 wazuh-modulesd:vulnerability-detector[58343] wm_vuln_detector_nvd.c:3313 at wm_vuldet_add_dic_cpe(): DEBUG: (5446): The CPE 'a:7-zip:7-zip:19.00::::::x64:' from the agent '005' was indexed.

Thanks so much for any tips.

**Comment by MiguelazoDS** [comment]
Hi @BooopLJ, 

I'm afraid that the CVEs related to 7-zip are falling into this condition (cpe:2.3:o:microsoft:windows:-:*:*:*:*:*:*:*) 
![image](https://github.com/wazuh/wazuh/assets/13010397/9458573c-0bf5-49f5-bffa-85fa427b3509)

The package is discarded since it does not match the generic CPE as a dependency for 7-zip packages. 

It's a known issue and it is meant to be addressed soon with the new changes related to the vulnerability scanner. 

Apologize for the inconvenience. Regards!

**Comment by Dwordcito** [comment]
@MiguelazoDS please create an issue in intelligence data for the translation and add tests into the VD QA tests to validate the efficacy.

**Comment by BooopLJ** [comment]
@MiguelazoDS  Thanks you for your response :)

**Comment by MiguelazoDS** [comment]
Thank you for contacting us!

**Comment by sebasfalcone** [comment]
Issue created to address this issue!
