### ISSUE TITLE
The problem with email_alerts

### ISSUE THREAD

**Issue by MikhailKrsk** [wazuh/wazuh#22901]
Hello, I neen help with solving the following problem: to send event notifications, I use the following code:
<email_alerts>
   <email_to>emailname@domenname.com</email_to>
    level 10  /level
    format sms /format
  /email_alerts

"Sms" format does not reflect all the necessary information. When I try to change the format to "full" or delete a line specifying the format, notifications stop coming. At the same time, no errors are displayed in mail.log. From the suspicious: warning: dict_nis_init: NIS domain name not set - NIS lookups disabled. 
At the same time, notifications configured by global are received. What is the problem?

**Comment by davidcr01** [comment]
Hello. Can you try to change the format value to the `default` value and apply the changes by restarting the Wazuh manager service with the `systemctl restart wazuh-manager` command? Make sure the `email_alerts` configuration block has the correct syntax and every tag is opened and closed. I leave you the [reference](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/email-alerts.html#format) of this configuration.

After this, please check the Wazuh manager status with the `systemctl status wazuh-manager` command and share with us the output in order to help you.

Also, please filter any errors or warnings by checking the `ossec.log` file. You can perform this with the `cat /var/ossec/logs/ossec.log | grep -i -E "warn|error"` command.

**Comment by MikhailKrsk** [comment]
Hello! 
My configuration block when notifications arrive correctly in SMS format:
`    <email_alerts>
      <email_to>myemail@email.com</email_to>
      <level>10</level>
      <format>default</format>
      <do_not_delay />
    </email_alerts>
`
If I use the sms format, in the ossec.log i see this warnings: "2024/05/02 09:09:23 wazuh-maild: WARNING: Invalid JSON alert read from 'logs/alerts/alerts.json': ...", their number corresponds to the received e-mail messages.

If I use a configuration block with the full or default format, the notification stops coming:
`    <email_alerts>
      <email_to>myemail@email.com</email_to>
      <level>10</level>
      <format>full</format>
      <do_not_delay />
    </email_alerts>
`
In the ossec.log i see 2 warnings: 

`2024/05/02` 09:11:54 wazuh-db: WARNING: DB(075) syscollector-packages component has more than one element with the same PK value `'f54dde620a62f81f3eee528e5ec9962af324a2ad'.`

`2024/05/02` 09:11:57 wazuh-analysisd: WARNING: Could not read XML string: '"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='MSOIDSVC.EXE'/><EventID Qualifiers='0'>0</EventID><Level>2</Level><Task>0</Task><Keywords>0x80000000000000</Keywords><TimeCreated SystemTime='2024-05-02T02:11:57.616736300Z'/><EventRecordID>11386758</EventRecordID><Channel>Application</Channel><Computer>******.******.com</Computer><Security/></System><EventData><Data>InitializeSvcAPI failed with hr = 0x8004825b</Data><Binary> _**Next, the error code is 35080 characters**_ `</Binary></EventData></Event>"'`

**Wazuh manager status:**

wazuh-manager.service - Wazuh manager
     Loaded: loaded (/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2024-05-02 09:09:46 +07; 20min ago
    Process: 658508 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
      Tasks: 183 (limit: 28683)
     Memory: 617.3M
     CGroup: /system.slice/wazuh-manager.service
             ├─658576 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
             ├─658577 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
             ├─658580 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
             ├─658583 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
             ├─658624 /var/ossec/bin/wazuh-authd
             ├─658641 /var/ossec/bin/wazuh-db
             ├─658665 /var/ossec/bin/wazuh-execd
             ├─658678 /var/ossec/bin/wazuh-maild
             ├─658686 /var/ossec/bin/wazuh-analysisd
             ├─658783 /var/ossec/bin/wazuh-syscheckd
             ├─658804 /var/ossec/bin/wazuh-remoted
             ├─658842 /var/ossec/bin/wazuh-logcollector
             ├─658859 /var/ossec/bin/wazuh-monitord
             └─658902 /var/ossec/bin/wazuh-modulesd

May 02 09:09:39 *******: Started wazuh-execd...
May 02 09:09:39 *******: Started wazuh-maild...
May 02 09:09:40 *******: Started wazuh-analysisd...
May 02 09:09:41 *******: Started wazuh-syscheckd...
May 02 09:09:42 *******: Started wazuh-remoted...
May 02 09:09:42 *******: Started wazuh-logcollector...
May 02 09:09:43 *******: Started wazuh-monitord...
May 02 09:09:44 *******: Started wazuh-modulesd...
May 02 09:09:46 *******: Completed.
May 02 09:09:46 ******* systemd[1]: Started Wazuh manager.

**Comment by MikhailKrsk** [comment]
> Hello. Can you try to change the format value to the `default` value and apply the changes by restarting the Wazuh manager service with the `systemctl restart wazuh-manager` command? Make sure the `email_alerts` configuration block has the correct syntax and every tag is opened and closed. I leave you the [reference](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/email-alerts.html#format) of this configuration.
> 
> After this, please check the Wazuh manager status with the `systemctl status wazuh-manager` command and share with us the output in order to help you.
> 
> Also, please filter any errors or warnings by checking the `ossec.log` file. You can perform this with the `cat /var/ossec/logs/ossec.log | grep -i -E "warn|error"` command.

Hello!
My configuration block when notifications arrive correctly in SMS format:
   <email_alerts> <email_to>myemail@email.com</email_to> <level>10</level> <format>default</format> <do_not_delay /> </email_alerts>
If I use the sms format, in the ossec.log i see this warnings: "2024/05/02 09:09:23 wazuh-maild: WARNING: Invalid JSON alert read from 'logs/alerts/alerts.json': ...", their number corresponds to the received e-mail messages.

If I use a configuration block with the full or default format, the notification stops coming:
   <email_alerts> <email_to>myemail@email.com</email_to> <level>10</level> <format>full</format> <do_not_delay /> </email_alerts>
In the ossec.log i see 2 warnings:

2024/05/02 09:11:54 wazuh-db: WARNING: DB(075) syscollector-packages component has more than one element with the same PK value 'f54dde620a62f81f3eee528e5ec9962af324a2ad'.

2024/05/02 09:11:57 wazuh-analysisd: WARNING: Could not read XML string: '"0200x8000000000000011386758Application..comInitializeSvcAPI failed with hr = 0x8004825b Next, the error code is 35080 characters </Binary></EventData></Event>"'

Wazuh manager status:

wazuh-manager.service - Wazuh manager
Loaded: loaded (/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: enabled)
Active: active (running) since Thu 2024-05-02 09:09:46 +07; 20min ago
Process: 658508 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
Tasks: 183 (limit: 28683)
Memory: 617.3M
CGroup: /system.slice/wazuh-manager.service
├─658576 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
├─658577 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
├─658580 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
├─658583 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
├─658624 /var/ossec/bin/wazuh-authd
├─658641 /var/ossec/bin/wazuh-db
├─658665 /var/ossec/bin/wazuh-execd
├─658678 /var/ossec/bin/wazuh-maild
├─658686 /var/ossec/bin/wazuh-analysisd
├─658783 /var/ossec/bin/wazuh-syscheckd
├─658804 /var/ossec/bin/wazuh-remoted
├─658842 /var/ossec/bin/wazuh-logcollector
├─658859 /var/ossec/bin/wazuh-monitord
└─658902 /var/ossec/bin/wazuh-modulesd

May 02 09:09:39 *******: Started wazuh-execd...
May 02 09:09:39 *******: Started wazuh-maild...
May 02 09:09:40 *******: Started wazuh-analysisd...
May 02 09:09:41 *******: Started wazuh-syscheckd...
May 02 09:09:42 *******: Started wazuh-remoted...
May 02 09:09:42 *******: Started wazuh-logcollector...
May 02 09:09:43 *******: Started wazuh-monitord...
May 02 09:09:44 *******: Started wazuh-modulesd...
May 02 09:09:46 *******: Completed.
May 02 09:09:46 ******* systemd[1]: Started Wazuh manager.

**Comment by davidcr01** [comment]
Hello. 

I could reproduce your problem. It seems that the emails can not be sent when specifying the `full` or `default` format. I opened [this](https://github.com/wazuh/wazuh/issues/23350) issue to investigate this problem and fix it.

I would recommend you to keep using the `sms` format by now. Sorry about the inconvenience, we will fix it as soon as possible.

**Comment by MikhailKrsk** [comment]
> Hello.
> 
> I could reproduce your problem. It seems that the emails can not be sent when specifying the `full` or `default` format. I opened [this](https://github.com/wazuh/wazuh/issues/23350) issue to investigate this problem and fix it.
> 
> I would recommend you to keep using the `sms` format by now. Sorry about the inconvenience, we will fix it as soon as possible.

Hello! Thanks for the feedback and help with the solution. The settings of my e-mail server automatically add a 700-character warning to each e-mail. I think that due to the established limit on the number of characters in the SMS format, the technical part of the alert is deleted, and I receive only 127 characters of technical information.
There is no way to change the settings of the electronic mail server, is there an opportunity somewhere in the wazuh settings to change the number of characters in the SMS format?

**Comment by davidcr01** [comment]
Hello.

Unfortunately, Wazuh does not have a native way to modify the number of characters sent for the email alerts. That's why we have different formats, in order to send more or less information. I leave you the [documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/email-alerts.html) of the email configuration.

A possible approach to this is that you could perform a custom integration with Wazuh using the integrator, and modify the content of the emails.

- Here is the custom Python script integration: https://github.com/jctello/JCT-Wazuh/blob/main/integrations/custom-email-alerts. You should modify the `email_server` and `email_from` variables.
- I leave you the full documentation about the integration section here: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/integration.html
- For example, I you want to send custom email alerts for level 10 or higher, add the following block to your `/var/ossec/etc/ossec.conf` file:
```yml
<integration>
  <name>custom-email-alerts</name>
  <hook_url>[your-emai...@example.com](https://groups.google.com/)</hook_url>
  <level>10</level>
  <alert_format>json</alert_format>
</integration>
```
- You should place the custom Python script in the `/var/ossec/integrations/custom-email-alerts` path and give it the right ownership and permissions with the following commands:
```
chown root:wazuh /var/ossec/integrations/custom-email-alerts
chmod 750 /var/ossec/integrations/custom-email-alerts
```
- Then, restart the Wazuh manager with `systemctl restart wazuh-manager` to apply the changes.

Hope it helps.

**Comment by davidcr01** [comment]
Hello.

Unfortunately, Wazuh does not have a native way to modify the number of characters sent for the email alerts. That's why we have different formats, in order to send more or less information. I leave you the [documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/email-alerts.html) of the email configuration.

A possible approach to this is that you could perform a custom integration with Wazuh using the integrator, and modify the content of the emails.

- Here is the custom Python script integration: https://github.com/jctello/JCT-Wazuh/blob/main/integrations/custom-email-alerts. You should modify the `email_server` and `email_from` variables.
- I leave you the full documentation about the integration section here: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/integration.html
- For example, I you want to send custom email alerts for level 10 or higher, add the following block to your `/var/ossec/etc/ossec.conf` file:
```yml
<integration>
  <name>custom-email-alerts</name>
  <hook_url>[your-emai...@example.com](https://groups.google.com/)</hook_url>
  <level>10</level>
  <alert_format>json</alert_format>
</integration>
```
- You should place the custom Python script in the `/var/ossec/integrations/custom-email-alerts` path and give it the right ownership and permissions with the following commands:
```
chown root:wazuh /var/ossec/integrations/custom-email-alerts
chmod 750 /var/ossec/integrations/custom-email-alerts
```
- Then, restart the Wazuh manager with `systemctl restart wazuh-manager` to apply the changes.

Hope it helps.

**Comment by MikhailKrsk** [comment]
Hello!
The proposed solution helped, I got the functionality that I needed. 
Thank you very much!
