### ISSUE TITLE
Add native capability to manage alerts and archives files

### ISSUE THREAD

**Issue by kclinden** [wazuh/wazuh#22952]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.2 | Manager | Manager | Packages | Linux |

Add a feature to manage the lifecycle of the files generated in `/var/ossec/logs/alerts/` and `/var/ossec/logs/archives/` similar to what Monitord does with ossec.log files. 

Today this has to be done on each manager through a cron job.
```
0 0 * * * find /var/ossec/logs/alerts/ -type f -mtime +365 -exec rm -f {} \;
0 0 * * * find /var/ossec/logs/archives/ -type f -mtime +365 -exec rm -f {} \;
```

**Comment by vikman90** [comment]
Hi @kclinden,

this issue is related to #3072 (and related). We're planning to overhaul our log management strategy in upcoming versions. The Engine (#11334) will handle logs differently (i.e. the archives log will no longer exist). On the other hand, we'll likely propose delegating file rotation and deletion tasks to native system tools like _crond_ and _logrotate_.

Thank you for your feedback!
Best regards.
