### ISSUE TITLE
FIM Diff report works only after second modification for existing files

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#23061]
|Wazuh version|Component|Install type|
|---|---|---|
| 4.7.0| FIM | Agent |

## Description 
There is an issue observed by two community users where they complained that the FIM feature of Wazuh did not send the "**Modification field**" alongside the alert until the action was triggered a second time.

From their observation, it only occurs on agents with version 4.7.0 and above.

## Expected behavior
The expected behavior is that the initial scan of FIM should create the first **diff** file. Then, the first modification on the file should contain a **diff** field in the alert.

**Comment by jotacarma90** [comment]
# Analysis

Hello team, I have checked this error.
I have found that the error is because the initial scan is avoiding processing all the alert content of each monitored file (this is expected as the initial scan should not generate any alerts). However, it should create the necessary report_changes files as it did initially.

Here you can see how the initial scan finishes processing the files before calling the `fim_file_diff` function, which is in charge of initialising the necessary report_changes files:

https://github.com/wazuh/wazuh/blob/cdc44097c91876950185faddbff7e6902a0ee5e1/src/syscheckd/src/create_db.c#L320-L343

It is also necessary to contemplate this case in the integration tests.

**Comment by MalthraxCrypto** [comment]
diffs for files/directories flagged as "realtime" or "whodata" need to be populated at agent startup.

as long as the above accounts for this, it should cover my use case satisfactorily.

would something like this work? or am I missing the mark here...
```
 320  if (_base_line == 0) { 
 321     diff = fim_file_diff(path, configuration); 
 322     return; // LCOV_EXCL_LINE 
 323  } 
```

**Comment by MarcelKemp** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/16487.
