### ISSUE TITLE
Configuration reading error on agents when installer in other directory than /var/ossec

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#231]
When installed on /opt/wazuh:

```
# /opt/wazuh/bin/agent-auth
2017/10/20 06:49:06 agent-auth: CRITICAL: (1226): Error reading XML file '/etc/ossec.conf':  (line 0).
```

The same thing occurs with other components such `ossec-execd`, `ossec-agentd` and `manage_agents`.

**Comment by vikman90** [comment]
**False positive.**

This is a common mistake at compile time: building project with no custom directory specification.

For example, this procedure is **incorrect**:

```
# make -C src TARGET=agent -j4
# ./install.sh
```

The system will fail to start because the custom directory must be specified at compile time.

These two build commands are **correct**:

```
# make -C src clean && ./install.sh
# make -C src clean-internals && make -C src TARGET=agent PREFIX=/opt/wazuh && ./install.sh
```

@chemamartinez please double check this issue. If the problem persists, please write which steps you follow to reproduce this problem.

**Comment by chemamartinez** [comment]
Hi @vikman90,

You are totally right, I have checked the both build commands that you said and it works properly.

**Comment by Flightkick** [comment]
I've installed according to the documentation (https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/wazuh_server_deb.html#wazuh-server-deb) and I get this error when restarting wazuh-manager.

dpkg installed it in /var/ossec/

But Wazuh/Ossec tries to read config from /etc/ossec.conf

`sudo service wazuh-manager restart` results in:

`Job for wazuh-manager.service failed because the control process exited with error code. See "systemctl status wazuh-manager.service" and "journalctl -xe" for details.`

Log file `/var/ossec/log/ossec.log` shows:
`ossec-testrule: CRITICAL: (1226): Error reading XML file '/etc/ossec.conf':  (line 0).`

**Comment by vikman90** [comment]
Hi @Flightkick,

I'm pretty sure this is a configuration issue. The log shows `/etc/ossec.conf` because it does chrooting, but the actual file is /var/ossec/etc/ossec.conf`.

Since the log prints an error at line 0, perhaps it's a syntax error. Please double check your configuration, I recommend you to use any XML validator like https://codebeautify.org/xmlvalidator.

If the problem persists, please show us a copy of your settings so we could try to debug them.
