### ISSUE TITLE
Package Query for Wazuh Agents in Inventory System

### ISSUE THREAD

**Issue by Lucas-MAI22** [wazuh/wazuh#23118]
Hello,

I found this issue https://github.com/wazuh/wazuh/issues/16706, and I would like to have the same thing, which is to make a query to find all agents that have the same package with Wazuh and its inventory system. I wanted to know if with the new versions this was integrated into the dashboard and how to do it.

Thanks in advance for your help.

**Comment by vikman90** [comment]
@Lucas-MAI22 currently, Wazuh categorizes inventory data on a per-agent basis, which indeed complicates global searches across all agents. That's why our colleague recommended running a query per each agent and then run a manual search. However, we are actively working on a solution to consolidate all inventory information into a unified database:

- https://github.com/wazuh/wazuh/issues/22887
  - https://github.com/wazuh/wazuh/issues/20540

This enhancement will enable users to perform searches across all agents, making it easier to identify specific software versions, vendors, or packages installed across your environment.

Regarding your specific request to query for agents with the same package, we are integrating this functionality into the dashboard as part of our ongoing development efforts. Once implemented, users will be able to effortlessly identify agents with matching packages, such as Wazuh and its inventory system.

You can keep posted with the issues above. Hope that helps.

Best.
