### ISSUE TITLE
Possible leak in the Vulnerability Detection register stress test

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#23202]
## Description

In the analysis of the issue https://github.com/wazuh/wazuh-jenkins/issues/6422 we have found a possible leak in the Wazuh manager of the Vulnerability Detection register stress test

The change applied consists of enabling syscollector in the Wazuh agents (change not merged yet), the configuration can be found in the following comment

Fix: https://github.com/wazuh/wazuh-jenkins/pull/6459/commits/f24a392f55aadeaa2462c71e9eeadb8fe6c3129c

Results comment: https://github.com/wazuh/wazuh-jenkins/issues/6422#issuecomment-2082452724

![image](https://github.com/wazuh/wazuh/assets/14913942/799f1ec0-eb39-4826-be23-78646582484e)
![image](https://github.com/wazuh/wazuh/assets/14913942/1e155d4e-d258-42a3-b2a6-500ccf93e345)

Related: https://github.com/wazuh/wazuh/issues/22841#issuecomment-2059826516

**Comment by Dwordcito** [comment]
Given the nature of the test, it's probably related to some pending elements in the queue.

I'll try to limit it.

**Comment by Dwordcito** [comment]
This is not a memory leak, after various tests, I conclude that this occurs due to managing the columns family under the persistent queue for delayed events.

The nature of this test generates many agents with the databases without complete synchronization, and each agent with the algorithm present in RC1 causes a column family to be created for each agent to try to re-analyze that agent. Then, by having so many family columns, both FDs and memory usage have increased, since the write buffers of the database, the opening of SST files, and everything that entails begin to multiply.



The new approach proposed by the PR of this issue is to have a single-column family but manage the agent ID by prefix in the key of the elements.

**Comment by Dwordcito** [comment]
<img width="1459" alt="image" src="https://github.com/wazuh/wazuh/assets/14300208/0a19c23d-9d85-4cd6-807e-7a7580176ecb">
<img width="1464" alt="image" src="https://github.com/wazuh/wazuh/assets/14300208/15886fe5-d095-4b00-8624-bdb763272981">



5 Hours tests.
