### ISSUE TITLE
Email alerts are not sent when using `full` or `default` format

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh#23350]
## Description

This issue is created from: https://github.com/wazuh/wazuh/issues/22901

The user and I have detected that the email alerts are not received when using the `full` or `default` format in the `<email_alerts>` block configuration of the Wazuh manager.

I noticed that two types of notifications are sent:
- "Wazuh notification".
- "Wazuh <alert_level>" - <RULE_ID>.

I suppose the first one are alerts generated from the email configuration of the `global` configuration, and the second one are alerts generated from the `email_alerts` configuration.

The configuration used is the following:

```yml
<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>no</logall_json>
    <email_notification>yes</email_notification>
    <smtp_server>localhost</smtp_server>
    <email_from>me@wazuh.com</email_from>
    <email_to>me@wazuh.com</email_to>
    <email_maxperhour>12</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
    <agents_disconnection_time>10m</agents_disconnection_time>
    <agents_disconnection_alert_time>0</agents_disconnection_alert_time>
  </global>

  <email_alerts>
    <email_to>me@wazuh.com</email_to>
    <level>3</level>
    <format>default</format>
    <do_not_delay />
  </email_alerts>

  <alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>3</email_alert_level>
  </alerts>
...
```

The emails of the green block received using the `full` or `default` format. As you can see, Gmail notifies that he could not send the emails. The emails of the red block are emails using the `sms` format. This behavior is exactly the same the community user reports.
![image](https://github.com/wazuh/wazuh/assets/72193239/6bc4c86c-d42c-47cf-af1b-0802c0daba03)

## Steps to reproduce

On a Ubuntu 22.04 system:

1. Install Wazuh v4.7.3.
2. Configure the STMP server: https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/smtp-authentication.html
3. Configure the email alerts: https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html
4. Configure the email alerts using the `sms` format. Check that you receive the emails correctly.
5. Configure the email alerts using the `full` or `default` format. Check that you get Gmail warnings notifying that some emails could not be sent.

## Conclusion

It is necessary to investigate why this is happening and fix it if it is a problem.

**Comment by Kobrik1** [comment]
Hello, 
Not functional even with reproduction steps 1 and 5 only. Not functional even with unencrypted SMTP on port 25. SMS format does not need to be configured. 

![image](https://github.com/wazuh/wazuh/assets/109299110/8056e157-c894-4fd9-904a-f7357174bee2)

Email notifications generated by global settings or in rules <options>alert_by_email</options> work.
Using <email_alerts> does not.
Eliminating this problem would make the job much easier.

**Comment by sebasfalcone** [comment]
## Update
The code related to this feature  will be refactored in 5.0.0

- Does it make sense to analyze this?
- We can move this to 4.8.1 as an alternative

CC: @Dwordcito

**Comment by MiguelazoDS** [comment]
# Update 

Unable to reproduce any kind of issue using full format 

```console
Wazuh Notification.
2024 Jun 10 18:25:32

Received From: jammy->syscheck
Rule: 553 fired (level 7) -> "File deleted."
Portion of the log(s):

File '/home/vagrant/test/file' deleted
```

**Comment by MiguelazoDS** [comment]
## Update 12/06 

Due to the abovementioned limit, it is tedious to use a Gmail account. But it is possible to use the local machine and check the mails at `/var/mail/root `

```xml
    <email_from>root@jammy.localdomain</email_from>
    <email_to>root@jammy.localdomain</email_to>
```

From there we can use the mail command line tool to read the messages. 

### Working configuration 

```xml
<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>no</logall_json>
    <email_notification>yes</email_notification>
    <smtp_server>localhost</smtp_server>
    <email_from>root@jammy.localdomain</email_from>
    <email_to>root@jammy.localdomain</email_to>
    <email_maxperhour>12</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
    <agents_disconnection_time>10m</agents_disconnection_time>
    <agents_disconnection_alert_time>0</agents_disconnection_alert_time>
    <update_check>yes</update_check>
  </global>

  <email_alerts>
        <email_to>root@jammy.localdomain</email_to>
        <level>5</level>
        <!--<group>syscheck,|sshd,</group>-->
        <format>sms</format>
        <do_not_delay/>
  </email_alerts>

  <alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>5</email_alert_level>
  </alerts>
```

The outputs are the following (two messages) - Syscheck delete example

Header
```console
From root@jammy.localdomain Wed Jun 12 12:44:42 2024
Return-Path: <root@jammy.localdomain>
X-Original-To: root@jammy.localdomain
Delivered-To: root@jammy.localdomain
Received: from notify.ossec.net (localhost [127.0.0.1])
	by jammy.localdomain (Postfix) with SMTP id 7BBBD2565
	for <root@jammy.localdomain>; Wed, 12 Jun 2024 12:44:42 -0300 (-03)
To: <root@jammy.localdomain>
From: Wazuh <root@jammy.localdomain>
Date: Wed, 12 Jun 2024 12:44:42 -0300
Subject: Wazuh 7 - 553 - File deleted.
Message-Id: <20240612154442.7BBBD2565@jammy.localdomain>
X-UID: 3
Status: O
```

Body
```console
File '/home/vagrant/test/file' deleted
Mode: realtime

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Wed Jun 
```

Header
```console
From root@jammy.localdomain Wed Jun 12 12:44:52 2024
Return-Path: <root@jammy.localdomain>
X-Original-To: root@jammy.localdomain
Delivered-To: root@jammy.localdomain
Received: from notify.ossec.net (localhost [127.0.0.1])
	by jammy.localdomain (Postfix) with SMTP id 7F2F52565
	for <root@jammy.localdomain>; Wed, 12 Jun 2024 12:44:52 -0300 (-03)
To: <root@jammy.localdomain>
From: Wazuh <root@jammy.localdomain>
Date: Wed, 12 Jun 2024 12:44:52 -0300
Subject: Wazuh notification - jammy - Alert level 7
Message-Id: <20240612154452.7F2F52565@jammy.localdomain>
X-UID: 4
Status: O
```

Body
```console
Wazuh Notification.
2024 Jun 12 12:44:38

Received From: jammy->syscheck
Rule: 553 fired (level 7) -> "File deleted."
Portion of the log(s):

File '/home/vagrant/test/file' deleted
Mode: realtime

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Wed Jun 12 11:58:48 2024
 - Inode: 512081
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855




 --END OF NOTIFICATION
```

### Invalid configuration 

```xml
  <email_alerts>
        <email_to>root@jammy.localdomain</email_to>
        <level>5</level>
        <!--<group>syscheck,|sshd,</group>-->
        <format>full</format>
        <do_not_delay/>
  </email_alerts>
```

The output is the following - Syscheck delete example 

Header
```console
From root@jammy.localdomain Wed Jun 12 12:48:34 2024
Return-Path: <root@jammy.localdomain>
X-Original-To: root@jammy.localdomain
Delivered-To: root@jammy.localdomain
Received: from notify.ossec.net (localhost [127.0.0.1])
	by jammy.localdomain (Postfix) with SMTP id C0E5759;
	Wed, 12 Jun 2024 12:48:34 -0300 (-03)
To: <root@jammy.localdomain>
From: Wazuh <root@jammy.localdomain>
To: <root@jammy.localdomain>
Date: Wed, 12 Jun 2024 12:48:34 -0300
Subject: Wazuh notification - jammy - Alert level 7
Message-Id: <20240612154834.C0E5759@jammy.localdomain>
X-UID: 2
Status: O
```

Body
```console
Wazuh Notification.
2024 Jun 12 12:48:31

Received From: jammy->syscheck
Rule: 553 fired (level 7) -> "File deleted."
Portion of the log(s):

File '/home/vagrant/test/file' deleted
Mode: realtime

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Wed Jun 12 12:44:58 2024
 - Inode: 512081
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855




 --END OF NOTIFICATION
```

### Differences 

![image](https://github.com/wazuh/wazuh/assets/13010397/6e5422f3-87f1-4f38-b081-c8ae8ad81e82)

In the invalid configuration case (root 2) the line `<root@jammy.localdomain>` is missing and there's a duplicate `To`. 
What is the report we got before 

> ... There are multiple To headers. 550-5.7.1 ...

It's like the `for` line is being considered as `To` when there's no group and the format is `full`.

**Comment by MiguelazoDS** [comment]
# Update 06/13

We're not checking for NULL here 

https://github.com/wazuh/wazuh/blob/e44fab6fb7733d803153471996d2590dda24fca2/src/os_maild/sendmail.c#L421

When we use group we have a NULL value there and it seems it enters the if just by coincidence and does not execute this 

https://github.com/wazuh/wazuh/blob/e44fab6fb7733d803153471996d2590dda24fca2/src/os_maild/sendmail.c#L428

But when we use group, the value in gran_set is 2, the `i` is not incremented and the code above is executed, duplicating the To header

**Comment by MiguelazoDS** [comment]
# Conclusions 

The code was not easy to follow, and it seems there are many linked options (not sure if on purpose or not) for granular configuration that change the behavior unexpectedly. 

Below is the complete overview considering the examples above and some others. 

## Configurations and results

### Format sms, no group tag 

```xml
  <email_alerts>
    <email_to>root@jammy.localdomain</email_to>
    <level>5</level>
    <!--<group>syscheck,</group>-->
    <format>sms</format>
    <do_not_delay/>
  </email_alerts>
```

This is the working example the user mentioned 

```console
From root@jammy.localdomain  Fri Jun 14 11:15:40 2024
Return-Path: <root@jammy.localdomain>
X-Original-To: root@jammy.localdomain
Delivered-To: root@jammy.localdomain
Received: from notify.ossec.net (localhost [127.0.0.1])
	by jammy.localdomain (Postfix) with SMTP id 8E06F2509
	for <root@jammy.localdomain>; Fri, 14 Jun 2024 11:15:40 -0300 (-03)
To: <root@jammy.localdomain>
From: Wazuh <root@jammy.localdomain>
Date: Fri, 14 Jun 2024 11:15:40 -0300
Subject: Wazuh 7 - 510 - Host-based anomaly detection event (rootcheck).
Message-Id: <20240614141540.8E06F2509@jammy.localdomain>

Trojaned version of file '/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).

From root@jammy.localdomain  Fri Jun 14 11:15:40 2024
Return-Path: <root@jammy.localdomain>
X-Original-To: root@jammy.localdomain
Delivered-To: root@jammy.localdomain
Received: from notify.ossec.net (localhost [127.0.0.1])
	by jammy.localdomain (Postfix) with SMTP id 8F2C3250C
	for <root@jammy.localdomain>; Fri, 14 Jun 2024 11:15:40 -0300 (-03)
To: <root@jammy.localdomain>
From: Wazuh <root@jammy.localdomain>
Date: Fri, 14 Jun 2024 11:15:40 -0300
Subject: Wazuh 7 - 510 - Host-based anomaly detection event (rootcheck).
Message-Id: <20240614141540.8F2C3250C@jammy.localdomain>

Trojaned version of file '/usr/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generi

From root@jammy.localdomain  Fri Jun 14 11:15:40 2024
Return-Path: <root@jammy.localdomain>
X-Original-To: root@jammy.localdomain
Delivered-To: root@jammy.localdomain
Received: from notify.ossec.net (localhost [127.0.0.1])
	by jammy.localdomain (Postfix) with SMTP id 90751250E
	for <root@jammy.localdomain>; Fri, 14 Jun 2024 11:15:40 -0300 (-03)
To: <root@jammy.localdomain>
From: Wazuh <root@jammy.localdomain>
Date: Fri, 14 Jun 2024 11:15:40 -0300
Subject: Wazuh 7 - 533 - Listened ports status (netstat) changed (new port opened or closed).
Message-Id: <20240614141540.90751250E@jammy.localdomain>

ossec: output: 'netstat listening ports':
tcp 0.0.0.0:22 0.0.0.0:* /usr
tcp6 :::22 :::* /usr
tcp 0.0.0.0:25 0.0.0.0:* 1306/m
```

> [!NOTE] 
> We can see there that the body of the messages is short and not very descriptive as the user said. 
> But there are some cases where the information is more verbose and it does not seem to respect the sms format. 

The full mail file has different subject descriptions 

https://github.com/wazuh/wazuh/blob/1a5ff212358b8be693eb3331f2afe68cbd1e9252/src/os_maild/maild.h#L25-L26

[root.log](https://github.com/user-attachments/files/15841965/root.log)

### Format SMS, group set with random value

```xml
  <email_alerts>
    <email_to>root@jammy.localdomain</email_to>
    <level>5</level>
    <group>random_group,</group>
    <format>sms</format>
    <do_not_delay/>
  </email_alerts>
```

There are no SMS format messages in the `/var/mail/root` file, all messages are in full format. 

[root.log](https://github.com/user-attachments/files/15842008/root.log)

All messages show the following subject

https://github.com/wazuh/wazuh/blob/1a5ff212358b8be693eb3331f2afe68cbd1e9252/src/os_maild/maild.h#L26

The function in charge to send sms messages that wasn't called is 

https://github.com/wazuh/wazuh/blob/071a7a59b019f6b57c3abc8da0b28adb8c48cd74/src/os_maild/sendmail.c#L57

The function is called if this variable is not NULL

https://github.com/wazuh/wazuh/blob/b294a4189c3ce0a0128629378ca9f9783f04ebbc/src/os_maild/maild.c#L238

The variable is set here 

https://github.com/wazuh/wazuh/blob/02029e27d1945ca7dec870da2e98cb00ee838e9b/src/os_maild/maild.c#L398

But taking a look inside the function we see that the variable is set if this other variable is set 

https://github.com/wazuh/wazuh/blob/b294a4189c3ce0a0128629378ca9f9783f04ebbc/src/os_maild/os_maild_client.c#L306

sms_set is never set, the code in the line below is not executed, which is correct, because the regex does not match, but the behavior after a wrong group is unexpected.

https://github.com/wazuh/wazuh/blob/b294a4189c3ce0a0128629378ca9f9783f04ebbc/src/os_maild/os_maild_client.c#L255

> [!NOTE]
> For the case without group tag mentioned before, the code never reaches the `continue` and the code below is executed 
> https://github.com/wazuh/wazuh/blob/071a7a59b019f6b57c3abc8da0b28adb8c48cd74/src/os_maild/os_maild_client.c#L208

### format sms, group set with valid groups

```xml
  <email_alerts>
    <email_to>root@jammy.localdomain</email_to>
    <level>5</level>
    <group>rootcheck,|syscheck,|vulnerability-detector,</group>
    <format>full</format>
    <do_not_delay/>
  </email_alerts>
```

The behavior is similar to the first case but sometimes some notifications are missing, this is probably related to the grouping option where many notifications are grouped in a single mail. 

[root.log](https://github.com/user-attachments/files/15842563/root.log)

Adding some logs here 

https://github.com/wazuh/wazuh/blob/071a7a59b019f6b57c3abc8da0b28adb8c48cd74/src/os_maild/os_maild_client.c#L203

We get the following logs, but sometimes there are less than expected 

```console
2024/06/14 16:09:35 wazuh-maild: INFO: Check group: ossec,rootcheck,pci_dss_10.6.1,gdpr_IV_35.7.d,
2024/06/14 16:09:35 wazuh-maild: INFO: Check group: ossec,rootcheck,pci_dss_10.6.1,gdpr_IV_35.7.d,
2024/06/14 16:09:41 wazuh-maild[110930] os_maild_client.c:281 at OS_RecvMailQ(): INFO: Check group: ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2024/06/14 16:11:36 wazuh-maild[110930] os_maild_client.c:281 at OS_RecvMailQ(): INFO: Check group: vulnerability-detector,gdpr_IV_35.7.d,pci_dss_11.2.1,pci_dss_11.2.3,tsc_CC7.1,tsc_CC7.2,
```

### Format full (default), group tag missing

```xml
  <email_alerts>
    <email_to>root@jammy.localdomain</email_to>
    <level>5</level>
    <!--<group>syscheck,</group>-->
    <format>full</format>
    <do_not_delay/>
  </email_alerts>
```

This reproduces the behavior described in the issue and the one reported by the user. The messages are returned to the sender due to a duplicate `To` header 

[root.log](https://github.com/user-attachments/files/15842609/root.log)

This behavior was described here https://github.com/wazuh/wazuh/issues/23350#issuecomment-2166811685

### Format full (default), random group

```xml
  <email_alerts>
    <email_to>root@jammy.localdomain</email_to>
    <level>5</level>
    <group>random_group,</group>
    <format>full</format>
    <do_not_delay/>
  </email_alerts>
```

This, according to the analysis, "fixes" the issue because of an unexpected behavior. Described here https://github.com/wazuh/wazuh/issues/23350#issuecomment-2166811685.

## Real cases 

### Format sms, group tag missing

<details><summary>Expand</summary>

> [!NOTE]
> Although the format is SMS, the information shouldn't be incomplete.
![image](https://github.com/wazuh/wazuh/assets/13010397/4b122652-5c31-48e1-9940-650f977067ab)
![image](https://github.com/wazuh/wazuh/assets/13010397/509d9d75-d255-4b81-984f-9c15b2d6d8da)
![image](https://github.com/wazuh/wazuh/assets/13010397/fecbcb16-da48-4684-8625-ef25e596a0fd)

> [!NOTE]
> No SMS format
![image](https://github.com/wazuh/wazuh/assets/13010397/9d2e2d11-7108-4894-8944-a5d8cd440572)
![image](https://github.com/wazuh/wazuh/assets/13010397/64c96a77-2e0f-4d88-8238-25ceff8700bb)
![image](https://github.com/wazuh/wazuh/assets/13010397/53b32a92-1ed7-4b10-949c-181f4c1bf4bf)

</details>

### Format full, random group 

Couldn't reproduce the real cases due to limit exceeded. But the output is the same as the "No SMS format" shown above. 
![image](https://github.com/wazuh/wazuh/assets/13010397/54d32a13-894f-463c-bad2-8880a6ee746a)

**Comment by sebasfalcone** [comment]
## Conclusion
Given these three points:
- The effort for 5.0.0 will be to refactor code into C++
- Fixing this behavior will demand a huge effort
- There is a workaround

## Workaround
To fix the issue, we can add a `<group>` tag to the configuration:

> [!NOTE]
> Is not necessary that the group exist

- Configuration not working
```xml
  <email_alerts>
    <email_to>root@jammy.localdomain</email_to>
    <level>5</level>
    <format>full</format>
    <do_not_delay/>
  </email_alerts>
```

- Configuration working
```xml
  <email_alerts>
    <email_to>root@jammy.localdomain</email_to>
    <level>5</level>
    <group>random_group,</group>
    <format>full</format>
    <do_not_delay/>
  </email_alerts>
```

We conclude that we can close these issues
