### ISSUE TITLE
upgrade fails

### ISSUE THREAD

**Issue by BuraNk** [wazuh/wazuh#234]
when i try to upgrade v2.0 to v2.1 Im getting kibana version error.

Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [wazuh]. Expected [5.5.1]; found [5.6.3]"

any help ?

**Comment by jlruizmlg** [comment]
Hi @BuraNk you are trying to install one plugin for Kibana v.5.6.3 in one Kibana v.5.5.1, We cannot provide backwards compatibility for plugins due to the high rate of change.

In the following list you can find the compatibilities:

https://github.com/wazuh/wazuh-kibana-app

If your upgrade is to Wazuh 2.1 (and not 2.1.1) you should use the following command:

``/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-2.1.0_5.5.1.zip``

But keep in mind that this Plugin doesn't have the last upgrades/fixes but should be compatible.

**Comment by jlruizmlg** [comment]
@BuraNk after our conversation in twitter we close this issue, thanks for your feedback!!!
