### ISSUE TITLE
Parser error in the Wazuh manager RPM installer generation

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#23475]
# Description

Testing the new script to generate installers for 4.9.0 I have found an error building the Wazuh manager for RPM systems

```
+ /usr/local/bin/rpmbuild --define '_sysconfdir /etc' --define '_topdir /build_wazuh/rpmbuild' --define '_threads 4' --define '_release 1' --define '_localstatedir /var/ossec' --define '_debugenabled no' --define '_rpmfilename wazuh-manager-4.9.0-1.x86_64.rpm' --target x86_64 -ba /build_wazuh/rpmbuild/SPECS/wazuh-manager-4.9.0.spec
Building target platforms: x86_64
Building for target x86_64
error: parse error in expression:  %{_isstage} == no
error:                             ^
error: /build_wazuh/rpmbuild/SPECS/wazuh-manager-4.9.0.spec:8: bad %if condition:  %{_isstage} == no
+ return 0
```

Workflow run: https://github.com/wazuh/wazuh/actions/runs/9117098718/job/25067204232

We need to review this and fix what is necessary

## Related

- https://github.com/wazuh/wazuh-jenkins/issues/6371

**Comment by mjcr99** [comment]
Hi team,

The problem is related to an outdated version of the tag `4.9.0` for the `pkg_rpm_manager_builder_amd64` docker image which is used to build this kind of package.

After updating this tag properly via this [workflow run](https://github.com/wazuh/wazuh/actions/runs/9120081888) the packages are built successfully. This has been tested running [this job](https://github.com/wazuh/wazuh/actions/runs/9123965298). This run was triggered manually with the following command:

```
gh workflow run packages-upload-manager-images.yml -r migration/21755-wazuh-packages-redesign -f docker_image_tag=4.9.0 -f system=rpm -f source_reference=migration/21755-wazuh-packages-redesign
```

**Comment by jotacarma90** [comment]
LGTM

**Comment by MarcelKemp** [comment]
LGTM.
