### ISSUE TITLE
Add post action after a content upgrade

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#23482]
## Description
This issue aims to add a post action after a content upgrade to force a complete rescan.

This behavior should be orchestrated as a full rescan and should be run for all items in the local inventory.
If the agent is offline, items should not be indexed at that time, but should be added to the index database, so that when they come online, synchronization takes place and exposes the documents into the index.

**Comment by Rebits** [comment]
This issue seems to be affecting Vulnerability Detection E2E (https://github.com/wazuh/wazuh-qa/issues/5397#issuecomment-2124334542)

**Report**: [Test_e2e_system_289_test_vulnerability_detector.zip](https://github.com/wazuh/wazuh/files/15405140/Test_e2e_system_289_test_vulnerability_detector.zip)

Currently rerunning tests with debug mode enabled.
