### ISSUE TITLE
Syscheck in realtime doesn't detect changes in hardlinks

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#2355]
## Bug report

**OS**
_CentOS7_

**Wazuh version**
_3.8.0-3800_

**Wazuh API version**
_None_

**Install type**
_local_

**Install method**
_sources_

Bug description
----------------

When we check in realtime a folder, which has several files that are hard-links to themselves, only one of them is taken into account because the rest has the same inode. 

In these cases, we need to recheck the file for changes.

**Comment by DaveVG1** [comment]
- The only thing that we can retrieve from a hard link is the number of hard links in the system that have the same inode. 

- The only thing we can do is manage the alert that comes from another path (but it's the same file) like it came from the path that we have in our database (if we already have that inode in our database and the file that generated the alert has at least two hard links in the system). This will only work for files that we are monitoring (not hard links to files in a non-monitored directory).

- We should process the inode instead of the filename in our alerts in order to completely fix the error.

**Comment by Lopuiz** [comment]
Hi!

It solved in the following PR:
https://github.com/wazuh/wazuh/pull/4666

Regards,
Eva
