### ISSUE TITLE
Test Fedora 41 installability using packages and functionality testing

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#23661]
# Description
As part of the OSs checks issue: https://github.com/wazuh/wazuh/issues/23524 and https://github.com/wazuh/wazuh/issues/23659

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 1 | Yes| Major |

- [x] Add support for the new OS to the GitHub Actions package builder.
- [x] Smoke test that the package works, including installation, upgrade, and its related tier functionality.
- [x] Modify the evidence issue template to include the new OS.

For this, it is necessary to perform the following tests to check that everything works as expected:

- [x] Log collection
   - [x] System events (Apply for Agent Tier: 1, 2)
   - [x] Log files (Apply for Agent Tier: 1, 2, 3)
   - [x] Command execution (Apply for Agent Tier: 1, 2, 3)
- [x] FIM
   - [x] Scheduled (Apply for Agent Tier: 1, 2, 3)
   - [x] Realtime (Apply for Agent Tier: 1)
   - [x] Whodata (Apply for Agent Tier: 1)
- [x] SCA (Apply for Agent Tier: 1, 2) 
- [x] Inventory (Apply for Agent Tier: 1, 2, 3)
- [x] VD (Apply for Agent Tier: 1)
- [x] Active response (Apply for Agent Tier: 1, 2)
- [x] Remote upgrade (Apply for Agent Tier: 1)
- [x] Command monitoring (Apply for Agent Tier: 1, 2)
- [x] Wodles (Apply for Agent Tier: 1)

**Comment by lchico** [comment]
# Testing

## :green_circle: Install wazuh-agent
<details>
<summary>Install wazuh-agent</summary>

```
dnf update
rpm --import https://packages.wazuh.com/key/GPG-KEY-WAZUH
cat > /etc/yum.repos.d/wazuh.repo << EOF
[wazuh]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=EL-\$releasever - Wazuh
baseurl=https://packages.wazuh.com/4.x/yum/
protect=1
EOF
yum install wazuh-agent-4.7.0-1
```

[I followed this documentation](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html)

 <img src="https://github.com/wazuh/wazuh/assets/21695385/0fee5f77-2b08-424b-9a00-710da3b69415" alt="Install wazuh-agent">
</details>

## :green_circle: Agent and server, (enrollment and connectivity with the manager)

<details>
<summary>Dashboard</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/27530bc9-f23e-4fcc-8e0d-808b5c0ef27d" alt="Con_dash">
</details>

<details>
<summary>Agent Log</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/0502fc1f-0518-4cf3-a1ac-42a83876356e" alt="Console">
</details>

### :green_circle: FIM scheduled
<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/7b3ec564-7e68-49ff-928a-9b8b63948607">
</details>

## :green_circle: FIM Real-time
<details>
<summary>Configuration on the agent</summary>

  ```
    <frequency>4</frequency>
    <directories realtime="yes">/var/log/testrealtime</directories>
  ```
</details>

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/c727e515-888e-4e7e-90e3-a6a99558f22e">
</details>



## :green_circle: Upgrade using WPK


<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/ff5873d4-01c1-4e1c-b3bd-09c50dd8ed7a">
</details>


## :red_circle: SCA support
No official SCA policies are available ( [check](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/available-sca-policies.html) this list).

This already have an issue https://github.com/wazuh/wazuh/issues/23680.

SCA module is tested anyway, with a custom policy.

Configuration

[This usecase](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/use-cases.html#detecting-keyword-in-a-file) is used to test SCA module.

<details>
<summary>Manager log:</summary>

  ```
** Alert 1716821482.66013: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
2024 May 27 14:51:22 (de39c56e2e6f) any->sca
Rule: 19005 (level 9) -> 'SCA summary: SCA use case: Keyword check: Score less than 30% (0)'
{"type":"summary","scan_id":821113204,"name":"SCA use case: Keyword check","policy_id":"keyword_check","file":"keywordcheck.yml","description":"Guidance for checking for a keyword or phrase in files on Ubuntu endpoints.","references":"https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/index.html,https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/creating-custom-policies.html","passed":0,"failed":1,"invalid":0,"total_checks":1,"score":0,"start_time":1716821462,"end_time":1716821462,"hash":"5d28a90f4498a81461efbaf6f628a19d9778390bb5c81a393dd936181cc3d826","hash_file":"a33741eefba60ba75052477564b607cc97bdf36c773194c7ead40f30e356ec4d","force_alert":"1","force_alert":"1"}
sca.type: summary
sca.scan_id: 821113204
sca.policy: SCA use case: Keyword check
sca.description: Guidance for checking for a keyword or phrase in files on Ubuntu endpoints.
sca.policy_id: keyword_check
sca.passed: 0
sca.failed: 1
sca.invalid: 0
sca.total_checks: 1
sca.score: 0
sca.file: keywordcheck.yml

** Alert 1716821491.67304: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
2024 May 27 14:51:31 (de39c56e2e6f) any->sca
Rule: 19005 (level 9) -> 'SCA summary: SCA use case: Keyword check: Score less than 30% (0)'
{"type":"summary","scan_id":821113204,"name":"SCA use case: Keyword check","policy_id":"keyword_check","file":"keywordcheck.yml","description":"Guidance for checking for a keyword or phrase in files on Ubuntu endpoints.","references":"https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/index.html,https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/creating-custom-policies.html","passed":0,"failed":1,"invalid":0,"total_checks":1,"score":0,"start_time":1716821462,"end_time":1716821462,"hash":"5d28a90f4498a81461efbaf6f628a19d9778390bb5c81a393dd936181cc3d826","hash_file":"a33741eefba60ba75052477564b607cc97bdf36c773194c7ead40f30e356ec4d","force_alert":"1","force_alert":"1","force_alert":"1"}
sca.type: summary
sca.scan_id: 821113204
sca.policy: SCA use case: Keyword check
sca.description: Guidance for checking for a keyword or phrase in files on Ubuntu endpoints.
sca.policy_id: keyword_check
sca.passed: 0
sca.failed: 1
sca.invalid: 0
sca.total_checks: 1
sca.score: 0
sca.file: keywordcheck.yml
  ```
</details>
<details>
<summary>Agent log:</summary>

  ```
2024/05/27 14:50:37 sca[1071] wm_sca.c:152 at wm_sca_main(): INFO: Module started.
2024/05/27 14:50:37 sca[1071] wm_sca.c:191 at wm_sca_main(): INFO: Loaded policy '/var/ossec/etc/custom-sca-files/keywordcheck.yml'
2024/05/27 14:50:37 sca[1071] wm_sca.c:329 at wm_sca_start(): INFO: Starting Security Configuration Assessment scan.
2024/05/27 14:50:55 sca[1071] wm_sca.c:339 at wm_sca_start(): INFO: Security Configuration Assessment scan finished. Duration: 18 seconds.
  ```

</details>

<details>
<summary>Inventory:</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/77ef6da4-32e0-451e-ae5e-205c3a1aee34">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/f3fa436e-33d1-442a-aa70-cce1f36c65d1">
</details>


## :green_circle: Vulnerability detector
Fedora is officially not supported (see Compatibility Matrix)

Since it is possible to scan unsupported systems, this configuration was attempted:

<details>
<summary>Manager Config</summary>

```
    <!-- RedHat OS vulnerabilities -->
    <provider name="redhat">
      <enabled>yes</enabled>
      <os>5</os>
      <os>6</os>
      <os>7</os>
      <os>8</os>
      <os>9</os>
      <os allow="Fedora Linux-41">9</os>
      <update_interval>1h</update_interval>
    </provider>

```
</details>

<details>
<summary>Agent: Installing Chromium</summary>

I had to Installing Chromium-0, to be able to detect some vulnerabilities caused by certain dependencies.

```
dnf install chromium-0:124.0.6367.201-1.fc41.x86_64
```
</details>
<details>
<summary>Dashboard</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/8a9990bc-4eb8-440d-ae55-a57fcd637406">
</details>

## :green_circle: Active response

<details>
<summary>Manager configuration:</summary>

```
<ossec_config>
  <active-response>
    <disabled>no</disabled>
    <command>restart-wazuh</command>
    <location>defined-agent</location>
    <agent_id>005</agent_id>
    <level>7</level>
  </active-response>
</ossec_config>
```
</details>

<details>
<summary>Result:</summary>
<img src="https://github.com/wazuh/wazuh/assets/21695385/a45f83da-6088-414a-8330-32b5a8fdefd9">
</details>


## :green_circle: Log Capture

<details>
<summary>Agent configuration:</summary>

```
  <localfile>
    <location>/var/log/log_capture.log</location>
    <log_format>syslog</log_format>
  </localfile>
```
</details>

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/e2454cb4-dc74-4cbe-a441-489928c9f043">
</details>


## :green_circle:  Syscollector

<details>
<summary>Inventory</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/c75c01ae-c378-4bec-bd15-e0d8a6ad4bb9">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/c9691a75-2b63-4ce8-a200-bd094b993f89">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/900ca607-9fe7-4469-898b-a10b04cb3fcb">
</details>

**Comment by lchico** [comment]
# Update
While testing with Docker, I couldn't test Whodata. Therefore, I will continue searching for a Vagrant box or OVA to test it.

**Comment by lchico** [comment]
# Update
Installed Fedora 41 in a virtual box and tested whodata and command monitoring.

**Comment by MarcelKemp** [comment]
LGTM.
However, I do not close the issue, in case it is necessary to replicate the testing on the machine provided by DevOps.

**Comment by mjcr99** [comment]
## Update
**(10/06/2024)** Updated provided machine state and configuration and enrolled with the testing server.

**Comment by MarcelKemp** [comment]
Done :green_circle:
