### ISSUE TITLE
Disk_Read usage increased in stress tests for 4.7.5-rc1

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh#23695]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.5-RC1| `agentd` | Manager | Packages | centOS 7 |

### Description

During the analysis of https://github.com/wazuh/wazuh/issues/23635, it has been observed an increase in Disk_Read by `agentd` compared to 4.7.4 and 4.7.3

| 4.7.5 | 4.7.4 | 4.7.3 |
| --- | --- | ----|
|![image](https://github.com/wazuh/wazuh/assets/44633633/48523927-4628-42b2-95f2-2bedccfc0218)| ![image](https://github.com/wazuh/wazuh/assets/44633633/c0743f02-52cb-4c8f-a77c-ec19142fc67f) |  ![image](https://github.com/wazuh/wazuh/assets/44633633/63bd170e-5cb4-4bc9-a542-82724b5b62b6)|

**Comment by QU3B1M** [comment]
It also happens for `modulesd` in some cases


| 4.7.5 | 4.7.4 | 4.7.3 |
| --- | --- | ----|
|![image](https://github.com/wazuh/wazuh/assets/44633633/028fe16d-0aca-439a-b49e-2142da85b4d9)| ![image](https://github.com/wazuh/wazuh/assets/44633633/7c11552c-8aa4-401f-8b74-1aecc03104f3) |  ![image](https://github.com/wazuh/wazuh/assets/44633633/ea220ac0-f6e8-4bff-9d07-22aa0d70adb6)|

**Comment by QU3B1M** [comment]
It seems to also happens in some occasions with the Disk at the initial spikes

![image](https://github.com/wazuh/wazuh/assets/44633633/3b63a10f-410c-4bec-84f8-f5a21833a904)

**Comment by LucioDonda** [comment]
## Analysis:

* This issue compares the same type of tests, but performed over different durations:
As the graphs show: **4.7.5** was run for 1440 minutes (1 day), **4.7.4** for 3600 (2.5 days) and **4.7.3** for 360 (6 hours).
* As the test progresses, the full load in the 4.7.4 case will remain in this state for a much longer time than in the other cases.
* Perhaps in some other scenarios this time span isn't so important, but in the case of disk reading it is directly related, and in some cases linear.

### Answering each graph / comment:

1) [Agentd 4.7.5 - 4.7.4 - 4.7.3: ](https://github.com/wazuh/wazuh/issues/23695#issue-2319493396)
4.7.4 shows a different scenario than the other 2, but the comparison of peak values in disk read between 4.7.5 (40.000) and 4.7.3 (12.000) is 30% and it remains similar to his time span ratio that it's approximately 25%.

2) [Modulesd  4.7.5 - 4.7.4 - 4.7.3: ](https://github.com/wazuh/wazuh/issues/23695#issuecomment-2135051567)
4.7.3 is 0 during the whole graph, 4.7.5 (15.000) vs 4.7.4 (12.000). In this case the timespan value doesn't seems to affect the amount. But this 25% of difference doesn't seems something to worry about.

3) [Disk 4.7.5 - 4.7.4: ](https://github.com/wazuh/wazuh/issues/23695#issuecomment-2135242106)
We have had some issues while using this value for analysis due to some inconsistencies on it's calculation. There's an [issue](https://github.com/wazuh/wazuh-jenkins/issues/5656) regarding this matter.

4) [syscheckd 4.7.5 - 4.7.4: ](https://github.com/wazuh/wazuh/issues/23695#issuecomment-2135432290)
4.7.5 Monitord peak: 7.6 * 10E9 against 4.7.4: 7.8 * 10E9. Not an important difference.

5) [All daemons 4.7.5. - 4.7.4: ](https://github.com/wazuh/wazuh/issues/23695#issuecomment-2135481488)
4.7.5 MonitorD peak 7.8 * E9  4.7.5 ModulesD peak 4.8 E9
4.7.5 MonitorD peak 8.2 * E10  4.7.5 ModulesD peak 2.8 E10
In this case there's a decrease of values.

c.c. @nbertoldo @cborla

**Comment by nbertoldo** [comment]
## Analysis:

Taking into account [this analysis](https://github.com/wazuh/wazuh/issues/22601#issuecomment-2029316526) and the fact that the duration times of the tests whose [graphs are being compared](https://github.com/wazuh/wazuh/issues/23695#issue-2319493396) are not the same: 

- 4.7.5 (1.0d)
- 4.7.4 (2.5d)
- 4.7.3 (6hs) 

It seems appropriate to compare _read_ops_ final values instead of _disk_read_ considering the differences in test durations, since this metric is cumulative:

Test | Daemon | Read_Ops | Disk_Read(B) | Test Duration
-- | -- | -- | -- | --
4.7.5 - RC1 - LOGCOLLECTOR (1.0d) | wazuh-agentd | 158252 | 40960 | 1440
4.7.4 - RC2 - LOGCOLLECTOR (2.5d) | wazuh-agentd | 389063 | 14680064 | 3600
4.7.3 - RC2 - LOGCOLLECTOR (2.5d) | wazuh-agentd | 389213 | 13410304 | 3600

It can be seen the values of _4.7.3_ and _4.7.4_ are practically the same and the values of _4.7.5_ decrease in proportion to the duration of the test (-60%).
