### ISSUE TITLE
Vulnerability scanner - Missing false positives efficacy tests

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#23735]
## Description
We currently have an efficacy test that aims to prevent **false negatives** on the vulnerability scanner. This is achieved by having a list of logs that we expect from the module.

To prevent **false positives**, we have to do the opposite. We need a list of logs that we don't expect from the module.

This could be done in two ways:
- Create a new script similar to [test_efficacy_log.py](https://github.com/wazuh/wazuh/blob/467593cf8c5592d884bb92f3a95895f111f76287/src/shared_modules/indexer_connector/qa/test_efficacy_log.py)
- Add this functionality to the current test (Eg. if the log starts with !!!, we don't expect that log)

The DRI should decide the best approach

## DoD
- [x] Decide the best approach
- [x] Implement the new functionality
- [x] Add some test cases to check the new behavior
- [x] Add a comprehensive documentation

**Comment by sebasfalcone** [comment]
## Good test cases
- https://github.com/wazuh/wazuh/issues/23758

**Comment by MiguelazoDS** [comment]
# Update 

I think the easiest way to implement this is by using another set of files with another representative name (maybe unexpected_xxx.out?), there's already a function to evaluate if a line is found in the log file, it will return false if the line does not exist. Also, the function accepts a value as a timeout that is useful for these cases, it is easier to detect if a line exists that checks for a line absent, we cannot wait for every false positive case for the timeout to run out because it will delay the execution of tests.

**Comment by MiguelazoDS** [comment]
# Update 

Talking to the team we concluded that it is not easy to implement the feature with logs. The best way, although the code will suffer big changes, is to query another source to verify no false positives are detected, one option could be to query the inventory database as @pereyra-m suggested.

**Comment by sebasfalcone** [comment]
@MiguelazoDS Changes LGTM! Rebase needed for the PR
