### ISSUE TITLE
Oracle Linux 9: Analyze vulnerability discrepancies in the report between 4.7.5 and 4.8.0

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#23751]
|Platform|From|To|
|--|--|--|
|Oracle Linux 9|4.7.5-rc1|4.8.0-rc3|

We are tasked with performing a comprehensive analysis of vulnerability discrepancies reported between versions 4.7.5 and 4.8.0 in Oracle Linux 9. This entails scrutinizing each vulnerability identified in the report, cross-referencing them with official sources such as the National Vulnerability Database (NVD), Canonical, Red Hat Security Advisories (RHSA), and other trusted sources.

To accomplish this, we will follow a systematic approach:

1. **Gathering Vulnerability List:** We will compile a comprehensive list of vulnerabilities detected in versions 4.7.5 and 4.8.0. This list will be sourced from the provided report and any additional channels that may provide pertinent information. **([Link](https://docs.google.com/spreadsheets/d/1MgkKGf9K1o1xVw6k2nFa7BEjg0d9SkU2FBj9ghePcQI/edit#gid=2018470947))**

2. **Package Inventory Examination:** We will thoroughly examine the package inventory associated with the aforementioned versions to ensure accuracy in vulnerability identification and tracking.

3. **Verification with Official Sources:** Each identified vulnerability will be meticulously compared with information available from official sources such as the NVD, Canonical, RHSA, and other relevant platforms. This step is crucial in validating the existence and severity of each vulnerability.

4. **Analysis and Documentation:** We will document our findings in a structured manner, presenting a detailed analysis of each vulnerability and highlighting any variances or discrepancies encountered between the provided report and official sources.

5. **Compilation of Results:** Based on our analysis, we will populate a comprehensive table detailing the results of our comparison. This table will serve as a reference point for understanding the status of each vulnerability and any deviations observed.

6. **Recommendations:** Finally, we will provide recommendations based on our findings, including potential actions to address any identified vulnerabilities and mitigate associated risks effectively.

By adhering to this methodical approach, we aim to ensure thoroughness and accuracy in our analysis of vulnerability discrepancies between versions 4.7.5 and 4.8.0. This endeavor will contribute to enhancing the overall security posture of our system and bolstering our resilience against potential threats.

**Comment by Damian-Mangold** [comment]
## Analysis

Both scanners fail because the NVD is used instead of a security feed provided by Oracle Linux.
This problem is the same as reflected here https://github.com/wazuh/wazuh/issues/22683#issuecomment-2046002328.

## Only reported in v4.7.5
A thorough analysis was conducted on the vulnerabilities detected with version 4.7.5. We also examined whether it is appropriate that these vulnerabilities are not reported with version 4.8 when an Oracle Linux feed is available.

|package.name  |package.version|vulnerability.id|Analysis result (from v4.8 perspective)|Comment                                                                                                                                                          |
|--------------|---------------|----------------|---------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------|
|binutils      |2.35.2-42.0.1.el9|CVE-2021-46174  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|binutils      |2.35.2-42.0.1.el9|CVE-2022-47695  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|binutils      |2.35.2-42.0.1.el9|CVE-2022-47696  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|binutils      |2.35.2-42.0.1.el9|CVE-2022-45703  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|binutils      |2.35.2-42.0.1.el9|CVE-2022-48063  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|binutils      |2.35.2-42.0.1.el9|CVE-2022-48064  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|binutils      |2.35.2-42.0.1.el9|CVE-2022-48065  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|binutils      |2.35.2-42.0.1.el9|CVE-2023-25584  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|binutils      |2.35.2-42.0.1.el9|CVE-2022-47673  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|cpio          |2.13-16.el9    |CVE-2021-38185  |OK 🟢                                  |Affected if cpio is earlier than 0:2.12-11.el8                                                                                                                   |
|curl          |7.76.1-26.el9_3.2|CVE-2021-22901  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|curl          |7.76.1-26.el9_3.2|CVE-2023-28319  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|curl          |7.76.1-26.el9_3.2|CVE-2021-22922  |OK 🟢                                  |Affected if curl is earlier than 0:7.61.1-18.el8_4.1                                                                                                             |
|curl          |7.76.1-26.el9_3.2|CVE-2021-22923  |OK 🟢                                  |Affected if curl is earlier than 0:7.61.1-18.el8_4.1                                                                                                             |
|curl          |7.76.1-26.el9_3.2|CVE-2021-22925  |OK 🟢                                  |Affected if curl is earlier than 0:7.61.1-22.el8                                                                                                                 |
|curl          |7.76.1-26.el9_3.2|CVE-2021-22926  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|curl          |7.76.1-26.el9_3.2|CVE-2023-28320  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|curl          |7.76.1-26.el9_3.2|CVE-2022-27781  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|curl          |7.76.1-26.el9_3.2|CVE-2022-32205  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|curl          |7.76.1-26.el9_3.2|CVE-2021-22946  |OK 🟢                                  |Affected if curl is earlier than 0:7.61.1-18.el8_4.2                                                                                                             |
|curl          |7.76.1-26.el9_3.2|CVE-2021-22947  |OK 🟢                                  |Affected if curl is earlier than 0:7.61.1-18.el8_4.2                                                                                                             |
|curl          |7.76.1-26.el9_3.2|CVE-2021-22897  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|curl          |7.76.1-26.el9_3.2|CVE-2021-22898  |OK 🟢                                  |Affected if curl is earlier than 0:7.61.1-22.el8                                                                                                                 |
|dbus          |1:1.12.20-8.0.1.el9|CVE-2020-35512  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|gcc           |11.4.1-2.1.0.1.el9|CVE-2023-4039   |OK 🟢                                  |Affected if gcc is earlier than 0:8.5.0-18.0.5.el8                                                                                                               |
|glibc         |2.34-83.0.1.el9_3.7|CVE-2023-0687   |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|glibc         |2.34-83.0.1.el9_3.7|CVE-2022-23218  |OK 🟢                                  |Affected if glibc is earlier than 2:2.28-164.0.5.ksplice1.el8_5.3                                                                                                |
|glibc         |2.34-83.0.1.el9_3.7|CVE-2022-23219  |OK 🟢                                  |Affected if glibc is earlier than 2:2.28-164.0.5.ksplice1.el8_5.3                                                                                                |
|glibc         |2.34-83.0.1.el9_3.7|CVE-2023-5156   |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|glibc         |2.34-83.0.1.el9_3.7|CVE-2021-38604  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|glibc         |2.34-83.0.1.el9_3.7|CVE-2021-3998   |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|glibc         |2.34-83.0.1.el9_3.7|CVE-2021-43396  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|libcurl       |7.76.1-26.el9_3.2|CVE-2021-22924  |OK 🟢                                  |Affected if libcurl is earlier than 0:7.61.1-18.el8_4.1                                                                                                          |
|libcurl       |7.76.1-26.el9_3.2|CVE-2021-22945  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|libeconf      |0.4.1-3.el9_2  |CVE-2023-32181  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|ncurses       |6.2-10.20210508.el9|CVE-2021-39537  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|openssh       |8.7p1-34.el9   |CVE-2021-41617  |OK 🟢                                  |Affected if openssh is earlier than 0:7.4p1-22.0.1.el7_9                                                                                                         |
|openssh       |8.7p1-34.el9   |CVE-2021-36368  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|openssl       |1:3.0.7-24.0.1.el9|CVE-2022-3996   |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|openssl       |1:3.0.7-24.0.1.el9|CVE-2023-4807   |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|passwd        |0.80-12.el9    |CVE-2009-2360   |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|rpm           |4.16.1.3-25.el9|CVE-2021-3521   |OK 🟢                                  |Affected if rpm is earlier than 0:4.14.3-19.el8_5.2                                                                                                              |
|rpm           |4.16.1.3       |CVE-2021-3521   |OK 🟢                                  |Affected if rpm is earlier than 0:4.14.3-19.el8_5.2                                                                                                              |
|selinux       |3.5            |CVE-2020-10751  |OK 🟢                                  |Package is not in the Oracle Linux vulnerability database                                                                                                        |
|selinux-policy|38.1.23-1.0.1.el9|CVE-2020-24612  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|snappy        |1.1.8-8.el9    |CVE-2023-28115  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|snappy        |1.1.8-8.el9    |CVE-2023-41330  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|sudo          |1.9.5p2-9.el9  |CVE-2022-43995  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|xz            |5.2.5-8.el9_0  |CVE-2020-22916  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|zlib          |1.2.11-40.el9  |CVE-2023-45853  |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |
|zlib          |1.2.11-40.el9  |CVE-2023-6992   |OK 🟢                                  |CVE-ID is not in the Oracle Linux vulnerability database                                                                                                         |

## Conclusion

The Oracle Linux OS scan is inaccurate. We should add a feed for this OS.

## Action Item

In this issue we will carry out research to generate the Oracle Linux feed:
- https://github.com/wazuh/intelligence-platform/issues/1571

**Comment by Dwordcito** [comment]
LGTM.
