### ISSUE TITLE
False positive in vulnerability scan (CVE-2023-28115 and CVE-2023-41330)

### ISSUE THREAD

**Issue by gitusr-gcar** [wazuh/wazuh#23758]
|Wazuh version|
|---|
| 4.7 | 

In my installation, there is a Rocky Linux 9.4 (minimal installation) server with the "Google Snappy" compression/decompression library (see https://github.com/google/snappy) installed, version snappy-1.1.8-8.el9.x86_64, which is erroneously associated with the CVE-2023-28115 and CVE-2023-41330 vulnerabilities, which are instead related to the "Snappy PHP Libary for PDF generation" (see https://github.com/KnpLabs/snappy)

**Comment by MiguelazoDS** [comment]
Hi @gitusr-gcar, 

Thanks for your report!, we are refactoring the module to fix, among others, these kinds of issues https://github.com/wazuh/wazuh/issues/14153. 

This happens because the vendor is not being considered and it will match against any package with the same name in the NVD. 

I'll comment to my team on this case to add testing to the new implementation.
