### ISSUE TITLE
Windows Server 2022: Analyze vulnerability discrepancies in the report between 4.7.5 and 4.8.0

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#23754]
|Platform|From|To|
|--|--|--|
|Windows Server 2022|4.7.5-rc1|4.8.0-rc3|

We are tasked with performing a comprehensive analysis of vulnerability discrepancies reported between versions 4.7.5 and 4.8.0 in Windows. This entails scrutinizing each vulnerability identified in the report, cross-referencing them with official sources such as the National Vulnerability Database (NVD), Canonical, Red Hat Security Advisories (RHSA), and other trusted sources.

To accomplish this, we will follow a systematic approach:

1. **Gathering Vulnerability List:** We will compile a comprehensive list of vulnerabilities detected in versions 4.7.5 and 4.8.0. This list will be sourced from the provided report and any additional channels that may provide pertinent information. **([Link](https://docs.google.com/spreadsheets/d/109F80xBdbrMVoHReGTYWNwaEkhwj-Jl46WEFo81SF7k/edit#gid=0))**

2. **Package Inventory Examination:** We will thoroughly examine the package inventory associated with the aforementioned versions to ensure accuracy in vulnerability identification and tracking.

3. **Verification with Official Sources:** Each identified vulnerability will be meticulously compared with information available from official sources such as the NVD, Canonical, RHSA, and other relevant platforms. This step is crucial in validating the existence and severity of each vulnerability.

4. **Analysis and Documentation:** We will document our findings in a structured manner, presenting a detailed analysis of each vulnerability and highlighting any variances or discrepancies encountered between the provided report and official sources.

5. **Compilation of Results:** Based on our analysis, we will populate a comprehensive table detailing the results of our comparison. This table will serve as a reference point for understanding the status of each vulnerability and any deviations observed.

6. **Recommendations:** Finally, we will provide recommendations based on our findings, including potential actions to address any identified vulnerabilities and mitigate associated risks effectively.

By adhering to this methodical approach, we aim to ensure thoroughness and accuracy in our analysis of vulnerability discrepancies between versions 4.7.5 and 4.8.0. This endeavor will contribute to enhancing the overall security posture of our system and bolstering our resilience against potential threats.

**Comment by pereyra-m** [comment]
## Update

The analysis of the provided logs is in progress.

**Comment by pereyra-m** [comment]
## Analysis (still in progress)

The aren't vulnerable packages detected, all the vulnerabilities found are related to the OS.
The agent OS has the following CPE

```
o:microsoft:windows_server_2022:21h2::::::x64:
```


### Wazuh v4.7.5

<details><summary>Details</summary>
<p>

For the followings CVEs, the same situation and messages were found

-  CVE-2024-20681
-  CVE-2024-20680
-  CVE-2024-20674
-  CVE-2024-20666
-  CVE-2024-20664
-  CVE-2024-20663
-  CVE-2024-20662
-  CVE-2024-20661
-  CVE-2024-20660
-  CVE-2024-20658
-  CVE-2024-20657
-  CVE-2024-20655
-  CVE-2024-20654
-  CVE-2024-20653 (for this CVE, the scanner properly recommends `KB5034129` in the logs)
-  CVE-2024-20652

- :yellow_circle: CVE-2024-XXXX affects Windows Server 2022: ` Agent '009' is vulnerable to 'CVE-2024-XXXXX'. Condition: 'KB5034130 patch is not installed'` https://nvd.nist.gov/vuln/detail/CVE-2024-XXXXX. https://msrc.microsoft.com/update-guide/vulnerability/CVE-2024-XXXXX.  https://www.catalog.update.microsoft.com/Search.aspx?q=KB5034130. The mentioned KB is in fact for 23H2, it should mention  `KB5034129` instead.

</p>
</details> 

<details><summary>Details</summary>
<p>

For the followings CVEs, the same situation and messages were found

- CVE-2023-36696
- CVE-2023-36012
- CVE-2023-36011
- CVE-2023-36006
- CVE-2023-36005
- CVE-2023-36004
- CVE-2023-36003
- CVE-2023-35644
- CVE-2023-35643
- CVE-2023-35642
- CVE-2023-35641

- :yellow_circle: CVE-2023-XXXX affects Windows Server 2022: ` Agent '009' is vulnerable to 'CVE-2023-XXXXX'. Condition: 'KB5033383 patch is not installed'` https://nvd.nist.gov/vuln/detail/CVE-2023-XXXXX. https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-XXXXX.  https://www.catalog.update.microsoft.com/Search.aspx?q=KB5033383. The mentioned KB is in fact for 23H2, it should mention  `KB5033118` instead.

</p>
</details> 

### Wazuh v4.8.0

<details><summary>Details</summary>
<p>

For the followings CVEs, the same situation and messages were found

-  CVE-2024-20681
-  CVE-2024-20680
-  CVE-2024-20674
-  CVE-2024-20666
-  CVE-2024-20664
-  CVE-2024-20663
-  CVE-2024-20662
-  CVE-2024-20661
-  CVE-2024-20660
-  CVE-2024-20658
-  CVE-2024-20657
-  CVE-2024-20655
-  CVE-2024-20654
-  CVE-2024-20653
-  CVE-2024-20652

- :red_circle: CVE-2024-XXXXX doesn't affect Windows Server 2022: `No match due to default status for OS: windows_server_2022, Version: 10.0.20348.2031 while scanning for Vulnerability: CVE-2024-XXXXX`. https://nvd.nist.gov/vuln/detail/CVE-2024-XXXXX. There isn't a CPE candidate in the NVD that matches this OS, the CVE should be sanitized. The generic ` cpe:2.3:o:microsoft:windows_server_2022:-:*:*:*:*:*:*:*` is not being considered.

</p>
</details> 

<details><summary>Details</summary>
<p>

For the followings CVEs, the same situation and messages were found

- CVE-2023-36696
- CVE-2023-36012
- CVE-2023-36011
- CVE-2023-36006
- CVE-2023-36005
- CVE-2023-36004
- CVE-2023-36003
- CVE-2023-35644
- CVE-2023-35643
- CVE-2023-35642
- CVE-2023-35641

- :red_circle: CVE-2023-XXXXX doesn't affect Windows Server 2022: `No match due to default status for OS: windows_server_2022, Version: 10.0.20348.2031 while scanning for Vulnerability: CVE-2023-XXXXX`. https://nvd.nist.gov/vuln/detail/CVE-2023-XXXXX. There isn't a CPE candidate in the NVD that matches this OS, the CVE should be sanitized. The generic ` cpe:2.3:o:microsoft:windows_server_2022:-:*:*:*:*:*:*:*` is not being considered.

</p>
</details> 

## Action items

We can review the interpretation of `-` for version field in CPEs, or perform the following sanitizations:

- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2024-20681 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2024-20680 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2024-20674 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2024-20666 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2024-20664 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2024-20663 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2024-20662 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2024-20661 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2024-20660 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2024-20658 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2024-20657 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2024-20655 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2024-20654 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2024-20653 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2024-20652 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2023-36696 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2023-36012 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2023-36011 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2023-36006 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2023-36005 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2023-36004 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2023-36003 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2023-35644 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2023-35643 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2023-35642 and add Windows Server 2022 21H2 and 22H2 as candidates
- Sanitize https://nvd.nist.gov/vuln/detail/CVE-2023-35641 and add Windows Server 2022 21H2 and 22H2 as candidates

## Conclusion

The `-` in the version of the Windows Server 2022 CPE prevents the scan of these CVEs in the new vulnerability detector.
This also happens because the candidates are taken from the NVD and not from the Microsoft Update Catalog.

Review approval:


- [ ] sebasfalcone

**Comment by sebasfalcone** [comment]
## Conclusion
The NVD lacks a standard on the use of `-` and `*` in the CPEs. This degrades the scanner's efficacy 

### Example 1:
The following vulnerability https://nvd.nist.gov/vuln/detail/CVE-2023-36046 contains the CPE `cpe:2.3:o:microsoft:windows_server_2022:-:*:*:*:*:*:*:*`

If we go to the [Microsoft security update for this CVE](https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-36046), and then to the relate KB, the affected versions are:
- `Windows Server 2022, 23H2`

### Example 2
The following vulnerability https://nvd.nist.gov/vuln/detail/CVE-2024-30051 contains the CPE `cpe:2.3:o:microsoft:windows_server_2022:*:*:*:*:*:*:*:*`

If we go to the [Microsoft security update for this CVE](related.https://msrc.microsoft.com/update-guide/vulnerability/CVE-2024-3005), and then to the related KB, the affected versions are:
- `Windows Server 2022, 21H2`
- `Windows Server 2022, 22H2`

**Comment by sebasfalcone** [comment]
## Action items
Pending conversation with @Dwordcito

**Comment by Dwordcito** [comment]
LGTM after meeting. We will create an issue in intelligence data and wazuh/wazuh.
