### ISSUE TITLE
Suse 15: Analyze vulnerability discrepancies in the report between 4.7.5 and 4.8.0

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#23752]
|Platform|From|To|
|--|--|--|
|SUSE 15|4.7.5-rc1|4.8.0-rc3|

We are tasked with performing a comprehensive analysis of vulnerability discrepancies reported between versions 4.7.5 and 4.8.0 in SUSE 15. This entails scrutinizing each vulnerability identified in the report, cross-referencing them with official sources such as the National Vulnerability Database (NVD), Canonical, Red Hat Security Advisories (RHSA), and other trusted sources.

To accomplish this, we will follow a systematic approach:

1. **Gathering Vulnerability List:** We will compile a comprehensive list of vulnerabilities detected in versions 4.7.5 and 4.8.0. This list will be sourced from the provided report and any additional channels that may provide pertinent information. **([Link](https://docs.google.com/spreadsheets/d/1ZAtOj-4ptZeGHaR0vv2_s14EkB7Bfm7or8zg3myaZ9I/edit#gid=0))**

2. **Package Inventory Examination:** We will thoroughly examine the package inventory associated with the aforementioned versions to ensure accuracy in vulnerability identification and tracking.

3. **Verification with Official Sources:** Each identified vulnerability will be meticulously compared with information available from official sources such as the NVD, Canonical, RHSA, and other relevant platforms. This step is crucial in validating the existence and severity of each vulnerability.

4. **Analysis and Documentation:** We will document our findings in a structured manner, presenting a detailed analysis of each vulnerability and highlighting any variances or discrepancies encountered between the provided report and official sources.

5. **Compilation of Results:** Based on our analysis, we will populate a comprehensive table detailing the results of our comparison. This table will serve as a reference point for understanding the status of each vulnerability and any deviations observed.

6. **Recommendations:** Finally, we will provide recommendations based on our findings, including potential actions to address any identified vulnerabilities and mitigate associated risks effectively.

By adhering to this methodical approach, we aim to ensure thoroughness and accuracy in our analysis of vulnerability discrepancies between versions 4.7.5 and 4.8.0. This endeavor will contribute to enhancing the overall security posture of our system and bolstering our resilience against potential threats.

**Comment by tsarquis88** [comment]
WIP

# False positive in 4.8.0 examples

Here there are some packages that are affected according to v4.8.0 but that they aren't according to v4.7.3. These differences are suspected to be due to a false positive in v4.8.0.

## CVE-2021-3450 for openssl-1_1

The package `openssl-1_1` is not affected by CVE-2021-3450 in SLES15 SP2, as can be seen in https://www.suse.com/security/cve/CVE-2021-3450.html:

![image](https://github.com/wazuh/wazuh/assets/42682247/2dc51844-e57b-4789-ab6d-01706d2aaebe)

However, the content from CTI tells that this packages is affected from version `0` to version `0:1.1.1l-150500.15.4` for `cpe:/o:suse:sled:15:sp2`: https://cti.wazuh.com/admin/catalog/contexts/vd_1.0.0/resources/CVE-2021-3450?version=12.

Looking at the source feed (https://ftp.suse.com/pub/projects/security/oval/suse.linux.enterprise.server.15.xml.gz), we can see that the criterias tells us the same as in the HTML site:
```xml
	<criteria operator="OR">
		<criteria operator="AND">
			<criteria operator="OR">
				<criterion test_ref="oval:org.opensuse.security:tst:2009302786" comment="SUSE Enterprise Storage 7 is installed"/>
				<criterion test_ref="oval:org.opensuse.security:tst:2009669875" comment="SUSE Linux Enterprise Desktop 15 SP2 is installed"/>
				<criterion test_ref="oval:org.opensuse.security:tst:2009479728" comment="SUSE Linux Enterprise High Performance Computing 15 SP2 is installed"/>
				<criterion test_ref="oval:org.opensuse.security:tst:2009281315" comment="SUSE Linux Enterprise Module for Basesystem 15 SP2 is installed"/>
				<criterion test_ref="oval:org.opensuse.security:tst:2009303870" comment="SUSE Linux Enterprise Server 15 SP2 is installed"/>
				<criterion test_ref="oval:org.opensuse.security:tst:2009659637" comment="SUSE Linux Enterprise Server for SAP Applications 15 SP2 is installed"/>
				<criterion test_ref="oval:org.opensuse.security:tst:2009302537" comment="SUSE Manager Proxy 4.1 is installed"/>
				<criterion test_ref="oval:org.opensuse.security:tst:2009346072" comment="SUSE Manager Retail Branch Server 4.1 is installed"/>
				<criterion test_ref="oval:org.opensuse.security:tst:2009302605" comment="SUSE Manager Server 4.1 is installed"/>
			</criteria>
			<criteria operator="OR">
				<criterion test_ref="oval:org.opensuse.security:tst:2009334864" comment="libopenssl-devel is not affected"/>
				<criterion test_ref="oval:org.opensuse.security:tst:2009333942" comment="openssl is not affected"/>
				<criterion test_ref="oval:org.opensuse.security:tst:2009334872" comment="libopenssl-1_1-devel is not affected"/>
				<criterion test_ref="oval:org.opensuse.security:tst:2009334866" comment="libopenssl1_1 is not affected"/>
				<criterion test_ref="oval:org.opensuse.security:tst:2009334867" comment="libopenssl1_1-32bit is not affected"/>
				<criterion test_ref="oval:org.opensuse.security:tst:2009343863" comment="libopenssl1_1-hmac is not affected"/>
				<criterion test_ref="oval:org.opensuse.security:tst:2009343864" comment="libopenssl1_1-hmac-32bit is not affected"/>
				<criterion test_ref="oval:org.opensuse.security:tst:2009333944" comment="openssl-1_1 is not affected"/>
			</criteria>
		</criteria>
                ...
	</criteria>
```

**Comment by tsarquis88** [comment]
# False negatives in 4.7.3

## CVE-2021-23841 for openssl-1_1

From https://www.suse.com/security/cve/CVE-2021-23841.html:
![image](https://github.com/wazuh/wazuh/assets/42682247/9d03e174-f37b-4129-8551-9d5b139611b0)

The package `openssl-1_1` is affected from version `0` to version `1.1.1d-11.17.1`. Since the installed version is equal to `1.1.1d-9.9`, this package should be considered as affected.

**Comment by tsarquis88** [comment]
# False negatives in 4.8.0

<details><summary>CVE-2021-3542 for kernel-default (5.3.18-22.2)</summary>

![image](https://github.com/wazuh/wazuh/assets/42682247/b0629030-b19f-404d-89e7-79c7fd959395)

The package should be affected, since the installed version is within the range of affected packages.
However, the CVE is not published in CTI, so the scanner doesn't detect it.

</details>

**Comment by Dwordcito** [comment]
@sebasfalcone we need to check the SP in syscollector data to match the CPE platform in the scanner. 

https://github.com/wazuh/intelligence-data/blob/main/base-rules/oscpe-global.json

**Comment by tsarquis88** [comment]
# Update

More than 45 cases of discrepancies were analyzed. Most of them are due to false positives in the new Vulnerability Scanner (v4.8.0).

As it is described in the comment above (https://github.com/wazuh/wazuh/issues/23752#issuecomment-2137414585), all the false positives are due to a content problem: It seems that the CVE5 content for SUSE is mixing affected version ranges from different releases all together. 

This means, for example, that if a package is affected in `SLES 15 SP3`, but the scan is being made on an agent in `SLES 15 SP2`, the Vulnerability Scanner could make a match with the SP3 release version ranges.

This problem has to be fixed in content-side:
- https://github.com/wazuh/intelligence-platform/issues/1576

No issues were found in the Vulnerability Scanner. Although not all the cases have been investigated, given that they are more than 1000.

**Comment by Dwordcito** [comment]
@sebasfalcone please create an issue for the scanner-related part of the mentioned issue (we need set the SP in the CPE platform comparator)

**Comment by sebasfalcone** [comment]
> @sebasfalcone we need to check the SP in syscollector data to match the CPE platform in the scanner.

> https://github.com/wazuh/intelligence-data/blob/main/base-rules/oscpe-global.json

@Dwordcito Currently, we are considering the update field for the CPE: 
https://github.com/wazuh/wazuh/blob/4a074c36391bb7037ca266abe1f82a3a04bbc83b/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanContext.hpp#L198-L203

If we check the logs:
```
2024/05/29 14:03:05 wazuh-modulesd:vulnerability-scanner[54686] packageScanner.hpp:275 at platformVerify(): DEBUG: The platform is in the list based on CPE comparison for Package: vim, Version: 8.0.1568-5.3.1, CVE: CVE-2009-0316, Content platform CPE: cpe:/o:suse:sles:15 OS CPE: cpe:/o:suse:sles:15:sp2
```
We see that the OS CPE has the update field (sp2)

---

The problem is that the platforms in the content are too wide:
```           "cpe:/o:suse:sles:15",
              "cpe:/o:suse:sles:15:sp1",
              "cpe:/o:suse:sles:15:sp2",
              "cpe:/o:suse:sles:15:sp3",
              "cpe:/o:suse:sles:15:sp4",
              "cpe:/o:suse:sles:15:sp5",
```

This will be solved with:
- https://github.com/wazuh/intelligence-platform/issues/1576

**Comment by Dwordcito** [comment]
LGTM.
