### ISSUE TITLE
Ubuntu 24: Analyze vulnerability discrepancies in the report between 4.7.5 and 4.8.0

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#23755]
|Platform|From|To|
|--|--|--|
|Ubuntu 24|4.7.5-rc1|4.8.0-rc3|

We are tasked with performing a comprehensive analysis of vulnerability discrepancies reported between versions 4.7.5 and 4.8.0 in Ubuntu. This entails scrutinizing each vulnerability identified in the report, cross-referencing them with official sources such as the National Vulnerability Database (NVD), Canonical, Red Hat Security Advisories (RHSA), and other trusted sources.

To accomplish this, we will follow a systematic approach:

1. **Gathering Vulnerability List:** We will compile a comprehensive list of vulnerabilities detected in versions 4.7.5 and 4.8.0. This list will be sourced from the provided report and any additional channels that may provide pertinent information. **([Link](https://docs.google.com/spreadsheets/d/1eAXyPQmePSq02_qTq5J9nIm3QIVUHYQ8vZv3fwFw8rc/edit#gid=0))**

2. **Package Inventory Examination:** We will thoroughly examine the package inventory associated with the aforementioned versions to ensure accuracy in vulnerability identification and tracking.

3. **Verification with Official Sources:** Each identified vulnerability will be meticulously compared with information available from official sources such as the NVD, Canonical, RHSA, and other relevant platforms. This step is crucial in validating the existence and severity of each vulnerability.

4. **Analysis and Documentation:** We will document our findings in a structured manner, presenting a detailed analysis of each vulnerability and highlighting any variances or discrepancies encountered between the provided report and official sources.

5. **Compilation of Results:** Based on our analysis, we will populate a comprehensive table detailing the results of our comparison. This table will serve as a reference point for understanding the status of each vulnerability and any deviations observed.

6. **Recommendations:** Finally, we will provide recommendations based on our findings, including potential actions to address any identified vulnerabilities and mitigate associated risks effectively.

By adhering to this methodical approach, we aim to ensure thoroughness and accuracy in our analysis of vulnerability discrepancies between versions 4.7.5 and 4.8.0. This endeavor will contribute to enhancing the overall security posture of our system and bolstering our resilience against potential threats.

**Comment by Damian-Mangold** [comment]
## Only reported in v4.8.0

|package.name  |package.version|vulnerability.id|Analysis result|Comment                                                                                                                                                          |
|--------------|---------------|----------------|---------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------|
|cryptography  |41.0.7         |CVE-2024-0727   |OK 🟢          |Match against pypi feed. Match found, the package 'cryptography', is vulnerable to 'CVE-2024-0727'. Current version: '41.0.7' (less than '42.0.2' or equal to '')|
|xz-utils      |5.6.1+really5.4.5-1|CVE-2020-22916  |OK 🟢          |Match found, the package 'xz-utils' is vulnerable to 'CVE-2020-22916' due to default status                                                                      |
|Jinja2        |3.1.2          |CVE-2024-22195  |OK 🟢          |Match against pypi feed. Match found, the package 'jinja2', is vulnerable to 'CVE-2024-22195'. Current version: '3.1.2' (less than '3.1.3' or equal to '').      |
|patch         |2.7.6-7build3  |CVE-2018-6952   |OK 🟢          |Match found, the package 'patch' is vulnerable to 'CVE-2018-6952' due to default status.                                                                         |
|patch         |2.7.6-7build3  |CVE-2021-45261  |OK 🟢          |Match found, the package 'patch' is vulnerable to 'CVE-2021-45261' due to default status.                                                                        |
|dbus          |1.14.10-4ubuntu4|CVE-2023-34969  |OK 🟢          |Match found, the package 'dbus' is vulnerable to 'CVE-2023-34969' due to default status.                                                                         |
|binutils      |2.42-4ubuntu2  |CVE-2018-20657  |OK 🟢          |Match found, the package 'binutils' is vulnerable to 'CVE-2018-20657' due to default status.                                                                     |
|binutils      |2.42-4ubuntu2  |CVE-2017-13716  |OK 🟢          |Match found, the package 'binutils' is vulnerable to 'CVE-2017-13716' due to default status.                                                                     |
|snapd         |2.62+24.04build1|CVE-2022-28948  |OK 🟢          |Match found, the package 'snapd' is vulnerable to 'CVE-2022-28948' due to default status.                                                                        |
|git           |1:2.43.0-1ubuntu7|CVE-2018-1000021|OK 🟢          |Match found, the package 'git' is vulnerable to 'CVE-2018-1000021' due to default status.                                                                        |
|wget          |1.21.4-1ubuntu4|CVE-2021-31879  |OK 🟢          |Match found, the package 'wget' is vulnerable to 'CVE-2021-31879' due to default status.                                                                         |
|linux-firmware|20240318.git3b128b60-0ubuntu2|CVE-2023-4969   |OK 🟢          |Match found, the package 'linux-firmware' is vulnerable to 'CVE-2023-4969' due to default status.                                                                |
|dmidecode     |3.5-3build1    |CVE-2023-30630  |OK 🟢          |Match found, the package 'dmidecode' is vulnerable to 'CVE-2023-30630' due to default status.                                                                    |

**Comment by Damian-Mangold** [comment]
## Only reported in v4.7.5  ---> WIP

|package.name  |package.version|vulnerability.id|Analysis result|Comment                                                                                                                                                          |
|--------------|---------------|----------------|---------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------|
|apport        |2.28.1-0ubuntu2|CVE-2022-28653  |False negative for content 🟡|The CVE-ID does not exist in the NVD, but Canonical feed reports that it is vulnerable                                                                           |
|apport-core-dump-handler|2.28.1-0ubuntu2|CVE-2022-28653  |no veo el paquete, falla la expancion?|                                                                                                                                                                 |
|bsdutils      |2.39.3-9ubuntu6|CVE-2013-0157   |OK 🟢          |Canonical feed indicates that it is not vulnerable                                                                                                               |
|bsdutils      |2.39.3-9ubuntu6|CVE-2016-5011   |OK 🟢          |Canonical feed indicates that it is not vulnerable                                                                                                               |
|bsdutils      |2.39.3-9ubuntu6|CVE-2014-9114   |OK 🟢          |Canonical feed indicates that it is not vulnerable                                                                                                               |
|bsdutils      |2.39.3-9ubuntu6|CVE-2024-28085  |OK 🟢          |Canonical feed indicates that it is not vulnerable                                                                                                               |
|busybox-initramfs|1:1.36.1-6ubuntu3|CVE-2023-42363  |no veo el paquete, falla la expancion?|                                                                                                                                                                 |
|busybox-initramfs|1:1.36.1-6ubuntu3|CVE-2023-42364  |no veo el paquete, falla la expancion?|                                                                                                                                                                 |
|busybox-initramfs|1:1.36.1-6ubuntu3|CVE-2023-42365  |no veo el paquete, falla la expancion?|                                                                                                                                                                 |
|busybox-initramfs|1:1.36.1-6ubuntu3|CVE-2023-42366  |no veo el paquete, falla la expancion?|                                                                                                                                                                 |
|busybox-static|1:1.36.1-6ubuntu3|CVE-2023-42363  |no veo el paquete, falla la expancion?|                                                                                                                                                                 |
|busybox-static|1:1.36.1-6ubuntu3|CVE-2023-42364  |no veo el paquete, falla la expancion?|                                                                                                                                                                 |
|busybox-static|1:1.36.1-6ubuntu3|CVE-2023-42365  |no veo el paquete, falla la expancion?|                                                                                                                                                                 |
|busybox-static|1:1.36.1-6ubuntu3|CVE-2023-42366  |no veo el paquete, falla la expancion?|                                                                                                                                                                 |
|gir1.2-glib-2.0|2.80.0-6ubuntu1|CVE-2024-34397  |False negative for content 🟡|The CVE-ID is AWAITING ANALYSIS in the NVD, but Canonical feed reports that it is vulnerable "lessThan": "2.80.0-6ubuntu3.1"                                     |
|gir1.2-packagekitglib-1.0|1.2.8-2build3  |CVE-2022-0987   |no veo el paquete, falla la expancion?|                                                                                                                                                                 |
|git           |1:2.43.0-1ubuntu7|CVE-2024-32002  |esperar update de contenido|                                                                                                                                                                 |
|git           |1:2.43.0-1ubuntu7|CVE-2024-32004  |esperar update de contenido|                                                                                                                                                                 |
|git           |1:2.43.0-1ubuntu7|CVE-2024-32465  |esperar update de contenido|                                                                                                                                                                 |
|git           |1:2.43.0-1ubuntu7|CVE-2024-32020  |esperar update de contenido|                                                                                                                                                                 |
|git           |1:2.43.0-1ubuntu7|CVE-2024-32021  |esperar update de contenido|                                                                                                                                                                 |
|git-man       |1:2.43.0-1ubuntu7|CVE-2024-32002  |esperar update de contenido|                                                                                                                                                                 |
|git-man       |1:2.43.0-1ubuntu7|CVE-2024-32004  |esperar update de contenido|                                                                                                                                                                 |
|git-man       |1:2.43.0-1ubuntu7|CVE-2024-32465  |esperar update de contenido|                                                                                                                                                                 |
|git-man       |1:2.43.0-1ubuntu7|CVE-2024-32020  |esperar update de contenido|                                                                                                                                                                 |
|git-man       |1:2.43.0-1ubuntu7|CVE-2024-32021  |esperar update de contenido|                                                                                                                                                                 |
|libglib2.0-0t64|2.80.0-6ubuntu1|CVE-2024-34397  |False negative for content 🟡|The CVE-ID is AWAITING ANALYSIS in the NVD, but Canonical feed reports that it is vulnerable "lessThan": "2.80.0-6ubuntu3.1"                                     |
|libglib2.0-bin|2.80.0-6ubuntu1|CVE-2024-34397  |False negative for content 🟡|The CVE-ID is AWAITING ANALYSIS in the NVD, but Canonical feed reports that it is vulnerable "lessThan": "2.80.0-6ubuntu3.1"                                     |
|libglib2.0-data|2.80.0-6ubuntu1|CVE-2024-34397  |False negative for content 🟡|The CVE-ID is AWAITING ANALYSIS in the NVD, but Canonical feed reports that it is vulnerable "lessThan": "2.80.0-6ubuntu3.1"                                     |
|libnghttp2-14 |1.59.0-1build4 |CVE-2024-28182  |False negative for content 🟡|The CVE-ID is AWAITING ANALYSIS in the NVD, but Canonical feed reports that it is vulnerable "lessThan": "1.59.0-1ubuntu0.1"                                     |
|libpackagekit-glib2-18|1.2.8-2build3  |CVE-2022-0987   |no veo el paquete, falla la expancion?|                                                                                                                                                                 |
|libssl3t64    |3.0.13-0ubuntu3|CVE-2024-4741   |no veo el paquete, falla la expancion?|The CVE-ID does not exist in the NVD                                                                                                                             |
|libtss2-esys-3.0.2-0t64|4.0.1-7.1ubuntu5|CVE-2024-29040  |no veo el paquete, falla la expancion?|The CVE-ID does not exist in the NVD                                                                                                                             |
|libtss2-mu-4.0.1-0t64|4.0.1-7.1ubuntu5|CVE-2024-29040  |no veo el paquete, falla la expancion?|The CVE-ID does not exist in the NVD                                                                                                                             |
|libtss2-sys1t64|4.0.1-7.1ubuntu5|CVE-2024-29040  |no veo el paquete, falla la expancion?|The CVE-ID does not exist in the NVD                                                                                                                             |
|libtss2-tcti-cmd0t64|4.0.1-7.1ubuntu5|CVE-2024-29040  |no veo el paquete, falla la expancion?|The CVE-ID does not exist in the NVD                                                                                                                             |
|libtss2-tcti-mssim0t64|4.0.1-7.1ubuntu5|CVE-2024-29040  |no veo el paquete, falla la expancion?|The CVE-ID does not exist in the NVD                                                                                                                             |
|libtss2-tcti-swtpm0t64|4.0.1-7.1ubuntu5|CVE-2024-29040  |no veo el paquete, falla la expancion?|The CVE-ID does not exist in the NVD                                                                                                                             |
|openssl       |3.0.13-0ubuntu3|CVE-2024-4741   |False negative for content 🟡|The CVE-ID does not exist in the NVD, but Canonical feed reports that it is vulnerable                                                                           |
|packagekit    |1.2.8-2build3  |CVE-2022-0987   |OK 🟢          |Canonical feed indicates that it is not vulnerable                                                                                                               |
|packagekit-tools|1.2.8-2build3  |CVE-2022-0987   |no veo el paquete, falla la expancion?|                                                                                                                                                                 |
|python3-apport|2.28.1-0ubuntu2|CVE-2022-28653  |False negative for content 🟡|The CVE-ID does not exist in the NVD, but Canonical feed reports that it is vulnerable                                                                           |
|python3-idna  |3.6-2          |CVE-2024-3651   |OK 🟢          |Canonical feed indicates that it is not vulnerable                                                                                                               |
|python3-problem-report|2.28.1-0ubuntu2|CVE-2022-28653  |no veo el paquete, falla la expancion?|                                                                                                                                                                 |

**Comment by eslerm** [comment]
Hello o/

In https://github.com/wazuh/wazuh/issues/23750 it is mentioned that NVD is being used to determine the vulnerability state of a package based on upstream's version numbering.

As you show, this will not work for distributions which backport security patches to older versions or require version numbers like `5.6.1+really5.4.5-1`. And some CVEs do not list package version numbers.

When the Ubuntu Security team works with a CVE we update https://git.launchpad.net/ubuntu-cve-tracker/ to show the state of Ubuntu in all supported releases. This data generates OVAL, which wazuh may want to parse: https://ubuntu.com/security/oval If there is interested, please let me know how I can help.

**Comment by eslerm** [comment]
You can also use ubuntu-cve-tracker to map a vulnerability to a package. CVE-2024-29040 is the source package `tpm2-tss`.
https://git.launchpad.net/ubuntu-cve-tracker/tree/active/CVE-2024-29040

https://git.launchpad.net/ubuntu-cve-tracker/tree/ignored/not-for-us.txt are CVEs for software which are not part of the Ubuntu archive.

It looks like the Canonical CNA needs to publish CVE-2022-28653.

**Comment by Damian-Mangold** [comment]
Hello @eslerm !!

Thank you very much for the information you provided; it is incredibly useful.

Given your expertise with the Canonical feed, I would like to ask you a question. Do you know why the feed delivered by the [API](https://ubuntu.com/security/api/docs#/) differs from the content in the OVAL? Is the OVAL more comprehensive than the API feed?

**Comment by Damian-Mangold** [comment]
Upon concluding the analysis, the following conclusions were reached:

- All detections in version 4.8 are accurate.
- Upon reviewing the detections in version 4.7.5 through the perspective of version 4.8, three issues were identified:
  1. Some CVEs are absent in the NVD feed, resulting in the lack of CVE-ID content generation. This problem is addressed in issue https://github.com/wazuh/intelligence-platform/issues/1578.
  2. Certain CVEs are still under analysis in the NVD, which also results in the lack of CVE-ID content generation. This problem is addressed in issue https://github.com/wazuh/intelligence-platform/issues/1573.
  3. The feed downloaded from the API lacks comprehensive information on vulnerable packages. This problem is addressed in issue https://github.com/wazuh/intelligence-platform/issues/1577.

**Comment by eslerm** [comment]
I am not all that familiar with the API. It appears to be owned by the Web Team who generates that part of the site based on the ubuntu-cve-tracker. For affected state, this might be enough. The recent 80 requests per hour rate limit may affect you: https://github.com/canonical/ubuntu.com/pull/13880

OVAL is a widely used standard for communicating this kind of information. It has fairly wide adoption. Since it is required by the US Government for SCAP compliance checks, many distros distribute it. So, an OVAL parser can be used for multiple distros.

The OVAL format is being deprecated across the industry. OSV and OpenVEX are likely replacements, but Ubuntu does not publish these feeds yet. I can ask about timelines. Likely, we will support both OVAL and new formats for a time.

Also, I have a hunch that [CISA's ADP](https://github.com/cisagov/vulnrichment) will eventually replace NVD (who has [largely stopped re-scoring CVEs](https://github.com/jgamblin/NVDAnalysisStatus/blob/main/NVDVulnStatus.ipynb)). And NVD gets their data (and adds to) [cvelistV5](https://github.com/CVEProject/cvelistV5). As a "Authorized Data Provider", CISA will add metadata directly to cvelistV5.

**Comment by Damian-Mangold** [comment]
Hello @eslerm Thank you once again for the valuable information. What you mentioned about CISA is especially interesting and I will study it further.

**Comment by Dwordcito** [comment]
LGTM, good analysis.

**Comment by eslerm** [comment]
On the 29th, NVD announced they secured funding for re-scoring CVEs again. https://www.nist.gov/itl/nvd

Please reach out if you need anything.
