### ISSUE TITLE
Windows 11: Analyze vulnerability discrepancies in the report between 4.7.5 and 4.8.0

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#23753]
|Platform|From|To|
|--|--|--|
|Windows 11|4.7.5-rc1|4.8.0-rc3|

We are tasked with performing a comprehensive analysis of vulnerability discrepancies reported between versions 4.7.5 and 4.8.0 in Windows. This entails scrutinizing each vulnerability identified in the report, cross-referencing them with official sources such as the National Vulnerability Database (NVD), Canonical, Red Hat Security Advisories (RHSA), and other trusted sources.

To accomplish this, we will follow a systematic approach:

1. **Gathering Vulnerability List:** We will compile a comprehensive list of vulnerabilities detected in versions 4.7.5 and 4.8.0. This list will be sourced from the provided report and any additional channels that may provide pertinent information. **([Link](https://docs.google.com/spreadsheets/d/1uYbd8-RvkYBjdyhLzEiqVXiRVBvrbvwavQZq0l1wuko/edit#gid=0))**

2. **Package Inventory Examination:** We will thoroughly examine the package inventory associated with the aforementioned versions to ensure accuracy in vulnerability identification and tracking.

3. **Verification with Official Sources:** Each identified vulnerability will be meticulously compared with information available from official sources such as the NVD, Canonical, RHSA, and other relevant platforms. This step is crucial in validating the existence and severity of each vulnerability.

4. **Analysis and Documentation:** We will document our findings in a structured manner, presenting a detailed analysis of each vulnerability and highlighting any variances or discrepancies encountered between the provided report and official sources.

5. **Compilation of Results:** Based on our analysis, we will populate a comprehensive table detailing the results of our comparison. This table will serve as a reference point for understanding the status of each vulnerability and any deviations observed.

6. **Recommendations:** Finally, we will provide recommendations based on our findings, including potential actions to address any identified vulnerabilities and mitigate associated risks effectively.

By adhering to this methodical approach, we aim to ensure thoroughness and accuracy in our analysis of vulnerability discrepancies between versions 4.7.5 and 4.8.0. This endeavor will contribute to enhancing the overall security posture of our system and bolstering our resilience against potential threats.

**Comment by pereyra-m** [comment]
## Update

I've started the analysis.

**Comment by pereyra-m** [comment]
# Analysis

There are too many vulnerabilities to be analyzed one by one, only those elements present in one system and not in the other one will be considered.

##  Firefox package

The package presents a different number of detected vulnerabilities

<details><summary>Details</summary>
<p>

```
{
        "scan": {
          "id": 0,
          "time": "2024-05-28T15:26:06+00:00"
        },
        "name": "Mozilla Firefox (x64 en-US)",
        "install_time": "2023-02-08T20:00:45+00:00",
        "vendor": "Mozilla",
        "description": " ",
        "source": " ",
        "architecture": "x86_64",
        "section": " ",
        "size": 0,
        "priority": " ",
        "location": "C:\\Program Files\\Mozilla Firefox",
        "version": "109.0.1",
        "format": "win",
        "agent_id": "013"
      }
```


</p>
</details> 

- v4.7.5: 155 vulnerabilities reported
- v4.8.0: 175 vulnerabilities reported 

These are the 20 vulnerabilities reported by the new scanner that aren't present in the legacy one

### The version range isn't available

<details><summary>Details</summary>
<p>

https://nvd.nist.gov/vuln/detail/CVE-2016-7153
https://nvd.nist.gov/vuln/detail/CVE-2016-7152
https://nvd.nist.gov/vuln/detail/CVE-2012-4930
https://nvd.nist.gov/vuln/detail/CVE-2012-4929
https://nvd.nist.gov/vuln/detail/CVE-2011-0064
https://nvd.nist.gov/vuln/detail/CVE-2009-4630
https://nvd.nist.gov/vuln/detail/CVE-2009-4130
https://nvd.nist.gov/vuln/detail/CVE-2009-4129
https://nvd.nist.gov/vuln/detail/CVE-2007-6715
https://nvd.nist.gov/vuln/detail/CVE-2007-3827
https://nvd.nist.gov/vuln/detail/CVE-2007-2176
https://nvd.nist.gov/vuln/detail/CVE-2007-1970
https://nvd.nist.gov/vuln/detail/CVE-2003-1492

</p>
</details> 

There is a generic CPE 
```
  cpe:2.3:a:mozilla:firefox:*:*:*:*:*:*:*:*
```

That produces the following log 
```
Match found, the package 'firefox' is vulnerable to 'CVE-2016-7153' due to default status. - Agent 'agent2' (ID: '012', Version: 'v4.8.0').
```

It was already reported here at https://github.com/wazuh/wazuh/pull/22687#issuecomment-2035926442 but the intelligence-data issues were closed because there isn't an available version range for these old vulnerabilities. There isn't an action item for this.

### Configuration nodes from NVD not properly parsed

Some other CVEs aren't properly parsed

https://nvd.nist.gov/vuln/detail/CVE-2014-6492
https://nvd.nist.gov/vuln/detail/CVE-2009-4102
https://nvd.nist.gov/vuln/detail/CVE-2008-2399


### CVEs to sanitize

Finally, some of them must be sanitized because they contain errors. There is a defined range, but an extra generic CPE is found. Some of them could be "running on" nodes

https://nvd.nist.gov/vuln/detail/CVE-2009-2469
https://nvd.nist.gov/vuln/detail/CVE-2008-4059
https://nvd.nist.gov/vuln/detail/CVE-2007-4013
https://nvd.nist.gov/vuln/detail/CVE-2007-0896

##  Pip package

The vulnerability detector at v4.8.0 detects the following vulnerabilities, when the legacy module doesn't
 
<details><summary>Details</summary>
<p>

CVE-2021-3572
CVE-2023-5752

</p>
</details> 

This seems correct, no action is required.

## OS

The agent has the following OS CPE
```
o:microsoft:windows_11_22h2:10.0.22621.1105::::::x64:
```

- v4.7.5: 535 vulnerabilities reported
- v4.8.0: 450 vulnerabilities reported 

The legacy module detects the 85 vulnerabilities that the refactored module doesn't.

The specific CVE

CVE-2023-36025

Contains a `-` in the version field of the OS CPE, so the candidate isn't considered. But the MSRC page shows available security updates for that OS. The situation is similar to https://github.com/wazuh/wazuh/issues/23754#issuecomment-2138582910

For the rest of the CVEs, they aren't considered vulnerable because the version isn't affected by the range by the NVD

<details><summary>Details</summary>
<p>

CVE-2023-29325
CVE-2023-29324
CVE-2023-28283
CVE-2023-28251
CVE-2023-24949
CVE-2023-24946
CVE-2023-24945
CVE-2023-24944
CVE-2023-24943
CVE-2023-24942
CVE-2023-24940
CVE-2023-24939
CVE-2023-24932
CVE-2023-24913
CVE-2023-24911
CVE-2023-24910
CVE-2023-24909
CVE-2023-24908
CVE-2023-24907
CVE-2023-24906
CVE-2023-24905
CVE-2023-24903
CVE-2023-24902
CVE-2023-24901
CVE-2023-24900
CVE-2023-24899
CVE-2023-24880
CVE-2023-24876
CVE-2023-24872
CVE-2023-24871
CVE-2023-24870
CVE-2023-24869
CVE-2023-24868
CVE-2023-24867
CVE-2023-24866
CVE-2023-24865
CVE-2023-24864
CVE-2023-24863
CVE-2023-24862
CVE-2023-24861
CVE-2023-24859
CVE-2023-24858
CVE-2023-24857
CVE-2023-24856
CVE-2023-23423
CVE-2023-23422
CVE-2023-23421
CVE-2023-23420
CVE-2023-23419
CVE-2023-23418
CVE-2023-23417
CVE-2023-23416
CVE-2023-23415
CVE-2023-23414
CVE-2023-23413
CVE-2023-23411
CVE-2023-23410
CVE-2023-23409
CVE-2023-23407
CVE-2023-23406
CVE-2023-23405
CVE-2023-23404
CVE-2023-23403
CVE-2023-23402
CVE-2023-23401
CVE-2023-23394
CVE-2023-23393
CVE-2023-23392
CVE-2023-23388
CVE-2023-23385
CVE-2023-21708

</p>
</details> 

However the build number in the NVD differs from the one reported by Microsoft, and this is another reason for not using the NVD as the main candidate list for OS vulnerabilities.

# Conclusion

The issues for the CVEs to sanitize of Firefox must be created.
Also, the issues for the configuration nodes that aren't properly parsed must be created. 

For the OS vulnerabilities discrepancy, we might consider using the MSRC as a candidate source instead of the NVD because the build versions of the affected systems differ and are causing false negatives.
