### ISSUE TITLE
Vulnerability Scanner - Research RPM version matcher because of possible bug

### ISSUE THREAD

**Issue by matias-braida** [wazuh/wazuh#23818]
## Description
While reviewing https://github.com/wazuh/wazuh/issues/23744, it was found that an RPM version comparison done by the manager differs from the one executed using the command "rpmdev-vercmp".

The version string of the real package is: `3.9.18-1.el9_3`
The version string of the lessThan condition is: `0:3.9.18-1.el9_3.1`

The rpmdev-vercmp command result is:
```
bash-5.2# rpmdev-vercmp 3.9.18-1.el9_3 0:3.9.18-1.el9_3.1
3.9.18-1.el9_3 < 0:3.9.18-1.el9_3.1 
```

While manager logs say the following:
```
2024/05/29 14:02:58 wazuh-modulesd:vulnerability-scanner[54686] packageScanner.hpp:275 at platformVerify(): DEBUG: The platform is in the list based on CPE comparison for Package: python-unversioned-command, Version: 3.9.18-1.el9_3, CVE: CVE-2023-27043, Content platform CPE: cpe:/o:redhat:enterprise_linux:9 OS CPE: cpe:/o:redhat:enterprise_linux:9
2024/05/29 14:02:58 wazuh-modulesd:vulnerability-scanner[54686] packageScanner.hpp:392 at versionMatch(): DEBUG: Scanning package - 'python-unversioned-command' (Installed Version: 3.9.18-1.el9_3, Security Vulnerability: CVE-2023-27043). Identified vulnerability: Version: 0. Required Version Threshold: 0:3.9.18-1.el9_3.1. Required Version Threshold (or Equal): .
2024/05/29 14:02:58 wazuh-modulesd:vulnerability-scanner[54686] packageScanner.hpp:541 at versionMatch(): DEBUG: No match due to default status for Package: python-unversioned-command, Version: 3.9.18-1.el9_3 while scanning for Vulnerability: CVE-2023-27043
```

This behavior was detected on the following packages:
| CVE | Package Name | Package Version | Condition Version |
| -- | -- | -- | -- |
|CVE-2023-27043 | python-unversioned-command | 3.9.18-1.el9_3 |0:3.9.18-1.el9_3.1 |
|CVE-2023-27043 | python3 | 3.9.18-1.el9_3 |0:3.9.18-1.el9_3.1 |
|CVE-2023-27043 | python3-libs | 3.9.18-1.el9_3 |0:3.9.18-1.el9_3.1 |

Other examples of this possible bug are the following cases:
| CVE | Package Name | Package Version | Condition Version |
| -- | -- | -- | -- |
|CVE-2023-4001|grub2-common|1:2.06-70.el9_3.1|1:2.06-70.el9_3.2|
|CVE-2023-43804|python3-urllib3|1.26.5-3.el9|0:1.26.5-3.el9_3.1|
|CVE-2023-44487|libnghttp2|1.43.0-5.el9|0:1.43.0-5.el9_2.1|

In all these cases the comparison made with rpmdev-vercmp tool is that the package version is less than the condition version.

We should investigate and fix a possible bug if it corresponds.

## DoD
- [x] Investigate if this situation is a bug
- [x] Fix the possible bug
- [x] Update the tests
  - [x] Efficacy
  - [x] UTs

**Comment by Dwordcito** [comment]
False positive, blocker.

**Comment by GabrielEValenzuela** [comment]
# Report Analysis: RPM Version Compare Algorithm Mismatch

## Introduction

This report aims to analyze an observed issue with the RPM (Red Hat Package Manager) version compare algorithm. The problem was identified during an implementation review, where it was noted that versions with different lengths were being compared inaccurately. Specifically, the version with the longest length was consistently considered the newer version, which is incorrect.

## Problem Description

### Observed Behavior

The current RPM version compare algorithm exhibits a mismatch when comparing versions of different lengths. The algorithm defaults to considering the version with the greater length as the newer one, regardless of the actual version content. This behavior leads to erroneous comparisons and can result in improper package version selection and dependency resolution.

### Example

Consider the following version comparison:
- Version A: `1.10`
- Version B: `1.2.3`

According to the current algorithm, Version B (`1.2.3`) would be deemed newer than Version A (`1.10`) solely due to its greater length, despite `1.10` being the more recent version in semantic terms.

## Root Cause Analysis

### Algorithmic Flaw

The flaw lies in the version comparison logic, which does not correctly parse and compare the numerical components of the versions. Instead, it relies on the length of the version strings, leading to the observed mismatch.

### Comparison Logic

The standard RPM version compare algorithm follows these steps:
1. Separate in `epoch:version-release`
2. Compare each corresponding component sequentially.
3. If components differ, determine the newer version based on numerical and alphabetical order.
4. If lengths differ, the longer version is incorrectly deemed newer.

## Proposed Customization

To address this issue, a customized RPM version compare algorithm should be implemented. This custom algorithm will focus on accurately comparing the content of the versions, rather than their lengths.
The customized algorithm should be integrated into the RPM package management version comparison, replacing the existing version comparison logic. 

## Conclusion

We can resolve the observed mismatch issue by customizing the RPM version compare algorithm to accurately compare the content of version strings, but we are going to be misaligned with the production algorithm used by RPM.

**Comment by sebasfalcone** [comment]
@GabrielEValenzuela Please perform the corresponding changes to align with the original RPM algorithm
