### ISSUE TITLE
send massage too big ,Is this situation normal?

### ISSUE THREAD

**Issue by begize** [wazuh/wazuh#2383]
hi:

i see my FW logs, find my offices dmz wazuh client send to internal wazuh server transaction logs, every client sends over 50MB in 180 seconds ,Is this situation normal?
![image](https://user-images.githubusercontent.com/26645073/51009522-6de6f200-158b-11e9-84aa-8d2c62bbd52d.png)

**Comment by Zenidd** [comment]
Hi @begize,

This behavior doesn't seem normal. Is it still happening? Could you update us on your current state about this problem? 



<br></br>
Best regards,

Juan Pablo Sáez

**Comment by Zenidd** [comment]
Hi @begize,

- As I said above, 50MB for each agent in 180 secs seems too high.
- Baseline network traffic between an agent and the manager is around 36 MB in 24hours.

I'm closing this ticket due to inactivity. If you keep experiencing network usage issues please, do not hesitate to reopen this issue or open a new one.

Best regards, JP Sáez
