### ISSUE TITLE
Support new OSs - Windows Server 2025 - Update allocator module

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23887]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/23838 | https://github.com/wazuh/wazuh/issues/23858 |

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
| Yes | 1 | No | Major|

# Plan

- **DevOps**
- [ ] **Agent**: deploy an All In One (in our featured OS, probably Amazon Linux) and allocate an accessible machine with the new OS to test the agent. This is the first step for everything else.
- [ ] **Major/New family**: Add support in the allocator.
- [ ] **Major/New family**: Adapt Puppet.
- [ ] **Major/New family**: Adapt Ansible.
- [ ] Update AMI, OVA, or Docker images if needed.

**Comment by c-bordon** [comment]
## Update report

Currently, I cannot create a new AMI with Windows server 2025, I have tried to build it from a locally built Virtual Machine, and when trying to convert it to AMI, I receive an error in AWS.

```console
cbordon@cbordon-MS-7C88:~/Documents$ aws ec2 describe-import-image-tasks --import-task-ids import-ami-01e91f0fc3a8f3015
{
    "ImportImageTasks": [
        {
            "Description": "Windows server 2025",
            "ImportTaskId": "import-ami-01e91f0fc3a8f3015",
            "Platform": "Windows",
            "SnapshotDetails": [
                {
                    "DiskImageSize": 12136505344.0,
                    "Format": "VMDK",
                    "Status": "completed",
                    "Url": "s3://warehouse.wazuh.com/tmp/Windows_server_2025.ova",
                    "UserBucket": {
                        "S3Bucket": "warehouse.wazuh.com",
                        "S3Key": "tmp/Windows_server_2025.ova"
                    }
                }
            ],
            "Status": "deleted",
            "StatusMessage": "ClientError: Unsupported Windows Version: Windows Server 2025 Standard Evaluation",
            "Tags": []
        }
    ]
}
```

I tried to upgrade from Windows server 2022 (AMI offered by AWS) to Windows server 2025 and the upgrade worked correctly, but after the reboot, it asks for manual configurations, which cannot be done because we do not have access to do so. So this complicates the upgrade.

![Screenshot_20240618_151746](https://github.com/wazuh/wazuh/assets/64099752/574815fa-1015-4873-b7c1-0edfb2d7634c)

**Comment by c-bordon** [comment]
I'm trying to create a vagrantbox for this OS version

**Comment by c-bordon** [comment]
I was doing some additional tests, and the iso I got only boots in VMware, the ideal would be to get it in VirtualBox since it is the virtualizer we use for allocator, although this is not possible at the moment.


The options we have to provision this system are exhausted

**Comment by davidjiglesias** [comment]
We changed the proceeding and we will revisit this once Windows Server 2025 is officially launched
