### ISSUE TITLE
Release 4.8.0 - RC 4 - Vulnerability Detection performance test

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#23982]
## Tests information

|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release stage issue**     |             https://github.com/wazuh/wazuh/issues/23949                   |
| **Main Vulnerability Detection tests issue**     |        https://github.com/wazuh/wazuh/issues/23966                      |
| **Version**                          |                   4.8.0                         |
| **Release stage**              |                   RC 4                       |
| **Tag**                              |          https://github.com/wazuh/wazuh-qa/tree/v4.8.0-rc4                                |
| **Previous Vulnerability performance tests issue**      |       https://github.com/wazuh/wazuh/issues/23683                      |

## Description

The objective is to conduct performance tests to analyze the vulnerability detection module across varying environment loads: high, medium, and low. This comparative analysis will provide a comprehensive understanding of the current status of the vulnerability detection module and will help identify any unexpected behavior.

### Methodology

Utilizing the CLUSTER-Workload_benchmarks_metrics pipeline to execute specified test cases automatically. Results will be manually analyzed and shared with the development team for validation adjustments.

### Test Cases

| Case | Description | Workers | Indexers |  Agents | EPS  | Frequency | Number of Vulnerable Packages | Time |
| --- | --- | --- | --- | --- | --- | --- | --- |--- |
| Medium Activity | Simulate a medium-sized environment with moderate activity | 2 | 2 | 50 | 10 | 60  | 100 | 3h |
| High Activity | Simulate a large-scale environment with significant activity | 2 | 2 | 200 | 50  | 60 | 100 | 3h |
| Very High Activity | Simulate a large-scale environment with significant activity | 25 | 3 | 50000 | 1 | 60 | 100 | 1h |

**Considerations**

- `KIBANA_API_REQUESTS` should be enabled
- `EXTRA_LOAD_API_REQUESTS` should be enabled
- Due to the current operation of the simulator and how it does the EPS distribution with the frequency, we can expect the actual EPS to be about half, so it is necessary to set twice as much.

### Conclusion :red_circle: 

**New issues**
- https://github.com/wazuh/wazuh-qa/issues/5479
- https://github.com/wazuh/wazuh-jenkins/issues/6585

**Known issues**
- https://github.com/wazuh/wazuh/issues/8480
- https://github.com/wazuh/wazuh-indexer/issues/71
- https://github.com/wazuh/wazuh-packages/issues/2519
- https://github.com/wazuh/wazuh-packages/issues/1582
- https://github.com/wazuh/wazuh-packages/issues/1511
- https://github.com/wazuh/wazuh-packages/issues/1511

**Comment by Rebits** [comment]
## Builds

**Medium Activity**: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/549/

**Comment by Rebits** [comment]
# Medium Activity :red_circle:

**Build**: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/549/
**Report**: [artifacts.zip](https://github.com/user-attachments/files/15786765/artifacts.7.zip)

***

## Logs :red_circle:
 
### Summary


<details>

<summary> Master :yellow_circle:  </summary>

- Worker node is started before the correct indexer configuration is set. Expected
```
2024/06/10 09:12:21 indexer-connector: WARNING: No username and password found in the keystore, using default values.
2024/06/10 09:12:21 indexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-172-31-15-105.ec2.internal', retrying until
```

- No username and password were set in the keystore. Expected
```
2024/06/10 09:20:56 indexer-connector: WARNING: No username and password found in the keystore, using default values.
```

- Reported in https://github.com/wazuh/wazuh/issues/8480. Known issue.
```
2024/06/10 09:26:15 wazuh-remoted: ERROR: (1320): Agent '000' not found.
```

</details>


<details>

<summary> Worker 1 :yellow_circle:  </summary>

- Worker node is started before the correct indexer configuration is set. Expected
```
2024/06/10 09:12:22 indexer-connector: WARNING: No username and password found in the keystore, using default values.
2024/06/10 09:12:22 indexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-172-31-15-109.ec2.internal', retrying until the
```

- No username and password were set in the keystore. Expected
```
2024/06/10 09:20:56 indexer-connector: WARNING: No username and password found in the keystore, using default values.
```

- Syscollector decoder queue is full. Expected in performance tests
```
2024/06/10 11:29:59 wazuh-analysisd: WARNING: Syscollector decoder queue is full.
```

</details>


<details>

<summary> Worker2 :yellow_circle:  </summary>

- Worker node is started before the correct indexer configuration is set. Expected

```
2024/06/10 09:12:23 indexer-connector: WARNING: No username and password found in the keystore, using default values.
2024/06/10 09:12:23 indexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-172-31-8-158.ec2.internal', retrying until the connection is successful.
```

- No username and password were set in the keystore. Expected
```
2024/06/10 09:20:56 indexer-connector: WARNING: No username and password found in the keystore, using default values.
```

- Syscollector decoder queue is full. Expected in performance tests

```
2024/06/10 10:54:46 wazuh-analysisd: WARNING: Syscollector decoder queue is full.
```


</details>


<details>

<summary> Indexer 1 :red_circle: </summary>

- Errors produced before security plugins are initialized. Expected.

```
[2024-06-10T09:08:36,678][ERROR][o.o.s.c.ConfigurationLoaderSecurity7] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_0] Failure no such index [.opendistro_security] retrieving configuration for [INTERNALUSERS, ACTIONGROUPS, CONFIG, ROLES, ROLESMAPPING, TENANTS, NODESDN, WHITELIST, ALLOWLIST, AUDIT] (index=.opendistro_security)
```

We can see that finally the opendistro_security was correctly processed
``` 
for [INTERNALUSERS, ACTIONGROUPS, CONFIG, ROLES, ROLESMAPPING, TENANTS, NODESDN, WHITELIST, ALLOWLIST, AUDIT] (index=.opendistro_security)
[2024-06-10T09:11:35,126][INFO ][o.o.p.PluginsService     ] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_0] PluginService:onIndexModule index:[.opendistro_security/grCkzMfNTpOm_tckTcNA2Q]
...
[2024-06-10T09:11:35,263][INFO ][o.o.i.r.RecoverySourceHandler] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_0] [.opendistro_security][0][recover to CLUSTER-Workload_benchmarks_metrics_B549_indexer_1] finalizing recovery took [4.7ms]
```

- Reported in https://github.com/wazuh/wazuh-packages/issues/1511

```
[2024-06-10T09:08:32,496][ERROR][o.o.s.a.s.SinkProvider   ] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_0] Default endpoint could not be created, auditlog will not work properly.
```


- Reported in https://github.com/wazuh/wazuh-indexer/issues/71
```
[2024-06-10T09:08:35,725][WARN ][o.o.p.c.s.h.ConfigOverridesClusterSettingHandler] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_0] Config override setting update called with empty string. Ignoring.
```



- `opensearch.yml` permissions are not the expected, probably related to indexer provision in performance test environment. Issue to be opened.
```
[2024-06-10T09:08:27,787][WARN ][o.o.s.OpenSearchSecurityPlugin] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_0] File /etc/wazuh-indexer/opensearch.yml has insecure file permissions (should be 0600)
```

- Reported in https://github.com/wazuh/wazuh-packages/issues/2519
```
[2024-06-10T09:08:34,272][WARN ][o.o.g.DanglingIndicesState] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_0] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
```


- Reported in https://github.com/wazuh/wazuh-packages/issues/1582

```
[2024-06-10T09:08:35,725][WARN ][o.o.p.c.s.h.ConfigOverridesClusterSettingHandler] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_0] Config override setting update called with empty string. Ignoring.
```



- Reported in https://github.com/wazuh/wazuh-packages/issues/1511
```
[2024-06-10T09:08:32,447][WARN ][o.o.s.c.Salt             ] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_0] If you plan to use field masking pls configure compliance salt e1ukloTsQlOgPquJ to be a random string of 16 chars length identical on all nodes
```


- Reported in https://github.com/wazuh/wazuh-packages/issues/1511
```
[2024-06-10T09:08:33,291][WARN ][o.o.s.p.SQLPlugin        ] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_0] Master key is a required config for using create and update datasource APIs. Please set plugins.query.datasources.encryption.masterkey config in opensearch.yml in all the cluster nodes. More details can be found here: https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/admin/datasources.rst#master-key-config-for-encrypting-credential-information
```




</details>



<details>

<summary> Indexer 2 :red_circle:  </summary>


- Errors produced before security plugins are initialized. Expected.

```
[2024-06-10T09:08:36,751][ERROR][o.o.s.c.ConfigurationLoaderSecurity7] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_1] Failure no such index [.opendistro_security] retrieving configuration for [INTERNALUSERS, ACTIONGROUPS, CONFIG, ROLES, ROLESMAPPING, TENANTS, NODESDN, WHITELIST, ALLOWLIST, AUDIT] (index=.opendistro_security)
```


- Reported in https://github.com/wazuh/wazuh-packages/issues/1511
```
[2024-06-10T09:08:32,490][ERROR][o.o.s.a.s.SinkProvider   ] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_1] Default endpoint could not be created, auditlog will not work properly.
{"type": "server", "timestamp": "2023-10-10T13:18:39,514Z", "level": "WARN", "component": "o.o.s.a.r.AuditMessageRouter", "cluster.name": "wazuh-cluster", "node.name": "node-1", "message": "No default storage available, audit log may not work properly. Please check configuration." }
```


- `opensearch.yml` permissions are not the expected, probably related to indexer provision in performance test environment. Issue to be opened.

```
[2024-06-10T09:08:27,898][WARN ][o.o.s.OpenSearchSecurityPlugin] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_1] File /etc/wazuh-indexer/opensearch.yml has insecure file permissions (should be 0600)
```



- Reported in https://github.com/wazuh/wazuh-packages/issues/1511

```
[2024-06-10T09:08:32,456][WARN ][o.o.s.c.Salt             ] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_1] If you plan to use field masking pls configure compliance salt e1ukloTsQlOgPquJ to be a random string of 16 chars length identical on all nodes
```


- Reported in https://github.com/wazuh/wazuh-packages/issues/1511

```
[2024-06-10T09:08:32,491][WARN ][o.o.s.a.r.AuditMessageRouter] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_1] No default storage available, audit log may not work properly. Please check configuration.
```


- Reported in https://github.com/wazuh/wazuh-packages/issues/1511

```
[2024-06-10T09:08:33,179][WARN ][o.o.s.p.SQLPlugin        ] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_1] Master key is a required config for using create and update datasource APIs. Please set plugins.query.datasources.encryption.masterkey config in opensearch.yml in all the cluster nodes. More details can be found here: https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/admin/datasources.rst#master-key-config-for-encrypting-credential-information
```

- Reported in https://github.com/wazuh/wazuh-packages/issues/2519

```
[2024-06-10T09:08:34,408][WARN ][o.o.g.DanglingIndicesState] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_1] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
```

- Reported in https://github.com/wazuh/wazuh-packages/issues/1582

```
[2024-06-10T09:08:35,716][WARN ][o.o.p.c.s.h.ConfigOverridesClusterSettingHandler] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_1] Config override setting update called with empty string. Ignoring.
```

- Researched in https://github.com/wazuh/wazuh-packages/issues/2402. Related to Opensearch
```
[2024-06-10T09:08:36,355][WARN ][o.o.s.SecurityAnalyticsPlugin] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_1] Failed to initialize LogType config index and builtin log types
```

- Related to https://github.com/opensearch-project/OpenSearch/issues/9061
```
[2024-06-10T09:08:36,448][WARN ][o.o.o.i.ObservabilityIndex] [CLUSTER-Workload_benchmarks_metrics_B549_indexer_1] message: index [.opensearch-observability/8uidJ0hdTy66gEinOunMDQ] already exists
```

</details>


<details>

<summary> Dashboard :green_circle:  </summary>


- Connection error detected. Only appears one time in all the test times. Related with initial setup of the environment. Marking as expected 
```
{"date":"2024-06-10T09:17:46.154Z","level":"error","location":"monitoring:getApiInfo","message":"connect ECONNREFUSED 127.0.0.1:55000"}
```

</details>

<details>

<summary> Tools :green_circle: </summary>

**API simulator**:

- Expected in performance test
```
2024/06/10 12:32:59 ERROR: [Kibana] Unhandled exception: HTTPSConnectionPool(host='172.31.15.105', port=55000): Max retries exceeded with url: /agents/summary/status (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4355e7b190>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

</details>

***

## Metrics :green_circle: 

### Summary

- In worker's nodes, the Wazuh-db and modulesd processes exhibit high CPU usage during the first two hours of operation. After this initial period, CPU usage decreases but begins to show periodic peaks on the graphs. The CPU usage of Wazuh-db is directly correlated with the activity of the modulesd daemon.


### Master :green_circle: 

No abnormal behavior was detected

<details>

<summary> Metrics </summary>

**Binaries**

![CPU](https://github.com/wazuh/wazuh/assets/11089305/e0cba2db-9bd8-47d7-9d1c-d3e7c1f23c0c)
![Disk_Read](https://github.com/wazuh/wazuh/assets/11089305/f82b37a6-01b7-4335-8fba-58a0dd5eb5eb)
![Disk_Read_Speed](https://github.com/wazuh/wazuh/assets/11089305/211a84c8-3be9-42a7-b06d-8ec5e3205202)
![Disk_Write_Speed](https://github.com/wazuh/wazuh/assets/11089305/b2fcaaa5-b6fe-4e5c-9dd3-3284f75ec4c3)
![Disk_Written](https://github.com/wazuh/wazuh/assets/11089305/0d6aeae2-2a9b-4e7d-a6b2-85ac7a208ba3)
![FD](https://github.com/wazuh/wazuh/assets/11089305/2cf24ea2-7709-41ed-884e-eb9435caf7a8)
![PSS](https://github.com/wazuh/wazuh/assets/11089305/033d1c8a-25a9-4b42-99ab-c4de723a766f)
![Read_Ops](https://github.com/wazuh/wazuh/assets/11089305/8273373b-984e-4268-b6b1-a02890637f74)
![RSS](https://github.com/wazuh/wazuh/assets/11089305/7a59fab7-fb5d-40a5-85c3-4ddeab0ff88e)
![SWAP](https://github.com/wazuh/wazuh/assets/11089305/04f54e32-a866-4418-800e-745d06a025d2)
![USS](https://github.com/wazuh/wazuh/assets/11089305/f94e303c-66c3-41b1-8fa8-270a5a5fd2ff)
![VMS](https://github.com/wazuh/wazuh/assets/11089305/257d449e-293c-4446-b4ff-fa4d89c8ec5a)
![Write_Ops](https://github.com/wazuh/wazuh/assets/11089305/72d048cf-bf62-48d4-8126-4e8b7343fd0c)


***

**Analysisd**

![wazuh-analysis_api_stats_alerts_info](https://github.com/wazuh/wazuh/assets/11089305/743c34a0-f3f7-4908-bda9-92e5131a13f4)
![wazuh-analysis_api_stats_decoded_events](https://github.com/wazuh/wazuh/assets/11089305/f52a32a1-fafc-4c1d-8124-7fa9edb93ed4)
![wazuh-analysis_api_stats_dropped_events](https://github.com/wazuh/wazuh/assets/11089305/595364e2-8ff6-47a5-9ef8-dd7e67053895)
![wazuh-analysis_api_stats_events_decoded_per_second](https://github.com/wazuh/wazuh/assets/11089305/ccff1750-186e-46e1-bfbf-36fbd12e6fa3)


</details>


### Worker 1 :red_circle:


The Wazuh-db and modulesd processes exhibit high CPU usage during the first two hours of operation. After this initial period, CPU usage decreases but begins to show periodic peaks on the graphs. The CPU usage of Wazuh-db is directly correlated with the activity of the modulesd daemon.


<details>

<summary> Metrics </summary>

**Binaries**

![CPU](https://github.com/wazuh/wazuh/assets/11089305/1863dd88-df17-438e-ae69-9bff3cbfc67d)
![Disk_Read](https://github.com/wazuh/wazuh/assets/11089305/1b785dd5-ec34-4040-8d5e-f16e161ac703)
![Disk_Read_Speed](https://github.com/wazuh/wazuh/assets/11089305/37000e3d-e978-4117-9707-62b18820505c)
![Disk_Write_Speed](https://github.com/wazuh/wazuh/assets/11089305/fec235e1-3d17-4fb9-936b-96c2f2daa7b0)
![Disk_Written](https://github.com/wazuh/wazuh/assets/11089305/796ef905-46e6-47e5-bc60-f70cec96af8a)
![FD](https://github.com/wazuh/wazuh/assets/11089305/8fb3602d-5287-477d-a4cd-a7111eaf2cb7)
![PSS](https://github.com/wazuh/wazuh/assets/11089305/05eeca7f-ba24-4a02-8e64-3a4b2c29315b)
![Read_Ops](https://github.com/wazuh/wazuh/assets/11089305/d5a3cf09-2a17-4c11-9ad6-4570e3e2a124)
![RSS](https://github.com/wazuh/wazuh/assets/11089305/5aeea6a9-2f13-4f38-a5be-d61bc5f19ec3)
![SWAP](https://github.com/wazuh/wazuh/assets/11089305/4c6b72c9-8eea-4cff-9735-8c045f075d2c)
![USS](https://github.com/wazuh/wazuh/assets/11089305/34650c82-ff8a-4d07-bce9-22117002e0cc)
![VMS](https://github.com/wazuh/wazuh/assets/11089305/8c8b9d34-aef5-4011-a49d-372b63650dd4)
![Write_Ops](https://github.com/wazuh/wazuh/assets/11089305/ea484959-e4ff-4f26-9f0d-57f61f4ddf39)

***

**Statistics**

![wazuh-analysis_api_stats_alerts_info](https://github.com/wazuh/wazuh/assets/11089305/28b1e382-a3fe-46b4-a924-7ec9d416ebac)
![wazuh-analysis_api_stats_decoded_events](https://github.com/wazuh/wazuh/assets/11089305/78fdbb9d-7426-422a-864a-9eec48b9f436)
![wazuh-analysis_api_stats_dropped_events](https://github.com/wazuh/wazuh/assets/11089305/512fd0bc-3f63-46cd-91e4-62ed16d2309c)
![wazuh-analysis_api_stats_events_decoded_per_second](https://github.com/wazuh/wazuh/assets/11089305/413c35e4-222f-4e70-8e9b-55ae8a2627cc)



</details>




### Worker 2 :red_circle:

The Wazuh-db and modulesd processes exhibit high CPU usage during the first hour. After this initial period, CPU usage decreases but starts to show peaks in the graphs. The CPU usage of Wazuh-db is directly linked to the modulesd daemon.



<details>

<summary> Metrics </summary>

**Binaries**

![CPU](https://github.com/wazuh/wazuh/assets/11089305/7388a7c9-2a8f-4c1e-b732-8e0420789b1a)
![Disk_Read](https://github.com/wazuh/wazuh/assets/11089305/e31b3a0c-622d-4162-be65-fbb77ffbeab2)
![Disk_Read_Speed](https://github.com/wazuh/wazuh/assets/11089305/90c4ffb7-c314-4f54-9997-5436a3b1b04d)
![Disk_Write_Speed](https://github.com/wazuh/wazuh/assets/11089305/4c6c806c-5176-4a3f-9535-d72f9e19d19b)
![Disk_Written](https://github.com/wazuh/wazuh/assets/11089305/8ffa5197-10de-415b-b47c-72ca73ad1d06)
![FD](https://github.com/wazuh/wazuh/assets/11089305/85e20263-1eab-44f4-8c00-454f5299021b)
![PSS](https://github.com/wazuh/wazuh/assets/11089305/c6b3a584-8f3d-41f8-a7b8-6f3b9e35fab9)
![Read_Ops](https://github.com/wazuh/wazuh/assets/11089305/0dfcc01a-51f6-44d9-97cd-8fb9d1b71917)
![RSS](https://github.com/wazuh/wazuh/assets/11089305/85a062fc-fda2-4d38-914a-854013e70ab8)
![SWAP](https://github.com/wazuh/wazuh/assets/11089305/c4476024-e433-447c-a0f3-616b4e8717b4)
![USS](https://github.com/wazuh/wazuh/assets/11089305/4c791efa-6082-4d82-a73c-c44bd6e2d940)
![VMS](https://github.com/wazuh/wazuh/assets/11089305/e92935df-0468-4a8d-b53c-94019fa22253)
![Write_Ops](https://github.com/wazuh/wazuh/assets/11089305/f90a7d8f-e701-45cb-a4cf-69256d94ef72)


**Analysisd**

![wazuh-analysis_api_stats_alerts_info](https://github.com/wazuh/wazuh/assets/11089305/941a5c9a-fc1b-404f-928a-0bf1d132f27b)
![wazuh-analysis_api_stats_decoded_events](https://github.com/wazuh/wazuh/assets/11089305/c13a2429-9d2a-47b6-96fd-da644b4d9ab3)
![wazuh-analysis_api_stats_dropped_events](https://github.com/wazuh/wazuh/assets/11089305/349199de-f4c4-4893-a07f-917f5481ec87)
![wazuh-analysis_api_stats_events_decoded_per_second](https://github.com/wazuh/wazuh/assets/11089305/d84c7b98-c541-4a69-af50-6201042089fa)



</details>

### Indexer 1 :green_circle:

No abnormal behavior detected

<details>

<summary> Metrics </summary>


![CPU](https://github.com/wazuh/wazuh/assets/11089305/d4754cdd-8627-4e7a-87fb-99cff8633ef2)
![Disk_Read](https://github.com/wazuh/wazuh/assets/11089305/1faa6a54-a2fc-4dbc-b39a-f420743c22a4)
![Disk_Read_Speed](https://github.com/wazuh/wazuh/assets/11089305/18209cc3-34ce-45de-a33e-6148b6b3970f)
![Disk_Write_Speed](https://github.com/wazuh/wazuh/assets/11089305/e2ba5deb-00e5-49f3-993c-f4e6b8751eb3)
![Disk_Written](https://github.com/wazuh/wazuh/assets/11089305/f5a34e91-b64d-4cc2-adae-817a9307f99c)
![FD](https://github.com/wazuh/wazuh/assets/11089305/3ea987f5-5e62-4caf-b826-569a17c9401a)
![PSS](https://github.com/wazuh/wazuh/assets/11089305/9c01da8d-9bd0-4b36-ada0-b85e76c28841)
![Read_Ops](https://github.com/wazuh/wazuh/assets/11089305/ce75842f-a82f-46e5-a2fe-56c11bd12172)
![RSS](https://github.com/wazuh/wazuh/assets/11089305/c3fe2f19-70b5-4401-8a2a-812706d8255a)
![SWAP](https://github.com/wazuh/wazuh/assets/11089305/25390f8f-afc0-4549-9d9e-2b9f8c50fa12)
![USS](https://github.com/wazuh/wazuh/assets/11089305/55788a17-7625-42c7-90d2-f585ea684f00)
![VMS](https://github.com/wazuh/wazuh/assets/11089305/307d1bab-1897-453a-a6be-8fa19c1897f6)
![Write_Ops](https://github.com/wazuh/wazuh/assets/11089305/625f5378-a60d-4d00-a61d-e33c69a03661)



</details>

### Indexer 2 :green_circle:

No abnormal behavior detected

<details>

<summary> Metrics </summary>

![CPU](https://github.com/wazuh/wazuh/assets/11089305/0f756b52-64ff-41d1-a18c-2fafb855d4d5)
![Disk_Read](https://github.com/wazuh/wazuh/assets/11089305/0840805b-3b0f-40a4-b1ae-fd2dcce5143d)
![Disk_Read_Speed](https://github.com/wazuh/wazuh/assets/11089305/5c69ace6-6ed3-45a8-9fb2-f2edc2c9edd3)
![Disk_Write_Speed](https://github.com/wazuh/wazuh/assets/11089305/9008eba1-f209-49b0-ad05-8ffe24fa6221)
![Disk_Written](https://github.com/wazuh/wazuh/assets/11089305/883e7b9c-cecf-4c82-8c82-837bc09263e1)
![FD](https://github.com/wazuh/wazuh/assets/11089305/caaf31d8-3ab1-42bd-97c1-ae703b7ecd55)
![PSS](https://github.com/wazuh/wazuh/assets/11089305/bdff1ff0-7420-4e72-9dab-e13c75a44b32)
![Read_Ops](https://github.com/wazuh/wazuh/assets/11089305/03b20b6a-6243-4daa-bb04-042438943763)
![RSS](https://github.com/wazuh/wazuh/assets/11089305/f666a168-f8d3-40c9-bf37-6e54383e722d)
![SWAP](https://github.com/wazuh/wazuh/assets/11089305/4c5184a9-4d5b-40e9-84ed-26b0ce8f8292)
![USS](https://github.com/wazuh/wazuh/assets/11089305/ec62f796-e77d-403d-b816-3b6ac754ee2c)
![VMS](https://github.com/wazuh/wazuh/assets/11089305/cb837809-5939-48d3-9b69-f63e31cea437)
![Write_Ops](https://github.com/wazuh/wazuh/assets/11089305/749e80fb-3890-4552-acbe-6ef1707bc758)


</details>


### Dashboard

No graphics were generated. Solved in `v4.8.1`

***

## Global Statistics :green_circle:

### Vulnerabilities State :green_circle:


![total_vulnerabilities](https://github.com/wazuh/wazuh/assets/11089305/3b46e808-ae2b-4bdb-b97f-048287cb133e)


We observe a sinusoidal pattern in the plot, indicating that the Vulnerability Detection module is correctly processing the insertion and deletion of vulnerable packages through simulated agents. However, this sinusoidal graph is not perfect because the module cannot generate all vulnerabilities in real-time, resulting in some irregularities.

Implementing various testing methods to determine if the final number of vulnerabilities aligns with expectations at specific points during the test could be highly beneficial.


***

### Alerts :green_circle:


![combined_and_new_total_alerts](https://github.com/wazuh/wazuh/assets/11089305/bfd4ef8a-f731-43a4-9bef-1a21878752eb)

We anticipate that the alerts generated by both the workers and the manager should correspond with the indexed alert values. Nonetheless, there appears to be a discrepancy:

Due to the high activity levels, some variance between the written alerts and indexed alerts is expected. However, it would be advantageous to incorporate testing methods to gradually mitigate this, thereby stabilizing the environment over time.

**Comment by Rebits** [comment]
# High Activity :large_blue_circle: (@santipadilla )

**Comment by Rebits** [comment]
# Very High Activity :large_blue_circle:

**Comment by rafabailon** [comment]
### LGTM

**Comment by Rebits** [comment]
## Explanation of High API Activity in Wazuh 4.8.0

![RSS](https://github.com/wazuh/wazuh/assets/11089305/f5399273-d6fb-4ddf-a379-b8c102d93925)


Based on feedback from @Selutario, high usage of RAM by the Wazuh API is expected. In addition, no changes were made to the API in version 4.8.0.

### Understanding the Behavior:

**Single Process Handling:**
- Only one process handles the logic behind the API endpoints.
- If this logic is time-consuming, new requests are queued and processed as the process becomes available.
- In large environments, with many agents registering and becoming active, the API must handle an increasing number of actions for these agents.

**Timeout and Queuing Issue:**
- Even if an endpoint times out after 10 seconds, the logic remains queued and executes anyway.
- This results in unnecessary processing since the client has already received a timeout message and stopped waiting.
- Consequently, the API queues more requests for slow tasks, leading to increased RAM usage as tasks accumulate.

These factors explain the high activity observed in the API and the resulting graphics.
