### ISSUE TITLE
wazuh-dashboard shows "Application not found" after upgrade to 4.8.0

### ISSUE THREAD

**Issue by afunix** [wazuh/wazuh#24090]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0 | dashboard | Manager | Packages | Ubuntu 22.04.4 |

After upgrade to 4.8.0 Wazuh Dashboard shows "Application not found".
Tried different browsers.
Developer tools show following errors:
Safari 17.5:
<img width="971" alt="image" src="https://github.com/wazuh/wazuh/assets/5682770/0d28dd7e-4330-479f-9a9f-cb3ff4ad2fdb">

Firefox 126.0.1 :
<img width="1059" alt="image" src="https://github.com/wazuh/wazuh/assets/5682770/297a4b41-a15a-43f9-86bf-fe69a051e5a1">

**Comment by rauldpm** [comment]
Hi @afunix 

A breaking change introduced in the 4.8.0 version is a change in the Wazuh user interface home endpoint

- https://documentation.wazuh.com/current/release-notes/release-4-8-0.html#dashboard-plugin

You will need to edit the `/etc/wazuh-dashboard/opensearch_dashboard.yml` configuration file and change the `uiSettings.overrides.defaultRoute` setting to have the following value `/app/wz-home` instead of `/app/wazuh`

After that, please restart the Wazuh dashboard service and check again

I share with you the troubleshooting guide in case it helps: https://documentation.wazuh.com/current/user-manual/wazuh-dashboard/troubleshooting.html#application-not-found

I also share the general upgrade troubleshooting guide: https://documentation.wazuh.com/current/upgrade-guide/troubleshooting.html

I hope this helps!

**Comment by afunix** [comment]
Thanks @rauldpm, I was able to fix this.
The problem is that everyone who got the update from their package manager automatically will run into this situation, unless they are able to read release notes ahead of time.

**Comment by rauldpm** [comment]
I am glad to hear that.

> unless they are able to read release notes ahead of time.

It is good practice to perform upgrade testing in a controlled environment rather than in production deployments, in addition to reading release notes published after a product is published if you are interested in the components upgrade.

We cannot control what the user does and how the user does it but we share the release notes in the community announcements through a link, and as you  understand, we cannot force the users to read it, for example: https://www.reddit.com/r/Wazuh/comments/1de96xi/introducing_wazuh_480/

https://documentation.wazuh.com/current/release-notes/release-4-8-0.html#breaking-changes
