### ISSUE TITLE
Vulnerability Detection Dashboard - Not updating ?

### ISSUE THREAD

**Issue by R00G3R** [wazuh/wazuh#24103]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8 | vulnerability-detection | Manager | Packages | CentOS 7.9 |

I noticed the vulnerability scan is working, new events had been created, but the dashboard just didn't show anything.
On ossec.log, we don't have any error/warning logs for this component.
Anyone has this behavior too ? Or I missing something?

![wazuh_vuln_agent](https://github.com/wazuh/wazuh/assets/72633075/297b5a88-8ef2-4e9e-88d9-b01e7d916cc9)

**Comment by pereyra-m** [comment]
Hello @R00G3R !

The events tab shows the alerts related to vulnerability detector. Filebeat reads the `alerts.json` file and sends the alerts right away.

But the inventory/dashboard tabs use a different index, and it's updated with the `indexer-connector` module of the Wazuh server not Filebeat. It works differently and it could send the data at a different rate.

In the video I see you have an agent filter, what happens if you remove it? Can you see the vulnerabilities of at least one agent or any?

You could also temporarily enable the debug logs of **wazuh-modulesd** to get more information about this module

https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#wazuh-modules
```
wazuh_modules.debug=2
```

**Comment by R00G3R** [comment]
Hi @pereyra-m 
I have 4 hosts that show up on the inventory/dashboard tabs of more than 150 endpoints with vulnerability detection enabled.

![image](https://github.com/wazuh/wazuh/assets/72633075/648f8a4e-7eda-44d7-990b-7b4d30392d88)

I am suspicious about the number of events that are showing up to exactly 32,000.

**Comment by pereyra-m** [comment]
Thank you for the details @R00G3R 

So I understand that the module is working, and we have two issues:
- We don't see anything from the rest, which is almost 150 hosts
- Just 4 agents show 32.000 vulnerabilities

About the first one, we could debug the vulnerability scan by enabling the debug logs as I recommended in the last comment.
Then, if you remove and install packages in the endpoints, we'll see the decisions the scanner is making. Upload the **ossec.log** file with the details. Also, do they all have the same OS?

And about the second one, could you upload one agent's packages inventory, OS details and CVEs found list? This way, we'll analyze them to identify if they are false positives or not.
