### ISSUE TITLE
Issues with reading security events from log files.

### ISSUE THREAD

**Issue by help010021256** [wazuh/wazuh#24119]
## Version Information

SIEM version: 4.8.0.
Agent version: 4.7.4.

Both the Wazuh SIEM and the agent are installed from packages on Ubuntu 22.04 Server.

## Configuration

The goal was to configure a Wazuh agent to read security events from log files.

The relevant part of `/var/ossec/etc/ossec.conf` on the agent:
```
<localfile>
    <location>/tmp/wazuh_test/*.syslog</location>
    <log_format>syslog</log_format>
</localfile>
```

I used the following event for testing, because it triggers Wazuh's built-in rules and generates a security event visible in the web interface without the need for any custom rules or other configuration:
```
Nov 20 11:11:11 fortinet.fortigate.com date=2000-11-11 time=11:11:11 device_id=00000000000000000 log_id=0000000000 type=ips subtype=signature pri=alert vd=root attack_id=000000000 src=111.11.111.111 dst=111.111.117.111 src_port=1234 dst_port=1234 src_int=port2 dst_int=port1 status=detected proto=0 service=1234/tcp msg="Wazuh test"
```

### Steps

1. Create the file: `/tmp/wazuh_test/test1.syslog`.
1. Paste the example Fortinet event into it.
1. Append the example Fortinet event again in a new line after the first one.

### Expected result

Two events with the name `FortiMail: Alert message.` visible in the web interface.

### Actual result

Only one event becomes visible, and only after adding the second line in the file. The first line seems to be lost, no events are generated for it.

### Steps

1. Create the file: `/tmp/test2.syslog` (outside the monitored directory).
1. Paste the example Fortinet event into it twice, in separate lines.
1. Move the file into the watched directory: `/tmp/wazuh_test`.

### Expected result

Two events with the name `FortiMail: Alert message.` visible in the web interface.

### Actual result

No events are generated in the web interface, not even for the second line, unlike in the previous test case.

**Comment by juliancnn** [comment]
Hi @help010021256,

When Wazuh-Logcollector discovers a new file, it starts reading from the end of the file, which means any existing lines at the beginning are ignored. This behavior is by design and cannot be changed. There are currently open issues related to this behavior:

- [Issue #4220](https://github.com/wazuh/wazuh/issues/4220)
- [Issue #4637](https://github.com/wazuh/wazuh/issues/4637)

To avoid losing initial lines, you can use the `only-future-events=no` option in your configuration:

```
<localfile>
    <location>/tmp/test2.syslog</location>
    <log_format>syslog</log_format>
    <only-future-events>no</only-future-events>
</localfile>
```

This way, Logcollector will continue reading from where it left off after restarts.

I hope this helps you in your case, 
Regards

**Comment by JcabreraC** [comment]
Hi @help010021256,

As @juli mentioned, this behavior is by design and cannot be changed and there are open issues related to this behavior: 
- https://github.com/wazuh/wazuh/issues/4220
- https://github.com/wazuh/wazuh/issues/4637

I close the issue.If you have more questions, feel free to reopen the issue.

Regards

**Comment by nalyotovsergey** [comment]
Hello, everyone! 

I am facing the same problem: Wazuh loses the first line of a log file that appeared when creating a new file with a different name (i.e. the file was created by adding this line). The option ```only-future-event=no``` allows logcollector to find those events that appeared when it was not running. But, unfortunately, adding this option does not help to solve my problem with losing the first line of the log file. I would be glad to receive your help.

Regards
