### ISSUE TITLE
elasticsearch indices loss after reinstalling

### ISSUE THREAD

**Issue by C4o** [wazuh/wazuh#2412]
## Bug report

**OS**
CennOS7.2

**Wazuh version**
3.6.1-1.x86_64

**Wazuh API version**
3.6.1-1.x86_64

**Install type**
manager

**Install method**
rpm packages

**Log sample**

```
elasticsearch dont have wazuh-alerts-* indices after reinstalling and reconfiguring by the wazuh document.
```

Bug description
----------------
elasticsearch dont have wazuh-alerts-* indices after reinstalling and reconfiguring by the wazuh document.

**Comment by C4o** [comment]
when i check all functions again,i found that the reason is WARNING(1213),but my client.keys format is right and all normal agents are ACTIVE.
```
2019/01/21 08:26:39 ossec-remoted: WARNING: (1213): Message from 'xxxx' not allowed.
2019/01/21 08:26:45 ossec-remoted: WARNING: (1213): Message from 'xxxx' not allowed.
2019/01/21 08:26:49 ossec-remoted: WARNING: (1213): Message from 'xxxx' not allowed.
2019/01/21 08:26:54 ossec-remoted: WARNING: (1213): Message from 'xxxx' not allowed.
```

**Comment by jesusgn90** [comment]
Hi @C4o ,

Sorry for the late response. 

> elasticsearch doesn't have wazuh-alerts-* indices after reinstalling and reconfiguring by the wazuh document.

Just to be sure, can you check it using `curl`?

```
curl elastic:9200/_cat/indices/wazuh-alerts*
```

> ossec-remoted: WARNING: (1213): Message from 'xxxx' not allowed.

There is an instance of a Wazuh agent sending messages (pointing to) your manager, but it's not known from the manager eyes, that's the reason for that message.

The Wazuh manager uses `remoted` to listen to agents among other tasks, once it receives a message from an agent, it must check the key and the origin (not always) for that agent. Otherwise, any agent pointing to your manager would generate alerts and that's not what you want.

Let us know, and one more time, sorry for the delay.

Regards,
Jesús

**Comment by C4o** [comment]
I remembered that I checked it at that time and found that it's bug of logstash and not be solved at that time, and I may solved my problem after reinstalling logstash. 
Thank you for your response.
