### ISSUE TITLE
GHA mac OS checks failing due to runners deprecation

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#24133]
## Description

Hi team,

It has been detected that GHA checks regarding mac OS 11 (BigSur) are failing because the used runner `macos-11` is being deprecated, causing the job not to be run and letting it as canceled.

Some failed jobs:
https://github.com/wazuh/wazuh/actions/runs/9549113532/job/26317931797?pr=24125
https://github.com/wazuh/wazuh/actions/runs/9549113535/job/26317939315?pr=24125

**Comment by vikman90** [comment]
According to our agent support list, we must support macOS 13 and 14, so let's switch to macOS 13.

**Comment by vikman90** [comment]
## Meeting notes

### Rationale

While GitHub provides both  `macos-13` and `macos-13-large` for macOS 13, they just offer `macos-14-large`. This means that we would be using "macOS 4 (Intel)" → $0.08 / minute for macOS 13, and "macOS 12-core" → $0.12 / minute for macOS 14.

The difference is **50 % more expensive**.

For ARM, we will use `macos-14` → "macOS 3 (M1) → $0.08 / minute.

### Summary & options

- **Option A:** Test macOS 13 on Intel: 👈 
  - Pros: Better price, more coverage.
- **Option B:** Test macOS 14 on Intel (Large):
  - Cons: Worst price.
  - Neutral: We're already testing macOS 14 @ ARM, there is no big difference.

Our vote is to **keep macOS 13 on Intel**, and go for macOS 14 on ARM.

## Reference

- [Runners](https://github.com/actions/runner-images)
- [Prices](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions)

**Comment by vikman90** [comment]
## Meeting notes

We had a meeting to discuss this issue.

First, we assume that support for macOS 14-15 applies already (version 4.9).

Currently, we are compiling the macOS agent using the Mac Mini, with:
- macOS 10 (Intel).
- macOS 12 (ARM).

### Proposals

1. Modify whatever is necessary to compile the agent for macOS 14.
2. Run the build and unit tests on macOS 14.
3. Run the integration tests (GitHub workflow) on macOS 15 (once supported). It doesn't make sense to test the full matrix of versions/architectures on each PR.
4. Extend the possibility to launch integration and system tests on-demand for macOS 14 and 15, both Intel and ARM. Since this doesn't work on GitHub Actions, it will be delegated to DevOps.

### Points to discuss

Thus, we will have a meeting with management to discuss these proposals.

1. Which version to support for each type of test.
2. Full support of tests in separate phases of the pull requests (e.g., nightlies).

**Comment by MarcelKemp** [comment]
For `5.0` it is intended to take into account what is mentioned in this [comment](https://github.com/wazuh/wazuh/issues/24133#issuecomment-2186631586).
