### ISSUE TITLE
Cluster: Bug propagating agent removal to worker nodes

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh#2414]
When an agent is removed in the master node, it looks like in the worker nodes 2 agents are removed: the correct one and the next one in the client.keys.

**Comment by jesuslinares** [comment]
It is fixed in this branch: https://github.com/wazuh/wazuh/commits/dev-cluster-performance.

**Comment by mgmacias95** [comment]
Hello @jesuslinares,

> 
> 
> It is fixed in this branch: https://github.com/wazuh/wazuh/commits/dev-cluster-performance.

More precisely, it has been fixed in commits https://github.com/wazuh/wazuh/commit/2d3907550542068c5e894b842bd5ce8a8966afb6 https://github.com/wazuh/wazuh/commit/19f16a7219e885682ad1786a378330498dcd62ac and https://github.com/wazuh/wazuh/commit/aa004d29e98182fec4ab05379b78d123993448ba.

Best regards,
Marta
