### ISSUE TITLE
Support new OSs - macOS Sequoia 15 - Test VD module

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#24162]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/25665 | https://github.com/wazuh/wazuh/issues/24146 |

| Agent tier | Central components support | OS type |
|-|-|-|
| 1 | No | Major |

# Plan

**CppServer**
- [x] **Tier 1 agent**: Make sure that VD works properly according to the OS tier.

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this issue as not planned because it is a pre-release version.

**Comment by jotacarma90** [comment]
Reopened due to release date for macOS 15 Sequoia is here:
https://9to5mac.com/2024/09/09/macos-sequoia-release-date/

**Comment by Dwordcito** [comment]
## Comparision between Sequoia and Sonoma

### Sequoia's lack of information
Display name -> fixed in https://github.com/wazuh/wazuh/issues/25652

![Image](https://github.com/user-attachments/assets/bd474435-5a2b-4604-b8c2-2167bda43393)

#### Sonoma
![Image](https://github.com/user-attachments/assets/4aa6af8d-252e-42ca-a403-3911a26ee02c)

#### Sequoia
![Image](https://github.com/user-attachments/assets/511e2ed6-88dd-4217-b0de-a3347016b587)


As you can see, the affectation of the display name affects several sectors of the document, which is a problem until the feed update that is executed in the future, since this does a full scan and cleans these elements.

### Errors in logs files.
![Image](https://github.com/user-attachments/assets/d15c2cd6-a948-4034-a927-9f614e3504ac)


## Summary
This one has no problems in terms of scanner since it does not work with the display name, but rather works with the version that is collected programmatically and correctly on macOS. Apart from this, I would like to point out that the versioning is maintained in its format, so there is no difficulty here on the part of the module either. In short, the operation is following the design.

In the case of macOS, no mapping or anything like that is necessary on the server side.

**Comment by sebasfalcone** [comment]
## Review
There is a significant decrease in the detected vulnerabilities, this seems consistent since this is a newer version of the OS

**Comment by Dwordcito** [comment]
exactly, this is the main reason.
