### ISSUE TITLE
After updating to Wazuh 4.8, disk consumption has become severe.

### ISSUE THREAD

**Issue by pyama86** [wazuh/wazuh#24243]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0| worker | - | Docker| ubuntu 22.04

Thank you always for your wonderful products. 
After updating to Wazuh 4.8.0, a large number of .sst files are being created in /var/ossec/queue/indexer/wazuh-states-vulnerabilities-wazuh, and it seems that disk consumption has increased. I have made changes to vulnerability detection and the indexer settings according to the release notes. 
Should these files be deleted at some point, or is it correct that disk consumption will increase going forward?

**Comment by bmm-alc** [comment]
Same issue here when upgrading to 4.8.0, we had to increase to 15Gi the pv of the master and the workers (sst take about 10GB), where before 1Gi was enough.

**Comment by rohangilbile123** [comment]
Facing the same issue with version 4.8.0. A large number of .sst files are getting created in /var/ossec/queue/vd/feed directory which occupies more than 10GB of my disk space

**Comment by rafprzybysz** [comment]
I'm facing the same issue with version 4.8.0 .sst files take around 10GB, upgrade to version 4.8.1 didn't help

**Comment by JSN-1** [comment]
i have the same issue on 4.8.1 .sst files take around 10 GB with only 6 agents connected.

**Comment by sebasfalcone** [comment]
Sorry to all for the delay

## Databases

- `/var/ossec/queue/vd`:
  - Occupies around 5.6 GB, it contains all the vulnerabilities information
  - This DB will grow over time but changes won't be as substantial.
  - It's not affected by the amount of agents
  
- ` /var/ossec/queue/indexer/wazuh-states-*`
  - This DB is used as a queue to retain information that should be indexed
  - It should grow with the number of agents but also decrease over time (when we dispatch the queued events)
  
And here is when I ask you all for some extra information:
- Are events being shown in the dashboard?
- What are the contents of this directory (many sst files?)

**Comment by JSN-1** [comment]
events are being shown in the dashboard 

wazuh-manager-worker-0
```
bash-5.2# pwd
/var/ossec/queue/vd/feed
bash-5.2# du -sh feed/
6.4G	feed/
bash-5.2# ls -l feed/*.sst |wc -l
503
```
it's sst files which are up to 130M in size.

wazuh-manager-master-0
```
bash-5.2# du -sh /var/ossec/queue/vd_updater/tmp/contents
3.4G	/var/ossec/queue/vd_updater/tmp/contents

bash-5.2# du -h /var/ossec/queue/vd_updater/tmp/contents/vd_1.0.0_vd_4.8.0_778892_1722409091.json
2.9G	/var/ossec/queue/vd_updater/tmp/contents/vd_1.0.0_vd_4.8.0_778892_1722409091.json
```

can this tmp file be deleted as it takes up 2.9G as it says 4.8.0 and i am running 4.8.1 ?

thanks for your help

**Comment by sebasfalcone** [comment]
> can this tmp file be deleted as it takes up 2.9G as it says 4.8.0 and i am running 4.8.1 ?

It should be deleted automatically after being processed. But yes, it can be removed once the manager is stopped

**Comment by JSN-1** [comment]
thanks

**Comment by pyama86** [comment]
thanks!

**Comment by whatthejay** [comment]
Hi, Team. I have a question on this, does deleting the remaining *.sst files affect my vulnerability detection result in the wazuh dashboard?

**Comment by sebasfalcone** [comment]
> Hi, Team. I have a question on this, does deleting the remaining *.sst files affect my vulnerability detection result in the wazuh dashboard?

Hi @whatthejay, yes deleting any sst file will corrupt the database. Depending on the DB you deleted the files from, the module will recover by itself

**Comment by dwagelaar** [comment]
I'm having this issue with Wazuh 4.9.2. We are currently running four wazuh-manager VMs (1 master, 3 workers), each with 800 GB of dedicated disk space mounted under /var/ossec. These disks run full over the course of 1 or 2 weeks, and I end up adding worker nodes every time. However, adding a worker node does little to nothing to free up disk space on the wazuh-manager node that ran full. I can add a graph of the disk usage over the last 60 days of our wazuh cluster, if that is helpful.

> Sorry to all for the delay
> 
> ## Databases
> * `/var/ossec/queue/vd`:
>   
>   * Occupies around 5.6 GB, it contains all the vulnerabilities information
>   * This DB will grow over time but changes won't be as substantial.
>   * It's not affected by the amount of agents
> * ` /var/ossec/queue/indexer/wazuh-states-*`
>   
>   * This DB is used as a queue to retain information that should be indexed
>   * It should grow with the number of agents but also decrease over time (when we dispatch the queued events)

This never decreases in my case. It just stops growing at some point after adding a new worker node. Note that we run an haproxy load balancer in front of the wazuh-manager nodes, so I can pull all agent connections away from a wazuh-manager node that has filled up.

> 
> And here is when I ask you all for some extra information:
> 
> * Are events being shown in the dashboard?
> * What are the contents of this directory (many sst files?)

There are events being shown on the dashboard for 5 out of 600 agents. The works seem to be completely clogged up.

In order to keep our cluster form dying altogether, I've performed the procedure outline here: https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/known-issues.html#step-2-reset-the-module-s-data

**Comment by CauchY75** [comment]
We have the same issue.

> This never decreases in my case. It just stops growing at some point after adding a new worker node. Note that we run an haproxy load balancer in front of the wazuh-manager nodes, so I can pull all agent connections away from a wazuh-manager node that has filled up.

**Comment by bmm-alc** [comment]
> In order to keep our cluster form dying altogether, I've performed the procedure outline here: https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/known-issues.html#step-2-reset-the-module-s-data

Hello

thanks for the link however I have two points for wazuh maintainers
- hardly doable for kubernetes
- the articles states this is fixed after `4.9x`, but I'm running the current stable version which is `4.11` and still get the issue.

Best

**Comment by luizmmello** [comment]
Same here, my case:
# pwd && du -sh *
/var/ossec/queue/indexer
1.5M    db
98G     wazuh-states-vulnerabilities-wazuh

This grows overtime, and I had to create a cron job to delete files older than 3 days.
This happens on all worker nodes.

**Comment by hevertydourado** [comment]
Same problem here in 4.11.1.

212 GiB in wazuh-states

[root@master 2025]# ls -lah /var/ossec/queue/indexer/wazuh-states-vulnerabilities-wazuh_cluster | head
total 212G
drwxr-xr-x 2 root root  116K Jun 18 15:57 .
drw-rw---- 4 root wazuh 4.0K Mar 26 16:15 ..
-rw-r--r-- 1 root root   65M Apr 10 11:22 001666.sst
-rw-r--r-- 1 root root   65M Apr 10 11:23 001761.sst
-rw-r--r-- 1 root root   65M Apr 10 11:23 001762.sst
-rw-r--r-- 1 root root   65M Apr 10 11:23 001763.sst
-rw-r--r-- 1 root root   65M Apr 10 11:23 001795.sst
-rw-r--r-- 1 root root   65M Apr 10 11:23 001796.sst
-rw-r--r-- 1 root root   65M Apr 10 11:23 001797.sst

**Comment by d-mankowski-synerise** [comment]
Same issue in 4.12.0

**Comment by dbray925** [comment]
This issue was closed, even though it is still happening on 4.12? Is there a documented fix I can't find?

**Comment by beingke** [comment]
This is still an issue btw

**Comment by Timothy-Daley** [comment]
We are experiencing the same issue where our /xxxx/ossec/queue/indexer/wazuh-states-xxx folder is fillling up with 100s of xxx.sst files, and old files dont seem to be removed automatically.

Filling up a 300GB volume in a few weeks.

Wazuh v4.12.0

**Comment by PedroValdevite** [comment]
Hello,

I'm facing the same problem: /xxxx/ossec/queue/indexer/wazuh-states-xxx keeps growing. It seems like the xxx.stt files aren't being cleaned up. Has anyone managed to resolve this issue?

**Comment by styxiner** [comment]
Still happens on  v4.14.0

**Comment by astsu777** [comment]
Hello. Anybody found a solution about this issue? Running v4.14.1 and it is still an issue

**Comment by bmm-alc** [comment]
Why this issue was closed ? 
The issue is still not fixed, we're running a fresh 4.14 installation and we are still getting the issue.

I created a new issue https://github.com/wazuh/wazuh/issues/34551 

People running into this issue, can you specify the installation setup (kubernets or system installation) ?

**Comment by mirfansulaiman** [comment]
Hi guys,

I encountered the same issue in wazuh version `4.12.0` , but I was able to resolve it without removing the `*.sst` files.

Before resolving it, I faced several issues as outlined below:

## Issues

1. Vulnerability Detection dashboard error:
`Vulnerability detection seems to be disabled or has a problem`

2. Disk usage increased in the directory:
`/var/ossec/queue/indexer/wazuh-states-*`

3. Timeout error:
`timeout of 20000ms exceeded`
This occurred even after disk usage returned to normal and the *.sst files were being processed. The issue was caused by the large amount of data being indexed.

## Solutions

Hopefully this helps anyone who runs into the same problem.

### Solution for Issue no 1 and 2

1. Verify indexer credentials. You can test by creating an index (if it does not exist) and then setting the credentials:
```
/var/ossec/bin/wazuh-keystore -f indexer -k username -v admin
/var/ossec/bin/wazuh-keystore -f indexer -k password -v <your-actual-password>
```

2. This step is only for verification purposes. The wazuh-manager will automatically create indices using the pattern `wazuh-states-vulnerabilities-*`:  
```
/var/ossec/queue/indexer/wazuh-states-vulnerabilities-wazuh-cluster-test
```

3. Restart the Wazuh Manager service:
```
systemctl restart wazuh-manager
```

After restarting the wazuh-manager service, it may take some time to process the existing data. ***Please wait*** and ***monitor*** the *.sst files during this process.

### Solution for Issue no 3

1. Increase the indexer timeout in the Wazuh Dashboard configuration file:
`/etc/wazuh-dashboard/opensearch_dashboards.yml`
```
# Increase timeout
opensearch.requestTimeout: 120000
opensearch.shardTimeout: 120000
```

2. Restart the Wazuh Dashboard service:
```
systemctl restart wazuh-dashboard
```

3. Increase the timeout on the OpenSearch side:
```
PUT _cluster/settings
{
  "persistent": {
    "search.default_search_timeout": "120s"
  }
}
```

4. Increase index-level timeout settings:
```
PUT wazuh-states-vulnerabilities-[index-name]/_settings
{
  "index": {
    "search.slowlog.threshold.query.warn": "10s"
  }
}
```

**Comment by bmm-alc** [comment]
> Hi guys,
> 
> I encountered the same issue in wazuh version `4.12.0` , but I was able to resolve it without removing the `*.sst` files.
> 

Yep, actually we came to the same conclusion, the sst issue was fixed back in the time of the release, but another problem was actually existing in the connection layer to indexers that would be unnoticeable.
