### ISSUE TITLE
Wazuh Vulnerability Dashboard - High Severity and Medium Severity text colours incorrect?

### ISSUE THREAD

**Issue by retroisbest** [wazuh/wazuh#24252]
|4.8.0|self hosted

The overview dashboard uses a red font colour for critical severity, orange for high severity blue for medium and green for low severity.

The vulnerability detection dashboard uses red font colour for critical, blue for high, orange for medium and green for low.

High should be orange
Medium should be blue

Thanks!

**Comment by MarcelKemp** [comment]
Hi @retroisbest,

As you report, the colours do not correspond correctly with their severity. 
This problem is known and already **fixed** for version `4.8.1`, as you can see below:
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6779
- PR: https://github.com/wazuh/wazuh-dashboard-plugins/pull/6793

I hope you find it useful.
