### ISSUE TITLE
Changes in Event Generation Patterns by agentd

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#24293]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-Alpha1 | Wazuh component | Agent | Packages | Windows, Ubuntu |

Testing: [Footprint Metrics - SYSCOLLECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/24270)

Changes in Event Generation Patterns by agents in Windows and Ubuntu

In 4.8.0 an increasing slope of events was observed, while in 4.9.0 it remains flat

Ubuntu
4.9.0-Alpha1
![image](https://github.com/wazuh/wazuh/assets/125690423/7e7ca032-f68f-4f65-8b08-8e366f8cb9c3)

4.8.0-rc4
![image](https://github.com/wazuh/wazuh/assets/125690423/d57ccb7e-ec0f-4b81-89d2-5511aa118a3c)

Windows
4.9.0-Alpha1
![image](https://github.com/wazuh/wazuh/assets/125690423/8d849138-e9b2-41be-804a-8a67ce01c13b)

4.8.0-rc4
![image](https://github.com/wazuh/wazuh/assets/125690423/5df8f406-c705-4fa3-bd80-5ecc98091252)

On the other hand, it is possible to see in the Manager:

4.9.0-Alpha1
![image](https://github.com/wazuh/wazuh/assets/125690423/fe26d245-365a-41ab-9b61-a09f91bc2446)
![image](https://github.com/wazuh/wazuh/assets/125690423/557b7778-0dfc-4f71-b355-5af2c04c188a)

4.8.0-rc4
![image](https://github.com/wazuh/wazuh/assets/125690423/793b910d-4f97-4d53-99be-3afc94d9432a)
![image](https://github.com/wazuh/wazuh/assets/125690423/660a807f-09a4-454f-8d5f-6f45308989bb)

**Comment by vikman90** [comment]
Wondering if this might be related to:

- https://github.com/wazuh/wazuh/issues/22440

**Comment by cborla** [comment]
## Analysis

### Configuration
The difference in test behavior is due to the fact that the correct configuration was not applied to the 4.9.0 test.
As can be seen in the ossec.conf files the syscollector module is disabled for 4.9.0.
![image](https://github.com/wazuh/wazuh/assets/41765669/ba117089-1202-482a-9558-d33cbfff538d)


The configuration to obtain the logs with syscollector is also not included.
![image](https://github.com/wazuh/wazuh/assets/41765669/b42840e8-841a-42d3-901b-8d8f43f25ab4)

And inside the /tmp folder, the directory where the test log is included is not found either.
![image](https://github.com/wazuh/wazuh/assets/41765669/44eee65b-03e0-47f0-8d66-069b06f9b767)

- 4.9.0-Alpha1 [ossec_Test_stress_B5321_ubuntu_2024-06-24.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5321-3600m/B5321_agent_ubuntu/logs/ossec_Test_stress_B5321_ubuntu_2024-06-24.zip)
- 4.8.0-RC4 [ossec_Test_stress_B5303_ubuntu_2024-06-09.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B5303-3600m/B5303_agent_ubuntu/logs/ossec_Test_stress_B5303_ubuntu_2024-06-09.zip)

**Comment by vikman90** [comment]
Thanks @cborla. We've opened an issue to check this configuration:

- https://github.com/wazuh/wazuh-jenkins/issues/6645
