### ISSUE TITLE
Spike - Engine metrics ingestion

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#24322]
| Epic |
|---|
|https://github.com/wazuh/wazuh-dashboard/issues/164|

This spike is a re-evaluation of the work in https://github.com/wazuh/wazuh/issues/15993

# Description
All the components of the system should be observable from outside, reporting metrics about what they are doing, and how quickly they are doing it. These metrics should include event counters, processing times, caches hit / failures, etc.
Although there are many approaches to accomplish this task, we want to use standards to report these metrics, furthermore generally accepted standards with good support for C++.

### Functional requirements

1. **Component Observability**:
    - All system components should be observable from the outside, reporting metrics about their performance and speed.
    - Each component should report specific metrics, including event counters, processing times, cache hits/failures, etc.

2. **Reporting Standards**:
    - Use widely accepted standards for reporting metrics.
    - Utilize OpenTelemetry (OTel) as the standard framework for instrumenting, generating, collecting, and exporting telemetry data.

3. **Reporting Frequency**:
    - Metrics should be reported at configurable regular intervals.

4. **Telemetry Data Categories (Signals)**:
    - **Traces**: Provide a big picture of what happens when a request is made by a user or an application.
    - **Metrics**: Measurements about a service, captured at runtime.
    - **Logs**: Timestamped text records, either structured (recommended) or unstructured, with metadata.
    - **Baggage**: Contextual information that’s passed between spans.
    

### Non-functional requirements
1. **Performance**:
    - The metrics reporting system should not significantly impact the performance of the observed components.
    - The impact on the processing time of each component should be minimal.

2. **Security**:
    - Reported metrics should be accessible only to authorized users.
    - Implement encryption in transit for reported metrics.

3. **Compatibility**:
    - The solution should be compatible with the current and future versions of components developed in C++.

### Implementation restrictions

1. **Programming Language**:
    - The implementation should be in C++ to ensure compatibility with existing system components.

2. **Performance**:
    - The solution should be efficient in terms of memory and CPU usage.
    - Minimize the overhead added by the metrics collection and reporting.

3. **Testing and Validation**:
    - Conduct stress tests to ensure the solution can handle the expected load.

## Plan
- [ ] Evaluate the current implementation carried out in the engine.
- [ ] Evaluate the possibility of sending information/metrics to index.
- [ ] Evaluate how much work is added under the process unification and the new architecture proposed for 5.0

**Comment by JcabreraC** [comment]
# Investigation Report: Wazuh Engine Metrics Module
### Available Metrics

The current metrics available in the Wazuh engine are as follows:

- **EventQueue**
  - `ConsumedEvents`: Counter, enabled
  - `QueuedEvents`: Counter, enabled
  - `UsedQueue`: UpDownCounter, enabled
  - `ConsumedEventsPerSecond`: Counter, enabled

- **TestQueue**
  - `ConsumedEvents`: Counter, enabled
  - `QueuedEvents`: Counter, enabled
  - `UsedQueue`: UpDownCounter, enabled
  - `ConsumedEventsPerSecond`: Counter, enabled

- **endpointAPI**
  - `ConnectedClients`: UpDownCounter, enabled
  - `QueueSize`: Histogram, enabled
  - `ResponseTime`: Histogram, enabled
  - `TotalRequest`: Counter, enabled
  - `RequestPerSecond`: Counter, enabled

- **endpointEvent**
  - `BytesReceived`: Counter, enabled
  - `ServerBusy`: Counter, enabled
  - `UsedQueueHistory`: Histogram, enabled
  - `EventSizeHistory`: Histogram, enabled
  - `BytesReceivedPerSeconds`: Counter, enabled
  - `EventsReceivedPerSeconds`: Counter, enabled

### Metrics Evaluation Process

When listing metrics for the first time, the result will be empty since no request has yet hit the API endpoint. The metrics will be listed on subsequent attempts as the initial request triggers the creation of the instruments.
```bash
# Initial metrics list command
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main metrics list

# Output: (empty)

# Second metrics list command
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main metrics list
endpointAPI.ConnectedClients,UpDownCounter,enabled
endpointAPI.QueueSize,Histogram,enabled
endpointAPI.ResponseTime,Histogram,enabled
endpointAPI.TotalRequest,Counter,enabled
endpointAPIRate.RequestPerSecond,Counter,enabled
```
After sending an event to the router:
``` bash
# Ingest event into router
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main router ingest "h:q:1"

# List metrics again
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main metrics list
EventQueue.ConsumedEvents,Counter,enabled
EventQueue.QueuedEvents,Counter,enabled
EventQueue.UsedQueue,UpDownCounter,enabled
EventQueueDelta.ConsumedEventsPerSecond,Counter,enabled
endpointAPI.ConnectedClients,UpDownCounter,enabled
endpointAPI.QueueSize,Histogram,enabled
endpointAPI.ResponseTime,Histogram,enabled
endpointAPI.TotalRequest,Counter,enabled
endpointAPIRate.RequestPerSecond,Counter,enabled
```
After sending a test event:

```bash

# Run test event
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main tester run test -n wazuh system

# Output: (Enter a log event and press Ctrl+C to exit)

# List metrics again
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main metrics list
EventQueue.ConsumedEvents,Counter,enabled
EventQueue.QueuedEvents,Counter,enabled
EventQueue.UsedQueue,UpDownCounter,enabled
EventQueueDelta.ConsumedEventsPerSecond,Counter,enabled
TestQueue.ConsumedEvents,Counter,enabled
TestQueue.QueuedEvents,Counter,enabled
TestQueue.UsedQueue,UpDownCounter,enabled
TestQueueDelta.ConsumedEventsPerSecond,Counter,enabled
endpointAPI.ConnectedClients,UpDownCounter,enabled
endpointAPI.QueueSize,Histogram,enabled
endpointAPI.ResponseTime,Histogram,enabled
endpointAPI.TotalRequest,Counter,enabled
endpointAPIRate.RequestPerSecond,Counter,enabled

```
## Router Metrics

- **ConsumedEvents:** All events removed from the queue.
```bash
# Get ConsumedEvents metric
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main metrics get EventQueue ConsumedEvents | jq
{
  "records": [
    {
      "type": "Counter",
      "attributes": [
        {
          "type": "SumPointData",
          "value": 2
        }
      ],
      "start_time": "Fri Jun 28 13:02:06 2024",
      "instrument_description": "",
      "unit": "",
      "instrument_name": "ConsumedEvents"
    }
  ],
  "schema": "",
  "version": ""
}

# Ingest another event
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main router ingest "h:q:1"

# Get ConsumedEvents metric again
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main metrics get EventQueue ConsumedEvents | jq
{
  "schema": "",
  "version": "",
  "records": [
    {
      "instrument_name": "ConsumedEvents",
      "type": "Counter",
      "instrument_description": "",
      "unit": "",
      "attributes": [
        {
          "value": 3,
          "type": "SumPointData"
        }
      ],
      "start_time": "Fri Jun 28 13:02:12 2024"
    }
  ]
}
```
- **QueuedEvents**: All events pushed, whether to disk or the queue.
```bash
# Get QueuedEvents metric
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main metrics get EventQueue QueuedEvents | jq
{
  "version": "",
  "records": [
    {
      "instrument_description": "",
      "instrument_name": "QueuedEvents",
      "attributes": [
        {
          "type": "SumPointData",
          "value": 3
        }
      ],
      "type": "Counter",
      "start_time": "Fri Jun 28 13:03:23 2024",
      "unit": ""
    }
  ],
  "schema": ""
}

# Ingest another event
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main router ingest "h:q:1"

# Get QueuedEvents metric again
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main metrics get EventQueue QueuedEvents | jq
{
  "version": "",
  "schema": "",
  "records": [
    {
      "instrument_name": "QueuedEvents",
      "unit": "",
      "attributes": [
        {
          "value": 4,
          "type": "SumPointData"
        }
      ],
      "start_time": "Fri Jun 28 13:03:33 2024",
      "type": "Counter",
      "instrument_description": ""
    }
  ]
}
```
- **FloodedEvents**: All events pushed to disk. Since the queue is not yet full, no events are sent to disk.
```bash
# Get FloodedEvents metric
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main metrics get EventQueue FloodedEvents | jq
The EventQueue scope does not have FloodedEvents instrument.
```
- **UsedQueue**: Increments when an event is pushed to the queue or disk and decrements when extracted.
```bash
# Get UsedQueue metric
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main metrics get EventQueue UsedQueue | jq
{
  "schema": "",
  "version": "",
  "records": [
    {
      "start_time": "Fri Jun 28 13:05:40 2024",
      "instrument_description": "",
      "attributes": [
        {
          "value": 0,
          "type": "SumPointData"
        }
      ],
      "instrument_name": "UsedQueue",
      "type": "UpDownCounter",
      "unit": ""
    }
  ]
}

# Ingest another event
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main router ingest "h:q:1"

# Get UsedQueue metric again
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main metrics get EventQueue UsedQueue | jq
{
  "records": [
    {
      "instrument_description": "",
      "type": "UpDownCounter",
      "start_time": "Fri Jun 28 13:05:47 2024",
      "attributes": [
        {
          "type": "SumPointData",
          "value": 0
        }
      ],
      "instrument_name": "UsedQueue",
      "unit": ""
    }
  ],
  "version": "",
  "schema": ""
}
```
## Tester Metrics

- **ConsumedEvents**: Created once an event is sent to a session.
```bash
# Get ConsumedEvents metric (initial)
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main metrics get TestQueue ConsumedEvents | jq
The TestQueue scope does not have ConsumedEvents instrument.

# Ingest test event
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main tester run test -n wazuh system

# Get ConsumedEvents metric again
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main metrics get TestQueue ConsumedEvents | jq
{
  "records": [
    {
      "start_time": "Fri Jun 28 13:12:12 2024",
      "instrument_description": "",
      "attributes": [
        {
          "value": 1,
          "type": "SumPointData"
        }
      ],
      "type": "Counter",
      "unit": "",
      "instrument_name": "ConsumedEvents"
    }
  ],
  "schema": "",
  "version": ""
}
```
- **QueuedEvents**: Created once an event is sent to a session.
```bash
# Get QueuedEvents metric (initial)
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main metrics get TestQueue QueuedEvents | jq
The TestQueue scope does not have QueuedEvents instrument.

# Ingest test event
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main tester run test -n wazuh system

# Get QueuedEvents metric again
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main metrics get TestQueue QueuedEvents | jq
{
  "records": [
    {
      "unit": "",
      "instrument_name": "QueuedEvents",
      "instrument_description": "",
      "attributes": [
        {
          "type": "SumPointData",
          "value": 1
        }
      ],
      "start_time": "Fri Jun 28 13:13:12 2024",
      "type": "Counter"
    }
  ],
  "version": "",
  "schema": ""
}
```
- **ConsumedEventsPerSecond**

Both in the router and tester, the ConsumedEventsPerSecond metric behaves like a gauge. To determine the rate, a bash script was used to inject 1 million events, and watch -d './build/main metrics get EventQueueDelta ConsumedEventsPerSecond |jq' was employed to observe changes in the rate. When events stop being sent, the metric retains the last observed value, indicating its behavior as a gauge rather than a typical counter.
```bash
#!/bin/bash

for ((i=1; i<=1000000; i++))
do
  ./build/main router ingest "h:q:1"
done
```
Partial result (script is still running):
```bash
Every 2.0s: ./build/main metrics get EventQueueDelta ConsumedEventsPerSecond |jq               engine-test: Fri Jun 28 13:13:02 2024

{
  "schema": "",
  "records": [
    {            
      "attributes": [                              
        {                                      
          "value": 8252,
          "type": "SumPointData"
        }
      ],                
      "instrument_description": "",
      "unit": "",
      "start_time": "Fri Jun 28 13:13:01 2024",
      "instrument_name": "ConsumedEventsPerSecond",
      "type": "Counter"
    }
  ],           
  "version": ""
}
```

## Pending Metrics
-  **kvdb**: Scope is created but not yet used for creating instruments.

**Comment by JcabreraC** [comment]
## endpointEvent Metrics (via UDP)
- Python script to send events to the UDP socket, initializing metrics:
```python
import socket
import json
import time
import os

def create_socket_connection(socket_path):
    try:
        s = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
        s.connect(socket_path)
        return s
    except socket.error as err:
        print(f"Socket creation failed with error: {err}")
        return None

def send_event(sock, event):
    try:
        event_data = json.dumps(event).encode('utf-8')
        sock.sendall(event_data)
        print(f"Event sent: {event}")
    except socket.error as err:
        print(f"Failed to send event with error: {err}")

def main():
    socket_path = '/var/ossec/queue/sockets/queue'

    if not os.path.exists(socket_path):
        print(f"Socket path {socket_path} does not exist")
        return

    sock = create_socket_connection(socket_path)
    if not sock:
        return

    events = [
        {"type": "login", "user": "user1", "timestamp": time.time()},
        {"type": "logout", "user": "user1", "timestamp": time.time()},
        {"type": "message", "user": "user2", "message": "Hello World", "timestamp": time.time()},
    ]

    for event in events:
        send_event(sock, event)
        time.sleep(1)

    sock.close()

if __name__ == "__main__":
    main()
```
- ConnectedClients 🔴 
the first one is 0 because there are no clients connected, then launch the script but it doesn't change (Bug)
```bash
Every 2.0s: ./build/main metrics get endpointAPI ConnectedClients | jq                         engine-test: Fri Jun 28 13:39:53 2024

{
  "schema": "",
  "version": "",
  "records": [                              
    {            
      "attributes": [         
        {            
          "value": 0,
          "type": "SumPointData"
        }                       
      ], 
      "start_time": "Fri Jun 28 13:39:52 2024",
      "instrument_name": "ConnectedClients",
      "instrument_description": "",           
      "type": "UpDownCounter",
      "unit": ""
    }           
  ]           
}
```
- **TotalRequest**: Displays total requests handled.
```bash
# Get TotalRequest metric
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main metrics get endpointAPI TotalRequest | jq
{
  "records": [
    {
      "instrument_name": "TotalRequest",
      "type": "Counter",
      "unit": "",
      "start_time": "Fri Jun 28 13:18:12 2024",
      "instrument_description": "",
      "attributes": [
        {
          "type": "SumPointData",
          "value": 0
        }
      ]
    }
  ],
  "version": "",
  "schema": ""
}
```
- **QueueSize**: Displays size of the request queue.
```bash
# Get QueueSize metric
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main metrics get endpointAPI QueueSize | jq
{
  "records": [
    {
      "instrument_name": "QueueSize",
      "type": "Histogram",
      "unit": "",
      "start_time": "Fri Jun 28 13:19:12 2024",
      "instrument_description": "",
      "attributes": [
        {
          "type": "SumPointData",
          "value": 0
        }
      ]
    }
  ],
  "version": "",
  "schema": ""
}
```
- **ResponseTime**: Displays response times for requests.
```bash
# Get ResponseTime metric
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# ./build/main metrics get endpointAPI ResponseTime | jq
{
  "records": [
    {
      "instrument_name": "ResponseTime",
      "type": "Histogram",
      "unit": "",
      "start_time": "Fri Jun 28 13:20:12 2024",
      "instrument_description": "",
      "attributes": [
        {
          "type": "SumPointData",
          "value": 0
        }
      ]
    }
  ],
  "version": "",
  "schema": ""
}
```
- **BytesReceivedPerSeconds**: Displays the rate of bytes received per second.
```bash
# Get BytesReceivedPerSeconds metric
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# watch -d './build/main metrics get endpointEventRate BytesReceivedPerSeconds | jq'
{
  "schema": "",
  "records": [
    {
      "instrument_name": "BytesReceivedPerSeconds",
      "type": "Counter",
      "unit": "",
      "start_time": "Fri Jun 28 13:21:12 2024",
      "instrument_description": "",
      "attributes": [
        {
          "type": "SumPointData",
          "value": 0
        }
      ]
    }
  ],
  "version": ""
}
```
- **EventsReceivedPerSeconds**: Displays the rate of events received per second.
```bash
# Get EventsReceivedPerSeconds metric
root@engine-test:/home/vagrant/engine-bk-1/wazuh/src/engine# watch -d './build/main metrics get endpointEventRate EventsReceivedPerSeconds | jq'
{
  "schema": "",
  "records": [
    {
      "instrument_name": "EventsReceivedPerSeconds",
      "type": "Counter",
      "unit": "",
      "start_time": "Fri Jun 28 13:22:12 2024",
      "instrument_description": "",
      "attributes": [
        {
          "type": "SumPointData",
          "value": 0
        }
      ]
    }
  ],
  "version": ""
}
```
This concludes the findings on the Wazuh engine metrics module. Further testing and debugging are needed for some metrics, especially `ConnectedClients.`

**Comment by JcabreraC** [comment]
There was an issue to continue improving the Wazuh metrics module, as outlined here: https://github.com/wazuh/wazuh/issues/16757.

Initially, this module was developed by a team with limited understanding of the Wazuh engine, as they were new to the project. Consequently, their implementation lacked depth and has remained unchanged since its inception, pending further work from the original team.

Given the significant changes the engine has undergone since then, and the fact that the metrics module has not been updated in response to these changes, we recommend a comprehensive rework of this module. Our current expertise with the engine and its codebase positions us well to enhance its functionality.

Moreover, this rework presents an opportunity to integrate functionality that enables the metrics to be sent to the indexer, allowing for API-based queries.

**Comment by JcabreraC** [comment]
## Conclusion

After a thorough investigation of the metrics module in the Wazuh engine, it has become evident that a complete rework of the module is necessary. The following key issues were identified:
1. **Initial Development and Team Knowledge**:
   - The initial development of the module was undertaken by a team that no longer exists and had insufficient knowledge about the intricacies of the system.
2. **Potential Deadlock:**
   - There is a potential deadlock issue, which occurred once during testing.
3. **Thread Usage:**   
   - The module currently uses as many threads as there are modules, typically around 7-8 threads.
   - Threads are created and destroyed every second, causing significant performance issues, particularly in the datahub.
4.  **Interface and Design:** 
    - The module lacks a proper interface separation, which complicates testing and maintenance.
    - The design and implementation are suboptimal, with the interface being adapted to the code rather than being well-separated.
5. **Mocking and Testing:**
   - There are no mocks available, making unit testing challenging.
6. **Memory Testing Issues:**
   - The metrics module severely contaminates memory tests, making it impossible to determine if memory growth is due to the metrics module or another module during Massif analysis.
   - It is crucial to modify the module to allow the engine to initialize without metrics, ensuring clean and accurate memory tests.
7. **Inconsistent JSON Output:**
   - The JSON returned by the metrics module does not maintain a consistent order, which can lead to issues in processing and analyzing the metrics data.
8. **Duplication and Performance:**
   - There is duplication of the Opentelemetry pipeline within the module.
   - The use of JSON exporters for in-memory queries is inefficient and costly in terms of performance.
   - 
Given these substantial issues, it is clear that a rework of the metrics module is essential to improve its performance, maintainability, and overall integration within the Wazuh engine. This rework will address the current limitations and ensure a more robust and efficient metrics system.
