### ISSUE TITLE
 rejecting enrollment. Agent ' ' doesn't comply with the registration time to be removed

### ISSUE THREAD

**Issue by ha-07-hub** [wazuh/wazuh#24339]
Hi everyone, 

I have a problem with my Wazuh installation. Suddenly, all the agents, which were previously active, became disconnected ,  and I found this log in ossec.log:

_wazuh-authd: WARNING: Duplicate name '  XXX', rejecting enrollment. Agent '011' key already exists on the manager._

Even when I delete them or add a new agent, I get this log:

_Duplicate name 'XXXX', rejecting enrollment. Agent '043' doesn't comply with the registration time to be removed._

I need help please!

My installation is on cluster (two servers ) and I use a load balancer.
whazu version is 4.8.0

![cap1](https://github.com/wazuh/wazuh/assets/174023457/97b10801-d411-44a3-8943-2abe1fdb8db9)
![image](https://github.com/wazuh/wazuh/assets/174023457/b5937c6f-fc9b-477d-950b-4b6a2bd13c1f)
![image](https://github.com/wazuh/wazuh/assets/174023457/5dd80085-58ef-4257-ab64-7caec8ce06e1)
![image](https://github.com/wazuh/wazuh/assets/174023457/18e41a96-7a87-4304-9f4e-0934bf7fa2c3)

**Comment by pereyra-m** [comment]
Hello @ha-07-hub 

Thank you for the provided information.
What I can see from the screenshots is that all the agents are in a **Never connected** state. This means that they were registered (with a request at port 1515) but they never were able to connect with the manager (using port 1514). See https://documentation.wazuh.com/current/getting-started/architecture.html#required-ports for more details.

When the agent fails to connect several times, it tries to generate a new key but this request is rejected by the server because the agent already has a valid key, or the disconnection was too recent. In the agents' `ossec.log` file, we'll find all the connection attempts and the rejected re-registration.

In this case, I suggest you confirm the agent can reach the manager at that port. For example with this command from the agent

```
nc -zv MANAGER_IP 1515 1514 
```

Also, make sure there isn't any firewall rule blocking the traffic for that port between the agents and the manager.
Regards.

**Comment by christiancopeland** [comment]
I spent a good couple hours digging through Wazuh issues, threads and write-ups. 

2 unique things I haven't seen elsewhere yet:

Make sure your time is set correctly on the machine you're setting the agent up on. For me, I was setting up an agent on pfSense and needed to run 'date HH:MM' to pull the time back a couple hours so it lined up right. 

Check your /var/ossec/etc/ossec.conf on the agent side uses 'tcp' as the protocol in the same block where your MANAGER_IP and port are designated

These changes fixed my connection issues.

**Comment by pereyra-m** [comment]
Thank you @christiancopeland .

Indeed, the `tcp` connection is more reliable than `udp` and should be the default since a few Wazuh updates.
If the agent is configured with that protocol in this section

https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#protocol

```
<client>
  <server>
    <address>MANAGER_IP</address>
    <port>1514</port>
    <protocol>tcp</protocol>
    ...
  </server>
</client>
```

Then we should have the same in the manager's corresponding section

https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/remote.html#protocol
```
<remote>
  <connection>secure</connection>
  <port>1514</port>
  <protocol>tcp,udp</protocol>
  ...
</remote>
```

Maybe something changed in the LB and the packets aren't arriving to the manager.
