### ISSUE TITLE
Integrate the indexer connector into the engine system

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#24354]
# Integrate the Indexer Connector into the Engine System

## Description
This task focuses on integrating the Indexer Connector into the engine system. The integration should be handled as a plugin within the forwarder of outputs, allowing the engine to efficiently use the Indexer Connector for alert indexing.

## Objectives
- Integrate the Indexer Connector as a plugin in the engine's forwarder of outputs.
- Ensure the integration is seamless and does not disrupt existing functionalities.

## Tasks
1. **Modify Forwarder of Outputs**
    - Update the forwarder of outputs to include the Indexer Connector as a plugin.
    - Ensure the configuration settings for the Indexer Connector are correctly implemented.

2. **Testing and Validation**
    - Test the integration in a staging environment to ensure it works as expected.
    - Verify that the Indexer Connector can process and forward alerts without issues.

## Deliverables
- Integrated Indexer Connector within the engine's forwarder of outputs.
- Test results confirming the successful integration and functionality.

**Comment by juliancnn** [comment]
## Update

- Investigating the actual operation and implementation of indexerConnector
- Modified to add interfaces
- Starting to configure docker-compose for an instance of opensearch

**Comment by juliancnn** [comment]
## Update

In a proof of concept I have managed to create an indexer connector output as a wazuh-engine stage, but I have found several problems with `indexerConnector module`, from bugs to functional that need to be overhauled:

- :bug:  Indexer connector is not able to re-establish a connection during an indexer shutdown, I have tried turning off the opensarch container and turning it back on, but it keeps logging that there are no servers available and it only indexes the events if we restart the engine with the indexer running.
- It is not possible to maintain the same connector indexer instance and change the index once it has already been instantiated. It would be desirable to keep the same queue and change the index at runtime, this will allow to change the index every day, and keep a pattern of indexes, something like `wazuh-alerts-5.x-%{+yyyyy.MM.dd}`, allowing a different index policy management and not a giant index. I am not an opensearch expert, maybe this is not necessary.
- Currently the indexer requires an `id` field to index the alert, this field must be unique in the case of alerts since we do not want to update a document and there should not be 2 alerts the same. Another option could be to use a hash of the alert, but it seems an unnecessary calculation. I think we should remove the id and let opensearch generate it automatically as the documentation here https://opensearch.org/docs/latest/api-reference/document-apis/bulk/#request-body makes clear.

**Comment by Dwordcito** [comment]
After meeting notes.

- Discarded, incorrecte testing from @juliancnn 
- [ ] Add place holder to manage index names with dates
- [ ] ID as optional field in the indexer connector
- Already implemented in the indexer connector destructor
- We won't implement this.
- [ ] Error handling for alerts in the indexer connector

**Comment by juliancnn** [comment]
## Update

- Create the PR
- Successfull integration in assets

Pending:
 - Test

**Comment by juliancnn** [comment]
## Update

- Test
- Minor change in expected behavior
- Ready for review

**Comment by juliancnn** [comment]
## Update

- Rebase
- Minor changes after revieew
