### ISSUE TITLE
Fixed vulnerabilities not removed from indexer. 

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#24444]
# Description 

It was found by several users that the information is not updated in the indexer after fixing vulnerabilities. 
https://github.com/wazuh/wazuh/issues/24131

A test was done as part of this issue https://github.com/wazuh/wazuh/issues/23066 with a similar behavior https://github.com/wazuh/wazuh/pull/23225#issuecomment-2103187338

**Comment by pereyra-m** [comment]
## Update

I try to reproduce the issue in a Docker environment.

**Comment by pereyra-m** [comment]
Hi @GabrielEValenzuela . Please link the community you've mentioned and include any valuable information it has provided.

**Comment by pereyra-m** [comment]
## Update

After running some tests, I analyzed different hypotheses to explain the described behavior.
Here I summarize some internal details of Opensearch that are related to this issue and describe a possible cause of the issue.

### Index settings research

When there is a write operation in the index, a `refresh` operation is required to make the new elements searchable because the data in the memory buffer must be written to the segments (https://opensearch.org/blog/optimize-refresh-interval/). The indexer module waits for a refresh before returning because of this parameter `refresh=wait_for` (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-refresh.html). This value by default is in the order of 1-2 seconds

https://github.com/wazuh/wazuh/blob/038fe11d988fa54cca8a6c3101fc7906fad5da3b/src/shared_modules/indexer_connector/src/indexerConnector.cpp#L239

This means that the new elements should be available right after the indexer module request.

The delete operations don't impact instantly but mark the rows for deletion (https://github.com/ev2900/OpenSearch_DeletedDocuments). The segments are inmutable and a merge operation is required for the space to be claimable. 

We can get the documents marked for deletion with `GET _cat/indices?v`. 
According to this source, the documents marked for deletion shouldn't be searchable anymore
https://www.elastic.co/es/blog/lucenes-handling-of-deleted-documents
 
This can degrade the search performance over time but it shouldn't be the cause of the situation we have here.

The merge can be forced in case we need to reclaim space, but this isn't a common maintenance task, it takes too much time and resources to be executed in large indexes

```
POST /<index-name>/_forcemerge?only_expunge_deletes=true
```
If we don't use fuzzy searches, the ghost fields don't affect the results (

On the other side, not clearing the index cache shouldn't be the cause of getting the wrong results 

https://stackoverflow.com/questions/76517009/do-i-need-to-explicitly-clear-the-index-cache-after-indexing-updating-a-document

### Vulnerabilities dashboard issue

According to the details described above, in a normal situation, the requests of the indexer module should impact shortly in the search.

The only situation that I was able to generate that makes the old vulnerabilities still visible is leaving a tab opened with old results and not reloading it (the refresh button doesn't work for this case). The direct query to the index doesn't show the results and neither does a new tab 

![2024-07-10_17-06](https://github.com/wazuh/wazuh/assets/65046601/cf63ddc3-b4ea-418d-b6ae-afc7a7e2173d)

We need to confirm with the users if this is the case they've found. If it isn't, I'd discard an issue in the indexer module connection first.

**Comment by GabrielEValenzuela** [comment]
Hi @pereyra-m !

Sure! 

- https://github.com/wazuh/community/issues/29884
- https://github.com/wazuh/community/issues/29876

**Comment by gkissand** [comment]
Hi
In my case in vulnerability dashboard for one agent I see package curl as Critical 
![image](https://github.com/wazuh/wazuh/assets/25226373/52188b59-94e5-4ac1-96e9-81fea4940901)

In wazuh-alerts index I see it as Solved
![image](https://github.com/wazuh/wazuh/assets/25226373/502dc300-2c6a-4f40-8798-0e39d6243b58)

In wazuh-states-vulnerabilities-* it's present
![image](https://github.com/wazuh/wazuh/assets/25226373/2fe65cf2-0897-4760-8522-7665e53b61d2)

In opensearch Dev Tools package "curl" is not present
![image](https://github.com/wazuh/wazuh/assets/25226373/99792af1-a7da-4b46-9569-25b0e6c18048)

If you need more info let me know

**Comment by sebasfalcone** [comment]
@gkissand Requests to the API have a restriction on the number of items retrieved, you should add the `?size=<number_of_items>` parameter to retrieve all of them

Like this:
`GET wazuh-states-vulnerabilities-thinkpad-sebas/_search?size=10000`

On the other hand, we are investigating other problems in this issue, if you need further assistance use one of our [community channels](https://wazuh.com/community/)

Thanks

**Comment by gkissand** [comment]
I didn't request for help. I just wanted to give you info about the issue :)
Thank you

**Comment by sebasfalcone** [comment]
## Close due to inactivity
We were unable to reproduce this issue despite the joint efforts of @MiguelazoDS and @pereyra-m 

We asked the users for more information to validate the root cause but they appear to be inactive, the timebox expired for this issue

We will re-open it if necessary

**Comment by djordjezecevic** [comment]
I have same problem, version : {"error":0,"data":[{"WAZUH_VERSION":"v4.8.2"},{"WAZUH_REVISION":"40819"},{"WAZUH_TYPE":"server"}]}
 Here is scenario: Say you have vulnerable packet node-ip(picture1) and you remove it from server. Inventory of that server is not showing node-ip installed (picture2) but in vulnerability inventory it still active and present !

tried restarting indexer, checked refresh interval:

Refresh interval:
{
  "wazuh-states-vulnerabilities-mydomainname": {
    "settings": {
      "index": {
        "refresh_interval": "2s"
      }
    }
  }
}

GET /syscollector/004/packages?name=node-ip
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "No syscollector information was returned",
  "error": 0
}

**Comment by pereyra-m** [comment]
Hello @djordjezecevic 


I'd need more details about your environment. Is it a Wazuh manager cluster or a single node? Do you have many Indexer nodes? Please share the `ossec.conf` and `ossec.conf` files for managers and an agent. Don't forget to remove any sensitive data.

The synchronization of the manager with the Indexer might be delayed due to the abuse control mechanism. It is meant to avoid too many requests in a short period. If this is the case, we'd see a message like this one in the manager
```
Agent 'X' sync omitted due to abuse control.
```

Another option is that the Indexer Cluster isn't in 'green' status. This also prevents the synchronization. 
You can confirm this with this query

```
curl -k -u <user:pass> -XGET https://<INDEXER_IP>:9200/_cluster/health
```

Regards.

**Comment by djordjezecevic** [comment]
Hello,
Configuration file attached. It is a simple setup one server for a
[ossec.conf.log](https://github.com/user-attachments/files/16928058/ossec.conf.log)
ll.
```
[root@swazuh ~]# cat /var/ossec/logs/ossec.log | grep "omitted due to abuse"
[root@swazuh ~]#

```
Yes there was a cluster problem

```
{
  "cluster_name": "wazuh-cluster",
  "status": "yellow",
  "timed_out": false,
  "number_of_nodes": 1,
  "number_of_data_nodes": 1,
  "discovered_master": true,
  "discovered_cluster_manager": true,
  "active_primary_shards": 155,
  "active_shards": 155,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 33,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 82.4468085106383
}
```

.opendistro-alerting-alert-history has replica shards. I tried to 

change configuration, but couldn't do with  admin user. 

`[security_exception] no permissions for [] and User [name=admin, backend_roles=[admin], requestedTenant=null]`

**Comment by pereyra-m** [comment]
Hi again @djordjezecevic, thank you for the information provided. 

> .opendistro-alerting-alert-history has replica shards. I tried to
change configuration, but couldn't do with admin user.

Can you share the command you've tried?
In cases like this one, it is useful to request the reason for the unassigned shards

```
curl -k -u <user:pass> -XGET https://<INDEXER_IP>:9200/_cluster/allocation/explain
```

If the index has more than one replica for a single node setup, there will always be unassigned shards.
You can check the configuration for that index 

```
curl -k -u <user:pass> -XGET https://<INDEXER_IP>:9200/.opensearch-control-center/_settings
```

Once we confirm that is the issue, we could update the index settings and set `"number_of_replicas":0`

Regards.

**Comment by djordjezecevic** [comment]
Hello,
![2024-09-10 09_43_21-Wazuh — Mozilla Firefox](https://github.com/user-attachments/assets/9c6dde8c-b4e7-4408-b66c-8aa1990047a8)

I tried from Kibana, see attached screenshot. 

```
{
  "index": ".opendistro-ism-managed-index-history-2024.08.30-000069",
  "shard": 0,
  "primary": false,
  "current_state": "unassigned",
  "unassigned_info": {
    "reason": "CLUSTER_RECOVERED",
    "at": "2024-09-09T14:43:00.771Z",
    "last_allocation_status": "no_attempt"
  },
  "can_allocate": "no",
  "allocate_explanation": "cannot allocate because allocation is not permitted to any of the nodes",
  "node_allocation_decisions": [
    {
      "node_id": "dOXuoguaTqacCjtTgrvFvg",
      "node_name": "node-1",
      "transport_address": "10.x.x.x:9300",
      "node_attributes": {
        "shard_indexing_pressure_enabled": "true"
      },
      "node_decision": "no",
      "deciders": [
        {
          "decider": "same_shard",
          "decision": "NO",
          "explanation": "a copy of this shard is already allocated to this node [[.opendistro-ism-managed-index-history-2024.08.30-000069][0], node[dOXuoguaTqacCjtTgrvFvg], [P], s[STARTED], a[id=U1khDAGJQA2jspSa00Ip5Q]]"
        }
      ]
    }
  ]
}
```

GET /.opendistro-ism-managed-index-history-2024.08.30-000069/_settings
```
{
  ".opendistro-ism-managed-index-history-2024.08.30-000069": {
    "settings": {
      "index": {
        "replication": {
          "type": "DOCUMENT"
        },
        "hidden": "true",
        "number_of_shards": "1",
        "provided_name": "<.opendistro-ism-managed-index-history-{now/d{yyyy.MM.dd}}-000069>",
        "creation_date": "1724991346822",
        "number_of_replicas": "1",
        "uuid": "R0QXw8eqSIOYVGpy4yiZvw",
        "version": {
          "created": "136317827"
        }
      }
    }
  }
}
```

**Comment by pereyra-m** [comment]
@djordjezecevic 

With this information, it is confirmed that the number of replicas for the index is the problem.
You need to modify the setting for any conflicting index. For example

```
curl -k -u <user:pass> -XPUT https://<INDEXER_IP>:9200/.opendistro-ism-managed-index-history-2024.08.30-000069/_settings 
{
  "index":{
    "number_of_replicas":0
  }
}
```

Then, you can verify the cluster health again to confirm it is green.
Regards.

**Comment by djordjezecevic** [comment]
Hello, a had problems with setting replica number, so I installed second node just to move on. Now, cluster is in green state
```
{
  "cluster_name": "wazuh-cluster",
  "status": "green",
  "timed_out": false,
  "number_of_nodes": 2,
  "number_of_data_nodes": 2,
  "discovered_master": true,
  "discovered_cluster_manager": true,
  "active_primary_shards": 157,
  "active_shards": 290,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 0,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 100
}
```

Still, there is problem. Data in vulnerability database is not reflecting inventory.  For example, agent 010 had Oracle VM version 7.0.18 
![Vulnerabilities for agent 010](https://github.com/user-attachments/assets/5edcf761-4b69-48a0-8f93-1991fa6833eb)
After upgrade to 7.0.20, inventory shows correct version
![Inventory for agent 010](https://github.com/user-attachments/assets/4e8cf1dd-bb50-47d7-8f17-9d0f665fadb2)

But vulnerability for for version 7.0.18 is not removed. 

Best regards,
Djordje

**Comment by pereyra-m** [comment]
Hi @djordjezecevic 

Adding a node is another way to solve the problem, and now that the cluster is in 'green' status we can continue with the research.

According to the captures you've shared, the packages' inventory is updated with the upgraded version, but the dashboard still shows the old vulnerabilities.
Can you query the index to verify the documents are still there? You can use a query like this in **Index management --> Dev Tools**, replace the index name with the right one for your environment

```
GET wazuh-states-vulnerabilities-wazuh.manager/_search
{
  "query": {
    "regexp": {
      "package.name": "Oracle.*"
    }
  }
}
```

In case the documents don't exist in the index but the dashboard still shows them, you might need to refresh the page because of this bug
- https://github.com/wazuh/wazuh-dashboard/issues/232

But if the documents do exist, then something failed with the synchronization.
We are researching that issue also here
- https://github.com/wazuh/wazuh/issues/25663

I wait for your comments.
Regards.

**Comment by pereyra-m** [comment]
@wazuh/devel-cppserver-div1 

I might have found a situation where the deleted package events aren't synced with the indexer.

The `ScannerType::PackageDelete` orchestration consists of a few chain links, the most important here are `TEventDeleteInventory` and `TResultIndexer`.
The DELETED events (from RSync and DBSync) trigger this sequence, and after loading all the CVEs from `m_inventoryDatabase` to `m_elements`, the entry is removed. 

The thing is that if we don't have an instance of `m_indexerConnector`, the elements to be removed never are processed by the `m_dispatcher` queue nor removed from `m_db`

https://github.com/wazuh/wazuh/blob/2617f9fa1ee88c21c90221bfd7beaf41d9b1618a/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/resultIndexer.hpp#L52

Once the sync between the inventory DB and indexer DB is lost, we never recover from that state. 
The fallback mechanism of `GlobalSyncInventory` (that works over `m_syncQueue`) that is triggered every time there is an integrity check global from **syscollector** only verifies the indexer DB content, not the inventory one.

Maybe we could add extra links in the `m_inventorySyncOrchestration` chain to cover this situation.

### How to reproduce

- Install a vulnerable package
- Confirm it's available in the index
- Disable the `index-status` option in the manager and restart
- Remove the package from the agent and restart it to force a sync
- The vulnerabilities will be present, even if we enable the option again and wait for the fallback synchronization mechanism

**Comment by pereyra-m** [comment]
## Update

We'll have a meeting to discuss a possible fix.

**Comment by sebasfalcone** [comment]
## Closing issue
The investigation concluded with the creation of a new issue:
- https://github.com/wazuh/wazuh/issues/25799

We are closing this issue to pursue the implementation of the fix
