### ISSUE TITLE
Vulnerability detector identifying wrong version of a package

### ISSUE THREAD

**Issue by Thur4321** [wazuh/wazuh#24485]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.8.0 | Vulnerability Detector | Manager | Packages (All in One) | Alma Linux 9.3 |

Hello there!

I was checking the vulnerabilities in my environment (mainly with the preview update) for the new CVE-2024-6387, and I found some records showing to be in recent versions of OpenSSH (and its variations), but with old CVEs from old packages.

![imagem_2024-07-08_075407769](https://github.com/wazuh/wazuh/assets/104312115/363227e3-e4ec-456a-9344-21002642f32f)

An example is the OpenSSH itself which the version presented is 1:9.2p1-2 (which in Debian-based systems have 1: before the number, and this specific one is from the end of last year), and even so, the module identified it as below of 4.6, most likely because it understands the 1: as indicative of a version 1, and not 9. 

Although I haven't researched much, I believe there may be more packages like this. Furthermore, sometimes certain CVEs are found for x version of a package, but are resolved in the next check. This is before we even acted. I believe it is because some packages are present in more than one version in the system, which can confuse the system that finds the package, and then finds another one.

**Comment by Damian-Mangold** [comment]
Hi @Thur4321 , thank you very much for the report. Let me analyze it and I will get back to you as soon as possible.

**Comment by Damian-Mangold** [comment]
Hi @Thur4321, Could you please share with me the following information in order to perform a deeper analysis and try to reproduce what you report
 - [OS information](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_os_info)
 - [package inventory](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_packages_info)
 - Vulnerability Inventory
   
![image](https://github.com/user-attachments/assets/21e4b674-182f-4240-86ea-caff71dac20a)

**Comment by Thur4321** [comment]
Hi @Damian-Mangold, the OS is between Debian 11 and 12, but unfortunately I cannot share the other information because after updating the openssh version (it was one below the one that corrected CVE-2024-6387, I corrected it in the same week that I made this publication) and wazuh itself (I was on 4.8, I went to 4.8.1 on Friday), the CVEs were fixed (but I can't find the logs regarding them being resolved, so I can't say if it was now or before). Now I have the following version on all my Debian-based servers, and it doesn't appear to have any problems, so at this point I can't say what could have happened.

![imagem_2024-07-22_085308150](https://github.com/user-attachments/assets/8c9ee205-c621-49fe-8d78-e44eb5e8e573)

**Comment by Damian-Mangold** [comment]
Hi @Thur4321, Thank you for your response. However, something is still unclear. In the issue description, you mention "Alma Linux 9.3," but in the previous message, you mentioned "Debian 11 and 12." It is crucial to know the exact OS on which these vulnerabilities are observed, as different feeds are used depending on the OS. Could you please clarify this for me?

**Comment by Damian-Mangold** [comment]
Thanks! I'll do the analysis with the Debian feed then. I will come back when I have news.

**Comment by Damian-Mangold** [comment]
The vulnerabilities were resolved after updating the versions, which is the expected behavior.

The Vulnerability Detector (VD) selects the most appropriate feed depending on the operating system being analyzed, and this selection is made automatically. For Debian, the official feed provided by Debian is used. Therefore, you can check the status of a vulnerability directly at [Debian Security Tracker](https://security-tracker.debian.org/tracker/), for instance, for [CVE-2024-6387](https://security-tracker.debian.org/tracker/CVE-2024-6387). 
As indicated, the fixed version is `1:9.2p1-2+deb12u3`. This is why, when you had version `1:9.2p1-2+deb12u2` installed, the vulnerability was reported. Now that you have updated to version `1:9.2p1-2+deb12u3`, the vulnerability has been resolved.

**Comment by Thur4321** [comment]
Hi @Damian-Mangold, I was investigating about the CVE with the description in my print, and the text corresponds to the CVE-2007-2243, which is the originally CVE of the same problem with CVE-2024-6387. Maybe because this last CVE didn't exist in the feed when I printed, could the old CVE appeared in the place of the new (which didn't appear before one or two days later if I remember right)? And, if I don't have logs of this CVE being resolved, could be because it was replaced by the new? And thanks for your responses.

**Comment by Damian-Mangold** [comment]
Hi @Thur4321

Correct, based on the image description, the CVE was CVE-2007-2243, while you mentioned CVE-2024-6387. This is why I requested the vulnerability inventory to gain a better understanding.

> Maybe because this last CVE didn't exist in the feed when I printed.

Yes, it is possible that when you captured the data, CVE-2024-6387 had not yet been published.

> Could the old CVE have appeared in place of the new one (which didn't appear until one or two days later if I remember correctly)? And if I don't have logs of this CVE being resolved, could it be because it was replaced by the new one?

CVEs are not replaced; they coexist and all that match a given vulnerability are reported. For example, if you install a version of OpenSSH lower than `1:9.2p1-2+deb12u2`, you will likely be reported with at least the vulnerabilities associated with both CVE-2007-2243 and CVE-2024-6387.

**Comment by sebasfalcone** [comment]
Inactive thread, please re-open it if necessary

> [!NOTE]
> The answer seems to be correct, a feed update could trigger this behaviour
