### ISSUE TITLE
False positive? - Package python-perf

### ISSUE THREAD

**Issue by R00G3R** [wazuh/wazuh#24486]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-rev | Vulnability Detection| Manager | Packages | CentOS 7 |

Hi guys,

Noticed the vulnerability detection dashboard showing the package "python-perf" with the description of the Linux kernel install.

![image](https://github.com/wazuh/wazuh/assets/72633075/838c2d42-97af-4cf7-b8f7-46bcc36306c6)

Is this expected?

CVE-2021-46916, for example, doesn't even include the version that is reported, not even the python-perf package.

![image](https://github.com/wazuh/wazuh/assets/72633075/7e1fbd23-4f81-4f75-af36-5573c051daa1)
Source: https://nvd.nist.gov/vuln/detail/CVE-2021-46916

**Comment by Damian-Mangold** [comment]
Hi @R00G3R, thank you very much for the report. Let me analyze it and I will get back to you as soon as possible.

**Comment by Damian-Mangold** [comment]
Hi @R00G3R , Could you please share with me the following information in order to perform a deeper analysis and try to reproduce what you report
 - [OS information](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_os_info)
 - [package inventory](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_packages_info)

**Comment by Damian-Mangold** [comment]
Hi @R00G3R,

After analyzing your report, we would like to mention two key concepts regarding the functioning of the vulnerability detector:

1. The vulnerability detection module analyzes vulnerable packages using the most suitable feed for the OS being analyzed. In this case, for CentOS 7, the [RedHat 7 feed is used](https://www.redhat.com/security/data/oval/v2/RHEL7/rhel-7-including-unpatched.oval.xml.bz2). Therefore, to determine if a package is vulnerable, the RedHat 7 feed should be used instead of the NVD feed.

2. The Wazuh manager is delivered with a base vulnerability content, which is automatically updated while the manager is running. During the first execution, this update may take a few minutes to complete.

We have reviewed the history of the "python-perf" package and noticed that its status changed from "affected" to "unaffected" in recent weeks. We verified that in the base content of version 4.8, the package was marked as vulnerable, but in the current content, it is no longer vulnerable.

Did you observe these vulnerabilities immediately after installing Wazuh? If so, you should wait for the manager to update, and those vulnerabilities should disappear.

**Comment by sebasfalcone** [comment]
Inactive thread, please re-open it if necessary
