### ISSUE TITLE
Unexpected error in Vulnerability Detection performance test: received string size is bigger than 65536 bytes

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#24547]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.1-rc2 | WazuhDB | Manager | Packages | Ubuntu 22 |

### Description

During [Release 4.8.1 - RC 2 - Vulnerability Detection performance test](https://github.com/wazuh/wazuh/issues/24504) it has been detected an unexpected warning in the master node:
```
2024/07/09 13:37:07 wazuh-db: WARNING: at run_worker(): received string size is bigger than 65536 bytes
```

More information can be found at https://github.com/wazuh/wazuh/issues/24504#issuecomment-2222791472

### Overview

Performance tests are planned to detect any regression in the Vulnerability Detection module. In order to generate multiple vulnerability detection events, used Agent [Simulator QA tool](https://github.com/wazuh/wazuh-qa/blob/master/deps/wazuh_testing/wazuh_testing/tools/agent_simulator.py). 
This warning could be related to the usage of the agent simulator, although it's necessary to a thorough research to determine the causes of this issue.

### Evidences

- [Artifact1.zip](https://github.com/user-attachments/files/16176888/Artifact1.zip)
- [Artifact2.zip](https://github.com/user-attachments/files/16176900/Artifact2.zip)
- [Artifact3.zip](https://github.com/user-attachments/files/16176907/Artifact3.zip)

**Comment by pereyra-m** [comment]
## Update

I begin with the issue.
I'll try to reproduce it locally, and analyze the code around the error.

**Comment by pereyra-m** [comment]
## Analysis

I've been analyzing the code and also made some tests.
I'll try to describe the key points of the research.

### Wazuh-DB communication protocol  

The error message suggests that a huge query has arrived at the socket, reaching the maximum 65536 length that the socket can handle per message.
I confirmed that sending a big message to Wazuh-DB generates this message. But also a small message with a big header has the same effect because the protocol consists of the following structure

```
    MSGLENGTH + MSG
```

So if the first 4 bytes of the message get changed or corrupted, the communication will fail as shown.

### Vulnerability detector requests

All the communication between Wazuh-DB and the vulnerability detector module happens through the `SocketDBWrapper` and  `WazuhDBQueryBuilder` classes. These calls were analyzed but it doesn't seem possible to create a big query naturally (an ID can't be that long). 
Behind them, we have the `SocketWrapper` class that handles the communication with `/var/ossec/queue/db/wdb` and could be responsible for data corruption that leads to the protocol error described above.

### Related issue with the same possible cause

During the same test, another issue was created #24546. Here, the communication happens in the opposite direction: Wazuh-DB sends a JSON to vulnerability detector and the message contains strange characters. Unless there is a problem with the cJSON/Nlohmann libraries or JSON message format, we could think that the `router` module that is used to publish the messages fails to deliver the data because the `SocketWrapper` class that works behind is presenting issues during the heavy load of the test.

### Trying to reproduce the error

I've been running a script that spawns many threads that query the Wazuh-DB with `wazuh_db_query_testtool`. This tool exercises the `SocketWrapper` and `SocketDBWrapper` classes. Also, many fake packages were added to the manager `000.db` database to generate more traffic in the socket and force a communication failure with Wazuh-DB.

It wasn't still possible to generate the expected error message after several attempts.

## Conclusion

I've proposed a cause for the issue but I couldn't confirm it with my tests.
If the team validates this hypothesis and line of investigation, I could carry on with the tests until the error is generated.

**Comment by sebasfalcone** [comment]
## Moved ETA and release
Given that the issue predates 4.8.1 and is non-stopper, we will continue the investigation in 4.10.0

**Comment by pereyra-m** [comment]
## Update

I keep trying to reproduce the issue. I'll use the QA agent simulator now.

**Comment by pereyra-m** [comment]
## Update

I've tried new ways to reproduce the issue with no success.
This time, the agent simulator was used
https://github.com/wazuh/wazuh-qa/blob/master/deps/wazuh_testing/wazuh_testing/scripts/simulate_agents.py

Different configurations were tested, changing the number of agents, EPS, packages per agent, OS, and frequency.
Up to 2200 agents were simulated because the local machine only has 64GB of RAM, it wasn't possible to simulate 50.000

```
python3 simulate_agents.py --debug -n 2200 -t 180 -a 172.17.0.2 -s 300 -m vulnerability --vulnerability-events 300 --vulnerability-frequency 5

python3 simulate_agents.py --debug -n 2200 -t 180 -a 172.17.0.2 -s 300 -m vulnerability --vulnerability-events 300 --vulnerability-frequency 1

python3 simulate_agents.py --debug -n 2200 -t 180 -a 172.17.0.2 -s 100 -m vulnerability --os debian10
```

Some WARNING/ERROR messages were seen but they aren't related to the situation we're trying to generate here
```
2024/07/16 01:20:57 wazuh-remoted: WARNING: Message queue is full (131072). Events may be lost.
2024/07/16 01:21:34 wazuh-db[22225] wdb_global.c:1397 at wdb_global_recalculate_agent_groups_hash(): WARNING: The groups were empty right after the set for agent '44405'
2024/07/16 01:21:40 wazuh-analysisd: WARNING: Syscollector decoder queue is full.
``` 

When I analyze the logs provided with the issue, it's interesting to note that many errors appear after a content update and all of them come from the delayed queue
```
...
2024/07/09 13:38:28 wazuh-authd: INFO: Received request for a new agent (1-YVop8FeTHvu5BzCg-debian10) from: 172.31.59.19
2024/07/09 13:38:28 wazuh-authd: INFO: Agent key generated for '1-YVop8FeTHvu5BzCg-debian10' (requested by any)
2024/07/09 13:38:33 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2024/07/09 13:38:33 wazuh-remoted: INFO: (1410): Reading authentication keys file.

2024/07/09 13:39:44 wazuh-modulesd:vulnerability-scanner: INFO: Triggered a re-scan after content update
2024/07/09 13:39:44 wazuh-modulesd:vulnerability-scanner: INFO: Feed update process completed
2024/07/09 13:51:03 wazuh-modulesd:vulnerability-scanner: ERROR: Error processing delayed event: [json.exception.parse_error.101] parse error at line 1, column 73: syntax error while parsing value - invalid literal; last read: '"no-index":true}<U+0006>'; expected end of input
2024/07/09 13:51:03 wazuh-modulesd:vulnerability-scanner: ERROR: Error processing delayed event: [json.exception.parse_error.101] parse error at line 1, column 73: syntax error while parsing value - invalid literal; last read: '"no-index":true}<U+0006>'; expected end of input
....
```

This indicates that the queries to Wazuh-DB during the re-scan weren't successful and some delayed events were scheduled. But then these events can't be parsed.
According to this, I added fake exceptions in the `SocketDBWrapper` to force delayed events. At the same time, I ran the agent simulator script but still, the error we were looking for didn't show up.

Maybe we should block the investigation until the Jenkins test is run again with more debugging details.

**Comment by sebasfalcone** [comment]
Thanks for the effort @pereyra-m 🦾 

## Issue blocked
Given that we weren't able to replicate the issue, we are going to wait for the new QA tests to be launched with better debugging

@Dwordcito We may close this issue and re-open it if neeeded

**Comment by sebasfalcone** [comment]
## Closed issue
Given that we weren't able to replicate the issue, even in highly stressed environments

We are going to wait for this test to be repeated in 4.10.0

@Rebits We need to set the corresponding flags in debug to improve the information available:
- wazuh_modules.debug=2
- wazuh_clusterd.debug=2
