### ISSUE TITLE
Analysis of vulnerabilities reported by @Lazlo on Slack

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#24624]
# Description

This issue is to investigate and implement a solution to improve the effectiveness of some tests marked as false negatives.

### CVE's

https://ubuntu.com/security/cve-2016-1585
https://ubuntu.com/security/cve-2018-14628
https://ubuntu.com/security/cve-2019-6461
https://ubuntu.com/security/cve-2020-25720
https://ubuntu.com/security/cve-2022-1615
https://ubuntu.com/security/cve-2022-28391
https://ubuntu.com/security/cve-2022-28653
https://ubuntu.com/security/cve-2022-32743
https://ubuntu.com/security/cve-2022-36227
https://ubuntu.com/security/cve-2022-45939
https://ubuntu.com/security/cve-2022-48174
https://ubuntu.com/security/cve-2022-48337
https://ubuntu.com/security/cve-2022-48339
https://ubuntu.com/security/cve-2023-37769
https://ubuntu.com/security/cve-2023-39810

### Inventory DB
[old_output (1).csv](https://github.com/user-attachments/files/16242936/old_output.1.csv)

### OS
ubuntu 22.04

**Comment by GabrielEValenzuela** [comment]
# Update

We made the analysis based on the user information and related CVE. We run the scanner for each package and get the following table

## Analysis

|        OS       | 
|-----------------|
| Ubuntu 22.04    |
| Jammy Jellyfish |



|     CVE       |      Package        |   Result                    | Ubuntu status |
|---------------|---------------------|-----------------------------|---------------|
| CVE-2016-1585 | apparmor | Match found, the package 'apparmor' is vulnerable to 'CVE-2016-1585' due to default status.  | Needed        |
| CVE-2018-14628| samba     | Match found, the package 'samba' is vulnerable to 'CVE-2018-14628' due to default status.  | Needed        |
| CVE-2020-25720| samba     | Content missing.  | Deferred        |
| CVE-2022-1615| samba     | Match found, the package 'samba' is vulnerable to 'CVE-2022-1615' due to default status.  | Needed        |
| CVE-2022-32743| samba     | Match found, the package 'samba' is vulnerable to 'CVE-2022-32743' due to default status.  | Needed        |
| cve-2019-6461 | cairo     | Match found, the package 'cairo' is vulnerable to 'CVE-2019-6461' due to default status.  | Deferred        |
| CVE-2022-28391| busybox | Match found, the package 'busybox' is vulnerable to 'CVE-2022-28391' due to default status.  | Deferred.        |
| CVE-2022-48174| busybox     | Match found, the package 'busybox' is vulnerable to 'CVE-2022-48174' due to default status.  | Needed        |
| CVE-2023-39810| busybox     |  Match found, the package 'busybox' is vulnerable to 'CVE-2023-39810' due to default status.  | Deferred        |
| CVE-2022-28653| apport     | Content missing.  | Needed        |
| CVE-2022-36227| libarchive     | Match found, the package 'libarchive' is vulnerable to 'CVE-2022-36227' due to default status.  | Needed        |
| CVE-2022-45939| emacs     | Match found, the package 'emacs' is vulnerable to 'CVE-2022-45939' due to default status.  | Needed        |
| CVE-2022-48337| emacs     |  Match found, the package 'emacs' is vulnerable to 'CVE-2022-48337' due to default status.  | Needed        |
| CVE-2022-48339| emacs     |  Match found, the package 'emacs' is vulnerable to 'CVE-2022-48339' due to default status.  | Needed        |
| CVE-2023-37769| pixman     | Match found, the package 'pixman' is vulnerable to 'CVE-2023-37769' due to default status.  | Deferred        |


## Conclusion

We notify them about the missing CVE to the corresponding team and check that most of the vulnerabilities have been found due to `default status`

**Comment by GabrielEValenzuela** [comment]
# Update

- Add PR with test case for emacs, samba and busybox

**Comment by GabrielEValenzuela** [comment]
# Update

- Add missing readme.

**Comment by sebasfalcone** [comment]
## Update ETA
Updated ETA so the final reviewer can see this issue

**Comment by Dwordcito** [comment]
The user indicates that the problem persists, please capture more data to solve it.


https://wazuh.slack.com/archives/C0A933R8E/p1722248750787279?thread_ts=1719222777.870679&cid=C0A933R8E

**Comment by sebasfalcone** [comment]
@Dwordcito Issues with the sanitization were wrongly closed

- https://github.com/wazuh/intelligence-data/issues/808
- https://github.com/wazuh/intelligence-data/issues/809

They are re-open so it should be addressed ASAP

**Comment by sebasfalcone** [comment]
## ETA updated
Commits in CTI are being delayed

**Comment by sebasfalcone** [comment]
## ETA updated
Commits in CTI are being delayed

**Comment by sebasfalcone** [comment]
## ETA update
@Damian-Mangold Hi, can we verify if the offsets for this CVEs are commited?

**Comment by Damian-Mangold** [comment]
> ## ETA update
> @Damian-Mangold Hi, can we verify if the offsets for these offsets are committed?
> 
> ## Added release
> This issue lacked a release, we added it to 4.10.0 where this test where implemented

@sebasfalcone, `CVE-2020-25720` and `CVE-2022-28653` sanitizations have already been published. Both CVEs are available in the content.

**Comment by sebasfalcone** [comment]
Thanks @Damian-Mangold!

## Closing issue
Given that sanitizations already impacted the content, we can close this issue
