### ISSUE TITLE
Benchmarking tests: Performance Statistical Data Analyzer

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#24688]
# Description

We need to develop a Performance Statistical Data Analyzer module capable of detecting performance regressions in our tests. This module should analyze statistical data collected during testing to identify any significant decreases in performance metrics compared to baseline benchmarks.

# Design

Based on the research conducted at https://github.com/wazuh/wazuh-qa/issues/5502, we have decided to use Python and its libraries to develop this analysis module by creating scripts. Libraries such as Pandas, NumPy, Matplotly, or Seaborn can be used.

This diagram can broadly represent the module:

```mermaid
graph LR

    Q[Metrics Data] --> P[Process Comparator]
    F1[Benchmark Baseline] --> P
    P --> R[Report]

    subgraph Statistical Data Analyzer
        P
    end    
```

## Functional requirements

- The metrics data coming into the module for comparison must be properly formatted according to the stipulations to match the baseline. So the module should include a pre-processing step to validate incoming data.
- The baseline benchmarks must be stored somewhere (for example in a database) to which the module has access and can extract the data.
- The module should compare current metrics data against the baseline benchmarks to detect significant performance regressions. Statistical methods must be used to identify regressions.
- After comparison, a report should be generated with the comparison results (HTML or, as possible, PDF). This report must highlight significant regressions and provide data to justify it. 

## Non-functional requirements

- The module must be optimized to handle large data sets efficiently.
- The module must be as easy to use as possible.
- The procedure for using the module must be documented.

## Validation

- Proof of Concept of analyzing data.

**Comment by MARCOSD4** [comment]
## Update

As a first approach, a script has been created that accepts two files by parameters, one with the reference data and the other with the data we want to analyze. First, a design has been made to calculate the most common statistical values of a set of data, such as the mean, median, variance, etc. These statistics are calculated for each demon and for each of the metrics to be analyzed. To show an example, we have taken data obtained from the footprint metrics for version 4.8.0 and a possible output for the modulesd daemon is the following:

<details><summary>Example</summary>

```console
+-----------------------------------------------------------------------------------------------------------------------------+
|                                                        wazuh-modulesd                                                       |
+-----------------+-----------------+----------------+--------------+-----------+--------------------+------------------------+
|      Metric     |       Mean      |     Median     |  Max value   | Min value | Standard deviation |        Variance        |
+-----------------+-----------------+----------------+--------------+-----------+--------------------+------------------------+
|      CPU(%)     |       1.59      |      0.0       |     36.0     |    0.0    |        3.25        |         10.54          |
|     RSS(KB)     |     63950.3     |    58896.0     |   109648.0   |  53968.0  |      10286.93      |      105820856.85      |
|     VMS(KB)     |    526381.62    |    520896.0    |   564928.0   |  480956.0 |      27108.54      |      734872769.56      |
|        FD       |      56.41      |      56.0      |      59      |     54    |        0.77        |          0.6           |
|     Read_Ops    |   911435874.09  |  892184496.5   |  1792467094  |   699170  |    414856573.26    | 1.7210597637788387e+17 |
|    Write_Ops    |   14091607.09   |   13161086.5   |   31064281   |    9190   |     7359236.91     |   54158367877016.23    |
|   Disk_Read(B)  |  2687930340.95  |  1941975040.0  |  5640837120  | 144569344 |   2172357506.77    | 4.719137137234522e+18  |
| Disk_Written(B) | 194084835138.89 | 203911350272.0 | 350919647232 |  18886656 |  122730598551.91   | 1.506279982090912e+22  |
|     Disk(%)     |       0.29      |      0.16      |     1.84     |    0.06   |        0.29        |          0.08          |
|     USS(KB)     |     55598.91    |    53112.0     |   101072.0   |   1588.0  |      14024.5       |      196686710.46      |
|     PSS(KB)     |     58105.58    |    54302.0     |   102147.0   |  20906.0  |      10755.87      |      115688786.75      |
|     SWAP(KB)    |       0.0       |      0.0       |     0.0      |    0.0    |        0.0         |          0.0           |
+-----------------+-----------------+----------------+--------------+-----------+--------------------+------------------------+
```

</details>

We would get a similar output for the rest of the demons.

Now, more complex statistical studies are needed on both data sets to allow us to compare them and obtain conclusions about possible changes in behavior. For example, we can use hypothesis tests such as the Student's t-test or the Mann-Whitney U test, which will allow us to conclude whether there are significant differences in the data or not, correlation analysis, to determine whether there is a relationship between two variables, etc. These analyses are being studied to check their effectiveness and to use them in the script.

**Comment by MARCOSD4** [comment]
After analyzing several statistical studies, the following conclusions have been reached:

- **Mann-Whitney U test**: this test has some limitations to be used in our use cases. To be effective, the data must meet a series of conditions: they must be independent, they must be ordinal or can be ordered from smallest to largest, they must have the same type of distribution and there must be equality of variances between the groups. Our data do not meet some of these conditions for most of the data, but in addition, this test is usually affected by the sample size. With large amounts of data, very small variations in the data can be considered as significant differences. All this makes the U-test not entirely effective for our study.

- **Student's t-test**: this test is robust to large amounts of data if they show deviations from normality. That is, for large amounts of data that do not exhibit normality, this test is usually effective. Moreover, it does not require the data to be ordinal.

- **Levene test**: is designed to be robust to non-normal distributions. It is mainly used to determine whether two sets of data have homoscedasticity, that is, they have the same variance, which can help us determine whether the data differ from each other.

The effectiveness of these tests has been verified with real data and indeed, the U-test indicated significant differences in the metrics of different versions when they were actually similar. However, when the t-test and Levene's test detected significant differences, after checking the graphs it was found that they were correct.

These tests will help us to detect when there are differences in the metrics analyzed for different versions, but they are not infallible and will have to be combined with other tests that still need to be studied.

<details><summary>Example</summary>

After comparing data from versions 4.8.0 and 4.8.1, we obtain the following results for the logcollector daemon:

```console
Metric 'VMS(KB)':
    - Mann-Whitney U Test: U-Statistic=585295740.5, p-value=3.242270652058079e-05
    - t-Student Test: t-Statistic=-0.19621690475839745, p-value=0.8444409847846539
    - Levene's Test: Statistic=0.03935100686551594, p-value=0.8427554917181669

  Significant difference detected in 'VMS(KB)' (Mann-Whitney U Test).

Metric 'Disk_Read(B)':
    - Mann-Whitney U Test: U-Statistic=591176316.5, p-value=9.582948617005977e-10
    - t-Student Test: t-Statistic=-6.719482773520405, p-value=1.8385351986887157e-11
    - Levene's Test: Statistic=419.0863015108946, p-value=7.371015690524063e-93

  Significant difference detected in 'Disk_Read(B)' (Mann-Whitney U Test).

  Significant difference detected in 'Disk_Read(B)' (t-Test).

  Variance difference detected in 'Disk_Read(B)' (Levene's Test).
```

To check their effectiveness, we proceed to compare the graphs of these metrics:

Although the U-test has detected significant differences, the VMS data are exactly the same:

![20240723170253_virtual_memory_comparison](https://github.com/user-attachments/assets/8712bc78-eeac-4002-9255-9bb0dbe48874)

However, when the t-test and Levene's test detect differences as well, the data are really different:

![20240723170212_disk_read_comparison](https://github.com/user-attachments/assets/cae34f17-1ff6-45b6-b427-b99608f0d8ab)

</details>

**Comment by Rebits** [comment]
Great approach!

To simplify the initial steps of this process, avoid using highly variable metrics like Disk(%), VM(%), and PSS(%), as these depend more on the overall state of the host rather than the actual performance of the manager/agent. Instead, I suggest focusing only on CPU and RSS metrics for now to create a more robust tool.

**Comment by MARCOSD4** [comment]
## Update

Research has continued on further statistical methods to help us identify discrepancies between different data sources. In this sense, the ANOVA test has also been used, which, broadly speaking, identifies when there are differences between the means of two or more variables. It behaves in a similar way to the t-student, since the larger the data, the more reliable the results if there is no normality. It also requires the variance between groups to be approximately equal. Again, we show an example of its use:

<details><summary>Example</summary>

```console
Daemon: wazuh-logcollector

ANOVA result for CPU(%):
  F-statistic: 0.9669343139587256
  p-value: 0.3254494499859697

ANOVA result for RSS(KB):
  F-statistic: 14.575775130293069
  p-value: 0.00013475383045110907

  Significant difference detected (p-value < 0.05). The means are significantly different.

ANOVA result for VMS(KB):
  F-statistic: 0.03850155636380295
  p-value: 0.8444400221443558

ANOVA result for FD:
  F-statistic: 0.2187079103120649
  p-value: 0.6400276961431309

ANOVA result for Read_Ops:
  F-statistic: 2.789363315143839
  p-value: 0.09489653473918858

...
```

Coincidentally, this test identifies significant differences in the same metrics as the t-test and the Levene test. There are only a few metrics that the three tests do not match, and it is only the Levene's test that does not appear, the t-test and ANOVA test always appear together. Thus, we have one more test to identify changing patterns.

</details>

We will now focus on analyzing the CPU and RSS metrics to check the efficiency of the results.

<details><summary>CPU and RSS analysis</summary>

```console
Daemon: wazuh-db


Metric 'CPU(%)':
    - t-Student Test: t-Statistic=3.445549549267306, p-value=0.0005702476835324906
    - Levene's Test: Statistic=6.7910105312839635, p-value=0.009163804074647057
    - ANOVA's Test: Statistic=11.879766149797552, p-value=0.000567814233352575

  Significant difference detected in 'CPU(%)' with 95% confidence (t-Test).

  Variance difference detected in 'CPU(%)' with 95% confidence (Levene's Test).

  Means difference detected in 'CPU(%)' with 95% confidence (ANOVA's Test).

Metric 'RSS(KB)':
    - t-Student Test: t-Statistic=137.59804255103867, p-value=0.0
    - Levene's Test: Statistic=2019.1907275801036, p-value=0.0
    - ANOVA's Test: Statistic=18886.36520388173, p-value=0.0

  Significant difference detected in 'RSS(KB)' with 95% confidence (t-Test).

  Variance difference detected in 'RSS(KB)' with 95% confidence (Levene's Test).

  Means difference detected in 'RSS(KB)' with 95% confidence (ANOVA's Test).



Daemon: wazuh-modulesd


Metric 'CPU(%)':
    - t-Student Test: t-Statistic=1.442775035691913, p-value=0.14908846981835702
    - Levene's Test: Statistic=2.0816108984858945, p-value=0.14908738606624963
    - ANOVA's Test: Statistic=2.0816108984858968, p-value=0.14908738606624963

Metric 'RSS(KB)':
    - t-Student Test: t-Statistic=75.4927175852933, p-value=0.0
    - Levene's Test: Statistic=104.16898098864301, p-value=1.9349362035516985e-24
    - ANOVA's Test: Statistic=5696.859842653444, p-value=0.0

  Significant difference detected in 'RSS(KB)' with 95% confidence (t-Test).

  Variance difference detected in 'RSS(KB)' with 95% confidence (Levene's Test).

  Means difference detected in 'RSS(KB)' with 95% confidence (ANOVA's Test).



Daemon: wazuh-integratord

Metric 'CPU(%)':
    - t-Student Test: t-Statistic=nan, p-value=nan
    - Levene's Test: Statistic=nan, p-value=nan
    - ANOVA's Test: Statistic=nan, p-value=nan

Metric 'RSS(KB)':
    - t-Student Test: t-Statistic=nan, p-value=nan
    - Levene's Test: Statistic=nan, p-value=nan
    - ANOVA's Test: Statistic=nan, p-value=nan



Daemon: wazuh-authd


Metric 'CPU(%)':
    - t-Student Test: t-Statistic=1.010753306041721, p-value=0.31213813898113585
    - Levene's Test: Statistic=1.0220832450302668, p-value=0.31202897157794973
    - ANOVA's Test: Statistic=1.0220832450302673, p-value=0.31202897157794973

Metric 'RSS(KB)':
    - t-Student Test: t-Statistic=-67.17603142339078, p-value=0.0
    - Levene's Test: Statistic=5086.727393874795, p-value=0.0
    - ANOVA's Test: Statistic=4523.964499296014, p-value=0.0

  Significant difference detected in 'RSS(KB)' with 95% confidence (t-Test).

  Variance difference detected in 'RSS(KB)' with 95% confidence (Levene's Test).

  Means difference detected in 'RSS(KB)' with 95% confidence (ANOVA's Test).



Daemon: wazuh-maild


Metric 'CPU(%)':
    - t-Student Test: t-Statistic=nan, p-value=nan
    - Levene's Test: Statistic=nan, p-value=nan
    - ANOVA's Test: Statistic=nan, p-value=nan

Metric 'RSS(KB)':
    - t-Student Test: t-Statistic=nan, p-value=nan
    - Levene's Test: Statistic=nan, p-value=nan
    - ANOVA's Test: Statistic=nan, p-value=nan



Daemon: wazuh-syscheckd


Metric 'CPU(%)':
    - t-Student Test: t-Statistic=0.3183517841802341, p-value=0.7502190876848073
    - Levene's Test: Statistic=0.00015870718847732154, p-value=0.9899486297574159
    - ANOVA's Test: Statistic=0.10135270127055568, p-value=0.7502133187461995

Metric 'RSS(KB)':
    - t-Student Test: t-Statistic=233.23958612880665, p-value=0.0
    - Levene's Test: Statistic=19.011818841145153, p-value=1.3010225948028802e-05
    - ANOVA's Test: Statistic=54462.068565305824, p-value=0.0

  Significant difference detected in 'RSS(KB)' with 95% confidence (t-Test).

  Variance difference detected in 'RSS(KB)' with 95% confidence (Levene's Test).

  Means difference detected in 'RSS(KB)' with 95% confidence (ANOVA's Test).



Daemon: wazuh-clusterd


Metric 'CPU(%)':
    - t-Student Test: t-Statistic=nan, p-value=nan
    - Levene's Test: Statistic=nan, p-value=nan
    - ANOVA's Test: Statistic=nan, p-value=nan

Metric 'RSS(KB)':
    - t-Student Test: t-Statistic=nan, p-value=nan
    - Levene's Test: Statistic=nan, p-value=nan
    - ANOVA's Test: Statistic=nan, p-value=nan



Daemon: wazuh-monitord


Metric 'CPU(%)':
    - t-Student Test: t-Statistic=-4.282517943342127, p-value=1.850909412287764e-05
    - Levene's Test: Statistic=18.2835723154853, p-value=1.9060124733380163e-05
    - ANOVA's Test: Statistic=18.283572315485262, p-value=1.9060124733380163e-05

  Significant difference detected in 'CPU(%)' with 95% confidence (t-Test).

  Variance difference detected in 'CPU(%)' with 95% confidence (Levene's Test).

  Means difference detected in 'CPU(%)' with 95% confidence (ANOVA's Test).

Metric 'RSS(KB)':
    - t-Student Test: t-Statistic=-36.548639549111954, p-value=2.0374826675632266e-289
    - Levene's Test: Statistic=5778.375241798576, p-value=0.0
    - ANOVA's Test: Statistic=1338.3504250339581, p-value=3.5668802396379207e-290

  Significant difference detected in 'RSS(KB)' with 95% confidence (t-Test).

  Variance difference detected in 'RSS(KB)' with 95% confidence (Levene's Test).

  Means difference detected in 'RSS(KB)' with 95% confidence (ANOVA's Test).



Daemon: wazuh-remoted


Metric 'CPU(%)':
    - t-Student Test: t-Statistic=-9.91160852335573, p-value=3.84325354614683e-23
    - Levene's Test: Statistic=20.46525779650717, p-value=6.082629525940791e-06
    - ANOVA's Test: Statistic=98.21161455467606, p-value=3.8984650538412055e-23

  Significant difference detected in 'CPU(%)' with 95% confidence (t-Test).

  Variance difference detected in 'CPU(%)' with 95% confidence (Levene's Test).

  Means difference detected in 'CPU(%)' with 95% confidence (ANOVA's Test).

Metric 'RSS(KB)':
    - t-Student Test: t-Statistic=43.389506999260234, p-value=0.0
    - Levene's Test: Statistic=657.2245860681658, p-value=2.9289126772259456e-144
    - ANOVA's Test: Statistic=1884.5014142904429, p-value=0.0

  Significant difference detected in 'RSS(KB)' with 95% confidence (t-Test).

  Variance difference detected in 'RSS(KB)' with 95% confidence (Levene's Test).

  Means difference detected in 'RSS(KB)' with 95% confidence (ANOVA's Test).



Daemon: wazuh-execd


Metric 'CPU(%)':
    - t-Student Test: t-Statistic=0.006385430970451877, p-value=0.9949052166084107
    - Levene's Test: Statistic=4.07733257384304e-05, p-value=0.9949052412071312
    - ANOVA's Test: Statistic=4.077332573842223e-05, p-value=0.9949052412071312

Metric 'RSS(KB)':
    - t-Student Test: t-Statistic=-16.662968184533838, p-value=3.2463398069774027e-62
    - Levene's Test: Statistic=396.36083843243114, p-value=6.092570130311116e-88
    - ANOVA's Test: Statistic=277.79493964374103, p-value=3.0209817250101137e-62

  Significant difference detected in 'RSS(KB)' with 95% confidence (t-Test).

  Variance difference detected in 'RSS(KB)' with 95% confidence (Levene's Test).

  Means difference detected in 'RSS(KB)' with 95% confidence (ANOVA's Test).



Daemon: wazuh-analysisd


Metric 'CPU(%)':
    - t-Student Test: t-Statistic=-0.5867834588461251, p-value=0.5573510997175561
    - Levene's Test: Statistic=1.1883139122559403, p-value=0.2756737951242809
    - ANOVA's Test: Statistic=0.3443250537280379, p-value=0.5573452465833635

Metric 'RSS(KB)':
    - t-Student Test: t-Statistic=-252.19582634377917, p-value=0.0
    - Levene's Test: Statistic=106.09434136690382, p-value=7.333786154984608e-25
    - ANOVA's Test: Statistic=63530.88562792323, p-value=0.0

  Significant difference detected in 'RSS(KB)' with 95% confidence (t-Test).

  Variance difference detected in 'RSS(KB)' with 95% confidence (Levene's Test).

  Means difference detected in 'RSS(KB)' with 95% confidence (ANOVA's Test).



Daemon: wazuh-logcollector


Metric 'CPU(%)':
    - t-Student Test: t-Statistic=-0.9834155401295885, p-value=0.32540647243412135
    - Levene's Test: Statistic=0.9669343139587011, p-value=0.3254494499859697
    - ANOVA's Test: Statistic=0.9669343139587256, p-value=0.3254494499859697

Metric 'RSS(KB)':
    - t-Student Test: t-Statistic=-3.8178159929385345, p-value=0.00013475785378330054
    - Levene's Test: Statistic=10.922490806547769, p-value=0.0009505300458784342
    - ANOVA's Test: Statistic=14.575775130293069, p-value=0.00013475383045110907

  Significant difference detected in 'RSS(KB)' with 95% confidence (t-Test).

  Variance difference detected in 'RSS(KB)' with 95% confidence (Levene's Test).

  Means difference detected in 'RSS(KB)' with 95% confidence (ANOVA's Test).
```

Now we will compare the logcollector graphs, in which supposedly only RSS has significant changes:

![20240724160742_cpu_comparison](https://github.com/user-attachments/assets/955dcf07-43de-4dcd-973f-f40846cef316)

![20240724160742_memory_comparison](https://github.com/user-attachments/assets/a8457669-cfd7-4d50-b0da-9d79396b7f96)

As we can see, RSS has a different behavior and CPU does not, in spite of having certain normal peaks in both versions.

We will now compare the remoted ones, both of which have differences:

![20240724161121_cpu_comparison](https://github.com/user-attachments/assets/c0800968-8c3a-44c8-a958-2e8b7331e5fe)

![20240724161121_memory_comparison](https://github.com/user-attachments/assets/f1e91fc5-7c29-4c62-8d21-47d09710b8ba)

Apparently, the CPU follows the same distribution and behaves similarly to the previous case. In this case, as the CPU values are smaller, it is possible that the tests are more sensitive and detect differences more easily, so the CPU has also been identified as changing from one version to another. It needs further research.

</details>

**Comment by MARCOSD4** [comment]
## Update

The focus of this module has been changed. Now, **Pytest** is used to run tests on two data sets and obtain an output with significant differences between them. For this, a test has been created in which first the results of the t-student, Levene, and ANOVA tests are checked. If any of them detect significant changes, then the test further checks for substantial changes in the statistics of the data sets, such as mean, variance, maximum value, etc. This ensures that, in addition to detecting changes with the statistical tests, changes are also detected between the statistical measures of both data sets, improving the accuracy of the module.

In addition, a parameter has been added that supports a `YML` file to define the demons, metrics, or statistics that we want to analyze, filter the analysis, and obtain more specific data.

The t-student, Levene, or ANOVA statistical tests use a percentage that represents the confidence level of the results. In addition, for the comparison of the statistics, a threshold value in percentage is used, so that, if the percentage difference between two statistics is greater than that threshold, then Pyest detects this as an error and reports it accordingly. Both values can be specified in the pytest run command, but by default, a confidence level of 95% and a threshold of 5% are set.

<details><summary>Example of use</summary><br>

To check that the module detects significant changes in the metrics, we will compare the Footprint data of VDR in 4.8.0-rc4 with those of VDR in 4.8.0-beta6, in which a significant memory leak was detected in FD and RSS for modulesd [here](https://github.com/wazuh/wazuh/issues/23202).

The YML file with the data we want to analyze is as follows:

```console
---
Daemons:
  - "wazuh-modulesd"
  - "wazuh-remoted"

Metrics:
  - "CPU(%)"
  - "RSS(KB)"
  - "FD"

Stats:
  - "Mean"
  - "Max value"
  - "Variance"
```

Now, we run the tests as follows (threshold and confidence level values are not specified because the default values of 5% and 95% are used):

```console
python3 -m pytest test_data_analyzer_module.py --baseline ./data/4.8.0-rc4-vdr.csv --datasource ./data/4.8.0-beta6-vdr-leak.csv --items_yaml ./data/items_to_compare.yml
```

And the output is:

```console
E           Failed: Difference over 5.0% detected in 'wazuh-modulesd' - 'CPU(%)' - 'Mean'
E           Difference over 5.0% detected in 'wazuh-modulesd' - 'CPU(%)' - 'Max value'
E           Difference over 5.0% detected in 'wazuh-modulesd' - 'RSS(KB)' - 'Mean'
E           Difference over 5.0% detected in 'wazuh-modulesd' - 'RSS(KB)' - 'Max value'
E           Difference over 5.0% detected in 'wazuh-modulesd' - 'RSS(KB)' - 'Variance'
E           Difference over 5.0% detected in 'wazuh-modulesd' - 'FD' - 'Mean'
E           Difference over 5.0% detected in 'wazuh-modulesd' - 'FD' - 'Max value'
E           Difference over 5.0% detected in 'wazuh-modulesd' - 'FD' - 'Variance'
E           Difference over 5.0% detected in 'wazuh-remoted' - 'RSS(KB)' - 'Variance'
```

If we increase the threshold value to 50:

```console
python3 -m pytest test_data_analyzer_module.py --baseline ./data/4.8.0-rc4-vdr.csv --datasource ./data/4.8.0-beta6-vdr-leak.csv --items_yaml ./data/items_to_compare.yml --threshold 50

E           Failed: Difference over 50.0% detected in 'wazuh-modulesd' - 'RSS(KB)' - 'Variance'
E           Difference over 50.0% detected in 'wazuh-modulesd' - 'FD' - 'Mean'
E           Difference over 50.0% detected in 'wazuh-modulesd' - 'FD' - 'Max value'
E           Difference over 50.0% detected in 'wazuh-modulesd' - 'FD' - 'Variance'
```

The results are expected due to the memory leak mentioned above.

</details>

**Comment by MARCOSD4** [comment]
## Update

### PoC

The design of the statistical data analysis module is as follows: the module will be launched using a Pytest test, which will be provided with a `YML` file containing the demons, metrics, and statistics to be analyzed, as explained in the previous comment. In addition, to make the analysis even more concrete and accurate, the threshold value from which the statistics comparisons are made will now be in the `YML` file and will be unique for each statistic. This is convenient because, depending on the metric and statistic, one threshold or another will be required.

In addition, in the report generated by Pytest, besides indicating those statistics that exceed the established difference threshold, a file with all the statistics has been added so that the data can be visualized manually.

Reminder: The way the tests work is as follows: first check whether any of the statistical tests (t-student, Levene, or ANOVA) detect any significant difference in the data. In affirmative case, we proceed to compare the statistics (mean, maximum value, variance, etc.) of each metric according to the threshold. If the threshold is exceeded, pytest marks it as an error and reports it accordingly.

<details><summary>Example</summary><br>

The `YML` file used for the analysis will be the following:

```console
---
Daemons:
  - "wazuh-modulesd"
  - "wazuh-remoted"

Metrics:
  CPU(%):
    Mean: 10
    Max value: 15
    Variance: 10

  RSS(KB):
    Mean: 10
    Max value: 25
    Variance: 5

  FD:
    Mean: 15
    Max value: 25
    Variance: 5
```

The command that launches the test will be as follows (the `--confidence_level` parameter is not passed as it is assumed to be 95 by default):

```console
python3 -m pytest test_data_analyzer_module.py --baseline ./data/4.8.0-rc4-vdr.csv --datasource ./data/4.8.0-beta6-vdr-leak.csv --items_yaml ./data/items_to_compare.yml --html=report.html
```

The results in the Pytest report are these:

![image](https://github.com/user-attachments/assets/e2fc9a5d-2cd8-430e-b53f-aebbb2c91717)

If we click on the link, we will be able to see all the specific statistics:

![image](https://github.com/user-attachments/assets/24807d4e-b74b-4b31-9149-d1a981ced3eb)

[report.zip](https://github.com/user-attachments/files/16414460/report.zip)

</details>

We are currently working on a Readme with the relevant information of this module and on unit tests for this module.

**Comment by MARCOSD4** [comment]
The code has been refactored to separate the library with the essential classes and methods from the script module, and its functionality has been changed to allow the analysis of any process, and not only of daemons as it was initially done. In addition, docstrings and comments have been added respecting the PEP8 standards. Unit tests have also been performed to verify the correct operation of the methods.

**Comment by rafabailon** [comment]
### LGTM

**Comment by Rebits** [comment]
Delayed ETA to review the development to 05/09/2024

**Comment by MARCOSD4** [comment]
Moved to On hold in favor of https://github.com/wazuh/wazuh/issues/25270

**Comment by MARCOSD4** [comment]
On hold due to https://github.com/wazuh/wazuh/issues/25403

**Comment by Rebits** [comment]
Delayed in order to allow final review to 18/09/2024
