### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by m2ura** [wazuh/wazuh#2468]
Hello,
Installation was completed with no errors, but I don't see any documentation on how to start it up, and show the GUI. How can I get to see the GUI?. I'm new to Wazuh.

**Comment by alberpilot** [comment]
Hello @m2ura 

  When you say the GUI you're talking about this, right?

![image](https://user-images.githubusercontent.com/3830293/51791492-43f51880-21a4-11e9-834b-17e79e02ebb1.png)

In that case, you need to follow the instructions below:
https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/index.html

We made integration with Elasticsearch, Logstash, and Kibana in order to have a complete stack for efficient and comfortable searching and manage tool. 
Please, let us know if you need further assistance.

**Comment by alberpilot** [comment]
Hello @m2ura 

  Due to inactivity, I will proceed to close this issue. Please feel free to re-open it if you need further information. 

Best regards,
