### ISSUE TITLE
Restart manager when the ruleset is synchronized or pushed from the API

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh#2474]
Restart the managers from the API/cluster.

##### Cluster level
If the ruleset is changed in the master node, it is pushed in the worker nodes but they are not restarted so the configuration is not applied. For this use case, we will use the API to restart the cluster and apply changes.

##### API level
The API allows putting new files (_decoders_, _rules_, _lists_, _ossec.conf_) in a manager/node using the `/files` call (https://github.com/wazuh/wazuh-api/issues/283, https://github.com/wazuh/wazuh-api/issues/297). It is necessary a new call to restart the nodes in order to apply the configuration:
```
PUT /manager/restart
PUT /cluster/:node_id/restart
PUT /cluster/restart
```

#### Restarting process
1. Run `logtest` to very the syntax of decoders/rules/ossec.conf.
2. Restart the manager running _ossec-control_ throught _execd_.

**Comment by druizz90** [comment]
Hi, I am able to restart the manager by sending a message to `execd` socket, but it is necessary to configure an `active-response` in `ossec.conf` as the next:

```
<active-response>
   <command>restart-ossec</command>
   <location>server</location>
   <level>15</level>
   <timeout>600</timeout>
 </active-response>
```

It could be possible to do this without edit `ossec.conf` @wazuh/core ?

**Comment by druizz90** [comment]
Hi, @wazuh/core it is possible to call to `logtest` using a socket? How can I verify the syntax by using `logtest` from rules, decoders and `ossec.conf`

**Comment by vikman90** [comment]
Hi @druizz90,

Let me answer your questions:

1. Currently, running commands through Execd requires Active Response enabled. In fact, we are running an AR request.

The agent has the same problem: https://github.com/wazuh/wazuh/blob/master/src/client-agent/restart_agent.c#L45

If you want to force restart the manager, you may bypass Execd and call the _ossec-restart_ AR script: https://github.com/wazuh/wazuh/blob/master/active-response/restart-ossec.sh.

It simply calls `ossec-control restart`. If you call it, you will take advantage of the improvements we shall apply, like replacing `ossec-control` with the proper call to `systemctl` on Systemd based platforms.

2. No, I'm afraid _ossec-logtest_ does not accept socket call because it's not a daemon. The best way IMO is calling it directly and use the _stdin_/_stdout_ streams to interchange data with it.

I think this is the better approach because:
- If _ossec-logtest_ had a socket, you still need to run it. If we execute it, pipes are easier than sockets.
- If we implemented a socket for log testing in Analysisd we would need to restart it for applying the new ruleset.

Hope it helps.
Cheers.

**Comment by crd1985** [comment]
Hi all.

Moving this issue to 6th week milestone.

Reason: we have to decide how to implement the restart, so we need to solve the dilemma of using sockets o calling a script.

**Comment by druizz90** [comment]
## Issue update (04/02/2019)

### Summary

The next calls have been implemented and work properly:

 ```PUT /manager/restart
PUT /cluster/:node_id/restart
PUT /cluster/restart```

We use `execq` for restarting managers.

### Pending

- Run `logtest` to very the syntax of decoders/rules/ossec.conf.

**Comment by druizz90** [comment]
I am trying to find the way to get the confirmation message when Wazuh manager is restarted by using a socket. I created a new script for restarting Wazuh managers.

**Comment by druizz90** [comment]
## Issue update (05/02/2019)

### Summary

I worked for getting a confirmation when manager is restarted. I tried it by sending a message by `execq` socket, but sockets dead when manager is restarted.

I developed other solution: a temporary file which is written with a message (`OK` or `KO`) if the manager has been restarted successfully. It is necessary to put a delay (10 seconds aprox) when for checking that restarting has been successfully.

I made a script called `restart-wazuh.sh` for launch `logtest` before restarting (if `logtest` fails, the manager will not restart).

My work is in branch `dev-restart-manager-api`.

### Pending

- Consider other options (or validate my solution). It may be possible to make a socket which never dead when Wazuh manager restarting?

- Mocha tests.

- Unit tests.

**Comment by druizz90** [comment]
## Issue update (06/02/2019)

### Summary

I created two scripts for restarting Wazuh (for managers and agents).

We thought that a new call for checking configuration in API was necessary.

When we restart manager from API, we don't wait for a response.

Unit tests were made.

### Pending

- Review of the new call.

**Comment by druizz90** [comment]
## Issue update (12/02/2019)

### Summary

I replaced the scripts for restarting manager and agents by an unique script for both.
