### ISSUE TITLE
ERROR: Upgrade aborted: Unexpected version in the new ruleset. Expected version v3.7.x. Found version v3.8.1

### ISSUE THREAD

**Issue by crakerkai** [wazuh/wazuh#2487]
Hello,

Currently, I had met an issues like that:
`[root@WAZUH bin]# ./update_ruleset`
`### Wazuh ruleset ###`
`ERROR: Upgrade aborted: Unexpected version in the new ruleset. Expected version v3.7.x. Found version v3.8.1`
Please help me to explain what is the issues and how can I update after fixing it?
I hope to receive your response soon.

Thanks,
Pm

**Comment by vikman90** [comment]
Hi @crakerkai,

**Comment by vikman90** [comment]
|Duplicate|
|---|
|#577|

Hi @crakerkai,

That error appears because _upgrade_ruleset_ tries to check out the latest version of the ruleset, but your version of Wazuh is incompatible.

Currently, the latest version of the ruleset is 3.8.1, you probably have Wazuh 3.7.0, 3.7.1 or 3.7.2.

If we want to update an older version of the ruleset (3.7.x in this case), we can define that with the option `-m`, this way:

```shell
# /var/ossec/bin/update_ruleset -b 3.7
### Wazuh ruleset ###
Restoring ruleset backup:
ERROR: No backups availables. Exiting...
[root@centos src]# /var/ossec/bin/update_ruleset -n 3.7
### Wazuh ruleset ###

You already have the latest version of ruleset.
```

Upgrading to the latest minor version of Wazuh (3.8 currently) is required to get the latest ruleset. We are currently releasing versions of Wazuh and the ruleset at the same time, so I recommend you a full upgrade of Wazuh when possible.

Hope it helps.
Best regards.

**Comment by crakerkai** [comment]
Hi @vikman90 ,
Sorry for the late reply. Our country has just had a long vacation :)
As you explain, my current version is 3.7.2 so I can only update to version 3.7. So this is the result after update:
`[root@WAZUH bin]# cat ../etc/ossec-init.conf`
`DIRECTORY="/var/ossec"`
`NAME="Wazuh"`
`VERSION="v3.7.2"`
`REVISION="3727"`
`DATE="Thu Dec 13 20:20:11 UTC 2018"`
`TYPE="server"`
`[root@WAZUH bin]# ./update_ruleset -n 3.7`
`### Wazuh ruleset ###`

`You already have the latest version of ruleset.`
Thanks for your explaintation. 

Best regard,
Pm

**Comment by vikman90** [comment]
Hi @crakerkai.

Glad that worked for you. We have definitely to make this tool easier and extend the support of the ruleset beyond the same minor version.

On the other hand, we are currently performing parallel releases of Wazuh and the Ruleset, so the _update_ruleset_ tool is only useful if you need to upgrade a patch version of the ruleset without upgrading the manager.

Let me close this issue.
Best regards.
