### ISSUE TITLE
Incorrect agents returned by endpoint for outdated agents

### ISSUE THREAD

**Issue by lucianogorza** [wazuh/wazuh#24914]
|Wazuh version|Component|
|---|---|
| 4.9.0 - Alpha 3 | API |

## Description
The endpoint responsible for retrieving outdated agents is returning agents that are actually up-to-date for certain operating systems.

**Steps to Reproduce:**
1. Call the [endpoint](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.get_agent_outdated) to retrieve outdated agents with `q` parameter to filter by agent ids.
2. Inspect the response.
3. Observe that some agents listed as outdated are, in fact, up-to-date on specific operating systems.

## Actual Behavior
The endpoint is returning agents that are up-to-date for some operating systems, causing inaccurate data to be provided.

![image](https://github.com/user-attachments/assets/1240f4d8-7273-4ff5-8f1f-6131bc6ee5ed)

### Payload
![image](https://github.com/user-attachments/assets/d83c3aa8-e22b-4ad8-86aa-f2fd90ea01de)

### Response
![image](https://github.com/user-attachments/assets/fbdfe582-fd2b-4c91-a66f-4c127d53c755)

## Expected Behavior
The endpoint should only return agents that are genuinely outdated across all specified operating systems. 

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

The error ocurred because the query was appended as is, and any OR parameter included in it would invalidate the version check.

The code did

```
query=f"version!={manager.version}" + (';' + q if q else ''),
```

If we provide the parameters mentioned in the description, the query would result in

```
version!=v4.9.0;id=001,id=002,id=003
```

> Returns outdated agent with the iD `001` or agents with the ID `002` or `003`.

The OR separator (`,`) is invalidating the version check, so the agents `002` and `003` will be returned regardless of their version.

I modified the query to wrap the appended query inside a parenthesis, so the new end query would be

```
version!=v4.9.0;(id=001,id=002,id=003)
```

> Returns outdated agents with the ID `001`, `002` or `003`.

Effectively making sure that the response will contain those agents only if they are outdated.

**Comment by GGP1** [comment]
## Update

Reviewed the failed API integration tests.
