### ISSUE TITLE
Entire cluster crash caused by large CBD list

### ISSUE THREAD

**Issue by pbassill** [wazuh/wazuh#24980]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.1 | Indexer | Manager | Ubuntu Packages | Ubuntu 24.04 LTS |

Our indexers run with 32GB of RAM and 16 cores. Indexer data is held on high performance SSD's.

Our managers run with 32GB of RAM and 8 cores. /var/ossec is mounted on high performance SSD's.

On on our managers, we deployed the following cdb's:

|List|Count|
|---|---|
|blacklist-alienvault|609|
|common-ports|205|
|known-scanners|14519|
|malware-hashes|41680893|

Operation of Wazuh is perfect. However, navigating to Server Management -> CBD Lists in the web UI causes the indexers to fail.

Service is restored by restarting all indexers and then all managers.

**Comment by TheCulturedSwine** [comment]
I have a similar to you issue as well, I made a 2GB CDB of malware hashes from VirusShare, turns out, I was getting (oom-kill) out of memory errors, You might want to check wazuh-manager's memory usage as it loads the CDB. My CDB was using 12GBs and counting. As it kept crashing had to abandon that idea. I don't know why it needs that much memory to load the CDB.

**Comment by davidjiglesias** [comment]
We do not support these kind of huge files and we are moving in a different direction with Wazuh 5.0.
