### ISSUE TITLE
False positive of vulnerabilities reported by @Markus on Slack

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#24997]
## Description
A community user has reported that version 4.8.0 of the vulnerability detector incorrectly reports some vulnerabilities. This issue aims to investigate these reports, verify the accuracy of the vulnerability detections, and address any discrepancies.

```
Hello so again here are some information to specify my problem:

We are using a production system which is now on the latest 4.7.x release and a test system on the latest 4.8.x. We would like to get the production system up to the new release but the vulnerability detection module is still quite strange. Why are these vulnerability detection modules are getting different information?

Both systems are built distributed: manager - 2x index - dashboard.
Both systems are completely built on debian12 (bookworm)

Comparison wazuh 4.7.4-1 und wazuh 4.8.1-1

Endpoints for comparison: wazuh-dashboard - debian12 (bookworm) with wazuh agent, full patched based on distro stable release.

Vulnerabilities:
On 4.8.x: 3 Critical (one is based on qemu... proxmox in the test environment) , 84 High, 153 Medium, 88 Low
On 4.7.x: 0 Critical, 22 High, 1 Medium, 4 Low

Critical packages ONLY in 4.8.x:
Paket: zlib1g ~ 1:1.2.13.dfsg-1 --- CVE-2023-45853
Paket: python3-certifi ~ 2022.9.24-1 all --- CVE-2023-37920

Both packages are analyzed by the debian team and are either unimportant (CVE-2023-37920) or ignored (CVE-2023-45853).
4.7.x don't show these vulnerabilities, so i believe the result on the dashboard is based on the OVAL feed of debian?!
4.8.x show theses ones...
Where is 4.8.x getting its oval feeds?
Like, is 4.8.x merging the feed of NVD and Debian? That would lead to exclude the filter capabilities of the debian security team. I would prefer to get the feed ONLY from debian, which is my source of truth.

The high number of vulnerabilities makes debian unusable on production systems if an CISO is going crazy about vulnerabilities. And it wont help because the high number just leads to vulnerability fatigue. And that's with an operating system, debian, which is rock solid and stable.

Greetings,
Markus
```

```
Hi Markus,

> Why are these vulnerability detection modules getting different information?
The Wazuh version 4.8 includes a refactor of the vulnerability detection module. This refactor brings improvements to the detection mechanism, simplifies the configuration of the module, and introduces changes to the vulnerability feed.

> Both packages are analyzed by the Debian team and are either unimportant (CVE-2023-37920) or ignored (CVE-2023-45853).
The Debian feed we use is [this one](https://security-tracker.debian.org/tracker/data/json). It contains the same information displayed on [Debian Security Tracker](https://security-tracker.debian.org/). As you can see, both CVEs you mentioned are marked as "vulnerable" for "bookworm," which is why they are identified as such. The "urgency" is not considered in the feed; whether the vulnerability is more or less urgent, it is still marked as vulnerable.
Do you consider that a vulnerability with a low urgency or unimportant should not be a vulnerability?

> Like, is 4.8.x merging the feed of NVD and Debian?
The manager uses multiple feeds and selects the most appropriate one based on the OS being analyzed. For Debian, only the Debian feed is used.

> The high number of vulnerabilities makes Debian unusable on production systems if a CISO is going crazy about vulnerabilities.
Thanks to community reports like yours, we identified an improvement in the Debian vulnerability content. This improvement includes correct source-to-binary expansion and a correction of versions associated with binaries, which will reduce many false positives currently being detected. You can find the issue identifying the problem [here](https://github.com/wazuh/wazuh/issues/24306). The implementation of these changes has already been applied, and we are currently testing the updates in the content. We expect to make these updates available to managers in the coming days.
Regarding the request to "know" or "filter" certain vulnerabilities, the request for this new functionality has been elevated and is currently under management review.
If possible, could you please share the following so we can analyze all detected vulnerabilities on your agent and identify if there are any other issues with the feed or the vulnerability detector?
- [OS information](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_os_info)
- [Package inventory](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_packages_info)
- Vulnerability inventory
```

```
Hi Damian,
Thanks for your reply and the information.
I did some research on the debian security tracker to answer your question:
"Do you consider that a vulnerability with a low urgency or unimportant should not be a vulnerability?"

And yes i consider that a "vulnerability" marked as unimportant is not a vulnerability. A low vulnerability is a vulnerability!
So here is my explanation:

Based on the debian security team (https://security-team.debian.org/security_tracker.html), new issues are in a processing or TODO state. This means:
"Processing TODO entries means checking if the problem affects Debian and if so which packages, as well as evaluate their severity. This information is based on research and not just in the CVE description in order to prevent integrating false positives or incorrect data in the security tracker. For example, if the CVE id says that something is vulnerable prior to version X, you need to check if that is the case as well as for the information given on distribution specific issues. Always make sure you understand the issue and are able to verify that the information is correct.

Thus, a proper research should include reading the code, finding fixes/commits in the upstream repository, or even writing patches yourself if you have the time and skills to do that. If you can't assure that, please add a TODO entry reflecting what is missing from your research." (https://security-team.debian.org/security_tracker.html#processing-todo-entries)

The debian security team evaluate the severity. Based on the severity description:
"unimportant: This problem does not affect the Debian binary package,...
All "non-issues in practice" fall also into this category, like issues only "exploitable" if the code in question is setuid root..." (https://security-team.debian.org/security_tracker.html#severity-levels)

Debian itself filters security issues for their stable suite tracker (https://security-tracker.debian.org/tracker/status/release/stable). Following filters are set:
- high
- medium
- low
- not yet assigned
So the important part is the research about how it affects debian. In other words, if i would not use debians research, i would need to do this by myself for EVERY vulnerability mentioned by wazuh. But that is not feasible! In practice this means to spend full time in reading code to tell the CISO if a vulnerability affects debian or not. But for my understanding, wazuh should only mentioned vulnerability which affect debian so that i can then think about workarounds (if no update is applicable).

For the debian security tracker in json (https://security-tracker.debian.org/tracker/data/json) it means, you should filter the result as shown in the stable suite to prevent integrating false positives or incorrect data.

Greetings,
Markus
```

### Related issue
 - https://github.com/wazuh/wazuh/issues/24448

## Context
Accurate vulnerability detection is critical for maintaining the security and reliability of systems. Incorrectly reported vulnerabilities can lead to unnecessary concerns or, conversely, missed critical security issues. It is essential to thoroughly investigate these reports to ensure the detector's reliability and trustworthiness.

## Expected
Analyse the reported problem and define action items if necessary.

**Comment by lixmx** [comment]
Here is little follow up to this issue based in the three critical vulnerabilities found by wazuh on debian12 (bookworm)

CVE-2023-45853 - Notes: "[bookworm] - zlib <ignored> (contrib/minizip not built and src:zlib not producing binary packages)"
-> so this is not tagged with a severity of "unimportant" BUT with a "not yet assigned*" ( the * is important) AND is tagged with NODSA - ignored

CVE-2023-37920 - Notes: "Debian's python-certifi is patched to return the location of Debian-provided CA certificates"
-> its tagged as unimportant! -> wont show up if filtered.

CVE-2022-36648 - Notes: "[bookworm] - qemu <postponed> (Minor issue, revisit when fixed upstream)"
-> same as the first one above BUT with NODSA - postponed


Here the JSON-Tracker raw Example for the first vulnerability.

zlib - CVE-2023-45853:
"CVE-2023-45853":{"description":"MiniZip in zlib through 1.3 has an integer overflow and resultant heap-based buffer overflow in zipOpenNewFileInZip4_64 via a long filename, comment, or extra field. NOTE: MiniZip is not a supported part of the zlib product. NOTE: pyminizip through 0.2.6 is also vulnerable because it bundles an affected zlib version, and exposes the applicable MiniZip code through its compress API.","debianbug":1054290,"scope":"local","releases":{"bookworm":{"status":"open","repositories":{"bookworm":"1:1.2.13.dfsg-1"},"urgency":"not yet assigned","nodsa":"contrib/minizip not built and src:zlib not producing binary packages","nodsa_reason":"ignored"},"bullseye":{"status":"open","repositories":{"bullseye":"1:1.2.11.dfsg-2+deb11u2","bullseye-security":"1:1.2.11.dfsg-2+deb11u2"},"urgency":"not yet assigned","nodsa":"contrib/minizip not built and src:zlib not producing binary packages","nodsa_reason":"ignored"},"sid":{"status":"resolved","repositories":{"sid":"1:1.3.dfsg+really1.3.1-1"},"fixed_version":"1:1.3.dfsg-2","urgency":"not yet assigned"},"trixie":{"status":"resolved","repositories":{"trixie":"1:1.3.dfsg+really1.3.1-1"},"fixed_version":"1:1.3.dfsg-2","urgency":"not yet assigned"}}}}

Tracker JSON:
Critical vulnerability?! - zlib: CVE-2023-45853
JSON Keys:Value

    zlib:
        CVE-2023-45853:
            releases:
                bookworm:
                    status: open
                    urgency: not yet assigned
                    nodsa:
                    nodsa_reason: ignored


Critical vulnerability?! - python-certifi: CVE-2023-37920
JSON Keys:Value

    python-certifi:
        CVE-2023-37920:
            releases:
                bookworm:
                    status: open
                    urgency: unimportant


Critical vulnerability?! - qemu-agent: CVE-2023-37920
JSON Keys:Value

    qemu:
        CVE-2022-36648:
            releases:
                bookworm:
                    status: open
                    urgency: not yet assigned
                    nodsa:
                    nodsa_reason: postponed


So for classification of issues we have another state with 2 sub-states for: "Issues not warranting a security advisory" (https://security-team.debian.org/security_tracker.html#issues-not-warranting-a-security-advisory)
nodsa = "...issue might not warrant an (immediate) security advisory, for example if its severity is minor."
ignored = "...totally ignored, and no updates will be provided for it,..."
postponed = "...deserves an update via a security advisory, but it is not needed to release an advisory..."

As you can see these states are important with the three CRITICAL vulnerabilities on debian with wazuh 4.8.x. But none of these is worth to be classified as critical.
Debian itself classify theses vulnerabilities as minor issues at most.

So if i think about it it should be a filter like that based on the Json Tracker:

urgency:
activated filter:

    high
    medium
    low
    not yet assigned

for "not yet assigned"
filter out:

    nodsa:
    nodsa_reason: ignored
    nodsa_reason: postponed

Actually thats the exact default filter list for the stable suite. (https://security-tracker.debian.org/tracker/status/release/stable)

Greetings
Markus

**Comment by jftuduri** [comment]
Based on the insight provided by @lixmx and the analysis of the previous comment, the current treatment of Debian vulnerabilities could be improved by considering the `urgency` and `nodsa_reason` fields.
Proposed changes:

Status | Urgency | nodsa_reason | Current output | Proposed output
-- | -- | -- | -- | --
Open | unimportant | (Not applicable) | affected | **unaffected**
Open | not yet assigned | "ignored" | affected | **unaffected**
Open | not yet assigned | "postponed" | affected | **unknown**(*)
Open | not yet assigned | "" (empty string) | affected | **unaffected**
Open | not yet assigned | not present | affected | **affected**

(*) Could also be unaffected. Either way it will not be reported by the scanner.

Quick references:
`unimportant`: https://security-team.debian.org/security_tracker.html#severity-levels
![image](https://github.com/user-attachments/assets/a894f555-49d0-4064-988f-ff5232b9fd93)

No Advisory: https://security-team.debian.org/security_tracker.html#issues-not-warranting-a-security-advisory
![image](https://github.com/user-attachments/assets/e07242f9-a3b2-4c0e-84f5-8f7f67a977f3)

**Comment by Damian-Mangold** [comment]
Update: pending final review.

**Comment by marcinliszka12** [comment]
Hey. I observed the same issue with CVE-2024-5535,

**Comment by jftuduri** [comment]
Hi @marcinliszka12!
Thanks for reporting this.
I checked the output of the fix under development and indeed this CVE will no longer be reported for Debian once the fix is released.
Regards!

**Comment by marcinliszka12** [comment]
Hi @jftuduri Thank you for confirmation. Do you know if this fix will be added to next Wazuh release?

**Comment by Damian-Mangold** [comment]
>Hi @jftuduri Thank you for confirmation. Do you know if this fix will be added to next Wazuh release?

Hi @marcinliszka12. The vulnerability content updates are independent of the Wazuh versions. We are continuously applying improvements to the content, which are then released for consumption.

The implementation phase is now complete, and we are beginning the testing phase. Once the tests are completed, the new content will be published and you will be able to access it automatically. However, I will let you know when the new content is published so that you are aware of it.

**Comment by marcinliszka12** [comment]
hmm so it looks that it will be added to Wazuh version 5.0.0?

**Comment by Damian-Mangold** [comment]
Update: Implementation completed. Awaiting publication of new content.

**Comment by marcinliszka12** [comment]
so does it should work right now?

**Comment by Damian-Mangold** [comment]
Hi @marcinliszka12, when the new content is published, it will be reported here.

**Comment by Damian-Mangold** [comment]
Update: Implementation completed. Awaiting publication of new content.

**Comment by Damian-Mangold** [comment]
Update: Implementation completed. Awaiting publication of new content.

**Comment by Damian-Mangold** [comment]
Update: Implementation completed. Awaiting publication of new content.

**Comment by marcinliszka12** [comment]
When the content will be published? :)

**Comment by Damian-Mangold** [comment]
Hi @marcinliszka12,  we are working on the last details. In the course of Q4 it will be published!

**Comment by marcinliszka12** [comment]
thank you for a lot for response!

**Comment by Damian-Mangold** [comment]
Update: Awaiting publication of new content.

**Comment by Damian-Mangold** [comment]
We need to add efficacy test.

**Comment by Damian-Mangold** [comment]
Efficacy test added.
