### ISSUE TITLE
Indexer connector selector to initialize the alerts mode

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#25119]
## Description
In order to select the algorithm to execute the indexation algorithm introduced in https://github.com/wazuh/wazuh/issues/24352 we need add a parameter in the IndexerConnector algorithm to select between the "Single and ordered algorithm" or the "multi and unordered" dispatcher.

## Expect
- New parameter in the constructor
- Interface change with a default value (SINGLE AND ORDERED)
- selection of the ThreadDispatchQueue based on this runtime parameter for the m_dispatcher instance.
- ++ PLUS remove m_initializeThread.

**Comment by pereyra-m** [comment]
## Update

I begin with the implementation. First, I analyze the recent changes that added the class that needs to be updated.

**Comment by pereyra-m** [comment]
## Update

I request more details.

Hello @Dwordcito , I'd like to confirm my interpretation of the issue.
Are we going to have only two fixed modes, single and multi? If this is the case, what is the expected number of threads of the second one, maybe four? Or maybe the client of the class could select between some more modes (multi-2, multi-4, etc.)?

Another option is that the value is completely arbitrary. If this is the case, maybe we should review the recent changes in `ThreadEventDispatcher` because the `TNumberOfThreads` parameter is templetized so I can't select on runtime a class type that wasn't generated at compile time.

**Comment by pereyra-m** [comment]
## Update

The issue is on hold due to higher priority issues.

**Comment by pereyra-m** [comment]
## Update 

I continue with the implementation.
Now that the additional changes are approved, I'll update all the required classes.

**Comment by pereyra-m** [comment]
## Update

I continue testing the changes in the utils class. I'll try to overcome some limitations of the previous implementations.

**Comment by pereyra-m** [comment]
## Update

Changes after review.

**Comment by pereyra-m** [comment]
## Update

I rebase the PR and solve the merge conflicts.
