### ISSUE TITLE
Footprint - Isolated increase in events dropped by sycheckd in the manager

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#25192]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-Beta2 | Wazuh component | Manager | Packages | CentOS |

Testing [Release 4.9.0 - Beta 2 - Footprint Metrics - SYSCHECK (2.5d)](https://github.com/wazuh/wazuh/issues/25154), an increase in events dropped by sycheckd in the manager since Beta 1 was found.

The pattern of increasing dropped events continued in Beta 2 in isolation.
There is no change in other values, it is an isolated growth in a single phase

[v4.9.0-beta2](https://github.com/wazuh/wazuh/issues/25154)
![image](https://github.com/user-attachments/assets/55435ceb-0aa8-4069-a20f-b572c20d4e6b)

[v4.8.1-rc2](https://github.com/wazuh/wazuh/issues/24467)
![image](https://github.com/user-attachments/assets/8369f441-9c86-47d8-ba4d-9e14f22348d0)

[v4.9.0-beta1](https://github.com/wazuh/wazuh/issues/25040)
![image](https://github.com/user-attachments/assets/8fa10764-e840-4e7d-986e-d7a7ea218db8)

Analysis is required to define whether this new pattern may be associated with any anomalous behavior.

**Comment by juliancnn** [comment]
### Managaer analysis

The loss of events is due to the syscheck queue being full at 6:40 am on 8/11, this can be seen in the queue status graphs:

![queue state](https://github.com/user-attachments/assets/4c8960ac-f5d5-4e2f-84dc-b1b121a5dca1)

The syscheck event decoding rate is constant, throughout the test:
![decode 2.5d](https://github.com/user-attachments/assets/cd1d0d55-516c-462b-8f38-463d46b59a06)

And also in the minutes that the queue fills up:
![decode range](https://github.com/user-attachments/assets/bc6409ea-1e66-4851-a0ac-2ab52f50689c)


Finally, comparing with the previous tests, the number of decoded events is the same, so that, in addition to the above, performance problems in wauzh-analysisd are ruled out.

No problems observed in other graphs, metrics or manager logs

### Agent analysis

The agents do not present any problems either, and seem to work normally, although the agent queues are saturated due to the stress test, which can generate bursts of events to the manager (this is an expected behavior).

### Related issues and conclusions

Due to the nature of the test, it is possible that a burst of events could affect the syscheck queue due to its small size (128) it is very susceptible to this scenario. This can also be seen in previous test versions we have in production:

- https://github.com/wazuh/wazuh/issues/22303
![4.7.3](https://camo.githubusercontent.com/509a8110c9c60f3636f4e8ac6797bc4199de1470daa5cc128d5916d6f7db0ac3/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343930332d333630306d2f42343930335f6d616e616765725f63656e746f732f706c6f74732f546573745f7374726573735f42343930335f6d616e616765725f616e616c79736973645f6576656e74735f44726f707065645f6576656e74732e706e67)

- https://github.com/wazuh/wazuh/issues/23162
![4.7.4](https://camo.githubusercontent.com/52a89a89db0029f9575a4ad901b1d6e00eb5bbbcf20baaf7f816be820701717d/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e342f42353037352d333630306d2f42353037355f6d616e616765725f63656e746f732f706c6f74732f546573745f7374726573735f42353037355f6d616e616765725f616e616c79736973645f6576656e74735f44726f707065645f6576656e74732e706e67)

- https://github.com/wazuh/wazuh/issues/19500
![4.7.5](https://camo.githubusercontent.com/0adbe966627788e542d6ffcbd4ebccc010840a423e9c8b308a8771ca96411f18/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343431392d333630306d2f42343431395f6d616e616765725f63656e746f732f706c6f74732f546573745f7374726573735f42343431395f6d616e616765725f616e616c79736973645f6576656e74735f44726f707065645f6576656e74732e706e67)

Considering all of the above, I don't think this is a new behavior or a problem with this version.

**Comment by JcabreraC** [comment]
As @juliancnn mentioned, the nature of the test can lead to a burst of events that overwhelm the syscheck queue due to its limited size, resulting in event drops. We've observed this issue in similar tests before.
