### ISSUE TITLE
No Disk_Read data in Wazuh Indexer at VD performance test

### ISSUE THREAD

**Issue by hossam1522** [wazuh/wazuh#25205]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-beta2 | Wazuh component | Manager | Packages/Sources | OS version |

In VD performance test, while analyzing plots in https://github.com/wazuh/wazuh/issues/25140#issuecomment-2284077790 for Indexer 1 at 4.9.0-beta2, it has been detected that there is no `Disk_Read` data, whereas in previous versions this does not occur and there is always data read.

### 4.9.0-Beta2
![Disk_Read](https://github.com/user-attachments/assets/d5eda45c-3572-4add-913b-c6ed42396905)

### 4.9.0-Beta1
![Disk_Read](https://github.com/user-attachments/assets/55194619-6d82-40dc-b124-3736ab694a67)

### 4.8.1-RC2
![Disk_Read](https://github.com/wazuh/wazuh/assets/11089305/d8f33171-90f8-43a8-ab19-826263437f36)

### 4.8.0-RC4
![Disk_Read](https://github.com/wazuh/wazuh/assets/11089305/1faa6a54-a2fc-4dbc-b39a-f420743c22a4)

Further investigation into the reason for this issue will be required.

**Comment by MARCOSD4** [comment]
This may be related to the way work is distributed among the indexers, discussed in this [issue](https://github.com/wazuh/wazuh-qa/issues/5667). By not setting a specific configuration and following the default configuration when installing the indexers, OpenSearch establishes a coordinator node automatically, which is in charge of distributing the operations over the rest of the nodes or even over itself. In this case, you can see how the `indexer_0`, which does not present data in `disk_read`, has a lower CPU usage than the `indexer_1`. This could mean that it is the “coordinator”, so the low values in its measurements could be expected. On the other hand, indexer_1 does show measurements in `disk_read`.

Also, although this has not appeared before in the medium activity tests, it has been seen on other occasions, for example in the high activity test of [4.8.1-rc4](https://github.com/wazuh/wazuh/issues/24504#issuecomment-2222631293), in `indexer_1`. In this case, it was left as expected and was not reported.

[artifacts.zip](https://github.com/user-attachments/files/16613576/artifacts.zip)

Ultimately, this may be expected behavior due to the operation of the indexer cluster and the distribution of work among them. Moreover, a similar case already happened in previous versions.

**Comment by pro-akim** [comment]
## Review Notes
LGTM

**Comment by Rebits** [comment]
As @MARCOSD4 mentioned, it appears that the reported Indexer node is actually a data node. This node is primarily functioning as a data node and is currently focused on indexing (writing) new data. As a result, the disk write activity is concentrated on the same nodes
