### ISSUE TITLE
Wazuh DB Error when running Cluster reliability test

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#25212]
|Wazuh version|Component|Install type|
|---|---|---|
|4.9.0 | Wazuh DB | Manager|

## Description

During the tests in https://github.com/wazuh/wazuh/issues/25175, the following error appeared in the `Cluster Reliability` tests and `API performance` tests:

```console
2024/08/14 02:48:34 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B630_manager_18] [Agent-groups send] Finished in 1.238s. Updated 14 chunks. There were 1 chunks with errors: ['Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups']
2024/08/14 02:48:34 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B630_manager_16] [Agent-groups send] Finished in 1.249s. Updated 14 chunks. There were 1 chunks with errors: ['Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups']
2024/08/14 02:48:34 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B630_manager_11] [Agent-groups send] Finished in 1.267s. Updated 14 chunks. There were 1 chunks with errors: ['Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups']
2024/08/14 02:48:34 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B630_manager_13] [Agent-groups send] Finished in 1.267s. Updated 12 chunks. There were 3 chunks with errors: ['Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups', 'Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups', 'Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups']
2024/08/14 02:48:34 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B630_manager_14] [Agent-groups send] Finished in 1.289s. Updated 0 chunks. There were 15 chunks with errors: ['Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups', 'Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups', 'Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups', 'Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups', 'Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups', 'Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups', 'Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups', 'Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups', 'Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups', 'Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups', 'Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups', 'Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups', 'Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups', 'Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups', 'Error 2007 - Error retrieving data from Wazuh DB: An error occurred during the set of the groups']
```

The errors shown in the `cluster.log` file happened while the `ossec.log` file was not logging any message:
```
2024/08/14 02:40:52 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2024/08/14 02:40:52 wazuh-remoted: INFO: (1410): Reading authentication keys file.
2024/08/14 02:48:04 wazuh-modulesd:router: INFO: Loaded router module.
2024/08/14 02:48:04 wazuh-modulesd:content_manager: INFO: Loaded content_manager module.
2024/08/14 02:48:06 wazuh-modulesd:router: INFO: Loaded router module.
2024/08/14 02:48:06 wazuh-modulesd:content_manager: INFO: Loaded content_manager module.
2024/08/14 02:48:19 wazuh-remoted: ERROR: (1320): Agent '000' not found.
2024/08/14 02:48:24 wazuh-remoted: ERROR: (1320): Agent '000' not found.
2024/08/14 02:55:51 wazuh-authd: INFO: Agent key generated for agent 'new_test_agent' (requested locally)
```

The logs obtained during the tests: [artifacts.zip](https://github.com/user-attachments/files/16612445/artifacts.zip)

**Comment by MiguelazoDS** [comment]
I keep looking at this, there are several errors besides the one with Wazuh-DB, I'll try to reproduce the errors since I figured out the command is sent to the wazuh-db for setting the agent groups, but I think I'm missing valuable information without the debug level for all these logs. 

Following the code, the group information is updated from the control msg. I haven't seen many significant changes since 4.8.1 but I'm thinking in some race condition that impedes to set the proper group information and arrives empty to the wazuh-db command parser. 

```console
WARNING: The groups were empty right after the set for agent
```

**Comment by MiguelazoDS** [comment]
# Update 

## Log analysis

### Master

50.000 agents are registered directly to the master node.

```console
2024/08/14 02:31:12 wazuh-authd: INFO: New connection from 172.31.70.237
2024/08/14 02:31:12 wazuh-authd: INFO: Received request for a new agent (1-bVlQ04JGpziDHuax-debian10) from: 172.31.70.237
2024/08/14 02:31:12 wazuh-authd: INFO: Agent key generated for '1-bVlQ04JGpziDHuax-debian10' (requested by any)
```

The first errors  (I didn't stopped here) 
```console
2024/08/14 02:48:19 wazuh-remoted: ERROR: (1320): Agent '000' not found.
2024/08/14 02:48:24 wazuh-remoted: ERROR: (1320): Agent '000' not found.
```

Registers 3 more agents using the API 
```console
2024/08/14 02:55:51 wazuh-authd: INFO: Agent key generated for agent 'new_test_agent' (requested locally)
2024/08/14 02:55:51 wazuh-authd: INFO: Agent key generated for agent 'new_test_agent_insert' (requested locally)
2024/08/14 02:55:51 wazuh-authd: INFO: Agent key generated for agent 'new_test_agent_insert_quick' (requested locally)
```

Deleted previously registered agents API (including the last 3) 
```console
2024/08/14 02:56:21 wazuh-authd: INFO: Agent '44611' (1-PTdDWmMZcu1QjYHs-debian10) deleted (requested locally)
```

Here we can see the inconvenience. As stated before this seems to be a race condition, it is trying to assign groups to already deleted agents.
```console
2024/08/14 02:56:27 wazuh-db: ERROR: There was an error assigning the groups to agent '5012'
2024/08/14 02:56:27 wazuh-db: WARNING: The groups were empty right after the set for agent '5012'
```

If we perform a query for an unexistent agent 5, the error messages are displayed

```console
root@jammy:/home/vagrant/wazuh# python3 wdb-query.py global "set-agent-groups {\"mode\":\"empty_only\",\"sync_status\":\"synced\",\"data\":[{\"id\":5,\"groups\":[\"default\"]}]}"
err An error occurred during the set of the groups
```

```console
2024/08/15 13:55:08 wazuh-db: ERROR: There was an error assigning the groups to agent '005'
2024/08/15 13:55:08 wazuh-db: WARNING: The groups were empty right after the set for agent '005'
```

The error is a consequence of a missing agent ID in the belongs table and it is easily reproducible with a delay here
https://github.com/wazuh/wazuh/blob/e49d9905d388d40177abf4f3c04d1fa99c22f38d/src/remoted/manager.c#L1456

```console
2024/08/15 16:50:02 wazuh-authd: INFO: Agent '001' (centos9) deleted (requested locally)
2024/08/15 16:50:02 wazuh-modulesd:database[130428] wm_database.c:748 at wm_inotify_start(): DEBUG: inotify: i='0', name='client.keys.WLohIr', mask='8', wd='1'
2024/08/15 16:50:02 wazuh-modulesd:database[130428] wm_database.c:748 at wm_inotify_start(): DEBUG: inotify: i='48', name='client.keys', mask='128', wd='1'
2024/08/15 16:50:02 wazuh-modulesd:database[130428] wm_database.c:816 at wm_inotify_push(): DEBUG: Adding 'etc/client.keys' to path table.
2024/08/15 16:50:02 wazuh-modulesd:database[130428] wm_database.c:847 at wm_inotify_pop(): DEBUG: Taking 'etc/client.keys' from path table.
2024/08/15 16:50:11 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2024/08/15 16:50:11 wazuh-remoted: INFO: (1410): Reading authentication keys file.
2024/08/15 16:50:11 wazuh-remoted: WARNING: (1408): Invalid ID 001 for the source ip: '192.168.33.65' (name 'unknown').
2024/08/15 16:50:11 wazuh-remoted: WARNING: (1408): Invalid ID 001 for the source ip: '192.168.33.65' (name 'unknown').
2024/08/15 16:50:16 wazuh-db: ERROR: There was an error assigning the groups to agent '001'
2024/08/15 16:50:16 wazuh-db: WARNING: The groups were empty right after the set for agent '001'
```

> [!NOTE]
> The key of this error is that the agent does not exist, regardless of the information for mode and sync_status

Going further, it starts with a thread to handle messages 

https://github.com/wazuh/wazuh/blob/ac09f54a477c768dcbe801ef485ae37b2ff494d9/src/remoted/secure.c#L90

Then, after the previous analysis, we can see a restart and some unattended requests to a stopped module.
```console
2024/08/14 02:56:30 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2024/08/14 02:56:30 wazuh-modulesd:syscollector: INFO: Module finished.
2024/08/14 02:56:30 wazuh-modulesd:vulnerability-scanner: INFO: Stopping vulnerability_scanner module.
2024/08/14 02:56:30 wazuh-modulesd:router: INFO: Stopping router module.
2024/08/14 02:56:30 wazuh-modulesd:content_manager: INFO: Stopping content_manager module.
2024/08/14 02:56:30 wazuh-monitord: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/14 02:56:30 wazuh-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/14 02:56:30 wazuh-remoted: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/14 02:56:30 wazuh-syscheckd: INFO: (1756): Shutdown received. Releasing resources.
2024/08/14 02:56:30 wazuh-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/14 02:56:30 wazuh-analysisd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/14 02:56:31 wazuh-execd: INFO: (1314): Shutdown received. Deleting responses.
2024/08/14 02:56:31 wazuh-execd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/14 02:56:31 wazuh-db: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/14 02:56:31 wazuh-db: INFO: Graceful process shutdown.
2024/08/14 02:56:31 wazuh-authd: ERROR: Cannot receive message: Connection reset by peer (104)
2024/08/14 02:56:31 wazuh-authd: ERROR: Cannot send message: (104) 'Connection reset by peer'.
2024/08/14 02:56:31 wazuh-authd: ERROR: Cannot send message: (32) 'Broken pipe'.
2024/08/14 02:56:31 wazuh-authd: ERROR: Connection with wazuh-db lost. Reconnecting.
```

> [!NOTE]
> The last behavior is explained here 
https://github.com/wazuh/wazuh/issues/25223#issuecomment-2290177419

**Comment by sebasfalcone** [comment]
## Conclusion
This issue can be replicated so we can further investigate a possible solution

> [!IMPORTANT]
> The system can recover from this state with a simple reset

PS: This investigations could have been much easier and in-depth with the logs in debug

**Comment by Dwordcito** [comment]
LGTM, recoverable sync error.

**Comment by fdalmaup** [comment]
After discussing with @Dwordcito about the detriment in the execution times of the `Agent-info sync` task that occurred in both [`v4.9.0-beta2`](https://github.com/wazuh/wazuh/issues/25175#issuecomment-2286618328) and [`v4.9.0-rc1`](https://github.com/wazuh/wazuh/issues/25368#issuecomment-2307762777), we decided to reopen the issue to determine what could be the reason why the server was frozen, causing the tasks carried out by the cluster related to `wazuh-db` to take longer than expected.

**Comment by pereyra-m** [comment]
## Update

I continue with the analysis of the issue.

Considering that there isn't major changes in `wazuh-db` at v4.9.0 (https://github.com/wazuh/wazuh/releases/tag/v4.9.0-rc1), my first hypothesis is that the new asynchronous cluster calls (https://github.com/wazuh/wazuh/pull/22640) might have uncovered these race conditions and server blocks.
This is possible because this a major change in the way that `Sendsync`, `Agent-info sync`, `Agent-groups recv` and `Agent-groups recv full` calls are made.

When these changes were merged, the performance tests were run (https://github.com/wazuh/wazuh/issues/21862#issuecomment-2034832186) but it might be required several runs to see the errors (consider the alpha-beta1-beta2 tests results). 

So I propose two approaches in parallel, both we'll require the assistance of @wazuh/devel-pyserver:
- To run many times the same performance tests over a branch with the same code as v4.9.0 but with the asynchronous calls reverted. This could confirm or discard the described possibility
- To mimic the new type of calls with a local script to make `wazuh-db` fail. It'd be really valuable to understand the impact of the changes so I can run that test.

**Comment by pereyra-m** [comment]
## Update

As a complement of the update shared above, I've analyzed some interesting logs from the test.

### Remoted error

This one for example was found at the manager and I can't explain it because the manager (agent 000) shouldn't talk to `wazuh-remoted`.  

```
2024/08/14 02:48:19 wazuh-remoted: ERROR: (1320): Agent '000' not found.
```

### Gaps in logs

Also there are some gaps in the logs. Several minutes without messages

```
2024/08/14 02:40:52 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2024/08/14 02:40:52 wazuh-remoted: INFO: (1410): Reading authentication keys file.
2024/08/14 02:48:04 wazuh-modulesd:router: INFO: Loaded router module.
2024/08/14 02:48:04 wazuh-modulesd:content_manager: INFO: Loaded content_manager module.
```

But that one in particular is really strange, because the initialization sequence for the `router` module is incomplete, suggesting that the server failed to log but still some operations were executed.
Here we can see that the first sequence is right (two times loaded, one time started, one time stopped). And then we have missing entries

```
$ grep ":router" ossec.log                                        
2024/08/14 02:07:58 wazuh-modulesd:router: INFO: Loaded router module.
2024/08/14 02:08:05 wazuh-modulesd:router: INFO: Loaded router module.
2024/08/14 02:08:05 wazuh-modulesd:router: INFO: Starting router module.
2024/08/14 02:26:16 wazuh-modulesd:router: INFO: Stopping router module.
2024/08/14 02:26:20 wazuh-modulesd:router: INFO: Loaded router module.
2024/08/14 02:26:28 wazuh-modulesd:router: INFO: Loaded router module.
2024/08/14 02:26:28 wazuh-modulesd:router: INFO: Starting router module.
2024/08/14 02:48:04 wazuh-modulesd:router: INFO: Loaded router module.
2024/08/14 02:48:06 wazuh-modulesd:router: INFO: Loaded router module.
2024/08/14 02:56:29 wazuh-modulesd:router: INFO: Loaded router module.
2024/08/14 02:56:30 wazuh-modulesd:router: INFO: Stopping router module.
2024/08/14 02:57:39 wazuh-modulesd:router: INFO: Loaded router module.
2024/08/14 02:57:39 wazuh-modulesd:router: INFO: Starting router module.
2024/08/14 02:57:52 wazuh-modulesd:router: INFO: Loaded router module.
2024/08/14 02:57:53 wazuh-modulesd:router: INFO: Stopping router module.
2024/08/14 02:58:27 wazuh-modulesd:router: INFO: Loaded router module.
2024/08/14 02:58:27 wazuh-modulesd:router: INFO: Starting router module.
```

### Groups related errors

This type of message is related to the race conditions during the agent operations like add, remove, group assign, group remove, etc.

```
2024/08/14 02:56:27 wazuh-db: ERROR: There was an error assigning the groups to agent '5012'
2024/08/14 02:56:27 wazuh-db: WARNING: The groups were empty right after the set for agent '5012'
```

I was able to force them adding delays in some `wazuh-db` methods.
These are the reproduction steps (the required configuration doesn't work at VS Code https://github.com/Microsoft/vscode-cpptools/issues/2639)
- Compile and install a v4.9.0 manager with debug symbols 
- Start all daemons manually except `wazuh-db`
- Start `wazuh-db` with the debugger: `gdb /var/ossec/bin/wazuh-db`
- Configure GDB to only stop the current thread: ` set pagination off` `set non-stop on`
- Add a breakpoint: `break wdb_global_recalculate_agent_groups_hash`
- Run the daemon: `r -fdd`
- Add a new agent, for example with `manage_agents`
- Create a group, for example with `agent_groups -a -g test`
- Assign the group to the agent: `agent_groups -a -g test -i 005`, one thread should stop at the breakpoint
- Remove the agent with `manage_agents`
- Switch to the stopped thread an resume it
- The log should be printed: `2024/08/28 00:45:12 wazuh-db[65674] wdb_global.c:1397 at wdb_global_recalculate_agent_groups_hash(): WARNING: The groups were empty right after the set for agent '005'`
- Also, in the `agent_groups` terminal, another error is found: `Error 2003 - Error in wazuhdb request: An error occurred during the set of the groups`

This is possible because of many reasons:
- The agents exists if they have an entry at `client.keys` file, but when it is removed, the related information to it like the groups, etc. lives in other places like databases
- The process of removing an agent or adding/removing it to/from groups isn't atomic. There are several intermediate steps that might fail if another thread modifies the information required for that step
- The operations over `global.db` aren't atomic either. If a thread is calculating the hash for the groups of an agent, it requires to reading/writing the `belongs` and `agent` table but nothing prevents another one from modifying the data in the middle of the chain of operations. 

**Note**: using the same sqlite3 DB connection by many threads is safe with the default settings. There are internal mutexes in the library that prevent any undefined behavior. However, the data might become inconsistent at the "application" layer (Wazuh) considering the current implementation and the required steps to update tables like `groups`, `belongs`, `agents`. 

https://www.sqlite.org/c3ref/c_config_covering_index_scan.html#sqliteconfigserialized
> SQLITE_CONFIG_SERIALIZED
There are no arguments to this option. This option sets the [threading mode](https://www.sqlite.org/threadsafe.html) to Serialized. In other words, this option enables all mutexes including the recursive mutexes on [database connection](https://www.sqlite.org/c3ref/sqlite3.html) and [prepared statement](https://www.sqlite.org/c3ref/stmt.html) objects. In this mode (which is the default when SQLite is compiled with [SQLITE_THREADSAFE=1](https://www.sqlite.org/compile.html#threadsafe)) the SQLite library will itself serialize access to [database connections](https://www.sqlite.org/c3ref/sqlite3.html) and [prepared statements](https://www.sqlite.org/c3ref/stmt.html) so that the application is free to use the same [database connection](https://www.sqlite.org/c3ref/sqlite3.html) or the same [prepared statement](https://www.sqlite.org/c3ref/stmt.html) in different threads at the same time. 

We can also infer that if an environment with 50k agents and 25 workers is running heavy groups and agents operations, the process will eventually face the bottleneck of one single sqlite3 DB (master's `global.db`) because only one thread of the `wazuh-db` pool of threads can write at the time. And as described above, there is a high chance of seeing the error/warning messages related to the non-atomic agent operations.

**Comment by sebasfalcone** [comment]
## Conclusion
This behaviour has been latent since (at least) 4.4.x. The following features of the WazuhDB are not prepared to receive asynchronous and parallel requests:
- Group assignment
- Group deletion
- Agent deletion
- Agent registration (with Group assignment)

This is a design problem, the infrastructure doesn't account for this type of request.

We think that after the tests are run we are going to have a way to conclude this issue

## Issue blocked
We will await for the proposed testing to be performed:
- https://github.com/wazuh/wazuh/issues/25427

## ETA updated
Update the ETA accordingly

**Comment by Dwordcito** [comment]
The change that introduces this error will be reverted: https://github.com/wazuh/wazuh/issues/25449

**Comment by javiersanchz** [comment]
## Update

- The issue is being reopened because, after working on [Release 4.9.0 - Release Candidate 2 - Workload benchmarks metrics](https://github.com/wazuh/wazuh/issues/25508), and after reverting the requested changes from https://github.com/wazuh/wazuh/issues/25449, very high times are still occurring in the cluster tasks related to `Wazuh-DB` operations

- These times increased compared to [RC1](https://github.com/wazuh/wazuh/issues/25368) and [Beta 2](https://github.com/wazuh/wazuh/issues/25175)

**Comment by sebasfalcone** [comment]
## Steps to continue
We are going to generate a historic graph of the performance for the tests:
- [Release 4.8.0 - Release Candidate 4 - Workload benchmarks metrics](https://github.com/wazuh/wazuh/issues/23992)
- [Release 4.8.1 - Release Candidate 2 - Workload benchmarks metrics](https://github.com/wazuh/wazuh/issues/24481)
- [Release 4.9.0 - Beta 1 - Workload benchmarks metrics](https://github.com/wazuh/wazuh/issues/25053)
- [Release 4.9.0 - Beta 2 - Workload benchmarks metrics](https://github.com/wazuh/wazuh/issues/25175)
- [Release 4.9.0 - Release Candidate 1 - Workload benchmarks metrics](https://github.com/wazuh/wazuh/issues/25368)
- [Release 4.9.0 - Release Candidate 2 - Workload benchmarks metrics](https://github.com/wazuh/wazuh/issues/25508)

We saw a suspicious increase in the time of some queries in between _4.9.0 Beta 1_ and _4.9.0 Beta 2_. The historic graphs should put this in evidence

CC: @MiguelazoDS

**Comment by sebasfalcone** [comment]
## Comparing historic information
To discard the possibility of a fluke in the tests we analyzed the metrics 

## agent-info

### Mean execution time
- Increase over time
![image](https://github.com/user-attachments/assets/e94f4007-9948-4554-90ad-adcc86157638)

### Max execution time
- Increase over time
![image](https://github.com/user-attachments/assets/566c45b3-0e58-4102-af74-874bafdb5bce)

### Normalized max and mean execution time
- Strong correlation between both metrics
![image](https://github.com/user-attachments/assets/3cacf17f-5253-45e0-9715-72b3e60b1788)

**Comment by MiguelazoDS** [comment]
## Update

Comparing 4.8.1-rc2 vs 4.9.0-b2 I see some similar errors previously mentioned above

In 4.8.1-rc2, the log gap is present and also the log message where the agent 000 communicates with remote module.
So I wouldn't put effort on figure out why is that happening.

v4.8.1-rc2
```console
2024/07/08 12:04:15 wazuh-remoted: INFO: (1410): Reading authentication keys file.
2024/07/08 12:04:48 wazuh-modulesd:vulnerability-scanner: INFO: Triggered a re-scan after content update
2024/07/08 12:04:48 wazuh-modulesd:vulnerability-scanner: INFO: Feed update process completed
2024/07/08 12:11:49 wazuh-modulesd:router: INFO: Loaded router module.
2024/07/08 12:11:49 wazuh-modulesd:content_manager: INFO: Loaded content_manager module.
2024/07/08 12:11:51 wazuh-modulesd:router: INFO: Loaded router module.
2024/07/08 12:11:51 wazuh-modulesd:content_manager: INFO: Loaded content_manager module.
2024/07/08 12:11:59 wazuh-remoted: ERROR: (1320): Agent '000' not found.
2024/07/08 12:12:04 wazuh-remoted: ERROR: (1320): Agent '000' not found.
```

------------

The following logs are only present in v4.9.x except in v4.9.0-beta1 where the tests didn't fail.

```console
2024/08/14 02:48:33 wazuh-db: WARNING: Unable to find the id of the group 'new_test_group'
2024/08/14 02:48:33 wazuh-db: ERROR: There was an error assigning the groups to agent '001'
```

---------

These master log messages are present in both versions (4.8.x and 4.9.x except v4.9.0-beta1)

```console
2024/07/08 12:13:32 wazuh-db: ERROR: There was an error assigning the groups to agent '2996'
2024/07/08 12:13:32 wazuh-db: WARNING: The groups were empty right after the set for agent '2996'
```

------

We have:  
- Failing tests in v4.9.0-alpha3
- Passing tests in v4.9.0-beta1
- Failing tests in v4.9.0-beta2

The changes between beta1 and beta2 are minimum.

```console
git diff v4.9.0-beta1..v4.9.0-beta2
```

```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 8728e65681..d83f90f459 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -16 +15,0 @@ All notable changes to this project will be documented in this file.
-- Added helper to manage HAProxy configuration and automatically balance agents. ([#23513](https://github.com/wazuh/wazuh/pull/23513))
@@ -98,0 +98 @@ All notable changes to this project will be documented in this file.
+- Fixed the `GET /agents/outdated` endpoint query. ([#24946](https://github.com/wazuh/wazuh/pull/24946))
diff --git a/api/api/spec/spec.yaml b/api/api/spec/spec.yaml
index 9f27a36835..d5a607d7ae 100644
--- a/api/api/spec/spec.yaml
+++ b/api/api/spec/spec.yaml
@@ -44 +44 @@ info:
-  x-revision: '40904'
+  x-revision: '40905'
diff --git a/framework/wazuh/core/cluster/__init__.py b/framework/wazuh/core/cluster/__init__.py
index c27456a84b..b38d9ca254 100644
--- a/framework/wazuh/core/cluster/__init__.py
+++ b/framework/wazuh/core/cluster/__init__.py
@@ -8 +8 @@ __version__ = '4.9.0'
-__revision__ = '40904'
+__revision__ = '40905'
diff --git a/src/Doxyfile b/src/Doxyfile
index 7800cfb91b..ec16597141 100644
--- a/src/Doxyfile
+++ b/src/Doxyfile
@@ -41 +41 @@ PROJECT_NAME           = "WAZUH"
-PROJECT_NUMBER         = "v4.9.0-40904"
+PROJECT_NUMBER         = "v4.9.0-40905"
diff --git a/src/REVISION b/src/REVISION
index 5dbcde4b9d..2322470665 100644
--- a/src/REVISION
+++ b/src/REVISION
@@ -1 +1 @@
-40904
+40905
diff --git a/src/init/wazuh-client.sh b/src/init/wazuh-client.sh
index e8ca9e0a2e..4ed50b9d69 100755
--- a/src/init/wazuh-client.sh
+++ b/src/init/wazuh-client.sh
@@ -15 +15 @@ VERSION="v4.9.0"
-REVISION="40904"
+REVISION="40905"
diff --git a/src/init/wazuh-local.sh b/src/init/wazuh-local.sh
index b893bfb88c..39576f72ef 100644
--- a/src/init/wazuh-local.sh
+++ b/src/init/wazuh-local.sh
@@ -17 +17 @@ VERSION="v4.9.0"
-REVISION="40904"
+REVISION="40905"
diff --git a/src/init/wazuh-server.sh b/src/init/wazuh-server.sh
index 11c6fb64ce..96f79c9ac4 100755
--- a/src/init/wazuh-server.sh
+++ b/src/init/wazuh-server.sh
@@ -17 +17 @@ VERSION="v4.9.0"
-REVISION="40904"
+REVISION="40905"
diff --git a/src/win32/wazuh-installer.nsi b/src/win32/wazuh-installer.nsi
index 2eb352cbb1..fedc271162 100644
--- a/src/win32/wazuh-installer.nsi
+++ b/src/win32/wazuh-installer.nsi
@@ -24 +24 @@
-!define REVISION "40904"
+!define REVISION "40905"
```

---------

**Comment by sebasfalcone** [comment]
## Conclusion
Based on all the investigations and the lack of results, I think we should repeat the tests. Maybe two more times for each release to rule out tests variations (some weird race condition maybe)

**Comment by juliamagan** [comment]
After a meeting with @havidarou and @fdalmaup, it has been decided to launch a Workload build that tests 4.9.0-rc2 packages, but with v4.8.1 tests. This way, we can see if the behavior is the same, regardless of pipeline or test changes.


Build: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/675/


Artifacts: [artifacts(2).zip](https://github.com/user-attachments/files/16871611/artifacts.2.zip)

**Comment by sebasfalcone** [comment]
## Comparing historical information - Update
> [!NOTE]
> Update over [this analysis](https://github.com/wazuh/wazuh/issues/25212#issuecomment-2327298031) (now outdated)


Two key changes on these new graphs:
- Releases ordered by date (to account for upward merges)
- Added new test case `4.9.0 RC2` code version, running on `4.8.1` tests

## agent-info

### Mean execution time
![Image](https://github.com/user-attachments/assets/6b4857f5-2825-44f3-833e-195c4f16bf24)


### Max execution time
![Image](https://github.com/user-attachments/assets/ac235253-5274-4aae-9823-c27a79283f58)


### Normalized max and mean execution time
![Image](https://github.com/user-attachments/assets/09dbf46f-c119-4d97-a57e-4611b9c8b3ec)

## Conclusion
All indicate that variations on the tests are responsible for changes in the metrics

**Comment by sebasfalcone** [comment]
## Update
Continue investigation over live environment

**Comment by sebasfalcone** [comment]
## Update
Continue investigation over a live environment ([Jenkins run](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/679/)):
- Source reference `4.9.0 RC2`
- Jenkins reference `4.8.1`
- QA reference `4.8.1`

> [!NOTE]
> This combination landed good results as seen [here](https://github.com/wazuh/wazuh/issues/25212#issuecomment-2329510000)

## Data
Managers last wazuh-db daemons stats ([Obtained via](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.manager_controller.get_daemon_stats))
- [Filtered data](https://github.com/user-attachments/files/16874937/filtered_data.tar.gz)

## Analysis
All the graphs can be found in this [analysis sheet](https://docs.google.com/spreadsheets/d/16jFeGyOSaN-ByGV3n5skeKGw4XYRrjjUdiXZUXMxXz8/edit?usp=sharing)

After further investigation with @TomasTurina, we determined that the number of queries and the mean execution time are within an expected range.

### Amount of queries
- Master node got fewer queries: This is expected due to the load it's put on, which is different from the workers 
![image](https://github.com/user-attachments/assets/83f8aa83-0fe2-4c95-884e-b2b69d8ca3bb)

### Time to query
- The mean time it took each query to execute is 
![image](https://github.com/user-attachments/assets/fbdcd5fa-8958-48d7-bfce-a8b5ad9e4acb)

**Comment by sebasfalcone** [comment]
## Update
Continue investigation over a live environment ([Jenkins run](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/682/)):
- Source reference `4.9.0 RC2`
- Jenkins reference `4.9.0 RC2`
- QA reference `fix/3665-xfailed-test-performance`

> [!IMPORTANT]
> As @Rebits proposed, @TomasTurina reverted the changes from the PR ["Fix logic for xfail test in api performance test"](https://github.com/wazuh/wazuh-qa/pull/4657#top), and we ran the tests with it.
>
> This can be found in the wazuh-qa repo under the [fix/25212-revert-xfail-logic](https://github.com/wazuh/wazuh-qa/tree/fix/25212-revert-xfail-logic) branch


## Data
Managers last wazuh-db daemons stats ([Obtained via](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.manager_controller.get_daemon_stats))
- [Filtered data](https://github.com/user-attachments/files/16881510/filtered_data.tar.gz)

## Analysis
All the graphs can be found in this [analysis sheet](https://docs.google.com/spreadsheets/d/16jFeGyOSaN-ByGV3n5skeKGw4XYRrjjUdiXZUXMxXz8/edit?gid=568064682#gid=568064682)


After comparing the results with the previous run I've found that the tests have different stimuli. In [this sheet](https://docs.google.com/spreadsheets/d/16jFeGyOSaN-ByGV3n5skeKGw4XYRrjjUdiXZUXMxXz8/edit?gid=265535839#gid=265535839) we can see that:

![image](https://github.com/user-attachments/assets/94cea760-f173-4e25-91cd-42b51079f870)

- Global queries were `4.95` more in run 1
  - Time to query was `3.36` times greater in run 1
- Agent queries were `3.79` more in run 1
  - Time to query was `1.36` times greater in run 1
- wazuhdb queries were `37` times fewer in run 1
  - Time to query was identical in both runs (no degradation)
  - As a note, all the wazuhDB queries are removal operations

## Conclusion
I think this is conclusive enough to point out that the changes in the wazuh-QA repository are affecting the tests. The stimuli are not the same, therefore we cannot guarantee that the thresholds are the same

**Comment by Dwordcito** [comment]
I understand that the tests are conclusive and this results in the revert indicated here:

https://github.com/wazuh/wazuh-jenkins/issues/6920 

Other team will revert those changes, on behalf of cppserver, the analysis concludes here.
