### ISSUE TITLE
`wazuh-authd` loses connection with `wazuh-db`

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#25223]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-beta2 | wazuh-authd/wazuh-db | Manager | Packages | CentOS 7 |

The following error messages have been found in the https://github.com/wazuh/wazuh/issues/25145 issue

```
2024/08/09 17:25:58 wazuh-authd ERROR: Cannot send message: (32) 'Broken pipe'.
2024/08/09 17:25:58 wazuh-authd ERROR: Connection with wazuh-db lost. Reconnecting.
2024/08/09 17:26:04 wazuh-authd ERROR: Unable to connect to socket 'queue/db/wdb'.
```

Those messages appeared previously in the following issues but in a different context, we need to investigate those messages

- https://github.com/wazuh/wazuh/issues/23301
- https://github.com/wazuh/wazuh/issues/22130

**Comment by pereyra-m** [comment]
## Update

I research the issue and try to reproduce it.

**Comment by pereyra-m** [comment]
# Analysis

## Summary

There is a race condition during the manager shutdown that generates the reported log messages.
If `wazuh-authd` is generating a key when `wazuh-db` isn't available, the socket won't be available and the query will fail.

The system can recover itself from this situation and to mitigate it a deep refactor is needed, because there isn't a central component that orchestrates the daemons properly and the notification of shutdown isn't instant but it allows the current task to end.

## Research

The logs from the test were analyzed.
This is the most important section

```
2024/08/09 17:25:51 wazuh-authd: INFO: New connection from 172.31.12.203
2024/08/09 17:25:52 wazuh-authd: INFO: Client timeout from 172.31.12.203
2024/08/09 17:25:55 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2024/08/09 17:25:55 wazuh-modulesd:syscollector: INFO: Module finished.
2024/08/09 17:25:55 wazuh-modulesd:vulnerability-scanner: INFO: Stopping vulnerability_scanner module.
2024/08/09 17:25:55 wazuh-modulesd:router: INFO: Stopping router module.
2024/08/09 17:25:55 wazuh-modulesd:content_manager: INFO: Stopping content_manager module.
2024/08/09 17:25:55 wazuh-monitord: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/09 17:25:55 wazuh-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/09 17:25:55 wazuh-remoted: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/09 17:25:55 wazuh-syscheckd: INFO: (1756): Shutdown received. Releasing resources.
2024/08/09 17:25:56 wazuh-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/09 17:25:56 wazuh-analysisd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/09 17:25:56 wazuh-execd: INFO: (1314): Shutdown received. Deleting responses.
2024/08/09 17:25:56 wazuh-execd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/09 17:25:57 wazuh-db: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/09 17:25:58 wazuh-db: INFO: Graceful process shutdown.
2024/08/09 17:25:58 wazuh-authd: INFO: New connection from 172.31.12.203
2024/08/09 17:25:58 wazuh-authd: INFO: Received request for a new agent (EC2AMAZ-L273KKC) from: 172.31.12.203
2024/08/09 17:25:58 wazuh-authd: INFO: Agent key generated for 'EC2AMAZ-L273KKC' (requested by any)
2024/08/09 17:25:58 wazuh-authd: ERROR: Cannot send message: (32) 'Broken pipe'.
2024/08/09 17:25:58 wazuh-authd: ERROR: Connection with wazuh-db lost. Reconnecting.
2024/08/09 17:25:58 wazuh-authd: INFO: Cannot find 'queue/db/wdb'. Waiting 1 seconds to reconnect.
2024/08/09 17:25:58 wazuh-authd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/09 17:25:59 wazuh-authd: INFO: Cannot find 'queue/db/wdb'. Waiting 2 seconds to reconnect.
2024/08/09 17:26:01 wazuh-authd: INFO: Cannot find 'queue/db/wdb'. Waiting 3 seconds to reconnect.
2024/08/09 17:26:04 wazuh-authd: ERROR: Unable to connect to socket 'queue/db/wdb'.
2024/08/09 17:26:04 wazuh-authd: INFO: Exiting...
```

The `wazuh-authd` daemon receives a request that timeouts, and then a second one right away but just before a manager restart. The new agent registration is processed when all the other daemons are down, so the connection with `wazuh-db` is lost and the socket isn't found even after several retries.

This happens because the signal handler of the daemon processes the `SIGTERM` setting down the `running` global flag and this variable is read by the running threads at the end of each iteration of their main loop. After generating the key, a query to `wazuh-db` is executed to add the new agent but it fails because the daemon is down. 

The next time the manager starts, it should sync the `client.keys` file with the DB. But if it didn't write the file, then the agent will eventually fail to communicate with the previously generated key and the registration process will happen again. So we find these error messages that shouldn't be there in a normal situation, but the system can recover itself.

## How to reproduce

I was able to force this situation and generate some really similar logs in the following way:
- Install Wazuh v4.9.0 with debug symbols
- Start the manager and attach to the `wazuh-authd` daemon. Set a breakpoint at some point of `run_dispatcher()` (main-server.c), for example the message `New connection from %s`
- From another host, execute `agent-auth` to request a new key
- Once the breakpoint is hit, stop the manager
- Now unpause the daemon and leave it to exit

These are the logs generated with the described procedure

```
2024/08/14 22:31:13 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2024/08/14 22:31:13 wazuh-modulesd:syscollector: INFO: Module finished.
2024/08/14 22:31:13 wazuh-modulesd:vulnerability-scanner: INFO: Stopping vulnerability_scanner module.
2024/08/14 22:31:13 wazuh-modulesd:vulnerability-scanner: INFO: Feed update interrupted: Module stopped..
2024/08/14 22:31:13 wazuh-modulesd:router: INFO: Stopping router module.
2024/08/14 22:31:13 wazuh-modulesd:content_manager: INFO: Stopping content_manager module.
2024/08/14 22:31:14 wazuh-monitord: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/14 22:31:14 wazuh-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/14 22:31:14 wazuh-remoted: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/14 22:31:14 wazuh-syscheckd: INFO: (1756): Shutdown received. Releasing resources.
2024/08/14 22:31:14 wazuh-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/14 22:31:14 wazuh-analysisd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/14 22:31:14 wazuh-execd: INFO: (1314): Shutdown received. Deleting responses.
2024/08/14 22:31:14 wazuh-execd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/14 22:31:14 wazuh-db: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/14 22:31:15 wazuh-db: INFO: Graceful process shutdown.
2024/08/14 22:31:23 wazuh-authd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/08/14 22:31:23 wazuh-authd: INFO: New connection from 172.17.0.3
2024/08/14 22:31:23 wazuh-authd: INFO: Received request for a new agent (2c1e3d372dec) from: 172.17.0.3
2024/08/14 22:31:23 wazuh-authd: INFO: Agent key generated for '2c1e3d372dec' (requested by any)
2024/08/14 22:31:23 wazuh-authd: INFO: Cannot find 'queue/db/wdb'. Waiting 1 seconds to reconnect.
2024/08/14 22:31:24 wazuh-authd: INFO: Cannot find 'queue/db/wdb'. Waiting 2 seconds to reconnect.
2024/08/14 22:31:26 wazuh-authd: INFO: Cannot find 'queue/db/wdb'. Waiting 3 seconds to reconnect.
2024/08/14 22:31:29 wazuh-authd: ERROR: Unable to connect to socket 'queue/db/wdb'.
2024/08/14 22:31:29 wazuh-authd: ERROR: Unable to connect to socket 'queue/db/wdb'.
2024/08/14 22:31:29 wazuh-authd: INFO: Exiting...
```

**Comment by sebasfalcone** [comment]
## Conclusion
As @pereyra-m states, the most important part is that this is a recoverable error. Once all daemons are running again, those errors should disappear.

Reproduction steps were provided so this could be further tested by the QA team

I think this is not a bug

**Comment by Dwordcito** [comment]
LGTM, this issue is not new and is a recoverable error.
