### ISSUE TITLE
SPIKE - Investigate centralized logging for the wazuh-server

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#25231]
# Description

Part of #25191, the following issue aims to research the most convenient mechanism for logging in to the Wazuh Server. In Wazuh v5.0, every daemon running in the Wazuh Server must log into a single file. Therefore, two options should be investigated and studied:
- Using `journald` and make every daemon to log into it.
- Developing a new task inside the Wazuh cluster to receive, process, and store every log from the daemons, including the rotation mechanism.

# Plan

- Investigate the feasibility of using `journald` to group every log message.
- Enumerate the pros and cons of using `journald` versus developing a task inside the Wazuh cluster.
- Develop two small PoCs. One must use `journald` to receive logs from two processes and the other must implement a process receiving logs from two other processes. Both PoCs must be developed in Python.

**Comment by GGP1** [comment]
## Update

I've been investigating ways of logging the information from many `wazuh-server` daemons into a single, centralized place.

So far, the alternatives I considered are:

- syslog
- journald
- Custom logging task running in a separate process and listening for logs on a unix socket

> [!Note]
> syslog and journald code examples are in Python, but I assume most languages have standard libraries to send logs to them.

### syslog

syslog is the unix standard for message logging and comes with any Unix distribution. It is compiled in C and works as a separate process, it is thread and process-safe.

The pros of using this standard are:

- No external libraries required
- Built-in log rotation
- Security level support (7 levels from emergency to debug)

The implementation would require logging message to the `user` or `local` *facilities*. Code example:

```py
from logging import getLogger
from logging.handlers import SysLogHandler

logger = getLogger('custom_logger_name')
handler = SysLogHandler(facility=16)
logger.addHandler(handler)

logger.info('message')
```

The main drawback is that we don't get a custom log exclusively for Wazuh processes, any application pointing to the same facility can write to it, making it necessary to filter the logs by their tags to debug the app's functionality.

Personally I would rule out syslog for this reason alone.

### journald

Journald is the part of [systemd](https://systemd.io/) that deals with logging.

It is written in C and provides :

- Indexing logs for fast search
- Structured logging
- Access control (`journalctl`)
- Built-in file rotation
- Signed messages

It is widely available and doesn't require creating custom clients as there's likely an official library for each language. For example, in Python we can use the [python-systemd](https://github.com/systemd/python-systemd/) package:

```py
import logging
from systemd import journal

logger = logging.getLogger('custom_logger_name')
logger.addHandler(journal.JournalHandler(SYSLOG_IDENTIFIER='custom_unit_name'))
logger.info('message')
```

Using journald has some disadvantages: 

- It requires the host to have `systemd` installed, most Linux distributions (Debian, Fedora, CentOS, Red Hat, Ubuntu, OpenSUSE, Arch, and Amazon Linux) use it though.

    Related to this, Docker containers don’t have systemd installed, deploying Wazuh on Docker would require using the host's driver ( `docker run wazuh-server --log-driver=journald`) and specifying different logging tags to avoid conflicts with other nodes.

- Instead of logging to a text log file, the only way to look at the logs is by using `journalctl`, forcing users to know how it works.

### Custom log server

An alternative would be to implement a lightweight unix socket server over HTTP that receives logs from multiple daemons on-the-fly and logs them to a file in a thread-safe and process-safe manner in Python 

The good thing about this options is that it would meet our specific requirements and can be tweaked according to them.

Moreover, it requires no dependencies, it's completely independent from the system services and 100% customizable.

However, it would require creating the server from scratch and its performance will likely be considerably slower than the other options.

**Comment by GGP1** [comment]
## Update

I've developed two proof of concepts with simple python scripts that spawn 5 processes whose task is to log their PID to the journal. The first script assumes it's executed by a systemd service and the second one logs to journald independently (without being part of a unit).

### Using a systemd service

This simulates a scenario in which users would start Wazuh using `systemctl start wazuh-server`. As it is expected, if we setup a service, all logs are stored within its journal. 

<details><summary>Systemd service</summary>

```console
gasti@gasti:~/work/wazuh$ sudo vim /etc/systemd/system/journald_test.service
gasti@gasti:~/work/wazuh$ cat /etc/systemd/system/journald_test.service
[Unit]
Description=Journald multiprocess test
After=multi-user.target

[Service]
Type=simple
Restart=always
User=root
ExecStart=/usr/bin/python3 /home/gasti/work/wazuh/framework/wazuh/core/cluster/logging/journald/main.py

[Install]
WantedBy=multi-user.target
gasti@gasti:~/work/wazuh$ systemctl daemon-reload
gasti@gasti:~/work/wazuh$ systemctl enable journald_test.service --now
Created symlink /etc/systemd/system/multi-user.target.wants/journald_test.service → /etc/systemd/system/journald_test.service.
gasti@gasti:~/work/wazuh$ systemctl status journald_test
● journald_test.service - Journald multiprocess test
     Loaded: loaded (/etc/systemd/system/journald_test.service; enabled; preset: enabled)
     Active: active (running) since Wed 2024-08-21 12:23:10 -03; 2s ago
   Main PID: 67332 (python3)
      Tasks: 6 (limit: 9424)
     Memory: 13.1M
        CPU: 28ms
     CGroup: /system.slice/journald_test.service
             ├─67332 /usr/bin/python3 /home/gasti/work/wazuh/framework/wazuh/core/cluster/logging/journald/main.py
             ├─67334 /usr/bin/python3 /home/gasti/work/wazuh/framework/wazuh/core/cluster/logging/journald/main.py
             ├─67335 /usr/bin/python3 /home/gasti/work/wazuh/framework/wazuh/core/cluster/logging/journald/main.py
             ├─67336 /usr/bin/python3 /home/gasti/work/wazuh/framework/wazuh/core/cluster/logging/journald/main.py
             ├─67337 /usr/bin/python3 /home/gasti/work/wazuh/framework/wazuh/core/cluster/logging/journald/main.py
             └─67338 /usr/bin/python3 /home/gasti/work/wazuh/framework/wazuh/core/cluster/logging/journald/main.py

Aug 21 12:23:10 gasti systemd[1]: Started journald_test.service - Journald multiprocess test.
Aug 21 12:23:10 gasti python3[67334]: INFO:test:67334
Aug 21 12:23:10 gasti python3[67335]: INFO:test:67335
Aug 21 12:23:10 gasti python3[67336]: INFO:test:67336
Aug 21 12:23:10 gasti python3[67337]: INFO:test:67337
Aug 21 12:23:10 gasti python3[67338]: INFO:test:67338
```

</details>

<details><summary>Get service logs</summary>

```console
gasti@gasti:~/work/wazuh$ journalctl -u journald_test
Aug 21 12:23:10 gasti systemd[1]: Started journald_test.service - Journald multiprocess test.
Aug 21 12:23:10 gasti python3[67334]: INFO:test:67334
Aug 21 12:23:10 gasti python3[67335]: INFO:test:67335
Aug 21 12:23:10 gasti python3[67336]: INFO:test:67336
Aug 21 12:23:10 gasti python3[67337]: INFO:test:67337
Aug 21 12:23:10 gasti python3[67338]: INFO:test:67338
```

</details>

### Using independent processes

<details><summary>Logging to journald from independent processes</summary>

```console
gasti@gasti:~/work/wazuh$ /usr/bin/python3 framework/wazuh/core/cluster/logging/journald/ind_main.py
gasti@gasti:~/work/wazuh$ 
```

</details>

<details><summary>Get service logs</summary>

> We can't use the `-u` flag because the unit does not exist. We filter logs by their syslog identifier.

```console
gasti@gasti:~/work/wazuh$ journalctl -t test_unit
Aug 21 12:58:14 gasti test_unit[69823]: 69823
Aug 21 12:58:14 gasti test_unit[69824]: 69824
Aug 21 12:58:14 gasti test_unit[69825]: 69825
Aug 21 12:58:14 gasti test_unit[69826]: 69826
Aug 21 12:58:14 gasti test_unit[69827]: 69827
```

</details>

**Comment by GGP1** [comment]
## Conclusion

After discussing it with the team, we have come to the conclusion that we will log all messages to the standard streams (stdout, stderr).

We expect Wazuh to be executed as a systemd service or inside Docker containers. In the first case, all prints to the standard streams will be captured by journald, in the second case, they will be handled by the Docker daemon (if the user specifies the [journald logging driver](https://docs.docker.com/engine/logging/drivers/journald/), all the container logs will be send to journald).

In addition to this, we will offer different logging handlers where the users can choose if they would like to have the logs in a file, send them to a remote location, etc.

> If the main Wazuh process is executed manually, it is expected that the logs won't appear in journald or any other place other than the standard streams and the configured log files/remote host.

**Comment by RamosFe** [comment]
### Review

LGTM 🚀

**Comment by fdalmaup** [comment]
# Review

The pure Python logging approach was not necessary due to design decisions.

Great analysis. LGTM!
