### ISSUE TITLE
Add coverage report for the engine unit test action

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#25333]
## Description
This issue aims to add a coverage report to the CI engine chain.

## Expected
We expect to add a report about the current coverage that runs in every engine change or on-demand trigger (for evidence purposes).

Since we do not know the current coverage, a failure is not expected at a certain low coverage number but we expect the mechanism.

## Implementation restrictions.
- Use Engine unit test github action to implement this.
- No adding new scripts.
- No modify any code C++ line.

**Comment by juliancnn** [comment]
## Update

Based on the initial implementation of coverage from issue #25292 (currently in pending final review) and after a meeting with @pereyra-m regarding his issue #24944, I have developed a Proof of Concept (PoC) locally with several modifications using the following approach:


***General coverage***

```bash
# Base
lcov --no-external  --capture --initial --directory ./ --output-file build/coverage_base.info  --ignore-errors mismatch
ctest --test-dir build/ -j
# After ctest
lcov --no-external  --capture --directory ./ --output-file build/coverage_after.info  --ignore-errors mismatch
# Merge
lcov --add-tracefile build/coverage_base.info --add-tracefile build/coverage_after.info --output-file build/coverage_total.info
# Remove
lcov --remove build/coverage_total.info '*/test/*' '*/build/vcpkg_installed/*' --output-file build/coverage_filtered.info
# Generate report
cd build
genhtml coverage_filtered.info --output-directory coverage_report
```

***Module coverage***
This can also be implemented module by module due to the directory structure of wazuh-engine:
For example, for the API:


```bash
lcov --no-external --capture --initial --directory ./build/source/api/ --base-directory ./source/api/ --output-file build/coverage_base.info --ignore-errors mismatch
ctest --test-dir ./build/source/api/ -j
lcov --no-external --capture --directory ./build/source/api/ --base-directory ./source/api/ --output-file build/coverage_after.info --ignore-errors mismatch
lcov --add-tracefile build/coverage_base.info --add-tracefile build/coverage_after.info --output-file build/coverage_total.info
lcov --remove build/coverage_total.info '*/test/*' '*/build/vcpkg_installed/*' --output-file build/coverage_filtered.info --ignore-errors unused
cd build
genhtml coverage_filtered.info --output-directory coverage_report --prefix ./source/api/
```

### Implementation Strategy and Next Steps

I will be looking for changes under the ./source/${module} directory where ${module} is the module to determine coverage for. I haven't yet assessed the feasibility of doing this with GitHub workflows, but this will be my next step. After this, an analysis of the results in the generated report is necessary.

### Mismatch Error (Orchestrator module)


I am currently running the coverage with the option --ignore-errors mismatch due to a mismatch error in the orchestrator module that I have not been able to resolve. The time dedicated has not been sufficient to identify the root problem:


```plainttext
lcov --no-external  --capture --initial --directory ./ --output-file build/coverage_base.info  --ignore-errors mismatch

Capturing coverage data from ./
geninfo cmd: '/usr/bin/geninfo ./ --output-filename build/coverage_base.info --ignore-errors mismatch --initial --no-external --memory 0'
Found gcov version: 13.2.0
Using intermediate gcov format
Writing temporary data to /tmp/geninfo_datyv1W
Scanning ./ for .gcno files ...
Found 284 graph files in ./
Processing ./build/CMakeFiles/3.30.2/CompilerIdC/a-CMakeCCompilerId.gcno
Processing ./build/CMakeFiles/3.30.2/CompilerIdCXX/a-CMakeCXXCompilerId.gcno
Processing ./build/source/router/CMakeFiles/router_ctest.dir/test/src/component/tester_test.cpp.gcno
geninfo: WARNING: ('mismatch') mismatched end line for _ZN40OrchestratorTesterTest_AddTestEntry_Test8TestBodyEv at /workspaces/repos/wazuh/src/engine/source/router/test/src/component/tester_test.cpp:122: 122 -> 134
geninfo: WARNING: ('mismatch') mismatched end line for _ZN48OrchestratorTesterTest_AddMultipleTestEntry_Test8TestBodyEv at /workspaces/repos/wazuh/src/engine/source/router/test/src/component/tester_test.cpp:136: 136 -> 151
        (use "geninfo --ignore-errors mismatch,mismatch ..." to suppress this warning)
geninfo: WARNING: ('mismatch') mismatched end line for _ZN45OrchestratorTesterTest_AddEqualTestEntry_Test8TestBodyEv at /workspaces/repos/wazuh/src/engine/source/router/test/src/component/tester_test.cpp:153: 153 -> 168
        (use "geninfo --ignore-errors mismatch,mismatch ..." to suppress this warning)
geninfo: WARNING: ('mismatch') mismatched end line for _ZN54OrchestratorTesterTest_DeleteTestEntryWithoutName_Test8TestBodyEv at /workspaces/repos/wazuh/src/engine/source/router/test/src/component/tester_test.cpp:170: 170 -> 177
        (use "geninfo --ignore-errors mismatch,mismatch ..." to suppress this warning)
geninfo: WARNING: ('mismatch') mismatched end line for _ZN43OrchestratorTesterTest_DeleteTestEntry_Test8TestBodyEv at /workspaces/repos/wazuh/src/engine/source/router/test/src/component/tester_test.cpp:179: 179 -> 192
        (use "geninfo --ignore-errors mismatch,mismatch ..." to suppress this warning)

```

**Comment by juliancnn** [comment]
## Update

The Workflow is already in its first phase, currently:

- Dynamically identifies engine modules. 
- It identifies which of these modules have been modified and still exist, i.e. they are not deleted modules.
- Executes the coverage for each modified module, generating reports for each modified module.
- The coverage has as a base before its first execution the module tests.
- Added the possibility to run the coverage of all modules manually.
- Supports module exclusion list.
- Reports are uploaded as artifacts, allowing download for 1 day, then automatically deleted.


The workflow has a good base but is still under development. There are still many things to investigate and improve:
- The CMake cache does not work, and it is shared with the other workflows of the wazuh-engine.
-  The missmach error in some modules still present ([here](https://github.com/wazuh/wazuh/issues/25333#issuecomment-2307717827))
- While the HTML report is generated correctly with `genhtml` there seems to be a problem when reading the same file with lcov, since the coverage of the functions is always zero and `%` are strange (out of range). And if the same file is used to generate the HTML report the output is correct. for example:
API:
  - HTML Report
![image](https://github.com/user-attachments/assets/7c634855-bfb8-45c4-af84-ef8b3d842665)

  - LCov same file report
      ```console
      ╰─# lcov --list ./src/engine/build/coverage_api_filtered.info                                                                            1 ↵
                                              |Lines       |Functions  |Branches    
      Filename                                |Rate     Num|Rate    Num|Rate     Num
      ==============================================================================
      [/workspaces/repos/wazuh/src/engine/source/api/]
      include/api/adapter.hpp                 | 426%     27| 0.0%    83|    -      0
      include/api/api.hpp                     |22.9%     35| 0.0%     7|    -      0
      include/api/catalog/catalog.hpp         | 200%      1| 0.0%     1|    -      0
      include/api/catalog/resource.hpp        | 9.1%     55| 0.0%     5|    -      0
      include/api/policy/policy.hpp           |12.5%      8| 0.0%     1|    -      0
      include/api/registry.hpp                |28.6%      7| 0.0%     2|    -      0
      src/catalog/catalog.cpp                 |12.8%    156| 0.0%    17|    -      0
      src/catalog/handlers.cpp                |13.0%    100| 0.0%     8|    -      0
      src/geo/handlers.cpp                    |18.2%     66| 0.0%    12|    -      0
      src/graph/handlers.cpp                  |    -      0|    -     0|    -      0
      src/kvdb/handlers.cpp                   | 8.0%    213| 0.0%    17|    -      0
      src/metrics/handlers.cpp                |    -      0|    -     0|    -      0
      src/policy/handlers.cpp                 |17.8%    258| 0.0%    42|    -      0
      src/policy/policy.cpp                   | 9.8%    173| 0.0%    17|    -      0
      src/policy/policyRep.hpp                |10.6%    180| 0.0%    19|    -      0
      src/registry.cpp                        |15.8%     19| 0.0%     3|    -      0
      src/router/handlers.cpp                 |29.5%    129| 0.0%    25|    -      0
      src/tester/handlers.cpp                 |17.4%    138| 0.0%    21|    -      0
      ==============================================================================
                                        Total:|22.7%   1565| 0.0%   280|    -      0
      ```

**Comment by juliancnn** [comment]
## Update

- Minor repairs were made for corner cases
- Fixed console coverage, allowing to see the coverage without having a complete report
- Excluded test code as part of coverage and also fixed missmach issues related to this. The gtest library seems to modify the original code, sometimes generating these problems.
- Added a step, which publishes a summary in the PR about the coverage, like the following image:

  ![image](https://github.com/user-attachments/assets/c18d9f32-ddd2-40c6-a20f-ff3d066bc85d)

- Currently it is not possible to obtain the coverage of the feedmanager and vscanner modules. The next step will be to solve this problem.

**Comment by juliancnn** [comment]
## Update

- Fixed logpar discovery test
- Fixed Indexer connector issues
- Minor improvment of workflow (bug parallel test and stage final check)
- Test with all modules
- Ready for review
