### ISSUE TITLE
Change the logger output to the stdout

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#25334]
## Description

This issue aims to change the logging output to the stdout.

Basically wazuh in 5.0.0 we will log into the stdout because when the engine runs into systems all stdout logs are written into the journals.

For docker executions, we maintain this and expect the users to have a custom driver.

**Comment by NahuFigueroa97** [comment]
## Update

- Remove the possibility of indicating another destination for the logger other than standard output
- Fix the vdscanner module so that it does not accept the logger output format as a parameter
- Correct tests that used files

**Comment by NahuFigueroa97** [comment]
## Update

- Investigate journal logging via stdout and stderr https://github.com/systemd/systemd/pull/6599.
- Try solution using two sinks, one for stdout and another for stderr (warning logs are duplicated from now on)
- Implement a custom sink to log to both stdout and stderr using a single sink instead of two
