### ISSUE TITLE
No events are displayed in the Vulnerabilities Detection dashboard

### ISSUE THREAD

**Issue by imartos-teradisk** [wazuh/wazuh#25421]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.2-1 | wazuh-dashboard | Manager | wazuh-dashboard | Ubuntu 20.04.6 LTS |

After upgrade from 4.7 to 4.8 the index of vulnerabilities changes from wazuh-alerts-* to wazuh-states-vulnerabilities-HOSTNAME. The dashboard "Vulnerability Detection" show the information correctly, but in the tab "Events" it doesn't show any event, and it's not possible changes the index pattern to "wazuh-states-*".

![image](https://github.com/user-attachments/assets/7031f1dd-1281-4c62-8df4-887ae1ce0f2a)

![image](https://github.com/user-attachments/assets/1705c3ec-a5f5-4e27-a88e-dbdab53cf921)

**Comment by MiguelazoDS** [comment]
@imartos-teradisk, 

The index `wazuh-alerts-*` did not change, it's still present in 4.8.x but additionally, we now have another index `wazuh-states-vulnerabilities-HOSTNAME` 

The first index contains the alerted events in alerts.json shipped by Filebeat, and the second one uses the indexer connector (a feature embedded in the vulnerability detector module) that indexes the vulnerabilities found in agents.

The type of document those indexes have is completely different, you can not interchange that. 

You are not seeing alerts because the events were silenced during synchronization to avoid flooding. If you install a package and wait for syscollector to report its changes, you will see an event for that last package.

I hope I was clear. Regards!

**Comment by sebasfalcone** [comment]
Inactive thread, please re-open it if necessary
