### ISSUE TITLE
Update logging macro calls in the Engine's lambdas

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#25455]
## Description
As developed in #25326 we need to update the logging macro calls used in the Engine that are inside a macro.

## Expected
- Replace all `LOG_<level>` macros with the corresponding `LOG_<level>_L` macro when inside a lambda.

**Comment by juliancnn** [comment]
maybe in the future use something like this for std::string support
```
template<typename FuncNameType, typename... Args>
void logDebugL(FuncNameType&& functionName, const char* msg, Args&&... args) {
    const char* funcName_cstr = std::is_same<std::decay_t<FuncNameType>, std::string>::value ? functionName.c_str() : functionName;

    logging::getDefaultLogger()->log(
        spdlog::source_loc{__FILE__, __LINE__, funcName_cstr}, 
        spdlog::level::debug, 
        msg, 
        std::forward<Args>(args)...
    );
}
```

**Comment by NahuFigueroa97** [comment]
Currently the tests do not pass because the iana database cannot be downloaded. An issue was created in the date library https://github.com/HowardHinnant/date/issues/836 and also an issue in iana.org that maintains these databases:
https://lists.iana.org/hyperkitty/list/tz@iana.org/thread/LBVCBNK5NPWBNQ5UDUY3YEZPWA2QV262/

**Comment by Dwordcito** [comment]
Re-estimated due problem in the IANA database.
