### ISSUE TITLE
Footprint - Increase in Disk_read by wazuh-modulesd in Ubuntu agent

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh#25552]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-rc2 | Wazuh Agent | Agent | Packages | Ubuntu |

## Description

During testing in [Release 4.9.0 - RC 2 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS](https://github.com/wazuh/wazuh/issues/25529), it has been detected a high increase in the `Disk_read` plot by `wazuh-modulesd` in the Ubuntu agent test. This increase has not been seen in any previous stage or version.

The plots have been compared with [4.8.1 - RC 2](https://github.com/wazuh/wazuh/issues/24537).

| 4.9.0 | 4.8.1 |
| --- | --- | 
| ![image](https://github.com/user-attachments/assets/fe7c6768-2e55-4f27-994a-bf133ee63642) |  ![image](https://github.com/user-attachments/assets/b3311d58-091a-4fba-87db-e1b0f9ce7ebb) | 

**4.9.0-RC1**

![image](https://github.com/user-attachments/assets/c1b6c915-7fa1-4b9e-9251-533a8a6f42f0)

## Evidences

[ossec_Test_stress_B5575_ubuntu_2024-09-02.zip](https://github.com/user-attachments/files/16845807/ossec_Test_stress_B5575_ubuntu_2024-09-02.zip)

**Comment by vikman90** [comment]
Let's compare across recent builds:

## Disk read

|4.8.1 RC 2|4.9.0 RC 1|4.9.0 RC 2|
|---|---|---|
|![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5406-3600m/B5406_agent_ubuntu/plots/monitor-agent-Test_stress_B5406_ubuntu-pre-release_Disk_Read.png)|![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5527-3600m/B5527_agent_ubuntu/plots/monitor-agent-Test_stress_B5527_ubuntu-pre-release_Disk_Read.png)|![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5575-3600m/B5575_agent_ubuntu/plots/monitor-agent-Test_stress_B5575_ubuntu-pre-release_Disk_Read.png)|

### Maximum values

|Daemon|4.8.1 RC 2|4.9.0 RC 1|4.9.0 RC 2|
|---|---|---|---|
|wazuh-agentd|8 MB|12 MB|12 MB|
|wazuh-modulesd|12 MB|12 MB|350 MB|

## Rationale

We should compare the `read_ops` value instead of `read_bytes` (`disk_read`) as this one implies the storage layer:

|proc|psutil|Meaning|
|--|--|--|
|rchar|:x:|Bytes requested to read|
|wchar|:x:|Bytes requested to write|
|syscr|read_ops|Calls to `read`|
|syscw|write_ops|Calls to `write`|
|read_bytes|read_bytes|Bytes effectively read from the storage layer|
|write_bytes|write_bytes|Bytes effectively written to the storage layer|

## Read Ops

|4.8.1 RC 2|4.9.0 RC 1|4.9.0 RC 2|
|---|---|---|
|Read Ops: ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5406-3600m/B5406_agent_ubuntu/plots/monitor-agent-Test_stress_B5406_ubuntu-pre-release_Read_Ops.png)|Read Ops: ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5527-3600m/B5527_agent_ubuntu/plots/monitor-agent-Test_stress_B5527_ubuntu-pre-release_Read_Ops.png)|Read Ops: ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5575-3600m/B5575_agent_ubuntu/plots/monitor-agent-Test_stress_B5575_ubuntu-pre-release_Read_Ops.png)|

### Maximum values

|Daemon|4.8.1 RC 2|4.9.0 RC 1|4.9.0 RC 2|
|---|---|---|---|
|wazuh-agentd|600 MB|480 MB|720 MB|
|wazuh-modulesd|580 MB|560 MB|600 MB|

## Conclusion

We cannot see such big difference in the `Read_Ops` chart. There are some differences but not very significant.

The fact that there is a large difference in Disk_Read could be due to a cache miss on the agent host.
