### ISSUE TITLE
Vulnerability Detection - Old CVE came back when package was upgraded to latest version.

### ISSUE THREAD

**Issue by Nothing2024** [wazuh/wazuh#25566]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.8.2 | Vulnerability Detection Module | Manager | docker | Ubuntu 22.04|

Old CVE were reported when Chrome and Firefox were upgraded to the latest versions:
![image](https://github.com/user-attachments/assets/59835429-575f-4b13-a286-0b1c5c7cc35c)

As can be seen CVE-2013-6662 for Chrome had long been resolved. It was "solved" in version 114 but "active" again in 115.
Firefox 130.0 is the latest version as per writing. But CVE of 200x were reported in the Event tab.

**Comment by Damian-Mangold** [comment]
Hi @Nothing2024, in order to analyze the issue and perform some tests, could you please provide me with the following information from the agents where you're observing the issue?

- [OS information](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_os_info)
- [Package inventory](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_packages_info)
- Vulnerabilities inventory
- [Hotfix information](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_hotfix_info) (for Windows OS)


If you need help to obtain all the information, please consult [here](https://github.com/wazuh/wazuh/issues/25001#issuecomment-2275709492).

Thank you!

**Comment by Nothing2024** [comment]
[hotfixes.json](https://github.com/user-attachments/files/16869673/hotfixes.json)
[os.json](https://github.com/user-attachments/files/16869674/os.json)
[packages.json](https://github.com/user-attachments/files/16869675/packages.json)
[vulnerabilities_inventory-2024-09-04T11_41_25.669Z.csv](https://github.com/user-attachments/files/16869676/vulnerabilities_inventory-2024-09-04T11_41_25.669Z.csv)

**Comment by Damian-Mangold** [comment]
Hi @Nothing2024, after doing an analysis of the reported CVEs I was able to identify that they are false positives and a sanitization of the content should be performed. All false positives have been identified and are in the process of being corrected, I am sharing the follow up issue with you:

- [CVE-2013-6662](https://github.com/wazuh/wazuh/issues/24178#issuecomment-2179334322)
- [CVE-2008-2399](https://github.com/wazuh/wazuh/issues/24171#issuecomment-2191700881)
- [CVE-2008-4059](https://github.com/wazuh/wazuh/issues/24171#issuecomment-2191657445)
- [CVE-2009-4129](https://github.com/wazuh/wazuh/issues/24179#issuecomment-2189745416)
- [CVE-2007-4013](https://github.com/wazuh/wazuh/issues/24179#issuecomment-2189915913)
- [CVE-2014-6492](https://github.com/wazuh/wazuh/issues/24179#issuecomment-2189355248)
- [CVE-2007-6715](https://github.com/wazuh/wazuh/issues/24179#issuecomment-2189887562)

**Comment by Damian-Mangold** [comment]
We close the issue. If there is another question, we can reopen it.
