### ISSUE TITLE
Add manual triggers to GHA workflows

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#25656]
## Description

As part of [this](https://github.com/wazuh/internal-devel-requests/issues/1501) research, it was identified that many workflows that run tests on each PR do not have a manual trigger.

Some of them are the following:
- [x] All unit/component tests of new modules (syscollector, fim, ...).
- [x] Integration tests of new modules (syscollector, ...).
- [x] RTR workflows.

Also, the following items should be carefully reviewed:
- [x] Review triggers configuration.
- [ ] Separate the logic as _actions_ from the _workflows_.

**Comment by LucioDonda** [comment]
|Test type|Component|Workflow|Manual trigger|
|--|--|--|--|
|Unit/component|syscollector (data_provider/dbsync/rsync)| [LINK](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/rtr_syscollector.yml) | ⚪  |
|Unit/component|syscollector (data_provider/dbsync/rsync)| [LINK](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/macos-unit-tests.yml) | ⚪ |
|Unit/component|syscollector (data_provider/dbsync/rsync)| [LINK](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/rtr_syscollector.yml) | ⚪ |
|Unit/component|fim (db)| [LINK](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/rtr_syscheck.yml) | ⚪ |
|Unit/component|fim (db)| Not available | ⚪ |
|Unit/component|fim (db)| [LINK](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/rtr_syscheck.yml) | ⚪ |
|RTR (scan-build)|legacy| [LINK](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/scan-build.yml) | ⚪ |
|RTR (scan-build)|legacy| [LINK](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/scan-build.yml) | ⚪ |
|RTR (scan-build)|legacy| [LINK](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/scan-build.yml) | ⚪ |
|RTR (ASAN/AStyle/cppcheck/scan-build/valgrind)|syscollector (data_provider/dbsync/rsync)| [LINK](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/rtr_syscollector.yml) ([Repeated](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/scan-build.yml) scan-build) | ⚪ |
|RTR (ASAN/AStyle/cppcheck/scan-build/valgrind)|syscollector (data_provider/dbsync/rsync) | [LINK](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/scan-build.yml) (Only scan-build)|  ⚪ |
|RTR (ASAN/AStyle/cppcheck/scan-build/valgrind)|syscollector (data_provider/dbsync/rsync)| [LINK](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/rtr_syscollector.yml) ([Repeated](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/scan-build.yml) scan-build)  | ⚪ |
|RTR (ASAN/AStyle/cppcheck/scan-build/valgrind)|fim (db)| [LINK](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/rtr_syscheck.yml) ([Repeated](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/scan-build.yml) scan-build)  | ⚪ |
|RTR (ASAN/AStyle/cppcheck/scan-build/valgrind)|fim (db)| [LINK](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/scan-build.yml) (Only scan-build)| ⚪ |
|RTR (ASAN/AStyle/cppcheck/scan-build/valgrind)|fim (db)| [LINK](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/rtr_syscheck.yml) ([Repeated](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/scan-build.yml) scan-build)  | ⚪ |
|Integration|syscollector (data_provider/dbsync/rsync)| [LINK](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/ubuntu-syscollector-tests.yml)  | ⚪ |
|Integration|syscollector (data_provider/dbsync/rsync)| [LINK](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/macos-syscollector-tests.yml)  | ⚪ |
|Integration|syscollector (data_provider/dbsync/rsync)| [LINK](https://github.com/wazuh/wazuh/blob/4.10.0/.github/workflows/windows-syscollector-tests.yml)  | ⚪ |
|Unit|legacy (cmocka)| Jenkins | Jenkins |
|Unit|legacy (cmocka)| Not available |  ⚪ |
|Unit|legacy (cmocka)| Jenkins |  Jenkins |

**Comment by LucioDonda** [comment]
## Update 03/10/2024

The base requirements of the issue are included in the corresponding [PR](https://github.com/wazuh/wazuh/pull/26106) with some remarks:
* After merging that PR the changes might not impact inn the corresponding WF on the Actions tab.
* Based on this [issue](https://github.com/orgs/community/discussions/58022#discussioncomment-8716372) that branch should be part of master to achieve this (thanks @jnasselle ).
* Some files like [macos-unit-tests.yml](https://github.com/wazuh/wazuh/commits/4.10.0/.github/workflows/macos-build-tests.yml) that exists in the repository from more than a year are not present on master, that means that there might be some other out-dated workflows.
* Regarding the _Separate the logic as actions from the workflows._ there are several WF files with duplicated code that could be unified appropriately but IMO that should have it's own issue because it carries a completely different priority and it goes beyond this issue title and base idea.

@cborla  @vikman90
