### ISSUE TITLE
Error updating an agent remotely on Rocky 8.1

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh#25660]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0 | Agent| Agent | Packages | Rocky 8.1 |

# Description
Resolving the following issue https://github.com/wazuh/wazuh/issues/25645, it has been observed that on Rocky 8.1 machines, an agent cannot be updated remotely. The error reported by the user has been reproduced, and it has been found that using the` -f` option along with the downloaded WPK package does allow for the update.

## Error reproduced
![2024-09-09_19-37](https://github.com/user-attachments/assets/447f3562-8587-4ae6-81fd-2de641bcb9aa)

## Using -f option
![2024-09-09_19-52](https://github.com/user-attachments/assets/615f3799-ebbf-4ed2-a575-4f99eedb427e)

**Comment by TomasTurina** [comment]
This is expected behavior since Rocky Linux is not officially supported:
https://documentation.wazuh.com/current/installation-guide/packages-list.html

It is not on the list of officially supported RPM or DEB platforms:

```c
static const char* deb_platforms[] = {
    "debian",
    "ubuntu"
};

static const char* rpm_platforms[] = {
    "amzn",
    "centos",
    "fedora",
    "ol",
    "opensuse",
    "opensuse-leap",
    "opensuse-tumbleweed",
    "rhel",
    "sles",
    "suse"
};
```

For these operating systems you always have the option to use the force option or use a custom package.
