### ISSUE TITLE
API: Flask - Reimplement logging

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#2569]
This issue is related to #2413

Now we have implemented in Python both API and framework we can get better logs to debug any error in code. 
We also need to migrate from node to Python the rotation logic.

Tasks:
- [x] Redesign logs for API (review format, logging level, configuration, etc)
- [x] Migrate nodejs rotation logic to Python

**Comment by mgmacias95** [comment]
# Status update
## Summary
I have refactored the logging logic implemented in `wazuh-clusterd` binary. That way, the API and the Cluster will use the same code to do the logging. Then, I have configured `Flask` to update the user which is being logged at every `/login` request.
The development of this issue is in branch [`dev-flask-api-logging`](https://github.com/wazuh/wazuh/tree/dev-flask-api-logging).

## Tasks
* Refactor `wazuh-clusterd` logging (54d444b3bb7b263b00ac6cd9ad88cd9c96169200)
* Configure Flask to update user in logs every `/login` API call (82eba29e2c9c243aad6fc64a4f4b6d9f87cb5157).

## Pending tasks:
* Add logging configuration defined in https://github.com/wazuh/wazuh/issues/2570 to the new refactored code.
* Log each received requests using the API logger instead of the Flask/Connexion one: 
    ```
    172.17.0.100 - - [20/Feb/2019 20:33:13] "GET /agents?limit=1 HTTP/1.1" 401 -
    ```

**Comment by mgmacias95** [comment]
## Status update
### Summary
I have been able to format the `werkzeug` logger with the same formatting as the wazuh logger, including the user who performed the request in the API logs. I think an extra formatting is still necessary to remove repeated data such as request date:
```
# /var/ossec/bin/wazuh-apid -f
 * Serving Flask app "wazuh-apid" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
2019-03-04 13:26:47,115 INFO: * Running on http://0.0.0.0:55000/ (Press CTRL+C to quit)
2019-03-04 13:27:01,590 INFO: foo 127.0.0.1 - - [04/Mar/2019 13:27:01] "GET /login?pretty HTTP/1.1" 404 -
2019-03-04 13:27:26,490 INFO: foo 127.0.0.1 - - [04/Mar/2019 13:27:26] "GET /agents?pretty HTTP/1.1" 401 -
2019-03-04 13:27:37,789 ERROR: foo Exception on /token [GET]
2019-03-04 13:27:37,791 INFO: foo 127.0.0.1 - - [04/Mar/2019 13:27:37] "GET /token?pretty HTTP/1.1" 500 -
```
### Tasks
* Remove date from `werkzeug` logs (`[04/Mar/2019 13:27:37]`)

**Comment by mgmacias95** [comment]
I have figured out how to clean logs from werkzeug server. Now the logs look like this:
```
# /var/ossec/bin/wazuh-apid -f
 * Serving Flask app "wazuh-apid" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
2019-03-04 14:36:35,537 INFO: Running on http://0.0.0.0:55000/ (Press CTRL+C to quit)
2019-03-04 14:36:38,299 INFO: marta 127.0.0.1 - -  "GET /login?pretty HTTP/1.1" 404 -
2019-03-04 14:36:44,017 INFO:  127.0.0.1 - -  "GET /agents?pretty HTTP/1.1" 401 -
```
I have also improved the way the user is logged: it's updated in each new request. Before this change, the old requests' user was logged if the current requests didnt include a username.
