### ISSUE TITLE
Investigate a possible bug on vulnerabilities shown for already deleted agents

### ISSUE THREAD

**Issue by matias-braida** [wazuh/wazuh#25698]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.x | Vulnerability Detector | Manager | - | - |

## Description 

In this [community](https://github.com/wazuh/community/issues/32716) the user reported that some of their agents were deleted from the manager, but they still could see their vulnerabilities.

The user says that he has this issue only for agents installed using a previous version of the manager (in this case, 4.7.1). But on agents that are installed using version 4.8.x and then removed, for those agents, the vulnerabilities are correctly removed.

This issue intends to investigate the existence of this possible bug.

As a context information, the user says that he has only one manager installed in his deployment:
![image](https://github.com/user-attachments/assets/4d1d5094-4456-4767-a965-9869a64cd283)

**Comment by GabrielEValenzuela** [comment]
# Update

- Research in progress

**Comment by GabrielEValenzuela** [comment]
# Update

- Task unable to continue due to high priority tasks. Resume ASAP

**Comment by sebasfalcone** [comment]
## Update
Moving this to 4.10.1 as this is a pre-existing bug

**Comment by GabrielEValenzuela** [comment]
# Update

- Task unable to continue due to high priority tasks. Resume ASAP

**Comment by GabrielEValenzuela** [comment]
# Vulnerability Detection Evaluation Report

## Introduction

This report presents the installation, upgrade, and assessment of a vulnerability detection system on a Windows 10 (22H2) agent. The focus is on evaluating the functionality of manager versions **4.7.5** and **4.8.1**, the accuracy of vulnerability detection, remediation effectiveness, and identifying potential issues related to deleted agents.

## Initial Installation and Scan

We initiated the process by installing **Manager Version 4.7.5** with the appropriate configuration of the **Vulnerability Detector** module. An initial scan was performed on a freshly installed Windows 10 (22H2) agent, which resulted in the detection of **500 vulnerabilities** approximately.

## Upgrade to Manager Version 4.8.1

Following the initial scan, we upgraded the manager to **Version 4.8.1** and allowed the offset update process to complete. During this phase, we observed:

- **Retention of Previous Events**: Events generated by the vulnerability detection in the previous version were still present. Which is an expected behavior.
- **Enhanced Detection Capabilities**: New vulnerabilities were identified due to the increased precision of the updated scanner. Which is an expected behavior.

## Post-Upgrade Observations

After completing the upgrade:

- **Remediation Events Generated**: Events corresponding to the remediation of associated (KB) updates were generated.
- **Inventory Discrepancies**: Some vulnerabilities remained active but were not displayed in the inventory, indicating that the database appeared empty. This suggests potential issues with database synchronization or update processes.

## Additional Testing with Firefox

To further evaluate the system's detection and remediation capabilities, we installed a potentially vulnerable version of Firefox (**Version 109**). Upon completing the scan and subsequently deleting the agent:

- **Complete Removal of Vulnerabilities**: All **185 detected vulnerabilities** were entirely removed from the inventory.

## Issue Analysis

Referencing existing reports:

- **"Unigen Corporation | Vulnerability Events for Deleted Agents #3218"**: Observed a total of **322 agents**.
- **"Investigate a Possible Bug on Vulnerabilities Shown for Already Deleted Agents #25698"**: Noted a total of **165 agents**.

These findings suggest that the issue may originate from a step in the orchestration process. Specifically, concurrent execution during orchestration or timing discrepancies during the transmission of updated information to the indexer could be causing the persistence of vulnerabilities associated with deleted agents.

## Conclusion

Throughout approximately **4 hours** of system operation, no recurrent alert transmissions were observed. The evaluation indicates potential flaws in the orchestration process related to agent deletion and database synchronization. There is not an evident relation with Vulnerability scanner: The inventory synchronization events won't be processed if the Indexer module is disabled #25799, but we can discard it. 
This issue is very close to the environment setup, which makes it difficult to reproduce.

We should:

- **Investigate Database Synchronization**: Examine the mechanisms responsible for updating the inventory database to resolve discrepancies where active vulnerabilities are not displayed or find the cause is the indexer, please take into consideration that we are not using the last stable version of Wazuh during these tests. 
- **Review Orchestration Steps**: Analyze the orchestration process during concurrent executions to identify any timing issues affecting the update of information to the indexer.

**Comment by GabrielEValenzuela** [comment]
# Vulnerability Detection Evaluation Report

## Introduction

This report presents the installation, upgrade, and assessment of a vulnerability detection system on a Windows 10 (22H2) agent. The focus is on evaluating the functionality of manager versions **4.7.5** and **4.8.1**, the accuracy of vulnerability detection, remediation effectiveness, and identifying potential issues related to deleted agents.

## Initial Installation and Scan

We initiated the process by installing **Manager Version 4.7.5** with the appropriate configuration of the **Vulnerability Detector** module. An initial scan was performed on a freshly installed Windows 10 (22H2) agent, which resulted in the detection of **500 vulnerabilities** approximately.

## Upgrade to Manager Version 4.8.1

Following the initial scan, we upgraded the manager to **Version 4.8.1** and allowed the offset update process to complete. During this phase, we observed:

- **Retention of Previous Events**: Events generated by the vulnerability detection in the previous version were still present. Which is an expected behavior.
- **Enhanced Detection Capabilities**: New vulnerabilities were identified due to the increased precision of the updated scanner. Which is an expected behavior.

## Post-Upgrade Observations

After completing the upgrade:

- **Remediation Events Generated**: Events corresponding to the remediation of associated (KB) updates were generated.
- **Inventory Discrepancies**: Some vulnerabilities remained active but were not displayed in the inventory, indicating that the database appeared empty. This suggests potential issues with database synchronization or update processes.

## Additional Testing with Firefox

To further evaluate the system's detection and remediation capabilities, we installed a potentially vulnerable version of Firefox (**Version 109**). Upon completing the scan and subsequently deleting the agent:

- **Complete Removal of Vulnerabilities**: All **185 detected vulnerabilities** were entirely removed from the inventory.

## Issue Analysis

Referencing existing reports:

- **"Investigate a Possible Bug on Vulnerabilities Shown for Already Deleted Agents #25698"**: Noted a total of **165 agents**.

These findings suggest that the issue may originate from a step in the orchestration process. Specifically, concurrent execution during orchestration or timing discrepancies during the transmission of updated information to the indexer could be causing the persistence of vulnerabilities associated with deleted agents.

## Conclusion

Throughout approximately **4 hours** of system operation, no recurrent alert transmissions were observed. The evaluation indicates potential flaws in the orchestration process related to agent deletion and database synchronization. There is not an evident relation with Vulnerability scanner: The inventory synchronization events won't be processed if the Indexer module is disabled #25799, but we can discard it. 
This issue is very close to the environment setup, which makes it difficult to reproduce.

We should:

- **Investigate Database Synchronization**: Examine the mechanisms responsible for updating the inventory database to resolve discrepancies where active vulnerabilities are not displayed or find the cause is the indexer, please take into consideration that we are not using the last stable version of Wazuh during these tests. 
- **Review Orchestration Steps**: Analyze the orchestration process during concurrent executions to identify any timing issues affecting the update of information to the indexer.

**Comment by sebasfalcone** [comment]
## ETA update
We are going to discuss the continuation of this issue tomorrow

**Comment by GabrielEValenzuela** [comment]
We created this troubleshooting guide that may help to solve this

---------------

### **Step 1: Stop the Wazuh Manager**

To begin, stop the Wazuh manager to prevent any processes from interfering during the reset.

```bash
sudo systemctl stop wazuh-manager
```

### **Step 2: Disable the Vulnerability Detector Module**

Edit the Wazuh configuration file to disable the Vulnerability Detector temporarily.

```bash
sudo nano /var/ossec/etc/ossec.conf
```

Locate the `<vulnerability-detector>` section and change the `<enabled>` parameter to `no`:

```xml
<vulnerability-detector>
    <enabled>no</enabled>
    <!-- Other configurations -->
</vulnerability-detector>
```

Save and exit the editor (`Ctrl+O`, `Enter`, `Ctrl+X`).


### **Step 3: Remove the Vulnerability Detector Inventory**

Delete the inventory directory to remove all cached vulnerability data.

```bash
sudo rm -rf /var/ossec/queue/vd/inventory/
```


### **Step 4: Remove the Indexer's Local Queue and Database**

Clear the Indexer's local queue and database to ensure no residual data remains.

```bash
sudo rm -rf /var/ossec/queue/indexer/
```

### **Step 5: Remove the Vulnerabilities Index from Elasticsearch/OpenSearch**

Delete the existing vulnerabilities index to remove stored vulnerability data.

  ```bash
  curl -X DELETE "http://<INDEXER_IP>/wazuh-states-vulnerabilities/*" -u <INDEXER_USER> -k <INDEXER_PASSWORD>
  ```

> **Note:** Replace `<INDEXER_IP>` with your Indexer IP address, in most of cases is `127.0.0.1`,  `<INDEXER_USER>` with the indexer user, in most of cases is `admin` and `<INDEXER_PASSWORD>` with the indexer password.


### **Step 6: Start the Wazuh Manager**

Restart the Wazuh manager to apply the changes.

```bash
sudo systemctl start wazuh-manager
```

At this point, all previous vulnerability data should be cleared.


### **Step 7: Re-enable the Vulnerability Detector Module**

Edit the configuration file again to re-enable the Vulnerability Detector.

```bash
sudo nano /var/ossec/etc/ossec.conf
```

Set the `<enabled>` parameter back to `yes`:

```xml
<vulnerability-detector>
    <enabled>yes</enabled>
    <!-- Other configurations -->
</vulnerability-detector>
```

Save and exit the editor.


### **Step 8: Restart the Wazuh Manager**

Restart the manager to initiate a fresh vulnerability scan.

```bash
sudo systemctl restart wazuh-manager
```


### **Step 9: Verify the Vulnerability Scan**

Monitor the logs to ensure that agents are being rescanned and new indices are being created.

```bash
sudo tail -f /var/ossec/logs/ossec.log
```

Look for entries indicating that the Vulnerability Detector is scanning agents and that new data is being indexed.

**Comment by sebasfalcone** [comment]
## Issue conclusion
On top of what @GabrielEValenzuela exposes as a workaround, we identified this issue and are attempting to fix it. It can be divided into two parts:
- https://github.com/wazuh/wazuh/issues/25799
- https://github.com/wazuh/wazuh/issues/25800
