### ISSUE TITLE
Investigate Integration with WMI API for Retrieving Installed Windows Updates

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#25765]
**Parent Issue:**

- #25760

## Description

The purpose of this spike is to investigate how to integrate the Wazuh agent with the WMI API to retrieve a list of installed Windows updates. This will help determine the feasibility, required resources, and design approach for the integration.

## Requirements

- Investigate the WMI API and how to query it for installed Windows updates.
- Identify any potential challenges or limitations in accessing this information via WMI.
- Research compatibility across different versions of Windows.

## Definition of Done

- [x] A report outlining the steps required to integrate with the WMI API.
- [x] A proposed design for the integration, including any limitations or challenges.
- [x] A decision on the next steps for development.

**Comment by MarcelKemp** [comment]
## Research

First of all, I have done a search about the pros and cons of **_WMIC_**, and I have searched if there are other alternatives to avoid the cons.

As it has happened in the past, **_WMIC_** does not collect all the hotfixes that are installed on the system, since it only returns the hotfixes that are installed manually or by local methods, sometimes omitting updates made by _Windows Update_.

Because of this problem, after some research, I have found the _Windows Update Agent_ (WUA) API, which collects the hotfixes that **_WMIC_** does not show, such as cumulative hotfixes, security hotfixes and other system patches.

The best option is probably to make use of both APIs, so that they can complement each other if necessary.

**Comment by MarcelKemp** [comment]
## Update

### APIs

As mentioned in the comment above, the two APIs used to get the list of hotfixes are:
- **WMI COM API**: https://learn.microsoft.com/en-gb/windows/win32/wmisdk/com-api-for-wmi
- **WUA API**: https://learn.microsoft.com/en-gb/windows/win32/wua_sdk/portal-client

With these two APIs, we try to cover all options to detect installed hotfixes. 
However, as a last step, the hotfix collection through the Windows registry will still be maintained, so that it will continue to work as it currently does, but trying to get the hotfixes that we can't get from the registry.
> As this is a `set` of `strings`, no duplicates will appear.

### Testing APIs

<details>
<summary>Code</summary>

The code has been compiled and tested in a _Visual Studio Community_ environment, where all the necessary libraries of the Windows APIs were available:

```cpp
#include <wbemidl.h>
#include <comdef.h>
#include <wuapi.h>
#include <iostream>
#include <set>
#include <regex>
#include <codecvt>

#pragma comment(lib, "wbemuuid.lib")

std::string BstrToString(BSTR bstr) {
    std::wstring_convert<std::codecvt_utf8<wchar_t>> converter;
    std::wstring wstr(bstr, SysStringLen(bstr));
    return converter.to_bytes(wstr);
}

void QueryWMIHotFixes(std::set<std::string>& hotfixSet) {
    HRESULT hres;
    IWbemLocator* pLoc = NULL;
    IWbemServices* pSvc = NULL;
    std::cout << "Querying hotfixes using WMI..." << std::endl;

    hres = CoCreateInstance(CLSID_WbemLocator, 0, CLSCTX_INPROC_SERVER, IID_IWbemLocator, (LPVOID*)&pLoc);
    if (FAILED(hres)) {
        std::cout << "Error creating IWbemLocator. Code: " << std::hex << hres << std::endl;
        return;
    }

    hres = pLoc->ConnectServer(_bstr_t(L"ROOT\\CIMV2"), NULL, NULL, 0, 0, 0, 0, &pSvc);
    if (FAILED(hres)) {
        std::cout << "Error connecting to WMI. Code: " << std::hex << hres << std::endl;
        pLoc->Release();
        return;
    }

    hres = CoSetProxyBlanket(pSvc, RPC_C_AUTHN_WINNT, RPC_C_AUTHZ_NONE, NULL, RPC_C_AUTHN_LEVEL_CALL, RPC_C_IMP_LEVEL_IMPERSONATE, NULL, EOAC_NONE);
    if (FAILED(hres)) {
        std::cout << "Error setting security on WMI. Code: " << std::hex << hres << std::endl;
        pSvc->Release();
        pLoc->Release();
        return;
    }

    IEnumWbemClassObject* pEnumerator = NULL;
    hres = pSvc->ExecQuery(bstr_t("WQL"), bstr_t("SELECT * FROM Win32_QuickFixEngineering"), WBEM_FLAG_FORWARD_ONLY | WBEM_FLAG_RETURN_IMMEDIATELY, NULL, &pEnumerator);
    if (FAILED(hres)) {
        std::cout << "Error executing WMI query. Code: " << std::hex << hres << std::endl;
        pSvc->Release();
        pLoc->Release();
        return;
    }

    IWbemClassObject* pclsObj = NULL;
    ULONG uReturn = 0;

    while (pEnumerator) {
        HRESULT hr = pEnumerator->Next(WBEM_INFINITE, 1, &pclsObj, &uReturn);
        if (0 == uReturn) {
            break;
        }

        VARIANT vtProp;
        hr = pclsObj->Get(L"HotFixID", 0, &vtProp, 0, 0);
        if (SUCCEEDED(hr) && vtProp.vt == VT_BSTR) {
            std::string hotfix = BstrToString(vtProp.bstrVal);
            if (hotfixSet.find(hotfix) == hotfixSet.end()) {
                hotfixSet.insert(hotfix);
                std::cout << "New HotFix found: " << hotfix << std::endl; // Debugging
            }
        }
        VariantClear(&vtProp);
        pclsObj->Release();
    }

    pSvc->Release();
    pLoc->Release();
    pEnumerator->Release();
}

void QueryWUHotFixes(std::set<std::string>& hotfixSet) {
    HRESULT hres;
    IUpdateSearcher* pUpdateSearcher = NULL;
    IUpdateHistoryEntryCollection* pHistory = NULL;
    std::regex hotfixRegex("KB[0-9]+");
    std::cout << "Querying hotfixes using Windows Update API..." << std::endl;

    hres = CoCreateInstance(__uuidof(UpdateSearcher), NULL, CLSCTX_INPROC_SERVER, __uuidof(IUpdateSearcher), (LPVOID*)&pUpdateSearcher);
    if (FAILED(hres)) {
        std::cout << "Error creating IUpdateSearcher. Code: " << std::hex << hres << std::endl;
        return;
    }

    LONG count;
    hres = pUpdateSearcher->GetTotalHistoryCount(&count);
    if (FAILED(hres)) {
        std::cout << "Error getting total update history count. Code: " << std::hex << hres << std::endl;
        pUpdateSearcher->Release();
        return;
    }

    std::cout << "Total number of updates in history: " << count << std::endl;

    hres = pUpdateSearcher->QueryHistory(0, count, &pHistory);
    if (FAILED(hres)) {
        std::cout << "Error querying update history. Code: " << std::hex << hres << std::endl;
        pUpdateSearcher->Release();
        return;
    }

    LONG historyCount;
    pHistory->get_Count(&historyCount);

    for (LONG i = 0; i < historyCount; ++i) {
        IUpdateHistoryEntry* pEntry = NULL;
        pHistory->get_Item(i, &pEntry);
        BSTR title;
        pEntry->get_Title(&title);
        std::string titleStr = BstrToString(title);

        std::smatch match;
        if (std::regex_search(titleStr, match, hotfixRegex)) {
            std::string hotfix = match[0];
            if (hotfixSet.find(hotfix) == hotfixSet.end()) {
                hotfixSet.insert(hotfix);
                std::cout << "New HotFix found: " << hotfix << std::endl; // Debugging
            }
        }
        pEntry->Release();
        SysFreeString(title);
    }

    pHistory->Release();
    pUpdateSearcher->Release();
}

int main() {
    // Initialize COM
    HRESULT hres = CoInitializeEx(0, COINIT_MULTITHREADED);
    if (FAILED(hres)) {
        std::wcout << L"Error initializing COM. Code: " << std::hex << hres << std::endl;
        return 1;
    }

    // Set to store and avoid duplicate hotfixes
    std::set<std::string> hotfixSet;

    // Query hotfixes using WMI
    QueryWMIHotFixes(hotfixSet);

    // Query hotfixes using Windows Update API
    QueryWUHotFixes(hotfixSet);

    // Display collected hotfixes
    std::wcout << L"List of installed hotfixes:" << std::endl;
    int totalHotfixes = 0;
    for (const auto& hotfix : hotfixSet) {
        std::cout << "- " << hotfix << std::endl;
        ++totalHotfixes;
    }
    std::cout << "Total number of installed hotfixes: " << totalHotfixes << std::endl;

    // Uninitialize COM
    CoUninitialize();

    return 0;
}
```

</details>

### Adaptation to current code

Using the above code we can get the list of hotfixes collected from both APIs, and by a `wstring` to `string` conversion, we adapt the `set` to be able to add it to the current code.

However, there are several issues to resolve when adapting this code with the current code:
- First, we need to adapt the CMakeLists to get the necessary libraries (`<wbemidl.h>`, `<comdef.h>`, `<wuapi.h>` & `wbemuuid.lib`) in order to compile without problems.
- Then, also related to the previous point, some functions may have to be modified by other alternative functions, so that there are no compilation problems or we don't have to add too many dependencies.
- And finally, verify and test that the code does not affect the support of old Windows, or in that case, limit the code so that it does not affect.

### Next steps

It would be necessary to start adapting the current Syscollector code for fetching hotfixes, adding the two APIs above:
- https://github.com/wazuh/wazuh/blob/ec78d1048c9264503aa4c2eab6e0cd028853ce3d/src/data_provider/src/sysInfoWin.cpp#L933-L951

To do this, you can adapt the functions tested for testing, so that the code looks like this:
1. Getting hotfixes via APIs -> Add hotfixes to `set`.
2. Get hotfixes from the logs -> Check if it exists (if not too much delay) and in case of adding a new hotfix, report it via debug, and add it to the `set`.
3. Add hotfixes in `JSON` format.

**Comment by MarcelKemp** [comment]
We close this issue and continue with the integration at:
- https://github.com/wazuh/wazuh/issues/25766. 

In case we need some extra research, we can reopen the issue.
