### ISSUE TITLE
Vulnerability-Inventory is not updated after system upgrade

### ISSUE THREAD

**Issue by ricokritzer** [wazuh/wazuh#25806]
|Wazuh version|Component|Install type|Platform|
|---|---|---|---|---|
| 4.9.0-7 | Vulnerability Detection | Manager/Agent | Ubuntu 24.04.1 LTS |

After upgrading my OS from Ubuntu 22.04.4 LTS to Ubuntu 24.04.1 LTS, vulnerability detection shows old vulnerabilities, which are resolved due to the system upgrade.

As you can see, Wazuh detects both the old and the new OS. After system upgrades, the database containing the old vulnerabilities should be removed.

![image](https://github.com/user-attachments/assets/8315e199-96bf-4a4e-a64d-ab2a595ff9cb)

**Comment by GabrielEValenzuela** [comment]
Hi @ricokritzer,

It seems that the issue is related to the change in your operating system version. Vulnerabilities are often tied to specific OS versions, and when you upgrade the OS, it may be considered a new installation.

We're currently aware of this behavior and are analyzing it further. In the meantime, we've created this troubleshooting guide that may help you resolve the issue:

---------------

### **Step 1: Stop the Wazuh Manager**

To begin, stop the Wazuh manager to prevent any processes from interfering during the reset.

```bash
sudo systemctl stop wazuh-manager
```

### **Step 2: Disable the Vulnerability Detector Module**

Edit the Wazuh configuration file to disable the Vulnerability Detector temporarily.

```bash
sudo nano /var/ossec/etc/ossec.conf
```

Locate the `<vulnerability-detector>` section and change the `<enabled>` parameter to `no`:

```xml
<vulnerability-detector>
    <enabled>no</enabled>
    <!-- Other configurations -->
</vulnerability-detector>
```

Save and exit the editor (`Ctrl+O`, `Enter`, `Ctrl+X`).


### **Step 3: Remove the Vulnerability Detector Inventory**

Delete the inventory directory to remove all cached vulnerability data.

```bash
sudo rm -rf /var/ossec/queue/vd/inventory/
```


### **Step 4: Remove the Indexer's Local Queue and Database**

Clear the Indexer's local queue and database to ensure no residual data remains.

```bash
sudo rm -rf /var/ossec/queue/indexer/
```

### **Step 5: Remove the Vulnerabilities Index from Elasticsearch/OpenSearch**

Delete the existing vulnerabilities index to remove stored vulnerability data.

  ```bash
  curl -X DELETE "http://<INDEXER_IP>/wazuh-states-vulnerabilities/*" -u <INDEXER_USER> -k <INDEXER_PASSWORD>
  ```

> **Note:** Replace `<INDEXER_IP>` with your Indexer IP address, in most of cases is `127.0.0.1`,  `<INDEXER_USER>` with the indexer user, in most of cases is `admin` and `<INDEXER_PASSWORD>` with the indexer password.


### **Step 6: Start the Wazuh Manager**

Restart the Wazuh manager to apply the changes.

```bash
sudo systemctl start wazuh-manager
```

At this point, all previous vulnerability data should be cleared.


### **Step 7: Re-enable the Vulnerability Detector Module**

Edit the configuration file again to re-enable the Vulnerability Detector.

```bash
sudo nano /var/ossec/etc/ossec.conf
```

Set the `<enabled>` parameter back to `yes`:

```xml
<vulnerability-detector>
    <enabled>yes</enabled>
    <!-- Other configurations -->
</vulnerability-detector>
```

Save and exit the editor.


### **Step 8: Restart the Wazuh Manager**

Restart the manager to initiate a fresh vulnerability scan.

```bash
sudo systemctl restart wazuh-manager
```


### **Step 9: Verify the Vulnerability Scan**

Monitor the logs to ensure that agents are being rescanned and new indices are being created.

```bash
sudo tail -f /var/ossec/logs/ossec.log
```

Look for entries indicating that the Vulnerability Detector is scanning agents and that new data is being indexed.

**Comment by lexzz** [comment]
Thank you, this was very useful. We had the same issue.

**Comment by mmccarn** [comment]
Step 5 gives me:

> {"error":"no handler found for uri [/wazuh-states-vulnerabilities/*]  and method [DELETE]"}

If I replace `/*` on the end with `-*`:

    curl -X DELETE "https://<INDEXER_IP>:9200/wazuh-states-vulnerabilities-*" -u <INDEXER_USER>:<INDEXER_PASSWORD> -k

I get:

> {"acknowledged":true}
