### ISSUE TITLE
Vulnerability scanner: remove all CVEs related to a deleted agent from the indexer

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#25800]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.x - 4.9.x | Vulnerability scanner| Manager | Packages/Sources | Any OS |

## Description

The Wazuh cluster consists of many nodes, and an agent that moves from one to another is a normal situation.
Only the node that the agent is currently connected to should receive and process the inventory events and keep the indexer synced, but each node has a DB in a different state (because they aren't synced among the nodes).

When an agent is removed, an event is generated and forwarded to the vulnerability scanner. The module then looks for all the CVEs in its inventory DB and requests their removal from the indexer. However, this represents a desynchronization risk because there could be an indexed vulnerability that isn't present in the local inventory, leaving a dangling entry.
Example sequence:

- We have a cluster with a master, a worker and an agent.
- The agent connects to the master, all the vulnerabilities are detected and indexed.
- At this point, the local master's DB contains the agent vulnerabilities and the worker one is empty
- The agent gets disconnected, and during that time, some vulnerable packages are removed/upgraded. 
- Then, the agent connects again but this time to the worker.
- The worker scans all the packages and doesn't find any new vulnerability to index. The diff mechanism isn't triggered yet because of the abuse control.
- At this point, the user sees dangling entries in the vulnerabilities index, because the packages are no longer installed but the entries weren't removed
- The agent is then removed. This event is processed by all the nodes and forwarded to the vulnerability scanners.
- Suppose that the master node, the one that contains the local entries of the dangling CVEs fails to process the event for some undetermined cause, then the worker only removes the vulnerabilities that it contains in its local DB, leaving dangling entries

## DoD

To fix the problem, it's proposed that when a `deleteAgent` action arrives in the module, a [Delete by query
](https://opensearch.org/docs/latest/api-reference/document-apis/delete-by-query/) is executed.
This will remove **all** the entries related to the agent and not only those stored in the local node DB.
This will ensure the consistency of the information shown by the Wazuh indexer.

- [x] Update the module to perform the requested delete
- [x] Manually confirm all entries and not only the local ones are removed
- [x] Add UT
- [x] Component test
- [x] CI Pass

>[!note]
>I confirmed manually that when an agent is removed, all the nodes process the event by the expected Wazuh-DB command
```
2024/09/19 22:01:56 wazuh-db[57618] wdb_parser.c:859 at wdb_parse(): DEBUG: Global query: delete-agent 1
```

**Comment by sebasfalcone** [comment]
## Re estimated ETA
Given that this issue is estimated for 5.0.0 and Matias won't be available for a week, I've re-estimated the ETA

**Comment by GabrielEValenzuela** [comment]
# Update

I've done some more research and am gathering additional information on this issue. The desynchronization problem primarily affects the **inventory data** stored in local RocksDB databases on each node. Discrepancies arise when agents connect to different nodes at different times because:

- Each node maintains its own local RocksDB instance.
- Vulnerabilities detected on one node may not be present in another node's database.
- Agent disconnections and reconnections to different nodes can lead to outdated or dangling entries in OpenSearch.

Currently, the system does not fully implement an **ACID** (Atomicity, Consistency, Isolation, Durability) approach across the distributed environment:

- **Atomicity**: RocksDB provides atomic operations at the local level but not across multiple instances.
- **Consistency**: There's no guarantee of consistency between different RocksDB instances without synchronization.
- **Isolation**: Local isolation exists, but concurrent operations across nodes may conflict.
- **Durability**: RocksDB ensures durability locally, but data may be lost if not synchronized before a node failure.

We could develop application-level synchronization between RocksDB instances using a message broker to propagate changes. However, this approach is complex to implement and maintain, and it may introduce performance bottlenecks.

Alternatively, we could schedule jobs to reconcile and synchronize data between RocksDB instances. This method is easier to implement than real-time synchronization, but data inconsistencies may exist between reconciliation periods.

RocksDB is used in building large-scale distributed systems for various requirements. Such systems divide data into shards distributed across multiple server nodes. Additionally, a single host may run multiple instances of RocksDB, requiring resource management at both global (per host) and local (per instance) levels.

Managed resources include:

- **Memory**: Write buffer, block cache
- **I/O Bandwidth**: Compaction
- **Threads**: Compaction (preferably using thread pools)
- **Disk Usage**
- **File Deletion Frequency**

We strive to meet the following requirements:

- Ensure that no instance overuses any resource.
- Set resource usage priorities among different instances.

Regarding OpenSearch, we could use the `delete by query` operation, but I think this only solves part of the problem. Additionally, we have an issue where version conflicts can occur if documents are updated during the delete operation, causing the deletion to fail. The delete operation could also take a significant amount of time due to the match condition.

**References**

- OpenSearch Delete by Query API: [OpenSearch Documentation](https://opensearch.org/docs/latest/api-reference/document-apis/delete-by-query/)
- "Evolution of Development Priorities in Key-value Stores Serving Large-scale Applications: The RocksDB Experience": [Paper](https://www.usenix.org/system/files/fast21-dong.pdf)

**Comment by GabrielEValenzuela** [comment]
# Update

We carry on today's meets with the indexer team and staff to increase the context information. We're trying to replicate the issue locally.

**Comment by GabrielEValenzuela** [comment]
# Update

### Test Setup

We created a test environment consisting of:
- **Master and Worker Nodes**: Installed using two virtual machines (VMs) with the latest stable release of Wazuh.
- **Docker Container**: Deployed an Ubuntu 20.04 container with a known vulnerable package, Firefox 75, to simulate and compare results during vulnerability detection and removal processes.

---

### Test Cases

**Test Case 1**  
- **Steps**:
  1. Connect to the master node.
  2. Detect vulnerabilities (Firefox 75).
  3. Stop the agent.
  4. Remove the vulnerable package (Firefox 75).
  5. Connect the agent to the worker node.
- **Result**: Pass. No inconsistencies found

**Test Case 2**  
- **Steps**:
  1. Connect to the worker node.
  2. Detect vulnerabilities (Firefox 75).
  3. Stop the agent.
  4. Remove the vulnerable package (Firefox 75).
  5. Connect the agent to the master node.
- **Result**: Pass. No inconsistencies found

**Test Case 3**  
- **Steps**:
  1. Connect to the master node.
  2. Stop the agent.
  3. Remove the vulnerable package (Firefox 75).
  4. Remove the agent entirely.
  5. Connect the agent to the worker node.
- **Result**: Pass. No inconsistencies found

---

### Findings

1. **Indexer Sync Issues**:  
   When we shut down the worker node’s indexer, the system behaved as expected, and the indexer’s state was properly managed upon recovery.

   However, shutting down the master node’s indexer resulted in a critical issue: the indexer failed to recover, rendering it broken. This unexpected behavior requires further investigation, as it poses a potential risk for cluster stability and data synchronization.

2. **Vulnerability State Desynchronization**:  
   The synchronization of keys between managers occurs every 10 seconds, which is the expected behavior. Despite this, we observed discrepancies in the state of vulnerabilities between the local RocksDB storage on each manager node. The local inventories of each node were out of sync, which could lead to desynchronization in the vulnerability data managed by the indexer.

---

### Next Steps

We suspect that the desynchronization issue could be related to a concurrency problem, although we have not yet been able to reproduce the problem consistently. Further testing and investigation are necessary to confirm this hypothesis.

- We need to schedule a meeting with the indexer team to discuss the issue in more detail.
- After the meeting, we plan to continue the research and potentially conduct a deeper analysis of concurrency issues and recovery behavior.

---

**Comment by GabrielEValenzuela** [comment]
# Updated Report

### Test Setup

We established a test environment composed of the following elements:

- **Master and Worker Nodes**: Two virtual machines (VMs) running the latest stable release of Wazuh were used to configure the master and worker nodes.
- **Docker Container**: An Ubuntu 20.04 container was deployed with Firefox 75 (a known vulnerable package) to simulate and evaluate vulnerability detection and remediation processes.

---

### Test Case

The test case was performed using an All-In-One (AIO) `4.9.x` release of Wazuh and followed these steps:

1. **Install the AIO environment**.
2. **Wait for the feed update**.
3. **Connect the agent to the manager** and wait until the vulnerability scan is complete.
4. **Stop the agent** after the scan finishes.
5. **Force a re-scan** by running the following command:

    ```console
    root@uadmin:/var/ossec# ./router_test_tool -m publisher -t vulnerability_feed_manager
    Press 'q' to exit.
    {"type": "offsets","offset": 851036,"paths":["/var/ossec/create.json","/var/ossec/update.json"],"stageStatus":[{"stage": "download","status": "ok"}]}
    ```

6. **Remove the agent from the manager**:

    ```console
    root@uadmin:/var/ossec# /var/ossec/bin/manage_agents

    ****************************************
    * Wazuh v4.9.0 Agent Manager.          *
    * The following options are available: *
    ****************************************
       (A)dd an agent (A).
       (E)xtract key for an agent (E).
       (L)ist already added agents (L).
       (R)emove an agent (R).
       (Q)uit.
    Choose your action: A, E, L, R, or Q: R

    Available agents:
       ID: xxx, Name: agent_vd_test, IP: any
    Provide the ID of the agent to be removed (or '\q' to quit): xxx
    Confirm deletion? (y/n): y
    Agent 'xxx' removed.
    ```

---

### Observations and Results

We conducted the test twice, observing the following outcomes:

- **First Test**: With only the default vulnerabilities from the container (15 vulnerabilities), the inventory was properly cleaned up after the scan.
- **Second Test**: With 591 vulnerabilities most of them originating from `firefox=75.0+build3-0ubuntu1`, the inventory was left in an inconsistent state until the vulnerability feed was updated and a re-scan was triggered. After the re-scan, the inventory was successfully cleaned.

Below are screenshots from the Wazuh dashboard reflecting the state before and after the re-scan:

- **Before re-scan**: After the initial scan, prior to the re-scan.
  
  ![Dashboard: After scan and prior re-scan](https://github.com/user-attachments/assets/e005384c-ade3-403b-9271-b02c63c20b34)

- **After re-scan**: Post re-scan after the feed update.

  ![Dashboard: After re-scan from update](https://github.com/user-attachments/assets/5329ac4c-b914-47db-ab01-942b289e37ed)

---

### Root Cause Analysis

A detailed analysis of the logs revealed that the root cause of the inconsistent state appears to be linked to the reboot process after the agent deletion. The logs indicate missing messages post-deletion, suggesting that the reboot could be the reason behind the issue. This conclusion was reached after reviewing the findings with the development team (@wazuh/devel-cppserver-div1).

For further details, refer to the full log available [here](https://github.com/user-attachments/files/17284611/master.log.gz)

**Comment by GabrielEValenzuela** [comment]
# Update

PR with changes and tests made, done. Pending review.

**Comment by pereyra-m** [comment]
## Update

I perform the manual tests to verify the development

**Comment by sebasfalcone** [comment]
## ETA update
Some edge cases were discovered, we need to discuss this further with the team

**Comment by GabrielEValenzuela** [comment]
# Update

- Refactoring and bug fixing. Align the QA tests

**Comment by GabrielEValenzuela** [comment]
# Update

- Fix UTs and make changes based on the reviewer's request.
