### ISSUE TITLE
Can't Use “!” to negate it in EventChannel.EventData.IpAddress

### ISSUE THREAD

**Issue by jjf012** [wazuh/wazuh#2581]
After wazuh is upgraded to version 3.8, `EventChannel.EventData.IpAddress` cannot use "!" to negate it like `srcip`.
my rule: 
```
<group name="windows,">
  <rule id="120001" level="12">
  <if_group>authentication_success</if_group>
  <field name="EventChannel.EventData.IpAddress">!127.0.0.1</field>
  <description>windows: login from unknow host</description>
  </rule>
</group>
```

**Comment by DanielMorLoz** [comment]
Hi jjf012,
This option isn't available nowadays.
Nevertheless, I'll give you a solution to use to match a rule with every IP address except one.
You could define 2 rules, one acting as father and the other one as child. Let's look an example:

     <group name="windows,">

      <rule id="120001" level="12">
       <if_group>authentication_success</if_group>
       <description>windows: login from unknow host</description>
      </rule>

      <rule id="120002" level="0">
        <if_sid>120001</if_sid>
        <field name="EventChannel.EventData.IpAddress">127.0.0.1</field>
        <description>windows: login from know host</description>
      </rule>

      </group>

Where you can see how the rule 120002 will only trigger with the IP we've selected. This rule won't be visible inside Kibana because of his level, rules need at least level 3 to get visibility because alerts below this level aren't sent to alerts.log/json file. (by default)

**Comment by jjf012** [comment]
@DanielMorLoz Thank you, this method is great.
