### ISSUE TITLE
Duplicated AWS Cloudtrail logs (3.8.0)

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#2585]
Hello team,

The AWS Woodle is duplicating logs in version 3.8.0 of Wazuh. The Woodle isn't ignoring the logs he's already read.

Regards,

Miguel Casares

**Comment by ntheo166** [comment]
Can confirm this is also an issue on v3.8.2

**Comment by druizz90** [comment]
Hi team,

I tried to reply this error. It is possible getting duplicate events if `AWS` wodle is interrupted unexpectedly.

Our wodle does not make commits in the database when a log file is processed (commits are made when 1000 logs are processed or region is changed).

If wodle execution is interrupted, some logs will be processed again in the next execution (this logs did not marked as processed because commit in database was not possible).

Best regards,

Demetrio.

**Comment by UranusBytes** [comment]
FWIW - Pull Request #2476 - Dynamically scale the db_retain_records - would resolve this...

**Comment by druizz90** [comment]
Hi @UranusBytes,

We are storing the name of 1000 log files per region in the database, and the limit for getting logs with function `list_objects_v2` is 1000. Furthermore, the function [ `db_maintenance`](https://github.com/wazuh/wazuh/blob/8cd6bfaa0c7b94e517630a96f59228546dde2515/wodles/aws/aws-s3.py#L452) is called when 1000 log files are processed.

I think is not necessary to scale dynamically the size of `db_retain_records` if this value is equal or less than the maximum of the keys that `list_objects_v2` could obtain. You can see that the maxium of keys that we can retrieve is 1000 in the line [523]( https://github.com/wazuh/wazuh/blob/8cd6bfaa0c7b94e517630a96f59228546dde2515/wodles/aws/aws-s3.py#L523) of the wodle.

Did you get duplicate alerts by the same event? I only got duplicate alerts when I stop the wodle when it is still processing logs and the processed logs were not commited in the database.

Best regards,

Demetrio.

**Comment by UranusBytes** [comment]
Hi @druizz90 ,

You are correct that `list_objects_v2` can only return 1000 objects per execution, but the `IsTruncated` value in the results indicate if there are additional objects that could be returned using the filter arguments in the execution.  Line 636 (https://github.com/wazuh/wazuh/blob/8cd6bfaa0c7b94e517630a96f59228546dde2515/wodles/aws/aws-s3.py#L636) is for the first execution, but line 668 (https://github.com/wazuh/wazuh/blob/8cd6bfaa0c7b94e517630a96f59228546dde2515/wodles/aws/aws-s3.py#L667-L669) is where `list_objects_v2` is iterated over for each additional batch of 1000 objects to process.

 With the current logic, if the key of the `list_objects_v2` has more than 1000 objects (and I have buckets that have 3-4k objects), then the DB will only keep the names of the last 1k objects processed, and at next execution of the wodle it will reprocess all the objects before the last 1k.

Currently, with the default value of 1000 for `db_retain_records`, set on line 391
https://github.com/wazuh/wazuh/blob/8cd6bfaa0c7b94e517630a96f59228546dde2515/wodles/aws/aws-s3.py#L391
I start getting duplicate events by mid-day, so I change the value to 5000.  However, on last upgrade I forgot to change this value, and didn't notice the issue until a few hours later, after which the wodle had been endlessly reprocessing the same cloudtrail logs over and over.

Thanks,

Jeremy

**Comment by druizz90** [comment]
Hi Jeremy,

I am testing the wodle with the variable `retain_db_records=5` and `MaxKeys=5` https://github.com/wazuh/wazuh/blob/8cd6bfaa0c7b94e517630a96f59228546dde2515/wodles/aws/aws-s3.py#L521-L525 and I have not got duplicated (or more) events.

I changed this lines https://github.com/wazuh/wazuh/blob/8cd6bfaa0c7b94e517630a96f59228546dde2515/wodles/aws/aws-s3.py#L528-L534

by:

```python
if not iterating and filter_marker:
        filter_args['StartAfter'] = filter_marker
        debug('+++ Marker: {0}'.format(filter_marker), 2)
else:
        filter_args['StartAfter'] = last_key
        debug('+++ Marker: {0}'.format(last_key), 2)
```
for using `StartAfter` parameter when there are more than `MaxKeys` events. When function `build_s3_filter_args` is called, `last_key` is assigned to `StartAfter`, so that files older than `last_key` are not processed.

Thoughts?
