### ISSUE TITLE
Race Condition at Indexer Connector's Monitoring Constructor

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#25884]
|Wazuh version|Component|Install type|CID|Source|
|---|---|---|---|---|
| 4.9.1-rc1 | Wazuh Indexer | Manager | 1599947 | https://github.com/wazuh/wazuh/issues/25878 |

We've reported a race condition at:

https://github.com/wazuh/wazuh/blob/eb675f76bec9faf550a5360da07e909251b6a786/src/shared_modules/indexer_connector/src/monitoring.hpp#L108-L114

> **missing_lock**: Accessing this->this without holding lock Monitoring.m_mutex. Elsewhere, Monitoring::Monitoring(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const &, unsigned int, SecureCommunication const &)::[lambda() (instance 1)].this is written to with Monitoring.m_mutex held 1 out of 1 times.

Please confirm this race condition, and fix that if necessary.

**Comment by sebasfalcone** [comment]
## Report analysis
The report states that we are accessing shared resources without acquiring the lock, specifically on these lines
https://github.com/wazuh/wazuh/blob/eb675f76bec9faf550a5360da07e909251b6a786/src/shared_modules/indexer_connector/src/monitoring.hpp#L102-L105

Because this is a member variable, which is then accessed in another thread:
https://github.com/wazuh/wazuh/blob/eb675f76bec9faf550a5360da07e909251b6a786/src/shared_modules/indexer_connector/src/monitoring.hpp#L122

The code analyzer is identifying this as a source of problems.

## Truthness analysis
This issue is a false positive. The `m_values` variable is initialized before dispatching the thread so there is no concurrency issue. It's more of a warning and could be a problem if we do something with the class members after dispatching the thread

A lock protects the only place we do this:
https://github.com/wazuh/wazuh/blob/eb675f76bec9faf550a5360da07e909251b6a786/src/shared_modules/indexer_connector/src/monitoring.hpp#L191-L196
