### ISSUE TITLE
Footprint - RSS, PSS, USS and VMS increase their values ​

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#25927]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.1-rc1 | Wazuh Agent | Agent | Packages | CentOS, Ubuntu |

## Description

During the tests of: [Release 4.9.1 - RC 1 - Footprint Metrics - ROOTCHECK (2.5d)](https://github.com/wazuh/wazuh/issues/25862), RSS, PSS, USS and VMS values ​​increase.

- 4.9.0 RC 2

PSS:
![image](https://github.com/user-attachments/assets/ded04d32-190a-49b3-807e-74e62425f643)

RSS:
![image](https://github.com/user-attachments/assets/630256ba-66a8-4999-b8f0-7b44b097c915)

USS:
![image](https://github.com/user-attachments/assets/cd1f1e69-7843-4bb3-9d82-87f199a66efa)

VMS:
![image](https://github.com/user-attachments/assets/65d7fe06-8948-43ad-b85e-3c82cf826f5f)

- 4.9.1 RC 1

PSS:
![image](https://github.com/user-attachments/assets/964b8863-e13a-461d-b5ee-f766ed866740)

RSS:
![image](https://github.com/user-attachments/assets/07fa052d-673d-474e-97a6-c350c8bfc221)

USS:
![image](https://github.com/user-attachments/assets/c7289a4f-a72b-4302-8ccd-ca6cd00a2dc6)

VMS:
![image](https://github.com/user-attachments/assets/39e5c4bd-3cf6-4e8e-a01a-9477fe0cf4fa)

The cause may need to be investigated.

**Comment by vikman90** [comment]
Let's summarize these results:

|Process|4.9.0 RC 2|4.9.1 RC 1||
|--|--:|--:|--|
|wazuh-agentd|8.05 MB|10.1 MB|⏫ 25 % | 
|wazuh-modulesd|9 MB|11.05 MB|⏫ 23 % |
|wazuh-syscheckd|8.7 MB|8.9 MB|🟰 2 %|

Now, let's perform the same comparison on FIM (same process, _wazuh-syscheckd_):

|Process|4.9.0 RC 2|4.9.1 RC 1||
|--|--:|--:|--|
|wazuh-agentd|8.4 MB|10.1 MB|⏫ 20 % | 
|wazuh-modulesd|6.8 MB|7.0 MB|🟰 3 % |
|wazuh-syscheckd|16.8 MB|14.8 MB|⏬ 12 %|  

## Conclusion

This test is especially related to Rootcheck. This component hasn't changed since many years ago. We see no noticeable change in the _wazuh-syscheckd_ process. The differences in the other processes may be circumstantial or related to other components (where we would see differences).

On the other hand, if we run the same test on FIM, the _wazuh-syscheckd_ process uses less memory. 

**These differences are tolerable, due to circumstances not controlled by demons.**
