### ISSUE TITLE
Footprint - Increase of wazuh-agentd in PSS, RSS, USS in CentOS agent

### ISSUE THREAD

**Issue by hossam1522** [wazuh/wazuh#25944]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.1-RC 1 | agentd | Agent | Packages/Sources | OS version |

While analyzing plots in https://github.com/wazuh/wazuh/issues/25865, it has been detected an increase of wazuh-agentd in PSS, RSS, and USS plots in CentOS agent compared to previous releases:

<details><summary>4.9.1-RC 1</summary>

![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.1/B5593-3600m/B5593_agent_centos/plots/monitor-agent-Test_stress_B5593_centos-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.1/B5593-3600m/B5593_agent_centos/plots/monitor-agent-Test_stress_B5593_centos-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.1/B5593-3600m/B5593_agent_centos/plots/monitor-agent-Test_stress_B5593_centos-pre-release_USS.png)

</details>

<details><summary>4.9.0-RC 2</summary>

![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5572-3600m/B5572_agent_centos/plots/monitor-agent-Test_stress_B5572_centos-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5572-3600m/B5572_agent_centos/plots/monitor-agent-Test_stress_B5572_centos-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5572-3600m/B5572_agent_centos/plots/monitor-agent-Test_stress_B5572_centos-pre-release_USS.png)

</details>

<details><summary>4.8.1-RC2</summary>

![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5395-3600m/B5395_agent_centos/plots/monitor-agent-Test_stress_B5395_centos-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5395-3600m/B5395_agent_centos/plots/monitor-agent-Test_stress_B5395_centos-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5395-3600m/B5395_agent_centos/plots/monitor-agent-Test_stress_B5395_centos-pre-release_USS.png)

</details>

Further investigation is required to determine the origin of the problem.

**Comment by vikman90** [comment]
Let's summarize the results (max RSS) in a table:

| Process | 4.8.1 RC 2 | |  4.9.0 RC 2 | | 4.9.1 RC 1 |
|--|--:|--|--:|--|--:|
| wazuh-agentd | 10.2 MB | ⏬ | 8.1 MB | ⏫ | 16 MB | 
| wazuh-logcollector | 17.6 MB | ⏫ | 20.4 MB | 🟰 | 20,4 MB |
| wazuh-modulesd | 23 MB | 🟰 | 23 MB | 🟰 | 23 MB |
| wazuh-syscheckd | 8 MB | 🟰 | 8 MB | 🟰 | 8 MB | 

The memory usage of the components under test (Logcollector and FIM) remain unchanged.

The memory usage of wazuh-agentd has gone up, but also down from 4.8.1 to 4.9.0. This, together with the comment at https://github.com/wazuh/wazuh/issues/25927#issuecomment-2373843513, leads us to conclude that this difference in memory usage may be due to memory fragmentation, as also mentioned in https://github.com/wazuh/wazuh/issues/25410#issuecomment-2311423035.
