### ISSUE TITLE
Significant decrease in logs from indexer in VD High Test

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh#25955]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.1-rc1 | Indexer | Manager/Agent | Packages/Sources | OS version |

# Description
During the analysis of: https://github.com/wazuh/wazuh/issues/25900, a significant decrease in the number of logs from both indexers were detected in the High test. Normally, previous logs had around 3000 lines, but in this test, it has only about 50 lines.

**Log from 4.9.1-rc1 High Test**:
[wazuh-cluster.log](https://github.com/user-attachments/files/17135020/wazuh-cluster.log)

**Log from 4.9.0-rc2 High Test**:
[wazuh-cluster.log](https://github.com/user-attachments/files/17135049/wazuh-cluster.log)

**Build from 4.9.1-rc1**:
https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/730/

**Artifact form 4.9.1-rc1**:
[artifacts.zip](https://github.com/user-attachments/files/17135107/artifacts.zip)

**Comment by AlexRuiz7** [comment]
Most of the logs from 4.9.0-rc2 are from a reported known issue:
- https://github.com/wazuh/wazuh-indexer/issues/329

On 4.9.1-rc1, this log appears as well but does not repeat as many times.

The reason behind is unknown, and we cannot investigate this further with the given information. Aside from that, looks like the wazuh-cluster.log for 4.9.1-rc1 is truncated. The logs are not consistent because we are comparing the logs from a worker node in 4.9.0-rc2 with the logs from a master node in 4.9.1-rc1. This would explain the difference in the amount of logs.

Unless there is a difference in the behavior of the indexer in terms of indexing capacity or dropped events, I don't think this represents a problem by itself.
