### ISSUE TITLE
Significant increase of wazuh-modulesd in Disk_Written

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh#25957]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.1-rc1 | Master | Manager/Agent | Packages/Sources | debian10 |

# Description
During the tests of: https://github.com/wazuh/wazuh/issues/25900, a significant increase of `wazuh-modulesd` in **Disk_Written** from **Master** has been detected. As can be seen, it reaches quite a high figure, whereas in previous versions it is usually not this high.

## 4.9.1-rc1
![Disk_Written](https://github.com/user-attachments/assets/354431cc-177e-4836-9ed5-62f43c806bfc)

## 4.9.0-rc2
![Disk_Written](https://github.com/user-attachments/assets/2e32aab8-e0d2-4987-9f34-398acda76e5f)

## Full output from 4.9.1-rc1
[full_output.txt](https://github.com/user-attachments/files/17150373/full_output.txt)

**Comment by GabrielEValenzuela** [comment]
Hi @joaquinsgi ! How are you?

Could you provide more context about which OS was running this test, what input was provided, and if you have detailed output metrics?

I did some research but I didn't find any significative change in the last test compared with this new one. 

Thanks in advance!

**Comment by joaquinsgi** [comment]
Hi! @GabrielEValenzuela
The OS is debian10, i will update the Description from the issue with this information.

**Comment by GabrielEValenzuela** [comment]
# Update

#### **1. Executive Summary**
Recent tests revealed a significant increase in `Disk_Written` metrics for the `wazuh-modulesd` component. This anomaly requires immediate investigation as it deviates substantially from historical data observed in previous software versions.

#### **2. Background**
A review of the differences between version tags **v4.9.0** and **v4.9.1** was conducted, alongside an analysis of performance metrics. Notably, the changelog for version 4.9.1 does not outline changes expected to impact the manager's performance directly. 
The only recorded log change pertains to an update in the database feed.

#### **3. Key Observations**
- **Changelog Analysis:**
  - The changelog does not highlight any modifications that would likely affect core functionalities.
  - Log entries lack debug information, limiting insight into the root cause of performance changes.

- **Code Review:**
  - A `git diff` analysis between **v4.9.0** and **v4.9.1** indicated numerous changes primarily related to the **http-request** interface.

#### **4. Conclusion**
Despite various updates in the codebase, there is no clear indication from the changelog or metrics that explain this anomaly.

**Comment by sebasfalcone** [comment]
## Conclusion
The increase in disk usage in the graphs can be attributed to an update in the feed. Offsets are being downloaded and dumped into the rocksDB database, and this is an expensive process

On the other hand, it's not possible to justify an increase in disk consumption with the changes introduced in **4.9.1**. This may be attributed to variations in the tests itself

> [!NOTE]
> The provided information won't be sufficient for further analysis. **modulesd** logs are not in debug

**Comment by Dwordcito** [comment]
LGTM.
