### ISSUE TITLE
Different vulnerabilities detected for the same OS but different architectures in macOS

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#25983]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.1-rc1 | Vulnerability Detection| Agent | Packages| macOS Sequoia |

## Description

During the final review of the [macOS E2E test](https://github.com/wazuh/wazuh/issues/25824), it has been seen in the Vulnerability Detection dashboard screenshots that the number of vulnerabilities detected is different, despite being the same operating system. No packages seem to have been installed or uninstalled in the process, so the only difference that can be seen at first glance is the architecture, with one agent being Intel and the other ARM.

**Screenshots**
- macOS Sequoia Intel:
![sequoiaintel](https://github.com/user-attachments/assets/e7514008-6368-4fdc-b435-1fd895c97635)

- macOS Sequoia ARM:
![sequoiaarm](https://github.com/user-attachments/assets/f373bc72-d695-4fd0-a64f-81ee8cfa8779)

We should investigate why these discrepancies in vulnerabilities appear.

**Comment by Dwordcito** [comment]
@juliamagan could you share the package and os information from this agent recollected with the API endpoints?

**Comment by sebasfalcone** [comment]
## Update
We obtained the following information:
- Package inventory
- OS information
- Vulnerability invetory

For 4.9.1 macOS agents using both **arm64** and **intel64** package architectures:
- [report.tar.gz](https://github.com/user-attachments/files/17194813/macOS.tar.gz)


Thanks @ncvicchi for the assistance

**Comment by sebasfalcone** [comment]
# Analysis
It's a known issue that **intel64** macOS agents aren't able to detect **pypi** or **npm** packages ([see analysis](https://github.com/wazuh/wazuh/issues/22896)), this should be taken into consideration when analysis discrepancies between vulnerability detections

## Sonoma
|   -   | ARM64 | Intel64 |
|-------|-------|---------|
| OS    |    63 |       0 |
| pkg   |    15 |      15 |
| pypi  |    8  |       0 |
| Total |    86 |      15 |

### Packages
|   -    | ARM64 | Intel64 |
|--------|-------|---------|
| pypi   |    14 |       0 |
| pkg    |   160 |     160 |
| Total  |   174 |     160 |

### Vulnerabilites

## Ventura

### Packages
|   -   | ARM64 | Intel64 |
|-------|-------|---------|
| pkg   |   149 |     149 |
| pypi  |    14 |       0 |
| Total |   163 |     149 |

### Vulnerabilites
|   -   | ARM64 | Intel64 |
|-------|-------|---------|
| OS    |   101 |     101 |
| pkg   |    14 |       0 |
| pypi  |     8 |       0 |
| Total |   123 |     101 |

**Comment by sebasfalcone** [comment]
# False positives
I've found that all pkg vulnerabilities detected (except for CVE-2024-44187) were false positives.

## Already fixed in VDP
- https://nvd.nist.gov/vuln/detail/CVE-2008-4216
  - Affected by default (fixed in VDP)
- https://nvd.nist.gov/vuln/detail/CVE-2008-3644
  - Affected by default (fixed in VDP)

## Investigation needed
### Affected by default
The following CVEs have no information of a version with a fix, given that these are old CVEs:
- https://nvd.nist.gov/vuln/detail/CVE-2010-2454
- https://nvd.nist.gov/vuln/detail/CVE-2010-1099
- https://nvd.nist.gov/vuln/detail/CVE-2010-0314
- https://nvd.nist.gov/vuln/detail/CVE-2008-3170
- https://nvd.nist.gov/vuln/detail/CVE-2007-2163
- https://nvd.nist.gov/vuln/detail/CVE-2008-5914
- https://nvd.nist.gov/vuln/detail/CVE-2008-3171
- https://nvd.nist.gov/vuln/detail/CVE-2008-7296
- https://nvd.nist.gov/vuln/detail/CVE-2008-0894
- https://nvd.nist.gov/vuln/detail/CVE-2007-2580

We will sanitize them.

### Poorly loaded running-on
The next CVEs are assumed to be running on vulnerabilities that weren't properly loaded by the NVD:
- https://nvd.nist.gov/vuln/detail/CVE-2008-3950
- https://nvd.nist.gov/vuln/detail/CVE-2009-3271

We will sanitize them.

**Comment by Tostti** [comment]
Hi @sebasfalcone, 
The wazuh agents were installed with approximately 15 minutes between each other. 
However, the test was done with 2 different laptops, both used for a long time by different people. They may have different programs installed too. 
I think that this issue would be valid if both systems were completely new, but that was not the case. I don't see any requirement for a new system for the agents in the E2E issue.

**Comment by sebasfalcone** [comment]
Thanks for the update @Tostti!

**Comment by Dwordcito** [comment]
LGTM based on https://github.com/wazuh/wazuh/issues/25983#issuecomment-2384324108
