### ISSUE TITLE
False Positives - Office 2021 LTSC

### ISSUE THREAD

**Issue by retroisbest** [wazuh/wazuh#25980]
<table role="table">
<thead>
<tr>
<th>Wazuh version</th>
<th>Component</th>
<th>Install type</th>
<th>Install method</th>
<th>Platform</th>
</tr>
</thead>
<tbody>
<tr>
<td>4.9.0</td>
<td>Vulnerability Detection</td>
<td>-</td>
<td>-</td>
<td>Ubuntu 22.04.5 LTS</td>
</tr>
</tbody>
</table>

We are seeing quite a few Office related CVEs and would like to investigate them further to check if they are a false positive.

The one CVE im going to investigate first is CVE-2023-33150

All of my clients are running the Wazuh agent version 4.9.0
Wazuh Manager is also 4.9.0

I have recently deployed Office 2021 LTSC Build number = 14332.20771 Version = 2108

The Microsoft article for this CVE shows there is an update for Office 2021 LTSC
https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-33150

The update notes for the Office 2021 LTSC
https://learn.microsoft.com/en-us/officeupdates/microsoft365-apps-security-updates

This is for the patch that was released on September the 10th which is the exact same version and build number of my deployed Office.

Is this a false positive?
Are there any steps I can take to resolve this logged CVE?

![image](https://github.com/user-attachments/assets/54b9ef17-6818-454d-a1b5-e1da400110b4)

I'm also seeing the following CVE's related to the above Office 2021 package

CVE-1999-0794 <- This one is being flagged even though its a very old CVE
CVE-2006-1311
CVE-2021-42293
CVE-2021-42295
CVE-2021-42296
CVE-2021-43255
CVE-2021-43256
CVE-2021-43875
CVE-2022-21840
CVE-2022-21841
CVE-2022-24461
CVE-2022-24462
CVE-2022-24473
CVE-2022-24509
CVE-2022-24510
CVE-2022-24511
CVE-2022-26901
CVE-2022-29107
CVE-2022-29109
CVE-2022-41060
CVE-2022-41061
CVE-2022-41063
CVE-2022-41103
CVE-2022-41104
CVE-2022-41105

.... and many more! (Shall i continue posting the CVE IDs?
The Package name is showing as "Microsoft Office LTSC Professional Plus 2021 - en-us"

and package.version = "16.0.14332.20771"

Thanks!

**Comment by Damian-Mangold** [comment]
Hi @retroisbest , in order to analyze the issue and perform some tests, could you please provide me with the following information from the agent where you're observing the issue?

- [OS information](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_os_info)
- [Package inventory](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_packages_info)
- Vulnerabilities inventory
- [Hotfix information](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_hotfix_info) (for Windows OS)


If you need help to obtain all the information, please consult [here](https://github.com/wazuh/wazuh/issues/25001#issuecomment-2275709492).

Thank you!

**Comment by Damian-Mangold** [comment]
Hi @retroisbest . Thank you very much for the information shared. Let me analyze it and I will get back to you as soon as I have news.

**Comment by Damian-Mangold** [comment]
I have carefully analyzed [CVE-2023-33150](https://nvd.nist.gov/vuln/detail/CVE-2023-33150), and all indications point to it being a false positive. According to Microsoft, the vulnerability is fixed with the July 11, 2023 patch (Build 14332.20529), which predates the version you are using. The false positive occurs because the NVD reports Office 2021 as vulnerable without specifying the build number `cpe:2.3:a:microsoft:office:2021:*:*:*:ltsc:*:x64:*`, making it impossible to determine whether the patch that resolves the vulnerability has been installed.

To address this issue, the NVD should include more detailed information, specifically the build number that fixes the vulnerability, so it can be properly identified.

Regarding [CVE-1999-0794](https://nvd.nist.gov/vuln/detail/CVE-1999-0794) and [CVE-2006-1311](https://nvd.nist.gov/vuln/detail/CVE-2006-1311), these also appear to be false positives. In this case, the NVD incorrectly states that all versions of Office are vulnerable `cpe:2.3:a:microsoft:office:*:*:*:*:*:*:*:*`, when that is not accurate. A more thorough analysis is needed to determine which versions are actually affected.

I will continue reviewing the remaining CVEs to see if the same logic applies and will subsequently inform the team so that the necessary sanitizations are made to prevent further false positives from being displayed.

**Comment by Damian-Mangold** [comment]
Hi @retroisbest. After conducting a thorough analysis of the reported false positives, we have identified an error in the translation mechanism that applies to certain products reported by NVD. We are currently working on correcting this issue, and we anticipate having a solution implemented within the next few days.

Thank you very much for your report. I will inform you as soon as the new content is published so that you can provide your valuable feedback.

Regards.

**Comment by Damian-Mangold** [comment]
Hi @retroisbest We have applied a change in the Microsoft Office translation, could you check if the false positives disappeared?

**Comment by retroisbest** [comment]
Hi @Damian-Mangold 
Thankyou for your hard work and time spent looking into this issue.

My dashboard overview still shows the CVE's but my events table shows no events

**Comment by Damian-Mangold** [comment]
Hi @retroisbest., thank you very much for your update. It’s unusual that you’re still seeing those vulnerabilities.

I have a quick question: Do you have Vulnerability Detector configured in offline mode?

---


If not, could you please enable debug level 2? You can do this by changing the `wazuh_modules.debug=2` setting in the `/var/ossec/etc/internal_options.conf` file.

After that, restart the manager with `systemctl restart wazuh-manager`, wait for about 30 minutes, and then share the entire `/var/ossec/logs/ossec.log` file with me.

**Comment by retroisbest** [comment]
[ossec.log](https://github.com/user-attachments/files/17261044/ossec.log)
@Damian-Mangold 

Please find a truncated ossec.log with debug 2 enabled

Thanks again

**Comment by Damian-Mangold** [comment]
Hi @retroisbest, Could you try to compress it and send it compressed ?

What do you see if you run the following search: `cat /var/ossec/logs/ossec.log | grep "Feed update process completed"`

**Comment by retroisbest** [comment]
> Hi @retroisbest, Could you try to compress it and send it compressed ?
> 
> What do you see if you run the following search: `cat /var/ossec/logs/ossec.log | grep "Feed update process completed"`

@Damian-Mangold 
Running the grep command for that string returns

**2024/10/04 18:50:27 wazuh-modulesd:vulnerability-scanner: INFO: Feed update process completed.**

Please find attached the compressed ossec.log

Thnakyou again
[ossec.zip](https://github.com/user-attachments/files/17263074/ossec.zip)

**Comment by retroisbest** [comment]
@Damian-Mangold 
After more diagnosing I can confirm that no CVEs are showing for my fully patched and updated clients running the latest version of Microsoft Office 2021 LTSC

**Comment by Damian-Mangold** [comment]
Hi @retroisbest. Alright, it seems that the translation has worked correctly, and you are no longer seeing false positives for Microsoft Office 2021 LTSC. Could you please confirm if this is the case?

**Comment by retroisbest** [comment]
Hi @Damian-Mangold 
I can confirm that I am no longer seeing any false positives that were affecting a fully patched Microsoft Office 2021 LTSC installation.

Thankyou 👍
