### ISSUE TITLE
Release 4.9.1 - RC 2 - Vulnerability Detection E2E tests

### ISSUE THREAD

**Issue by hossam1522** [wazuh/wazuh#26065]
## Tests information

|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release stage issue**     |            https://github.com/wazuh/wazuh/issues/25996                   |
| **Main Vulnerability Detection tests issue**     |           https://github.com/wazuh/wazuh/issues/26064                       |
| **Version**                          |                   4.9.1                         |
| **Release stage**              |                  RC 2                      |
| **Tag**                              |          https://github.com/wazuh/wazuh/tree/v4.9.1-rc2                               |
| **Previous E2E Vulnerability tests issue**      |       https://github.com/wazuh/wazuh/issues/25899                        |

### Description

The following issue aims to run all [Vulnerability Detector E2E](https://github.com/wazuh/wazuh-qa/issues/4369) tests for the current release candidate, report the results, and open new issues for any encountered errors.

### Instruction

Run the vulnerability detector tests using the [Test_e2e_system](https://ci.wazuh.info/job/Test_e2e_system/) pipeline

### Evidences

**Build**: https://ci.wazuh.info/job/Test_e2e_system/392/
**Report**:  [Test_e2e_system_392_test_vulnerability_detector.zip](https://github.com/user-attachments/files/17230245/Test_e2e_system_392_test_vulnerability_detector.zip)

### Known issues

- https://github.com/wazuh/vulnerability-detector-provider/issues/1467 
- https://github.com/wazuh/wazuh-qa/issues/5797

### Not Known issues
- https://github.com/wazuh/wazuh-qa/issues/5659
- https://github.com/wazuh/wazuh-qa/issues/5608
- https://github.com/wazuh/wazuh-qa/issues/5665

**Comment by pro-akim** [comment]
<details><summary>test_vulnerability_detector_scans_cases[upgrade_package_maintain_vulnerability]</summary>

Error:
```
>       assert test_result.get_test_result(), test_result.report()
E       AssertionError: 
E         Test test_vulnerability_detector_scans_cases[upgrade_package_maintain_vulnerability] failed
E         
E         Check no_errors succeeded
E         Check operation_successfull_for_all_agents succeeded
E         Check expected_vulnerabilities_found_in_index failed. Evidences (['missing_vulnerabilities']) can be found in the report.
E         Check no_unexpected_vulnerabilities_found_in_index succeeded
E         Check expected_vulnerability_affected_alert failed. Evidences (['missing_affected_alerts']) can be found in the report.
E         Check expected_vulnerability_mitigated_alert failed. Evidences (['missing_mitigated_alerts']) can be found in the report.
E         Check setup_operation_results failed. Evidences (['setup_failed_agents']) can be found in the report.
E         Check no_duplicated_vulnerabilities succeeded
E         -----
E         
E       assert False
E        +  where False = <bound method TestResult.get_test_result of <wazuh_testing.end_to_end.TestResult object at 0x7f7c1ce23070>>()
E        +    where <bound method TestResult.get_test_result of <wazuh_testing.end_to_end.TestResult object at 0x7f7c1ce23070>> = <wazuh_testing.end_to_end.TestResult object at 0x7f7c1ce23070>.get_test_result
```
In missing_vulnerabilities, missing_affected_alerts, missing_mitigated_alerts

```
{
    "agent2": [
        [
            "CVE-2022-0778",
            "Node.js",
            "17.1.0",
            "x86_64"
        ]
    ]
}
```

In setup_failed_agents
```
[
    "agent6",
    "agent2"
]
```

</details>







<details><summary>test_vulnerability_detector_scans_cases[upgrade_package_maintain_add_vulnerability]</summary>

Error:
```
>       assert test_result.get_test_result(), test_result.report()
E       AssertionError: 
E         Test test_vulnerability_detector_scans_cases[upgrade_package_maintain_add_vulnerability] failed
E         
E         Check no_errors succeeded
E         Check operation_successfull_for_all_agents succeeded
E         Check expected_vulnerabilities_found_in_index succeeded
E         Check no_unexpected_vulnerabilities_found_in_index succeeded
E         Check expected_vulnerability_affected_alert succeeded
E         Check expected_vulnerability_mitigated_alert failed. Evidences (['missing_mitigated_alerts']) can be found in the report.
E         Check setup_operation_results succeeded
E         Check no_duplicated_vulnerabilities succeeded
E         -----
E         
E       assert False
E        +  where False = <bound method TestResult.get_test_result of <wazuh_testing.end_to_end.TestResult object at 0x7f7c1d3f16a0>>()
E        +    where <bound method TestResult.get_test_result of <wazuh_testing.end_to_end.TestResult object at 0x7f7c1d3f16a0>> = <wazuh_testing.end_to_end.TestResult object at 0x7f7c1d3f16a0>.get_test_result
```



In missing_mitigated_alerts:
```
{
    "agent2": [
        [
            "CVE-2022-0778",
            "Node.js",
            "17.1.0",
            "x86_64"
        ]
    ]
}

```

</details>



<details><summary>test_vulnerability_detector_scans_cases[upgrade_package_add_vulnerability]</summary>

Error:
```
>       assert test_result.get_test_result(), test_result.report()
E       AssertionError: 
E         Test test_vulnerability_detector_scans_cases[upgrade_package_add_vulnerability] failed
E         
E         Check no_errors succeeded
E         Check operation_successfull_for_all_agents succeeded
E         Check expected_vulnerabilities_found_in_index failed. Evidences (['missing_vulnerabilities']) can be found in the report.
E         Check no_unexpected_vulnerabilities_found_in_index succeeded
E         Check expected_vulnerability_affected_alert failed. Evidences (['missing_affected_alerts']) can be found in the report.
E         Check expected_vulnerability_mitigated_alert failed. Evidences (['missing_mitigated_alerts']) can be found in the report.
E         Check setup_operation_results succeeded
E         Check no_duplicated_vulnerabilities succeeded
E         -----
E         
E       assert False
E        +  where False = <bound method TestResult.get_test_result of <wazuh_testing.end_to_end.TestResult object at 0x7f7bf56e52e0>>()
E        +    where <bound method TestResult.get_test_result of <wazuh_testing.end_to_end.TestResult object at 0x7f7bf56e52e0>> = <wazuh_testing.end_to_end.TestResult object at 0x7f7bf56e52e0>.get_test_result

```



In missing_vulnerabilities and missing_affected_alerts:
```
{
    "agent2": [
        [
            "CVE-2022-32223",
            "Node.js",
            "18.0.0",
            "x86_64"
        ]
    ]
}
```

In missing_mitigated_alerts
```
{
    "agent2": [
        [
            "CVE-2022-0778",
            "Node.js",
            "17.1.0",
            "x86_64"
        ]
    ]
}
```

</details>

**Comment by hossam1522** [comment]
LGTM!

**Comment by rauldpm** [comment]
# Review analysis

- test_vulnerability_detector_scans_cases[upgrade_package_maintain_vulnerability]
  - CVE-2022-0778 To be [fixed](https://github.com/wazuh/vulnerability-detector-provider/issues/1467) in v1.1.0 vulnerability detector provider
- test_vulnerability_detector_scans_cases[upgrade_package_maintain_add_vulnerability]
  - CVE-2022-32223 The linked issue does not seem to be related as the CVE is not mentioned, we should open an issue
- test_vulnerability_detector_scans_cases[upgrade_package_add_vulnerability]
  - CVE-2022-0778 To be [fixed](https://github.com/wazuh/vulnerability-detector-provider/issues/1467) in v1.1.0 vulnerability detector provider
  - CVE-2022-32223 The linked issue does not seem to be related as the CVE is not mentioned, we should open an issue
- test_vulnerability_detector_scans_cases[remove_package]
  - CVE-2022-0778 To be [fixed](https://github.com/wazuh/vulnerability-detector-provider/issues/1467) in v1.1.0 vulnerability detector provider
- test_vulnerability_detector_scans_cases[install_package]
  - CVE-2022-0778 To be [fixed](https://github.com/wazuh/vulnerability-detector-provider/issues/1467) in v1.1.0 vulnerability detector provider
- test_install_vulnerable_package_when_agent_down[install_package]
  - CVE-2022-0778 To be [fixed](https://github.com/wazuh/vulnerability-detector-provider/issues/1467) in v1.1.0 vulnerability detector provider
- test_change_agent_manager[install_package]
  - CVE-2022-0778 To be [fixed](https://github.com/wazuh/vulnerability-detector-provider/issues/1467) in v1.1.0 vulnerability detector provider

---

Based on the previous CVE analysis, we have 2 failed CVEs, one will be fixed in a future provider version and the other should be reported as we do not have a proper issue

  - CVE-2022-0778 To be [fixed](https://github.com/wazuh/vulnerability-detector-provider/issues/1467) in v1.1.0 
  - CVE-2022-32223 The linked issue does not seem to be related as the CVE is not mentioned, we should open an issue

**Comment by pro-akim** [comment]
New issue opened https://github.com/wazuh/wazuh-qa/issues/5797 in relation to CVE-2022-32223 failures
