### ISSUE TITLE
Review and fix cluster reliability tests

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#26100]
# Description

This issue continues the analysis at https://github.com/wazuh/wazuh/issues/25942 initially opened for `4.9.1`. Since the errors shown were not due to the misbehavior of the cluster but from a bug in the `test_cluster_sync.py` test, it was decided that the necessary changes should be made in the next opened release.

**Comment by RamosFe** [comment]
## Update

After the changes made in https://github.com/wazuh/wazuh/issues/25942#issuecomment-2383103353 and https://github.com/wazuh/wazuh-qa/pull/5782#issuecomment-2383504782, the bug was fixed and no more changes need to be implemented. 

I will rebase the PR and then pass this Issue's state to `pending review.`
