### ISSUE TITLE
False Positive in Vunlenrability Assessment

### ISSUE THREAD

**Issue by neilkamulkar** [wazuh/wazuh#26110]
Wazuh version 4.9  Vulnerability Assessment Quick Install Quick Install method Ubuntu 22.04
Have noticed lot of False Positive in the Vulnerability Assessment Module, sending you the Execel Report Attached with this Issue ...
[2nd October 2024.xlsx](https://github.com/user-attachments/files/17238626/2nd.October.2024.xlsx)

**Comment by neilkamulkar** [comment]
I have facing a same type of problem, I have a Linux Router of Ubuntu 22.04, I 
[firewall router dewas (1).xlsx](https://github.com/user-attachments/files/17243271/firewall.router.dewas.1.xlsx)
have done 
sudo apt update and sudo apt dist-upgrade 
before doing this, on the WAZUH Dashboard there were Vulnerabilities listed, but after the successful upgrade I can still view the Vulnerabilities

**Comment by Damian-Mangold** [comment]
Hi @neilkamulkar, I’ve reviewed the shared document and noticed it contains over 6000 lines, as well as data related to multiple agents/endpoints. The vulnerability detector selects the vulnerability feed that best matches the operating system it’s analyzing, which makes it crucial to have three key pieces of information together for each agent: the [package inventory](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_packages_info), the vulnerability inventory, and the [operating system details](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_os_info).

If you need help to obtain all the information, please consult [here](https://github.com/wazuh/wazuh/issues/25001#issuecomment-2275709492).

I understand that organizing and separating this content by agent might require additional effort on your part, but I need the information structured this way in order to perform a thorough and accurate analysis.

I appreciate your cooperation in this process.

**Comment by neilkamulkar** [comment]
Any updates ???

**Comment by Damian-Mangold** [comment]
Ho @neilkamulkar. I am working on it. I'm in the last part of the analysis.

**Comment by Damian-Mangold** [comment]
Hi @neilkamulkar, here is the vulnerability analysis. All of them were detected correctly:

|	package.name	|	package.version	|	vulnerability.id	|	Analysis	|	Reference	|
|	---	|	---	|	---	|	---	|	---	|
|	policykit-1	|	0.105-33	|	CVE-2016-2568	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2016-2568	|
|	zipp	|	1.0.0	|	CVE-2024-5569	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-jfmj-5v4g-7637	|
|	urllib3	|	1.26.5	|	CVE-2024-37891	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-34jh-p97f-mpxf	|
|	urllib3	|	1.26.5	|	CVE-2023-43804	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/PYSEC-2023-192	|
|	urllib3	|	1.26.5	|	CVE-2023-45803	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/PYSEC-2023-212	|
|	Twisted	|	22.1.0	|	CVE-2024-41810	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/PYSEC-2024-75	|
|	Twisted	|	22.1.0	|	CVE-2022-24801	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/PYSEC-2022-195	|
|	Twisted	|	22.1.0	|	CVE-2022-39348	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-vg46-2rrj-3647	|
|	Twisted	|	22.1.0	|	CVE-2024-41671	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-c8m8-j448-xjx7	|
|	Twisted	|	22.1.0	|	CVE-2022-21716	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/PYSEC-2022-160	|
|	Twisted	|	22.1.0	|	CVE-2023-46137	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/PYSEC-2023-224	|
|	systemd	|	249.11-0ubuntu3.12	|	CVE-2023-7008	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2023-7008	|
|	dmidecode	|	3.3-3ubuntu0.1	|	CVE-2023-30630	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2023-30630	|
|	coreutils	|	8.32-4.1ubuntu1.2	|	CVE-2016-2781	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2016-2781	|
|	requests	|	2.25.1	|	CVE-2024-35195	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-9wx4-h78v-vm56	|
|	requests	|	2.25.1	|	CVE-2023-32681	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-j8r2-6x86-q33q	|
|	Jinja2	|	3.0.3	|	CVE-2024-34064	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-h75v-3vvj-5mfj	|
|	Jinja2	|	3.0.3	|	CVE-2024-22195	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-h5c8-rqwp-cp95	|
|	patch	|	2.7.6-7build2	|	CVE-2021-45261	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2021-45261	|
|	patch	|	2.7.6-7build2	|	CVE-2018-6952	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2018-6952	|
|	idna	|	3.3	|	CVE-2024-3651	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-jjg7-2v4v-x38h	|
|	mdadm	|	4.2-0ubuntu2	|	CVE-2023-28938	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2023-28938	|
|	mdadm	|	4.2-0ubuntu2	|	CVE-2023-28736	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2023-28736	|
|	ntfs-3g	|	1:2021.8.22-3ubuntu1.2	|	CVE-2023-52890	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2023-52890	|
|	nano	|	6.2-1	|	CVE-2024-5742	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2024-5742	|
|	fwupd	|	1.7.9-1~22.04.3	|	CVE-2022-3287	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2022-3287	|
|	libgcrypt20	|	1.9.4-3ubuntu3	|	CVE-2024-2236	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2024-2236	|
|	PyJWT	|	2.3.0	|	CVE-2022-29217	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-ffqj-6fqr-9h24	|
|	configobj	|	5.0.6	|	CVE-2023-26112	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-c33w-24p9-8m24	|
|	cryptography	|	3.4.8	|	CVE-2023-50782	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-3ww4-gg4f-jr7f	|
|	cryptography	|	3.4.8	|	CVE-2023-49083	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-jfhm-5ghh-2f97	|
|	cryptography	|	3.4.8	|	CVE-2023-0286	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-x4qr-2fvf-3mr5	|
|	cryptography	|	3.4.8	|	CVE-2024-0727	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-9v9h-cgj8-h64p	|
|	cryptography	|	3.4.8	|	CVE-2023-23931	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-w7pp-m8wf-vj6r	|
|	setuptools	|	59.6.0	|	CVE-2024-6345	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-cx63-2mw6-8hw5	|
|	Babel	|	2.8.0	|	CVE-2021-42771	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-h4m5-qpfp-3mpv	|
|	binutils	|	2.38-4ubuntu2.6	|	CVE-2019-1010204	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2019-1010204	|
|	binutils	|	2.38-4ubuntu2.6	|	CVE-2022-48064	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2022-48064	|
|	binutils	|	2.38-4ubuntu2.6	|	CVE-2017-13716	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2017-13716	|
|	binutils	|	2.38-4ubuntu2.6	|	CVE-2022-27943	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2022-27943	|
|	binutils	|	2.38-4ubuntu2.6	|	CVE-2018-20657	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2018-20657	|
|	cpio	|	2.13+dfsg-7ubuntu0.1	|	CVE-2023-7216	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2023-7216	|
|	amd64-microcode	|	3.20191218.1ubuntu2.2	|	CVE-2023-31315	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2023-31315	|
|	amd64-microcode	|	3.20191218.1ubuntu2.2	|	CVE-2021-26318	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2021-26318	|
|	dbus	|	1.12.20-2ubuntu4.1	|	CVE-2023-34969	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2023-34969	|
|	oauthlib	|	3.2.0	|	CVE-2022-36087	|	Correctly detected. A vulnerable version is installed	|	https://osv.dev/vulnerability/GHSA-3pgj-pg6c-r5p7	|
|	git	|	1:2.34.1-1ubuntu1.11	|	CVE-2018-1000021	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2018-1000021	|
|	wget	|	1.21.2-2ubuntu1.1	|	CVE-2021-31879	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2021-31879	|
|	snapd	|	2.63+22.04ubuntu0.1	|	CVE-2024-5138	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2024-5138	|
|	apport	|	2.20.11-0ubuntu82.6	|	CVE-2022-28653	|	In the last few days Canonical changed its affected status to Ignored, in the next vulnerability content update this detection should be removed.	|	https://ubuntu.com/security/CVE-2022-28653	|
|	openssl	|	3.0.2-0ubuntu1.18	|	CVE-2024-41996	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2024-41996	|
|	python3-twisted	|	22.1.0-2ubuntu2.5	|	CVE-2024-41671	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2024-41671	|
|	linux-firmware	|	20220329.git681281e4-0ubuntu3.34	|	CVE-2020-12319	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2020-12319	|
|	linux-firmware	|	20220329.git681281e4-0ubuntu3.34	|	CVE-2020-12313	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2020-12313	|
|	linux-firmware	|	20220329.git681281e4-0ubuntu3.34	|	CVE-2023-4969	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2023-4969	|
|	linux-firmware	|	20220329.git681281e4-0ubuntu3.34	|	CVE-2020-12317	|	Correctly detected. A vulnerable version is installed	|	https://ubuntu.com/security/CVE-2020-12317	|

**Comment by Damian-Mangold** [comment]
I would like to take this opportunity to guide you through the process of verifying whether a vulnerability has been accurately detected. This process involves obtaining the information of the detected product and then consulting the appropriate feed for verification.

Let’s walk through an example using a PyPI product, specifically `CVE-2024-35195`. The first step is to gather the relevant product information. In this case, the detected product is "requests," and its details are as follows:

```json
{
  "scan": {
    "id": 0,
    "time": "2024-05-17T11:31:55+00:00"
  },
  "priority": " ",
  "section": " ",
  "size": 0,
  "description": " ",
  "vendor": " ",
  "name": "requests",
  "install_time": " ",
  "format": "pypi",
  "location": "/usr/lib/python3/dist-packages/requests-2.25.1.egg-info/PKG-INFO",
  "source": " ",
  "version": "2.25.1",
  "architecture": " ",
  "agent_id": "058"
}
```

As you can see, the "vendor" field does not contain any information in this case. However, the "format" field indicates that the product is from PyPI, so the corresponding feed to consult is the PyPI feed. To check the relevant vulnerability details, we can use the Open Source Vulnerability (OSV) database. Searching for the CVE-ID in question will help determine the affected versions.

For instance, you can look up CVE-2024-35195 on OSV using the following link:

[https://osv.dev/list?q=CVE-2024-35195&ecosystem=PyPI](https://osv.dev/list?q=CVE-2024-35195&ecosystem=PyPI)

After selecting the search result, you will be able to view the range of affected versions. Since the installed version in your case is "2.25.1," which falls within the affected version range, the product is vulnerable.

![image](https://github.com/user-attachments/assets/14e747b5-688d-4133-9f41-8c00af9ce46f)


---

Now, let’s consider another example using the Canonical feed, specifically with `CVE-2023-7008`, where the detected product is "systemd." Below is the package information:

```json
{
  "scan": {
    "id": 0,
    "time": "2024-05-17T11:31:59+00:00"
  },
  "priority": "important",
  "section": "admin",
  "size": 9501,
  "multiarch": "foreign",
  "description": "/dev/ and hotplug management daemon",
  "vendor": "Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>",
  "name": "udev",
  "install_time": " ",
  "format": "deb",
  "location": " ",
  "source": "systemd",
  "version": "249.11-0ubuntu3.12",
  "architecture": "amd64",
  "agent_id": "058"
}
```

In this case, we can clearly see that the vendor is listed as "Ubuntu," so the relevant feed to consult is the Ubuntu feed. To verify the vulnerability, you can visit the Ubuntu Security page and search for CVE-2023-7008 using the following link:

[https://ubuntu.com/security/CVE-2023-7008](https://ubuntu.com/security/CVE-2023-7008)

From this page, you will see that "systemd" is indeed vulnerable in Ubuntu 22.04 LTS (Jammy).

![image](https://github.com/user-attachments/assets/6baeffcd-ddcd-4b44-a6c8-ddf635dbe4ae)

**Comment by neilkamulkar** [comment]
My primary concern is that despite executing apt dist-upgrade on Ubuntu Server 22.04, and with no further patches available after the upgrade, vulnerabilities are still being detected. Could you clarify how these vulnerabilities are being found despite the system appearing fully up to date?

Additionally, what is the most effective method to address or remediate these vulnerabilities? While I understand from your earlier response that upgrading to Ubuntu 24.04 would resolve this issue, we cannot proceed with an OS version upgrade at this time. This is due to the possibility that our installed application may not function correctly on the new version, and we cannot take that risk without explicit authorization from the application vendor.

Your guidance on this matter would be greatly appreciated.

**Comment by Damian-Mangold** [comment]
Hi @neilkamulkar

> No further patches are available after the upgrade, but vulnerabilities are still being detected.

The reason for this is that, as you can see, these vulnerabilities have not yet been addressed by Canonical. For some reason, Canonical has either chosen to defer addressing the issue or has not yet released a patch. As a result, these vulnerabilities remain active.

> Could you clarify how these vulnerabilities are being found despite the system appearing fully up to date?

Although your system is fully updated, certain vulnerabilities may still be present because there is no available fix for them yet. You can verify this information using the links I previously provided, as they contain the vendor's official data. The vulnerability detector relies on the official vendor feeds, and if the vendor's feed indicates that a specific package is vulnerable, the detector will report it as such.

> Additionally, what is the most effective method to address or remediate these vulnerabilities?

For Ubuntu packages, there is unfortunately not much that can be done until Canonical releases a patched version. Once a fix is made available, it will be distributed through the OS update system.

As for vulnerabilities related to PyPI packages, you should check if there are newer versions of the affected packages. For example, in the case of the [zipp](https://pypi.org/project/zipp/) package, version 3.20.2 is available, which resolves the known vulnerability. However, it is important to ensure that updating the package does not break any dependencies or cause issues in the environment. You can update PyPI packages by using the following command:

`pip install --upgrade library-name`

**Comment by sebasfalcone** [comment]
Inactive thread, please re-open it if needed
