### ISSUE TITLE
Wazuh - Facing some issues [IndexerConnector, All shards failed, ConnectionError] 

### ISSUE THREAD

**Issue by rober1412** [wazuh/wazuh#26123]
Hello.

Im facing the following issues since the v4.8.2 Wazuh upgrade:

- indexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-******', retrying until the connection is successful.
- opensearch-dashboards[800]: {"type":"log","@timestamp":"2024-10-03T13:30:05Z","tags":["error","opensearch","data"],"pid":800,"message":"[search_phase_execution_exception]: all shards failed"}
- opensearch-dashboards[800]: {"type":"log","@timestamp":"2024-10-03T13:29:21Z","tags":["error","opensearch","data"],"pid":800,"message":"[ConnectionError]: connect ECONNREFUSED 127.0.0.1:9200"}

I have gone through many forums where this problem is discussed and I can't seem to solve it.
I have changed the <vulnerability-detector> block. In the <indexer> block I have put the correct certificates from /etc/filebeat/certs and the IP from the /etc/filebeat/filebeat.yml file. 
I have also saved the admin keys in the wazuh-keystore.
I have also created a retention policy for the indexes but it seems to be stuck as well.

Thanks !!

**Comment by rober1412** [comment]
The errors I am experiencing at the user level are as follows:

- Vulnerability Detection events are not updating. Detections with status “solved” keep appearing in the Dashboard.
- There are thousands of alerts that are false positives that I would like to filter out.
- The index retention policy seems to have deleted quite a few, but does not finish executing. It gets stuck.
- With a “GET _cluster/health” I see that the status is “yellow” and the number of unassigned shards is 66.

I have checked hundreds of forums without being able to fix it.

Thank you very much in advance.

**Comment by rbr-acs** [comment]
Hi @rober1412 

i fixed the issue with recreate the wazuh keystore

`/var/ossec/bin/wazuh-keystore -f indexer -k username -v admin
/var/ossec/bin/wazuh-keystore -f indexer -k password -v ##########`

`echo ########## | filebeat keystore add password --stdin --force`

`systemctl restart filebeat.service
systemctl restart wazuh-manager.service`

**Comment by rober1412** [comment]
Hello @rbr-acs !

The problem persists. I have to clarify that the main reason for opening the case is that the Vulnerability Detection events are not updated. Neither new ones appear nor the patched ones disappear.

If you know the parameters to check in this case, I would appreciate your collaboration.

Thanks for all !!

**Comment by matias-braida** [comment]
Hello rober1412,

The errors you shared seem to be a problem in the indexer.
Since Wazuh version 4.8, the vulnerability module only indexes its alerts and states if the indexer status is GREEN. If your indexer has a YELLOW or RED status, the manager's vulnerability module will not connect to it.
This is why you see the log error line "indexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-******', retrying until the connection is successful.".

Please check the indexer status with the following command:

This is the command you need to run to get the indexer health status:
curl -k -u <USER>:<PASSWORD> -X GET "https://<WAZUH_INDEXER_IP>:9200/_cluster/health?pretty"

If you have default passwords for admin, and you are running the command on the same host where the indexer is installed, then the command is the following:
curl -k -u admin:admin -X GET "https://localhost:9200/_cluster/health?pretty"

You should get an answer like this:
# curl -k -u admin:admin -X GET "https://localhost:9200/_cluster/health?pretty"
{
  "cluster_name" : "wazuh-cluster",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "discovered_master" : true,
  "discovered_cluster_manager" : true,
  "active_primary_shards" : 189,
  "active_shards" : 189,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}

Please share your results to check them.
Regards

**Comment by Tuxman2** [comment]
Hello,

I have the same problem. I updated wazuh 4.7.x to 4.9.0 and now I don't have access to the dashboard. The message error is ":"[search_phase_execution_exception]: all shards failed".

If you have an idea. 

Thanks.

Note: Here is the result for me:

{
  "cluster_name" : "wazuh-cluster",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "discovered_master" : true,
  "discovered_cluster_manager" : true,
  "active_primary_shards" : 1006,
  "active_shards" : 1006,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 4,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 99.60396039603961
}

**Comment by Tuxman2** [comment]
Hello,

in my case, the problem is solved. I don't how it happened but it is ok now.

Regards.

**Comment by rober1412** [comment]
curl -k -u admin:############# -X GET "https://localhost:9200/_cl
uster/health?pretty"
{
  "cluster_name" : "wazuh",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "discovered_master" : true,
  "discovered_cluster_manager" : true,
  "active_primary_shards" : 341,
  "active_shards" : 341,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 6,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 98.27089337175792
}

**Comment by matias-braida** [comment]
Hello again,

The yellow state in your Wazuh-indexer is because you have unassigned shards on it.
The first thing you need to know is why you have them. For that, you have to run the following command:
```
curl -k -u <USER>:<PASSWORD> -X GET "https://<WAZUH_INDEXER_IP>:9200/_cluster/allocation/explain?pretty&include_disk_info=true"
```

Please share your results.

As the issue is in the indexer, here are the documentation links of OpenSearch related to the commands to analyze its status:
https://opensearch.org/docs/latest/api-reference/cluster-api/cluster-health/
https://opensearch.org/docs/latest/api-reference/cluster-api/cluster-allocation/

Also, here is a link you could use as a guide to check different reasons for the yellow status. Take into account that this is not an official link:
https://opster.com/guides/opensearch/opensearch-basics/yellow-status/

**Comment by Damian-Mangold** [comment]
I closed it because it had been inactive for more than 7 days. Please reopen it if necessary.
