### ISSUE TITLE
False positive of ASP.NET Core

### ISSUE THREAD

**Issue by yuchen1931** [wazuh/wazuh#26134]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |
Wazuh Version: 4.9.0

I have a server installed asp.net core 3.1.32(runtime) 3.1.426(SDK)，but wazuh agent determine asp.net core version is 3.1.10 
Because the installation path has a folder named 3.1.10 
Path: C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref
![named](https://github.com/user-attachments/assets/bc71b661-f72b-4e4f-9c3e-54ec27c771dd)

Vulneralbilty Detection:
CVE-2021-1723
CVE-2021-34532
Please help check，thanks

P.S There are two other folders called 3.1.0, and the others are 3.1.32 and 3.1.426

**Comment by jftuduri** [comment]
Hi @yuchen1931 , in order to analyze the issue we will need some extra information from your part. Could you please provide the following information from the agent where you're observing the issue?

- [OS information](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_os_info)
- [Package inventory](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_packages_info)
- Vulnerabilities inventory
- [Hotfix information](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_hotfix_info) (for Windows OS)

Let me know if you need help retrieving this data.
Thanks!

**Comment by yuchen1931** [comment]
> Hi @yuchen1931 , in order to analyze the issue we will need some extra information from your part. Could you please provide the following information from the agent where you're observing the issue?
> 
> * [OS information](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_os_info)
> * [Package inventory](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_packages_info)
> * Vulnerabilities inventory
> * [Hotfix information](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_hotfix_info) (for Windows OS)
> 
> Let me know if you need help retrieving this data. Thanks!

Hi jftuduri,
OS information:  microsoft windows server 2022
Package inventory: v4.9.0
Vulnerabilities inventory: 
https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/958986_1728048154.zip
Hotfix information: 
KB2468871
KB2478063
KB2533523
KB2544514
KB2600211
KB2600217
KB5004330
KB5041160
KB5041948
KB5042881

**Comment by jftuduri** [comment]
Hi @yuchen1931!

Thank you for the information! I realize I should have been more specific in certain areas. 

Here's what we need:

- **Package Information from Syscollector**: We need the exact package data that the Vulnerability Detector uses to match CVEs to ASP.NET. This is the most important information that we need to analyze these false positives. To retrieve this information, follow these steps:
  - Go to `Server Management -> Dev Console`.
![devtools](https://github.com/user-attachments/assets/2a972de6-fbbe-474c-bf77-fe92b5502a6f)
  - Run the following command, replacing `<AGENT_ID>` with the actual agent ID:
`GET /syscollector/<AGENT_ID>/packages`

![packages](https://github.com/user-attachments/assets/f45ab464-54df-4427-98c0-39c53ff0f643)

Once the command is executed, click on Export as JSON (3) and share the resulting file.

---

- **OS Information from Syscollector**: Similarly, for the OS information, run this command:

GET /syscollector/<AGENT_ID>/os

---

- **Vulnerability Inventory for your Agent**:
  - Go to the Vulnerability Detection inventory, 
  - filter by your agent
  - then click Export Formatted to save the inventory to a file.
![inventory](https://github.com/user-attachments/assets/49a7650a-cc3a-4f58-b8d5-e2513c02e378)

Once you’ve gathered these files, please share them with us.

Thanks!

**Comment by yuchen1931** [comment]
[asp.zip](https://github.com/user-attachments/files/17285921/asp.zip)
Attached is a sever with the same situation, version is 3.1.29，thanks

**Comment by jftuduri** [comment]
Hello @yuchen1931!

After analyzing the provided information we have:

For the ASP.NET CVEs:

- CVE-2021-34532
- CVE-2021-1723

The affected range for these CVEs for Microsoft ASP.NET is from version `3.1 up to (including) 3.1.17`.

In your case, these CVEs are being flagged due to the detection of the package `Microsoft ASP.NET Core 3.1.10 Targeting Pack (x64)`. Below is the relevant data, as collected by Syscollector and used by the Vulnerability Detector:
```json
{
    "scan":
    {
        "id": 0,
        "time": "2024-10-04T03:27:34+00:00"
    },
    "version": "3.1.10.20520",
    "section": " ",
    "priority": " ",
    "source": " ",
    "vendor": "Microsoft Corporation",
    "architecture": "x86_64",
    "description": " ",
    "size": 0,
    "format": "win",
    "location": " ",
    "name": "Microsoft ASP.NET Core 3.1.10 Targeting Pack (x64)",
    "install_time": "2022-09-30T09:58:44+00:00",
    "agent_id": "020"
}
```

Since this package version falls within the affected range, it has been marked as vulnerable. 
However, this could be a false positive, as it seems the Vulnerability Detector might be confusing the `Targeting Pack` with a core component of ASP.NET Core. 
If this is the case, we can make some minor adjustments to the vulnerability content to resolve the issue.

I’m not too familiar with ASP.NET, could you confirm if this `Targeting Pack` was specifically installed (perhaps for developing .NET apps with version 3.1.10)? Or could it be a leftover from an older ASP.NET SDK installation?

On the other hand, the `Microsoft ASP.NET Core 3.1.29 Shared Framework (x64)` is correctly detected and does not trigger these vulnerabilities, as its version is beyond the affected range (3.1.17):
```json
{
"scan": {
  "id": 0,
  "time": "2024-10-04T03:27:37+00:00"
},
"version": "3.1.29.22418",
"section": " ",
"priority": " ",
"source": " ",
"vendor": "Microsoft Corporation",
"architecture": "x86_64",
"description": " ",
"size": 0,
"format": "win",
"location": " ",
"name": "Microsoft ASP.NET Core 3.1.29 Shared Framework (x64)",
"install_time": "2022-09-30T09:46:14+00:00",
"agent_id": "020"
}
```

--- 
As for CVE-2023-36046 related to `Microsoft Windows Server 2022 Standard 10.0.20348.2700`, this is a known false positive and will be addressed shortly: 
- https://github.com/wazuh/wazuh/issues/25629

**Comment by yuchen1931** [comment]
I confirm that Microsoft ASP.NET Core 3.1.29 Shared Framework is not specifically installed or leftover from an older ASP.NET SDK installation, it was downloaded and installed directly from Microsoft. Thanks

**Comment by jftuduri** [comment]
As you may know, the Vulnerability Scanner takes package information retrieved by Syscollector and has to apply a 'translation' to match it correctly to the corresponding CVEs information. 
In this case, the translation applied is incorrectly matching `Microsoft ASP.NET Core 3.1.10 Targeting Pack (x64)` as a main ASP.NET Core product.

I've created an internal issue to solve this false positive. This fix consists in adjusting the ASP.NET Core translation so that it does not match the `Targeting Pack`, but it keeps matching the `Shared Framework` package.
Once this issue is completed and the updated content published, your Wazuh Manager will update the content automatically and stop reporting these false positives.

Thank you for reporting this problem and helping us improve our content!

**Comment by Damian-Mangold** [comment]
We need to add the efficacy test.

**Comment by Damian-Mangold** [comment]
Added translation and efficacy test.
