### ISSUE TITLE
Wazuh SELinux context

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh#2615]
Hi team,

We have found Wazuh agent and manager doesn't have a specific SELinux context.

When the service is installed at **/etc/systemd/system/** the wazuh processes run with context _unconfined_service_t_

![imagen](https://user-images.githubusercontent.com/37381070/52871653-d1e07580-314a-11e9-92a6-9acfcd473699.png)

When it is installed at **/etc/init.d/** all the processes are executed with initrc_t context, which goes against the CIS Benchmarks (RHEL 7 - 12-27-2017 - 1.6.1.6)

![imagen](https://user-images.githubusercontent.com/37381070/52871099-95604a00-3149-11e9-9410-ac7ef0a08a99.png)

We will need to investigate how to solve this issue and consider if Wazuh requires it's own SELinux context that fits it's necessities

Best regards,
Miguel

**Comment by ParthasarathiPM** [comment]
Hi Team,

Any update on this issue or else any workaround to fix this **unconfined_service_t** issue.

**Comment by Nicogp** [comment]
Hi ParthasarathiPM,
Our team has this issue on the Roadmap and we will start working on it as soon as possible. We will update this thread with more information.

Sorry for the inconvenience. Kind regards.

**Comment by Nicogp** [comment]
_Update:_

The main cause of **Wazuh** running with different contexts is because processes inherit the context of the service that launched them. So, when Wazuh service is installed and launched by `systemd` it runs with `unconfined_service_t` context inherited from `systemd`, and when it is installed and launched by `init.d`(sysV) it runs with `initrc_t` context inherited from `initd`.

Both contexts (`unconfined_service_t` and `initrc_t`) have no restrictions so Wazuh can run without problems.

We have tested in both contexts and have not found any case where Wazuh is denied any action.
