### ISSUE TITLE
Different behaviour in plots from the Manager in Footprint Test

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh#26202]
| Version | Revision | Production/Development | Component | Install type | 
|:--:|:--:|:--:|:--:|:--:|
|  4.9.1  |  RC 3  |    |  Manager  | Download/Repository/Sources/Assistant |  

## Description
During the tests performed at https://github.com/wazuh/wazuh/issues/26176, the plots have very different behaviour in Disk, Disk_Read, Disk_Written. The instance will be up until the reason for this behavior is known.

### Current result

Plots from 4.9.1-rc3:
![image](https://github.com/user-attachments/assets/651d8b48-8137-46d3-878f-4b3cbb4574a3)
![image](https://github.com/user-attachments/assets/fba280a9-1808-45e4-8a49-24a0b926e9ed)
![image](https://github.com/user-attachments/assets/03de72ba-6f3d-4437-82c3-5b58818a9a9b)

### Expected result
Something similar to 4.9.0-rc2
![image](https://github.com/user-attachments/assets/4a455836-010c-430b-9013-7c145a03b519)
![image](https://github.com/user-attachments/assets/c461b47a-e509-475c-8c56-378386482f75)
![image](https://github.com/user-attachments/assets/b645c742-56ec-4ae7-a1a3-d7c6df106cfa)

### Attachments

- Build link: https://ci.wazuh.info/job/Test_stress/5638/

- Build parameters: https://ci.wazuh.info/job/Test_stress/5638/parameters/

- Logs: .txt, .log or .zip: 
[ossec_Test_stress_B5638_manager_2024-10-07.zip](https://github.com/user-attachments/files/17276977/ossec_Test_stress_B5638_manager_2024-10-07.zip)

- Plots: 
[B5638_manager_centos.zip](https://github.com/user-attachments/files/17276991/B5638_manager_centos.zip)

**Comment by pereyra-m** [comment]
## Analysis in progress

I am analyzing each type of plot.
The logs don't contain relevant information, only a `Initiating update feed process.` log just at the beginning that can explain the initial increase in disk activity.

- The disk image seems normal, because the graph slowly decays as time passes (there is an old issue related to this)
- The disk read is almost constant all over the test, we can't infer a failure from this result
- The disk written slowly increases until the end of the test because it's a cumulative metric. At the end of the test, it stops increasing
- The CPU activity is higher during the stress test and normalizes with the test
- The RSS values are higher during the stress test and normalizes with the test

So I wouldn't set `4.9.0-rc2` as an expected result
- The disk plot is erratic, this could be a data problem of the test
- The disk read has a peak in the middle of the test, which might be related to a content update
- The disk written behaves as described above

I'll discuss the results with the team, but they seem normal.

**Comment by pereyra-m** [comment]
## Conclusion

After discussing with @wazuh/devel-cppserver-div1 , we think that the current metrics are natural and expected according to the stress test.

The `4.9.0-rc2` shouldn't be considered as the expected results.

**Comment by Dwordcito** [comment]
It makes sense, the comparison is not valid. Closed.
