### ISSUE TITLE
High increase in Written_alerts in Footprint test

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh#26221]
| Version | Revision | Production/Development | Component | Install type | 
|:--:|:--:|:--:|:--:|:--:|
|  4.9.1  |  RC 3  |    |  Manager  | Download/Repository/Sources/Assistant |  

## Description

During the tests performed at https://github.com/wazuh/wazuh/issues/26167, in Syscollector test has been found a high increase from Written_alerts in Written_stats plot, it has not been seen in 4.9.1-rc2 and 4.9.0-rc2 plots, it is necessary to understand why it has increased from 3-9 alerts into 50 alerts.

### Current result

The plots from 4.9.1-rc3 are:
![image](https://github.com/user-attachments/assets/936d26ea-42ca-4d07-884f-70957ed64fc9)

### Expected result

It is expected to have a similar behavior like in 4.9.0-rc2
![4 9 0](https://github.com/user-attachments/assets/94ee169d-bede-421b-8f68-f8e025d24a92)

4.9.1-rc2 plot:
![image](https://github.com/user-attachments/assets/b8ea9518-5755-427d-909a-61e0182c1561)

### Attachments

- Build link: https://ci.wazuh.info/job/Test_stress/5637/

- Build parameters: https://ci.wazuh.info/job/Test_stress_tier/188/parameters/

- Artifacts and logs: 
[B5637_manager_centos.zip](https://github.com/user-attachments/files/17292117/B5637_manager_centos.zip)

**Comment by JcabreraC** [comment]
Hello @joaquinsgi ,

I have a few observations and questions regarding this issue:
- **Missing Alerts Directory:** I've noticed that there is no "alerts" directory available in the artifacts. Does this test refer to those alerts? If so, it won't be possible to proceed with an analysis without this data.
- **Clarification on Graphs:** Additionally, I observed that the graphs mention “Written_stats,” while the issue description refers to “Written_alerts.” Is this correct? What exactly is being measured in this test? Understanding this will help ensure that we are looking at the right data.

Thank you for your help with these points.

**Comment by rauldpm** [comment]
>    Missing Alerts Directory: I've noticed that there is no "alerts" directory available in the artifacts. Does this test refer to those alerts? If so, it won't be possible to proceed with an analysis without this data.

No, there is no alerts directory as we can't fetch them due to the alert files generated (too much size)
No, this test does not refer to those alerts, this plot refers to written stats, which include several stats, like alerts

>    Clarification on Graphs: Additionally, I observed that the graphs mention “Written_stats,” while the issue description refers to “Written_alerts.” Is this correct? What exactly is being measured in this test? Understanding this will help ensure that we are looking at the right data.

No, you can see in the plots the Written_alerts line, which is part of the Written_stats, as I said above

This data (Written_stats) is obtained from the `analysisd_events` CSV (wazuh-analysisd)

- https://github.com/wazuh/wazuh-jenkins/blob/89dc64cddaa6054293161839442443df4ce63314/quality/python-packages/jenkins_utils/jenkins_utils/monitor.py#L220
- https://github.com/wazuh/wazuh-jenkins/blob/89dc64cddaa6054293161839442443df4ce63314/quality/python-packages/jenkins_utils/jenkins_utils/monitor.py#L216


- Obtain analysisd data: https://github.com/wazuh/wazuh-jenkins/blob/89dc64cddaa6054293161839442443df4ce63314/quality/python-packages/jenkins_utils/jenkins_utils/monitor.py#L351C36-L354
- Get written events: https://github.com/wazuh/wazuh-jenkins/blob/89dc64cddaa6054293161839442443df4ce63314/quality/python-packages/jenkins_utils/jenkins_utils/monitor.py#L360
- Write to log: https://github.com/wazuh/wazuh-jenkins/blob/89dc64cddaa6054293161839442443df4ce63314/quality/python-packages/jenkins_utils/jenkins_utils/monitor.py#L414-L418

Data is obtained from https://github.com/wazuh/wazuh-jenkins/blob/89dc64cddaa6054293161839442443df4ce63314/quality/python-packages/jenkins_utils/jenkins_utils/monitor.py#L621C27-L626

The state files are defined here https://github.com/wazuh/wazuh-jenkins/blob/89dc64cddaa6054293161839442443df4ce63314/quality/python-packages/jenkins_utils/jenkins_utils/monitor.py#L587-L594

**Comment by JcabreraC** [comment]
Hi @joaquinsgi @rauldpm ,

As observed in the CSV data, the values correspond to the "Alerts written" field, which appears to represent a cumulative count of alerts that have been logged. This value increases consistently until it stabilizes at 55 in version 4.9.1-RC3, as shown in the provided graph.

Upon inspecting the machine, I noticed several rotated files within the alerts directory. For example, when running the following command:
```
# cat /var/ossec/logs/alerts/2024/Oct/ossec-alerts-04.json | wc -l
1131
```
I found that the oldest file contains a total of 1,131 alerts, while the remaining files are empty. However, reviewing the ossec.log file reveals the following log entries:
```yml
2024/10/04 18:29:20 wazuh-authd: INFO: Exiting...
2024/10/04 18:29:22 wazuh-modulesd:router: INFO: Loaded router module.
2024/10/04 18:29:22 wazuh-modulesd:content_manager: INFO: Loaded content_manager module.
2024/10/04 18:29:25 wazuh-csyslogd: INFO: Remote syslog server not configured. Clean exit.
2024/10/04 18:29:25 wazuh-dbd: INFO: Database not configured. Clean exit.
2024/10/04 18:29:25 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
2024/10/04 18:29:25 wazuh-agentlessd: INFO: Not configured. Exiting.
2024/10/04 18:29:25 wazuh-authd: INFO: Started (pid: 13212).
2024/10/04 18:29:25 wazuh-authd: INFO: Accepting connections on port 1515. No password required.
2024/10/04 18:29:25 wazuh-authd: INFO: Setting network timeout to 1.000000 sec.
2024/10/04 18:29:26 wazuh-db: INFO: Started (pid: 13229).
```
It indicates that a restart occurred around 18:30. The graph data collection starts at 18:30, showing the alerts generated at that time.

Upon further review, all the alerts recorded at this time are repetitions of the following three types:
```vbnet
** Alert 1728066635.1095968: - wazuh,agent_flooding,pci_dss_10.6.1,gdpr_IV_35.7.d,
2024 Oct 04 18:30:35 (EC2AMAZ-L273KKC) any->wazuh-agent
Rule: 202 (level 7) -> 'Agent event queue is 90% full.'
wazuh: Agent buffer: '90%'.
level: 90%

** Alert 1728066635.1096203: - wazuh,agent_flooding,
2024 Oct 04 18:30:35 (EC2AMAZ-L273KKC) any->wazuh-agent
Rule: 205 (level 3) -> 'Agent event queue is back to normal load.'
wazuh: Agent buffer: 'normal'.
level: normal

** Alert 1728066635.1096425: - wazuh,agent_flooding,pci_dss_10.6.1,gdpr_IV_35.7.d,
2024 Oct 04 18:30:35 (EC2AMAZ-L273KKC) any->wazuh-agent
Rule: 203 (level 9) -> 'Agent event queue is full. Events may be lost.'
wazuh: Agent buffer: 'full'.
level: full
```
These alerts indicate that the event queue is becoming saturated with incoming events (likely due to the volume of data being sent by syscollector), leading to potential data loss as the buffer fills up.

Conclusion: It is expected that at the start, a large number of these alerts will be captured due to the significant volume of events being sent. This is a normal behavior as the system processes the initial data load, and the number of alerts should stabilize as the volume of events decreases or the system adjusts to the incoming data flow.

**Conclusion:**
It is to be expected that a large number of these alerts will be captured initially due to the large volume of events being sent when the first syscollector scan is performed. This is normal behavior as the system processes the initial data load, stabilizes, and no more such alerts are generated.

**Comment by Dwordcito** [comment]
LGTM, time issue during the test initialization.
