### ISSUE TITLE
Footprint - High increase of `wazuh-modulesd` in PSS, RSS, USS plots in CentOS agent

### ISSUE THREAD

**Issue by hossam1522** [wazuh/wazuh#26226]
| Version | Revision | Production/Development | Component | Install type | 
|:--:|:--:|:--:|:--:|:--:|
|  4.9.1-RC 3  |  1  |  Development  |  wazuh-modulesd  | - |  

## Description

While analyzing plots in https://github.com/wazuh/wazuh/issues/26180, a high increase of `wazuh-modulesd` in PSS, RSS, and USS plots in the CentOS agent has been detected. Further investigation is required.

### Current result

<details><summary>4.9.1-RC 3</summary>

![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.1/B5647-3600m/B5647_agent_centos/plots/monitor-agent-Test_stress_B5647_centos-pre-release_PSS.png)

![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.1/B5647-3600m/B5647_agent_centos/plots/monitor-agent-Test_stress_B5647_centos-pre-release_RSS.png)

![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.1/B5647-3600m/B5647_agent_centos/plots/monitor-agent-Test_stress_B5647_centos-pre-release_USS.png)
</details>

### Expected result

<details><summary>4.9.0-RC 2</summary>

![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5580-3600m/B5580_agent_centos/plots/monitor-agent-Test_stress_B5580_centos-pre-release_PSS.png)

![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5580-3600m/B5580_agent_centos/plots/monitor-agent-Test_stress_B5580_centos-pre-release_RSS.png)

![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5580-3600m/B5580_agent_centos/plots/monitor-agent-Test_stress_B5580_centos-pre-release_USS.png)
</details>

<details><summary>4.8.1-RC 2</summary>

![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5402-3600m/B5402_agent_centos/plots/monitor-agent-Test_stress_B5402_centos-pre-release_PSS.png)

![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5402-3600m/B5402_agent_centos/plots/monitor-agent-Test_stress_B5402_centos-pre-release_RSS.png)

![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5402-3600m/B5402_agent_centos/plots/monitor-agent-Test_stress_B5402_centos-pre-release_USS.png)
</details>

### Attachments

- Build link: https://ci.wazuh.info/job/Test_stress/5647/

**Comment by vikman90** [comment]
## Analysis

|Version|Image|Starting RSS (MB)|Ending RSS (MB)
|---|---|--:|--:|
|4.8.1-RC2|![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5402-3600m/B5402_agent_centos/plots/monitor-agent-Test_stress_B5402_centos-pre-release_RSS.png)|28|22|
|4.9.0-RC2|![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5580-3600m/B5580_agent_centos/plots/monitor-agent-Test_stress_B5580_centos-pre-release_RSS.png)|24|22|
|4.9.1-RC1|![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.1/B5601-3600m/B5601_agent_centos/plots/monitor-agent-Test_stress_B5601_centos-pre-release_RSS.png)|24|17|
|4.9.1-RC2|![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.1/B5619-3600m/B5619_agent_centos/plots/monitor-agent-Test_stress_B5619_centos-pre-release_RSS.png)|40|33|
|4.9.1-RC3|![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.1/B5647-3600m/B5647_agent_centos/plots/monitor-agent-Test_stress_B5647_centos-pre-release_RSS.png)|38|32|

There is a notable RSS usage from RC 1 to RC 2.

### Changes from RC 1 to RC 2

```bash
git diff --name-only v4.9.1-rc1..v4.9.1-rc2 --
```

- .github/actions/ghcr-pull-and-push/retag_image.sh
- .github/workflows/packages-build-manager.yml
- .github/workflows/packages-upload-images.yml
- .github/workflows/packages-upload-manager-images.yml
- CHANGELOG.md
- api/api/spec/spec.yaml
- api/test/integration/test_manager_endpoints.tavern.yaml
- framework/wazuh/core/cluster/__init__.py
- packages/debs/SPECS/wazuh-agent/debian/changelog
- packages/debs/SPECS/wazuh-agent/debian/copyright
- packages/debs/SPECS/wazuh-manager/debian/changelog
- packages/debs/SPECS/wazuh-manager/debian/copyright
- packages/debs/arm64/manager/Dockerfile
- packages/generate_package.sh
- packages/rpms/SPECS/wazuh-agent.spec
- packages/rpms/SPECS/wazuh-manager.spec
- packages/rpms/arm64/manager/Dockerfile
- src/Doxyfile
- src/REVISION
- src/init/wazuh-client.sh
- src/init/wazuh-local.sh
- src/init/wazuh-server.sh
- src/shared_modules/indexer_connector/src/indexerConnector.cpp
- src/win32/wazuh-installer.nsi

## Conclusion

There are no changes related to wazuh-modulesd between RC 1 and RC 2 (where the change is noticeable). In RC 3, memory usage improves by 2 MB compared to RC 2.

Since the difference happens right at startup, it may be due to an uncontrolled reason (like the order of modules startup or the load of hosts). I see no reason to relate it to 4.9.1.
