### ISSUE TITLE
Bug in collecting AuditD logs

### ISSUE THREAD

**Issue by reza-n051** [wazuh/wazuh#26245]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.3 | Wazuh Agent | Agent | Packages | Debian |

Hello
In AuditD according to the documentation of https://man7.org/linux/man-pages/man5/auditd.conf.5.html, different records of an event are not logged consecutively and there may be a gap between them.
```
              event0_record0
              event1_record0
              event2_record0
              event1_record3
              event2_record1
              event1_record4
              event3_record0
```
Consider the following example:
```   
             event1_record1
              event1_record2
              event2_record1
              event2_record2
              event2_record3
              event2_record4
              event1_record3
              event1_record4
```
In this case wazuh collects the logs as follows:
```
alert1 : event1_record1 event1_record2
alert2 : event2_record1 event2_record2 event2_record3 event2_record4
alert3 : event1_record3 event1_record4
```
While we should have 2 alerts:
```
alert1 : event1_record1 event1_record2 event1_record3 event1_record4
alert2 : event2_record1 event2_record2 event2_record3 event2_record4
```
How can I collect alerts correctly?
For real simulation, a general rule can be applied as follows:
```
-a always,exit -F arch=b64 -S all -F key=key1
```
As can be seen in the image below, we have three alerts in wazuh, whose ID is equal to 2078479, while they should have been collected in one alert.

![image](https://github.com/user-attachments/assets/d9280988-d994-4fa2-9dd4-7af285a8c81e)

**Comment by vikman90** [comment]
Hi @reza-n051,

The key to this issue lies in the fact that, although Auditd events may be split across multiple logs, the Wazuh agent assumes that logs for the same event will arrive continuously. As a result, the agent accumulates logs with the same identifier (`msg=audit(...)`) until it reads one with a different ID.

This represents a lack of functionality in the agent (specifically in the `localfile` audit format).

## Workaround

The Wazuh Manager also has the capability to group logs, but it will generate an alert for each log it receives, even though each successive alert will be richer as more information accumulates. However, the Manager cannot determine when a log is the last one for a given event.

You can apply the following changes to the Auditd decoder (`/var/ossec/ruleset/decoders/0040-auditd_decoders.xml`):

1. Add `<accumulate />` to the main decoder:
   ```xml
   <decoder name="auditd">
     <prematch>^node=\S+ type=|^type=</prematch>
     <accumulate />
   </decoder>
   ```
2. Change the `audit.id` field to `id` (the Manager uses the `id` field to accumulate):
   ```xml
   <order>audit.type,id</order>
   ```

This can help with the issue, but it will introduce a new one: repeated alerts.

## Conclusion

We will review this functionality in the upcoming Logcollector 5.0 release. Thank you for your understanding.

Best regards.
