### ISSUE TITLE
Vulnerability Detection keeps finding the same CVE every minute - hundreds of events.

### ISSUE THREAD

**Issue by R00G3R** [wazuh/wazuh#26487]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.1-rev | Wazuh Vulnerability Detection | Manager | Packages | CentOS 7 |

Vulnerability Detection keeps reporting the same CVE for the same agent every minute, causing thousands of events within multiple agents.

example of one single agent and a single CVE:
![image](https://github.com/user-attachments/assets/7b77d956-a995-4855-87e5-54189a053d93)

55k events on last then 24h from this agent
![image](https://github.com/user-attachments/assets/8e2fe18d-da66-4788-9c14-22e2af88e18a)

For now, I have disabled the vulnerability scan. Is there something I can do to fix this?

**Comment by Dwordcito** [comment]
Hi @R00G3R this issue is fixed in 4.10.0 (#25800).

@sebasfalcone please provide a WA here.

**Comment by pereyra-m** [comment]
Hi @R00G3R 

This situation was fixed at:
- https://github.com/wazuh/wazuh/issues/26157

This happens because of two simultaneous conditions:
- If the agent's packages inventory isn't synced, the re-scan of the agent (by a content update for example) fails to complete, and this event is retried every minute. This is the cause of the loop.
- There is a key mismatch issue with the OS scan that reports the same vulnerabilities in each re-scan. This is solved in the mentioned issue.

We can solve the first condition with a workaround. Maybe this agent has an intermittent connection with the manager and the **syscollector** inventory can't finish the synchronization.
If you temporarily disable the packages scan in the agent `ossec.conf` file, the manager will reset the agent's `sync_info` table and will able to process the re-scan event

```
  <wodle name="syscollector">

...   
    <packages>no</packages>
...

 </wodle>
```

If after re-enabling the vulnerability detector module the constant reporting has stopped, you can enable the package scan again. 
Consider that a content update in the manager will force a re-scan of the agents soon, and the situation could repeat if the agents fail to sync their inventories. In that case, we can analyze the agent and manager logs to find the cause of the lack of synchronization.

Regards.

**Comment by sebasfalcone** [comment]
Inactive thread, please re-open it if needed
