### ISSUE TITLE
Inconsistent Vulnerability Severity Categorization in Wazuh

### ISSUE THREAD

**Issue by joseraeiro** [wazuh/wazuh#26642]
Hello Wazuh team,

I’ve noticed inconsistencies in how Wazuh version 4.9.1 categorizes vulnerabilities in terms of severity based on the CVSS base scores. Specifically, some vulnerabilities with identical CVSS base scores are assigned different severity levels. Additionally, I’ve observed instances where a base score of 10 is categorized as “High” severity, while a base score of 9.8 is categorized as “Critical.”

## Examples:

Vulnerabilities with the same base score categorized under different severities.
A base score of 10 categorized as “High” severity, while a base score of 9.8 is labeled “Critical.”

## (Screenshots attached for reference)

![2024-10-30 10_13_28-Wazuh](https://github.com/user-attachments/assets/01c14d7d-3ec9-4106-bb2a-4858dd44c8ea)
![2024-10-30 10_17_32-Remote Desktop Manager  Wazuh](https://github.com/user-attachments/assets/16dcaac4-f16f-4f24-97d1-e79c2f13a0bc)

## Potential Causes:

I understand that Wazuh might be consolidating data from multiple vulnerability sources, which could lead to variances in severity mapping. However, these discrepancies create challenges in vulnerability prioritization and could affect security operations.

## Feature Request:

Would it be possible to have an option to standardize severity categorizations based solely on base score thresholds or allow for custom severity mappings? Alternatively, is there any guidance on configuring custom rules for consistent severity handling?

Thank you for your attention to this matter!

**Comment by Damian-Mangold** [comment]
Hi @joseraeiro, Let me analyze the information shared and I will get back to you as soon as possible.

Could you please share me an image or export the complete inventory where I can see the metric version (3.1, 3.0, 2.0, etc.)?

**Comment by Damian-Mangold** [comment]
Hi @joseraeiro. The information for score and severity is taken directly from the vendor's feed. In Wazuh versions 4.8.x and 4.9.x, the default source is the information provided by the NVD. However, starting with Wazuh 4.10.x, the information provided by each vendor will be used based on the specific operating system being analyzed.

Regarding your observation that, in some cases, a score of 10 results in a "HIGH" severity while a score of 9.8 shows as "CRITICAL," this discrepancy is due to the severity criteria defined for CVSS v2.0 and CVSS v3.x. Below, I have provided a table where you can review how severity is assigned according to the CVSS version.

![image](https://github.com/user-attachments/assets/d53d6d6e-fbea-458c-8bc5-ed3c0393dc17)

Ref: [Vulnerability Metrics](https://nvd.nist.gov/vuln-metrics/cvss)

Therefore, the criticality depends on the CVSS standard being applied.

In some cases, more than one metric may be provided for a single CVE. In such instances, the most recent metric should always be used. After analyzing the information you shared, I identified that this is not occurring as expected, which likely indicates a bug in the implementation. However, this does not impact the previous explanation regarding criticality and severity assignment.

**Comment by Damian-Mangold** [comment]
Hi @wazuh/devel-cppserver-div1. After analyzing the provided information, I have identified a behavior that may be related to a potential bug in the selection of which CVSS information to use. Specifically, when examining [CVE-2022-26809](https://nvd.nist.gov/vuln/detail/CVE-2022-26809), it can be observed that it contains two metrics: one for CVSS v3.x and another for CVSS v2.0. 

According to the logic implemented in [this part of the code](https://github.com/wazuh/wazuh/blob/030da3527b7031348ae3f686aae663621d981c26/src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/updateCVEDescription.hpp#L97), it should always prioritize the most recent metric, in this case, CVSS v3.x. However, this is not what is occurring.

Upon further analysis, I have determined that the system currently only uses CVSS v3.x information when CVSS v2.0 information is unavailable. This suggests a potential error in metric prioritization, which prevents the selection of the most up-to-date version as intended.

**Comment by MiguelazoDS** [comment]
# Update 

Implementing the checks to solve this behavior, I found some cases where we can experience some inconsistencies too. 

For example, https://nvd.nist.gov/vuln/detail/CVE-2009-10002 has two different sources for CVSSV3.1, but the content currently does not have the source information. 

To be discussed with the team. 

Issue on hold

**Comment by MiguelazoDS** [comment]
# Update 

Taking a look at the analysis here https://github.com/wazuh/vulnerability-detector-provider/issues/1825. Waiting for definitions

**Comment by MiguelazoDS** [comment]
# Update

Added 3 UT cases to cover all the metrics formats we currently get from NVD. Waiting for definitions to implement the verifications and fix the unit tests. 

![image](https://github.com/user-attachments/assets/2ee50983-df51-4fc9-be48-b5b18b49f69a)

**Comment by sebasfalcone** [comment]
## Definitions
The CVSS vector will now contain the "source" information appended to it:
- `CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H nvd@nist.gov`
- `CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H audit@patchstack.com`

**Comment by MiguelazoDS** [comment]
# Update 

We're not going to address the issue for multiple metrics from different sources for the same version as explained here. https://github.com/wazuh/wazuh/issues/26642#issuecomment-2457918775

The implementation to prioritize the higher metric version is done and ready for review. The UT cases for the problematic mentioned above we'll be disabled and should be enabled once the fix is implemented.
