### ISSUE TITLE
New error messages in AIX Agent uninstallation

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#26817]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  v4.10.0-alpha3  |  1  | Development   | Agent AIX  | Packages | 

## Description

During the tests performed at https://github.com/wazuh/wazuh/issues/26798, the test AIX Remove has displayed the following message

```
# rpm -e wazuh-agent
cannot remove /var/ossec/logs - directory not empty
cannot remove /var/ossec/etc/shared - directory not empty
cannot remove /var/ossec/etc - directory not empty
cannot remove /var/ossec - directory not empty

```

https://github.com/wazuh/wazuh-packages/issues/607
There were similar messages in previous versions that were reported in this issue, but that message has changed.

### Environment

| Node | Vagrant/AWS | Image | CPU | RAM (GB) | Disk size (GB) | Packages/Repository/Sources branch |
|:--:|:--:|:--:|:--:|:--:|:--:|---|
| Wazuh AMI | AWS AMI | AmazonLinux | 4 | 8 | 100 | pre-release |
| Agent AIX | cloud.siteox.com VM | AIX | 2 | 4 | 50 | pre-release |

### Steps to reproduce

1. Deploy a Wazuh AMI
2. Request to DevOps a AIX machine in cloud.siteox.com
3. Install wazuh-agent v4.10.0-alpha3
4. Remove the installation by using 

### Current result

```
# rpm -e wazuh-agent
cannot remove /var/ossec/logs - directory not empty
cannot remove /var/ossec/etc/shared - directory not empty
cannot remove /var/ossec/etc - directory not empty
cannot remove /var/ossec - directory not empty
```

### Expected result

No error messages should be seen.

**Comment by vikman90** [comment]
### Comment

This issue is a known behavior related to the generation of the `rpmsave` files during the uninstallation process. 

The messages reported are not errors but informational messages. They occur because the directories are not fully removed when **certain configuration files or logs are preserved as `rpmsave`**. 

Although the same RPM `SPEC` file is used for both CentOS and AIX, these messages are only observed on AIX due to the **older version of the RPM engine** it uses. The CentOS RPM engine handles this situation differently, which explains why no such messages appear on CentOS.

This behavior is not exclusive to the new 4.10.0 version and has been present in previous versions as well. Therefore, **it is not considered a blocker** for this release.

**Comment by vikman90** [comment]
This issue is a known behavior related to the generation of the `rpmsave` files during the uninstallation process. 

The messages reported are not errors but informational messages. They occur because the directories are not fully removed when **certain configuration files or logs are preserved as `rpmsave`**. 

Although the same RPM `SPEC` file is used for both CentOS and AIX, these messages are only observed on AIX due to the **older version of the RPM engine** it uses. The CentOS RPM engine handles this situation differently, which explains why no such messages appear on CentOS.

This behavior is not exclusive to the new 4.10.0 version and has been present in previous versions as well. Therefore, **it is not considered a blocker** for this release.
