### ISSUE TITLE
Include the PyServer 5.0 development environment

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#26820]
## Description

This issue aims to include the docker environment that the team uses for development in the repository—something like the CppServer team had at https://github.com/wazuh/wazuh/tree/master/src/engine/tools.

The issue's main focus will be the development environment for version 5.0 and enhancements in the migrated 4.X environment.

## Plan

- [x] Define the enhancements to be carried out for 4.X.
- [x] Implement the enhancements.
- [x] Include the environment for 5.X

**Comment by GGP1** [comment]
## Update

I've been moving the development environment from `wazuh/wazuh-tools` to `wazuh/wazuh`, adding automatic certificates generation and making modifications to the images we use to make them more efficient.

**Comment by GGP1** [comment]
## Update

Moved to on hold to focus on https://github.com/wazuh/wazuh/issues/27048.

**Comment by GGP1** [comment]
## Update

Continue developing the environment for 5.0.0, could execute three nodes that connect and sync as well as executing the Engine and both APIs.

**Comment by GGP1** [comment]
## Update

I've been making modifications to the Engine image, reducing its size from 13GB to 2GB, modifying the indexer SSL configuration and including a 5.0.0 agent using packages.

**Comment by GGP1** [comment]
## Update

Moved the engine image to our folder since they won't be pushing it to production, created an image to compile the agent from sources, created a volume to avoid downloading the VD feed every time we start a node.

**Comment by GGP1** [comment]
## Update

I've been advancing on the following points

- Added the 4.x environment
- Made changes to the opensearch configuration to authenticate using server certificates instead of requiring generating ones for the clients
- Updated the opensearch image version and wazuh-indexer plugins
- Reduced the wazuh-server image from 2GB to 600MB by copying just wazuh directories to a new stage image

**Comment by GGP1** [comment]
## Update

- Changes to the entrypoint of the nodes to stop or restart when receiving docker stop/restart
- Tested the environment with all components
- Debugging race conditions when stopping daemons
- Changes to not include plugin files

**Comment by GGP1** [comment]
## Update

Tried modifying the server script to avoid killing the container when the server process is killed but the issue comes when starting the server again, if the output is not redirected to the same file, the container won't show any logs.

As such, I decided not to implement the change and keep it like it is now. Lastly, I rebased the branch to master to use the latest changes.

**Comment by GGP1** [comment]
## Update

Applied suggested changes.
