### ISSUE TITLE
Suggestion: Add an "acknowledge" functionality to make the vulnerabilities dashboard actually useful

### ISSUE THREAD

**Issue by Gulaschcowboy** [wazuh/wazuh#26874]
Currently, the vulnerability module reports thousands of unfixed CVEs, e.g. because of being unimportant, rated to high, declined by the vendor or the distro, whatever.

Filtering is not efficient enough, to handle literally 1000+ CVE/OS/host and so on combinations.

This clogs up the visibility of important, unpatched vulnerabilities, and unfortunately it renders the vulnerability dashboard almost completely useless as of Wazuh 4.9.2. / November 2024.

Please consider implementing an acknowledgement function, like infrastructure monitoring tools like e.g. Nagios, Checkmk, Icinga, etc. do since decades.

This would enable to selectively and efficiently acknowledge certain combinations of unimportant or risk-accepted CVEs transparently.

It should contain:
- Who acknowledged
- When
- For what reason
- an expiration possibility to re-enenble visibility after a certain time

It should be flexible and hence "apply-able" to:
- single CVEs
- CVE / Host combinations
- based on searches/search filters

This is how it is done in Checkmk for example:
![image](https://github.com/user-attachments/assets/f17beb93-92e9-4ff4-b37e-55ec84f5b0f9)

**Comment by SirStephanikus** [comment]
Hi Alex (we know each other)

You can easily filter out every CVE in the dashboard by just clicking on it, once done, with just another click you can save your filter for future use.

For are further customization, custom rules and lists can be created and (like in Checkmk that I know extremely well) a person can create his own dashboards to reflect those customizations in an extreme automated way, without almost no limitations.

Keep in mind, that CVE's should never ever just ACKed (people could and will drop the issues under the table <-- perfect German translation of a common German phrase ☺️).

Instead, every and each CVE must be evaluated within the responsible team and a justification for its treatment, agreed on, must be written down (See ISO/IEC 27001:2022 and for further help ISO/IEC 27005, also NIS-2). Adding these CVEs to a custom filter (which content and amount is measurable) is an easy task. I did many custom dashboards and filters with Elasticsearch (prior Wazuh) and did/still do with Wazuh and OpenSearch.

I can assure you, that (once understood) the Vulnerability-Dashboard of Wazuh is "_not useless_", but a powerful overview.

**Comment by SirStephanikus** [comment]
@Gulaschcowboy 

Have you tried to filter by the CVE base score or its severity instead of the CVE identification number???

I run some test systems here with thousands of vulnerable packages, absolute no issues. May I ask for a sample?

**Comment by Gulaschcowboy** [comment]
@SirStephanikus
we have been using your approach, but we see this as an area, which can and will make Wazuh more usable in realistic scenarios.
Thus, this is a suggestion to make Wazuh better. We are well aware of the power of filters, but see the limitations here as well.

**Comment by pereyra-m** [comment]
Hi

The team is working in a CVE exclusion list that seems related to this request
- https://github.com/wazuh/wazuh/issues/26819

**Comment by Gulaschcowboy** [comment]
Hi @pereyra-m,

thank you. Yes, related. But the use case is not necessarily mitigated by #26819

**Comment by Xyz00777** [comment]
i have the same opinion like @Gulaschcowboy , at the moment there are too many Vulnerability who are not even possible to handle because there could also not even be an workaround beside an fix to the vulnerability. These Vulnerability is than absolutely useless for security persons, because they can do absolutely nothing with it, beside of looking one time at it and than (if a feature like that would be there) acknowledge it. It would be really hopeful if when you acknowledge an vulnerability  and than a fix or even a workaround would come up, the system recognize these and would bring it up again because than the security personal/administrators are able to do something. And it would be nice if there would be a option than to acknowledge the CVE with an issue at all systems and not just one or also otherwise, acknowledge it for just one system and not for other systems, like workaround is not possible because its not allowed to make an change on a system for the next 4 month or something like that. these can be the case in high security and safetly areas...

**Comment by pereyra-m** [comment]
Hi everyone again.

I mentioned https://github.com/wazuh/wazuh/issues/26819 because right now, it is the nearest improvement we have in the road map. This would be a change in the scanner to ignore some CVEs. However, as you point out, it fixes only part of the problem.

Our work in the scanner is to fix the errors and provide all the necessary tools to the teams that create the translations and sanitizations of the content to make the scanner results more accurate every day. Once the data is indexed, the Dashboard team should design the best filter method. Maybe we can move the feature request to that repository.

Currently, all the development teams are working on v5.0.0, which brings many architectural changes to the product. But even in this new diagram, I don't see space for an "acknowledge" system. One of the main ideas is to index everything (agents inventory, etc.) and once in the Indexer, everything can be filtered and visualized better. We can "hide" some vulnerabilities with an improved user interface, but a whole module that records who acknowledged the CVE, when, etc. might not be in the roadmap.

We can keep working on this feature request and share your comments with the corresponding team.

Regards.

**Comment by Xyz00777** [comment]
hi first thanks for your response.
im not sure if the dashboard team is the right stake holder for these, but im not aware of your team struckture so you should know it better.
But based on my small knowledge about how these could work at the moment. i guess there is some kind of database in the backend where the CVEs and the corresponding informations are stored. in my opinion it should not be that hard to add an additional column which an acknowledge boolean who gets triggert from the frontend to be set to true (dont show, when not especially searched for it) because not updatebale or workaround abailable and an addition to the cve update script so if an cve is getting fixable (workaround or update) its getting set back to false.

And i think especially an major update like 5.0.0 would be the best time to bring these feature finaly and make the vulnerability part really usable. because at least on my system around 80+% of the cves are not fixable and therefor noise i dont want and cant do anything with it so more or less useless.

**Comment by Gulaschcowboy** [comment]
@pereyra-m Thanks for your explanaition.
But I can only support the conclusion of @Xyz00777.
We are flooded with non-fixable CVEs and also issues that that do not really apply. And I'm talking here about thousands and thousands in a small enviroment of just ~200 hosts.

**Comment by sebasfalcone** [comment]
Thanks to all for the suggestions and opinions, this is what drives the open-source community 💪🏽 

Implementing this feature won't be easy in the current architecture. As @Xyz00777 states, 5.0.0 may be the best time to implement this. We are investigating all edges of this problem that's why we are asking the dashboard team to help us out

---

> I guess there is some kind of database in the backend where the CVEs and the corresponding informations are stored.

This is correct, we have local tracking of which CVEs are indexed

**Comment by Gulaschcowboy** [comment]
@sebasfalcone may I ask why you set it to “closed as completed”? This is far away from being the case and a closed FR will most probably get lost and never show up on the roadmap.

**Comment by Dwordcito** [comment]
@Gulaschcowboy 
For now the solution for this will be exclusions, we have to take into consideration that what Wazuh offers is a vulnerability scanner, not a comprehensive vulnerability manager per host. This gives visibility to the vulnerabilities it has, allowing it to be excluded in the future both by CVE and by product. I assume that you have many kernels that are a large number. I suggest you track the exclusions issue https://github.com/wazuh/wazuh/issues/26819

**Comment by Gulaschcowboy** [comment]
Hi @Dwordcito
Two kernels per system as the Ubuntu standard is already enough to report thousands of CVEs. But there is much more than that.
There are CVEs for
- generic vulnerabilities. E.g. matching every vpn-subpackage, because someone found out that a rogue DHCP can influence VPN routing - unfixable. Or (theoretical) vulnerabilities in the bluetooth protocol, etc.
- Vulnerabilities that are highly disputed, e.g. the CVE author claims a very high base score, but the maintainer and the distributors decline this
- Vulnerabilities that only come into effect in an unrealistic edge case and are therefore not fixed by the maintainer/distro
- and so on and on

Overall this leads to an unhandable numbers in the dashboard, while monitoring just 200 hosts:
![image](https://github.com/user-attachments/assets/335fb76d-c56e-437a-97a7-01cc03e9c95e)

"This gives visibility to the vulnerabilities" No, in reality it doesn't. It just creates non-actionable scary high numbers.

**Comment by Gulaschcowboy** [comment]
@Dwordcito to add to that.
These are the numbers of just one Ubuntu 24.04 Laptop, daily fully patched. (my machine)
![image](https://github.com/user-attachments/assets/badc8122-2dc8-4299-bbe2-010e11cb5933)

With open CVEs back to 2016:
![image](https://github.com/user-attachments/assets/72cf59cd-472b-4b0a-bb42-406ccb6ac089)

Also, full of false positives, the package matching seems to have room for improvement too.

Anyhow, with that state it is not possible to filter for the important and actionable REAL vulnerabilities.

And trust me, you don't want to see the numbers for supported and still patched older Ubuntu versions (even with additional ESM) or Debian.

**Comment by Xyz00777** [comment]
Im 100% behind @Gulaschcowboy i think it's not okay to close it while you are discussing it with management. You should keep the issue open, even if management said that it will be implemented in the future because it will get lost otherwise. 
Oh and just as a short reminder ON the Wazuh Webside AND as the site description in Google you ARE advertising it as an unified XDR and SIEM, and a siem is a Management solution.

**Comment by Dwordcito** [comment]
@Gulaschcowboy 
It would be very good if instead of sharing aggregations, you would share certain witness cases with us so we can analyze them. Just because a system is updated or patched does not mean that it does not have vulnerabilities.

All the cases that you mention in your 3 points, none of them are considered false positives and the software packager itself marks them as vulnerable. Saying that it is full of false positives when canonical explicitly says that they are vulnerable does not seem correct to me.

If you see any case that the vendor (Ubuntu in your case) says that it is not vulnerable and we show it as vulnerable, we can solve it and it would be of great help to us if you would inform us. 

I repeat... if you don't want to see it in your vulnerability catalog because you don't agree with Ubuntu or whatever, you can exclude them in the future.

**Comment by Gulaschcowboy** [comment]
Hi Octavio,

"It would be very good if instead of sharing aggregations, you would share certain witness cases with us so we can analyze them"
-> We had a paid support ticket around that with you and disclosed everything there. The result was: "Please open a feature request on github" - which I did here. Also, your customer success team was involved.

"Just because a system is updated or patched does not mean that it does not have vulnerabilities."
-> I am fully aware. But if the distro or maintainer decides correctly, that the CVE is a non-issue or irrelevant and hence not patching: What shall I do with that result other than marking it somehow as accepted?

"Saying that it is full of false positives when canonical explicitly says that they are vulnerable does not seem correct to me." -> There are **package version detection** issues. It was all discussed in the support sessions. E.g. for Thunderbird and Firefox. Especially when you use the Mozilla packages directly. Similar problems with snap packages.

"I repeat... if you don't want to see it in your vulnerability catalog because you don't agree with Ubuntu or whatever, you can exclude them in the future."
-> First: I don't want to hide them completely, I need to mark them as accepted.

Second: I 100% agree with Ubuntu, this is really not the point.
But the distros or maintainers say e.g. "low prio due to low impact or edge case or whatever - won't fix", then I need to mark it as: Analyzed, checked, accepted for reason xyz. Because in the end I have to justify my decisions in front of an auditor, why we didn't shut down the whole system instead.

I don't see how a non-granular exclusion like 
   <exclusions>
       <cves>CVE-2024-12345,CVE-2024-6789</cves>
       <packages>tar,xz</packages>
   <exclusions>
makes it possible to handle the sheer number of to be accepted open CVEs in a "documentable" way and make room to see the really dangerous issues.

Again: It feels wrong, that the paid support and customer success team tells me: "please open a feature request on GitHub" while you are closing it immediately. 
Hence, we didn't progress to sign a support contract as this module is currently far from being useful for us and the proposed solution doesn't bring us closer.
 :shrug:

**Comment by Dwordcito** [comment]
You are talking to the development team here, not support. Basically here we try to be honest, for now the only thing we have approved from management (of which I am part) at the moment is the exclusions and I try to cover your case with what is approved. I can't lie to you and tell you "yes we will" or leave the issue perpetually open. 

Regarding Firefox and Thunderbird, we solved those problems some time ago, have you updated to the latest feed? False positives are an very high priority for us, regardless of whether we have the "acknowledge" feature or not.

Related issues:
Firefox products: https://github.com/wazuh/wazuh/issues/24171 and https://github.com/wazuh/wazuh/issues/25632

Please privately send me the support case number to escalate it... octavio.valle@wazuh.com I will interrupt the operations workflow sending implicit feature request to development under anonymity, when the development has no context about this.

**Comment by Xyz00777** [comment]
I feel like this discussion is drifting a bit off track 😅

What Gulaschcowboy and I are trying to say is this: while the current workaround you mentioned does help a little, it's not really a sustainable long-term solution. We’d have to constantly update the dashboard, adding longer and more complex searches over time. This isn’t great for performance, nor is it user-friendly. A good piece of software should do more than just present important data—it should actually help users work more efficiently, not slow them down. Coming from a SOC environment, I gave it a try on my home network and ended up uninstalling after two days because it created more hassle than it solved.

What we don’t understand is why close the issue altogether? Even if you don’t implement the feature right now, leaving it open causes no harm and ensures it’s not forgotten.

We’re not asking for a total rewrite or an acknowledgment feature for every single system. Just having an acknowledgment option for CVEs would be a great start. I think I even given you a really simple solution above for the start with really less to change in the code base and fast to be implemented.

If you wanted, you could even include these “non-fixable” states in the future inside the daily vulnerability updates or even as a additional so the customer don't have to do it. If that’s not possible right now due to supporting older versions or too mutch work on your site, I get it.
But at the very least consider keeping the issue open to revisit down the line or it will get forgotten.

**Comment by Gulaschcowboy** [comment]
Hi @Dwordcito , you requested to send a mail to you. I did. No answer?
