### ISSUE TITLE
False positive -  CVE-2013-7445 Ubuntu 24.04.1 LTS

### ISSUE THREAD

**Issue by retroisbest** [wazuh/wazuh#26884]
|Wazuh version|Component|Install type|Install method|Platform|
|4.92|VD|Local Install|Ubuntu|

https://nvd.nist.gov/vuln/detail/CVE-2013-7445#toggleConfig1

According to known affected software from [NVD CVE-2013-7445](https://nvd.nist.gov/vuln/detail/CVE-2013-7445#toggleConfig1). Linux kernel v4.x versions are affected only.

Ubuntu 24.04.1 LTS uses Kernel version 6.x

**Comment by JcabreraC** [comment]
As @Dwordcito points out, Ubuntu builds and maintains this specific package, along with managing a list of CVE vulnerabilities. They confirm that this vulnerability exists but have decided to postpone its fix due to its low priority:
https://ubuntu.com/security/CVE-2013-7445

I’m closing the issue. If you have any questions, feel free to reopen it.
