### ISSUE TITLE
Increase in Disk_read by wazuh-modulesd in Logcollector-SCA stress test

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh#26906]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  Alpha 3  |  Development  |  Ubuntu agent  | Download | 

## Description

During testing performed in https://github.com/wazuh/wazuh/issues/26897, a high increase of `wazuh-modulesd` in the Ubuntu agent `Disk_read` plot has been seen. This behavior has not been seen in previous versions or stages.

Plots are compared to [4.9.2-rc1](https://github.com/wazuh/wazuh/issues/26658).

### Current result

4.10.0 - Alpha 3 plot:

![logcollector_sca_ubuntu-pre-release_Disk_Read](https://github.com/user-attachments/assets/82320823-a2a4-4afc-9095-52a8c1a1d484)

### Expected result

4.9.2 - RC 1 plot:

![image](https://github.com/user-attachments/assets/86eda2a1-13e8-405d-b48d-5bf0bf5af83f)

### Attachments

- Build link: https://jenkins-staging.qa.wazuh.info/job/test_stress/51/

- Build parameters: https://jenkins-staging.qa.wazuh.info/job/test_stress/51/parameters/

- Artifacts: [csv.zip](https://github.com/user-attachments/files/17813969/csv.zip)

- Logs: [ossec.zip](https://github.com/user-attachments/files/17813967/ossec.1.zip)

**Comment by vikman90** [comment]
This issue has been described at:

- https://github.com/wazuh/wazuh/issues/25552#issuecomment-2326193350

Please, **compare `read_ops` instead of `disk_read`**.

## Data Comparison

### Disk Read

This metric shows how many bytes the process has read from the storage layer. This metric may be altered by many factors such as system load or memory stress.

|4.9.2 RC 1|4.10.0 Alpha 3|
|--|--|
| ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.2/B5703-3600m/B5703_agent_ubuntu/plots/monitor-agent-Test_stress_B5703_ubuntu-pre-release_Disk_Read.png) | ![logcollector_sca_ubuntu-pre-release_Disk_Read](https://github.com/user-attachments/assets/eb8caf9b-f1e8-47ff-93b8-c671d5292f2d) |

### Read Ops

This metric shows how much data the process has requested to read. It's related to the process behavior.

|4.9.2 RC 1|4.10.0 Alpha 3|
|--|--|
| ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.2/B5703-3600m/B5703_agent_ubuntu/plots/monitor-agent-Test_stress_B5703_ubuntu-pre-release_Read_Ops.png) | ![logcollector_sca_ubuntu-pre-release_Read_Ops](https://github.com/user-attachments/assets/d8d32d17-414b-49f6-9704-4106f796a850) |

This shows that the agent's behavior has not changed.

## Conclusion

This is a false positive, maybe caused by the environment.
