### ISSUE TITLE
Increase in PSS, RSS, USS and VMS of wazuh-modulesd in Logcollector stress test

### ISSUE THREAD

**Issue by jseg380** [wazuh/wazuh#26916]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  Alpha 3  |  Development  |  CentOS agent  | Download | 

## Description  

During testing performed in https://github.com/wazuh/wazuh/issues/26882, a high increase of `wazuh-modulesd` has been seen in several plots (PSS, RSS_MAXMIN, USS, VMS) of the CentOS agent.

Plots are compared to [4.9.2-rc1](https://github.com/wazuh/wazuh/issues/26671).

### Current plots

<details><summary>PSS</summary>
<p>

![image](https://github.com/user-attachments/assets/02d8b489-4c74-4087-8e9f-454e13240bab)

</p>
</details> 

<details><summary>RSS</summary>
<p>

![image](https://github.com/user-attachments/assets/b55ed6ae-eead-4c03-bd67-d3c898195458)

</p>
</details> 

<details><summary>RSS_MAXMIN</summary>
<p>

![image](https://github.com/user-attachments/assets/a8c43cfd-f82e-44b6-90ca-d08914135100)

</p>
</details> 

<details><summary>USS</summary>
<p>

![image](https://github.com/user-attachments/assets/de3c07f5-3c21-43d2-9b0b-4a106d927ac4)

</p>
</details> 

<details><summary>VMS</summary>
<p>

![image](https://github.com/user-attachments/assets/3b9f6d72-3666-4fb9-918f-079d96cda893)

</p>
</details> 

<details><summary>Disk_Read</summary>
<p>

![image](https://github.com/user-attachments/assets/08641cfe-6c8f-476b-9e20-bf166cfc8d83)

</p>
</details> 

### Previous plots

<details><summary>PSS</summary>
<p>

![image](https://github.com/user-attachments/assets/2762da26-db24-4410-8b62-e115a4b479d9)

</p>
</details> 

<details><summary>RSS</summary>
<p>

![image](https://github.com/user-attachments/assets/c731602b-28ac-48cd-86ef-c398e73c9d54)

</p>
</details> 

<details><summary>RSS_MAXMIN</summary>
<p>

![image](https://github.com/user-attachments/assets/30aba780-a771-41f8-bbb4-b1ab9485d41a)

</p>
</details> 

<details><summary>USS</summary>
<p>

![image](https://github.com/user-attachments/assets/ce5bb720-1bbd-4407-9598-5d4bb2020abd)

</p>
</details> 

<details><summary>VMS</summary>
<p>

![image](https://github.com/user-attachments/assets/93367208-e7a2-4ef6-a43e-c3d5bdf4aeaa)

</p>
</details> 

<details><summary>Disk_Read</summary>
<p>

![image](https://github.com/user-attachments/assets/f406eb49-097a-4bd6-9b7f-48add6c4b3bb)

</p>
</details> 

### Attachments

- Build link: https://jenkins-staging.qa.wazuh.info/job/test_stress/45/

- Build parameters: https://jenkins-staging.qa.wazuh.info/job/test_stress/45/parameters/

- Artifacts: [csv.zip](https://github.com/user-attachments/files/17814245/csv.zip)

- Logs: [ossec.zip](https://github.com/user-attachments/files/17814237/ossec.zip)

## Tasks
- [ ] Investigate the cause of this behaviour

**Comment by vikman90** [comment]
After carefully analyzing the data, we have the following insights:

1. **Test Context**:  
   The test in question does not place stress on any wazuh-modulesd components. Therefore, the observed metrics should not be attributed to component behavior under load.
2. **Cross-Platform Comparison**:  
   While an increase is noted in CentOS, similar tests performed on Ubuntu (with a comparable implementation) show significantly lower values, indicating this is not a consistent behavior across platforms.
3. **Consistency Across Test Scenarios**:  
   When comparing the RSS of `wazuh-modulesd` in other tests, such as Logcollector+SCA, we observe similar values, further reinforcing the inconsistency of this particular measurement.

## Analysis

### Logcollector test

#### CentOS

|| [4.9.2 RC 1](https://github.com/wazuh/wazuh/issues/26671) | [4.10.0 Alpha 3](https://github.com/wazuh/wazuh/issues/26882) |
|--|--|--|
| Chart | ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.2/B5696-3600m/B5696_agent_centos/plots/monitor-agent-Test_stress_B5696_centos-pre-release_RSS.png) | ![monitor-agent-Test_stress_B45-centos-pre-release_RSS](https://github.com/user-attachments/assets/877e9d89-e1de-40cf-818a-7a95f305537d) |
| RSS | ~ 7 MB | ~ 13 MB ⚠️  |

### Ubuntu

|| [4.9.2 RC 1](https://github.com/wazuh/wazuh/issues/26671) | [4.10.0 Alpha 3](https://github.com/wazuh/wazuh/issues/26882) |
|--|--|--|
| Chart | ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.2/B5696-3600m/B5696_agent_ubuntu/plots/monitor-agent-Test_stress_B5696_ubuntu-pre-release_RSS.png) | ![monitor-agent-Test_stress_B45-ubuntu-pre-release_RSS](https://github.com/user-attachments/assets/ee1d802d-7916-45ad-90bd-5457877d72ab) |
| RSS | ~ 3 MB | ~ 3 MB |

### Logcollector + SCA test

#### CentOS

|| [4.9.2 RC 1](https://github.com/wazuh/wazuh/issues/26658) | [4.10.0 Alpha 3](https://github.com/wazuh/wazuh/issues/26897) |
|--|--|--|
| Chart | ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.2/B5703-3600m/B5703_agent_centos/plots/monitor-agent-Test_stress_B5703_centos-pre-release_RSS.png) | ![logcollector_sca_centos-pre-release_RSS](https://github.com/user-attachments/assets/8ed6532c-0377-4544-bd9d-311b41c737c2) |
| RSS | ~ 62 MB | ~ 62 MB |

### Ubuntu

|| [4.9.2 RC 1](https://github.com/wazuh/wazuh/issues/26658) | [4.10.0 Alpha 3](https://github.com/wazuh/wazuh/issues/26897) |
|--|--|--|
| Chart | ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.2/B5703-3600m/B5703_agent_ubuntu/plots/monitor-agent-Test_stress_B5703_ubuntu-pre-release_RSS.png) | ![logcollector_sca_ubuntu-pre-release_RSS](https://github.com/user-attachments/assets/0ebd36e1-9c2f-42c7-981c-cae37b33df9f) |
| RSS | ~ 58 MB | ~ 53 MB |

## Conclusion  

The reported increase in the CentOS environment appears to be an outlier in the measurement process rather than an inherent issue with `wazuh-modulesd`.
