### ISSUE TITLE
Abnormal increase in Syscheck dropped events for Footprint stress test 4.10.0-alpha3

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh#26926]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  alpha3  |  Development  |  syscheck  | Download | 

## Description
During the analysis of [Footprint syscheck test for 4.10.0-alpha3](https://github.com/wazuh/wazuh/issues/26881), it has been found an abnormal behavior in dropped events of syscheck plot, comparing with 4.9.2-rc1 version the plots are different in that case, in the rest the plots are very similar, so it is needed to investigate if that behavior is expected, also the configuration for manager and agents haven't any strong change.

- 4.10.0-alpha3
![387689783-f5364ce5-35a0-4bb9-bba0-55780b4d4600](https://github.com/user-attachments/assets/fa058cfd-84e9-4776-aadf-522b867747c1)

- 4.9.2-rc1
![387690563-ba26564a-58c8-46b2-a38c-bd74dbe06c79](https://github.com/user-attachments/assets/b2e70d6d-2652-4aa0-ae29-bb9ee9ab9f01)

### Environment

| Node | Vagrant/AWS | Image | CPU | RAM (GB) | Disk size (GB) | Packages/Repository/Sources branch|
|:--:|:--:|:--:|:--:|:--:|:--:|---|
| Master node | AWS | CentOS 8 | c5a.large | c5a.large | 400 | Packages |
| Agent node | AWS | CentOS 8 | c5a.large | c5a.large | 32 | Packages|
| Agent node | AWS | Ubuntu 20 | c5a.large | c5a.large | 32 | Packages|
| Agent node | AWS | Windows 2019 | c5a.2xlarge| c5a.2xlarge | 64 | Packages|

### Steps to reproduce

1. Launch Test Stress build 2,5d: https://jenkins-staging.qa.wazuh.info/job/test_stress_tier/ with the parameters: https://jenkins-staging.qa.wazuh.info/job/test_stress_tier/4/parameters

2. Check the test and plots for Syscheck

### Current result
An abnormal increase in dropped events plot for syscheck

### Expected result
A similar behavior with 4.9.2-rc1 plot, unless it is expected that behavior.

### Attachments

- Build link: https://jenkins-staging.qa.wazuh.info/job/test_stress/44/

- Build parameters: https://jenkins-staging.qa.wazuh.info/job/test_stress/44/parameters

- Logs: 

  - 4.10.0-alpha3
  [csv.zip](https://github.com/user-attachments/files/17828656/csv.zip)
  [ossec.zip](https://github.com/user-attachments/files/17828657/ossec.zip)

  - 4.9.2-rc1
  [csv.zip](https://github.com/user-attachments/files/17828671/csv.zip)
  [ossec_Test_stress_B5695_manager_2024-10-31.zip](https://github.com/user-attachments/files/17828673/ossec_Test_stress_B5695_manager_2024-10-31.zip)

**Comment by vikman90** [comment]
## Analysis

||[4.9.2 RC 1](https://github.com/wazuh/wazuh/issues/26670)|[4.10.0 Alpha 3](https://github.com/wazuh/wazuh/issues/26881)|Delta|
|--|--|--|--|
|Decoded events|![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.2/B5695-3600m/B5695_manager_centos/plots/Test_stress_B5695_manager_analysisd_events_Decoded_events.png)|![test_stress_B44_manager_analysisd_events_Decoded_events](https://github.com/user-attachments/assets/99e71d9c-6617-413b-8e53-72c476a3129b)| Similar |
|Dropped events|![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.2/B5695-3600m/B5695_manager_centos/plots/Test_stress_B5695_manager_analysisd_events_Dropped_events.png)|![test_stress_B44_manager_analysisd_events_Dropped_events](https://github.com/user-attachments/assets/c534ca57-db37-47cb-b130-bc7b045dbad9)|45 events, just once |
|EDPS|![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.2/B5695-3600m/B5695_manager_centos/plots/Test_stress_B5695_manager_analysisd_events_EDPS.png)|![test_stress_B44_manager_analysisd_events_EDPS](https://github.com/user-attachments/assets/591ccf6a-c543-44f1-80b8-23f43f6908f2)| Similar |
|Queue|![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.2/B5695-3600m/B5695_manager_centos/plots/Test_stress_B5695_manager_analysisd_state_Queues_state.png)|![test_stress_B44_manager_analysisd_state_Queues_state](https://github.com/user-attachments/assets/0688de47-3fac-4a9d-b165-74362f340d37)| Similar |

## Conclusion

This issue is related to:
- #25192

Due to the very small queue, it is possible that it will fill up at certain times. However, we see that the queue is usually below 40%.
