### ISSUE TITLE
Package provider for RPM reports vendor with NULL value. 

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#26953]
# Description 

During testing on Fedora 41, as part of this issue (https://github.com/wazuh/wazuh/issues/26738), it was found that one of the RPM format packages has a null vendor value. 

```json
{
  "scan_id": 0,
  "scan_time": "2024/11/21 12:50:30",
  "format": "rpm",
  "name": "inspectorssmplugin",
  "priority": " ",
  "section": "Unspecified",
  "size": 41678439,
  "vendor": null,
  "install_time": "1709821428",
  "version": "1.0.185-1",
  "architecture": "x86_64",
  "multiarch": null,
  "source": " ",
  "description": "Inspector ssm plugin for linux which scans packages installed on host to find vulnerabilities",
  "location": " ",
  "cpe": null,
  "msu_name": null,
  "checksum": "075c4168384f0e57b7ae5bc98e61a9df0c569978",
  "item_id": "79b5e66869e6ec84e600032d24c8a48d610829c1"
}
```

Doing a quick research it seems an AWS package, but we need vendor information to tell the vulnerability scanner how to evaluate that package. 

## DoD 
- [ ] Verify whether the vendor information does not exist or is wrongly parsed.
- [ ] If the vendor is not present, a value different from null must be defined. Take into account the information that the vulnerability scanner requires to scan the package. Sync with @wazuh/devel-cppserver-div1

**Comment by mjcr99** [comment]
## Update
**(25/11/2024)** The reason for this behavior is that the retrieved package vendor from the executed query is empty, as seen here tracing it with `gdb`:

```
(gdb) p package.vendor
$172 = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<std::__new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffd8f0 ""}, _M_string_length = 0, {
    _M_local_buf = "\000edora Project\000", _M_allocated_capacity = 5773721866411992320}}
```

To deal with this kind of situations, which is really strange since this package is the only one that has had this structure, the following commit: 85bcb7fd0b3c339d5bf157a46a0595fde7ea5792 is pretended to be added, to check if the vendor field is empty and set it to `UNKNOWN_VALUE`  in that case.
