### ISSUE TITLE
Decrease of modulesd values in multiple plots in the manager

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#27087]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  beta1  |  Development  |  modulesd  | Packages | 

 

## Description
During the analysis of [VULNERABILITY-DETECTOR-REGISTER (2.5d)](https://github.com/wazuh/wazuh/issues/26999), it has been found a relevant drop of modulesd in multiple manager plots, comparing to 4.9.2-rc1 and 4.10.0-alpha2 (in alpha3 the test was skipped) version 

CPU: Decrease of modulesd level at the end of the test
Disk: modulesd has a different level of disk use similar to db and authd while in 4.9.2 the use was relevantly higher
Disk_read, disk_written: relevant decrease of modulesd
FD, PSS, Read_Ops, RSS, USS, VMS, write_ops: decrease of modulesd

This could be related to: https://github.com/wazuh/wazuh/issues/27086

- 4.10.0-beta1
![image](https://github.com/user-attachments/assets/41214020-61ff-4cf7-9fe0-50c0867c69fd)
![image](https://github.com/user-attachments/assets/d0ccd4e8-65e5-42ee-b47a-ceea37d74ee2)
![image](https://github.com/user-attachments/assets/1b3efd76-dc03-46cc-958d-a038fffc7bba)
![image](https://github.com/user-attachments/assets/dbbceec0-db29-4854-8690-0588da4ea541)
![image](https://github.com/user-attachments/assets/536ded3f-9145-4c91-960a-c9d1cea736d7)
![image](https://github.com/user-attachments/assets/a9aba51e-76f6-45ea-a096-5d4caa30fabe)
![image](https://github.com/user-attachments/assets/910f28bd-92ff-4f05-bcee-cac869416705)
![image](https://github.com/user-attachments/assets/2c2e35c5-bc53-4381-be73-c596d6509790)
![image](https://github.com/user-attachments/assets/811efa14-8a41-4241-9c49-2fed72d3e1f3)
![image](https://github.com/user-attachments/assets/5bd2984c-a2e0-435f-ad7e-f4c26d584841)
![image](https://github.com/user-attachments/assets/08b012d1-fe10-46a2-9414-e3422bd02981)

- 4.9.2-rc1
![image](https://github.com/user-attachments/assets/6b643c31-cf0c-47db-9b0a-09a7c383778d)
![image](https://github.com/user-attachments/assets/12d67fee-1315-47d1-9442-e41815445a45)
![image](https://github.com/user-attachments/assets/e16b9902-fad0-4f61-bca6-9d78462998c0)
![image](https://github.com/user-attachments/assets/896e5ada-362a-44a8-b904-4c1aec6c9395)
![image](https://github.com/user-attachments/assets/492c4890-2da0-453c-8e7a-d6ceae3cecde)
![image](https://github.com/user-attachments/assets/17004980-0baa-4201-90a4-045793843390)
![image](https://github.com/user-attachments/assets/d618d991-1816-4d2f-88f2-065f7fc42732)
![image](https://github.com/user-attachments/assets/0f321f72-1db4-4fb3-88ed-1ba463a21d1f)
![image](https://github.com/user-attachments/assets/f6181919-3be6-44ef-bc81-4efc4bb61e04)
![image](https://github.com/user-attachments/assets/5240f29f-9bdf-4b52-9e48-b36dc1dcc63b)
![image](https://github.com/user-attachments/assets/59224754-8914-4b28-8957-9a432773dde6)

### Environment

| Node | Vagrant/AWS | Image | CPU | RAM (GB) | Disk size (GB) | Packages/Repository/Sources branch|
|:--:|:--:|:--:|:--:|:--:|:--:|---|
| Master node | AWS | CentOS 8 | c5a.large | c5a.large | 400 | Packages |
| Agent node | AWS | CentOS 8 | c5a.large | c5a.large | 32 | Packages|
| Agent node | AWS | Ubuntu 20 | c5a.large | c5a.large | 32 | Packages|
| Agent node | AWS | Windows 2019 | c5a.2xlarge| c5a.2xlarge | 64 | Packages|

### Steps to reproduce

1. Launch Test Stress build 2,5d: https://jenkins-staging.qa.wazuh.info/job/test_stress/ with the parameters: https://jenkins-staging.qa.wazuh.info/job/test_stress/91/parameters

2. Check the test and plots

### Current result
A relevant drop of modulesd in multiple manager plots and the presence of:

```
2024/11/25 00:40:41 wazuh-modulesd:content-updater WARNING: Error '-1' when downloading file: Could not connect to server. 
```
Described: https://github.com/wazuh/wazuh/issues/27086

### Expected result
A similar behavior with 4.9.2-rc1 plot, unless it is expected that behavior.

### Attachments

- Build link: https://jenkins-staging.qa.wazuh.info/job/test_stress/91/

- Build parameters: https://jenkins-staging.qa.wazuh.info/job/test_stress/91/parameters

- Logs: 

  - 4.10.0-beta1
https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B91-3600m/B91_manager_centos/logs/ossec_test_stress_B91_manager_2024-11-25.zip

  - 4.9.2-rc1
https://ci.wazuh.com/data/Test_stress/pre-release/4.9.2/B5701-3600m/B5701_manager_centos/logs/ossec_Test_stress_B5701_manager_2024-10-31.zip

**Comment by pereyra-m** [comment]
## Analysis

I haven't found any error or warning message in the logs that isn't expected.


### CPU :green_circle: 

Here I see a constant CPU usage during the tests, and a sudden decrease when the test ends.
The plot is expected and it's real similar to v4.9.2.

### Disk, disk_read, disk_write, Read_Ops, Write_Ops, FD :green_circle: 

I understand that now the content isn't updated during the test.
That's why in v4.9.2 we see a message like `Feed update process completed` that isn't present in v4.10.0.
The download of the new DB offsets at the beginning of the tests explains the difference between v4.9.2 and v4.10.0 related to the disk usage.

There is a red spike for `wazuh-modulesd` around `2024-11-24 12:42:24` but the logs don't show anything unusual and both plots (4.9.2 and 4.10.0) end up with similar values.

The disk write plots have the same shape in fact, because now that the total writes have decreased due to the lack of offsets update, we are comparing plots with one order of magnitud of difference

<details><summary>Details</summary>
<p>

![2024-11-28_11-34](https://github.com/user-attachments/assets/50880122-aa57-4d26-a834-0ac44a639ea9)

</p>
</details> 

## RSS, USS, VMS, PSS :green_circle: 

It's hard to explain the memory usage only with logs (without debug). 
The v4.10.0 release contains some improvements and fixes for the module, and we know that now the test is run without content update. 

Comparing the images, we can see that during the stress phase, both plots have the same working strip of almost 150MB.
The main difference for the total memory usage is due to the initial phase, related to the content update

<details><summary>Details</summary>
<p>

![2024-11-28_11-54](https://github.com/user-attachments/assets/6a8a989c-8983-4764-9d83-9c2e3f81e4dc)

</p>
</details>

**Comment by sebasfalcone** [comment]
Thanks @pereyra-m for the analysis

## Conclusion
The reduction can be explained by the lack of content update, the tests don't reflect the same scenario

**Comment by Dwordcito** [comment]
LGTM
