### ISSUE TITLE
Consistent increase of modulesd in RSS, RSS_MAXMIN and USS in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#27092]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  beta1  |  Development  |  modulesd  | Packages | 

 

## Description
During the analysis of [Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS (2.5d)](https://github.com/wazuh/wazuh/issues/27006), it has been found an consistent increase modulesd in RSS, RSS_MAXMIN, USS in CentOS to 4.9.1-RC4 version 

RSS, RSS_MAXMIN, USS : increase of modulesd

- 4.10.0-beta1
![image](https://github.com/user-attachments/assets/fbd99e73-cbcf-4167-be5c-837d3b504cd6)
![image](https://github.com/user-attachments/assets/44208701-ad45-41dc-add7-251fe19569ee)
![image](https://github.com/user-attachments/assets/e816cbdb-bbad-41ed-b4fb-c9dd8063459b)

- 4.9.2-rc1
![image](https://github.com/user-attachments/assets/591e3df5-7550-450c-8fb6-b8da998e7fb2)
![image](https://github.com/user-attachments/assets/e2edc6dc-20f0-4935-bb43-e544e2f0ca44)
![image](https://github.com/user-attachments/assets/31c16838-a496-4195-9a77-2f3539ca4318)

### Environment

| Node | Vagrant/AWS | Image | CPU | RAM (GB) | Disk size (GB) | Packages/Repository/Sources branch|
|:--:|:--:|:--:|:--:|:--:|:--:|---|
| Master node | AWS | CentOS 8 | c5a.large | c5a.large | 400 | Packages |
| Agent node | AWS | CentOS 8 | c5a.large | c5a.large | 32 | Packages|
| Agent node | AWS | Ubuntu 20 | c5a.large | c5a.large | 32 | Packages|
| Agent node | AWS | Windows 2019 | c5a.2xlarge| c5a.2xlarge | 64 | Packages|

### Steps to reproduce

1. Launch Test Stress build 2,5d: https://jenkins-staging.qa.wazuh.info/job/test_stress/ with the parameters: https://jenkins-staging.qa.wazuh.info/job/test_stress/95/parameters

2. Check the test and plots

### Current result
Increase of the range of fluctuation of RSS.

### Expected result
A similar behavior with 4.9.1-rc4 plot, unless it is expected that behavior.

### Attachments

- Build link: https://jenkins-staging.qa.wazuh.info/job/test_stress/95/

- Build parameters: https://jenkins-staging.qa.wazuh.info/job/test_stress/95/parameters

- Logs: 

  - 4.10.0-beta1
 
https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/logs/ossec_test_stress_B95_centos_2024-11-25.zip

https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/logs/ossec_test_stress_B95_ubuntu_2024-11-25.zip

  - 4.9.1-rc4
  
https://ci.wazuh.com/data/Test_stress/pre-release/4.9.1/B5686-3600m/B5686_agent_centos/logs/ossec_Test_stress_B5686_centos_2024-10-24.zip

https://ci.wazuh.com/data/Test_stress/pre-release/4.9.1/B5686-3600m/B5686_agent_ubuntu/logs/ossec_Test_stress_B5686_ubuntu_2024-10-24.zip

**Comment by vikman90** [comment]
## Analysis

### CentOS Agent

||[4.9.1 RC 4](https://github.com/wazuh/wazuh/issues/26501)|[4.10.0 Alpha 3](https://github.com/wazuh/wazuh/issues/26889)|[4.10.0 Beta 1](https://github.com/wazuh/wazuh/issues/27006)|Difference|
|---|--:|--:|--:|--:|
|CPU Time (s)|139.28|64.47|110.67|20.54 % 🔽 |
|CPU Average (%)|0.35|0.16|0.28|20.56 % 🔽 |
|CPU Max (%)|4.00|4.00|4.00|🟰 |
|**RSS Average** (MB)|10.42|10.17|21.79|**109.06** % 🔼 |
|**RSS Max** (MB)|10.52|10.23|22.17|**110.73** % 🔼 |
|FD Average|13.00|13.00|13.00|0.01 % 🔼 |
|FD Max|14.00|14.00|15.00|7.14 % 🔼 |
|Read Ops Average (M)|71.04|71.09|70.96|0.11 % 🔽 |
|Read Ops Max (M)|142.09|142.01|141.81|0.19 % 🔽 |
|Write Ops Average (M)|1.19|1.20|1.19|0.09 % 🔼 |
|Write Ops Max (M)|2.38|2.39|2.39|0.12 % 🔼 |
|Disk Read Average (MB)|73.96|72.67|73.48|0.64 % 🔽 |
|Disk Read Max (MB)|76.30|73.32|74.80|1.98 % 🔽 |
|Disk Write Average (MB)|6622.48|5419.04|5645.14|14.76 % 🔽 |
|Disk Write Max (MB)|11872.21|9429.07|9722.83|18.10 % 🔽 |

### Ubuntu Agent 

||[4.9.1 RC 4](https://github.com/wazuh/wazuh/issues/26501)|[4.10.0 Alpha 3](https://github.com/wazuh/wazuh/issues/26889)|[4.10.0 Beta 1](https://github.com/wazuh/wazuh/issues/27006)|Difference|
|---|--:|--:|--:|--:|
|CPU Time (s)|38.70|27.10|21.00|45.73 % 🔽 |
|CPU Average (%)|0.10|0.07|0.05|45.71 % 🔽 |
|CPU Max (%)|4.00|4.00|4.00|🟰 |
|**RSS Average** (MB)|7.43|8.23|8.30|**11.60** % 🔼 |
|**RSS Max** (MB)|8.58|8.26|8.45|**1.55** % 🔽 |
|FD Average|11.00|11.00|11.00|🟰 |
|FD Max|12.00|12.00|12.00|🟰 |
|Read Ops Average (M)|0.31|0.31|0.28|8.24 % 🔽 |
|Read Ops Max (M)|0.58|0.58|0.55|5.22 % 🔽 |
|Write Ops Average (M)|0.01|0.01|0.01|🟰 |
|Write Ops Max (M)|0.01|0.01|0.01|🟰 |
|Disk Read Average (MB)|0.04|0.01|0.01|70.97 % 🔽 |
|Disk Read Max (MB)|0.11|0.01|0.02|85.19 % 🔽 |
|Disk Write Average (MB)|12.55|12.60|12.68|1.02 % 🔼 |
|Disk Write Max (MB)|25.04|25.09|25.21|0.67 % 🔼 |

### Rationale

There is a more than noticeable increase in 4.10.0 Beta-1, with the following facts:

- It only appears in the CentOS agent, but not in Ubuntu, with a similar implementation.
- It is seen in 4.10.0 Beta-1 but not in Alpha-3
- There have been no changes in this tag that affect memory.
- The difference happens at the start of the daemon, which is prone to using a noticeably different amount of memory randomly due to fragmentation.

#### Changes affecting wazuh-modulesd Beta 1:

- https://github.com/wazuh/wazuh/pull/26836
- https://github.com/wazuh/wazuh/pull/26903

For all these reasons, we conclude that it was a one-off increase due to fragmentation.

## Conclusion

For all these reasons, we conclude that it was a one-off increase due to fragmentation.
