### ISSUE TITLE
Memory values (RSS, USS, PSS) increase for modulesd and wazuh-db during Vulnerability Detection performance tests

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#27104]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  beta1  |  Development  |  modulesd/wazuh-db  | Packages | 

 

## Description
During the analysis of https://github.com/wazuh/wazuh/issues/26996 - Very High Activity, it has been found a baseline increase for memory values related to modulesd and wazuh-db. This is happening on the master node.

- 4.9.2-rc1

![PSS](https://github.com/user-attachments/assets/b910aae3-1ccf-4a4b-8551-3d18383fb05d)
![RSS](https://github.com/user-attachments/assets/148a8d0e-8eaa-4aab-a532-55a6084444df)
![USS](https://github.com/user-attachments/assets/95c374ec-2e8f-4fe5-8313-10478a7f84c2)

- 4.10.0-beta1
![PSS](https://github.com/user-attachments/assets/dc80adbf-5787-42ea-8735-09b9289feb82)
![RSS](https://github.com/user-attachments/assets/0c9d1082-ca77-4c1e-ac75-82bb86365e8b)
![USS](https://github.com/user-attachments/assets/f6111f13-faa0-406c-8dc4-15c52037feaf)

### Details
- Job https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/801/

**Comment by pereyra-m** [comment]
## Update

I've working to understand what is happening with the memory consumption.

A memory spike during a full re-scan is expected as we analyzed at https://github.com/wazuh/wazuh/issues/26628#issuecomment-2449072642.
What we need to understand is why it's higher in 4.10.0_beta1 than 4.9.2_RC1.

I've compared 4.10.0_beta, 4.10.0_alpha3 and 4.9.2_RC1.
We don't find the spike in alpha3 because the re-scan happens before the agent registration

![rss_compare](https://github.com/user-attachments/assets/cd49e832-ae07-4854-bdf3-e1d9f13c1d62)

4.10.0_beta1
```
...
2024/11/27 04:13:20 wazuh-authd: INFO: Agent key generated for '1-FqmfrRbs2ShWwVPC-debian10' (requested by any)
...
2024/11/27 04:17:32 wazuh-modulesd:vulnerability-scanner: INFO: Triggered a re-scan after content update
```

4.10.0_alpha3
```
...
2024/11/12 21:00:46 wazuh-modulesd:vulnerability-scanner: INFO: Triggered a re-scan after content update.
...
2024/11/12 21:03:52 wazuh-authd: INFO: Received request for a new agent (1-tejD4Qc89sUyWaTI-debian10) from: 172.31.19.174
...
```

4.9.2_RC1
```
...
2024/10/29 12:22:33 wazuh-authd: INFO: Agent key generated for '1-o7qUJOHXCcdwLg81-debian10' (requested by any)
...
2024/10/29 12:23:57 wazuh-modulesd:vulnerability-scanner: INFO: Triggered a re-scan after content update.
....
```

The same happens for `wazuh-modulesd`, we have a greater value at 4.10.0_beta1
![newplot](https://github.com/user-attachments/assets/167883c6-6d57-4b64-8594-be12062942b5)

If we plot at the same time `wazuh-db` and `wazuh-modulesd` we can see that the modules are working at the same time during the high memory usage because the re-scan is in progress. But at 4.9.2_RC1 `wazuh-db` is higher than `wazuh-modulesd`, and at 4.10.0_beta1, `wazuh-modulesd` is higher than `wazuh-db`

![both_4 9 2](https://github.com/user-attachments/assets/5425ad15-b271-447d-b977-a433c9197b4f)

![both_4 10 0](https://github.com/user-attachments/assets/f181597e-a793-4491-99a8-83a2b8fa443f)

I've studied the release notes https://github.com/wazuh/wazuh/releases/tag/v4.10.0-beta1.
I'll describe some changes in the scanner, none of them request more data from `wazuh-db` and there aren't changes in `wazuh-db`

- The fixes in the scanner that avoid repeated reports or indexation/content update loops don't explain this behavior (https://github.com/wazuh/wazuh/pull/25094) (https://github.com/wazuh/wazuh/pull/26223) (https://github.com/wazuh/wazuh/pull/26922).
- The improvement of the descriptions doesn't impact `wazuh-db` because that new information doesn't come from there. It could explain the increase of memory usage of `wazuh-moduled` only, because before we used only the `NVD` descriptions but now we request also the `ADP` ones (https://github.com/wazuh/wazuh/issues/25479).
- The fix in the concurrency of the caches doesn't impact the memory usage (https://github.com/wazuh/wazuh/pull/26073).
- The fix to remove the dangling entries from the index when an agent is removed isn't related either (https://github.com/wazuh/wazuh/pull/26232).
- The segmentation fault fix doesn't impact in the memory consumption (https://github.com/wazuh/wazuh/pull/26842).
- The changes in the re-scan logic when the configuration changes aren't related to this issue (https://github.com/wazuh/wazuh/pull/24034).
- The self-recovery mechanism doesn't impact in this issue (https://github.com/wazuh/wazuh/pull/24333). 

So if:
- We don't have changes in `wazuh-db`
- We don't have changes in the scanner that request more data
- We have the same amount of agents

My only hypothesis is that the amount of data has changed, for example, agents' packages, etc.
I'll verify this with the QA team to continue the research.

**Comment by sebasfalcone** [comment]
## Conclusion
As @pereyra-m states, there is no good justification for these changes in the manager's code. We suspect that the data received could differ from one test to the other, this is still not verified (CC: @jnasselle)

On the other hand, we propose to see the results of the next RC and make this comparison again

**Comment by Dwordcito** [comment]
LGTM, @jnasselle reopen if this issue occurs in RC1 tests. It looks fragmentation at first glance.
