### ISSUE TITLE
Investigate and ensure proper logging visibility for Wazuh-Engine with Systemd

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh#27122]
#### Description

When running **Wazuh-Server** with systemd, the **Wazuh-Engine** logs are expected to be accessible via `journalctl`. However, there seems to be an issue where logs from Wazuh-Engine are not visible when using the command:

```bash
journalctl -xeu wazuh-engine --no-pager
```

Instead, it may be necessary to use the following command to see the logs:

```bash
journalctl -xeu wazuh-server --no-pager
```

This issue needs investigation to confirm:
1. Whether **Wazuh-Engine** logs are being output correctly to `journald`.
2. If they are being redirected or encapsulated under the `wazuh-server` systemd unit.

#### Objectives

1. Investigate why `journalctl -xeu wazuh-engine` does not show logs for Wazuh-Engine.
2. Verify that logs from Wazuh-Engine are properly routed to `journald` under the expected unit.
3. Make adjustments to systemd configurations if necessary to ensure logs are visible via `journalctl -xeu wazuh-engine`.

#### Acceptance Criteria

- Logs for Wazuh-Engine are visible via `journalctl -xeu wazuh-engine` or `wazuh-server`
- No logs are lost, and the logging behavior is consistent with expectations.
- Documentation is updated to reflect the correct commands and configurations.

#### Additional Information

- **Potential Cause:** The issue may stem from Wazuh-Engine logs being routed through Wazuh-Server's systemd unit instead of having a dedicated journald stream.
- **Reference:** [systemd.service Logging Documentation](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#StandardOutput=)

**Comment by juliancnn** [comment]
## Update

I confirm that the logs can be viewed from wazuh-server unit logs.

![image](https://github.com/user-attachments/assets/38d451b2-58bb-4fca-9106-93304fea00c5)

**Comment by JcabreraC** [comment]
### Resolution:
After investigation, it was confirmed that logs generated by **Wazuh-Engine** are currently routed through the `wazuh-server` systemd unit and are accessible via:

```bash
journalctl -xeu wazuh-server --no-pager
```

This behavior is intentional, as **Wazuh-Engine** is tightly integrated with **Wazuh-Server**, and its logging is designed to flow through the main server unit.

For consistency and simplicity, we will retain the current configuration where **Wazuh-Engine** logs are included in the `wazuh-server` unit logs. Users can reliably access all relevant logs through the `wazuh-server` unit.
