### ISSUE TITLE
Version 3.8.2 Windows Agent truncating the event logs

### ISSUE THREAD

**Issue by teb1z** [wazuh/wazuh#2713]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.8.2 | Manager/Agent | Packages/Sources | Windows Server 2016 / Windows 10 |

## EventChannel issue that led to incomplete windows logs
The new eventchannel idea is great, but it's breaking hundreds of my own custom rules. Further my custom made dashboards also breaks because of this eventchannel transformation. It's difficult to adapt to these new json decoded fields afterwards.

This is why I had to figure out a way to keep the old event logging format. I did it via **wazuh manager** in the shared **agent.conf** file by changing the log_format to be eventlog.
`<agent_config>`
`<localfile>`
`    <location>Security</location>`
`    <log_format>eventlog</log_format>`
`</localfile>`
`<localfile>`
`    <location>System</location>`
`    <log_format>eventlog</log_format>`
`</localfile>`
`</agent_config>`

This works, and the data is flowing like in the previous version **but** those logs are not complete. The full logs are interrupted from somewhere in the middle.

This is log example from process creation event 4688.
**Before version upgrade and agent.conf change, full log looks like this:**
`2019 Feb 27 14:00:41 WinEvtLog: Security: AUDIT_SUCCESS(4688): Microsoft-Windows-Security-Auditing: (no user): no domain: LABCOMPUTER01.LAB01: A new process has been created.    Creator Subject:   Security ID:  S-1-5-18   Account Name:  LABCOMPUTER01$   Account Domain:  LAB01   Logon ID:  0x3E7    Target Subject:   Security ID:  S-1-0-0   Account Name:  -   Account Domain:  -   Logon ID:  0x0    Process Information:   New Process ID:  0x2e58   New Process Name: C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe   Token Elevation Type: %%1936   Mandatory Label:  S-1-16-16384   Creator Process ID: 0x26d4   Creator Process Name: C:\Windows\SysWOW64\cmd.exe   Process Command Line:   Token Elevation Type indicates the type of token that was assigned to the new process in accordance with User Account Control policy.    Type 1 is a full token with no privileges removed or groups disabled.  A full token is only used if User Account Control is disabled or if the user is the built-in Administrator account or a service account.    Type 2 is an elevated token with no privileges removed or groups disabled.  An elevated token is used when User Account Control is enabled and the user chooses to start the program using Run as administrator.  An elevated token is also used when an application is configured to always require administrative privilege or to always require maximum privilege, and the user is a member of the Administrators group.    Type 3 is a limited token with administrative privileges removed and administrative groups disabled.  The limited token is used when User Account Control is enabled, the application does not require administrative privilege, and the user does not choose to start the program using Run as administrator.`

**After the agent/manager upgrade and disabling the eventchannel logtype**:
`2019 Feb 27 15:50:52 WinEvtLog: Security: AUDIT_SUCCESS(4688): Microsoft-Windows-Security-Auditing: (no user): no domain: LABCOMPUTER01.LAB01: A new process has been created. Subject:  Security ID:  S-1-5-18  Account Name:  LABCOMPUTER01$  Account Domain:  LAB01  Logon ID:  0x3e7  Process Information:  New Process ID:  0x3514  New Process Name: C:\Windows\System32\consent.exe  Token Elevation Type: %%1936  Creator Process ID: 0x1918`

In this example, the log is interrupted between Windows fields *Creator Process ID* and *Creator Process Name*.

At this moment my fix was downgrading manager and agent to version 3.7.2.

**Comment by Zenidd** [comment]
Hello @Leamsy,

first of all, we feel sorry for the late reply.

Our team is reviewing this issue an if it is possible we are going to include your arrangement in Wazuh project. Thank you for your contribution!

<br></br>
Best regards,

Juan Pablo Sáez

**Comment by Zenidd** [comment]
Hello again, @teb1z

Effectively the ruleset had a [great change in 3.8]( https://documentation.wazuh.com/3.x/release-notes/release_3_8_0.html#wazuh-core), where the events are extracted and sent in JSON. 
We have left aside the previous ruleset in order to extract much more useful information and adapting your custom rules to new JSON format will give you access to more fields from each event.

From the Wazuh team we apologize for the inconveniences this situation may cause. You have the option not to update your agents, or update them and use the latest version of the ruleset. 

As for Eventlog, log truncating is a known bug. We are going to fix this bug in upcoming releases so that you can display and use the complete log.
<br></br>
Best regards,

Juan Pablo Sáez

**Comment by daescar** [comment]
We have been researching what reason the log is truncated and it seems the "Security Logs" is being read with a specific function : **`el_vista_getMessage`** in [**read_win_el.c**](https://github.com/wazuh/wazuh/blob/master/src/logcollector/read_win_el.c),
which is based on a template file [(**vista_sec.txt**)](https://github.com/wazuh/wazuh/blob/master/src/win32/vista_sec.txt) to parse different events.
However, when we use the ordinary function to read logs : **`el_getMessage`** in [**read_win_el.c**](https://github.com/wazuh/wazuh/blob/master/src/logcollector/read_win_el.c),
we get the complete log event : 
```
2019 Jun 18 05:38:33 WinEvtLog: Security: AUDIT_SUCCESS(4688): Microsoft-Windows-Security-Auditing: (no user): no domain: WIN-S60LUSP4202: A new process has been created.    
Subject:   Security ID:  S-1-5-21-2322774348-1821007170-2891687796-500   
Account Name:  Administrator   Account Domain:  WIN-S60LUSP4202   
Logon ID:  0x18c44    Process Information:   New Process ID:  0xb54   
New Process Name: C:\Windows\System32\conhost.exe   Token Elevation Type: %%1936   
Creator Process ID: 0x8f8   Process Command Line:     
Token Elevation Type indicates the type of token that was assigned to the 
new process in accordance with User Account Control policy.    
Type 1 is a full token with no privileges removed or groups disabled.  
A full token is only used if User Account Control is disabled or 
if the user is the built-in Administrator account or a service account.    
Type 2 is an elevated token with no privileges removed or groups disabled.  
An elevated token is used when User Account Control is enabled and 
the user chooses to start the program using Run as administrator.  An elevated token is also 
used when an application is configured to always require administrative privilege or
to always require maximum privilege, and the user is a member of the Administrators group.    
Type 3 is a limited token with administrative privileges removed and administrative groups
 disabled.  The limited token is used when User Account Control is enabled, 
the application does not require administrative privilege, and the user does not choose to start 
the program using Run as administrator.
```

Currently, we are researching the reason why each function is being used.

**Comment by daescar** [comment]
We keep making progress on the issue :
Testing with Windows Server 2012 (US Version) all it's ok when we use `el_getMessage` function.
However, testing with Windows 10 Pro (Spanish Version) we can see that the log's fields are changed and do not match with [windows-decoders.xml](https://github.com/wazuh/wazuh/blob/master/etc/decoders/0380-windows_decoders.xml).
So, this might be the reason for using this file [vista_sec.txt](https://github.com/wazuh/wazuh/blob/master/src/win32/vista_sec.txt).

Currently, we are testing if it is possible to deprecate `el_vista_getMessage` and `vista_sec.txt` and use `el_getMessage` function only, indicating inside this function the LANGID by `FormatMessage` : [here](https://github.com/wazuh/wazuh/blob/ea29f8167a4995fa1c4f9230682515869ab7732b/src/logcollector/read_win_el.c#L237)

**Comment by daescar** [comment]
Unfortunately, after several days of research and tests, we could not find a solution to this issue.
Because, by using `el_getMessage` function we were getting unformatted values for "New Process Name", "Creator Process Name" and "Process Command Line" fields (to see the next extract log). It has occurred for Windows 2010 and Windows Server 2016. Otherwise, on older Windows versions such as Windows XP, Windows Vista or Windows Seven worked fine and all values are correctly formatted. 

`2019 Jul 01 09:56:34 (DESKTOP-O3C98QH) 192.168.70.24->WinEvtLog 2019 Jul 01 11:56:31 WinEvtLog: Security: AUDIT_SUCCESS(4688): Microsoft-Windows-Security-Auditing: (no user): no domain: DESKTOP-O3C98QH: A new process has been created.    Creator Subject:   Security ID:  S-1-5-18   Account Name:  DESKTOP-O3C98QH$   Account Domain:  WORKGROUP   Logon ID:  0x3e7    Target Subject:   Security ID:  S-1-0-0   Account Name:  -   Account Domain:  -   Logon ID:  0x0    Process Information:   New Process ID:  0x1474`   **New Process Name: ??????????**   `Token Elevation Type: %%1936   Mandatory Label:  S-1-16-16384   Creator Process ID: 0x70` **Creator Process Name: ????E?????????????????)??????-???????!??????????)????)????n??4????????'**   **Process Command Line: ????0--?0???????????????e??????**    `Token Elevation Type indicates the type of token that was assigned to the new process in accordance with User Account Control policy.    Type 1 is a full token with no privileges removed or groups disabled.  A full token is only used if User Account Control is disabled or if the user is the built-in Administrator account or a service account.    Type 2 is an elevated token with no privileges removed or groups disabled.  An elevated token is used when User Account Control is enabled and the user chooses to start the program using Run as administrator.  An elevated token is also used when an application is configured to always require administrative privilege or to always require maximum privilege, and the user is a member of the Administrators group.    Type 3 is a limited token with administrative privileges removed and administrative groups disabled.  The limited token is used when User Account Control is enabled, the application does not require administrative privilege, and the user does not choose to start the program using Run as administrator.`

However, we are more clear about the next points: 
- Log field names depending on language package installed on Windows system.
- The number of fields for the same event could be different according to Windows version.
- The fields' values are independent of language package but depending on Windows version.

On the other hand, we were looking for the reason why the values mentioned above are being incorrectly formatted. At first, we inspected the array of values (`el_sstring` achieved from `readel`function after `ReadEventLog` is called) and we could check to all of them were right. 
So, we discovered that the values are being corrupted in `FormatMessage` function.

The event message is formatted according to a registry key which contains the message-schema related to the event we are processing. This schema is provided to `FormatMessage` by `hevt` argument. In this case, `adtschema.dll` file is used to parse the event 4688 as well as audit events. 

We tested different audit events (event 4688 included) in different Windows versions as we said at the beginning of this comment and we achieved a good format message. Event 4688 was the only one which returned unexpected values on newer Windows versions.
Then, it seems the `adtschema.dll` file has been updated recently and so `FormatMessage` cannot parse correctly this event.

We will continue researching a solution to get a right and full event description.

**Comment by chemamartinez** [comment]
Hi @teb1z,

After a deeper investigation trying to solve the issue, it seems the only valid option goes through maintaining the template [vista_sec.txt](https://github.com/wazuh/wazuh/blob/master/src/win32/vista_sec.txt). Adding the missing part of the Security events defined at that template.

For now, we are not able to face that task, we are working on moving all the Windows log collection to the new Eventchannel format, which apports much more information for each event, in a standard format (JSON) easier to maintain throught the time, and independent from the Windows language.

Sorry for the inconveniences, I would recommend you to adapt your rules to the new format, to take advantage of the enhancements it offers. If you need assistance with that process, don't hesitate to ask us whatever you need.

Best regards,
Chema.
