### ISSUE TITLE
Huge decrease of queue usage in Vulnerability Detection performance test

### ISSUE THREAD

**Issue by DiegoRatto** [wazuh/wazuh#27262]
| Version | Revision | Production/Development | Component | Install type | 
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  RC 1  |  Development  |  Worker  | Repository |  

## Description

During the testing of 4.10.0 - RC 1 in vulnerability detection perfomarce test in [this issue](https://github.com/wazuh/wazuh/issues/27190), comparing it with previous versions an decrease in queue usage has been detected and needs to be investigated. It has been detected in the case of high activity in the  worker 2. Here are the details.

<details><summary>4.10.0-Beta 1</summary>

![wazuh-remote_api_stats_Queue status](https://github.com/user-attachments/assets/175ee92b-c57e-4619-afa4-9917de69d70b)

</details>

<details><summary>4.10.0-RC 1</summary>

![wazuh-remote_api_stats_Queue status](https://github.com/user-attachments/assets/a6981726-03b5-40d6-913d-3872399cd6ee)

</details>

### Environment

The tests have been launched with the [CLUSTER-Workload_benchmarks_metrics](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/) pipeline, using the following environment:

| Case | Description | Workers | Indexers |  Agents | EPS  | Time |
| --- | --- | --- | --- | --- | --- | --- |
| High Activity | Simulate a large-scale environment with significant activity | 2 | 2 | 200 | 50  | 3h |

<details><summary>Build parameters</summary>

[Build 803](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/803/parameters/)

</details>

## Evidences

- [4.10.0-RC 1 Artifact](https://github.com/user-attachments/files/18071057/high.zip)

- [4.10.0-Beta 1 Artifact](https://github.com/user-attachments/files/17935910/high.zip)

## Additional information

could be related to [Huge increase of wazuh-modulesd in Vulnerability Detection performance test](https://github.com/wazuh/wazuh/issues/27260)

**Comment by sebasfalcone** [comment]
# Data

> [!NOTE]
> I've removed values that didn't change from one run to the other or that are too small compared to the other ones (more than 4 order of magnitude)

## Events processed and received

|     .     |   Release    | Events processed | Events received |
|:---------:|:------------:|-----------------:|----------------:|
|           | Beta1        | 2.397.915        | 49.235.612      |
|           | RC1          | 2.615.331        | 47.477.509      |
| Variation | RC1 - Beta1  | 217.416          | -1.758.103      |


## Events decoded

|     -     |   Release    | Decoded from vulnerability | Decoded from syscollector |
|:---------:|:------------:|---------------------------:|--------------------------:|
| -         | Beta1        | 836.441                    | 1.555.643                 |
| -         | RC1          | 985.102                    | 1.624.383                 |
| Variation | RC1 - Beta1  | 148.661                    | 68.740                    |

## Events dropped

|     -     |   Release   | Dropped from syscollector |
|:---------:|:-----------:|--------------------------:|
| -         | Beta1       | 46.819.302                |
| -         | RC1         | 44.843.837                |
| Variation | RC1 - Beta1 | −1.975.465                |

## Alerts written

|     -     |   Release   | Written alerts |
|:---------:|:-----------:|---------------:|
| -         | Beta1       |        836.499 |
| -         | RC1         |        985.160 |
| Variation | RC1 - Beta1 |        148.661 |

## Events Dropped Per Second

|     -     |  Release  | EDPS from vulnerability | EDPS from syscollector |
|:---------:|:---------:|------------------------:|-----------------------:|
| -         | Beta1     | 85.98                   | 141,78                 |
| -         | RC1       | 73.01                   | 135,79                 |
| Variation | RC1/Beta1 | -%16.31                 | -%4.31                 |

# Analysis
Overall the module improved its efficacy, dropping fewer events and decoding more

This could be explained due to the decrease in events received (1.758.103), which will reduce the modules load and make it work more relaxed.

## Conclusion
The decrease in queue usage is most probably explained by the decrease in events received. Given that the tests are not equal in the amount of events received its not possible to make a direct comparison between both

**Comment by Dwordcito** [comment]
LGTM

**Comment by DiegoRatto** [comment]
> [!IMPORTANT]
> Update:
The plot is analyzed in version 4.9.1-RC 2 and also has similar behavior to 4.10.0-Beta 1.

**4.9.1-RC 2**
![wazuh-remote_api_stats_Queue status](https://github.com/user-attachments/assets/09288326-7366-49d4-8e31-0119dfe70d00)

**4.10.0-RC 1**
![wazuh-remote_api_stats_Queue status](https://github.com/user-attachments/assets/3335ad83-e5b4-426c-afdc-9d2bfbc23efc)


**Would the same conclusion apply? Should a new analysis be done?**
