### ISSUE TITLE
Definition of Active Response in agent.conf doesn't work

### ISSUE THREAD

**Issue by rdemendoza** [wazuh/wazuh#2732]
Definition of Active Responses in agent.conf doesn't work.

How can we setup Active Responses by groups ?
Or 
How can we Exclude groups for Active Responses (aka: Dev group) ?

Thanks.
----
Wazuh 3.8.2

**Comment by Cerv1** [comment]
Hi @rdemendoza,

First of all, I apologize for the late response. 

_**Active Response**_ is extremely delicate because it can perform almost unlimited actions on the agent's side. Therefore, these responses should be considered carefully. Poor implementation of rules and responses may increase the vulnerability of the system.

Because of this, we don't support the modification of _**Active Response**_ in agent groups. The only way to change this setting is by accessing the agents and change it manually.

I hope you understand the reason for this behavior. If you have any doubt or concerns, please don't hesitate to ask here again.

Best regards,
Cerv1.
