### ISSUE TITLE
"CVE-2024-27982" and "CVE-2024-27983" are awaiting analysis but they appear as vulnerabilities

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh#27323]
| Version   | Component | 
|:--:|:--:|
|  4.10.0  |  Vulnerability  |   

## Description
Fixing the following issue: https://github.com/wazuh/wazuh-qa-automation/issues/423, it has been found that "CVE-2024-27982" and "CVE-2024-27983" are awaiting analysis but they appear as vulnerabilities in different Node.js versions, so it is needed an investigation for this behavior.
![Image](https://github.com/user-attachments/assets/9cb5d807-1588-4fd8-be35-297c6705b7a8)
![Image](https://github.com/user-attachments/assets/cf371102-e3e2-49ed-840f-495da5d52a9c)

### Current result
"CVE-2024-27982" and "CVE-2024-27983" are awaiting analysis and appear as vulnerabilities.

### Expected result
If "CVE-2024-27982" and "CVE-2024-27983" are awaiting analysis they should not appear as vulnerabilities.

### Attachments

- Link CVE-2024-27982: https://nvd.nist.gov/vuln/detail/cve-2024-27982
- Link CVE-2024-27983: https://nvd.nist.gov/vuln/detail/cve-2024-27983
- Report of the test: [Test_e2e_system_34_test_vulnerability_detector.zip](https://github.com/user-attachments/files/18162952/Test_e2e_system_34_test_vulnerability_detector.zip)

**Comment by sebasfalcone** [comment]
## Justification
Those CVEs were sanitized at the time due to a [user reporting it](https://github.com/wazuh/wazuh/issues/25642)

Here is the full CVEv5 content for each CVE:
- [CVE-2024-27983.json](https://github.com/user-attachments/files/18165570/CVE-2024-27983.json)
- [CVE-2024-27982.json](https://github.com/user-attachments/files/18165571/CVE-2024-27982.json)
