### ISSUE TITLE
SonicWall decoder fails to parse messages from firewall when unexpected whitespaces are present and/or UTC timestamps are used.

### ISSUE THREAD

**Issue by DarkMatterCore** [wazuh/wazuh#2757]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| Any | Manager | Any | Linux (Any) |

User Giorgio Biondi [reported this issue on the mailing list](https://groups.google.com/forum/#!topic/wazuh/fz45-vu_LF0). Apparently, some SonicWall firewall models introduce additional whitespace characters at unexpected positions and/or use UTC timestamps, which in turn makes the Sonicwall decoder in Wazuh fail because the message string doesn't match the expected regular expression in the `<prematch>` field.

An expected raw message string (in this case, from a SonicWall NSA3500BR with SonicOS 5.9) looks like this:

```
id=NSA3500BR sn=0017C5DFCEEC time="2019-02-28 15:34:01 UTC" fw=172.29.169.2 pri=1 c=32 m=30 msg="Administrator login denied due to bad credentials" sess="Web" n=9 usr="admin" src=10.12.20.208:64789:X0 dst=10.12.14.2:444:X0 proto=tcp/444
```

However, SonicWall NSA3600 with SonicOS 6.5 returns a message string like this one:

```
  id=NSA3600  sn=C0EAE4599E78 time="2019-02-28 15:41:11 UTC" fw=2.228.169.242 pri=1 c=32 m=30 msg="Administrator login denied due to bad credentials" sess="Web" dur=0 n=18 usr="admin" src=10.12.20.208:64860:X0-V514 dst=10.12.20.1:444:X0-V514 proto=tcp/444 note="admin"
```
Removing the additional whitespaces fixed the problem when performing some manual tests with `ossec-logtest`. Furthermore, Giorgio Biondi was able to tweak the SonicWall decoder in order to make it compatible with such messages, by changing this:

```
<decoder name="sonicwall">
  <type>firewall</type>
  <prematch>^id=\w+ sn=\w+ time="\.+" fw=\S+ </ prematch>
  <plugin_decoder>SonicWall_Decoder</plugin_decoder>
</decoder>
```

Into this:

```
<decoder name="sonicwall">
  <type>firewall</type>
  <prematch>\s*id=\w+ sn=\w+ time="\.+" fw=\S+ </ prematch>
  <plugin_decoder>SonicWall_Decoder</plugin_decoder>
</decoder>
```

**Comment by Hardcore-fs** [comment]
This  patch still has not been applied to the latest version.
As new users,  We wasted nearly 4 hours on trying to get sonicwall working with Wazuh,
so this has been   outstanding for over 1 year.

Also there is a major problem, that if you have more than one sonicwall, you cannot easily tell the difference.
the  decoder needs the following added into it to allow serial number & ID to be accessed.
ESP if both are talking at the same time......

`
 /var/ossec/ruleset/decoders/0295-sonicwall_decoders.xml
<decoder name="sonicwall-fields">
  <parent>sonicwall</parent>
 <regex>^\s*id=(\S+)\s+sn=(\S+)</regex>
 <order>dev_id, dev_sn</order>
</decod

`
The UTC is not a firewall issue, it is due to user settings... 
That change the string settings are under:

Appliance->System time

* Display UTC in logs (instead of local time)
* Display date in International format

so much of the filter can only catch specific lines that have been extracted from different firewalls, potentially  based on user settings of that firewall..

**Comment by Nicogp** [comment]
Hi @Hardcore-fs,
First of all, sorry for the late response  and the inconvenience caused.
Thank you very much for your feedback, we will evaluate the case of multiple firewalls to capture the id and serial number.
Regarding the initial issue, it is currently under review. We have fixed it in [https://github.com/wazuh/wazuh-ruleset/pull/503](url) and will merge it as soon as possible.
Regards,
Pedro Nicolas.

**Comment by Hardcore-fs** [comment]
no problem......
could it not be possible, to add some sort of "git" front end  gui to the wazuh, so that  the users can "merge" in extra rules /changes into an already existing rule set.
so basically the base set gets written/ changed, then on the users system  a merge takes place, with users changes, to produce a final rule/filter.
If there is a conflict the user can stash  the system updated rule , the same way GIT functions, instead of playing "hide the rule" & override the trigger...
I then completely negates having to wait  2 years for rulesets to be corrected & re-merged...
Users can then  provide a "diff" as a sort of shopping list for other users, for a particular rule set
