### ISSUE TITLE
Make ossec-logtest support for implicit decoders

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2765]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0 | Manager | Packages/Sources | Linux |

`ossec-logtest` is a very useful tool to test decoders and rules manually. It allows to input an event and it is processed throught the analysis engine to check if matches with a specific decoder and rule inside the Wazuh ruleset.

However, Wazuh contain decoders written in C instead of XML for specific types of events, such as Eventchannel or FIM events. Currently, `ossec-logtest` is not compatible with those decoders and it is not possible to use it for testing Windows or inventory events.

This issue consists in extend the `ossec-logtest` support for those implicit decoders.

**Comment by branchnetconsulting** [comment]
This is very important and I'm glad to see an issue for it.  We really need the ability to feed examples of any kind of log that ossec-logcollector can collect, into ossec-logtest for testing.  Custom rule development is so much easier when ossec-logtest can be used.  

We also need to be able to optionally specify a hostname value when invoking ossec-logtest so that we can test rules that use <hostname> criteria with log samples that don't explicitly mention the hostname.   Analysisd knows the hostname in such cases because it knows the name of the agent from which the log arrived.  Ossec-logtest needs the ability to be informed manually, probably with some kind of parameter, like this:

echo "log sample with no hostname in it" | ossec-logtest -n server7

Kevin

**Comment by cristgl** [comment]
Some information about the decoder flow:

The `OS_GetFirstOSDecoder` module is in charge of obtaining the ruleset's decoders, which have been unified into a decoders structure built by `ReadDecodeXML`. This module calls `OS_AddDecoder`, its goal is adding the XML decoders one by one, classifying them into two structures, one with names and the other without them. Once the decoders, lists and rules are loaded by `ReadDecodeXML`, the `DecodeEvent` module is called. This one's goal is to find the matching decoder for the log entered at `ossec-logtest`.

The proposal is to build a new function to add the internal decoders in the same two structures from above, find out from which program the event comes and convert it to the same format as it should be sent to the specific decoder. For example, for eventchannel the format log would be a JSON, with the event message and the event itself, inside an XML; for syscheck it would consist of a string with different values separated by ':'. This way the event would be broken down by its specific decoder and then the rule matching process will trigger alerts.

**Comment by crolopez** [comment]
The `ignore` tag for the contextual rules is not being taken into account in `ossec-logtest` executions. 

More information: https://github.com/wazuh/wazuh/pull/3810#pullrequestreview-294368886

**Comment by Lopuiz** [comment]
**This issue is divided in the following tasks:**
- [ ] Allows Logtest decodes SCA events
- [ ] Allows Logtest decodes Eventchannel events
- [ ] Allows Logtest decodes Syscheck events
- [ ] Allows Logtest decodes Syscollector events
- [ ] Allows Logtest decodes Ciscat events
- [ ] Allows Logtest decodes Rootcheck events

Allows Logtest decodes Logcollector events when they are processed by:
- [ ] `read_nmapg` function
- [ ] `read_postgresql_log` function
- [ ] `read_mysql` function
- [ ] `read_multiline` function
- [ ] `read_audit` function
- [ ] `read_snortfull` function
- [ ] `read_mssql_log` function
- [ ] `read_djbmultilog` function
- [ ] `read_command` function
- [ ] `read_fullcommand` function
- [ ] `read_ucs2_le` function
- [ ] `read_ucs2_be` function

**Comment by Zer0Risk** [comment]
> This is very important and I'm glad to see an issue for it. We really need the ability to feed examples of any kind of log that ossec-logcollector can collect, into ossec-logtest for testing. Custom rule development is so much easier when ossec-logtest can be used.
> 
> We also need to be able to optionally specify a hostname value when invoking ossec-logtest so that we can test rules that use criteria with log samples that don't explicitly mention the hostname. Analysisd knows the hostname in such cases because it knows the name of the agent from which the log arrived. Ossec-logtest needs the ability to be informed manually, probably with some kind of parameter, like this:
> 
> echo "log sample with no hostname in it" | ossec-logtest -n server7
> 
> Kevin

As Kevin mentioned at the start of this issue, this is a very important feature, which is essential for building/testing custom rules for specific Logformats (for Example: Windows Eventchannel).
Without this, building custom rules or decoders is very "guessy" and cumbersome.

If there is another way to test such rules please let me know, but as I currently see it this would be the only way.

Julian

**Comment by branchnetconsulting** [comment]
Until Wazuh fundamentally resolves these limitations, which I expect to see in Wazuh version 5, my current way of log-testing Windows event samples is documented in the article I wrote here:
https://docs.google.com/document/d/1nVRB-mmX7zJx1zzPZIlthiIaRTKaLpxesg_0Vna8aoE

**Comment by Zer0Risk** [comment]
> Until Wazuh fundamentally resolves these limitations, which I expect to see in Wazuh version 5, my current way of log-testing Windows event samples is documented in the article I wrote here: https://docs.google.com/document/d/1nVRB-mmX7zJx1zzPZIlthiIaRTKaLpxesg_0Vna8aoE

Thank you very much for your workaround. 👍
