### ISSUE TITLE
Service fails if manager address specified by hostname is not initally reachable

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh#2770]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
|  All | Agent | Packages & Sources | tested on Windows and Linux |

If the `<address>` in  `<ossec_config><client><server>` of an agent's `ossec.conf` is specified using a hostname instead of an IP, and the Internet is temporarily unavailable when the service is started (or restarted) the service will fail giving the error:
`ERROR: (4104): Invalid hostname: '<managerhostname>.com'`

This is caused by the way this section of the code works: 
https://github.com/wazuh/wazuh/blob/3.8/src/os_net/os_net.c#L487-L515

This may lead to agents becoming unreachable if they don't have Internet during a system reboot (like after a power outage).

It should continue to try to reach the manager the same way it does if an IP is specified, while giving an error in `ossec.log`.

**Comment by DarkMatterCore** [comment]
Hi there. Thanks for reporting this issue.

Looking at the code flow behind this problem, I don't think it is a good idea to keep running `OS_GetHost()` using an infinite loop in this case, due to its dependance on `gethostbyname()`. This function doesn't provide proper error checking so, a lot of problems can be represented using the same error codes (which makes it hard to identify the real source).

What could actually be done, though, is checking if an actual Internet connection is available before calling `OS_GetHost()`, using an infinite loop. I'm working on a possible solution at this moment.

**Comment by DarkMatterCore** [comment]
@jctello A draft PR has been submitted, which includes the functionality described in my previous comment. I would greatly appreciate it if you could check it out!

**Comment by jctello** [comment]
Hello @DarkMatterCore, this is an interesting solution. And I'm not familiar with this method of network diagnosis so if approved someone else should review it as well, but I think it may not be enough because:

 - If it checks for local network connection (and not the WWW) it may still fail once the LAN is operational but before the WAN is available.
 - And if it attempts to verify the WWW it will get stuck waiting for Internet access if it is a LAN without external access that uses an internal DNS.

I understand the benefit of doing verification of hostnames to detect typos. However it may lead to these failures while failing to catch typos that may occur when using an IP. 

There is already a warning message (4101) in place when the agent is "Waiting for server reply" which should be enough to determine that there's a connectivity issue and the user may see if the hostname expressed there makes sense.

**Comment by DarkMatterCore** [comment]
@jctello Thanks for your input on this matter. It is greatly appreciated.

The verification method proposed on the draft PR consists on looking at the OS routing table for the default destination route (`0.0.0 0`). If it is available and belongs to an active network interface (by looking at its flags), the program will get out of the infinite loop. There are other ways to check for an active Internet connection, like `ping`ing a specific external resource, but after studying them, I ended up choosing this one. It is less obstructive.

The problem with `gethostbyname()` is that, even though it is used to translate domain names to IP addresses through DNS resolution queries, it doesn't provide proper error checking, so using its output to determine if we should keep trying because an Internet connection is unavailable is simply not possible. `OS_GetHost()` hasn't been modified at all in the draft PR because of these facts.

If the provided hostname is invalid, `gethostbyname()` should fail after the hardcoded 5 attempts have been performed (by calling `OS_GetHost()`), but after the connectivity check is finished. Basically just like it did before, assuming that an Internet connection was available.

The only thing that could represent a real problem for this method is if an external DNS is used and the ISP is also down/restarting. It is **very** uncommon, though, but it could indeed occur.

Checking if an internal DNS is being could prove to be difficult, specially if DNS queries are being forwarded to the default gateway instead of being sent directly to the DNS server. I'll look into this matter.

**Comment by gjahchan** [comment]
Would caching the last known good fqdn / server_IP_address pair (or just the last known good server IP address) help with the issue?

The cached values could potentially be maintained in the hosts file.

If for any reason the server's fqdn cannot be resolved (DNS down or connectivity lost), try the cached IP address. If it is a connectivity issue, log server unreachable events while continuing to try resolving every few seconds. If DNS in unreachable but connectivity to server is OK, temporarily use the last known good IP address until the server's fqdn can be resolved in DNS.

**Comment by jctello** [comment]
> If the provided hostname is invalid, `gethostbyname()` should fail after the hardcoded 5 attempts have been performed (by calling `OS_GetHost()`), but after the connectivity check is finished. Basically just like it did before, assuming that an Internet connection was available.

Sorry if I'm failing to see something obvious here, but:
Why does it have to fail when hostname is provided and not when a mistyped IPv4 is?.

The way at see it, upon initial configuration agent connection success is more likely to be verified by the person installing Wazuh.
However the agents will then have a lifetime of many unattended startups and we can't assume they will be accessible by administrators so their logic shouldn't be the source of failure due to a temporary issue.

I like the `OS_CheckInternetConnection` very much as a new feature for logging. Although to be more precise I'd change the warning message to "No network connection established". And I would trigger it for logging after reaching the manager (not only on startup, and also when using IPv4).

**Comment by DarkMatterCore** [comment]
First of all, let me thank you for all your input on this matter. It is greatly appreciated!
____________________________________________

@gjahchan That's a good approach to this problem that could also be used alongside the connection check. Thanks! I'll look into it.

@jctello Because `OS_IsValidIP()` is used to determine if the `<server><address>` field in `ossec.conf` contains a valid IP address. If it fails, the program assumes that a hostname was provided instead, thus calling `gethostbyname()` using this value. That's how the code flow goes.

A mistyped IPv4 address such as `192..168.0.1` will make `gethostbyname()` fail, because a valid hostname cannot begin with a dot, nor contain two dots following each other. Similarly, an address like `172.16.257.1` is invalid, and won't be recognized as a valid hostname either (it won't resolve to any kind of resource).

`OS_CheckInternetConnection()` could very well be used in other cases in which hostname resolution or access to an external resource is needed. I strongly agree on that. However, it would be best to open an additional issue on that matter after this one is closed.

I believe that mixing `OS_CheckInternetConnection()` with the FQDN/IP pair caching solution proposed by @gjahchan would be alright, unless I'm missing something else. Any additional opinions are fully welcome.

**Comment by vikman90** [comment]
Hi all,

The problem here is that some daemons, like Agentd, perform _chroot_ jailing. The agent first tries to resolve the hostname during the settings parsing ([client-config.c](https://github.com/wazuh/wazuh/blob/v3.8.2/src/config/client-config.c#L80)). Then, it performs _chroot_ ([agentd.c](https://github.com/wazuh/wazuh/blob/v3.8.2/src/client-agent/agentd.c#L48-L52)), and this makes Agentd unable to resolve hostnames.

Finally, the daemon tries to resolve the hostname on each connection attempt ([start-agent.c](https://github.com/wazuh/wazuh/blob/v3.8.2/src/client-agent/start_agent.c#L55)), in vain.

My proposal is to develop a new module capable of resolving hostnames. In fact, Modulesd won't perform _chroot_ jailing. Agentd and any daemon that runs in _chroot_ shall query for hostname resolution to this module.

What do you think?
Best.

**Comment by jctello** [comment]
The benefit of having this check every time the service starts is minimal (it will only help you debug configuration upon first connection, afterwards it's redundant).

While the downside is persistent, during the lifetime of an agent it lingers, providing no further benefit while risking being the cause of disconnection of the agent.

A simple warning would help debug initial configuration. An stopping error here is a bad idea.

**Comment by vikman90** [comment]
Hi, 

We should commit three changes here:
1. Remove the _chroot_ operation from the agent so it will be able to reload the hostnames.
2. Let the agent keep running even if it could not resolve a hostname.
3. Make Wazuh run after the network service (#1106)

**Comment by vikman90** [comment]
We still need to allow Agentd refresh the hostname in runtime.

## Next step

We should remove _chroot_ as explained above.

**Comment by vikman90** [comment]
Hi @jctello,

This problem has been fixed at #4241. Thanks to @Molter73 and @Lopuiz for developing this solution!

I'll close this issue.
Cheers!
