### ISSUE TITLE
Pattern Handler (getPatternList). Server did not respond

### ISSUE THREAD

**Issue by xisafe** [wazuh/wazuh#2908]
![image](https://user-images.githubusercontent.com/29724312/54981336-01548e80-4fe3-11e9-827d-70fe14ce3e2e.png)

Pattern Handler (getPatternList). Server did not respond

A new notification appears
Agents Preview. Server did not respond

A new notification appears
Directives - Menu. Cannot read property 'filter' of undefined

wazuh 3.7.1

centos 7

**Comment by jesusgn90** [comment]
Hi @xisafe, 

Sorry for the late response. I'm going to close this ticket because Wazuh is currently on 3.9.0 and there are a lot of changes since 3.7.1.

In any case, if you are still in 3.7.1 and you still have the problem, re-open this ticket and we will be glad to help you with any kind of issue you are facing.

Best regards,
Jesús
