### ISSUE TITLE
alerts.json should be compressed when is rotated by rotate_interval setting

### ISSUE THREAD

**Issue by toniMR** [wazuh/wazuh#2919]
Hello team,
In wazuh manager, when **rotate_interval** is set in **/var/ossec/etc/ossec.conf**:
```
<global>
  <rotate_interval>30m</rotate_interval>
</global>
```
In **/var/ossec/logs/alerts/Year/Month/**, I get an alerts.json file every 30 min but these alerts aren’t compressed until 00:01.
rotate_interval should create the alerts.json files and compress them at the same time.

**Comment by antoniojpascualv** [comment]
Hello team,

I am going to write an update on this issue for the latest version.

In wazuh manager, when rotate_interval is set in `/var/ossec/etc/ossec.conf`:

```
<global>
  <rotate_interval>10m</rotate_interval>
</global>
```
In version 4.0 in `/var/ossec/logs/alerts/Year/Month/`, the only compressed files at 00:01 are the last file, in which the manager was injecting the alerts, but the previous files that were rotated do not get compressed and stay that way.

![image](https://user-images.githubusercontent.com/22274721/100481957-1e196180-30f6-11eb-8424-c0a437b9b0e6.png)

**Comment by vikman90** [comment]
Closing this issue as it will be superseded by version 5.0.

**Comment by richierg** [comment]
@vikman90 , can't this issue be reopen ? Wazuh 5.0 still hasn't been released.

**Comment by vikman90** [comment]
Hi @richierg,

This issue is part of the epic:
- #3072 

Which collects several enhancements related to log rotation. After internal discussions, we decided not to address these problems in the current version. Instead, future versions will introduce a new design to allow log rotation to be managed through standard system tools such as `logrotate`.

For this reason, the issue remains closed and will not be fixed in the current release line.

Best regards.
