### ISSUE TITLE
Wazuh cluster not creating client.keys if removed

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh#2984]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.8.2-1 | Manager (Worker) | Packages | - |

Hi team,

I had an issue on Wazuh cluster when the `client.keys` accidentally gets removed from a Worker node, the cluster is not able to Synchronize the file unless it exists with the proper permissions.

Expected behaviour: Wazuh cluster creates the clients.keys file during Synchronization.

Real behaviour: Wazuh cluster detects the file as 'Missing' but doesn't creates it (No error logs)

Solution:
```
touch /var/ossec/etc/client.keys
chmod 660 /var/ossec/etc/client.keys
chown root:ossec /var/ossec/etc/client.keys
```

After that the cluster is able to synchronize the file.

Steps to reproduce:
Wazuh cluster configured and running, then rename or remove client.keys from the worker.

**Comment by mgmacias95** [comment]
I have just checked and this bug has been fixed with the Cluster reimplementation in asyncio. When removing the client.keys the following message is shown in the worker at synchronization time:
```
2019/04/01 12:18:15 wazuh-clusterd: INFO: [Worker worker-1] [Integrity] Analyzing received files: Missing: 1. Shared: 0. Extra: 0. ExtraValid: 0
2019/04/01 12:18:15 wazuh-clusterd: INFO: [Worker worker-1] [Integrity] Worker does not meet integrity checks. Actions required.
2019/04/01 12:18:15 wazuh-clusterd: INFO: [Worker worker-1] [Integrity] Updating files: Start.
2019/04/01 12:18:15 wazuh-clusterd: DEBUG: [Worker worker-1] [Integrity] Received 1 missing files to update from master.
2019/04/01 12:18:15 wazuh-clusterd: DEBUG2: [Worker worker-1] [Integrity] Processing file /etc/client.keys
2019/04/01 12:18:15 wazuh-clusterd: WARNING: [Worker worker-1] [Integrity] Could not parse client.keys file: [Errno 2] No such file or directory: '/var/ossec/etc/client.keys
```
The warning message comes from the following function:
https://github.com/wazuh/wazuh/blob/6aeafe6b5530c2de66e0893eb811fbd1b9b9ada1/framework/wazuh/cluster/worker.py#L267-L298
When a worker receives a client.keys file it checks which agents have been removed comparing the received client.keys file with its local one. If the client.keys doesn't exist the warning will be shown but the new client.keys will be created:
```shellsession
root@worker-1:/home/vagrant# rm /var/ossec/etc/client.keys
root@worker-1:/home/vagrant# ls /var/ossec/etc/
decoders               lists                        localtime        ossec.conf  rules   sslmanager.cert
internal_options.conf  local_internal_options.conf  ossec-init.conf  rootcheck   shared  sslmanager.key
root@worker-1:/home/vagrant# ls /var/ossec/etc/
client.keys  internal_options.conf  local_internal_options.conf  ossec-init.conf  rootcheck  shared           sslmanager.key
decoders     lists                  localtime                    ossec.conf       rules      sslmanager.cert
```
