### ISSUE TITLE
What does "ERROR: Unable to bind to socket '/queue/ossec/control': (111) Connection refused." mean?

### ISSUE THREAD

**Issue by cheney223** [wazuh/wazuh#3156]
When I manually kill the wazuh-modulesd on a agent, I cannot find any log suggesting this in /var/ossec/logs/ossec.log while killing other agent's processes giving "INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...". However, I found  "ERROR: Unable to bind to socket '/queue/ossec/control': (111) Connection refused." shows each per 10 seconds in /var/ossec/logs/ossec.log after killing wazuh-modulesd. Does it mean anything?

**Comment by DaveVG1** [comment]
Hi Cheney,

This `ERROR: Unable to bind to socket '/queue/ossec/control': (111) Connection refused.` message is a consequence of `wazuh-modulesd` process being killed. The Wazuh agent will still work, but the keep-alive message will be sent without the IP.

I think we should consider if this message should be displayed as an error as it may flood the ossec log of the agent. On the other hand, this could be caused by an actual error (not because `wazuh-modules` being killed but the socket being deleted for some other reason).

Anyway, I think you're right and we should log the same message that we use for other processes when `wazuh-modulesd` is killed.  I'll keep you informed if we take any action on this matter. Thank you for reporting this.

Kind regards.

**Comment by cheney223** [comment]
> Hi Cheney,
> 
> This `ERROR: Unable to bind to socket '/queue/ossec/control': (111) Connection refused.` message is a consequence of `wazuh-modulesd` process being killed. The Wazuh agent will still work, but the keep-alive message will be sent without the IP.
> 
> I think we should consider if this message should be displayed as an error as it may flood the ossec log of the agent. On the other hand, this could be caused by an actual error (not because `wazuh-modules` being killed but the socket being deleted for some other reason).
> 
> Anyway, I think you're right and we should log the same message that we use for other processes when `wazuh-modulesd` is killed. I'll keep you informed if we take any action on this matter. Thank you for reporting this.
> 
> Kind regards.

Thank you!

**Comment by vikman90** [comment]
Hi @cheney223,

As @DaveVG1 proposed, we have changed the log description to be more friendly. In addition, we changed it from _ERROR_ to _DEBUG_, in order to prevent it from flooding the log.

Hope this helps you.
Best regards.
