### ISSUE TITLE
Emailing alerts with no full log

### ISSUE THREAD

**Issue by elwali10** [wazuh/wazuh#3163]
Currently a giving rule that has a level allowing to it be emailed for instance : 

```
 <rule id="501" level="12" overwrite="yes">
    <if_sid>500</if_sid>
    <if_fts />
    <match>Agent started</match>
    <description>New Wazuh agent connected.</description>
     <options>no_full_log</options>
    <group>pci_dss_10.6.1,gpg13_10.1,gdpr_IV_35.7.d,</group>
</rule>
```

The alerts are being emailed with the full log regardless the **no_full_log** options used.

**Comment by DaveVG1** [comment]
Summary
---
I've been looking for the error and I've come to the following conclusion this:

- If the option `email_log_source` is set to `alerts.log` we will always show the **full_log** in the alert and it'll be sent with it by email. `full_log` can only be discarded for `alerts.json`.
- If the option `email_log_source` is set to `alerts.json` the alert will be shown without the `full_log` field. However, the email won't be sent, because of this:
https://github.com/wazuh/wazuh/blob/013bf64218540e965729547bcdb8426735d64cbb/src/os_maild/os_maild_client.c#L390
We are always reading the `full_log` field from `alerts.json`; if the field doesn't exist (it returns `NULL`) we don't send the email. This is clearly a bug. I'm working on it.

**Comment by chemamartinez** [comment]
Closing it in favor of #3762. It treats the same issue and the fix will be available in the next released version.

Regards.
