### ISSUE TITLE
Path problems with 3.0.0

### ISSUE THREAD

**Issue by avinchakov** [wazuh/wazuh#319]
Ubuntu 16.04.03 Xenial. 
Hello, after upgrading wazuh-manager to 3.0.0 I get problem:
1) I have falco installed and I get:
`Error File below /etc opened for writing (user=<NA> command=ossec-remoted  file=/etc/shared/default/merged.mg.tmp)
`
It seems that the problem with path var. Wazuh installed into /var/ossec/. it must be /var/ossec/etc/shared/default/merged.mg.tmp, not /etc/shared/default/merged.mg.tmp

**Comment by vikman90** [comment]
Hi @avinchakov,

The call system refers `/etc` instead of `/var/ossec/etc` because the process `ossec-remoted` (like some others) makes _chroot_ in _/var/ossec_ for security reasons.

The file `merged.mg.tmp` is created temporarily and the is moved into `merged.mg`. Could you kindly check the file `/var/ossec/etc/shared/default/merged.mg`? If it's updated, the manager is working properly.

Thank you for feedback.
Best regards.

**Comment by avinchakov** [comment]
shared/default: -rw-r----- 1 ossecr ossec 251011 Dec 19 09:48 merged.mg
shared: -rw-r----- 1 ossecr ossec 251243 Dec 19 07:08 merged.mg

How to understand?

**Comment by vikman90** [comment]
Wazuh 3.0 introduces agent grouping, that is, you can create groups with different configuration sets, and add your agents to one of these groups. The default group (if you haven't assigned your agents) is `default`.

In other words, the files that were in `/var/ossec/etc/shared` before upgrading should now be in `/var/ossec/etc/shared/default`. So the file `/var/ossec/etc/shared/merged.mg` became useless.

Best regards.

**Comment by avinchakov** [comment]
Thank you. 
Apparently I need to adjust this alert in falco...
