### ISSUE TITLE
Why I don’t see alerts in the Wazuh app

### ISSUE THREAD

**Issue by cheney223** [wazuh/wazuh#3191]
I have deployed a single-host wazuh server and the status of Logstash, elasticsearch, wazuh-manager, wazuh-api seem to be all active(running). However, when i check 'lsof /var/ossec/logs/alerts/alerts.json' as the troubleshooting says, there is only ossec-analysisd reading the alerts.json. Where is the JAVA and how can I fix this issue?

**Comment by TJOSERAFAEL** [comment]
Hi @cheney223 ,

you need to install `Filebeat` in order to forward the messages from `/var/ossec/logs/alerts/alerts.json` to  `Logstash`. https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/wazuh_server_deb.html#installing-filebeat

Check the file `/etc/filebeat/filebeat.yml` to point `/var/ossec/logs/alerts/alerts.json`.

After this, you can dump the port 5000 running the followin command:

- `# tcpdump -i eth0 'port 5000' ` 

To see if Filebeat and Logstash connect correctly.

We also have a troubleshooting guide https://documentation.wazuh.com/3.x/user-manual/kibana-app/troubleshooting.html

Best regards.
