### ISSUE TITLE
[Vuln-Detector] Getting plenty of 'The package name could not be obtained' error logs

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh#3229]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0-3918 | Manager| Packages| Amazon Linux |

I'm obtaining a huge amount of `ERROR` logs:

![image](https://user-images.githubusercontent.com/10210567/57129006-86c31f80-6d95-11e9-9e27-e5b208a48566.png)

My wodle configuration:

```
<wodle name="vulnerability-detector">
        <disabled>no</disabled>
        <interval>12m</interval>
        <ignore_time>6h</ignore_time>
        <run_on_start>yes</run_on_start>
        <feed name="ubuntu-18">
            <disabled>no</disabled>
            <update_interval>1h</update_interval>
        </feed>
        <feed name="redhat">
            <disabled>no</disabled>
            <update_from_year>2010</update_from_year>
            <update_interval>1h</update_interval>
        </feed>
        <feed name="debian-9">
            <disabled>no</disabled>
            <update_interval>1h</update_interval>
        </feed>
    </wodle>
```

Thanks

**Comment by crolopez** [comment]
This bug is due to a change in the definition of vulnerabilities made by Canonical, which we have not contemplated. It affects **all versions of Vulnerability Detector**. 

An online update cannot be performed on Ubuntu Xenial and Canonical feeds. It is possible to update these feeds offline from files that content the old syntax.

At the moment, the Ubuntu Trusty and Precise feeds have not changed this syntax, so they are not affected.

It needs to be fixed ASAP.

**Comment by albertomn86** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/3245
