### ISSUE TITLE
Cannot add plugin to kibana with wazuh version 

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh#323]
i tried to install wazuh using this 

`/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip`

but i alwasy got this error

Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [wazuh]. Expected [6.1.1]; found [6.1.0]"

can you give me a package to support for wazuh version?

**Comment by gagantous** [comment]
there is no 6.1.1 version yet ?

**Comment by JuanjiJG** [comment]
Hi @gagantous,

The Elastic team just released Elasticsearch 6.1.1, and the Wazuh team is working to get an updated version of the app compatible with that.

We'll let you know when it's available.

If you go to the documentation, you can install the 6.1.0 version of the stack, wich is our latest and functional version: https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/index.html

If you have more questions or issues about anything, feel free to ask us.
Thank you for your patience!

Best regards,
Juanjo

**Comment by gagantous** [comment]
Okay thanks for the replies, hope the update would released soon (y)

**Comment by JuanjiJG** [comment]
Hi again @gagantous 

We've just released our new version of the Wazuh App, with full compatibility with the Elastic Stack 6.1.1. You can go to our [documentation](https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/index.html) and follow the steps in order to proceed to install it.

Let me know if you still have some questions, problems or doubts about anything. If it's something related to our app, you can open a new issue on our [specific repository](https://github.com/wazuh/wazuh-kibana-app/issues) in order to have a better follow-up of your problem.

Best regards,
Juanjo
