### ISSUE TITLE
What is the function of the python code in Wazuh?

### ISSUE THREAD

**Issue by cheney223** [wazuh/wazuh#3239]
Can anyone give me a summary of the function of the python code in Wazuh?

**Comment by crd1985** [comment]
Hi @cheney223,

there are several features that Python code implements in the manager:
- Cluster of managers (including distributing API requests)
- Abstraction layer to be used by Wazuh restful API (framework)
- Integration with AWS, Azure, Docker
- Other utils in framework/scripts

Please, use our [Slack channel](https://wazuh.com/community/join-us-on-slack/) or our [Wazuh mailing list](https://groups.google.com/forum/#!forum/wazuh) for questions better. 

I am closing this issue since it is not either a bug report or a new feature request.

Regards,
Dani
