### ISSUE TITLE
Vulnerability detector problems

### ISSUE THREAD

**Issue by avinchakov** [wazuh/wazuh#3251]
1) I have many such errors in manager's logs:
`wazuh-modulesd:vulnerability-detector: ERROR: (5404): The package name could not be obtained.`

2) Sometimes I see such logs:
`ossec-analysisd: WARNING: Syscollector decoder queue is full.`

3) About week ago I stopped having events from syscollector
![image](https://user-images.githubusercontent.com/13016561/57272774-81741680-70ae-11e9-8a06-9b84b58aab7b.png)

My config:
```
    <wodle name="syscollector">
      <disabled>no</disabled>
      <interval>24h</interval>
      <scan_on_start>no</scan_on_start>
      <hardware>yes</hardware>
      <os>yes</os>
      <network>yes</network>
      <packages>yes</packages>
      <ports all="no">yes</ports>
      <processes>yes</processes>
    </wodle>
    <client_buffer>
        <!-- Agent buffer options -->
        <disable>yes</disable>
	<length>10000</length>
	<events_per_second>1000</events_per_second>
    </client_buffer>
```

|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0-1  | Manager/Agent | DEB | Ubuntu 16 |

**Comment by sergiospa** [comment]
Hi avinchakov,

1. This is a new known bug due to a change in the definition of vulnerabilities made by Canonical. You may be interested in digging deeper into this by visiting this issue → https://github.com/wazuh/wazuh/issues/3229#L1609

2. That means, as you can see, that syscollector decoder queue is full. There must be too many syscollector events, or too many agents reported at the same time, and your queue size doesn't give you enough.  That size can be amplified by adding a new line like the following in `/var/ossec/etc/local_internal_options.conf` configuration file:
`analysisd.decode_event_queue_size=16384`

You can find further information in https://documentation.wazuh.com/current/user-manual/reference/internal-options.html?highlight=analysisd%20decode_syscollector_queue_size#analysisd.

Please, let me know if the problem persists.

Best regards,
Sergio.

**Comment by avinchakov** [comment]
Thank you. I will check #3229
