### ISSUE TITLE
Manager restart doesn't work on Docker

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#3273]
Hello team,

I've noticed the manager restart request doesn't work, but the `api.log` doesn't show any error:

`WazuhAPI 2019-05-07 13:28:04 foo: [::ffff:172.18.0.5] PUT /manager/restart - 200 - error: '0'.`

Regards.

**Comment by crd1985** [comment]
Hi team,

the fix we are proposing will address two things:
- Fix script `restart.sh` to detect if `systemctl` command will fail. This can be achieved easily by changing this line: https://github.com/wazuh/wazuh/blob/69729679efce4aed0029ae37f80610aef574f5e8/active-response/restart.sh#L45
- Improve the message returned by the API call to tell the user the restart command have been sent, but we can't say if it's done properly or not.

Consider we can't turn restart endpoint into a synchronous call due to its complex implications (undetermined time response, timeouts, errors and so on). We already provided another endpoint to let the app actively query the real status of the restarting process.

Regards
