### ISSUE TITLE
"Starting/Ending syscheck scan" alert message no longer generated 

### ISSUE THREAD

**Issue by arshad01** [wazuh/wazuh#3371]
|Wazuh version|Component|Install type|Install method|Platform|
|-----|-----|-----|-----|-----|
|3.9.0|syscheck|local|Source build|CentOS 6.7|

Hello,
In earlier versions of Wazuh OSSEC (ca. 2.x), the syscheckd would generate alert messages when it started building the db or finished it. I used to get these alerts by raising the alert level of rule 515. In the latest version (3.9.0), I no longer see these alerts getting generated. I do see Rootkit Start/End alerts though. Any idea, how to enable Syscheck alerts?

Thanks
Arshad

**Comment by arshad01** [comment]
The local_rules.xml that I am using is follows:
```
<group name="local,syslog,ossec,syscheck,rootcheck,">
  <rule id="100057" level="5">
    <if_sid>515</if_sid>
    <description>Syscheck/Roocheck scan start/stop event</description>
  </rule>
</group>
```

**Comment by arshad01** [comment]
From the syscheck code, I see that it no longer generate scan message of the form 'Starting syscheck scan' or 'Ending syscheck scan'. Now the messages are of form 'fim-db-start-first-scan', 'fim-db-end-first-scan', 'fim-db-start-scan' and 'fim-db-end-scan'. Are these messages treated in any specific way by analysisd?

**Comment by bah07** [comment]
Hi @arshad01 

That alert was not intended for that functionality, but rather to store the start and end of each module scan. They have been removed because it is now stored directly in a database.
You can check the date of the last scan from the next API call's:
Syscheck:
https://documentation.wazuh.com/current/user-manual/api/reference.html#get-last-syscheck-scan
Rootcheck:
https://documentation.wazuh.com/current/user-manual/api/reference.html#get-last-rootcheck-scan
If necessary we can add this functionality, but to maintain a standard all modules should operate in the same way.
What case of use do you have? We can try to find another solution that is not getting the alert as you do so far.

Regards.

**Comment by arshad01** [comment]
Hi Borja

Thanks very much for the reply.

At the moment I am using Wazuh OSSEC 2.0 in local configuration to detect File Integrity failures and Rootkit check alerts. I have a background process written in python 2.7 that listens for alerts from OSSEC on a ZeroMQ socket. It keeps track of system state by getting the Scan start/end alerts and FIM/Rootkit alerts. From Syscheck scan start/end and FIM alert times it determines if the system is in a violated state or not. Without the Syscheck scan times it cannot clear the violated state if the last FIM alert was before the scan.

Using the REST API is one way to get the scan times. From what I understand, it would require the running of additional Wazuh API process(es) and storing the password for API access. Also with API, one has to pull the data from the DB whereas the current design of monitor process gets the data pushed to it.

I looked at the python API under framework directory. It could have been a way to go but the code is for python 3.6+ whereas in my case I have to use python 2.7. I can try to figure out from the framework code how it talks to the DB and then implement the minimal required code for my use.

Please share any solution (besided REST API) that helps in my upgrade to Wazuh OSSEC 3.9.

Thanks and Regards
Arshad

**Comment by bah07** [comment]
Hi @arshad01 

Since version 3.9 we have our own Python 3.7 interpreter, so the API solution can work.

If not, we can look for another option but I think it's the one that can carry less work.

Regards.

**Comment by arshad01** [comment]
Hi Borja

Ok, thanks. I will look into the python interpreter bundled with OSSEC.

I also tested with direct DB access through sqlite3 API and could read the start/end times from the scan_info table. However, I could not find any table storing rootcheck scan times. Are these times not stored in the DB?

Thanks and Regards
Arshad

**Comment by bah07** [comment]
Hi @arshad01 

In the new versions of Wazuh, the SCA module is progressively replacing the Rootcheck module. That's why the Rootcheck start and end of scan messages keep working in the same way.

You may be interested in updating your agents.

Take a look at the features of the new module in our documentation: 
- https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/security-configuration-assessment.html?highlight=sca

- https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/sca.html?highlight

Are you still receiving the Rootcheck alerts for the start and end of the scan?
You should use the API only to get the Syscheck scans.

Regards.

**Comment by arshad01** [comment]
Thanks. I'll look into the SCA module. Rootkit has been giving us quite a high number of false positives.

As on version 3.9.0, I still get the start/end scan alerts from Rootcheck (I have the alert level elevated by using a rule).

I will close this issue now. Will make changes in my monitoring system to get the scan times using the API.

Thanks very much for your patience and help :)

Regards
