### ISSUE TITLE
ELK 7.0.1 Support

### ISSUE THREAD

**Issue by AshenOfValheru** [wazuh/wazuh#3390]
Hi all,

Just wondering if ELK 7.0.1 support is available for the platform or may be available at some point?

Require it for an additional plugin that doesn't support 7.1.0 at the moment and the 6.7 versions of the plugin were pretty hit and miss.

Awesome platform by the way so thank you for that.

**Comment by jesusgn90** [comment]
Hi @AshenOfValheru, we've decided to directly publish for 7.1.0 due to the "security free" features they put on 6.8.0/7.1.0. In any case, we started the adaptation for 7.0.0 some time ago and our plugin should work as expected for 7.0.1 too.

In any case, in the next days you'll have a package for 7.0.1, but take care of the SSL layer for the stack and all that stuff,  our documentation was built for 7.1.0.

As I said, next week I'll give you a package for it.

Regards,
Jesús

**Comment by AshenOfValheru** [comment]
Ah that's great Jesús thanks for the help and quick response. Much appreciated.

**Comment by jesusgn90** [comment]
Hi @AshenOfValheru,

Here is an unofficial package for 7.0.1, https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.1_7.0.1.zip, our active support is intended to 6.8.0/7.1.x as I said, but it should work as expected, let me know if you find any issue and we'll try to help you as best as possible.

Closing this ticket, re-open it or create a new one if needed.

Regards
