### ISSUE TITLE
Wazuh installation in Local mode doesn't install python packages

### ISSUE THREAD

**Issue by JmZero** [wazuh/wazuh#3448]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10 | Python Framework | Local | Sources | Ubuntu |

Hi team, 

Currently, when installing wazuh manager in local mode if we execute any call to the API will return the following [error](https://github.com/wazuh/wazuh/issues/3418):
```
{
   "error": 1,
   "message": "Error executing internal command"
}
```
This problem appears when doing the installation from sources, which at the beginning indicates the type of installation we want to do:

![Install-local-manager](https://user-images.githubusercontent.com/33158869/58859835-0a30a300-86ab-11e9-84d5-07686fc1a96d.png)

When doing the installation in local mode the python packages are not installed for some reason, which causes that no calls can be made to the API. We can check by accessing the path `/var/ossec/framework` and checking that the `python` directory doesn't exist.

![Info-framework-python](https://user-images.githubusercontent.com/33158869/58860081-9d69d880-86ab-11e9-8122-c37c35a18db3.png)

Best regards,
Jesús Jaldo.

**Comment by BraulioV** [comment]
Hi @JmZero, 

After debugging this error with @crd1985 we found that there's an error in the `setup.py` script from the source code of our CPython. That script is modified in order to link the CPython modules with the `libwazuhext.so` and one of the changes consists of setting where `libffi.a` was. Here you can see the line: ```ffi_inc = ["{0}/{1}/server/include".format(WAZUH_SOURCES,WAZUH_LIBFFI), WAZUH_SOURCES]```

The problem is if you build Wazuh in `local` mode, the `libffi.a` is stored in `src/external/libffi/local/include` instead of `src/external/libffi/server/include`. 

To fix this issue, I will change this line 
```ffi_inc = ["{0}/{1}/server/include".format(WAZUH_SOURCES,WAZUH_LIBFFI), WAZUH_SOURCES]``` 
to
```ffi_inc = ["{0}/{1}/{2}/include".format(WAZUH_SOURCES,WAZUH_LIBFFI,TARGET), WAZUH_SOURCES]```

where `TARGET` is the variable used in the Wazuh's Makefile to indicate the build target.

Regards.

**Comment by BraulioV** [comment]
Hi again team,

The new `src_cpython.tar.gz` has already been uploaded to the 3.10 deps repository. 

Regards.
