### ISSUE TITLE
IP of Agents when multiple net interfaces configured may be duplicated.

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh#3457]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.1 rev.3921 | Wazuh component | Manager/Agent | Packages/Sources | Centos 7 |

Hi team,

When having multiple network interfaces, Kibana will get the IP of the default interface in use. 

Wazuh-Agent will register itself with the IP of the interface directly connected to Manager and sometimes, like Virtualized Environments or when having multiple net interfaces, the IP grabbed by Kibana and the IP registered in the manager will be different.

### Screenshots:

![image](https://user-images.githubusercontent.com/46649922/58872687-e37f6600-86c4-11e9-8fdd-61e23fc95be5.png)

![image](https://user-images.githubusercontent.com/46649922/58872816-27726b00-86c5-11e9-9b28-98c6105b1495.png)

![image](https://user-images.githubusercontent.com/46649922/58872869-3e18c200-86c5-11e9-8a7d-1819e6da1740.png)

So when registering multiple Agents, all will have the same ip: `10.0.2.15`.

Best Regards,

Jose

**Comment by chemamartinez** [comment]
On the manager side, since Wazuh v3.9.0 we have two IP addresses to identify agents, the one used to register the agent (register IP) and the one reported by the agent as primary IP (report IP).

Now, in the agent list of the App, the primary IP has priority over the registration one. I think the best practice here is to use the primary IP to list the agents only when the registration IP is set to `any`. Otherwise, we should use the registration IP to identify the agent.

The cause of this is that the registration IP is the one used to connect to the server when the setting `use_source_ip` is set to `yes`.

**Comment by WazuhUser** [comment]
Hi Chema, 

I have a question with multiple interfaces. I have a windows machine with rdp service enables in interface with ip 192.168.1.254 but the ip connected with de manager is 192.168.254.249. Could it be the problem detecting RDP burte force attack? 
I only received an alert with description "Logon Failure - Unknown user or bad password" and rule id "60122". 

Thanks fo your help,
Regards

**Comment by chemamartinez** [comment]
Hi @WazuhUser,

Sorry for the delayed response.

The fact the interface where the RDP service is listening is different from the one connected to the manager, does not affect to the brute force attack detection.

The security events that fire rule 60122 are collected from the Windows Event Log, here you can read more info about how Wazuh collects Windows security events: https://documentation.wazuh.com/3.11/user-manual/capabilities/log-data-collection/how-to-collect-wlogs.html

So, brute force attacks should be logged by the Windows Event Log regardless of the interface.

I hope it helps,
Chema.
