### ISSUE TITLE
Error reading rule files: Wazuh API error: 1201 - Error reading rule files

### ISSUE THREAD

**Issue by EvaSok98** [wazuh/wazuh#3460]
Wazuh version - 3.9.1
ELK version 7.1.1

After upgrading wazuh to latest version I got an error reading rule files in Wazuh App:
![image](https://user-images.githubusercontent.com/48674472/58877067-855c7e00-86d8-11e9-99c6-76c7cee579cc.png)

In /var/ossec/logs/api.log:
`WazuhAPI 2019-06-04 14:50:52 apiuser: [::ffff:172.29.0.5] GET /manager/status? - 200 - error: '0'.
WazuhAPI 2019-06-04 14:50:52 apiuser: [::ffff:172.29.0.5] GET /version? - 200 - error: '0'.
WazuhAPI 2019-06-04 14:50:53 apiuser: [::ffff:172.29.0.5] GET /cluster/status? - 200 - error: '0'.
WazuhAPI 2019-06-04 14:50:53 apiuser: [::ffff:172.29.0.5] GET /agents/000? - 200 - error: '0'.
WazuhAPI 2019-06-04 14:50:53 apiuser: [::ffff:172.29.0.5] GET /manager/status? - 200 - error: '0'.
WazuhAPI 2019-06-04 14:50:54 apiuser: [::ffff:172.29.0.5] GET /agents/summary? - 200 - error: '0'.
WazuhAPI 2019-06-04 14:50:55 apiuser: [::ffff:172.29.0.5] GET /manager/status? - 200 - error: '0'.
WazuhAPI 2019-06-04 14:50:55 apiuser: [::ffff:172.29.0.5] GET /version? - 200 - error: '0'.
WazuhAPI 2019-06-04 14:50:55 apiuser: [::ffff:172.29.0.5] GET /cluster/status? - 200 - error: '0'.
WazuhAPI 2019-06-04 14:50:56 apiuser: [::ffff:172.29.0.5] GET /agents/000? - 200 - error: '0'.
WazuhAPI 2019-06-04 14:50:57 apiuser: [::ffff:172.29.0.5] GET /manager/status? - 200 - error: '0'.
WazuhAPI 2019-06-04 14:50:58 apiuser: [::ffff:172.29.0.5] GET /rules/?limit=500&offset=0 - 200 - error: '1201'.
`
As you can see - other api calls work without errors.
Hope, you'll help me. Thank you for any response!

**Comment by adri9valle** [comment]
Hi @EvaSok98,

The API requests seem to work ok, then the error most probably comes for the rules files configuration or permissions.

This error happens when Wazuh cannot read the file properly, the reason why this happens usually is that the file has incorrect permissions.

Please as a first step check the owner of the file and the groups, to do this execute the following command:

```
# ls -l /var/ossec/etc/rules
total 4
-rw-r-----. 1 root ossec 562 Jun  5 07:34 local_rules.xml
```

In the previous command output you can see the permissions of the local rules, now we go to check the rest of the rules files:

```
# ls -l /var/ossec/ruleset/rules/
total 1096
-rw-r-----. 1 root ossec   1552 May  3 01:35 0010-rules_config.xml
-rw-r-----. 1 root ossec  12348 May  3 01:35 0015-ossec_rules.xml
-rw-r-----. 1 root ossec   4731 May  3 01:35 0016-wazuh_rules.xml
-rw-r-----. 1 root ossec  25033 May  3 01:35 0020-syslog_rules.xml
-rw-r-----. 1 root ossec   5503 May  3 01:35 0025-sendmail_rules.xml
-rw-r-----. 1 root ossec   7711 May  3 01:35 0030-postfix_rules.xml
-rw-r-----. 1 root ossec    849 May  3 01:35 0035-spamd_rules.xml
-rw-r-----. 1 root ossec   1574 May  3 01:35 0040-imapd_rules.xml
.....
...
.
```

Please check that at least the group is ossec, if some file does not have ossec as owner or group  change this:

```
# chown root:ossec {path_to_file}
```

After that please try again an API request to check this:

```
curl -u foo:bar http://localhost:55000/rules
```

Please, let me know if this is your error and if it helps you, otherwise don't be hesitate to ask again.


Regards,

Adri,

**Comment by EvaSok98** [comment]
Hi, Adri!

All my rule files have permissions, as you wrote.
When I make API request I get the same error:
`{"error":1201,"message":"Error reading rule files"}`

**Comment by adri9valle** [comment]
Hi @EvaSok98,

Let's try to get more information about the error, please set the API log in debug mode, to do this edit this file `/var/ossec/api/configuration/config.js` and set **config.logs** to debug, by default is in info mode.

```
// Values for API log: disabled, info, warning, error, debug (each level includes the previous level).
config.logs = "debug";
```
**NOTE**: The line number is 28.

Once you have edited this restart the API to apply changes:

```
systemctl restart wazuh-api
```

When the API has been restarted we go to check the API log in real time, please execute:

```
tail -f /var/ossec/logs/api.log
```

The previous command will show more enriched information when an API call was made.

Once you're watching the `api.log` file execute the following API request again:

```
curl -u {user_api}:{pass_api} http://{your_manager_ip}:55000/rules?pretty
```

I've forced an error changing the `local_rules.xml` permissions. The log shows:

```
# tail -f /var/ossec/logs/api.log 
WazuhAPI 2019-06-05 09:26:44 foo: CMD - STDOUT:
---
{"message": "Error reading rule files: local_rules.xml. Error: [Errno 13] Permission denied: '/var/ossec/etc/rules/local_rules.xml'", "error": 1201}

---
WazuhAPI 2019-06-05 09:26:44 foo: CMD - STDOUT: 149 bytes
WazuhAPI 2019-06-05 09:26:44 foo: Error reading rule files: local_rules.xml. Error: [Errno 13] Permission denied: '/var/ossec/etc/rules/local_rules.xml'
WazuhAPI 2019-06-05 09:26:44 foo: [::ffff:172.16.2.1] GET /rules/?pretty - 200 - error: '1201'.
WazuhAPI 2019-06-05 09:29:54 foo: Sending SIGTERM to CMD - Command: /var/ossec/framework/python/bin/python3 args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/rules","arguments":{"wait_for_complete":false},"ossec_path":"/var/ossec"}
WazuhAPI 2019-06-05 09:30:44 foo: Sending SIGTERM to CMD - Command: /var/ossec/framework/python/bin/python3 args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/rules","arguments":{"wait_for_complete":false},"ossec_path":"/var/ossec"}
```

As you can see the error is present in the log, please follow the previous steps and paste here the output in order to give you better assistance.

Regards,

Adri,

**Comment by EvaSok98** [comment]
Adri,

Thank you very much! My custom rules were with invalid syntax. I change them and now everything is ok.

FYI
Tool /var/ossec/bin/ossec-logtest worked without errors with invalid syntax in rules.
Example of invalid rule configuration:
`    <rule id="221002" level="6">
        <if_sid>80700</if_sid>
        <field
name="audit.file.name">/etc/shadow|/etc/passwd</field>
        <description>User auid $(audit.auid) $(audit.file.name) access. Success $(audit.success). Exe: $(audit.exe)</description>
        <group>linux,auditd,users,account_discovery,</group>
    </rule>
`

**Comment by adri9valle** [comment]
Hi @EvaSok98,

I'm glad to know that it works for you.

>Tool /var/ossec/bin/ossec-logtest worked without errors with invalid syntax in rules.

This is strange, I've edited a rule file to force the error and when I've executed `ossec-logtest` I've received the next error:

```
[root@master rules]# /var/ossec/bin/ossec-logtest 
2019/06/05 11:30:13 ossec-testrule: ERROR: (1226): Error reading XML file 'ruleset/rules/0285-systemd_rules.xml': XMLERR: Attribute '<program_name' has no value. (line 15).
2019/06/05 11:30:13 ossec-testrule: CRITICAL: (1220): Error loading the rules: 'ruleset/rules/0285-systemd_rules.xml'.
```

This meaning that `ossec-logtest` checks if the decoders and rules have errors before. Maybe the problem was that you didn't restart `ossec-logtest`  after make the change.  Every time that you make a change is necessary to restart it to load again the rules and decoders.

You could test it closing `ossec-logtest` editing a rule file with errors and executing again `ossec-logtest`.

Don't hesitate to re-open this ticket or create a new one if needed.

We are also on Slack, feel free to join us.

Regards,

Adri
