### ISSUE TITLE
agent-auth missing from wazuh OVA image

### ISSUE THREAD

**Issue by netpanda** [wazuh/wazuh#347]
Trying to setup the registration service as per:
https://documentation.wazuh.com/current/user-manual/registering/use-registration-service.html
On the latest OVA image:
https://packages.wazuh.com/vm/wazuh3.1.0_6.1.1.ova

[root@wazuh-server ~]# /var/ossec/bin/agent-auth -m 10.64.146.23 -v /var/ossec/etc/rootCA.pem 
-bash: /var/ossec/bin/agent-auth: No such file or directory
[root@wazuh-server ~]# find / -name agent-auth

No Results.

**Comment by jlruizmlg** [comment]
Hi @netpanda 

The binary ```agent-auth``` is present in the agent, not in the manager.

The command ```/var/ossec/bin/agent-auth -m 10.64.146.23``` needs to be run in the agent in order to ask the manager for a valid client.keys.

If you are using the standard OVA the parameter ```-v /var/ossec/etc/rootCA.pem``` is not necessary.

The next step in the agent after receiving the correct client.keys is setup the Manager IP in the configuration; to do that edit the file ```/var/ossec/etc/ossec.conf``` and modify the following block:

```
  <server>
    <address>IP</address>
  </server>
```
by, following your example with the same IP:

```
  <server>
    <address>10.64.146.23</address>
  </server>
```

Then restart the agent with service wazuh-agent restart.
