### ISSUE TITLE
Elastic Search template error(while loading kibana) and having issues registering agents!

### ISSUE THREAD

**Issue by jaanav6** [wazuh/wazuh#3479]
Hey it would be great if someone can help me out,
I'm having issues with the kibana app. it says elastic search template is not found.
Also I'm having trouble registering wazuh agents to the manager.
Thank you

**Comment by adri9valle** [comment]
Hi @jaanav6,

Could you please send me the version of ELK that you are using? 

To check if the template is created properly you can execute the next command:

```
$ curl http://localhost:9200/_cat/templates
```

Assuming that you're using Elastic 7.x you can find more info in our [documentation](https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/wazuh_server_rpm_centos.html#installing-filebeat).

About the problem registering agents, which registration type are you using? There are several ways to register an agent. You can find every method [here](https://documentation.wazuh.com/current/user-manual/registering/index.html).

Regards, 

Adri,

**Comment by jaanav6** [comment]
<img width="581" alt="Screen Shot 2019-06-06 at 6 33 41 PM" src="https://user-images.githubusercontent.com/25122708/59034858-af08d700-8889-11e9-8e58-cb3f58959b83.png">
Thats the output of the command. And tried using the agent-auth but it wasn't connecting to my manager so i then manually registered it but on the kibana app it still says never connected.

**Comment by jaanav6** [comment]
@adri9valle forgot to mention you in my response above!! My bad

**Comment by adri9valle** [comment]
Hi @jaanav6,

It seems that you don't have the `wazuh-alerts` template. When you execute that curl commando the output should contain something similar to this:

```
# curl "http://172.16.1.2:9200/_cat/templates"
.watches             [.watches*]                2147483647
.monitoring-es       [.monitoring-es-7-*]       0          7000199
wazuh-agent          [wazuh-monitoring-3.x-*]   0
.watch-history-9     [.watcher-history-9*]      2147483647
.monitoring-kibana   [.monitoring-kibana-7-*]   0          7000199
.ml-notifications    [.ml-notifications]        0          7010199
wazuh                [wazuh-alerts-3.x-*]       0
.monitoring-logstash [.monitoring-logstash-7-*] 0          7000199
.monitoring-alerts-7 [.monitoring-alerts-7]     0          7000199
.ml-state            [.ml-state*]               0          7010199
.triggered_watches   [.triggered_watches*]      2147483647
.ml-meta             [.ml-meta]                 0          7010199
.logstash-management [.logstash]                0
.ml-anomalies-       [.ml-anomalies-*]          0          7010199
.monitoring-beats    [.monitoring-beats-7-*]    0          7000199
.ml-config           [.ml-config]               0          7010199
```

If you compare your output with the previous response you can see that in your templates is missing: 
```
wazuh                [wazuh-alerts-3.x-*]       0
```

Please configure this template executing the following commands:

```
# curl -so /etc/filebeat/wazuh-template.json https://raw.githubusercontent.com/wazuh/wazuh/v3.9.1/extensions/elasticsearch/7.x/wazuh-template.json
# chmod go+r /etc/filebeat/wazuh-template.json
```

Please ensure that you have properly configured filebeat to send the alerts to the index:

Edit the file `/etc/filebeat/filebeat.yml` and replace `YOUR_ELASTIC_SERVER_IP` with the IP address or the hostname of the Elasticsearch server. For example:

```
output.elasticsearch:
  hosts: ['http://YOUR_ELASTIC_SERVER_IP:9200']
  indices:
    - index: 'wazuh-alerts-3.x-%{+yyyy.MM.dd}'
```

Once you've configured this enable and restart filebeat:

```
# systemctl daemon-reload
# systemctl enable filebeat.service
# systemctl start filebeat.service
```

Now you should have the template properly configured, please check it executing the curl command again.

About the problem of registering agents, the manager says that the agent is never connected, assuming that your agent is a Linux agent, please ensure that you have the correct manager IP in the `ossec.conf` file:

```
<client>
  <server>
    <address>{YOUR_MANAGER_IP_HERE}</address>
    ...
  </server>
</client>
```

After that restart the agent:

```
systemctl restart wazuh-agent
```

If the problem persists, please paste here all the possible info as `/var/ossec/logs/ossec/ossec.log`.

I hope it helps.

Regards,

Adri,

**Comment by jaanav6** [comment]
Hey thanks again for your help. 
I ran the curl commands for adding the template and then checked the templates using the command
curl http://localhost:9200/_cat/templates
but it didn't show the alerts template on there.

Also i went into var/ossec/etc/ossec.conf and i couldn't find any script like the one showed above. 
Please do let me know what i can do to make this work. Thank you

**Comment by jaanav6** [comment]
Also the log files you asked for are suffixed ossec.log.gz and its gibberish inside the file

**Comment by jaanav6** [comment]
Just an update @adri9valle I managed to add the alerts template.
Reading some forums i was advised to use this command
curl api_user:api_pass@api_url:55000/version
to check if the connectivity was right but it failed 
my wazuh api is active though.
Don't know what to do

**Comment by jaanav6** [comment]
Another update @adri9valle 

Thanks you to you have successfully configured and setup wazuh as a single host architecture.
If it is possible i would like some advice.

I am setting this up for an enterprise that runs on the cloud of sorts, i was wondering if you had tips on the best way to go about this. Also i am using the agent to provide all the endpoint data i need, so i was wondering how i can gain maximum visibility on an endpoint using this agent.
Thank you

**Comment by adri9valle** [comment]
Hi @jaanav6,

First of all, we go to try to solve the problem when trying to connect with the Wazuh API and try to connect an agent. 

We go to try some tests in order to solve your problems.

#### 1. Check the API connectivity
Edit `/var/ossec/api/configuration/config.js` and change **line 28**:

```
config.logs = "info";
```

By:
```
config.logs = "debug";
```

Once you've done this restart the API:

```
# systemctl restart wazuh-api
```

Now, check the status and let's see the log in real time:

```
# systemctl status wazuh-api
```

If the API is running properly then execute:

```
# tail -f /var/ossec/logs/api.log 
```

The previous command will show in real time the API log, after that while the `tail` command is watching the log, please execute again the `curl` command to check the API connectivity:

```
# curl -u <user>:<pass> http://<your_manager_ip>:55000?pretty
```

The output, if the process went well, should be something similar to this:

```
{
   "error": 0,
   "data": {
      "msg": "Welcome to Wazuh HIDS API",
      "api_version": "v3.9.0",
      "hostname": "master",
      "timestamp": "Fri Jun 07 2019 06:32:49 GMT+0000 (UTC)"
   }
}
```

On the other hand, please check the output of the API log and paste here.


#### 2. Check the agent connectivity

We go to re-connect the agent to the manager using the manual method as you did, please execute in the manager:

```
/var/ossec/bin/manage_agents
```

Press the **E** option to extract the key, please ensure that the IP is the correct agent IP, once you've got the key execute in the agent the same command `/var/ossec/bin/manage_agents` and press the **I** option, paste the key and you should receive the information set in the manager.

Once you've done this, replace **MANAGER_IP** from `/var/ossec/etc/ossec.conf` by **<your_manager_ip>**.

When you've done these steps, please restart the agent:

```
# systemctl restart wazuh-agent
```

If the process was done the agent will be running else the restart command should show an error, please paste here too.


#### 3. Create wazuh-alerts template for Elastic

We go to create manually the files that you need. I assuming that you have Elastic in the same host that the manager if your distribution is different please let me know.

**NOTE**: Filebeat mus be installed in the manager.

Once you have both files created execute:

Copy the content of [filebeat.yml](https://raw.githubusercontent.com/wazuh/wazuh/v3.9.1/extensions/filebeat/7.x/filebeat.yml) to ` /etc/filebeat/filebeat.yml` and the content of [wazuh-template.json](https://raw.githubusercontent.com/wazuh/wazuh/v3.9.1/extensions/elasticsearch/7.x/wazuh-template.json) to `/etc/filebeat/wazuh-template.json`.

```
# chmod go+r /etc/filebeat/filebeat.yml
# chmod go+r /etc/filebeat/wazuh-template.json
```

When you've given permissions then restart filebeat and Elastic:

```
# systemctl restart elasticsearch
# systemctl restart filebeat
``` 

If you received errors please paste here.

After that, if you didn't receive errors check again the templates of elastic with the curl command.


**NOTE**: If you are in a cloud environment, please check the firewall if you have one and check if the ports that Wazuh need are properly open. A cloud environment could create this type of conflicts.

I hope it helps if the problems persist please give me all the possible information about your environment, OS version, IPs (**if possible and does not compromise your safety**), etc.

Regards, 

Adri,

**Comment by jaanav6** [comment]
@adri9valle 

The api is function properly.
I managed to successfully connect my agent to the manager and have it registered.
Also it is active on the Kibana app, and is receiving data from the agent.
So i think i have set it up right and have followed everything you suggested.
thank you for helping me out with this.

The main incentive i had to use wazuh was to gain maximum endpoint visibility. I was wondering how i could gain as much meta data of the endpoint using the agent. By meta data i mean,

 Devices (Type of device, System, Storage,  Location, connection type, H/W Info, MAC, IP, Certificates)
        - User (ID, Name, Authentication status, Workgroup, Email, Phone)
        - OS (Type, Version, Registry, File Names + Dates, Sizes, Services and Processes installed and running)
        - Apps (Installed, Running, Version, Registry Settings, Files Sizes, Connections, Services, process,
        - Services (Running, ports, )
        - Security Agents (Anti-Malware/Virus, DLP, ), Patch Management Agents, Encryption Agents, Firewall Status, Configuration)
        - Network (Wired, Wireless, VPN, connections, bytes/)
        - Peripherals (Type of device, manufacturer, Connection Type, Attached/detached, data transferred,  )
        - VMs, Containers, (Configuration, uptime, etc)
        - Files (new files created,
        - Statistics
        -   Alerts/Events (network events, PIP, New software installed, removal of hardware)

Thats the data I'm wanting to be able to see and manage of every endpoint in my network. I was hoping the wazuh agent provided some form of visibility to all of that data.
Do let me know how i can go about looking at that.
Thank you

**Comment by adri9valle** [comment]
HI @jaanav6,

I'm glad to know that it's working properly now.

Regarding the different points that you related, there are several capabilities that are working by default.


> - User (ID, Name, Authentication status, Workgroup, Email, Phone)

By default, Windows alerts come with ID, Name, and Workgroups in each alert.

In the following alert you can see several windows field in the alert:

```
{
  ...
  ...
  ...
    "data": {
      "win": {
        "eventdata": {
          "subjectLogonId": "0x3e7",
          "targetLinkedLogonId": "0x0",
          "subjectDomainName": "WORKGROUP",
          "impersonationLevel": "%%1833",
          "authenticationPackageName": "Negotiate",
          "targetLogonId": "0x3e7",
          "logonProcessName": "Advapi",
          "logonGuid": "{00000000-0000-0000-0000-000000000000}",
          "targetUserName": "SYSTEM",
          "keyLength": "0",
          "elevatedToken": "%%1842",
          "subjectUserSid": "S-1-5-18",
          "processName": "C:\\Windows\\System32\\services.exe",
          "processId": "0x330",
          "targetDomainName": "NT AUTHORITY",
          "targetUserSid": "S-1-5-18",
          "virtualAccount": "%%1843",
          "logonType": "5",
          "subjectUserName": "DESKTOP-GDPBOU6$"
        },
        "system": {
          "eventID": "4624",
          "keywords": "0x8020000000000000",
          "level": "0",
          "providerGuid": "{54849625-5478-4994-a5ba-3e3b0328c30d}",
          "channel": "Security",
          "opcode": "0",
          "message": "Se inició sesión correctamente en una cuenta.",
          "systemTime": "2019-06-21T10:52:59.833411000Z",
          "version": "2",
          "eventRecordID": "23359",
          "threadID": "9048",
          "computer": "DESKTOP-GDPBOU6",
          "task": "12544",
          "processID": "840",
          "severityValue": "AUDIT_SUCCESS",
          "providerName": "Microsoft-Windows-Security-Auditing"
        }
      }
    },
    ...
    ...
    ...
}
```

> - OS (Type, Version, Registry, File Names + Dates, Sizes, Services, and Processes installed and running)
> - Apps (Installed, Running, Version, Registry Settings, Files Sizes, Connections, Services, process)
> - Network (Wired, Wireless, VPN, connections, bytes/)
> - Services (Running, ports, )

For this Wazuh provides a feature called [System inventory](https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html), is enabled by default, by you can modify some configuration parameters configuring [syscollector](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-syscollector.html).

If you go to Agents > {agent} > Inventory Data, you can see information related to the previous requirements:

![packets](https://user-images.githubusercontent.com/7983984/59919760-9e7b6380-9428-11e9-9c53-fec7232cbaab.png)

> - VMs, Containers, (Configuration, uptime, etc)

For this, you could use follow [monitoring containers activity](https://documentation.wazuh.com/current/docker-monitor/monitoring_containers_activity.html) in order to monitor your Docker containers.
This module is in charge of monitoring all the docker actions, pull new images, create new containers, etc. The below image shows an example alert:

![image](https://user-images.githubusercontent.com/7983984/59927055-e2c42f00-943b-11e9-9169-f427fb61eaaa.png)

> - Files (new files created)

[File integrity monitoring](https://documentation.wazuh.com/current/pci-dss/file-integrity-monitoring.html) (Syscheck) is performed by comparing the cryptographic checksum and other attributes of a known good file against the checksum and attributes of that file after it has been modified.

You can configure the [syscheck](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html) module to monitor custom folders and see which files are created, modified or deleted.

In the following image there's an example of a new created file alert:

![image](https://user-images.githubusercontent.com/7983984/59928350-d8effb00-943e-11e9-99c7-fa599289f556.png)

> - Security Agents (Anti-Malware/Virus, DLP, ), Patch Management Agents, Encryption Agents, Firewall Status, Configuration)

Wazuh can scan monitored files for malicious content in monitored files. This solution is possible through an integration with VirusTotal, which is a powerful platform that aggregates multiple antivirus products along with an online scanning engine. Combining this tool with our FIM engine provides a simple means of scanning the files that are monitored to inspect them for malicious content.

In our official documentation, there is more information about how to integrate virustotal [VirusTotal integration](https://documentation.wazuh.com/current/user-manual/capabilities/virustotal-scan/integration.html).

> - Alerts/Events (network events, PIP, New software installed, removal of hardware)

A very interesting tool for monitoring network events and catch suspicious network traffic is [Suricata](https://documentation.wazuh.com/current/learning-wazuh/suricata.html). 


> - Devices (Type of device, System, Storage, Location, connection type, H/W Info, MAC, IP, Certificates)

[Syscollector](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-syscollector.html) is the one which performs the monitoring of H/W Info, MAC and IP and for Storage may you could check [detect USB storage](https://documentation.wazuh.com/current/user-manual/capabilities/command-monitoring/command-configuration.html?highlight=usb#detect-usb-storage) in our official documentation.

An example of an alert in Kibana you can see:

![image](https://user-images.githubusercontent.com/7983984/59930091-713baf00-9442-11e9-9107-9d5c932f09ff.png)


I hope it helps you, if you have problems with some module configuration please let me know.

Regards,

**Comment by adri9valle** [comment]
Hi @Zenidd,

I've closed because you don't reply to it the issue but don't hesitate to re-open or open a new issue if you need it. We're to help!

Regards,

Adri,
