### ISSUE TITLE
Whodata Error on Windows 10 Agents

### ISSUE THREAD

**Issue by Timo3as** [wazuh/wazuh#3500]
|Wazuh version|Component|Install type|Install method|Platform|
|3.8.2|Syscheck|Agent|.msi|Windows 10|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

We are trying to configure whodata on Windows 10 Agent. 
In ossec.conf we changed the following:

<directories check_all="yes" whodata="yes">C:\Users\wazuh\Documents</directories>

We also changed Windows Local Audit Policies.
Now we get the following error:

2019/06/11 09:23:10 ossec-agent: ERROR: The event could not be added to the ignored hash table because it is duplicated. Target: 'c:\program files (x86)\ossec-agent\ossec.log'.

As far as I can tell this should've been fixed in https://github.com/wazuh/wazuh/pull/2416

**Comment by crolopez** [comment]
Hi @Timo3as,

The issue has been solved with the PR you mentioned in combination with this one: https://github.com/wazuh/wazuh/pull/3362. I recommend you to update your Windows agents to 3.9.2 because many improvements have been made to the Whodata engine since 3.8.2.

I'm going to close this issue because it was already solved in a past release. Feel free to reopen it or open a new one if necessary.

Thank you for reporting!

Best regards.
