### ISSUE TITLE
Syscollector does not extract the architecture of the single-user programs

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#3505]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.2 | Syscollector | Agent | Packages and sources | Windows Server 2016 |

A Windows program scan of Syscollector collects the list of software in `Currentversion/Uninstall` registry. This is achieved by operating with the registers in different ways depending on the type of software.

- The **64-bit** programs installed for all users are extracted by checking the registry with the `KEY_WOW64_64KEY` flag.

https://github.com/wazuh/wazuh/blob/421c4fd9b5c142936b3f1922587c355076ae4e03/src/wazuh_modules/syscollector/syscollector_windows.c#L800

- The **32-bit** programs installed for all users are extracted by checking the registry with the `KEY_WOW64_32KEY` flag.

https://github.com/wazuh/wazuh/blob/421c4fd9b5c142936b3f1922587c355076ae4e03/src/wazuh_modules/syscollector/syscollector_windows.c#L818

- The **32-bit and 64-bit** programs installed for a single user are extracted by checking the registry without the previous flags.

https://github.com/wazuh/wazuh/blob/421c4fd9b5c142936b3f1922587c355076ae4e03/src/wazuh_modules/syscollector/syscollector_windows.c#L981

The problem appears with the software inventory extracted from the single user source. Those programs are marked as `NOARCH`, which causes its architecture to be `unknown`.

https://github.com/wazuh/wazuh/blob/421c4fd9b5c142936b3f1922587c355076ae4e03/src/wazuh_modules/syscollector/syscollector_windows.c#L936

https://github.com/wazuh/wazuh/blob/421c4fd9b5c142936b3f1922587c355076ae4e03/src/wazuh_modules/syscollector/syscollector_windows.c#L1055

I have tried to open the registries of this list using the 32 and 64 bits keys separately but they have not been classified by architecture. Instead, single-user programs have been duplicated. 

The solution of `HKEY_LOCAL_MACHINE` does not apply to  `HKEY_USERS`.

**Comment by SalvaMilenario** [comment]
In that registers where the information of the single user programs is stored, windows does not save the architecture (32 bits or 64 bits) of the programs, so when the records of the programs installed for a single user are requested with ` KEY_READ | KEY_WOW64_64KEY` or `KEY_READ | KEY_WOW64_32KEY` you get the same results as they are not discriminated in the registry by the architecture of the programs.

**Comment by Dwordcito** [comment]
@HanesSciarrone please verify if this issue happens in > 4.2.

**Comment by HanesSciarrone** [comment]
## Test 

Wazuh v4.3.5 was tested with an Ubuntu 22.04 manager and a Windows 10 agent, the results showed that this problem still happens.

![image](https://user-images.githubusercontent.com/58960358/176493059-8be1fba1-3321-47bf-a5fe-93f1c013d897.png)

![packages-v435](https://user-images.githubusercontent.com/58960358/176493179-502caa86-bbec-485e-adf8-2e52dfcc8329.png)

The problem is that the data provider uses the KEY_WOW64_64KEY and KEY_WOW64_32KEY flags to get the architecture but for individual users it does not use these flags when reading the sub-registries. 

![image](https://user-images.githubusercontent.com/58960358/176496793-9c5b8da0-6b06-48e5-b7e6-f0e3dbfc1036.png)

![image (1)](https://user-images.githubusercontent.com/58960358/176496801-e6ef700c-a420-4806-81dc-c9348737a603.png)
