### ISSUE TITLE
wazuh agent ip address and Registration date is wrong

### ISSUE THREAD

**Issue by xufengnian** [wazuh/wazuh#3511]
|Wazuh version:3.9.2-1
|Component: Wazuh-manager
|Install type:Manager
|Install method:Packages
|Platform|CentOS 6.9

Hello,my host's ip address is 192.168.248.163,
but when I just try to install wazuh agent, I see kibana app wazuh show my agent  ip is 192.168.248.16,missing the last number.I try to request  wazuh api  ,the ip is missing the last number,too.
when I use manage_agents to lookup my agent ip ，I just find the  ip is  correct.
and my workmate help me to  query  global.db ，just find the  ip column is missing the last num,the registerIP column is correct. like this:

"ip": "192.168.248.16",
"registerIP": "192.168.248.163",

so I guess some bug in ip processing。

And my agent  Registration date is earlier 8 hours than my time,I just install agent at 10:00 AM,but  kibana app show  the  Registration date  is 18:00 AM,I check the wazuh  Server and  agent  host  timezone,they  are  same  ,both of them use  ntp to make sure the time is correct.

so I  want to know if it's  my  error  or  real bug?thx!

**Comment by chemamartinez** [comment]
Hi @xufengnian,

Sorry for the delayed response.

On the manager side, since Wazuh v3.9.0 we have two IP addresses to identify agents, the one used to register the agent (register IP) and the one reported by the agent as primary IP (report IP).

The Wazuh App uses the primary IP to list agents (to avoid showing `any` as the agent IP in cases where the agent was registered without source IP). On the other side, the `manage_agents` tool shows the registration IP of the agent.

It is possible your agent has two network interfaces? One with the IP 192.168.248.16 and the other with 192.168.248.163. You could check it by running one of the following commands into it:

```
# ip addr
# ifconfig
```

In addition, to find out the cause of your issue, it would be very helpful for us if you can share the content of the `agent-info` file for that agent. 

It is located on the manager host, in the route `/var/ossec/queue/agent-info/<agent-name>-<agent-ip>`.

Looking forward to your reply.

Best regards,
Chema.

**Comment by xufengnian** [comment]
I am very glad to recive your reply
My agent has 3 network-interfaces but all of them has interface without ip 192.168.168.16. you can see some pictures,they show my agent only has one ip address 192.168.248.163
![image](https://user-images.githubusercontent.com/15324125/59552550-0b22d800-8fbb-11e9-8990-0e8794b41881.png)
![image](https://user-images.githubusercontent.com/15324125/59552596-a87e0c00-8fbb-11e9-90d7-67e99eaac00a.png)

And I just find **/var/ossec/queue/agent-info/<agent-name>-<agent-ip>**, this file show my agent ip is different from registerIP
![image](https://user-images.githubusercontent.com/15324125/59552611-d5caba00-8fbb-11e9-8c33-75a63faddb29.png)

I think you can just try  install wazuh-agent in host that has ip address like  192.168.xxx.xxx. Maybe some interesting result can happen or maybe something wrong with my hosts.Thank you very much!

**Comment by Zenidd** [comment]
Hi @xufengnian,

Could you also show us the output of `cat bbb-192.168.248.136` and  `cat bbb-192.168.248.136`?

Since all ip is identical except for the least significant digit, I get the feeling that that less significant digit may be being truncated. 
<br></br>
Best regards,

Juan Pablo Sáez

**Comment by xufengnian** [comment]
> Hi @xufengnian,
> 
> Could you also show us the output of `cat bbb-192.168.248.136` and `cat bbb-192.168.248.136`?
> 
> Since all ip is identical except for the least significant digit, I get the feeling that that less significant digit may be being truncated.
> 
> 
> 
> Best regards,
> 
> Juan Pablo Sáez

hello ,I open the bbb-192.168.248.136,this is result
![image](https://user-images.githubusercontent.com/15324125/60475547-6be42d00-9caa-11e9-9c1d-0ff7f472d7a8.png)

**Comment by chemamartinez** [comment]
Hi @xufengnian,

After regarding your screenshots, it seems there is a bug when reading the IP address which is missing the last digit of the IP.

Let us investigate it and try to reproduce it for finding out what can be happening.

Thank you for your feedback.

Best regards.

**Comment by Skeptor** [comment]
Hi @xufengnian 

I have been able to reproduce your issue. The function that receives the IP truncates the last digit if the IP length is the longest possible `XXX.XXX.XXX.XXX` replacing the character 15 with null character `\0`.
It will be solved in the next version.

Thank you for reporting the issue.
Best regards.

**Comment by xufengnian** [comment]
Thanks for your help.
