### ISSUE TITLE
Windows agent client.keys has wrong permissions

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh#3520]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|3.9.2|agent-auth|Agent|Packages|Windows 10 (among others)|

After doing a fresh installation of the Wazuh agent via packages the `C:\Program files(x86)\ossec-agent\client.keys` can be read by unprivileged accounts. 

This has been observed in several installations including Windows 10 Home and Pro, Windows Server 2012 R2 Standard. 

However in at least one instance of Windows 10 Pro proper permissions (Only readable by the administrator) was observed. I was not able to determine yet the defining factor for this last instance.

This was observed from Wazuh version 3.6.1 to 3.9.2.

**Comment by sergiovp** [comment]
I could check that effectively, an unprivileged account can read inside `ossec-agent` directory.
The problem is that normal users have read permissions.

## Possible solution:

One posible solution is deny access to `ossec-agent` directory to users.
We can do it adding `system("echo y|icacls . /T /deny \"*S-1-5-32-545:D\" ");` at `src/win32/setup-win.c` file.

+ **icacls**: command allows to display or change an Access Control Lists (ACLs) for files and folders on the file system
+ **.** : the hole directory
+ **/T**: this will apply permission changes to all subfolders
+ **/deny**: deny access privileges
+ ***S-1-5-32-545**: Users
+ **:D**: Delete access

## Next Step:
Check if it works.

**Comment by sergiovp** [comment]
It worked, so, the error is fixed up.

**Comment by vikman90** [comment]
## Research conclusion

1. We should not add _deny_ rules since they might conflict with other _grant_ rules. For instance, `grant X to Administrators` and `deny x to Users`, they conflict for users who belong to both groups.
2. In order to achieve that, we must disable ACL inheritance for the _ossec-agent_ folder and copy the ACL from _Program Files_, and then remove the `grant X to Users` rule.
3. Windows XP does not support references to SID (`S-1-5-32-545`), so we must refer that group as "Users", which only works in the English language.

## Proposed solution

We will apply this procedure in the `setup-win.exe` (post-install) tool:

1. Disable inheritance and copy ACL:

```sh
ICACLS ossec-agent /inheritancelevel:d
```

2. Remove permissions related to the "Users" group:

```sh
ICACLS ossec-agent /remove "*S-1-5-32-545"
```

## References

[icacls documentation](https://docs.microsoft.com/es-es/windows-server/administration/windows-commands/icacls)

**Comment by sergiovp** [comment]
## Advances
It worked perfectly using `.exe` file, but when we generate the `.msi`, it doesn't work.
We have to change `wazuh-installer.wxs` file, which it's used to generate the `.msi` file.

## Proposed solution
As we comment above, we should not add deny rules, so that, after investigate about change permissions in **Wix**, I decided to execute **icacls** comand on `wazuh-installer.wxs`.

### I have follow these steps:

1. We have to assigne the command call to a property element.
`<Property Id="ID" Value='"cmd" /c icacls "C:\Folder_rute" /inheritancelevel:d'/>`

2. Specifies a custom action to be added to the MSI CustomAction table.
`<CustomAction Id="ID" BinaryKey="WixCA" DllEntry="CAQuietExec64" Execute="deferred" Return="ignore" Impersonate="no"/>`

    1. DllEntry is an important attribute, we call **CAQuietExec64** which means that we are going to execute a CMD command in a 64-bit machine. So, we have to add another rule for 32-bit. `CAQuietExec32`

3. Add the custom action.
We would need to link this source file along with a source file that contained `<Product/>`  to successfully complete.
`<Custom Action="ID" Before='InstallFinalize' > NOT Installed</Custom>`

## Implications

We get the same implications commented below.

## References
+ Stack Overflow: 
    + [icacls runs from Wix](https://stackoverflow.com/questions/10450029/icacls-run-from-wix-caquietexec-behaving-differently-than-when-run-from-dos-comm)
    + [WIX Custom Action running as 32 bit process](https://stackoverflow.com/questions/12098382/wix-custom-action-running-as-32-bit-process)
+ Wix documentation:
    + [Adding a CustomAction](https://wixtoolset.org/documentation/manual/v3/wixdev/extensions/authoring_custom_actions.html)
    + [CustomAction Element](https://wixtoolset.org/documentation/manual/v3/xsd/wix/customaction.html)
    + [Property Element](https://wixtoolset.org/documentation/manual/v3/xsd/wix/property.html)
    + [Quiet Execution Custom Action](https://wixtoolset.org/documentation/manual/v3/customactions/qtexec.html)

**Comment by jctello** [comment]
Please note that the correct permissions are set if the key is extracted from the manager using the `/var/ossec/bin/manage_agents` utility and then pasting it into the `win32ui.exe` graphical interface in the `Authentication key:` field (which prompts the `Confirm Importing Key` dialog, which in turn eventually calls upon the [set_ossec_key](https://github.com/wazuh/wazuh/blob/3.9/src/win32/ui/common.c#L482) function). 

This can serve as a workaround and maybe the solution needs to mimic that process.

**Comment by sergiovp** [comment]
## Advances

After check what possibilities we had to change absolute rute of the command by a relative rute, I decided to discard the commented previous solution .

In `wazuh-installer.wxs` file, we call `InstallerScripts.vbs`, so, we could execute our commands there:
+ `ICACLS ossec-agent /inheritancelevel:d`
+ `ICACLS ossec-agent /remove "*S-1-5-32-545"`

## Implications
It works well, so independently of our folder rute installation, we have the correct permissions.

## Next Step
Check if it works on x32 systems.
