### ISSUE TITLE
Vulnerability Detector Not Fetching Vulnerabilities from OVAL Files

### ISSUE THREAD

**Issue by abdulrafaykhan** [wazuh/wazuh#3521]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.2 | Vulnerability-Detector | Manager | Packages | Ubuntu 16/18 |
```
> {"timestamp":"2019/06/13 08:42:40","tag":"wazuh-modulesd:vulnerability-detector","level":"info","description":"(5461): Starting Ubuntu Bionic database update..."}
> {"timestamp":"2019/06/13 08:42:58","tag":"wazuh-modulesd:vulnerability-detector","level":"error","description":"(5405): SQL error: UNIQUE constraint failed: VULNERABILITIES.CVEID, VULNERABILITIES.OS, VULNERABILITIES.PACKAGE, VULNERABILITIES.OPERATION_VALUE"}
> {"timestamp":"2019/06/13 08:42:58","tag":"wazuh-modulesd:vulnerability-detector","level":"error","description":"(5409): Could not refresh the BIONIC DB."}
> {"timestamp":"2019/06/13 08:42:58","tag":"wazuh-modulesd:vulnerability-detector","level":"error","description":"(5426): CVE database could not be updated."}
```

Last week I updated Wazuh from 3.8.2 to 3.9.2 to resolve a bug related with the vulnerability detector, after which it started working as expected. Since, that was in my Dev Env, I had to shift the config to the Prod Env, where I updated it too from 3.8.2 to 3.9.1. But to my surprise this morning I found this error in my vulnerability detector logs, and find that it is unable to fetch the vulnerabilities. This affects both my Dev and Prod Envs and this only affects Ubuntu OVALs (both 16 and 18). Redhat and Debian vulnerabilities are updated fine. Please look over this issue. 
Do feel free to contact me for any required details. Thanks!

**Comment by crolopez** [comment]
Hi @abdulrafaykhan,

The reason for this bug is an uncontrolled change in the Canonical OVAL structure. Specifically, a new section has been added to the OVAL structure, which must be processed in order to detect the vulnerabilities. This section, because it is new and unnecessary until now, is not being parsed and that is why the failure appears.

This new structure has not led to a change in the file version.

``` XML
    <generator>
        <oval:product_name>Canonical CVE OVAL Generator</oval:product_name>
        <oval:product_version>1.1</oval:product_version>
        <oval:schema_version>5.11.1</oval:schema_version>
        <oval:timestamp>2019-06-13T07:27:22</oval:timestamp>
    </generator>
```

To give a practical example, before we analyzed the section `<objects>` to extract from here the package on which the vulnerability is applied. With this restructuring, and in not all cases, we must jump from `linux-def:dpkginfo_object to the new `test` section to get the same information.

### Before

``` XML
<objects>
...
        <linux-def:dpkginfo_object id="oval:com.ubuntu.bionic:obj:200224390000000" version="1" comment="The 'cpp-4.8' package.">
            <linux-def:name>cpp-4.8</linux-def:name>
        </linux-def:dpkginfo_object>
...
</objects>
```

### After the change

``` XML
<objects>
...
        <linux-def:dpkginfo_object id="oval:com.ubuntu.bionic:obj:200224390000000" version="1" comment="The 'gcc-4.8' package binaries.">
            <linux-def:name var_ref="oval:com.ubuntu.bionic:var:200224390000000" var_check="at least one" />
        </linux-def:dpkginfo_object>
...
</objects>

...

<variables>
...
        <constant_variable id="oval:com.ubuntu.bionic:var:200224390000000" version="1" datatype="string" comment="'gcc-4.8' package binaries">
            <value>cpp-4.8</value>
            <value>g++-4.8</value>
            <value>g++-4.8-multilib</value>
            <value>gcc-4.8</value>
            <value>gcc-4.8-base</value>
            <value>gcc-4.8-locales</value>
            <value>gcc-4.8-multilib</value>
            <value>gcc-4.8-source</value>
            <value>gccgo-4.8</value>
            <value>gccgo-4.8-multilib</value>
            <value>gdc-4.8</value>
            <value>gfortran-4.8</value>
            <value>gfortran-4.8-multilib</value>
            <value>gobjc++-4.8</value>
            <value>gobjc++-4.8-multilib</value>
            <value>gobjc-4.8</value>
            <value>gobjc-4.8-multilib</value>
            <value>lib32asan0</value>
            <value>lib32go4</value>
            <value>lib64asan0</value>
            <value>lib64go4</value>
            <value>libasan0</value>
            <value>libgo4</value>
            <value>libsfasan0</value>
            <value>libstdc++-4.8-pic</value>
            <value>libx32asan0</value>
            <value>libx32go4</value>
        </constant_variable>
...
</variables>

```

You can compare these formats by evaluating [Ubuntu Precise's OVAL](https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.precise.cve.oval.xml), which has not been updated since May 10, 2017.

We are working on a solution for this bug, which will be released as soon as possible.

Thank you for reporting it!

Best regards.

**Comment by abdulrafaykhan** [comment]
Okay thank you @crolopez for the superbly swift response both here and on the Slack channel. You greatly helped me in explaining to my team the reason for the issue. I am glad to see that you guys are working on it and hope it would be resolved soon. Although, I have one question, how will you release the fix to this? Will it be in the form of version update, or in the form of a patch? This will help us in planning the upgrade cycle more efficiently. 
Once again a big thank you for the awesome support!
Feel free to contact me regarding any thing that is required from my end!
Thanks!

**Comment by crolopez** [comment]
Hi @abdulrafaykhan,

The fixes in the Wazuh code are given through software updates and depending on the priority of the fix. In this case, because it is a critical error in a fundamental part of the module, it will most likely be included in the next release (3.9.3 or 3.10.0).

We still have to discuss some questions regarding the final solution, but you will be able to see the evolution of the fix through this issue.

The next step will be to make a script that makes the new format compatible with the old one. At first, I am going to skip the variables section and build the object nodes based on the comment (where the package comes between quotes). I will share it when it is ready.

Thank you for your kindness and interest in the project!

Best regards.

**Comment by abdulrafaykhan** [comment]
Okay! Thank you for this. Hoping that it gets resolved soon! Waiting eagerly for the fix. :smile:

**Comment by abdulrafaykhan** [comment]
Plus thank you for the OVAL files as well. I have deployed them in my dev and prod envs and now the vulnerability detector is working fine. But this is not a permanent solution. So hoping that it gets fixed soon, and considering your pace of response, I have no doubt that it will be fixed swiftly! :smile:

**Comment by crolopez** [comment]
This script adapts OVAL's new structure to the previous one, which uses Vulnerability Detector. 

To use it:

``` BASH
./oval_adapt.py com.ubuntu.xenial.cve.oval.xml adapted_xenial_oval.xml
```

``` Python
# Script to adapt the changes in the Canonical OVAL introduced on June 13, 2019 to the previous format

# Copyright (C) 2015-2019, Wazuh Inc.
# June 13, 2019
# This program is a free software; you can redistribute it and/or modify it under the terms of GPLv2

import sys
import re

if len(sys.argv) != 3:
	print("Use: ./oval_adapt.py <input> <output>")
	exit(1)

input = sys.argv[1]
output = sys.argv[2]
object_node = False
package_name = ""
variables_section = False

f_output = open(output, "w")
	
with open(input, 'r') as f_input:
 	for line in f_input:
   		if "<linux-def:dpkginfo_object" in line:
   			object_node = True
   			result = re.search("'(.*)'", line)
   			package_name =  result.group(1)
   			f_output.write(line)
   			continue
		elif "</linux-def:dpkginfo_object" in line:
			object_node = False
			package_name = ""
		elif "<variables>" in line:
			variables_section = True
			continue
		elif "</variables>" in line:
			variables_section = False
			continue
		elif variables_section:
			continue

		if not object_node:
			f_output.write(line)
		else:
			f_output.write("\t\t\t<linux-def:name>" + package_name + "</linux-def:name>\n")
exit(0)
```

To use the output OVAL file, you can set the **path** or **url** options as follow:

``` XML
    <feed name="ubuntu-16">
      <disabled>no</disabled>
      <path>/output_path/adapted_xenial_oval.xml</path>
      <update_interval>1h</update_interval>
    </feed>
```

It is a temporary solution while fixing the issue, but it will allow using the updated OVALs files. You can find them here:

- **Xenial**: https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.xenial.cve.oval.xml
- **Bionic**: https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.bionic.cve.oval.xml

Best regards.

**Comment by crolopez** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/3563.
