### ISSUE TITLE
Time and IP exclusion in granular options when sending email alerts

### ISSUE THREAD

**Issue by dataatsky** [wazuh/wazuh#3522]
Wazuh Manager version: 3.8

Description:

We would like to stop receiving email alerts from servers taking into account the time and IP.
For example, we have:

Server 1 (10.158.13.20) -> Sending the same alert from 2 to 3 am due to a normal behaviour of that server.
Server 2 (10.158.13.21) -> Sending the same alert from 2 to 3 am due to a normal behaviour of that server.

Is there any way in granular options to filter emails that come from a specific IP and a range of time?
I have checked granular options but I could not find anything.

Thank you

**Comment by Zenidd** [comment]
Hello @dataatsky,

- **Time-range** mail filtering/dropping is not available on emails right now. It's an interesting feature that we'll keep in mind for future versions of Wazuh.

-  As for **IP filtering**, on a granular configuration we can specify which IP's we want to receive messages from and not which IP's we want to drop messages. In any case, since we cannot filter by time range, we cannot solve the problem from here.


A **possible workaround** is to create child rules with the labels `<time>`(to target the required time range) and  `<options>no_email_alert</options>` for those rules that trigger a lot on Server1/2 on the 2-3AM range.

These rules with `<options>no_email_alert</options>` label generate alerts that will not be sent by mail.


You can follow the further example to add the child rules:
 
```XML

<!-- Original rule that triggers a lot on Server1/2 on interval 2-3AM   -->
  <rule id="5501" level="3">
    <if_sid>5500</if_sid>
    <match>session opened for user </match>
    <description>PAM: Login session opened.</description>
    <group>authentication_success,pci_dss_10.2.5,gpg13_7.8,gpg13_7.9,gdpr_IV_32.2,</group>
  </rule>

<!-- Bridge rule to test correct time -->
  <rule id="559801" level="3" noalert="yes">
    <if_sid>5501</if_sid>
    <time>02:00-03:00</time>
    <description>TESTING RULE0</description>
  </rule>

    <!-- Rule that generates alert without sending an email if location is Server1/2 and time is on range 2-3AM -->
  <rule id="559802" level="3">
    <if_sid>559801</if_sid>
    <location>10.158.13.20|10.158.13.21</location>
    <options>no_email_alert</options>
    <description>TESTING RULE1</description>
  </rule>
```
It's possible to target a group of rules on your bridge rule using commas to separate. This will allow you to disable mailing of several rules from the desired locations and time range:
```XML
<if_sid>5000,5001,5002</if_sid>
```

Please let me know if it helps. In case it doesn't work we can look for other solutions.


Best regards,

Juan Pablo Sáez

**Comment by Zenidd** [comment]
Hi @dataatsky,

I'm closing this ticket due to inactivity. If you need additional help configuring the alerts according to your needs please do not hesitate to reopen this ticket or open a new one.

Best regards, Juan Pablo Sáez
