### ISSUE TITLE
certificate packages.wazuh.com expired

### ISSUE THREAD

**Issue by petersutty** [wazuh/wazuh#3528]
it seems the certificate on packages.wazuh.com has just expired

**Comment by albertomn86** [comment]
Hi @petersutty,

thanks for reporting. Our team is working on it.

Regards.

**Comment by snaow** [comment]
Hi @petersutty,

We had a problem related to Amazon subdomain certificates auto-renewal. 
The certificate has been renewed within 30 minutes since we detected the issue.
 I hope you can check it and tell us if it is working properly on your side.

I have checked from different locations (Ohio, N.Virgina, N.California, West EU, East EU) and the certificate is valid.

Thanks for reporting the issue and truly sorry for the inconveniences caused.

Best regards,
Pedro.

**Comment by petersutty** [comment]
works good now
thanks
P
