### ISSUE TITLE
Infrastructure integration

### ISSUE THREAD

**Issue by ghost** [wazuh/wazuh#3551]
I was wondering if there was a way i can use the wazuh agent without the wazuh manager. As in can the agent still collect metadata and send it to a third party server instead of having a wazuh manager control the agents?

I have an already existing infrastructure and would like the agent to monitor that endpoint but be connected to a personal server for control and logging. Please do let me know if this is even possible. 

Thank you

**Comment by jaanav6** [comment]
@adri9valle Any input from your side?

**Comment by Lopuiz** [comment]
Hello @jaanav6 

Agents can only report to managers.
You can install a manager instead of an agent.
The manager monitors and analyzes the same events as an agent. There are two ways to send the information collected by Wazuh manager:
1. Sent alerts to your server via Syslog using `<syslog_outpu>`.  A configuration example can be the following:
```
<syslog_output>
  <server>10.0.0.1</server>
  <format>json</format>
</syslog_output>
```
You can read more about it in our [documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syslog-output.html).

2. Send with Rsyslog all `/var/ossec/logs/archives/archives.log` logs. This file contains all logs processed by Wazuh.

For these configurations, it is not necessary to install Wazuh API or Wazuh APP.

I hope it helps you. If you have further questions, lets us know.

Regards, Eva.

**Comment by jaanav6** [comment]
@Lopuiz Thank you this definitely helps, I had another question if you can help me it would be great.
What are the source files in the repository that do the agent inventory check and system check for the metadata visibility that people require.
i would like to read the code in c to try and understand what exactly it is the agent is doing.
Thank you

**Comment by Lopuiz** [comment]
Hello @jaanav6,

I'm glad I was helpful.
 
I'm not sure the functionality you refer to. If you refer [Syscollector](https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html) you can find all source files in [src/wazuh_modules/syscollector](https://github.com/wazuh/wazuh/tree/master/src/wazuh_modules/syscollector).

Regards, Eva

**Comment by Lopuiz** [comment]
Hello again!

I'll close this issue. If you have further questions you can reopen this issue or open another one.

Regards,
Eva
