### ISSUE TITLE
Vulnerability Detector Alerts No Rationale

### ISSUE THREAD

**Issue by ericlee0517** [wazuh/wazuh#3588]
![vuln-detector1](https://user-images.githubusercontent.com/52303393/60311111-5d370680-9988-11e9-9e6b-c61e4bf7ee25.png)
![1561685912(1)](https://user-images.githubusercontent.com/52303393/60311155-94a5b300-9988-11e9-98af-4ae66342fd79.jpg)
As u can see, in Wazuh User Manual ,there is a tag named Rationale in ever alert when u test Vulnerability detector.However, here is my test alert 
* Alert 1561542239.1191068: - vulnerability-detector,gdpr_IV_35.7.d,
2019 Jun 26 17:43:59 localhost->vulnerability-detector
Rule: 23505 (level 10) -> 'RHSA-2019:0818: kernel security and bug fix update (Important)'
{"vulnerability":{"cve":"CVE-2019-7221","title":"RHSA-2019:0818: kernel security and bug fix update (Important)","severity":"High","published":"2019-02-07","updated":"2019-02-07","reference":"https://access.redhat.com/security/cve/CVE-2019-7221","state":"Fixed","package":{"name":"python-perf","version":"3.10.0-862.el7","cvss3":"7.5/CVSS:3.0/AV:L/AC:H/PR:H/UI:N/S:C/C:H/I:H/A:H","patch":"RHSA-2019:0818-01","condition":"less than 0:3.10.0-957.12.1.el7"}}}
vulnerability.cve: CVE-2019-7221
vulnerability.title: RHSA-2019:0818: kernel security and bug fix update (Important)
vulnerability.severity: High
vulnerability.published: 2019-02-07
vulnerability.updated: 2019-02-07
vulnerability.reference: https://access.redhat.com/security/cve/CVE-2019-7221
vulnerability.state: Fixed
vulnerability.package.name: python-perf
vulnerability.package.version: 3.10.0-862.el7
vulnerability.package.cvss3: 7.5/CVSS:3.0/AV:L/AC:H/PR:H/UI:N/S:C/C:H/I:H/A:H
vulnerability.package.patch: RHSA-2019:0818-01
vulnerability.package.condition: less than 0:3.10.0-957.12.1.el7
No Rationale tags please help me

**Comment by crolopez** [comment]
Hi @ericlee0517,

The rationale field is only displayed if the vulnerability does not have the reference field. The reason for this is that the rationale field usually occupies a lot of space, and it is not necessary if we can obtain vulnerability information from its reference.

However, this should be reflected in the documentation. We have opened a [PR to include this information](https://github.com/wazuh/wazuh-documentation/pull/1312).

I'm going to close the issue because the doubt is solved. Feel free to reopen it if you don't think so.

Best regards.
