### ISSUE TITLE
SCA Template needs to add rules？

### ISSUE THREAD

**Issue by ericlee0517** [wazuh/wazuh#3600]
Hi,bros,sorry to bother u again. I found the new feature SCA and I read the config files cis_rhel7_linux_rcl.yml, it only has about 70 rules. However, when I used openscap last week and I config it with the profile Cis in ssg-centos-7-ds.xml, it has about 200 rules.If we need to add new rules?Besides, when I was excuting openscap，agent CPU almost 100%.How about the SCA when it is enabled on an agent?

**Comment by Zenidd** [comment]
Hi @ericlee0517,


SCA rules are an adaptation of rootcheck policies and aren't equal to openscap policies.
If you need more policies, you can include yours in the file `cis_rhel7_linux_rcl.yml`. We recommend doing a backup of the file once you have added your rules since updating process deletes the changes.

On the other hand, SCA resources usage has been tested and does not present any known problems in the supported architectures. If you have high resource consumption problems with SCA at any agent, please let us know so we can investigate.
<br></br>
Please, let me know if it helps. If you need more help do not hesitate to contact us.

Best regards,

Juan Pablo Sáezw

**Comment by Zenidd** [comment]
Hi again @ericlee0517,

I'm gonna close this ticket. Please, if you have any other questions or want more information on this topic, do not hesitate to reopen this ticket or a new one.

Regards,

Juan Pablo Sáez
