### ISSUE TITLE
Unknown problem somewhere in the system ossec alert stoped for few server

### ISSUE THREAD

**Issue by yuvrag** [wazuh/wazuh#3632]
OSSEC HIDS Notification.
2019 Jul 08 16:13:15

Received From: (pbx.xxxxxx.com) 10.0.2.1->/var/log/messages
Rule: 1002 fired (level 2) -> "Unknown problem somewhere in the system."
Portion of the log(s):

Jul  8 16:12:50 pbx nrpe[3038]: Error: Could not complete SSL handshake. 5

**Comment by cristgl** [comment]
Hello @yuvrag,

This unknown alert has been fired because of the "Error" word in your log. I have noticed that this log has been obtained from /var/log/messages, where the system can write; it doesn't seem to be related with Wazuh, but with NRPE.
Could you specify what you have said about some servers being stopped?

Kind regards,
Cristina

**Comment by cristgl** [comment]
Hi @yuvrag,

I am closing this issue as it has no new answers since July 8th. If you need further help do not hesitate to contact us again.

Regards,
Cristina
