### ISSUE TITLE
wazuh v3.1

### ISSUE THREAD

**Issue by kulozzzz** [wazuh/wazuh#364]
I am using the ./bin/agent_groups -a -i 002 -g test to add a user to a group with the following error:
Internal error: strptime () argument 1 must be string without null bytes, not unicode. I do not know how to solve this problem.

**Comment by kulozzzz** [comment]
Debug out as follows:
Internal error: strptime () argument 1 must be string without null bytes, not unicode
Traceback (most recent call last):
  File "./bin/agent_groups", line 278, in <module>
    main ()
  File "./bin/agent_groups", line 255, in main
    set_group (arguments ['agent-id'], arguments ['group'], arguments ['quiet'])
  File "./bin/agent_groups", line 124, in set_group
    msg = Agent.set_group (agent_id, group_id)
  File "./bin/../framework/wazuh/agent.py", line 1630, in set_group
    Agent (agent_id) .get_basic_information ()
  File "./bin/../framework/wazuh/agent.py", line 270, in get_basic_information
    self._load_info_from_DB (select)
  File "./bin/../framework/wazuh/agent.py", line 257, in _load_info_from_DB
    self.status = Agent.calculate_status (self.lastKeepAlive, pending)
  File "./bin/../framework/wazuh/agent.py", line 135, in calculate_status
    last_date = datetime.strptime (last_keep_alive, '% Y-% m-% d% H:% M:% S')
TypeError: strptime () argument 1 must be string without null bytes, not unicode

**Comment by Lifka** [comment]
Hello @kulozzzz,

it seems a problem with the last_keep_alive save on DB.

I would like to see the last_keep_alive of agent 002. If you have installed Wazuh API, you could use the following request:
`curl -u foo:bar -k -X GET "http://127.0.0.1:55000/agents/002?pretty&select=last_keepalive"`

If you don't have the API installed, you can use:
```
$ sqlite3 /var/ossec/var/db/global.db
$ select * from agent;
```

Please, copy and paste here the result.

Best regards,
Javier.

**Comment by kulozzzz** [comment]
hello @Lifka 
Wazuh API request:
{
   "error": 0,
   "data": {
      "lastKeepAlive": "2018-01-23 20:19:56"
   }
}

**Comment by Lifka** [comment]
Hello,

I think your problem is solved in this PR #289 and included in Wazuh version 3.0.

Check if your version is 3.0 or upper:
```shellsession
# cat /etc/ossec-init.conf
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.1.0"
REVISION="3491"
DATE="Tue Jan 23 14:34:10 CET 2018"
TYPE="server"
```

Also, you can check if your file `/var/ossec/framework/wazuh/agent.py` includes this changes: https://github.com/wazuh/wazuh/pull/289/files.

**Comment by kulozzzz** [comment]
@Lifka  
`# cat /etc/ossec-init.conf
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.1.0"
REVISION="3491"
DATE="Mon Jan 15 16:21:15 CST 2018"
TYPE="server"
`
The contents of /var/ossec/framework/wazuh/agent.py is up to date

**Comment by mgmacias95** [comment]
Hello @kulozzzz,

Which Python version are you using? The script needs to be used with Python 2.7.

Also, can you set the group for other agents or does the script fail always the same way?

Best regards,
Marta

**Comment by kulozzzz** [comment]
@mgmacias95  
I am using python version 2.7.14 and I use agent_groups -i 001 -g test to set up other groups or an error occurred

**Comment by kulozzzz** [comment]
@Lifka @mgmacias95 can be grouped by resetful api

**Comment by mgmacias95** [comment]
Hello @kulozzzz,

The API and the `agent_groups` script use the same python framework to group agents:

https://github.com/wazuh/wazuh/blob/62429274dc7dcf588a2ae70d0f540938acb9d8bd/framework/scripts/agent_groups.py#L124

https://github.com/wazuh/wazuh-api/blob/0235f561ebba7b14bf171f521db0e7dd6165c404/models/wazuh-api.py#L198

If you can use the API but not the `agent_groups` script, the problem is on the `agent_script` side. On the debug information you showed, the error was in the python framework, so I think there's a problem on how the `agent_groups` script reads the data. Could you please edit the script and add a print just before calling the function `Agent.set_group ` (line 123) to check the IDs the python framework is receiving? 

Thank you so much and sorry for the inconvenience,
Marta

**Comment by kulozzzz** [comment]
@mgmacias95 My python is not very good, what should I do?

**Comment by mgmacias95** [comment]
Hello @kulozzzz,

The problem seems to be on the `_load_info_from_DB` function so I'm going to ask you to put some prints there. The `last_keepalive` is not correctly loaded from DB but I'd like to check if all other fields are correctly loaded or not from the database.

In line 194 of the `agent.py` file add the following line:
```python
print("{}: {}".format(field, value))
```
Please indent the code using spaces instead of tabs and run again the `agent_groups` script.

Best regards,
Marta

**Comment by kulozzzz** [comment]
@Lifka hello,The result after running agent_groups is：
![image](https://user-images.githubusercontent.com/29471339/35839041-4a7abd1e-0b29-11e8-8b1c-2b22bf9f377c.png)

**Comment by mgmacias95** [comment]
Hello @kulozzzz,

It seems there's a problem with the `sqlite3` package the `agent_groups` script is using. I can see in your screenshots the data that comes from the database is not completed (all variables seem to be incomplete).

Before processing any request, the API adds `/var/ossec/framework/lib` to the `LD_LIBRARY_PATH` to use the recommended `sqlite3` version compiled by Wazuh:

```shellsession
# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/var/ossec/framework/lib
```

Best regards,
Marta

**Comment by kulozzzz** [comment]
@mgmacias95 Sorry, this time because the Spring Festival vacation response late.I've added this global variable to / etc / profile before, still the same result
