### ISSUE TITLE
Deployment with the new MSI Package Wazuh 3

### ISSUE THREAD

**Issue by sametsazak** [wazuh/wazuh#367]
Hello,

https://blog.wazuh.com/automatically-deploying-ossec-to-windows-using-wazuh-api/

This deployment script can be used only with executable file, not with msi package.

Is there any v3 executable or should I build my own?

**Comment by smtszk** [comment]
I installed agent with msi and then used agent-deploy.ps1

https://raw.githubusercontent.com/wazuh/wazuh-api/master/examples/api-register-agent.ps1

Thanks.

**Comment by vikman90** [comment]
Hi @smtszk,

The MSI package embeeds agent auto-registration. This documentation may help you:

https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/wazuh_agent_windows.html#using-the-command-line

You can also use the API and the script you mentioned. If you need another case of use, please let us know.

Best regards.

**Comment by smtszk** [comment]
Hi, @vikman90 

I'd like you to know that 

'ConvertFrom-Json' cmdlet isn't working on powershell v2 and its under versions. At least v3 needed.

Powershell v2,
https://social.technet.microsoft.com/wiki/contents/articles/13876.powershell-2-0-cmdlets.aspx

Powershell v3,
https://social.technet.microsoft.com/wiki/contents/articles/4694.powershell-3-cmdlets.aspx

Hope it helps.

**Comment by Zenidd** [comment]
Hi @sametsazak,

sorry for our late reply!

Thank you very much for the information about the `ConvertFrom-Json` cmdlet on the different Powershell versions. 

I'm closing this ticket because it looks like your doubt has been resolved. If you have any other questions or problems, please do not hesitate to open another ticket and we will assist you.
<br></br>
Greentings,

Juan Pablo Sáez
