### ISSUE TITLE
Validate Wazuh configuration file from API

### ISSUE THREAD

**Issue by druizz90** [wazuh/wazuh#3686]
Hi team,

We added API calls for validating Wazuh configuration (`ossec.conf`, rules and decoders) in older versions (`/manager/configuration/validation`, `/cluster/:node_id/configuration/validation` and `/cluster/configuration/validation`). These endpoints give the result of running `ossec-logtest -t` (it checks if Wazuh configuration is OK in managers).

We want an endpoint for validating Wazuh configuration in agents, the same as `verify-agent-conf` does but through Wazuh API.

An example of a call for validating a Wazuh agent configuration is the next:
```bash
# curl -u foo:bar -k -X PUT -H 'Content-type: application/xml' -d "<agent_config> <!-- Shared agent configuration here --> </agent_config>" "https://127.0.0.1:55000/agents/configuration/validation?pretty"
```

Best regards,

Demetrio.

**Comment by daescar** [comment]
The main purpose of this issue is to validate an agent configuration file that will be provided in the payload of API call. 
To get it we have chosen for validating a temporary config file which we will receive thought `execd` socket. This file will be validated by `verify-agent-conf` call with `-f` option to indicate the file path.
By default, the `verify-agent-conf` binary look for validating a remote config file : `<agent_config> ... </agent_config>`. 

* So, to increase their capabilities we will add another option in order to indicate the validation target whether local or remote. For example : ```verify-agent-conf -f path/to/file -t local```
* The result message will be redirected to output in order to the API can read it.

**Comment by druizz90** [comment]
# Issue update

I am developing a new endpoint for validating agent configurations (`PUT agents/configuration/validation`) which creates a temporary file with the configuration to validate. This temporary file will be validated by `verify-agent-conf` and it response will be the result of this validation.

**Comment by druizz90** [comment]
# Issue update

I am working in branches `dev-verify-agent-conf-3686` (API and framework) for this new call. I hardcoded the result of the validator (it is not available at this moment) but this result should be equal to the final output:

```
# curl -u foo:bar -H 'Content-type: application/xml' -X PUT -d @/agent.conf "https://localhost:55000/agents/configuration/validation?pretty" -k
{
   "error": 0,
   "data": {
      "error": "0",
      "data": [
         {
            "type": "WARNING",
            "message": "The 'vulnerability-detector' module only works for the manager"
         },
         {
            "type": "INFO",
            "message": "WPK verification with CA is disabled"
         }
      ]
   }
}

```

**Comment by AdriiiPRodri** [comment]
Hi team,

We have modified the original endpoint implementation to check if the desired configuration is correct.

As the socket that checks the settings can check **three different types of files**, we have modified the endpoint so that users can validate the one they want.

In this way the endpoint goes from:
```curl -u foo:bar -H 'Content-type: application/xml' -X PUT -d @/agent.conf "https://localhost:55000/agents/configuration/validation?pretty" -k```

to:
```curl -u foo:bar -H 'Content-type: application/xml' -X PUT -d @/agent.conf "https://localhost:55000/configuration/validation/:type?pretty" -k```

Where **type** can be **manager**, **agent** and **remote** as indicated in issue #3731.
We have also modified the output. Now the errors are shown in the following way:

```bash
root@d12a36d4b81b:/# curl -u foo:bar -H 'Content-type: application/xml' -X PUT -d @/var/ossec/etc/shared/default/agent.conf "https://localhost:55000/configuration/validation/remote?pretty&wait_for_complete" -k
{
   "error": 0,
   "data": {
      "status": "KO",
      "details": [
         {
            "type": "ERROR",
            "message": "No XML nodes found on: /var/ossec/tmp/api_group_conf_1574941272_352"
         },
         {
            "type": "CRITICAL",
            "message": "Invalid configuration file"
         }
      ]
   }
}
``` 

All necessary **exceptions** have also been added to account for the **new socket error codes**.

Regards

**Comment by AdriiiPRodri** [comment]
## Status update

We have added the tests of this new endpoint, these are the results:
```bash
root@e3a939bb1e5d:/wazuh-api# mocha ./test/test_configuration.js --timeout 10000


  Configuration
    PUT/configuration/validation/:type
(node:6322) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
      ✓ Request (702ms)
      ✓ Request (348ms)
      ✓ Request (329ms)
      ✓ Request (376ms)
      ✓ Request (329ms)


  5 passing (2s)

```
