### ISSUE TITLE
Let Analysisd support MITRE attack technique IDs

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#3711]
|Epic issue|Branch|
|---|---|
|#3709|[3.10-mitre](https://github.com/wazuh/wazuh/compare/3.10...3.10-mitre)|

We need to extend rule parser to support references to MITRE attack technique IDs.

Example of a MITRE attack technique ID definition:

```xml
<rule id="100001" level="3">
  <description>Attack technique sample.</description>
  <compliance>
    <mitre>T1103</mitre>
    <mitre>T1037</mitre>
  </compliance>
</rule>
```

Sample of an alert related to this rule:
```json
{
  "rule": {
    "level": 3,
    "description": "Ossec server started.",
    "id": "100001",
    "mitre": [
      "T1103",
      "T1037"
    ]
  }
}
```

**Comment by danimegar** [comment]
In order to extend rule parser to support references to MITRE attack technique IDs, I have modified the files rules.c, rules.h and to_json.c from src/analysisd.  

In rules.c I created the element compliance. Then I added a function that read the elements that compliance contain (mitre in this case) and copy the elements in a string vector. 

In json.c I created a string array object with cJSON_CreateStringArray and then I added it to the object rule with cJSON_AddItemToObject.

**Comment by danimegar** [comment]
I created a new rule in /var/ossec/etc/rules/local_rules.xml:

<rule id="100002" level="3">
    <program_name>example</program_name>
    <description>Attack technique sample.</description>
    <compliance>
      <mitre>T1103</mitre>
      <mitre>T1037</mitre>
    </compliance>
  </rule>

When a log comply with rule "100002", an alert in json format is generated like this:

{"timestamp":"2019-07-24T17:28:08.721+0200",
"rule":{
         "level":3,
         "description":
         "Attack technique sample.",
         "id":"100002",
         "mitre":["T1103","T1037"],
         "firedtimes":1,
         "mail":false,
         "groups":["local","syslog","sshd"]},
"agent":{"id":"000","name":"myhost"},
"manager":{"name":"myhost"},
"id":"1563982088.128396",

**Comment by danimegar** [comment]
I run Valgrind to check memory leak:

`valgrind --leak-check=full --trace-children=yes --read-var-info=yes --track-origins=ye--show-leak-kinds=all --read-var-info=yes /var/ossec/bin/ossec-analysisd -f`

No memory leaks found

**Comment by danimegar** [comment]
### Update

Mitre elements aren't considered as a compliance, so the structure of the rule changes:

```
<rule id="100002" level="3">
    <program_name>example</program_name>
    <description>Attack technique sample.</description>
    <mitre>T1103</mitre>
    <mitre>T1037</mitre>
    <compliance>
        <others> ... </others>   
    </compliance>
</rule>
```

**Comment by danimegar** [comment]
I created two files (mitre.c and mitre.h) in _/src/analysisd/_. Mitre.c read the enterprise-attack.json file and create a Hash Table whose keys are MITRE attack technique IDs (e.g. T1122) and the data are the JSON file's object associated with the IDs. In that way, I can select the items more interesting of the object and add them in to_json.c file so that alerts can show more information concerning MITRE attack technique ID.

In addition, analysisd.c have to run the mitre.c only once.

**Comment by danimegar** [comment]
I modified mitre.c and to_json.c so that the alerts can show Mitre information in an appropriate format. 

```
"rule":{
       "level":3,
       "description":"Attack technique sample.",
       "id":"100002",
       "mitre":[
               {"id":"T1122",
                "name":"Component Object Model Hijacking",
                "phases":["defense-evasion","persistence"],
                "platforms":["Windows"]
               },
               {"id":"T1156",
                "name":".bash_profile and .bashrc",
                "phases":["persistence"],
                "platforms":["Linux","macOS"]
               }],
       "firedtimes":1,
       "mail":false,
       "groups":["local","syslog","sshd"]
       },
```
I added two lines in _inst-functions.sh_ so that the Installer make the folder 'mitre' in ruleset and install the mitre json file there.

**Comment by danimegar** [comment]
Now, Wazuh DB should support the MITRE attack technique taxonomy. To do that, I added three tables in Wazuh DB to save the MITRE ATT&CK Matrix. One of them store the complete json object whereas the others store interesting parameters such us the involved platforms or the phase names.

**Comment by danimegar** [comment]
I added a query in Wazuh-DB (/src/wazuh_db/wdb_parser.c) in order to query an attack technique by ID. The next step will be to add an endpoint in the API.

**Comment by danimegar** [comment]
I added two queries more in Wazuh-DB inside wdb_parse_mitre() function (/src/wazuh_parser.c) in order to query an attack technique by platform (Windows, Linux, MacOS) or phase (credential-access, persistence, etc.).

**Comment by danimegar** [comment]
I added a function in wdb_parser.c (**wdb_param_parse()**) to parser the parameters limit and offset. These parameters are store in a struct called **opt_param**. When a Mitre query by Platform or Phase is done, the following sentence will be parsered: 

Example: [limit 10 offset 0] global mitre get_platform Windows 
or
Example: [limit 10 offset 0] global mitre get_phase persistence

In this case, the outputs show 10 json objects with a offset 0.

**Comment by danimegar** [comment]
I have created a script in Python (/tools/mitre/mitredb.py) in order to create the mitre.db. The script reads the enterprise-attack.json (/etc/mitre/enterprise-attack.json) and filles the mitre.db's tables. In that file you can see some examples of use. Then, I modified the Makefile to execute that script so that mitre.db can be installed in {prefix}/var/db.

**Comment by danimegar** [comment]
The best option we thought to implement the **mitre** and **compliance** extension is **B**. To do so, I had modified analysisd/rules.c, analysisd/format/to_json.c and analysisd/mitre.c files.

So, an example of rule is:
```
<rule id="100002" level="3">
    <program_name>example</program_name>
    <description>Attack technique sample.</description>
    <mitre>
      <id>T1169</id>
      <id>T1078</id>
    </mitre>
    <compliance>
      <pci_dss>10.2.5</pci_dss>
      <pci_dss>10.2.2</pci_dss>
      <gpg>13_7.6</gpg>
      <gpg>13_7.8</gpg>
      <gpg>13_7.13</gpg>
      <gdpr>IV_32.2</gdpr>
      <hipaa>164.312.b</hipaa>
      <nist>800_53_AU.3.1</nist>
      <nist>800_53_IA.10</nist>
    </compliance> 
  </rule>
``` 
When an alert is generated, it shows mitre and compliance information. Mitre information consists of a Mitre IDs array and a Tactics array whereas compliance information consists of some ID arrays for each compliance that is in rule. An example of this is:
```

"rule":{
        "level":3,
        "description":"Attack technique sample.",
        "id":"100002",
        "mitre":{
                 "id":["T1169","T1078"],
                 "tactics":["Privilege Escalation","Defense Evasion","Persistence","Initial Access"]
                    },
        "compliance":{
                  "pci_dss":["10.2.5","10.2.2"],
                  "gpg":["13_7.6","13_7.8","13_7.13"],
                  "gdpr":["IV_32.2"],
                  "hipaa":["164.312.b"],
                  "nist":["800_53_AU.3.1","800_53_IA.10"]
                    },
           },
```

**Comment by danimegar** [comment]
We want to add endpoints to query the ATT&CK matrix and others to Wazuh DB so that Wazuh App will show the corresponding data for the alerts. The queries are:

**1. A query that gets more information about a technique that is shown in the alert.** 
As I explained above, alerts will show the ID technique and tactics. The requirements are:
- SQL Sentence: 'mitre get_attack ?', where ? is the ID technique (e.g. T1122, (String)).
- Range of input values is: [T1001 - T1223] and [T1480 - T1501] except T1481. This range can change in the future.  
- Output: 'ok json_object' if the query is successful or 'err ......' if it fails.


**2. A query that gets all techniques's information that include a specific tactic.** 
The requirements are:
- SQL Sentence: '[limit ?? offset ??] mitre get_phase ?', where ? is a tactic (e.g. 'Persistence', 'Privilege Escalation', etc) and ?? is a integer value. Limit should not be greater than 15.
- Possible tactics are:
    -  'Persistence'
    - 'Privilege Escalation'
    - 'Defense Evasion'
    - 'Discovery'
    - 'Credential Access'
    - 'Execution'
    - 'Lateral Movement'
    - 'Collection'
    - 'Exfiltration'
    - 'Command and Control'
    - 'Initial Access'
    - 'Impact'
- Output: 'ok json_objects' if the query is successful or 'err ......' if it fails.

**3. A query that gets all techniques's information that include a specific platform.** 
The requirements are:
- SQL Sentence: '[limit ?? offset ??] mitre get_platform ?', where ? is a platform (e.g. 'Windows') and ?? is a integer value. Limit should not be greater than 15.
- Possible platforms are:
    - 'Windows'
    - 'macOS'
    - 'Linux'
- Output: 'ok json_objects' if the query is successful or 'err ......' if it fails.

**Comment by danimegar** [comment]
### Use case

Mitre Technique [T1110](https://attack.mitre.org/techniques/T1110/) is related to brute force attack. Wazuh has some rules that generate an alert when they detect a possible brute force attack. For example, rule 5712 detects a SSH brute-force attack and generates an alert. This rule 5712 is a special kind of child rule to rule 5710. It will only fire if rule 5710 fires on events involving the same source IP at least eight times in a 120 second period. So, I extend Mitre to rule 5712 as shown below:  

```
<rule id="5712" level="10" frequency="8" timeframe="120" ignore="60">
    <if_matched_sid>5710</if_matched_sid>
    <description>sshd: brute force trying to get access to </description>
    <description>the system.</description>
    <mitre>
      <id>T1110</id>
    </mitre>
    <same_source_ip />
    <group>authentication_failures,pci_dss_11.4,pci_dss_10.2.4,pci_dss_10.2.5,gdpr_IV_35.7.d,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_SI.4,nist_800_53_AU.14,nist_800_53_AC.7,</group>
  </rule>   
```
I opened ossec.conf and added these lines in Log - analysis:
```
<localfile>
    <log_format>syslog</log_format>
    <location>/var/ossec/logs/mitre.log</location>
  </localfile>
```
Then, I created mitre.log and added this line 8 times:
`# echo "Oct 08 02:39:54 linux-agent sshd[30449]: Invalid user blimey from 208.103.56.41 port 51498" >> /var/ossec/logs/mitre.log`

An alert is generated in /var/ossec/logs/alerts/alerts.json:
```
{
    "timestamp":"2019-10-08T13:08:33.160+0200",
    "rule":{
               "level":10,
               "description":"sshd: brute force trying to get access to the system.",
               "id":"5712",
               "mitre":{"id":["T1110"],
                        "tactics":["Credential Access"]
                        },
               "frequency":8,"firedtimes":1,
               "mail":false,
               "groups":["syslog","sshd","authentication_failures"],"pci_dss":["11.4","10.2.4","10.2.5"],"gdpr":["IV_35.7.d","IV_32.2"],"hipaa":["164.312.b"],"nist_800_53":["SI.4","AU.14","AC.7"]
            },
    "agent":{"id":"000","name":"equipo"},
    "manager":{"name":"equipo"},
    "id":"1570532913.405669",
    "previous_output":"Oct 08 02:39:54 linux-agent sshd[30449]: Invalid user blimey from 208.103.56.41 port 51498\nOct 08 02:39:54 linux-agent sshd[30449]: Invalid user blimey from 208.103.56.41 port 51498\nOct 08 02:39:54 linux-agent sshd[30449]: Invalid user blimey from 208.103.56.41 port 51498\nOct 08 02:39:54 linux-agent sshd[30449]: Invalid user blimey from 208.103.56.41 port 51498\nOct 08 02:39:54 linux-agent sshd[30449]: Invalid user blimey from 208.103.56.41 port 51498\nOct 08 02:39:54 linux-agent sshd[30449]: Invalid user blimey from 208.103.56.41 port 51498\nOct 08 02:39:54 linux-agent sshd[30449]: Invalid user blimey from 208.103.56.41 port 51498","full_log":"Oct 08 02:39:54 linux-agent sshd[30449]: Invalid user blimey from 208.103.56.41 port 51498","predecoder":{"program_name":"sshd","timestamp":"Oct 08 02:39:54","hostname":"linux-agent"},
    "decoder":{"parent":"sshd","name":"sshd"},
    "data":{"srcip":"208.103.56.41","srcport":"51498","srcuser":"blimey"},
    "location":"/var/ossec/logs/mitre.log"
}
```
As can be seen, the alert has Mitre information: ID (T1110) ant tactic ("Credential Access").

**Comment by winhigh** [comment]
@danimegar can you just share what exactly you have created or altered in ossec analysied

In order to extend rule parser to support references to MITRE attack technique IDs, I have modified the files rules.c, rules.h and to_json.c from src/analysisd. 

what are the modification you have done - it will hwlp to build my project
