### ISSUE TITLE
Add a configuration validator native in Wazuh modules

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#3731]
|Working branch
|---|
| [#issue3731](https://github.com/wazuh/wazuh/tree/issue3731) |

The goal of this issue is to develop the core part mentioned in https://github.com/wazuh/wazuh/issues/3686 by creating a configuration validator running into Wazuh.
 
After further discussions with the team, we have redesigned this configuration validator on its core side. We have chosen to add a new module, `wm_validator` for that purpose. Moreover, we will add a new binary file (CLI) to validate a configuration file without needing the new module is running.

The idea is that the `validator` module is in charge of validating a temporary configuration file created by the framework. In addition, a new request type will be defined to receive and send JSON requests

The validator target is to test any configuration file such as manager, agent or remote. So, both CLI program and `validator`module must support differents arguments such as : 
* type : manager, agent or remote
* file : the file which will be tested.

### Requirements / Subtasks

- [x] Extend the `TestComponent()` functions to missing components (socket, active-response, etc.)
- [x] Support for validating manager or agent configuration, local (ossec.conf) or remote (agent.conf)
- [ ] Documentation

* **New module:**
- [x] Add the new module `wm_validator`
- [x] Support the `validator`module in the manager
- [x] Define the communication protocol for the module to receive/send validation queries
- [x] Create a new socket for the new module

* **CLI:**
- [x] Add the new binary file
- [x] This program must allow arguments such as : -t (type), -f (file)

* **Input format for the module**

- ``component`` : Specifies the target component for the query. For now, only one value is allowed: ``check_configuration``.
- ``params`` : List of parameters of the query.
  - ``type`` : Specifies the type of configuration to validate. Allowed values are ``manager``, ``agent`` and ``remote``.
  - ``file`` : The path of the file to validate. This is an optional field, by default, it looks for the configuration file at the default route.

Example:

```js
{
    "component": "check_configuration",
    "params":
      {
          "type": "manager",
          "file": "/var/ossec/tmp/ossec.conf"
      },
}
```

* **Output format for the module**

- ``error`` : The error code (integer). Allowed values: 0 (no error) , 1 (error)
- ``data`` : Array with information about the errors found during the validation.
  - ``type`` : Type of log. Allowed values: INFO / WARNING / ERROR / CRITICAL
  - ``message`` : Description of the log. Allowed values: Any string.

**All the fields described above are mandatory.** Here some examples:

```js
{
    "error": 0,
    "data": [
        {
             "type": "INFO",
             "message": "Configuration validated successfully"
        }
    ]
}
```
```js
{
    "error": 0,
    "data": [
        {
            "type": "WARNING",
            "message": "The 'vulnerability-detector' module only works for the manager"
        },
        {
            "type": "INFO",
            "message": "WPK verification with CA is disabled"
        },
        {
            "type": "INFO",
            "message": "Configuration validated successfully"
        }
    ]
}
```
```js
{
    "error": 1,
    "data": [
        {
            "type": "ERROR",
            "message": "Invalid value for element 'alerts_log': perhaps"
        },
        {
            "type": "CRITICAL",
            "message": "Configuration error at '/var/ossec/etc/ossec.conf'"
        }
    ]
}
```

**Comment by daescar** [comment]
First steps : 
* New functions have been added in `wm_module.c` : 
  **verify_manager_conf** and **verify_agent_conf**. 
The purpose of these functions is to validate the manager or agent configuration file. To do it we will use the `TestComponent` functions which will be specific to each of them.
* New function declarations have been added in `config.h`: `Test_SCA`, `Test_ActiveResponse` and `Test_Socket`
* `Test_Socket`definition was added in `socket-config.c`file.
* `Test_ActiveResponse` definition was added in `active-response.c` file

All of the above changes are in progress. We're working on them.

**Comment by daescar** [comment]
New changes : 
* Test_SCA function has been removed since the SCA module is being checked in `Test_WModule`
* Similarly, the 'Test_Socket` function has been removed because the socket configuration is being checked in 'Test_Localfile' function
* We added the next new functions to `wm_control.c` in verify_manager_conf:
        `Test_Authd` ; `Test_Remoted` ; `Test_Execd` and `Test_Analysisd`
   In order to extend the control module capabilities by adding a manager configuration validator. 
   So, we will avoid the calling to the rest of daemons with -t option.
* Finally, a few useful functions such as: `Free_OSList`, 'free_remoted' and 'free_authd_config' have been added. These functions aim to free the memory was reserved dynamically for their correspondent structures

**Comment by daescar** [comment]
New changes :
* The `verify_manager_conf` from `wm_control.c` has been extended with : 
    - `Test_Syscheck`
    - `Test_Rootcheck`
    - `Test_Integratord`
    - `Test_Maild`

* In order to free the memory was reserve dynamically for `Integratord Config` and `Mail Config` we have added new functions such as : `free_integratord` and `freeMailConfig` 

[Related commit](https://github.com/wazuh/wazuh/commit/189f1fe78ebf0a4905082f9df65b1e08d5ba3a1c)

**Comment by daescar** [comment]
Latest changes : 

* The functions `Test_Agentless` and `Test_DBD` was added to `verify_manager_conf`.
* In order to free the memory reserved dynamically: `free_dbdConfig` and `free_AgentlessConfig` functions was added too.
* `free_MailConfig` was improved.
* We have not added any function to check the `clusterd` since it is checked within `analysisd`
* On the other hand, the `Test_Maild` function aims to check the email configuration. So,  `Read_Config` is called once instead of two times as happened before. Since the `Read_Config` function is called with the `CMAIL`flag, it will check both `global` and `granular` email configurations

[Related commit](https://github.com/wazuh/wazuh/commit/0058fa0113bc2a3019055334b81ca177c93f29ca)

**Comment by daescar** [comment]
New changes : 
* The `free_dbdConfig` was completed.
* The called to `Test_ActiveResponse` function was added to `verify-manager-conf` function.
* `Test_CSyslogd` was created. However, it is not being used at the moment. Since, `CheckManagerConfiguration` from `execd.c` did not invoke the `csyslogd -t` daemon either.
* The `Test_DBD` and `free_dbdConfig` functions were moved to the `dbd-config.c` file.
* By the way, the `Test_Maild` and `freeMailConfig` functions were moved to the new file called `mail-config.c`
* `Test_Analysisd` is now defined  in the `config.c` file.
* The `Test_Execd` function must be redefined. This function will perform in a similar way to `ExecdConfig` function from `os_execd/config.c`.
*  `wm_control_main` has been modified in order to support different requests by `CONTROL_SOCK`. This requests are : `get-notify-ip` , `check-manager-configuration` and `check-agent-configuration`
* So, `send_ip()` has been deprecated.
* 

Related commits : 
[commit 1](https://github.com/wazuh/wazuh/commit/0a51c6450b25c338c953b50c9670b8af612b3458)
[commit 2](https://github.com/wazuh/wazuh/commit/f07144e8eb13aa442d99fa96c992fc4c012b1a2a)
[commit 3](https://github.com/wazuh/wazuh/commit/bca488087dcd369fc5125351d6b21af751428154)

**Comment by daescar** [comment]
Latest changes : 

* The `looking_for_cfgfile` function was added in order to check whether the file provided already exists.
* `msg_to_json` function has been added to get the output as a json message.
* At the moment, the test result is being sent to `ossec.log` by merror function.
  Now, this result must be redirected to stderr or another log file in order to catch this message and    
  send to the above function: `msg_to_json` 

Related [commit](https://github.com/wazuh/wazuh/commit/24fb9c82078992a58e09fd3fca705813b2bbc9c7)

On the other hand, we are researching different alternatives to deploy this feature (config validator) such as: 
* Build a new module to deploy the configuration validator instead of using the control module
* Build a new binary file in order to validate a configuration file with no need to any wazuh-module is started.

**Comment by daescar** [comment]
Hi team!

In relation to the [new update of this issue](https://github.com/wazuh/wazuh/issues/3731#issue-472133815), the following changes have been made:

* Reverting changes made for: wm_control, wmodules, agentd, notify and verify-agent-conf.
  In order to keep the initial capabilities of these components.

* A new macro has been added: `CLOCAL_CONFIG`
* The `CAGENT_CONFIG` has been renamed to `CRMOTE_CONFIG` 
  These changes have been made in order to ReadConfig is able to differentiate the type of 
  the configuration file is reading.

* A new param (type), has been added to the `Test_Component()` functions shared between     
  manager and agent. This param will be provided to ReadConfig to differentiate the type of the 
  configuration file will be read, as we mentioned before.

* `verify-agent-conf` has been deprecated. Now, a single message will be shown, 
   "Use validator-config instead."

[Related commit](https://github.com/wazuh/wazuh/commit/d95a8502dd58816d72380e4ebf8d3db059e5ef6c)

**Comment by daescar** [comment]
Hi again!

In this [commit](https://github.com/wazuh/wazuh/commit/f336d881112e7938199ec77979e7eaf542a5d00e), the next changes have been made:

* wazuh_validator binary file has been created for that purpose the files below have been added too: `validator.c` `validator.h` `wazuh_validator.c`

* `Read_WModule` function has been modified. In order to know what kind of configuration file is being tested, a new param, `cfg_type`, was added. Since, some modules such as azure-logs, agent-key-polling, aws-s3 or vulnerability-detector are not present in the agent side

* Due to the above change `read_main_elements` was also modified in order to notify to `Read_WModule` the configuration filetype.

* The `free_remoted` function was improved to avoid a potential segmentation fault.

* Moreover, `test_manager_conf`, `test_agent_conf` and `test_remote_conf` have been split in order to get more control over them (possible future developments) and a clearer code. However, they are susceptible to merge into one, and differentiate them by `type`.

Now, we are testing different configuration files by `wazuh_validator`.

**Comment by daescar** [comment]
We have been working on the following changes: 

* ReadConfig function has been modified in order to exit whenever an unknown attribute is found while testing a `remote` config file.

* New error messages have been added to `defs.h` such as `CONF_READ_ERROR` and `XML_INV_TARGET`

* Test_Localfile function has been modified in order to check `socket` along with `localfile`. Moreover, `agent_cfg` and `accept_remote` are set to `1` when a remote file is being tested.

* Test_Maild was modified to check that log source matches with mailconfig and globalconfig.

* Test_Remoted was improved by initializing the remote structure. In addition, the possible error messages were also improved.

* Read_WModule function was modified to issue an error if an unknown module is found.

* The CLI bin was added to </wazuh/installdir>/bin

* A new module was created: `wm_check_config`
* A new socket for the above module, was created: `CHK_CONF_SOCK`
* The new module was added to `wmodules.c`

[Related commit](https://github.com/wazuh/wazuh/commit/7ab12e73b9977043d58ad49845532113c5cec658)

**Comments**
Currently, we are testing the new tool and the new module. 
The new module will always be on, waiting for a specific request in JSON format.
When a valid request is received by the module's socket, the check_configuration binary file will be launched to test the file provided. 
The test result will be returned by the socket as a JSON message.

**Comment by daescar** [comment]
**Current issue situation**

* The CLI bin file is completed and works as expected. Different configuration files could be tested according to `-t` option: (provided when the CLI is run) manager, agent or remote. 
These tests are made by calling to `test_manager_conf`, `test_agent_conf` or `test_remote_conf`, respectively. The `-f`option will be used to provide a configuration file to be tested, when this option is not present, the default configuration file (ossec.conf or agent.conf) will be checked.

* Currently, the check_config wazuh module is able to check any configuration file. For that purpose, the module will always be on, waiting for a specific request in JSON format by the check_config socket. If a valid request is received, the configuration file provided or default config file when any file is provided, will be tested by calling the CLI binary file.
The test result is captured and returned by the check_config socket.

**Changes suggested**

Currently, the error, warning and info messages are written to both, ossec.log and standard output when CLI is used. On the other hand, when `wm_check_config` is used these messages are only written to ossec.log.

- [ ] In order to improve this behavior, it could be interesting add to ReadConfig and Read__Component_ functions another variable as `char **output` to capture this messages. 

- [ ] Since the CLI binary cannot be launched for this module, the `test_file` function must be modified.
This function must call to `test_manager_conf`, `test_agent_conf` or `test_remote_conf` according to the filetype provided.

After this, the way the JSON message is built and sent to the API can be kept.

**Comment by carlocas** [comment]
Hi team!

We have been working in the next changes:

* The errors, warning and info messages were written in the ossec.log, and in the standard output, when the CLI is used. With the new commit if we used the CLI only will be written in the standard output.

* Also, we have modified  `test_file ` to call the functions `test_manager_conf`, `test_agent_conf` and `test_remoted_conf`. In `test_file`, we check the type of the configuration file to call the right function.

**Comments**
Currently, we are testing the new tool and the new module with the new changes. that this commit introduces. 

[Related commit](https://github.com/wazuh/wazuh/commit/9dbf89f2c7080bad6cc74b91f5d1c9b8e3f57ddf)

**Comment by carlocas** [comment]
Hi team!

We have been working on resolving several memory leaks. This memory leaks appeared because of the functions used by the validator were not configurated to only read the files. There were, also, configurated to initialized global variables, and some of these variables were expected to continue working in the program. But in the current case, that is not the desired behavior.

To resolve this memory leaks, we used gdb and Valgrind to follow every memory leaks until the Valgrind report shows that we don't have any memory leak.

[Related commit](https://github.com/wazuh/wazuh/commit/f183b3c9b756b65c857e219271913d8069abef6b)

**Comment by carlocas** [comment]
Hi team!

We have been working on the next changes:
* `Read_Cluster` has been modified to check if the cluster is working. If the cluster is active, other components will be checked to ensure that the configuration is valid.
* Several memory leaks were resolved. These memory leaks appeared when we don't close a field in the configuration fields, and when the validator encountered an error.
* The variable output has been added to the modules osquery,  oscap, syscollector, and command. 

Currently, we are working on the JSON input/output format of the module. The format for input and output are shown below. 

The input format:
```
  "operation": "GET",
  "type": "request",
  "version": "3.10",
  "component": "check_configuration",
  "data": 
    {
      "type": "manager",
      "file": "/var/ossec/etc/ossec.conf"
    },
}

```
And the output format:
```
{
  "error": "0",
  "data": [
    {
      "type": "WARNING",
      "message": "The 'vulnerability-detector' module only works for the manager"
    },
    {
      "type": "INFO",
      "message": "WPK verification with CA is disabled"
    }
  ]
}
```
Related commit
[commit1](https://github.com/wazuh/wazuh/commit/63535952869fec0a661f9b16bdf1ab01652ed1fe)
[commit2](https://github.com/wazuh/wazuh/commit/dd0194f5d9295789c7fee716940bbeeef82d3ae7)
[commit3](https://github.com/wazuh/wazuh/commit/67489cec227509ff8b923d54e456c530b8babb17)

Regards.

**Comment by carlocas** [comment]
Hi team:

We have been working on the next changes:
* Resolve the memory leaks that appeared when duplicating blocks of the configuration one after other.
* Also, resolve the memory leaks that occurred when specified tags were duplicated, inside some blocks of the configuration. An example of that is the following configuration:
```XML
  <cluster>
    <name>wazuh</name>
    <node_name>node01</node_name>
    <node_type>master</node_type>
    <key></key>
    <port>1516</port>
    <bind_addr>0.0.0.0</bind_addr>
    <nodes>
        <node>NODE_IP</node>
    </nodes>
    <hidden>no</hidden>
    <disabled>yes</disabled>
    <name>wazuh</name>
    <node_name>node01</node_name>
    <node_type>master</node_type>

  </cluster>
```
* Improve the readability of the code, for that we change some functions for others more easy to read.
* Fix a bug in `email_alerts-config` that provoked an infinity loop, and allocated memory to a variable inside. 
* Working in the documentation of the validator.

Related commits:
[Repeated block](https://github.com/wazuh/wazuh/pull/4139/commits/c9c389d61663b114e0f899fc4df0fe7782543d2c)
[Repeated tags](https://github.com/wazuh/wazuh/pull/4139/commits/d16057b681e7396ef8740d86bcc5dec941d378d5)
[Bug](https://github.com/wazuh/wazuh/pull/4139/commits/4c23dc3582e208aef035c61a4bb61512c341fba3)

Regards

**Comment by carlocas** [comment]
Hi team:

We have been working in the next changes:

* Fix memory leaks that appeared when we have some empty tags.
* Check the output messages after the rebase to 3.11. Some messages appeared in ´ossec.log´, We fixed that no message was found in `ossec.log`.
* Also, we have been working in a series of tests to check different types of configurations. This test will check the possible memory leaks that still would have the validator. 

Related commits:

[ab91ca](https://github.com/wazuh/wazuh/pull/4139/commits/ab91cab445fc160fd2d72d6af206a2b5e6823bf1)
[50feafb](https://github.com/wazuh/wazuh/pull/4139/commits/50feafb6adb8f4ab73887976a5da087161e852f0)
[e5ec74](https://github.com/wazuh/wazuh/pull/4139/commits/e5ec742ad0e433b42966fc0f366a72c192fb9e0f)
[65f9a5](https://github.com/wazuh/wazuh/pull/4139/commits/65f9a58cddb251e3ae25a3c85e9b35e39ba56f0e)

Regards, Carlos

**Comment by Molter73** [comment]
In order to better handle errors between the API and the validator the following values will be returned in the error field when something goes wrong:
- 0: Configuration validated succesfully.
- 1: Error during validation of given configuration file.
- 2: Request size bigger than expected.
- 3: Unable to receive the input message due to a socket error (a message field could be added to this response in order to provide more information).
- 4: Empty input message received.
- 5: Invalid input message.
- 6: Requested file does not exist.
- 7: Requested "type" for validation is neither of manager, agent or remote.

Any input on this subject is welcome.
