### ISSUE TITLE
How to check/print the source logs from remoted deamon?

### ISSUE THREAD

**Issue by heejunfeng** [wazuh/wazuh#3734]
I have add below part to ossec.conf, and I make the firewall(10.0.9.3) send event logs to the manager IP:514(tcpdump cat get the event logs normally from the IP:514),but I can't get any result in kibana.
  <remote>
    <connection>syslog</connection>
    <port>514</port>
    <protocol>udp</protocol>
    <allowed-ips>10.0.9.0/24</allowed-ips>
  </remote>

**Comment by Zenidd** [comment]
Hi again @heejunfeng, 

I'm closing this ticket due to inactivity. If you need more help, please don't hesitate to reopen this ticket or open a new one.

If you want to chat with us directly, please join Slack: https://wazuh.com/community/join-us-on-slack.

We will happy to help you in the Community channel.

Greetings, Juan Pablo Sáez

**Comment by Daulet-AlmatyKZ** [comment]
hello!!! I'm testing Wazuh virtual machine. During testing included a localfile. But vazuh does not see files. Also, does not see syslogs. why??
I'm sending your screenshots of the settings.
![archives log](https://user-images.githubusercontent.com/55727526/65500644-6bda7e80-dee1-11e9-849c-e5d21dd60a92.JPG)
![ossec_config_localfile](https://user-images.githubusercontent.com/55727526/65500645-6bda7e80-dee1-11e9-8db0-5aad2b5acde6.JPG)
![ossec_config_log collection](https://user-images.githubusercontent.com/55727526/65500647-6c731500-dee1-11e9-88a3-ace03f254ee5.JPG)
![ossec_config_remote](https://user-images.githubusercontent.com/55727526/65500648-6c731500-dee1-11e9-975b-a07c02099e06.JPG)
