### ISSUE TITLE
Suricata integration in wazuh

### ISSUE THREAD

**Issue by sasam3l4** [wazuh/wazuh#3756]
In the documentation theres a sentence " Set up Suricata on both elastic-server and linux-agent".
Do i have to install suricata in every agent?

Thank you,
samela

**Comment by Zenidd** [comment]
Hi again @sasam3l4,

I'm closing this ticket due to inactivity. If you have any questions or we can help you with anything else, feel free to reopen this ticket or open a new one.

Also If you want to chat with us directly, please join Slack: https://wazuh.com/community/join-us-on-slack.

We will happy to help you in the Community channel.

Best regards, Juan Pablo Sáez
