### ISSUE TITLE
Possible memory leak on Docker module

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh#3764]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.4-3932 | wazuh-modulesd/docker | Agent | Packages/Sources | CentOS 7 |

Hi team,

While testing the packages from `v3.9.4-rc2` tag, we found a possible memory leak on the `docker` module from `wazuh-modulesd`. Here you can find an image showing the RSS used by `wazuh-modulesd` only with this module running.

![image](https://user-images.githubusercontent.com/9081114/62030032-69f78600-b1e4-11e9-9e22-da9dd049f94d.png)

Regards.

**Comment by vikman90** [comment]
## Configuration
```xml
<wodle name="docker-listener">
  <attempts>200</attempts>
  <run_on_start>no</run_on_start>
  <disabled>no</disabled>
  <interval>1s</interval>
</wodle>
```

## Explanation

The Docker integration uses `wm_exec()` to run the integration. `wm_exec` stores the output of the integration up to 64 MiB, that's why the memory grows.

The output of the integration is useful only if it exits with an error. If the size of the output reaches 64 MiB, the module will print this error and restart the integration:
```
2019/07/29 12:05:19 wazuh-modulesd: WARNING: String limit reached.
2019/07/29 12:05:19 wazuh-modulesd:docker-listener: WARNING: Returned exit code 1
2019/07/29 12:05:19 wazuh-modulesd:docker-listener: ERROR: OUTPUT: (64 MiB string)
```

## Fix

We would get rid of this issue if we changed the call to `wm_exec()` to `wpopen()`.
