### ISSUE TITLE
vulnerability-detector Error in 3.9.3

### ISSUE THREAD

**Issue by ericlee0517** [wazuh/wazuh#3777]
I started the wazuh-server and I found this in ossec.log
![image](https://user-images.githubusercontent.com/52303393/62109059-18332680-b2de-11e9-81d8-2281289d2d2c.png)
Here is my config in server:
![image](https://user-images.githubusercontent.com/52303393/62109095-2a14c980-b2de-11e9-93b8-2b8b1e2ff133.png)
I can not figure out why this happened.

**Comment by crolopez** [comment]
Hi @ericlee0517,

The reason for the error is you are configuring the old feed format for Red Hat. The OVAL file for this system is not supported by Wazuh since 3.8.0 version.

In that release, Vulnerability Detector began using the Red Hat Security Data API as vulnerabilities feed, which significantly improves the report accuracy.

If you want to deploy an offline update, you must generate a single feed file by concatenating the API response pages. To do this, you can use a script as follow:

``` BASH
#!/bin/bash

# Wazuh script to generate a Vulnerability Detector's feed for Red Hat systems
# Copyright (C) 2015-2019, Wazuh Inc.
# January 4, 2018.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

page=1
last_page=0
year=$1
output="./rh-feed.json"

if [ $# -ne 1 ]
then
    echo "Use: $0 <min_year>"
    exit 1
fi

echo -e "[" > $output

while [ true ]
do
    link="https://access.redhat.com/labs/securitydataapi/cve.json?after=$year-01-01&per_page=1000&page=$page"
    file=redhat-feed$page.json
    if [ $last_page -ne $page ]
    then
        echo "Fetching $link"
    fi

    last_page=$page
    result=$(curl -O assets/content.json $link --output $file --silent -w '%{http_code}')

    if [ $result -ne 200 ]
    then
        echo "Page download failed ($result), retrying..."
        rm -f $file
        continue
    fi

    content=`cat $file`
    if [[ $content == "[]" ]]
    then
        rm -f $file
        break
    fi

    if [ $page -ne 1 ]
    then
        echo -E "," >> $output
    fi

    echo "${content:1:-1}" >> $output

    page=$[ $page + 1 ]
    rm $file
done

echo -e "]" >> $output

exit 0
```

Best regards.

**Comment by crolopez** [comment]
Hi @ericlee0517,

I'm going to close this issue due to inactivity. If you have any questions or we can help you with anything else, feel free to reopen it.

Best regards.
