### ISSUE TITLE
Realtime syscheck alerts are not queued if agent is offline

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh#3811]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.4-3936 | syscheck | Agent | Packages | CentOS 7 |

## Issue
Changes to files being monitored in realtime are not queued to be sent if an agent is not being able to send messages to the manager, but before it has declared itself offline, so this information is lost. 

## Steps to reproduce
1. Configure the syscheck module to monitor a directory in realtime on an agent.
2. Disconnect the wazuh-manager (or stop the service).
3. Promptly make changes to the folder being monitored on the agent.
4. Reconnect the manager.
5. Verify that new changes will be reported but not the ones that occured during disconnection.

## Additional information
Setting `syscheck.debug=2` in the agent's `local_internal_option.conf` file (or running the daemon in the foreground with `-fdd` will show that the messages are allegedly sent immediately instead of being queued:
```
2019/08/07 16:22:36 ossec-syscheckd[12563] run_check.c:48 at send_syscheck_msg(): DEBUG: (6310): Sending msg to the server: '29:33188:0:0:73e5cf171c157303fbf3d7721cda0b06:3246edcd867ee11fea5b840f694062dd6184b928:root:root:1565194956:378339:caf52b1325afaed61cf03370d017ca644bc67e5ffb8a29385404816889b2ce0f:0!::::::::::::: /etc/testfim'.
```
This will happen whether or not the agent has already stated in it's `ossec.log` file that it has not been able to send a message to the server 
```
2019/08/07 16:21:54 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
```
But not if it has already stated that the agent is offline. 
```
2019/08/07 16:25:15 ossec-agentd: WARNING: Server unavailable. Setting lock.
2019/08/07 16:25:15 ossec-agentd: WARNING: Process locked due to agent is offline. Waiting for connection...
2019/08/07 16:25:16 ossec-logcollector: WARNING: Process locked due to agent is offline. Waiting for connection...
```
However after the process is locked not all changes are reported (I've tested making many changes, restarting the manager and after re-connection only two alerts are generated, no matter how many changes occurred). 
And in this case the debugging information is less clear as it does not generate a message for each event)

**Comment by jotacarma90** [comment]
Hi jctello,

I have been reproducing this issue, and effectively, thereis a few seconds in which events are being missed.

### Sequence of steps:

- Manager and agent ON:
No problems, events appear normally.
- Manager OFF, agent has not yet realized that the manager is down:
Events appear in the agent's log, but since the manager is down, they are not reaching him, **and they are not being queued.**
- Agent realizes that manager is down.
At this point, a message appears in the agent's log: 
`ossec-agentd[6731] notify.c:96 at run_notify(): WARNING: Server unavailable. Setting lock.`
Then, agent stops showing the events. But they're being queued.
-Manager ON again:
Both in the agent's log and in the manager's alerts, all the events in the queue appear.

### Conclusion
Well, the problem is the time it takes for the agent to realize that the manager is offline

There is a variable in ossec.conf `notify_time` (seconds) with which you can lower the frequency with which the agent checks the connection with the manager. This way, you will get to lose less events.
In addition, the `time-reconnect` (seconds) variable regulates the frequency of the request by the agent to reconnect.
