### ISSUE TITLE
Failure to monitor directories in real-time when configuring Windows audit policies.

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#3812]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.4 | Syscheck | Agent | Packages/Sources | Windows |

We have found an error in which we can remain without monitoring a directory in real-time (configuring _Whodata_ mode) in case the call that configures the Windows audit policies fails.

https://github.com/wazuh/wazuh/blob/bb811ff3372208024f63ef8a65b0d507487e33db/src/syscheckd/win_whodata.c#L1113

During the initialization of the _Whodata_ engine the Windows audit policies are established, if at this point an error occurs by which these policies cannot be established we must change the monitoring to "Real-time" mode, so at least, we will keep these directories monitored. 

https://github.com/wazuh/wazuh/blob/bb811ff3372208024f63ef8a65b0d507487e33db/src/syscheckd/win_whodata.c#L333-L340

**Comment by Lopuiz** [comment]
Hello team,

`set_policies` isn't the only function that can fail in the initialization of the Whodata engine.

Function `fim_whodata_initialize` start Whodata engine. First, set SACLs calling  `realtime_adddir`. Then, call `run_whodata_scan` to set policies and whodata callback. Finally, it creates the `state_checker` thread.

https://github.com/wazuh/wazuh/blob/c4f7457782312b7d81bf4563060e85e43ef737f7/src/syscheckd/run_check.c#L415-L446

The first issue happens when `run_whodata_scan` fails. SACLs don't remove from the directories. The second issue is realtime doesn't monitor these directories.

Have Wazuh monitor the directories when `set_policies` fail is an incomplete solution. The function `run_whodata_scan` does two things:

https://github.com/wazuh/wazuh/blob/c4f7457782312b7d81bf4563060e85e43ef737f7/src/syscheckd/win_whodata.c#L338-L375

What would happens if `EvtCreateRenderContext` or `EvtSubscribe` fail? Realtime doesn't monitor the directories because only do if `set_policies` fails

Additionally, set SACLs can fail, and Wazuh neither monitors directories in realtime.

**Solution:**
If `run_whodata_scan` fails Wazuh has to:
1. Restore the SACLs to the original state.
2. `state_check` mustn't be created.

If `win_sacl` fails, the directory must be monitored by Realtime.

Best regards,
Eva
