### ISSUE TITLE
Update RPM and other Packege Repositorys

### ISSUE THREAD

**Issue by FloThinksPi** [wazuh/wazuh#382]
At least the RPMs for RHEL7 are 2.1.1 and thus old when looking at the releases from github.
May i ask that someone could go over the Repositorys and upload the latest versions ?

https://packages.wazuh.com/yum/rhel/7Server/x86_64/

**Comment by BraulioV** [comment]
Hi @FloThinksPi,

since we released Wazuh 3.0, we made a changed in our repositories structure. We decided to create a new repository in https://packages.wazuh.com/3.x. In this folder, you can find:
- `.deb` packages: https://packages.wazuh.com/3.x/apt
- `.rpm` packages: https://packages.wazuh.com/3.x/yum
- `.rpm` for CentOS/RHEL 5: https://packages.wazuh.com/3.x/yum/5

The packages stored in https://packages.wazuh.com/yum, are for Wazuh 2.x. You can check the new repositories in https://documentation.wazuh.com/current/installation-guide/index.html and all the packages list in https://documentation.wazuh.com/3.x/installation-guide/packages-list/index.html.

Regards,  
Braulio.

**Comment by FloThinksPi** [comment]
Ah thanks @BraulioV
