### ISSUE TITLE
Feature request: Compound rules/Event correlation. 

### ISSUE THREAD

**Issue by SpotHound** [wazuh/wazuh#3852]
Hello team!

We are aware of the need for some users to be able to generate composite rules that trigger only if two different alerts have been triggered in in a given period of time.

For example, given the two following rules:

```
 <rule id="86621" level="3">
    <if_sid>86601</if_sid>
    <field name="alert.signature_id">^2001219$</field>
    <description>Suricata: ET SCAN Potential SSH Scan.</description>
    <options>no_full_log</options>
  </rule>

 <rule id="5715" level="3">
    <if_sid>5700</if_sid>
    <match>^Accepted|authenticated.$</match>
    <description>sshd: authentication success.</description>
    <group>authentication_success,pci_dss_10.2.5,gpg13_7.1,gpg13_7.2,gdpr_IV_32.2,</group>
  </rule>
```

We would like to generate the following one:

```
<rule id="40112" level="12" timeframe="300">
    <description>Multiple authentication failures followed </description>
    <description>by a success.</description>
   <group>pci_dss_10.2.4,pci_dss_10.2.5,pci_dss_11.4,gpg13_7.1,gpg13_7.8,gdpr_IV_35.7.d,gdpr_IV_32.2,</group>
  </rule>
```

Only if the two given rules have been triggered in the timeframe selected in the compound rule and (in this case) the source ip of both alerts is the same.

We propose to discuss the feasibility of such functionality and to raise support in the future.

Best regards.

**Comment by Canon88** [comment]
Hello，team：
      Compare the fields of different events by adding a temporary field.  I am not a developer, this is just an idea of mine, I hope it can help.

**Comment by jctello** [comment]
To clarify, this is in fact a current feature of the software and the rule provided as an example is part of the default rules found [here](https://github.com/wazuh/wazuh/blob/v4.0.4/etc/rules/0280-attack_rules.xml#L101-L112)
```
  <rule id="40112" level="12" timeframe="240">
    <if_group>authentication_success</if_group>
    <if_matched_group>authentication_failures</if_matched_group>
    <same_source_ip />
    <description>Multiple authentication failures followed </description>
    <description>by a success.</description>
    <mitre>
      <id>T1078</id>
      <id>T1110</id>
    </mitre>
    <group>pci_dss_10.2.4,pci_dss_10.2.5,pci_dss_11.4,gpg13_7.1,gpg13_7.8,gdpr_IV_35.7.d,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,nist_800_53_SI.4,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>
  </rule>
```
This will be triggered when any rule from the `authentication_failures` group is triggered followed by one from the `authentication_success` group. This can be easily tested by providing a wrong password to a machine 8 times in less than two minutes and then providing a correct password in the following 4 minutes.

If you wish to use specific rules instead of groups of rules you may use `<if_sid>` instead of `<if_group>` and `<if_matched_sid>` instead of `<if_matched_group>`.

I proceed to close this issue.
