### ISSUE TITLE
Cannot set srcip as a domain name in rule

### ISSUE THREAD

**Issue by joey1a2b3c** [wazuh/wazuh#3871]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.5.1 | Wazuh Manager | Manager | apt | Ubuntu |

`decoder-name: web-accesslog`
`rule.id: 31516`
`Full-log: somedomain.example.ca - - [22/Aug/2019:15:04:32 -0600] "GET /server-status?auto HTTP/1.1" 200 1495 5365 1276 "-" "Mozilla/4.0 (compatible; MSIE 6.0)" ` 

Wazuh manager can generate an alert with data.srcip="somedomain.example.ca", but if I tried to create a custom rule to add this name to exception, 
`  <rule id="100002" level="3">`
` <srcip>somedomain.example.ca</srcip>`
 ` </rule>`
it give me an error
`ossec-testrule: ERROR: (1237): Invalid ip address: 'somedomain.example.ca'`

**Comment by Zenidd** [comment]
Hi @joey1a2b3c,

> `<srcip>somedomain.example.ca</srcip>`

The [srcip](https://documentation.wazuh.com/3.9/user-manual/ruleset/ruleset-xml-syntax/rules.html#srcip) field, as our documentation states, can only contain `Any IP address or CIDR block to be compared to an IP decoded as `srcip`.` In this case, you are trying to enter alphanumeric values and that is causing the error. 

On the other hand, the event you pasted as an example lacks a `srcip` field:

```
# /var/ossec/bin/ossec-logtest

somedomain.example.ca - - [22/Aug/2019:15:04:32 -0600] "GET /server-status?auto HTTP/1.1" 200 1495 5365 1276 "-" "Mozilla/4.0 (compatible; MSIE 6.0)"


**Phase 1: Completed pre-decoding.
       full event: 'somedomain.example.ca - - [22/Aug/2019:15:04:32 -0600] "GET /server-status?auto HTTP/1.1" 200 1495 5365 1276 "-" "Mozilla/4.0 (compatible; MSIE 6.0)"'
       timestamp: '(null)'
       hostname: 'nanoPill'
       program_name: '(null)'
       log: 'somedomain.example.ca - - [22/Aug/2019:15:04:32 -0600] "GET /server-status?auto HTTP/1.1" 200 1495 5365 1276 "-" "Mozilla/4.0 (compatible; MSIE 6.0)"'

**Phase 2: Completed decoding.
       decoder: 'web-accesslog'
       srcip: '-'
       protocol: 'GET'
       url: '/server-status?auto'
       id: '200'

**Phase 3: Completed filtering (rules).
       Rule id: '31516'
       Level: '6'
       Description: 'Suspicious URL access.'
**Alert to be generated.



```

If you paste here some more events and explain us your use case, we can help you with the Wazuh manager tuning. 

Please, let me know if it helps! Greetings, 

Juan Pablo Sáez

**Comment by Zenidd** [comment]
Hi @joey1a2b3c,

Thank you for this point. The `ossec-logtest` tool is now able to pàrse the `srcip` field from the log. It gets filled with the DNS at the log beginning:

```
**Phase 1: Completed pre-decoding.
       full event: '- somedomain.example.ca - - [22/Aug/2019:15:04:32 -0600] "GET /server-status?auto HTTP/1.1" 200 1495 5365 1276 "-" "Mozilla/4.0 (compatible; MSIE 6.0)"'
       timestamp: '(null)'
       hostname: 'nanoPill'
       program_name: '(null)'
       log: '- somedomain.example.ca - - [22/Aug/2019:15:04:32 -0600] "GET /server-status?auto HTTP/1.1" 200 1495 5365 1276 "-" "Mozilla/4.0 (compatible; MSIE 6.0)"'

**Phase 2: Completed decoding.
       decoder: 'web-accesslog'
       srcip2: '-'
       srcip: 'somedomain.example.ca'
       protocol: 'GET'
       url: '/server-status?auto'
       id: '200'

**Phase 3: Completed filtering (rules).
       Rule id: '31516'
       Level: '6'
       Description: 'Suspicious URL access.'
**Alert to be generated.
```

Unfortunately, the `<srcip>` field [ only admits numbers, points and bars](https://github.com/wazuh/wazuh/blob/0038e09fcfe1118d3ea69cbfc5ef3e851f2c135e/src/shared/validate_op.c#L315-L345). If we try to enter alphanumeric values, as you can see, the following error pops up:
```
2019/08/27 08:20:37 ossec-testrule: ERROR: (1237): Invalid IP address: 'aaaa.a.a.a'.
2019/08/27 08:20:37 ossec-testrule: CRITICAL: (1220): Error loading the rules: 'etc/rules/local_rules.xml'
```
<br></br>
I propose you two workarounds to generate alerts based on these events DNS:

- Using [Regex](https://documentation.wazuh.com/3.x/user-manual/ruleset/ruleset-xml-syntax/rules.html#regex) field. You can enter any [regex expression](https://documentation.wazuh.com/3.x/user-manual/ruleset/ruleset-xml-syntax/regex.html) to match against the log event. This way you can set domains or subdomains to trigger the rule using regex expressions. You have an example below:
```XML
<rule id="100002" level="3">
   <if_sid>31516</if_sid>
   <regex>somedomain.example.ca</regex>
   <description>Test rule 0</description>
</rule>
```
Output on ossec-logtest:
```
**Phase 1: Completed pre-decoding.
       full event: '- somedomain.example.ca - - [22/Aug/2019:15:04:32 -0600] "GET /server-status?auto HTTP/1.1" 200 1495 5365 1276 "-" "Mozilla/4.0 (compatible; MSIE 6.0)"'
       timestamp: '(null)'
       hostname: 'nanoPill'
       program_name: '(null)'
       log: '- somedomain.example.ca - - [22/Aug/2019:15:04:32 -0600] "GET /server-status?auto HTTP/1.1" 200 1495 5365 1276 "-" "Mozilla/4.0 (compatible; MSIE 6.0)"'

**Phase 2: Completed decoding.
       decoder: 'web-accesslog'
       srcip2: '-'
       srcip: 'somedomain.example.ca'
       protocol: 'GET'
       url: '/server-status?auto'
       id: '200'

**Phase 3: Completed filtering (rules).
       Rule id: '100002'
       Level: '3'
       Description: 'Workaround 0 test rule'
**Alert to be generated.
```


Please, note that I create this rule as a `31516` child rule(by using `<if_sid>`).


- Using a [CDB list](https://documentation.wazuh.com/3.x/user-manual/ruleset/cdb-list.html). I recommend you using this workaround because it is more scalable and comfortable:

For this, you should [create a list](https://documentation.wazuh.com/3.x/user-manual/ruleset/cdb-list.html#creating-a-cdb-list) in the `/var/ossec/etc/lists` path. i.e:

`/var/ossec/etc/lists/test_list`

Then you should fill the list with key + value pairs:
```
somedomain.example.ca:bad_dns1
1.0.196.222:bad_ip1
1.0.196.223:bad_ip2
1.0.196.224:bad_ip3
```

Lastly, you should include a rule associated with the CDB list:
```XML
    <rule id="100100" level="10">
        <if_sid>31516</if_sid>
      <list field="srcip" lookup="address_match_key">etc/lists/test_list</list>
      <description>DNS/IP in black list.</description>
    </rule>
```
This is the ossec-logtest output for this workaround:

```
**Phase 1: Completed pre-decoding.
       full event: '- somedomain.example.ca - - [22/Aug/2019:15:04:32 -0600] "GET /server-status?auto HTTP/1.1" 200 1495 5365 1276 "-" "Mozilla/4.0 (compatible; MSIE 6.0)"'
       timestamp: '(null)'
       hostname: 'nanoPill'
       program_name: '(null)'
       log: '- somedomain.example.ca - - [22/Aug/2019:15:04:32 -0600] "GET /server-status?auto HTTP/1.1" 200 1495 5365 1276 "-" "Mozilla/4.0 (compatible; MSIE 6.0)"'

**Phase 2: Completed decoding.
       decoder: 'web-accesslog'
       srcip2: '-'
       srcip: 'somedomain.example.ca'
       protocol: 'GET'
       url: '/server-status?auto'
       id: '200'

**Phase 3: Completed filtering (rules).
       Rule id: '100100'
       Level: '10'
       Description: 'DNS/IP in black list.'
**Alert to be generated.
```

I hope it helps. Let me know if you need more details.

Best regards, Juan Pablo Sáez

**Comment by joey1a2b3c** [comment]
Thanks. This is working well for me :)
