### ISSUE TITLE
Unify the behavior of the Wazuh daemons when reconnecting to unix sockets

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#3876]
## Original issue

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.7.2 | Analysisd/Active response | Manager | Packages | Linux |

We have found an error message in _ossec.log_ referring an issue when writing into Active response queue.

```
2019/08/23 17:52:58 ossec-analysisd: ERROR: AR socket error (shutdown?).
2019/08/23 17:52:58 ossec-analysisd: ERROR: Error communicating with ar queue (-6).
```

## Update

This issue attempts to review and unify the behavior of Wazuh daemons on Unix systems when handling the reconnection attempts between them.

Now, Unix sockets are used to establish persistent connections between the Wazuh daemons (e.g. `ossec-analysisd`-`ossec-remoted`, `ossec-agentd`-`ossec-syscheckd`...). The problem is, when a socket is not available, each daemon handles the situation in a different way, in most of the cases they exit after a coupe of attempts to reconnect. For example, here we can see the case for the Syscheck daemon: https://github.com/wazuh/wazuh/blob/971b1acbb881c86b20c0d364ce12f004ec43419d/src/syscheckd/run_check.c#L42

In case it is useful, the data flow between those daemons is illustrated at the diagram located [here](https://documentation.wazuh.com/current/getting-started/architecture.html#communications-and-data-flow).

### Proposal solution

As is made on [this pull request](https://github.com/wazuh/wazuh/pull/4435) for Logcollector, when a socket is not available, the daemons connected to that socket have to keep trying to reconnect to it indefinitely. 

I would include this logic in the function `StartMQ()` in order to centralize the algorithm, but further analysis is needed to determine the best solution. https://github.com/wazuh/wazuh/blob/971b1acbb881c86b20c0d364ce12f004ec43419d/src/shared/mq_op.c#L21

**Comment by vikman90** [comment]
## How to reproduce

We managed to reproduce this issue:

1. Connect an agent (we need than the target of the AR is other than the manager itself).
2. Kill and restart Remoted:

```sh
pkill -f ossec-remoted
/var/ossec/bin/ossec-remoted
```

3. Make the agent log anything that would produce an alert attached to an AR.

This happens because Analysisd establishes a persistent connection with Remoted. If Remoted exits or crashes, Analysisd also needs to restart. On the other hand, some other daemons that connect to Analysisd must be restarted.

**Comment by cristgl** [comment]
Working in branch [3876-fix-socketer](https://github.com/wazuh/wazuh/tree/3876-fix-socketerr).

When analysisd has fallen, daemons try to connect to it permanently. Do we want to add a `sleep` between each trial? When they have already reconnected, do we want to add an info message of this reconnection?

**Comment by Molter73** [comment]
I did some looking around in the code and came up with the following information:

- Sockets opened with StartMQ are currently being used with SendMSG, OS_SendUnix and wm_sendmsg, making unification of behaviour on StartMQ a little easier than on the send functions.
- I checked all calls to StartMQ in order to see in which particular situations it is used:

Here is a list of uses of StartMQ in different daemons:

|Writter daemon|Reader daemon/queue|Comentarios|
|---|---|---|
|agentlessd|analysisd|Moving the reconnection logic inside StartMQ is possible|
|agentlessd|API|lessdcom_main connects to the agentless queue using OS_BindUnixDomain, no special error handling.|
|analysisd|main queue|Continuously read from the main queue and push messages to corresponding MQs, does not seem necessary to handle disconnection|
|analysisd|remoted|Connections used for active response on 2 different sockets, AR and Exec. Moving the logic into StartMQ would make analysisd block on start up until these queues are connected. Furthermore, AR and Exec queues are used without trying to reconnect because of them being in a time constrained thread (w_process_event_thread), it might be possible to make separate AR threads and change w_process_event_thread to push messages into a queue.<br />Connections for SCA have their own threads and open/close connections for every request they must handle, no problems moving reconnection logic to StartMQ that I can see here |
|agentd|execq|Reconnections are not attempted.|
|agentd|sca|Attempts to reconnect to the queue only once per message.|
|logcollector|analysisd|Added reconnection capabilities on previous PR, if logic for this goes into StartMQ it will need rewriting|
|monitord|analysisd|No reconnection attempts are made.|
|execd|API|Connection is opened and closed for each message.|
|remoted|analysisd|On secure and syslog (either UDP or TCP) connections attempts to reconnect once, exits if it fails.|
|rootcheck|analysisd|Attempts to reconnect once, exits if it fails|
|agent_control|remoted|Changing StartMQ to constantly reconnect would hang the users console until remoted was started|
|syscheckd|analysisd|Syscheckd attempts to reconnect on startup and exits if it fails 3 consecutive times. Once running, reconnection is attempted once and exits if it fails.|
|syscollector|analysisd|Attempts to connect a fixed number of times on start up, exits if it fails. If connection is lost, not attempt of reconnecting is done|
|vuln-detector|analysisd|Attempts to connect a fixed number of times on start up, exits if it fails. If connection is lost, a single reconnection attempt is done and exits if it fails.|
|wm_aws<br />wm_azure<br />wm_ciscat<br />wm_command<br />wm_oscap<br />wm_osquery|analysisd|Attempts to connect a fixed number of times on start up, exits if it fails. No reconnection attempts are made.|
|wm_keyrequest|remoted|No reconnection attempts are made|

## Proposed solution
Given the big amount of places StartMQ is used and that in some cases a blocking call to it would not be convenient (see agent_control above) I would first write a separate StartMQWithRetry function that could block execution until a successfull reconnection, replace it in the required modules and add it in the ones where there is no reconnection attempts being made currently.

As a very special case, active response and execd will be moved from w_process_event_thread into their own thread in order to not block the main analysisd thread when attempting to reconnect.
