### ISSUE TITLE
CDB lists are not compiled with service restart

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh#3895]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.5-rev | ossec-control | Manager | Packages | - |

## Issue
If a CDB list is added and configured correctly, using `systemctl restart wazuh-manager` or `service wazuh-manager restart` will not compile it. However doing `/var/ossec/bin/ossec-control restart` will indirectly run `/var/ossec/bin/ossec-makelists`.

Since now lists can be created and populated via the web interface the only missing step is the ability to compile them. Changing the above behavior would allow to do this since the web interface has the ability to restart the manager but it will attempt to do so with either `service` or `systemctl`.

This was requested some time ago here: https://github.com/wazuh/wazuh-kibana-app/issues/1438

**Comment by chemamartinez** [comment]
Hi @jctello, @branchnetconsulting,

Since https://github.com/wazuh/wazuh/pull/3488 it won't be needed to call `ossec-makelists` from the service scripts neither `ossec-control`. `Analysisd` will rebuild them at start-up, ensuring that the last version of the CDB lists will be loaded automatically when running the manager. This PR will be available in the next release.

Let me close the PR https://github.com/wazuh/wazuh/pull/3897 since it won't be needed. Anyway, thank you for it.

Regards,
Chema.
