### ISSUE TITLE
vulnerability-detector <ignore_time>

### ISSUE THREAD

**Issue by ericlee0517** [wazuh/wazuh#3908]
Hi guys,
I have been working on vulnerability-detector for a long time.Yesterday，I found the <ignore_time>means 'Time during which vulnerabilities that have already been alerted will be ignored',nonetheless,everytime the Vulnerability scanning start when I restart server and I can see the alerts in the alerts.json.Here is my ossec.conf in manager side:
![image](https://user-images.githubusercontent.com/52303393/64161416-31486d80-ce70-11e9-9cd2-d642adfc3c26.png)

Another two questions:
1、Can we run the vulnerability-detector immediately on selected agent now ?
2、As we know,Red Hat & CentOS use Red Hat Security Data ,and Ubuntu still use OVAL.Can we provide some unified feeds for these systems?(I used the Red Hat Data Api in json format and I found it is complexity and I could not recognize which CVE belongs to RedHat 5-7.

**Comment by crolopez** [comment]
Hi @ericlee0517,

The `<ignore_time>` option configures the interval during Vulnerability Detector will not analyze the packages which have been processed unless a new package is installed or an existing one is updated. The time cycle of this option starts when Wazuh began, so it will be restarted every time you restart Wazuh.

Regarding your questions:
1) That option is currently not supported. However, it is a desired featured and will be included in a future release.
2) We use this alternative source for Red Hat to improve the accuracy of the results since the OVAL format provided for Red Hat does not relate the CVEs with the packages affected directly, as the Debian and Ubuntu OVAL files do. It is not possible to provide a unified feed format for Ubuntu and Red Hat at the moment, but it is possible that in the future Wazuh will unify this database making the update process less complex.

I didn't understand your use case with the Red Hat Security Data API. Can you describe it a little more?

Best regards.

**Comment by ericlee0517** [comment]
> Hi @crolopez,
Sorry to bother u again bro,I want to try vulnerability-detector on Debian but I can not find the Debian OVAL.Could you please provide some databases like Debian or Ubuntu or tell me where can I download ?
Best wishes.

**Comment by crolopez** [comment]
Sure, you can download the feeds from:


- **Debian 7**: https://www.debian.org/security/oval/oval-definitions-wheezy.xml
- **Debian 8**: https://www.debian.org/security/oval/oval-definitions-jessie.xml
- **Debian 9**: https://www.debian.org/security/oval/oval-definitions-stretch.xml
- **Ubuntu 12**: https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.precise.cve.oval.xml
- **Ubuntu 14**: https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.trusty.cve.oval.xml
- **Ubuntu 16**: https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.xenial.cve.oval.xml
- **Ubuntu 18**: https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.bionic.cve.oval.xml

Best regards.

**Comment by Zenidd** [comment]
Hello @ericlee0517,

I'm closing this issue. Do not hesitate to reopen this or open a new one if you need some guidance or help. You can also contact us through our [#community Slack channel](https://wazuh.com/community/join-us-on-slack/).

Greetings, JP Sáez
