### ISSUE TITLE
Wazuh 3.2 for ELK 5

### ISSUE THREAD

**Issue by ankyclutin** [wazuh/wazuh#403]
Is it possible to deploy Wazuh 3.2 for ELK 5.xx ?
Or integrate the new CIS compliance into the old wazuh installation ?

**Comment by havidarou** [comment]
Hi @ankyclutin ,

it is not possible to deploy Wazuh 3.2.0 for Elastic Stack 5.xx if you plan to use the Wazuh app plugin for Kibana.

I would highly recommend you to upgrade to Elastic Stack 6.xx as the Wazuh app is way more stable and offers more functionality.

Regards.

**Comment by ankyclutin** [comment]
I would love to but that would mean migrating our current build into the
new version and with the breaking changes in the ELK 6, might pose quite a
headache.

**Comment by q2dg** [comment]
Well, Wazuh App installation fails if Kibana is 6.2.2 instead of 6.2.1 (as seen in https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/elastic_server_deb.html#elastic-server-deb)

**Comment by jesusgn90** [comment]
Hi @q2dg we were working to adapt it to 6.2.2 the last days and we have now a new Wazuh App package. It's not avalaible yet, because the server is cached, on the next server cache refreshing (between today and tomorrow) it will be avalaible for our users. Thanks for your patience.

Best regards,
Jesús

**Comment by ankyclutin** [comment]
As I have obtained the answer to my question, I am closing the issue. Thank you for the responses.
