### ISSUE TITLE
With Maxmind not supporting GeoIP egacy database how can we make use of GeoIP lookup in 3.10?

### ISSUE THREAD

**Issue by zin1x** [wazuh/wazuh#4053]
As above

**Comment by Zenidd** [comment]
Hello @zin1x,

While Wazuh still has the ability to read GeoIP databases through the [geoipdb](https://documentation.wazuh.com/3.8/user-manual/reference/ossec-conf/global.html#geoipdb) option,  we are currently using Filebeat along with the GeoIP Processor in Elasticsearch to obtain geographic location information based on IP addresses.

There is a [pipeline](https://github.com/wazuh/wazuh/blob/v3.10.2/extensions/filebeat/7.x/wazuh-module/alerts/ingest/pipeline.json) that will match the following fields of the alert:
- data.srcip
- data.win.eventdata.ipAddress
- data.aws.sourceIPAddress

The first one is included by default in most Linux systems, the second one is related to Window systems and the third one is related to the AWS integration.

Keep in mind that geoIP requires the IP to be public in order to be able to locate it, for example, the IP: 10.2.1.2 (subnet) won't trigger geoIP but the 216.23.2.15 (public) will do.

![geoIP2](https://user-images.githubusercontent.com/14923294/66570974-f6241300-eb6e-11e9-9ab3-a00e60fdb8e8.png)

Hope this resolves your doubt, let me know if you need further help

Regards, Juan Pablo Sáez

**Comment by danimegar** [comment]
Hi @Zenidd 
I had to do some more steps to show the GeoIP info:

Add the following lines to local_internal_options.conf:  
- analysisd.geoip_jsonout=1
- maild.geoip=1

Add the following lines to ossec.conf:
```
<global>
    ...
    ...
    <geoipdb>/var/ossec/etc/GeoIP.dat</geoipdb>
</global>
```
```
<alerts>
    ...
    ...
    <use_geoip>yes</use_geoip>
</alerts>
```

Regards,
Daniel.

**Comment by priyanka0077362** [comment]
can you tell me how to use <use_geoip>yes</use_geoip> in ossec.conf file


it is showing me error 


and i dont know how to parse with libgeoip_enabled in wazuh 


kindly help me

**Comment by priyanka0077362** [comment]
> Hi @Zenidd I had to do some more steps to show the GeoIP info:
> 
> Add the following lines to local_internal_options.conf:
> 
> * analysisd.geoip_jsonout=1
> * maild.geoip=1
> 
> Add the following lines to ossec.conf:
> 
> ```
> <global>
>     ...
>     ...
>     <geoipdb>/var/ossec/etc/GeoIP.dat</geoipdb>
> </global>
> ```
> 
> ```
> <alerts>
>     ...
>     ...
>     <use_geoip>yes</use_geoip>
> </alerts>
> ```
> 
> Regards, Daniel



can you tell me how to use <use_geoip>yes</use_geoip> in ossec.conf file

it is showing me error

and i dont know how to parse with libgeoip_enabled in wazuh

kindly help me

**Comment by AbdellahDv** [comment]
what the solution to this problem
<img width="1330" height="304" alt="Image" src="https://github.com/user-attachments/assets/3c875bda-05f6-418a-b21a-21ce3fc90a05" />

**Comment by whiterabb17** [comment]
> what the solution to this problem
> <img width="1330" height="304" alt="Image" src="https://github.com/user-attachments/assets/3c875bda-05f6-418a-b21a-21ce3fc90a05" />

You need to ensure in your ossec.conf file that the use_geoip tag is in the alerts section specifically.

```
<ossec_conf>
   <global>
     ...
     ...
     ...
     <geoipdb>/var/ossec/etc/GeoIP.dat</geoipdb>
   <alerts>
        ...
        ...
        <use_geoip>yes</use_geoip>
    </alerts>
</ossec_conf>
```

**Comment by whiterabb17** [comment]
> I hadn't considered the GeoIP events enrichment(prior to its check against the rules) so I tried to use The Wazuh geoipdb option:
> 
> These are the steps I have followed to make it work:
> 
> * Firstly, the Wazuh manager has to be compiled with the`USE_GEOIP=yes`flag:
>   `make TARGET=server USE_GEOIP=yes`
> * [Here](https://dev.maxmind.com/geoip/geoip2/geolite2/) you can download the GeoLite2 free databases. You should choose the City version in `CSV format, zipped`. I tried the Country version with no luck.
> * I can confirm that [geolite2legacy](https://github.com/sherpya/geolite2legacy) works on converting from current to a legacy(supported by Wazuh) database file. You should copy the `GeoLite2-City-CSV` file to the `geolite2legacy` source directory and then convert the DB with the command above:
>   `./geolite2legacy.py -i GeoLite2-City-CSV_20191008.zip -f geoname2fips.csv -o GeoIP.dat`
>   Then copy the converted GeoIP DB inside the Wazuh directory:
>   `cp GeoIP.dat /var/ossec/etc`
> * Output with Wazuh GeoIP DB
> 
> ```
> **Phase 2: Completed decoding.
>        decoder: 'sshd'
>        dstuser: 'root'
>        srcip: '2.136.147.146'
>        srcgeoip: 'ES / Catalonia'  <----------- Wazuh GeoIP DB field
>        srcport: '1055'
> 
> **Phase 3: Completed filtering (rules).
>        Rule id: '100011'
>        Level: '15'
>        Description: 'Log attempt from ES / Catalonia'
> **Alert to be generated.
> ```
> 
> And... it works! Thanks [@branchnetconsulting](https://github.com/branchnetconsulting) for the awesome advice. [@zin1x](https://github.com/zin1x), now you have these two GeoIP alternatives to choose the one that fits your use case. Greetings,
> 
> JP Sáez

I have done all this but havent actually been able to get srcgeoip in outputs.
Could you maybe provide some test logs i can use to try assess whether this is working?

# Note: 
- Manager source built using 'USE_GEOIP=yes' flag
- GeoIP.dat has correct permissions along with the geoipdb and use_geoip ossec.conf tags.
- GeoIP.dat created from GeoLite2 City CSV
- local_internal_options and internal_options both the relevant config lines.
- tested versions in use: 4.14.0/1
