### ISSUE TITLE
Monitoring local network while having wazuh installed on a VPS

### ISSUE THREAD

**Issue by jorgemfm** [wazuh/wazuh#407]
Is there a way to monitor servers on my local network while having wazuh server on a VPS?

Asking this since the IP when any agent tries to connect to the manager is going to be the public IP.

Also, its possible to monitor multiple networks that have agents installed on server with same IP?

EDIT: Rephrasing my question, I know that I can use "Any" as the IP address, my question ir more, if there is any problem using the same IP from multiple sources at the same time.

Thank you

**Comment by vikman90** [comment]
Hi @jorgemfm,

Unfortunately, the manager won't allow two different agents with the same static IP. This is because the protocol between agent and manager depends on whether the IP is static or dynamic. In the former case, the agent doesn't send its ID, the identification relies on the source IP. In the latter case, the agent sends its ID.

However, the source IP does not have to be `any` or a single IP: you may set a CIDR like `192.168.0.0/24`. In other words: the source `any` is an alias of `0.0.0.0/0`.

So if you have a VPS and want to restrict the source IP, this format may help you: `IP/31`, for example:
```
192.168.1.24/0
```

You should care that the fourth number is even (to respect the netmask). This means that only two IP addresses will be allowed.

Hope it helps.
Best regards.

**Comment by jorgemfm** [comment]
Thanks of the answer, but (and I may not be right) shouldn't the identification be the key generated? 

Shouldn't that the enough to identify a unique agent?

Thank you.

**Comment by vikman90** [comment]
Hi @jorgemfm,

The key generated is used to encrypt and decrypt the message. It would be hard to use it to identify the agent since the manager would have to try to decrypt the payload using all the available keys until it finds a key that produces a valid message.

You may take a look at the [technical documentation](https://documentation.wazuh.com/current/development/message-format.html#payload) about this.

The payload (data between agent and manager) depends on the registration mode:

If the agent was registered with a unique IP, the payload does not include the agent ID:

```
:<encrypted log>
```

In this case, the manager uses the source IP to identify the agent.

On the other hand, if the agent was added with `IP=any` or any address with a netmask, the actual payload is:

```
!<id>!:<encrypted log>
```

That's why we cannot register some agents with the same IP address.

Best regards.
