### ISSUE TITLE
Incorrect Kibana version in plugin [wazuh]. Expected [6.2.1]; found [6.2.2]"

### ISSUE THREAD

**Issue by magenx** [wazuh/wazuh#414]
this issue makes me crazy all the time im tryint to install new stack...
could you please fixit once and for all??

```
Running transaction
  Installing : kibana-6.2.1-1.x86_64                                                                                                            1/1 
  Verifying  : kibana-6.2.1-1.x86_64                                                                                                            1/1 

Installed:
  kibana.x86_64 0:6.2.1-1                                                                                                                           

Complete!
[root@stack ~]# /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Transferring 4693193 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [wazuh]. Expected [6.2.1]; found [6.2.2]"
```

**Comment by jesusgn90** [comment]
Hi @magenx we have specific Wazuh App packages for each version of Elastic, the problem you are facing is because you have installed [Kibana 6.2.1](https://www.elastic.co/downloads/past-releases/kibana-6-2-1) and our latest package is pointing to 6.2.2. You have two options in order to fix this little trouble:

1. Upgrade all your  [Elastic](https://www.elastic.co/) components to 6.2.2
2. Using the right Wazuh App package for [Kibana 6.2.1](https://www.elastic.co/downloads/past-releases/kibana-6-2-1) that could be installed as follow:

```# /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.2.0_6.2.1.zip```

You can check our compatibility table [here](https://github.com/wazuh/wazuh-kibana-app/tree/3.2#installation).

Best regards,
Jesús
