### ISSUE TITLE
Getting wrong timestamp with file integrity module

### ISSUE THREAD

**Issue by Theoooooo** [wazuh/wazuh#4174]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.2-1 | syscheck | Manager/Agent | Sources | CentOS7 |

After using Wazuh for a while, i noticed a timestamp issue with the syscheck module.

Whenever the module detect a changed made to a file in the default directories that are configured, the alert include the time before and after the modification has been done.

But this time is in UTC format and cannot be changer what so ever in the config file from both the manager and my agents installed.

The alert is generated every 12 hours (defualt settings) :
![image](https://user-images.githubusercontent.com/33425208/67933639-841b7880-fbc6-11e9-8d7e-b9cd999e768f.png)

But when i looked into my VM, i can clearly see what's going on :
![image](https://user-images.githubusercontent.com/33425208/67933726-b4631700-fbc6-11e9-9f8d-ac973e7882a9.png)

Is a feature coming for this issue or is it a option in the ossec.conf file ?

**Comment by Zenidd** [comment]
Hello @Theoooooo,

Your issue is related to the daylight saving time adjustment. We are aware that it may trigger false-positive FIM alerts in Windows NTFS file systems.

We already [opened an issue](https://github.com/wazuh/wazuh/issues/4167) where you can track the fixing progress, understand why this happens and check the suggested workarounds. I'm labeling this as a duplicate and closing it.

Greetings, JP Sáez
