### ISSUE TITLE
SCA Regex: Ensure password creation requirements are configured

### ISSUE THREAD

**Issue by nimeops** [wazuh/wazuh#4210]
Hi,
seems that the check is not good for **3084 Ensure password creation requirements are configured**:

`- 'c:dpkg -s libpam-pwquality -> install ok installed'`

should be

`- 'c:dpkg -s libpam-pwquality -> r:install ok installed'`

File: https://github.com/wazuh/wazuh/blob/master/etc/sca/debian/cis_debian9_L1.yml

**Comment by cristgl** [comment]
Hi @nimeops and thanks again for reporting these bugs. The project grows thanks to users contributing.
The bug has been fixed in this PR https://github.com/wazuh/wazuh-ruleset/pull/522.

Kind regards,
Cristina

**Comment by chemamartinez** [comment]
Hi @nimeops,

Thanks again for reporting these SCA issues, the requested changes have been added to 3.11, which hope it is available soon. Thanks to @cristgl as well for the prompt fixes.

Here you can see the ruleset changelog for that version: https://github.com/wazuh/wazuh-ruleset/blob/master/CHANGELOG.md

I suggest you using the [wazuh-ruleset repository](https://github.com/wazuh/wazuh-ruleset) for SCA policies related issues, they belong to the Wazuh ruleset and changes are made in there.

Let me close issues #4209, #4235 and this one since they are already solved.

Best regards,
Chema.
