### ISSUE TITLE
Let FIM collect permissions, user and group for Windows registry keys

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#4223]
I open this feature request for Syscheck to collect Windows Registry keys permissions set, just like it already does with regular files.

## Snapshot

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/10536251/68636480-7a402200-04b0-11ea-985d-5dd42e4a46cd.png">

## References

- [How to apply permissions to a Windows registry key](https://community.sophos.com/kb/en-us/13811)
- [Registry Key Security and Access Rights](https://docs.microsoft.com/en-us/windows/win32/sysinfo/registry-key-security-and-access-rights)

**Comment by jesusjimsa** [comment]
The user and group information will also be added to registries to add `check_owner` and `check_group` to the `windows_registry` option.

**Comment by jesusjimsa** [comment]
The working branch is [4223-fim-registry-permissions](https://github.com/wazuh/wazuh/tree/4223-fim-registry-permissions).

**Comment by jesusjimsa** [comment]
Here is some information on Windows documentation about how to get registry owner, group and security information: https://docs.microsoft.com/en-us/windows/win32/api/aclapi/nf-aclapi-getnamedsecurityinfoa

**Comment by jesusjimsa** [comment]
To get user information (user name and user id) for files, we currently use the `get_user` function:
https://github.com/wazuh/wazuh/blob/2be2fa789f483ea041e321cc97496274b8617218/src/shared/syscheck_op.c#L659-L774

In `get_user`, the `GetSecurityInfo` function is called, using the `SE_FILE_OBJECT` enum value. This entire function can be reused to retrieve the user information, I would only need to add a parameter to differentiate between files and registries and use the `SE_REGISTRY_KEY` enum value in the case we need the registry user information.

In the case of the group information (group name and group id), the function currently used for files return an empty string:
https://github.com/wazuh/wazuh/blob/2be2fa789f483ea041e321cc97496274b8617218/src/shared/syscheck_op.c#L946-L948
We could use a similar logic to the one already present in `get_user` to check the group information of a registry using the `GROUP_SECURITY_INFORMATION` flag instead of the `OWNER_SECURITY_INFORMATION` one used for user information.

These changes will need to be made in the functions in _syscheck_op.c_,  _syscheck_op.h_ and all the places where they are called, like _create_db.c_ and _syscheck_audit.c_

**Comment by jesusjimsa** [comment]
I have created a PoC to test that the functions developed to retrieve the user and group information are working correctly. Once I confirm they work as expected, I will write the function to read the permissions.

**Comment by jesusjimsa** [comment]
I am getting an error when trying to execute the PoC executable file (not valid win32 application):

<img width="259" alt="Captura de pantalla 2020-09-21 a las 9 42 56" src="https://user-images.githubusercontent.com/16068600/93754885-4f5b4a00-fbfa-11ea-8b1e-409a5b2ff7d3.png">

As the pull requests for the scan, the database and `report_changes` have now been merged, I am going to do the testing now directly with Wazuh in Windows.

**Comment by jesusjimsa** [comment]
I have managed to get the following information from a test registry key:

```
User name ---> Administradores
User id -------> S-1-5-32-544
Group name --> None
Group id -----> S-1-5-21-3527455827-79240758-596275861-513
```

The group id corresponds to the `HomeUsers` group, but it is not getting it from the `LookupAccountSid` function. For now, I am going to change the group name to `""` in the case it comes as `"None"`.

**Comment by jesusjimsa** [comment]
I wrote a function to obtain the registry permissions using the [`GetSecurityInfo`](https://docs.microsoft.com/en-us/windows/win32/api/aclapi/nf-aclapi-getsecurityinfo) and [`GetSecurityDescriptorDacl`](https://docs.microsoft.com/en-us/windows/win32/api/securitybaseapi/nf-securitybaseapi-getsecuritydescriptordacl) functions, but it is crashing Wazuh.
I have found now a function that seems better suited for retrieving a registry key permissions: [`RegGetKeySecurity`](https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-reggetkeysecurity). I am going to rewrite what I did yesterday using this new function.

**Comment by jesusjimsa** [comment]
I have now been able to get the permissions of a registry key:
```
PERM: Usuarios (allowed): read_control|read_data|read_ea|write_ea, Usuarios (allowed): generic_read, Administradores (allowed): delete|read_control|write_dac|write_owner|read_data|write_data|append_data|read_ea|write_ea|execute, Administradores (allowed): generic_all, SYSTEM (allowed): delete|read_control|write_dac|write_owner|read_data|write_data|append_data|read_ea|write_ea|execute, SYSTEM (allowed): generic_all, CREATOR OWNER (allowed): generic_al
```

**Comment by jesusjimsa** [comment]
I am going to add the `mtime` information to the `fim_registry_get_key_data` function, too. This will be done using the [`RegQueryInfoKeyA`](https://docs.microsoft.com/es-es/windows/win32/api/winreg/nf-winreg-regqueryinfokeya?redirectedfrom=MSDN) Windows function.
