### ISSUE TITLE
<syslog_output> not working with hostname

### ISSUE THREAD

**Issue by antoniojpascualv** [wazuh/wazuh#4227]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| "v3.10.2" | <syslog_output> | Manager | Sources | Centos 7 |

Hi team,
We have detected a problem with the <syslog_output> configuration.
https://documentation.wazuh.com/3.10/user-manual/reference/ossec-conf/syslog-output.html

The Syslog output works properly when using the IP in the <server> tag, but it stops working when using the server hostname.

Below you can see the output error at ossec.log when hostname is used to configure the syslog output endpoint:
csyslogd.c in line 88 is: ERROR: (1216) Unable to connect to '%hostname%' : 'Permission denied'.

**Comment by danielvalbuenasosa** [comment]
Hi,
Any update on this issue?

**Comment by Zenidd** [comment]
Hello @danielvalbuenasosa,

The team is still researching the root cause of this issue and where locate it in our roadmap. We get back to you here with any update.

Sorry for the inconvenience. Greetings, 
JP Sáez

**Comment by Molter73** [comment]
In order to allow the syslog daemon to resolve hostnames, we will need to remove its chroot jail so it can properly access `/etc/hosts`.

As far as I can tell, if the connection to the remote syslog server is closed for whatever reason we are not trying to reopen it, so we might as well do a little extra work and add this functionality to the `OS_Alert_SendSyslog` and `OS_Alert_SendSyslog_JSON` functions.
