### ISSUE TITLE
Block RDP/Other bruteforce on Windows 

### ISSUE THREAD

**Issue by Koploseus** [wazuh/wazuh#4234]
Hello,

I am using Wazuh 3.10 and i wanted to know how do i block an attacker (the ip adress) while he is bruteforcing my services ?

(mostly on RDP)

Thanks!

**Comment by Zenidd** [comment]
Hello @Koploseus,

When the active-response mechanism is triggered, it executes its response (i.e: blocking an attacking IP) through a `<command>` `ossec.conf` block.  

The issue here is that the `expect` <command> field only allows  `srcip`, `user` or `filename` as input. That's why it is not working with the fields `EventChannel.EventData.IpAddress/ win.eventdata.ipAddress` that probably are in your RDP events. We already opened [an issue](https://github.com/wazuh/wazuh/issues/2084) proposing an enhancement for the `expect` field to allow dynamic values including the fields from the alert. You can also read another user report for this issue [here](https://groups.google.com/forum/?hl=es#!searchin/wazuh/active-response$20srcip$20windows|sort:date/wazuh/LX54895Moxs/bhS5XNwaBgAJ). We will take your interest into account and start developing the solution as soon as our workflow allows us. Sorry for the inconvenience.


On Linux endpoints, there should be no problem blocking the attacker's addresses.

Nevertheless, there is something you could test. Integratord is a tool that connects Wazuh with external software, you can check our blog to find more information about it: [Integrator post](https://www.google.com/url?q=https%3A%2F%2Fwazuh.com%2Fblog%2Fhow-to-integrate-external-software-using-integrator%2F&sa=D&sntz=1&usg=AFQjCNEFNy-rG8v1xnSuYOSiVeWN7vcxOA).
You can configure Integratord to execute a script when this specific rule is triggered. The script expects the event in JSON format, extracts the field EventChannel.EventData.IpAddress (for Wazuh v3.9+ this field would be named as win.eventdata.ipAddress) and follows the same steps as netsh-win-2016.cmd. 

On the other hand, for further questions please we would like you to use our [#community Slack channel](https://wazuh.com/community/join-us-on-slack/) or the [Wazuh mail list](https://groups.google.com/forum/?hl=es#!forum/wazuh).

I hope this helps. Greetings, JP Sáez

**Comment by Koploseus** [comment]
OK! Thanks for the info!

And yes on a linux server everything is perfect!

**Comment by Zenidd** [comment]
Hello again @Koploseus,

I closing this issue to avoid maintaining duplicates. Remember that you can track [here](https://github.com/wazuh/wazuh/issues/2084) the progress of the AR enhancement for the expect field to allow dynamic values including the fields from the alert. 

On the other hand, for further questions please we would like you to use our [#community Slack channel ](https://wazuh.com/community/join-us-on-slack/)or the [Wazuh mail list](https://groups.google.com/forum/?hl=es#!forum/wazuh).

Warm regards, JP Sáez
