### ISSUE TITLE
Run CLANG analyzer (scan-build) for Windows agents building

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#4239]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| All | All | Agent | Sources | Windows |

When building Wazuh for Linux the CLANG analyzer is totally supported. However, for Windows agents, which are built by MinGW, the following errors appear.

 ```
# /usr/share/clang/scan-build-8/bin/scan-build make TARGET=winagent
scan-build: Using '/usr/lib/llvm-8/bin/clang' for static analysis
    CC wazuh_modules/syscollector/syscollector_win_ext.o
/bin/sh: 1: i686-w64-mingw32-/usr/share/clang/scan-build-8/bin/../libexec/ccc-analyzer: not found
Makefile:979: recipe for target 'wazuh_modules/syscollector/syscollector_win_ext.o' failed
make: *** [wazuh_modules/syscollector/syscollector_win_ext.o] Error 127
scan-build: Removing directory '/tmp/scan-build-2019-11-14-003355-42552-1' because it contains no reports.
scan-build: No bugs found.
```

It is needed research to make this analyzer supported for Windows agents. Some articles talks about this topic with success:
https://pete.akeo.ie/2011/10/building-and-running-clang-static.html

Regards.

**Comment by danimegar** [comment]
In the scan-build [website](https://clang-analyzer.llvm.org/scan-build.html), I found out that it works by overriding the CC and CXX environment variables to (hopefully) change the build to use a "fake" compiler instead of the one that would normally build your project.

So, the CC variable in Makefile (CC=gcc) is overwritten by CC=/usr/share/clang/scan-build-8/bin/../libexec/ccc-analyzer. For that reason, it appears the line: _/bin/sh: 1: i686-w64-mingw32-/usr/share/clang/scan-build-8/bin/../libexec/ccc-analyzer: not found_ 

To solve this, I propose two options:
**1) To use scan-build-py-8**: The following commands work well:
`/usr/bin/scan-build-py-8 make TARGET=winagent`
or
`/usr/bin/scan-build-py-8 --override-compiler make CC=gcc TARGET=winagent`

The problem is that I do not know if this binary is appropriate in order to analyze Wazuh agent.

**2) To modify Makefile**: scan-build override CC variable so we can put another variable (CC2) in the Makefile and then we assign CC2 = gcc in the command:
`/usr/bin/scan-build-8 make CC2=gcc TARGET=winagent`

So we can use CC or CC2 in the Makefile depending on whether CC = gcc or not.

**Comment by danimegar** [comment]
According to this [site](http://blog.canyonbliss.net/static-code-analysis-with-scan-build-while-cross-compiling/), it is necessary to use the following scan-build options: **--use-cc** and **--analyzer-target**. An example would be:
 
`# scan-build-8 --use-cc=/usr/bin/i686-w64-mingw32-gcc --analyzer-target=i686-w64-mingw32 -v -v make TARGET=winagent`

I modified Makefile in order to CC = /usr/share/clang/scan-build-8/bin/../libexec/ccc-analyzer can be used when scan-build starts and to avoid errors.

**Comment by danimegar** [comment]
According to this [web site](https://clang-analyzer.llvm.org/scan-build.html), it is very recommendable analyzing a project in its "debug" configuration or using _--force-analyze-debug-code_ flag in order to enable assertions.
