### ISSUE TITLE
API Integration  

### ISSUE THREAD

**Issue by austinsonger** [wazuh/wazuh#4267]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager | Packages/Sources | OS version | Linux Ubunutu

## Trying to add API Key for virustotal API Integration, but the following appears.

![](https://i.imgur.com/5j6FkwM.png)

**Comment by manuasir** [comment]
Hello @austinsonger ,

It seems something went wrong with your configuration. Can you paste your `ossec.conf` configuration here? Also, it'd help if you could paste any `WARN`,`ERROR` or `CRITICAL` messages into your `/var/ossec/logs/ossec.log` and `/var/ossec/logs/api.log`. You should have something like this in your `ossec.conf` :

```
<integration>
  <name>virustotal</name>
  <api_key>API_KEY</api_key> <!-- Replace with your VirusTotal API key -->
  <group>syscheck</group>
  <alert_format>json</alert_format>
</integration>
```

And after setting that up, the manager must be restarted.

Looking forward to hearing from you.

Regards

**Comment by manuasir** [comment]
Hi @austinsonger ,

Was that useful for you? Let me know if we can already close this issue.

Cheers

**Comment by Zenidd** [comment]
Hello @austinsonger,

I'm closing this ticket due to inactivity. Feel free to reopen it if you keep experiencing problems with the Integrations settings. For further questions please we would like you to use our [#community Slack channel](https://wazuh.com/community/join-us-on-slack/) or the [Wazuh mail list](https://groups.google.com/forum/?hl=es#!forum/wazuh).

Greetings, JP Sáez
