### ISSUE TITLE
FIM v2.0: Unit testing for Analysisd functions

### ISSUE THREAD

**Issue by Skeptor** [wazuh/wazuh#4344]
Working branch
|--|
[3319-fim-rework-unit-tests](https://github.com/wazuh/wazuh/tree/3319-fim-rework)

The purpose of this issue is to keep track of progress made on the creation and review of unit testing done on the analysisd module in the context of the FIM module.

Tier 1 (FIM v2.0)
----------------
**syscheck.c**
- [x] decode_fim_event
- [x] fim_process_alert
- [x] fim_process_scan_info
- [x] fim_generate_alert
- [x] fim_send_db_save
- [x] fim_send_db_delete
- [x] fim_send_db_query
- [x] fim_fetch_attributes
- [x] fim_fetch_attributes_state
- [x] fim_generate_comment
- [x] fim_adjust_checksum

**dbsync.c**
- [x] dispatch_send_local
- [x] dispatch_send_remote
- [x] dispatch_answer
- [x] dispatch_check
- [x] dispatch_state
- [x] dispatch_clear
- [x] DispatchDBSync

Tier 2 (FIM v1.0 & external functions)
-------------------------------------
**syscheck.c**
- [ ] DecodeSyscheck
- [ ] fim_db_search
- [ ] fim_alert
- [ ] InsertWhodata
- [ ] SumCompare
- [ ] fim_check_changes
- [ ] fim_control_msg
- [ ] fim_update_date
- [ ] fim_database_clean
- [x] sdb_clean
- [ ] fim_get_scantime
- [x] fim_init
- [x] sdb_init

**decode-xml.c**
- [ ] getDecoderfromlist

**string_op.c**
- [ ] wstr_chr
- [ ] wstr_replace
- [ ] wm_strcat

**read-agents.c**
- [ ] agent_file_perm

**hash_op.c**
- [ ] OSHash_Add_ex
- [ ] OSHash_Add
- [ ] OSHash_Get_ex
- [ ] OSHash_Update_ex

**wazuhdb_op.c**
- [ ] wdbc_query_ex
- [ ] wdbc_parse_result

Status
----------

Test file | Review | Line Coverage | Status
-- | -- | -- | --

**Comment by Molter73** [comment]
### Tests on syscheck.c
- The following tests cause segmentation faults due to input parameters not being checked:
  - test_fim_send_db_delete_null_sdb
  - test_fim_send_db_save_null_sdb
  - test_fim_process_scan_info_null_sdb
  - test_fim_generate_alert_null_lf
  - test_fim_process_alert_null_sdb
  - test_fim_process_alert_null_eventinfo
  - test_decode_fim_event_null_sdb
  - test_decode_fim_event_null_eventinfo
  - test_fim_adjust_checksum_null_newsum
  - test_fim_adjust_checksum_null_checksum
- The following tests fail because the buffer length being written to is smaller than the length being checked, causing the error condition to not be triggered:
  - test_fim_send_db_delete_query_too_long
  - test_fim_process_scan_info_query_too_long
- The following tests fail because a null string is being passed to printf-like statement, causing "(null)" to be written to a buffer:
  - test_fim_send_db_delete_null_agent_id
  - test_fim_send_db_delete_null_path
  - test_fim_send_db_save_null_agent_id
  - test_fim_send_db_save_null_data
  - test_fim_process_scan_info_null_agent_id
  - test_fim_generate_alert_null_mode
  - test_fim_generate_alert_null_event_type
  - test_fim_process_alert_no_path
  - test_fim_process_alert_no_mode

**Comment by Molter73** [comment]
### test_dbsync
- test_dispatch_send_local_socket_connect_error fails because OS_ConnectUnixDomain return OS_SOCKTERR (-6) on error, but dispatch_send_local expects sock to be -1 on error.
- test_DispatchDBSync_null_ctx and test_DispatchDBSync_null_lf fail with segmentation faults.
- Tests for null parameters where not implemented on all functions due to the fact that only DispatchDBSync is public, all other functions are called through it and therefore, it should be responsible for securing that no null parameters are passed to the inner functions.

**Comment by chemamartinez** [comment]
Done & merged at [3319-fim-rework](https://github.com/wazuh/wazuh/tree/3319-fim-rework)
