### ISSUE TITLE
Registering Windows agents with password authorization ERROR

### ISSUE THREAD

**Issue by dkempny** [wazuh/wazuh#4345]
I am following the documentation on:  https://documentation.wazuh.com/3.10/user-manual/registering/password/windows-password-registration.html 

Registration using password saved in "authd.pass" file doesn't work for me. If a password is provided in a command-line with -P flag, registration goes fine.

I am getting the below error:

PS C:\Program Files (x86)\ossec-agent>.\agent-auth.exe -m 192.168.76.3
2019/12/10 09:21:45 agent-auth: INFO: Started (pid: 1816).
2019/12/10 09:21:45 agent-auth: INFO: Using password specified on file: authd.pass
2019/12/10 09:21:45 agent-auth: INFO: Connected to 192.168.76.3:1515
2019/12/10 09:21:45 agent-auth: INFO: Using agent name as: windows2
2019/12/10 09:21:45 agent-auth: INFO: Send request to manager. Waiting for reply.
2019/12/10 09:21:45 agent-auth: ERROR: Unable to create key. Either wrong password or connection not accepted by the manager.
2019/12/10 09:21:45 agent-auth: INFO: Connection closed.

**Comment by vikman90** [comment]
Hi @dkempny, I'm trying to reproduce this issue.

I assume you're using Wazuh Agent 3.10.2 on Windows.

I'm managed to reproduce that, creating the password file via PowerShell, since it creates the file in _UCS2-LE-BOM_ encoding:

<img width="280" alt="Screen Shot 2019-12-10 at 16 30 38" src="https://user-images.githubusercontent.com/10536251/70581261-75cc5f00-1b6b-11ea-88a3-e8078cc59903.png">

The agent assumes the input file is in UTF-8 encoding, without byte-order mark (BOM).

Please check your _authd.pass_ file format and let me know.

Cheers!

**Comment by dkempny** [comment]
Hi @vikman90 ,
thank you for your answer.

The input file was created in UTF-16LE encoding. After changing to UTF-8 encoding the registartion process went fine.

Cheers!
