### ISSUE TITLE
Wazuh Agent - Incorrect ossec.conf file permissions

### ISSUE THREAD

**Issue by jakko10** [wazuh/wazuh#4348]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.2 | ossec.conf | Agent | Packages (MSI) |Windows|

Hi,

Looks like "Program Files (x86)\ossec-agent\ossec.conf" file has incorrect file permissions.
Everyone read/write.

When installing the Windows agent by the MSI package, the configuration file has permissions for everyone due to the following declaration:

https://github.com/wazuh/wazuh/blob/f38516ad45643287e4ee4e781b57cee6129c4df3/src/win32/wazuh-installer.wxs#L283

**Comment by vikman90** [comment]
Hi @jakko10,

Thank you for letting us know about this issue. It's related to issue #3520 where we're fixing the permissions for the _C:\Program Files\ossec-agent_ folder on Windows.

That issue is in the QA stage but we will include this issue as a dependency.

Thank you again. We will keep you posted.

Best regards.

**Comment by vikman90** [comment]
Hi @jakko10.

This issue has been fixed in #3593, and will be available in 4.0.1.

Thank you for reporting this problem.

Best regards.
