### ISSUE TITLE
Errors accessing "Regulatory Complaince" (all)

### ISSUE THREAD

**Issue by juaromu** [wazuh/wazuh#4366]
Wazuh Manager :  v3.10.2

Trying to access Regulatory compliance info (PCI, GDPR, HIPAA or NIST) throws an error like:

3026 - An error occurred trying to parse GDPR requirements (/api/gdpr/all)

(Error code is different, depending on the compliance selected).

If done on one specific agent no error is shown but the page is not shown either.

Thanks!

**Comment by AdriiiPRodri** [comment]
Hi @juaromu,

This error may be due to multiple reasons, so let's take the following steps to determine what the problem might be:

1º We are going to put the API in **debug** mode, to do this we must modify the **config.js** file of the Wazuh API. This file is in the path(default) `/var/ossec/api/configuration/config.js`.
Inside this file we will modify the value `"config.logs" = "info"` and let it so that `"config.logs" = "debug"`.

2º Once changed, we will make the **call** to the API, in our case: 
```curl -u USER:PASSWORD -k -X GET "http://YOUR_WAZUH_API_IP:YOUR_WAZUH_API_PORT/rules/gdpr?&pretty"```
(**Note**: if https is not enabled, change it to http. foo:bar are the default user and password. By default, the call should be: 
```curl -u foo:bar -k -X GET "http://YOUR_WAZUH_API_IP:55000/rules/gdpr?&pretty"```).

3º Let's see the error in the API log, for that we shall check the path `/var/ossec/logs/api.log`, it is necessary that you copy the log for us to better be able to help you. We are going to execute the following command just **after making the call**: `tail -n 100 /var/ossec/logs/api.log`

I look forward to hear from you, if you have any questions about the process, please do not hesitate to ask.

Best regards,
Adri

**Comment by juaromu** [comment]
Hi mate:

Thanks a lot for your help with this.

After enabling logs in debug mode turned out there was problem with the permissions on one of the ruleset files (root:root) when it should be root:ossec

Error reading rule files: 0015-ossec_rules.xml. Error: [Errno 13] Permission denied: '/var/ossec/ruleset/rules/0015-ossec_rules.xml'

I had moved across this file from another machine and that's why permissions were wrong.
All good now.

Gracias compadre :-)

Juan.
