### ISSUE TITLE
wazuh aws vpc logs

### ISSUE THREAD

**Issue by prabhinmp** [wazuh/wazuh#4373]
2019/12/16 11:52:24 wazuh-modulesd:aws-s3: WARNING: Bucket:  -  No files were found in 'wazuhvpc/vpc/'. No logs will be processed.
2019/12/16 11:52:24 wazuh-modulesd:aws-s3: INFO: Fetching logs finished.

kindly help on this

**Comment by crd1985** [comment]
Hi @prabhinmp,

this is not a valid issue since it is nor a feature request or a detailed bug description.

Please, open a new thread in our community mailing list or Slack channel. More information [here](https://wazuh.com/community/). I recommend describing your use case as detailed as possible and attaching your `ossec.conf` (hiding sensitive data).

Furthermore, check out our [official documentation](https://documentation.wazuh.com/3.10/amazon/index.html) where there are some examples of configurations to monitor AWS buckets and services.

I hope you understand.

Regards,
Daniel
