### ISSUE TITLE
<disabled> setting for open-scap wodle gets reset to 'no' in agent.conf

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#4393]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.11.0 | agent.conf | Agent | na | na |

I have confirmed this in 3.10.2 and after reading the release notes and changelog for 3.11.0 I presume the issue is also present in 3.11.0.

In agent.conf, if there is more than one open-scap wodle section that applies to a given agent, the `<disabled>` setting appears to get defaulted to 'no' even if there was no `<disabled>` section in the final applicable open-scap config section and an applicable open-scap config section higher up with `<disabled>` set explicitly to 'yes'.  For example, with the following agent.conf and a Linux  agent that uses the "ubuntu14" profile, that agent will have OpenSCAP enabled even though nowhere in agent.conf is there an open-scap `<disabled>yes</disabled>` line.

```
<agent_config os="Linux">
	<wodle name="open-scap">
		<disabled>yes</disabled>
		<timeout>1800</timeout>
		<interval>1d</interval>
		<scan-on-start>no</scan-on-start>
	</wodle>
</agent_config>
<agent_config profile="ubuntu14">
	<wodle name="open-scap">
		<content path="ssg-ubuntu-1404-ds.xml" type="xccdf"/>
	</wodle>
</agent_config>
```

I have not explored this issue deeply, but I wonder if when Wazuh applies default values to certain fields in certain config sections (like `<disabled>` gets a default value of 'no' for the open-scap wodle), that it fails to recognize that in a previous instance of the same config section, that the value had already been explicitly set.  

If in agent.conf, config-section default values are being reapplied over the top of values previously explicitly set, then I would suggest this violates the expected behavior of settings once set in agent.conf persisting unless they are explicitly changed/overridden further down in agent.conf.   Please fix this or explain why this would be intended behavior.

Thanks,
Kevin

**Comment by Zenidd** [comment]
Hello @branchnetconsulting,


Sorry for the late reply and I hope you are having a nice end of year.

>  the <disabled> setting appears to get defaulted to 'no' even if there was no <disabled> section in the final applicable open-scap config section and an applicable open-scap config section higher up with <disabled> set explicitly to 'yes'. 

**Accumulative and Overwriting configuration sections**

While some `ossec.conf` configuration options are accumulative (i.e: for two `<syscheck>` stanzas, its contents will sum up and in conflict case, the last value will be taken ) in the Wodle case, the last stanza will completely overwrite previous ones.

That's causing the `<disabled>` value be set to no in your example above:

- First stanza

```XML
<agent_config os="Linux">
	<wodle name="open-scap">
		<disabled>yes</disabled>
		<timeout>1800</timeout>
		<interval>1d</interval>
		<scan-on-start>no</scan-on-start>
	</wodle>
</agent_config>
```

- Second stanza: The first stanza is replaced with this one and the missing value for `<disabled>` is set to no by default.
![image](https://user-images.githubusercontent.com/14923294/71577350-14593980-2af4-11ea-848e-2c102c74715f.png)

```XML
<agent_config profile="ubuntu14">
	<wodle name="open-scap">
  <!--         <disabled>yes</disabled> -->  MISSING DEFAULT VALUE
		<content path="ssg-ubuntu-1404-ds.xml" type="xccdf"/>
	</wodle>
</agent_config>
```

This is the expected behavior for Wodle configuration section. I think we have to document exactly which sections of the configuration are overwritten and which ones combine its content. 

Thanks for helping us to realize that this needs some clarification. Any of your suggestions will be appreciated.

Greetings, JP Sáez

**Comment by branchnetconsulting** [comment]
Thank you for clarifying that wodle configuration sections overwrite each other rather than being accumulative like other Wazuh config sections.  This does need to be made consistent as well as to be explained in the documentation, but now I understand how this works.
