### ISSUE TITLE
Timestamp filter

### ISSUE THREAD

**Issue by tientmse62290** [wazuh/wazuh#4403]
I'm using Wazuh 3.11. Now I need to make a dashboard that shows event between 18:00 yesterday and 8:00 today but using filter between "now/d-6h" to "now/d+8h" is not working.
Does anyone have solutions?
Thanks

**Comment by Zenidd** [comment]
Hello @tientmse62290,

I'm closing this issue since it is nor a feature request or a detailed bug description.

Please, open a new thread in our community mailing list or Slack channel. More information [here](https://wazuh.com/community/). I recommend describing your use case as detailed as possible.

I hope you understand.

Regards, JP Sáez

**Comment by ssaymin** [comment]
Hello there,
I want to filter timestamp using log match parameter in wazuh rule below.
In the rule I want to create, I aim to receive a mail notification by changing a different rule to a different rule, for example, I want the log that comes to the current rule between 15:00 and 17:00 to fall into the rule I just created and send a mail notification.
For this, I wonder if we can apply a filter in the match parameter?
Thank you very much in advance...

  <rule id="100001" level="5">
    <if_sid>5716</if_sid>
<match>timestamp filter parameter</match>
 <description>sshd: authentication failed from IP 1.1.1.1.</description>
    <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
  </rule>
