### ISSUE TITLE
My wazuh active response didnt work on debian 8

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh#444]
I have  tried this tutorial 

https://blog.wazuh.com/blocking-attacks-active-response/

but  active-response didnt work, it didnt even stored any log in `active-response.log`
but i could catch a log like this in my kibana dashboard.

`host:debian full_log:Mar 14 00:49:51 debian sshd[12624]: Failed password for invalid user asdhjasjdh from 192.168.56.1 port 61857 ssh2 path:/var/ossec/logs/alerts/alerts.json id:1521002993.13981 agent.name:debian agent.id:000 predecoder.program_name:sshd predecoder.timestamp:Mar 14 00:49:51 predecoder.hostname:debian rule.level:5 rule.pci_dss:10.2.4, 10.2.5, 10.6.1 rule.groups:syslog, sshd, invalid_login, authentication_failed, gpg13_7.1 rule.firedtimes:7 rule.id:5710 rule.description:sshd: Attempt to login using a non-existent user rule.mail:false manager.name:debian cluster.node:node01 cluster.name:wazuh data.srcuser:asdhjasjdh data.srcip:192.168.56.1 location:/var/log/auth.log decoder.parent:sshd decoder.name:sshd @timestamp:March 14th 2018, 12:49:53.000 _id:JULXImIBgxOWVLcZ2n6_ _type:wazuh _index:wazuh-alerts-3.x-2018.03.14 _score: -
`

Could anyone help me with this ? i have reinstaled many VM and installed all of it again many times but active response still didnt work...

Below is my `command` and `active-response` config in my `ossec.conf` ( I am using host.deny)

 ```
<command>
    <name>host-deny</name>
    <executable>host-deny.sh</executable>
    <expect>srcip</expect>
    <timeout_allowed>yes</timeout_allowed>
  </command>
```

```
<active-response>
    <command>host-deny</command>
    <location>local</location>
    <level>6</level>
    <timeout>1800</timeout>
</active-response>
```

**Comment by frgv** [comment]
Hello @gagantous 

I think I can see where is the problem. If you take a close look to your settings, you are triggering the comand `host-deny` when an alert with a level higher than 5 (at least 6) is created. And, the alerts you are receiving in Kibana are level 5, as you can see in the log you pasted:

`...
 predecoder.hostname:debian rule.level:5 rule.pci_dss:10.2.4, 10.2.5, 10.6.1
...`

Just for make sure, I have recreated the same environment with debian 8 and tested active response with this configuration:


```
<command>
    <name>host-deny</name>
    <executable>host-deny.sh</executable>
    <expect>srcip</expect>
    <timeout_allowed>yes</timeout_allowed>
</command>


<active-response>
  <command>host-deny</command>
  <location>local</location>
  <level>4</level>
  <timeout>600</timeout>
</active-response>
```


As you can see, I have set a lower threshold, so active response will work with at least level 4 rules.
After a few wrong username ssh attempts, we take a look at `/var/ossec/logs/alerts/alerts.log` file and we see the following:


```
...
** Alert 1521027397.39635: - syslog,sshd,invalid_login,authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,pci_dss_10.6.1,gpg13_7.1,
2018 Mar 14 07:36:37 osboxes->/var/log/auth.log
Rule: 5710 (level 5) -> 'sshd: Attempt to login using a non-existent user'
Src IP: 192.168.0.101
Mar 14 07:36:36 osboxes sshd[9310]: Failed password for invalid user testing123 from 192.168.0.101 port 63679 ssh2

** Alert 1521027399.40029: - ossec,active_response,pci_dss_11.4,gpg13_4.13,
2018 Mar 14 07:36:39 osboxes->/var/ossec/logs/active-responses.log
Rule: 603 (level 3) -> 'Host Blocked by host-deny.sh Active Response'
Src IP: 192.168.0.101
Wed Mar 14 07:36:37 EDT 2018 /var/ossec/active-response/bin/host-deny.sh add - 192.168.0.101 1521027397.38493 5710
script: host-deny.sh
type: add

** Alert 1521027399.40411: - syslog,access_control,access_denied,pci_dss_10.2.4,
2018 Mar 14 07:36:39 osboxes->/var/log/auth.log
Rule: 2503 (level 5) -> 'syslog: Connection blocked by Tcp Wrappers.'
Mar 14 07:36:38 osboxes sshd[9321]: refused connect from 192.168.0.101 (192.168.0.101)
```


Here, we can see that, when the alerts have been received and active response triggered, an entry has been added to `host-deny.sh`, and the next time that host tried to log in, his connection was blocked.

Also, if we take a look at `/var/ossec/logs/active-responses.log ` we can see the following: 

`Wed Mar 14 07:36:37 EDT 2018 /var/ossec/active-response/bin/host-deny.sh add - 192.168.0.101 1521027397.38493 5710`

And, if we check the hosts.deny files, we can check that the entry has been added successfully:

```
# /etc/hosts.deny: list of hosts that are _not_ allowed to access the system.
#                  See the manual pages hosts_access(5) and hosts_options(5).
#
# Example:    ALL: some.host.name, .some.domain
#             ALL EXCEPT in.fingerd: other.host.name, .other.domain
#
# If you're going to protect the portmapper use the name "rpcbind" for the
# daemon name. See rpcbind(8) and rpc.mountd(8) for further information.
#
# The PARANOID wildcard matches any host whose name does not match its
# address.
#
# You may wish to enable this to ensure any programs that don't
# validate looked up hostnames still leave understandable logs. In past
# versions of Debian this has been the default.
# ALL: PARANOID

ALL:192.168.0.101
```

Note that 192.168.0.101 was the attacker IP.

Additionally, we can appreciate that, with this config, we have set up a 600 seconds timeout, so, after 10 minutes, the blocked IP will be erased from the list, as we can see in `/var/ossec/logs/active-responses.log`:

```
Wed Mar 14 07:36:37 EDT 2018 /var/ossec/active-response/bin/host-deny.sh add - 192.168.0.101 1521027397.38493 5710
Wed Mar 14 07:46:38 EDT 2018 /var/ossec/active-response/bin/host-deny.sh delete - 192.168.0.101 1521027397.38493 5710
```

So, for fixing your configuration, you can lower the threshold for the active response to be activated OR you can choose a certain rule for blocking hosts, as shown below:
```

<command>
    <name>host-deny</name>
    <executable>host-deny.sh</executable>
    <expect>srcip</expect>
    <timeout_allowed>yes</timeout_allowed>
</command>

<active-response>
  <command>hosts-deny</command>
  <location>local</location>
  <rules_id>5710</rules_id>
  <timeout>1800</timeout>
</active-response>
```

Note that this active response will only work for 5710 rules `Rule: 5710 (level 5) -> 'sshd: Attempt to login using a non-existent user'`.

Hope that helps, and don't hesitate to ask any further questions you may have.

Best regards,

Fran G.

**Comment by gagantous** [comment]
Hi Fran G.

Thank you Frans G. For give me a very good explanation to my issue here. Sorry for bothering you with my childish  and non-sense question. I dont know that to say... your answer is more than enough. I really thanksfull for that.

But perhaps one last question from me.

Do you know how to connect OSSEC with ELK manually, without using wazuh package ? So i used Pure ossec, not wazuh-ossec. 

I hope my question is not bothering you more. Thansk again

Regards 
Fathin A. Hadi

**Comment by frgv** [comment]
Hello @gagantous 

Thanks for your words, we're always happy to help.

First of all, about your configuration: I've been doing some testing with it, and yes, it will work. But for me, it's a little bit redundant, let me explain myself. With those lines:

```
    <rules_id>5712</rules_id> 
     <level>4</level>
```

You are triggering active response if rule 5712 is received **OR** a level 4 or higher alert is received. The point here is, since rule 5712 is level 10, active response would be triggered anyways because of the level 4 or higher condition, so the `rules_id` line is innecesary here. 

One use case for that kind of configuration would be to set a more restrictive alert level (i.e. 12) and also a certain rule of your choice that you want to trigger the active response (level 8, for example), that wouldn't kick in if it wasn't declared with that `rules_id` line.

And, about the OSSEC with ELK integration, yes, it is doable. But it has more cons than pros, in my opinion.

You always can use filebeat to send the logs to logstash+elastic and represent them in Kibana, but you would have to define your own elastic indices, templates, etc. And in addition, there are many features that you would lose without Wazuh, like:
  - Wazuh API
  - Virustotal, VULS, AWS, CIS-CAT integration
  - Vulnerability detection
  - Manager clustering
  - Easier manager and agent monitoring and control from Kibana
  - Updated ruleset
  - Automatic agent installation and configuration (everything can be done with one simple line)

...And so on.

If you don't want to get your hands dirty, and since pure ossec integration with ELK requires some additional configuration, I'd strongly suggest you using Wazuh, since all the steps are included in the documentation and the installation is pretty straight-forward: https://documentation.wazuh.com/current/installation-guide/index.html

In addition, you can always check our mailing lists and ask for guidance if you have any problem or question: https://groups.google.com/forum/#!forum/wazuh

I hope it helped.

Regards,

Fran.
