### ISSUE TITLE
Original-Ossec active response works, but Wazuh-Ossec didnt.

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh#445]
I have tried this in two seperated Virtual machine. first VM we used, pure ossec, and second VM used a package from wazuh which is included ossec in it. Both of them used Single-Host Architecture. For the first VM i am not using ELK, because i dont know how to connect those two apps.

The First VM's active response works great, i have checked the `ossec.conf` and they have both the `<command>` tag and `<active-response>` tag. I tried to block an ip using `host-deny` for  SSH invalid login attempt/SSH brute Force attack, and it works!!. I did no configuration since the command and active response were default settings.

THe second VM's active response seems a bit little different. I checked `ossec.conf`, it did have `<command>` tag with `host-deny` name, but it didnt like the first VM which is  have `<active-response>` with `host-deny` at the default setting. It did have but it's got commented and no `host-deny` active-response function. So i just simply added the `<active-response>` for `host-deny` just like the first VM. but when i tried to pentest the second VM. It did not blocked the ip.

Is there any different between active response Wazuh-Ossec and Pure-ossec Configuration ?

**Comment by frgv** [comment]
Hello @gagantous 

I think this might be the same issue as #444 .

As you correctly said, Ossec has enabled active response by default, and it will be triggered for level 6 (and higher) alerts, the same way you had configured in the previous issue.

The problem here is that SSH brute Force attack (rule 5712) is a level 10 alert, so it will trigger the active response, meanwhile rule 5710 is a level 5 alert, so active response won't trigger.

`Rule: 5712 (level 10) -> ‘SSHD brute force trying to get access to the system.’
`

I hope that helps,

best regards,

Fran G.

**Comment by gagantous** [comment]
Hi @frgv  

Thanks for your replies to my issue here. I will close this thread since you just gave me a very very good explanation for my other issue i just made before this. Really appreciate it (y)
