### ISSUE TITLE
[Feature Request] Start Vulnerability Scan on demand

### ISSUE THREAD

**Issue by Theoooooo** [wazuh/wazuh#4490]
I would be great if we could launch a new vulnerability scan with the vulnerability-detector module on single host when needed.

I also notice, if you set (for exemple) an interval of 1d to rescan the host, and then restart the host within a day, the scan timer will reset and you will have to wait anthor day for the scan to show up.

Some times, wazuh configuration can't afford to activate the "scan_on_start" option, and the scan may need to be launched manually, but i can't find a way to do that with the API documentation 
https://documentation.wazuh.com/3.11/user-manual/api/reference.html#id1

**Comment by Zenidd** [comment]
Hello @Theoooooo,

> I would be great if we could launch a new vulnerability scan with the vulnerability-detector module on single host when needed.

> Some times, wazuh configuration can't afford to activate the "scan_on_start" option, and the scan may need to be launched manually, but i can't find a way to do that with the API documentation

I understand you here, this is a really useful functionality that other modules already have. We are working to give the users remote SCA management capabilities through our API. It will allow performing actions like scans on-demand or getting the result details. There are already opened issues about where you can follow our progress:
- https://github.com/wazuh/wazuh/issues/3231
- https://github.com/wazuh/wazuh/issues/3687

Feel free to comment there whatever you think useful.


> I also notice, if you set (for exemple) an interval of 1d to rescan the host, and then restart the host within a day, the scan timer will reset and you will have to wait anthor day for the scan to show up.

In this respect, the scan interval has the Wazuh manager startup time as a reference. That's why it resets on every Wazuh manager restart. You could open another issue about this topic.

I'm closing this issue as the feature requested here is already on an existing issue. Thanks for your contributions Theo.


Best regards, JP Sáez
