### ISSUE TITLE
Question about Wazuh Cluster

### ISSUE THREAD

**Issue by John33000** [wazuh/wazuh#4506]
Hi,

I would like make Wazuh cluster with load balancer so, I will follow this doc : 

https://documentation.wazuh.com/3.10/user-manual/configuring-cluster/index.html and https://documentation.wazuh.com/3.10/user-manual/configuring-cluster/advanced-settings.html

My question is :  Wazuh worker I need to install ElasticSearch and Filebeat  ? Like Wazuh master ? And filebeat and Elasticsearch point to Master ? 

Currently we work in Single-host architecture. After we will create nodes ElasticSearch. 

Best Regards

**Comment by AdriiiPRodri** [comment]
Hi @John33000,

I recommend you, besides the links you specify, the following blog which will help you to configure the load balancer [NGINX Load balancer for a Wazuh cluster](https://wazuh.com/blog/nginx-load-balancer-in-a-wazuh-cluster/.)

Regarding the need to install in the Workers elasticsearch nodes, no, it is **not necessary** in fact, elasticsearch can be installed in a different machine than the one where Wazuh is installed. As for the filebeat, it **is necessary** to install it in **all the manager nodes (Master and Workers)** since it sends the events and alerts to **elasticsearch**. 

The master node is responsible for registering agents, in case it fails, **the workers nodes will keep on generating alerts from the previously registered agents**, so they need filebeat to take those alerts to Elasticsearch. I leave you a configuration guide of Elasticsearch for Wazuh [Installing Elastic Stack](https://documentation.wazuh.com/3.11/installation-guide/installing-elastic-stack/elastic_server_deb.html#elasticsearch).

To configure filebeat, I give you the following link [Forwarder installation](https://documentation.wazuh.com/3.11/user-manual/configuring-cluster/)

For any other questions, let me know.

Best regards,
Adrián Peña

**Comment by AdriiiPRodri** [comment]
Hi @John33000,

If the machine on which you have Elasticsearch, Filebeat, Kibana, Wazuh-master shuts down or has a problem, Elasticsearch will stop. But it is important to note that Elasticsearch is independent of Wazuh, that is, if for example Wazuh is not installed, Elasticsearch can be installed and work. Elasticsearch listens on an **address** that is [configurable](https://documentation.wazuh.com/3.11/installation-guide/installing-elastic-stack/elastic_server_deb.html#elasticsearch), and it is Filebeat who sends to that [address](https://documentation.wazuh.com/3.11/installation-guide/installing-wazuh-manager/linux/debian/wazuh_server_packages_deb.html#installing-filebeat). 

So all the filebeats from all the manager nodes must point to Elasticsearch's address so that events and alerts can reach it. You can see a detail of this communication cycle in the following [diagrams](https://documentation.wazuh.com/3.11/getting-started/architecture.html).

For any other questions, don't hesitate to ask.

Best regards,
Adrián Peña

**Comment by John33000** [comment]
Hi @AdriiiPRodri 

Ok I understand. 
Thank you

Best Regards

**Comment by John33000** [comment]
Hi @AdriiiPRodri 

Sorry , I re-open this case. 

I have question. Will do this configuration : 

![image](https://user-images.githubusercontent.com/46779058/73343265-9918ae00-4280-11ea-8c55-ae75667dfb2c.png)


If my master is stopped, every agent go to on worker01 for example. But the worker01 become Master ? And if I repair, lunch master, the agent return to Master ?

Best Regards

**Comment by AdriiiPRodri** [comment]
Hi @John33000,

No, the worker node does not become master. In the case you propose, as there is no master, no new agents could be registered.

I leave you one link where you can find the community groups, where we can help you better and faster. Both on the mailing list and on our Slack channel:

**Slack:** https://wazuh.com/community/join-us-on-slack/
**Mailing list:** https://groups.google.com/forum/#!forum/wazuh

Best regards,
Adrián Peña

**Comment by John33000** [comment]
Hi,

Ok, if master is down, the events collected by agents continue to send to Elasticsearch, Kibana and other Wazuh Manager Worker, but if I want add a new agent, is not possible if master is down ? 

Thank you for the link

**Comment by AdriiiPRodri** [comment]
You're welcome. Exactly, if the master node is disconnected you cannot register new agents. When the master node is down, the agents connected to it will be changed to another manager node. This last thing happens thanks to the load balancer.

Regards
