### ISSUE TITLE
Crypto library unit tests failed in FIM Rework branch

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#4521]
|Wazuh version|Component|
|---|---|
| 3319-fim-rework | Unit tests |

The TAP unit tests reported two issues in _os_crypto_ library:

```
# make TARGET=server test
   STARTING TEST - OS_CRYPTO

    ok  1 - Blowfish encryption test.
    ok  2 - MD5 encryption test.
    ok  3 - MD5 file reading encryption test.
    ok  4 - MD5 non-existing file to read from.
not ok  5 - SHA1 encryption test.
not ok  6 - SHA1 file reading encryption test.
    ok  7 - SHA1 non-existing file to read from.
    ok  8 - MD5+SHA1 file reading encryption test.
    ok  9 - MD5+SHA1 reading from file using command encryption test.
    ok 10 - MD5+SHA1 non-existing file to read from using command.
1..10

       [ 2 TEST FAILED ]

    ENDING TEST  - OS_CRYPTO
```

**Comment by Lopuiz** [comment]
Hello team,

This issue is due `os_sha1` size has changed on FIM rework. The `os_sha1` size will be 41.

In the following SHA1 function the parameter output is filled with 0 using the old size (65). It causes a core dump.

https://github.com/wazuh/wazuh/blob/006792ea3261fdd99cef0e0cb213fd306d917aef/src/os_crypto/sha1/sha1_op.c#L30-L62



Best regards,
Eva
