### ISSUE TITLE
Fix totalItems for framework functions using process_array for the new API

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4588]
# Description

This issue is related to #4575. 

The merged in https://github.com/wazuh/wazuh/pull/4576 must be adapted to the refactored code in new API.

**Comment by davidjiglesias** [comment]
In 4.0 we have to check every framework function using `process_array` to ensure the `total_affected_items` is calculated after applying filters and search but before pagination (offset, limit). Otherwise the `total_affected_items` will always display the same quantity as the selected limit, which is wrong.

An example:
```
    result.affected_items = process_array(
        lists, search_text=search_text, search_in_fields=search_in_fields, complementary_search=complementary_search,
        sort_by=sort_by, sort_ascending=sort_ascending, offset=offset, limit=limit)['items']
    result.total_affected_items += len(result.affected_items)
```
