### ISSUE TITLE
Possible rootcheck false positive in Ubuntu Xenial (due to s-nail utility)??

### ISSUE THREAD

**Issue by alago197** [wazuh/wazuh#4606]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.11.0-rev | Manager | Manager | Packages/Sources | Ubuntu 16.04.6 |

Hi,

I'm getting rootcheck messages for a _"Trojaned version of file '/usr/bin/mail' detected. Signature used: 'bash|file\.h|proc\.h|/dev/[^nu]_' which seems a false positive.  

In the system, I previously installed the smartmontools package, which also installed s-nail as a dependency. http://manpages.ubuntu.com/manpages/xenial/man1/s-nail.1.html 

so, "/usr/bin/mail" in this system points to:
```
lrwxrwxrwx 1 root root 22 Oct 24  2018 /usr/bin/mail -> /etc/alternatives/mail
root@host:/root# ls -l /etc/alternatives/mail
lrwxrwxrwx 1 root root 15 Oct 24  2018 /etc/alternatives/mail -> /usr/bin/s-nail

root@host:/root# ls -l /usr/bin/s-nail
-rwxr-xr-x 1 root root 551160 Jan  2  2016 /usr/bin/s-nail
root@host:/root# file /usr/bin/s-nail
/usr/bin/s-nail: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 2.6.32, BuildID[sha1]=6b5a95810a82b117ea9af3a20e07b672e5a77112, stripped
```
, which I already verified is not trojaned. 

Any quick means to whitelist this path aside from commenting it in the rootkit_trojans.txt?

**Comment by 0xN3utr0n** [comment]
Hello alago197,
Right now Rootcheck works by searching at runtime every binary listed on `rootkit_trojans.txt` and comparing earch string within said binaries against some regular expressions such as `!bash|file.h|proc.h|/dev/[^nu]`.  That is, `s-nail` probably contains a string like "bash" or "file.h". Hence, the only choices I can think of are:

- Comment the faulty line in `rootkit_trojans.txt`. 

- Rename the symbolic link. For instance, instead of `/usr/bin/mail` use `/usr/bin/syml_mail`.

I'm well aware they are not ideal solutions but rather patches. Right now we're assessing the possibility of redesigning Rootcheck, because, as you can see, this implementation (inherited from ossec) is prone to false positives.

I hope it helps.

Kind regards,
Fernando

**Comment by alago197** [comment]
OK, Fernando, thanks.

**Comment by phxyz12** [comment]
Hi

Four years and 10 months later, this issues still persists e. g. on Rocky Linux 9.5 where the sym links are named `sendmail`.

Cheers,

Pascal

**Comment by DavorSaric** [comment]
Yes, it is still present with s-nail on Rocky 9.5

**Comment by mj84** [comment]
This issue still persists 6 years later in Rocky Linux 9.7
