### ISSUE TITLE
Manager status fails when hidepid mount option is used

### ISSUE THREAD

**Issue by GwennG** [wazuh/wazuh#4630]
|Wazuh version|Component|Install method|Platform|
|---|---|---|---|
| 3.11.3-1 | Manager | Packages | Debian 10.3 |

When the `/proc` filesystem is mounted with `hidepid=(1|2)` option, the `get_manager_status()` function from `framework/wazuh/cluster/utils.py` returns state `stopped` for processes because it can't read `/proc/<PID>` folder.

As the state is always `stopped`, the Wazuh Kibana app is not functional.

**Comment by crd1985** [comment]
Hi @GwennG,

After doing some research, I believe this issue cannot be considered a bug anymore. The reason is that the Wazuh framework and API relies on /proc to check the status of other components.

If you still need to harden your server with `hidepid` option, consider including a `gid` option to allow any other users in the ossec group to see their status. This is an example taken from my `/etc/fstab` test environment:
```
proc           /proc        proc         defaults,hidepid=2,gid=993    0    0
```
where `993` is the gid for ossec group taken from `/etc/passwd`.

This is the result of the `get_manager_status` function under this config:
```
>>> from wazuh.cluster.utils import get_manager_status
>>> get_manager_status()
{'ossec-agentlessd': 'running', 'ossec-analysisd': 'running', 'ossec-authd': 'running', 'ossec-csyslogd': 'running', 'ossec-dbd': 'stopped', 'ossec-monitord': 'running', 'ossec-execd': 'running', 'ossec-integratord': 'running', 'ossec-logcollector': 'running', 'ossec-maild': 'stopped', 'ossec-remoted': 'running', 'ossec-reportd': 'stopped', 'ossec-syscheckd': 'running', 'wazuh-clusterd': 'running', 'wazuh-modulesd': 'running', 'wazuh-db': 'running'}
```

I will keep this issue opened because I consider the documentation should explain this case. We will study where and how include it for future releases.

Let me know how it goes.

Regards,
Daniel Ruiz

**Comment by GwennG** [comment]
Hi @crd1985 

Thanks for your reply and for pointing the `gid` option out.
I tried it and it works fine.

Regards,
Gwenn
