### ISSUE TITLE
Buffer Overflow and Policy ID Errors when deleting or modifying files with syscheck:realtime

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh#4724]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12 Fim Testing Branch | Syscheck | Agent| Packages| Windows Server 2016|

- **wazuh-agent Custom Package RPM URL**:  _https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/warehouse/branches/3.12/windows/wazuh-agent-3.12.0-0.3319fimreworksqlite.msi_
- **wazuh-agent Windows package name**: _wazuh-agent-3.12.0-0.3319fimreworksqlite.msi_
- **md5** : _864b57b960d5e23ed704d96cabc5aaf2_
---

**Problem Description**
When deleting or when modifying files, we experienced a shortage in the number of expected alerts to be received by the manager.

---

**Syscheck Configuration**
```xml
<directories recursion_level="320" check_all="yes" realtime="yes">
C:\fim_testing
</directories>
```

---

**Error Log**
```
> ossec-agent: ERROR: Could not get message for (policy_id)
> Warning: (6906): Real time process: no data. Probably buffer overflow.
> ossec-agent: WARNING: At get_user(c:\fim_testing\eupyh\jtpre\rzjvd\ixiqkgfj): CreateFile():
    The system cannot find the file specified. (2)
> Warning: (6906): Real time process: no data. Probably buffer overflow.
```
---

**How To Re-Produce**

To generate files, we ran the script [generate_files.py](https://github.com/wazuh/wazuh-qa/blob/feature-493-create-test-scenarios/tests/system/fim/common_tasks/generate_files.py)

**`Number of Files:`** 5010

files_configuration.json is found [here](https://github.com/wazuh/wazuh-qa/blob/feature-493-create-test-scenarios/tests/system/fim/common_tasks/files_configuration.json.j2)

```bash

python3 generate_files.py -c files_configuration.json -o files_generated.txt"
```

To modify the files, then we ran the script [modify_files.py](https://github.com/wazuh/wazuh-qa/blob/feature-493-create-test-scenarios/tests/system/fim/common_tasks/modify_files.py)

```
python3 modify_files.py -i files_generated.txt -o files_modified.txt -t
```

or to delete the files
```
python3 delete_files.py -i files_generated.txt -o files_modified.txt -t
```

Kr,

Rshad

**Comment by jesusjimsa** [comment]
This issue appears to be related with the available memory in Windows.
The warning message that appears when adding a big amount of files is only written to the log in the `RTCallBack` function in the `run_realtime.c` file. One of its parameters is `dwBytes`, which refers to the size of the memory block available. If this value is `0`, the warning appears in the log and the file is not inserted in the database nor the realtime hash table, because the buffer is full. All the files added after filling the buffer, will be ignored by the realtime engine and, if they are modified later, the alert will show them as added, even though they are being modified.
When inserting 5050 files with a 0.2 seconds delay between each file, every file is inserted in the database and the hash table correctly.
The `RTCallBack` is this one:
https://github.com/wazuh/wazuh/blob/67d39a0e492179b79725a0fc769680d5cbbb4129/src/syscheckd/run_realtime.c#L225-L305
