### ISSUE TITLE
Getting "Please set up Wazuh API credentials" popup message during access kibana dashboard

### ISSUE THREAD

**Issue by zakirpcs** [wazuh/wazuh#4804]
I am getting below popup during access kibana dashboard. While my credential is correct. Also credential test is ok.
"Wazuh App: Please set up Wazuh API credentials."

Also getting bellow error message at /usr/share/kibana/optimize/wazuh/logs/wazuhapp.log file:

ERROR | Cannot convert undefined or null to object

Can anyone help me to resolve the issue. Also note that my wazuh environment as below:

Wazuh Version: 3.12.0
ELK: 7.6.1

**Comment by juankaromo** [comment]
Hi @zakirpcs 

It could be due to an incorrect cookie in the cache, perhaps due to an earlier version installed.

You need to delete all cookies stored in your browser and try to enter the Wazuh app again.

In Chrome you must press F12 to open the developer tools. In them, go to Application, and Delete all <kibana_ip> cookies:

![image](https://user-images.githubusercontent.com/21195730/77858870-7403d580-7206-11ea-8c14-98b27f89f431.png)

In Firefox you must press F12 to open the developer tools. In them, go to Storage, and Delete all <kibana_ip> cookies:

![image](https://user-images.githubusercontent.com/21195730/77858859-6ea68b00-7206-11ea-8823-026e5a69ed7b.png)

Once deleted, try to access it again. Tell us the results.

Regards.

**Comment by zakirpcs** [comment]
Hi Juanka,
Thanks for your help its working now.
