### ISSUE TITLE
Duplicate file descriptors when starting logcollector in Windows systems.

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#4920]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12.* | Logcollector | Agent | Packages/Sources | Windows |

We have detected a leak of descriptors in Windows agents when they are configured in logcollector files with Wildcards, for example:

```xml
  <localfile>
    <location>C:\test\logcollector\test*.log</location>
    <log_format>syslog</log_format>
  </localfile>
```

The wildcard expands to monitor all log files matched.

```
2020/04/16 16:17:05 ossec-agent: INFO: Windows version is 6.0 or newer. (Microsoft Windows Server 2016 Standard Evaluation [Ver: 10.0.14393] - Wazuh v3.12.3).
2020/04/16 16:17:05 ossec-agent: INFO: (1950): Analyzing file: 'C:\test\logcollector\test1.log'.
2020/04/16 16:17:05 ossec-agent: INFO: (1950): Analyzing file: 'C:\test\logcollector\test2.log'.
2020/04/16 16:17:05 ossec-agent: INFO: (1950): Analyzing file: 'C:\test\logcollector\test3.log'.
2020/04/16 16:17:05 ossec-agent: INFO: (1950): Analyzing file: 'C:\test\logcollector\test4.log'.
```

If we examine the file descriptors opened by the agent we find the duplicated log files.

![Captura de pantalla de 2020-04-16 16-19-00](https://user-images.githubusercontent.com/6572618/79468645-76846e80-7fff-11ea-99b0-aecb0789f4bf.png)

In case the files do not exist when the agent starts, only open them once.

Therefore the leak is limited to the number of files that are monitored when the wildcard is expanded when the agent starts.

Thanks @okynos to report.
Regards.

**Comment by antoniomanuelfr** [comment]
The problem is caused because logcollector is calling twice to the function: `handle_file` if the wildcard * is present. In case the wildcard is omitted, only calls once to the function `handle_file`. 
The two callings are in this parts of the code: 
1. Function `check_pattern_expand(1): https://github.com/wazuh/wazuh/blob/e36bb6f1f3b6c6c0ab4423cf2de60c19b0655408/src/logcollector/logcollector.c#L1309 
2.Function `LogCollectorStart`:  https://github.com/wazuh/wazuh/blob/e15ae79d71b606bf0a684bf6667fb79ee6894f42/src/logcollector/logcollector.c#L267
