### ISSUE TITLE
Support for native GuardDuty to S3 via AWS S3 Wodle

### ISSUE THREAD

**Issue by mire3212** [wazuh/wazuh#4950]
AWS released an update to GuardDuty that now supports direct GuardDuty to S3 integration and no longer requires a Kinesis/Firehose/CloudWatch integration to export events to S3. The mechanism is effectively identical to CloudTrail in the format and style of notification delivery.

https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-guardduty-supports-exporting-findings-to-an-amazon-s3-bucket/

Please consider adding this native support as it make administration easier, or avoid additional incurred costs of having to use CloudWatch + Kinesis/Firehose.

**Comment by danimegar** [comment]
Hi @mire3212 
Thank you for the information. This native support simplifies the process to get the GuardDuty events. We will modify the Wazuh module for AWS to add it.

Regards,
Daniel

**Comment by ben79git** [comment]
Is there any time scale on when this support will come? We are in the process of setting up Wazuh but I would like to avoid the additional setup of Kinesis/Firehose/CloudWatch for GuardDuty logs now that AWS directly supports export to S3.

Thanks

**Comment by danimegar** [comment]
Hello @ben79git

**Comment by danimegar** [comment]
Hello @ben79git 

We have in mind to do a development to incorporate this native tool to AWS although unfortunately, we have not been able to plan it yet. We will keep you informed when there is new news about it.

**Comment by okynos** [comment]
|Wazuh version|Component|
|---|---|
| All | AWS-S3 wodle |

Hello all,

We want to bump this issue to keep track of it.
This way to use GuardDuty allow users to store the events directly to S3. We want to include support to this feature avoiding the use of Firehose and Amazon Kinesis.

By the moment we have detected the following troubles:
- GuardDuty events are stored in JSONL format instead of old ones JSON.
- The GuardDuty stored fields differs from stored with the old method.

Regards.

**Comment by taxidis** [comment]
Is this effort dropped? It really makes sense to use the guardduty to s3 feature as it simplifies infra setup.

**Comment by davidjiglesias** [comment]
Necessary steps:
- Review the impact of native GuardDuty logs in the decoders and rules
- Do we maintain support for both Kinesis + native GuardDuty?
- Generate sample logs for manual and integration testing
- Implement development

**Comment by fdalmaup** [comment]
# Issue Update

In our current implementation of the module, `GuardDuty` events are stored  in .zip files inside AWS S3 buckets. The logs present inside these files contain the following structure:

```json
{
    "version": "0",
    "id": "id",
    "detail-type": "GuardDuty Finding",
    "source": "aws.guardduty",
    "account": "account-id",
    "time": "date",
    "region": "region",
    "resources": [],
    "detail": {
        "..."
    }
}
```
`GuardDuty` event information can be found inside the `detail` field.
When directly exporting `GuardDuty` Findings, the name of the fields match with those of the `detail` field differing in the camelCase type (e.g. `resourceType` and `ResourceType`). Our current implementation uses many of these fields to manipulate data and send it to `Analysisd`, starting with the `detail` field previously mentioned.

https://github.com/wazuh/wazuh/blob/011dbf0006dc3a30291484fa5c3a271d5924fd2c/wodles/aws/aws_s3.py#L2093-L2098

Therefore, the results of exporting the findings to S3 need to be analyzed to determine if these are changed in the process in order to design a solution that does not require AWS Kinesis Firehose and that may be similar to the one used for our current `CloudTrail` implementation. This last point could be useful for refactoring our code to avoid duplicate logic.

Another important point is the one pointed out in the previous comment regarding the maintenance of support for both Kinesis + native GuardDuty. It should be discussed after testing the native GuardDuty mechanism

**Comment by fdalmaup** [comment]
# Issue Update

An export of `GuardDuty` sample findings to an S3 bucket, setting up the `Findings export options`, has been carried out. 
As stated [here](https://github.com/wazuh/wazuh/issues/4950#issuecomment-793891330), `GuardDuty` events are stored in the bucket as `jsonl.gz` files preceded by the prefix of the format `AWSLogs/account-id/GuardDuty/region/YEAR/MONTH/DAY/`.
![image](https://user-images.githubusercontent.com/26691145/191351647-56f40d82-1b1d-4cc3-9864-2ddd6de4f79f.png)

The mentioned prefix is common to the buckets used for `CloudTrail`  and `Config`, which in our module are handled by subclasses of the `AWSLogsBucket` class, having the latter the necessary logic to browse through the folders. Therefore, the code can be refactored so the `AWSGuardDutyBucket` class inherits its behavior from `AWSLogsBucket` , avoiding duplicate code.
None of the mentioned classes handle JSONL type files, so it will be required to develop the logic to extract each JSON from those files and send them to `Analysisd`, probably overriding the `load_information_from_file` method of the `AWSLogsBucket` class. 

The events have the same format and field names as those present in our current implementation, so at first glance it does not present a problem for decoders and rules. It will be tested once the final development is implemented.

As a final note, it should be determined if both mechanisms will be maintained in order to move forward with the development.

**Comment by fdalmaup** [comment]
# Issue Update

Reviewing the current code, it was found that the `load_information_from_file` is the method used to generate the information that will be sent. 
In `AWSCustomBucket`, the one used by the current GuardDuty implementation, the method is the following:
https://github.com/wazuh/wazuh/blob/8fec08af38d66246aa1d26e5fdfc3a10ad922d1d/wodles/aws/aws_s3.py#L2096-L2123

This method takes into account the possibility that the file does not contain a JSON log due to the different bucket types that could be custom types.

The method in the `AWSLogsBucket` class is the following:

https://github.com/wazuh/wazuh/blob/8fec08af38d66246aa1d26e5fdfc3a10ad922d1d/wodles/aws/aws_s3.py#L1173-L1177

This is the key method to be tested and/or refactored in order to generate a minimum impact with the GuardDuty native implementation.

**Comment by fdalmaup** [comment]
# Issue Update

The following approach has been developed in a separate branch in order to test code modifications. The main goal is to change the code in the simplest way possible for its maintenance and update when the original implementation gets deprecated. 
An override of the `load_information_from_file` method in the `AWSGuardDutyBucket` was carried out as shown below:

```python3
    def load_information_from_file(self, log_key):
        if log_key.split('.', 1)[1] == 'jsonl.gz':
            with self.decompress_file(log_key=log_key) as f:
                json_list = list(f)
                return [dict(json.loads(x), source=json.loads(x)['service']['serviceName']) for x in json_list]
        else:
            debug("+++ WARNING: The GuardDuty + Kinesis integration will be deprecated in future releases. GuardDuty "
                  "native support should be used instead", 1) 
            AWSCustomBucket.load_information_from_file(self, log_key)
```

To obtain the logs from the bucket that receives directly from GuardDuty, the following command can be used after the modification of the code:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-guardduty-native -t guardduty -l test-4950/AWSLogs/<account_id>/GuardDuty/us-east-1/ -s 2021-Jun-22 -p dev -d2 
```

**Note** that, due to the use of the current implementation of `AWSCustomBucket`, the parameter `-l` was added with the default prefix that is set up when exporting findings options is configured in `GuardDuty`.

Currently, the results in the `archives.log` file are giving a repeated log (`"aws, "id": "46c1adb1d69b32284ea1a42a0d871477"`) for reasons yet to be discovered.

The original behavior, that is for buckets that make use of the Kinesis integration, was also tested with the following command:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-guardduty -t custom -s 2021-Jun-22 -p dev -d2 | grep -v 'Skipping file with'
```

Giving the expected results:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-guardduty -t custom -s 2021-Jun-22 -p dev -d2 | grep -v 'Skipping file with'
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: +++ Table does not exist; create
DEBUG: +++ Marker: 2021/06/22
DEBUG: ++ Found new log: 2021/06/22/16/firehose_guardduty-1-2021-06-22-16-15-05-872e154c-1fd8-4369-a151-947ec0438d8d.zip
DEBUG: ++ Found new log: 2021/07/08/03/firehose_guardduty-1-2021-07-08-03-46-07-12788dc1-723b-4e2b-9d12-07885e967524.zip
DEBUG: ++ Found new log: 2021/12/24/03/firehose_guardduty-1-2021-12-24-03-46-07-12788dc1-723b-4e2b-9d12-07885e967524.zip
DEBUG: +++ DB Maintenance
```

**Comment by fdalmaup** [comment]
# Issue Update

After discussing with the team, the first approach needed to be modified in order to maintain a certain level of consistency regarding how the rest of the AWS module integrations work. The use of the prefix `.../AWSLogs/<account_id>/GuardDuty/<region>` would limit the users to set manually the `account_id` and `region` sections of the prefix. Therefore a different approach has been carried out, making the `AWSGuardDutyBucket` a child of the `AWSLogsBucket` class. This brought several issues due to the difference between the SQL queries defined in `AWSLogsBucket` and `AWSCustomBucket`. 

The next approach being developed is maintaining the original inheritance from `AWSCustomBucket` and finding a way to check if the `AWSLogs/` folder is present in the bucket to retrieve GuardDuty Native logs.

**Comment by fdalmaup** [comment]
# Issue Update

The code has been modified in order to accept both types of buckets transparently to the user. The `AWSGuardDutyBucket` remains a child of the `AWSCustomBucket` class. Several methods have been redefined in `AWSGuardDutyBucket` and a check at the `__init__` method has been added in order to determine which type of bucket will be used. This is a proposal, not definitive, the type check adds complexity to the code but, assuming that in the next closest release the GuardDuty + Kinesis will be deprecated, it's worth the cost.

The code that covers the complete deprecation of the current implementation is already developed since it was part of one of the redesigns of the module for this issue.

The new design shall be discussed with the team before opening the corresponding PR

## Manual tests

### GuardDuty + Kinesis Bucket
Command
`/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-guardduty -t guardduty -s 2021-Jun-22 -p dev -d2 | grep -v 'Skipping file with'`

Results
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-guardduty -t guardduty -s 2021-Jun-22 -p dev -d2 | grep -v 'Skipping file with'
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: +++ Table does not exist; create
DEBUG: +++ WARNING: The GuardDuty + Kinesis integration will be deprecated in future releases. GuardDuty native support should be used instead
DEBUG: +++ Marker: 2021/06/22
DEBUG: ++ Found new log: 2021/06/22/16/firehose_guardduty-1-2021-06-22-16-15-05-872e154c-1fd8-4369-a151-947ec0438d8d.zip
DEBUG: ++ Found new log: 2021/07/08/03/firehose_guardduty-1-2021-07-08-03-46-07-12788dc1-723b-4e2b-9d12-07885e967524.zip
DEBUG: ++ Found new log: 2021/12/24/03/firehose_guardduty-1-2021-12-24-03-46-07-12788dc1-723b-4e2b-9d12-07885e967524.zip
DEBUG: +++ DB Maintenance
```

### GuardDuty Native
Command
`/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-guardduty-native -t guardduty -l test-4950/ -s 2021-Jun-22 -p dev -d2`

Results
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-guardduty-native -t guardduty -l test-4950/ -s 2021-Jun-22 -p dev -d2 
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: +++ Working on account-id - region
DEBUG: +++ Marker: test-4950/AWSLogs/account-id/GuardDuty/region/2021/06/22
DEBUG: ++ Found new log: test-4950/AWSLogs/account-id/GuardDuty/region/2022/09/20/09d41cb2-dc23-3ec6-a59d-b77625c6ddd8.jsonl.gz
DEBUG: ++ Found new log: test-4950/AWSLogs/account-id/GuardDuty/region/2022/09/20/2642d6b9-c0c0-30e4-a7cb-ce1983c53e1b.jsonl.gz
DEBUG: ++ Found new log: test-4950/AWSLogs/account-id/GuardDuty/region/2022/09/20/388203f4-4d6b-3be7-8790-843978860f98.jsonl.gz
DEBUG: ++ Found new log: test-4950/AWSLogs/account-id/GuardDuty/region/2022/09/20/4b6c54fe-fb15-357a-b7d9-20099bea7999.jsonl.gz
DEBUG: ++ Found new log: test-4950/AWSLogs/account-id/GuardDuty/region/2022/09/20/4bc69a8c-53b8-30bd-9f1d-11bf615b5cbd.jsonl.gz
DEBUG: ++ Found new log: test-4950/AWSLogs/account-id/GuardDuty/region/2022/09/20/566c9fde-c2bf-34eb-b1f0-dc37f0665c6f.jsonl.gz
DEBUG: ++ Found new log: test-4950/AWSLogs/account-id/GuardDuty/region/2022/09/20/a54d242d-0200-3fcc-a321-3ff67887047d.jsonl.gz
DEBUG: ++ Found new log: test-4950/AWSLogs/account-id/GuardDuty/region/2022/09/20/ba106b79-a888-3dab-bc58-f929860d3776.jsonl.gz
DEBUG: ++ Found new log: test-4950/AWSLogs/account-id/GuardDuty/region/2022/09/20/c65747f2-c625-3972-b9b6-222172434149.jsonl.gz
DEBUG: ++ Found new log: test-4950/AWSLogs/account-id/GuardDuty/region/2022/09/20/d995abe7-81df-397d-8a0a-b1033a4058af.jsonl.gz
DEBUG: ++ Found new log: test-4950/AWSLogs/account-id/GuardDuty/region/2022/10/21/4ca2d459-4b27-34f9-9f96-0689041ab45b.jsonl.gz
DEBUG: ++ Found new log: test-4950/AWSLogs/account-id/GuardDuty/region/2022/10/21/b67b5cbd-cf37-3c91-97ad-2ab367d01eab.jsonl.gz
DEBUG: ++ Found new log: test-4950/AWSLogs/account-id/GuardDuty/region/2022/10/21/ec7b0b8c-5ec8-32ec-8e77-c738515b4f6f.jsonl.gz
DEBUG: +++ DB Maintenance
```

**Comment by fdalmaup** [comment]
# Manual Tests
The following tests have been carried out in a v4.5 Wazuh Manager

## GuardDuty Native Bucket
Command
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-guardduty-native -t guardduty -s 2021-Jun-22 -p dev -d2
```
Results
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-guardduty-native -t guardduty -s 2021-Jun-22 -p dev -d2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: +++ Table does not exist; create
DEBUG: +++ Working on account-id - region
DEBUG: +++ Marker: AWSLogs/account-id/GuardDuty/region/2021/06/22
DEBUG: ++ Found new log: AWSLogs/account-id/GuardDuty/region/2022/09/20/09d41cb2-dc23-3ec6-a59d-b77625c6ddd8.jsonl.gz
DEBUG: ++ Found new log: AWSLogs/account-id/GuardDuty/region/2022/09/20/2642d6b9-c0c0-30e4-a7cb-ce1983c53e1b.jsonl.gz
DEBUG: ++ Found new log: AWSLogs/account-id/GuardDuty/region/2022/09/20/388203f4-4d6b-3be7-8790-843978860f98.jsonl.gz
DEBUG: ++ Found new log: AWSLogs/account-id/GuardDuty/region/2022/09/20/4b6c54fe-fb15-357a-b7d9-20099bea7999.jsonl.gz
DEBUG: ++ Found new log: AWSLogs/account-id/GuardDuty/region/2022/09/20/4bc69a8c-53b8-30bd-9f1d-11bf615b5cbd.jsonl.gz
DEBUG: ++ Found new log: AWSLogs/account-id/GuardDuty/region/2022/09/20/566c9fde-c2bf-34eb-b1f0-dc37f0665c6f.jsonl.gz
DEBUG: ++ Found new log: AWSLogs/account-id/GuardDuty/region/2022/09/20/a54d242d-0200-3fcc-a321-3ff67887047d.jsonl.gz
DEBUG: ++ Found new log: AWSLogs/account-id/GuardDuty/region/2022/09/20/ba106b79-a888-3dab-bc58-f929860d3776.jsonl.gz
DEBUG: ++ Found new log: AWSLogs/account-id/GuardDuty/region/2022/09/20/c65747f2-c625-3972-b9b6-222172434149.jsonl.gz
DEBUG: ++ Found new log: AWSLogs/account-id/GuardDuty/region/2022/09/20/d995abe7-81df-397d-8a0a-b1033a4058af.jsonl.gz
DEBUG: ++ Found new log: AWSLogs/account-id/GuardDuty/region/2022/10/21/4ca2d459-4b27-34f9-9f96-0689041ab45b.jsonl.gz
DEBUG: ++ Found new log: AWSLogs/account-id/GuardDuty/region/2022/10/21/b67b5cbd-cf37-3c91-97ad-2ab367d01eab.jsonl.gz
DEBUG: ++ Found new log: AWSLogs/account-id/GuardDuty/region/2022/10/21/ec7b0b8c-5ec8-32ec-8e77-c738515b4f6f.jsonl.gz
DEBUG: +++ DB Maintenance
```
## GuardDuty + Kinesis Bucket
Command
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-guardduty -t guardduty -s 2021-Jun-22 -p dev -d2 | grep -v 'Skipping file with'
```
Results
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-guardduty -t guardduty -s 2021-Jun-22 -p dev -d2 | grep -v 'Skipping file with'
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
The GuardDuty + Kinesis integration was deprecated in 4.5. GuardDuty native support should be used instead. Check https://documentation.wazuh.com/current/amazon/services/supported-services/guardduty.html#amazon-configuration for more information.
DEBUG: +++ Marker: 2021/06/22
DEBUG: ++ Found new log: 2021/06/22/16/firehose_guardduty-1-2021-06-22-16-15-05-872e154c-1fd8-4369-a151-947ec0438d8d.zip
DEBUG: ++ Found new log: 2021/07/08/03/firehose_guardduty-1-2021-07-08-03-46-07-12788dc1-723b-4e2b-9d12-07885e967524.zip
DEBUG: ++ Found new log: 2021/12/24/03/firehose_guardduty-1-2021-12-24-03-46-07-12788dc1-723b-4e2b-9d12-07885e967524.zip
DEBUG: +++ DB Maintenance
```

## Conclusions
Every processed log was present in the `archives` file. The module works as expected, processing both types of buckets

**Comment by fdalmaup** [comment]
# ossec.conf Test

The following configuration was added to the `ossec.conf` file
```
<wodle name="aws-s3">
    <disabled>no</disabled>
    <remove_from_bucket>no</remove_from_bucket>
    <interval>10m</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>no</skip_on_error>

    <bucket type="guardduty">
        <aws_profile>dev</aws_profile>
        <name>wazuh-aws-wodle-guardduty-native</name>
        <only_logs_after>2021-Jun-22</only_logs_after>
    </bucket>

    <bucket type="guardduty">
        <aws_profile>dev</aws_profile>
        <name>wazuh-aws-wodle-guardduty</name>
        <only_logs_after>2021-Jun-22</only_logs_after>
    </bucket>
</wodle>
```
<details><summary>ossec.log</summary>

    2022/10/24 15:56:12 wazuh-modulesd:aws-s3[3320] wm_aws.c:59 at wm_aws_main(): INFO: Module AWS started
    2022/10/24 15:56:12 wazuh-modulesd:aws-s3[3320] wm_aws.c:81 at wm_aws_main(): INFO: Starting fetching of logs.
    2022/10/24 15:56:12 wazuh-modulesd:aws-s3[3320] wm_aws.c:133 at wm_aws_main(): INFO: Executing Bucket Analysis: (Bucket: wazuh-aws-wodle-guardduty-native, Type: guardduty, Profile: dev)
    2022/10/24 15:56:12 wazuh-modulesd:aws-s3[3320] wm_aws.c:328 at wm_aws_run_s3(): DEBUG: Create argument list
    2022/10/24 15:56:12 wazuh-modulesd:aws-s3[3320] wm_aws.c:443 at wm_aws_run_s3(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --bucket wazuh-aws-wodle-guardduty-native --aws_profile dev --only_logs_after 2021-Jun-22 --type guardduty --debug 2
    2022/10/24 15:56:18 wazuh-modulesd:aws-s3[3320] wm_aws.c:483 at wm_aws_run_s3(): DEBUG: Bucket:  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
    2022/10/24 15:56:19 wazuh-modulesd:aws-s3[3320] wm_aws.c:133 at wm_aws_main(): INFO: Executing Bucket Analysis: (Bucket: wazuh-aws-wodle-guardduty, Type: guardduty, Profile: dev)
    2022/10/24 15:56:19 wazuh-modulesd:aws-s3[3320] wm_aws.c:328 at wm_aws_run_s3(): DEBUG: Create argument list
    2022/10/24 15:56:19 wazuh-modulesd:aws-s3[3320] wm_aws.c:443 at wm_aws_run_s3(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --bucket wazuh-aws-wodle-guardduty --aws_profile dev --only_logs_after 2021-Jun-22 --type guardduty --debug 2
    2022/10/24 15:56:22 wazuh-modulesd:aws-s3[3320] wm_aws.c:483 at wm_aws_run_s3(): DEBUG: Bucket:  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
    2022/10/24 15:56:26 wazuh-modulesd:aws-s3[3320] wm_aws.c:173 at wm_aws_main(): INFO: Fetching logs finished.
    2022/10/24 15:56:26 wazuh-modulesd:aws-s3[3320] wm_aws.c:77 at wm_aws_main(): DEBUG: Sleeping until: 2022/10/24 16:06:12
</details>

## Conclusions
The module worked as expected. The events were sent to the analysis engine.
