### ISSUE TITLE
New install:  Visualize: Fielddata is disabled on text fields by default. 

### ISSUE THREAD

**Issue by crazyhandpuppet** [wazuh/wazuh#496]
I have a new install on Ubuntu 16.04.4.  I just managed to get the API connected but there appears to be something wrong.  At the top of the overview and agents pages I'm getting:

Visualize: Fielddata is disabled on text fields by default. Set fielddata=true on [agent.name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.

The overview page has blank graphs.  The Agents page is blank.

**Comment by crazyhandpuppet** [comment]
I've tried an uninstall / reinstall to no avail:
apt-get remove wazuh-manager
apt-get remove wazuh-api
apt-get install wazuh-manager
apt-get install wazuh-api

The problem persists.

**Comment by crazyhandpuppet** [comment]
I just did another fresh install with the same results.  These are the steps I took:
apt-get update
apt-get upgrade
apt-get update
apt-get install curl apt-transport-https lsb-release
curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
echo "deb https://packages.wazuh.com/3.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
apt-get update
ufw allow ssh
ufw allow 55000/tcp
ufw allow 5601/tcp
ufw allow 1514/tcp
ufw enable
apt-get install wazuh-manager -y
systemctl status wazuh-manager
curl -sL https://deb.nodesource.com/setup_6.x | bash -
apt-get install nodejs -y
apt-get install wazuh-api -y
systemctl status wazuh-api
add-apt-repository ppa:webupd8team/java
apt-get update -y
apt-get install oracle-java8-installer -y
apt-get install curl apt-transport-https -y
curl -s https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | tee /etc/apt/sources.list.d/elastic-6.x.list
apt-get update
apt-get install elasticsearch=6.2.2 -y
systemctl daemon-reload
systemctl enable elasticsearch.service
systemctl start elasticsearch.service
curl https://raw.githubusercontent.com/wazuh/wazuh/3.2/extensions/elasticsearch/wazuh-elastic6-template-alerts.json | curl -XPUT 'http://localhost:9200/_template/wazuh' -H 'Content-Type: application/json' -d @-
curl https://raw.githubusercontent.com/wazuh/wazuh/3.2/extensions/elasticsearch/wazuh-elastic6-template-monitoring.json | curl -XPUT 'http://localhost:9200/_template/wazuh-agent' -H 'Content-Type: application/json' -d @-
curl https://raw.githubusercontent.com/wazuh/wazuh/3.2/extensions/elasticsearch/alert_sample.json | curl -XPUT "http://localhost:9200/wazuh-alerts-3.x-"`date +%Y.%m.%d`"/wazuh/sample" -H 'Content-Type: application/json' -d @-
apt-get install logstash=1:6.2.2-1 -y
usermod -a -G ossec logstash
curl -so /etc/logstash/conf.d/01-wazuh.conf https://raw.githubusercontent.com/wazuh/wazuh/3.2/extensions/logstash/01-wazuh-local.conf
systemctl daemon-reload
systemctl enable logstash.service
systemctl start logstash.service
apt-get install kibana=6.2.2 -y
/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.2.1_6.2.2.zip
systemctl daemon-reload
systemctl enable kibana.service
systemctl start kibana.service
sed -i -r '/deb https:\/\/artifacts.elastic.co\/packages\/6.x\/apt stable main/ s/^(.*)$/#\1/g' /etc/apt/sources.list.d/elastic-6.x.list
sed -i '/#server.host: "localhost"/ c\ server.host: "0.0.0.0"' /etc/kibana/kibana.yml
/var/ossec/api/scripts/configure_api.sh

I've put it into a script and then run it as root.

**Comment by crazyhandpuppet** [comment]
Have also tried

apt-get purge wazuh-manager
apt-get autoremove
rm -rf /var/ossec
rm -f /etc/ossec-init.conf
rm -f `find /etc/rc* | grep wazuh`
apt-get install wazuh-api

With the same results.  I feel like I'm going down a rabbit hole...

**Comment by crazyhandpuppet** [comment]
Well, it has something to do with the script.  If I go through and run each line one by one it appears to work normally.  Maybe a process is starting before another is finishing?

**Comment by crazyhandpuppet** [comment]
Once I realized it was the script I went back and added some stops to see what was happening and there were a lot of connection refused errors loading the templates.  So I added a sleep 30 line after systemctl start elasticsearch.service and it went through properly this time.

**Comment by havidarou** [comment]
Hello,

you are right.

If you take a look at our installation guide:
https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/elastic_server_deb.html#elastic-server-deb

there is a note before inserting the templates warning about Elasticsearch
taking a bit to start.

The error you mention occurs when a visualization is prepared to accept a
certain type of field and then finds it with a different type (in this case
due to an incorrect template).

Hope that helps!

Regards.

**Comment by crazyhandpuppet** [comment]
Thanks. That note is what had me start looking there. Now that I've
figured out how to properly install, how do I fix the existing install?

**Comment by JuanjiJG** [comment]
Hello @crazyhandpuppet, and sorry for the late response.

If your Elastic server has already created indices, these won't be valid for the Wazuh app, because the app expects indices with a specific type of fields, that's why we must insert the template before starting Logstash, which sends the alerts to Elasticsearch.

To insert the templates, just execute the following commands:
```
curl https://raw.githubusercontent.com/wazuh/wazuh/3.2/extensions/elasticsearch/wazuh-elastic6-template-alerts.json | curl -XPUT 'http://localhost:9200/_template/wazuh' -H 'Content-Type: application/json' -d @-
curl https://raw.githubusercontent.com/wazuh/wazuh/3.2/extensions/elasticsearch/wazuh-elastic6-template-monitoring.json | curl -XPUT 'http://localhost:9200/_template/wazuh' -H 'Content-Type: application/json' -d @-
```

Your old indices will not be considered for the app, but the new ones will be generated correctly if you've inserted the template following the steps. What you can do (but it's not mandatory) is delete the old ones if you don't really need to keep the old alerts.

List your current indices with this command:
```
curl -XGET localhost:9200/_cat/indices?v
```
Locate the indices starting with `wazuh-alerts-3.x-*` (usually followed by the year-month-day the index was created). You can delete them with this command:
```
curl -XDELETE 'localhost:9200/<index_name>?pretty'
```

Please let me know about the results with this. If you still have questions or problems, don't hesitate to post a new comment.

Thanks for your patience.

Best regards,
Juanjo

**Comment by JuanjiJG** [comment]
Hello @crazyhandpuppet,

It's been more than a month since the last response to this issue, so I'll proceed to close it. Please, if you still have problems with Wazuh or the Wazuh app, open a new thread.

For a better assistance and tracking of your issues, you can use our [Wazuh app repository](https://github.com/wazuh/wazuh-kibana-app/issues) to open an issue if your problem is related to the app.

Regards,
Juanjo
