### ISSUE TITLE
Logs from agents

### ISSUE THREAD

**Issue by a108a108** [wazuh/wazuh#4984]
Hi guys,

according to the documentation:  "Alerts will be stored at /var/ossec/logs/alerts/alerts.(json|log) and events at /var/ossec/logs/archives/archives.(json|log). Logs are rotated and an individual directory is created for each month and year."

I collect syslog (every facility and every level) and accesslog from nginx and its sent via the rsyslog service(not the agent), alerts are working correctly but in 
/var/ossec/logs/archives/archives all the files are empty. Is there a way i can see all the syslog/log collected?

Thanks!

Manager/Agents version 3.12.2
OS: Cent OS 7.7

**Comment by antoniomanuelfr** [comment]
Hi @a108a108 
By default the output to the archives is disabled.
In order to make wazuh register every event in the archives you must enable the `log_all`  or/and the `log_all_json` from the config file that is located in `/var/ossec/etc/ossec.conf`. 
This is the link in the docs: https://documentation.wazuh.com/3.12/user-manual/reference/ossec-conf/global.html#logall
After changing these options you will have to restart wazuh. 
Could you please check if these options are disabled? 
Regards, 
Antonio.

**Comment by a108a108** [comment]
Yes it was disabled, now i see them.

Thanks!

**Comment by antoniomanuelfr** [comment]
Hi, I`m glad that it was useful. 
I'm going to close this issue. 
Regards.
