### ISSUE TITLE
[Development] cluster-control doesn't work if wazuh-clusterd is running in the foreground

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh#5011]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.0-31300 | cluster-control | Manager | Packages | CentOS 7 |

Hi team,

I found this issue while testing `wazuh-clusterd` after upgrading the Python interpreter from 3.7.2 to 3.8.2. I set up the cluster with a master and a worker node, both of them are running in the foreground.

If you run `cluster-control` in any of the nodes, this is the output:
```shellsession
# /var/ossec/bin/cluster_control -l 
ERROR: Cluster is not running.
```

**Comment by whuskeytombras** [comment]
I am attempting to set up a Master and Worker node cluster for the first time and have run into this issue myself. I cannot seem to get the Cluster to run. I am using a clean install of the OVA from wazuh and a clean install of centOS 8 for the second manager, in a sandbox environment.

**Comment by BraulioV** [comment]
Hi @whuskeytombras,

Thanks for reporting it. I made some testing and I could reproduce your error in several scenarios. I just opened #5744 and we're currently investigating this issue. I'll keep you updated.

Thanks again,
Braulio.

**Comment by whuskeytombras** [comment]
Certainly! 

Here is the `master` configuration:

```
 <cluster>
    <name>wazuh</name>
    <node_name>node01</node_name>
    <node_type>master</node_type>
    <key>c98b62a9b6169ac5f67dae55ae4a9088</key>
    <port>1516</port>
    <bind_addr>0.0.0.0</bind_addr>
    <nodes>
        <node>master</node>
    </nodes>
    <hidden>no</hidden>
    <disabled>yes</disabled>
  </cluster>

```

Here is the `worker` configuration:
 ```
<cluster>
    <name>wazuh</name>
    <node_name>workernode01-node</node_name>
    <node_type>worker</node_type>
    <key>c98b62a9b6169ac5f67dae55ae4a9088</key>
    <port>1516</port>
    <bind_addr>0.0.0.0</bind_addr>
    <nodes>
        <node>master</node>
    </nodes>
    <hidden>no</hidden>
    <disabled>yes</disabled>
  </cluster>

```

I initially set the IP to the master node in `<node>master</node>`  on both configuration files but I ran into the issue, so I changed it to this current configuration which still has the issue.

Thanks for the quick response and the assistance!
Weston.

**Comment by mcarmona99** [comment]
## Issue status

**Main problem reported in the issue**: cluster-control does not work with wazuh-clusterd in foreground

For this issue, I have changed the `get_manager_status` function in `/framework/wazuh/core/cluster/utils.py`.

Before the change, the function was comparing only the first process pidfile in `/var/ossec/var/run` with the pids in `/proc`. This was a bad behavior and the cause of the error.

Now all the processes pidfiles are compared with all pids in /proc. This way if the cluster is running, cluster-control will always show the cluster information.

This will solve the issue, but I have discovered new behavior that I think is unexpected:

- If you run wazuh-clusterd in backround or foreground with wazuh-clusterd already running in backround or foreground, the result of cluster-control is:
`ERROR: Error 3012 - Cluster is not running
`
After running it, a new pidfile is created but with no pid in /proc (expected??)
After this case, no cluster endpoint in the API works, but the cluster does not appear to be down due to the cluster.log (there is no error messages and everything appears to be OK)
The first wazuh-clusterd pid is in /proc and /var/run but as I said, the cluster-control gives an error and you cannot use cluster endpoints

- Wazuh-apid does not create any pidfile when running in foreground, wazuh-clusterd does. The pidfile created by a foreground wazuh-clusterd daemon is used  in the cluster-control. If we had no pidfile in this case, we wouldn't be able to see the cluster information with cluster control. In order to have the same behavior when creating pidfiles, `cluster-control` or `wazuh-clusterd` (or both) must be changed.

- If you create more than one wazuh-apid or wazuh-clusterd task and kill it, the pidfiles will remain in /var/run, but the pids in /proc won't. Is it expected to have old daemon pidfiles?



MANUAL TESTS:

- All cluster-control arguments are working.
- Wazuh-clusterd in the background -> cluster-control works
- Wazuh-clusterd in the foreground -> cluster-control works
- The rest of tests  originated the unexpected behaviors commented above.

I am going to talk to my team in order to see if this is expected or if changes or new issues are needed.

Regards,
Manuel.

**Comment by mcarmona99** [comment]
The PR #6724 will solve the error reported in this issue.

**Summary of the errors or bad behavior detected in the last last comment and new information:**

In the last comment, I reported unexpected behavior.

- Talking about number 1, the `ERROR 3012` message appears because the socket breaks down when running `wazuh-clusterd` again. The socket is going to be created but the last socket is still running. (It happens when running the daemon in both foreground and background). This may be solved including a condition before running the script that in case the daemon is in both `/var/run` and `/proc` (cluster running), the script stops.

- Talking about number 2 and 3, we, the framework team, have been talking and have decided to change the PIDs management in `/var/run` as old pidfiles can't remain in `/var/run`. We will try to make a pidfile management in order to have a similar behavior than the rest of daemon (the scripts must remove old pidfiles, `kill` must kill the process and remove its corresponding `pidfile`, etc).

Regards,
Manuel.
