### ISSUE TITLE
Wazuh packaging: Add prelude support

### ISSUE THREAD

**Issue by ToToL** [wazuh/wazuh#5016]
|Wazuh version|Component|Install type|Install method|Platform|
|All|All|All|Packages|CentOS7|

Hello

I opened a thread in Wazuh google groups and they send me here :)
https://groups.google.com/forum/?!msg/wazuh/hgqH2PAAf24/-K_vtjFHAwAJ#!searchin/wazuh/prelude|sort:date/wazuh/hgqH2PAAf24/T6iAdzYHBAAJ

Prelude is fully working in Wazuh, Is it possible to enable prelude support when Wazuh generate its packages in https://packages.wazuh.com/yum/el/$releasever/$basearch for CentOS 7 ?

If you need help, please contact me

Thanks

Regards

**Comment by ToToL** [comment]
Hello

How can we go forward on this issue ?

Thanks

Regards

**Comment by vikman90** [comment]
Hi @ToToL,

Sorry for the late response. As I wrote to you in private, I would like to share our opinion on this issue:

- We need the package to have no dependencies because it would make deployments on systems that do not have an Internet connection. That's one of the reasons why we compile the external dependencies along with our source code (_src/external_). I know _libprelude_ is available as a package in most Linux distros, but we would need it to be preinstalled, otherwise, a user would need to install it; this is a difficulty on systems with limited connectivity.

- We need to evaluate the possibility of adding the Prelude library according to the demand that this functionality has since it would definitely increase the size of the package. In this order of matters, we should also add support for MySQL and PostgreSQL database output, or the feature to enrich the alerts with GeoIP data. All these features would require an external library dependency.

This is why it's difficult to add support for Prelude in our official packages.

As we wrote in the email, we can help you to build your custom RPM package with Prelude support, as well as adding a tutorial in the documentation.

Greetings.

**Comment by ToToL** [comment]
Hello

Thanks for your feedback.

I work on my side with your help if needed (thanks for this !). When it will be ready, I will notice here and we will talk about adding a tutorial in the documentation :)

Thanks

Regards

Thomas

**Comment by vikman90** [comment]
Hi @ToToL,

We already merged the PR's #5003 and #5004 which fixed the support for Prelude (#2552). Per our last comments, we don't plan to add support to Prelude in the packages but will be happy to help you out with that.

Please consider closing this issue.
Best regards.
