### ISSUE TITLE
wazuh-db *.db-wal files in /var/ossec/queue/db grow to huge size and never shrink

### ISSUE THREAD

**Issue by selivan** [wazuh/wazuh#5049]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.11.0-1 | wazuh-db | Manager | Packages | Ubuntu 18.04 Bionic |

On my small installation with 28 agents and 1 wazuh-manager the directory /var/ossec/queue/db grows up to 6 Gb after a copule of weeks. All the space is taken by `*.db-wal` files.

After restarting wazuh-manager these files are re-created and directory size shrinks back to 57 Mb.

Those are sqlite write-aherad log files([sqlite documentation](https://sqlite.org/wal.html)) and they should not be growing without limit. They can be truncated manually by calling appropriate sqlite functions or automatically on commit(controlled by PRAGMA wal_autocheckpoint directive).

This is the same issue as #3535, which was not solved but was closed anyway.

**Comment by antoniomanuelfr** [comment]
Hi @selivan 
This problem was fixed in 3.12.3, you can check the wazuh changelog here https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md and this is the pull request that fixed the problem https://github.com/wazuh/wazuh/pull/4949. 

I recommend you update your wazuh installation to 3.12.3 and the problem should be gone. 
Best regards. 
Antonio Fresneda.

**Comment by selivan** [comment]
Hi @antoniomanuelfr 

Thanks! I close this issue as a duplicate of fixed #4411
