### ISSUE TITLE
syscheck delete not working on 3.12

### ISSUE THREAD

**Issue by 2ZZ** [wazuh/wazuh#5052]
|Wazuh version|Component|Platform|
| --- | --- | --- |
|3.12.0|Wazuh Master|Ubuntu 18.04|
|3.12.3-1|Wazuh Agent|Ubuntu 18.04|

I am trying to periodically clear the syscheck database of an agent in order to force Wazuh to put a new alert into Elasticsearch. I need to do this because my Elasticsearch database only has a retention of 30 days and I need to make sure it always contains the current hash of each file being monitored.

After running the delete command against the API, and also deleting fim.db on the agent and restarting the agent daemon, there is still no new alert logged.
```
~ curl -sk -u user:pass -XDELETE https://wazuh-manager:55000/syscheck/<agent-id>
{"error":0,"data":"Syscheck database deleted"}
```

Is there another step required?

**Comment by jesusjimsa** [comment]
Hello, @2ZZ.

With Wazuh 3.12 we added synchronization to the FIM databases between agents and managers. This makes that the database stays always updated in the manager, it will keep always the current hash.

Also, if you stop Wazuh, delete the `fim.db` file, and then restart Wazuh, no `added` alert will appear. Since Wazuh 3.12, files modified while an agent is stopped do not send an alert, the agent will only send the synchronization message to the manager with the file information to keep the manager updated. Files modified after syscheck restart do send an alert.

Best regards,
Jesús.

**Comment by 2ZZ** [comment]
Thanks @jesusjimsa that makes sense
