### ISSUE TITLE
False positives for CVE-2019-8324 on Centos 7 and Wazuh 3.12.3 vulnerability detection

### ISSUE THREAD

**Issue by dmit2k** [wazuh/wazuh#5078]
Hello,

vulnerability detection of my Wazuh 3.12.3 detects a CVE-2019-8324 vulnerability with ruby / rubygems on my freshly updated Centos 7 server. 

I consider this as a false positive because my installed version is rubygems-2.0.14.1-36.el7 and according to CVE database affected versions are RubyGems 2.6 and later through 3.0.2

Can anyone comment please? Maybe this is somehow related to bug #3860?

The full alert message is:

`data.vulnerability.package.name:
    ruby
input.type:
    log
agent.ip:
    172.16.xxxx
agent.name:
    xxxxx
agent.id:
    021
manager.name:
    wazuh-manager
data.vulnerability.severity:
    High
data.vulnerability.advisories:
    RHSA-2019:1148,RHSA-2019:1235,RHSA-2019:1972,RHSA-2019:1151,RHSA-2019:1150,RHSA-2019:1429
data.vulnerability.reference:
    https://access.redhat.com/security/cve/CVE-2019-8324
data.vulnerability.cve:
    CVE-2019-8324
data.vulnerability.package.condition:
    Package less than 2.5-8000020190524123348.55190bc5
data.vulnerability.package.version:
    2.0.0.648-36.el7
data.vulnerability.package.architecture:
    x86_64
data.vulnerability.bugzilla_reference:
    https://bugzilla.redhat.com/show_bug.cgi?id=1692520
data.vulnerability.published:
    Mar 5, 2019 @ 02:00:00.000
data.vulnerability.state:
    Fixed
data.vulnerability.cwe_reference:
    CWE-20
data.vulnerability.title:
    rubygems: Installing a malicious gem may lead to arbitrary code execution`

**Comment by chemamartinez** [comment]
Hello @dmit2k,

After investigating your issue I can confirm it is a false positive caused by an unexpected version of Ruby provided by the RHEL feed that the Vulnerability Detector ingests.

It is filtering the version 2.5-8000020190524123348.55190bc5 as the one that fixes the vulnerability, which is wrong, the correct patch for that package in RHEL7 would be 2.0.0.648-35.el7_6 as the [RHSA](https://access.redhat.com/errata/RHSA-2019:1235) states, so your package is not vulnerable to CVE-2019-8324.

We are currently working on fixing it and will be available in the next release, which is expected to get it out the door the next week. It also will include a rework of the Vulnerability Detector for Linux agents which is attempting to improve its accuracy. You have more information at [#4749](https://github.com/wazuh/wazuh/issues/4749).

Best regards,
Chema.

**Comment by dmit2k** [comment]
Hello @chemamartinez ,

thank you very much for your prompt response, I beleive I've got a couple more FPs, but will fire separate tickets.

Regards,
Dmitry
