### ISSUE TITLE
Modify Wazuh Rules

### ISSUE THREAD

**Issue by John33000** [wazuh/wazuh#5106]
Wazuh 3.12.3
Elasticsearch 7.6.2
Filebeat 7.62

Hi,
In Windows Log I would like get only the part "eventdata" and the first line : 
May 26 10:00:05 SERVER ossec: Alert Level: 3; Rule: 60106 - Windows Logon Success; Location: (SERVER) 192.168.X.X

I don't want  classification and the payload of log. Only the part "Eventdata" How  I can do that please ? 

Best Regards

**Comment by antoniomanuelfr** [comment]
Hi @John33000.
Wazuh doesn' t support natively that feature because if you remove a field from an alert it may cause other components to fail.
But you can do it using logstash. You can have a look at this link in the documentation https://documentation.wazuh.com/3.12/installation-guide/installing-elastic-stack/transform_logstash.html#transform-logstash. 

If you have any doubts don' t hesitate to ask.
Regards.
Antonio.

**Comment by John33000** [comment]
Hi @antoniomanuelfr 

Ok thank you for you help, I have a second question. I have Wazuh Cluster, one master and one worker. If I change ossec.conf of the Master the configuration is replicate in the worker ? Same thing if I modify agent.conf ? 

Best Regards

**Comment by antoniomanuelfr** [comment]
Hi @John33000 
I'm glad that it was helpful.
In order to provide a better answer, I will ping @wazuh/framework team. They are experts using cluster configuration. 
Best regards.

**Comment by John33000** [comment]
Hi @antoniomanuelfr 
Ok, They will anwser here ? 

Best Regards

**Comment by antoniomanuelfr** [comment]
Yes. 
I will say that the master node can' t share its configuration with the workers.
The agent.conf file is used to overwrite the configuration of other agents, if you have any doubts of how it works you can have a look at this page of the documentation: https://documentation.wazuh.com/3.12/user-manual/reference/centralized-configuration.html

**Comment by Selutario** [comment]
Hi @John33000,

As my team mate @antoniomanuelfr said, the master doesn’t send its local configuration file to the workers. If the configuration is changed in the master node, it should be changed manually in the workers. Please, take care of **not overwriting the cluster section** in the local configuration of each worker. You can find a more detailed explanation in our [documentation](https://documentation.wazuh.com/current/user-manual/configuring-cluster/basics.html) 

Regarding the agent.conf, the aim is to centralize the configuration of the agents in a single place (in this case the master). Therefore, the only things that are synchronized between the master and the workers, according to the documentation, are the agent groups files and assignments.

If you have any other questions, don't hesitate to ask.

Kind regards,
Selu.

**Comment by John33000** [comment]
Hi @Selutario 
Ok I understand, so in Master I configure to send event to syslog and put the same rules and configuration in worker ? Like this if master is down for example is off the worker send alert to syslog ? If I add rules in Master I need to add too in Worker that's it ? 

Best Regards ?

**Comment by Selutario** [comment]
Hi @John33000,

Sorry, I should have specified it. The master node synchronizes all these files with the worker nodes:
- Agent registration.
- Agent deletion.
- Rules, decoders and CDB lists synchronization.
- Configuration of agents grouping.

Therefore, all the rules, decoders and CDB lists that you add in `/var/ossec/etc/rules`, `/var/ossec/etc/decoders` and `/var/ossec/etc/lists` (inside the master) will be available on all workers. As for the local `ossec.conf` configuration, since it is not synchronized, you will have to add the syslog configuration you want to each worker.

Kind regards

**Comment by John33000** [comment]
Hi @Selutario 
Ok I understand, thank you.

Last question what is that on ossec.conf in agent : 

```
<localfile>
    <location>Security</location>
    <log_format>eventchannel</log_format>
    <query>Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and
      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and
      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and
      EventID != 5152 and EventID != 5157]</query>
  </localfile>
```

Best regards

**Comment by Selutario** [comment]
Hi @John33000,

`Localfile` is used to configure the collection of log data from files, Windows events, and from the output of commands. In that example, events will be retrieved from Security and filtered based on that query. The query is an XPATH that follows the [event schema](https://msdn.microsoft.com/en-us/library/windows/desktop/aa385201(v=vs.85).aspx).

For more detailed information on this matter, please check out this blog post about [How to collect Windows events with Wazuh](https://wazuh.com/blog/how-to-collect-windows-events-with-wazuh/) and our documentation for [localfile section](https://documentation.wazuh.com/3.12/user-manual/reference/ossec-conf/localfile.html#log-format).

Kind regards

**Comment by Selutario** [comment]
Hi @John33000,

Sorry for the delay. The `syslog_output` option is used to send the alerts to a syslog server, in your case, located at 172.17.2.240 (don't forget that alerts are generated in the manager, so this configuration only makes sense there). By adding the `<rule_id>` parameter, it only redirects those generated alerts that have the specified ID.

It is not clear to me after your question if this is the tool you are looking for. Could you explain (or give me an example) what exactly do you want to achieve? In this way I can try to find the source of the problem or an alternative for what you want to do.

On the other hand, if you want to specify what rules can be used, you can set it within the ruleset section in your manager's ossec.conf. Here is the documentation about it: https://documentation.wazuh.com/3.12/user-manual/reference/ossec-conf/ruleset.html

If you have any doubts, don't hesitate to ask or explain what you want to do.

Best regards,
Selu.

**Comment by John33000** [comment]
Hi, @Selutario 

Yes I know that, but  I don't understand why I have ID of Windows event in localfile of my ossec.conf in Wazuh agent : 

I don't understand why agent have ID of event windows if the rules was define in Manager.
```
<localfile>
    <location>Security</location>
    <log_format>eventchannel</log_format>
    <query>Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and
      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and
      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and
      EventID != 5152 and EventID != 5157]</query>
  </localfile>
```

Best Regards

**Comment by Selutario** [comment]
Hi @John33000,

So, do you mean that you set that `<localfile>` configuration block inside your manager but after doing so, it appears in your agent's ossec.conf too? 

Would you mind telling me in which place of your manager are you writing those settings? It's strange because, as far as I know, the agent's `ossec.conf` file is not modified from the manager. It is possible to add configuration for the agent through the manager using the `agent.conf` file (`/var/ossec/etc/shared/default/agent.conf` inside the manager), but this configuration remains there and is not appended inside the ossec.conf file of the agent. You could find the shared configuration inside `/var/ossec/etc/shared/agent.conf` of your agent, but not inside `ossec.conf`.

If you don't need that configuration block in your agent, just delete it. It should not appear again since that file is not externally modified. 

Maybe you added it by mistake or it was written by default when installing the agent (for some reason that I don't know).

Kind regards,
Selu.

**Comment by John33000** [comment]
Hi @Selutario 

I never write in ossec.conf of my agent except IP of the manager. I have this block in all windows agent.  And the configuration of /var/ossec/etc/shared/agent.conf  is by default or empty (I never used this file)

Best Regards

**Comment by Selutario** [comment]
Hi @John33000,

Sorry I didn't realize it at first but that's part of the default settings on Windows agents as you can see here.
https://github.com/wazuh/wazuh/blob/776cc205b55c06ff6d2afacb0d66d6e6e51c8b54/src/win32/ossec.conf#L34-L41

Windows events with those IDs are intentionally excluded since they are very noisy. You can see here the PR in which the exclusion of some of those events was added: #2763

Those IDs are from Windows events, and not from Wazuh rules. You can take a look at a reference with all Windows events and their IDs here: https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/default.aspx

Kind regards,
Selu.

**Comment by John33000** [comment]
Hi @Selutario 

Ok thank you, I understand now. You can close this case 

Best Regards

**Comment by Selutario** [comment]
Hi @John33000,

I'm glad I was helpful. Don't hesitate to open another issue if you have new questions.

Kind regards,
Selu.
