### ISSUE TITLE
Sample log size limited to 4096 bytes by ossec-logtest

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#5124]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|3.12.3|ossec-logtest|n/a|n/a|Linux|

Back in 2018 we increased Wazuh's buffer size from 6K to 64K (https://github.com/wazuh/wazuh/pull/411) but it appears that ossec-logtest needs to be aligned with that.  

If you paste a sample log message larger than 4096 bytes into ossec-logtest, only the first 4096 bytes end up being extracted into the `log` field, with the rest getting discarded.

I presume ossec-logtest has a 4K limit that needs to be raised to 64K to match the rest of Wazuh.  Please address this as it is quite easy these days to have a log sample much larger than 4K, especially with the advent of JSON log ingestion by Wazuh.

Thanks,
Kevin Branch

**Comment by vikman90** [comment]
@branchnetconsulting I'm reviewing _ossec-logtest_ and it appears to be getting up to 64 KiB lines (losing a few bytes reserved for headers).

This is the call to read a line from _stdin_: [testrule.c](https://github.com/wazuh/wazuh/blob/v3.12.3/src/analysisd/testrule.c#L445).

I've made some tests and I think the issue is related to the terminal.

## Testing decoder

```xml
<decoder name="test">
    <prematch>demo:</prematch>
    <regex offset="after_prematch">^ a=(\S+)</regex>
    <order>a</order>
</decoder>
```

## Testing input

This is a 65.000 byte long file (_input.txt_):

```shell
$ cat input.txt
demo: a=0123456789(...)123456789012345678901f
$ wc input.txt
    1     2 65501 input.txt
```

**Comment by branchnetconsulting** [comment]
I see what you mean, Victor.  When I paste my huge example log line into a
text file like sample.txt and then pipe it to logtest like with "cat
sample.txt | /var/ossec/bin/ossec-logtest" it indeed works correctly that
way.  Would this terminal issue be something specific to ossec-logtest or
of a broader scope when in an ssh session to the Wazuh manager?

Kevin

**Comment by vikman90** [comment]
@branchnetconsulting I admit I didn't know about this issue until now. 

After a quick look at StackOverflow ([How to read over 4k input without new lines on a terminal?](https://unix.stackexchange.com/questions/131105/how-to-read-over-4k-input-without-new-lines-on-a-terminal)), this limitation seems to be due to a parameter defined in the kernel: [`N_TTY_BUF_SIZE`](https://elixir.bootlin.com/linux/v4.1/source/include/linux/tty.h#L308).

On the other hand, _ossec-logtest_ simply reads up to 65538 bytes from the standard input, which indeed, in the case of a console, would be limited by `N_TTY_BUF_SIZE`.

Best regards.
