### ISSUE TITLE
Packages data does not show for windows operating system.

### ISSUE THREAD

**Issue by zakirpcs** [wazuh/wazuh#5135]
For windows operating system it does not show packages information in kibana dashboard. could you guys please help me to resolve the issue.

Below is the information of my setup:
ELK: 7.7.0
Wazuh: 3.12.3
Wazuh Agent: 3.12.3

Wazuh Manager Config:
======================
` <vulnerability-detector>
    <enabled>yes</enabled>
    <interval>5m</interval>
    <ignore_time>6h</ignore_time>
    <run_on_start>yes</run_on_start>
    <provider name="redhat">
      <enabled>yes</enabled>
      <update_from_year>2010</update_from_year>
      <url start="1" end="22">http://10.0.14.42/rh-feed/redhat-feed[-].json</url>
      <update_interval>1h</update_interval>
    </provider>
    <provider name="nvd">
      <enabled>yes</enabled>
      <update_from_year>2007</update_from_year>
      <url start="2002" end="2020">http://10.0.14.42/nvd-feed/nvd-feed[-].json.gz</url>
      <update_interval>1h</update_interval>
    </provider>
  </vulnerability-detector>
`

Wazuh Client Config:
=======================
  
`
  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>1h</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>yes</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <processes>yes</processes>
    <hotfixes>yes</hotfixes>
  </wodle>
`

**Comment by chemamartinez** [comment]
Hi @zakirpcs,

I would need more details about what do you mean with `packages information`?

The package inventory for each agent should appear in the `Inventory tab` after selecting the desired agent.

![Screenshot 2020-06-01 at 19 10 44](https://user-images.githubusercontent.com/29475387/83434928-abc40f00-a43b-11ea-9ee3-cf8825135953.png)

if you're referring to the vulnerability alerts related to those packages. They appear in the `Vulnerabilities` dashboard where you can also filter by the Windows agents.

Regarding the Vulnerability Detector configuration that you pasted, I see you are trying to load the JSON provided by the NVD compressed. You have to uncompress them before uploading to your custom repository.

It is explained at https://documentation.wazuh.com/3.12/user-manual/capabilities/vulnerability-detection/offline_update.html#how-to-use-the-the-update-script. The last configuration example of that section is wrong.

The valid configuration should look like:

```xml
<provider name="nvd">
    <enabled>yes</enabled>
    <url start="2002" end="2020">http://10.0.14.42/nvd-feed/nvd-feed.*json$</url>
    <update_interval>1h</update_interval>
</provider>
```

I hope it helps.

Regards,
Chema.

**Comment by zakirpcs** [comment]
Hi Chema,

Thanks for your reply.
Actually i did not get any **packages** information in **Inventory Data** tab for windows agent. For example 
![packages](https://user-images.githubusercontent.com/39796037/83497399-3fe5b300-a4dc-11ea-9627-f5a1f9ddafe7.png)

Regards,
Zakir Hossain

**Comment by chemamartinez** [comment]
Hi @zakirpcs,

The package inventory is enabled by default in Wazuh agents.

I would check the following items to find where the problem may be.

- The agent is connected

- If you have access to the Windows agent. Review the `ossec.log` file looking for any error message. The file is located in the installation folder, by default `C:\Program Files (x86)\ossec-agent\`.

- In the WUI, go to the `Dev Tools` tab and run the following query `GET /syscollector/001/packages?` replacing 001 by your agent ID. It should return a JSON with the package inventory of the agent. If that query doesn't return any result, the issue probably lies in the agent itself, otherwise, it can be a visualization problem from the WUI.

![image](https://user-images.githubusercontent.com/29475387/83672234-3a6c9380-a5d6-11ea-8142-c846a3e13ee6.png)

Best regards,
Chema.

**Comment by zakirpcs** [comment]
I am getting packages information by using your command in dev tools:

![packages-kibana](https://user-images.githubusercontent.com/39796037/83903413-e56c8100-a77f-11ea-8c47-fe064da4b5fe.png)

I am getting packages information by using below command:
curl -u user:password -k -X GET "http://127.0.0.1:55000/syscollector/050/packages?pretty"

![packages](https://user-images.githubusercontent.com/39796037/83903220-8d357f00-a77f-11ea-9077-e73d687086eb.png)

Best Regards,
Zakir

**Comment by chemamartinez** [comment]
Hi again @zakirpcs,

Since you are able to get the inventory data for that agent by the API call, the problem lies in the WUI.

I have been talking with the team in charge of its development and it is a known issue related to the AngularJS transpiler used in Kibana 7.7.x. Here you have more information about it: https://github.com/wazuh/wazuh-kibana-app/issues/2255

The team is working on solving it right now, and a fix will be included in the next Wazuh release.

Sorry for the inconvenience, and thank you for reporting this bug. I am closing this issue since it is not a bug related to this repository. You can track the progress of the fix in the issue I referenced above.

Best regards,
Chema.
