### ISSUE TITLE
Loading cloudtrail events from aws-s3 wodle doesn't parse "eventTime" as the date of the event

### ISSUE THREAD

**Issue by alitheg** [wazuh/wazuh#5149]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12.3-rev | S3 Wodle | Manager | Docker package | Amazon Linux 2 |

Cloudtrail logs result in a field data.aws.eventTime, but all of my logs are appearing as the timestamp that Wazuh parsed the file.

**Comment by FernandoCP** [comment]
Hi @alitheg! 

First of all, my apologies for the slow response. 

I have been researching and found in the AWS documentation that the` eventTime `field shows the date and time the request was made and not the date and time the event happened.
I think that's where the problem lies. Here is a link to the AWS documentation if you need it.  

https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-record-contents.html

I don't know if this will solve your problem, if you have any other questions don't hesitate to ask. 

Best regards, Fernando.

**Comment by alitheg** [comment]
Hi @FernandoCP - no worries!

Makes sense - but with Cloudtrail is the date of the request the date of the event? What I'm seeing is that in Wazuh the events are coming up as the date the log was *parsed* - so if I'm loading the last month's worth of events on a new system (as I was doing), they *all* come up as having occurred today.

**Comment by alitheg** [comment]
Or, thinking about it more - does Wazuh ignore the timestamp field in ElasticSearch and actually use the Cloudtrail data? I was looking in the Explore tab of Kibana to interrogate the data, so it could be that Wazuh uses a different field to plot events?

**Comment by FernandoCP** [comment]
Hi @alitheg !

Wazuh takes the value that AWS offers us, it is an external value to wazuh's agent and therefore I cannot assure you which date is displayed.  I understand from what I read in the AWS documentation that it is the date of the event returned and that this may be where the problem lies. 

I am not sure that this will solve your problem, so I am here for any other questions you may have and will try to help you. 

Best regards, Fernando.
