### ISSUE TITLE
How to register Wazuh agent with hostname?

### ISSUE THREAD

**Issue by nkhljswl** [wazuh/wazuh#5167]
Hello,

I have recently deployed the Wazuh server and I am planning to deploy Wazuh agent across the whole infrastructure. While testing the agent I observed, the registration can be done only with the IP address(Correct me if I am wrong).

We are using DHCP for IP allocation and due to that, there is a high possibility the IP of the client machine may change. Is there any way to register the agent only with a hostname?

**Comment by jsanchez91** [comment]
Hi @nkhljswl,
Before we start, I think we should do some checking.

First, let's check the Wazuh administrator's settings. In the `ossec.conf` file look for the `use_source_ip` property, if its value is `yes` the administrator will only authorize the messages of the agent that come from the agent's IP at the time of registration, you must change it to `no` so that when registering the agents you put the value `any` in their IP.
[Wazuh documentation - auth](https://documentation.wazuh.com/3.12/user-manual/reference/ossec-conf/auth.html#use-source-ip)

With this command you can check the IP assigned to the agents.
```
/var/ossec/bin/agent_control -l
```

If your agents have been registered with an IP you must register them again after changing the value "use_source_ip" so that it assigns the value "any" to the IP field.
>Don't forget to restart the manager after editing the "ossec.conf".

**Comment by nkhljswl** [comment]
Hi @jsanchez91 

I changed the configuration as per your suggestion and it's working if register agent using /var/ossec/bin/agent_control.

**Comment by jsanchez91** [comment]
Hi @nkhljswl,

Yes, after registering the agent again it is necessary to restart it.

Have you had any more problems since you changed the configuration?

**Comment by nkhljswl** [comment]
Nope.

From last 4 days it's perfectly.

Thanks a lot for help @jsanchez91 

Closing the issue.
