### ISSUE TITLE
Question about Wazuh on AD/DC

### ISSUE THREAD

**Issue by John33000** [wazuh/wazuh#5205]
Wazuh 3.12.3, Elasticsearch 7.6.2 and Filebeat 7.6.2.

Hi,
I have 2 DC/AD (DC1 and DC2) and one attached console. I have one agent in DC1, if I create account in DC1 I have alert Wazuh. But if I create account in DC2 or attached console Wazuh don't create alert. I need to install Wazuh agent in all DC/AD ? Or there is an other solution ? Do you see this case ? 

Best Regards,

**Comment by chemamartinez** [comment]
Hi @John33000,

Understanding a DC as an independent server, the short answer is yes, you have to install a Wazuh agent in each server you want to monitor, it doesn't matter the attached console or any other way of connectivity between the domain controllers since the Wazuh agent scope is limited to the local server.

For further occasions, we would appreciate it if you let the opening of issues in the Wazuh repositories to report bugs or feature requests. For questions like this one, the better via is to join to the Slack channel or the mailing list, you can read more information [here](https://wazuh.com/community/).

Best regards,
Chema.

**Comment by John33000** [comment]
Hi @chemamartinez 

Ok thank you for your help, so I need to install Wazuh agent in all DC. I ask the question here because you give a anwser more faster, in slack I need to wait 1 week for 1 reply... 

Best Regards

**Comment by chemamartinez** [comment]
Thank you for your feedback.

I'm sorry you have that feeling about community channels. The team is doing its best to meet the needs of all users, but sometimes some questions get left behind due to the growth of the community every day.

We are continuously trying to improve our processes to avoid those situations. I hope you will not experience this situation again.

Best regards.

**Comment by John33000** [comment]
Yes I understand, but for example I have a issue with LB since 2 months and I work with one of your colleague but, the time of reply it's so long... And he don't give any element for resolve the issue. Because  I suppose he's very occupied.

Best Regards

**Comment by John33000** [comment]
I send him 6 messages since 2 days :(

**Comment by chemamartinez** [comment]
I am sorry to hear that. As I said before, I hope it doesn't happen again.

Let me close the issue since the question is solved. Feel free to contact us again with any further questions.

Best regards.
