### ISSUE TITLE
[Vulnerability Detector] Latest KB not detected in Windows server 2019

### ISSUE THREAD

**Issue by Anthony-helix** [wazuh/wazuh#5302]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12.3 | Vulnerability Detector | Manager/Agent | Packages/Sources | Windows Server 2019 Standard 10.0.17763- 1809 |

Hello team,

I am facing an issue concerning latest patch installed on Windows server. The vulnerability detector detects   `data.vulnerability.cve:CVE-2020-0679`  and `data.vulnerability.package.condition -  4532691 patch is not installed.` 

I then click on the referred link https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2020-0679 to download KB and the patch `4532691` has been replaced by the latest one [KB4567513](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4567513)

![new-kb](https://user-images.githubusercontent.com/67327338/85417351-8cbf2580-b580-11ea-8f86-02422c3713e2.PNG)

The new KB is installed in my Windows server, and Wazuh even recognizes it in the inventory data : 

![new-kb-win-update](https://user-images.githubusercontent.com/67327338/85417578-d27bee00-b580-11ea-9091-fc5ddd8c33c9.PNG)

However, after a vulnerability scan, the same CVE is still here with same condition as above `data.vulnerability.package.condition -  4532691 patch is not installed` as if nothing has been done.

I am quite new to Wazuh, my agent config is as follows : 

```
<wodle name="syscollector">
  <disabled>no</disabled>
  <interval>1h</interval>
  <packages>yes</packages>
  <os>yes</os>
  <hotfixes>yes</hotfixes>
</wodle>
```

and on manager side : 

```
	</provider>
		<provider name="nvd">
			<enabled>yes</enabled>
			<update_from_year>2010</update_from_year>
			<update_interval>1h</update_interval>
		</provider>
```

Actions performed : 

- manager/ agent restarted

- filebeat restarted

- all the official docs and blog post were followed but found no relationship with my issue.

more info on the logs below : 

![log-srv1](https://user-images.githubusercontent.com/67327338/85437673-07e20500-b59c-11ea-898e-4cf9c72fb48a.PNG)
![log-srv2](https://user-images.githubusercontent.com/67327338/85420011-c0e81580-b583-11ea-8ad1-afd5333ca525.PNG)

Would be grateful if you could help.

Thanks in advance and regards,

Anthony

**Comment by JcabreraC** [comment]
Hello @Anthony-helix :

To check for the latest vulnerabilities, you must have the product updated. Each Wazuh version stores information about all the packages who were publicly available until the day said wazuh version was released.

The `MSU.json` file that we use to check for vulnerabilities in Windows, is the result of the correlation between the information provided by the `Windows API` and the `Microsoft Update Catalog`. It takes some time for Microsoft to release this information. We want to make sure that all the data we give about your vulnerabilities is correct, that's why the hotfixes are updated between versions.

Unfortunately, the `KB4567513` hotfix was released only eight days ago, so your version has no information about this new package.

We will soon have our own online feed and the manager will automatically keep this information up to date.

Thank you for your understanding, a greeting:
Juan Cabrera

**Comment by Anthony-helix** [comment]
Hello @JcabreraC ,

Many thanks for taking the time to revert back.

I understand the fact that you @wazuh want to make sure every piece of information given is correct and that your own  online feed's development is in the pipeline. 

Can you please confirm is an upgrade towards Wazuh version `3.13.x` will correct this issue or we will have to wait for the online feed?

Warm greetings,

Anthony

**Comment by JcabreraC** [comment]
Hello @Anthony-helix 

In the next release of Wazuh, the information about the Windows vulnerability will be updated, discarding that false positive alert.

As I said before, we are working on our own online feed, so this information will be updated automatically.

Best regards:
Juan

**Comment by JcabreraC** [comment]
Hello @Anthony-helix 

Due to inactivity I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our Slack channel or subscribe to our mailing list.

Best regards,
Juan
