### ISSUE TITLE
vulnerability-detector could not be started

### ISSUE THREAD

**Issue by mrtc0** [wazuh/wazuh#5306]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.0 | wazuh-moduled:vulnerability-detector | Manager | Packages | Ubuntu 16.04 |

Upgrading from Wazuh 3.12.3 to 3.13.0 resulted in the following error The vulnerability-detector could not be started.

```
2020/06/24 16:06:45 wazuh-modulesd:vulnerability-detector: ERROR: (5514): The database could not be checked or created.
2020/06/24 16:06:45 wazuh-modulesd:vulnerability-detector: ERROR: (5503): SQL error: 'no such column: SOURCE'
2020/06/24 16:06:45 wazuh-modulesd:vulnerability-detector: ERROR: (5562): The integrity of the database is invalid, so Vulnerability Detector will stop working.
```

Set `wazuh_modules.debug=2` in `local_internal_options.conf`, resuletd in the following error.

```
2020/06/24 17:00:39 wazuh-modulesd[5224] main.c:98 at main(): DEBUG: Created new thread for the 'vulnerability-detector' module.
2020/06/24 17:00:39 wazuh-modulesd:vulnerability-detector[5224] wm_vuln_detector.c:451 at wm_vuldet_create_file(): ERROR: (5514): The database could not be checked or created.
2020/06/24 17:00:39 wazuh-modulesd:vulnerability-detector[5224] wm_vuln_detector.c:2030 at wm_vuldet_sql_error(): ERROR: (5503): SQL error: 'no such column: SOURCE'
2020/06/24 17:00:39 wazuh-modulesd:vulnerability-detector[5224] wm_vuln_detector.c:2664 at wm_vuldet_check_db(): ERROR: (5562): The integrity of the database is invalid, so Vulnerability Detector will stop working.
```

I think that wazuh-db has no column of name "SOURCE", do I need to perform any migration operations?

Out vulnerability-detector configuration is :

```
  <vulnerability-detector>
    <enabled>yes</enabled>
    <interval>1d</interval>
    <ignore_time>2d</ignore_time>
    <run_on_start>no</run_on_start>
    <provider name="canonical">
      <enabled>yes</enabled>
      <os path="/var/ossec/oval/ubuntu_14.xml">trusty</os>
    </provider>
    <provider name="canonical">
      <enabled>yes</enabled>
      <os path="/var/ossec/oval/ubuntu_16.xml">xenial</os>
    </provider>
    <provider name="canonical">
      <enabled>yes</enabled>
      <os path="/var/ossec/oval/ubuntu_18.xml">bionic</os>
    </provider>
    <provider name="redhat">
      <update_interval>12h</update_interval>
      <enabled>yes</enabled>
    </provider>
    <provider name="nvd">
      <enabled>yes</enabled>
      <update_from_year>2010</update_from_year>
      <update_interval>12h</update_interval>
    </provider>
  </vulnerability-detector>
```

**Comment by chemamartinez** [comment]
Hi @mrtc0,

The database handled by Vulnerability Detector should be purged on upgrades since it still has not a migration mechanism. Let me try to reproduce your case to find out the cause of the error with more precision.

It also can be related to this issue opened a few days ago: https://github.com/wazuh/wazuh/issues/5261

When `run_on_start` is set to `no`, the database is not updated before the first scan. We are working on solving it.

To fix the issue in the meantime, I suggest you to follow these steps:

1. Stop the manager
2. Remove the vulnerabilities database, located at `/var/ossec/queue/vulnerabilities/cve.db`
3. Set `run_on_start` to `yes` in the Vulnerability Detector configuration
4. Restart the manager

Best regards,
Chema.

**Comment by chemamartinez** [comment]
Hi again,

I have launched an upgrade of the manager from 3.12.3 to 3.13 by packages in a Ubuntu host.
The database is overwritten as expected, so the module is not complaining about the missing of the `SOURCE` column as in your case.

However, due to the bug I told you with the `run_on_start`, the database is not filled at start-up, and the module fires this error when running the scan:

```
2020/06/24 03:51:09 wazuh-modulesd:vulnerability-detector: ERROR: (5582): Unavailable vulnerabilities at the NVD database. The scan is aborted.
```

I have skipped the problem by enabling the `run_on_start`.

However, I could not reproduce your issue, could you tell me how did you perform the upgrade process?

Regards,
Chema.

**Comment by mrtc0** [comment]
HI, @chemamartinez 

Thank you for your reply.

This was fixed by removing `/var/ossec/queue/vulnerabilities/cve.db` .
However, there was a problem with the other wazuh manager that prevented the update from starting as well.

```
wazuh-modulesd:vulnerability-detector: ERROR: (5582): Unavailable vulnerabilities at the NVD database. The scan is aborted.
# It is expected that the update will be launched after this, but it has not been launched at all...
```

This was due to the fact that cpe_helper.json did not exist.   
vulnerability/dictionaries from queue-template I copied it and it started up fine.

Anyway, thanks to you, we've solved the problem! Thank you.
