### ISSUE TITLE
OVA - upgrade 3.12 to 3.13 ENOENT wazuh-registry.json 2001

### ISSUE THREAD

**Issue by b4b857f6ee** [wazuh/wazuh#5314]
|Wazuh version|Component|Install type|Install method|Platform|
|3.13|Kibana app|OVA|update from 3.12 to 3.13|CentOS 7|

I just upgrade by following the process on the documentation my appliance from 3.12 to 3.13.
I get a problem because the update install me kibana 7.8 and the app is not compatible for this version.
I downgrade to 7.71 kibana, filebeat and elasticsearch

And now i get this : 
![image](https://user-images.githubusercontent.com/36012515/85590504-c194b080-b644-11ea-8422-3bfc5881d1a4.png)

This is not the first time i have trouble during upgrading the Wazuh appliance.
Maybe the problem is me but maybe you can add a specific OVA documentation to upgrade it, (i hope i don't miss it)

Thank you for your help!

**Comment by b4b857f6ee** [comment]
Ok i re-test the process by forcing the upgrade with elasticsearch-oss-7.1.1 kibana-oss-7.1.1 and filebeat-7.1.1 and it's work.
Maybe change the documentation to no write for the OVA for doing yum upgrade and do the documentation.
Maybe you need to change the main documentation because the elasticsearch package isn't elasticsearch-7.1.1 by elasticsearch-oss-7.1.1.

**Comment by DFolchA** [comment]
Hello @b4b857f6ee ,

Since a couple of releases ago the OVA appliance uses the OSS versions of Elasticsearch, Kibana, and Filebeat, so you need to use those packages when updating to a new version.

Indeed this should be reflected in our documentation, so I opened this issue in our documentation:

https://github.com/wazuh/wazuh-documentation/issues/2662

Remember that if you want to use any of the functionalities of XPACK, you will need to uninstall the OSS packages and install the regular ones.

Regards,
Daniel Folch

**Comment by b4b857f6ee** [comment]
Ok i manage to update mine now and i have some with -oss and some other without xD.
thank's for the information about the XPACK!
