### ISSUE TITLE
Review q parameter and integration tests in 4.0 api

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#5344]
Hello team,

As part of the development for the new Wazuh API 4.0, we should review and update the behaviour of the `q` parameter for the different API endpoints. Said parameter was introduced in Wazuh version 3.7 to support [filtering data using queries](https://documentation.wazuh.com/3.13/user-manual/api/queries.html?highlight=query) and is widely used by our Kibana APP. It provides a very powerful tool but it comes with some restraints. In any endpoint with a bunch of parameters the combinations of different queries that could be performed are huge, making it difficult to be fully tested.

We should however ensure the correct behaviour of the different available parameters and add a few basic test cases for each endpoint that supports `q` in our Tavern integration tests.

Best regards,

David J. Iglesias

**Comment by Selutario** [comment]
Hello team,

As some member of the frontend-team have pointed out, the `q` parameter has disappeared in some 4.0 endpoints (but it was in 3.X). Therefore, it should be reviewed and re-implemented in those places where it is missing. For now:
- groups
- syscheck

Kind regards,
Selu.

**Comment by Selutario** [comment]
# Status
## Summary
Hello team. This issue covers multiple aspects.

On the one hand, I have already integrated the parameter q in those endpoints that I mentioned (syscheck and groups). Besides, I have also added tests that make a more complex query by using multiple operators, so we can to detect any related problems in the future. I have also modified this part of WazuhDBQuery:

https://github.com/wazuh/wazuh/blob/ee703653bb66561f720144f7e0a59b83a36c1968/framework/wazuh/core/utils.py#L1045-L1047

As you can see, the strings were divided by commas. This behaviour generated some errors like the ones reported in the issue #5312. After the modification, I have passed all the integrated tests successfully to make sure that the change does not affect the behaviour of other endpoints.

On the other hand, regarding the problems of the q parameter itself (it seemed not to apply all the specified filters, some operators were strangely not supported, etc.), the reason is as follows:

Certain reserved symbols are used in the query which is later interpreted by the framework. From what I have inferred, in the framework part this is still done well. However, it is API itself that when generating the `request` object which groups all the data, misunderstands those reserved symbols. That doesn't seem to cause problems with the comma (`,`), the equal (`=`) and other signs, but it does with the semicolon (`;`) which is interpreted as a separator (like `&`). Therefore by specifying, for example, this q:

> os.name=ubuntu;os.major<18

What the request object got was something like:

> query = {MultiDictProxy: 4} <MultiDictProxy('q': 'os.name=ubuntu', 'os.major<18': '')>

As you can see, the object q has only the content up to the first semicolon, while the rest divides it (as `&` would do) as a different parameter. For some reason or configuration, this did not happen in API 3.X made in NodeJS.

## Difficulties
I have been trying some solutions to such problem. 

First, I used the `query_string` attribute of the `request` object to manually parse the content of the q. Although this worked fine, the spec verifies that the parameters inside the query are allowed. When dividing by semicolons, there were parts of the query that are interpreted as different parameters and which obviously are not allowed. As a consequence, the spec forbids the execution of the endpoint.

I also tried to create a new middleware which takes care of percent-encoding the parameters, so that the reserved characters can be used. I finally discarded this option too since the `MultiDictProxy` object is immutable and I didn't find a good workaround.

I have also spent quite some time trying to specify which symbols are to be interpreted as special. Finally we have seen this maybe it is being done inside the Connexion module used in the API, and it is what I am working on right now.

## Other APIs
I did a little research on how other APIs use the `q` parameter. 

**Twitter**
I've only seen one key-value pair in each q parameter. For example, to get tweets from a specific location and language:
```
q=%23superbowl&result_type=recent
```

**RestDB**
The query is done with JSON. It uses unsafe characters that must always be encoded, so if you do not do it as a body, you should also encode them.
```
https://mydb-fafc.restdb.io/rest/people?q={"name" : {"$in" : ["Joe", "Jane", "Donald"]}}
```

**Plos API**
Use spaces, words like AND and OR, and reserved symbols like`:`.
```
http://api.plos.org/search?q=title:"Drosophila" AND body:"RNA"&fl=id,abstract
```
However, spaces and others must also be encoded:
```
http://api.plos.org/search?q=title:%22Drosophila%22%20and%20body:%22RNA%22&fl=id,abstract
```

**Skyscanner, facebook, etc**
I have not seen examples that use a query with more than one element. For example in skyscanner (the q and locale are different parameters):
?q=lond&locale=en-GB'
## Pending

**Comment by Selutario** [comment]
# Issue update

Hello team. We found out which method should be overwritten in order to update the request method to what we need. 

https://github.com/zalando/connexion/blob/bed4b95205205861bd6014282d0f61d50231d3ac/connexion/decorators/uri_parsing.py#L121-L147

We have discarded any type of modification on the request object. Finally, we will only add to this function an exception that will be thrown when an uncoded semicolon is entered in the parameter q. This way we avoid accepting a response that does not apply all the requested filters.

Best regards,
Selu.

**Comment by Selutario** [comment]
# Issue update

## Missing `q` parameter
Hello team. I have found several endpoints in 4.0 which do not contain the `q` parameter, but did have it in 3.X. Specifically, this is this list:
- /agents/summary/os -> (http://localhost:8000/user-manual/api/reference.html#get-os-summary)
- /ciscat/:agent_id/results -> (https://documentation.wazuh.com/3.13/user-manual/api/reference.html#results)
- /cluster/:node_id/logs -> (https://documentation.wazuh.com/3.13/user-manual/api/reference.html#logs)
- /cluster/nodes -> (https://documentation.wazuh.com/3.13/user-manual/api/reference.html#logs)
- /manager/logs -> (https://documentation.wazuh.com/3.13/api/reference.html#get-ossec-log)
- /syscollector/:agent_id/hotfixes -> (https://documentation.wazuh.com/3.13/user-manual/api/reference.html#hotfixes)
- /syscollector/:agent_id/netaddr -> (https://documentation.wazuh.com/3.13/user-manual/api/reference.html#id25)
- /syscollector/:agent_id/netiface -> (https://documentation.wazuh.com/3.13/user-manual/api/reference.html#id26)
- /syscollector/:agent_id/netproto -> (https://documentation.wazuh.com/3.13/user-manual/api/reference.html#get-network-protocol-info-of-an-agent)
- /syscollector/:agent_id/packages -> (https://documentation.wazuh.com/3.13/user-manual/api/reference.html#get-packages-info)
- /syscollector/:agent_id/ports -> (https://documentation.wazuh.com/3.13/user-manual/api/reference.html#get-ports-info-of-an-agent)
- /syscollector/:agent_id/processes -> (https://documentation.wazuh.com/3.13/user-manual/api/reference.html#id31)

I have already added to all of them the mentioned parameter. I have also tested them by hand to make sure they work correctly and have developed the corresponding integrated tests.

## Different behaviours in `q` parameter

I have also detected that the `filter_array_by_query` function did not have a behavior comparable to that of filter q in classes that inherit from WazuhDBQuery. While, for example in `/agents`, it was possible to filter by typing the value os.name, there was no option to nest fields on endpoints that use the mentioned function, as in the case of `/rules` and `/decoders`. 

https://github.com/wazuh/wazuh/blob/583bbc7dfc7e39b0e6842dade98cbfada45cf75c/framework/wazuh/core/utils.py#L735-L804

This can lead to confusion for users, so I have also modified it to allow this action and make it more similar to other endpoints.

Best regards,
Selu.
