### ISSUE TITLE
wazuh offline installation 

### ISSUE THREAD

**Issue by DavidOrtice** [wazuh/wazuh#5347]
Hello guys am trying to install wazuh as an agent in a suse linux server...however am getting this error whenever i try to install the software curl -so external/cJSON.tar.gz https://packages.wazuh.com/deps/3.12/cJSON.tar.gz
make: *** [external/cJSON.tar.gz] Error 6
Makefile:691: *** No external directory found. Run "make deps" before compiling external libraries.  Stop. Please advice on the way forward.

**Comment by FernandoCP** [comment]
Hi @DavidOrtice!

I'm sorry to tell you that it's necessary to have a connection in order to download the dependencies you need. 

If it is not possible for you to have a connection you can do 2 things, both from another connected PC:


1.- Download and install from packages as described in the following link to our documentation 
https://documentation.wazuh.com/3.13/installation-guide/installing-wazuh-manager/linux/suse/wazuh_server_packages_suse.html#wazuh-server-packages-suse
From packages is already compiled and would solve your problem, is the option I recommend. 

2.- Download the Wazuh repository and from the `wazuh/src` folder do the following: 
```
make -C src deps
make TARGET=server external -j2
tar -zcf ~/external.tar.gz external
```
Then you move the compressed file to the other computer and decompress it on the same path. Once that's done, you can go on with your normal installation without any problems.

I hope it helps, if you have any other problems don't hesitate to ask. 

Best regards, Fernando.

**Comment by DavidOrtice** [comment]
Am trying to execute the commands you mentioned up there and they are not working. am at the src folder

**Comment by FernandoCP** [comment]
Are you running them on a computer with an internet connection? The instructions are to run them on a connected PC and then pass the file to the PC where it gives you errors.

If you are testing it on a computer with a connection, could you tell me what errors you have so that I can have more information and help you?

Finally, if you have problems I think the package option is easier to make work.

Best regards, Fernando.

**Comment by DavidOrtice** [comment]
Okay let me do that and i will post my findings.

**Comment by DavidOrtice** [comment]
Thanks FernandoCP i have installed the application on 3 servers, but the remaining issue is with the ips...from the kibana dashboard the ips of the servers are different.

**Comment by FernandoCP** [comment]
Hi @DavidOrtice !

I don't know if this is what you mean but Kibana's IP address can be changed. If you access our documentation in the following link and select the type of OS you have the way to do it.

https://documentation.wazuh.com/3.13/installation-guide/installing-elastic-stack/index.html#installation-elastic

To make your search easier, here I show you the two ways:

- For **DEB**: 
Kibana will only listen on the loopback interface (localhost) by default, which means that it can only be accessed from the same machine. To access Kibana from the outside, make it listen on its network interface IP by editing the file /etc/kibana/kibana.yml, uncomment the setting server.host, and change the value to:
`server.host: "<kibana_ip>"`

- For **RPM**: 
Set the URL or the IP of the Elasticsearch node by editing the file /etc/kibana/kibana.yml:
`elasticsearch.hosts: ["http://<elasticsearch_ip>:9200"]`

I hope this information helps you if your problem is another one, can you give me more information about it?

Best regards, Fernando.

**Comment by DavidOrtice** [comment]
Hello@FernandoCP thanks for your help, i believe my issue is with ip address which am going to address with my network administrator, thank you very much for your help.
