### ISSUE TITLE
wazuh FIM taking too much time to bring back results...

### ISSUE THREAD

**Issue by aitonc** [wazuh/wazuh#5361]
i've started FIM scan on one of my agents and it's been days without any results on the kibana/wazuh app

**Comment by bah07** [comment]
Hi @aitonc 

I will try to help here, so could you provide us with some more information about your environment?

- What version of Wazuh are you using?
- Is the agent connected and reporting other alerts?
You can use `agent_control -l` on the manager's side. You should be see something like:
> ID: 003, Name: win7agent-PC, IP: any, Active

If you see Never connected or Disconnected, there is some problem with agent registration or connection.
- You can also see if in the manager alert.log file there are FIM alerts for that agent. Maybe the problem is that elastic is not indexing correctly.

Some things you can test on the agent side to see if it's working properly:

- You can activate the debug mode in the agent in the internal_options.conf file and see what information appears in ossec.log. You must restart Wazuh to apply the changes. `syscheck.debug=2` or `windows.debug=2` if it is a Windows agent-

- You could monitor a test folder with realtime=yes to see that events are actually generated in the agent itself (with the active debug mode displaying the ossec.log)

- What FIM configuration are you using?

- Are you applying a different configuration through a centralized configuration that overwrites the agent's one? You can see it in the agent.conf file.

Regards.

**Comment by aitonc** [comment]
Hi bah07 I’m currently using Wazuh app 3.9.5-7.3.0 the virtual Machine Appliance, and I am trying to make it run on my file server due security reasons I can’t provide you with the logs, but I want FIM to analyze about 5TB of data and last time it took FIM about 2 Hours to scan 530 MB of data am I doing something wrong??? All my agents are  connected although after a few hours my file server disconnects automatically, but during that time it's reporting all other security events, except for the FIM and vulnerability which for some reason is not working anymore. I’m using realtime, whodata and checkall on the agent’s ossec.conf file

**Comment by bah07** [comment]
Issue closed for duplication with https://github.com/wazuh/wazuh/issues/5457.

Regards.
