### ISSUE TITLE
Restart agent CLI not response

### ISSUE THREAD

**Issue by Aviv641999** [wazuh/wazuh#5365]
Hi,
I am using wazuh v3.11.2 server ubuntu 16.04 from package. i have also wazuh app in splunk.
I am trying to restart my redhat agent from agent_control:

`/var/ossec/bin/agent_control -R -u 100`

The output is normal:

`Wazuh agent_control: Restarting agent: 100`

But the agent actually didn't restart, i checked in the local logs of the agent - ossec.log and there is no indication of restart.

When i check if the agent is active, it show that it is active:

```
root@MyServer:~# /var/ossec/bin/agent_control -l | grep "ID: 100"
ID: 100, Name: MyComputer, IP: any, Active
```

I don't see any difficulties in the functioning of the agent and the server, the syschecks are occurs and the data is flowing to the server, same for local logs that transfering to the server, everything is okay.
 The local_internal_options.conf contains:

```
logcollector.remote_commands=1
wazuh_command.remote_commands=1
```

The weird thing is the API PUT call is working:

`PUT /agents/100/restart`

Then i see in ossec.log of the agent the restart process.

Is there any problem in the connection between the server and the agents?
Is something is configure wrong?

Thanks for the helpers :)

**Comment by pereyra-m** [comment]
Hello @Aviv641999

Sorry to hear you are having troubles, thank you for your detailed question.

Your configuration is correct, and I have already tested it in **v3.13.0**
When the manager uses the command 

`/var/ossec/bin/agent_control -R -u 100`

The agent should be restarted. The log with that info is located in **/var/ossec/logs/active-responses.log** in the agent. This is an example entry

> Wed Jul  1 09:03:06 UTC 2020 /var/ossec/active-response/bin/restart-ossec.sh add - null (from_the_server) (no_rule_id)

You said the API is able to restart the agent, so It isn't clear what is causing this issue.

My recommendation would be to upgrade from **v3.11.2**, if it is possible, to the latest stable version **v3.13.0**. 

If this is not viable, could you please tell me more in detail why do you need to restart the agent? So we can find a workaround to this situation.

Regards.

**Comment by Aviv641999** [comment]
Hi @pereyra-m,
Thank you for your time, i really appreciate it.

The log **/var/ossec/logs/active-responses.log** doesn't contain any log such this.
There is not effect to the command 
`/var/ossec/bin/agent_control -R -u 100`

The need to remotely restarting the agent is necessary for the functionality of the organization.
I don't see any sufficient reason to upgrade wazuh version.

Does the API use a different way than agent_control? why so basic capability doesn't work?

**Comment by pereyra-m** [comment]
Hi  @Aviv641999.

Well, we'll try then to figure it out !

We are going to run the **agentd** daemon in debug mode, so we can track the message when it arrives. 

Do this two times please, one of them using **agent_control** and the other one using the **API**. 
And share the results after, so we can find the problem.

Regards.

### Steps in the agent

#### Stop the daemon

`kill -9 "$(pidof ossec-agentd)"`

#### Check the process isn't running
You shouldn't see a process here
`ps -aux | grep ossec-agentd`

#### Run the daemon in foreground/debug mode

`/var/ossec/bin/ossec-agentd -f -dd`

### Steps in the manager

Perform an **agent restart** using both methods.

### Example data

You'll see a lot of debug information, but after a successful restart request, you may find something like this

```
2020/07/02 00:56:11 ossec-agentd[6341] receiver.c:92 at receive_msg(): DEBUG: Received message: '#!-execd restart-ossec0 - null (from_the_server) (no_rule_id)'

2020/07/02 00:56:13 ossec-agentd[6341] sig_op.c:49 at HandleSIG(): INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
```

**Comment by Aviv641999** [comment]
Hi, great idea!
I run the agentd daemon in debug mode on the agent, and execute `/var/ossec/bin/agent_control -R -u 100`,
the result is nothing.
However, when i try executing `PUT /agents/100/restart`, the following message pop up:

```
ossec-agentd[63141] receiver.c:92 at receive_msg(): DEBUG: Received message: '#!-execd restart-ossec0 - null (from_the_server) (no_rule_id)'
ossec-agentd[63141] sig_op.c:49 at HandleSIG(): INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
```

Do you know what is the problem?

**Comment by pereyra-m** [comment]
Hi, thank you for your answer.

Following the debug information you provided, it seems that the manager isn't sending the requested command. Or maybe, it isn't arriving to the agent.  But this only happens if you don't use the API.
Please, consider that the API **is** the recommend method.

Have you tried with the other agents too? is it the only one failing? 
If we try to restart all agents at once, do we have the same behavior ? 
(`/var/ossec/bin/agent_control -R -a`)

We'll do the same debugging trick, but now from the manager's side. In this case, the daemon is called **remoted**:
### Steps in the manager
#### Stop the daemon

`kill -9 "$(pidof ossec-remoted)"`

#### Check the process isn't running

`ps -aux | grep ossec-remoted`

#### Run the daemon in foreground/debug mode

`/var/ossec/bin/ossec-remoted -f -dd`

#### Restart the agent

`/var/ossec/bin/agent_control -R -u 100`

For all agents

`/var/ossec/bin/agent_control -R -a`

### Example data

You'll find a lot of messages, even the ones that this agent is sending. 
This is useful to double check the communication between the two ends.

After the restart request, you may find something similar to the example below:

> 
> 2020/07/07 09:53:21 ossec-remoted[4987] ar-forward.c:44 at AR_Forward(): DEBUG: Active response request received: (msg_to_agent) [] NNS 010 restart-ossec0 - null (from_the_server) (no_rule_id)
> 
> 2020/07/07 09:53:21 ossec-remoted[4987] ar-forward.c:119 at AR_Forward(): DEBUG: Active response sent: #!-execd restart-ossec0 - null (from_the_server) (no_rule_id)
>

**Comment by Aviv641999** [comment]
Hi @pereyra-m.
I've done what you said and i get your valid output like:

```
ossec-remoted[4987] ar-forward.c:44 at AR_Forward(): DEBUG: Active response request received: (msg_to_agent) [] NNS 010 restart-ossec0 - null (from_the_server) (no_rule_id)
ossec-remoted[4987] ar-forward.c:119 at AR_Forward(): DEBUG: Active response sent: #!-execd restart-ossec0 - null (from_the_server) (no_rule_id)
```

But i also got this:

`ossec-remoted[4987] sendmsg.c:89 at send_msg(): WARNING: (1245): Sending message to disconnected agent '100'.`

When i do **/var/ossec/bin/agent_control -l | grep "ID: 100"**, i get:

`ID: 100, Name: Computer-100, IP: any, Active`

So the agent is active for sure, also when i mstsc to the computer and check the service of wazuh is running.
Maybe it is because i use wazuh in cluster mode so the server that manage the agent is some node not the manager we debug just now.

Thank you very much.
Have a nice day :)

**Comment by pereyra-m** [comment]
Hello @Aviv641999!

Excellent! I'm glad you could notice that message.

I apologize for the inconvenience, there is an issue in progress ([#5428](https://github.com/wazuh/wazuh/issues/5428)) that will unify the behavior of **agent_control** and **cluster_control** when the agents are listed.

In the meantime, you can use [cluster_control](https://documentation.wazuh.com/3.13/user-manual/reference/tools/cluster_control.html) to list your agents

`/var/ossec/bin/cluster_control -a`

We'll leave the issue opened until the fix is merged.
Thank you for your time.

Have a nice day too!
Regards.

**Comment by gary561** [comment]
If the agent is registered and connected to the manager, execute ./agent_control -R -u agent_id on the manager, the agent can be restarted.
If the agent is registered and connected to work, execute ./agent_control -R -u agent_id on the manager, and the agent will fail to restart.
Reason: I found the answer after reading the agent_control code. When agent_control is executed on the manager, unix sock msg:(msg_to_agent) [] NNS 1001 restart-ossec0-null (from_the_server) (no_rule_id) will be sent to the local machine /var/ossec/queue/alerts/ar.
 After the remote dynamic response thread of the process on the manager receives the message, it will send the message to the specified agent, using the structured socket: keyentries[key_id]->sock, but because the manager is not connected to the agent, it is connected to the agent The connection is work. So here will directly hit a debug message: Send operation cancelled due to closed socket. That is to say, it was not sent successfully, and the code did not make any judgment on it.

**Comment by pereyra-m** [comment]
Hello @gary561 !
Thank you for your contribution!

Indeed, the `agent_control` tool should warn the user about this.
In a cluster scenario, the **API** is the recommended method because it makes a distributed call, considering the agents and the workers they are reporting to.

Regards.
