### ISSUE TITLE
Agent-info implementation analysis

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#5368]
### Description

The goal of this issue is to get a good understanding of the current usage and management of the information stored in the plain text files located within the folder `queue/agent-info` from the code point of view. In addition, we should get knowledge enough of the data query and data update flows in order to re-design those mechanisms.

The items going to be analyzed are:

- [x] Analyze the usage of the folder `queue/agent-info`. Identify the processes that access it either for query or modify data.
- [x] Analyze the data stored in the plain text files located within the folder `queue/agent-info`.
- [x] Analyze the `wazuhdb` and the possibilities to store in this DB the data that is currently stored in the plain text files.
- [x] Analyze the data related to groups stored in plain text files and the possibilities to save it in the `wazuhdb`.
- [x] Analyze how the agent status is queried by `cluster_control`, `agent_control`, `manage_agents` and `Wazuh API`.
- [x] Analyze the execution flow of a `Wazuh API` query.
- [x] Analyze the `keep-alive` execution flow for single manager and cluster scenarios.
- [x] Analyze the current design of the synchronization module.
- [x] Analyze the execution flow of plain text files synchronization in a cluster scenario.
- [x] Research about tools to make a baseline measure of the disk access.

**Comment by pereyra-m** [comment]
#### Analyze the usage of the folder queue/agent-info. Identify the processes that access it either for query or modify data.

The manager stores in the folder **queue/agent-info** a plain text file for every agent ever connected.
Each file has the **AgentName-ip** name structure.

We can identify many modules, functions and daemons that access this folder. 
The following files use the **AGENTINFO_DIR** definition:

- labels.c
- manager.c
- ossecalert_decoder.c
- read-agents.c 
- validate.c
- wm_database.c

These binaries and daemon also access this folder:

- agent_control
- manage_agents
- rootcheck_control
- analysisd
- remoted
- authd
- monitord 
- wm_database

**Comment by pereyra-m** [comment]
### Analyze the data stored in the plain text files located within the folder queue/agent-info

The structure defined for the **agent-info** folder files has the following fields
```

typedef struct _agent_info {
    char *last_keepalive;
    char *syscheck_time;
    char *syscheck_endtime;
    char *rootcheck_time;
    char *rootcheck_endtime;
    char *os;
    char *version;
    char *merged_sum;
} agent_info;
```
Other related plain text files are listed below

#### queue

- **queue/agent-info/(name-ip)** // #define AGENTINFO_DIR
- **queue/agent-groups/(xxx)**    // #define GROUPS_DIR      "/queue/agent-groups"
- **queue/agents-timestamp**    //#define TIMESTAMP_FILE "/queue/agents-timestamp"

#### etc

- **etc/client.keys**         // #define AUTH_FILE          KEYS_FILE
- **etc/authd.pass**        // #define AUTHD_PASS      "/etc/authd.pass"

#### syscheck

- **queue/syscheck/**         // #define SYSCHECK_DIR "/queue/syscheck"

#### rootcheck

- **queue/rootcheck/**         //#define ROOTCHECK_DIR "/queue/rootcheck"

**Comment by pereyra-m** [comment]
#### Analyze the wazuhdb and the possibilities to store in this DB the data that is currently stored in the plain text files.

The **global.db** database in **var/db** should be deprecated, and a new **global.db**  may be created in **queue/db**.
The **queue/agent-info** folder information will be migrated to the new **db** , and the whole folder should be removed.

In order to achieve this goal, all the information inside these elements has been analyzed. 
The following table shows a comparison between this database and the plain text files inside **agent-info**:

- If both fields exist, we have duplicated information
- The notes in bold to the right indicate where the information is stored (outside **agent-info**)
- The notes in bold to the left indicate where the information is stored (outside **global.db**)

The plain text file has not a column nor a variable name, a generic one has been used.


Global DB (agent table) | agent-info/*
-- | --
id | id_agent
name | name
ip | #"_agent_ip" 
register_ip | #"_agent_ip" 
internal_key | **"etc/client.keys"**
os_name | os_name
os_version | os_version = os_major.os_minor.os_build
os_major | os_version = os_major.os_minor.os_build
os_minor | os_version = os_major.os_minor.os_build
os_codename | os_codename
os_build | os_version = os_major.os_minor.os_build
os_platform | os_platform
os_uname | os_uname
os_arch | os_arch
version | version
config_sum | config_sum
merged_sum | merged_sum
manager_host | #"_manager_hostname"
node_name | #"_node_name"
date_add | **"/queue/agents-timestamp"**
last_keepalive | last_keepalive
status | **[inferred through file stats]**
fim_offset | **[inferred through file stats]**
reg_offset | **[inferred through file stats]**
group | **"/queue/agent-group"**
  **"/queue/syscheck"**  | syscheck_time
 **"/queue/syscheck"** | syscheck_endtime
  **"/queue/rootcheck"** | rootcheck_time
 **"/queue/rootcheck"** | rootcheck_endtime

**Comment by DProvinciani** [comment]
### Analyze how the agent status is queried by cluster_control, agent_control, manage_agents, and Wazuh API.

- **cluster_control**: This is, in fact, a python script located at:

`https://github.com/wazuh/wazuh/blob/3.14/framework/scripts/cluster_control.py`

The way for getting information of the agents is:

`cluster_control -a, --list-agents`

This gets the agents information by using the function `get_agents` within the file:

`https://github.com/wazuh/wazuh/blob/3.14/framework/wazuh/cluster/control.py`

This function essentially makes a GET request to the Wazuh API with the next parameters:

```python
    input_json = {'function': '/agents', 'from_cluster': False,
                  'arguments': {
                      'filters': {'status': ','.join(filter_status), 'node_name': ','.join(filter_node)},
                      'limit': None, 'wait_for_complete': False,
                      'select': {'fields': list(select_fields)}}}
```

- **agent_control**: This binary is implemented in the file:

`https://github.com/wazuh/wazuh/blob/3.14/src/util/agent_control.c`

All the possible queries will take information from the files `/etc/client.keys` and all the plain text files located within `/queue/agent-info`

- **manage_agents**: This is a binary implemented by all the code within:

`https://github.com/wazuh/wazuh/blob/3.14/src/addagent/main.c`

The mechanism that this tool uses to get information related to the agents is exactly the same as the **agent_control** tool.

**Comment by DProvinciani** [comment]
### Analyze the execution flow of a Wazuh API query.

The API exposes a set of different methods for each Wazuh module. We have a file for each module with the code of each method located within the folder:

`https://github.com/wazuh/wazuh-api/tree/3.14/controllers`

If we take as an example the agent list flow, we should analyze the `/agents` GET request that is located in the file:

`https://github.com/wazuh/wazuh-api/blob/3.14/controllers/agents.js`

This request will call the helper method located in:

`https://github.com/wazuh/wazuh-api/blob/3.14/helpers/request_templates.js`

And finally, this will call the `exec` helper in:

`https://github.com/wazuh/wazuh-api/blob/3.14/helpers/execute.js`

By this method, the API executes a Python script. This script is:

`https://github.com/wazuh/wazuh-api/blob/3.14/models/wazuh-api.py`

And in the Wazuh manager, is located at `/var/ossec/api/models/`. This script will end up calling the `DistributedAPI` exposed by the cluster. It receives and returns a JSON.

**Comment by DProvinciani** [comment]
### Analyze the data related to groups stored in plain text files and the possibilities to save it in the wazuhdb

Related to groups we can say that when a group is created, a new folder with the name of the group is created in:

`/var/ossec/etc/shared/`

This folder contains an empty configuration file for the group. Then, for each agent being added to the group, the name of the group will be specified in the file (in a CSV format):

`/var/ossec/queue/agent-groups/<agent-id>`

**Comment by pereyra-m** [comment]
#### Research about tools to make a baseline measure of the disk access.

It is necessary to measure the current disk usage, to determine the success of the implementation.
Many different tool were tested:
- iotop
- htop
- perf
- iosnoop (perf_tools)
- SystemTap

The results must be easy to record and analyze afterwards. So, a batch implementation of **iotop** seems more adequate

`sudo iotop -aobtqqqk -u ossec `

This command scans the disk access by the **ossec** user, and saves the accumulated read, write and I/O data.

**Comment by DProvinciani** [comment]
**Analyze the execution flow of plain text files synchronization in a cluster scenario**

The explanation of the purpose of this file synchronization is explained here:

`https://documentation.wazuh.com/3.13/development/wazuh-cluster.html?highlight=framework#agent-info`

And essentially, all the synchronization flow is done by the function `sync_agent_info` defined here:

`https://github.com/wazuh/wazuh/blob/3.14/framework/wazuh/cluster/worker.py#L213`

**Comment by DProvinciani** [comment]
Closing the issue as the analysis was finalized and is reflected in all the comments.
