### ISSUE TITLE
Syscheck will not switch to realtime when whodata is enabled, Audit is set to immutable mode and wazuh_fim rule has not been written manually.

### ISSUE THREAD

**Issue by sergiospa** [wazuh/wazuh#5400]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.0-31306 | ossec-syscheckd | Agent | Packages | CentOS Linux 7  |

Hi team,

Enabling audit immutable mode is a security measure described here: https://secscan.acron.pl/centos7/4/1/18.

As the title of this issue states, `syscheck` will not switch to `realtime` mode when the following conditions are met:
-  `whodata` is enabled
- `audit` is set to `immutable` mode
- `wazuh_fim` rule has not been written manually.

These are the steps that I followed to configure whodata with immutable mode:

1. Disable `startup_healthcheck` in the syscheck configuration and monitor some directory with `whodata`:
```xml
<whodata>
  <startup_healthcheck>no</startup_healthcheck>
 </whodata>
 <directories check_attrs="yes" check_group="yes" check_inode="yes" check_mtime="yes" check_owner="yes" check_perm="yes" check_sha256sum="yes" check_size="yes" recursion_level="0" report_changes="yes" tags="appid=1234" whodata="yes">/test</directories>
```
2. Enable immutable mode and write the wazuh audit rule manually:
In `/etc/audit/rules.d/audit.rules`:
```
# This file contains the auditctl rules that are loaded
# whenever the audit daemon is started via the initscripts.
# The rules are simply the parameters that would be passed
# to auditctl.

# First rule - delete all
-D

# Increase the buffers to survive stress events.
# Make this bigger for busy systems
-b 320

#Wazuh ule
-w /test/ -p wa -k wazuh_fim

# Immutable mode
-e 2
```

3. Reload the rules file:
`auditctl -R /etc/audit/rules.d/audit.rules`

At this point, whodata should be working fine. Now, let's recreate the issue:

1. Comment the wazuh audit rule in `/etc/audit/rules.d/audit.rules`:
```
# This file contains the auditctl rules that are loaded
# whenever the audit daemon is started via the initscripts.
# The rules are simply the parameters that would be passed
# to auditctl.

# First rule - delete all
-D

# Increase the buffers to survive stress events.
# Make this bigger for busy systems
-b 320

#Wazuh ule
#-w /test/ -p wa -k wazuh_fim

# Immutable mode
-e 2
```

2. Reboot the system: `reboot`.
At this point, syscheck should have switched to `realtime` mode. Instead, `realtime` will not be working, but syscheck will run scheduled scans (according to the configured `frequency`).

# Logs with `syscheck.debug=2`:
[syschecklogs.txt](https://github.com/wazuh/wazuh/files/4870499/syschecklogs.txt)

The expected behavior for syscheck would be to switch to `realtime` mode when`whodata` is not working due to the absence of the audit rule.

Let me know if you need any further information.

Regards,
Sergio.

**Comment by jesusjimsa** [comment]
I have been researching and I have found a first solution to this problem. When reloading the rules, we could run a command like this one:
```bash
auditctl -s | grep enabled | sed -e 's/\\(^.*\\)\\(.$\\)/\\2/' > audit_status
```

This would write the status of auditd to a file, this status can be 0 (disabled), 1 (enabled) or 2 (immutable). We would read this status and enable realtime if auditd is in immutable mode.

**Comment by Molter73** [comment]
libaudit already provides a way to query auditd directly through a socket in order to get it's operation mode. With this in mind I believe a better way to handle this is to use calls to [audit_request_status](https://linux.die.net/man/3/audit_request_status) and [audit_get_reply ](https://linux.die.net/man/3/audit_get_reply) in order to retrieve auditd status. The `enabled` field from the `audit_status` struct does not explicitly say so, but by inspecting the code for `auditctl` we can see that a value of 2 equals auditd enabled and in immutable mode: https://github.com/linux-audit/audit-userspace/blob/06925edb8068c1a7b60fd51b086ce6757880b689/src/auditctl-listing.c#L485-L499

By keeping all this in mind, I would replace our `check_auditd_enabled` function so it queries the status directly to the daemon, instead of trying to get it from an `openproc` -> `readproc` operation
https://github.com/wazuh/wazuh/blob/89aa5cbe466b74f16fc195402dea9b36742103a6/src/syscheckd/syscheck_audit.c#L91

We should also consider keeping a descriptor open to auditd instead of opening and closing it everytime we try to read the configured rules, preferably one that can only be accessed inside `syscheck_audit.c`.
https://github.com/wazuh/wazuh/blob/89aa5cbe466b74f16fc195402dea9b36742103a6/src/syscheckd/syscheck_audit.c#L216-L218

**Comment by jesusjimsa** [comment]
I have now developed this second solution using `audit_request_status` and `audit_get_reply`. I have also changed the way we handle the descriptor having a global variable to the `syscheck_audit.c` file and opening the file in the `audit_init` function.
I will write now a function to check which directories already had audit rules before enabling the immutable mode.

**Comment by jesusjimsa** [comment]
Using `search_audit_rule` I have been able to write the function that enables realtime for the directories that don't already have rules when auditd is immutable. I will test now that everything is working correctly create a pull request.

**Comment by jesusjimsa** [comment]
I will start now fixing the unit tests.

**Comment by jesusjimsa** [comment]
I launched the integration tests last Friday and all of them passed in CentOS, Ubuntu and Windows. The problem was in macOS and Solaris, because they run only in _scheduled_ mode.
To fix the failed tests, I have to add the fix explained here: https://github.com/wazuh/wazuh/issues/6690#issuecomment-741616584
I will wait to talk about this with the team first, as this will now cause conflicts in several pull requests.
