### ISSUE TITLE
Linux agent change bin names

### ISSUE THREAD

**Issue by Aviv641999** [wazuh/wazuh#5407]
Hi,
I am using wazuh v3.11.2 and i want to change the bin files names (`ossec-logcollector`, `ossec-execd` etc.)
from default.
If i change the name of `ossec-control` it is possible to configure it in **/etc/systemd/system/wazuh-agent.service**, 
but when other bins (`ossec-agentd`, `ossec-syscheckd` etc.) are changed it can not start the service.
I tried to create symlinks that link to the original bin files with other names but the same name is shown in the 
`top -c`.
Can you know how to run linux agent with other names for the bin files?

Thanks for the helpers :)

**Comment by FernandoCP** [comment]
Hi @Aviv641999 !

There is no proposed way to do this at the moment but to make that change you should at least:

- Change the name of the binaries in the Makefile so that they are compiled with that new name.

- Modify the agent-control scripts, so that they run with the correct binaries.

If you need more help or have any specific question when making changes, do not hesitate to ask. I hope this information will be helpful to you.

Best regards,
Fernando.

**Comment by Aviv641999** [comment]
Hi @FernandoCP,
Thanks you for your time.
I've done the compile process once so i pretty familiar with it.
But i need your guidance on changing the specific files.

Where in the 'Makefile' the changes that need to be done for changing the bin files names?
Agent-control scripts? can you explain please.

Thank you, i am really grateful.

**Comment by antoniomanuelfr** [comment]
hi @Aviv641999 
I have been investigating your case and these are the steps that I have been trying to change the binary name of logcollector: 
## Makefile modifications: 

- First, I have changed these two variables [BUILD_SERVER](https://github.com/wazuh/wazuh/blob/ff962364251c1fa38468bc750c8431ced9254b84/src/Makefile#L557) and [BUILD_AGENT](https://github.com/wazuh/wazuh/blob/ff962364251c1fa38468bc750c8431ced9254b84/src/Makefile#L579) replacing `ossec-logcollector` by `ossec-custom_logcollector`.
- After that, I modified the target of the [rule](https://github.com/wazuh/wazuh/blob/ff962364251c1fa38468bc750c8431ced9254b84/src/Makefile#L1243-L1244) that will create the binary. I changed  `ossec-logcollector` by `ossec-custom_logcollector`

## Install script modifications:
After that, I modified the install script in order to get the correct binaries
- In the [file](https://github.com/wazuh/wazuh/blob/ff962364251c1fa38468bc750c8431ced9254b84/src/init/inst-functions.sh#L738) change `ossec-logcollector` by `ossec-custom_logcollector`
## Ossec control modifications
The next step that I took was to modify the ossec-control script. In order to do that I modified these files: 
- [`src/init/ossec-server.sh`](https://github.com/wazuh/wazuh/blob/ff962364251c1fa38468bc750c8431ced9254b84/src/init/ossec-server.sh#L39)
- [`src/init/ossec-client.sh`](https://github.com/wazuh/wazuh/blob/ff962364251c1fa38468bc750c8431ced9254b84/src/init/ossec-client.sh#L15)
- [`src/init/ossec-local.sh`](https://github.com/wazuh/wazuh/blob/ff962364251c1fa38468bc750c8431ced9254b84/src/init/ossec-local.sh#L24)
The change was the same for the three files, change `ossec_logcollector` by `ossec_custom_logcollector`

Here I post a copy of the `ossec.log` that checks that logcollector was working: 
```
2020/07/22 10:03:45 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/audit/audit.log'.
2020/07/22 10:03:45 ossec-logcollector: INFO: (1950): Analyzing file: '/var/ossec/logs/active-responses.log'.
2020/07/22 10:03:45 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/messages'.
2020/07/22 10:03:45 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/secure'.
2020/07/22 10:03:45 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/maillog'.
2020/07/22 10:03:45 ossec-logcollector: INFO: Monitoring output of command(360): df -P
2020/07/22 10:03:45 ossec-logcollector: INFO: Monitoring full output of command(360): netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d
2020/07/22 10:03:45 ossec-logcollector: INFO: Monitoring full output of command(360): last -n 20
2020/07/22 10:03:45 ossec-logcollector: INFO: Started (pid: 21032).
```

This confirms that you can change the binary name, but I don't recommend doing this because the software is not designed to change the binaries in an easy way.
If you have any questions, I will be glad to help you.
Kind regards.

**Comment by Aviv641999** [comment]
Hi @antoniomanuelfr !
Thank you for answering, it was very useful !

I have only one problem, when i try to rename **wazuh-modulesd** error are created while restarting.

Every restart leave lonely **wazuh-modulesd** process that hasn't stopped, i can assume that it occurs because the file  `wazuh-modulesd-30073.pid` isn't rename like others. (`ossec-logcollector-30073.pid`, `ossec-syscheckd-30077.pid` have renamed to my custom name) 

So when ossec-control stop the service processes it doesn't find my custom  `wazuh-modulesd-30073.pid`.

Do you know why from the beginning it didn't created with my custom name  ?

Thank you so much for helping!

**Comment by antoniomanuelfr** [comment]
Hi again @Aviv641999 

If you want to rename wazuh-modulesd you have to change this[ definiton](https://github.com/wazuh/wazuh/blob/ff962364251c1fa38468bc750c8431ced9254b84/src/wazuh_modules/wmodules.h#L16) in the source code. 

In the previous answer, I missed one thing. You have to change the definition of those variables in the modules that you are going to rename, you can do it in the makefile. For example, if the module that you are going to rename is **os_maild** : 
https://github.com/wazuh/wazuh/blob/ff962364251c1fa38468bc750c8431ced9254b84/src/Makefile#L1179
You have to change this line by  `${OSSEC_CC} ${OSSEC_CFLAGS} -DARGV0=\"ossec-custom-maild\" -c $^ -o $@`

Kind regards. 
Antonio.
