### ISSUE TITLE
Can linux agent use custom user?

### ISSUE THREAD

**Issue by Aviv641999** [wazuh/wazuh#5410]
Hi,
I am using wazuh v3.11 for a while in linux agents and i want to change the name of the user **'ossec'**.
This name is familiar so i want it to be something else, i tries to change it by:
`usermod -l myName ossec`
But after restarting the service it pop this error:
`ossec-execd: CRITICAL: (1203): Invalid user 'ossec' or group 'ossec' given.`
How can it be done?

Thanks for the helpers :)

**Comment by 0xN3utr0n** [comment]
Hi @Aviv641999,
By default the username and groupname  are hardcoded to `ossec`. This is done for security reasons, since once the modules start running they drop privileges from `root` to `ossec`. If you really wish to use a different user and group, the only workaround is to recompile the agent and change this flags:

**Comment by 0xN3utr0n** [comment]
Hi @Aviv641999,
By default the username and groupname are hardcoded to `ossec`. This is done for security reasons, since once the modules start running they drop privileges from `root` to `ossec`. 

If you really wish to rename them, the only workaround is to recompile the agent and change the following flags in the Makefile:
https://github.com/wazuh/wazuh/blob/8886861a537de72714b9c463ea27b5a8f27f5143/src/Makefile#L42-L43
_Overwrite with the desired names._

Once done, just follow this [guide](https://documentation.wazuh.com/3.13/installation-guide/installing-wazuh-agent/linux/centos6-or-greater/wazuh_agent_sources_centos6_or_greater.html#centos-6-or-greater-from-sources) for source-code installation.

Hope it helps,
Fernando

**Comment by Aviv641999** [comment]
Hi @0xN3utr0n .
Thank you for helping, i really appreciate it.
I've done what you said and recompile the agent with 

```
OSSEC_GROUP?=aviv 
OSSEC_USER?=aviv
```

After installation i got this error

`ossec-execd: CRITICAL: (1203): Invalid user '' or group 'aviv' given.`

Do you know why this is happening?
Thank you!

**Comment by 0xN3utr0n** [comment]
Hi @Aviv641999 ,
You must too rename the group to the one specified in the Makefile:
`groupmod -n avid ossec`

No errors should appear afterwards.

Kind regards,
Fernando

**Comment by Aviv641999** [comment]
Great @0xN3utr0n thank you very much!
