### ISSUE TITLE
New feature request for SCA

### ISSUE THREAD

**Issue by eric-holtzclaw** [wazuh/wazuh#5421]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

4.1 | Manager SCA | Manager and OSX Agent | OSX | 10.x

Security configuration assessment agent
Disk encryption Yes/No
Complex password Yes/No
Show other local accounts Show
Show admins group Show
Screen timeout to lock screen Yes/No
Biometrics enabled Yes/No
Firewall on Yes/No
Automatic updates on Yes/No
WiFi info SSID show last 3

**Comment by chemamartinez** [comment]
Hi @eric-holtzclaw,

I think you mean to include that checks to SCA policies. In that case, I would transfer this issue to the [ruleset repository](https://github.com/wazuh/wazuh-ruleset) where they are located.

We are continuously working on adding new content to SCA policies, most of them based on CIS benchmarks. For those policies based on CIS, custom checks cannot be included because of consistency.

However, those custom checks could fit in the generic policy for Unix agents: https://github.com/wazuh/wazuh-ruleset/blob/master/sca/generic/sca_unix_audit.yml

Please, provide us more details about your request and we will evaluate how to implement it.

Best regards,
Chema.

**Comment by eric-holtzclaw** [comment]
Looks like someone else has done this can this in the default install now for OSX IE DARWIN?
https://github.com/wazuh/wazuh-ruleset/blob/master/sca/darwin/17/cis_apple_macOS_10.13.yml

**Comment by chemamartinez** [comment]
Hi @eric-holtzclaw,

For now, there are three policies available for macOS agents:

- https://github.com/wazuh/wazuh-ruleset/blob/master/sca/darwin/17/cis_apple_macOS_10.13.yml for macOS 10.13 (High Sierra)
- https://github.com/wazuh/wazuh-ruleset/blob/master/sca/darwin/16/cis_apple_macOS_10.12.yml for macOS 10.12 (Sierra)
- https://github.com/wazuh/wazuh-ruleset/blob/master/sca/darwin/15/cis_apple_macOS_10.11.yml for macOS 10.11 (El Capitan)

But they are not provided with the macOS agent installer, so they have to be added to macOS agents manually. We are working on supporting more OSX versions such as Mojave and Catalina.

I hope it answers your question. Please, don't hesitate to contact us for further questions.

Best regards,
Chema.

**Comment by eric-holtzclaw** [comment]
@chemamartinez will you add this to your documentation? https://documentation.wazuh.com/3.9/user-manual/capabilities/sec-config-assessment/security-configuration-assessment.html#available-policies
