### ISSUE TITLE
Refactor and fix manager SDK, update API filter names for /manager/logs

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#5459]
Hello team,

After reviewing https://github.com/wazuh/wazuh/issues/5431 I realized our current [SDK for the manager](https://github.com/wazuh/wazuh/blob/4.0/framework/wazuh/manager.py) has some code pieces which should be refactored, such as:

https://github.com/wazuh/wazuh/blob/583bbc7dfc7e39b0e6842dade98cbfada45cf75c/framework/wazuh/manager.py#L81-L113 Here we have a very complex logic to use filters (category and type_log) who do not match with the current name of the response given (tag and level). We also use a hardcoded number of lines to read from the log (2000), while using a maximum number of 500 (database_limit).

https://github.com/wazuh/wazuh/blob/583bbc7dfc7e39b0e6842dade98cbfada45cf75c/framework/wazuh/manager.py#L190-L197 Here we have a possible use case where a file could end up being deleted and then an exception raised. (Check and update unit tests, they should have catch this)

We should review and update the entire code looking to refactor for a better efficiency and clarity.

We should also update related API endpoints and associated tests so they use the appropriate filter names (tag and level), and any other suffering from the same issue.

Best regards,

David J. Iglesias

**Comment by Selutario** [comment]
|Working branch|
|--|
|[dev-5459-refactor-manager-sdk](https://github.com/wazuh/wazuh/tree/dev-5459-refactor-manager-sdk)|

## Issue update

Hi team!

I've already done the manager SDK refactor. Some changes to core / manager have also been required. I have updated all the unit tests related to the changes made, and have fixed and improved some of the ones that already existed. I've also added some new built-in tests in API 4.0.

I was trying to modify process_array so that by using the q parameter it is possible to specify parentheses for the order of operations, although I have not seen it feasible to do so as part of this issue.

Kind regards,
Selu.
