### ISSUE TITLE
Eventchannel doesn't work after restart of Windows Event Log

### ISSUE THREAD

**Issue by grg121** [wazuh/wazuh#5495]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.1| Log collector | Agent | Packages | Windows |

Hello team,

Helping a user from our slack channel to develop a new rule to trigger alerts when the Windows Event Log service is restarted we've detected that, after a restart of the service, logcollector doesn't keep sending events from the Windows agent. 

We're using the following configuration:

```
<localfile>
    <location>Security</location>
    <only-future-events>no</only-future-events>
    <log_format>eventchannel</log_format>
    <query>Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and
      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and
      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and
      EventID != 5152 and EventID != 5157]</query>
  </localfile>
```

To test the custom rule:

```
<rule id="100011" level="14">
 <if_sid>63108</if_sid>
 <field name="win.system.eventID">^1100$</field>
 <description>The event logging service has shut down</description>
 <options>no_full_log</options>
 </rule>
```

The rule works and generates the expected alert **after restarting the agent**. It seems that there is a problem reconnecting with the Event Log Service after it restarts. 

Maybe this is related with https://github.com/wazuh/wazuh/pull/3836 

Some logs with debug 2:

```
2020/07/17 00:54:44 ossec-agent[3620] run_check.c:95 at fim_send_sync_msg(): DEBUG: (6317): Sending integrity control message: {"component":"syscheck","type":"integrity_check_left","data":{"id":1594972163,"begin":"[x64] HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Internet Explorer\\ActiveX Compatibility\\{B34B19F4-7EBE-46CB-807C-746E72EBB4B6}","end":"[x64] HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Internet Explorer\\ActiveX Compatibility\\{B34B19F4-7EBE-46CB-807C-746E72EBB4B6}","tail":"[x64] HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Internet Explorer\\ActiveX Compatibility\\{B375275F-4705-4D2C-88C1-A891105B9ABA}","checksum":"2a8d7af777fadd2d367e6d4a36e0a6039cc2e47e"}}
2020/07/17 00:54:44 ossec-agent[3620] receiver-win.c:128 at receiver_thread(): DEBUG: Received message: '#!-syscheck dbsync checksum_fail {"id":1594972163,"begin":"[x64] HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Internet Explorer\\ActiveX Compatibility\\{B34B19F4-7EBE-46CB-807C-746E72EBB4B6}","end":"[x64] HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Internet Explorer\\ActiveX Compatibility\\{B34B19F4-7EBE-46CB-807C-746E72EBB4B6}"}'
2020/07/17 00:54:45 ossec-agent[3620] read_win_event_channel.c:628 at win_start_event_channel(): ERROR: Could not EvtSubscribe() for (all) which returned (15007)
2020/07/17 00:54:45 ossec-agent[3620] read_win_event_channel.c:628 at win_start_event_channel(): ERROR: Could not EvtSubscribe() for (compliance) which returned (15007)
2020/07/17 00:54:45 ossec-agent[3620] read_win_event_channel.c:511 at event_channel_callback(): DEBUG: Trying to reconnect compliance channel in 5 seconds.
2020/07/17 00:54:45 ossec-agent[3620] read_win_event_channel.c:511 at event_channel_callback(): DEBUG: Trying to reconnect all channel in 5 seconds.
```

I've already communicated this to the core team and Mauro is working on a possible solution.

Best regards.

**Comment by Molter73** [comment]
This problem is due to the event log name being used is stored on a pointer to free'd memory.

Here we can see that when starting the event channel reader, the channel name is passed into `win_start_event_channel` as `current->file` and later free'd:
https://github.com/wazuh/wazuh/blob/26605d5a37c81090b9a20a8e1f49f4d131c545b3/src/logcollector/logcollector.c#L178-L187

Inside `win_start_event_channel`, a copy to the pointer is stored inside the context used by the subscription function, which is invalid immediately after returning from the call:
https://github.com/wazuh/wazuh/blob/26605d5a37c81090b9a20a8e1f49f4d131c545b3/src/logcollector/read_win_event_channel.c#L543

This all means that when the subscription function gets called after a restart of Windows logging service, it will use an invalid pointer while attempting to reconnect:
https://github.com/wazuh/wazuh/blob/26605d5a37c81090b9a20a8e1f49f4d131c545b3/src/logcollector/read_win_event_channel.c#L510

**Comment by Molter73** [comment]
Just in case someone runs into this problem when trying to reproduce this behaviour, in order to stop/restart the Windows Event Log service the Schedule service needs to be stopped first. In order to achieve this, I had to modify the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Schedule\start` register value from 2 to 4 and restart the machine, after these steps I was able to freely stop and start the Windows Event Log service.
