### ISSUE TITLE
Same logs is lost on the master

### ISSUE THREAD

**Issue by kreon** [wazuh/wazuh#55]
I'm collecting all commands on the system via syslog and 'd like to process it with ossec.
Any command should generate alert level 1 and it's ok if I enter one or two commands.
But sometimes if I enter 10x ls and 10x id and then check the alerts.log I get only 1 x ls and 1 x id in the logfile. Seems there're some kind of alerts truncating but I can't find how to avoid this.
I checked the agent-logcollector first and it simply sends all logs to remoted.

**Comment by vikman90** [comment]
Hi @kreon,

As I understand, you're using a `command` or `full_command` log format and set a localfile to run `ls`. 

In order to get every output as you need, we may set the level of the rule 530 to 1. With this configuration it seems to work properly. There is a feature on the manager (_analysysd_ process) that ignores intentionally a log if the last received message is exactly the same.

For example, for messages "A B B C A B C C D", it will process "A B C A B C D".

So if you put the same command, such `ls` 10 times it's possible that the most of then arrive together and only one will be processed. If this is your problem you may append the `ls` output to the date with nanoseconds precision, or a random message, like this:

```
<localfile>
  <frequency>1</frequency>
  <log_format>full_command</log_format>
  <command>date +%s.%N; ls</command>
</localfile>
```

So messages will be always different and the manager will process all of them. 

If you're experimenting another kind of problem, please paste your configuration for us and explain the steps that you're following.

Kind regards.

**Comment by kreon** [comment]
BTW, I've found the reason. It was about syslog deduplicate mechanism that is a little buggy.
I've removed it and the logs appeared again.

**Comment by vikman90** [comment]
Thank you @kreon. In fact we disabled this feature a few days ago (https://github.com/wazuh/wazuh/commit/ef1afb0fd8b6e4abd0c9295d5ea207fedd1e319f) since it was so confusing and led to miscounting repetitive alerts.

From the next version on, logs will be parsed no matter the previous log. On the other hand, we are working on more sophisticated anti-flooding mechanisms.

Best regards.

**Comment by kreon** [comment]
As for me, I solved this problem by customizing rules. Now it fires once on a duplicating rules.
