### ISSUE TITLE
What happens with events when agent is disconnected?

### ISSUE THREAD

**Issue by rejszynski** [wazuh/wazuh#5559]
Hello,

My question is as it is in the title. 
Let's assume that agent have been disconnected for some reason and there is no connection to manager for a while - what about all the events coming through? Are they queued in some buffer until the agent have the connection again or are they simply lost?
I had also an issue when the events have been blocked on the Windows agent. 
I was doing some tests with my client and the events were not sent at all until my client has made a restart of the agent. 
Is there some mechanism or an option to configure to prevent from this kind of behaviour?

**Comment by vikman90** [comment]
Hi @rejszynski,

The agent has a global [buffer](https://documentation.wazuh.com/3.13/user-manual/reference/ossec-conf/client_buffer.html), which we call the leaky bucket, to handle the output throughput. If the manager gets disconnected, the agent blocks the modules so that the leaky bucket does not fill up:

![d1](https://user-images.githubusercontent.com/10536251/88524213-564e4d80-cff9-11ea-944d-7e3d2f56e78b.png)

In the particular case of Logcollector (the component that handles the [`<localfile>`](https://documentation.wazuh.com/3.13/user-manual/reference/ossec-conf/localfile.html) stanzas, we can set this module to send logs to an external source (like Fluentbit).

That's why Logcollector has one output buffer (which can also leak when it's full) for each output. One of these outputs is the agent itself.

![d2](https://user-images.githubusercontent.com/10536251/88525387-d3c68d80-cffa-11ea-9d16-df2e0f47d98f.png)

We can configure the size of these buffers (internal option [`logcollector.queue_size`](https://documentation.wazuh.com/3.13/user-manual/reference/internal-options.html#logcollector)).

If the agent gets disconnected, it blocks the data flow between Logcollector and the agent's buffer. However, Logcollector continues reading the log files and Eventchannel so the output buffer may continue to grow. If the buffer fills up, new logs will be lost.

Hope this answers your question.

Best regards.
