### ISSUE TITLE
analysisd process 100% CPU usage

### ISSUE THREAD

**Issue by kir-b** [wazuh/wazuh#560]
I have more than 500 agents with one server. And now I use Wazuh for FIM only.
But ossec-analysisd process use 100% CPU of one core.
Previously, I analyzed the logs from agents, but when the number of agent instances increased by more than 300, many agents lost connection to the server. I stoped collect logs after that.
Now all agents don't lost connection to the server.
Аlso I tried to reduce the number of rules for analysis, but this did not change the use of the CPU.
The number of events from stat are 120 000 - 130 000 per hour.

How many agents could be connected to one server?
Could  ossec-analysisd use more than one CPU core?

**Comment by TJOSERAFAEL** [comment]
Hi @kir-b ,

since **analysisd** is not multithreaded it only runs on the main thread on one core. In our roadmap we have the task to implement a multithreaded version of analysisd and remoted that will increase performance drastically.

The default maximum number of agents supported for a manager are 8000. You can change this value when running the Makefile with the parameter MAXAGENTS=xxxx. 

The most important part isn't the number of agents connected, it is the events per second that the manager receives. As you have around 130.000 per hour it isn't that much at all.

Can you please provide your manager hardware specs? Are you connecting the agents via TCP or UDP?

Best regards.

**Comment by kir-b** [comment]
Hi @TJOSERAFAEL 
This is virtual server - 10 x 2,4 GHz vCPU, RAM 8192 Мb
I tried both TCP and UDP, and it's TCP now.

Regards

**Comment by vikman90** [comment]
Hi @kir-b and @TJOSERAFAEL ,

The file change detection procedure for FIM may become inefficient if the
databases get too big. That's because Syscheck keeps the historical data
and never deletes old change marks —although it never uses it—.

Could you please take a look at your FIM databases?

- `wc -l /var/ossec/queue/syscheck/*` gets the total number of FIM entries in
your system.
- `grep "^#" /var/ossec/queue/syscheck/* | wc -l` will get the number of
useless historical entries.

If the second number is significative, we could have performance issues. We
are working on moving the FIM databases to a more efficient and
historical-less format.

In the meantime I recommend you to wipe the Syscheck databases:
```sh
# Stop manager
  systemctl stop wazuh-manager
# Clean databases  sed -i'' "/^#/d"
/var/ossec/queue/syscheck/*
# Start manager
  systemctl start wazuh-manager
```

Hope it help.
Best regards.

**Comment by kir-b** [comment]
Hi all,
The total number of  FIM entries is 20 480 448. Number of historical entries was 1 658 514.
I wiped the Syscheck databases. But unfortunately cpu usage still 100%.
Best regards.

**Comment by doubledeee** [comment]
I've had this issue as well.  My only negative I have seen with clearing the syscheck database is if any folders/files are being monitored for FIM with new files being detected, after clearing the database all of the files are detected as new - which causes the database to fill up again.  Essentially, what I've seen is the initial syscheck happens on all of the agents and reports every file as new because it doesn't have a baseline.  Is that expected functionality?

+1000 for implementing multi-threading.

**Comment by vikman90** [comment]
Hi all,

Totally agree. In fact, we are working on this just now. Actually, there are two issues:

1. Remoted and Analysisd are single-thread processes. This makes them use 100% of CPU without taking advantage of multi-core systems.

2. FIM databases are text-based. Each registry update requires a linear search, marking the old item as invalid and write the new item at the end of the file. Write operations are very fast but read operations are linear, so a complete agent scan has a performance of _O(n²)_. Multithreading helps here but does not solve the problem, we need to reduce an order of magnitude.

So, we have three tasks in the roadmap:

1. Parallelize Remote daemon (https://github.com/wazuh/wazuh/issues/501). 
2. Parallelize Analysis daemon.
3. Move the FIM databases to an SQLite format. We are working on this with the `wazuh-db` daemon. It supports parallel queries (one per agent). Item search is faster: _O(log(n))_. Write operations are amortized by a cache: Analysis daemon requests a change and continues working. This is working now for Syscollector events, we're debugging and optimizing `wazuh-db` and will use it for FIM very soon. Hopefully, this will help with FIM data performance.

Best regards.
