### ISSUE TITLE
Syscheck option <scan_time> doesn't work properly when set to 12am or 12pm

### ISSUE THREAD

**Issue by sergiospa** [wazuh/wazuh#5610]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.1-31309 | Syscheck| Manager/Agent | Packages | Ubuntu 19.10|

Hi team,

There's an issue with the option `<scan_time>` of syscheck:
- When this option is set to `12am` (which translates to `00:00`) the syscheck scan is performed at `12:00` instead (noon).
- When it's set to `12pm` (which translates to `12:00` (noon)) the scan is never performed.

**Steps to replicate:**
1. Open the local configuration file `ossec.conf` in your Wazuh manager of Wazuh agent.
2. In the `syscheck` configuration, disable `<scan_on_start>` and set `<scan_time>` to `12am`:
```xml
    <scan_on_start>no</scan_on_start>
    <scan_time>12am</scan_time>
```
3. Restart the service to apply changes.
4. Change the system's time to something close to 12:00:00. You can use `timedatectl`: `timedatectl set-time '2020-07-31 23:59:00'`
5. Monitor `ossec.log`. You should be able to see that the syscheck scan starts at 12pm.
6. Repeat step 2, 3, 4 and 5 but setting `<scan_time>12pm</scan_time>` this time. You should see that the syscheck scan is not performed at 12am or 12pm.

Debug logs did not provide further information.

Let me know if you have any questions.

Regards,
Sergio.

**Comment by Molter73** [comment]
This seems to be an error on how the `12am` and `12pm` configurations are interpreted by the function [__gettime](https://github.com/wazuh/wazuh/blob/e3b905ace2faf9af54989e1afb35f9599e5cb19a/src/shared/validate_op.c#L478). `12am` is directly translated to `12:00` which is actually noon in 24 hours format and `12pm` gets translated to `24:00` which is not a valid time, causing the following log messages to appear:

```
2020/07/31 12:01:59 ossec-syscheckd: ERROR: (1240): Invalid time format: 'm-12pm'.
2020/07/31 12:04:56 ossec-syscheckd: ERROR: (1235): Invalid value for element 'scan_time': 12pm.
2020/07/31 12:04:56 ossec-syscheckd: ERROR: (1202): Configuration error at '/var/ossec/etc/ossec.conf'.
2020/07/31 12:04:56 ossec-syscheckd: ERROR: (1207): syscheck remote configuration in '/var/ossec/etc/ossec.conf' is corrupted.
```

Analysisd also uses this function, so extra care must be taken when fixing this issue in order to not break functionality in this module.
