### ISSUE TITLE
Filter option in <localfile> to exclude regex matches of log lines

### ISSUE THREAD

**Issue by 1stOfHisGame** [wazuh/wazuh#5628]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12.3 | logcollector | Agent | Packages/Sources | Linux |

It would be good to have an option in `<localfile>` of `ossec.conf` to exclude certain log lines from being pushed to the manager from host machines.

One use case that I have right now is around `audit.log` file. In case SELinux on the host machine is in permissive mode, which writes a lot of redundant warning messages, logcollector should exclude log lines that match a certain regex pattern.

**Comment by chemamartinez** [comment]
Hi @1stOfHisGame,

The use case you propose sounds fair. Actually, a similar feature is available for other components such as FIM (https://documentation.wazuh.com/3.13/user-manual/reference/ossec-conf/syscheck.html#ignore), so we will study to include it in the product roadmap.

Until the Logcollector is able to exclude undesired logs, I suggest you as a workaround to create custom rules to ignore them when they are analyzed in the manager. To achieve it, let's suppose you want to ignore this event related to configuration changes:

```
type=CONFIG_CHANGE msg=audit(1368831799.081:466947): auid=4294967295 ses=4294967295 op="remove rule" path="/path/to/my/bin0" key=(null) list=4 res=1
```

We can use the tool [ossec-logtest](https://documentation.wazuh.com/3.13/user-manual/reference/tools/ossec-logtest.html) to see if that particular event fires any alert.

```
# /var/ossec/bin/ossec-logtest
2020/08/05 04:06:56 ossec-testrule: INFO: Started (pid: 20046).
ossec-testrule: Type one log per line.

type=CONFIG_CHANGE msg=audit(1368831799.081:466947): auid=4294967295 ses=4294967295 op="remove rule" path="/path/to/my/bin0" key=(null) list=4 res=1


**Phase 1: Completed pre-decoding.
       full event: 'type=CONFIG_CHANGE msg=audit(1368831799.081:466947): auid=4294967295 ses=4294967295 op="remove rule" path="/path/to/my/bin0" key=(null) list=4 res=1'
       timestamp: '(null)'
       hostname: 'ubuntu'
       program_name: '(null)'
       log: 'type=CONFIG_CHANGE msg=audit(1368831799.081:466947): auid=4294967295 ses=4294967295 op="remove rule" path="/path/to/my/bin0" key=(null) list=4 res=1'

**Phase 2: Completed decoding.
       decoder: 'auditd'
       audit.type: 'CONFIG_CHANGE'
       audit.id: '466947'
       audit.auid: '4294967295'
       audit.session: '4294967295'
       audit.op: 'remove rule'
       audit.key: 'null'
       audit.list: '4'
       audit.res: '1'

**Phase 3: Completed filtering (rules).
       Rule id: '80705'
       Level: '3'
       Description: 'Auditd: Configuration changed'
**Alert to be generated.
```
 
We see the default rule 80705 is matching that event. The rule is located in the file `0365-auditd_rules.xml` of the ruleset and looks like:

```xml
<rule id="80705" level="3">
      <if_sid>80700</if_sid>
      <field name="audit.type">CONFIG_CHANGE|DAEMON_CONFIG</field>
      <description>Auditd: Configuration changed</description>
      <group>audit_configuration,gpg13_10.1,gdpr_IV_30.1.g,</group>
</rule>
```

Here you have two options, you can overwrite that rule or create a new one to silence it:

### Overwriting rule 80705

1. Go to the local rules directory (`/var/ossec/etc/rules` by default) and create a new file for your custom audit rules:

```
# touch /var/ossec/etc/rules/local_audit_rules.xml
```

2. Overwrite rule 80705 by adding the following content to the created file:

```xml
<!-- Local audit rules -->

<group name="local,audit,">

  <rule id="80705" level="0" overwrite="yes">
      <if_sid>80700</if_sid>
      <field name="audit.type">CONFIG_CHANGE|DAEMON_CONFIG</field>
      <description>Auditd: Configuration changed</description>
      <group>audit_configuration,gpg13_10.1,gdpr_IV_30.1.g,</group>
  </rule>

</group>
```

We have already overwritten the rule changing its level to 0 (zero level alerts are not logged).

### Creating a new rule to silence the event

1. Go to the local rules directory (`/var/ossec/etc/rules` by default) and create a new file for your custom audit rules:

```
# touch /var/ossec/etc/rules/local_audit_rules.xml
```

2. Create a child rule of 80705 with level 0:

```xml
<!-- Local audit rules -->

<group name="local,audit,">

  <rule id="100001" level="0">
      <if_sid>80705</if_sid>
      <description>Auditd: Configuration changed (Silenced)</description>
      <group>audit_configuration,gpg13_10.1,gdpr_IV_30.1.g,</group>
  </rule>

</group>
```

**Remember to add new rules in the local rules directory instead of tuning the default ruleset. That way, changes will persist across upgrades.**

**Comment by 1stOfHisGame** [comment]
Thanks for tagging this as an enhancement @chemamartinez.

I already implemented the workaround to silence the alerts. Just wanted to raise the issue of logcollector because silencing only the alerts would still not prevent those events from being transferred from host to manager.

**Comment by ptrsimon** [comment]
Hi @chemamartinez, just wanted to up this issue because we have a similar use case. Frequent cronjobs and healtchecks generate lots of log entries which we do not want to forward from the agents. At a scale of multiple thousand hosts the load caused by this becomes noticable.

The ability to create regex / syslog program name filters in the localfile configuration would improve scalability a lot and would help reduce network load. It would also decrease the load on the agent queue so it would be less likely to drop critical events.

**Comment by dariommr** [comment]
Hello Guys,
I think this is a critical feature since it can prevent flooding the manager with unuseful logs, in the same way as the event_channel queries works.
Here are other issues asking for the same:
- https://github.com/wazuh/wazuh/issues/11798
- https://github.com/wazuh/wazuh/issues/169

**Comment by hitman28594** [comment]
There are some features proposed in #13635  which could also be applied at logcollector however I think this exclude option should also be possible at the remoted layer because currently this is also a problem when receiving logs via syslog not only logcollector/localfile. 

https://github.com/wazuh/wazuh/issues/13635

Other additions to localfile:
- Add metadata (labels only work for json logs)

**Comment by hitman28594** [comment]
Hello Team,

There is also the requirement to have an “include” option aswell as an “exclude” option. 

Exclude = ignore lines matching the regex pattern (use cases already described above)


Include = Only include lines matching the regex pattern. 
—- example use case: monitoring Wazuh-modulesd logs from ossec.log.

Wazuh components can be put into debug mode and generate HUGE amounts of logs. Having an “include” feature would allow us to only collect logs for a specific program or component without overloading the manager with unwanted logs.

**Comment by jotacarma90** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core---Watchdogs-6039126e30fb7400140030e7/issues/wazuh/wazuh/5628?planning-poker) with ZenHub @antoniomanuelfr @FrancoRivero @MarcelKemp
