### ISSUE TITLE
Python not Available by Default on Ubuntu 20.04

### ISSUE THREAD

**Issue by chalbersma** [wazuh/wazuh#5656]
https://github.com/wazuh/wazuh/blob/ff962364251c1fa38468bc750c8431ced9254b84/wodles/docker-listener/DockerListener.py#L1

Sorry for the lack of stuff. You can install python2 on Ubuntu 20.04 to make this work. But by default python2 isn't available on 20.04. This might be a bigger thing, testing all the python stuff with python3.8+ but I think this will go a long way given that 20.04 is the first LTS without python2.

**Comment by davidjiglesias** [comment]
Hello @chalbersma,

You are absolutely right. We are using embedded python3 from a long time in Wazuh, and we have bumped it to python 3.8 in wazuh version 3.13.0. https://github.com/wazuh/wazuh/pull/5150.

 However, we have to ensure that all our python code is supported and tested using python3 instead of python2. It is included in our roadmap and we will be taking care of this. 

Thank you for pointing it out!

**Comment by chalbersma** [comment]
No worries. I'll update to 3.13 (I think I was testing with 3.12.something. Thanks for the info!

**Comment by mattvw** [comment]
To add, this is an issue for RHEL/CentOS 8 as well that I brought up back in April in #4879. I mentioned that this was also an issue in Ubuntu 20.04 after that was released at https://github.com/wazuh/wazuh/issues/4879#issuecomment-635336269. RHEL/CentOS 8 was also the first major version to not provide Python2 by default (and will only support Python2 until 2024).

Regardless of the embedded Python in the Wazuh Manager install, this remains an issue for Wazuh agents (which is mostly what my issue is about now).

Also an issue is that there is no un-versioned 'python' binary by default in both RHEL 8 and Ubuntu 20, which makes various scripts (including DockerListener) fail in default OS installs (again, mostly for agent installs) since they specify just 'python' instead of 'python2' or 'python3'.

Don't know if this is a duplicate issue though since my issue was originally specifically for RHEL/CentOS 8, but I also want Ubuntu 20.04 LTS agents to work too without having to install Python 2 (which is EOL).

Thought I'd mention it here regardless, as they are at least related issues.

**Comment by chalbersma** [comment]
> Don't know if this is a duplicate issue though since my issue was originally specifically for RHEL/CentOS 8, but I also want Ubuntu 20.04 LTS agents to work too without having to install Python 2 (which is EOL).

I've got a workaround for that. If you use the latest version (that expects python3) on Ubuntu and install the `python-is-python3` package the agent "just works". That package does what you'd expect it to, namely it uses alternatives to set `python` => `python3`.
