### ISSUE TITLE
Slack alerts

### ISSUE THREAD

**Issue by onelife9** [wazuh/wazuh#5713]
Hi. I have a question. Is there a way to limit slack alerts if the same IP keeps doing the same action? I have a dozen or so servers and I wonder how to do it to make it transparent on the slack channel. For example, to have him send a message only once.

**Comment by antoniomanuelfr** [comment]
Hi @onelife9 
There is not a specific way to do that, there are some workaround like using `frequency` option in order to create a custom alert that triggers when a certain rule had been triggered a number of times and the `<not_same_source_ip />` option. Then use the slack only when your custom rule is triggered. 
The rule should look something like 

```xml
<rule id="100002" level="5" frequency="3">
        <if_matched_sid>550</if_matched_sid>
        <not_same_source_ip />
    <field name="file">.test$</field>
    <description>test file modified</description>
</rule>

```

You can find more information in the docs: 
- https://documentation.wazuh.com/3.13/user-manual/ruleset/ruleset-xml-syntax/rules.html
- https://documentation.wazuh.com/3.13/user-manual/ruleset/ruleset-xml-syntax/rules.html#rule

If you have any question don't hesitate to ask.
Kind regards. 
Antonio

**Comment by antoniomanuelfr** [comment]
Hi @onelife9. I'm going to close this issue. If you have any doubts don't hesitate to contact us. You can re-open this issue or contact us using the mailing list or the slack channel: https://wazuh.com/community/

Kind regards.
Antonio.
