### ISSUE TITLE
Can't monitor Windows directories

### ISSUE THREAD

**Issue by Pakerito** [wazuh/wazuh#5752]
Wazuh 3.13.1

Hello, I am trying to monitor Windows directories but after following every single tutorials I saw, nothing works, my syntax is the following, even though i tried many more : 

```xml
<directories check_all="yes" whodata="yes">C:\</directories>
```
It works perfectly for my linux agents, i can't figure out what the problem is.

**Comment by antoniomanuelfr** [comment]
Hi @Pakerito 

To monitor a directory in a Windows agent you have to follow the next steps:
- Be sure that wazuh is stopped (you can check it in the UI).  
- Open the file located in `C:\Program Files (x86)\ossec-agent\ossec.conf`
- Inside the `<syscheck>` section, add the `<directories>monitored_folder</directories>` option.
- Re-start wazuh by using the UI. 
- Generate an alert by modifying, creating, or deleting a file inside the folder. You can check it by looking at the file `/var/ossec/logs/alerts/alerts.log` (only in the manager).
 
It's not recommended to monitor `C:\` using whodata, because that may lead to instability in components like Windows Event Viewer (because of the number of files that are inside `C:\`). If you want to monitor `C:\` you should use the `scheduled` option instead. Keep in mind that the scan may take a long time, depending on the number of files that you are monitoring, and the number of files inside `C:\` is huge. 

My recommendation is to use Whodata only in folders that are critical for your system.

Another recommendation is that you use the code block when sharing configuration using the GitHub comments. You can have a look at this link to find more information: https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

If you have any doubts don't hesitate to contact us. You can also use our slack channel and the mailing list: https://wazuh.com/community/

Kind regards.

**Comment by Pakerito** [comment]
Hello @antoniomanuelfr 

It works now, I have to precise a directory inside C:\ and not just C:\, thanks for your help !
