### ISSUE TITLE
Audit rules are not being removed after symbolic link changes its target

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh#5761]
|Wazuh version|Branch|Component|Install type|Install method|Platform|
|---|---|---|---|---|---|
| 4.0.0 | develop | ossec-syscheck | Manager/Agent | Packages/Sources | Linux |

## Description

Using symbolic links, when changing its target with _whodata_ enabled, _audit_ rules are not being removed from the previously monitored file and FIM tries to scan not monitored files.

## Example
When changing the target from `/file_3` to `/test/file_1`, the link is updated correctly in FIM:
```
2020/08/18 12:14:11 ossec-syscheckd[102138] run_check.c:557 at symlink_checker_thread(): INFO: (6034): Updating the symbolic link from '/file_3': '/test/linko' to '/test/file_1'.
```

However, after waiting for _audit_ rules to reload, this message appears in the log:
```
2020/08/18 12:16:41 ossec-syscheckd[102138] syscheck_audit.c:1120 at audit_reload_rules(): DEBUG: (6275): Reloading Audit rules.
2020/08/18 12:16:41 ossec-syscheckd[102138] audit_op.c:74 at audit_print_reply(): DEBUG: Audit rule loaded: -w /file_3 -p wa -k wazuh_fim
2020/08/18 12:16:41 ossec-syscheckd[102138] audit_op.c:74 at audit_print_reply(): DEBUG: Audit rule loaded: -w /test/file_1 -p wa -k wazuh_fim
2020/08/18 12:16:41 ossec-syscheckd[102138] syscheck_audit.c:1122 at audit_reload_rules(): DEBUG: (6276): Audit rules reloaded. Rules loaded: 1
```

According to this message, both `/file_3` and `/test/file_1` have `audit` rules, but only `/test/file_1` should have rules as it is the file pointed to by the symbolic link.

This messages are written in the log every time the _audit_ rules are reloaded. Because the rule is not removed for `/file_3`, this kind of message will appear in the log:
```
2020/08/18 12:18:22 ossec-syscheckd[102138] create_db.c:668 at fim_configuration_directory(): DEBUG: (6319): No configuration found for (file):'/file_3'
```

The `No configuration found...` message is appearing also when monitoring a link using _realtime_, so the same issue affecting the _audit_ rules may be affecting the _inotify_ watches.

**Comment by antoniomanuelfr** [comment]
Hi team! 
I have been investigating this issue and right now, this is the trace of how it's working now:

 - Once the audit health_check is executed, a new rule is created in `audit_added_rules`  for the directory that the link is pointing  (syscheck_audit.c_231)
 - When an event is triggered in the directory, `audit_parse` gets the event and extracts the fields that will be used in the alert.
 - After modifying the target of the link, `fim_link_update` is called and the new path is saved in `syscheck.symbolic_links[pos]` (pos is the position of the link in the array)
 - After that, the new path is monitored and the rules are reloaded using the real path of each configured path. (syscheck_audit.c:212)
   -  If the real path is not found by `search_audit_rule` in the vector `_audit_rules_list`, a new rule is added (using W_Vector_insert_unique).
   - If it's find, it tries to insert a new rule in `audit_added_rules` (using `W_Vector_insert_unique`)


These are some debug messages that are generated after reproducing this issue:
```
2020/12/10 12:06:44 ossec-syscheckd[3621] syscheck_audit.c:1128 at audit_reload_rules(): DEBUG: (6275): Reloading Audit rules.
2020/12/10 12:06:44 ossec-syscheckd[3621] audit_op.c:74 at audit_print_reply(): DEBUG: Audit rule loaded: -w /test -p wa -k wazuh_fim
2020/12/10 12:06:44 ossec-syscheckd[3621] audit_op.c:74 at audit_print_reply(): DEBUG: Audit rule loaded: -w /test_2 -p wa -k wazuh_fim
2020/12/10 12:06:44 ossec-syscheckd[3621] syscheck_audit.c:1130 at audit_reload_rules(): DEBUG: (6276): Audit rules reloaded. Rules loaded: 1
```

It's clear that if the link's target is changed, the rule of the previous target is not removed because it only takes into count the real paths that are monitored.

One option can be to clear the vectors where the audit rules are saved and insert them again using the updated information. That can be inefficient.

Another option is to remove the rule from the vector when the symlink is updated. This option is a bit riskier and it may need some changes in the code.

Kind regards

**Comment by Molter73** [comment]
I believe our safest option is to tweek [audit_reload_rules](https://github.com/wazuh/wazuh/blob/79e4d3fd09b28c65fb7990148821b47742d867c4/src/syscheckd/syscheck_audit.c#L1127), we could add a call to a second function that checks the existing rules against the configuration and removes any entries that correspond to a directory with no configuration (due to a symbolic link change), or an inexistent directory if the deleted event was lost for some reason.

**Comment by Molter73** [comment]
We should also add an integration test that checks that once the symbolic link has been updated and the audit rules reloaded, no events are received from them.

**Comment by antoniomanuelfr** [comment]
Working branch [5761-audit-rules-not-removed-after-symlink-update](https://github.com/wazuh/wazuh/tree/5761-audit-rules-not-removed-after-symlink-update)
