### ISSUE TITLE
integration not working for alerts on the manager server

### ISSUE THREAD

**Issue by emailbob** [wazuh/wazuh#58]
To reproduce I have a slack integration setup with a rule_id set to 5710 (Attempt to login using a non-existent user). When I try to log into my other agents with a non-existent user the integration triggers correctly.  When I try to log into the OSSEC manager server with a non-existent user the integration does not get triggered.
 
Looking at /var/ossec/logs/alerts/alerts.json I do see the alert for the login attempt on the manager server and it also shows up in Kibana so I know it is logging correctly.

**Comment by vikman90** [comment]
Hi @emailbob,

sorry for the late response. We did some tests and  we're receiving rule 5710 alerts from both manager and agent. In theory, there should not be differences between alerts from manager and agent referring to configuration. This is our tested configuration:

```
<integration>
  <name>slack</name>
  <rule_id>5710</rule_id>
  <hook_url>https://hooks.slack.com/services/BD42T3A9/G6ABnHB3F7V4/wafDP3ZBaFsHuywLvmE</hook_url>
</integration>
```

The Slack integration doesn't read `alerts.json` but `alerts.log`. Please produce an alert at the manager and another on an agent, and look for any strange difference, or copy one of each here for us to test this issue more deeply.

Best regards.

**Comment by emailbob** [comment]
Here are the alerts for an agent (vault11) and manager (ossec) from alerts.log

`Dec 29 17:05:45 vault11 sshd[31480]: Invalid user bobtest from 10.x.x.x
Dec 29 17:05:56 vault11 sshd[31480]: Failed password for invalid user bobtest from 10.x.x.x port 51710 ssh2
Dec 29 17:06:13 ossec sshd[21085]: Invalid user bobtest from 10.x.x.x
Dec 29 17:06:24 ossec sshd[21085]: Failed password for invalid user bobtest from 10.x.x.x port 51720 ssh2`

The agent alert showed up in slack for me but the manager did not.

**Comment by vikman90** [comment]
Hi,

we repeated your steps again but have no problems. Please let me know whether the complete alert has this form:

> ** Alert 1483109410.209010: - syslog,sshd,invalid_login,authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,pci_dss_10.6.1,
> 2016 Dec 30 15:50:10 ubuntu->/var/log/auth.log
> Rule: 5710 (level 5) -> 'sshd: Attempt to login using a non-existent user'
> Src IP: ::1
> Dec 30 15:50:09 ubuntu sshd[11678]: Failed password for invalid user evil from ::1 port 42648 ssh2

Does the file `/var/ossec/logs/integrations.log` say anything interesting?

We created a branch: https://github.com/wazuh/wazuh/tree/debug-integrator, for debug purposes. You may want to use it in order to have more logs.

To increase by one step the debug level, just call:

> `/var/ossec/bin/ossec-control enable debug`

If you do this twice you will enable level 2 debugging. Many debugging messages should appear at `/var/ossec/logs/ossec.log`.

Please write us back if you could get some more information. In the meantime we'll continue doing some tests.

Thank you again.
