### ISSUE TITLE
Wazuh on windows - Maximum size permitted. 

### ISSUE THREAD

**Issue by farhanorderlogix** [wazuh/wazuh#580]
Hi,

Can anyone help with the real time monitoring issue, Is there a registry setting in windows. I am on windows server 2012 R2 with wazuh agent 2.0. 

2018/04/27 18:00:23 ossec-syscheckd: ERROR: Unable to add directory to real time monitoring: 'C:\inetpub\wwwroot\host1' - Maximum size permitted.

This guy here explained how to fix it for Linux,

https://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached

Is there a work around for Windows?

It would be great if I could find solution to this issue.

**Comment by vikman90** [comment]
Hi @farhanorderlogix,

The Windows agent has historically a limit of 256 directories —and subfolders— monitored in real-time.

This condition was already issued (https://github.com/wazuh/wazuh/issues/530) and fixed (https://github.com/wazuh/wazuh/pull/540) in the _master_ branch. It will be available in the next minor release.

Best regards.

**Comment by farhanorderlogix** [comment]
When is next minor release coming out. Is there a timeline.

**Comment by vikman90** [comment]
We don't have a release date yet. We are finalizing the release of 3.2.2, I hope 3.3.0 is released in a couple of months.

Regards.

**Comment by farhanorderlogix** [comment]
Can i still get alert of file modification / checksum changes? If yes what is the configuration on agent / server i need?

  <directories check_all="yes">D:\apps\</directories>

**Comment by farhanorderlogix** [comment]
.........<directories check_all="yes">D:\apps</directories>.......

**Comment by bah07** [comment]
Hi @farhanorderlogix,

With the `check_all` option all the `check_*` options are used together. In the following link to our documentation you have all options that can be configured in the label directories.

https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html?highlight=syscheck#directories

To get alerts about modifications you could use the `check_sum` option to check MD5 and SHA-1 or select one of them with `check_md5sum` or `check_sha1sum`

For example:

```
<directories check_all="no" check_sum="yes">C:\folderA</directories>
<directories check_all="no" check_md5sum="yes" check_perm="yes" check_size="yes">C:\folderB</directories>
```

Hope its help.
Best regards.

**Comment by ckozler** [comment]
Hi there - I have a quick question relative to this. What is the point in hard limiting it to a certain size? I understand it could be a performance impact or something but why *wouldnt* you let users configure something to their preference for their OS? Unless Windows already does not allow > 1024 handles? Just trying to understand why we cant decide this configuration > 1024? Thanks!

**Comment by bah07** [comment]
Hello @ckozler 

In windows, when a directory is configured, all its contents are monitored, this recursiveness is managed by the operating system itself. The configuration of 1024 does not refer to handlers, but to directories configured in `ossec.conf` for monitoring. 
That is, in windows, up to 1024 labels can be configured:

>  \<directories check_all="yes" realtime="yes">folder\</directories>

This limit comes because we believe that the possibility of configuring 1024 directories is more than enough and depending on the content of these directories this could cause performance problems. 

By adding the option `realtime="yes"`` you should value not only the amount of files that exist but also the frequency with which they are modified.

I hope I've answered all your questions. If not, please do not hesitate to write again.
Regards.

**Comment by ckozler** [comment]
Hi @bah07 - thank you for getting back to me

I do agree that consideration should be given but I think we should be *able* to configure what we want for this since it would directly impact our systems should it actually be a problem, no? The hard limit of 1024 is still a bit of a small cap I believe:

An example here is I am required to monitor C:\Windows\System32 in real time however on my Windows systems this folder already contains 1210 directories out of the box and I have no way to say what to exclude from the system32 real time monitoring nor do I really want to exclude stuff. To expand, if I exclude c:\windows\system32\drivers\etc because I know this is a default folder, what happens if some malware writes to it? I've now missed that action until the full system scan runs

Is there a limitation from within ossec/wazuh agent or is it on windows? Or is there actually no limitation and its more of a precaution / suggestion by the developers? If the latter, I dont see the harm in removing this limit and, for instance, on a user configuring > 1024 you can log a warning or something similar. What do you think?

**Comment by bah07** [comment]
Hi again @ckozler 

I think we misunderstood each other. If you configure the directory `C:\Windows\System32` will count as one.  There will still be 1023 more directories you can monitor.

Regards.

**Comment by ckozler** [comment]
Hmm...perhaps I missed something obvious then? Using this configuration today https://pastebin.com/3wmSJU2z yields the following log messages https://pastebin.com/tZwJL3Rz 

Now I realize I am running old version that does not have this feature but it appears I am already being limited. My understanding is that yes C:\windows\system32 is one element but its recursive so that:

- C:\windows\system32
-- \drivers
--- \etc
-- Logs

Would be a total of 4 elements
1. c:\window\system32
2. c:\window\system32\drivers
3. c:\window\system32\drivers\etc
4. c:\window\system32\Logs

No? In either case, having real time monitoring in C:\windows\system32 with the above config, nothing gets added because of this max size permitted

**Comment by bah07** [comment]
Okay, fine. I understand you're testing version 3.3. 

What happens is that this fix has not entered version 3.3, it is ready for version 3.4.

To know for sure if a new or fixed feature is in a version, you can check the `CHANGELOG.md` file.

If you want to test this feature it is available in the master branch.
I'm sorry if this has caused any inconvenience.
Regards.

**Comment by ckozler** [comment]
@bah07 sorry for the confusion...I realize that I do not have the latest version which raises the limit to 1024 however, there is currently a hard limit of 256. In either case though trying to monitoring C:\windows\system32 recursively with realtime configuration will not work even with the new feature simply because there is 1200 entries in the system32 folder. Did I misunderstand something?

**Comment by bah07** [comment]
Hi @ckozler.

Version 3.4 was released a few days ago, now you can probe this options.
```
syscheck.max_fd_win_rt  Maximum numbers of directories can be configured in ossec.conf for 
windows in realtime and whodata mode.  New in version 3.4.0.

Default value | 256
Allowed value | Any integer between 1 and 1024
```
