### ISSUE TITLE
Modify registry scan algorithm

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh#5864]
| Wazuh version | Component       | Install type | Install method   | Platform |
|---------------|-----------------|--------------|------------------|----------|
| 4.0.0         | ossec-syscheckd | Agent        | Packages/Sources | Windows  |

## Description

We need to modify the algorithm in charge of scanning Windows registries in order to generate events when a `value` inside a `registry key` is modified. Every single modified `value` should send an alert.

This new algorithm should also check and send an alert if a `subkey` is deleted.

**Comment by jesusjimsa** [comment]
The algorithm must scan all subfolders in a `registry key` to be able to scan the values inside them.
Also, when saving the entries in the database, it should escape the necessary characters before concatenating the `value` to the `registry key`.

**Comment by Molter73** [comment]
Some of the first steps that will be taken in order to complete this issue:
 - [ ] Cleanup existing code.
 - [ ] In order to improve performance of the current algorithm, we will move the recursive call up into the routine responsible for scanning subkeys into the same function that opens subkeys.
 - [ ] Create a function that checks if a given event is to be send by applying ignore/restrict/recursion_level and any other constraint that might be required.
 - [ ] Send alerts for each key and each value that has been added/deleted/modified and complies with the constraints checked by the function in the previous point.
 - [ ] Rename functions in order to better fit with existing fim functions.

**Comment by Molter73** [comment]
With the new directory structure I've renamed and splitted `win-registry.c` into the following files:
- `registry/registry.c`: Contains all of the required logic for scanning the registry and generate event for added, modified and deleted entries, both keys and values.
- `registry/registry.h`: Holds the prototypes of public functions to be used from outside the `registry` subdirectory.
- `registry/events.c`: Has all the functions required for generating json registry events.

I might add some other files as development goes on.

**Comment by Molter73** [comment]
Basic implementation of the new algorithm for scanning the registry and generating alerts is already in place, even if many function calls are only placeholders at the moment and won't compile as a result.

I've also added a couple of callback functions which process deleted entries following the logic described in this diagram:

![FIM registry delete](https://user-images.githubusercontent.com/20206636/92587278-b9d5c700-f297-11ea-8356-8bedaa0c35d5.png)
