### ISSUE TITLE
Agent status improvement analysis

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#5886]
### Description

As part of the [Epic 5887](https://github.com/wazuh/wazuh/issues/5887) we would like to have a deep understanding of all the components involved. The main goal of this issue is to analyze and determine all the parts of the Wazuh code that should be modified to meet the requirements specified in the Epic description.

### Definition of done

- [ ] Generate a list of all the places where an agent status is used.
- [ ] Determine the parts of the code that involves a TCP connection between the agents and the manager.
- [ ] Analyze the parts of the code involved in the generation of an alert when the agents get disconnected.

**Comment by pereyra-m** [comment]
### Analysis results

After exploring the Wazuh source code, it was determined that **remoted** already has knowledge about the current TCP active connections, so the analysis and PoC (proof of concept) presented is focused on the organization, storage and communication of that information.

#### Places where the agent status is used 

The following functions are called by Wazuh Core. Other modules, like the API or **clusterd** perform their requests to Wazuh DB to get agent's status, and it should be the only source of this information. All of them, consider the time passed since the last keepalive:

- **get_agent_status()**: _/src/shared/read-agents.c_
    Called in _agent_control.c_ and _validate.c_

- **wdb_get_agents_by_keepalive()**:  _/src/wazuh_db/wdb_agent.c_ 
    Called in _read_agents.c_ and _wm_vuln_detector.c_

#### TCP connection between the manager and the agents

The **remoted** daemon always knows how many active TCP connections exist at any time, because it stores this information in the _remoted_state.tcp_sessions_ variable. The functions **rem_inc_tcp()** and **rem_dec_tcp()** keep it updated, and its value is printed in the _ossec-remoted.state_ statistical file.

The **HandleSecureMessage()** function in _/src/remoted/secure.c_ decrypts the control message from the agent, and if the protocol used is TCP, the keystore global struct is updated. The _keyhash_sock_ hash table is updated with a new node (ID/socket number) in **OS_AddSocket()**, and then updated again in  **OS_DeleteSocket()** (inside **_close_sock()**) after the connection closes.

##### **rem_inc_tcp()**
This functions is called inside **HandleSecure()** in _/src/remoted/secure.c_. Then a debug message is printed, like "New TCP connection at SOURCE_IP [PEER]"

##### **rem_dec_tcp()**
This functions is called inside **_close_sock()** in _/src/remoted/secure.c_. Then a debug message is printed, like "TCP peer disconnected [SOCK]"

#### Agent disconnected alert

The **monitord** daemon checks the status of all agents in **monitor_agents()** (_/src/monitord/monitor_agents.c_) and if the condition of one of them changed, sends a disconnected message.

### Design proposal

There are basically two different options considered. Each one of them has its own characteristics, advantages and disadvantages.

#### Creating a communication channel with remoted

This daemon has all the required information, so it can provide it to any client that requests it. But we consider that this option unnecessary overloads this Wazuh module, and that this is not its main function to handle multiple and heavy data requests. It could also be difficult to synchronize all the workers information in a cluster scenario.

#### Storing all the information in Wazuh DB

This daemon already centralizes all the information of the agents, handles multiple requests and has synchronization methods between the workers and the master. But in this case, **remoted** should periodically send the TCP connection status of the agents. It could be done with a "heartbeat" thread, or simply every time there is a change in the _remoted_state.tcp_sessions_ variable.

There are many design questions to answer and define in this implementation, some of them are:

- Should Wazuh DB store this information in the **global.db** database? The agent status isn't persistent information in fact, and a new column could involve more logic (setting initial state, updating at manager's start and close). The information about the TCP connection may be stored in memory, like a hash table. 
- Should the status of the agent be a combination of the TCP socket and last keepalive? Is it necessary to calculate the status of all agents all the time (every 10 seconds for example) or only at request?
- In the case of a cluster, all the **clusted** daemons are going to report the **remoted** information with the last keepalive information? Will they wait until a distributed request?

Both PoC were implemented under this Wazuh DB scenario.

### PoC

These are the main points of this implementation. In both cases, a periodic query to Wazuh DB was executed to check the results. The TCP connection and disconnection impacted almost instantly in both cases.

#### New column in Wazuh DB

Inside **remoted**:
- After calling **OS_AddSocket()** in **HandleSecureMessage()**, the keystore struct is scanned and all the ID/sock pairs are sent to Wazuh DB
- After calling **OS_DeleteSocket()** in **\_close\_sock()**, the keystore information is sent again

Here, all the elements are sent and written every time. Only the difference may be sent instead.
The information sent to Wazuh DB from **remoted** is in JSON format.

Inside **wazuh-db**:
- A new column _active_TCP_  is created
- A method like **wdb_update_TCP_connections(cJSON)** is necessary. Also, the Wazuh DB parser was modified to receive the new "global update-TCP %s" command
- The method writes 1 or -1 in the new column, considering if there is a valid socket or not for that agent

#### Wazuh DB hash table

In the second test, the information about the TCP connections was saved in memory.
All the agents were stored regardless of its state, but a variant could be considered to only save the active ones. This would allow small messages between daemons, an ID list instead of ID/sock pairs.

The changes in **remoted** were basically the same than before.

Inside **wazuh-db**:
- A new **agent_status** hash table was created
- A mutex logic was implemented to avoid data corruption in every read/write
- There are two new methods, **wdb_update_TCP_connections()** and **wdb_get_TCP()** to write and read the hash table
- Every time **wdb_global_delete_agent()** is called, that agent is removed from the hash table
- The parser was modified to receive the "global get-TCP" and "global update-TCP %s" commands
- The method writes 1 or 0, considering if there is a valid socket or not for that agent

### Conclusion

There are many aspects of the design to consider, review and improve; but this small proof of concept showed the viability of the implementation.
