### ISSUE TITLE
Problem when upgrading wazuh-manager from 3.12.3 to 3.13.1

### ISSUE THREAD

**Issue by nothinux** [wazuh/wazuh#5946]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12.3 | All | Manager | Packages | Ubuntu 18.04 |

### Description
Got an error when trying to upgrade wazuh manager from version 3.12.3 to 3.13.0, and got the same error when upgrading from version 3.12.3 to 3.13.1, I tried upgrading with apt.

### Log

```
Setting up wazuh-manager (3.13.1-1) ...
cp: -r not specified; omitting directory '/var/ossec/packages_files/manager_config_files/oscap/ansible'
cp: -r not specified; omitting directory '/var/ossec/packages_files/manager_config_files/oscap/bash'
cp: -r not specified; omitting directory '/var/ossec/packages_files/manager_config_files/oscap/guides'
cp: -r not specified; omitting directory '/var/ossec/packages_files/manager_config_files/oscap/kickstart'
cp: -r not specified; omitting directory '/var/ossec/packages_files/manager_config_files/oscap/tables'
dpkg: error processing package wazuh-manager (--configure):
 installed wazuh-manager package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of wazuh-api:
 wazuh-api depends on wazuh-manager (>= 3.13.1); however:
  Package wazuh-manager is not configured yet.
 wazuh-api depends on wazuh-manager (<< 3.13.2); however:
  Package wazuh-manager is not configured yet.

dpkg: error processing package wazuh-api (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Errors were encountered while processing:
 wazuh-manager
 wazuh-api
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
the error is `wazuh-manager package post-installation script subprocess returned error exit status 1`.

this is happening on manager only and no problem when upgrading agent.

**Comment by jotacarma90** [comment]
Hi @nothinux 
I've been talking to some teammates. They tell me that this is a known error that will soon be resolved. You can read much more in-depth in this thread of our community channel in Slack:
https://wazuh.slack.com/archives/C0A933R8E/p1595837556122800

To fix this, you have to modify the **postinst** script (`/var/lib/dpkg/info/wazuh-manager.postinst`).
Line 233 with: `cp -R ${WAZUH_TMP_DIR}/oscap/* ${DIR}/wodles/oscap/content/`

This is my co-worker's final answer:
"We introduced some changes on 3.13.0 to lighten up the binary packages ([428](https://github.com/wazuh/wazuh-packages/pull/428) and [429](https://github.com/wazuh/wazuh-packages/pull/429)). RPM packages work fine but Deb packages are affected by this bug. Indeed, wazuh-manager and wazuh-agent are affected. The bug is found in these lines from the postinst script:
wazuh-manager: https://github.com/wazuh/wazuh-packages/blob/master/debs/SPECS/3.13.0/wazuh-manager/debian/postinst#L231-L234
wazuh-agent: https://github.com/wazuh/wazuh-packages/blob/master/debs/SPECS/3.13.0/wazuh-agent/debian/postinst#L156-L159
This if block should look like this:
```
    # Restore OpenSCAP policies files
    if [ -d ${WAZUH_TMP_DIR}/oscap ]; then
        cp -R ${WAZUH_TMP_DIR}/oscap/* ${DIR}/wodles/oscap/content/
    fi
```
So, if you really need to upgrade to the latest version and you are using OpenSCAP in your agents/managers in Debian based systems, you will need to modify the postinst script as we did previously to successfully upgrade. Systems using rpm packages will upgrade without problem.
Other possible solution is create a custom package of wazuh-v3.13.1 with the tools from this repository [wazuh-packages](https://github.com/wazuh/wazuh-packages) and upgrade your hosts. You can find more info about this [here](https://documentation.wazuh.com/3.13/development/packaging/index.html). I can help you to create a custom package if you want.
Otherwise, you can wait until the next official release and install official packages with the fix."

If you need more help, don't hesitate to ask.
Greetings, Jose.

**Comment by nothinux** [comment]
Hi Jose @jotacarma90 

Thank you for the quick response and thank you for your help, I have successfully upgraded wazuh-manager with the solution you provide.

Thank you.

**Comment by nothinux** [comment]
Solved
