### ISSUE TITLE
[Development] Agent registered multiple times when using delay_after_enrollment = 1

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#5975]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.0-rc1| auto-enrollment | Manager/Agent | Packages/Sources | All |

Hello team,

We found that if we use low values when for `delay_after_enrollment`, `max_retries` and `retry_interval` then the auto-enrollment process registers the agent multiple times.

### How to reproduce

1. Set the `client` configuration of the agent like this:

```
  <client>
    <server>
      <address>MANAGER_IP</port>
      <protocol>tcp</protocol>
      <max_retries>1</max_retries>
      <retry_interval>1</retry_interval>
    </server>
    <enrollment>
      <delay_after_enrollment>1</delay_after_enrollment>
    </enrollment>

    <config-profile>ubuntu, ubuntu18, ubuntu18.04</config-profile>
    <notify_time>5</notify_time>
    <time-reconnect>6</time-reconnect>
    <auto_restart>yes</auto_restart>
    <crypto_method>aes</crypto_method>
  </client>
``` 

2. Restart the agent and wat for the enrollment to finish.

3. Check in the manager the ID of the agent:

```
# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: centos7 (server), IP: 127.0.0.1, Active/Local
   ID: 005, Name: ubuntu18LTS, IP: any, Active
```

As you can see the agent has ID `005` instead of the expected `001`, this issue can rapidly increase the agent ID count in environments that use multiple managers and can make it harder to keep track of the alerts reported by the agents.

Regards, 
Daniel Folch

**Comment by vikman90** [comment]
Hi team,

This behavior is expectable. An agent registration operation does not make the key available immediately. There is a propagation time from when Authd registers an agent until it is transmitted through the cluster Remoted loads it.

The maximum propagation time is:
```
remoted.keyupdate_interval + cluster.intervals.worker.sync_files
```

The default value of both parameters is 10 seconds, so the default value for `delay_after_enrollment` is 20 seconds.

But, if we set up a single-node manager and set `remoted.keyupdate_interval` to `1`, then we could set `delay_after_enrollment` to `1`. Otherwise, the agent may try to connect before the new key is applied, which would make the agent try to enroll again.

A configuration like this would never produce a major issue, and the agent won't appear multiple times in the keys file though it enrolls multiple times.

Closing this issue.
Thank you.
