### ISSUE TITLE
Parent rules

### ISSUE THREAD

**Issue by hitman28594** [wazuh/wazuh#6007]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

Also...

When rules are triggered, would it be possible to also make the parent rule still trigger too? 

Example 1:
If we have a rule for 1 failed login (e.g rule:18130) and a child rule with frequency 100 then:
99 logs will trigger the singe failure rule (e.g 18130) and 1 log will trigger the 100 failures rule. 

Example 2:
We have had two failed logins:
One failure from Admin1
One failure from IP1

If we have the generic parent rule: 1 failed login (e.g rule:18130) 
And two child rules of 18130:
Failed from Admin1 
Failed from IP1 

When attempting to see all failures by querying rule 18130 there will be 0, and 1 each for the child rules. 

############### 

This is okay and expected, but can we have a feature/option to also make the parent rule generate an alert? 

This would make keeping track of things much more easier and introduce less discrepancies in a larger scale where there are millions of failures. We would be able to query for rule 18130 and get all the events, instead of things getting jumbled in other child rules. 

I understand these may not be the best examples.

**Comment by vikman90** [comment]
Hi @hitman28594. These examples are so valid, I think I understood what you need.

Currently, every input log in Wazuh is a candidate to produce only one alert. The ruleset is a decision tree, each log traverses that tree to select the rule that matches the data extracted by the decoder. In other words, each alert belongs exclusively to one log and it indicates the rule that most exactly matched that log.

We can discuss about developing a feature to let one log trigger multiple rules, though that would be complex.

However, I think rule groups can help you out with what you need.

## Example

### Use case

We want to alert login attempts and distinguish between three cases:

1. Login from "A" (100002)
2. Login from "B" (100003)
3. Login from any other source (100001)

### Example 

#### Decoder

```xml
<decoder name="test">
  <program_name>test</program_name>
  <regex>Login from (\S+)</regex>
  <order>source</order>
</decoder>
```

#### Rules

```xml
<rule id="100001" level="5">
  <decoded_as>test</decoded_as>
  <description>Test log.</description>
  <group>login_test,</group>
</rule>

<rule id="100002" level="5">
  <if_sid>100001</if_sid>
  <field name="source">^A$</field>
  <description>Login from A.</description>
  <group>login_test,</group>
</rule>

<rule id="100003" level="5">
  <if_sid>100001</if_sid>
  <field name="source">^B$</field>
  <description>Login from B.</description>
  <group>login_test,</group>
</rule>
```

#### Alerts

```
** Alert 1600083181.342345: - local,syslog,sshd,login_test,
2020 Sep 14 13:33:01 focal->/var/log/syslog
Rule: 100002 (level 5) -> 'Login from A.'
Sep 14 13:32:59 focal test: Login from A
source: A

** Alert 1600083183.342543: - local,syslog,sshd,login_test,
2020 Sep 14 13:33:03 focal->/var/log/syslog
Rule: 100003 (level 5) -> 'Login from B.'
Sep 14 13:33:02 focal test: Login from B
source: B

** Alert 1600083191.342741: - local,syslog,sshd,login_test,
2020 Sep 14 13:33:11 focal->/var/log/syslog
Rule: 100001 (level 5) -> 'Test log.'
Sep 14 13:33:10 focal test: Login from C
source: C
```

Having every rule into group `login_test`, you can:

- Search for login attempts from "B", querying the alerts with rule id `100003`.
- Search for any login attempt (regardless of the source), querying the alerts with rule group `login_test`.

You can also group A and B into another group so that you could query for login attempts from known sources. This way you have one alert per log and you can select the data as you need, preventing from having two alerts for the same log.

Hope this helps you.

Best regards.
