### ISSUE TITLE
ERROR: Upgrade aborted: Unexpected version in the new ruleset. Expected version v3.9.x. Found version v3.13.1

### ISSUE THREAD

**Issue by numbfx** [wazuh/wazuh#6010]
Getting this error, I see this error has come up in the past on previous versions.  I am running a clean install of SecurityOnion.

**Comment by danimegar** [comment]
Hi @numbfx 

That error appears because upgrade_ruleset tries to check out the latest version of the ruleset, but your version of Wazuh is incompatible.

Currently, the latest version of the ruleset is 3.13.1.

If we want to update an older version of the ruleset (3.9.x in this case), we can define that with the option `-n`, this way:

`# /var/ossec/bin/update_ruleset -n 3.7`

Upgrading to the latest minor version of Wazuh (3.13.1 currently) is required to get the latest ruleset. We are currently releasing versions of Wazuh and the ruleset at the same time, so I recommend you a full upgrade of Wazuh when possible.
