### ISSUE TITLE
Unable to install Wazuh Agent on Plesk Server with Imunify 360 ( Ossec Conflict)

### ISSUE THREAD

**Issue by Stefan-CPlanet** [wazuh/wazuh#6038]
Ubuntu 20.04 Wazuh-Server ; Ubuntu 18.04 Wazuh-Agent
Wazuh Server all on single node (manager + Api) , Splunk (not elastic)

I have a server with Plesk Obsidian ( newest version ) and Imunify360 security plugin. When I try to install Wazuh I get following error:
```
Selecting previously unselected package wazuh-agent.
(Reading database ... 183879 files and directories currently installed.)
Preparing to unpack ./wazuh-agent.deb ...
=====================================================================================
= Backup from your ossec.conf has been created at /var/ossec/etc/ossec.conf.deborig =
= Please verify your ossec.conf configuration at /var/ossec/etc/ossec.conf =
=====================================================================================
Unpacking wazuh-agent (3.13.1-1) ...
dpkg: error processing archive ./wazuh-agent.deb (--install):
trying to overwrite '/var/ossec/bin/manage_agents', which is also in package imunify360-ossec-server 3.1.0-81
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
dpkg: error while cleaning up:
new wazuh-agent package post-removal script subprocess returned error exit status 1
Errors were encountered while processing:
./wazuh-agent.deb
```
There seems to be some sort of conflict with Immunity. 

It is imperative that I do not break Immunity trying to setup Wazuh, therefor I didn't proceed.

How can I fix this issue?
Thank you

**Comment by antoniomanuelfr** [comment]
Hi @Stefan-CPlanet 
I have been investigating and look like Imunify comes with a preinstalled version of OSSEC. 
If it's mandatory that you don't break Imunify, you can try installing Wazuh in a custom path (the most common alternative path is `/opt/ossec`).

For that, you can install Wazuh from sources following these steps: 

- Install the dependencies (has mentioned in the [docs](https://documentation.wazuh.com/3.13/installation-guide/installing-wazuh-manager/linux/ubuntu/wazuh_server_sources_ubuntu.html#wazuh-server-sources-ubuntu):

- Download the source code, `curl -Ls https://github.com/wazuh/wazuh/archive/v3.13.1.tar.gz | tar zx`

- After that, you should compile the source code, in order to do that, change to the `wazuh-3.13/src` folder and execute the next command: `make deps PREFIX=/opt/ossec && make PREFIX=/opt/ossec TARGET=server -j4` (In the PREFIX variable you should write the custom installation path). If you want to install an agent, instead of `TARGET=server` you should write `TARGET=agent`

- When the compilation has finished, you have to execute the installation script (`wazuh-3.13/install.sh`). Execute it and when it asks you about the installation path, you write the same path that you wrote before (in my case `/opt/ossec`) and the rest of the options that the script will ask are not relevant when installing in a custom path.

Another way is by using a custom package. You have a detailed description of this process at the Wazuh [documentation](https://documentation.wazuh.com/3.13/development/packaging/generate-deb-package.html).

I hope this information is useful. 
Kind regards.

**Comment by Stefan-CPlanet** [comment]
Thank you @antoniomanuelfr for the help. 
I managed to install per your instructions, however, when I try to start the agent it fails to start.
**/opt/ossec/logs/ossec.log contains:**
```
2020/09/17 14:39:18 ossec-execd: INFO: Started (pid: 22418).
2020/09/17 14:39:18 ossec-agentd: INFO: (1410): Reading authentication keys file.
2020/09/17 14:39:18 ossec-agentd: CRITICAL: (1751): File client.keys not found or empty.
```
Do you think you know what can be an issue?
Also could you perhaps let me know what ports I need to open for Agent to work, same port (5500) of the API?

Thank you again for the help, your tutorial was really detailed.

**Comment by antoniomanuelfr** [comment]
Hi again @Stefan-CPlanet

Have you connected the agent to a Wazuh manager?

The file `client.keys` is used to store the password that is going to be used for communication between the agent and the manager. If you didn't register that Wazuh agent to a Wazuh manager, the file client.keys will be empty and the agent won't start. 
To register a Wazuh agent to a Wazuh manager, you can follow the steps mentioned in the [documentation](https://documentation.wazuh.com/3.13/user-manual/registering/index.html) page.

In this section of the [documentation](https://documentation.wazuh.com/3.13/getting-started/components/index.html) you can also see the main components of the Wazuh architecture, in short: 
- The agents send all the information to a Wazuh manager
- The manager, gets that information, analyses it, and triggers alerts when threats or anomalies are detected.

The Wazuh manager has an agent too, so you should consider installing a manager instead of an agent. 
The API is also installed only on the manager side.

If you have any doubts, don't hesitate to contact us.
Kind regards

**Comment by Stefan-CPlanet** [comment]
Hi @antoniomanuelfr , thank you that worked.
I have never done it this way so I didn't know about that step. 
Finally, it is working.

One more thing I would like to ask you is in Splunk, how can I show agent 000 ( wazuh manager) in the agent list? Thank you for everything

**Comment by antoniomanuelfr** [comment]
Hi, I'm glad that you work it out. 
You can't show the agent 000 in the agent list when using Splunk, because that list is only for Wazuh agents, not for the manager. 
In the alerts dashboard, all of the alerts of the agent 000 are going to appear, because Splunk uses the `alerts.json` file to get those alerts.

Kind regards

**Comment by Stefan-CPlanet** [comment]
Thank you for everything. I will close the issue for now.
Have a great day!
