### ISSUE TITLE
Fix permission extraction in Windows [FIM]

### ISSUE THREAD

**Issue by joselopezrio** [wazuh/wazuh#6055]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.1 | Syscheck | Agent | Packages | Windows 10|

Wazuh stops when trying to monitor with `syscheck` a  file that has no associated permissions to the object displaying the following message:
```
syscheck_op.c:813 at w_get_file_permissions(): DEBUG: 'c:\users\all users\nvidia\nvstarted' has no DACL, so no permits can be extracted.
```
For this example, the file `nvstarted` located at `c:\users\all users\nvidia` did not have any permissions attached.

### Steps to reproduce
1. Locate a file without permissions attached. In Windows with `Nvidia` graphics, it is common to have the following one: `C:\users\all users\nvidia\nvstarted` or `C:\ProgramData\NVIDIA\nvstarted`.
2. Add the following directory monitoring inside the `Syscheck` stanza for the Wazuh agent:
```
<directories check_all="yes" realtime="yes" recursion_level="2">%SystemDrive%\Users</directories>
```
3. Add debug logging setting `windows.debug` to `2`  in the `internal_options.conf` in  `C:\Program Files (x86)\ossec-agent` by default.
4. Wait until the agent stops and check the last messages of the `ossec.log` file.

Let me know if you need anything.

Regards,
Jose Manuel Lopez

**Comment by Molter73** [comment]
I have been testing files with no permissions set in Windows and narrowed down this error to the function `decode_win_permissions`. Specifically in these lines, the function returns a `NULL` pointer which is stored and later used directly in several places with no extra checks on it.

https://github.com/wazuh/wazuh/blob/556d1b64d7feba74bb5060fd5fe18e48db55bee6/src/shared/syscheck_op.c#L986-L990

Further testing will be required in order to check if returning an empty string is enough to fix the issue or if extra care should be taken.
