### ISSUE TITLE
Unable to Decode Watchguard log

### ISSUE THREAD

**Issue by VisakhMV-Coder** [wazuh/wazuh#6075]
Dear team,

I am new in wazuh,i tried making a decoder for the following log from watchguard,but no predecoder matched

Sep 11 17:23:52 FlorenceSt-T35 (2020-09-11T07:23:52) firewall: msg_id="3000-0148" Deny 1-Florence St. - LAN Firebox 11 tcp 22 33 11.11.11.11 22.22.22.22 0007 8888 offset 8 A 356442 win 362 msg="tcp syn checking failed (expecting SYN packet for new TCP connection, but received ACK, FIN, or RST instead)." (Internal Policy)

can someboday say how to prematch this log.i tried different ways,but not working.is it any bug from wazuh also i dont know.somebody please help as we are new to wazuh.attaching a screenshot for your reference.
![image](https://user-images.githubusercontent.com/61306426/93966004-3b8e2000-fd81-11ea-9bf1-99c970699b7b.png)

the first marking is the original log and the second marking is hw it is predecoded,which confuses us
Thanks in advance.
florence

**Comment by davidjiglesias** [comment]
Hello @VisakhMV-Coder,

I have been reading the `Watchguard` log documentation for how to [Read a log message](https://www.watchguard.com/help/docs/fireware/11/en-US/log_catalog/index.html#intro/read_log-msg.html).

I have checked that against the log you posted here and the problem seems to be this piece of log `(2020-09-11T07:23:52)` right after the hostname, I do not find any information about that in the Watchguard documentation. Wazuh pre-decoder is not prepared for it and therefore that is why you see an error in the pre-decoding, with half of that date splitted between program_name and log:

       program_name: `'(2020-09-11T07'`
       log: `'23:52)` LOG

Is it an optional field? 

Anyway that log is not being pre-decoded properly. I will move this issue to `Research and Development` so our core team can include it in our roadmap for a future investigation.

Thank you for your contribution, if you have any other inquiries please do not hesitate to ask.

Regards

**Comment by VisakhMV-Coder** [comment]
sure buddy...thanks for your support
