### ISSUE TITLE
Store FIM data in Wazuh DB

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#611]
Currently, the manager stores FIM data onto plain-text databases at `/var/ossec/queue/syscheck`.

- It opens one database per agent and keeps it, the limit of descriptors may reach the system limit.
- Search efficiency: _O(n).
- Write efficiency: _O(1)_, but it never deletes old entries so the DB can grow indefinitely.
- Database file search: _O(n)_.
- Complete agent scan efficiency: _O(n²)_.

Replace file handling with a connection with Wazuh DB. In this case:

- Search efficiency should be _O(log(n))_.
- Write operations should be cached.
- No historical data will be kept.

Please open only one socket —as Syscollector decoder does— and avoid that eventual errors in Wazuh DB impact Analysisd.

**Comment by bah07** [comment]
The task is divided as follows

- [ ] Connect FIM decoder to SQLite database via '_Wazuh-db_' (Complete decoder restructuring)
- [ ] Delete historical records in the database. Only files currently being monitored are kept. (New functionality)
- [ ] Create an independent socket for each '_Analysisd_' thread dedicated to FIM.
- [ ] Restructure the way '_Wazuh-db_' receives events so that each thread can process queries from different sources.
