### ISSUE TITLE
Wazuh Issues SIGTERM to kill subprocess without logging why

### ISSUE THREAD

**Issue by mire3212** [wazuh/wazuh#6142]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13 | Wazuh Agent/Agent-Auth | Agent | Packages | Amazon Linux 2 |

While attempting to perform an enrollment of a new agent against the Wazuh Master node, if the `agent-auth` process is unable to connect to the host (i.e. a timeout occurred), the debug logging only indicates a `SIGTERM` received rather then any useful information about the registration process.

```
2020/09/29 00:49:38 agent-auth[17260] ssl.c:83 at os_ssl_keys(): DEBUG: Returning CTX for client.
2020/09/29 00:49:43 agent-auth[17260] sig_op.c:49 at HandleSIG(): INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
```

This is an example that was demonstrated by using `iptables` to block outbound 1510-1520, preventing the agent from reaching the manager. The logs here are useless and may indicate a use-case for better exception handling in the network communication stack.

Additionally, this time-out was executed after only 5-seconds and the agent doesn't even attempt to re-connect after the SIGTERM is received. 5-seconds is extremely low for a time-out, but this failure to log the accuracy of the event is even worse and should be corrected.

**Comment by vikman90** [comment]
Hi @mire3212,

I'm investigating this issue. The agent service should kill the running daemons via _SIGTERM_ when stopping or restarting the agent.

The following commands:
```sh
systemctl stop wazuh-agent
systemctl restart wazuh-agent
service wazuh-agent stop
service wazuh-agent restart
/var/ossec/bin/ossec-control stop
/var/ossec/bin/ossec-control start
```

Any of them should send _SIGTERM_ to every agent daemon. We can check them this way:
```sh
# ls /var/ossec/var/run/*.pid
/var/ossec/var/run/ossec-agentd-6831.pid        /var/ossec/var/run/ossec-syscheckd-6845.pid
/var/ossec/var/run/ossec-execd-6822.pid         /var/ossec/var/run/wazuh-modulesd-6872.pid
/var/ossec/var/run/ossec-logcollector-6858.pid
```

The agent will kill these processes and only these processes. In other words, the service should never kill a running instance of _agent-auth_ as it is a CLI tool, not a daemon.

I followed the steps you described on agents from 3.13.0 to 4.0 (develop). In my case, the manager is at 192.168.33.12:
```
# iptables -A OUTPUT -d 192.168.33.12 -j DROP
# agent-auth -ddm 192.168.33.12
2020/09/29 17:18:42 agent-auth[6695] main-client.c:241 at main(): DEBUG: Starting ...
2020/09/29 17:18:42 agent-auth[6695] main-client.c:271 at main(): INFO: Started (pid: 6695).
2020/09/29 17:18:42 agent-auth[6695] ssl.c:83 at os_ssl_keys(): DEBUG: Returning CTX for client.
2020/09/29 17:18:42 agent-auth[6695] main-client.c:330 at main(): INFO: No authentication password provided.
```

Since the firewall is dropping connection attempts to the manager, the agent keeps waiting indefinitely. Obviously, if I kill it from another terminal:

```sh
pkill -f agent-auth
```

Then _agent-auth_ ends with the log:
```
2020/09/29 17:18:58 agent-auth[6913] sig_op.c:49 at HandleSIG(): INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning... 
```

I don't have an explanation for the agent itself to kill the tool. I'm pretty sure the _SIGTERM_ signal is produced by an external actor. Could you provide us with more information about your environment? For instance, if you are deploying the agent with Ansible, and the playbook runs `agent-auth` via a shell module with a timeout defined. I'd like to follow the same steps you're running to be able to explain that log.

Best regards.

**Comment by mire3212** [comment]
You're correct. I found the cause of the `SIGTERM` as being something sent from our deployment mechanism.
