### ISSUE TITLE
Update OSSEC from the master

### ISSUE THREAD

**Issue by scrow123** [wazuh/wazuh#62]
OSSEC have added some additional functionality allowing the notify time to be changed when an ossec agent disconnects. I use the Wazuh branch of OSSEC and i have not seen this functionality added. See commit: https://github.com/ossec/ossec-hids/pull/1020

**Comment by vikman90** [comment]
Hi @scrow123,

we saw that PR and are planning to add that feature but we will do it later in order to launch the new release.

In addition we detected some issues at that recently added functionality (https://github.com/ossec/ossec-hids/issues/1022) and, in our case, we have also to deal with the API, that uses the same parameter to detect whether an agent is connected or disconnected.

We will add it as soon as possible for the next version when the detected problem is solved.

Thank you very much for your interest.
Kind regards.
