### ISSUE TITLE
File integrity monitoring error  windows agent

### ISSUE THREAD

**Issue by ozgursuder** [wazuh/wazuh#6239]
Hi
I want to run FILM on public folder.
I guess I'm getting this error because the file size is a little big.
Do I have a chance to increase this dimension.

syscheck
    disabled>no</disabled
    scan_on_start>yes</scan_on_start
    frequency>300</frequency
    directories check_all="yes">D:/Groups</directories
syscheck>

ossec-agent[1200] fim_db.c:918 at fim_db_insert(): DEBUG: Couldn't insert 
'd:\groups\xxx\fixxx\xx\xxx\49312.doc' entry into DB. The DB is full, please check your configuration.

**Comment by ozgursuder** [comment]
The file limit set for this agent is 100000. Now, 100000 files are being monitored and no more files will be monitored. Change this setting in centralized configuration or locally on the agent.

**Comment by Molter73** [comment]
Hi @ozgursuder 

By default, agents stop adding files to the database once 100k files have been scanned, in order to increase this number you need to add the `<file_limit>` section to your configuration as described in [this link](https://documentation.wazuh.com/3.13/user-manual/reference/ossec-conf/syscheck.html#file-limit)

With your configuration it would look something like this:
```xml
<syscheck>
    <disabled>no</disabled>
    <scan_on_start>yes</scan_on_start>
    <frequency>300</frequency>
    <directories check_all="yes">D:/Groups</directories>

    <!-- Maximum number of files to be monitored -->
    <file_limit>
        <enabled>yes</enabled>
        <entries>1000000</entries>
    </file_limit>
</syscheck>
```

That would make it so the limit is 1 million files, or you can disable this limit:

```xml
<syscheck>
    <disabled>no</disabled>
    <scan_on_start>yes</scan_on_start>
    <frequency>300</frequency>
    <directories check_all="yes">D:/Groups</directories>

    <!-- Maximum number of files to be monitored -->
    <file_limit>
        <enabled>no</enabled>
        <entries>1000000</entries>
    </file_limit>
</syscheck>
```

Keep in mind that 5 minutes (300 seconds) might not be enough time for the agent to completely scan such a large directory, if I was in your place I would look into the log file once you have modified the limit and see how long it takes to scan, adjust the frequency accordingly so that the agent is not constantly scanning the directory.

**Comment by ozgursuder** [comment]
Thank you for your support

I'm testing now

**Comment by ozgursuder** [comment]
In this way, any variable is not reflected in the wazuh manager, unfortunately
