### ISSUE TITLE
There are false positives when using vulnerability detection

### ISSUE THREAD

**Issue by gary561** [wazuh/wazuh#6261]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.1-0 | vulnerability | Manager| Packages| centos 7.6 |

There are false positives when using vulnerability detection, the specific symptoms are as follows
![image](https://user-images.githubusercontent.com/45163216/95651012-b729f400-0b19-11eb-96d4-c2e5c150003d.png)
- The software has been upgraded to the latest version without vulnerabilities, but there will still be warnings in the vulnerability detection, which may be a problem with **el6_4**
![image](https://user-images.githubusercontent.com/45163216/95651038-efc9cd80-0b19-11eb-8f05-48a79ba945a7.png)

**Comment by 0xN3utr0n** [comment]
Hi @gary561,
It sure does look like a false-positive, but we still need some more information in order to confirm it. The `minor` number (el6_4) is a rather obscure and unknown field with very little documentation available that has given us a lot of headaches. Keep in mind that, even now, we are still fine-tunning vuln-detector's engine.

Being that said, could please share the output of the `uname -a` command? (from the agent's side)

**Comment by gary561** [comment]
![Uploading image.png…]()

**Comment by 0xN3utr0n** [comment]
Hi @gary561 ,
Thanks for the image, It's clearly a bug in Vulnerability-Detector. We'll have to investigate this more in detail, but I think it should be fairly easy to fix. Since this issue is so well documented, we'll just use it to keep track of the bug.  Any future news on this matter will be commented here. 

Thanks again and sorry for the inconvenience.

**Comment by chemamartinez** [comment]
Hi @gary561,

After further investigation, we have opened a pull request where the problem is described and a fix is implemented to avoid this situation anymore.

You can see the added changes at https://github.com/wazuh/wazuh/pull/6709, which will be available in the next release.

Thanks for reporting this bug.

Regards.

**Comment by chemamartinez** [comment]
Hi @gary561,

Please let me close this issue since the fix I told you about is already merged.

As I said, it will available in the next release. I hope it solves your problems with the Vulnerability Detector.

Thank you again for your feedback, don't hesitate to open a new issue for further concerns.

Best regards.
