### ISSUE TITLE
Audit events are lost with Whodata engine

### ISSUE THREAD

**Issue by Schnoogemetzger** [wazuh/wazuh#6264]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.2 | Whodata engine | Agent | Packages | Debian Buster 10.6 |

Hi,

while monitoring a directory with the whodata engine (`<directories check_all="yes" whodata="yes">/TEST</directories>`) some events are lost. I can force the problem with a for loop adding 3000 files for example.
I'm aware of the _How to tune audit to deal with a huge amount of who-data events at the same time_ [documentation](https://documentation.wazuh.com/3.13/user-manual/capabilities/file-integrity/fim-configuration.html#how-to-tune-audit-to-deal-with-a-huge-amount-of-who-data-events-at-the-same-time) section and I found a similar bug #4660 of this problem, but after tuning the mentioned audit options, I've still the problem.
I don't have any problem monitoring the directory in realtime.

I've installed Wazuh 3.13.2 on two systems (both Debian Buster 10.6). One as agent and the other as a server. 

At the agent I've changed the audit values as follows:

```
agent$ grep q_depth /etc/audisp/audispd.conf 
q_depth = 42000

agent$ grep disp_qos /etc/audit/auditd.conf 
disp_qos = lossless
```

_Sidenote about q_depth: In your documentation you mention to change "q_dephs". Is this a typo, because several man pages mention only "q_depth" and not "q_dephs"?_

As mentioned before, everything works in realtime mode:
`<directories check_all="yes" realtime="yes">/TEST</directories>`

Creating the files on the agent:
`agent$ for i in {001..3000}; do head -c 1M </dev/urandom >test_three$i; done`

Review the log entries on the server:
```
server$ grep "File '/TEST/test_three" /var/ossec/logs/alerts/alerts.log | wc -l
3001

server$ grep "File '/TEST/test_three" /var/ossec/logs/alerts/alerts.log | grep added | wc -l
3000

server$ grep "File '/TEST/test_three" /var/ossec/logs/alerts/alerts.log | grep modified | wc -l
1
```

Overwrite the files on the agent:
`agent$ for i in {001..3000}; do head -c 1M </dev/urandom >test_three$i; done`

Review:
```
server$ grep "File '/TEST/test_three" /var/ossec/logs/alerts/alerts.log | grep modified | wc -l
3002
```

Deleting the files on the agent:
`agent$ rm test_three*`

Final review on the server:
```
server$ grep "File '/TEST/test_three" /var/ossec/logs/alerts/alerts.log | wc -l
9002

server$ grep "File '/TEST/test_three" /var/ossec/logs/alerts/alerts.log | grep added | wc -l
3000

server$ grep "File '/TEST/test_three" /var/ossec/logs/alerts/alerts.log | grep modified | wc -l
3002

server$ grep "File '/TEST/test_three" /var/ossec/logs/alerts/alerts.log | grep deleted | wc -l
3000
```

Afterwards I've triggered a syscheck run at the agent, but there weren't any missed files. Therefore, everything works as expected in realtime mode.

The same test with the whodata engine:
`<directories check_all="yes" whodata="yes">/TEST</directories>`

Creating the files:
`agent$ for i in {001..3000}; do head -c 1M </dev/urandom >test_four$i; done`

Review the files:
```
server$ grep "File '/TEST/test_four" /var/ossec/logs/alerts/alerts.log | wc -l
3000
```

Looks good at first glance, but the syscheck is going to find modified files afterwards:
```
server$ /var/ossec/bin/agent_control -r -u 004
Wazuh agent_control: Restarting Syscheck/Rootcheck on agent: 004

server$ grep "File '/TEST/test_four" /var/ossec/logs/alerts/alerts.log | wc -l
3098

server$ grep "File '/TEST/test_four" /var/ossec/logs/alerts/alerts.log | grep added | wc -l
3000

server$ grep "File '/TEST/test_four" /var/ossec/logs/alerts/alerts.log | grep modified | wc -l
98
```

I can say, that the modified files all about the size, for example:
`Size changed from '491520' to '1048576'`

It seems to me, that the creation process of some files are recognized, but not until the end (= 1M), which leads to the modification event. This is also the main problem, why I stumbled about this issue.

Overwriting the files:
`agent$ for i in {001..3000}; do head -c 1M </dev/urandom >test_four$i; done`

Review:
```
server$ grep "File '/TEST/test_four" /var/ossec/logs/alerts/alerts.log | wc -l
6098

server$ grep "File '/TEST/test_four" /var/ossec/logs/alerts/alerts.log | grep added | wc -l
3000

server$ grep "File '/TEST/test_four" /var/ossec/logs/alerts/alerts.log | grep modified | wc -l
3098
```

Again, after a run of syscheck additional events from the test_four file will be logged:
```server$ /var/ossec/bin/agent_control -r -u 004
Wazuh agent_control: Restarting Syscheck/Rootcheck on agent: 004

server$ grep "File '/TEST/test_four" /var/ossec/logs/alerts/alerts.log | wc -l
6161

server$ grep "File '/TEST/test_four" /var/ossec/logs/alerts/alerts.log | grep modified | wc -l
3161
```

Deleting the files:
```
agent$ rm *

server$ grep "File '/TEST/test_four" /var/ossec/logs/alerts/alerts.log | wc -l
9161

server$ grep "File '/TEST/test_four" /var/ossec/logs/alerts/alerts.log | grep deleted | wc -l
3000
```

I think the deleting worked without a problem, but there was an error message in the ossec.log of the agent. This happens only by deleting files:
```
agent$ /var/ossec/logs/ossec.log:
2020/10/09 09:22:36 ossec-syscheckd: ERROR: (6643): Caching Audit message: event too long.
2020/10/09 09:22:36 ossec-logcollector: ERROR: Discarding audit message because cache is full.
```

One more test with the whodata engine. I've modified the for loop and added a sleep. Here we go again – creating the files:
`agent$ for i in {001..3000}; do head -c 1M </dev/urandom >test_six$i; sleep 0.3s; done`

Review:
```
server$ grep "File '/TEST/test_six" /var/ossec/logs/alerts/alerts.log | wc -l
2999

server$ grep "File '/TEST/test_six" /var/ossec/logs/alerts/alerts.log | grep added | wc -l
2999
```

As we can see, one file is missing. Therefore I've started a syscheck:
```
server$ /var/ossec/bin/agent_control -r -u 004
Wazuh agent_control: Restarting Syscheck/Rootcheck on agent: 004

server$ grep "File '/TEST/test_six" /var/ossec/logs/alerts/alerts.log | wc -l
5908

server$ grep "File '/TEST/test_six" /var/ossec/logs/alerts/alerts.log | grep added | wc -l
3000

server$ grep "File '/TEST/test_six" /var/ossec/logs/alerts/alerts.log | grep modified | wc -l
2908
```

Syscheck found again a lot modified files and not only one missing file. The modified ones are all about the size again.

I ran the for loop with the sleep command also with the realtime engine on:

```
agent$ for i in {001..3000}; do head -c 1M </dev/urandom >test_eight$i; sleep 0.3s; done

server$ grep "File '/TEST/test_eight" /var/ossec/logs/alerts/alerts.log | wc -l
5904

server$ grep "File '/TEST/test_eight" /var/ossec/logs/alerts/alerts.log | grep added | wc -l
3000

server$ grep "File '/TEST/test_eight" /var/ossec/logs/alerts/alerts.log | grep modified | wc -l
2904

server$ /var/ossec/bin/agent_control -r -u 004
Wazuh agent_control: Restarting Syscheck/Rootcheck on agent: 004

server$ grep "File '/TEST/test_eight" /var/ossec/logs/alerts/alerts.log | wc -l
5904
```

In realtime mode, there are 2904 modified events, just after the created events in the log. A run of the syscheck do not find any new/additional events, as expected.

I've also checked the `syscheck.rt_delay` parameter, but in- or decreasing this didn't change the behavior of this issue. So I left it at the default value of 5.

We've configured a monitoring about file changes and we always wondered, why there were file changes, e.g. three hours later after the initial ones, which was a planned rollout for example. The three hours later events was just the run of the syscheck which found several addtional events, which weren't recognized three hours earlier by the whodata engine.

Is this a bug, as in github issue #4660 or how can I mitigate this problem? I have no further ideas to tweak this, beside to let syscheck run every 15 minutes or so, or switch to the realtime engine.

Thanks.

**Comment by jotacarma90** [comment]
Hello @Schnoogemetzger,
Thank you very much for this analysis you have done of the issue. We have two different problems:

- The first one is related to double alerts for the same event, it happens when the file is too big, and the creation process takes enough time to generate two different events in audit. You can read about this same problem when downloading large files on this issue https://github.com/wazuh/wazuh/issues/5242.
  One possibility for this problem is to increase the value of the **rt_delay** variable. Although we are still working on it.

- The other problem is the loss of events in audit/whodata. The issue https://github.com/wazuh/wazuh/issues/4660, and its effects can be reduced with the auditd configuration variables that you have commented on. 
I have tested with your same command for the generation of files, and in my machine, they have appeared all (perhaps for being slower) since these problems appear when a great amount of events happens in the same instant.

At the moment we have these two issues in our roadmap in the short term and we will try to find a solution for them as soon as possible.
Greetings.

**Comment by Schnoogemetzger** [comment]
Hi @jotacarma90,
thank you for your answer.

> it happens when the file is too big

The files I've created are only 1 MB large. From what size do you consider the file large?
About **rt_delay**: If I'm going to increase the value, do I have drawbacks with a high value, e.g. 20?

> I have tested with your same command for the generation of files, and in my machine, they have appeared all

Did you use one machine or as I did, two?

Before this will be fixed, what do you suggest? Should I switch to realtime mode only?

Thank you very much again.

**Comment by jotacarma90** [comment]
Hi @Schnoogemetzger 

The problem is not that the size is more or less big. It is a special case in which the audit log of the file creation is processed faster than its own content is written. So an "added" alert appears that does not correspond to the total content of the file.
Later in a second analysis, you will see that there has been a modification. 

With high values of **rt_delay**, you can give some more time for the content of the file to be written before processing the event. The disadvantage is the slow processing of the alerts.

I did my tests with manager and agent, but in reality, processing occurs on the agent's side. You can do these same tests by checking the agent's log (`/var/ossec/logs/ossec.log`).

It is difficult to suggest an ideal configuration, since it depends on many factors. When we are dealing with a great amount of events in the same moment, we can have several conflicting points.

The audit configuration that you have modified is a good decision. And to reduce the problem of double events, try higher values of **rt_delay**. This should solve it.

Greetings

**Comment by jotacarma90** [comment]
Issue closed due to inactivity, do not hesitate to reopen if we can help you in any way.
