### ISSUE TITLE
False positive for CVE-2017-15994 on Ubuntu 18.04 Bionic

### ISSUE THREAD

**Issue by morph027** [wazuh/wazuh#6313]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.2 | unknown | unknown | Packages | Ubuntu 18.04 Bionic |

Recently, alerts regarding CVE-2017-15994  are popping up for 18.04 based systems. According to https://people.canonical.com/~ubuntu-security/cve/2017/CVE-2017-15994.html, the version 3.1.2 [shipped](https://packages.ubuntu.com/bionic/rsync) is not affected.

**Comment by MarcelKemp** [comment]
Hi @morph027,

In wazuh version 3.13.2, the vendor's OVAL does not contain information about the vulnerability, and as the NVD does contain this vulnerability, it reports it.

In the case of wazuh 4.0, this false positive has been fixed.
Now, the vendor of the package is taken into account when analysing vulnerabilities reported by each source. In this case, since the vendor of the package should be "Ubuntu developers", it means the package was installed by the official repositories of Canonical, so the criteria of the vendor (not vulnerable because it doesn't appear in the OVAL) is heavier than the criteria of the NVD (vulnerable).
 As you can check in the log:

    wazuh-modulesd:vulnerability-detector[6537] wm_vuln_detector_nvd.c:2445 at wm_vuldet_check_generic_package(): DEBUG: 
    (5458): Package 'rsync' inserted into the vulnerability 'CVE-2017-15994'. Version (3.1.2-2.1ubuntu1.1) 'less than or equal' '3.1.2' 
    (feed 'NVD').
    wazuh-modulesd:vulnerability-detector[6537] wm_vuln_detector.c:1515 at wm_vuldet_linux_rm_nvd_not_affected_packages(): 
    DEBUG: (5462): Package 'rsync' not vulnerable to 'CVE-2017-15994' since it is not affected (feed 'OVAL').

To see more information about the problem, I offer you the PR where it has been fixed for wazuh version 4.0: https://github.com/wazuh/wazuh/pull/5330

If you have any further questions, don't hesitate to ask.

**Comment by MarcelKemp** [comment]
We will close the issue, thank you for your feedback.
Feel free to open another issue when you have more questions to report.
Kind regards.
