### ISSUE TITLE
Backup and replace manager server

### ISSUE THREAD

**Issue by Aviv641999** [wazuh/wazuh#6319]
Hi, 
I am using wazuh v3.11.2 server from package, in cluster mode, 2 node and master.
I have some questions before my manager(master) wazuh server is being replaced.

Which files need to be backuped? (sensitive files, configuration files, DBs ect.)
Is it ok?
`cp /var/ossec /backup/ossec-backup`

I want to establish new server to be my manager, how do i do it? 
Install wazuh, add to cluster?, move /backup/ossec-backup from last master to current /var/ossec ?, when do it config the <cluster> tag in ossec.conf? how i make the new server recognize the agents that the old server authenticated?
Do i miss something? 

As you can see I'm a little confused, I would love someone arrange things a bit for me :)

**Comment by AdriiiPRodri** [comment]
Hi @Aviv641999,

We recommend copying the **/var/ossec** folder, as you say, in order to make the migration. It is important that the new server has wazuh installed in /var/ossec, otherwise the services will not be able to start because the paths of these are different. Once this folder has been copied, we will carry out the following steps:

1. Install Wazuh Manager in the new server. **Do no select to run Manager after installation**.

2. Restore configuration. Before you attempt restoration make sure the Manager **is stopped** in the new server.

   ` cp -p /var/ossec_backup/etc/client.keys /var/ossec/etc/`
    `cp -p /var/ossec_backup/etc/ossec.conf /var/ossec/etc/`
    `cp -p /var/ossec_backup/queue/rids/sender_counter /var/ossec/queue/rids/sender_counter`
   
    If you have made local changes to any of the following then also restore:

    `cp -p /var/ossec_backup/etc/local_internal_options.conf /var/ossec/etc/local_internal_options.conf`
    `cp -p /var/ossec_backup/rules/local_rules.xml /var/ossec/etc/rules/local_rules.xml`
    `cp -p /var/ossec_backup/etc/local_decoder.xml /var/ossec/etc/decoders/local_decoder.xml`

    If you have the centralized configuration you must restore:
   
    `cp -p /var/ossec_backup/etc/shared/agent.conf /var/ossec/etc/shared/default/agent.conf`

    Optionally the following files can be restored to preserve alert log files and syscheck/rootcheck databases:

    `cp -rp /var/ossec_backup/logs/archives/* /var/ossec/logs/archives`
    `cp -rp /var/ossec_backup/logs/alerts/* /var/ossec/logs/alerts`
    `cp -rp /var/ossec_backup/queue/rootcheck/* /var/ossec/queue/rootcheck`
    `cp -rp /var/ossec_backup/queue/syscheck/* /var/ossec/queue/syscheck`

3. Start Wazuh Manager service.

4. Change agents **ip address to point to new Wazuh manager ip** and restart the agents.

I hope this helps.

Regards

**Comment by Aviv641999** [comment]
Thank you @AdriiiPRodri, It was very helpful.

**Comment by Aviv641999** [comment]
Hi @AdriiiPRodri,

I tried to perform it, and i have some questions.

**First**, i deployed new server and installed wazuh-manager on it, i configured it to be master and configured one of my nodes too to be under his responsibility.
In addition, i copied the `client.keys` and `sender_counter ` from the old manager to the new one.

But, when i checked the agents status from the new master i got nothing.


```
root@new-server:~# /var/ossec/bin/cluster-control -l
ID      NAME         IP                 STATUS     VERSION         NODE NAME
000     new-master   192.168.25.10      Active     Wazuh v3.11.2   manager
```

It is very odd because i know that the worker suppose to manage agents. 
I expected to get at least the list of agents that this specific node manages.

All the nodes are behind a load-balancer that route the data to every working node, i checked and after the node moved from the old master to the new one it was still ok by the LB so it can't be that traffic didn't flow to the node because the LB.

Maybe i should copy the `/var/ossec/var/db` folder too? or something like `/var/ossec/queue/agent-info` `/var/ossec/queue/agent-groups`? 


**Second** , i installed wazuh server by package, and not by the source method.
Is it ok? 
I am asking because in this method it is not possible to choose whether to run wazuh-manager immediately after installation or not, the run happens automatically.


**Third**, is it possible to convert node to be the master?
Following the recent events I got the impression that this process can be less problematic, cause all the cluster data is already there, using this method it is possible to prevent a situation where a new server enters the cluster and becomes the master and overrides the existing cluster data.

I will be very glad for any help, thanks.

**Comment by AdriiiPRodri** [comment]
Hi @Aviv641999,

I will try to answer these questions:

Let's start with the first one, it is not necessary to copy the DBs or the agent-info, this is because the manager is able to regenerate this information as long as the agents connect correctly to it.

As for the second question, it is important that the manager is stopped while we make this process since if it is not like this the file client.keys can be replaced. You can check if this has happened by looking at the content of the file. This would explain why the agents do not connect to the manager, the manager could be rejecting the connection. Therefore my recommendation is to first stop the Wazuh service, replace the files and then start the service again:

```
service wazuh-manager stop
```

Move files and then:

```
service wazuh-manager start
```

Finally, yes, it is possible to turn a worker node into a master. In the current model, it is convenient to add the new manager as a worker to synchronize the cluster files. After this we can change the type of manager to master. To choose the role of a manager node you can follow this part of the [documentation](https://documentation.wazuh.com/3.11/user-manual/reference/ossec-conf/cluster.html?highlight=cluster#node-type).

We have pending a guide that describes how to perform this process step by step. We hope to have it as soon as possible.

I hope I have solved your doubts, if you have any other questions, don't hesitate to ask.

Regards

**Comment by AdriiiPRodri** [comment]
Close this issue due to inactivity. Feel free to reopen it if you have any questions.

Regards
