### ISSUE TITLE
Wazuh virustotal integration permission denied 

### ISSUE THREAD

**Issue by y0d4a** [wazuh/wazuh#6348]
Hi,

just enabled integration with virustotal and after restart manager getting permission denied:
2020/10/20 16:28:36 ossec-integratord: ERROR: (1103): Could not open file '/var/ossec/logs/alerts/alerts.json' due to [(13)-(Permission denied)].

# ls -la /var/ossec/logs/alerts/
total 36745280
drwx------. 3 ossec ossec          55 Oct 20 16:32 .
drwxrwx---. 8 ossec ossec         219 Oct 20 16:29 ..
drwxr-x---. 4 ossec ossec          28 Oct  1 00:00 2020
-rw-r-----. 2 ossec ossec 19902249762 Oct 20 17:13 alerts.json
-rw-r-----. 2 ossec ossec 15059932071 Oct 20 17:13 alerts.log

**Comment by 0xN3utr0n** [comment]
Hi @y0d4a ,
With which permissions is `ossec-integratord` running now? 

Please, share the output of:
`# ps -uax | grep integrator`

My guess is that the process is running as an unauthorized user without enough privileges to access `alerts.json`. For reference, the expected owner should be `ossecm`, who should belong to the `ossec` group. You can check out this in `/etc/passwd`:
```
ossec:x:992:989::/var/ossec:/sbin/nologin
ossecm:x:991:989::/var/ossec:/sbin/nologin
ossecr:x:990:989::/var/ossec:/sbin/nologin
```
Note that the three of them share a common group 989(which is ossec as per my `/etc/group`).

**Comment by y0d4a** [comment]
Seems it is correct?

passwd:
ossec:x:987:983::/var/ossec:/sbin/nologin
ossecr:x:986:983::/var/ossec:/sbin/nologin
ossecm:x:985:983::/var/ossec:/sbin/nologin

group:
ossec:x:983:ossec,ossecr,ossecm

**Comment by 0xN3utr0n** [comment]
Alright, although you didn't paste the `ps` output I'll just assume the process' owner is `ossecm`. Aside from the basic Linux privileges, are you using any other security mechanism such as SELinux or Apparmor?  Perhaps ACLs? 

It's quite odd that only `integratord` module is giving that kind of error... By the way, which wazuh-manager version is currently installed?

**Comment by y0d4a** [comment]
Sorry, forgot, but you are right:
`ossecm     18883  0.0  0.0  48920  3204 ?        Sl   00:42   0:00 /var/ossec/bin/ossec-integratord`

and yes, selinux is enabled by default..

**Comment by 0xN3utr0n** [comment]
If it's possible, then go ahead please. Wazuh comes with a default SELinux config, but maybe in your environment is not working correctly.

In order to replicate the error I need more information:
Which distribution are you using? The Wazuh-manager was installed from a package or from source? And which is its version?

Thanks and sorry for the inconvenience.

**Comment by y0d4a** [comment]
no problem at all!
I disabled selinux and it is same.

App version: 3.13.1 - installed from package (yum).
Wazuh app for Kibana 7.9.1
CentOS Linux release 8.2.2004 (Core)

**Comment by 0xN3utr0n** [comment]
Great, thanks @y0d4a. I'll test it out ASAP, and hopefully come back with a more proper answer.

**Comment by y0d4a** [comment]
no problem, thank you for looking into it.

**Comment by 0xN3utr0n** [comment]
@y0d4a  After several trials, I managed to reproduce the error (only once though). There may be several reasons why it showed up, but in any case check out this:
https://github.com/wazuh/wazuh/blob/c94a45249da5b544d74569c0fdf72fe7cb88826c/src/os_integrator/integrator.c#L44-L52
The above source code works like this:

- Open the `alerts.json` file. If for whatever reason it's not possible, try it again. Keep doing it for 100 times, until at least one succeeds. 
- If the file is successfully opened, show the message:` "JSON file queue connected."` (With debug enabled)
- Otherwise: `"Could not open JSON queue after 100 tries."` 

Which one is your case? 
The  error `ossec-integratord: ERROR: (1103): Could not open file '/var/ossec/logs/alerts/alerts.json' due to [(13)-(Permission denied)].`  appears once per try, meaning that if the file is totally inaccessible, a total of 100 error messages will be logged.

Therefore, even when that error might show up once or twice, `integratord` should still be able to work properly.

By the way, as I previously said, the error appeared once in my environment, but after restarting everything worked fine.

**Comment by khangcnttspkt** [comment]
hey @y0d4a 
can you tell me how did you fixed it?
I have same error with you
