### ISSUE TITLE
Feature request: add group parameter to delete agents via API

### ISSUE THREAD

**Issue by sergiospa** [wazuh/wazuh#6366]
Hello team

Removing (unregistering) all the agents that belong to a group of agents should be an easier task. Right now, the only way to do so is to list all agents in a group and delete them by adding their IDs as a parameter in a `DELETE` query. I propose adding a `groups` parameter in the `DELETE /agents` query to facilitate this task.

Example: we should be able to run a query like the following to delete all agents in the `test` agent group:

```
DELETE /agents?groups=test&older_than=10s&purge?pretty
```
The parameter should also accept multiple groups separated by commas:
```
DELETE /agents?groups=test,anothertest&older_than=10s&purge?pretty
```
Another alternative could be adding the `q` param. An example of usage could be:
```
DELETE /agents?older_than=10s&purge&q="groups=test"
```

Regards,
Sergio.

**Comment by Selutario** [comment]
## Issue update

Hi team!

I am researching the best way to do what is requested here. However, at the moment, I cannot find the correct way to integrate it with the corresponding RBAC permissions and without creating a different endpoint to `DELETE /agents`. 

When removing an agent, the required permissions and resources must be `agent:delete` and `agent:id:{agent_id}`. Therefore, the agents returned after expanding the groups in `groups_list` must also be inside the `agent_list` returned by the RBAC decorator.

The problem is that if we want to keep only one endpoint, there is no way to discern whether if an empty list of groups is due to the user not specifying any group, or the user having no permissions over any group. 

The first approach can be seen below:
```Python
@expose_resources(actions=["group:read"], resources=["group:id:{group_list}"], post_proc_func=None)
@expose_resources(actions=["agent:delete"], resources=["agent:id:{agent_list}"],
                  post_proc_kwargs={'exclude_codes': [1701, 1703]})
def delete_agents(agent_list=None, backup=False, purge=False, status=None, older_than="7d", use_only_authd=False,
                  group_list=[]):
    """Deletes a list of agents.

    :param agent_list: List of agents ID's.
    :param backup: Create backup before removing the agent.
    :param purge: Delete definitely from key store.
    :param older_than:  Filters out disconnected agents for longer than specified. Time in seconds | "[n_days]d" |
    "[n_hours]h" | "[n_minutes]m" | "[n_seconds]s". For never_connected agents, uses the register date.
    :param status: Filters by agent status: active, disconnected or never_connected. Multiples statuses separated
    by commas.
    :param use_only_authd: Force the use of authd when adding and removing agents.
    :return: AffectedItemsWazuhResult.
    """
    result = AffectedItemsWazuhResult(all_msg='All selected agents were deleted',
                                      some_msg='Some agents were not deleted',
                                      none_msg='No agents were deleted'
                                      )
    agents_in_groups = set()
    for group in group_list:
        agents_in_groups.update(expand_group(group))

    if agents_in_groups:
        agent_list = agent_list + list(set(agent_list).intersection(agents_in_groups))
```

Only agents which are allowed in RBAC (agent_list) can be deleted. If a group which contains agents is specified, and only those agents inside the group which are also in agent_list (RBAC allowed) can be deleted. 

However, with said approach we are forced to specify the list of agents to be deleted AND the group, or 'all' agents and the group, so this is not any improvement if we compare it with the original use case.

I'll keep on researching.

Regards,
Selu.

**Comment by Selutario** [comment]
## Issue update

Hi team!

Finally we have decided to give a little change to the issue. The `DELETE /agents` endpoint has been modified so it accepts the same filters as `GET /agents`. Therefore, now it is possible to delete agents based not only on the group to which they belong, but also on any of the fields below:
- status
- older_than
- q
- os.platform
- os.version
- os.name
- manager
- version
- node_name
- name
- ip
- registerIP

So for example, with the query below we would delete all Windows agents:

> DELETE /agents?agents_list=all&status=all&older_than=0s&os.platform=Windows

`Status` and `agents_list` parameters are still mandatory. The error message has also been changed so it shows all used parameters when an agent did not meet any of them:
```JSON
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 3,
    "failed_items": [
      {
        "error": {
          "code": 1731,
          "message": "Agent is not eligible for removal: some of the requirements are not met -> status: ['all'], older_than: 0s, os.platform: Windows",
          "remediation": "Please, make sure the agent meets the requirements."
        },
        "id": [
          "199",
          "200",
          "201"
        ]
      }
    ]
  },
  "message": "No agents were deleted",
  "error": 1
}
```

## To do
- Fix and improve/extend related unit tests so they test all the new fields.
- Fix and improve/extend related integration tests.
- Changelog.
- Update documentation.

Regards,
Selu.

**Comment by Selutario** [comment]
## Issue update

Hi team!

Unittests and integration tests in `test_agent_DELETE_endpoints.tavern.yaml` have already been updated and extended.

## To do
- Update and extend RBAC integration tests for agent_endpints.

Regards,
Selu.
