### ISSUE TITLE
[WPK] Reduce queries execution time

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#6384]
|Wazuh version|Component|Install type|
|---|---|---|
| 4.1 | wazuh-modulesd | Manager |

The upgrade module takes a long time to answer an API request when the number of agents is large.

Most of this time is spent executing the following queries:

- Request the status of the last task for each agent to verify that there is no task in progress.

- Create the tasks in the tasks DB for each agent.

To reduce this time, it is necessary to implement bulk queries. Regardless the number of agents, we should compile and execute:

- One query to ask for the status of all agent tasks.

- One query to insert all the tasks in the DB.

**Comment by MiguelCasaresRobles** [comment]
Hello team,

I am reopening the issue because we've faced the limitation of the API for upgrade agents and it seems it's because of this.

Currently, it is only possible to upgrade 100 agents per request as per the documentation: https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.put_upgrade_custom_agents

Even if we increase this limitation, if the request is delayed because of `modulesd` the task won't be complete at a reasonable time.

Additionally, 100 agents per request, it's not reasonable to be used in a production environment. If we want to upgrade 30.000 agents, we would need to perform 300 requests to the API.

The goal here is to give the users the possibility to upgrade all the agents with only one call. Ideally, later in the WUI with a button. 

Regards,

Miguel Casares

**Comment by TomasTurina** [comment]
Solved here: https://github.com/wazuh/wazuh/issues/8939
