### ISSUE TITLE
Vulnerability detector problem changing interval

### ISSUE THREAD

**Issue by PerkinTahmaz** [wazuh/wazuh#6403]
|Wazuh version 3.12 |Vulnerability |Open Source | Ubuntu 18.04|

Hello, I am having hard times with changing the vulnerability detection interval, currently the scan happens every 4 or 6 hour, I want to decrease the vulnerability detection time to 1 hour, how is this possible?

ossec.conf:

```
  <vulnerability-detector>
    <enabled>yes</enabled>
    <interval>5m</interval>
    <ignore_time>1h</ignore_time>
    <run_on_start>yes</run_on_start>

    <provider name="canonical">
      <enabled>yes</enabled>
      <os>trusty</os>
      <os>xenial</os>
      <os>bionic</os>
      <os>focal</os>
      <update_interval>1h</update_interval>
    </provider>

    <provider name="debian">
      <enabled>yes</enabled>
      <os>wheezy</os>
      <os>stretch</os>
      <os>jessie</os>
      <os>buster</os>
      <update_interval>1h</update_interval>
    </provider>

    <provider name="redhat">
      <enabled>yes</enabled>
      <update_from_year>2010</update_from_year>
      <update_interval>1h</update_interval>
    </provider>

    <provider name="nvd">
      <enabled>yes</enabled>
      <update_from_year>2010</update_from_year>
      <update_interval>1h</update_interval>
    </provider>

  </vulnerability-detector>
```

**Comment by chemamartinez** [comment]
Hi @PerkinTahmaz,

The scan runs every 5 minutes by default, as you can see in the `interval` parameter.

Since Vulnerability Detector runs in the manager, a high frequency allows scanning new connected agents quickly. That's why the `ignore_time` option exists. It permits to skip packages that have already been analyzed, so the amount of alerts in that period is reduced to the vulnerabilities of newly installed packages and agents.

If you want to get the complete report every scan, you just have to decrease that `ignore_time` to, for example, one minute.

Here you can read more about the Vulnerability Detector configuration: https://documentation.wazuh.com/4.0/user-manual/reference/ossec-conf/vuln-detector.html

If your manager's version is 3.12, I highly recommend that you update your environment to the latest version available. The Vulnerability Detector has undergone major improvements in these versions.

Best regards,
Chema.
