### ISSUE TITLE
NVD vulnerability detector database cannot be disabled

### ISSUE THREAD

**Issue by aglarendil** [wazuh/wazuh#6411]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.2 | Vulnerability Detector | Manager | Packages | Ubuntu 16.04 |

Hi there, we faced an issue when trying to work only with upstream Canonical database - vulnerability detector does not work it all without nvd json files being downloaded. It is not even possible to set nvd provider to 'enabled:no', wazuh does not seem to respect these settings. Thus, we get ' ERROR: (5582): Unavailable vulnerabilities at the NVD database. The scan is aborted.' error and cannot get the detector to work without downloading dbs from NVD, which is not our intention.

**Comment by danimegar** [comment]
Hi @aglarendil 

From Wazuh 3.13.0 on, we made NVD primary feed for both Linux and Windows environments to improve the detection rate and reduce the number of false-positives. The VD module follows these steps:
- Get potential vulnerabilities from Linux OVAL (Canonical in your case).
- Get potential vulnerabilities from NVD feeds.
- Packages unaffected or already fixed by the vendor and the packages that depend on packages not installed are discarded.
- Packages that are a dependency not vulnerable are discarded. We use the NVD feed for that,
- Packages not fixed by the OVAL that the NVD said they are not affected are discarded.

 It indeed takes time for the NVD database to build but, in that way, we avoid the VD to report tens or hundreds of false positives. That is why we decided to make NVD a primary feed and it is necessary for the scan.

For RedHat / Centos systems, it is not necessary the NVD feed to complete the scan in Wazuh v3.13.2 but it is necessary for Wazuh v4.0. 

Regards,
Daniel
