### ISSUE TITLE
Log rotation

### ISSUE THREAD

**Issue by y0d4a** [wazuh/wazuh#6423]
Hi, i search over documentation, but did not found what i looking for.
I would like to rotate all logs after... lets say 2-3 weeks.
Is it possible to create that kind of setup?

thank you

**Comment by antoniomanuelfr** [comment]
Hi @y0d4a 

At this moment, the logs are rotated daily or when they reach a certain size.
If you check the [internal options](https://documentation.wazuh.com/4.0/user-manual/reference/internal-options.html#monitord) for monitord, you may find usefull the option `monitord.keep_log_days`. The logs will be rotated daily and the will be deleted after that period of time. 

I will leave this issue oppened and the team will discuss the implementation of this feature. 
Sorry for the inconvenients that may be caused.

Kind regards.
Antonio

**Comment by y0d4a** [comment]
ok, thank you.
I changed in internal options:
monitord.keep_log_days=15
and restart wazuh manager, but he did not remove old data?

**Comment by antoniomanuelfr** [comment]
Hi  @y0d4a 

The `keep_log_days` will remove the already rotated logs after 15 days (in your case). I'm going to create an environment in order to test this option and I will reply as soon as I have an answer.

Regarding the second question, I think that the option of removing the logs using the usage of the partition has some problems. Other applications may fill the same partition and recent logs may be deleted.

In my opinion, the best solution is to establish a size limit for the logs that are generated by Wazuh. If you take a look at the option `monitord.size_rotate` ([internal options](https://documentation.wazuh.com/4.0/user-manual/reference/internal-options.html#monitord)) you can set that limit. 

Kind regards

**Comment by y0d4a** [comment]
ok, so i can free delete old data on fs?
just for example rm -rf /var/ossec/logs/alerts/2020/Sep/ ?
because today is 28, i have enough data so far

**Comment by antoniomanuelfr** [comment]
Hi @y0d4a 
Sorry for the late reply.

Yes, you can remove those logs if they are unnecessary. 

If you want to automate this process, you can setup a cron job in order to remove these files automatically.
You can find more info at this [web page](https://www.cyberciti.biz/faq/how-do-i-add-jobs-to-cron-under-linux-or-unix-oses/)

Hope this information is useful
Kind regards

**Comment by y0d4a** [comment]
no problem at all.
Ok, thank you for confirmation.
Have a nice day.
