### ISSUE TITLE
Alerting Daemon hangup

### ISSUE THREAD

**Issue by mohakkataria** [wazuh/wazuh#65]
Following is a log of slack integration for alerts which we have done.

2017/01/24 11:17:35 ossec-integratord: ERROR: Unable to run integration for slack -> /var/ossec/integrations/slack

After some time, such kind of error message appears out of blue and we stop getting the alerts from the ossec system to our slack channel. Although the alert.log is getting filled with new alerts, but I am unable to get the alerts on slack. And if i check the status of ossec service, it shows as running.

The issue doesnt get fixed until i restart the ossec service

**Comment by vikman90** [comment]
Hi @mohakkataria,

can you tell us what configuration you have? Issue https://github.com/wazuh/wazuh/issues/58 is similar to this one. That's why we created the branch https://github.com/wazuh/wazuh/tree/debug-integrator, with more descriptive messages.

Feel free to test that branch and please write back to us if you receive some more logs that serves as a clue to find the problem.

In the meanwhile we will continue doing some tests on the Integratord.

Thank you very much for your feedback.

Kind regards.

**Comment by Xcess** [comment]
I have the same problem. if the script returns with error code than 0, an error message is printed on the log and the daemon hangs.
