### ISSUE TITLE
[API] [RBAC] Query param to skip some agent from the endpoint `GET /agents/summary/status`

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh#6502]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0 | api |

Hi team!
Some issues with the API endpoint were reported in [#wazuh-kibana-app/issues/2579](https://github.com/wazuh/wazuh-kibana-app/issues/2579). After doing some research, we (frontend-team) need to check with the API team this point:

Regarding the issue about the query `GET /agents/summary/status` doesn't return properly when the current user doesn't have the agent 000 in its permissions.
We use this endpoint to obtain and show the stats. But we are substracting 1 agent by default from the `total` and `active` values. Because we don't consider the manager's agent (000) as such. That's why when an user does't have permission to see the agent 000, the values are showing unproperly.
 So, to resolve this we need some query param (like q=id!=000) in the endpoints `GET /agents/summary/status` and `GET /agents/summary/os` to allow us to skip any agent, then we can remove the substracting logic from our code.

Regards!

**Comment by mcarmona99** [comment]
The framework team decision in order to fix this error has been a different one.

We are not going to consider the agent `000` in both the `GET /agents/summary/status` and the `GET /agents/summary/os` endpoints. This way we will avoid using a `q` parameter so we will not make the issue that complex. 
Not considering 000 will have the same expected consequence.

Regards,
Manuel.
