### ISSUE TITLE
How often Wazuh different database get updated?

### ISSUE THREAD

**Issue by VisakhMV-Coder** [wazuh/wazuh#6518]
Could you please give me the details of the following database frequency of the updates?

1: Wazuh Vulnerability database
2: Wazuh Compliance database
3; Wazuh root-check database

In addition, How can we get the details of the above database updates?

**Comment by MarcelKemp** [comment]
Normally, you can see the frequency of each module in the _ossec.conf_ file, as you can see below:

- Vulnerability detector: 

      <vulnerability-detector>
        <interval>5m</interval>
        <ignore_time>3h</ignore_time>
        <run_on_start>yes</run_on_start>
      </vulnerability-detector>

The database is located here: _/var/ossec/queue/vulnerabilities/cve.db_

- Rootcheck: 

      <rootcheck>
       
       <frequency>43200</frequency>
      </rootcheck>

The database files are in the following path: _/path/to/wazuh/src/rootcheck/db/_

Although the policy monitoring files are deprecated, as that functionality is now in the SCA module.

- Compliance: 

It does not have a database, but every time rules are modified or developed, it is updated.

It is represented in a mapping within the wazuh rules, so that when a rule is shown, its compliances are associated with it. And they are stored in the following folder: _/var/ossec/ruleset/rules/_

I hope my answer helps you. If you have any other questions, don't hesitate to ask.
