### ISSUE TITLE
Exploratory testing for the new agents' connection status management

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#6519]
### Description

As part of the [Epic 5887](https://github.com/wazuh/wazuh/issues/5887) final exploratory testing should be done in order to validate the right behaviors of all the scenarios involved and affected by this implementation.

The list of scenarios that should be verified is:

- **Upgrade**:
- [x] Upgrade from different Wazuh versions to verify that the `connection_status` column is correctly created in `global.db`.
- [x] Verify that agents in `active` state with an old Wazuh version are properly upgraded.

- **Remoted**:
- [x] Register agents and verify that they are in status `never_connected`.
- [x] Start the Wazuh agents and verify that the agents are properly set to `pending` and then to `active`.
- [x] Stop the manager, stop the agents and start the manager to verify that the agents' connection status is reset to `disconnected`.

- **Monitord**:
- [x] Having a manager with an agent registered and `active`. Stop the agent and check that after `20s` is set to `disconnected`, and after `2m` is alerted.
- [x] Enable the `delete_old_agents` in `3m`. Having a manager with an agent registered and `active`. Stop the agent and check that after `20s` is set to `disconnected`, after `2m` is alerted, and after `3m` is removed.
- [x] Enable the `delete_old_agents` in `1m`. Having a manager with an agent registered and `active`. Stop the agent and check that after `20s` is set to `disconnected`, and after `1m` is removed.
- [x] Repeat the tests with times different than the default values.

- **Wazuh cluster**:
- [x] Verify that the agents' connection status is properly reported in the Master node when the agents are reporting either to the Master or the Worker nodes.

- **Vulnerability Detector**:
- [x] Verify that the scans are properly executed to the manager itself and all the agents in `active` state.

- **agent_control**:
- [x] Verify that the tool lists correctly the agents' connection status in all the execution modes.

**Comment by pereyra-m** [comment]
### Test results

Some manual tests were performed on a cluster environment: 
 - 1 worker and master 4.1  _(dev-connection-status)_
 - 1 Agent 3.13.2
 - 1 Agent 4.0

With a **default** configuration, it was confirmed (with the _agent_control_ tool and directly in the DB) that the agents showed the correct/expected value in these situations:
- Active (agents reporting normally)
- Disconnected (an alert was generated after the corresponding time)
- Active after disconnected (an alert was not generated)
- Never connected (agent registered but never turned on)
- Pending (the agent's startup is being carried on, temporary state)
- Disconnected before a server's restart (no alert generated)
- Disconnected after a server's restart (previously active)

With the _delete_old_agents_ setting:
- A value less than _agents_disconnection_alert_time_, the agent is removed and not alerted
- A value greater than _agents_disconnection_alert_time_, the agent is reported and then removed

Custom configuration values:
- Invalid parameters cannot be configured
- Different disconnection times were configured in worker and master, so the databases are not consistent for a while

The _logs/ossec.logs_ files in the worker and master didn't have any warning nor error messages.

In the case of a worker, it was unnecessarily adding the disconnected agents to the table in memory, and it was fixed in the PR [6516](https://github.com/wazuh/wazuh/pull/6516).
Also, it was noted that the active status is stored in the DB when the manager stops, and it becomes _disconnected_ when it backs online a few seconds later. An user may not ask directly to the database for the agent's status if the manager is not active.

**Comment by DProvinciani** [comment]
I just finished the testing execution. I don't have any specific findings to report in terms of behavior. But, related to the code, there is something that could be improved in the way that the `pending` status is currently set.

As you can see [here](https://github.com/wazuh/wazuh/blob/dev-connection-status/src/remoted/manager.c#L181), the `pending` status is set by using the `wdb_update_agent_keepalive` Wazuh DB helper. This simplifies the way in which we also set the agent in a `syncreq` status in order to be taken into account to be synchronized in the cluster.

The thing is that this is not semantically correct, because the `HC_STARTUP` message is not a keepalive update. So, although this does not result in unexpected behaviors, the right behavior here should be just set the connection status and the cluster synchronization status.

**Comment by palaciosjeremias** [comment]
### Test results
**Framework**
- 1 master manager 4.1
- 1 worker manager 4.1
- 1 agent 4.0

Tests:
- Check minimal configuration values for agents_disconnection_alert_time and agents_disconnection_alert_time.
- Check invalid values of agents_disconnection_alert_time and agents_disconnection_alert_time.
- Check that connection status is propagated thru worker and master.
- Check status and info of agents that change from worker/master.
- Check connection status SM when: 
-   Agents got disconnected after pending status previous active status.
-   Agents with enrollment
- Check delete_old_agents configuration and correct agent removal.
- Check default configuration values even if they are missing in ossec.conf.

**Observations:**
- Minimum config times needs to be changed as targeted on [PR ](https://github.com/wazuh/wazuh/pull/6540)

**Comment by DProvinciani** [comment]
Considering the comments and the fix implemented. Closing the issue.
