### ISSUE TITLE
Error when trying to modify some rule: 3013 - Error communicating with socket: timed out

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh#6530]
|Wazuh version|Component|Install type|Install method |
|---|---|---|---|
| 4.0.0-40005 | wazuh-api| Manager | Packages |

Hello team,

A community user has reported a problem when trying to modify a rule. The error that appears is the following:

![image](https://user-images.githubusercontent.com/23462183/98385783-ae144000-204f-11eb-87f2-e0f25a6a9656.png)

I have been trying to reproduce this case using the same configuration as the user, but I have not been able to get this error. The checks that I have made have been the following:

- I have upgraded from `3.13.2` to `4.0.0` and modified the rules from the kibana interface.

- I have checked the custom user rules, and I have not seen any errors. They are imported correctly.

- I have validated the `ossec.conf` configuration and there are no syntax errors.

- I have imported the `ossec.conf` file shared by the user, edited the rules, and got no error.

Here is attached the error obtained in the [api.log](https://github.com/wazuh/wazuh/files/5502244/api.log.txt) error and the [ossec.conf](https://github.com/wazuh/wazuh/files/5502243/ossec.conf.txt) file.

It is required to investigate this case, to see if it is possible to find the cause.

The original thread is https://groups.google.com/forum/#!topic/wazuh/DEYe7_0bDlM.

Best regards.

**Comment by CarlosRS9** [comment]
# Status Update

I finally managed to replicate the issue reported by the user. I'm still working on this to find the root cause of the issue, as it is difficult to replicate it.

It seems the `GET /manager/configuration/validation`  is taking more than 5 seconds to validate the configuration even when its a valid one. We can see in the ossec.log the following message when the timeout is raised:
```
ossec-execd: ERROR: (1210): Queue '/var/ossec/queue/alerts/execa' not accessible: 'No such file or directory'
```

It is necessary to find out exactly under which circunstances this endpoint endpoint is taking more than 5 seconds to validate the configuration and why.

**Comment by CarlosRS9** [comment]
# Status Update

I have finally managed to replicate the user problem consistently. It seems the configuration validation process is run in a slow environment the process may take more than 5 seconds to finish an because of that the API raises a timeout when waiting for the answer in the socket.

I have checked the validation process and it takes less than 2 seconds to finish which means the additional delay that causes the timeout comes from the communication process with the socket and not from the checking process itself.

Additionally, I have tested a workaround modiying the framework to be able to wait a few seconds before raising the timeout from the socket and in that case the timeout does not occur. However, the final solution should be to determine where the true bottleneck is being introduced and whether it is justified or not.

**Comment by CarlosRS9** [comment]
# Status Update

As stated in the previous update, it is possible to get a timeout if we run the endpoint in a very slow environment. This is because when we create the socket used by the API to wait for the validation result (`execa`) in `core/manager.py` we are setting its timeout to 5s. It should be a valid value, as in a regular environment it should take around 2-3 seconds to get a response from the validation in the `execa` socket. However, in a very slow environment the Core validation operation may take up to 8 seconds to return the response in the socket, hence triggering the timeout.

Therefore, the bottleneck is in the Core part, as the full workflow (from the moment it receives the `check-manager-configuration` request until it returns the response) takes more than 5s seconds in very slow environments.

I checked what Core is doing to validate the configuration and the process consists of running the daemon binaries with the `-t` parameter. However, if I run those binaries with the `-t` in my slowed down environment, it always takes less than 3 seconds, while if I run it in the regular environment (without slowing down), it only takes 1.8s.

Therefore, the validation process itself is taking only 3 of those 8 seconds, and the rest of the time is related to the Core or communication process. Because of that, we propose to increase our timeout value from 5s to 10s to allow the usage of this endpoint in those problematic environment.
