### ISSUE TITLE
[Question] RoadMap and clarification

### ISSUE THREAD

**Issue by andel7** [wazuh/wazuh#657]
Hi,

I have a few questions - would really appreciate your response:
1. Are there ways to monitor ELB logs and S3 access Logs like you currently monitor CloudTrail?
2. Do you have plans to integrate Wazuh with Google Cloud Platform ?
3. How Wazuh can detect intrusion for container based or serverless apps.

Thanks in advance for your help

**Comment by chemamartinez** [comment]
Hi @andel7,

First of all, thank you for sharing your questions, I think they are very interesting and I will do my best to try to clarify them. In addition, I encourage you to open a thread on our mailing list when you have more questions like these ones since I think it will have more visibility and it makes sense discuss topics like this in there.

I share you the link to the mailing list: https://groups.google.com/forum/#!forum/wazuh

**1. Are there ways to monitor ELB logs and S3 access Logs like you currently monitor CloudTrail?**

In our case, we have internal deployments where we are monitoring these logs, we actually forward logs from ELB and S3 to the monitored CloudTrail bucket. In the following link of the AWS documentation you have an example of doing this:

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudtrail-logs.html#cloudtrail-event-records

Despite this, ELB and S3 logs are not in JSON format, so custom decoders are needed to decode and process these logs. In more simple words, the CloudTrail wodle reads all the logs stored in the S3 bucket, if you are able to store in that bucket logs from ELB and S3 access, the wodle will also read that logs.

To find a workaround for doing this, you could take a look into the [aws.py](https://github.com/wazuh/wazuh/blob/stable/wodles/aws/aws.py) script, in charge of process and send CloudTrail logs to the Wazuh module.

In our roadmap is planned to integrate this feature to the current CloudTrail Wazuh module, but we still do not know when it will be available.

**2. Do you have plans to integrate Wazuh with Google Cloud Platform?**

There is no doubt that it would be a significant improvement for Wazuh. It is also on our roadmap and one of the reasons is because Kubernetes works really fine in GCP.

It would be very useful if you tell us about your needs on this point, or if you have any idea about how to face this integration.

**3. How Wazuh can detect intrusion for container-based or serverless apps.**

I am not very familiarized with this kind of applications, but I think Wazuh performance for serverless apps would depend on several factors such as the accessibility of the application or the security policies. Probably, there is no problem when talking about FIM (File Integrity Monitoring) or log collection.

However, other components as Rootcheck (which monitors running processes in the system among other things) would not work properly due to the restricted environment where serverless apps run.

I hope it helps, and if you have any other doubt don`t hesitate to ask us.

Best regards,
Chema.

**Comment by mjflve** [comment]
Hi,

Here are some decoders sent by a community user for AWS Load Balancer:

https://groups.google.com/d/msg/wazuh/OJbGue7DhDk/3vpy5_vXDQAJ

Regards,
