### ISSUE TITLE
syscheck schedule : Changed attributes: group_name bug

### ISSUE THREAD

**Issue by vladimir-monari** [wazuh/wazuh#6592]
Wazuh version | Component | Install type | Install method | Platform
-- | -- | -- | -- | --
wazuh-agent-3.13.2 | syscheck  | Agent | Packages |  Red Hat Enterprise Linux Server 7.8

Hello,

Whenever syscheck run in scheduled mode, it generates file integrity changed attributes: group_name alerts. These alerts are wrong and contains bad values.

**For example:**
![example](https://user-images.githubusercontent.com/2751340/99057275-dba34100-259b-11eb-8b89-289af6dd3f1d.jpg)

**The associated alert received on the manager contains a special character **(▒)** :**
** Alert 1605194358.158309561: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2020 Nov 12 16:19:18 (myhostname) any->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/usr/lib/udev/hwdb.d/20-acpi-vendor.hwdb' modified
Mode: scheduled
Changed attributes: group_name
Group name was 'root', now it is 'dbus :x : 81
▒'
Attributes:
- Size: 126596
- Permissions: rw-r--r--
- Date: Fri Oct 18 18:48:22 2019
- Inode: 340
- User: root (0)
- Group: dbus:x :81
▒ (0)
- MD5: bb7e486aff51fd1b4b1b87500d6f8f0f
- SHA1: 17b4a08d9f132cba7b67d1dffc9022545b7b6a07
- SHA256: dd1a1ec65452eb63a18804a59af08f3d06d2f18c248bb21f4da81629ba758ed2

When I check the agent database from the manager I see the group name is always "root":
_select * from fim_entry where file like "%/usr/lib/udev/hwdb.d/20-acpi-vendor.hwdb%";_

file|type|date|changes|size|perm|uid|gid|md5|sha1|uname|**gname**|mtime|inode|sha256|attributes|symbolic_path|checksum
/usr/lib/udev/hwdb.d/20-acpi-vendor.hwdb|file|1605196184|1|126596|rw-r--r--|0|0|bb7e486aff51fd1b4b1b87500d6f8f0f|17b4a08d9f132cba7b67d1dffc9022545b7b6a07|root|**root**|1571417302|340|dd1a1ec65452eb63a18804a59af08f3d06d2f18c248bb21f4da81629ba758ed2|||670a8ffe9ac5c2417a6104c83b8767d8e2bc6def

This behavior is only present in scheduled mode and not in real time or data mode.

Also, if I select the distinct groupe name in the db, I see stranges values like :
_sqlite>  select distinct gname from fim_entry;_
**gname
slocate**
**osse**

I cannot understand the difference in the syschek execution of the different modes.

Please can you help me to debug that ?

Best regards,

**Comment by 0xN3utr0n** [comment]
Hi @vladimir-monari ,
I've been trying to reproduce your bug, alas, to no avail. Furthermore, Its the first time we've seen that odd behavior, so we will need some debugging in order to find out the cause. 

Let's start with the agent, since we already have enough information about the manager. Try to run the following SQL query in the fim database (agent's side).

`sqlite3 /var/ossec/queue/fim/db/fim.db "SELECT path, group_name FROM entry_data INNER JOIN entry_path ON inode_id = entry_data.rowid WHERE path='the path of the file';`
**Don't forget to customize the query with your own file path.**

In addition, run syscheckd in debug mode and try to reproduce again the bug (change the group name):

 1. Set `syscheck.debug=0` to **2** in `/var/ossec/etc/internal_options.conf`
 2. restart wazuh-agent
 3. The debug output will appear, as usual, in the `ossec.log`.

**Comment by vladimir-monari** [comment]
Hi **@0xN3utr0n**,

When I run the sql command I get this result:
/usr/lib/udev/hwdb.d/20-acpi-vendor.hwdb|root

Also, after activating syscheck.debug=2 and restarting the agent, if I search the same kind of modification, I see for example:

2020/11/14 20:22:44 ossec-syscheckd[1864] syscheck_audit.c:901 at audit_parse(): DEBUG: (6247): audit_event: uid=root, auid=, euid=root, gid=ossec, pid=1867, ppid=1, inode=657463, path=/var/ossec/logs/ossec.log, pname=/var/ossec/bin/ossec-syscheckd
2020/11/14 20:22:44 ossec-syscheckd[1864] run_check.c:114 at send_syscheck_msg(): DEBUG: (6321): Sending FIM event: {"type":"event","data":{**"path":"/etc/selinux/targeted/active/modules/100/minissdpd/lang_ext"**,"mode":"scheduled","type":"modified","timestamp":1605381760,"attributes":{"type":"file","size":2,"perm":"rw-------","uid":"0","gid":"0","user_name":"root",**"group_name":"ossec"**,"inode":531080,"mtime":1604588218,"hash_md5":"c483f6ce851c9ecd9fb835ff7551737c","hash_sha1":"6d3236ec3c88039ca534b81acad564e847ecb062","hash_sha256":"d53315bea08cec50d2591fcaf3b32dc5d289cdc6c16b7e8bed8c8e3f7ceaa34e","checksum":"7dcd70773a7e035c78ee68c3836d513ce44e4d2a"},"changed_attributes":["group_name"],"old_attributes":{"type":"file","size":2,"perm":"rw-------","uid":"0","gid":"0","user_name":"root",**"group_name":"root"**,"inode":531080,"mtime":1604588218,"hash_md5":"c483f6ce851c9ecd9fb835ff7551737c","hash_sha1":"6d3236ec3c88039ca534b81acad564e847ecb062","hash_sha256":"d53315bea08cec50d2591fcaf3b32dc5d289cdc6c16b7e8bed8c8e3f7ceaa34e","checksum":"c3e2d880e5cd6bf2f1b64ac5f14f134dd4d938f1"}}}

And when I run the sql command, I get this result :
/etc/selinux/targeted/active/modules/100/minissdpd/lang_ext|root

I have the same behaviour, on many agents and different cluster managers.

**This only happens when syscheck runs in scheduled mode, it sees the file integrity attributes changed, but only on: group_name.**

I think the name of the group hasn’t been changed and it’s a false positive, because otherwise real-time verification would generate an alert as well.

**Comment by 0xN3utr0n** [comment]
Hi @vladimir-monari ,
Thanks for detailed answer, but there's something I still don't quite understand:
> I think the name of the group hasn’t been changed and it’s a false positive, because otherwise real-time verification would generate an alert as well.

Could you please confirm this statement? The `group_name`values that appear in the `fim.db` are in fact the correct ones? Then the `dbus` group name that appears in your first massage it's not the right owner of `/usr/lib/udev/hwdb.d/20-acpi-vendor.hwdb`, right? At first I though the issue was only the invalid character you previously mentioned. 

If that's the case that would mean that the alerted logs are indeed false-positives.

**Comment by vladimir-monari** [comment]
Hi @0xN3utr0n,
Yes, because the dbus group doesn’t exist on the host... I don’t understand where these values come from.

**Comment by 0xN3utr0n** [comment]
Hi @vladimir-monari ,

Apologies for the delay, I'm trying to find the cause for this abnormal behavior. One last question, do any of the agents or O.S where this bug is taking place have anything in common? Are all of them `RHEL7` and `Wazuh-3.13.2`?

**Comment by vladimir-monari** [comment]
Hi @0xN3utr0n, 

Yes, that's it !

**Comment by 0xN3utr0n** [comment]
Got it, thanks. I'll reach you as soon as I have a proper answer.

**Comment by vladimir-monari** [comment]
Thank you 0xN3utr0n !

**Comment by 0xN3utr0n** [comment]
Hi @vladimir-monari ,
Sorry for the delay, we've been investigating this in more detail:

- The first bug (`dbus` group), we suspect that somehow your `/etc/group `or `/etc/gshadow` file is corrupted. Perhaps the `dbus` group does really exist but Wazuh fails to correctly fetch it due to the invalid values. 
Just to make sure of this, could you please manually check if such group (`dbus`) appears in any of those files? Running the command [grcpk](https://linux.die.net/man/8/grpck) would be useful too.

- Regarding the second bug, are you consulting `fim.db` immediately after the alerts show-up? SQlite mainly works with a cache (in memory), and it updates the database file from time to time. Waiting a few minutes would be the correct approach. By the way, is there any way to replicate this behavior? Or it just happens at Syscheck's startup?

**Comment by vladimir-monari** [comment]
Hello @0xN3utr0n, it took me a little while to respond as well.

Regarding the 1st bug, I'm sorry for my previous aswer, You are right, the group exists.
When y launch grpck only, I don't see any error.
If I launch  grpck dbus, I see : Memory fault...

Regarding the 2nd bug, when I consult the database several hours after the alert for the file whose group would have been modified, I always find the initial group.

After investigations on my side, the bug appeared from start of July following an upgrade of wazuh version v3.11.4-1 to version 3.12.3-1.

Since then we have upgraded to version 3.13.0 and 3.13.2 without this bug resolution.

**Comment by 0xN3utr0n** [comment]
Hi @vladimir-monari ,
Thanks for the feedback. I'm still trying to reproduce the bugs, but with no success so far. The most concerning thing is that the data used in `send_syscheck_msg` is fetched from the database, yet it looks like the db it's no being updated with the latest changes.

It's imperative for us to somehow reproduce the errors. Have you tried manually reproducing any of the bugs? That is, by modifying the group of a test file, does `Syscheck` update the db accordingly?

And regarding the `grpck` command, I think the correct way is:  
`sudo grpck -r /etc/group ` 
_(No output is a good sign)_

**Comment by Molter73** [comment]
We have identified a race condition between whodata and the rest of the modes of operation. It was reported in [this comment](https://github.com/wazuh/wazuh/issues/6708#issuecomment-762809280)

We will fix the problem be replacing this call to `getgrgid` with a call to `w_getgrgid` and duplicating the group name string before returning from `get_group`. https://github.com/wazuh/wazuh/blob/26ef346265232ed4f248b463ef428ed9cf640182/src/shared/syscheck_op.c#L599
