### ISSUE TITLE
build issue during directory copy

### ISSUE THREAD

**Issue by rnbwkat** [wazuh/wazuh#66]
when building wazuh ossec on different platforms, a user may encounter a build issue with a new install.  Steps required:
1. clone wazuh per directions. Run normal install, for example, server, installs with no issues
2. copy same folder over to a new host to install, for example, an agent. Run install for agent, system fails at agent-auth build. This is caused because a change in the build platform, in one example, RHEL 6 to 7 or RHEL 7 to Debian and a "make clean" is not inferred during a normal build process.

Suggestion is to add a "make clean" before the build process, if binaries are detected in any of the src folders.

**Comment by vikman90** [comment]
Hi @rnbwkat,

Thank you for your feedback. I think a `make clean` is always recommended before a new build. Doing it automatically at `install.sh` could be disadvantageous because there are some cases in that we would run `make` before `install.sh` for making some tunings.

For instance, if we want to compile the entire project with debugging symbols and using 4 threads to boost the process, we would run:

> `make -C src clean`
> `make -C src -j4 DEBUG=yes TARGET=manager`
> `sudo ./install.sh`

Nevertheless we will think about it, maybe it's interesting to add a line at `install.sh` to remember users to clean the previous build.

Thank you again.
Best regards.

**Comment by rnbwkat** [comment]
Good points - I would just like to add - one of the reasons OpenSource does not take off more is that the teams trying to install are at more beginner to intermediate levels. When they encounter a compile error when trying to install and have no resources to resolve them, they get frustrated and move to COTS. I am only suggesting either the documentation might be better written, or perhaps offering an option to clean up from a previous build.  I honestly have no issue with this, but I want this tool to be used by more and more entities, and because of that, it must be mistake-proof no matter what.

Thanks
Kat
