### ISSUE TITLE
[Needs research] Manager receiving logs after uninstalling agent

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh#662]
Hello team,

According to this [mailing list thread](https://groups.google.com/forum/#!topic/wazuh/9iyYETgtHzc), the manager still generates alerts from an agent, even after uninstalling it. Also, the agent appears active.

Maybe we should take a look at this in some time. But I think that this is not a bug, it's just the manager finishing the last alerts with the data received from the agent, although it's been already uninstalled.

The user only uninstalled the agent package, and didn't remove it from the manager using the API or the `manage_agents` tool.

I've tried to reproduce this on my environment without success, everything seems to work right.

Regards,
Juanjo

**Comment by vikman90** [comment]
Hi @JuanjiJG,

Sorry for the late reply.

- The agent is still active: there is a known 30-minute delay to detect an agent as disconnected.
- According to the list thread, logs are still reachable because they are stored in the alerts file and in Elasticsearch. They won't disappear even if the agent is deleted.

Let me close this issue.
Best regards!
