### ISSUE TITLE
Review how the MSU is working with patches for Microsoft software

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#6717]
### Description

When the Microsoft Update Catalog is read and the MSU generated, it is included patches for Windows software apart from the OS. Let's see an example:

[CVE-2018-0978](https://nvd.nist.gov/vuln/detail/CVE-2018-0978)

The NVD configurations look like:

![image](https://user-images.githubusercontent.com/29475387/100081351-344dc600-2e47-11eb-98aa-17a5f56ee458.png)

The application and OS scan are separated in the Windows scanner, the application scan is based on version comparison, so for this case, it will check if the Internet Explorer coming from Syscollector is less than 10. But the MSU entry is not checked:

```
{
                    "patch": "4230450",
                    "product": "Internet Explorer 10 on Windows Server 2012",
                    "restart_required": "Yes",
                    "subtype": "IE Cumulative",
                    "title": "Internet Explorer Memory Corruption Vulnerability",
                    "url": "https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4230450"
}
```

We have to decide between:

- Adding the capability to correlate Windows software such as Internet Explorer, Word, Office, etc. with the MSU patches.
- Filter that patches from the MSU, where there are not used.

More examples:

```
- KB4484268
- KB4486738
- KB4461577
- KB4484299
```

**Comment by MarcelKemp** [comment]
Based on the research carried out, I have observed the following points to consider:

- There are some windows patches to cover the vulnerabilities of the applications which microsoft is the vendor. That is, when updating windows and applying patches, internally they are updating the default applications along with their version. Examples: 
  - https://support.microsoft.com/en-us/help/4461577/descriptionofthesecurityupdateforexcel2010december112018 
  - https://support.microsoft.com/es-es/help/4486738/security-update-for-office-2010-november-10-2020.

- But in the case of NVD, these are usually related to the _program_ together with its _major version_, or to the _program related to the affected OS_ (like the example described in the issue). So according to the decision to be made, it would be necessary to **check the msu** to know if the vulnerability has been fixed.

- Also, I have found a windows software ([Microsoft 365 e5](https://www.microsoft.com/en-us/microsoft-365/enterprise/e5?activetab=pivot:overviewtab)), which contains access to its windows defender API. This API already collects all the windows software installed on the machines, and also obtains its vulnerabilities. If there is a patch that fixes the vulnerability, it also tells you what it is. 
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/get-all-vulnerabilities-by-machines

- Finally, in order to verify that microsoft applications do not have vulnerabilities, it would be necessary to: 

   - Firstly, modify syscollector to be able to collect them. Then we would check if vulnerabilities are found in the NVD, in the case of having Microsoft as a vendor and there is a vulnerability, activate the hotfix tag and check the CVEs in the MSU, in the same way that we check the vulnerabilities of the system. Note that currently if there is no patch installed on the OS (it can happen on newly installed OS), the MSU will not be queried.
