### ISSUE TITLE
[API] Investigate and solve API timeout issues in big environments

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#6744]
Hello team,

We have been observing some API timeouts (asyncio timeout) with `GET /agents` call in loaded cluster environments (40k+ agents, 4+ cluster nodes). It is possible the error is affecting others endpoints also.

We need to investigate the origin of these problems and propose a solution.

Regards,

David J. Iglesias

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by davidjiglesias** [comment]
### Status update:

We have concluded there is an issue with using `wazuh-db` and the big quantity of queries the `framework` is performing to obtain the necessary system resources to apply RBAC permissions.  It does not scale linearly when trying to expand `agent:group` type permissions and it takes a long time to process if there are thousand of agents and they are inside a different bunch of agent groups. 

We have propose a short term solution to this problem and will be further study and investigating a long term solution maintaining the use of the `wazuh-db`. For the said short term fix we:
- Obtain agents in the system parsing client.keys instead of wazuh-db queries.
- Obtain groups in the system reading /var/ossec/etc/shared folders instead of wazuh-db queries.
- Obtain agents belonging to a group or groups parsing agent-group files instead of wazuh-db queries.P

Doing so reduces the computation time dramatically:
![image](https://user-images.githubusercontent.com/48716145/100434135-5724e800-309c-11eb-8a50-a21d8b862cf9.png)
![image (1)](https://user-images.githubusercontent.com/48716145/100434143-58eeab80-309c-11eb-8a1c-3e90a3cac7aa.png)

**Comment by AdriiiPRodri** [comment]
## Status update (Decorator)

Starting in the Framework, when a function is invoked we go inside the **decorator**.

The first part of the decorator is the **get_required_permissions**, this is to split the information we need into variables.

The second part is the one that has the weight, inside **match_permissions** in black case we always have one more expansion, this is because the starting point in this case are all the resources and we remove them, in the white case we start with an empty set and we fill it. This initial expansion is based on the type of resource, for example agent:id. According to this, the black mode will always have a little more load.

Then would go the single_processor which is where the burden of the decorator is. Within this function the resource expansion function is called. You can call the resource expansion function twice, the second time being an individual call (a specific resource, for example `agent:id:001`).

When the `*` is expanded within **expand_resources** the function **get_agent_info** is called if the resource is `agent:id` or the function **expand_group** if the resource is `agent:group`. In both functions there is a certain delay (in debugger tests). This occurs for each call as long as the user has in his permissions `agent:id:*` or `agent:group:ANY`. The **get_agents_info** function is cached.

The **single_processor** function is called as many times as the framework function requires. And within **single_processor** it will be invoked to **expand_resource** as many times as the user has permissions. For example, if the user has permissions on `agent:group:west` and `agent:group:east`, it is called twice to **expand_resource** and therefore twice to **expand_group**. In case the user has permissions on `agent:group:*` (all groups) and `agent:group:west`, first all the groups will be expanded, including the **west** group and later the **west** group will be expanded again individually. Here we could have a context variable that is valid for this particular case (first `agent:group:*` and then another `agent:group:ANY`) because in the first expansion is also expanded subsequent groups.

Regards

**Comment by Selutario** [comment]
## Issue update

Hello team, below are the results of unittests after updating those which were failing:
### core/cluster/tests/test_utils.py
```
=============================================== test session starts ===============================================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.8.2, pluggy-0.13.1
rootdir: /home/selu/Git/wazuh/framework
plugins: metadata-1.10.0, testinfra-5.0.0, tavern-1.2.2, cov-2.10.0, asyncio-0.14.0, html-2.0.1
collected 7 items                                                                                                 

framework/wazuh/core/cluster/tests/test_utils.py .......                                                    [100%]

================================================ 7 passed in 0.05s ================================================
```
### core/tests/test_agent.py
```
=============================================== test session starts ===============================================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.8.2, pluggy-0.13.1
rootdir: /home/selu/Git/wazuh/framework
plugins: metadata-1.10.0, testinfra-5.0.0, tavern-1.2.2, cov-2.10.0, asyncio-0.14.0, html-2.0.1
collected 187 items                                                                                               

framework/wazuh/core/tests/test_agent.py .................................................................. [ 35%]
........................................................................................................... [ 92%]
..............                                                                                              [100%]

=============================================== 187 passed in 1.27s ===============================================
```
### tests/test_agent.py
```
=============================================== test session starts ===============================================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.8.2, pluggy-0.13.1
rootdir: /home/selu/Git/wazuh/framework
plugins: metadata-1.10.0, testinfra-5.0.0, tavern-1.2.2, cov-2.10.0, asyncio-0.14.0, html-2.0.1
collected 90 items                                                                                                

framework/wazuh/tests/test_agent.py ....................................................................... [ 78%]
...................                                                                                         [100%]

=============================================== 90 passed in 2.74s ================================================
```

Regards,
Selu.
