### ISSUE TITLE
The alarm is not generated by my custom rules

### ISSUE THREAD

**Issue by bth8939** [wazuh/wazuh#6760]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v3.13.2_7.9.1 | Wazuh component | Manager/Agent | kubernetes EKS | AMZ2 |

Hello,

I try adding new decoder and rule but i can't see the alarm in the dashboard.
=> https://documentation.wazuh.com/4.0/user-manual/ruleset/custom.html

The standard alarms work.

### stack
<pre><code>
NAME                            READY   STATUS    RESTARTS   AGE
wazuh-elasticsearch-0           1/1     Running   0          10h
wazuh-kibana-6996d759dd-5c7b8   1/1     Running   0          10h
wazuh-manager-master-0          1/1     Running   0          10h
wazuh-manager-worker-0          1/1     Running   0          10h
wazuh-manager-worker-1          1/1     Running   0          10h
wazuh-nginx-67dcd9997f-lhhcj    1/1     Running   0          10h
</code></pre>

### input
```
Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.100'
```
###  wazuh-manager-master-0
Test with ossec-logtest
```
root@wazuh-manager-master-0:/var/ossec/bin# ./ossec-logtest
2020/11/30 11:54:39 ossec-testrule: INFO: Started (pid: 2085).
ossec-testrule: Type one log per line.

Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.100'


**Phase 1: Completed pre-decoding.
       full event: 'Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.100''
       timestamp: 'Dec 25 20:45:02'
       hostname: 'MyHost'
       program_name: 'example'
       log: 'User 'admin' logged from '192.168.1.100''

**Phase 2: Completed decoding.
       decoder: 'example'
       dstuser: 'admin'
       srcip: '192.168.1.100'

**Phase 3: Completed filtering (rules).
       Rule id: '100010'
       Level: '10'
       Description: 'User logged'
**Alert to be generated.
```
=> /var/ossec/etc/decoders/ex.xml
```
<decoder name="example">
   <program_name>^example</program_name>
</decoder>

<decoder name="example">
  <parent>example</parent>
  <regex>User '(\w+)' logged from '(\d+.\d+.\d+.\d+)'</regex>
  <order>user, srcip</order>
</decoder>
```

=> /var/ossec/etc/rules/ex.xml
```
<group name="local,syslog,sshd,">
<rule id="100010" level="10">
 <program_name>example\</program_name>
 <description>User logged\</description>
</rule>
</group>
```

###  Client redhat 7.7
=> /var/ossec/etc/ossec.conf

```
...
<ossec_config>
  <localfile>
    <log_format>audit</log_format>
    <location>/var/log/audit/audit.log</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/ossec/logs/active-responses.log</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/messages</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/secure</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/maillog</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/test</location>
  </localfile>

</ossec_config>
```

=> logs
```
... 
2020/11/30 11:59:38 ossec-logcollector: INFO: Monitoring full output of command(360): last -n 20
2020/11/30 11:59:38 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/audit/audit.log'.
2020/11/30 11:59:38 ossec-logcollector: INFO: (1950): Analyzing file: '/var/ossec/logs/active-responses.log'.
2020/11/30 11:59:38 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/messages'.
2020/11/30 11:59:38 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/secure'.
2020/11/30 11:59:38 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/maillog'.
2020/11/30 11:59:38 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/test'.
2020/11/30 11:59:38 ossec-logcollector: INFO: Started (pid: 1263).
```

Test write log
```
 echo "Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.100'" > /var/log/test
```

###  wazuh-manager-master-0

The alert not appears on the alerts.log

Can you help me please ?

**Comment by pereyra-m** [comment]
Hello @bth8939 !

Thank you for the detailed description.

I can confirm your custom decoder and rule work, just like you did with _ossec-logtest_, in my environment.
I only had to remove the extra **\\** in the rule, after **example** and **User logged**:

```
  <program_name>example\</program_name>
  <description>User logged\</description>
```

I have also registered an agent and configured the syslog file _/var/log/test_.
I think you may having a permissions issue, because if you don't run the echo command with sudo, the file isn't properly updated. You can use a double **>>** to append data to a file:

`# echo "Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.100'" >>  /var/log/test`

Please, check that the new lines are being written to the log file with `# cat /var/log/test`.
Also, restart both the manager and the agent after every configuration change.

Now, if the alerts still aren't being generated, it may be a connection issue that is preventing the agent to send the events to the manager. Is this agent reporting correctly?
In a cluster, we can check an agent status with the tool `# /var/ossec/bin/cluster_control -a`.

Come back with this new information and we'll solve the issue.
Regards.

**Comment by bth8939** [comment]
it's an error in my message but I put without \ in the server

Finally, it works after restarting manager and agent.

thank you so much

**Comment by pereyra-m** [comment]
Excellent!
Thank you for coming back with the result.

Have a nice day.
Regards.
