### ISSUE TITLE
Change Name of agent?

### ISSUE THREAD

**Issue by killmasta93** [wazuh/wazuh#6814]
Hi I was wondering if its possible to change the name of the agent manually or on the config?
The issue im having a few servers on different sites with the same name 

Thank you

**Comment by mcarmona99** [comment]
Hi @killmasta93 ,

I am afraid to say that for now, it is not possible to change the agent name. To accomplish that you would have to register the agent again. You can find more information about agent registration here https://documentation.wazuh.com/4.0/user-manual/registering/index.html.

I hope this helps, do not hesitate to ask if you have more questions!

**Comment by killmasta93** [comment]
thanks for the reply thats what i needed, so to re register the agent i would run 

`/var/ossec/bin/agent-auth -m 192.168.3.156 -A newagentname`

would i need to delete the agent first?

Thank you

**Comment by mcarmona99** [comment]
Hi again @killmasta93 ,

You don't need to delete the agent. If you follow the documentation I sent, you will be able to re-register the agent. Once you have re-registered, the old "registration" will still appear but as `disconnected`. You can delete it if you want.

I have made some tests in order to show you some examples.

Here you can see my `/var/ossec/bin/cluster-control -a` output. What I have done is:
Re-register `wazuh-agent1` with a new name: `newagent2`. I have upgraded the agent to Wazuh 4.0.0. As you can see the new agent has ID `015` and the output shows the new version, whereas the old registration (`001`) shows the agent as `disconnected` and the old version. I have repeated this process but without upgrading, what ends up with a new registration of the same agent. Finally, I have re-registered the agent and with name `newagent4`. This is the actual registration so the agent is being shown as `active`.
Note that all the agent `IPs` are the same.

```
ID   NAME          IP       STATUS           VERSION        NODE NAME
000  wazuh-master  <IP>     active           Wazuh v4.0.3   master-node
001  wazuh-agent1  <IP_1>   disconnected     Wazuh v3.13.2  master-node

..... (more agents)

015  newagent2     <IP_1>   disconnected     Wazuh v4.0.0   master-node
016  newagent3     <IP_1>   disconnected     Wazuh v4.0.0   master-node
017  newagent4     <IP_1>   active           Wazuh v4.0.1   master-node
```

I hope this helps, ask if you are facing more problems!

**Comment by killmasta93** [comment]
Thank you so much that did the trick, but quick question so in the future to add the name would i run this?

`curl -so wazuh-agent.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.0.0-1_amd64.deb && sudo WAZUH_MANAGER='192.168.3.156' dpkg -i ./wazuh-agent.deb -A agentname`

**Comment by mcarmona99** [comment]
Hi again,

That command is not working for me. Apart from using the `WAZUH_MANAGER` deployment variable, you may have to use the `WAZUH_AGENT_NAME` one in order to give the agent a custom name. You could have a look [here](https://documentation.wazuh.com/4.0/installation-guide/wazuh-agent/deployment_variables/linux/deployment_variables_apt.html#deployment-variables-for-linux-using-apt-repository) to see more Linux deployment variables that could be useful.

Try the following command to deploy an agent with custom name and its manager IP:

`curl -so wazuh-agent.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.0.0-1_amd64.deb && WAZUH_MANAGER='manager-ip' WAZUH_AGENT_NAME='agent-name' apt-get install ./wazuh-agent.deb`

Don't forget to use `sudo` privileges when necessary.

Restart your wazuh-agent and you will see it in the `/var/ossec/bin/cluster-control -a` output.

```
ID   NAME           IP           STATUS           VERSION        NODE NAME
....
014  new_agent_1    <IP>         active           Wazuh v4.0.0   worker1
```

I hope this helps!

**Comment by killmasta93** [comment]
Thank you so much
