### ISSUE TITLE
active response logs not showing in wazuh kibana app

### ISSUE THREAD

**Issue by samcallen** [wazuh/wazuh#6836]
@davidjiglesias i need help. active response is working fine but showing no logs in wazuh kibana app. all logs relating to id 5710 are showing up except acting-response.logs

firewall-drop.sh add - 192.168.2.99 1607204399.2782640 5710

wazuh version 4.0.3

 TAKE A LOOK AT MY LOGS
[no active response logs.txt](https://github.com/wazuh/wazuh/files/5648555/no.active.response.logs.txt)

**Comment by CarlosRS9** [comment]
Hello @samcallen 

Its seems `active-response` is working fine but is not showing in kibana because you have an alert level greater than 3 in your `ossec.conf`. This alert level is used to ignore any alert with a level below this value and the alert for `active-response` has a level `3`, as you can see here:
```
<rule id="607" level="3">
<if_sid>600</if_sid>
<description>Active response: $(script) - $(type)</description>
<group>active_response,pci_dss_11.4,gdpr_IV_35.7.d,nist_800_53_SI.4,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,tsc_CC7.4,</group>
</rule>
```

I suggest you to reduce your alert level value in the master node `ossec.conf` to 3 or lower in case you want to see those alerts in the Wazuh UI. You can find the `ossec.conf` file in `{wazuh_installation_path}/etc/ossec.conf`.

I hope this answer your question.
