### ISSUE TITLE
Centralized configuration - e.g. to change from UDP to TCP traffic

### ISSUE THREAD

**Issue by MidavSec** [wazuh/wazuh#6883]
Hi all,

this seems to be a feature request, please refer to Slack thread -> https://wazuh.slack.com/archives/C0A933R8E/p1607858797122100

I am using Wazuh since version 3.11 and the traffic was to agents was set by default to UDP, before version 4. Now I would like to change all agent configs over centralized agent configuration:

 <client>
    <server>
      <address>dd.hostname.com</address>
      <port>1514</port>
      **<protocol>tcp</protocol>**
    </server>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
    <crypto_method>aes</crypto_method>
  </client>

This fails, because there is no section to update client/server settings. So the ossec.log from the agent shows:
ossec-agentd: INFO: (4102): Connected to the server (dd.hostname.com/192.168.2.56:1514/**udp**) -> instead of TCP.

The target is to apply the changes without using a 3rd party deployment tool, as Ansible, Chef, etc. To accomplish it with Wazuh on-board tools. Would be great if you could implement this function. Thanks!

**Comment by pereyra-m** [comment]
Hello @MidavSec !

Thank you for creating this feature request issue.
After the protocol changed from UDP to TCP in `v4.0`, both manager and agent now have this option as default. When an upgrade is performed, the configuration isn't modified and the previous protocol is kept.

Centralized configuration doesn't allows to modify the protocol of the agents because the manager isn't multiprotocol yet. Thus, modifying the agent protocol leads to missing the communication until the manager modifies the protocol too. This is considered as unsafe.
Fortunately, a multiprotocol manager is in our roadmap, but there isn't an ETA for this feature yet. Once this is developed,  the agent protocol modification will be easier and safer.

But it may be possible to create your own [WPK](https://documentation.wazuh.com/4.0/development/packaging/generate-wpk-package.html) package and perform a custom upgrade of the agents with this change built in.
This upgrade is performed remotely but consider that this procedure will disconnect the agent until the manager updates its own protocol, and the update process will generate error messages due to this situation.

 To [Generate WPK packages manually](https://documentation.wazuh.com/4.0/user-manual/agents/remote-upgrading/create-custom-wpk/generate-wpk-package-manually.html), first a certificate has to be createad ([Get an X509 certificate and CA](https://documentation.wazuh.com/4.0/user-manual/agents/remote-upgrading/create-custom-wpk/create-wpk-key.html#get-an-x509-certificate-and-ca)) and then installed in every agent ([Install the root CA into the agent](https://documentation.wazuh.com/4.0/user-manual/agents/remote-upgrading/create-custom-wpk/create-wpk-key.html#get-an-x509-certificate-and-ca))

If the third party tools aren't an option, or the custom WPK isn't what you are looking for, the manual access to every agent can not be avoided, because even when you create a remote command or script that modifies the `ossec.conf` file, you'd need first to allow it explicitly in `etc/local_internal_options.conf`. So it would be simpler in that case, just to modify the protocol in the agent's `ossec.conf`

I apologize if this is a problem, we'll work on this as soon as possible.

Regards.
