### ISSUE TITLE
New decoder with dynamic field

### ISSUE THREAD

**Issue by greenbitlock** [wazuh/wazuh#6942]
Hi, my name is Sérgio

I am creating custom decoder for my firewall logs. already validated by ossec log test. I would like to know if when we create new fields like msg_id in tag order, it shows this field in kibana.

**Comment by TomasTurina** [comment]
Hi Sérgio,

The logs that get to the Kibana UI are those that match a rule.

Having said that, if your logs are decoded and you include some dynamic fields, all these fields will be added to the alert generated after matching a rule.

In this documentation page, you will find an example of how the dynamic fields are added to the alert:
https://documentation.wazuh.com/4.0/user-manual/ruleset/dynamic-fields.html#dynamic-decoders

The Kibana UI receives all the alerts and shows them in plain and JSON format. Since dynamic fields are part of the alert, you will be able to see them. Also, you can filter alerts by your fields, so you can filter them by the dynamic fields you added.

Let me know if thie information helps you.
