### ISSUE TITLE
Binaries have to resolve the installation path by their own

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#6957]
### Description

In order to avoid to define the installation path when building the Wazuh binaries, now they have to detect the installation folder on runtime, just when they start to run.

The goal of this issue is to develop that detection in every binary start-up.

Research is needed to know how the binaries can guess the absolute path in any condition. If not possible, the installation process should create an environment variable called `$WAZUH_HOME` where the path is stored.

**Comment by MarcelKemp** [comment]
Development branch: https://github.com/wazuh/wazuh/tree/6957-binaries-detect-installation-path

**Comment by MarcelKemp** [comment]
Hello team,

I've decided that the best option to tackle this problem is by getting the installation path of each binary at runtime. For them we use `argv[0]` and the `realpath()` function to know the location of the binary, and then we parse that path.

It is currently being tested on different OSs, and tests related to the new function are being created. 
Below I show the OSs tested so far:

- [x] Linux (Ubuntu)
- [x] Solaris 11
- [x] FreeBSD 
- [x] MacOS 
- [x] Windows
