### ISSUE TITLE
The Wazuh installation should be independent of the PREFIX

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#6960]
### Description

Now, the Wazuh installation process depends on the `PREFIX` defined when building the code. Now, in the installation process the user will define a destination path (`/var/ossec` by default).

This path is used to install the Wazuh instance, as well as the Makefiles for the framework and the API should be adapted to the defined installation path.

**Comment by danimegar** [comment]
[Development branch](https://github.com/wazuh/wazuh/compare/6938-make-wazuh-installdir-independent...6960-wazuh-installation-independent-prefix)

**Comment by danimegar** [comment]
Hello team,

At the moment, I have not deleted `PREFIX` Makefile parameter because this parameter is used during the installation to install Python and other files. However, this parameter has been renamed by `INSTALLDIR` in another [branch](https://github.com/wazuh/wazuh/tree/6959-adapt-makefile-without-prefix) so I did changes in the install script too. 

A question. I have this unusual configuration:
```
cd wazuh/src
make deps INSTALLDIR=/opt/ossec && make INSTALLDIR=/opt/ossec TARGET=server DEBUG=1 -j8
../install (I choose installation in /var/ossec/)
Error:
make[1]: se sale del directorio '/home/user/wazuh/src/external/cpython'
find /var/ossec/framework/python -name "*libpython3.8.so.1.0" -exec ln -f {} /var/ossec/lib/libpython3.8.so.1.0 \;
find: '/var/ossec/framework/python': No existe el archivo o el directorio
make: *** [Makefile:1707: install_python] Error 1
```
The error makes sense but I don't know if we should make this more robust.

Regards,
Daniel

**Comment by danimegar** [comment]
According to the unusual configuration described above, the issue #7177 was opened to decide the best way to adapt the Wazuh python interpreter to be installed in any location. Once the decision is made, it will be easy to finish the development related to this issue.
