### ISSUE TITLE
Getting wrong timestamp in Kibana dashboard

### ISSUE THREAD

**Issue by zakirpcs** [wazuh/wazuh#697]
Hi,

I am getting wrong timestamp in File Integrity log. But in json format timestamp is ok. Please check the below screenshot for better understanding. 
![wazuh-timestamp](https://user-images.githubusercontent.com/39796037/40776943-117f6d42-64ee-11e8-9dd9-4ba7602e13d8.png)
![wazuh-timestamp01](https://user-images.githubusercontent.com/39796037/40776999-4625ee68-64ee-11e8-8b30-a2c4d9a79dcd.png)

**Comment by zakirpcs** [comment]
Please help me out to get rid of this issue.

**Comment by JuanjiJG** [comment]
Hello @zakirpcs,

We could try something to fix this. Kibana can adjust the timezone in use for the timestamp fields. In this case, your Wazuh manager is configured on a different time zone from your Internet browser.

Follow these steps in order to change the timezone Kibana uses:
1. Go to **Management**.
2. Open the **Advanced Settings** tab.
3. On the search bar, type `timezone`.
4. Click on the **Edit** button and select the correct timezone (in this case, the timezone used by your Wazuh manager).

![timezone](https://user-images.githubusercontent.com/10928321/40777788-1dddb3c4-64cf-11e8-8bda-ebf3ffd553a7.png)

Let me know if this works for you.

Regards,
Juanjo

**Comment by zakirpcs** [comment]
I already try this but result is same. Also note that my server and client under NTP and time zone is Asia/Dhaka.

**Comment by gagantous** [comment]
@zakirpcs  i think it's really similar with my problem, and it's solved.

https://github.com/wazuh/wazuh-kibana-app/issues/325

maybe you should install ntp in your OS ?

**Comment by gagantous** [comment]
how do you get that `syscheck,*****` ? i unable to find it in my Discover selected fields...

Which  data template  are you using ? @zakirpcs

**Comment by zakirpcs** [comment]
@Gagantous my both server is under NTP also hwclock is same. What do you mean by syschek? Which data template you are talking about?

**Comment by zakirpcs** [comment]
Please note that, if i set "privacy.resistFingerprinting=true" in firefox browser then syscheck.mtime_before and  syscheck.mtime_after time shows ok but in "Time field" show wrong timestamp. So i think its issue with timezone. Is there any way to set the timezone for syscheck.mtime_before and  syscheck.mtime_after parameter.

**Comment by JuanjiJG** [comment]
Hello again @zakirpcs, and sorry for the late response.

I've tried to change the timezone on my development environment, and all the time fields are updated correctly to the selected timezone, even the `syscheck` ones.

It's not possible to adjust the timezone for different fields on an alert. The time is generated on the manager, and sent through Logstash to store it in Elasticsearch. Elasticsearch generates a timestamp field on the default UTC timezone, and can be quite different from the dates generated on the Wazuh alerts. That's why you can edit the timezone on the Kibana's advanced settings.

Could you please type the following command on your Wazuh manager server and paste here the output?
```
date
```

Let's see if it's using the correct timezone.

Thanks for your patience.

Regards,
Juanjo

**Comment by zakirpcs** [comment]
Hello Juanjo,
Sorry for late response please check the output of date command.
[root@fim]# date
Sun Jun 24 09:49:32 +06 2018

Regards,
Zakir Hossain

**Comment by JuanjiJG** [comment]
Hello again @zakirpcs,

After some researching, I'm still not capable of finding any problem with the timestamp in the alerts. Looking at your first screenshot, I can see that in Kibana, the `timestamp`, `mtime_after` and `mtime_before` have a time difference of +6 hours according to your second screenshot of an alert.

Then, if I modify the `dateFormat:tz` value on Kibana, all of the fields get correctly updated. The fields are treated as a date, and all of them are updated by Kibana according to your timezone preferences.

Let's try something else. Could you please take a screenshot of an alert with `timestamp`, `mtime_after` and `mtime_before` without modifying the `dateFormat:tz` (make sure that you're using the "Browser" value"), and then take another screenshot after setting the timezone to "Asia/Dhaka")?

Thanks for your patience.

Regards,
Juanjo

**Comment by zakirpcs** [comment]
Hello Juanjo,
Result is the same in both scenario. Please check the screenshot for better understanding. 
**date.Format.tz="browser"**
![wazuh-browser](https://user-images.githubusercontent.com/39796037/41888127-b53e5c68-7925-11e8-957e-2db6899d2a17.png)

**date.Format.tz="Asia/Dhaka"**
![wazuh-asia-dhaka](https://user-images.githubusercontent.com/39796037/41888175-e40ff7b8-7925-11e8-81f2-476d62612c6e.png)

**Comment by JuanjiJG** [comment]
Hello again @zakirpcs,

Apologies for my misunderstanding. Now I can see that your browser timezone is in "Asia/Dhaka", so it's expected to see the same timestamps on the alerts on both "Browser" and "Asia/Dhaka".

According to my research, if you set a different timezone, all the `date` fields such as `@timestamp`, `syscheck.mtime_before` and `syscheck.mtime_after` will be affected by the setting. Aren't you getting this result when you modify the timezone? (For example, only the syscheck fileds being affected by the timezone change).

Another thing that I would like to check is the raw JSON alert content. We can see this if you click on a single Alert on Discover (with the syscheck fields), and the open the `JSON` tab. See attached screenshot:

![syscheck](https://user-images.githubusercontent.com/10928321/41893213-47ed12c6-791b-11e8-8ee3-d8b08950e79e.PNG)

As indicated on the image, take a screenshot of an alert with `@timestamp`, `syscheck.mtime_before` and `syscheck.mtime_after` fields on both Table and JSON tabs, and paste here, so we can see the timezone difference applied by Kibana (Elasticsearch store the real timestamp).

Thanks for your patience.

Regards,
Juanjo

**Comment by zakirpcs** [comment]
Hello Juanjo,
Please check the below screenshot for your better understanding.

![wazuh-json](https://user-images.githubusercontent.com/39796037/41895809-d1574940-7944-11e8-98d3-a2172d20182a.png)

Please note that my server timezone is "Asia/Dhaka". Should i change timezone to UTC?

Regards,
Zakir Hossain

**Comment by JuanjiJG** [comment]
Hello again @zakirpcs,

Thanks for your patience on this issue. After more research on how Elasticsearch and Logstash works, I can tell you that the Elastic stack treats the `@timestamp` fields as UTC by default, so Kibana, Logstash, etc hope that the dates are on this timezone.

Given this situation, I recommend you to change the timezone to UTC, so you'll see the dates on the same time as stored on your Wazuh server, which is in "Asia/Dhaka" timezone.

The problem was that Kibana was configured to show the alerts on a timezone of UTC+6 ("Browser" timezone), but your alerts were already on a UTC+6 basis according to your `date` command output, so in other words, you were visualizing alerts on UTC+12 timezone.

I hope this makes everything clear to you. Let me know if you still have more questions about this, we'll be glad to help you.

Regards,
Juanjo

**Comment by zakirpcs** [comment]
Hello Juanjo,
Thanks for your clarification. After change my timezone i will let you know the result.

Regards,
Zakir Hossain

**Comment by JuanjiJG** [comment]
It's been more than a month since the last response to this issue, so I'll proceed to close it.

If you have more questions or problems, feel free to open a new issue, and if it's related to the Wazuh app, you can open the issue on [its repository](https://github.com/wazuh/wazuh-kibana-app/issues).

Regards,
Juanjo

**Comment by peng891025** [comment]
The same problem when i upgraded to version 7.6.1.

**Comment by jsanchez91** [comment]
Hi @peng891025,

The agent syscollector module is storing some dates as local time instead of UTC.
Our colleagues are working on solving this problem, you can check their progress on this topic: #4068 

I hope it helps. Please, don't hesitate to ask again if you have more doubts

Best regards,
Jose.
