### ISSUE TITLE
Wazuh Integrator Memory Error

### ISSUE THREAD

**Issue by arnabnath96** [wazuh/wazuh#7001]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|----|
|4.x | Wazuh Integrator | Manager | Packages/Sources | Debian |

```
sudo python3  /var/ossec/integrations/flock.py /var/ossec/logs/alerts/alerts.json abc:123 https://api.flock.com/hooks/sendMessage/fe710541

Traceback (most recent call last):
  File "/var/ossec/integrations/flock.py", line 19, in <module>
    alert_json = json.loads(alert_file.read())
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
MemoryError
```
```
-rw-r----- 2 ossec ossec 1000M Dec 21 16:16 /var/ossec/logs/alerts/alerts.json
```
file.read() or json.loads() is unable handle very large file.

**Comment by AdriiiPRodri** [comment]
Hi @arnabnath96,

Thank you for reporting this problem. It is possible that in this case the system does not have enough space to handle a file of that size. In Python, objects need some overhead. Because of this when this file is loaded it is highly probable that it takes more memory than disk. My recommendation is that you use [Wazuh log rotation](https://documentation.wazuh.com/4.0/user-manual/reference/ossec-conf/global.html#rotate-interval) to avoid this issue.

This way, besides solving this issue, the files will be easier and faster to handle, improving the speed of Wazuh's processes. It is possible that on the side of the flock.py file you can use an alternative library like [ijson](https://pypi.org/project/ijson/). Although my recommendation is the use of log rotation because if not possible that there are more errors in other processes.

I hope this answer helps you, if you have any doubt, don't hesitate to ask.

Best regards,
Adri Peña

**Comment by AdriiiPRodri** [comment]
Close this issue due to inactivity. Feel free to reopen it if you have any questions.

Regards
