### ISSUE TITLE
Decoder <regex> option and cyrillic characters

### ISSUE THREAD

**Issue by Alex989898** [wazuh/wazuh#7032]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.3 | Wazuh manager | Manager | Packages | Debian 9.9 |

Hello, Team!

If the input log contains the cyrillic characters, it is impossible to parse them with decoder 'regex' option. 
Cyrillic text does not match the expression, but the same decoder works perfect with the english characters in the same log.

I also have the same problem when use 'field' option in rules: if the content of the decoded field is cyrillic, the rule is not triggered.

--
Alex

**Comment by Alex989898** [comment]
decoder 'regex' option
rule 'field' option

**Comment by pereyra-m** [comment]
Hello @Alex989898 !

I apologize for this inconvenient.
Currently, the Cyrillic characters are not supported. All the Wazuh modules work only in ASCII compatible languages, such as English.

There are other related issues, like #4386, #4612 and #6244.
The solution is not trivial because it impacts many features, as FIM for example, and it is already in our roadmap: #6194.

We will solve this as soon as possible.
Regards.

**Comment by Alex989898** [comment]
Thank you for help.

--
Best regards,
Alex
