### ISSUE TITLE
Syscheck Regulation and Disc Usage

### ISSUE THREAD

**Issue by tk129909** [wazuh/wazuh#7057]
Hi,
I used wazuh 3.13. I want to change wazuh configuration to reduce disc usage. By the way, 
1-How can I ignore FIM file tracking with registry_ignore(or other solution?) for windows on wazuh manager server although wazuh agents have some default windows registry entries to monitor. Now, I wrote some registry_ignore line on wazuh server but still log is produced from the defined registry_ignore lines.
2-Can you offer some benchmarks to reduce disc and memory usage? My clustered architecture has one manager and three worker nodes. It consumes approximately, 1TB every week:(
Thank you.

**Comment by jotacarma90** [comment]
Hello @tk129909
For the first point, **ignore_registry**:
- Maybe you are adding the configuration in the manager's **ossec.conf** file, so you are only acting on the manager. To change the agent configuration, you should go to **ossec.conf** in the agent, although we have a method to change the configuration in a centralized way, from the manager:
https://documentation.wazuh.com/4.0/user-manual/reference/centralized-configuration.html
Using this **agent.conf**, you can add as many **ignore_registries** as you need.

Second point:
- A good configuration of Wazuh (more specifically of FIM), requires a deeper analysis to optimize all resources. It is necessary that you analyze all these alerts, to see which are less important or useless. To be able to configure those directories in the right way. For example, ask yourself if it is necessary to use **report_changes** and **whodata** in so many directories, since the great majority of logs that you are going to obtain with those configurations are overloaded and certain information is not necessary.
This way you can drastically reduce the number of logs you will be generating.
Try to control which alerts you want, and with which information fields. And little by little configuring the system in a more optimal way.

Greetings

**Comment by tk129909** [comment]
Hello jotacarma90,
Although I add the below adding to agent.conf, registeries continue to come.
/var/ossec/etc/shared/Clients/agent.conf

<agent_config>
  
  
  <registry_ignore arch="both">HKEY_LOCAL_MACHINE</registry_ignore>
  <registry_ignore type="sregex">HKEY_LOCAL_MACHINE\\Software*</registry_ignore>
  <registry_ignore type="sregex">HKEY_LOCAL_MACHINE\\System*</registry_ignore>
</agent_config>

**Comment by jotacarma90** [comment]
Hola @tk129909
Let's look for the problem then. Before we start, let's make sure that the configuration is all correct. Could you show me the **ossec.log** of some agent with this problem?
The file is located in the **ossec-agent** directory. It would also be helpful to activate the debug mode, in the **local_internal_options.conf** file, by adding `syscheck.debug=2`

When you restart, you can see how all the configuration is established, it would be something of this style:
(It works the same for the registries)

- Example configuration:
```
<directories check_all="yes" realtime="yes" report_changes="yes">C:\testdir</directories>
<ignore>C:</ignore>
```
- ossec.log:

At reset:
```
2020/06/21 22:20:40 ossec-agent[2752] syscheck.c:175 at Start_win32_Syscheck(): INFO: (6003): Monitoring directory/file: 'c:\testdir', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | report_changes | realtime'.
2020/06/21 22:20:40 ossec-agent[2752] syscheck.c:185 at Start_win32_Syscheck(): INFO: (6206): Ignore 'file' entry 'c:'
```

Typical ignore event (with debug syscheck mode ON)
```
2020/06/21 22:20:45 ossec-agent[2752] create_db.c:62 at fim_scan(): INFO: (6008): File integrity monitoring scan started.
2020/06/21 22:20:45 ossec-agent[2752] run_check.c:114 at send_syscheck_msg(): DEBUG: (6321): Sending FIM event: {"type":"scan_start","data":{"timestamp":1592774445}}
2020/06/21 22:20:45 ossec-agent[2752] create_db.c:1164 at fim_check_ignore(): DEBUG: (6204): Ignoring 'file' 'c:\testdir\file1' due to 'c:'
2020/06/21 22:20:45 ossec-agent[2752] create_db.c:1164 at fim_check_ignore(): DEBUG: (6204): Ignoring 'file' 'c:\testdir\new text document.txt' due to 'c:'
```

**Comment by tk129909** [comment]
Hi jotacarma90,
I used sregex shown below to capculate all definitions as th sregex structure. 
agent ossec.conf(just small part)
<windows_registry arch="both">HKEY_LOCAL_MACHINE\Software\Policies</windows_registry>

manager ossec conf
<agent_config>
	
	
	<registry_ignore arch="both">HKEY_LOCAL_MACHINE</registry_ignore>
	<registry_ignore type="sregex">HKEY_LOCAL_MACHINE\\Software*</registry_ignore>
	<registry_ignore type="sregex">HKEY_LOCAL_MACHINE\\System*</registry_ignore>
</agent_config>

As you saw, actually, 'HKEY_LOCAL_MACHINE\Software\Policies' is encapsulated as 'HKEY_LOCAL_MACHINE\\Software*' regex structure. But still they comes shown below


Jan 5, 2021 @ 12:14:25.752 | [x32] HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows NT\Printers\PushedPrinterConnectionStore\{C8859156-32BA-454A-8FBC-F4432CBCCB7D}\{69C4FBCC-8D9F-463D-A510-E2E1A0640A59}
-- | --

**Comment by jotacarma90** [comment]
Hello @tk129909
Ok, after doing an in-depth analysis and some tests, I have found the following problems, and I have a solution.

- In the first line of ignores you have (_<registry_ignore arch="both">HKEY_LOCAL_MACHINE</registry_ignore>_) there is a bug in version 3.13, a conventional ignore will not ignore the events of the subkeys, you can read more in this issue:
https://github.com/wazuh/wazuh/issues/5251
This problem will be fixed in one of the next versions of Wazuh, since the whole log monitoring system will be updated. Anyways, you can use sregex to solve this problem.

- When using the sregex-type ignore, I see a couple of problems:
    - You must set the registry architecture, the same as when you set the monitoring (_arch="both"_).
    - In Wazuh, sregex is not the same as regex, it is a simplified regex for this kind of cases, you can read in our docu:
https://documentation.wazuh.com/4.0/user-manual/ruleset/ruleset-xml-syntax/regex.html#sregex-os-match-syntax
As you can see the `*` is not a symbol allowed in sregex.

Finally, taking into account all these points, your problem would be solved in this way:
```
<registry_ignore arch="both" type="sregex">HKEY_LOCAL_MACHINE\Software</registry_ignore>
<registry_ignore arch="both" type="sregex">HKEY_LOCAL_MACHINE\System</registry_ignore>
```

I hope I have helped, and if any complication or doubt arises, do not hesitate to write again.
Greetings

**Comment by tk129909** [comment]
Hello @jotacarma90
Even if I wrote like your offer, still they comes:(
Config file for agent group:

<agent_config>                                                                                                                                               
                                          
                                   
  <registry_ignore arch="both" type="sregex">HKEY_LOCAL_MACHINE\System</registry_ignore>                                                                          
  <registry_ignore arch="both" type="sregex">HKEY_LOCAL_MACHINE\Software</registry_ignore>                                                                        
</agent_config>  

Logs(Little Part):

![image](https://user-images.githubusercontent.com/54212911/104179358-c6705480-541c-11eb-8627-fc8e408a59db.png)

**Comment by jotacarma90** [comment]
Hello @tk129909
First, we will check that the centralized configuration is working as expected.
To do this you can execute the following commands on the manager side:
- `agent_groups -l` It shows the list of groups that are active in the centralized configuration. The Clients group that you have configured should appear.
- `agent_groups -s -i 004` (You need to change the id for the agent that you are configuring) It shows specifically some data from the agent, it should appear the agent indicated as part of the Clients group.

To be 100% sure, if you have access to the agent, in the ossec-agent\shared folder, you can check that the agent.conf file is correct.

Finally, in the configuration, it is necessary to introduce everything related to the registries within the **syscheck section**. It should be something like this:

```
<agent_config>
  <syscheck>
    <registry_ignore arch="both" type="sregex">HKEY_LOCAL_MACHINE\System</registry_ignore>
    <registry_ignore arch="both" type="sregex">HKEY_LOCAL_MACHINE\Software</registry_ignore>
  </syscheck>
</agent_config>
```

Tell me if you are still having problems!
Greetings, Jose

**Comment by jotacarma90** [comment]
Hello @tk129909 
We have decided to close this issue due to inactivity, if for any reason you need it, feel free to reopen it and we will be happy to help you!
Regards
