### ISSUE TITLE
ossec-hids :: rootcheck

### ISSUE THREAD

**Issue by linuxadmin25** [wazuh/wazuh#7070]
I have installed ossec, and started receiving alerts like 
1) Files hidden inside this directory /xxx/xxxx/xxxx. Link count does not match number of files(2,1).

Is this a false positive or let me know what do i need to check specifically to remove this.

Note :: I have checked the previous posts on this, but answers were not so assuring, that's why opening a new issue.

Thanks 
Tanmay

**Comment by 0xN3utr0n** [comment]
Hi @linuxadmin25 ,
Rootcheck uses two different techniques in order to find out the real number of files within a specific directory. If the reported numbers differ, that will most likely mean:

1. There's a rootkit. That is, one technique has successfully reported the real number of files, even the hidden ones.
2. It's a false positive. There's a chance that a benign process created a file within the time frame between technique1 and technique2.

Either way, you'll need to manually check the suspicious file. In case of doubt, upload it to [virustotal](https://www.virustotal.com/gui/).

Regards,
Fernando

**Comment by 0xN3utr0n** [comment]
Closed due to inactivity. Feel free to open the issue again if you have any related question.
