### ISSUE TITLE
Make Wazuh Server a cluster by default

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#7108]
|Epic|
|---|
| #25208 | 

# Description

Considering the upcoming changes for Wazuh v5.0, one of the new features of the Wazuh cluster is that it will run by default in every Wazuh server installation. This issue aims to study, analyze, and develop a solution to make Wazuh Server installations a cluster by default.

# Requirements

## Functional requirements

- `wazuh-server` must be always running and will be the principal daemon of the Wazuh Server, initializing first before any other daemon that it will start via the Process Control task.
- Define the mechanism to be used for the key management in the encrypted communications between the nodes.
  - The original idea was to use a `.pass` file for the cluster key. Option to load key from configuration or file. If it is not defined it will be automatically generated and added to the file. We might remove the FERNET key and use only the server SSL certificate.
- The `wazuh-server` daemon must be able to capture the sub-processes output and instruct them whether to log messages to a file, remote host or just the standard streams.

## Non-functional requirements

- The cluster default configuration must be changed following the new capacities in the upcoming configuration template.
- `wazuh-server` must be bounded at localhost:1516 by default for security reasons. Currently, it is bonded at 0.0.0.0:1516 by default.

## Implementation restrictions

- The current socket used for the communications must be the one available for the tasks to be carried out by the cluster.

# Plan

- [x] #25228
- [x] #25648
- [x] #25650
- [x] #25651
- [x] #25895
- [x] #25778

> [!NOTE]
> This issue was initially worked in the following branches that should be used as a reference for the starting work:
> - **Working branch:** [dev-7108-cluster-by-default](https://github.com/wazuh/wazuh/tree/dev-7108-cluster-by-default)
> - **Documentation branch:** [dev-7108-cluster-by-default](https://github.com/wazuh/wazuh-documentation/tree/dev-7108-cluster-by-default)

**Comment by Selutario** [comment]
# Epic update

There are some aspects of the design that we need to review again before continuing with the development.

## 1. Removing `fernet-key`
As I have reported here, https://github.com/wazuh/wazuh/issues/13798, when eliminating the pre-shared key (fernet-key), it is necessary to use certificates in the cluster nodes to verify their identity. Otherwise, a Man in the Middle attack could occur.

This would require users upgrading from previous versions to take extra steps to generate certificates or, if they already have (for example, after using the installation assistant in v4.3.0+), modify `ossec.conf` to point to their location. This would be a breaking change so we need to make a decision:
- Keep fernet-key (at least until v5.0.0).
- Use SSL and certificates.

## 2. Reading cluster configuration in other services
Right now every service that needs to know the cluster configuration reads it directly from `ossec.conf`. 

It is intended to remove [this file](https://github.com/wazuh/wazuh/blob/master/src/config/cluster-config.c) and have only `wazuh-clusterd` read the cluster config in the `ossec.conf`. Services should ask `wazuh-clusterd` what is the loaded configuration instead of reading it themselves.

However, we have to decide what the default values should be in case the cluster can't communicate or isn't running for some reason. Only node_name and node_type are required as far as I know. In my opinion, the default values should be:
- **node_name:** Name of the host (if different to `localhost`).
- **node_type:** Master.

## 3. Running tasks and children process if loopback

As part of https://github.com/wazuh/wazuh/pull/13655 we added a new feature whereby certain tasks would not run if the manager is bound to localhost, nor would child processes be created. 

Perhaps it would be interesting if this behavior did not depend on whether it is bound to localhost but on whether there are workers connected. However, the child processes start when the master node starts, which would consume some more unused resources.

An alternative would be to keep this feature and add that, in cases where it is not bound to localhost, some tasks do not start until the connection occurs.

## 4. Loopback by default
Until now the cluster was bound to `0.0.0.0` (all interfaces) by default, but disabled. From now on, the cluster will always be enabled so we have to decide whether to keep `0.0.0.0` as the default `bind_addr` or change it to `localhost`.

**Comment by GGP1** [comment]
## Update

I've created the issues #25648, #25650 and #25651 so we can start making the changes required for the new cluster structure.
