### ISSUE TITLE
No oscap.py and oscap wodle directory

### ISSUE THREAD

**Issue by smolar** [wazuh/wazuh#7110]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.0.3 | oscap | Manager/Agent | Packages/Sources | OS version |

Hello,
I'm trying to run openscap module on wazuh running in docker stack.

ossec.conf:
```
...
  <wodle name="open-scap">
    <disabled>no</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>

    <content type="xccdf" path="ssg-rhel7-ds.xml">
      <profile>xccdf_org.ssgproject.content_profile_pci-dss</profile>
      <profile>xccdf_org.ssgproject.content_profile_common</profile>
    </content>
  </wodle>
...
  ```

Log with debug:
```
2021/01/07 16:38:58 wazuh-modulesd:oscap[2784] wm_oscap.c:269 at wm_oscap_info(): INFO: SHOW_MODULE_OSCAP: ----
2021/01/07 16:38:58 wazuh-modulesd:oscap[2784] wm_oscap.c:270 at wm_oscap_info(): INFO: Timeout: 1800
2021/01/07 16:38:58 wazuh-modulesd:oscap[2784] wm_oscap.c:271 at wm_oscap_info(): INFO: Policies:
2021/01/07 16:38:58 wazuh-modulesd:oscap[2784] wm_oscap.c:274 at wm_oscap_info(): INFO: [ssg-rhel7-ds.xml]
2021/01/07 16:38:58 wazuh-modulesd:oscap[2784] wm_oscap.c:275 at wm_oscap_info(): INFO: 	Profiles:
2021/01/07 16:38:58 wazuh-modulesd:oscap[2784] wm_oscap.c:278 at wm_oscap_info(): INFO: 		Name: xccdf_org.ssgproject.content_profile_pci-dss
2021/01/07 16:38:58 wazuh-modulesd:oscap[2784] wm_oscap.c:278 at wm_oscap_info(): INFO: 		Name: xccdf_org.ssgproject.content_profile_common
2021/01/07 16:38:58 wazuh-modulesd:oscap[2784] wm_oscap.c:281 at wm_oscap_info(): INFO: SHOW_MODULE_OSCAP: ----
2021/01/07 16:38:58 wazuh-modulesd:oscap[2784] wm_oscap.c:48 at wm_oscap_main(): INFO: Module started.
2021/01/07 16:38:58 wazuh-modulesd:oscap[2784] wm_oscap.c:70 at wm_oscap_main(): INFO: Starting evaluation.
2021/01/07 16:38:58 wazuh-modulesd:oscap[2784] wm_oscap.c:187 at wm_oscap_run(): DEBUG: Launching command: /var/ossec/wodles/oscap/oscap.py --xccdf ssg-rhel7-ds.xml --profiles xccdf_org.ssgproject.content_profile_pci-dss,xccdf_org.ssgproject.content_profile_common
2021/01/07 16:38:58 wazuh-modulesd:oscap[2784] wm_oscap.c:216 at wm_oscap_run(): ERROR: Internal error. Exiting...
```  

When i try run it manually, **there is now oscap.py file or any directory in wodle directory**:
```
[root@wazuh-master wodles]# ls -la /var/ossec/wodles/
total 28
drwxr-x---. 6 root ossec 4096 Jan  7 17:15 .
drwxr-x---. 1 root ossec 4096 Jan  7 15:02 ..
drwxr-x---. 2 root ossec 4096 Jan  7 17:14 aws
drwxr-x---. 2 root ossec 4096 Dec 21 21:03 azure
drwxr-x---. 2 root ossec 4096 Dec 21 21:03 docker
drwxr-x---. 2 root ossec 4096 Dec 21 21:03 gcloud
```

Documentation says: 
> Each agent must have its policies in /var/ossec/wodles/oscap/content.

But nothing about source of this files or something...

I found some commit which suggest me that oscap are migrating [here](https://github.com/wazuh/wazuh/commit/bdcb28fcdaa0d5b18c9cbfe86940d4a6c4b0f548) and [here](https://github.com/wazuh/wazuh/commit/f610f883e4f620ef1c9fa28b7bd5d544ebe66a8f#diff-cc200ba6b8c0cbd77989f4b0cb7d5625050a724625dcf1f9d7dea9ad3acc47c4), but I don't found any official information about it and what i can to do now

Please, help. I need this feature.

**Comment by TomasTurina** [comment]
Hello @smolar.

My workmate has explained this in [this slack thread](https://wazuh.slack.com/archives/C0A933R8E/p1607629694483200?thread_ts=1607435219.239300&cid=C0A933R8E).

As it is stated in the [Breaking Changes section](https://documentation.wazuh.com/4.0/release-notes/release_4_0_0.html#breaking-changes) for **Wazuh 4.0.0**, OpenSCAP policies were removed from RPM and DEB packages, and the folder present policies in the agent installation will be removed.

Currently, we recommend you to use SCA instead of configuring OpenSCAP as SCA is our opensource option for hardening, which means increasing the security of hosts by reducing their vulnerability surface. By default, the Wazuh Agent will run SCA scans for every policy (.yaml or .yml files) present in their ruleset folder:

- Linux agents: `<agent-installation-folder>/ruleset/sca`
- Windows agents: `<agent-installation-folder>\ruleset\sca`

For more information about SCA, please take a look to these documentation links:

- [How SCA works](https://documentation.wazuh.com/4.0/user-manual/capabilities/sec-config-assessment/what_is_it.html).
- [SCA configuration](https://documentation.wazuh.com/4.0/user-manual/capabilities/sec-config-assessment/how_to_configure.html).
- [SCA blogpost](https://wazuh.com/blog/security-configuration-assessment/).

In case you still want or need to set up OpenSCAP, you will need to solve the error manually by adding the missing folder `/var/ossec/wodles/oscap`. For doing this, you can download the folder from the [Wazuh GitHub repository](https://github.com/wazuh/wazuh/tree/master/wodles/oscap).

I hope this information helps.

Best regards.

**Comment by smolar** [comment]
Thank you for your answer. I think it will be good for others to write about it in the documentation.
Best regards.

**Comment by Stef-33560** [comment]
Hi,

> Currently, we recommend you to use SCA instead of configuring OpenSCAP as SCA is our opensource option for hardening, which means increasing the security of hosts by reducing their vulnerability surface. By default, the Wazuh Agent will run SCA scans for every policy (.yaml or .yml files) present in their ruleset folder:
> * Linux agents: `<agent-installation-folder>/ruleset/sca`
> * Windows agents: `<agent-installation-folder>\ruleset\sca`

May you please share an example ? I don't understand the link between the ruleset and oscap binary executable :(

> In case you still want or need to set up OpenSCAP, you will need to solve the error manually by adding the missing folder `/var/ossec/wodles/oscap`. For doing this, you can download the folder from the [Wazuh GitHub repository](https://github.com/wazuh/wazuh/tree/master/wodles/oscap).

This folder has flown away !

Thanks !

**Comment by jasminstrkonjic** [comment]
Hi team,

this folder is missing.
Does openscap integration still works on latest wazuh version?

I have managed to go through branches and found python script for verison 3.9 but returned an error fifo line 110.
Found the fix for it but it still does not work.

My agent is in centos 8 stream.
Any help would be great.

Thank you!

**Comment by mrjson79** [comment]
watching this.
