### ISSUE TITLE
Improve LB access logs parsing in AWS integration

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#7168]
|Wazuh version|Component|
|---|---|
| 4.x | AWS module |

AWS module will include LB access logs as a new source of information, but the current parsing mechanism is not extracting IP and ports into separate fields.

This happens because the current parsing uses spaces as the delimiter, but the source and destination IPs and ports follow the `ip:port` syntax.

This is a reference to NLB parsing: https://github.com/wazuh/wazuh/blob/develop-aws-lb/wodles/aws/aws_s3.py#L2077-L2082

Regards,
Javier.

**Comment by Espectro123** [comment]
## Status update

Hello team!

I have started with the development of this issue.

Today I have been studying wazuh's AWS documentation and reading wazuh's AWS related blogs.

I have left the AWS wodle ready to work offline and I have studied the problem to determine what would be the best way to fix it. 

#### Today I have determined that there are three possible solutions:
```
1º Preprocess the .log file to eliminate the separator between the ip and the port

2º Modify the DictReader class to add the necessary functionality to deal with these kinds of problems

3º Process the dictionary after its creation to return the dict in the desire format
```
The second solution has been discarded since the DictReader class is part of the CSV module.

The next day I will continue working on the first and third solutions

**Comment by Espectro123** [comment]
## Status update

Hello team!

The fix is already working. 

Here is an example of the new output returned by the AWSNLBBucket class.

## Logs example

To test the fix, the module has been manually executed, having previously activated the ```logall``` option. The log information has been modified for security reasons.

### Log file

```
tls 2.0 2020-08-01T00:49:02 net/echo-3456-prod-Test/fffffffffd66t i9k2b2c4556k5111 88.11.77.55:66666 10.20.4.220:666 1111 5555 11 222 - ttt www sss us-west-1 100150001675 certificate/es03tt20-111d-1f11-a11e-11111f281t20 - GGFFF-RSA-AES256-TTT-SHA128 tlsv12 - - - - -
```
### Command used

```
/var/ossec/framework/python/bin/python3 /var/ossec/wodles/aws/aws-s3.py -d 2 -a ACCESS -k SECRET -r us-east-1 -t nlb -b wzaccesslogslb
```

### Log output from /var/ossec/logs/archives/archives.log
```
2021 Apr 26 10:46:21 wazuh-master->Wazuh-AWS {"integration": "aws", "aws": {"log_info": {"aws_account_alias": "", 
"log_file": "AWSLogs/1111111111/elasticloadbalancing/us-west-1/2020/07/22/111111111111_elasticloadbalancing_us-west-1_net.demo-3130-prod-Wazuh.gggggggggg_20200722F1950F_2cg47b57.log.gz",
"s3bucket": "wzaccesslogslb"}, "type": "tls", "version": "2.0", "time": "2020-07-22T19:49:15",
 "elb": "net/demo-3130-prod-Wazuh/f279b3dd67f9c98e", "listener": "c3c3c3c3c3c3c3c3c3", 
"client_ip": "88.11.77.55", "destination_ip": "10.20.4.220", "connection_time": "111919", 
"tls_handshake_time": "225", "received_bytes": "32982", "sent_bytes": "69819", "incoming_tls_alert": "-", 
"chosen_cert_arn": "arn:aws:acm:us-west-1:11111111:certificate/7111111111111111111",
 "chosen_cert_serial": "-", "tls_cipher": "TTHHH-FTT-PTT256-GCM-SHA128", 
"tls_protocol_version": "tlsv12", "tls_named_group": "-", "domain_name": "test.test.com", 
"alpn_fe_protocol": "-", "alpn_client_preference_list": "-", "null": "-", "source": "nlb",
"client_port": "66666", "destination_port": "666"}}
```
