### ISSUE TITLE
Add support for SUSE OVAL in Vulnerability Detector

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#7171]
### Description

The aim of this issue is to add native support for vulnerability scans to SUSE OS.

SUSE offers its own OVAL DB: https://www.suse.com/support/security/oval/

### Requirements

- This development will include the following Suse OS versions:
  - SLES 11 desktop
  - SLES 11 server
  - SLES 12 desktop
  - SLES 12 server
  - SLES 15 desktop
  - SLES 15 server 

due to compatibility issues with the SUSE feeds, we are not supporting OpenSuse for now.

Regards,
Javier.

**Comment by GuazP** [comment]
I wonder, there is a way to provide it now not natively? 
So far I looked for it, I can't find which provider for that should I use.

**Comment by danimegar** [comment]
> I wonder, there is a way to provide it now not natively?
> So far I looked for it, I can't find which provider for that should I use.

Hello @GuazP 

At the moment it is necessary to use this option `os allow` to detect vulnerabilities in SUSE. You have to modify the redhat provider in the vulnerability detector section in the ossec.conf.

Example:
```xml
 <provider name="redhat">
    <enabled>yes</enabled>
    <os>5</os>
    <os>6</os>
    <os allow="SLES-12">7</os>
    <os allow="SLES-15">8</os>
    <update_interval>1h</update_interval>
 </provider>
```
Note that this configuration can lead to false positives since each OS vendor handles the package management and security patching by their own.

You can find more details about this option in the [documentation](https://documentation.wazuh.com/4.0/user-manual/capabilities/vulnerability-detection/allow_os.html).

Regards,
Daniel

**Comment by chemamartinez** [comment]
Devel branch: [#7171-suse-vdt](https://github.com/wazuh/wazuh/tree/7171-suse-vdt)

**Comment by StefanSa** [comment]
Hi there @chemamartinez 
First of all, thank you for the good work with Wazuh.
Is there an ETA for SuSe / openSuSe and oval support, maybe. in v4.2 ?
