### ISSUE TITLE
Adapt the Wazuh python interpreter to be installed in any location

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#7177]
### Description

As explained in this [wiki](https://github.com/wazuh/wazuh-jenkins/wiki/How-to-build-Wazuh-Python-interpreter), the Wazuh python interpreted is provided in a pre-compiled version for the default install directory, `/var/ossec`, along with a sources version when the install directory is not defined.

The goal of this issue is to adapt the interpreter to be installed in custom directories without the need of rebuilding it once the destination is set.

For doing this, we have several options in which have to work to choose the one that best fits:

1. The Wazuh repository provides a packaged interpreter, which is precompiled and preinstalled ready to be unpackaged in the installation directory without the need for any extra building.
2. Make the pre-compiled python to be linked and installed in the location defined at installation time, without the need of rebuilding it.

**Comment by danimegar** [comment]
According to the second option, I found two possible options:

**1) This is the easy option: the python interpreter is always installed in /var/ossec/framework/python/.** 
The idea is to move /var/ossec/framework/python/ to INSTALLDIR/framework/python during installation. The problem is that pip3 stop working and installation is interrumped:
```
/opt/ossec/framework/python/bin/pip3
bash: /opt/ossec/framework/python/bin/pip3: /var/ossec/framework/python/bin/python3.8: bad interpreter: No such file or directory
```
However, I found out that pip3 works in this way:
```
# /opt/ossec/framework/python/bin/python3 -m pip

Usage:   
  /opt/ossec/framework/python/bin/python3 -m pip <command> [options]
```
So, it is only necessary to modify:
```
install_python:
	cd ${EXTERNAL_CPYTHON} && export WPATH_LIB=${PREFIX}/lib && export SOURCE_PATH=${ROUTE_PATH} && export WAZUH_FFI_PATH=${EXTERNAL_LIBFFI} && ${MAKE} install
ifneq (${INSTALLDIR},/var/ossec)
	mv /var/ossec/framework ${PREFIX}
endif
	find ${WPYTHON_DIR} -name "*${WLIBPYTHON}" -exec ln -f {} ${PREFIX}/lib/${WLIBPYTHON} \;

python_dependencies := requirements.txt

install_dependencies: install_python
	${WPYTHON_DIR}/bin/python3 -m pip install --upgrade pip --index-url=file://${ROUTE_PATH}/${EXTERNAL_CPYTHON}/Dependencies/simple
	LD_LIBRARY_PATH="${PREFIX}/lib" LDFLAGS="-L${PREFIX}/lib" ${WPYTHON_DIR}/bin/python3 -m pip install -r ../framework/${python_dependencies}  --index-url=file://${ROUTE_PATH}/${EXTERNAL_CPYTHON}/Dependencies/simple
```

**2) More Difficult: Another option is to reconfigure the INSTALLDIR and do the make again just before the make install in case INSTALLDIR is different from /var/ossec/**
```
install_python:
ifneq (${INSTALLDIR},/var/ossec)
    export WPATH_LIB="'\$$\$$ORIGIN/../../../lib'" && export SOURCE_PATH=${ROUTE_PATH} && export WAZUH_FFI_PATH=${EXTERNAL_LIBFFI} && export LD_LIBRARY_PATH=${ROUTE_PATH} && cd ${EXTERNAL_CPYTHON} && ./configure --prefix="${WPYTHON_DIR}" --libdir="${WPYTHON_DIR}/lib" --enable-shared --with-openssl="${ROUTE_PATH}/${EXTERNAL_OPENSSL}" LDFLAGS="${ARCH_FLAGS} -L${ROUTE_PATH} -lwazuhext -Wl,-rpath,'\$$\$$ORIGIN/../../../lib',--disable-new-dtags" CPPFLAGS="-I${ROUTE_PATH}/${EXTERNAL_OPENSSL}" $(CPYTHON_FLAGS) && ${MAKE}
endif
    cd ${EXTERNAL_CPYTHON} && export WPATH_LIB=${INSTALLDIR}/lib && export SOURCE_PATH=${ROUTE_PATH} && export WAZUH_FFI_PATH=${EXTERNAL_LIBFFI} && ${MAKE} install
    find ${WPYTHON_DIR} -name "*${WLIBPYTHON}" -exec ln -f {} ${INSTALLDIR}/lib/${WLIBPYTHON} \;
python_dependencies := requirements.txt
```
In that case, advantage: both python3 and pip3 would work perfectly. The downside is that if the cpython is pre-compiled for /var/ossec, when it should be for INSTALLDIR/ossec (that's in make deps), it takes time to recompile the python during installation. However, if the cpython is well pre-compiled, it takes only about 20 seconds during installation to change the prefixes from /var/ossec to INSTALLDIR/ossec and everything would install correctly.

The problem here is the pre-compilation. We will need to use the INSTALLDIR during `make deps` or do not use the pre-compiled cpython for /var/ossec/.

I think the first option is better and easier.

**Comment by alromeros** [comment]
Regarding the first option:

**Comment by alromeros** [comment]
Regarding the first option:

1. The Wazuh repository provides a packaged interpreter, which is precompiled and preinstalled ready to be unpackaged in the installation directory without the need for any extra building.

As specified in the description, I've tried compressing the dependencies installed in `$INSTALLDIR/framework/python` to the file  `python.tar.gz`, then adding it in the `src/external` directory. Then, I've tried modifying the main Makefile to treat this tar file as a external dependency, just decompressing it in installation time. 

Testing branch v1: https://github.com/wazuh/wazuh/tree/7177-adapt-python-interpreter-v1

**Comment by alromeros** [comment]
Hi team,

**Comment by alromeros** [comment]
Hi team,

Still testing and trying to fix issues within the first option:

**1. The Wazuh repository provides a packaged interpreter, which is precompiled and preinstalled ready to be unpackaged in the installation directory without the need for any extra building.**

As described in my last comment, I tried compressing an already installed and built python interpreter in `$INSTALLDIR/framework/python`, to then proceed testing it in different environments to check it's portability. At the moment, I've found two main issues with this approach:

**1. First error: Python scripts being path-dependent**

The first error I've come to find appears when attempting to use the prebuilt interpreter in a different location from the one used when compiling. For example, using a `python.tar.gz` that was created after a standard installation in `/var/ossec` inside a new installation in `/opt/ossec` causes this next error. Mind that I'm using a fixed Makefile:

```
...

cp external/python.tar.gz /opt/ossec/framework/python.tar.gz && tar -zxf /opt/ossec/framework/python.tar.gz -C /opt/ossec/framework && rm -rf /opt/ossec/framework/python.tar.gz
find /opt/ossec/framework/python -name "*libpython3.8.so.1.0" -exec ln -f {} /opt/ossec/lib/libpython3.8.so.1.0 \;
find: '/opt/ossec/framework/python': No such file or directory
Makefile:1658: recipe for target 'install_python' failed
make: *** [install_python] Error 1
```

This output appears after trying to manually run one script inside the portable folder:

```

# /opt/ossec/framework/python/bin/pip3.8
bash: /opt/ossec/framework/python/bin/pip3.8: /var/ossec/framework/python/bin/python3.8: bad interpreter: No such file or directory
```

After checking the issued script, we find the old path hardcoded inside:

```
[root@manager]# cat /opt/ossec/framework/python/bin/pip3.8
#!/var/ossec/framework/python/bin/python3.8
# -*- coding: utf-8 -*-
import re
import sys
from pip._internal.cli.main import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

Two main solutions come to mind when finding this error: 

- One would involve deleting this next part inside the Makefile, but I'm not sure if the affected scripts would still be necessary outside compilation:

```
install_dependencies: install_python
	${WPYTHON_DIR}/bin/pip3 install --upgrade pip --index-url=file://${ROUTE_PATH}/${EXTERNAL_CPYTHON}/Dependencies/simple
	LD_LIBRARY_PATH="${PREFIX}/lib" LDFLAGS="-L${PREFIX}/lib" ${WPYTHON_DIR}/bin/pip3 install -r ../framework/${python_dependencies}  --index-url=file://${ROUTE_PATH}/${EXTERNAL_CPYTHON}/Dependencies/simple
```

- The other one would involve updating the refference to the new path with a command like sed once Wazuh installation has started. I've personally added a line like this next one inside my Makefile, which can be seen inside this [testing branch]( https://github.com/wazuh/wazuh/tree/7177-adapt-python-interpreter-v1).

`find ${WPYTHON_DIR}/bin/ -type f -exec grep -rlw '/var/ossec/framework/python/bin/python3.8' {} \; -exec sed -i "s|/var/ossec/|${PREFIX}/|" {} \;`

**2. Second error: Error trying to find dependencies after changing environment**

This second error happens when installing Wazuh using the portable python interpreter inside a different system from the one in which it was built. The interpreter I've been testing was built inside an Ubuntu distribution, and it has been unsuccessfully tested in Linux Mint and Centos environments. 

This next error can be seen when attempting to install wazuh-manager:

```
Done building server
Wait for success...
success
Removing old SCA policies...
Installing SCA policies...
Installing additional SCA policies...
mkdir -p /opt/ossec/framework/python
cp external/python.tar.gz /opt/ossec/framework/python/python.tar.gz && tar -zxf /opt/ossec/framework/python/python.tar.gz -C /opt/ossec/framework/python && rm -rf /opt/ossec/framework/python/python.tar.gz
find /opt/ossec/framework/python -name "*libpython3.8.so.1.0" -exec ln -f {} /opt/ossec/lib/libpython3.8.so.1.0 \;
cd ../framework && /opt/ossec/framework/python/bin/python3 setup.py clean --all install --prefix=/opt/ossec/framework/python --wazuh-version=v4.2.0 --install-type=server
/opt/ossec/framework/python/bin/python3: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /opt/ossec/framework/python/bin/../../../lib/libpython3.8.so.1.0)
make: *** [install_framework] Error 1
```

When trying to manually run the Python interpreter, the same error happens:

```
# ./python3
./python3: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /vagrant/bin3/bin2/bin/../../../lib/libpython3.8.so.1.0)
./python3: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /vagrant/bin3/bin2/bin/../../../lib/libwazuhext.so)
./python3: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /vagrant/bin3/bin2/bin/../../../lib/libwazuhext.so)
```

After several attempts importing libraries within the .tar.gz file, I've not been able to find the solution. I've carefully read this next Wiki but I've not come to find the answer: https://github.com/wazuh/wazuh-jenkins/wiki/How-to-build-Wazuh-Python-interpreter

**Comment by alromeros** [comment]
Hi team, 

Just a quick update on the **second error** that was reported in my previous comment: I was encountering a problem when trying to use the portable Python in a different system from the one in which it was built. 

An example of the logs that appeared when trying to run `install.sh`: 

```
...

Done building server
Wait for success...
success
Removing old SCA policies...
Installing SCA policies...
Installing additional SCA policies...
mkdir -p /opt/ossec/framework/python
cp external/python.tar.gz /opt/ossec/framework/python/python.tar.gz && tar -zxf /opt/ossec/framework/python/python.tar.gz -C /opt/ossec/framework/python && rm -rf /opt/ossec/framework/python/python.tar.gz
find /opt/ossec/framework/python -name "*libpython3.8.so.1.0" -exec ln -f {} /opt/ossec/lib/libpython3.8.so.1.0 \;
cd ../framework && /opt/ossec/framework/python/bin/python3 setup.py clean --all install --prefix=/opt/ossec/framework/python --wazuh-version=v4.2.0 --install-type=server
/opt/ossec/framework/python/bin/python3: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /opt/ossec/framework/python/bin/../../../lib/libpython3.8.so.1.0)
```
I finally got the portable interpreter to work in a different system just by following this [wiki](https://github.com/wazuh/wazuh-jenkins/wiki/How-to-build-Wazuh-Python-interpreter)'s advice on building it on a Centos machine for optimal compatibility. I've tested this new portable interpreter in several systems (Ubuntu 20.04, Linux Mint 19.3, CentOS 7 and Debian 10) and everything seems to be working fine.

### Logs

```
...

Extracting api-4.2.0-py3.8.egg to /var/ossec/framework/python/lib/python3.8/site-packages
api 4.2.0 is already the active version in easy-install.pth

Installed /var/ossec/framework/python/lib/python3.8/site-packages/api-4.2.0-py3.8.egg
Processing dependencies for api==4.2.0
Finished processing dependencies for api==4.2.0
cd ../tools/mitre && /var/ossec/framework/python/bin/python3 mitredb.py -d /var/ossec/var/db/mitre.db
Generating self-signed certificate for wazuh-authd...


Starting Wazuh...

 - Configuration finished properly.

 - To start Wazuh:
      /var/ossec/bin/wazuh-control start

 - To stop Wazuh:
      /var/ossec/bin/wazuh-control stop

 - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


   Thanks for using Wazuh.
   Please don't hesitate to contact us if you need help or find
   any bugs.

   Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

   More information can be found at:
          - http://www.wazuh.com

    ---  Press ENTER to finish (maybe more information below). ---


 - In order to connect agent and server, you need to add each agent to the server.

   More information at: 
   https://documentation.wazuh.com/

```

```
user@casa:~$ TOKEN=$(curl -u wazuh:wazuh -k -X GET "https://localhost:55000/security/user/authenticate?raw=true")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   265  100   265    0     0    401      0 --:--:-- --:--:-- --:--:--   400

user@casa:~$ curl -k -X GET "https://localhost:55000/" -H "Authorization: Bearer $TOKEN"
{
    "data": {
        "title": "Wazuh API REST",
        "api_version": "4.2.0",
        "revision": 40200,
        "license_name": "GPL 2.0",
        "license_url": "https://github.com/wazuh/wazuh/blob/4.1/LICENSE",
        "hostname": "casa",
        "timestamp": "2021-01-20T17:18:25+0000"
    },
    "error": 0
}
```

**Comment by alromeros** [comment]
Development branch: https://github.com/wazuh/wazuh/tree/7177-adapt-scripts-to-embedded-interpreter

**Comment by chemamartinez** [comment]
Final devel branch: https://github.com/wazuh/wazuh/tree/7177-make-python-portable
