### ISSUE TITLE
Add /lists/files/{filename} endpoints

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#7180]
|Wazuh version|Component|
|---|---|
| 4.1.0 | Wazuh API |

Hello team,

as part of the epic issue https://github.com/wazuh/wazuh/issues/7148, we need to split the `manager/files` and `/cluster/{node_id}/files` endpoints.

This issue will cover lists files. For that, we need the following new endpoints:
- [x] `GET /lists/files/{filename}`
  - Add option to choose between raw or JSON.
  - **RBAC**: Action `lists:read` (it already exists). Resource `list:path`.
- [x] `PUT /lists/files/{filename}`
  - Raw format required.
  - **RBAC**: Action `lists:update`. Resource `list:path`.
- [x] `DELETE /lists/files/{filename}`
  - **RBAC**: Action `lists:delete`. Resource `list:path`.

These new endpoints require adaptations in the framework in order to have static paths and proper content validation. Remember to update the documentation for these new RBAC actions and resources.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Víctor Fernández.

**Comment by Selutario** [comment]
## Issue update

Hey team!

The implementation of the GET method is almost finished. However, there are some things to point out:
- The endpoint `GET /lists` won't be deleted. It is different to the new `GET /lists/files/{filename}`
- The new endpoint will return the list content either in raw format or as a JSON. However, and as the core function used to get the list content is common for both endpoints, I'm deciding whether it is a good idea to change how the information is returned right now. It would consist of changing this output format:

```JSON
{
  "data": {
    "affected_items": [
      {
        "items": [
          {
            "key": "200",
            "value": ""
          },
          {
            "key": "201",
            "value": ""
          }
        ],
        "relative_dirname": "etc/lists",
        "filename": "security-eventchannel"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All specified lists were returned",
  "error": 0
}
```

To something like this, where the words `key` and `value` are deleted:
```JSON
{
  "data": {
    "affected_items": [
      {
        "items": {
          "AttachLoadBalancers": "Autoscaling",
          "DetachLoadBalancers": "Autoscaling",
          "PutScalingPolicy": "Autoscaling",
          "TerminateInstanceInAutoScalingGroup": "Autoscaling",
          "CancelUpdateStack": "Cloudformation",
          "CreateStack": "Cloudformation"
        },
        "relative_dirname": "etc/lists/amazon",
        "filename": "aws-eventnames"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All specified lists were returned",
  "error": 0
}
```

It is necessary to find out if there is any reason why it is being done this way and what things should be changed in front-end after the changes.

Regards,
Selu.

**Comment by Selutario** [comment]
## Issue update

Hi team! 

All three methods are already developed. Output examples below:

> GET /lists/files/aws-eventnames
(`aws-eventnames` can be found in `/var/ossec/etc/lists/amazon/aws-eventnames`, so it is being searched recursively.)

```JSON
{
  "data": {
    "affected_items": {
      "AttachLoadBalancers": "Autoscaling",
      "DetachLoadBalancers": "Autoscaling",
      "PutScalingPolicy": "Autoscaling",
      "TerminateInstanceInAutoScalingGroup": "Autoscaling",
      "CancelUpdateStack": "Cloudformation",
      "CreateStack": "Cloudformation",
      "DeleteStack": "Cloudformation",
      "UpdateStack": "Cloudformation",
       ...
    },
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "CDB list was returned",
  "error": 0
}
```

> PUT /lists/files/test

```JSON
{
  "data": {
    "affected_items": [
      "etc/lists/test"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "CDB list file uploaded successfully",
  "error": 0
}
```

> DELETE /lists/files/test

```JSON
{
  "data": {
    "affected_items": [
      "etc/lists/test"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "CDB list file was successfully deleted",
  "error": 0
}
```

## To do 
- New unittests
- New API integration tests

Best regards, 
Selu

**Comment by Selutario** [comment]
## Issue update

Hi team!

Unittests are almost finished, only remaining one or two for the new functions of SDK. However, while developing tests for `core/cdb_list` I found out that CDB list validation before uploading a file was not correct. The problem is that lists like below are supposed to be accepted:
```
test-wazuh-w:write
test-wazuh-r:read
test-wazuh-a:attribute
test-wazuh-x:execute
test-wazuh-c:command
test-key:"value:1"
"test-key:1":value
"test-key:2":"value:2"
"test-key::::::3":value3
test-key4:"value:::4"
``` 

But the regex used before uploading the file did not allow more than one double point (`:`), even though it is between quotes. 
https://github.com/wazuh/wazuh/blob/9bd5f49aaad5d614405069c1b7d3a459864dbf06/framework/wazuh/core/manager.py#L237-L256

I developed a new regex that works accordingly to what is accepted inside cdb lists files:
```Python
# This regex allows any line like key:value.
    # If key or value contains ":", the whole key or value must be within quotes:
    # - test_key:test_value     VALID
    # - "test:key":test_value   VALID
    # - "test:key":"test:value" VALID
    # - "test:key":test:value   INVALID
    # - test:key:test_value     INVALID
    regex_cdb = re.compile(r'(?:^"([\w\-:]*?)"|^[^:"\'\s]+):(?:"([\w\-:]*?)"$|[^:]*$)')
```

Regards,
Selu.

**Comment by Selutario** [comment]
|Working branch|
|--|
|[dev-7180-cdb-lists-endpoints](https://github.com/wazuh/wazuh/tree/dev-7180-cdb-lists-endpoints)|

## Issue update

Hi team!

Unittests for the new functions are finished. RBAC actions are:
**lists:read (resource list:path):**
- GET /lists (not new)
- GET /lists/files/{filename}
- GET /lists/files (not new)

**lists:update (resource list:path):**
- PUT /lists/files/{filename}

**lists:delete (resource list:path):**
- PUT /lists/files/{filename}
- DELETE /lists/files/{filename}

## To do
- [ ] Add new API integration tests in `test_cdb_list_endpoints.tavern.yaml`, `test_rbac_black_cdb_list_endpoints.tavern.yaml`, `test_rbac_white_cdb_list_endpoints.tavern.yaml`.
- [ ] Update changelog.md
- [ ] Update RBAC reference in the documentation.

Best regards,
Selu.

**Comment by Selutario** [comment]
## Issue update

Hi team!

There working branch has been recreated in order to merge the new endpoints to 4.1. Now the branch is [https://github.com/wazuh/wazuh/tree/dev-7180-cdb-lists](https://github.com/wazuh/wazuh/tree/dev-7180-cdb-lists).

The way PUT and DELETE methods work has been slightly changed:
- **PUT:** Now, before adding a new file, it is searched if the same filename is used in any subdirectory so future problems are avoided.
- **DELETE:** Now, only files in the root directory (`{wazuh_path}/etc/lists/`) can be deleted. Files are no longer searched recursively to be deleted.

Unittests have been updated so they work after said changes.

I am developing the integrated tests. I am encountering a problem with the output validation. 

Best regards,
Selu.

**Comment by Selutario** [comment]
## Issue update

Hey team,

I fixed an error with response validation in OpenAPI and finished the development of the integration tests (no RBAC) for CDB lists endpoints: `test_cdb_list_endpoints.tavern.yaml`.

However, while developing the integration tests for RBAC CDB lists, we concluded that the RBAC resources for the old endpoints are incorrect. For example: 
```YAML
- actions:
  - lists:read
  resources:
  - list:path:etc/lists/amazon/aws-eventnames
  - list:path:etc/lists/audit-keys
  effect: deny
```

Instead of using a full path as a resource, we should use only the filename. Specially since the new endpoints don't allow any path, only the filename which is searched recursively inside `etc/lists`. The resource will be renamed to `list:file:`. We will discuss some effects this may have on changes in the future (if relative_dirname is replaced by a `group` option, or if default lists are moved to ruleset), but it will solve several problems for now. 

Regards,
Selu.

**Comment by Selutario** [comment]
## Issue update

Hi team,

In order to modify `list:path` resource for CDB lists endpoints, multiple refactorizations of SDK functions have been done to make them work the same way as before.  For example:
https://github.com/wazuh/wazuh/blob/ace86df8fb3b3df7d3468b985cc17f68bb41e86e/framework/wazuh/cdb_list.py#L14-L52

In the function above, the variable used in the `@expose_resources` wrapper (`path`) has been replaced by `filename`. Therefore, the expanded resources are now a list inside `filename` variable. It now looks like this (comments need to be added/updated yet):
```Python
@expose_resources(actions=['lists:read'], resources=['list:file:{filename}'])
def get_lists(offset=0, limit=common.database_limit, select=None, sort_by=None, sort_ascending=True,
              search_text=None, complementary_search=False, search_in_fields=None, dirname=None,
              filename=None):
    """Get CDB lists

    :param offset: First item to return.
    :param limit: Maximum number of items to return.
    :param select: List of selected fields to return
    :param sort_by: Fields to sort the items by
    :param sort_ascending: Sort in ascending (true) or descending (false) order
    :param search_text: Text to search
    :param complementary_search: Find items without the text to search
    :param search_in_fields: Fields to search in
    :param dirname: Filters by dirname.
    :param filename: List of filenames to filter by.
    :return: AffectedItemsWazuhResult
    """
    result = AffectedItemsWazuhResult(all_msg='All specified lists were returned',
                                      some_msg='Some lists were not returned',
                                      none_msg='No list was returned')

    paths = [str(next(Path(common.lists_path).rglob(file), os.path.join(common.lists_path, file))) for file in filename]

    lists = list()
    for path in paths:
        if not any([dirname is not None and os.path.dirname(path) != dirname, not os.path.isfile(path)]):
            lists.append({'items': [{'key': key, 'value': value} for key, value in get_list_from_file(path).items()],
                          'relative_dirname': os.path.dirname(get_relative_path(path)),
                          'filename': os.path.split(get_relative_path(path))[1]})

    data = process_array(lists, search_text=search_text, search_in_fields=search_in_fields,
                         complementary_search=complementary_search, sort_by=sort_by, sort_ascending=sort_ascending,
                         offset=offset, limit=limit, select=select, allowed_sort_fields=SORT_FIELDS,
                         required_fields=REQUIRED_FIELDS)
    result.affected_items = data['items']
    result.total_affected_items = data['totalItems']

    return result
```

`Integration tests are passing fine both for normal and RBAC variants of `GET /lists` endpoint.`

## To do
Due to the increased complexity resulting from the refactor of the resources of this policy, the tasks to be done have been increased: 
- Check that `GET /lists/files` still works the same way as before.
- Update all new failing unittests after the changes.
- Add remaining RBAC integration tests for CDB lists.
- Update changelog.
- Update documentation.

Regards,
Selu.

**Comment by Selutario** [comment]
## Issue update

Hi team,

I'm applying the changes requested in #7375. Some other changes not requested there are also being applied:
- Restructuring the steps within the function `upload_list_file`. (Taking a long time since any small change leads to multiple new use cases which need to be checked).
- Adding a step to back up the original CDB list file before deleting it in `upload_list_file`.
- Moving some common actions (getting full path from a filename) to an external function so it can be used multiple times.
- Debugging to make sure that everything above is working as expected.

## To do
- Apply the minor changes mentioned in the PR.
- Update all failing tests after changes mentioned above.
- Add new unittests to check new funcionts cretaed.
- Run again API Integration tests to make sure nothing is wrong.

Regards,
Selu.
