### ISSUE TITLE
Add /manager/configuration and /cluster/{node_id}/configuration endpoints

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#7181]
|Wazuh version|Component|
|---|---|
| 4.1.0 | Wazuh API |

Hello team,

as part of the epic issue https://github.com/wazuh/wazuh/issues/7148, we need to split the `manager/files` and `/cluster/{node_id}/files` endpoints.

This issue will cover configuration files. For that, we need the following new endpoints:
- [x] `PUT /manager/configuration`
  - XML format required.
  - **RBAC:** Action `manager:update_config`. Resourceless.
- [x] `PUT /cluster/{node_id}/configuration`
  - XML format required.
  - **RBAC:** Action `cluster:update_config`. Resource `node:id`.

These new endpoints require adaptations in the framework in order to make a proper content validation and only perform over the `ossec.conf` file.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Víctor Fernández.

**Comment by CarlosRS9** [comment]
## Status Update

Development of the `GET` endpoints is done. GET `/manager/configuration` and GET `/cluster/{node_id}/configuration` now allows the usage of `raw` parameter.

**Comment by CarlosRS9** [comment]
## Status Update

The development of the `PUT` endpoints is amost done. Only a minor fix to the RBAC action and further testing is needed before considering it finished. 

An bug related to the GET /manager/configuration endpoint has been found. Currently it is not returning the full configuration when not using the `raw` parameter if that configuration contains more than one element with the same name. Here is an example:

**Comment by CarlosRS9** [comment]
## Status Update


The scope of this issue has changed. We have conclude that we are not going to add the `raw` option for the GET endpoints. This issue will focus in develop the new PUT endpoints instead.


Here are the details of the changes applied since the last updated and the status of each endpoint:


### GET /manager/configuration and GET /cluster/{node_id}/configuration

The endpoints have been restored. No modifications are going to be applied to them except for the bug described in the previous state update.


### PUT /manager/configuration and /cluster/{node_id}/configuration

The new endpoinst are finished and working correctly. Here is an example of its output:

```
{
  "data": {
    "affected_items": [
      "master-node"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Configuration was successfully updated in specified node",
  "error": 0
}
```



### Pending

- Review and improve existing tests for the GET requests (in progress)
- Create new tests for the new PUT requests (in progress)

**Comment by CarlosRS9** [comment]
## Status Update

The development is finished. Several unit and integration tests have been created to tests the new endpoints.
