### ISSUE TITLE
Delete event is not being triggered in Solaris when using realtime="yes"

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh#7263]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.4-40011 | FIM | Agent | Packages | Solaris 11.3 |

Hi team,

While testing how the Wazuh plugin for Kibana works with FIM events, I noticed that it doesn't show `delete` events for Solaris 11. After digging into this, I found this event is not triggered by syscheck. Here you have the configuration used in the test and the logs with `debug=2`.
#### Configuration 
```xml
  <!-- File integrity monitoring -->
  <syscheck>
    <disabled>no</disabled>
    <!-- Frequency that syscheck is executed default every 12 hours -->
    <frequency>30</frequency>
    <scan_on_start>yes</scan_on_start>
    <!-- Directories to check  (perform all possible verifications) -->
    <directories realtime="yes">/etc,/usr/bin,/usr/sbin</directories>
    <directories>/bin,/sbin,/boot</directories>
    <!-- Files/directories to ignore -->
    <ignore>/etc/mtab</ignore>
    <ignore>/etc/hosts.deny</ignore>
    <ignore>/etc/mail/statistics</ignore>
    <ignore>/etc/random-seed</ignore>
    <ignore>/etc/random.seed</ignore>
    <ignore>/etc/adjtime</ignore>
    <ignore>/etc/httpd/logs</ignore>
    <ignore>/etc/utmpx</ignore>
    <ignore>/etc/wtmpx</ignore>
    <ignore>/etc/cups/certs</ignore>
    <ignore>/etc/dumpdates</ignore>
    <ignore>/etc/svc/volatile</ignore>
    <!-- File types to ignore -->
    <ignore type="sregex">.log$|.swp$</ignore>
    <!-- Check the file, but never compute the diff -->
    <nodiff>/etc/ssl/private.key</nodiff>
    <skip_nfs>yes</skip_nfs>
    <skip_dev>yes</skip_dev>
    <skip_proc>yes</skip_proc>
    <skip_sys>yes</skip_sys>
    <!-- Nice value for Syscheck process -->
    <process_priority>10</process_priority>
    <!-- Maximum output throughput -->
    <max_eps>100</max_eps>
    <!-- Database synchronization settings -->
    <synchronization>
      <enabled>yes</enabled>
      <interval>5m</interval>
      <max_interval>1h</max_interval>
      <max_eps>10</max_eps>
    </synchronization>
  </syscheck>
```

#### Logs
[ossec.log](https://github.com/wazuh/wazuh/files/5868648/ossec.log)

#### Note
The same test has been performed in Linux and Windows systems and it works perfectly in both systems.

**Comment by BraulioV** [comment]
Update here: This bug appears if the label `realtime="yes"` appears in the conf. Otherwise, it works fine:
![image](https://user-images.githubusercontent.com/9081114/105752387-83979c00-5f47-11eb-8ee2-bd536008dcc7.png)

**Comment by Molter73** [comment]
This problem comes from the configured directory remaining as `realtime` when it should have been configured as `scheduled` when reading the configuration and reporting that realtime is not supported in the OS. We will need to review how we handle the configuration mode on systems that don't support realtime and whodata to fix this issue.

We will also need to look into this fim_db function:
https://github.com/wazuh/wazuh/blob/405b3e00b2ddad59e2add28fbf7b2d2988b90db3/src/syscheckd/fim_db.c#L1065-L1095

Since it validates the configured and the event's mode to match, if a delete event is lost in realtime due to an inotify queue overflow (as an example), once the scan is performed the agent will neither send the delete event, nor update the DB with the deleted entry.
