### ISSUE TITLE
Wazuh parse IIS log access

### ISSUE THREAD

**Issue by hqcthunders** [wazuh/wazuh#7296]
I have problem when config Wazuh agent collect IIS access log. (Examples: Alert's timestamp: 2021-01-27 but Record in access log: 2019-07-18)
![img](https://i.imgur.com/wreFIUE.png)
My question: How can I parse exactly timestamp in IIS access logs ?

**Comment by vikman90** [comment]
Hi @hqcthunders,

The manager tries to automatically detect the timestamp in logs according to the syslog format. In these cases, you will find a member `predecoder` in rules including the timestamp:

```json
{
  "full_log": "Jan 29 18:40:03 groovy sshd[38284]: Accepted publickey for root from 192.168.33.1 port 62841 ssh2: RSA SHA256:uhFanl4fNGvHK/2FON2NbW4MNMZ7m5/xr69XeTmdyQI",
  "predecoder": {
    "program_name": "sshd",
    "timestamp": "Jan 29 18:40:03",
    "hostname": "groovy"
  },
  "decoder": {
    "parent": "sshd",
    "name": "sshd"
  },
  "data": {
    "srcip": "192.168.33.1",
    "dstuser": "root"
  }
}
```

However, IIS has a different format, that's why the manager does not decode it automatically. We can easily extend the decoder regex to include the detection of the timestamp. If I'm not wrong, the corresponding decoder is `web-accesslog-iis-default` ([0380-windows_decoders.xml](https://github.com/wazuh/wazuh/blob/4668d19ea5969daae32dc7e766d9efc6b6163199/ruleset/decoders/0380-windows_decoders.xml#L89-L96)).

Let's extend the `regex` to include the chunk decoded by the parent (remove `offset="after_parent"`), and add the regex in the `prematch` part of the decoder `windows-date-format`:
```xml
<decoder name="web-accesslog-iis-default">
  <parent>windows-date-format</parent>
  <type>web-log</type>
  <use_own_name>true</use_own_name>
  <prematch offset="after_parent">^\S+ GET |^\S+ POST</prematch>
  <regex>^(\S+ \S+) \S+ (\w+) (\S+ \S+) (\S+) \S+ (\S+) (\S+) \.*(\d\d\d) </regex>
  <order>timestamp, action, url, srcport, srcip, user_agent, id</order>
</decoder>
```

This is a sample of the resulting alert:
```json
{
"full_log": "2018-11-27 17:33:25 ::1 GET /app1/oopp – 80 – ::1 Mozilla/5.0+(Windows+NT+10.0;+WOW64;+Trident/7.0;+Touch;+rv:11.0)+like+Gecko – 404 0 2 46",
  "data": {
    "action": "GET",
    "srcip": "::1",
    "srcport": "80",
    "id": "404",
    "url": "/app1/oopp –",
    "timestamp": "2018-11-27 17:33:25",
    "user_agent": "Mozilla/5.0+(Windows+NT+10.0;+WOW64;+Trident/7.0;+Touch;+rv:11.0)+like+Gecko"
}
```

Nevertheless, I'm leaving this issue open for us to make the ruleset decode this field by default.

Hope it helps.
Best regards.
