### ISSUE TITLE
Wazuh AWS integration is not able to finish the analysis of AWS logs in an appropriate time if it has a huge number of objects in the bucket

### ISSUE THREAD

**Issue by maumrsms** [wazuh/wazuh#7351]
Hello team, 

Wazuh AWS integration is not able to finish the analysis of the logs when having a huge bucket. In our case, it took more than 24 hours to finish the process. This may prevent us from analyzing a second bucket because if the process does not finish within the defined interval, it will be restarted before getting to the second one.

As a workaround, the other buckets can be configured on another Wazuh manager or on an agent, but it might be cases when this is not possible to deploy.

**Details:**

- Wazuh Manager version 4.0.4
- AWS service: WAF
- Bucket size: 1.5 TB
- 85,000 objects in the bucket.
- Hardware specs Wazuh manager: 2vCPU and 1GiB RAM

Configuration example:

```
<wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>24h</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>yes</skip_on_error>
    <bucket type="waf">
      <name>bucket_name1</name>
      <access_key>access_key1</access_key>
      <secret_key>secret_key1</secret_key>
    </bucket>
    <bucket type="waf">
      <name>bucket_name2</name>
      <access_key>access_key2</access_key>
      <secret_key>secret_key2</secret_key>
    </bucket>
  </wodle>
```
  

Enabled debug logging and this is the output we get in **ossec.log**:

```
2021/02/08 17:23:13 wazuh-modulesd[18690] main.c:97 at main(): DEBUG: Created new thread for the 'aws-s3' module.
2021/02/08 17:23:13 wazuh-modulesd:aws-s3[18690] XXXX:XX at XXXX(): INFO: Module AWS started
2021/02/08 17:23:13 wazuh-modulesd:aws-s3[18690] XXXX:XX at XXXX(): INFO: Starting fetching of logs.
2021/02/08 17:23:13 wazuh-modulesd:aws-s3[18690] XXXX:XX at XXXX(): INFO: Executing Bucket Analysis: (Bucket: Bucket_name1, Type: waf)
2021/02/08 17:23:13 wazuh-modulesd:aws-s3[18690] XXXX:XX at XX_s3(): DEBUG: Create argument list
2021/02/08 17:23:13 wazuh-modulesd:aws-s3[18690] XXXX:XX at XX_run_s3(): DEBUG: Launching S3 Command: /var/ossec/wodles/aws/aws-s3--bucket bucketname1--access_key XXXXXXXXXXXXX --secret_key XXXXXXXXXXXXXXXXX --type waf --debug 2 --skip_on_error
```

Tests have been carried out and when the integration is executed, the execution begins with the first bucket of the configuration "bucket_name1" and it remains there without getting to the 2nd bucket. However, we are still getting alerts so this means it is not getting stuck.

Additionally, the `only_logs_after` tag has been used to decrease the number of events to extract but depending on the number of objects to analyze it might not help.

We should consider increasing the performance of our integration because there may be cases when having several buckets like the aforementioned may prevent us to centralized the AWS configuration.

Regards,

Miguel Casares

**Comment by guilhermerezendemarques** [comment]
I the same problem, my S3 Bucket work only Cloud Trail . I don't saw Cloud Watch(service integration) and Trusted Advisor.

**Comment by CarlosRS9** [comment]
We are working on this issue, trying to find out if this could be happening due to a bottleneck in the module. It is possible that because the bucket contains so many logs its taking more than one hour to process those files.

Please, provide us the following information:

- Could you confirm us you are using debug mode set to `2` and there is no error or warning message present in the ossec.log?

- Is the `Fetching logs finished` message present in the ossec.log at any time?

- Was debug mode active originally, or was it enabled by us instead to debug the issue? The debug mode messages may cause the process to take even longer to complete.


As a workaround, did you tried to use both the `only_logs_after` tag and an `interval` value greater than `60m`, such as `360m`?

**Comment by guilhermerezendemarques** [comment]
Hi Carlos, this my issue in https://github.com/wazuh/wazuh/issues/7407 .

In my case, yes, debug is 2 and not appear errors in ossec.log.

Ossec.log appear this message for bucket Fetching logs finished.

I try this workaround: 
 only_logs_after tag and an interval value greater than 60m, such as 360m.

**Comment by guilhermerezendemarques** [comment]
Where insert this tag only_logs_after  ? I don't find in ossec.conf

**Comment by guilhermerezendemarques** [comment]
The same problem, after insert only_logs_after and increase interval to 60m.
my logs are too small (test enviroment)

**Comment by CarlosRS9** [comment]
Sorry for the confusion guilhermerezendemarques, but that message was for @maumrsms and @abohorqu.

I am aware of your issue and am addressing it in #7407. However, your issue and this one are not related. In your case the module is working perfectly (the logs show it), however no alerts are being generated because there are no rules that match your logs available in AWS. However, the problem for this particular issue seems to be that since this user has a huge amount of data available daily, the AWS module might not be able to process all the data from the first bucket and start processing the second bucket before the interval is met.

If you don't mind, let's keep these two issues separated to avoid any confusion with the rest of the community and to have all the information regarding each topic in its own thread.

Regards.

**Comment by CarlosRS9** [comment]
Hello @maumrsms and @abohorqu.

After several performance tests we can conclude this issue could be caused by the time it takes to the module to process such large amounts of data, not being fast enough to do so with that specified `interval` value. To solve this problem we suggest to apply the following modifications to the user's AWS module configuration:


- Increase the `interval` value. A few hours may be necessary if the amount of data in the bucket is too large.
- Use the `only_logs_after` tag if possible.
- Use the `path` tag if necessary. If the data is located in a path such as `<BUCKET_NAME>/WAF/YEAR/MONTH/DAY...>` but no `path` tag is being specified the module may attempt to process any other log available in the bucket, but not inside the desired WAF path, which would considerably increase the processing time of the WAF logs.

The configuration would therefore look like this:
```
<wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>360m</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>yes</skip_on_error>
    <bucket type="waf">
      <name>bucket_name1</name>
      <path>waf</path>
      <access_key>access_key1</access_key>
      <secret_key>secret_key1</secret_key>
    </bucket>
    <bucket type="waf">
      <name>bucket_name2</name>
      <path>waf</path>
      <access_key>access_key2</access_key>
      <secret_key>secret_key2</secret_key>
    </bucket>
  </wodle>
```

In order to estimate the exact value the user should apply to the `interval` we would need to know the average volume of data stored each day for WAF in that bucket.

Regards.

**Comment by abohorqu** [comment]
Hello @CarlosRS9,

Thank you for the help,

Answering your questions:

_Could you confirm us you are using debug mode set to 2 and there is no error or warning message present in the ossec.log?_ Yes, we set debug mode to "2" and there weren't relevant warning messages related to AWS.

_Is the Fetching logs finished message present in the ossec.log at any time?_ I did not see this message present in the log.

_Was debug mode active originally, or was it enabled by us instead to debug the issue? The debug mode messages may cause the process to take even longer to complete._

It was enabled by us only to debug the issue. After we set the interval to 24 hours as a test, we disabled debug logging.

_As a workaround, did you tried to use both the only_logs_after tag and an interval value greater than 60m, such as 360m?_

Yes, I tried using the "`only_logs_after`" tag to bring in logs only from the same day we did the troubleshooting.

An interval of 24 hours was also configured, which did not work since 24 hours passed and we only saw logs from the first bucket, not the second configured. 

The only thing we haven't tried is applying the `path` tag. We will run the test with the recommended configuration to see if this helps.

I am working on getting the average volume of data stored each day for WAF in that bucket. By having it I will be updating you.

Regards.
