### ISSUE TITLE
Negate report_changes

### ISSUE THREAD

**Issue by marinovgit** [wazuh/wazuh#7365]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| wazuh-manager-4.0.4-1.x86_64 | Wazuh component | Manager/Agent | Packages | centos 7 |

Is it possible to negate report_changes?
The idea is to generate an alert if a file IS NOT modified in some time let's say 1h.

**Comment by Molter73** [comment]
Hi @marinovgit 

Due to how FIM works and how the manager generates alerts based on receiving events, there is no direct way to generate this type of alert. (FIM only generates events when a change is detected in a file, there is no `no event detected on a file` event generated to trigger an alert).

You could however, monitor the generated alerts with a script and trigger your own event by writing into a monitored file in the manager.

This is a small (and in no way ready for production) python script to illustrate how you could constantly read from the `alerts.json` and print a message to another file you can ingest with the manager.

```python
from datetime import datetime
from time import sleep
import json
from io import SEEK_END

alert_log = open('/var/ossec/logs/alerts/alerts.json', 'r')
output = open('/home/vagrant/logcollector/test.log', 'w')

alert_log.seek(0, SEEK_END)

last_event = datetime.now()

constantly_changing = '/home/vagrant/link/test'

while 1:
    print('Read all new lines')
    for line in alert_log.readlines():
        json_alert = json.loads(line)
        print(json_alert)

        # print(json_alert)
        if 'syscheck' in json_alert:
            if json_alert['syscheck']['path'] == constantly_changing:
                last_event = datetime.now()

    print('Check timeout')
    time_to_last_event = datetime.now() - last_event
    if time_to_last_event.seconds > 5:
        output.write(f'{constantly_changing} has not been modified in over a minute\n')
        output.flush()
        last_event = datetime.now()

    print('Wait for some time')
    sleep(1)
```

On top of running this script, you will need to create a custom decoder and rule for triggering alerts on the message you write and add a way to reopen the appropriate alerts.json file when it gets rotated.

**Comment by marinovgit** [comment]
I like the idea. Thank you for the script. :)
