### ISSUE TITLE
Remoted syslog over TCP not removing header

### ISSUE THREAD

**Issue by fhielpos** [wazuh/wazuh#7381]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.4 | Remoted | Manager | - | - |

Hello team,

We have noticed that when receiving `Syslog` messages over TCP the `<PRI>` header is not being removed and causing the logs to not be analyzed.

**Example logs:**
```
# RFC 3164
<34>Oct 11 22:14:15 mymachine su: 'su root' failed for lonvick on /dev/pts/8
# RFC 5424
<165>1 2003-10-11T22:14:15.003Z mymachine.example.com evntslog - ID47 [exampleSDID@32473 iut="3" eventSource="Application" eventID="1011"][examplePriority@32473 class="high"]
```

**Expected behavior:**
Remoted should be able to remove the `<PRI>` header as it does over UDP so the logs could be analyzed:

**Example:**
```
Oct 11 22:14:15 mymachine su: 'su root' failed for lonvick on /dev/pts/8

2003-10-11T22:14:15.003Z mymachine.example.com evntslog - ID47 [exampleSDID@32473 iut="3" eventSource="Application" eventID="1011"][examplePriority@32473 class="high"]
```

Regards,

**Comment by chuyengiason** [comment]
we're having same problem with older version of wazuh, for my case : 3.13.2-1

**Comment by juliancnn** [comment]
The problem seems to be here. 
On UDP the header is dropped:

https://github.com/wazuh/wazuh/blob/aa61bc040c448cb23af04e93d1c744253cb7e679/src/remoted/syslog.c#L83-L92

While in TCP it sends the log as it receives it
https://github.com/wazuh/wazuh/blob/aa61bc040c448cb23af04e93d1c744253cb7e679/src/remoted/syslogtcp.c#L81-L98
