### ISSUE TITLE
Wrong sort combination with os.name and os.version in endpoint /agents

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh#7397]
|Wazuh version|Component|
|---|---|
| 4.1.0 | API |

Hi team, 
the endpoint `/agents` when sending this sort query `sort=os.name,os.version` the results are misordered.
![image](https://user-images.githubusercontent.com/26828184/107225937-3bbd4e00-69f8-11eb-93ec-7806937fea83.png)

<details>
<summary>The complete respose</summary>
<p>

```json
{
  "data": {
    "affected_items": [
      {
        "registerIP": "any",
        "name": "NewAgent",
        "ip": "any",
        "node_name": "unknown",
        "status": "never_connected",
        "id": "007",
        "dateAdd": "2021-02-08T12:27:46Z"
      },
      {
        "os": {
          "arch": "x86_64",
          "major": "2",
          "name": "Amazon Linux",
          "platform": "amzn",
          "uname": "Linux |wazuh-manager-master |4.14.114-105.126.amzn2.x86_64 |#1 SMP Tue May 7 02:26:40 UTC 2019 |x86_64",
          "version": "2"
        },
        "manager": "wazuh-manager-master",
        "registerIP": "127.0.0.1",
        "name": "wazuh-manager-master",
        "ip": "127.0.0.1",
        "node_name": "master",
        "version": "Wazuh v4.1.0",
        "lastKeepAlive": "9999-12-31T23:59:59Z",
        "status": "active",
        "id": "000",
        "dateAdd": "2021-01-29T13:06:33Z"
      },
      {
        "os": {
          "arch": "x86_64",
          "major": "2",
          "name": "Amazon Linux",
          "platform": "amzn",
          "uname": "Linux |ip-10-0-1-226.us-west-1.compute.internal |4.14.114-105.126.amzn2.x86_64 |#1 SMP Tue May 7 02:26:40 UTC 2019 |x86_64",
          "version": "2"
        },
        "manager": "wazuh-manager-worker-0",
        "registerIP": "any",
        "name": "Amazon",
        "ip": "10.0.1.226",
        "group": [
          "default",
          "Group1-test"
        ],
        "node_name": "worker_01",
        "version": "Wazuh v4.1.0",
        "mergedSum": "87a71c45b1ab3fcfc5bcbc38d7050ef7",
        "configSum": "69441d85c60b64217b0c5c13563e0d3f",
        "lastKeepAlive": "2021-02-08T13:17:22Z",
        "status": "active",
        "id": "001",
        "dateAdd": "2021-01-29T13:16:28Z"
      },
      {
        "os": {
          "arch": "x86_64",
          "codename": "Maipo",
          "major": "7",
          "minor": "5",
          "name": "Red Hat Enterprise Linux Server",
          "platform": "rhel",
          "uname": "Linux |ip-10-0-1-76.us-west-1.compute.internal |3.10.0-862.el7.x86_64 |#1 SMP Wed Mar 21 18:14:51 EDT 2018 |x86_64",
          "version": "7.5"
        },
        "manager": "wazuh-manager-worker-0",
        "registerIP": "any",
        "name": "RHEL7",
        "ip": "10.0.1.76",
        "group": [
          "default",
          "redhat",
          "apache",
          "mysql"
        ],
        "node_name": "worker_01",
        "version": "Wazuh v4.1.0",
        "mergedSum": "f260044fe2fcc9b5f806978348103412",
        "configSum": "4c0485551ade3372dca715ce6a4bcb00",
        "lastKeepAlive": "2021-02-08T13:17:23Z",
        "status": "active",
        "id": "005",
        "dateAdd": "2021-01-29T13:17:49Z"
      },
      {
        "os": {
          "arch": "x86_64",
          "major": "7",
          "minor": "6",
          "name": "CentOS Linux",
          "platform": "centos",
          "uname": "Linux |ip-10-0-1-176.us-west-1.compute.internal |3.10.0-957.1.3.el7.x86_64 |#1 SMP Thu Nov 29 14:49:43 UTC 2018 |x86_64",
          "version": "7.6"
        },
        "manager": "wazuh-manager-worker-0",
        "registerIP": "any",
        "name": "Centos",
        "ip": "10.0.1.176",
        "group": [
          "default"
        ],
        "node_name": "worker_01",
        "version": "Wazuh v4.1.0",
        "mergedSum": "dea79c18fb817a96780dbc29b089ba87",
        "configSum": "3ef368d564a962eb1c0e007bd1cd0179",
        "lastKeepAlive": "2021-02-08T13:17:25Z",
        "status": "active",
        "id": "004",
        "dateAdd": "2021-01-29T13:17:15Z"
      },
      {
        "os": {
          "arch": "x86_64",
          "codename": "stretch",
          "major": "9",
          "name": "Debian GNU/Linux",
          "platform": "debian",
          "uname": "Linux |ip-10-0-1-16 |4.9.0-9-amd64 |#1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) |x86_64",
          "version": "9"
        },
        "manager": "wazuh-manager-worker-0",
        "registerIP": "any",
        "name": "Debian",
        "ip": "10.0.1.16",
        "group": [
          "default",
          "Group1-test"
        ],
        "node_name": "worker_01",
        "version": "Wazuh v4.1.0",
        "mergedSum": "87a71c45b1ab3fcfc5bcbc38d7050ef7",
        "configSum": "69441d85c60b64217b0c5c13563e0d3f",
        "lastKeepAlive": "2021-02-08T13:17:24Z",
        "status": "active",
        "id": "002",
        "dateAdd": "2021-01-29T13:16:31Z"
      },
      {
        "os": {
          "build": "17763",
          "major": "10",
          "minor": "0",
          "name": "Microsoft Windows Server 2019 Datacenter",
          "platform": "windows",
          "uname": "Microsoft Windows Server 2019 Datacenter",
          "version": "10.0.17763"
        },
        "manager": "wazuh-manager-worker-0",
        "registerIP": "any",
        "name": "Windows",
        "ip": "10.0.1.246",
        "group": [
          "default",
          "windows"
        ],
        "node_name": "worker_01",
        "version": "Wazuh v4.1.0",
        "mergedSum": "c27c9c7962733b645186ac362f71d919",
        "configSum": "d867ae0af9f428d5356b564a1a94c4c6",
        "lastKeepAlive": "2021-02-08T13:17:25Z",
        "status": "active",
        "id": "006",
        "dateAdd": "2021-01-29T13:19:13Z"
      },
      {
        "os": {
          "arch": "x86_64",
          "codename": "Bionic Beaver",
          "major": "18",
          "minor": "04",
          "name": "Ubuntu",
          "platform": "ubuntu",
          "uname": "Linux |ip-10-0-1-231 |4.15.0-1039-aws |#41-Ubuntu SMP Wed May 8 10:43:54 UTC 2019 |x86_64",
          "version": "18.04.2 LTS"
        },
        "manager": "wazuh-manager-master",
        "registerIP": "any",
        "name": "Ubuntu",
        "ip": "10.0.1.231",
        "group": [
          "default",
          "prueba",
          "Group1-test"
        ],
        "node_name": "master",
        "version": "Wazuh v4.1.0",
        "mergedSum": "1505be727f0c5b635e9ba613b599fa73",
        "configSum": "90c2282ab87c4abfa5eb77d890d7f6ae",
        "lastKeepAlive": "2021-02-08T13:17:19Z",
        "status": "active",
        "id": "003",
        "dateAdd": "2021-01-29T13:16:40Z"
      }
    ],
    "total_affected_items": 8,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents information was returned",
  "error": 0
}
```

</p>
</details>  

Regards

**Comment by Espectro123** [comment]
## Status update

I begin to study the issue and to set up an appropriate docker environment to test it.

Tomorrow I will continue with it and try the different ways to use the sort parameter to understand what is happening

**Comment by Espectro123** [comment]
## Issue update

GET agents calls with a sort parameter specifying the comapos os.name and os.version, in this order, do not work correctly. 

This call:

```GET agents?sort=os.name,os.version```

should return the agents sorted alphabetically in ascending order, however, it returns them in descending order. 


![image](https://user-images.githubusercontent.com/9986983/116244845-99944300-a768-11eb-881f-57a1d41b121c.png)

![image](https://user-images.githubusercontent.com/9986983/116246292-24297200-a76a-11eb-9dda-137e0f4ba9cf.png)

When the operating system name is the same for both agents, it should return the agents sorted by their version in descending order, but it fails in this task too.

![image](https://user-images.githubusercontent.com/9986983/116246769-8da98080-a76a-11eb-906c-f9c36dcf9d45.png)

**Comment by Espectro123** [comment]
## Issue update

The ```WazuhDBQueryAgents``` query that gets the agents is not responding well when both fields are specified. Sometimes, the query will return the agents out of order. 

The failure seems to occur with any number of agents and with any value of ```os.name``` and ```os.version```.

### framework/wazuh/agent.py
```python
rbac_filters = get_rbac_filters(system_resources=system_agents, permitted_resources=agent_list, filters=filters)

db_query = WazuhDBQueryAgents(offset=offset, limit=limit, sort=sort, search=search, select=select,
                              query=q, **rbac_filters)
# Here
data = db_query.run()

result.affected_items.extend(data['items'])
result.total_affected_items = data['totalItems']

```

I have tested it with two and three agents. Sometimes, when using three agents, only the last two elements appear out of order.

### Three agent debug

#### Agent configuration in DB
Agent 001

- os.name: A-os-name
- os.version: 18.04.1 LTS
- os.major: 18
- os.minor: 04

Agent 002

- os.name: B-os-name
- os.version: 19.04.1 LTS
- os.major: 16
- os.minor: 04

Agent 005

- os.name: C-os-name
- os.version: 17.04.1 LTS
- os.major: 17
- os.minor: 04

#### Sort fields used in this test

- Field 1: **os.name**
- Field 2: **os.version**
- Order: **asc**

The expected order of the agents in this case is: **001,002,005**

```bash
RESULT:  
{'data': {'affected_items': [
{'os': {'name': 'B-os-name', 'version': '19.04.1 LTS'}, 'id': '002'}, 
{'os': {'name': 'C-os-name', 'version': '17.04.1 LTS'}, 'id': '005'}, 
{'os': {'name': 'A-os-name', 'version': '18.04.1 LTS'}, 'id': '001'}], 
'total_affected_items': 3, 'total_failed_items': 0, 'failed_items': []}, 
'message': 'All selected agents information was returned', 'error': 0}
```
The order returned in this test has been: **002,005,001**

### Debug information
Here I show the values of the variables that have been used to make the query and what it has returned with the debugger.

#### Sort and Select parameters used in this call
![image](https://user-images.githubusercontent.com/9986983/116392011-32d26080-a820-11eb-8611-eb2e4a6b1508.png)

#### Items inside data variable
```python
db_query = WazuhDBQueryAgents(offset=offset, limit=limit, sort=sort, search=search, select=select,
                             query=q, **rbac_filters)
data = db_query.run()
```

![image](https://user-images.githubusercontent.com/9986983/116392452-c2780f00-a820-11eb-8692-67c951c063bc.png)

**Comment by Espectro123** [comment]
## Issue update

Two agents tests with reported values for ```os.name``` and ```os.version``` fields used to sort the agents

## Two agent debug

### Agent configuration in DB
Agent 001

- os.name: Red Hat Enterprise Linux Server
- os.version: 7.5
- os.major: 7
- os.minor: 5

Agent 002

- os.name: CentOS Linux
- os.version: 7.6
- os.major: 7
- os.minor: 6

### Sort fields used in this test

- Field 1: **os.name**
- Field 2: **os.version**
- Order: **asc**

The expected order to be returned in this test is: **002,001**

**Comment by Espectro123** [comment]
## Issue update

```python
def _add_sort_to_query(self):
    if self.sort:
       if self.sort['fields']:
          sort_fields, allowed_sort_fields = set(self.sort['fields']), set(self.fields.keys())
```

![image](https://user-images.githubusercontent.com/9986983/116554508-8c5b8d80-a8fb-11eb-97e9-d20acb22e0ff.png)

**Comment by mcarmona99** [comment]
### Issue update

We should change the sorting process performed in the `WazuhDBQuery` class (`_add_sort_to_query`) to use **lists** instead of **sets** in order to avoid this error.

https://github.com/wazuh/wazuh/blob/f9d04e47c2529fcd820750ecdbc8b4ccdfc3a79a/framework/wazuh/core/utils.py#L1156-L1169

New API integration tests use cases must be added to test WazuhDBQuery calls using sort with multiple fields. Ensure we are testing the conflictive use cases, like the one mentioned in this issue.

This problem was reported in version 4.1. It may be also present in master. Check this and perform the fix and new test cases over the master branch.

## Checks

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)


### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Manuel.

**Comment by Espectro123** [comment]
## Issue update

This could be a temporary solution. The bug in the core test is because we use the ```-``` operator in the join when raising the exception if the fields are not in the list of allowed fields. This operator cannot be used since ```self.sort['fields']``` is a list and ```allowed_sort_fields``` is a set.

```python
    def _check_allowed_sort_fields(self, sort_fields):

        allowed_sort_fields = set(self.fields.keys())

        for field in sort_fields:
            if field not in allowed_sort_fields:
                return False
        return True

    def _add_sort_to_query(self):
        if self.sort:
            if self.sort['fields']:
                # check every element in sort['fields'] is in allowed_sort_fields
                if not self._check_allowed_sort_fields(self.sort['fields']):
                    allowed_sort_fields = set(self.fields.keys())
                    raise WazuhError(1403, "Allowed sort fields: {}. Fields: {}".format(
                        sorted(allowed_sort_fields, key=str), ', '.join(self.sort['fields'] - allowed_sort_fields)
                    ))
                self.query += ' ORDER BY ' + ','.join([self._sort_query(i) for i in self.sort['fields']])
            else:
                self.query += ' ORDER BY {0} {1}'.format(self.default_sort_field, self.sort['order'])
        else:
            self.query += ' ORDER BY {0} {1}'.format(self.default_sort_field, self.default_sort_order)
```

## Checks

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`) (1 Failed)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)


### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Espectro123** [comment]
## Issue update

The _add_sort_to_query function has been modified to work with lists instead sets. This will prevent that the order of the sort fields change. 

I am working on a unit test to check that the fix works and to make sure that in the future something similar does not happen.

## Checks

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
-->

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Espectro123** [comment]
The branch base of this PR #8542 has changed. 

This issue will be now resolved in #8548

**Comment by Espectro123** [comment]
## Issue update
An integrated test is being finalized. The two new unit tests are working correctly, so it seems that the fix has fixed the issue when the order of the sort fields was being changed.

For the integrated test the function ```test_sort_response``` of ```tavern_utils.py``` is being redone in order to be able to sort by multiple fields and check that the returned solution is correct.

**Comment by Espectro123** [comment]
## Issue update 

The new tavern_utils function that will check if the sort response is correctly sorted fails due to disconnected agents. The disconnected agents, don't have some of the fields that should be tested, so it was returning a KeyError. 

These agents have to be considered when comparing the sort. In case the order is ascending, they will go at the beginning and in case it is descending, they will go at the end.

```python
def _sort_items(unordered_items, dict_field, reverse):
    """
    Used in test_sort_response_multiple_fields
    Return a ordered dict. Accept nested fields like os.name
    """
    if len(dict_field) == 1:
        items_ordered = sorted(unordered_items, key=(lambda item: item[dict_field[0]]) if dict_field[0] else None, reverse=reverse)
    else:
        items_ordered = sorted(unordered_items, key=(lambda item: item[dict_field[0]][dict_field[1]]) if dict_field[0] and dict_field[1] else None, reverse=reverse)
    return items_ordered


def test_sort_response_multiple_fields(response, key=None, reverse=False):
    """
    """
    affected_items = response.json()['data']['affected_items']

    # Split multiple fields
    if ',' in key:
        key = key.split(',')

    process_fields = []

    # Split nested fields
    if not isinstance(key, list):
        process_fields.append(key.split('.'))
    else:
        [process_fields.append(field.split('.')) for field in key if isinstance(key, list)]

    items = list(affected_items)

    for field in process_fields[::-1]:
        items = _sort_items(items, field, reverse)

    assert affected_items == items

```

**Comment by mcarmona99** [comment]
## Issue status

Hi team,

I have updated the `test_sort_response` function. Now this function can test items are sorted by multiple keys and or nested keys. I have also update its parameter reverse. I have changed all API integration tests as now this param is `False` by default.

I have also update the `test_utils` unittest (`add_sort_to_query` case) to check the sort was added to the query properly. The `test_agent` unittest has also new use cases.

### Test results:

- API test integration using `test_sort_response`:

```
test_agent_GET_endpoints.tavern.yaml 
	 91 passed, 93 warnings

test_mitre_endpoints.tavern.yaml 
	 7 passed, 13 warnings

test_rootcheck_endpoints.tavern.yaml 
	 4 passed, 6 warnings

test_rule_endpoints.tavern.yaml 
	 15 passed, 17 warnings

test_sca_endpoints.tavern.yaml 
	 3 passed, 5 warnings

test_task_endpoints.tavern.yaml 
	 2 passed, 4 warnings
```
	 

`test_vulnerability_endpoints` is failing due to an error reported here https://github.com/wazuh/wazuh/issues/8595#issuecomment-836877391

This issue will be merged after that issue (https://github.com/wazuh/wazuh/issues/8595).


- Unit tests:

```
pytest framework/wazuh/core/tests/
===================================================================== 666 passed, 1 xfailed, 2 xpassed, 9 warnings in 4.37s =====================================================================

pytest framework/wazuh/tests/
========================================================================== 590 passed, 13 warnings in 64.12s (0:01:04) ==========================================================================
```

Regards,
Manuel
