### ISSUE TITLE
Upgrade embedded python version to 3.8.6

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#7416]
Hello team,

As part of the investigation for https://github.com/wazuh/wazuh/issues/7220 we have realized that uvloop dependency is not currently compatible with python 3.9.1.

They have released an statement indicating that it should be fixed soon. However, we have decided to complete the python upgrade in two steps. We first bump our python version to 3.8.6 for Wazuh v4.1.1 and then update to python 3.9.1 for the next major release (initially Wazuh v4.2.0) when  uvloop fixes the compatibility problems.

Best regards,

David J. Iglesias

**Comment by davidjiglesias** [comment]
### **Testing custom path (`/var/wazuh`) installation from sources:**
```  
root@wazuh-master:/wazuh# service wazuh-manager start 
Starting Wazuh v4.1.1...
Started wazuh-apid...
Started ossec-csyslogd...
Started ossec-dbd...
2021/02/12 11:29:38 ossec-integratord: INFO: Remote integrations not configured. Clean exit.
Started ossec-integratord...
Started ossec-agentlessd...
Started ossec-authd...
Started wazuh-db...
Started ossec-execd...
Started ossec-analysisd...
Started ossec-syscheckd...
Started ossec-remoted...
Started ossec-logcollector...
Started ossec-monitord...
Started wazuh-modulesd...
Completed.

root@wazuh-master:/wazuh# /var/wazuh/framework/python/bin/python3 --version
Python 3.8.6

root@wazuh-master:/wazuh# /var/wazuh/framework/python/bin/pip3 freeze | grep cryptography
cryptography==3.3.2

```

**Comment by davidjiglesias** [comment]
The documentation steps to install extra dependencies when installing Wazuh from sources on a custom path is outdated and we need to update it:
```
echo "deb-src http://deb.debian.org/debian $(lsb_release -cs) main" >> /etc/apt/sources.list
apt-get update
apt-get build-dep python3.5 -y
```

**Comment by davidjiglesias** [comment]
We need to update documentation.

Packages changes: https://github.com/wazuh/wazuh-packages/pull/646

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

We have completed the migration from Python **3.8.2** to **3.8.6**, in the process we have fixed a bug that caused that when an agent was installed the **cpython package was downloaded when it is not a dependency of it**. In this way we have accelerated the installation/update process of the agent.

On the other hand, we have added new dependencies to the Wazuh framework, and we have fixed a vulnerability in the cryptography library. 

Finally, we have changed the structure of dependencies stored in AWS. Previously **there was a dependency folder for each version of Wazuh**, however, usually between version changes, the dependencies did not change so most of the files were repeated. Along with this we have removed the dependency packages for the manager node type for the 32-bit versions since they are not currently supported. Therefore, **now the dependencies will be versioned and the version of the dependencies will be upgraded depending on whether we change any of them**. The first version of these dependencies will be number 10.

### AIX test after the changes
![image (3) (1)](https://user-images.githubusercontent.com/15522808/108351065-4be9e000-71e5-11eb-8062-a78a233c27d7.png)
