### ISSUE TITLE
Node client with same name as master node is starting

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#748]
Hello team, if I have a cluster with master node named node01 and configure a client node named node01 too, the client node is starting and I don't know it's failing unless I see the cluster.log which tell us weird messages.

```
Starting Wazuh v3.2.4 (maintained by Wazuh Inc.)...
Started wazuh-db...
Started wazuh-modulesd...
Started ossec-execd...
Started ossec-analysisd...
Started ossec-syscheckd...
Started ossec-remoted...
Started ossec-logcollector...
Started ossec-monitord...
Started wazuh-clusterd...
Completed.
```

Thanks,
Jesús

**Comment by Lifka** [comment]
Hi @jesusgn90,

it's not possible to add an error message because this log informs about the boot of the daemons. Even if the node fails to connect, the daemon is running and retrying to establish a connection because the reasons why it has been rejected may be different. But technically the demon is running smoothly.

Regards!

**Comment by jesuslinares** [comment]
The client node is doing its job: trying to connect to the master.

If the master rejects the connection (due to the name), any reason is specified in the client (only in the master). We should review if it is interesting to send the reason to the client and it doesn't have security implications.

**Comment by jesuslinares** [comment]
We will keep this behavior. Feel free to re-open this issue if you consider that is unclear for the users.
