### ISSUE TITLE
Improve MITRE ATT&CK mapping on current ruleset. 

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#7556]
## Description
Global Issue to refer all others related with MITRE mapping in rules

### Reviewed
- [x] Level 15
- [X] Level 14
- [X] Level 13
- [X] Level 12
- [X] Level 11
- [X] Level 10
- [X] Level 9
- [X] Level 8
- [X] Level 7
- [x] Level 6
- [x] Level 5
- [x] Level 4
- [x] Level 3
- [x] Level 2
- [x] Level 1
### Statistics

![image](https://user-images.githubusercontent.com/32262972/129884811-af991fb2-bbac-4fd9-a4df-afefacb0b75f.png)

![image](https://user-images.githubusercontent.com/32262972/129884699-f4266704-2ce9-4465-ac08-8bd8bbda372a.png)
![image](https://user-images.githubusercontent.com/32262972/129884749-42c22b1f-e568-4804-886f-e10c58cb85cb.png)

**Comment by Nekaze** [comment]
@JavierBejMen and I **finished the analysis of all rules that currently have levels of 11 and above** assigned (Around 190 rules)

The analysis consisted in studying them, and assigning a proper MITRE technique / subtechnique ID, and tactic, focusing on rules that did not currently have any MITRE associated.

Rules that already had MITRE, were left as is. Looking into them might be a good idea for the future.

Of the evaluated rules, many have been found to not being mappable into MITRE. Others, are too generic, and need more info in order to be mappable

Also, we started analyzing the rules related to C2 (Command and Control) mentioned in #803

**Comment by JavierBejMen** [comment]
Status Update

Rules reviewed with successful mapping:
|         |           |         |                             |
|---------|-----------|---------|-----------------------------|
| Rule ID | Technique | Tactic  | Status                      |
| 11209   | T1571     | TA0011  | OK - RULE is good           |
| 62113   | T1588.001 | TA0042  | OK - RULE is good           |
| 62126   | T1588.001 | TA0042  | OK - RULE is good           |
| 204     | T1499.001 | TA0040  | OK - RULE is good           |
| 2937    | T1495     | TA0040  | OK - RULE is good           |
| 2938    | T1495     | TA0040  | OK - RULE is good           |
| 2939    | T1495     | TA0040  | OK - RULE is good           |
| 6321    | T1557.002 | TA0009  | OK - RULE is good           |
| 6323    | T1595     | -       | OK - RULE is good           |
| 30120   | T1499.002 | TA0040  | OK - RULE is good           |
| 62162   | T1499.001 | TA0040  | OK - RULE NEEDS TO BE ADDED |
| 62163   | T1562.001 | TA0005  | OK - RULE NEEDS TO BE ADDED |
| 62164   | T1562.001 | TA0005  | OK - RULE NEEDS TO BE ADDED |
| 62167   | T1562.006 | TA0005  | OK - RULE NEEDS TO BE ADDED |
| 62170   | T1564.006 | TA0005  | OK - RULE NEEDS TO BE ADDED |
| 62171   | T1562.006 | TA0005  | OK - RULE NEEDS TO BE ADDED |
| 81628   | T1499.001 | TA0040  | OK - RULE is good           |
| 4381    | T1498.001 | TA0040  | OK - RULE is good           |
| 4382    | T1498.001 | TA0040  | OK - RULE is good           |
| 4385    | T1498.001 | TA0040  | OK - RULE is good           |
| 11512   | T1499.002 | TA0040  | OK - RULE is good           |
| 60115   | T1110     | TA0003  | OK - RULE is good           |
| 60115   | T1531     | TA0040  | OK - RULE is good           |
| 60652   | T1499.001 | TA0040  | OK - RULE is good           |
| 82405   | T1071.004 | TA0011  | OK - RULE is good           |
| 60109   | T1098     | TA0003  | OK - RULE NEEDS TO BE ADDED |
| 60110   | T1098     | TA0003  | OK - RULE NEEDS TO BE ADDED |
| 60111   | T1098     | TA0003  | OK - RULE NEEDS TO BE ADDED |
| 60111   | T1531     | TA0040  | OK - RULE is good           |
| 60114   | T1098     | TA0003  | OK - RULE NEEDS TO BE ADDED |
| 9510    | T1102.002 | TA0011  | OK - RULE is good           |
| 60116   | T1529     | TA0003  | OK - RULE is good           |
| 60629   | T1112     | TA0005  | OK - RULE is good           |
| 5706    | T1021.004 | TA0008  | OK - RULE is good           |
| 60102   | T1005     | TA0009  | OK - RULE NEEDS TO BE ADDED |
| 60121   | T1098     | TA0003  | OK - RULE is good           |
| 60121   | T1136     | TA0003  | OK - RULE is good           |
| 60121   | T1531     | TA0040  | OK - RULE is good           |
| 60649   | T1489     | T0040   | OK - RULE is good           |
| 60654   | T1112     | TA0005  | OK - RULE is good           |
| 60667   | T1112     | TA0005  | OK - RULE is good           |
| 60792   | T1112     | TA0005  | OK - RULE is good           |
| 18658   | T1095     | TA0011  | OK - RULE is good           |

Rules reviewed with unsuccessful mapping:
|         |                                                                                                                                                                                                                                                                                                                       |                             |
|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------|
| Rule ID | Reason                                                                                                                                                                                                                                                                                                                | Status                      |
| 62105   | Need more info on what is repeating                                                                                                                                                                                                                                                                                   | TOO GENERIC - REWORK NEEDED |
| 62106   | Need more info on what is repeating                                                                                                                                                                                                                                                                                   | TOO GENERIC - REWORK NEEDED |
| 64205   | No detail of what these high severity categories are. Categories might be these https://www.pandasecurity.com/homeusers/downloads/docs/product/help/is/2010/da/21.htm                                                                                                                                                 | TOO GENERIC - REWORK NEEDED |
| 22406   | Its a vulnerability present in the system                                                                                                                                                                                                                                                                             | CAN'T BE MAPPED             |
| 23506   | Its a vulnerability present in the system                                                                                                                                                                                                                                                                             | CAN'T BE MAPPED             |
| 233     | This action migth be performed by a valid user, or by a malicious agent with many different objectives, i.e. reduce size to clear. Suggestion is to add who is the user performing this action                                                                                                                        | TOO GENERIC - REWORK NEEDED |
| 7504    |                                                                                                                                                                                                                                                                                                                       | TOO GENERIC - REWORK NEEDED |
| 7705    |                                                                                                                                                                                                                                                                                                                       | TOO GENERIC - REWORK NEEDED |
| 23510   | This needs to be evaluated according to the vulnerability                                                                                                                                                                                                                                                             | TOO GENERIC - REWORK NEEDED |
| 30104   |                                                                                                                                                                                                                                                                                                                       | TOO GENERIC - REWORK NEEDED |
| 30304   |                                                                                                                                                                                                                                                                                                                       | TOO GENERIC - REWORK NEEDED |
| 31204   | This is too generic, also last update on this rule was 14 years ago                                                                                                                                                                                                                                                   | CAN'T BE MAPPED             |
| 35056   |                                                                                                                                                                                                                                                                                                                       | TOO GENERIC - REWORK NEEDED |
| 40113   | This is too generic, also last update on this rule was 12 years ago                                                                                                                                                                                                                                                   | TOO GENERIC - REWORK NEEDED |
| 60015   | Multiple critical events is too generic, rules should be evaluated according to specific events                                                                                                                                                                                                                       | TOO GENERIC - REWORK NEEDED |
| 61112   | Multiple critical events is too generic, rules should be evaluated according to specific events                                                                                                                                                                                                                       | TOO GENERIC - REWORK NEEDED |
| 62165   | This error indicates that Microsoft Defender Antivirus failed to quarantine a threat.                                                                                                                                                                                                                                 | CAN'T BE MAPPED             |
| 62166   | This error indicates that a reboot is required to complete threat removal.                                                                                                                                                                                                                                            | CAN'T BE MAPPED             |
| 62168   |                                                                                                                                                                                                                                                                                                                       | CAN'T BE MAPPED             |
| 62169   | This error indicates that manual steps are required to complete threat removal.                                                                                                                                                                                                                                       | CAN'T BE MAPPED             |
| 62172   |                                                                                                                                                                                                                                                                                                                       | CAN'T BE MAPPED             |
| 62173   | This error indicates that an offline scan is required.                                                                                                                                                                                                                                                                | CAN'T BE MAPPED             |
| 62174   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62175   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62176   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62177   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62178   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62179   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62180   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62181   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62182   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62183   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62184   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62185   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62186   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62187   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62188   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62189   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62190   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62191   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62192   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62193   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62194   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62195   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62196   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62197   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62198   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62199   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62200   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62201   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62202   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62203   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62204   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62205   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62206   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62207   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62208   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62209   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62210   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62211   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62212   | Defender internal error                                                                                                                                                                                                                                                                                               | CAN'T BE MAPPED             |
| 62606   |                                                                                                                                                                                                                                                                                                                       | CAN'T BE MAPPED             |
| 63603   |                                                                                                                                                                                                                                                                                                                       | CAN'T BE MAPPED             |
| 64204   | No detail of what these high severity categories are. Categories might be these https://www.pandasecurity.com/homeusers/downloads/docs/product/help/is/2010/da/21.htm                                                                                                                                                 | TOO GENERIC - REWORK NEEDED |
| 65010   | This needs more data to be able to map it into MITRE                                                                                                                                                                                                                                                                  | CAN'T BE MAPPED             |
| 65017   | This needs more data to be able to map it into MITRE                                                                                                                                                                                                                                                                  | CAN'T BE MAPPED             |
| 65020   | This needs more data to be able to map it into MITRE                                                                                                                                                                                                                                                                  | CAN'T BE MAPPED             |
| 65046   | This needs more data to be able to map it into MITRE                                                                                                                                                                                                                                                                  | CAN'T BE MAPPED             |
| 80355   | This can be mapped onto more specific rules, in order to assign a proper mitre id, as per https://docs.aws.amazon.com/macie/latest/userguide/macie-alerts.html#macie-alert-categories. Also, this is probably more related to the cloud matrix https://attack.mitre.org/matrices/enterprise/cloud/                    | TOO GENERIC - REWORK NEEDED |
| 83001   |                                                                                                                                                                                                                                                                                                                       | TOO GENERIC - REWORK NEEDED |
| 87105   |                                                                                                                                                                                                                                                                                                                       | CAN'T BE MAPPED             |
| 20161   | These rules are 15 years old, probably are obsolete                                                                                                                                                                                                                                                                   | NOT CLEAR - REWORK NEEDED   |
| 20162   | These rules are 15 years old, probably are obsolete                                                                                                                                                                                                                                                                   | NOT CLEAR - REWORK NEEDED   |
| 65009   | This needs more data to be able to map it into MITRE                                                                                                                                                                                                                                                                  | CAN'T BE MAPPED             |
| 65016   | This needs more data to be able to map it into MITRE                                                                                                                                                                                                                                                                  | CAN'T BE MAPPED             |
| 65045   | This needs more data to be able to map it into MITRE                                                                                                                                                                                                                                                                  | CAN'T BE MAPPED             |
| 3331    | Seems like the server has run out of disk space, could be DoS, didnt found any relevant documentation on this matter                                                                                                                                                                                                  | CAN'T BE MAPPED             |
| 4380    | Too generic alerts                                                                                                                                                                                                                                                                                                    | TOO GENERIC - REWORK NEEDED |
| 4383    | Currently, PIX Firewall does not generate severity 4, warning, syslog messages.                                                                                                                                                                                                                                       | CAN'T BE MAPPED             |
| 4552    | Could be Credential Acces, DoS?¿, Scanning                                                                                                                                                                                                                                                                            | TOO GENERIC - REWORK NEEDED |
| 4553    | Could be Credential Acces, DoS, Scanning                                                                                                                                                                                                                                                                              | TOO GENERIC - REWORK NEEDED |
| 35052   | Needs distinction of request origin if possible, could be DoS or Proxy                                                                                                                                                                                                                                                | TOO GENERIC - REWORK NEEDED |
| 35052   | Needs distinction of request origin if possible, could be DoS or Proxy                                                                                                                                                                                                                                                | TOO GENERIC - REWORK NEEDED |
| 60117   | Currently this rule has T1070.004 "File deletion" assgined, but I believe it should be T1070.001 "Clear windows event logs"                                                                                                                                                                                           | NOT CLEAR - REWORK NEEDED   |
| 64223   | Seems related to active scan and Dos, need distinction betwen legitimate users if posible and/or frecuency                                                                                                                                                                                                            | TOO GENERIC - REWORK NEEDED |
| 60112   |                                                                                                                                                                                                                                                                                                                       | TOO GENERIC - REWORK NEEDED |
| 18659   | May needed to create repetition rule                                                                                                                                                                                                                                                                                  | TOO GENERIC - REWORK NEEDED |
| 18660   | May needed to create repetition rule                                                                                                                                                                                                                                                                                  | TOO GENERIC - REWORK NEEDED |
| 18661   | May needed to create repetition rule                                                                                                                                                                                                                                                                                  | TOO GENERIC - REWORK NEEDED |
| 2503    | Need to specify who set the block rule                                                                                                                                                                                                                                                                                | TOO GENERIC - REWORK NEEDED |
| 5601    | Need to specify who set the block rule                                                                                                                                                                                                                                                                                | TOO GENERIC - REWORK NEEDED |
| 11107   | Need to specify blocked connection origin, legitimate user or external                                                                                                                                                                                                                                                | TOO GENERIC - REWORK NEEDED |
| 11207   | Need to specify who set the block rule                                                                                                                                                                                                                                                                                | TOO GENERIC - REWORK NEEDED |
| 35007   | As it is needs distinction of origin request, could be Adversary DoS through proxy, active scanning, Command and Control                                                                                                                                                                                              | TOO GENERIC - REWORK NEEDED |
| 60104   | These rules are too generic. As per https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/basic-security-audit-policy-settings, theres many different types of audit events. "Audit success" or "Audit failure" do not match specific MITRE criteria                                           | TOO GENERIC - REWORK NEEDED |
| 60105   | This rule can match any of the subtechniques for T1078. Also, technique T1078 can be associated to multiple tactics                                                                                                                                                                                                   | TOO GENERIC - REWORK NEEDED |
| 60113   | This rule has T1484 assigned, which is "Domain Policy Modification", but I believe it should be T1098 "Account manipulation"                                                                                                                                                                                          | NOT CLEAR - REWORK NEEDED   |
| 60679   |                                                                                                                                                                                                                                                                                                                       | NOT CLEAR - REWORK NEEDED   |
| 60680   |                                                                                                                                                                                                                                                                                                                       | NOT CLEAR - REWORK NEEDED   |
| 60897   | The Registry of a remote system may be modified to aid in execution of files as part of lateral movement. It requires the remote Registry service to be running on the target system. [5] Often Valid Accounts are required, along with access to the remote system's SMB/Windows Admin Shares for RPC communication. | NOT CLEAR - REWORK NEEDED   |
| 60898   | The Registry of a remote system may be modified to aid in execution of files as part of lateral movement. It requires the remote Registry service to be running on the target system. [5] Often Valid Accounts are required, along with access to the remote system's SMB/Windows Admin Shares for RPC communication. | NOT CLEAR - REWORK NEEDED   |
| 60899   | The Registry of a remote system may be modified to aid in execution of files as part of lateral movement. It requires the remote Registry service to be running on the target system. [5] Often Valid Accounts are required, along with access to the remote system's SMB/Windows Admin Shares for RPC communication. | NOT CLEAR - REWORK NEEDED   |
| 60900   | The Registry of a remote system may be modified to aid in execution of files as part of lateral movement. It requires the remote Registry service to be running on the target system. [5] Often Valid Accounts are required, along with access to the remote system's SMB/Windows Admin Shares for RPC communication. | NOT CLEAR - REWORK NEEDED   |
| 60901   | The Registry of a remote system may be modified to aid in execution of files as part of lateral movement. It requires the remote Registry service to be running on the target system. [5] Often Valid Accounts are required, along with access to the remote system's SMB/Windows Admin Shares for RPC communication. | NOT CLEAR - REWORK NEEDED   |
| 60107   |                                                                                                                                                                                                                                                                                                                       | NOT CLEAR - REWORK NEEDED   |
| 60790   |                                                                                                                                                                                                                                                                                                                       | CAN'T BE MAPPED             |
| 60106   | This rule can match any of the subtechniques for T1078. Also, technique T1078 can be associated to multiple tactics                                                                                                                                                                                                   | TOO GENERIC - REWORK NEEDED |
| 60108   |                                                                                                                                                                                                                                                                                                                       | NOT CLEAR - REWORK NEEDED   |
| 60118   | Proper tactic needs to be specified                                                                                                                                                                                                                                                                                   | TOO GENERIC - REWORK NEEDED |
| 60119   | Proper tactic needs to be specified                                                                                                                                                                                                                                                                                   | TOO GENERIC - REWORK NEEDED |

**Comment by JavierBejMen** [comment]
## Update
### Current ruleset MITRE status
![image.png](https://images.zenhubusercontent.com/602cf858864bfc5b71b3cbc8/2f72cf2b-69b0-4b12-a63d-eca0b5a7f393)

**Comment by Nekaze** [comment]
Analyzed most of the rules from levels 15 until 6. Around 1700 rules left

**Comment by JavierBejMen** [comment]
## Update Status
Mapped Rules MITRE distribuitions
![image.png](https://images.zenhubusercontent.com/602cf858864bfc5b71b3cbc8/d5b7c840-76df-43f8-a259-1fd8ce86d4dc)

**Comment by fabamatic** [comment]
Update status

![image.png](https://images.zenhubusercontent.com/602d01751617aa35972166e0/7bbeaf4e-730b-49ba-a465-6ee6af477657)

![image.png](https://images.zenhubusercontent.com/602d01751617aa35972166e0/b6d87938-07ef-40f0-9fed-ed8fa7fc6f95)

**Comment by Nekaze** [comment]
Analyzed around 73 rules today; finished all level 5 and above. 31,5% pending to review (1023 rules)

**Comment by jcruzlp** [comment]
Excel to track the progress: https://docs.google.com/spreadsheets/d/15mMrb9oD117wP5g4qg2XZmXJUkqfWISWELw_lVaLpCg/edit?ts=602fb83d#gid=1152148461

**Comment by NicoGuini** [comment]
Last status of mapping:
![image](https://user-images.githubusercontent.com/6727099/126831225-7a829cec-7fbd-4672-8ea5-e8d2ca1db5e8.png)

![image](https://user-images.githubusercontent.com/6727099/126831265-53c023f9-48fb-43d6-9e44-79c4887cd326.png)

**Comment by fabamatic** [comment]
Completed review off level 3 rules

**Comment by JavierBejMen** [comment]
## Update
All rules with level 0+ have been reviewed, since level 0 rules are not mapeable to MITRE ATT&CK this issue is finished
