### ISSUE TITLE
Adding flexibility to the syntax required to work for the AWS integration module

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh#7593]
|Wazuh version|Component|
|---|---|
| stable | AWS-S3 module|

Hello team,

Currently, our AWS module is not able to retrieve the information from those buckets that are not following our required syntax. By adding flexibility to it, we can improve this capability and it will increase the usability of the module. 
For instance, if I created an AWS CloudTrail bucket that is following this syntax:

`<bucket_name>/<prefix>/AWSLogs/<suffix>/<account_id>/CloudTrail/<region>/<year>/<month>/<day>`

If we are able to check the service and the prefix, the bucket may introduce another directory in between, <suffix>, but we can still read it.

This will help if we are deploying automatically in AWS without previous knowledge about our required syntax. In that case, we don't need to redeploy in order to follow it.

Please let me know if you need any further information.
Thanks in advance!

**Comment by CarlosRS9** [comment]
It is possible to modify the `aws-s3` module so the customer could use that custom path for his buckets. This way, he could use `<bucket_name>/AWSLogs/<prefix>/<account_id>/CloudTrail/<region>` instead of `<bucket_name>/<prefix>/AWSLogs/<account_id>/CloudTrail/<region>` by simply specifying the `path` in the configuration. However, is important to take into account the following consecuences if this modification is applied:


1. This modification will be applied to the entire `aws-s3` module which means the user won't be able to get logs from a `<bucket_name>/AWSLogs/<prefix>/<account_id>/CloudTrail/<region>` path for one bucket and logs from a `<bucket_name>/<prefix>/AWSLogs/<account_id>/CloudTrail/<region>` path for another one in the same Wazuh instance. Only `<bucket_name>/AWSLogs/<prefix>/<account_id>/CloudTrail/<region>` will be a valid path.
2. If Wazuh is updated in the future those changes will be lost as the new module will replace the old one.


With this in mind, to adapt the aws-s3 module apply the following changes:


Replace this line: https://github.com/wazuh/wazuh/blob/3.13/wodles/aws/aws_s3.py#L473
```
self.prefix = prefix
```
with this:
```
self.prefix = 'AWSLogs/{}'.format(prefix)
```

Finally, replace this line: https://github.com/wazuh/wazuh/blob/3.13/wodles/aws/aws_s3.py#L835
```
base_prefix = '{}AWSLogs/'.format(self.prefix)
```

with this:
```
base_prefix = '{}'.format(self.prefix)
```

Let us know if you have more questions related to this modification.

Regards.

**Comment by MiguelCasaresRobles** [comment]
Hello team,

As you mentioned, this solution will prevent the users from using other services so it is a limiting factor.

Regards,

Miguel Casares

**Comment by CarlosRS9** [comment]
To add flexibility to the bucket path we could create a new parameter for the bucket configuration used to specify a suffix.  The `path` parameter would be used to specify the prefix (the custom path before the `AWSLogs` string) while `path_suffix` would be used to specify a suffix (the custom path that goes after the `AWSLogs` string but before the `<account_id>`). 


With this new parameter we would support paths with the `<bucket_name>/<prefix>/AWSLogs/<suffix>/<account_id>/CloudTrail/<region>/<year>/<month>/<day>` format. Here is an example of the configuration for this case:

```
<bucket type="cloudtrail">
    <name> bucket_name </name>
    <access_key> insert_access_key </access_key>
    <secret_key> insert_secret_key </secret_key>

    <path> custom_path_prefix </path>
    <path_suffix> custom_path_suffix </path_suffix>
</bucket>
```

**Comment by Selutario** [comment]
## Issue update

### Errors found
Hi team!

I found an error before starting the development of this feature. 

We have some cloudtrail logs (for testing purposes) in a bucket called `wazuh-aws-wodle`, under these paths:
1. `wazuh-aws-wodle/AWSLogs/<account_id>/CloudTrail/us-east-1/`
2. `wazuh-aws-wodle/test_config/AWSLogs/<account_id>/CloudTrail/us-east-1/`

In order to get the logs stored there, a call to boto3 API is performed in the line 746 below:
https://github.com/wazuh/wazuh/blob/e2ad99bb9c0690bf252ce0e071024e03b5b06469/wodles/aws/aws_s3.py#L744-L746

It is working fine for the path `#1` shown before and a list of `.gz` files like this is returned:
- `AWSLogs/<account_id>/CloudTrail/us-east-1/2020/05/06/<account_id>_CloudTrail_us-east-1_20200506T1115Z_WXBxpSwm2u3s7lxQ.json.gz`
- `AWSLogs/<account_id>/CloudTrail/us-east-1/2020/05/06/<account_id>_CloudTrail_us-east-1_20200506T1115Z_iPfeDdpoI46Gw5lc.json.gz`
- `AWSLogs/<account_id>/CloudTrail/us-east-1/2020/05/06/<account_id>_CloudTrail_us-east-1_20200506T1120Z_4UcVcNPIGVrUKCeh.json.gz`

However, for the path `#2` the list of files returned is:
- `test_config/AWSLogs/<account_id>/CloudTrail/us-east-1/2021/`
- `test_config/AWSLogs/<account_id>/CloudTrail/us-east-1/2021/02/`
- `test_config/AWSLogs/<account_id>/CloudTrail/us-east-1/2021/02/03/`
- `test_config/AWSLogs/<account_id>/CloudTrail/us-east-1/2021/02/03/<account_id>_CloudTrail_us-east-1_20210223T0000Z_4A1Zfp24tjwEFgxG.json.gz`
- `test_config/AWSLogs/<account_id>/CloudTrail/us-east-1/2021/02/03/<account_id>_CloudTrail_us-east-1_20210223T0000Z_H85mOB8RiSRkPvET.json.gz`

As it can be seen, the first 3 elements are incomplete, paths to a folder and not to each of the log files. When the wodle tries to process that, an error like this is raised and the fetching of logs is cancelled:
```
WARNING: Bucket:  -  Unexpected error querying/working with objects in S3: list index out of range
```

#### Fix
I have temporarily fixed it to avoid problems during this development by using a regex that checks that the path contains a full date and a name after it. However, this should be further investigated and properly fixed ([L752-754](https://github.com/wazuh/wazuh/blob/e2ad99bb9c0690bf252ce0e071024e03b5b06469/wodles/aws/aws_s3.py#L752-L754)):
```PYTHON
            for bucket_file in bucket_files['Contents']:
                if not bucket_file['Key'] or not re.match(r'^.*\/\d{4}\/\d{2}\/\d{2}\/.+$', bucket_file['Key']):
                    continue
```

### Adding a suffix parameter
This is the main feature requested in this PR. Until now, we could use the parameter `--trail_prefix <prefix>` to specify a path where the AWSLogs folder is stored.

Now, a new `--trail_suffix <suffix>` has been added. When using any of both parameters, we can retrieve logs stored in any of these paths inside our `wazuh-aws-wodle` S3 bucket:
- **wazuh-aws-wodle/AWSLogs/<account_id>/...**: Default path. No prefix or suffix needed.
- **wazuh-aws-wodle/AWSLogs/test_cloudtrail/<account_id>/...**: `--trail_suffix test_cloudtrail/`
- **wazuh-aws-wodle/test_config/AWSLogs/<account_id>/...**: `--trail_prefix test_config/`
- **wazuh-aws-wodle/test_config/AWSLogs/test_cloudtrail/<account_id>/...**: `--trail_prefix test_config/ --trail_suffix test_cloudtrail/`

Regards,
Selu
