### ISSUE TITLE
Analyze alternatives to create the new MITRE DB

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#7614]
### Description

The current mechanism to create the MITRE DB uses a python script that creates and populates the DB tables in compilation time.

This behavior has to be analyzed to identify if there is a better way to do this.

For now, the DB should still be created in compilation time. However, alternatives to Python should be considered to create the DB, with the aim to improve the manipulation of SQL queries.

To close this issue, it is necessary to propose a solution that will later be used to create the new MITRE DB.

**Comment by Nicogp** [comment]
Alternatives to create the new MITRE DB:

- SQL: as is currently being done.
    Advantages: 

      - Is currently being done.
      - More efficient. (Not very relevant as it only runs on build)

    Disadvantages:

      - Greater amount of code.
      - More complexity as tables are added.
      - SQL statements must be hardcoded

- ORM - SQLalchemy: provide a high-level abstraction upon a relational database that allows a developer to write Python code instead of SQL to create, read, update and delete data and schemas in their database.

    Advantage:

      - It is being used in other parts of the platform.
      - Allows an abstraction of SQL code
      - Possible code reduction.
      - map tables to Python classes.

    Disadvantages:

      - Potential performance decrease (Not very relevant as it only runs on build)

**Comment by javabalm** [comment]
Within the ORM frameworks we can find two different implementations: 

> `Active Record and Data Mapper`

The big difference between the Active Record style and the Data Mapper style is, the Data Mapper style completely separates your domain from the persistence layer. This means none of your model objects know anything about the database.

At this point we can find two different ways to implement it:
`Django ORM` uses the `Active Record` implementation and `SQLAlchemy` uses the `Data Mapper` implementation.

To check these two different options I opted to set up a database using `Django ORM` (which is not being used in Wazuh).
The implementation was not a huge challenge because the django documentation is very clear. 
At the end I realized that Active Record has been developed for another purpose, it's my believe that if your application is a mostly a CRUD (Create, Read, Update, Delete) application which no hard and complex rules to apply on the relationships between the different data entities, you should use the Active Record implementation.

If you add this to the fact that Wazuh is not using django for any other purpose, you come to the conclusion that the option to use `Data Mapper with SQLAlchemy` is the indicated.

**Comment by TomasTurina** [comment]
Will use Data Mapper with SQLAlchemy.
