### ISSUE TITLE
Inventory - Processes name table shows ossec-logcollector process truncated

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh#7634]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.4   | 7.10.0     | 4016 |

**Description**
The Inventory table "Processes" truncate the `ossec-logcollector` process name. 

![image](https://user-images.githubusercontent.com/3830293/105508059-36f45c80-5ccc-11eb-9352-b5f53127ba96.png)

**Steps to reproduce**

1. Register a CentOS 7 agent.
2. Click on the CentOS agent in the Wazuh agent list. 
3. Click on "Inventory".
4. Go to table "Processes"

Regards, 
AlbertoR

**Comment by Dwordcito** [comment]
The process name appears truncated, under a fixed limit of 15 characters.

Actual result: process basename max length = 16
Expected result: process basename without max length.

![imagen](https://user-images.githubusercontent.com/14300208/109352111-171b0000-7859-11eb-8c1b-e6cf2ad4f4c3.png)

Destination Branch: `dev-syscollector-tde`

## DoD
- [ ] Use another option to get complete basename.
- [ ] Add Unittest
- [ ] PR CI Pass

**Comment by Dwordcito** [comment]
Analyzing a little more deeply this, I draw the conclusion that the behavior is the one waiting if what is trying to print is the process name, this is not only hardcoded in ProcPS, but it is established in a constant define in the linux kernel.

[URL Linux Kernel code](https://github.com/torvalds/linux/blob/fe07bfda2fb9cdef8a4d4008a409bb02f35f1bd8/include/linux/sched.h#L215)

It would be a bad approach to take basename from the binary (obtaining the / proc / pid / exe or from the cmdline), since the process name can be changed in runtime with prctl and it would even be invalid by the previous thing and by how it is interpreted in the OS, 

[URL PRCTL](https://man7.org/linux/man-pages/man2/prctl.2.html)
As you can see, this limit also exists when setting the process name.

this should be treated as an enhancement, in which the path of the binary to which this process name refers should be shown.
