### ISSUE TITLE
Windows Wazuh Agent not collecting some logs - EventChannel - Windows Server 2016

### ISSUE THREAD

**Issue by K-razy** [wazuh/wazuh#7651]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.1 | Wazuh Agent | wazuh-agent-4.1.1-1.msi | Install Method : GUI | Windows 2016 Server 1607 | 

Hello, 
Hope you are fine, 

I'm not able to collect some Event with the last Wazuh Agent.
I'm trying to collect "Microsoft-Windows-TerminalServices-LocalSessionManager/Operational" or "Microsoft-Windows-TerminalServices-RemoteConnectionManager/Operational" logs without success : 

I used using the following lines in ossec.conf

1) Test 1 : Nok
 ` <localfile>
    <location>Microsoft-Windows-TerminalServices-LocalSessionManager/Operational</location>
    <log_format>eventchannel</log_format>
  </localfile>`

2) Test 2 : Nok
`<localfile>
    <location>Microsoft-Windows-TerminalServices-LocalSessionManager/Operational</location>
    <log_format>eventchannel</log_format>
    <query>Event/System[EventID \>= 0]</query>
  </localfile>`

3) Test 3 : Nok
`<localfile>
    <location>RDP</location>
    <log_format>eventchannel</log_format>
    <query>
      \<QueryList>
        \<Query Id="0" Path="Microsoft-Windows-TerminalServices-RemoteConnectionManager/Operational">
          \<Select Path="Microsoft-Windows-TerminalServices-RemoteConnectionManager/Operational">*\</Select>
        \</Query>
      \</QueryList>
    </query>
  </localfile>`

In ossec log, i can see the following line in ossec.log : 
ossec-agent: INFO: (1951): Analyzing event log: 'Microsoft-Windows-TerminalServices-RemoteConnectionManager/Operational'.

But nothing in wazuh manager.
i enabled : logall option in the server side, and no data concerning Local or RemoteConnection

If you have some idea.

Thanks a lot
King Regards

**Comment by chemamartinez** [comment]
Hi @K-razy,

Thanks for your detailed report.

Your configuration looks correct, I'd test the basic configuration (without any filter) to be able to collect all the events generated for these channels:

```xml
<localfile>
    <location>Microsoft-Windows-TerminalServices-LocalSessionManager/Operational</location>
    <log_format>eventchannel</log_format>
</localfile>

<localfile>
    <location>Microsoft-Windows-TerminalServices-RemoteSessionManager/Operational</location>
    <log_format>eventchannel</log_format>
</localfile>
```

Once that configuration is applied, restart the agent and force the firing of events from that channel.

The [Microsoft docs](https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-terminalservices-localsessionmanager) say that it is the component in charge of starting the computer, as well as the mechanism for switching between user accounts. So, for example, switching between user accounts should fire a few events from that channel.

It is important that the Wazuh agent is running when the events appear. It is possible that the logs related to the computer starting are not read by the agent since they are generated before the Wazuh agent starts to run.

You can check that the events are properly generated while the Wazuh agent is running by checking the logs timestamp in the Event Viewer tool:

<img width="1629" alt="Screenshot 2021-03-11 at 10 34 53" src="https://user-images.githubusercontent.com/29475387/110767786-e8d4f180-8256-11eb-8022-4cbaeedc2d29.png">

Once you are sure that events from these channels are generated while the Wazuh agent is monitoring them, these logs should appear in the `archives.log` file if the `logall` option is enabled on the manager side.

I hope it helps.

Best regards.

**Comment by K-razy** [comment]
Hi @chemamartinez 

First of all thanks a lot for taking time to reply.
I tried again to configure all, with 

1) logall options enabled in server side
2) On Agent Side 

`<localfile>
    <location>Microsoft-Windows-TerminalServices-LocalSessionManager/Operational</location>
    <log_format>eventchannel</log_format>
</localfile>`

I confirm that the log are available in archives.log (Sorry it's in French)

`{"win":{"system":{"providerName":"Microsoft-Windows-TerminalServices-LocalSessionManager","providerGuid":"{5D896912-022D-40AA-A3A8-4FA5515C76D7}","eventID":"25","version":"0","level":"4","task":"0","opcode":"0","keywords":"0x1000000000000000","systemTime":"2021-03-28T16:43:39.619325100Z","eventRecordID":"421","processID":"728","threadID":"416","channel":"Microsoft-Windows-TerminalServices-LocalSessionManager/Operational","computer":"OTP-01.LABS.local","severityValue":"INFORMATION","message":"\"Services Bureau à distance : réouverture de session réussie :\r\n\r\nUtilisateur : LABS\\Administrateur\r\nID session: 1\r\nAdresse réseau source : 192.168.69.100\""},"eventXML":{"user":"LABS\\\\Administrateur","sessionID":"1","address":"192.168.69.100"}}}`

3) I created a very simple rule to match the log 

`<rule id="999001" level="5">
    <field name="win.system.eventID">25</field>
    <description>RDP Connection : Success</description>
  </rule>`

4) I tested using ossec-logtest and wazuh-logtest and everything seems working.

`ossec-testrule: Type one log per line.

{"win":{"system":{"providerName":"Microsoft-Windows-TerminalServices-LocalSessionManager","providerGuid":"{5D896912-022D-40AA-A3A8-4FA5515C76D7}","eventID":"25","version":"0","level":"4","task":"0","opcode":"0","keywords":"0x1000000000000000","systemTime":"2021-03-28T16:43:39.619325100Z","eventRecordID":"421","processID":"728","threadID":"416","channel":"Microsoft-Windows-TerminalServices-LocalSessionManager/Operational","computer":"OTP-01.LABS.local","severityValue":"INFORMATION","message":"\"Services Bureau à distance : réouverture de session réussie :\r\n\r\nUtilisateur : LABS\\Administrateur\r\nID session: 1\r\nAdresse réseau source : 192.168.69.100\""},"eventXML":{"user":"LABS\\\\Administrateur","sessionID":"1","address":"192.168.69.100"}}}


**Phase 1: Completed pre-decoding.
       full event: '{"win":{"system":{"providerName":"Microsoft-Windows-TerminalServices-LocalSessionManager","providerGuid":"{5D896912-022D-40AA-A3A8-4FA5515C76D7}","eventID":"25","version":"0","level":"4","task":"0","opcode":"0","keywords":"0x1000000000000000","systemTime":"2021-03-28T16:43:39.619325100Z","eventRecordID":"421","processID":"728","threadID":"416","channel":"Microsoft-Windows-TerminalServices-LocalSessionManager/Operational","computer":"OTP-01.LABS.local","severityValue":"INFORMATION","message":"\"Services Bureau à distance : réouverture de session réussie :\r\n\r\nUtilisateur : LABS\\Administrateur\r\nID session: 1\r\nAdresse réseau source : 192.168.69.100\""},"eventXML":{"user":"LABS\\\\Administrateur","sessionID":"1","address":"192.168.69.100"}}}'
       timestamp: '(null)'
       hostname: 'Debian10'
       program_name: '(null)'
       log: '{"win":{"system":{"providerName":"Microsoft-Windows-TerminalServices-LocalSessionManager","providerGuid":"{5D896912-022D-40AA-A3A8-4FA5515C76D7}","eventID":"25","version":"0","level":"4","task":"0","opcode":"0","keywords":"0x1000000000000000","systemTime":"2021-03-28T16:43:39.619325100Z","eventRecordID":"421","processID":"728","threadID":"416","channel":"Microsoft-Windows-TerminalServices-LocalSessionManager/Operational","computer":"OTP-01.LABS.local","severityValue":"INFORMATION","message":"\"Services Bureau à distance : réouverture de session réussie :\r\n\r\nUtilisateur : LABS\\Administrateur\r\nID session: 1\r\nAdresse réseau source : 192.168.69.100\""},"eventXML":{"user":"LABS\\\\Administrateur","sessionID":"1","address":"192.168.69.100"}}}'

**Phase 2: Completed decoding.
       decoder: 'json'
       win.system.providerName: 'Microsoft-Windows-TerminalServices-LocalSessionManager'
       win.system.providerGuid: '{5D896912-022D-40AA-A3A8-4FA5515C76D7}'
       win.system.eventID: '25'
       win.system.version: '0'
       win.system.level: '4'
       win.system.task: '0'
       win.system.opcode: '0'
       win.system.keywords: '0x1000000000000000'
       win.system.systemTime: '2021-03-28T16:43:39.619325100Z'
       win.system.eventRecordID: '421'
       win.system.processID: '728'
       win.system.threadID: '416'
       win.system.channel: 'Microsoft-Windows-TerminalServices-LocalSessionManager/Operational'
       win.system.computer: 'OTP-01.LABS.local'
       win.system.severityValue: 'INFORMATION'
       win.system.message: '"Services Bureau à distance : réouverture de session réussie :

Utilisateur : LABS\Administrateur
ID session: 1
Adresse réseau source : 192.168.69.100"'
       win.eventXML.user: 'LABS\\Administrateur'
       win.eventXML.sessionID: '1'
       win.eventXML.address: '192.168.69.100'

**Phase 3: Completed filtering (rules).
       Rule id: '999001'
       Level: '5'
       Description: 'RDP Connection : Success'
**Alert to be generated.

`

But the problem is that nothing appears in the Dashboard, and i really can't understand why.

Do you have any idea ?

Thanks a lot

Kind Regards

**Comment by chemamartinez** [comment]
Hi @K-razy,

I think I have the reason why the event is not properly firing the alert.

Let me give you a little bit of context to understand what is happening: 

Even the Windows events are in JSON format, the Wazuh analysis engine processes them with a special decoder instead of using the generic JSON decoder. That's why some fields need extra processing.

This behavior is not replicated when testing events with Logtest, which processes Windows events through the JSON decoder. 
```
**Phase 2: Completed decoding.
decoder: 'json'
```
There exists an open issue to add support for these events and test Windows rules with more accuracy. https://github.com/wazuh/wazuh/issues/2765

On the other hand, the problem here is that the rule you created is independent of the rest of Windows rules. If you want to extend the Windows ruleset for a new channel you have to respect the Windows rule tree. [Here](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/how-to-collect-wlogs.html#windows-ruleset-redesign) you can read more about the Windows ruleset.

The rule base for Windows events right now is:
```xml
<rule id="60000" level="0">
    <category>ossec</category>
    <decoded_as>windows_eventchannel</decoded_as>
    <field name="win.system.providerName">\.+</field>
    <options>no_full_log</options>
    <description>Group of windows rules</description>
</rule>
```
Located at https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/ruleset/rules/0575-win-base_rules.xml#L15
Notice that this file contains the base rules for every monitored channel, so the first rule you have to create should look like:

```xml
<rule id="999001" level="0">
    <if_sid>60000</if_sid>
    <field name="win.system.channel">^Microsoft-Windows-TerminalServices-LocalSessionManager/Operational$</field>
    <options>no_full_log</options>
    <description>Group of Windows rules for the Local Session Manager channel</description>
</rule>
```

After that, you can create child rules from it. For example, replicating the rule you created:

```xml
 <rule id="999002" level="5">
    <if_sid>999001</if_sid>
    <field name="win.system.eventID">25</field>
    <description>RDP Connection : Success</description>
</rule>
```

That way you can create as many rules as you need to filter events from that channel.

I hope it helps, don't hesitate to contact us if you need further assistance with this.

Best regards,
Chema.

**Comment by K-razy** [comment]
Hi @chemamartinez 

Hope you are fine.
Thanks a lot for your detailed answer.

However i'm still having this issue :(
I really understand, your explanation which were very clear for me.

But the event still appear on archive.log, but still nothing on the Wazuh DashBoard.

We agree that i supposed to add rules on "local_rules.xml" ?

Maybe i'm doing something wrong but i can't find 

Thanks again for your help

Kind Regards

**Comment by K-razy** [comment]
Closing this issue, thanks to @chemamartinez 

The solution was to use Rule id 60009 (event as INFORMATION)

Thanks a lot

Kind Regards
