### ISSUE TITLE
No error is shown when AR command is not available

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh#766]
Hello team,

I've been testing active response command. More concretely, I've been testing whether an error is shown in the `ossec.log` when an active response command is not available. To do so:

1. I've added a test custom rule and decoder following the [docs](https://documentation.wazuh.com/current/user-manual/ruleset/custom.html).
2. I've added the following active response configuration:
    ```xml
    <command>
      <name>win_route-null</name>
      <executable>route-null.cmd</executable>
      <expect>srcip</expect>
      <timeout_allowed>yes</timeout_allowed>
    </command>

    <active-response>
      <command>win_route-null</command>
      <location>local</location>
      <rules_id>100010</rules_id>
    </active-response>
    ```
3. I've run the following command to raise an alert with that rule:
   ```shellsession
   # logger -t example User 'admin' logged from '193.556.35.2'
   # tail /var/ossec/logs/alerts/alerts.log
   ** Alert 1528736012.151616: - local,syslog,sshd,
   2018 Jun 11 18:53:32 debian->/var/log/syslog
   Rule: 100010 (level 8) -> 'User logged'
   Jun 11 18:53:32 debian example: User admin logged from 193.556.35.2
   ```

After this process, no errors are shown in ossec.log file.

Best regards,
Marta

**Comment by Cerv1** [comment]
Hi Marta,

This isn't exactly an error because of the following reasons:

1. If you define an **invalid command** inside the `active-response` configuration in `/var/ossec/etc/ossec.conf`, an error will appear after you restart indicating that the command is invalid.

2. If you give an **invalid response** to the agent, an error indicating that you selected a non existing active response.

3. If the agent has to execute a **non existing script**, it'll write in the log the following output:

  ```
  2018/06/13 08:55:03 ossec-execd: INFO: Active response command not present: '/var/ossec/active- 
  response/bin/restart-ossec.cmd'. Not using it on this system.
  ```
But it'll only be written the first time to prevent flooding on the `ossec.log` files.

Hope you find this useful Marta.

Regards,
Sergio.
