### ISSUE TITLE
Kibana Doesnt work on Ossec Unix System

### ISSUE THREAD

**Issue by ChrisCMCS** [wazuh/wazuh#77]
Hi There,
I am new to a company as a network technician. 
I have been tasked with fixing their kibana system, I don't have any UNIX or Linux background apart from installing a few Linux systems.

The machine runs on a VM the reports still work we can work with it but currently the dashboard doesn't load at all.. when you do "service kibana4 status" it will say Kibana is running but then after about 30 minutes, it will say Kibana is not running. 

I would love all the help i can get. My colleague knows a lot of code and is familiar with UNIX systems so if any code is needed he can enter this with me.

Apparently this is a Necessity for the company. So it currently works just the dashboard doesn't- if the logs don't get stored we are pretty screwed from my understanding.

Regards,
Chris.

**Comment by snaow** [comment]
Hi @ChrisCMCS,

Are you using Wazuh HIDS ? I think your problem is not related to Wazuh, creating a issue on this repository is not accurate, please feel free to forward your current issue to our mailing list:
https://groups.google.com/forum/#!forum/wazuh

If your issue is strictly related to Kibana maybe you can find some help at official Kibana discussion forums at: https://discuss.elastic.co/c/kibana

Still, let me try to help you here and close the issue.
I think your problem is maybe related to VM total available RAM, Kibana 4.x garbage collector is not so efficient and in some cases the SO shutdown Kibana process. Please take a look at our documentation for a fix to "Kibana on low memory systems": http://documentation.wazuh.com/en/latest/ossec_elk_kibana.html#kibana-on-low-memory-systems

Best regards,
Pedro Sanchez.
