### ISSUE TITLE
Scan by delta in Vulnerability Detector and alert enhancement - Analysis

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#7750]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/7749, we need to implement changes in many components in order to improve the way in which Vulnerability Detector performs the scans and trigger alerts. Having said that, we should analyze the next key points in order to define all the tasks that will involve the development of this epic.

- Analyze the way in which dbsync updated the agents' databases with the information of the installed packages.
- Analyze the way in which we could define a unique way to identify the vulnerabilities that affect a package in the `vuln_cves` table with the packages in the table `sys_programs`.
- Analyze and research the best way for implementing the event handler.
- Review the integration tests status for either Vulnerability Detector as well as dbsync.

We will consider this task done by documenting all the items in a comment.

**Comment by pereyra-m** [comment]
**Review the integration tests status for either Vulnerability Detector as well as dbsync**

The integration tests for Vulnerability Detector have some known issues that should be addressed by the end of this new epic:

- We can get different results depending on the host hardware resources. A common criteria should be defined.
- Currently, some test are not valid. For example, the `update_from_year` option isn't used properly. 

Also, new tests should be designed by the QA team, so we can be totally sure that the vulnerability detector engine keeps working as expected. Many of the existing tests are configuration oriented. 

The most important tests for this implementation are inside the **test_scan_results** folder, and they have no problem in Jenkins: [https://ci.wazuh.info/job/test_integration_vulnerability_detector/313](https://ci.wazuh.info/job/test_integration_vulnerability_detector/313).

On the other hand, the dbsync library is used in some tests of **analysisd** and **FIM**, and can be used as examples for this vulnerability detector implementation.

**Comment by DProvinciani** [comment]
**Analyze and research the best way for implementing the event handler**

I spent some time exploring alternatives to implement an event handler for Vulnerability Detector. There are two key points that I took into consideration:

- The event handler could receive requests coming from different sources. 
- The event handler will prepare the information that will be used by the scaner.
- The event handler will be responsible for triggering the scans.
- It could be performing/triggering a scan at the moment of receiving a request.

This made me think on the event handler as if it were a dispatching queue. So, it should be:

- The event handler should expose a socket to where the ones that want to trigger the scans will send the requests.
- The event handler will have a thread responsible for receiving the scan requests from the socket and save them in a queue.
- The event handler will have a dispatching thread that will take scan requests from the queue and will do the next actions:
    - It will prepare the information to be scanned in the `cve.db` database.
    - It will trigger the scans.
    - It will take the scan results and will save the vulnerabilities in the agents' databases and trigger the proper alerts.

**Comment by palaciosjeremias** [comment]
**Analyze and research how to synchronize sys_programs and hotfixes modifications with vuln_cves:**
First, I investigated the way that **syscolector** updates the agents DB (**sys_programs** and **hotfixes** tables) to find a way to trigger actions in **vulnerability detector** that could update **vuln_cve** table and start a new scan with modified packages.
The below diagram represents this proposal where **rsync** would trigger actions in **wuln_detector** **event handler**.
![Deltas proposal](https://user-images.githubusercontent.com/11434230/110179232-768f8780-7de6-11eb-9d96-44d682d3790f.png)
But this proposal isn't valid, after a meeting with **dbsync** developers, we found that it is not possible to generate triggers because **rsync** isn't handling packages deltas, thus, there are no events that could trigger vuln_detector.

So, a new proposal was generated represented in the diagrams below:
![Vuln_det proposal](https://user-images.githubusercontent.com/11434230/110179650-341a7a80-7de7-11eb-9ec6-4c3d84704ccf.png)
![Full Scan](https://user-images.githubusercontent.com/11434230/110179676-3ed50f80-7de7-11eb-8735-3991f688aff0.png)
![Partial Scan](https://user-images.githubusercontent.com/11434230/110179680-41376980-7de7-11eb-86e8-df2930a29719.png)
In this new proposal, **sys_programs** and **hotfix** tables are synchronized with **vuln_cves** to tag a deleted package as obsolete in **vuln_cves**. Note that, to do this, the entries of these tables have to be related.
On the other hand, the partial and full scan concepts are conserved from the legacy implementation of **vuln_det**. 
But now, a partial scan will generate alerts only if the alert is new (not found in **vuln_cves** table) and will be able to delete obsolete vulnerabilities because of the synchronization between the packages and vulnerabilities tables.
Also, the full scan is now only required when the **CVE** feed has changed or if a user request it **on_demand**. During a full scan, every package is scanned, but only new vulnerable packages are reported. And if a package isn't vulnerable anymore it is removed from the table.

**Comment by MiguelazoDS** [comment]
**Research about the possibility of enforcing the relationship between unrelated tables.**

According to this little research, shouldn't be hard to perform some code modifications that let us establish a relationship between the tables `vuln_cve` and `sys_programs`, which ones are part of the same database.

Since the columns created in the first table are just made from a few fields of a bigger structure called `report`, we can make use of the rest of this structure fields to create a more detailed table. 

The structure `report` is filled with information extracted for the tables involved in the definition of package vulnerabilities, it has for example, a field called `software` that contains information of a package. 

What it lacks of definition is the amount of information we need to include in the tables to achieve this goal, because we also need to take into account CVEs that are not part of a package itself but as a vulnerability of the OS, and also in case of Windows should be required to include the `sys_hotfixes` table.

**Comment by DProvinciani** [comment]
After designing the enhancements for the Vulnerability Detector alerting mechanism, we decided to implement a set of POCs that could help us to estimate the work that we have to do for this epic. The POCs are:

- Insert a hash in the `sys_programs` table for the legacy agents in order to uniquely identify the information of a software entry. In this POC should be determined which fields should be taken into account for calculating the hash. https://github.com/wazuh/wazuh/issues/7813

- Add a hash in the database table that contains information related to the OS to identify it. This will allow us to uniquely match the vulnerabilities that affect the OS. https://github.com/wazuh/wazuh/issues/7814

- Propagate a hash from the OS and packages database tables to the `agents` and `cpe_index` tables. This hash will allow us to match the vulnerabilities with either the OS as well as the packages. https://github.com/wazuh/wazuh/issues/7815

- Implement a SQL trigger that at the moment of removing an entry from `sys_programs` could take an action over the `vuln_cves` table. https://github.com/wazuh/wazuh/issues/7816

- Add the propagated hash to the JOIN SQL statements in order to have in the vulnerabilities scan results the hashes of the affected packages as well as the OS. https://github.com/wazuh/wazuh/issues/7817

- Implement a new alert type to report CVEs that no longer affect the manager. https://github.com/wazuh/wazuh/issues/7818

**Comment by DProvinciani** [comment]
As all the POCs were completed (check the closing comment of each of them), closing this issue.
