### ISSUE TITLE
Adapt Arch Linux OS detection to the data provider

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#7765]
### Description

#7058 adds the detection of the Arch Linux distribution through the OS scanner. These changes have to be adapted to the Syscollector refactor performed at https://github.com/wazuh/wazuh/issues/6104.

### Tasks

- The data provider should support the OS inventory for Arch Linux
- Adapt unit tests to cover all the added code for the data provider

**Comment by MarcelKemp** [comment]
After a research, I have verified that the Arch Linux OS is already detected with the new changes applied in master on syscollector (#7745).

Specifically, it uses the _UnixOsParser::parseFile_  function since it gets the data from the `/etc/os-release` file, although it also has the reading of `/etc/arch-release` (in my case it was empty).

And finally, as we do not have any version of the Arch Linux OS, we have collected the `os_build` field in the _UnixOsParser_ (obtained from `BUILD_ID`), to provide more information about the system to the user. Commit: https://github.com/wazuh/wazuh/commit/21ff5759935014782bdf61f2f21b553dddb16833
