### ISSUE TITLE
Insert a hash in the sys_programs table for the legacy agents

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#7813]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/7749, we need to uniquely identify the alerts generated in Vulnerability Detector with the packages saved in the agents' databases. For doing this, an easy solution should be using the hash that identifies each package entry in the `sys_programs` table.

The legacy packages do not contain the hash in the information. As part of this POC we should explore the possibilities of adding it without causing any impact on other components.

In addition, as part of this POC it should be determined which information fields should be used to calculate the hash in order to uniquely identify the packages avoiding variations in the hash after each Syscollector scan.

**Comment by palaciosjeremias** [comment]
The first approach for this solution was to recycle the **checksum** field of **sys_programs** to calculate it on the manager side even if the legacy agents don't calculate and sync it. Having calculated it, this field will be capable to be propagated on the vulnerability analysis to uniquely identify the CVE against the vulnerable software.
But this approach wasn't able because the same field is nowadays used by **dbsync** synchronization mechanism to detect when the table entry was generated by a legacy agent; in which case, a special synchronization is required to avoid duplicated entries after an agent upgrade from legacy to newer versions.
To solve this, the final approach is to use **item_id** as the unique identifier for every **sys_programs** entry. This field is **NULL** for legacy agents so it must be calculated on the insertion. But as it isn't used by other modules it doesn't generate conflict if the manager calculates and updates this field.
**Item_id** is a **SHA1** checksum using **name**, **version** and **architecture** of the program.
On the other hand, **sys_osinfo** table will require also a unique identifier even for legacy agents. In this case, the checksum field isn't used for **dbsync** to identify legacy agents, so it can be calculated by the manager without conflicts.
