### ISSUE TITLE
Implement a trigger to update the vuln_cves table with the sys_programs entryes get modified

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#7816]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/7749, we need to perform updates over the vulnerabilities inserted in the `vuln_cves` table when they get updated or modified. Having said that, as part of this POC, a SQL trigger should be implemented to update the vulnerabilities statuses when an entry is modified in the `sys_programs` table.

It should be taken into account the scenario of legacy agents where the entries are not updated. All the entries are removed and added again. As an approach for this case, the trigger should set the vulnerabilities as obsolete when an entry is removed and then as valid if an entry is inserted and its hash has a coincidence with a vulnerability in the `vuln_cves` table.

**Comment by pereyra-m** [comment]
### PoC implementation

The key points of this implementation are listed below:

- The `vuln_cves` table was modified, the `state` and `item_id` columns were added
- Two triggers were implemented for the `sys_programs` table, for the INSERT and DELETE operations
- The **SHA1()** method from `<openssl/sha.h>` was used for inserting the corresponding hash **(item_id)** for legacy agents in  `sys_programs` (**wdb_package_save()**) and for vulnerable packages in `vuln_cves` (old and new agents)

#### New columns in vuln_cves

The `item_id` column is required to identify every package uniquely according to its **name**, **version** and **architecture**. It should be equal to the one found in `sys_programs`. It is calculated at the time of inserting the vulnerabilities (**wdb_agents_insert_vuln_cve()**), but this isn't possible in the real implementation because the packages data may change in the process of vulnerable software detection.

The `state` column is used to reflect the condition of a vulnerability: if that package doesn't exist anymore, it is considered "INVALID" and should be removed later in a new vulnerability detector scan. If a package is inserted and it has a corresponding row in `sys_programs`, it state should be "VALID".

```
    CREATE TABLE IF NOT EXISTS vuln_cves (
        name TEXT,
        version TEXT,
        architecture TEXT,
        item_id TEXT,
        cve TEXT,
        PRIMARY KEY (name, version, architecture, cve)
    );
```

#### SQLite triggers

It was found that neither the old nor the new agents perform an UPDATE operation on the `sys_programs` table (it is done by a combination of INSERT and REMOVE), so only two triggers were created.

```
    CREATE TRIGGER package_delete
        AFTER DELETE ON sys_programs
    BEGIN
        UPDATE vuln_cves SET state = 'INVALID' WHERE vuln_cves.item_id = old.item_id;
    END;

    CREATE TRIGGER package_insert
        AFTER INSERT ON sys_programs
    BEGIN
        UPDATE vuln_cves SET state = 'VALID' WHERE vuln_cves.item_id = new.item_id;
    END; 
```

The packages removal/update was tested with both type of agents, and the trigger worked as expected.

#### Package hash

The `<openssl/sha.h>` was used to calculate the hash of the packages. Here is a piece of the code used as reference

```
...
    SHA_CTX shactx;
    unsigned char digest[SHA_DIGEST_LENGTH];

    SHA1_Init(&shactx);
    SHA1_Update(&shactx, name, strlen(name));
    SHA1_Update(&shactx, version, strlen(version));
    SHA1_Update(&shactx, arch, strlen(arch));
    SHA1_Final(digest, &shactx);
    
    for (int i=0; i<SHA_DIGEST_LENGTH; i++)
        printf("%02x", digest[i]);
...
```

### Conclusion

The triggers mechanism is really useful in this situation, but there are still some things to define. 

For example, the old agent's **syscollector** mechanism erases and re-inserts the packages constantly, even when there was not a real change. This could trigger an undesired behavior, so maybe only the "DELETE" trigger could be used in that case in combination with the vulnerability detector side of the implementation. The Wazuh agent's version is stored in the `vuln_metadata` table if it's necessary.

Also, this analysis was around the packages, but in case of the OS, we have a slightly different scenario. 
In the case of a Windows agent, a change in the `sys_hotfixes` table should update the state of all the OS vulnerabilities because the hot-fixes are not present in the table `vuln_cves`.
