### ISSUE TITLE
Investigate and design framework and WazuhDBQuery changes for new MITRE endpoints

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#7820]
Hello team,

As part of the development of the [new MITRE endpoints](https://github.com/wazuh/wazuh/issues/7819) we should define the design to follow for the implementation.

We should evaluate the need of new WazuhDBQuery classes for each principal MITRE item (tactic, technique, mitigation, group and software) and a parent WazuhDBQueryMitre class. In this case, other MITRE items such as `Data source`, `Defense bypassed`, `Effective permission`, `Impact`, etc are left out of this iteration (investigate).

We should also evaluate current MITRE database in search of possible constraints for the development, including clear Primary and Foreign keys and available access to all the relationships.

Regards,

David J. Iglesias

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

As part of this design issue we have been analyzing the current MITRE database in the `dev-mitredb` branch. Here we can see the relational schema of this database:

![11-03-MITRE_ER](https://user-images.githubusercontent.com/15522808/110779820-49b6f680-8264-11eb-8ed9-9086723a054d.png)

For the implementation of the changes in MITRE on the API/Framework side this schema is valid, in principle we can get from the database all the necessary data as described here: 

- MITRE metadata.
- Tactics and their related techniques.
- Techniques and their related tactics, groups, software and mitigations.
- Mitigations and their related techniques.
- Groups and their related techniques.
- Software and their related techniques.
- References.

However, we would like to clarify some doubts regarding the database schema:

- In the database schema we can see that some of the relationships mentioned here are missing: https://github.com/wazuh/wazuh/issues/7612, for example, the table `use` does not have any relationship. For the development of the Framework part, this does not harm us in principle. However, we should clarify these cases.
- As for the `reference` table, the `id` refers to the `ids` of **tactic/technique/mitigation/group/software**. Right now the method we have to identify the `id` type is the `id` prefix (T for techniques, TA for tactics, M for mitigations), however, with groups and software this is not immediate. Giving rise to a possible lack of information for the Framework.

Finally, as for the implementation of a parent class, in principle it is not necessary because the queries, sort methods, searchs, etc are different depending on the table. However, it is possible that we can make a generic class for relational tables and for generic tables such as `contributor`, `alias` or `metadata`.

We will update this issue with more details about the implementation when we clarify the doubts with the database schema.

Regards,

Adrián Peña

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

We have discussed how we can improve the MITRE database especially the associative tables. We are going to add a new column that specifies the type of related element. In this way we will be able to make more efficient queries.

At the moment these are the basic queries to obtain information from the main tables of the MITRE database. For the tables without relations it is not necessary to make joined queries. Just add filters.

### Tactics

#### Get related tactic specifying a technique id:
```
SELECT tactic.* FROM tactic JOIN phase ON phase.tactic_id=tactic.id JOIN technique ON technique.id=phase.tech_id AND technique.id="attack-pattern--1c4e5d32-1fe9-4116-9d9d-59e3925bd6a2";
```

### Mitigations

#### Get related mitigation specifying a technique id:
```
SELECT mitigation.* FROM mitigation JOIN mitigate ON mitigate.source_id=mitigation.id JOIN technique ON technique.id=mitigate.target_id AND technique.id="attack-pattern--1c4e5d32-1fe9-4116-9d9d-59e3925bd6a2";
```

### Groups

#### Get related group specifying a technique id:
```
SELECT `group`.* from `group` JOIN use ON use.source_id=`group`.id JOIN technique ON technique.id=use.target_id AND technique.id="attack-pattern--1c4e5d32-1fe9-4116-9d9d-59e3925bd6a2";
```

#### Get related group specifying a software id:
```
SELECT `group`.* from `group` JOIN use ON use.source_id=`group`.id JOIN software ON software.id=use.target_id AND software.id="tool--fbd727ea-c0dc-42a9-8448-9e12962d1ab5";
```

### Software

#### Get related software specifying a technique id:
```
SELECT software.* from software JOIN use ON use.source_id=software.id JOIN technique ON technique.id=use.target_id AND technique.id="attack-pattern--1c4e5d32-1fe9-4116-9d9d-59e3925bd6a2";
```
#### Get related software specifying a group id:
```
SELECT software.* FROM software JOIN use ON use.target_id=software.id JOIN `group` ON `group`.id=use.source_id AND `group`.id="intrusion-set--fe8796a4-2a02-41a0-9d27-7aa1e995feb6";
```

#### Note: software, group and technique are related. Specifying one technique id we can get its related software and its related group. However, software and group are related too, specifying one group id we can get its related software. The use table has source_id and target_id. Technique always corresponds to "use.target_id" and group/software corresponds to "use.source_id", but in the relationship group-software, group corresponds with "use.source_id" and software with "use.target_id". This may change with the new column "Type".


### Technique

#### Get related technique specifying a tactic id:
```
SELECT technique.* FROM technique JOIN phase ON phase.tech_id=technique.id JOIN tactic ON tactic.id=phase.tactic_id AND tactic.id="x-mitre-tactic--2558fd61-8c75-4730-94c4-11926db2a263";
```

#### Get related technique specifying a group id:
```
SELECT technique.* FROM technique JOIN use ON use.target_id=technique.id JOIN `group` ON `group`.id=use.source_id AND `group`.id="intrusion-set--fe8796a4-2a02-41a0-9d27-7aa1e995feb6";
```

#### Get related technique specifying a software id:
```
SELECT technique.* FROM technique JOIN use ON use.target_id=technique.id JOIN software ON software.id=use.source_id AND software.id="tool--fbd727ea-c0dc-42a9-8448-9e12962d1ab5";
```

#### Get related technique specifying a mitigation id:
```
SELECT technique.* FROM technique JOIN mitigate ON mitigate.target_id=technique.id JOIN mitigation ON mitigation.id=mitigate.source_id AND mitigation.id="course-of-action--feff9142-e8c2-46f4-842b-bd6fb3d41157";
```

Regards,

Adrián Peña
