### ISSUE TITLE
Develop new MITRE technique endpoints

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#7824]
|Wazuh version|Component|
|---|---|
| N/A | API/Framework |

## Description

Hello team,

This issue focuses on the development and implementation of the new MITRE `technique` framework, API endpoints and all the necessary tests.

Regards,

David J. Iglesias

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

We have already implemented a first version of the MITRE techniques endpoint. For the creation of this endpoint we have added two new `WazuhDBQuery` classes. The first one is in charge of extracting from the "technique" table all the information of the specified techniques.

The second one is a class that will serve us for the development of the other endpoints. This is the one in charge of obtaining all the relations of a certain object. In this case we have used it to extract the relations of the collected techniques.

For the implementation of the Framework part, we have tried several options but the one that most convinces us is the development of an intermediate function between the Framework and `WazuhDBQueryMitre` which will be cached. This way, only the first time that information is requested from MITRE it will load all the information. This approach is convenient because the MITRE database is static and in case of updating it would be necessary to restart Wazuh so the cache would be cleared.

This is the current state of the endpoint:

```
/mitre/techniques:
  Parameters:
    - limit
    - offset
    - technique_ids
    - pretty
    - wait_for_complete
    - sort
    - select
    - search
    - q
```


This is an output example:

```
https://localhost:55000/mitre/techniques?offset=200&limit=1
```

```json
{
  "data": {
    "affected_items": [
      {
        "mitre_detection": "While detecting adversaries accessing credentials may be difficult without knowing they exist in the environment, it may be possible to detect adversary use of credentials they have obtained. Monitor the command-line arguments of executing processes for suspicious words or regular expressions that may indicate searching for a password (for example: password, pwd, login, secure, or credentials). See [Valid Accounts](https://attack.mitre.org/techniques/T1078) for more information.\n\nMonitor for suspicious file access activity, specifically indications that a process is reading multiple files in a short amount of time and/or using command-line arguments  indicative of searching for credential material (ex: regex patterns). These may be indicators of automated/scripted credential access behavior.\n\nMonitoring when the user's <code>.bash_history</code> is read can help alert to suspicious activity. While users do typically rely on their history of commands, they often access this history through other utilities like \"history\" instead of commands like <code>cat ~/.bash_history</code>.\n\nAdditionally, monitor processes for applications that can be used to query the Registry, such as [Reg](https://attack.mitre.org/software/S0075), and collect command parameters that may indicate credentials are being searched. Correlate activity with related suspicious behavior that may indicate an active intrusion to reduce false positives.",
        "network_requirements": 0,
        "description": "Adversaries may search compromised systems to find and obtain insecurely stored credentials. These credentials can be stored and/or misplaced in many locations on a system, including plaintext files (e.g. [Bash History](https://attack.mitre.org/techniques/T1552/003)), operating system or application-specific repositories (e.g. [Credentials in Registry](https://attack.mitre.org/techniques/T1552/002)), or other specialized files/artifacts (e.g. [Private Keys](https://attack.mitre.org/techniques/T1552/004)).",
        "modified_time": "2020-10-15 19:39:36.109000",
        "mitre_version": "1.1",
        "name": "Unsecured Credentials",
        "deprecated": 0,
        "created_time": "2020-02-04 12:47:23.631000",
        "id": "attack-pattern--435dfb86-2697-4867-85b5-2fef496c0517",
        "remote_support": 0,
        "related_tactics": [
          "x-mitre-tactic--2558fd61-8c75-4730-94c4-11926db2a263"
        ],
        "related_mitigations": [
          "course-of-action--20f6a9df-37c4-4e20-9e47-025983b1b39d",
          "course-of-action--2a4f6c11-a4a7-4cb9-b0ef-6ae1bb3a718a",
          "course-of-action--2f316f6c-ae42-44fe-adf8-150989e0f6d3"
        ],
        "related_software": [],
        "related_group": []
      }
    ],
    "total_affected_items": 670,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Techniques information was returned",
  "error": 0
}
```


The time spent on **the first query is on average about 1.6 seconds** on the computer used for development, this time decreases to **about 90 ms on average on subsequent calls** for the same computer.

**Comment by AdriiiPRodri** [comment]
## Status update

While testing we have detected an error in the [select_array](https://github.com/wazuh/wazuh/blob/a4ae0d260a28f4031ee8a28675cc69befad395c4/framework/wazuh/core/utils.py#L285) function invoked by the `process_array` function. When we apply a select to an object that lacks the key specified in the select we get the following error:

```
https://localhost:55000/mitre/techniques?technique_ids=attack-pattern--43e7dc91-05b2-474c-b9ac-2ed4fe101f4d&select=subtechnique_of
```

```json
{
  "title": "Bad Request",
  "detail": "Not a valid select field: name, subtechnique_of, id",
  "remediation": "Please, use only allowed select fields",
  "dapi_errors": {
    "master-node": {
      "error": "Not a valid select field: name, subtechnique_of, id"
    }
  },
  "error": 1724
}
```

However, when we perform the same operation but with an endpoint that uses `WazuhDB` to apply the select, we have that the behavior differs, we see that in this case the requested object is returned (in this case only the min_select_fields) and the key set in the select does not appear because the object does not contain it:

```
https://localhost:55000/agents?agents_list=000&select=group
```

```json
{
  "data": {
    "affected_items": [
      {
        "id": "000"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents information was returned",
  "error": 0
}
```

Under our criteria this second behavior is more correct so we have modified the function [select_array](https://github.com/wazuh/wazuh/commit/52ba92523a42bc703b7dbb02c67bb7fd8133d555) so that the behavior is the same, being like this:

```
https://localhost:55000/mitre/techniques?technique_ids=attack-pattern--43e7dc91-05b2-474c-b9ac-2ed4fe101f4d&select=subtechnique_of
```

```json
{
  "data": {
    "affected_items": [
      {
        "id": "attack-pattern--43e7dc91-05b2-474c-b9ac-2ed4fe101f4d",
        "name": "Process Injection"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Techniques information was returned",
  "error": 0
}
```

This change will be applied to all functions that use process_array, so that the behavior will be consistent throughout the Framework.

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

We are developing the whole test suite (integration tests, unittests) for the techniques endpoint. Right now we have implemented a first version of the integrated tests (without RBAC):

```
adriiiprodri@wazuh pytest -x test_mitre_endpoints.tavern.yaml 
================================================================================================ test session starts =================================================================================================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/git/wazuh/api/test/integration, configfile: pytest.ini
plugins: tavern-1.14.0, metadata-1.11.0, html-3.1.1
collected 2 items                                                                                                                                                                                                    

test_mitre_endpoints.tavern.yaml ..                                                                                                                                                                            [100%]

=========================================================================================== 2 passed, 5 warnings in 3.97s ============================================================================================
```

**Comment by AdriiiPRodri** [comment]
## Status update

```
adriiiprodri@wazuh python3 run_tests.py -rbac both -k mitre             
Collected tests [3]:
test_mitre_endpoints.tavern.yaml, test_rbac_black_mitre_endpoints.tavern.yaml, test_rbac_white_mitre_endpoints.tavern.yaml


test_mitre_endpoints.tavern.yaml 
	 2 passed, 5 warnings

test_rbac_black_mitre_endpoints.tavern.yaml 
	 2 passed, 5 warnings

test_rbac_white_mitre_endpoints.tavern.yaml 
	 2 passed, 5 warnings
```

**Comment by AdriiiPRodri** [comment]
## Status update

### Integration test: white_all
```
adriiiprodri@wazuh pytest -x test_rbac_white_all_endpoints.tavern.yaml  
================================================================================================ test session starts =================================================================================================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/git/wazuh/api/test/integration, configfile: pytest.ini
plugins: tavern-1.14.0, metadata-1.11.0, html-3.1.1
collected 154 items                                                                                                                                                                                                  

test_rbac_white_all_endpoints.tavern.yaml ..................................................................................................................................x..xx...................           [100%]

============================================================================== 151 passed, 3 xfailed, 156 warnings in 156.08s (0:02:36) ==============================================================================
```
