### ISSUE TITLE
Log investigation on MacOS

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#7847]
Hello team,

This issue is for research on reading the system log for MacOS. Due to the structure it uses, currently, the logs of this operating system are not checked in Wazuh, because the information is not in plain text in Syslog format. Unified Logger has its own database of events and the Console App and Log CLI command are used to poll DB for select log events.

It will be studied which is the best way to collect these events in Wazuh.

Regards

**Comment by JcabreraC** [comment]
## Interesting links

OS Logging:
https://developer.apple.com/documentation/os/logging
OSlog:
https://developer.apple.com/documentation/oslog
MacOS Unified log: 1 why, what and how:
https://eclecticlight.co/2018/03/19/macos-unified-log-1-why-what-and-how/
Example log:
https://pastebin.com/jsGXeRjV
Example log ( stream + ndjson)
https://pastebin.com/f8W7zGGa
log.h:
https://opensource.apple.com/source/xnu/xnu-3789.21.4/libkern/os/log.h.auto.html
Unified Logging and Activity Tracing (video):
https://developer.apple.com/videos/play/wwdc2016/721/
Man log:
https://www.manpagez.com/man/1/log/
https://www.dssw.co.uk/reference/log.html
Log show command:
https://community.splunk.com/t5/Archive/Mac-OS-X-Sierra-How-to-get-all-logs-from-the-Unified-Log/m-p/347711/highlight/true#M54520
Leveraging the Apple Unified Log for Incident Response:
https://www.crowdstrike.com/blog/how-to-leverage-apple-unified-log-for-incident-response/
Streaming OSLog
https://steipete.com/posts/logging-in-swift/ 
https://llvm.org/LICENSE.txt
https://github.com/llvm/llvm-project/tree/main/lldb/tools/debugserver/source/MacOSX/DarwinLog
System log view
https://www.howtogeek.com/356942/how-to-view-the-system-log-on-a-mac/
OSLog Review/Info:
https://krypted.com/mac-os-x/logs-logging-logger-oh/

**Comment by jnasselle** [comment]
## Configuration proposal
Values of `localfile` options will allow to get logs from OSLog
- `log_format`: use `oslog` in order to specify that localfile will capture information tru this mechanism.
- `location`: related to OSLog `type`: `activity`,`log`,`trace`
- `only-future-events`: allowed by getting logs from OSLog database.
- `query`: use [NSPredicate](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Predicates/AdditionalChapters/Introduction.html) as filter
### Example
The following `localfile` block will handle activity logs from `com.apple.geod`
```xml
<localfile>
  <log_format>oslog</log_format>
  <location>activity</location>
  <query>processImagePath CONTAINS[c] "com.apple.geod"</query>
</localfile>
```
## Implementation proposals

### Execution of `log` command line tool and get stdout

- Description: For each localfile, open a thread that invokes the macOS "log" process with the configured parameters and obtain its stdout. stdout can be in ndjson format (one json per line), which greatly simplifies the task.

- Advantages: the simplest at the implementation level.

- Disadvantages: a "log" process for each "channel" to avoid the overload of filtering the logs being on the agent side. It's not a fancy solution. Depends on `log` command (developed by third party)

- Impact analysis: determine the load that it would imply to have at least 5 (or any tentative number that represents an average of channels of interest) processes being achieved in parallel

### Use a native Swift intermediary tool

- Description: Develop a swift application that serves as an intermediary between logcollector and the logs db. It would fulfill the same functionality as the “log” tool, except that it would be specifically designed according to the requirements that are needed.

- Advantages: Handling the backpressure of logs using a high-level language like Swift and directly accessing the OSLog API and  OSLog framework. With a process (perhaps multi-threaded) it would be enough to do the job

- Disadvantages: Integration of a new programming language to the project. Developing and deploying a tool that runs independently from wazuh-agent. Hard to test. Longer development time

### Use OSLog SPI

- Description: Integrate the log capture mechanism to wazuh-agent via SPI (System Programming Interface. Private API that’s used within Apple’s frameworks) using LLDB implementation as reference.

- Advantages: fastest mechanism.

- Disadvantages: lack of documentation. Use of clang as compiler. License os ActivityStreamAPI.h (Apache)
