### ISSUE TITLE
Automatically update checksums on apt update?

### ISSUE THREAD

**Issue by knx** [wazuh/wazuh#786]
Hi, is there a way to automatically update syscheck cheksums when doing apt update on a host?

**Comment by bah07** [comment]
Hi @knx. I'm not sure I understand exactly what you want to do. 

If you need to update the hash of the files at the moment you do `apt update` you can activate the real time option of _Syscheck_ in this directory. For example:

`<directories check_all="yes" realtime="yes">repos-dir</directories>`

Note that the realtime option will send a real-time alert for every change that occurs in that directory. This could cause high resource consumption if that directory contains many files that are constantly changing.

I hope it'll be helpful. Don't hesitate to write again if you have any more questions.
Regards.

**Comment by knx** [comment]
Thank you for answering so quickly! 

I am wondering if there is a way to prevent the alert when you are doing a legitimate system updates. Ideally Wazuh could update stored file checksums automatically and do not send an alert.

**Comment by bah07** [comment]
Hi @knx, I understand, 

In order to know if the change that has taken place is legitimate or not we need information about who or what is producing it (Who-Data). We are currently developing this feature and will be available in future versions.

With this information we will be able to silent those alerts that come from certain users or processes.

You can see the progress in the following issue [#756](https://github.com/wazuh/wazuh/issues/756).
Regards.

**Comment by knx** [comment]
Awesome! I will wait until its completed then. Thank you for the explanation.
