### ISSUE TITLE
[Config_File] WatchGuard decoders and rules

### ISSUE THREAD

**Issue by simon-verbois** [wazuh/wazuh#7883]
Hello everyone, 

Here is my repository where I prepared decoders and rules for WatchGuard firewalls, I don't know how to create Pull Request so I publish them here.

https://github.com/simon-verbois/wazuh-watchguard

They allow to process watchguard firewall logs.

Here you go :p

**Comment by alromeros** [comment]
Hello @Simon-Verbois,

Thank you very much for opening this issue and for wanting to contribute to Wazuh's ruleset! Some notes regarding your contribution:

First of all, there's no problem if you want us to manually commit and merge your contribution. That being said, we usually prefer users themselves to open a **Pull Request** with their own commits: In that way, their contribution will not be overwritten by our commits, thus enriching Wazuh with user contributions. For more information, you can find [here](https://github.com/wazuh/wazuh/tree/master/ruleset#contribute) a guide that explains how to correctly contribute to our ruleset project.

That being said, in order to create a **Pull Request**, first fork the Wazuh repository as shown in the image:

![Screenshot from 2021-03-18 13-52-39](https://user-images.githubusercontent.com/52510206/111634610-f827e200-87f6-11eb-8fbc-df36ca7df9b3.png)

Then, download your repository and create a new branch from `master`. We usually use short, descriptive names starting with the related issue's number as our branch's names:  

`git checkout -b 7883-watchguard-rules-and-decoders`

Once you've created your branch, commit your changes (again, follow this [guide]( https://github.com/wazuh/wazuh/tree/master/ruleset#contribute) for more information) and, open the **Pull Request** with the Pull Request button from your branch's page in GitHub. For example, with this Branch I've personally created, I would go to the compare section of my branch to find the Pull Request button:

![Screenshot from 2021-03-18 13-10-39](https://user-images.githubusercontent.com/52510206/111635269-9ddb5100-87f7-11eb-963f-1723ef39b98d.png)

That should be enough for us to be able to review and merge your contribution. Finally, one last thing regarding your rules and decoder's IDs: We usually use numbers for our rules and decoders IDs that are under 100,000, so we'd recommend you to find some free ID's and change the ones in your rules, as large numbers like 20000 are usually meant for custom rules. [Here]( https://github.com/wazuh/wazuh/pull/7031) you can find a ruleset-related **Pull Request** for example purposes. 

Best regards,
Álvaro Romero.

**Comment by simon-verbois** [comment]
thank you for this answer, 
where can I find the rule id lists?

**Comment by alromeros** [comment]
Hello @simon-verbois,

To check which IDs are already in use you'll have to manually check both rules and decoders in our repository. However, it shouldn't be that time-consuming using a command like `grep` to filter the unwanted information. For example, after a quick search, I've found that IDs **89000, 89001, 89002...** are available.

I hope this helps!
