### ISSUE TITLE
Replacement for sha1 and md5 checksum ?

### ISSUE THREAD

**Issue by aremai** [wazuh/wazuh#79]
Hi guys,

since the announcement of the sha1 collision and md5 being vulnerable for a while as well, I wondered if there were considerations to replace sha1/md5 with something more reliable and secure like sha256 for syscheck/fim. what are your thoughts on the impact?

resources:
https://shattered.io/
http://valerieaurora.org/hash.html
https://www.thesslstore.com/blog/sha-1-collision-created/

just a thought. what do you think?

cheers,
theresa

**Comment by snaow** [comment]
Hi @aremai,

Sorry for late response.
I think it could be great to replace current SHA1 for SHA2, I think we will move into that when the time comes.

In order to do that for FIM feature, we could replace SHA1 functions by SHA2, they are located at:

https://github.com/wazuh/wazuh/blob/master/src/os_crypto/md5_sha1/md5_sha1_op.c#L55

Replacing Init, update and final by the newest versions will do the trick.

Said so, the modification is not so simple, for example, string length for sha256 is bigger than sha1, meaning that we will need to adjust some variables, which also will affect to OSSEC communications.

Cheers,
Pedro.

**Comment by aremai** [comment]
Hola @snaow ,

awesome, great to hear this Pedro! Yeah I thought that replacing SHA1 functions by SHA2 wouldn't be so trivial... I just thought it would be a nice idea in terms of security enhancement for a future release :)

You're doing fantastic work, keep up the great work!

adios,
theresa

**Comment by crolopez** [comment]
Hi,

Wazuh includes support for SHA256 from version 3.4.0. 

Let me close the issue.

Best regards.
