### ISSUE TITLE
[Config_File] Active-reponse decoder more inclusive for others languages 

### ISSUE THREAD

**Issue by simon-verbois** [wazuh/wazuh#7907]
**Hello everyone :)**

Here is a diffreent version of the decoders to make it work with other languages (French, English, etc.).

https://github.com/simon-verbois/wazuh-ar

There is 4 examples, 2 on Linux and 2 on Windows.
<br>
_Linux:_
EN : Wed Dec 7 18:12:14 UTC 2016 /var/ossec/active-response/bin/route-null.sh delete - 192.168.2.4 1481134294.521764 100
FR : mer 17 mar 2021 10:54:16 CET /var/ossec/active-response/bin/disable-account.sh add usertest - 1615974856.216416928 5720

_Windows :_ 
EN : Wed 12/07/2016 19:40:06.89 "active-response/bin/restart-ossec.cmd" add "-" "10.99.99.12" "(from_the_server) (no_rule_id)"
FR : 17-03-21 10:16:55,83 "active-response/bin/restart-ossec.cmd" add "-" "null" "(from_the_server) (no_rule_id)"

<br><br><br>
PS : I don't know how to make a pull request, sorry
<br>
Bye

**Comment by jotacarma90** [comment]
Hi @simon-verbois 
First of all, thank you very much for contributing to our development. We are very grateful.

In order to create a PR in our repository, you will need to create a fork of Wazuh in your repository, you can found a guide step by step here:
https://jarv.is/notes/how-to-pull-request-fork-github/

On which version of Wazuh have you checked your decoder?
You will have to create the branch associated to the PR with the base of your choice.

**Comment by simon-verbois** [comment]
I'm on 4-1.2

I've created a pull request :)


Thanks
Bye
