### ISSUE TITLE
API fails to return custom CDB lists (with certain characters in filename)

### ISSUE THREAD

**Issue by DGawr** [wazuh/wazuh#7931]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.2 | API | Manager | Packages | Ubuntu 20.04.2 LTS |

The new API fails to return custom CDB lists when the filenames contains certain characters, like dots or underscores, because it checks the filename against the `^[\-\w]+$` pattern. This prevents viewing and editing such lists through the API (or the Kibana App), even though they still work.

Error message:
```
{
  "error": "3013",
  "message": {
	"title": "Bad Request",
	"detail": "'forcepoint_domain.blacklist' does not match '^[\\-\\w]+$'. Failed validating 'pattern' in schema: {'pattern': '^[\\-\\w]+$', 'type': 'string'}. On instance: 'forcepoint_domain.blacklist'"
  }
}
```

This restriction was not applied in prior versions and in fact the documentation even uses an example with a CDB list including an underscore in its name (see [Wazuh Docs](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/ruleset.html#example-of-configuration)).
If this new restriction was planned, it should be reflected in the documentation so users can rename their existing lists.

**Comment by Selutario** [comment]
Hi @DGawr!

You are totally right. After the refactor of `/manager/files` endpoints in this epic https://github.com/wazuh/wazuh/issues/7148, the regex that is used to filter filenames was also modified and maybe we went too strict. 

It is allowed to use underscores since they are included in `\w`, but we believe that the most appropriate option will be to restore the use of points in the filenames. We will discuss it in the team and it will probably be fixed as part of this issue https://github.com/wazuh/wazuh/issues/7544. 

In any case, it is our fault not to realize that the documentation went outdated and that there were certain use cases that could be affected. I apologize for the inconvenience and I thank you for reporting this problem. 

Regards,
Selu.

**Comment by Selutario** [comment]
Hi again @DGawr,

In the end and after discussing it with the team, we believe that it is best not to allow points in the name since everything after the point is considered an extension. This, although allowed in the past, is a bad practice and could lead to future problems. 

Therefore, it will be necessary to update all those CDB lists filenames that were using dots. We will update the documentation based on your report. 

Again, sorry for the inconveniences and thank you for letting us know!

Regards,
Selu.

**Comment by DGawr** [comment]
Hi @Selutario,

thank you for the quick update and clarification!

No problem, the argumentation perfectly makes sense, we'll just rename our files then. 👍
