### ISSUE TITLE
I want to change wazuh-alerts-* to internal-alerts-*

### ISSUE THREAD

**Issue by vamse1988** [wazuh/wazuh#794]
Hello, i need yr help please, i'm a new member of wazuh, i've just follow the wzush online document 2.0 guide for system installation. The installation was done, i saw the "wazuh-alerts-*" when click on VIsualize button under agian click on any tab it showing "wazuh-alerts-*" , how to change from "wazuh-alerts-*" to internal-alerts-* [no results found]. May you help me ?

thanks

![2018-06-14-141617_1366x768_scrot](https://user-images.githubusercontent.com/40263003/41402303-93b9c3b0-6fdf-11e8-96d8-9f16c9b50759.png)
![2018-06-14-141623_1366x768_scrot](https://user-images.githubusercontent.com/40263003/41402304-93f656ae-6fdf-11e8-8210-2088ae116cd8.png)

**Comment by JuanjiJG** [comment]
Hello @vamse1988,

In Wazuh app v2.0, it's not possible to change the name of the `wazuh-alerts` index due to some hard-coded references to that name in the app source code.

Our latest app for Wazuh 3.3.0 and Kibana 6.2.4 has the ability to change the default index-name, and you can configure several files in order to generate indices with a different name.

In addition to this, I can see on your Kibana sidebar that the Wazuh app is not loaded. What is your current Kibana version? You can check it on the `Management` tab on the left sidebar.

Regards,
Juanjo

**Comment by vamse1988** [comment]
Hi JuanjiJG,

      Thank you JuanjiJG for quick reply , i changing to our names like wazuh to controller same thing only i trying to change wazuh-alerts- to internal-alerts- when i click on Visualize button after i got some more tabs in that  click on any tab it show title with wazuh-alerts-*, i want to change this name to my convenience name, please help me out from this issue.

Here i am using kibana version 5.6.3
                          wazuh ---2.1
![2018-06-14-141623_1366x768_scrot](https://user-images.githubusercontent.com/40263003/41416033-a1f0706e-7007-11e8-95bd-4d18ecc2bdc7.png)

**Comment by vamse1988** [comment]
Hi JuanjiJG,

  Thank you JuanjiJG for quick reply , i changing to our names like wazuh to controller same thing only i trying to change wazuh-alerts- to internal-alerts- when i click on Visualize button after i got some more tabs in that  click on any tab it show title with wazuh-alerts-*, i want to change this name to my convenience name, please help me out from this issue.

Here i am using kibana version 5.6.3
wazuh ---2.1


![2018-06-14-141623_1366x768_scrot](https://user-images.githubusercontent.com/40263003/41449934-b4947ff6-7081-11e8-92c4-4015de5283ce.png)

Thanks,
Vamse

**Comment by JuanjiJG** [comment]
Hello again @vamse1988,

You can create a new index pattern on the `Management` tab, on the left sidebar of Kibana web interface.

Open the `Index patterns` menu an click on the button to create a new one. Give it the desired name, and follow the steps. The required `Time Filter field name` has to be `@timestamp`.

This way, you can now select the new index pattern and mark it as the selected one with the star icon on the Index patterns section.

Keep in mind that this won't make the Wazuh app work, and you won't get new alerts if you use our Elasticsearch templates. Our previous versions of Wazuh or the Wazuh app were not capable of changing the index name due to some hard-coded references on the source code.

Let us know if you have more questions or problems.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
It's been more than a month since the last response to this issue, so I'll proceed to close it.

If you have more questions or problems, feel free to open a new issue, and if it's related to the Wazuh app, you can open the issue on [its repository](https://github.com/wazuh/wazuh-kibana-app/issues).

Regards,
Juanjo
