### ISSUE TITLE
Failure on the deployment command 

### ISSUE THREAD

**Issue by simon-verbois** [wazuh/wazuh#7946]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.2-1 | deployment tool | Manager | Sources | Fedora 33 |

Hello everyone,

I found a mistake on the deployment tool,
There is no space after the protocol setting, when you put this command on a client.
We have on the setting this "'UDP'WAZUH_AGENT_GROUP='default,debian,client'"  instead of "UDP" and no groups.
![image](https://user-images.githubusercontent.com/59267907/111682563-d04f7300-8824-11eb-88fb-ad2d86fd0f5a.png)

And would it be possible to add the choice of protocol in the tool?

<br>

Thanks,

Bye bye

**Comment by johnfont** [comment]
Hi @simon-verbois, Hope you’re doing well today!
Thank you for using Wazuh and for taking the time to report this.

This is observed because the manager is configured to use the UDP protocol to communicate with the agents. You can modify this in the manager's configuration file, under the `<remote>` section the `<protocol>` stanza is set to UDP.
Starting with Wazuh version 4.0.0 versions we changed the default manager-agent connection protocol to TCP. This is reflected on the [changelog here](https://github.com/wazuh/wazuh/blob/v4.1.2/CHANGELOG.md#changed-6).

If you upgraded from a previous version, then the configuration from the previous version may still be present and you may modify it to TCP.

As for the issue of the lack of space after the protocol settings on the deployment tool,  we are going to report this issue to our team in order to solve it on our next release.

Best regards!

**Comment by simon-verbois** [comment]
thanks to you, I don't have any problems with the protocols as I modify the orders before sending them to my customers ;)
I especially wanted to publish this bug
