### ISSUE TITLE
Define specific name for agents

### ISSUE THREAD

**Issue by simon-verbois** [wazuh/wazuh#7984]
Hello everyone,

I would like to deploy agents by giving them specific names (before adding them to the manager), but without changing their hostname, is this possible?

The purpose of this maneuver is to sort with rules in outlook by client the alerts mails (ex: in the subject if "company" then move to a certain folder), here is the kind of name I would like to give to the agent :

company.osname.etc

Thanks

Bye bye

**Comment by pereyra-m** [comment]
Hello @simon-verbois !

The agent's name is independent from its hostname, it is used as a default value in case you haven't assigned one. There are many different ways to deploy an agent.

For example, let's say you'll define the name during the installation. 
You can use [Deployment variables](https://documentation.wazuh.com/4.1/installation-guide/wazuh-agent/deployment_variables/deployment_variables.html), here the **WAZUH_AGENT_NAME** variable can be used:

`
WAZUH_MANAGER="10.0.0.2" WAZUH_AGENT_NAME="company.osname.etc" apt-get install wazuh-agent
`

Also, you can configure the [enrollment](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#enrollment) section after the installation. Since **v4.0**, the agents can request a key automatically and this section describes the parameters of the registration process. Modify the `<agent_name>` tag for every agent before running it to use that name instead of hostname

```
<client>
  <enrollment>
    <enabled>yes</enabled>
    <manager_address>10.0.0.2</manager_address>
    <port>1515</port>
    <agent_name>company.osname.etc</agent_name>
    ...
  </enrollment>
</client>
```

There are a few registration methods more. In the [Registering Wazuh agents](https://documentation.wazuh.com/4.1/user-manual/registering/) section you can find the manual methods (without auto-enrollment) using the command line or the API. And in [Deployment](https://documentation.wazuh.com/4.1/deployment.html) you have the automation tools, like Puppet and Ansible. The name can be specified in all of these methods.

I hope this information to be helpful to you.
Regards.
