### ISSUE TITLE
XML validation of /var/ossec/etc/ossec.conf fails if there is a prolog

### ISSUE THREAD

**Issue by redgryphon** [wazuh/wazuh#8050]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.4-1 | ossec-csyslogd | Manager | RPM package  | RHEL 8 |

Working with your ansible method of delivery I noticed I didn't find any tool to customize the ossec.conf file in order to configure a cluster. I managed to prepare and use a personal playbook using the standard xml feature of ansible. I noticed that it changes a bit the xml file adding the prolog `<?xml version='1.0' encoding='UTF-8'?>`. Obviously it's a perfect fine xml file but the validator doesn't like it and when I try to start the service with `systemctl start wazuh-manager` it prints this error in the journal: `ossec-csyslogd: CRITICAL: (1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).` I actually spent a lot of time trying to understand what was going on since the error is cryptic and all the other xml validator, including `xmllint` didn't complain.

My proposal for the resolution of this bug is doing one of the following, put in order of what I think it's best for sysadmins experience:

1. Make the parser actually accept the "prolog" situation
2. Print at least a better error message for debugging purposes

**Comment by redgryphon** [comment]
I need to say that I edited the issue (both the text and the body) because while trying to understand better the bug I find out it that the thing that made the parser not accept the xml file was the prolog added by the ansible xml module.

**Comment by vicferpoy** [comment]
Hello @redgryphon ,

Regarding the XML validation, the `ossec.conf` parser is based on XML, but it is really a subset of XML. That is why prologs, for instance, are not valid. In order to accept a prolog, you would have to treat it like another tag:

```xml
<?xml version='1.0' encoding='UTF-8'>
</?xml>
```

As for the error message, I agree. I will share this issue with the team to see if we can add something more descriptive.

Now, regarding the ansible issue, I believe you could use one of the variables under the `Wazuh manager` section to avoid using a personal playbook. Look for `wazuh_manager_cluster` here: https://documentation.wazuh.com/current/deploying-with-ansible/reference.html#wazuh-manager

That should do the job. If you have any more questions do not hesitate to ask.

Regards,
Víctor Fernández
