### ISSUE TITLE
Add new filter option to AWS wodle configuration to discard events

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#8055]
Hello team,

Due to some performance issues when pulling high quantity of logs from AWS services/buckets, we have decided to add a new option to the AWS module configuration to discard certain events based on a regex.

Something like:

```
<wodle name="aws-s3">
  <disabled>no</disabled>
  <interval>10m</interval>
  <run_on_start>yes</run_on_start>
  <skip_on_error>yes</skip_on_error>
  <bucket type="cloudtrail">
    <name>wazuh-cloudtrail</name>
    <aws_profile>default</aws_profile>
    <discard_regex>$REMOVE_IF_FOUND<discard_regex>
  </bucket>
</wodle>
```

The aws-s3 wodle should ensure the event is filtered with the `discard_regex` and it will not send the event to `analysisd` in case it matches.

Regards,

David J. Iglesias

**Comment by CarlosRS9** [comment]
In order to implement this requested feature we put forward 3 possible solutions, regarding where and how to apply the `regex` validation:

- Apply `json.dumps` to the message received from AWS and then use `re.match`.
- Apply `json.dumps` to the message received from AWS and then use `jq`
- Apply the `regex` to the message received from AWS in json format and discard it (if it matches) before applying the `json.dumps`.


To determine which one is the best solution in terms of performance we have set up a series of tests using a custom script and custom data. We have to check and compare the elapsed time for each proposed solution.The scenarios considered are the following ones:


**CASE 1: 100 bytes per log - 0% discarded events**

Having one file with `10000` logs and the size of every log is `100` bytes. The regex value aplied will discard none of these events.

**CASE 2: 500 bytes per log- 0% discarded events**

Having one file with `10000` logs and the size of every log is `500` bytes. The regex value aplied will discard none of these events.

**CASE 3: 1000 bytes per log - 0% discarded events**

Having one file with `10000` logs and the size of every log is `1000` bytes. The regex value aplied will discard none of these events.




**CASE 4: 100 bytes per log - 50% discarded events**

Having one file with `10000` logs and the size of every log is `100` bytes. The regex value aplied will discard none of these events.

**CASE 5: 500 bytes per log - 50% discarded events**

Having one file with `10000` logs and the size of every log is `500` bytes. The regex value aplied will discard none of these events.

**CASE 6: 1000 bytes per log - 50% discarded events**

Having one file with `10000` logs and the size of every log is `1000` bytes. The regex value aplied will discard none of these events.



**CASE 7: 100 bytes per log - 100% discarded events**

Having one file with `10000` logs and the size of every log is `100` bytes. The regex value aplied will discard none of these events.

**CASE 8: 500 bytes per log - 100% discarded events**

Having one file with `10000` logs and the size of every log is `500` bytes. The regex value aplied will discard none of these events.

**CASE 9: 1000 bytes per log - 100% discarded events**

Having one file with `10000` logs and the size of every log is `1000` bytes. The regex value aplied will discard none of these events.

**Comment by CarlosRS9** [comment]
## Status Update

We are currently working on a new solution to allow the user to specify the field name

**Comment by CarlosRS9** [comment]
We are currently working on a new solution to allow the user to specify on which field we want to apply the regex. The structure should be something like this:

```
<discard_regex field="FIELD_NAME"> REGEX </discard_regex>
```

The idea is to be able to specify more than one of those tags to improve flexibility. This new solution can be implemented using `jq`, so performance should be improved over the previous proposed solution. We are still working on the design and preliminary performance tests to determine which solution is the addecuated.

**Comment by CarlosRS9** [comment]
We have concluded the implementation of a recursion solution to this problem. This implementation is slower than the `json.dumps` solution and the current implementation (no skipping option) in the worst case scenario, but better overal for real case scenarios.
