### ISSUE TITLE
Refactor agent-info task to send all chunks from workers in just 1 task iteration

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#8056]
Hello team,

We have found a performance issue with the current design of the agent-info synchronization task. When the master node is very loaded, and due to the design of the `asyncio` queues, the agent-info task from the workers might take a long time to complete a full synchronization cycle.

Right now, the worker collects all information (stored in chunks) and then send it to the master node using `SendSync`, with 1 message for chunk. This communication is blocking, and the worker does not send the following chunk until it has received the OK from the master node. However, and as said above, if the master node is loaded, this causes a huge delay because each new chunk sent is queued up together with the chunks from all other worker nodes plus all other integrity and synchronization processed being handled by the master node.

We should ensure that once the agent-info synchronization task is started in the worker node, all chunks are sent to the master which will then send the information to `wazuh-db` in a single synchronous process. 

Regards,

David J. Iglesias

**Comment by Selutario** [comment]
## Issue update

Hi team!

A meeting is still pending to define the important aspects of the design. However, and after some tests, we can define that the protocol on which the new synchronization will work will be `send_string()`:
https://github.com/wazuh/wazuh/blob/bd86b194d6af7ee3daf60209aa40c4c09ef10ba7/framework/wazuh/core/cluster/common.py#L404-L426

This protocol allows us to send strings without a size limit. In case of exceeding `request_chunk` (5MB), they will be cut into pieces in the worker and rejoined in the master (that's what `send_string()` takes care of).

## Draft design
Therefore, the way it will work will be, very broadly, as follows: 
#### Worker side
1. Get the full list of agent-info chunks on the worker. 
2. Convert it to JSON and encode it. 
3. Send it to master using send_string, which will return a task_id. 
4. Once the sending is finished, notify the master by means of a new command (for example `sync_a_w_m)` of what the task_id of the string is.
#### Master side
5. The master, once the task id has been received, will decode the string stored inside said task_id and load it with `json.load()`.  
6. Each chunk will be sent to the local wazuh-db, its response stored and, once all are ready, the worker will be responded. 

Regards,
Selu.

**Comment by Selutario** [comment]
## Issue update

Hi team! 

Below we can see a diagram showing a summary representation of the initial draft design: 
![agent-info](https://user-images.githubusercontent.com/23361101/113009559-59956c80-9178-11eb-9326-b684c8297936.jpg)

However, there is a problem that prevents using this system. As you can see, the worker waits for the master's response once the master starts updating on its local wazuh-db the agent-info received in the chunks. Therefore, if this process is delayed for any reason, the worker could show a `timeoutError`. 

The best practice would be for the worker to finish its job once it has sent the `task_id` of the string to the master. Notwithstanding, the way in which this process could be carried out, which would be similar to integrity synchronization, cannot be done in the same way since the tools to be used (`send_file` vs `send_string`) have a completely different behavior. 

There are 2 alternatives:
- Write the information of all the chunks in a single text file and make use of all the methods already implemented for file synchronization. 
- Develop a whole new set of classes, methods and tools that allow you to work with send_string in a similar way to file syndronization right now. 

For now, I will continue to research and define possible designs for the second option. 

Regards,
Selu.

**Comment by Selutario** [comment]
## Issue update

Hi team!

The development of the key parts of the synchronization seems to be working correctly. Finally, a process similar to file synchronization has been carried out, but using only strings (which are stored in memory). The steps of synchronization are, summarized: 
- Worker asks for permission to sync agent-info.
- Worker gets chunks from agent-info on its local wazuh-db. 
- Worker sends them to the master as a string and gets a task_id. 
- Worker sends `sync_a_w_m` command to the master along with the task_id of the string. 
- Master starts an asyncio task and responds to the worker, who stops waiting. 
- The master executes the task (when possible) and updates all the chunks received. 
- The master sends to the worker data from the synchronization (updated chunks and errors found, if any). 

Below is an example of the worker log: 
```
2021/03/31 15:22:33 INFO: [Worker worker1] [Agent-info sync] Starting.
2021/03/31 15:22:33 DEBUG: [Worker worker1] [Agent-info sync] Permission to synchronize granted.
2021/03/31 15:22:34 DEBUG: [Worker worker1] [Agent-info sync] Obtained 51 chunks of data in 0.36594605445861816s to be sent.
2021/03/31 15:22:34 INFO: [Worker worker1] [Agent-info sync] Finished in 0.903s (51 chunks updated).
```

Regards,
Selu.

**Comment by Selutario** [comment]
## Issue update

Hi team!

I've been comparing the sync times of agent-info after the refactor with those of the master branch. The environment in both cases has been the same, and its characteristics are: 
- 10.000 agents -> 25 chunks of data
- 1 master node
- 1 worker node where the 10.000 agents are being updated

The time has been averaged, using the data from 58 synchronizations in both cases:
### Refactored agent-info
- **Mean:** 0.38968965517241 s
- **Median:** 0.381 s
- **Minimum:** 0.273 s
- **Maximum:** 0.603 s
- **Count:** 58
- **Sum:** 22.602 s
- **Raw data:** 
```
0.273, 0.275, 0.283, 0.298, 0.307, 0.312, 0.313, 0.315, 0.318, 0.318, 0.323, 0.324, 0.331, 0.332, 0.334, 0.338, 0.343, 0.343, 0.346, 0.346, 0.346, 0.350, 0.352, 0.352, 0.361, 0.368, 0.376, 0.377, 0.377, 0.385, 0.388, 0.389, 0.390, 0.395, 0.408, 0.409, 0.410, 0.415, 0.416, 0.417, 0.424, 0.424, 0.430, 0.436, 0.439, 0.442, 0.446, 0.454, 0.466, 0.469, 0.480, 0.480, 0.493, 0.497, 0.504, 0.516, 0.546, 0.603
```

### Old agent-info (currently in master branch)
- **Mean:** 0.46370689655172 s
- **Median:** 0.4425 s
- **Minimum:** 0.337 s
- **Maximum:** 0.747 s
- **Count:** 58
- **Sum:** 26.895 s
- **Raw data:** 
```
0.337, 0.341, 0.344, 0.358, 0.387, 0.391, 0.391, 0.391, 0.393, 0.395, 0.397, 0.400, 0.401, 0.401, 0.406, 0.406, 0.412, 0.417, 0.417, 0.418, 0.419, 0.421, 0.423, 0.425, 0.426, 0.430, 0.437, 0.438, 0.442, 0.443, 0.449, 0.450, 0.451, 0.458, 0.460, 0.462, 0.466, 0.471, 0.473, 0.479, 0.479, 0.480, 0.500, 0.501, 0.501, 0.511, 0.514, 0.524, 0.524, 0.528, 0.563, 0.568, 0.626, 0.628, 0.632, 0.671, 0.672, 0.747
```

In theory, these differences should be even more noticeable in loaded environments. However, that will have to be proven in appropriate tests for this purpose. 

Regards,
Selu.

**Comment by Selutario** [comment]
## Issue update

Hey team,

This is a simplified schematic of the current operation of the refactored agent-info synchronization:
![agent-info-2](https://user-images.githubusercontent.com/23361101/114044632-added180-9887-11eb-9a26-4471172bdb0c.jpg)

I am trying to make tools common for both file and string syncing. However, due to its characteristics, this is not being possible in most cases. 

I'm also trying to make the tools as generic as possible, so that they can be used not just for agent-info in the future, if necessary. 

Regards,
Selu.

**Comment by Selutario** [comment]
|Working branch|
|--|
|[8056-refactor-agent-info](https://github.com/wazuh/wazuh/tree/feature/8056-refactor-agent-info)|

## Issue update

Hi team, 

The development of this issue is almost finished. Things to do yet:
- Performance tests with more workers and integrity processes using CPU. 
- Run and update system tests. 
- Update docu.

Regards,
Selu.

**Comment by Selutario** [comment]
# Issue update
Hi team!

I have built an environment with the following characteristics: 
- 1 master
- 4 workers
- 40.000 agents (only information is ID, name, register-ip and key)

Then, using a script that updates the `sync_status` value in each worker's db, each worker has been getting the information from 10,000 unsynchronized agents (~25 chunks of 65KB of data) and sending it to the master as part of the agent-info sync process. 

A total of 45 synchronization cycles have been measured in each worker and a series of calculations have been carried out for each one, such as the mean, median, min/max, etc. This has been done in both the branch containing the agent-info refactor (`feature/8056-refactor-agent-info`) and the master branch, so that they can be compared. The results can be seen below. 

## Normal environment 
### Description
The environment as described above, with no other CPU loads other than agent synchronization.

### Results
The result after adding the times measured of the 4 workers, both with the agent-info refactor and without it, is:
|                | New agent-info   | Old agent-info   |
|----------------|------------------|------------------|
| Mean           | 0.40009444444444 | 0.65437777777778 |
| Median         | 0.4              | 0.652            |
| Range          | 0.268            | 0.994            |
| Min            | 0.272            | 0.364            |
| Max            | 0.540            | 1.358            |
| Numer of items | 180              | 180              |
| Sum            | 72.017           | 117.788          |

As we can see, the mean time in seconds that it takes for each worker to sync the information of 10.000 agents after the refactor is **0.40s**. Before the refactor, it took **0.654s** for each worker to complete an agent-info synchronization process (10.000 agents).

This represents a **time reduction of 38.85%**. Detailed comparisons for each worker can be seen below. 

#### Worker 1
|          | New agent-info   | Old agent-info   |
|----------|------------------|------------------|
| Mean     | 0.39964444444444 | 0.57351111111111 |
| Median   | 0.402            | 0.523            |
| Range    | 0.191            | 0.901            |
| Min      | 0.315            | 0.364            |
| Max      | 0.506            | 1.265            |

#### Worker 2
|          | New agent-info | Old agent-info   |
|----------|----------------|------------------|
| Mean     | 0.4078         | 0.73724444444444 |
| Median   | 0.407          | 0.690            |
| Range    | 0.224          | 0.888            |
| Min      | 0.303          | 0.459            |
| Max      | 0.527          | 1.347            |

#### Worker 3
|          | New agent-info   | Old agent-info             |
|----------|------------------|----------------------------|
| Mean     | 0.39375555555556 | 0.55655555555556           |
| Median   | 0.398            | 0.514                      |
| Range    | 0.239            | 0.604                      |
| Min      | 0.272            | 0.381                      |
| Max      | 0.511            | 0.985                      |

#### Worker 4
|          | New agent-info   | Old agent-info |
|----------|------------------|----------------|
| Mean     | 0.39917777777778 | 0.7502         |
| Median   | 0.396            | 0.698          |
| Range    | 0.214            | 0.751          |
| Min      | 0.326            | 0.607          |
| Max      | 0.540            | 1.358          |


## Stressed env
### Description
The environment as described above, but with 100.000 local rules files (`/var/ossec/etc/rules`) in the master and workers. The files are not modified so the master does not have to send them repeatedly to the workers. However, it does have to generate the MD5 for all of them and compare it with that of the workers, which increases the load on the cluster. 

### Results
|                | New agent-info  | Old agent-info  |
|----------------|-----------------|-----------------|
| Mean           | 1.6844166666667 | 3.2535277777778 |
| Median         | 0.751           | 2.2025          |
| Range          | 5.891           | 8.815           |
| Min            | 0.329           | 0.452           |
| Max            | 6.220           | 9.267           |
| Numer of items | 180             | 180             |
| Sum            | 303.195         | 585.635         |

With a more loaded environment, we see that the time difference for the synchronization of agent-info is even more significant. While for the new agent-info sync process it takes about **1.68s** to finish the synchronization of 10,000 agents in each worker, in the master branch the time is around **3.25s** on average. 

It represents a **time reduction of 48.22%**. Detailed comparisons for each worker can be seen below. 

#### Worker 1
|        | New agent-info  | Old agent-info |
|--------|-----------------|----------------|
| Mean   | 1.5809555555556 | 3.3688         |
| Median | 0.711           | 2.497          |
| Range  | 5.649           | 7.787          |
| Min    | 0.398           | 0.457          |
| Max    | 6.047           | 8.244          |

#### Worker 2
|        | New agent-info  | Old agent-info |
|--------|-----------------|----------------|
| Mean   | 1.4436888888889 | 3.1034         |
| Median | 0.718           | 1.941          |
| Range  | 5.023           | 6.701          |
| Min    | 0.329           | 0.452          |
| Max    | 5.352           | 7.153          |

#### Worker 3
|        | New agent-info | Old agent-info  |
|--------|----------------|-----------------|
| Mean   | 2.0094         | 3.3885777777778 |
| Median | 0.850          | 2.705           |
| Range  | 5.687          | 7.743           |
| Min    | 0.471          | 1.325           |
| Max    | 6.158          | 9.068           |

#### Worker 4
|        | New agent-info  | Old agent-info  |
|--------|-----------------|-----------------|
| Mean   | 1.7036222222222 | 3.1533333333333 |
| Median | 0.749           | 1.868           |
| Range  | 5.822           | 7.971           |
| Min    | 0.398           | 1.296           |
| Max    | 6.220           | 9.267           |

Regards,
Selu.
