### ISSUE TITLE
Rename ossec.log to wazuh.log and ossec.json to wazuh.json in API and Framework

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#8091]
|Wazuh version|Component|
|---|---|
| 5.0 | All |

The purpose of this issue is to rename `ossec.log` to `wazuh.log` and `ossec.json` to `wazuh.json` in Wazuh Framework/API according to https://github.com/wazuh/wazuh/issues/8086.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by mcarmona99** [comment]
**Working branch**: [feature/8091-rename-ossec-log-wazuh-api](https://github.com/wazuh/wazuh/tree/feature/8091-rename-ossec-log-wazuh-api)

**Comment by mcarmona99** [comment]
### Issue status

The issue is finished, the linked PR includes all the changes needed to rename `ossec.log` to `wazuh.log` in API and framework.

The PR is on hold until some rebases are made.
These rebases are needed to include the changes done in this https://github.com/wazuh/wazuh/pull/8333. These changes fix the API integration tests failing in the PR related to this issue (jenkins check).

**Rebases needed:**
- `5.0-dev` onto `master`
- `dev-rename-log` onto `5.0-dev`
- `feature/8091-rename-ossec-log-wazuh-api` onto `dev-rename-log`
