### ISSUE TITLE
Get the location information on decoder

### ISSUE THREAD

**Issue by stoksoz1** [wazuh/wazuh#8156]
It would be great to have a way to decode the location information on wazuh decoder section. Let's say we are collecting syslogs from 10 different linux server without wazuh agent, we are getting the log from 514-tcp and 5 of the servers are DMZ-XYZ-Server and the rest Local-XYZ-Server. We want to first see if all log sources are sending the logs, secondly we want to use different rule sets for the DMZ and different for the Local servers. If I can get the decoder to tag my DMZ-XYZ-Server with group = dmz-xyz-server , that would be great.

`<decoder name="web-accesslog">
  <location>10.10.10.20 | 10.10.10.30 | 10.10.10.40</location>
  </decoder>`

**Comment by juliancnn** [comment]
Hi @stoksoz1,

When using the Wazuh Syslog server, the location field is automatically filled with the client ip.

For example, if a Linux host with IP `192.168.0.5` sends the Wazuh Syslog server a message, then the location field is automatically filled with the ip `192.168.0.5`.

This field could then be used in a rule, without the need to modify the decoder, as follows::
```
  <rule id="..." level="..">
    ....
    <location>192.168.0.5</location>
    ....
  </rule>
```

It is important to note that the field value has no spaces, so if you want to match multiple ips, it could be as follows:

```
  <rule id="..." level="..">
    ....
    <location>10.10.10.20|10.10.10.30|10.10.10.40</location>
    ....
  </rule>
```

Another good news is that, as of version 4.1, Wazuh allows the use of PCRE2 and OSRegex in the location field. You may be interested in the following pages of documentation:
-  [Regular Expression Syntax](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html)
- [location](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#location)

Please let me know if this is helpful to you.

Regards,
Julian

**Comment by stoksoz1** [comment]
Thanks for the information juliancnn, I know we cat get the location information on the rule section. What I need to have location field separated on decoder section, according to my given regex.

**Comment by juliancnn** [comment]
Hi @stoksoz1.

Actually, the location field can be checked by regex at the rule matching stage, this allows to have a different set of rules depending on the location, for example, in the case of syslog, to separate rules according to subnets. 

Could you tell us about a use case of the feature you propose? This would help us to better understand its application.

Regards,
Julian

**Comment by juliancnn** [comment]
Hi @stoksoz1.

I will close this issue due to inactivity, if you find a use case for this proposal, feel free to reopen it.

Thank you for your contributions to the Wazuh community.
Regards,
Julian

**Comment by stoksoz1** [comment]
Hi juliancnn,
I know the location IP can be pull from rules using the regex matching, but what I need is to catch the location IP from the decoder. So, from decoder looking into IP address I can say this log coming from IPS server ,  IDS server or else. Then my rules will be different  according to the decoder location type.

**Comment by juliancnn** [comment]
Hi @stoksoz1 

Could you share with us a detailed example of this proposal? This would help us a lot to understand it and to see the actual limitations.
For example, you could share a log and a location, a decoder and 2 rules and tell us the behavior you are looking for.

sorry for the inconvenience, but I need a better understanding of the problem in order to solve it.

**Comment by branchnetconsulting** [comment]
Being able to match at the decoder level for a pattern in the location field would be extraordinarily helpful at times.  There are many cases where certain kinds of log lines (text or json) are not very distinctive but the filename (possibly combined with agent name) is very distinctive.  Applications that produce logs that Wazuh has to treat like syslog even though they are not rfc-compliant syslog records, tend to partly or entirely fail to get predecoded by Wazuh, which can make it very hard to identify the kind of log solely on the content of the log line itself.  I've wished for years to be able to make the decoder phase match against the <location> field at the decoder level.  This really needs to be at the decoder rather than the rule level since it is the decoder level that ensures that the event is routed to the correct target rule family.  And pcre2 regex support would be good in that a single parent decoder could look specifically for one or more filename patterns coming in from one or more listed agents.

You could earn even more kudos if you were to add an <agent-group> match option to both the decoder and rule levels so we can make decoders and/or rule families apply only events coming from agents in one or more agent-groups.  

For even more massive kudos, how about also making agent labels and syscheck tags accessible for rule based analysis?  That would absolutely add customization super-powers to the rule engine.

Kevin

**Comment by stoksoz1** [comment]
hi juliancc, let me try to explain my self little more. My request is to  able to detect the log source IP on the decoder side, and able to tag each log depends on their location. By the way this scenario is mostly log sources that deliver their logs to the wazuh manager using 514-TCP.

Log Source 1
`Sep 11 16:05:15 **192.168.10.1 1** 1599865515.687171503 events ip 192.168.10.68 from server mac E0:CB:BC:0F:XX:XX for client mac 8C:16:45:XX:XX:XX

Log Source 2
Sep 11 16:05:15 **192.168.10.41** 1 1599865515.687171543 events ip 192.168.10.6 from server mac E0:CB:BC:0F:XX:XX for client mac 8C:16:45:XX:XX:XX`

The idea is to separate Log 1 and Log 2, and tag Log 1 as SERVER1 and Log2 as SERVER2

**Comment by juliancnn** [comment]
Hi @stoksoz1 @branchnetconsulting  

Sorry for the late reply, we are going to discuss this feature request with the Wazuh team. I'll be writing you back with news as soon as possible.

Regards,
Julian

**Comment by jnasselle** [comment]
Hi @juliancnn,

In certain cases will be really helpful to bind some decoder to certain remote syslog configuration, and i think using location in decoder scope will be a good approach to solve this problem.

Regards,
NIco

**Comment by juliancnn** [comment]
Hi @stoksoz1 & @branchnetconsulting:

After reviewing this issue with the team, we agreed to implement this feature.
It has already been incorporated into our roadmap, so it will be available in a future version of Wazuh.

Thank you very much for your feedback.

Regards,
Julian
