### ISSUE TITLE
Fix the Arch Linux libraries building 

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#8167]
### Description

This issue is part of #7075.

The following two errors should be addressed before finishing the development.

- **Error when building `alpm` and `libarchive` libraries in a system different from Linux, such as Solaris and macOS.**

```
make: *** No rule to make target `external/pacman/lib/libalpm/libalpm.a', needed by `external'.  Stop.
```

- **Error when Jenkins builds 64 bits packages**

```
[ 85%] Building CXX object testtool/CMakeFiles/sysinfo_test_tool.dir/main.cpp.o
[100%] Linking CXX executable ../bin/sysinfo_test_tool
/build_wazuh/manager/wazuh-manager-4.3.0/src/external/libarchive/.libs/libarchive.so: undefined reference to `memcpy@GLIBC_2.14'
/build_wazuh/manager/wazuh-manager-4.3.0/src/external/libarchive/.libs/libarchive.so: undefined reference to `posix_spawnp@GLIBC_2.15'
collect2: error: ld returned 1 exit status
make[6]: *** [bin/sysinfo_test_tool] Error 1
```

Probably due to the `gcc` version used for the Jenkins tests is lower than the one that compiled the `libarchive` library.

**Comment by alromeros** [comment]
**Devel branch (first error):** https://github.com/wazuh/wazuh/tree/8167-fix-error-building-lib

**Comment by MarcelKemp** [comment]
Hi team,

After verifying that it is not possible to compile the **_libalpm_** library in _CentOS 5_ because the kernel version is equal to `2.6.18`, and the `O_CLOEXEC` flag is introduced in version `2.6.33`.

To solve this problem, the following cases have been considered:

- Compile the libraries only for _Arch Linux_ (so a specific package would have to be generated for it).
- Avoid compiling these libraries for _CentOS 5_, so that the package that is generated is compatible with most Linux (and the compilation for _CentOS 5_ would have to be modified).

In the end, it was decided to avoid compiling the libraries for _CentOS 5_ and _RHEL5_.

Devel branch: https://github.com/wazuh/wazuh/tree/8167-fix-compilation-centos5

**Comment by MarcelKemp** [comment]
After talking with the team, the issue has been reopened to modify the changes made for `CentOS 5` and keep the library design consistent according to the style guide.

**Comment by chemamartinez** [comment]
Done #8396. Thanks, @MarcelKemp @alromeros!
