### ISSUE TITLE
Arch linux feed is always updated even if there are no new changes

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh#8194]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.2.0 | Modulesd | Manager | Sources | Tested on Ubuntu Focal|

We're writing integration tests for the new Arch Linux support on Vulnerability Detector, as part of https://github.com/wazuh/wazuh-qa/issues/1119

We've detected that the feed for Arch Linux is always updated, that is, if the update interval is short, for example, 10 seconds, every 10 seconds the feed will be updated, even though there are no changes in it. 

On others os, the version of the feed is controlled and the update is only performed if there are any updates in the feed.

```
2021/04/13 10:12:33 wazuh-modulesd:vulnerability-detector[51094] wm_vuln_detector.c:4103 at wm_vuldet_check_feed(): INFO: (5400): Starting 'Arch Linux' database update.
2021/04/13 10:12:33 wazuh-modulesd:vulnerability-detector[51094] wm_vuln_detector.c:5750 at wm_vuldet_fetch_arch(): DEBUG: (5404): Trying to download 'https://security.archlinux.org/all.json'
2021/04/13 10:12:33 wazuh-modulesd:download[51094] wm_download.c:229 at wm_download_dispatch(): DEBUG: Downloading 'https://security.archlinux.org/all.json' to 'tmp/vuln-temp-fitted'
2021/04/13 10:12:35 wazuh-modulesd:download[51094] wm_download.c:249 at wm_download_dispatch(): DEBUG: Download of 'https://security.archlinux.org/all.json' finished.
2021/04/13 10:12:35 wazuh-modulesd:vulnerability-detector[51094] wm_vuln_detector.c:3799 at wm_vuldet_index_feed(): DEBUG: (5414): Refreshing 'Arch Linux' databases.
2021/04/13 10:12:35 wazuh-modulesd:vulnerability-detector[51094] wm_vuln_detector.c:2538 at wm_vuldet_insert(): DEBUG: (5415): Inserting vulnerabilities.
2021/04/13 10:12:35 wazuh-modulesd:vulnerability-detector[51094] wm_vuln_detector.c:2582 at wm_vuldet_insert(): DEBUG: (5419): Inserting Arch Linux vulnerabilities section.
2021/04/13 10:12:35 wazuh-modulesd:vulnerability-detector[51094] wm_vuln_detector.c:2833 at wm_vuldet_insert(): DEBUG: (5426): Inserting 'Arch Linux' vulnerabilities information.
2021/04/13 10:12:35 wazuh-modulesd:vulnerability-detector[51094] wm_vuln_detector.c:3805 at wm_vuldet_index_feed(): DEBUG: (5427): Refresh of 'Arch Linux' database finished.
2021/04/13 10:12:35 wazuh-modulesd:vulnerability-detector[51094] wm_vuln_detector.c:3810 at wm_vuldet_index_feed(): DEBUG: remove(tmp/vuln-temp): No such file or directory
2021/04/13 10:12:35 wazuh-modulesd:vulnerability-detector[51094] wm_vuln_detector.c:3816 at wm_vuldet_index_feed(): DEBUG: remove(tmp/vuln-temp.bz2): No such file or directory
2021/04/13 10:12:35 wazuh-modulesd:vulnerability-detector[51094] wm_vuln_detector.c:4126 at wm_vuldet_check_feed(): INFO: (5430): The update of the 'Arch Linux' feed finished successfully.
2021/04/13 10:12:35 wazuh-modulesd:vulnerability-detector[51094] wm_vuln_detector.c:7347 at wm_vuldet_run_sleep(): DEBUG: Sleeping for 10 seconds...
2021/04/13 10:12:45 wazuh-modulesd:vulnerability-detector[51094] wm_vuln_detector.c:7347 at wm_vuldet_run_sleep(): DEBUG: Sleeping for 1 seconds...
2021/04/13 10:12:46 wazuh-modulesd:vulnerability-detector[51094] wm_vuln_detector.c:4103 at wm_vuldet_check_feed(): INFO: (5400): Starting 'Arch Linux' database update.
2021/04/13 10:12:46 wazuh-modulesd:vulnerability-detector[51094] wm_vuln_detector.c:5750 at wm_vuldet_fetch_arch(): DEBUG: (5404): Trying to download 'https://security.archlinux.org/all.json'
2021/04/13 10:12:46 wazuh-modulesd:download[51094] wm_download.c:229 at wm_download_dispatch(): DEBUG: Downloading 'https://security.archlinux.org/all.json' to 'tmp/vuln-temp-fitted'
2021/04/13 10:12:47 wazuh-modulesd:download[51094] wm_download.c:249 at wm_download_dispatch(): DEBUG: Download of 'https://security.archlinux.org/all.json' finished.
2021/04/13 10:12:47 wazuh-modulesd:vulnerability-detector[51094] wm_vuln_detector.c:3799 at wm_vuldet_index_feed(): DEBUG: (5414): Refreshing 'Arch Linux' databases.
```

In other feeds this message appear: https://github.com/wazuh/wazuh/blob/3b372e6bc790b57cd13a7c41bbaeb4fdf195f2e4/src/error_messages/debug_messages.h#L21

We may need to check if there is a possibility to skip the feed download and update if there is no changes on it.

**Comment by alromeros** [comment]
**#8194 update:**

Hi team,

As we previously researched, the vulnerability feed provided by [Arch](https://security.archlinux.org/) does not contain the necessary metadata to check if the mentioned feed has been modified since the last scan. After a thorough investigation about our other options, we've decided to close this issue for the following reasons:

- When possible, It's intended to avoid unnecessary redundant scans in already updated logs, which is pointed out with the log message `VU_UPDATE_DATE`, as described in this issue. However, for small feeds with low vulnerability volume, the scanning process is not **CPU-demanding** enough to ensure the need for this procedure, as happens with the **Debian Security Tracker** or **Microsoft** feeds. With this being said, the **Arch Linux** feed can be considered is small enough to discard the need for this procedure.

- While testing additional fixes for the problem mentioned in this issue, the option that ended up being most feasible was to compare the **hashes** from previous feeds to the new one, to check if the **JSON** had been changed since the last scan. However, as hinted by the last point, this method ended up being more **CPU-demanding** than the scan itself, which seemed pointless when trying to avoid unnecessary scans for performance reasons.

With this being said, I suggest following the same procedure as with **Debian Security Tracker**, as `VU_UPDATE_DATE` ends up being pointless in small feeds for performance reasons.

Best regards,
Álvaro Romero.
