### ISSUE TITLE
Error with custom Arch Linux feed paths on vulnerability detector. 

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh#8197]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.2.0 | Modulesd | Manager | Sources | Tested on Ubuntu Focal|

* Tested with development commit 20caceacab9c95dfd75966c638b446cfdc63b589 from branch `7075-arch-linux-support`

We're writing integration tests for the new Arch Linux support on Vulnerability Detector, as part of https://github.com/wazuh/wazuh-qa/issues/1119

## Steps to reproduce

- Create a custom JSON file with the feed and try to use it, for example using the conf:
```
<vulnerability-detector>
    <enabled>yes</enabled>
    <run_on_start>yes</run_on_start>
    <provider name="arch"><enabled>yes</enabled>
    <path>/tmp/test/arch.json</path>
  </provider>
  </vulnerability-detector>
```

Where `/tmp/test/arch.json`is an empty folder with a unique file called `arch.json`(with a valid arch Linux feed, for example https://gist.github.com/spothound/9402c8bc0fb5dbd86d6a09c5407c8e1a), the feed will be imported correctly:

```
2021/04/13 14:29:03 wazuh-modulesd:vulnerability-detector[118877] wm_vuln_detector.c:4005 at wm_vuldet_fetch_feed(): DEBUG: (5484): Cleaning metadata for target 'ARCH'
2021/04/13 14:29:03 wazuh-modulesd:vulnerability-detector[118877] wm_vuln_detector.c:4020 at wm_vuldet_fetch_feed(): DEBUG: (5403): Fetching feed from '/tmp/test/arch.json'
2021/04/13 14:29:03 wazuh-modulesd:vulnerability-detector[118877] wm_vuln_detector.c:6826 at wm_vuldet_index_json(): DEBUG: (5408): Updating from '/tmp/test/arch.json'
2021/04/13 14:29:03 wazuh-modulesd:vulnerability-detector[118877] wm_vuln_detector.c:3799 at wm_vuldet_index_feed(): DEBUG: (5414): Refreshing 'Arch Linux' databases.
```

Now, if you create another file with a name starting by the same name, for example:

```
$> touch /tmp/test/arch.json.mytest
```

The vulnerability detector will attempt to parse both files and will fail with the second one if it isn't a valid json file.

```
2021/04/13 14:32:22 wazuh-modulesd:vulnerability-detector[119960] wm_vuln_detector.c:4005 at wm_vuldet_fetch_feed(): DEBUG: (5484): Cleaning metadata for target 'ARCH'
2021/04/13 14:32:22 wazuh-modulesd:vulnerability-detector[119960] wm_vuln_detector.c:4020 at wm_vuldet_fetch_feed(): DEBUG: (5403): Fetching feed from '/tmp/test/arch.json'
2021/04/13 14:32:22 wazuh-modulesd:vulnerability-detector[119960] wm_vuln_detector.c:6826 at wm_vuldet_index_json(): DEBUG: (5408): Updating from '/tmp/test/arch.json'
2021/04/13 14:32:22 wazuh-modulesd:vulnerability-detector[119960] wm_vuln_detector.c:6826 at wm_vuldet_index_json(): DEBUG: (5408): Updating from '/tmp/test/arch.json.mytest'
2021/04/13 14:32:22 wazuh-modulesd:vulnerability-detector[119960] wm_vuln_detector.c:4520 at wm_vuldet_json_parser(): ERROR: (5524): The 'Arch Linux' feed couldn't be parsed from '/tmp/test/arch.json.mytest' file.
```

## Use case

Let's say that I download a custom feed, compressed as a  `tar.gz` file, and I uncompress it but I keep it on the desired folder. I would end up with the following error:

```
root@focal:/tmp/test# ls
arch.json  arch.json.tar.gz
```

```
2021/04/13 14:35:43 wazuh-modulesd:vulnerability-detector[121029] wm_vuln_detector.c:4103 at wm_vuldet_check_feed(): INFO: (5400): Starting 'Arch Linux' database update.
2021/04/13 14:35:43 wazuh-modulesd:vulnerability-detector[121029] wm_vuln_detector.c:4005 at wm_vuldet_fetch_feed(): DEBUG: (5484): Cleaning metadata for target 'ARCH'
2021/04/13 14:35:43 wazuh-modulesd:vulnerability-detector[121029] wm_vuln_detector.c:4020 at wm_vuldet_fetch_feed(): DEBUG: (5403): Fetching feed from '/tmp/test/arch.json'
2021/04/13 14:35:43 wazuh-modulesd:vulnerability-detector[121029] wm_vuln_detector.c:6826 at wm_vuldet_index_json(): DEBUG: (5408): Updating from '/tmp/test/arch.json.tar.gz'
2021/04/13 14:35:43 wazuh-modulesd:vulnerability-detector[121029] wm_vuln_detector.c:4520 at wm_vuldet_json_parser(): ERROR: (5524): The 'Arch Linux' feed couldn't be parsed from '/tmp/test/arch.json.tar.gz' file.
2021/04/13 14:35:43 wazuh-modulesd:vulnerability-detector[121029] wm_vuln_detector.c:3810 at wm_vuldet_index_feed(): DEBUG: remove(tmp/vuln-temp): No such file or directory
2021/04/13 14:35:43 wazuh-modulesd:vulnerability-detector[121029] wm_vuln_detector.c:3813 at wm_vuldet_index_feed(): DEBUG: remove(tmp/vuln-temp-fitted): No such file or directory
2021/04/13 14:35:43 wazuh-modulesd:vulnerability-detector[121029] wm_vuln_detector.c:3816 at wm_vuldet_index_feed(): DEBUG: remove(tmp/vuln-temp.bz2): No such file or directory
2021/04/13 14:35:43 wazuh-modulesd:vulnerability-detector[121029] wm_vuln_detector.c:4111 at wm_vuldet_check_feed(): DEBUG: (5521): Failed when updating 'arch provider' database. Retrying in '300' seconds.
2021/04/13 14:35:43 wazuh-modulesd:vulnerability-detector[121029] wm_vuln_detector.c:4843 at wm_vuldet_main(): ERROR: (5513): CVE database could not be updated.
```

**Comment by spothound** [comment]
Update:

If there are multiple valid files, for example:

```
root@focal:/tmp/wazuh-qa# ls /tmp/wazuh-qa/tests/integration/test_vulnerability_detector/data/feeds/custom_archlinux_feed.json*
/tmp/wazuh-qa/tests/integration/test_vulnerability_detector/data/feeds/custom_archlinux_feed.json      /tmp/wazuh-qa/tests/integration/test_vulnerability_detector/data/feeds/custom_archlinux_feed.json.gz
/tmp/wazuh-qa/tests/integration/test_vulnerability_detector/data/feeds/custom_archlinux_feed.json.bz2
```

The vulnerability detector won't fail to update the feed but it will create duplicated entries in the database (one for each file).

**Comment by alromeros** [comment]
**#8197 update:**

Hi team,

After some research, I've gathered some information that hints that the behavior described in this issue is totally expected.

This behavior occurs due not to a lack of error handling or bug while parsing the **Arch Linux** custom feed, but to a lack of precision when defining what is expected and not while scanning said custom feed. After some testing, I've found that almost all other custom paths can be configured to output the same error.

For a better understanding of this issue, I'll use **RedHat**, **Debian** and **NVD** feeds as an example:

- Regarding the usage of custom **RedHat** feeds: Our [documentation](https://documentation.wazuh.com/4.0/user-manual/capabilities/vulnerability-detection/offline_update.html#red-hat) clearly specifies that only files whose names follow the `redhat-feed<number>.json` format should be used, indicated by the regular expression `<path>/local_path/rh-feed/redhat-feed.*json$</path>` (notice the '**$**' at the end). 

    While testing custom **RedHat** feeds, the same error as the one described in this issue can be replicated using a regular expression without the '**$**' character while scanning feeds with a similar pattern as the one used in this issue:

````
2021/04/15 11:49:09 wazuh-modulesd:vulnerability-detector[46959] wm_vuln_detector.c:4103 at wm_vuldet_check_feed(): INFO: (5400): Starting 'JSON Red Hat Enterprise Linux' database update.
2021/04/15 11:49:09 wazuh-modulesd:vulnerability-detector[46959] wm_vuln_detector.c:4005 at wm_vuldet_fetch_feed(): DEBUG: (5484): Cleaning metadata for target 'JREDHAT'.
2021/04/15 11:49:09 wazuh-modulesd:vulnerability-detector[46959] wm_vuln_detector.c:4020 at wm_vuldet_fetch_feed(): DEBUG: (5403): Fetching feed from '/var/ossec/feeds/rh-feed/redhat-feed.*json'
2021/04/15 11:49:56 wazuh-modulesd:vulnerability-detector[46959] wm_vuln_detector.c:6826 at wm_vuldet_index_json(): DEBUG: (5408): Updating from '/var/ossec/feeds/rh-feed/redhat-feed1.json.test'
2021/04/15 11:50:02 wazuh-modulesd:vulnerability-detector[46959] wm_vuln_detector.c:4520 at wm_vuldet_json_parser(): ERROR: (5524): The 'JSON Red Hat Enterprise Linux' feed couldn't be parsed from '/var/ossec/feeds/rh-feed/redhat-feed1.json.test' file.
````



- Regarding the usage of custom **Debian** feeds: This scenario is somewhat different. Our [documentation](https://documentation.wazuh.com/4.0/user-manual/capabilities/vulnerability-detection/offline_update.html#debian) specifies that a single **JSON** file described with an absolute path, and not with a regular expression should be used when attempting to perform an offline update. The usage of regular expressions or multiple feeds is not supported and leads to an error whilst scanning this feed.

- Lastly, regarding the usage of **NVD** feeds: Our [documentation](https://documentation.wazuh.com/4.0/user-manual/capabilities/vulnerability-detection/offline_update.html#national-vulnerability-database) specifies the following:


_Finally, you will have the feed divided into a succession of numbered files whose name follows format `nvd-feed<number>.json.gz`. **Those files are compressed and should be extracted**. To update locally, the path to those files must be indicated by a regular expression as such:_ 
```xml
<provider name="nvd">
    <enabled>yes</enabled>
    <path>/local_path/nvd-feed.*json$</path>
    <update_interval>1h</update_interval>
</provider>
````
Again, notice the ' **$**' character at the end of the regular expression. Omitting this character would lead, as with the **RedHat** feed, to the vulnerability detector attempting to scan files with unexpected suffixes (which would lead to an error as with **arch.json.mytest**) or expected formats like **json.gz** that could lead to double entries in the database.

With this being said, I suggest following the same procedure as with **NVD** and **RedHat** feeds, as handling these errors in the **vulnerability detector** code would lead to an intensive and undesired rework of several functions and tests :
- Specify in the documentation that only pure **JSON** files should be used as feeds when attempting to perform an offline update. Other cases should be handled as exceptions in tests.
- Also, specify that the regular expression that describes these feeds should end with the '**$**' character, thus avoiding errors with problematic formats and double entries in the database.

Best regards,
Álvaro Romero.
