### ISSUE TITLE
Add remote SCA capability's option to the setup/msi

### ISSUE THREAD

**Issue by jhjacobs81** [wazuh/wazuh#8233]
per documentation: https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/how_to_configure.html?highlight=sca#how-to-share-policy-files-and-configuration-with-the-wazuh-agents

i need to add sca.remote_commands=1 to some file before i can allow the Wazuh manager to push and manage policy's. While this is easy for me to do, this might not so easy for the people we send the agent to. Does anyone know of a way around this? Ive been looking into MSI editors but they can be quite expensive.

what i want is to send people ONE msi, that then connects to the right wazuh manager, grabs all the SCA policy's from the manager, etc etc. without our client having to meddle with files or command prompts.

**Comment by juanmanuelug** [comment]
Hi,

At first instance, I must tell you that the setting `sca.remote_commands` has `0` as default value because of security.

Since the manager is able to run remote commands in agents by different ways such as push SCA policies remotely, we added this setting to force the user giving explicit permissions to run these remote commands.

It is that why it makes no sense to enable this flag by default, or to provide any way to switch it remotely.

On the other hand, talking about Windows policies to MSI, at the moment the wazuh installer do not detect the specific Windows version where is getting installed. So, for now when installing the Wazuh agent in a Windows host, a generic SCA policy is placed.

In spite of that, we are currently working on improving the Windows installer to be able to detect the Windows version during the installation process, so the particular SCA policy for that version is installed. 

Here you could get more information about this Issue: https://github.com/wazuh/wazuh/issues/3912  and also you could take a look at the PR: https://github.com/wazuh/wazuh/pull/8724, so you could follow the development.

Thanks you!

**Comment by jhjacobs81** [comment]
I understand what you are saying, but we are looking to deploy the Wazuh agent to “dumb people” who have no clue how to do anything other then use outlook, let alone modify a config file :) Thats why they need us to monitor their system using Wazuh, and we are using the sca module to generate reporting about their systems.

**Comment by juanmanuelug** [comment]
Hi,

At first instance, if you want to modify a default installion of wazuh, you should modify the source code of Wazuh. 

About the `sca.remote_commands` value you should modify it in the following file to keep it in every upgrade of the software. https://github.com/wazuh/wazuh/blob/master/etc/local_internal_options.conf. 
In your case you may write a line like this: `sca.remote_commands=1` which will overwrite the default value..

On the other hand, speaking of generating a Windows agent. I will leave you the following repository so you could take a look at all the tools available to build a Wazuh package https://github.com/wazuh/wazuh-packages. 

Also in the documentation we have avalaible the following guide that explain how to generate an agent in Windows. https://documentation.wazuh.com/current/development/packaging/generate-windows-package.html#compiling-windows-agent.

Thanks you!
