### ISSUE TITLE
Vulnerability detector hotfix config enabled doesn´t work if the setting was enabled once

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#8236]
|Wazuh version|Component|Install type|
|---|---|---|
| 4.2 | Vulnerability Detector | Manager | 

On Wazuh Agent side, Syscollector has different configuration sections to enable/disable specific system information. One of them is the section **<hotfixes>**  that is enabled and hidden by default and works to determine if Syscollector has to collect or not hotfixes from the hosting OS.
On the manager side, Vulnerability Detector has a mechanism to check in vuln_metadata if **hotfixes_scan_id** is different than 0 in order to know if this setting was enabled or disabled. If the setting is disabled, the complete OS scan is bypassed.
But, **hotfixes_scan_id** will be 0 only if the hotfix scan wasn´t ever synced in the manager. If **<hotfixes>** is enabled only once, the agent will scan the hotfixes and the synchronization will update **hotfixes_scan_id**; after that, if the setting is disabled, the scan of the OS will not be bypassed anymore.
On the other hand, the [documentation](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/running_vu_scan.html) explicitly demands to turn on **<hotfixes>**. So, this mechanism can be considered obsolete and be deprecated.

**Comment by pereyra-m** [comment]
### Brief description

This issue has many different aspects:

- The **syscollecor** `<hotfixes>` configuration tag can be used to prevent the system scan in the agent, but the vulnerability detector module isn't able to recognize this situation in all possible cases. 
- The new agents don't use the **scan_id** variable, the OS would be bypassed every time

The situations described above are covered by the Issue #8273 and PR #8280: now that the module doesn't check **scan_id**, both new and old Windows agents will be scanned. And the configuration tag now can't modify the vulnerability detector behavior.

But now, there are some synchronization issues that should be analyzed.

### False positive time window

The vulnerability detector module has no knowledge of the synchronization status of the **syscollector** DB. 
Let's divide the analysis 

#### Hotfixes

If a Windows agent OS scan is performed with incomplete or inaccurate information, many false positives will be reported 

1. First scan :
- Legacy agents (less than v4.2) / New agents: There is no check of at least one valid scan. We could have the OS info but an empty hotfixes table only because the scan hasn't sent data yet

2. Regular scans:
- Legacy agents: even when there is no change in the hotfix table, this mechanism inserts all the data every time. If vulnerability detector queries the table during the synchronization time frame, incomplete data will be retrieved. This is considered the worst scenario described in this issue
- New agents: here, the synchronization mechanism is different. Only the changes are written, the query could receive an old list of hotfixes. This would be solved in the next scan, and the results are the same than a vulnerability scan run a few minutes before this exact moment. This situation is less critical.

#### Packages

An incomplete list of packages could generate a difference between the alerts generated in one scan and the following ones. Also, in newer versions of the vulnerability detector module, a previously detected CVE for a package would be reported as removed only because of a synchronization delay 

1. First scan :
- Legacy agents (less than v4.2) / New agents: if the **sys_programs** table is empty at the beginning, no false positives would be generated and the information would be completed later

2. Regular scans:
- Legacy agents: the situation here is similar to the hotfixes case.
- New agents: the situation here is similar to the hotfixes case.

### Tests

If we have a hotfixes table with an old complete scan and a new one in progress, the vulnerability detector module will only read the newest rows 

![hotfixes_table](https://user-images.githubusercontent.com/65046601/115788845-92e98280-a39a-11eb-8c7c-07477ce2b836.png)

**Comment by pereyra-m** [comment]
### PoC

We could solve these issues if the vulnerability detector module knows the synchronization state of the packages and hotfixes tables.

A **PoC** (`PoC-vuln-detector-hotfix-false-positive` branch ) was implemented to store a flag representing the sync status.

#### Test table

The results are stored in a simple test table
```
CREATE TABLE IF NOT EXISTS syscollector_sync_status (
    hotfix_sync_status INTEGER(1) DEFAULT 0,
    packages_sync_status INTEGER(1) DEFAULT 0
);
```

#### Legacy agents

The previous **syscollector** mechanism sends all the data and then a fake package/hotfix that represents the end of the synchronization. 

So, the "not-synced" state will be set every time there is a new insertion and the "synced" state at the end.

- **wdb_parse_packages()** after a correct insertion

```
...
wdb_exec(wdb->db, "UPDATE syscollector_sync_status SET packages_sync_status = 0;");
...
``` 

- **wdb_parse_hotfixes()** after a correct insertion
```
...
wdb_exec(wdb->db, "UPDATE syscollector_sync_status SET hotfix_sync_status = 0;");
...
```

- **decode_hotfix()** final hotfix found
```
} else if (strcmp(msg_type, "hotfix_end") == 0) {
...
snprintf(msg2, OS_SIZE_1024 - 1, "agent %s sql UPDATE syscollector_sync_status SET hotfix_sync_status = 1", lf->agent_id);
...
```

- **decode_package()** final package found
```
} else if (strcmp(msg_type, "program_end") == 0) {
...
 snprintf(msg2, OS_SIZE_1024 - 1, "agent %s sql UPDATE syscollector_sync_status SET packages_sync_status = 1", lf->agent_id);
...
```

#### New agents

The new synchronization module checks the DB state in the **wdbi_query_checksum()** method. According to the result and the component, the corresponding flag is set

```
        ...
        if(component == WDB_SYSCOLLECTOR_HOTFIXES ) {
             if (1 == retval || 0 == retval) {
                data = wdb_exec(wdb->db, "UPDATE syscollector_sync_status SET hotfix_sync_status = 0;");
        ...

             else if (2 == retval ) {
                data = wdb_exec(wdb->db, "UPDATE syscollector_sync_status SET hotfix_sync_status = 1;");
        ...
             
        } else if (component == WDB_SYSCOLLECTOR_PACKAGES) {
             if (1 == retval || 0 == retval) {
                data = wdb_exec(wdb->db, "UPDATE syscollector_sync_status SET packages_sync_status = 0;");
        ...

             else if (2 == retval ) {
                data = wdb_exec(wdb->db, "UPDATE syscollector_sync_status SET packages_sync_status = 1;");
        ...
```

#### Results

If the vulnerability detector module checks the state of the flag before running a scan, it wouldn't have the risk of having incomplete information.

It's important to consider that the new synchronization module doesn't call the **wdbi_query_checksum()** function when it finishes sending data. So, this approach would have a "not synced" flag for new agents during a long time until the new scan confirms the data is synced.

**Comment by DProvinciani** [comment]
Closing the issue as all the remaining cases were covered and fixed by the implementation of the epic https://github.com/wazuh/wazuh/issues/8529.
