### ISSUE TITLE
Map AWS current ruleset to MITRE ATT&CK

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#8265]
Review current rules for AWS and map them to mitre tactics and techniques, as specified on #6807.

**Comment by Nekaze** [comment]
All current AWS rules have been mapped to MITRE

| Rule File              | Rule ID | Level | Rule Description                                                                                                                                                                                                                                                                   | Technique | Tactic |
| ---------------------- | ------- | ----- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------- | ------ |
| 0350-amazon\_rules.xml | 80200   | 0     | AWS alert.                                                                                                                                                                                                                                                                         | NO        | NO     |
| 0350-amazon\_rules.xml | 80202   | 3     | AWS Cloudtrail: $(aws.eventSource) - $(aws.eventName).                                                                                                                                                                                                                             | NO        | NO     |
| 0350-amazon\_rules.xml | 80203   | 4     | AWS Cloudtrail: $(aws.eventSource) - $(aws.eventName). Error: $(aws.errorCode).                                                                                                                                                                                                    | NO        | NO     |
| 0350-amazon\_rules.xml | 80250   | 5     | AWS Cloudtrail: $(aws.eventSource) - $(aws.eventName). Error: $(aws.errorCode).                                                                                                                                                                                                    | NO        | NO     |
| 0350-amazon\_rules.xml | 80251   | 3     | AWS Cloudtrail: $(aws.eventSource) - $(aws.eventName).                                                                                                                                                                                                                             | NO        | NO     |
| 0350-amazon\_rules.xml | 80252   | 10    | AWS Cloudtrail: $(aws.eventSource) - $(aws.eventName) - high number of deleted object.                                                                                                                                                                                             | T1485     | TA0040 |
| 0350-amazon\_rules.xml | 80253   | 3     | AWS Cloudtrail: $(aws.eventSource) - $(aws.eventName) - User Login Success.                                                                                                                                                                                                        | T1078     | TA0001 |
| 0350-amazon\_rules.xml | 80254   | 5     | AWS Cloudtrail: $(aws.eventSource) - $(aws.eventName) - User Login failed.                                                                                                                                                                                                         | NO        | NO     |
| 0350-amazon\_rules.xml | 80255   | 10    | AWS Cloudtrail: $(aws.eventSource) - $(aws.eventName) - Possible breaking attempt (high number of login attempts).                                                                                                                                                                 | T1110     | TA0006 |
| 0350-amazon\_rules.xml | 80300   | 0     | AWS GuardDuty alert.                                                                                                                                                                                                                                                               | NO        | NO     |
| 0350-amazon\_rules.xml | 80301   | 3     | AWS GuardDuty: $(aws.service.action.actionType) - $(aws.title)                                                                                                                                                                                                                     | NO        | NO     |
| 0350-amazon\_rules.xml | 80302   | 6     | AWS GuardDuty: $(aws.service.action.actionType) - $(aws.title)                                                                                                                                                                                                                     | NO        | NO     |
| 0350-amazon\_rules.xml | 80303   | 10    | AWS GuardDuty: $(aws.service.action.actionType) - $(aws.title)                                                                                                                                                                                                                     | NO        | NO     |
| 0350-amazon\_rules.xml | 80305   | 3     | AWS GuardDuty: $(aws.service.action.actionType) - $(aws.title) \[IP: $(aws.service.action.portProbeAction.portProbeDetails.remoteIpDetails.ipAddressV4)\] \[Port: $(aws.service.action.portProbeAction.portProbeDetails.localPortDetails.port)\]                                   | T1046     | TA0007 |
| 0350-amazon\_rules.xml | 80306   | 6     | AWS GuardDuty: $(aws.service.action.actionType) - $(aws.title) \[IP: $(aws.service.action.portProbeAction.portProbeDetails.remoteIpDetails.ipAddressV4)\] \[Port: $(aws.service.action.portProbeAction.portProbeDetails.localPortDetails.port)\]                                   | T1046     | TA0007 |
| 0350-amazon\_rules.xml | 80307   | 10    | AWS GuardDuty: $(aws.service.action.actionType) - $(aws.title) \[IP: $(aws.service.action.portProbeAction.portProbeDetails.remoteIpDetails.ipAddressV4)\] \[Port: $(aws.service.action.portProbeAction.portProbeDetails.localPortDetails.port)\]                                   | T1046     | TA0007 |
| 0350-amazon\_rules.xml | 80325   | 3     | AWS ALB alert.                                                                                                                                                                                                                                                                     | NO        | NO     |
| 0350-amazon\_rules.xml | 80330   | 3     | AWS CLB alert.                                                                                                                                                                                                                                                                     | NO        | NO     |
| 0350-amazon\_rules.xml | 80335   | 3     | AWS NLB alert.                                                                                                                                                                                                                                                                     | NO        | NO     |
| 0350-amazon\_rules.xml | 80350   | 0     | AWS Macie alert.                                                                                                                                                                                                                                                                   | NO        | NO     |
| 0350-amazon\_rules.xml | 80351   | 3     | AWS Macie $(aws.severity): $(aws.name) - $(aws.summary.description)                                                                                                                                                                                                                | NO        | NO     |
| 0350-amazon\_rules.xml | 80352   | 4     | AWS Macie $(aws.severity): $(aws.name) - $(aws.summary.description)                                                                                                                                                                                                                | NO        | NO     |
| 0350-amazon\_rules.xml | 80353   | 6     | AWS Macie $(aws.severity): $(aws.name) - $(aws.summary.description)                                                                                                                                                                                                                | NO        | NO     |
| 0350-amazon\_rules.xml | 80354   | 8     | AWS Macie $(aws.severity): $(aws.name) - $(aws.summary.description)                                                                                                                                                                                                                | NO        | NO     |
| 0350-amazon\_rules.xml | 80355   | 12    | AWS Macie $(aws.severity): $(aws.name) - $(aws.summary.description)                                                                                                                                                                                                                | NO        | NO     |
| 0350-amazon\_rules.xml | 80400   | 0     | AWS VPC Flow alert.                                                                                                                                                                                                                                                                | NO        | NO     |
| 0350-amazon\_rules.xml | 80401   | 3     | AWS VPC Flow: \[$(aws.action)\] - Interface: $(aws.interface\_id) - Protocol: $(aws.protocol)                                                                                                                                                                                      | NO        | NO     |
| 0350-amazon\_rules.xml | 80402   | 4     | AWS VPC Flow: \[$(aws.action)\] - Interface: $(aws.interface\_id) - Protocol: $(aws.protocol)                                                                                                                                                                                      | NO        | NO     |
| 0350-amazon\_rules.xml | 80440   | 0     | AWS WAF alert.                                                                                                                                                                                                                                                                     | NO        | NO     |
| 0350-amazon\_rules.xml | 80441   | 0     | AWS WAF - Allowed request.                                                                                                                                                                                                                                                         | NO        | NO     |
| 0350-amazon\_rules.xml | 80442   | 3     | AWS WAF - Blocked request.                                                                                                                                                                                                                                                         | NO        | NO     |
| 0350-amazon\_rules.xml | 80443   | 10    | AWS WAF - Multiple Blocked request.                                                                                                                                                                                                                                                | T1190     | TA0001 |
| 0350-amazon\_rules.xml | 80450   | 0     | AWS Config alert.                                                                                                                                                                                                                                                                  | NO        | NO     |
| 0350-amazon\_rules.xml | 80451   | 0     | AWS Config - History                                                                                                                                                                                                                                                               | NO        | NO     |
| 0350-amazon\_rules.xml | 80452   | 0     | AWS Config - Snapshot                                                                                                                                                                                                                                                              | NO        | NO     |
| 0350-amazon\_rules.xml | 80453   | 0     | AWS Config - History \[$(aws.awsAccountId) $(aws.awsRegion)\] \[$(aws.resourceType)\]: $(aws.resourceId) ($(aws.configurationItemStatus))                                                                                                                                          | T1526     | TA0007 |
| 0350-amazon\_rules.xml | 80454   | 3     | The resource was newly discovered. AWS Config - History: \[$(aws.awsAccountId) $(aws.awsRegion)\] \[$(aws.resourceType)\]: $(aws.resourceId) ($(aws.configurationItemStatus))                                                                                                      | T1526     | TA0007 |
| 0350-amazon\_rules.xml | 80455   | 3     | The resource was discovered but its configuration was not recorded since the recorder excludes the recording of resources of this type. AWS Config - History: \[$(aws.awsAccountId) $(aws.awsRegion)\] \[$(aws.resourceType)\]: $(aws.resourceId) ($(aws.configurationItemStatus)) | T1526     | TA0007 |
| 0350-amazon\_rules.xml | 80456   | 3     | The resource was deleted. AWS Config - History: \[$(aws.awsAccountId) $(aws.awsRegion)\] \[$(aws.resourceType)\]: $(aws.resourceId) ($(aws.configurationItemStatus))                                                                                                               | T1070     | TA0005 |
| 0350-amazon\_rules.xml | 80457   | 3     | The resource was deleted but its configuration was not recorded since the recorder excludes the recording of resources of this type. AWS Config - History: \[$(aws.awsAccountId) $(aws.awsRegion)\] \[$(aws.resourceType)\]: $(aws.resourceId) ($(aws.configurationItemStatus))    | T1070     | TA0005 |
| 0350-amazon\_rules.xml | 80475   | 3     | AWS Config - Snapshot \[$(aws.awsAccountId) $(aws.awsRegion)\] \[$(aws.resourceType)\]: $(aws.resourceId) ($(aws.configurationItemStatus))                                                                                                                                         | NO        | NO     |
| 0350-amazon\_rules.xml | 80476   | 6     | AWS Config - Snapshot Compliance \[$(aws.awsAccountId) $(aws.awsRegion)\] \[$(aws.resourceType)\] \[$(aws.configuration.configRuleList.configRuleName)\]: $(aws.resourceId) ($(aws.configurationItemStatus)) $(aws.configuration.complianceType)                                   | NO        | NO     |
| 0350-amazon\_rules.xml | 80480   | 0     | AWS Trusted Advisor alert.                                                                                                                                                                                                                                                         | NO        | NO     |
| 0350-amazon\_rules.xml | 80481   | 5     | AWS Trusted Advisor - \[$(aws.uuid)\] \[$(aws.check-name)\]: $(aws.status)                                                                                                                                                                                                         | NO        | NO     |
| 0350-amazon\_rules.xml | 80482   | 4     | AWS Trusted Advisor - \[$(aws.uuid)\] \[$(aws.check-name)\]: $(aws.status)                                                                                                                                                                                                         | NO        | NO     |
| 0350-amazon\_rules.xml | 80483   | 3     | AWS Trusted Advisor - \[$(aws.uuid)\] \[$(aws.check-name)\]: $(aws.status)                                                                                                                                                                                                         | NO        | NO     |
| 0350-amazon\_rules.xml | 80490   | 0     | AWS KMS alert.                                                                                                                                                                                                                                                                     | NO        | NO     |
| 0350-amazon\_rules.xml | 80491   | 3     | AWS KMS: \[$(aws.eventName)\] $(aws.userIdentity.type)                                                                                                                                                                                                                             | T1078.004 | \-     |
| 0350-amazon\_rules.xml | 80492   | 3     | AWS KMS: \[$(aws.eventName)\] $(aws.userIdentity.type) - $(aws.userIdentity.userName) - $(aws.sourceIPAddress)                                                                                                                                                                     | T1078.004 | \-     |
| 0350-amazon\_rules.xml | 80493   | 0     | AWS KMS: \[$(aws.eventName)\] $(aws.userIdentity.type)                                                                                                                                                                                                                             | NO        | NO     |
| 0350-amazon\_rules.xml | 80494   | 0     | AWS KMS: \[$(aws.eventName)\] $(aws.userIdentity.type) - $(aws.userIdentity.userName) - $(aws.sourceIPAddress)                                                                                                                                                                     | NO        | NO     |
| 0350-amazon\_rules.xml | 80495   | 0     | AWS Inspector - Network assessment \[$(aws.createdAt)\]: $(aws.title) \[$(aws.severity)\]                                                                                                                                                                                          | NO        | NO     |
| 0350-amazon\_rules.xml | 80496   | 10    | AWS Inspector - Network assessment \[$(aws.createdAt)\]: $(aws.title) \[$(aws.severity)\]                                                                                                                                                                                          | T1046     | TA0007 |
| 0350-amazon\_rules.xml | 80497   | 7     | AWS Inspector - Network assessment \[$(aws.createdAt)\]: $(aws.title) \[$(aws.severity)\]                                                                                                                                                                                          | T1046     | TA0007 |
| 0350-amazon\_rules.xml | 80498   | 4     | AWS Inspector - Network assessment \[$(aws.createdAt)\]: $(aws.title) \[$(aws.severity)\]                                                                                                                                                                                          | T1046     | TA0007 |
| 0350-amazon\_rules.xml | 80499   | 3     | AWS Inspector - Network assessment \[$(aws.createdAt)\]: $(aws.title) \[$(aws.severity)\]

**Comment by Nekaze** [comment]
This rules will be added to default ruleset once #7556 is finished
