### ISSUE TITLE
Add an ability to add labels via ReST API

### ISSUE THREAD

**Issue by DaspawnW** [wazuh/wazuh#8293]
It would be great to be able to add after an Agent was registered successfully labels to it via the ReST API.
I saw the configuration example for adding AWS related information for example via this approach: https://documentation.wazuh.com/current/user-manual/capabilities/labels.html

But it would be great if for the Agent this is "transparent" and someone who uses AWS / Azure or whatever can use a bash script or application he develops that scrapes the apis of the provider and based on this adds for example the tags of the instance as label to this agent via a ReST API.

Sorry for this short message, I think this already explains the "idea".

**Comment by Selutario** [comment]
Hi @DaspawnW!

If I have not misunderstood you, what you ask is already possible to do. For this you can make use of [agents grouping](https://documentation.wazuh.com/current/user-manual/agents/grouping-agents.html) and [centralized configuration](https://documentation.wazuh.com/current/user-manual/reference/centralized-configuration.html), which supports the use of labels. The steps are the following: 

### 1. Create the group
First, you will have to create a group to which the agents will belong. You can update the configuration of all the agents that belong to a group at the same time. After obtaining an API token as explained in [Getting started](https://documentation.wazuh.com/current/user-manual/api/getting-started.html), you can use the [POST /grupos](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.post_group) endpoint to create the group as shown below. 

> curl -k -X POST "https://localhost:55000/groups?pretty=true" -H  "Authorization: Bearer $TOKEN" -H  "Content-Type: application/json" -d "{\"group_id\":\"aws_agents\"}"

```JSON
{
   "message": "Group 'aws_agents' created.",
   "error": 0
}
```

### 2. Assign agent(s) to group
Then, you can make use of [PUT /group](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.put_multiple_agent_single_group) in order to assign agents to the group created before:

> curl -k -X PUT "https://localhost:55000/agents/group?agents_list=001&group_id=aws_agents" -H  "Authorization: Bearer $TOKEN"
```JSON
{
   "data": {
      "affected_items": ["001"],
      "total_affected_items": 1,
      "total_failed_items": 0,
      "failed_items": [],
   },
   "message": "All selected agents were assigned to aws_agents",
   "error": 0,
}
```

### 3. Update the configuration of the group
Finally, you will have to update the group's configuration to add the desired tags, so that the agent(s) belonging to that group will obtain such tags. You can use [PUT /groups/{group_id}/configuration](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.put_group_config). 

In the example below I add these labels to agent 001, which belongs to group `aws_agents`:
```XML
<labels>
  <label key="aws.instance-id">i-052a1838c</label>
  <label key="aws.sec-group">sg-1103</label>
  <label key="network.ip">172.17.0.0</label>
  <label key="network.mac">02:42:ac:11:00:02</label>
  <label key="installation" hidden="yes">January 1st, 2017</label>
</labels>
```

> curl -k -X PUT "https://localhost:55000/groups/aws_agents/configuration?pretty=true" -H  "Authorization: Bearer $TOKEN" -H  "Content-Type: application/xml" -d "<agent_config><labels><label key=\"aws.instance-id\">i-052a1838c</label><label key=\"aws.sec-group\">sg-1103</label><label key=\"network.ip\">172.17.0.0</label><label key=\"network.mac\">02:42:ac:11:00:02</label><label key=\"installation\" hidden=\"yes\">January 1st, 2017</label></labels></agent_config>"
```JSON
{
   "message": "Agent configuration was successfully updated",
   "error": 0
}
```

In case you need to add different tags to each agent (as expected), you will need to create a unique group for each agent. 

If you have any questions, let me know. 

Regards,
Selu.

**Comment by Selutario** [comment]
I'm closing this issue as it seems that there are no more questions. Feel free to open new issues if you have other questions or to join our [Slack channel](https://wazuh.com/community/join-us-on-slack/) or our [mailing list](https://groups.google.com/g/wazuh). 

Regards!
