### ISSUE TITLE
Error when opening Rootcheck files on Windows

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#8309]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0 | Rootcheck | Agent | All | Windows Server 2019 |

### Description

This is a bug reported by the @wazuh/qa team in the unstable version 4.2.

Sometimes, when the Windows agent is installed and started for the first time, its first Rootcheck scan is not able to find the benchmarks located at `$INSTALLDIR\ossec-agent\shared`, showing the following errors:

![image](https://user-images.githubusercontent.com/29475387/115577130-0cf70a00-a2bc-11eb-827e-a97af21da182.png)

The steps to reproduce it are:

- Install Wazuh 4.2.0 in a Windows Server 2019
- Connect it to a manager
- Wait until the first Rootcheck scan

**Comment by alromeros** [comment]
**#8309 update:**

Hello team,

After a thorough investigation, we have come to the following conclusions regarding the error described in this issue:

- Said error is happening due to a race condition present in **Windows** agents. This race condition occurs when the `fopen()` function in `run_rk_check.c` attempts to open a file that has been previously deleted by `cldir_ex_ignore()`. These deleted files are supposed to be restored before any opening attempt.

```c
// cldir_ex_ignore() is called in receiver-win.c, which attempts to erase all the content inside ossec-agent\shared
int cldir_ex_ignore(const char * name, const char ** ignore) {    
        ...
        // Erase content    
        ...
        if (rmdir_ex(path) < 0) {
            closedir(dir);
            return -1;
        }
        ...
````

```c
// In run_rk_check.c, fopen() attempts to open the file after it's been deleted
            ...
            fp = fopen(rootcheck.winmalware, "r");
            if (!fp) {
                mterror(ARGV0, "No winmalware file: '%s'", rootcheck.winmalware);
            }
            ...
````

This can be verified by looking at this next log, which has been obtained with a modified version of the code with additional warning messages:


![timestamp](https://user-images.githubusercontent.com/52510206/115902374-ab24d480-a462-11eb-9947-d8761b676be9.PNG)



- As this [commit](https://github.com/wazuh/wazuh/commit/e813188601d4089f495086ac66a75717cde4347e) shows, this behavior has been present in **Wazuh** since **v3.0.0**. However, it has not been replicated until **v4.2.0** due to the randomness and rarity of the race condition.

- None of the changes introduced in **v4.2.0** contribute directly to the occurrence of this error: It's just a matter of extremely precise timing. 

With this in mind, I suggest closing this issue and discard it as _stopper_ for **v4.2**, as none of the commits planned for this release contribute directly to this error.

Best regards,
Álvaro Romero.

**Comment by chemamartinez** [comment]
Found an error that may be related to this one during the Windows installation test in a pull request:
``` 
================================== FAILURES ===================================
____________________________ test_check_log_errors ____________________________
install_agent_test.py:64: in test_check_log_errors
    assert expected_error == True, assert_description['error']['exception_not_detected'] + " in line {}".format(line)
E   AssertionError: An error was found in the log in line 2022/09/29 10:05:11 rootcheck: ERROR: (1252): Invalid rk configuration value: 'OSTS -> r'.
E     
E   assert False == True
E     -False
E     +True
```
