### ISSUE TITLE
Error in Analysisd when producing a FIM alert

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#8312]
|Wazuh version|Component|Install type|Platform|
|---|---|---|---|
| 4.1.x | Analysisd | Manager | Linux |

We're seeing this error in Analysisd when printing a JSON alert:

```
ossec-analysisd: ERROR: The new permissions could not be added to the JSON alert.
```

It must come from this code line: https://github.com/wazuh/wazuh/blob/ecc19c3a5735509370c96b1b818c0c5d67658cd0/src/analysisd/format/to_json.c#L269.

**Comment by Molter73** [comment]
I've been investigating this issue and have not been able to reproduce the error yet.

However, while looking around the code I found the following potential problems:
- In `copy_ace_info`, when copying the ACE information into an auxiliar buffer to be used on return if a large number of ACEs are present in a file or registry a call to `snprintf` could truncate the output leaving an invalid string. In the following code block `written` is always 0 and `perm_size` is potentially an integer larger than 1 but not large enough to hold the formatted string, (the buffers used are around 6KB in size so this condition is unlikely but not impossible).
https://github.com/wazuh/wazuh/blob/d6119bb49306ea1dea3231ee1817be9a2e50f68b/src/shared/syscheck_op.c#L894-L896
- The output of the functions that call `copy_ace_info` is then forwarded to `decode_win_permissions` which again attempts to use `snprintf` on a buffer that could potentially not be large enough to hold the output, resulting in an invalid string being forwarded to the manager (again, unlikely due to the size of the buffer being used, but not impossible).
https://github.com/wazuh/wazuh/blob/d6119bb49306ea1dea3231ee1817be9a2e50f68b/src/shared/syscheck_op.c#L1235

I believe this last condition is the one that is causing the error on the manager. We should consider refactoring the way in which we collect and forward windows permissions. We are already sending a JSON object as the message, instead of the current formatted string we could send the JSON as it would be translated by the manager to be printed in an alert. If we consider that information would be too large to be forwarded over a network, we could send a simplified array of objects holding the username/sid, as well as allowed and denied fields with the mask of each as an integer.

**Comment by Molter73** [comment]
I managed to reproduce the error by using a small powershell script that adds multiple local users and ACEs to a specific file for each of them:

```ps1
$acl = Get-Acl C:\testdir\test

For ($i=0; $i -lt 320; $i++) {
    $user = "test-$($i)"
    New-LocalUser -name $user -NoPassword | Out-Null

    $AccessRule = New-Object System.Security.AccessControl.FileSystemAccessRule($user,"FullControl","Allow")

    $acl.SetAccessRule($AccessRule)
}

$acl | Set-Acl C:\testdir\test

```

As I explained on my previous comment, both `copy_ace_info` and `decode_win_permissions` have buffers with a static size that could potentially not be large enough to hold the ACEs of a file.

By leveraging the newly added `version` field on FIM messages, we should change how we handle this data and have it sent on the JSON message in the same format the manager currently outputs to `alerts.json`, but we should be aware that doing this would mean either:
- Changing how we print alerts on the legacy format `alerts.log`, effectively breaking compatibility with older agents.
- Writing a function that translates the new JSON field received to the legacy format.

I believe the second option would be the ideal, since it will allow us to move forward using a cJSON container and fixing the possible buffer overruns, while also keeping compatibility with older versions of the agent.

**Comment by Molter73** [comment]
Thanks to the contribution of a user we have been able to narrow down this error to a more mundane problem.

It looks like the agent is sometimes sending ACL entries belonging to registry keys that look as follows: `[...]read_ea|write_ea, Your Internet connection (denied):, [...]`

The given entry won't be considered as a valid one by the manager due to it being empty.

I haven't been able to reproduce the error yet, but looks like there might be related to some type of permission specific to the registry keys that is not being considered in `decode_win_permissions`

**Comment by Molter73** [comment]
I've managed to reproduce the error with the following python script (requires a local user named `test` and key located at `HKEY_LOCAL_MACHINE\Software\test`):

```python
import win32api
import win32con
import win32security

k = win32api.RegOpenKeyEx(win32con.HKEY_LOCAL_MACHINE, 'software\\test',
                          0, win32con.KEY_ALL_ACCESS | win32con.KEY_WOW64_64KEY)
s = win32api.RegGetKeySecurity(k, win32con.DACL_SECURITY_INFORMATION)
acl = s.GetSecurityDescriptorDacl()
user = win32security.LookupAccountName(None, 'test')
acl.AddAccessAllowedAce(0, user[0])
s.SetDacl(True, acl, False)
win32api.RegSetKeySecurity(k, win32con.DACL_SECURITY_INFORMATION, s)
```

It looks like regedit does not allow an empty ACE to be set on a registry key, but nothing stops a user program from doing this.

I will try to fix this problem as well as fixing the logic on the buffers that could overflow. I will also open a separate issue to send the Windows permissions in JSON format as discussed in a previous comment.
