### ISSUE TITLE
Migration of cve.db database to be managed by Wazuh DB - Analysis

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#8316]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/8315 in which we have the main goal of migrating the `cve.db` database to be managed by Wazuh DB, we should perform an analysis to define the next bullets:

- Design of the changes to be implemented.
- Definition of the components that should be modified.
- Define the new API endpoints that will be created.
- Define the information that will be displayed in the Wazuh UI.
- Design a testing plan to validate the changes.

This issue will be closed with a clear definition of all the listed bullets.

**Comment by palaciosjeremias** [comment]
As part of this investigation, we analyzed the proposal of using the **cve** DB in Wazuh DB handled by transactions.
In this approach, WDB has a command receives a command for each of the following actions:
- **prepare**
- **bind_text**
- **bind_int**
- **step**
- **column_text**
- **column_int**
- **finalize**
Each of this actions will be requested by one independent command and will generate that Wazuh-DB executes a corresponding SQL command on the DB, the response of each SQL command will be returned as the command response.

To test this approach a PoC was created, and different commands SQL queries where tested:
![image](https://user-images.githubusercontent.com/11434230/115744705-3326b380-a369-11eb-8b01-0a2fa960318f.png)

![image](https://user-images.githubusercontent.com/11434230/115744550-0bcfe680-a369-11eb-8306-2da106e69bfa.png)

![image](https://user-images.githubusercontent.com/11434230/115744636-21451080-a369-11eb-992d-2c5de7622726.png)

![image](https://user-images.githubusercontent.com/11434230/115745321-b34d1900-a369-11eb-8638-552d612981a2.png)

The PoC confirmed that the same queries that Vulnerability Detector is now lunching independently can be executed by WazuhDB. This will allow to centralize the handling of the Databases as expected and lets the API query WDB to obtain the information of CVE.
On the other hand, this approach doesn´t use statement cache optimization and only allows one transaction at a time. But Vulnerability Detector has these two same limitations too.

**Comment by DProvinciani** [comment]
Continuing with the analysis, we evaluated the possibility of avoiding the migration of the `cve.db` to Wazuh DB. In this approach both, Vulnerability Detector and the RESTfull API would directly access the database file with the next purposes:

- Vulnerability detector:
    - Write access to update the vulnerabilities information.
    - Write access during the scans.
    - Read access during the scans.
- RESTfull API:
    - Read access to query vulnerabilities information.

**Test case 1:** Select operations during a transaction with 10 insert operations and commit.

- Result: In this test case we observed that the reader can successfully read the data, in the status that was before opening the sql write transaction, and until committing. After committing the transaction the reader will see the data inserted into the database.

**Test case 2:** Select operations during a transaction with a big number of insert operations and commit.

- Result: In this test case we observed that the reader cant continue reading the database when, even before committing, the number of insert operations in the transaction is big. After committing the transaction, the database is unlocked and the reader can read the database again.

**Test case 3:** Select operations during a transaction with 10 insert operations and rollback.

- Result: In this test case we observed that the reader can successfully read the data, in the status that was before opening the sql write transaction, and until rolling back. After rolling back the transaction, the reader will see the data inserted into the database as it was originally. In summary, the reader will never see any change.

**Test case 4:** Select operations during a transaction with a big number of insert operations and rollback.

- Result: In this test case we observed that the reader cant continue reading the database when, even before rolling back, the number of insert operations in the transaction is big. After rolling back the transaction, the database is unlocked and the reader can read the database again.

**Comment by palaciosjeremias** [comment]
Continuing with the analysis, we evaluated the possibility of avoiding the migration of the `cve.db` to Wazuh DB. In this approach both, Vulnerability Detector and the RESTfull API would directly access the database file with the next purposes:

- Vulnerability detector:
    - Write access to update the vulnerabilities information.
    - Write access during the scans.
    - Read access during the scans.
- RESTfull API:
    - Read access to query vulnerabilities information.

**Test case 1:** Open two transactions with BEGIN TRANSACTION command in parallel. 
  Open a transaction with BEGIN TRANSACTION, prepare a statement, bind parameters, open a second transaction, execute STEP on the first statement.

- Result: In this test case we observed that the second opening of a transaction can lead to errors with the already prepared statements. The already bound values of the statement can be truncated or nullified.

**Test case 2:** Try to write on the DataBase when there is another transaction already opened.
  Open a transaction with BEGIN TRANSACTION, try to execute a write operation on a different thread.

- Result: In this test case we observed that the second thread that tries to write on the DataBase fails with the message **DataBase is locked**

**Test case 3-a:** Try to read on the DataBase when there is another transaction already opened.
  Open a transaction with BEGIN TRANSACTION, execute a write operation, try to execute a read operation on a different thread.

- Result: In this test case we observed that the second thread that tries to read on the DataBase successfully read the information.

**Test case 3-b:** Try to write on the DataBase when there is another transaction already opened actively writing.
  Open a transaction with BEGIN TRANSACTION,  execute several write operations, try to execute a read operation on a different thread.

- Result: In this test case we observed that the second thread that tries to read on the DataBase fails with the message **DataBase is locked** when the first thread writes a big amount of data with the same transaction. Approximately, the second thread starts failing to read from the DataBase after 20000 write operations of 20 bytes each.
  Note: This error is bypassed if the writing thread closes and reopens the transaction when reaching the 20000 write operations.

**Test case 4:** Check when a JOIN operation delays to execute.
  Prepare a JOIN operation, execute a first STEP operation, execute consecutive STEP operations.
  Scenario: Join AGENTS table with 2k rows with VULNERABILITIES table with 20k rows from **cve.db**

- Result: In this test case we observed that the first STEP operation lasts 10 seconds to execute and obtain the first set of data, the consecutive STEP operation executed immediately, obtaining the next set of data without any delay.
This concludes that the JOIN operation is performed during the first STEP of the statement, consecutive STEPS only retrieves the already joined data.

**Comment by MiguelazoDS** [comment]
Continuing with the analysis, we evaluated the possibility of avoiding the migration of the `cve.db` to Wazuh DB. In this approach both, Vulnerability Detector and the RESTfull API would directly access the database file with the next purposes:

- Vulnerability detector:
    - Write access to update the vulnerabilities information.
    - Write access during the scans.
	- Read access during the scans.
- RESTfull API:
    - Read access to query vulnerabilities information.

**test case 1:** Reading information during a transaction that performs a delete before commiting the changes.

![1- Reading during a delete transaction](https://user-images.githubusercontent.com/13010397/116404775-5936d280-a805-11eb-9192-1f1e7b4dc64b.png)

- Result: The reader is not able to perform any operation in the database, it remains locked until the transaction ends (COMMIT or ROLLBACK).

![2- Rollback-commit unlock db](https://user-images.githubusercontent.com/13010397/116404868-7075c000-a805-11eb-9c84-7adf880193d6.png)

**test case 2a:** Starting a transaction during a select query. Simulated doing a long select query that last a couple of seconds.

![3- Starting transaction during long read](https://user-images.githubusercontent.com/13010397/116404886-74a1dd80-a805-11eb-9b8c-a3233bbeaaf2.png)

- Result: The transaction starts, it can performs the insert in the database, but it not able to commit those changes since the database is locked by the reader.

**test case 2b:** Commit during a select query. The transaction begins, it performs the insert operation, and before the commit a long select query occurs.

- Result: The result is the same as before, the transaction is not able to perform the commit until the select query ends.

**test case 3:** As a general case. Transaction begins and performs an insert operation, before the transactions ends a select query occurs. The query is canceled and started again.

![4- double lock](https://user-images.githubusercontent.com/13010397/116404907-78cdfb00-a805-11eb-88ed-c8769fdba31e.png)

- Result: The database is locked first by the reader, as the previous test, the transaction is not able to finish the operation. After the select query is canceled and re-started the database is locked by the writer (transaction in course). To unlock the database the transaction do COMMIT or ROLLBACK.

**Comment by pereyra-m** [comment]
### Multiple readers - one writer test

If it were possible to avoid the `cve.db` migration to Wazuh-DB, it should be possible to have many threads reading the database at the same time the vulnerability detector module is writing on it.

This is the script used for testing (change its extension to `.c` for using). The `sqlite3.c` and `sqlite3.h` files are required:
[sqlite3_test.log](https://github.com/wazuh/wazuh/files/6391914/sqlite3_test.log)

#### Test 1: two tables on the same DB

For this test, set the **TEST_MODE** flag to `0`.
The program will create a DB with two tables, and many **THREADS** to read the **ROWS** from first table, all of them at the same time. In the meantime, the script writes and reads data to the second table.

All the successful reads and any error are printed to the `output.log` file. This log is also printed to the terminal if it contains any error. Here are some example logs, indicating that the database does not allow this concurrent access:

```
...
**ERROR: STMT Insert Step. Result (5): database is locked
**ERROR from 10: Select Prepare. Result (5): database is locked
**ERROR: STMT Insert Step. Result (5): database is locked
**ERROR from 10: Select Step. Result (21): database is locked
**ERROR: STMT Insert Step. Result (5): database is locked
...
```

#### Test 2: two databases, one of them attached 

To overcome this limitation, the `sqlite3` **ATTACH** command is tested.
Setting the **TEST_MODE** flag to 1, all the reading threads open the first DB and the writing thread works on the second one while the first one is attached.

The command is confirmed to work, because the writing thread opens a connection to one database but is able to read the information from the other one. No errors were found in the log.

**Comment by DProvinciani** [comment]
After analyzing the possibility of having concurrent access to the `cve.db` database by the Vulnerability Detector module and the RESTfull API, and based on the tests described above, we concluded that the design would be inappropriate and would cause multiples issues.

As an alternative, we decided to implement a mechanism to have two databases:

- `cve.db`: This database will continue being the database used by Vulnerability Detector to perform the scans, and will be the only one that will make use of it.
- `vulnerabilities.db`: This database will be hosted and managed by Wazuh DB. It will be a database used only for the purposes of query CVEs information through the RESTfull API. The information in this database will be inserted right after finalizing the vulnerabilities feeds update by Vulnerability Detector.

Although this approach causes an increase in the usage of disk space, it avoids any issue caused because of the concurrent access. No one will need to wait to access the information.

The epic was divided into the next set of tasks:

1. `vulnerabilities.db` database design.
2. Creation and management of the database by Wazuh DB.
3. Creation of a Wazuh DB command to insert or update information from the database.
4. Synchronization of the database after the feeds update performed by Vulnerability Detector.
5. Creation of a new API endpoint to query the information.
6. Modification of the Wazuh UI to expose vulnerabilities information.
7. Update the Wazuh documentation.
8. Desing and implementation of new integration tests.
9. Coverity and scan-build analysis.
10. Exploratory testing.

Having a final decision of the design to implement, and the list of tasks, we close this issue.
