### ISSUE TITLE
Remove agent files in workers when it is deleted in client.keys

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#8327]
|Wazuh version|Component|Install type|Install method|
|---|---|---|---|
| master | modulesd | Manager | Packages/Sources |

## Description

Hi team! 

In a cluster environment, the way in which files from an agent are deleted when it is unregistered (rids, agent-groups, db, etc) is different depending on whether it happens in the master node or in the workers. 

### Master node
If authd service is running, it is in charge of deleting all the agent related files.

### Worker nodes
As authd is not used in worker nodes, the steps are as follows: 
1. Master node unregisters the agent and it is removed from the `client.keys` file.
2. Worker node receives a new updated `client.keys` file.
3. Before replacing the old `client.keys`, both old and new are compared to get which agents have been removed.
4. Worker node iterates over the list of paths below for each removed agent, and each file is deleted:
https://github.com/wazuh/wazuh/blob/ecc19c3a5735509370c96b1b818c0c5d67658cd0/framework/wazuh/core/cluster/worker.py#L758-L762
5. A query is sent to wazuh-db to remove the agents from the `belongs` table. 
https://github.com/wazuh/wazuh/blob/ecc19c3a5735509370c96b1b818c0c5d67658cd0/framework/wazuh/core/cluster/worker.py#L768-L771

## Inconsistent behavior 
In my tests, although the cluster tries to delete the files mentioned before, there are some of them that are already deleted by other service. 

For instance, these are the files in `worker1` for the agent `002`, before it is deleted:
```
/var/ossec/queue/agent-groups/002
/var/ossec/queue/diff/3ecc9709f601
/var/ossec/queue/rids/002
/var/ossec/var/db/agents/002-3ecc9709f601.db
```

Then, I changed the code in the worker so that it does not remove any of those files. However, after the `client.keys` is updated, this is the result:
```
/var/ossec/queue/agent-groups/002
/var/ossec/queue/diff/3ecc9709f601
/var/ossec/queue/rids/002
```

As we can see, something has deleted `/var/ossec/var/db/agents/002-3ecc9709f601.db`, but not the other files. On top of that, wazuh-modulesd takes care of inserting agents into the `agent` table of `global.db` when they are added to the `client.keys`, and deleting them from the same place when the `client.keys` file changes. However, it doesn't delete them from the table `belongs`, leaving that work to the cluster for no apparent reason. 

## Proposal
We believe that the worker's `wazuh-clusterd` process should not be in charge of checking which agents have been removed and searching for related files. 

In the same way that some service is deleting the files in `/var/ossec/var/db/agents/`, and modulesd is inserting and deleting the agents from the agents table, we think that it should take care of deleting all the agent related files and updating all the necessary tables. 

Therefore, the cluster process would only consist on keeping the common files (rules, decoders, client.keys, etc) synchronized, but it would not have to parse and check the `client.keys`, which is a duplicated task since modulesd is doing it too. This could also help reduce the busyness of the cluster process. 

Regards,
Selu.

**Comment by Molter73** [comment]
I've been doing some research on this and here is what I have found this far:
- The module responsible for deleting the DBs found on `var/db` is `wm_database`. This module is also removing the agent from the `belongs` table (or at least it's issuing the query).
- We need to double check whether deletion of the `queue/db` agent database is necessary, since it looks like those DBs are currently deleted by `authd`
- We will need to implement a way for this module to safely delete the files listed in the issue. Unlinking files on Linux systems stops processes from accessing the file but file descriptors already open are kept and the OS is prevented from cleaning the file until no fds are left open for the file. As it stands now:
  - The diff files kept at `queue/diff/{agent-name}` are open only when needed, it could be directly removed. However if an event for the given agent is processed after deleting the file an alert could be triggered with wrong information, which means we need to at least ensure `remoted` reloads the keys before deleting it.
  - The files held at `queue/rootcheck` were moved into `wazuh_db` in v4.1. Might be necessary to either purge the DB or directly remove the agent DB.
  - The files under `queue/agent-groups` are already being cleaned up by the `database` module on startup, looks like we could easily delete it.
  - Similarly to the `queue/diff` files, `queue/rids` are used by remoted, we need to ensure it won't try to reopen the file after we delete it by ensuring it reloads the agent keys.

**Comment by Molter73** [comment]
I've create branch [8605-delete-agent-files](https://github.com/wazuh/wazuh/tree/8605-delete-agent-files) to be used as the base branch for both Core and Framework teams. We will merge all changes needed onto that branch in order to create a PR closing this issue.

**Comment by antoniomanuelfr** [comment]
I created the branch https://github.com/wazuh/wazuh-qa/tree/8605-delete-agent-files in the QA repository to merge all the needed changes in the integration/system tests.

**Comment by snaow** [comment]
System tests merged: https://github.com/wazuh/wazuh-qa/pull/1527
