### ISSUE TITLE
Wazuh 4.1.5 API rule load crashes if the match string in a <field> line ends with a double backslash

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#8387]
|Wazuh version|Component|
|---|---|
| 4.1.4/4.1.5 API | listing rules |

Rules I have been using for some time started causing Wazuh API rule load failures when I upgraded from 4.0.4 to 4.1.X.  I have encountered this on multiple Wazuh managers in the 4.1.4-4.1.5 range.

A rule like this looking for a currentDirectory field ending with `xyz\` would need to have the backslash escaped as `xyz\\` to be parsed correctly.  When it is, Wazuh will parse it just fine when the manager restarts and when running ossec-logtest.  In Wazuh 4.0.4, it also will be handled fine by the Wazuh API for either direct API calls or via browsing the rules via the Wazuh web UI.  However, with Wazuh 4.1.4 and later I find the following rule causes the Wazuh web interface to report 0 rules loaded and direct Wazuh API calls to list rules throw an internal error.

```
<rule id="100020" level="0">
    <if_sid>60000</if_sid>
    <field name="win.eventdata.currentDirectory">xyz\\</field>
    <description>test rule</description>
</rule>
```

The double backslash at the end of the field match string in the above rule literally crashes Wazuh API's loading of the ruleset, throwing this in api.log:

```
2021/04/26 18:30:09 ERROR: Error executing API request locally: mismatched tag: line 11, column 4
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.5-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 250, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.5-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 224, in run_local
    data = self.f(**self.f_kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.5-py3.9.egg/wazuh/rule.py", line 71, in get_rules
    rules.extend(load_rules_from_file(rule_file['filename'], rule_file['relative_dirname'], rule_file['status']))
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.5-py3.9.egg/wazuh/core/rule.py", line 70, in load_rules_from_file
    root = load_wazuh_xml(os.path.join(common.ossec_path, rule_relative_path, rule_filename))
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.5-py3.9.egg/wazuh/core/utils.py", line 740, in load_wazuh_xml
    return fromstring(entities + '<root_tag>' + data + '</root_tag>')
  File "/var/ossec/framework/python/lib/python3.9/xml/etree/ElementTree.py", line 1347, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 11, column 4
2021/04/26 18:30:09 INFO: wazuh-wui 127.0.0.1 "GET /rules" with parameters {"offset": "0", "limit": "15"} and body {} done in 1.062s: 500
```

**Comment by AdriiiPRodri** [comment]
Hi @branchnetconsulting,

Thank you so much for your report. As you say, currently, in version `4.1.x` of Wazuh there is a bug when the path ends with the character `\`. It is possible that this bug was introduced in this commit: https://github.com/wazuh/wazuh/commit/654aa15fa6d64c1378810bbd44c712f5c5f4b3f9. 

In this commit, some improvements were introduced for another endpoint, however, it seems that these improvements do not work as well as they should for the rules. In addition, it is possible that this error occurs in more endpoints, such as decoders.

Again, thank you very much for your contribution, we will prioritize this issue to fix this bug as soon as possible and check that all endpoints using `load_wazuh_xml` are working correctly.

https://github.com/wazuh/wazuh/blob/e733d239fad6f88fe188c00006d171d3b1d35ca6/framework/wazuh/core/utils.py#L716

Best regards,
Adrián Peña
