### ISSUE TITLE
Create an AND condition between two rules

### ISSUE THREAD

**Issue by maknuspl** [wazuh/wazuh#8403]
Feature request:

I want to use rules: 553 **and** 554.
I want to detect simultaneous repetitions of these events within a certain time.  
Something like that

`<rule id="1000000" level="15" timeframe="10" frequency="5">`
	`<if_sid>553 & 554</if_sid>`
	`<description>Ransomwaere Attack</description>`
`</rule>`

**Comment by alromeros** [comment]
Hello @maknuspl!

Thank you for opening this feature request issue, it is very much appreciated.

First of all, I'd like to know better about your goal with this custom rule, so we can study a possible workaround to address your needs temporarily: Would you like to check when certain files are deleted and created inside a directory? Is there anything in particular that you may want to check with this rule?

Regarding the custom rule you've shared, there are several things to take into account in order to write similar, functional rules:
- While using the `timeframe` and `frequency` options, it's obligatory to use the `if_matched_sid` label, instead of `if_sid`. Their usage is almost identical, with the only difference that `if_matched_sid` enables the use of additional options (like `timeframe` and `frequency`). Thi is fully explained in our [documentation]( https://documentation.wazuh.com/4.0/user-manual/ruleset/ruleset-xml-syntax/rules.html#if-matched-sid).

- Your `timeframe` and `frequency` values would make it incredibly hard to trigger said rule, as the described condition would have to occur 5 times in just the 10 seconds that are specified in `timeframe`.

Lastly, regarding the addition of conditional operators to our ruleset: We understand that our rule system lacks some functionalities that could significantly enhance the user's experience, and we are planning to improve such features in the future. That being said, our team will gladly consider adding your request to future roadmaps.

I hope this helps! I'll be looking towards your answer in order to keep helping you.

Best regards,
Álvaro Romero

**Comment by maknuspl** [comment]
Hello @alromeros

Thank you very much for your reply and for taking this issue :)

I used this `timeframe` and ` frequency` because I want to detect ransomware. The ransomware adds a new encrypted file to the directory and deletes the original file. According to my tests, it can perform such operations even several times per second.

I think, ransomware is the most dangerous cyber attack right now. I want to create a honeypot folder and detect simultaneous additions and deletions of files on it in a short time to rule out a false positive.

Best regards,
MaknusPL

**Comment by alromeros** [comment]
Hi again, @maknuspl

Thank you for clarifying your goal with the custom rule, and sorry for the late response!

Regarding the detection of ransomware attacks, you can check [this](https://wazuh.com/blog/preventing-and-detecting-ransomware-with-wazuh/) post on our website, where we delve into **Wazuh**'s best practices to prevent and detect such attacks. 

As you've probably guessed, both rule **553** and rule **554** play a crucial role while trying to detect **ransomware** attacks, but as the post specifies, it's currently on the user's hand to manually check the alerts to discard false positives. That being said, It shouldn't be a major problem to rely on the two rules separately when scanning a single **honey pot** with [File Integrity Monitoring](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/index.html), while following the post's advice to successfully detect ransomware attacks.

As I said, this feature request will be gladly considered by our team, which is working hard to improve all of **Wazuh**'s functionalities, ruleset included. One last thing! If you still want more assistance with **Wazuh**, I recommend you to join our [slack community](https://wazuh.com/community/join-us-on-slack/), where you can share your questions and issues with both users and members of **Wazuh**, who will gladly assist you. 

Best regards,
Álvaro Romero

**Comment by maknuspl** [comment]
Hi again, @alromeros :)

I know this blog article. Your blog is very helpful as well as the community on Slack.

I think manual detection can be difficult in my case. I use Wazuh to monitor 10,000 endpoints. Additionally, the response of manual discovery may be too slow to protect the data. I want to run auto incident response when the behavior indicates ransomware (adding and removing files very quickly). The best way seems to me to combine rules 553 and rule 554 into one event. Then I can add an auto incident response script to such an event to, for example, cut off such a workstation from the network or even turn it off. This will give the administratorm time to react appropriately.

**Comment by alromeros** [comment]
Hi again, @maknuspl!

After reading your case, I've been testing with custom rules again and I've ended up finding a solution that would probably fit your needs: Despite what I told you, It is still possible to chain rules as you proposed combining the `if_group` and `if_matched_group` labels.

I'll use this next custom rule as an example:
```xml
<rule id="100002" level="12" timeframe="10">
    <if_group>syscheck_entry_added</if_group>
    <if_matched_group>syscheck_entry_deleted</if_matched_group>
    <description>Ransomware attack</description>
</rule>
````
With a directory in `ossec.conf` configured as:
```xml
 <syscheck>
    <disabled>no</disabled>
    ...
    <directories whodata="yes" real_time="yes">/etc/test</directories>
    ...
````


**Where**:

- The `<if_group>` label contains the group that will finally trigger the rule. In this case, it's **syscheck_entry_added** from rule **554**.
- The `<if_matched_group>` contains the group that serves as a prerequisite for the custom rule to be triggered: In this case, **syscheck_entry_deleted** from rule **553**.
- The `timeframe` value is set so each time a file is deleted in **/etc/test**, creating another file in a timelapse of 10 seconds will trigger this custom rule.

As I said, though it's not possible to concatenate rules using conditional operators as **AND** or **OR**, it's completely possible to reach the same goal with these labels, and you can even customize more the rule's behavior by adding extra labels. You can find the full list [here](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#overview). 

I'm sorry for the inconveniences or misinformation that my previous messages could have caused, as I've just recently learned about this behavior. I hope this helps and let me know if this solution solves your problem!

Best regards,
Álvaro Romero

**Comment by maknuspl** [comment]
@alromeros, thank you very much for your response. This is what I need. I will test it in my environment.

**Comment by maknuspl** [comment]
@alromeros 
Sorry for the delay - a lot of work. Your solution works perfectly. Thanks again, it opened up new monitoring possibilities for me.

**Comment by alromeros** [comment]
Hi @maknuspl, I'm glad you found my answer useful! I'll close this issue since the proposed workaround fulfills the requested behavior. Please, do not hesitate to contact us again for more help and assistance.
