### ISSUE TITLE
Run cluster performance pipeline and report errors

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#8439]
Hello team,

We shall run the new cluster performance pipeline and report any found errors.

We will start the investigation using a simple cluster with 1 worker and 1000 agents.

We should also analyze the API test results and possible errors in the logs.

Regards,

David J. Iglesias

We are fixing the API performance tests in QA branch [cluster-performance-pipeline-improvements](https://github.com/wazuh/wazuh-qa/tree/cluster-performance-pipeline-improvements)

**Comment by davidjiglesias** [comment]
After running the first pipeline we have detected a failure in the way the API integration tests were being run. The pytest command was using -x which caused the test to be interrupted after the first failure.

https://github.com/wazuh/wazuh-jenkins/blob/eede1ceedb81b061a8257082e212ef632a2c7111/dockers/util/api_performance/run_api_performance_test.sh#L21

Said error has been reported and it is to be fixed here: https://github.com/wazuh/wazuh-jenkins/pull/2525

**Comment by davidjiglesias** [comment]
### **2nd run test parameters:**

**Version:** 4.2.0
**Worker:** 1
**Agents:** 1000

**Comment by davidjiglesias** [comment]
## 3rd run
### Test parameters:

**Version:** 4.2.0
**Workers:** 1
**Agents:** 1000
**Test duration:** 600s

### API test results:

**Comment by davidjiglesias** [comment]
## 4th run
### Test parameters:

**Version:** 4.2.0
**Workers:** 1
**Agents:** 1000
**Test duration:** 600s

### API test results:
![image](https://user-images.githubusercontent.com/48716145/116685403-92607580-a9b2-11eb-9378-8c95859fa452.png)

### Findings:

### Fixes:

**Comment by davidjiglesias** [comment]
## 5th run
### Test parameters:

**Version:** 4.2.0
**Workers:** 1
**Agents:** 1000
**Test duration:** 600s

### API test results:

### Findings:

### Fixes:

**Comment by davidjiglesias** [comment]
## 6th run
### Test parameters:

**Version:** 4.2.0
**Workers:** 6
**Agents:** 30000
**Test duration:** 1200s

### API test results:

### Findings:

### Fixes:

**Comment by davidjiglesias** [comment]
## 7th run
### Test parameters:

**Version:** 4.2.0
**Workers:** 6
**Agents:** 30000
**Test duration:** 900s
**Build:** 183 

### API test results:

### Findings:

### Fixes:

**Comment by davidjiglesias** [comment]
## 8th run
### Test parameters:

**Version:** 4.2.0
**Workers:** 10
**Agents:** 50000
**Test duration:** 900s
**Build:** 185 

### API test results:

## Findings:
### Finding1

## Fixes:

**Comment by mcarmona99** [comment]
## 9th run
### Test parameters:
**Version:** 4.2.0
**Workers:** 10
**Agents:** 50000
**Test duration:** 900s
**Build:** 208
**Kibana API request:** ☑️ 

### API test results:
API tests weren't run this time.

### Findings:
Build in progress...

**Comment by Selutario** [comment]
## 10th run
### Test parameters:
**Version:** 4.2.0
**Workers:** 10
**Agents:** 50000
**Test duration:** 900s
**Build:** 227

☑️ **Kibana API request**  
🔲 **Extra load API request** 


### API test results:
API tests weren't run this time.

## Findings:
Build in progress...

**Comment by AdriiiPRodri** [comment]
## Description

Hi team,

As a result of the tests performed on the issue https://github.com/wazuh/wazuh/issues/8439, numerous improvements have been implemented on the Wazuh cluster side. In this issue, we will collect all the issues derived from this issue. Therefore, the objective of this issue is to obtain a general summary of the implemented improvements and a list of the derived issues and their status.

- [1st RUN]: Test are running with "-x" pytest flag -> [Fixed] https://github.com/wazuh/wazuh-jenkins/pull/2525

- [2nd RUN]: There are currently 7 failing API tests, these errors have been fixed in [Fixed] https://github.com/wazuh/wazuh-qa/commit/39467d2b480b33eda28b94190a731b0a84a0bd1c

- [3rd RUN]:
  - [Finding 1] Agent simulator version not being able to reply with agent configuration details (PUT /active-response) -> [Fixed] https://github.com/wazuh/wazuh-qa/commit/67b494d9f2f4d12b1c9f4351c602c0e9415255ae
  - [Finding 2] Check error value: [Fixed] https://github.com/wazuh/wazuh-qa/commit/81695dfeb894c016f3513da7d45c7c147fa060f2
  - [Finding 3] Increase the delay after some endpoints (restart, config, changes, etc) -> [Fixed] https://github.com/wazuh/wazuh-qa/commit/e4da3eb0a7d5dd8c6ae33068512fe3ef29f100d0
  - [Finding 4] Restart endpoints before creating new agents -> [Fixed] https://github.com/wazuh/wazuh-qa/commit/68716e187f90caf6ac13f73d0546f25ee4862675
  - [Finding 5] Agent 'X' not found in ossec.log -> [Reported] https://github.com/wazuh/wazuh/issues/8480
  - [Finding 6] Monitoring stop worker after restart the cluster/manager using the Wazuh API request -> [Fixed] https://github.com/wazuh/wazuh-qa/pull/1334

- [4th RUN]:
  - [Finding 1] Race condition between the API delete request and the cluster integrity calculation -> [Fixed] https://github.com/wazuh/wazuh/issues/8463
  - [Finding 2] Monitoring script is stopping after the Wazuh manager restarts (in any node). Acquire new PID -> [Fixed] https://github.com/wazuh/wazuh-qa/pull/1334

- [5th RUN]: Nothing

- [6th RUN]:
  - [Finding 1] API performance test was not properly showing the result when the status code is different to 200 -> [Fixed] https://github.com/wazuh/wazuh-qa/commit/bdab39b42e93159131073af3b10436f417ff8f20
  - [Finding 2] If the restart takes too long, the API can't process the response -> [Fixed] https://github.com/wazuh/wazuh-qa/pull/1334
  - [Finding 3] Worker node did not restart the wazuh-apid module after sending the cluster restart request -> [Reported] https://github.com/wazuh/wazuh/issues/8482
  - [Finding 4] Detected some errors in cluster.log -> [Fixed] https://github.com/wazuh/wazuh/pull/8142
  - [Finding 5] Probably error with wazuh-authd -> [Reported] https://github.com/wazuh/wazuh/issues/8498

- [7th RUN]:
  - [Finding 1] Wazuh master node take more time to restart than the defined timeout -> [Fixed] https://github.com/wazuh/wazuh-qa/commit/ae5d2fab6f542f4aff7b0711a97104f880e39165
  - [Finding 2] Discrepancy between agent-groups and client.keys after the deletion of agents -> [Fixed] https://github.com/wazuh/wazuh/issues/8497
  - [Finding 3] Error with agent_simulator and centralized configuration -> [Fixed] https://github.com/wazuh/wazuh-qa/issues/1284

- [8th RUN]:
  - [Finding 1] Workers nodes don't have the expected TCP connections (5000 for each worker node) -> [Fixed] https://github.com/wazuh/wazuh-qa/issues/1292
  - [Finding 2] Sudden drops in the number of TCP connections -> [Reopened - Reported] https://github.com/wazuh/wazuh-qa/issues/1294

- [9th RUN]:
  - [Finding 1] There are two missing active agents. This can be check-in cluster.log (There are 50000 unique keys in ossec.log) -> [Reported] https://github.com/wazuh/wazuh-qa/issues/1318
  - [Finding 2] Slow agent-group files creation -> [Reported] https://github.com/wazuh/wazuh/issues/8625
  - [Finding 3] Kibana API simulator getting a 401 code -> [Reported] https://github.com/wazuh/wazuh-qa/issues/1320

- [10th RUN]
  - [Finding 1] Agent connections drops -> [Reopened] https://github.com/wazuh/wazuh-qa/issues/1294#issuecomment-839700561
  - [Finding 2] Not all agents are being registered in Test_cluster_pipeline -> [Reported] https://github.com/wazuh/wazuh-qa/issues/1325
  - [Finding 3] Not all agents connected in Test_cluster_performance pipeline environment -> [Reported] https://github.com/wazuh/wazuh-qa/issues/1318
  - [Finding 4] Wrong behavior in the load balancer used in Test_cluster_performance -> [Reported] https://github.com/wazuh/wazuh-qa/issues/1323


## Conclusion

As a final result of the issue https://github.com/wazuh/wazuh/issues/8439, numerous improvements have been implemented. These range from improvements in the testing pipeline itself as well as improvements on the cluster side of Wazuh. However, there are still some improvements to be made:

### ToDo

- [ ] https://github.com/wazuh/wazuh/issues/8480
- [ ] https://github.com/wazuh/wazuh/issues/8482
- [ ] https://github.com/wazuh/wazuh/issues/8498
- [ ] https://github.com/wazuh/wazuh/issues/8625
- [ ] https://github.com/wazuh/wazuh-qa/issues/1294
- [ ] https://github.com/wazuh/wazuh-qa/issues/1318
- [ ] https://github.com/wazuh/wazuh-qa/issues/1320
- [ ] https://github.com/wazuh/wazuh-qa/issues/1323
- [ ] https://github.com/wazuh/wazuh-qa/issues/1325
