### ISSUE TITLE
Analysis of the cve.db database for the design of the database for the global CVEs searching

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#8453]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/8315 we should design and create a new database schema that will contain all the CVEs information that will be exposed to the users. Having said that, as part of this issue we should do the next set of tasks:

- Analyze and determine from each vulnerability feed, the information that could be useful for the users.
- Define the set of queries that should be performed to extract the information.
- Evaluate the possibilities of merge the data to be inserted in a single database table.

**Comment by DProvinciani** [comment]
### NVD data analysis

The NVD provides the CVEs information in a way in which a CVE will be effective if a set of software products is installed. That said, if we take as an example the [CVE-2010-0019](https://nvd.nist.gov/vuln/detail/CVE-2010-0019), it will affect an endpoint if one of the next conditions are satisfied:

1. The `microsoft silverlight` package version `3.0.40624`, OR version `3.0.40723`, OR any version up to (including) `3.0.40818` are installed and running on `Apple Mac OSX` of any version.
2. The `microsoft silverlight` package version `3.0.40624`, OR version `3.0.40723`, OR version `3.0.40818`, OR any version up to (including) `3.0.50106` are installed and running on `Microsoft Windows` of any version.

So we can conclude that a single CVE id, could affect multiples software products and in fact, different combinations of them. This introduces some complexity on the data normalization in order to save all the data in a single database table. Considering this, here is a set of queries that could be used to extract all the relevant information of a CVE and the needed tables from the `cve.db`:

- **Select 1**: Initially we should select the general information of the cve:

```sql
SELECT ID, NVD_METADATA_YEAR, CVE_ID, CWE_ID, ASSIGNER, DESCRIPTION, PUBLISHED, LAST_MODIFIED FROM NVD_CVE
```

- **Select 2**: Then we should know the combination of packages that make effective the CVE:

```sql
SELECT NVD_CVE_CONFIGURATION.ID, NVD_CVE_CONFIGURATION.PARENT, NVD_CVE_CONFIGURATION.OPERATOR FROM
NVD_CVE JOIN NVD_CVE_CONFIGURATION WHERE NVD_CVE.ID = NVD_CVE_CONFIGURATION.NVD_CVE_ID AND NVD_CVE.ID = SELECT1.ID
```

From this result, we should take into account the items that have a parent `0` (zero). And from this point, two situations could happen:

1. If the operator is `OR`, it means that there is not a combination of packages that make the CVE effective. So, we just need to look for all the packages versions that make effective this CVE.
2. If the operator is `AND`, it means that a combination of packages makes the CVE effective. So in this case we should look for the results that have as a parent, the current item. Finally, we should look for the versions of the packages that satisfy the `AND` condition.

The query to get this information related to the versions of the packages is:

```sql
SELECT URI, VERSION_START_INCLUDING, VERSION_START_EXCLUDING, VERSION_END_INCLUDING, VERSION_END_EXCLUDING FROM NVD_CVE_MATCH WHERE NVD_CVE_CONFIGURATION_ID = SELECT2.ID
```

- The final step is to complement the information with the vulnerability vectors and the references. This information should be taken from the `NVD_METRIC_CVSS` and `NVD_CVE` tables.

**NOTE:** The database tables required to obtain all the information mentioned above are `NVD_CVE`, `NVD_CVE_CONFIGURATION`, `NVD_CVE_MATCH`, `NVD_METRIC_CVSS`, and `NVD_REFERENCE`. All these database tables should be included in the new database that will be hosted and managed by Wazuh DB.

**Comment by MiguelazoDS** [comment]
### RedHat data analysis.

Before starting with the information that should be useful to get and the queries to do so, there are a few things that are worth mentioning.

#### Considerations
--------------------
Seeing that the `TARGET` field in the `VULNERABILITIES` table distinct between the different versions of the operating system but does not in the `VULNERABILITIES_INFO`, was necessary to verify if some entries could have been missing in the other table. And in fact, the table `VULNERABILITIES_INFO` contains older CVEs that are not present in the `VULNERABILITIES` table.

`sqlite3 cve.db 'select * from vulnerabilities where target like "RHEL%" order by cveid limit 10'`

![1](https://user-images.githubusercontent.com/13010397/116738956-816f2e80-a9c9-11eb-8964-aefbdfd38408.png)

*The older CVEs found are from 2002 for RHEL5/6/7/8**

`sqlite3 cve.db 'select * from vulnerabilities_info where target like "JREDHAT" order by id limit 10'`

![2](https://user-images.githubusercontent.com/13010397/116738971-859b4c00-a9c9-11eb-9535-ee244d2fa420.png)

*The older CVEs found are from 1999*

We can see that all CVEs in the `VULNERABILITIES` table have an entry in the `VULNERABILITIES_INFO` table with the following queries.

`sqlite3 cve.db 'select count(distinct(cveid)) from vulnerabilities where target like "RHEL%" order by cveid'`

`sqlite3 cve.db 'select count(distinct(cveid)) from vulnerabilities vu join vulnerabilities_info on cveid = id where vu.target like "RHEL%" order by cveid'`

![3](https://user-images.githubusercontent.com/13010397/116738989-892ed300-a9c9-11eb-8ce9-ac89c9ad4da9.png)

`sqlite3 cve.db 'select count(distinct(id)) from vulnerabilities_info where target like "JREDHAT" order by id'`

![4](https://user-images.githubusercontent.com/13010397/116739003-8cc25a00-a9c9-11eb-8bf3-a5aa32af41ad.png)

So it is important to say that this does not seem to affect the information we may need from the tables, but is needed to revise the reason for those extra CVEs (23145-13836) in the `VULNERABILITIES_INFO`, that also are available in the `BUGZILLA_REFERENCE_INFO` and `REFERENCE_INFO` tables.

![5](https://user-images.githubusercontent.com/13010397/116739015-8fbd4a80-a9c9-11eb-9ddd-d905ce713876.png)

#### Tables
----------------------------

##### VULNERABILITIES table description. 

```
0|CVEID|TEXT|1||1
1|TARGET|TEXT|1||2
2|TARGET_MINOR|TEXT|0||3
3|PACKAGE|TEXT|1||4
4|OPERATION|TEXT|1||0
5|OPERATION_VALUE|TEXT|0||5
6|CHECK_VARS|INTEGER|0|0|0
7|IGNORE|INTEGER|0|0|0
8|ARCH_ID|INTEGER|0|0|6
````

**Examples:**

```
CVE-2019-14287|RHEL5||sudo|less than|1.7.2p1-31.el5_11.1|0|0|1
CVE-2019-5489|RHEL5||kernel-xen-devel|less than|2.6.18-439.el5|0|0|2
CVE-2013-7488|RHEL8||perl-convert-asn1|less than|0:0|0|0|0
```

**Important fields**

According to the examples we consider that the fields that could be useful to get information from are the following. 

`cveid, target, package, operation, operation_value`

##### VULNERABILITIES_INFO table description.

```
0|ID|TEXT|1||1
1|TITLE|TEXT|0||0
2|SEVERITY|TEXT|0||0
3|PUBLISHED|TEXT|0||0
4|UPDATED|TEXT|0||0
5|TARGET|TEXT|1||2
6|RATIONALE|TEXT|0||0
7|CVSS|TEXT|0||0
8|CVSS_VECTOR|TEXT|0||0
9|CVSS3|TEXT|0||0
10|CVSS3_VECTOR|TEXT|0||0
11|CWE|TEXT|0||0
```

**Examples:**

```
CVE-2020-14860||low|2020-10-20T00:00:00Z||JREDHAT|mysql: Server: Security: Roles unspecified vulnerability (CPU Oct 2020)|||2.700000|CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:N/I:L/A:N|\
CVE-2001-0568||Unknown|2001-02-23T00:00:00Z||JREDHAT|security flaw|||||
```

**Important fields**

According to the examples we consider that the fields that could be useful to get information from are the following. 

`id, severity, published, target, rationale.`

#### Queries.

-----------

We need to perform queries that involve multiple tables if we want to get more detailed information.
Since in `VULNERABILITIES_INFO`, `BUGZILLA_REFERENCE_INFO` and `REFERENCE_INFO` we don't have information about the version of the operating system, it always mandatory to get that data from the `VULNERABILITIES_INFO` table if we need to get a specific version CVEs data.

- CVE id, severity, published, rationale all ordered by target. It can be ordered by others fields.

`sqlite3 cve.db 'select distinct(cveid), severity, published, rationale, vu.target from vulnerabilities vu join vulnerabilities_info vi on vu.cveid = vi.id where vu.target like "RHEL%" order by vu.target'`

- CVE id, severity, published, rationale per RedHat version.

`sqlite3 cve.db 'select distinct(cveid), severity, published, rationale from vulnerabilities vu join vulnerabilities_info vi on vu.cveid = vi.id where vu.target = "RHEL6"'`

- CVE id, packages, rationale.

`sqlite3 cve.db 'select cveid, package, rationale from vulnerabilities vu join vulnerabilities_info vi on vu.cveid = vi.id where vu.target like "RHEL%" and vi.target = "JREDHAT" order by cveid'`

- CVE id, severity, published, rationale, target. Ordered by published date.

`sqlite3 cve.db 'select distinct(cveid), severity, published, rationale from vulnerabilities vu join vulnerabilities_info vi on vu.cveid = vi.id where vu.target = "RHEL6" order by strftime(published) limit 10'`

- CVE id, severity, published, rationale, target. Between year 20xx and 20yy.

`sqlite3 cve.db 'select distinct(cveid), severity, strftime("%Y", published), rationale from vulnerabilities vu join vulnerabilities_info vi on vu.cveid = vi.id where vu.target = "RHEL6" and strftime("%Y", published) between "2010" and "2018" order by strftime(published)'`

- CVE id, target, reference. Ordered by target.

` sqlite3 cve.db 'select distinct(cveid), vu.target, reference from VULNERABILITIES vu join REFERENCES_INFO ri on vu.cveid = ri.id where vu.target like "RHEL%" and ri.target = "JREDHAT" order by vu.target'`

- CVE id, target, bugzilla_reference. Ordered by cve.

`sqlite3 cve.db 'select distinct(cveid), vu.target, bugzilla_reference from VULNERABILITIES vu join BUGZILLA_REFERENCES_INFO ri on vu.cveid = ri.id where vu.target like "RHEL%" and ri.target = "JREDHAT" order by cveid'`

**Comment by palaciosjeremias** [comment]
### Ubuntu analysis
Ubuntu vendor feed is pretty stright-forward to be resumed into a unique vulnerability table.
The main content of the feed is obtained from the **VULNERABILITIES** table, and each item obtained from this table can be completed with extra information from the **VULNERABILITIES_INFO**, **REFERENCES_INFO** and **BUGZILLA_REFERENCES_INFO**.

The bellow information can be obtained from these tables to consolidate a unique one for customer queries:
- CVE_ID
- PACKAGE. This column can be in a non-human readable format, but these values can be replaced with a human-readable version on the VARIABLES table. 
- TITLE. A brief of the vulnerability.
- RATIONALE. A complete description of the vulnerability.
- SEVERITY. A scale of the severity (LOW, MEDIUM, HIGH)
- PUBLISHED and UPDATED. The dates of the first published and the update of the vulnerability.
- BUGZILLA_REFERENCE y REFERENCE These fields are extracted from two different tables and can be appended to create one string with every reference found.
- OPERATION and OPERATION_VALUE. These fields usually don´t have useful information, but can be a good complement to inform the user how the package's version matches the rule.

**Note** regarding CVE_ID, PACKAGE, OPERATION, and OPERATION_VALUE:
There can be multiple entries for each CVE_ID as the same vulnerability can have multiple packages affected and there is one row for each of them, as OPERATION and OPERATION_VALUE refers to each of these packages, we should generate multiple entries for each CVE_ID+PACKAGE if we want to add the OPERATION and OPERATION_VALUE fields. On the other hand, as these fields are usually empty and are thought for programmatic analysis and not as information, they can be avoided. This lets us create one unique entry for each CVE_ID and append in one unique field as many PACKAGES this vulnerability affects.

To select the above information, the following SQL queries were implemented as an example:
SELECT CVEID, PACKAGE, `OPERATION`, OPERATION_VALUE FROM VULNERABILITIES WHERE TARGET = 'FOCAL' LIMIT 1 OFFSET 0;
SELECT VALUE FROM VARIABLES WHERE VID = 'oval:com.ubuntu.focal:var:201245420000300' AND TARGET = 'FOCAL'
SELECT TITLE, SEVERITY, PUBLISHED, UPDATED, RATIONALE FROM VULNERABILITIES_INFO WHERE ID = 'CVE-2021-28957';
SELECT BUGZILLA_REFERENCE FROM BUGZILLA_REFERENCES_INFO WHERE ID = 'CVE-2021-28957';
SELECT REFERENCE FROM REFERENCES_INFO WHERE ID = 'CVE-2021-28957';

**Comment by pereyra-m** [comment]
### Debian tables analysis 

Currently, only `Buster` and `Stretch` are supported.
The are three tables that have information related to these operating systems: **REFERENCES_INFO**, **VULNERABILITIES** and **VULNERABILITIES_INFO**.

One possible approach is to create a new table for every target, with the following fields:
- **CVEID**: the unique string identifies a vulnerability
- **PACKAGE**: the name of the vulnerable package
- **OPERATION**: it generally has the `less than` value. It is related to `OPERATION_VALUE`
- **OPERATION_VALUE**: the package version that is affected
- **REFERENCES**: a single link to the Mitre web page with more information about the CVE
- **PUBLISHED**: when the vulnerability was uploaded
- **UPDATED**: when the vulnerability was updated
- **RATIONALE**: a vulnerability description

It is importante to note that this feed has no severity related.
Also, the **IGNORE** column has to be considered to avoid duplicated information, and sometimes the **OPERATIONAL_VALUE** is 0, so it can be confusing for the user.

#### Test

All the information could be retrieved with the following example query for `Buster`:

```
    SELECT
        VULNERABILITIES.CVEID,
        VULNERABILITIES.PACKAGE, 
        VULNERABILITIES.OPERATION, 
        VULNERABILITIES.OPERATION_VALUE, 
        REFERENCES_INFO.REFERENCE,
        VULNERABILITIES_INFO.PUBLISHED,
        VULNERABILITIES_INFO.UPDATED,
        VULNERABILITIES_INFO.RATIONALE
    FROM 
        VULNERABILITIES
    INNER JOIN 
        REFERENCES_INFO ON VULNERABILITIES.CVEID = REFERENCES_INFO.ID AND VULNERABILITIES.TARGET = REFERENCES_INFO.TARGET
    INNER JOIN
        VULNERABILITIES_INFO ON VULNERABILITIES.CVEID = VULNERABILITIES_INFO.ID AND VULNERABILITIES.TARGET = VULNERABILITIES_INFO.TARGET
    WHERE 
        VULNERABILITIES.IGNORE = 0 AND VULNERABILITIES.TARGET = 'BUSTER'
    ORDER BY 
        VULNERABILITIES.CVEID;
```
