### ISSUE TITLE
Obtain syslogcollector data in Wazuh

### ISSUE THREAD

**Issue by srikwit** [wazuh/wazuh#846]
Hi Team,

I have enabled syscollector at the server conf using:
https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/wodle-syscollector.html

Where would I be able to view the raw data that is collected from the endpoints?
Can it be converted as an alert and processed upon?
Should the conf also be modified at the client or will it be pushed to the client?

**Comment by TJOSERAFAEL** [comment]
Hi @srikwit 

- Where would I be able to view the raw data that is collected from the endpoints?
You can view the raw data enabling the `logall` option on the manager ossec.conf file:
`<logall>yes</logall>`
Restart the manager, you will see all the traffic that the manager receives.

-  Can it be converted as an alert and processed upon?
Since the hardware info is stored on the database, you can view the information using the API https://documentation.wazuh.com/current/user-manual/api/reference.html#get-hardware-info

 - Should the conf also be modified at the client or will it be pushed to the client?
If your agents belong to the group `default`, you can add the syscollector wodle to the `/var/ossec/etc/shared/default/agent.conf ` file. This will be pushed to the agents and restart then automatically 

Best regards.

**Comment by srikwit** [comment]
Thanks @TJOSERAFAEL, please give me a day to test it out and close the issue. 
Thanks a lot for your detailed help.

**Comment by srikwit** [comment]
Thanks @TJOSERAFAEL , I have been able to successfully list the hardware scan , OS details and package scan details from Ubuntu machines but I am not getting any data for Windows machines. Can you please let me know if I am doing anything wrong?

**Comment by TJOSERAFAEL** [comment]
Hi @srikwit,

Let's try to find out whats happening.

- What version of the Wazuh Agent do you have installed on Windows? 
- What Windows version are you testing this on?

The syscollector configuration is exactly the same for Windows agents too.

Best regards.

**Comment by srikwit** [comment]
HI @TJOSERAFAEL , 

Wazuh agent version: Wazuh v3.3.1
Windows version: Microsoft Windows 10 Enterprise 10.0.17134

Thanks for reaching back.

**Comment by TJOSERAFAEL** [comment]
Hi @srikwit ,

can you please take a look on the agent's log and watch for any error related to syscollector?

Best regards.

**Comment by srikwit** [comment]
Thanks @TJOSERAFAEL I have remade an Windows only environment and I am able to get the same details as Linux systems. Thanks a lot for your patience and assistance.
