### ISSUE TITLE
Wazuh EDR capability to auto delete malaious file

### ISSUE THREAD

**Issue by ZubairRahimZubi** [wazuh/wazuh#8478]
On the slack community of Wazuh, I requested to add a feature to the EDR capability of Wazuh to auto-delete the malicious file I received this solution but it does not work for me. where is the error/bug?

Here is the proposed answer https://wazuh.slack.com/archives/C0A933R8E/p1619793327378600

**Comment by MiguelazoDS** [comment]
Hello ZubairRahimZubi, 

Apologies for overlooking this question. Unfortunately, I'm not able to see the **Slack** thread due to the period of time slack retains the messages.
But I can explain an approach on how to perform what you describe. For this, you could use the integrator module to integrate Wazuh with the external **Virus Total API** together with the Wazuh **FIM**
module.

Using the **FIM** module allows you to trigger alerts every time a change is detected under the directory that is monitored by **FIM**. 
This option is configurable under the ossec.conf file on your agent. 

For this case, you may want to configure real-time monitoring under a certain directory.

```xml
<syscheck>
  <directories check_all="yes" realtime="yes">c:/tmp</directories>
</syscheck>
```

More about **FIM** configuration can be found [here](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/index.html)

It will trigger an alert when it detects a change. The alert contains a hash of the file that will be captured by the Virus Total integration (when it is enabled)
and will perform a request to the **Virus Total API** to detect if whether or not it is a malicious file. 

To configure the integration you will need something like this.

```xml
<integration>
  <name>virustotal</name>
  <api_key>API_KEY</api_key> <!-- Replace with your VirusTotal API key -->
  <group>syscheck</group>
  <alert_format>json</alert_format>
</integration>
```

The **API_KEY** is obtained from www.virustotal.com after registration.

More about this integration [here](https://documentation.wazuh.com/current/user-manual/capabilities/virustotal-scan/integration.html)

Finally, it is required to also configure Active Response to remove the malicious files detected under the directory configured by **FIM**

In your manager, a block like this is needed 

```xml
<ossec_config>

    <command>
        <name>remove-threat</name>
        <executable>remove-threat.sh</executable>
        <timeout_allowed>no</timeout_allowed>
    </command>

    <active-response>
        <disabled>no</disabled>
        <command>remove-threat</command>
        <location>local</location>
        <rules_id>87105</rules_id>
    </active-response>

</ossec_config>
```

Where the `rule id 87105` is triggered after a malicious file is detected by Virus Total.
Then the script described by the command tag is in charge to delete the file. 

More details [here](https://documentation.wazuh.com/current/user-manual/capabilities/active-response/ar-use-cases/removing-malware.html)

I hope it is not too late for this and helps. Regards!
