### ISSUE TITLE
Exploratory test in Linux based(Ubuntu, Centos 5, Centos 8 and Archlinux)

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#8518]
## Description
Execute defined charter to verify in high level the correct functionality.

Manager: manager-siteox.wazuh.info

## DoD 
- [ ] Run charters.
- [x] Post charter results as evidence.

## Charter
- Check libwazuhext and libwazuhshared deployment.
- Validate active response run as well local and e2e for restart-agent.
- Compare size of new installers with pre-release versions -> 
[Centos 5](https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/trash/yum5/x86_64/wazuh-agent-4.2.0-footprint.el5.x86_64.rpm)
[Centos > 5](https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/trash/yum/wazuh-agent-4.2.0-footprint.x86_64.rpm)
[Deb](https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/trash/apt/pool/main/w/wazuh-agent/wazuh-agent_4.2.0-footprint_amd64.deb)
- Compare deployed new agent size vs pre-release version.
- Only for Ubuntu, Centos 5 and Centos 8 -> Imports dll lists PE-bear / ldd-otool results for each binary Wazuh/bin and Wazuh/active-response/bin

**Comment by konangc87** [comment]
**Ubuntu 20.04**
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/bb819ae7-3ec6-45b1-bf34-d6d4af2fea25)
**Fresh install:**
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/3708adbb-3dc6-4151-8317-dbd1c8ecc51a)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/0f2ed258-bd35-45ae-829a-ac0142ae57be)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/216a2f35-0998-4ca7-a535-5d10a36c7941)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/19d2c057-7a41-4a7d-98ac-387d52597c10)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/53b47ffa-07b3-47b4-836f-efb0b2b8ce29)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/805cef7b-e9fa-44bc-91b7-cb5405d3c83e)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/0ce8b2c2-7c2b-49f0-9eaa-0d4b5cbe42eb)
**Upgrade from 4.1.5:**
Worked as expected.

**Comment by tinachoB** [comment]
**Centos 8**

- **Package size:**
![image](https://user-images.githubusercontent.com/22640902/118048370-92695980-b352-11eb-8b8e-dc9acd5d4bde.png)

- **Wazuh binaries size:**
![image](https://user-images.githubusercontent.com/22640902/118048481-b88ef980-b352-11eb-9f53-422b3287e612.png)

- **Wazuh Active Reponse binaries size:**
![image](https://user-images.githubusercontent.com/22640902/118048553-cf355080-b352-11eb-8aa6-a22ffb741146.png)

- **Wazuh Active Reponse libraries loaded per binary:**
![image](https://user-images.githubusercontent.com/22640902/118048768-1f141780-b353-11eb-94fc-7fe2c2aea13c.png)
![image](https://user-images.githubusercontent.com/22640902/118048869-4c60c580-b353-11eb-8b61-3e0354c81074.png)
![image](https://user-images.githubusercontent.com/22640902/118048937-6a2e2a80-b353-11eb-8a82-d364d02f529d.png)
![image](https://user-images.githubusercontent.com/22640902/118049000-8205ae80-b353-11eb-81ec-bfb071c7c276.png)
![image](https://user-images.githubusercontent.com/22640902/118049050-921d8e00-b353-11eb-8d97-9b17adbc57cf.png)

**Comment by konangc87** [comment]
**Arch Linux**
**Fresh Install from sources**
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/c99a34a1-ffda-4afe-b538-e3faa6027c37)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/eda9b821-2c1a-46e1-a292-c43d7376acd2)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/db1a3a85-79a2-4712-9b04-8e14a4dc6d7f)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/5e89ff42-dec7-4184-9308-a8e8a647e31d)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/3cbbf37f-3b17-4dd4-94d3-9d7ba30538ab)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/10f64276-7fa4-4a6d-a088-867308295cd8)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/abdf3c3e-c593-4605-a9d4-d21638b2c0bd)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/6666a91e-60e7-4c7c-a5b7-83a2fefcd726)
**Upgrade from 4.1.5 from sources**
Worked as expected. One little detail is that there's no entry in active-responses.log of the execution of restart-wazuh binary even though it's executed correctly and can be checked in ossec.log snapshot. This issue was also observed in 4.2 branch.

**Comment by Dwordcito** [comment]
**Centos 5**
Fresh install
![imagen](https://user-images.githubusercontent.com/14300208/118095171-20bafb00-b3a6-11eb-98c7-24753f4be03f.png)
![imagen](https://user-images.githubusercontent.com/14300208/118095291-42b47d80-b3a6-11eb-89f6-9bd4d4322116.png)
![imagen](https://user-images.githubusercontent.com/14300208/118095306-4811c800-b3a6-11eb-9e2d-951e8af084c0.png)
![imagen](https://user-images.githubusercontent.com/14300208/118095375-5f50b580-b3a6-11eb-9287-d374cc3aeb6e.png)
![imagen](https://user-images.githubusercontent.com/14300208/118095416-6d9ed180-b3a6-11eb-93bd-723b1a65d472.png)
![imagen](https://user-images.githubusercontent.com/14300208/118095449-74c5df80-b3a6-11eb-9455-2015b7c7730b.png)
![imagen](https://user-images.githubusercontent.com/14300208/118095533-92934480-b3a6-11eb-9d73-abd5de268aa3.png)
![imagen](https://user-images.githubusercontent.com/14300208/118095597-a6d74180-b3a6-11eb-9c94-d0f95247e3d2.png)


Upgrade from 4.1.5 from sources
Worked as expected. One little detail is that there's no entry in active-responses.log of the execution of restart-wazuh binary even though it's executed correctly and can be checked in ossec.log snapshot. This issue was also observed in 4.2 branch.
