### ISSUE TITLE
Compare cluster performance metrics after improvements 

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#8562]
Hi team,

After the investigation of the API and cluster performance in loaded environments done in the issue https://github.com/wazuh/wazuh/issues/7366, we have included several changes to improve the Wazuh cluster performance, avoid errors, reduce times, etc.

The aim of this issue is to check that the changes done have improved the cluster performance metrics:
- integrity check time
- integrity sync time
- agent-info sync time and chunks sent (all chunks are now sent at once as a string using `send_string()`, maybe this will decrease max times found in `agent-info` 4.2.0 metrics but increase the rest of times, check this)

These tests will be parameterized as following:

```
MANAGER_WORKERS= 10
AGENTS_NUMBERS= 25000
```

Regards,
Manuel.

**Comment by mcarmona99** [comment]
## 4.2.0 tests:

### Test 1:


#### Parameters:
**Version:** 4.2.0
**Workers:** 10
**Agents:** 25.000
**Test duration:** 900s
**Build:** 233

☑️ **Kibana API request**  



#### Results:

There has been an error regarding the load balancer. A worker has less agents connected than the other ones. I have investigated this and opened a new issue: https://github.com/wazuh/wazuh-qa/issues/1323

Another problem was an agents host broke down. This has happened some times in the past. In this case the environment has 24500 agents instead of 25000 due to this issue. This will not have a big effect on the test.




### Test 2



#### Parameters:
**Version:** 4.2.0
**Workers:** 25
**Agents:** 50.000
**Test duration:** 900s
**Build:** 234

☑️ **Kibana API request**  



#### Results:

There are TCP sessions dropping, as it was reported here: https://github.com/wazuh/wazuh-qa/issues/1294#issuecomment-839726944




Tests building again ...

**Comment by Selutario** [comment]
# Results comparison

Hi team!

Updates like this will focus on explaining the results after comparing two identical builds, except for the package used. One package will be 4.2 in its current state, and another will contain all cluster fixes and enhancements that have not yet been merged. 

## Test parameters:
**Version:** 4.2.0
**Workers:** 10
**Agents:** 25.000
**Test duration:** 900s
**Pipeline**: Test_cluster_performance_without_LB
**Build without fixes/improvements:** 4 (based on [4.2-no-cluster-improvements](https://github.com/wazuh/wazuh/tree/4.2-no-cluster-improvements) branch)
**Build with fixes/improvements:** 5 (based on [4.2-new-cluster-improvements](https://github.com/wazuh/wazuh/tree/4.2-new-cluster-improvements) branch)

☑️ **Kibana API request**  

## Comparison
Most comparisons will be made on a single node since they all present very similar results. 

### Agent-info (worker1)
#### Before improvements
![imagen](https://user-images.githubusercontent.com/23361101/118147628-11709780-b410-11eb-9b7b-bfca35816f48.png)
#### After improvements
![imagen](https://user-images.githubusercontent.com/23361101/118149068-7ed0f800-b411-11eb-8c2c-a18a1583f34f.png)

### Integrity check (worker1)
I noticed that after the agent-info refactor, the `[Integrity check] Finished in` log shows the time needed until the master responds to the worker whether synchronization is requested or not (build 5).

Before the refactor (build 4), the log showed how long it took the worker to send the metadata, without taking into account all the time that could pass until the master responded.

Despite having to wait for the master response, the improvement is evident. It would be even more pronounced if the same criteria had been followed. 

#### Before improvements
![imagen](https://user-images.githubusercontent.com/23361101/118148758-2dc10400-b411-11eb-9ef4-d09389e9fb78.png)

#### After improvements
![imagen](https://user-images.githubusercontent.com/23361101/118148777-30235e00-b411-11eb-8333-bcfb02581cde.png)

### Integrity sync (worker1)
No direct improvement has been made on this task. The better result is a consequence of the fact that the cluster process has less overall load thanks to the change of the MD5 and agent-info. 

#### Before improvements
![imagen](https://user-images.githubusercontent.com/23361101/118149026-711b7280-b411-11eb-9130-32b1b2e4cf2a.png)
#### After improvements
![imagen](https://user-images.githubusercontent.com/23361101/118149100-85f80600-b411-11eb-9258-0cc903a3b3e8.png)


### CPU (worker1)
#### Before improvements
![imagen](https://user-images.githubusercontent.com/23361101/118149227-a45e0180-b411-11eb-838d-b85d7e279266.png)
#### After improvements
![imagen](https://user-images.githubusercontent.com/23361101/118149241-a88a1f00-b411-11eb-989a-2585df609436.png)


### CPU (master)
#### Before improvements
![imagen](https://user-images.githubusercontent.com/23361101/118149318-b93a9500-b411-11eb-92c8-a392f14a62a0.png)
#### After improvements
![imagen](https://user-images.githubusercontent.com/23361101/118149332-bdff4900-b411-11eb-89e4-bbdf673ce741.png)

In progress...

Regards,
Selu.
