### ISSUE TITLE
Wazuh 3.11.5 ignores random events 

### ISSUE THREAD

**Issue by MrRubi** [wazuh/wazuh#8596]
Wazuh version | Component | Install type | Install method | Platform
-- | -- | -- | -- | --
3.11.5 | Logcollector | Manager/Agent | Source code| Linux

We use Wazuh 3.11.5 on a production environment. We started to notice that some events from critical sources were being randomly ignored by Wazuh. We call it "randomly" because the decoder and ruleset works perfectly, but for the same exact event, sometimes Wazuh raises and alert and other times, no.

Our first hipotesis was that the logcollector queue reached his limit and some events were lost. To solve this, we created an independent Wazuh instance only reading events from this critical source (we are talking about 20 events per month maximum). But even so, this new instance ignores some of the events. 

We completely discard that this problem is due to high event volume. And also the events are triggered very time separated, so we also discard that wazuh is aggregating multiple of the alerts in a single one.

When this happensa, there are not any information on the ossec.log output that could indicate a malfunction in Wazuh.

These are the parameters we set in the internal_options.conf:

```
# Decoder event queue size
analysisd.decode_event_queue_size=2000000
# Decode syscheck queue size
analysisd.decode_syscheck_queue_size=2000000
# Decode syscollector queue size
analysisd.decode_syscollector_queue_size=2000000
# Decode rootcheck queue size
analysisd.decode_rootcheck_queue_size=2000000
# Decode security configuration assessment queue size
analysisd.decode_sca_queue_size=2000000
# Decode hostinfo queue size
analysisd.decode_hostinfo_queue_size=2000000
# Decode winevt queue size
analysisd.decode_winevt_queue_size=2000000
# Decode Output queue
analysisd.decode_output_queue_size=2000000
# Archives log queue size
analysisd.archives_queue_size=2000000
# Statistical log queue size
analysisd.statistical_queue_size=2000000
# Alerts log queue size
analysisd.alerts_queue_size=2000000
# Firewall log queue size
analysisd.firewall_queue_size=2000000
# FTS log queue size
analysisd.fts_queue_size=2000000
# Interval for analysisd status file updating (seconds) [0..86400]
# 0 means disabled
analysisd.state_interval=5


# Logcollector file loop timeout (check every 2 seconds for file changes)
logcollector.loop_timeout=2

# Logcollector number of attempts to open a log file [2..998]
logcollector.open_attempts=8

# Logcollector - If it should accept remote commands from the manager
logcollector.remote_commands=0

# Logcollector - File checking interval (seconds) [0..1024]
logcollector.vcheck_files=64

# Logcollector - Maximum number of lines to read from the same file [100..1000000]
# 0. Disable line burst limitation
logcollector.max_lines=0

# Logcollector - Maximum number of files to be monitored [1..100000]
logcollector.max_files=1000

# Time to reattempt a socket connection after a failure [1..3600]
logcollector.sock_fail_time=300

# Logcollector - Number of input threads for reading files
logcollector.input_threads=4

# Logcollector - Output queue size [128..220000]
logcollector.queue_size=220000

# Sample log length limit for errors about large message [1..4096]
logcollector.sample_log_length=64

# Maximum number of file descriptor that Logcollector can open [1024..1048576]
# This value must be higher than logcollector.max_files
logcollector.rlimit_nofile=1100

# Force file handler reloading: close and reopen monitored files
# 0: Disabled
# 1: Enabled
logcollector.force_reload=0

# File reloading interval, in seconds, if force_reload=1 [1..86400]
# This interval must be greater or equal than vcheck_files.
logcollector.reload_interval=64

# File reloading delay (between close and open), in milliseconds [0..30000]
logcollector.reload_delay=1000

# Excluded files refresh interval, in seconds [1..172800]
logcollector.exclude_files_interval=86400
```

In order to reproduce the error, just deploy a wazuh 3 instance and generate random events. 

Are you aware of this behaviour?

Regards
Angel

**Comment by vikman90** [comment]
Hi @MrRubi,

Indeed, the behavior you describe is not expected. First, we're updated Logcollector with many features and bug fixes since 3.11. There is a related issue (#4673) that we fixed in 3.12 (#4730). Did you have a chance to test that in the latest version (4.1.5)?

On the other hand, you confirmed you saw no errors in _ossec.log_, but I did not understand that you created an independent instance. Do you mean a dedicated agent that is only monitoring the critical source, or an independent manager that has enabled `<localfile>` only?

We don't expect the system to drop any message without logging that. These are the points that I would examine in order to figure out where the problem is. In this example, we're adding a simple rule for this log:

```
test: Hello
```

To produce this alert:
```
** Alert 1620988130.533161: - local,syslog,sshd,
2021 May 14 12:28:50 (hirsute) any->/root/test/test.log
Rule: 100001 (level 5) -> 'Test rule.'
test: Hello
```

### Logcollector

If we enable the internal option `logcollector.debug=2`, we should see a log like this:

```
DEBUG: Reading syslog message: 'test: Hello'
DEBUG: Read 1 lines from /root/test/test.log
```

Despite it would be very unlikely with your configuration, Logcollector might lose logs when detected a rotation. If this happens, we would see a log like this:

```
DEBUG: Performing file check.
DEBUG: File inode changed. /root/test/test.log
```

And this alert:
```
** Alert 1620988569.533789: - ossec,pci_dss_10.5.2,pci_dss_10.5.5,gpg13_10.1,gdpr_II_5.1.f,gdpr_IV_35.7.d,hipaa_164.312.b,nist_800_53_AU.9,tsc_CC6.1,tsc_CC7.2,tsc_CC7.3,tsc_PI1.4,tsc_PI1.5,tsc_CC7.1,tsc_CC8.1,
2021 May 14 12:36:09 (hirsute) any->wazuh-logcollector
Rule: 591 (level 3) -> 'Log file rotated.'
ossec: File rotated (inode changed): '/root/test/test.log'.
```

If the Logcollector's queue got full, it would print this log (although we ruled out this condition):
```
WARNING: Target 'agent' message queue is full (1024). Log lines may be lost.
```

### Agent daemon

The agent has another queue that might get full. When it happens, it prints these logs:
```
WARNING: Agent buffer at 90 %.
WARNING: Agent buffer is full: Events may be lost.
```

And it sends the event to the manager for it to produce this alert:
```
** Alert 1620988666.566400: - wazuh,agent_flooding,gdpr_IV_35.7.d,
2021 May 14 12:37:46 (hirsute) any->wazuh-agent
Rule: 203 (level 9) -> 'Agent event queue is full. Events may be lost.'
wazuh: Agent buffer: 'full'.
level: full
```

### Remoted (in the manager)

Remoted has another queue. If agents fill it, Remoted prints this warning:
```
WARNING: Message queue is full (131072). Events may be lost.
```

### Analysisd

I can imagine two points where Analysisd might drop an event.

1. The input queue is full.

The input queue is the only that can drop events, while the rest of internal queues are blocking. Analysisd can print this warning if the input queue gets full:

```
Input queue is full.
```

2. Malfunction in the rule matcher.
If there was a bug there, I would expect it to fail always. But let me suggest to enable archives in _etc/ossec.conf_:

```xml
<ossec_config>
  <global>
    <logall>yes</logall>
```

Set `<logall>` to `yes` and restart the manager. Then, anytime it should print every input log in _logs/archives/archives.log_ no matter if they produced an alert:

```
2021 May 14 12:40:14 (hirsute) any->/root/test/test.log test: Hello
```

I hope the steps above help us to narrow down the problem. Thank you for reporting this behavior.

I await your reply.
Best regards.

**Comment by MrRubi** [comment]
Hello @vikman90 vikman90 

Thank you for your comments.

When I said that I created an  independent instance, I mean I have a manager that has enabled <localfile> only for the critical source.

I did not test it on wazuh 4.1.5. I will try to apply your recommended config

logcollector.debug=2

**Comment by vikman90** [comment]
@MrRubi I see you've closed this issue. I'm looking forward to having your feedback. Please feel free to reopen it if you need further help.

Best regards.
