### ISSUE TITLE
 TO change the Kibana name to InternalThreats

### ISSUE THREAD

**Issue by vamse15** [wazuh/wazuh#869]
Hello, i need yr help please, i'm a new member of wazuh, i've just follow the wzush online document 2.0 guide for system installation. The installation was done, i saw the "Management / Kibana" when click on Index Patterns button under Management Tab, when i click on Index Patterns tab it showing "Management / Kibana" , how to change from "Management / Kibana" to "Management / InternalThreats" [no results found]. May you help me ?

In screen shot two marked with red color, what i am going to change name Kibana to InternalThreats .

kibana version 5.6.3
wazuh ---2.1
![screenshot1](https://user-images.githubusercontent.com/28727493/42024677-5c69a8ce-7ae0-11e8-8765-557fb803f015.png)
![screenshot2](https://user-images.githubusercontent.com/28727493/42024678-5c9e4c8c-7ae0-11e8-9b70-3307b03913f7.png)

**Comment by jesusgn90** [comment]
Hello @vamse15 ,

First of all I want to say you are following an outdated documentation unless you really want to use Elastic 5.x and Wazuh 2.x due to any reason.

- Current documentation for Wazuh:
  - https://documentation.wazuh.com/current/installation-guide/
- Current documentation for Elastic:
  - Look at https://www.elastic.co/ for each component you are using

Since the Wazuh App is a Kibana plugin we don't modify the Kibana UI itself, any case my suggestion is go directly to the discuss forum at https://discuss.elastic.co, that's the Elastic main forum. Regarding to Kibana itself, the right forum is located at https://discuss.elastic.co/c/kibana.

Hope it helps,
Jesús
