### ISSUE TITLE
Add debug message for cluster restart

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#8718]
|Wazuh version|Component|
|---|---|
| 4.3 | Wazuh-clusterd |

## Description

Hi team,

In the current version of `Wazuh-clusterd` there is no easy way to determine if the cluster has restarted at any given time. We should add a new debug message in `cluster.log` to let us now when the cluster starts or restarts.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Selutario** [comment]
## Issue update

Hey team!

I've been trying to implement what is requested in this issue. We wanted to achieve (or investigate) two aspects: 

#### 1. Show a log message in the node that is being stopped/restarted
Until now, there was no message at all when restarting a node. It was possible to infer that the node was stopped because a disconnection message was shown in the logs of the other node. If the master node was restarted, a message like the one below would show up in all the workers.
```
2021/05/19 15:48:24 INFO: [Worker worker1] [Main] The master closed the connection
```
In case a worker was stopped, the message would appear in the master node and would look like this: 
```
2021/05/19 15:47:29 DEBUG: [Worker worker2] [Main] Disconnected.
2021/05/19 15:47:29 INFO: [Worker worker2] [Main] Cancelling pending tasks.
```

Now, we are handling the signals so that an explicit message is displayed in the log of the stopped node itself, which can help to understand what happens in the cluster at certain times. 
```
2021/05/19 15:40:57 INFO: [Master] [Main] SIGTERM received. Canceling all tasks...
```

This was easy to achieve in the master node and it's already finished there, but it is not working in the worker nodes yet. It seems that tasks are not being canceled in the worker nodes so the process does not end.

#### 2. Send a message to the workers before stopping the master
We wanted to send a new command `b'm_restart'` to the workers with information about which signal had been received in the master node or vice-versa. In order to do this, we needed to use the method `send_request`. 

However, said method can only be used inside client handlers, so a function like below should be called inside [MasterHandler](https://github.com/wazuh/wazuh/blob/1cf8f31463a364f1f8003622b60e729059830380/framework/wazuh/core/cluster/master.py#L133), for instance:
```PYTHON
async def ask_exit(self, sig):
    self.logger.info(f"{sig} received. Notifying to {self.name}...")
    await self.send_request(b'm_restart', data=sig.encode())
    for task in asyncio.all_tasks():
        task.cancel()
```

The problem is that there is one instance of [MasterHandler](https://github.com/wazuh/wazuh/blob/1cf8f31463a364f1f8003622b60e729059830380/framework/wazuh/core/cluster/master.py#L133) for each worker connected to the master so, once the first instance executes the method above, all tasks are canceled in the master and only one worker can be notified.

However, we can not skip the `task.cancel()` since once we are handling the SIGTERM signal, we are responsible for stopping all the tasks. Otherwise, the clusterd process does not stop unless it is kill with `-9` option.

I have been investigating different ways although finally, I believe that there is no correct way to do this. Therefore, this second point should be discarded. 

### To do
- Find out why worker nodes are not canceling all taks in the same way that the master node.
- Test if there is any unusual behavior.

Regards,
Selu.
