### ISSUE TITLE
Add the possibility of using VPC endpoints on the AWS integration

### ISSUE THREAD

**Issue by fhielpos** [wazuh/wazuh#8761]
|Wazuh version|Component|
|---|---|
| 4.1.5 | AWS integration |

Hello team,

This issue is to evaluate the feasibility of adding the option to use VPC endpoints to make the calls from boto3 to AWS in the AWS integration.

By adding this possibility, users of the AWS integration would be able to reduce the costs of the constant requests to the AWS services.

Reference:
- https://aws.amazon.com/premiumsupport/knowledge-center/vpc-reduce-nat-gateway-transfer-costs/

Regards,
Franco Hielpos

**Comment by CarlosRS9** [comment]
## Status update

After some research about VPC Endpoints and the required changes to be able to use them in our AWS module, we concluded that it is feasible to add the proposed feature.

We would use a VPC endpoint for the Amazon S3 service, as it is the one we use when accessing the logs for each bucket through boto3. Regarding the supported AWS services, CloudWatchLogs service will require the creation of a different VPC endpoint by the user while AWS Inspector is not compatible at all with VPC endpoints.

The VPC endpoint URL must be specified in the wodle configuration by means of a new parameter, so that the module can make use of this endpoint.

Finally, in order to correctly test this new feature we will need a cloud environment consisting of a VPC with a host running Wazuh and the updated AWS module, as well as a VPC endpoint for Amazon S3.

**Comment by CarlosRS9** [comment]
## Status Update

The development is finished. The support will be added in the form of two new tags available for buckets and services configuration:
- `sts_endpoint` : Allows the user to specify a VPC endpoint to be used for the STS token request when a IAM role is provided.

- `service_endpoint`: Allows the user to specify a VPC endpoint to be used to obtain the data from buckets (S3) or the service required.

Here is an example:
```
<wodle name="aws-s3">
  <disabled>no</disabled>
  <interval>10m</interval>
  <run_on_start>yes</run_on_start>
  <skip_on_error>yes</skip_on_error>

  <bucket type="cloudtrail">
    <name>wazuh-cloudtrail</name>
    <aws_profile>dev</aws_profile>
    <service_endpoint>https://bucket.xxxxxxxxxxx.s3.us-east-2.vpce.amazonaws.com</service_endpoint>
  </bucket>

    <service type="cloudwatchlogs">
    <aws_profile>dev</aws_profile>
    <regions>us-east-2</regions>
    <aws_log_groups>framework-test-apache</aws_log_groups>
    <service_endpoint>https://xxxxxxxxxxx.logs.us-east-2.vpce.amazonaws.com</service_endpoint>
  </service>

</wodle>
```

The documentation for this new feature is in progress.
