### ISSUE TITLE
Make API timeout customizable in the `api.yaml`

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#8799]
|Wazuh version|Component|
|---|---|
| 4.3 | API |

## Description

Hello team!

Right now, the API default timeout is 10 seconds, and it is defined inside the `cluster.json` file, which does not make much sense as it is not so closely related to the cluster (#L112):
https://github.com/wazuh/wazuh/blob/7ed5c58e213e4d085e685fd59d313f7a6d5c4a4c/framework/wazuh/core/cluster/cluster.json#L109-L114

This value should be able to be set in the `api.yaml` file. However, there is a problem: if you only modify the master's timeout, there will be strange behaviors in the distributed requests (if timeout is reached in any worker, for instance). 

For this reason, it is necessary to study whether the API timeout should be passed as a parameter in the distributed requests or the importance of clearly indicate to the users that establishing the same value in all nodes is required. 

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Selu.

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

Usually, the average response time is used to establish a maximum response time. In our case, we would have to study which endpoint consumes more time depending on the number of resources.

An environment with 100000 agents will have a different mean response time than an environment with 1000 agents. If we manage to determine the scale between the times, we could determine an approximate average response time for each environment in a personalized way. However, this has the disadvantage that several endpoints have scalability problems, so we would have to establish as the maximum time **the average time necessary to attend the most time-consuming request**.

Another option is to follow the current standards of consolidated APIs such as AWS, GCP, Azure, DigitalOcean, SalesForce, etc. Within these, we have times between **5 seconds to 2 minutes**. In our case, we do not estimate necessary a time of 2 minutes because if this happens we would have a serious performance problem because the Wazuh interface could not work properly.

Therefore, based on these investigations, we have two possible solutions: 

- The first one is to set a custom timeout based on the most time-consuming endpoint. This solution is not straightforward as it will depend on the number of resources and the type (agents, rules, etc).

- The second solution is to set a static timeout based on other APIs. In which case, I think we should not exceed 1 minute timeout. And as for the default value, we can set it to **20-30 seconds**.
