### ISSUE TITLE
Remove old `calculate_status` function in framework

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#8802]
|Wazuh version|Component|
|---|---|
| master | Wazuh component |

## Description

Hi team, 

After the refactor of agent status (#6479), there are a function that is no longer used nor needed:
https://github.com/wazuh/wazuh/blob/8aff0c96e9a0d2cbe535534cea7225d2ceb3afcb/framework/wazuh/core/agent.py#L1243-L1251

We should remove it, together with its unit test:
https://github.com/wazuh/wazuh/blob/8aff0c96e9a0d2cbe535534cea7225d2ceb3afcb/framework/wazuh/core/tests/test_agent.py#L1481-L1499

and this unused variable:
https://github.com/wazuh/wazuh/blob/8aff0c96e9a0d2cbe535534cea7225d2ceb3afcb/framework/wazuh/core/common.py#L182

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Selu.

**Comment by mcarmona99** [comment]
## Issue update

As @selutario said in his last comment [here](https://github.com/wazuh/wazuh/pull/8846#issuecomment-852920049), the WazuhDBQueryAgents `min_select_fields` needs to be changed due to the new behavior. 

The API integration tests using the `select` parameter also need to be changed to use `test_select_key_affected_items` as we were not testing them properly in some test cases.

A new test case needs to be added to test the `GET /agents` endpoint sorting by `status` as old code to sort by status will be removed to.

Regards,
Manuel.
