### ISSUE TITLE
The sysinfo.dll triggers and exception after starting the WazuhSvc in Windows 8 and 8.1

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#8822]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2 | Syscollector | Agent | 4.2 branch | Windows 8 and 8.1 |

The WazuhSvc stops after installing the 4.2 agent version because of an exception generated by the `sysinfo.dll`. The service runs just a moment and then it stops the execution because of this error.

![image](https://user-images.githubusercontent.com/5703274/119746762-970c3280-be67-11eb-9eb3-dca802c48079.png)

The issue was reproduced in both Windows 8 x64 and Windows 8.1 x64 clean installations. It was also verified that the issue does not happen in Windows 10 x64. Attached you can find the logs of the agent installed on Windows 8.1.

[ossec.log](https://github.com/wazuh/wazuh/files/6550278/ossec.log)

**Comment by tinachoB** [comment]
I've been executing some tests around this issue and, effectively, the service stops running after this bug is reproduced. I used the sysinfo test tool to double check if the system information is being populated correctly and this was the result:
![image](https://user-images.githubusercontent.com/22640902/119763585-34765f00-be86-11eb-842f-e0e25c724a68.png)

It looks like the issue is located in the code where the specific Windows version is being consulted. The following line: https://github.com/wazuh/wazuh/blob/4.2/src/data_provider/src/osinfo/sysOsInfoWin.cpp#L29 tries to get information for two possible registry values (it's under the `IsWindows8OrGreater()` condition evaluated to true):
- CurrentMinorVersionNumber
- CurrentMajorVersionNumber

In particular, those attributes don't exist in Windows 8/8.1:
![image](https://user-images.githubusercontent.com/22640902/119763443-ecefd300-be85-11eb-9cfd-302c67f555f2.png)

So the fix is under the `getVersion` method (https://github.com/wazuh/wazuh/blob/4.2/src/data_provider/src/osinfo/sysOsInfoWin.cpp#L21)
