### ISSUE TITLE
ossec always not working

### ISSUE THREAD

**Issue by xxxby** [wazuh/wazuh#8864]
ossec-auth always not working,After manually turning it on, it automatically shuts down in a short time.
This is reported in the log:
ossec-authd: ERROR: SSL Error (0)

**Comment by jnasselle** [comment]
Hi @xxxby ,
Sorry to hear you are having troubles. I'm going to need some extra information in order to determinate what is causing your problem:

- Wazuh Version
- Operating System
- `ossec.log` extract containing the error while setting `authd.debug=2` in [`local_internal_options.conf`](https://documentation.wazuh.com/current/user-manual/reference/internal-options.html)
- Any custom configuration related to [`<auth>`](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/auth.html) block.

Thank you and I wait for this information to move forward.

Regards,
Nico

**Comment by jnasselle** [comment]
Close this issue due to inactivity. Feel free to reopen it if you have any questions.

Regards
