### ISSUE TITLE
Improve PUT /agents/restart API request

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#8870]
## Environment settings
- Agents: 50000
- Workers: 5

## Description

Hi team,

Continuing with the tests of the issue https://github.com/wazuh/wazuh/issues/8325, we have detected a scalability problem with the `PUT /agents/restart` endpoint. 

In this case, again we have an error of type Timeout, in 10 seconds the API does not return a response to this request so it is canceled and a Timeout error is returned.

The goal of this issue is to improve as much as possible this endpoint. Here we can see the api.log file for this request and its response:

#### api.log
```
2021/05/31 16:03:09 INFO: wazuh 172.31.80.61 "GET /" with parameters {} and body {} done in 0.011s: 200
2021/05/31 16:03:23 INFO: wazuh 172.31.80.61 "PUT /agents/restart" with parameters {} and body {} done in 13.937s: 500
2021/05/31 16:04:23 INFO: wazuh 172.31.80.61 "GET /" with parameters {} and body {} done in 0.006s: 200
```

#### Response
```
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "Test_cluster_performance_B162_manager_2": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_1": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_5": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_4": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_3": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    }
  },
  "error": 3021
}
```

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by mcarmona99** [comment]
## Issue update

This problem was also detected and commented in the issue: https://github.com/wazuh/wazuh/issues/6748.

It was discovered in the investigation done in the issue https://github.com/wazuh/wazuh/issues/6744 and it is related to the endpoints `PUT /agents/restart`, `PUT /agents/node/{node_id}/restart` and `PUT /agents/group/{group_id}/restart` in loaded environments.

Due to the RBAC changes in Wazuh v.4.0.0, it is not possible to restart all agents at once due to permissions from users. For that reason, in environments with a lot of agents, these calls may take a lot of time to process since they restart the agents 1 by 1, following a list of permitted agents.

The solution proposed was the usage of tasks. In these cases, the API would process the restart petitions, start tasks for the restart of those agents and provide a response with the task_ids. Later on, the user could check the status of all or some of those tasks using the appropriate endpoints. 

The API should never wait until all the processing is finished for such long tasks.

**Comment by mcarmona99** [comment]
## Issue update

### PUT /agents/restart profiling

We have been testing to obtain the time spent by the different parts of the **Framework** code. The testing environment has `2000 agents` and `1 worker` node. Next, we are going to show the code with the consumed times:

```
    for agent_id in agent_list:
        try:
            if agent_id not in system_agents:
                raise WazuhResourceNotFound(1701)
            if agent_id == "000":
                raise WazuhError(1703)
            Agent(agent_id).restart()  --------------------------> time spent in agent.restart = 0.001-0.004
            result.affected_items.append(agent_id)
        except WazuhException as e:
            result.add_failed_item(id_=agent_id, error=e)
    ------------------------> time spent in loop = 2.978053569793701
```

```
    def restart(self) -> str:
    	"""
    	...
    	"""
        # Check if agent is active
        self.get_basic_information()    -------------------------> time spent in get_basic_information = 0.0009 - 0.001
        if self.status.lower() != 'active':
            raise WazuhError(1707, extra_message='{0}'.format(self.status))

        return send_restart_command(self.id, self.version) -------------------------> time spent in send_restart_command = time loop - time get_basic_info = 0.003
```

The part of the code that is taking more time is the `restart` method. This is the bottleneck as this line is repeated for all agents. In that method, `send_restart_command` is taking the most time. `get_basic_information` is also taking part of the time.

To improve this code, I have improved the `send_restart_command` method. 
A WazuhQueue object is created for each agent in agent_list to be restarted. This can be generalized as it is done in active response. I have changed this to create only a WazuhQueue object that will be used for all agents.

I have also changed `get_basic_information` to `load_info_from_db` as we don't need the json created in `get_basic_information`.

Regards,
Manuel.

**Comment by mcarmona99** [comment]
## Issue update

After the last changes (only 1 wq and get_basic_info changed to load_info), I have decided to use a WazuhDBQuery instead of loading each agent database information. The following is the code with the new improvements and times. The testing environment has `2000 agents` and `1 worker` node.

```
    agent_list = set(agent_list)

    # Add agent with ID 000 to failed_items
    try:
        agent_list.remove('000')
        result.add_failed_item('000', WazuhError(1703))
    except KeyError:
        pass

    if agent_list:
    	# ---------------- GET DATA FROM DB
        system_agents = get_agents_info()
        rbac_filters = get_rbac_filters(system_resources=system_agents, permitted_resources=list(agent_list))
        agents_with_data = WazuhDBQueryAgents(limit=None, select=["id", "status", "version"],
                                              **rbac_filters).run()['items']

        # Add non existent agents to failed_items
        not_found_agents = agent_list - system_agents
        [result.add_failed_item(id_=agent, error=WazuhResourceNotFound(1701)) for agent in not_found_agents]

        # Add non active agents to failed_items
        non_active_agents = [agent for agent in agents_with_data if agent['status'] != 'active']
        [result.add_failed_item(id_=agent['id'], error=WazuhError(1707, extra_message=f'{agent["status"]}'))
         for agent in non_active_agents]

        eligible_agents = [agent for agent in agents_with_data if agent not in non_active_agents] if non_active_agents \
            else agents_with_data
        # ---------------- TIME AFTER GETTING DATA FROM DB 0.04498767852783203
        
        
        # ---------------- RESTART ELIGIBLE AGENTS
        wq = WazuhQueue(common.ARQUEUE)
        for agent in eligible_agents:
            try:
                send_restart_command(agent['id'], agent['version'], wq)
                result.affected_items.append(agent['id'])
            except WazuhException as e:
                result.add_failed_item(id_=agent['id'], error=e)
        wq.close()

        result.total_affected_items = len(result.affected_items)
        result.affected_items.sort(key=int)
        # ---------------- TIME AFTER RESTARTING AGENTS 3.680727481842041

    return result
```

```
1st run:

TIME AFTER GETTING DATA FROM DB 0.04498767852783203
TIME AFTER RESTARTING AGENTS 3.680727481842041

2nd run:

TIME AFTER GETTING DATA FROM DB 0.04442286491394043
TIME AFTER RESTARTING AGENTS 3.664293050765991
```

After these new improvements, the times are now higher. It could be because we are iterating over a list of dictionaries. I have made another possible improvement to iterate over tuples instead of dicts. I have tested these with 50 agents and 1 worker in local, and it appears to be an improvement (*40 to see how much time would be consumed for 2k agents):

TIME AFTER GETTING DATA FROM DB 0.0019252300262451172 (* 40 = 0.08)
TIME AFTER LOOP 0.0273435115814209 (* 40 = 1.0938)

Testint these new improvements in the cluster performance pipeline...

**Comment by mcarmona99** [comment]
With the new changes mentioned in last comment, iterate over tuples instead of dicts, we haven't improved the endpoint:

```
3rd run:

TIME AFTER GETTING DATA FROM DB 0.050716400146484375
TIME AFTER LOOP 3.7241172790527344
```

The first measured block has higher times as we are spending more time to preprocess the data (transform it to list of tuples). The loop spends the same time it spent in last 2 runs.

Therefore, this run shows there are no improvements with the last changes, so I am going to take the changes commented here https://github.com/wazuh/wazuh/issues/8870#issuecomment-864833590. Despite the fact that times are still higher, this will scale more than the original solution.

Regards,
Manuel.
