### ISSUE TITLE
Problem installing Debian Wazuh agent

### ISSUE THREAD

**Issue by ponchov** [wazuh/wazuh#888]
## Description

Routes. Error. Cannot read property 'manager' of undefined
![image](https://user-images.githubusercontent.com/6090240/42235817-882dd6a6-7ebe-11e8-9b27-9fb73cf0ab2a.png)

The connections to the agents are active.
The agents in Kibana are in instances of Ubuntu.
With the latest version of wazuh, elasticsearch, filebeat 6.xx.

**Comment by havidarou** [comment]
Hi @ponchov ,

sorry you are having problems.

May I ask, is this a fresh installation or an update?

It seems some kind of problem with your Wazuh API entries.

Can you delete your API entry in settings and introduce it again to see if that solves the issue?

Regards.

**Comment by ponchov** [comment]
Hi @havidarou 
It was a service update.
The delete of the API did not work.
Regards.

**Comment by JuanjiJG** [comment]
Hello @ponchov,

We would like to know more information about your environment. Could you please share the output from the following commands (as root)?
```
cat /usr/share/kibana/package.json | grep "version"
cat package.json | grep -i -E "version|revision"
cat /etc/ossec-init.conf
```

Thanks for your patience.

Regards,
Juanjo

**Comment by ponchov** [comment]
Hi @JuanjiJG 

**1. cat /usr/share/kibana/package.json | grep "version"**
     
"version": "6.2.4",

**2. cat package.json | grep -i -E "version|revision" in /var/ossec/api**
  "version": "2.1.1"

**3. cat /etc/ossec-init.conf**
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v2.1.1"
REVISION="3485"
DATE="Tue Sep 19 12:03:54 UTC 2017"
TYPE="server"

Thanks for your help Juanjo

Regards.

**Comment by JuanjiJG** [comment]
Hello @ponchov,

You're using an incompatible version of the Wazuh app for Wazuh v2.1.1. If you want to use the Elastic Stack v.6.2.4, you need to upgrade to Wazuh v3.x. If you want to keep using Wazuh v2.x, you have to install the Elastic Stack v.5.6.5.

You can read more about this on our [compatibility guide](https://documentation.wazuh.com/current/installation-guide/compatibility_matrix/index.html#api-and-app).

I strongly recommend you to update to the latest version of Wazuh, which includes lots of new features and improvements. You can check our [upgrading guide](https://documentation.wazuh.com/current/installation-guide/upgrading/different_major.html), which will guide you through the process. In this case, you don't have to follow the step to add the new Elastic 6.x repository, since you're already using it.

Let me know if you need more help.

Regards,
Juanjo

**Comment by ponchov** [comment]
Hi @JuanjiJG 
Update version 3.x of wazuh-manager and wazuh-api without any problem.

But when updating wazuh-agent with apt and with dpkg I have the following error:

Errors were encountered while processing:
/var/cache/apt/archives/wazuh-agent_3.3.1-1_amd64.deb
E: Subprocess / usr / bin / dpkg returned an error code (1)

Regards.

**Comment by ponchov** [comment]
Hi @JuanjiJG , how are you?

Duplicate of #453.

**Comment by jesusgn90** [comment]
Hi @ponchov , 

Are you still in need of helping?

Regards,
Jesús

**Comment by jesusgn90** [comment]
Hi @ponchov ,

What are you meaning with "same mistakes"? Are you referring wazuh-agent, wazuh-manager, wazuh-api, wazuh-app? Please, let us know which component is causing troubles for your before continue helping you.

Regards,
Jesús

**Comment by teamcoworker** [comment]
I can not install the wazuh agent.
Errors were encountered while processing:
/var/cache/apt/archives/wazuh-agent_3.3.1-1_amd64.deb
E: Subprocess / usr / bin / dpkg returned an error code (1)

I have used apt and dpkg

**Comment by jesusgn90** [comment]
Hi @teamcoworker , what about cleaning the apt cache and trying to reinstall the package? 

```
# apt-get clean
# apt-get install --reinstall wazuh-agent=3.3.1-1
```

I hope it helps. Let us know.

Regards,
Jesús

**Comment by teamcoworker** [comment]
The problem was solved by eliminating it completely, including the wazuh-agent repository.

Then install it again as the documentation mentions.
https://documentation.wazuh.com/2.0/installation-guide/installing-wazuh-agent/wazuh_agent_deb.html

After installing the agents and configuring the api I got the following error.
I try the solution to ticket  #574 and it did not work.

https://github.com/wazuh/wazuh-kibana-app/issues/574

![image](https://user-images.githubusercontent.com/31854361/43483512-847964ca-94d1-11e8-996a-5904151b301a.png)

**Comment by ponchov** [comment]
To fix the error, delete Wazuh by counting the repository and then reinstalling
https://documentation.wazuh.com/2.0/installation-guide/installing-wazuh-agent/wazuh_agent_deb.html

After installing the agents and configuring the api I got the following error.
I try the solution to ticket # 574 and it did not work.

https://github.com/wazuh/wazuh-kibana-app/issues/574 

![image](https://user-images.githubusercontent.com/6090240/43484221-57639a12-94d3-11e8-83fb-17b262773273.png)

**Comment by JuanjiJG** [comment]
Hello @ponchov,

Please, keep in mind that you're reading an old version of the Wazuh Documentation. Please, head to this URL to get the latest installation information: https://documentation.wazuh.com/current/index.html

We've been trying to fix those `Cannot read property 'setBlankScr'` errors on the latest Wazuh app packages. I recommend you to upgrade your Elastic Stack to the latest version, along with the Wazuh app, to see if the error is finally fixed.

Read this guide to upgrade your Wazuh installation to the latest version (assuming that you're already using at least Wazuh 3.x): https://documentation.wazuh.com/current/installation-guide/upgrading/latest_wazuh3_minor.html#upgrading-latest-minor

Let us know if you still have more problems or questions.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
Hello @ponchov,

It's been more than a month since the last response to this issue, so I'll proceed to close it.

Don't hesitate to open a new one if you have problems or questions about Wazuh.

Regards,
Juanjo
