### ISSUE TITLE
ossec-execd reports errors after stopping

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#8880]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0-40205 | execd | Agent | Packages | Linux |

While performing upgrade tests, we found that sometimes execd reports an error while it is supposedly down.

```
15:19:46  2021/06/01 13:18:59 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
15:19:46  
15:19:46  2021/06/01 13:18:59 wazuh-modulesd:syscollector: INFO: Module finished.
15:19:46  
15:19:46  2021/06/01 13:18:59 ossec-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
15:19:46  
15:19:46  2021/06/01 13:18:59 ossec-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
15:19:46  
15:19:46  2021/06/01 13:19:00 ossec-agentd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
15:19:46  
15:19:46  2021/06/01 13:19:00 ossec-execd: INFO: (1314): Shutdown received. Deleting responses.
15:19:46  
15:19:46  2021/06/01 13:19:00 ossec-execd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
15:19:46  
15:19:46  2021/06/01 13:19:00 ossec-execd: ERROR: (1312): Error executing '/var/ossec/bin/ossec-control': No such file or directory
15:19:46  
15:19:46  2021/06/01 13:19:00 wazuh-execd: INFO: Started (pid: 1650).
```

**Comment by alromeros** [comment]
**#8880 update:**

Hi team,

After some research, we've gathered some information that hints that the behavior described in this issue is happening due to a non-expected simultaneity between the **restart** and **update** processes.

For testing purposes, we've been using a script like this one in order to reproduce the above-mentioned error:

```sh
rpm -i wazuh-agent-3.8.0-1.x86_64.rpm
sed -r -i 's|<address>.*</address>|<address>MANAGER_IP</address>|g' /var/ossec/etc/ossec.conf
sed -r -i 's|<protocol>.*</protocol>|<protocol>tcp</protocol>|g' /var/ossec/etc/ossec.conf
/var/ossec/bin/agent-auth -A agent_name -m MANAGER_IP

systemctl restart wazuh-agent

cat /var/ossec/logs/ossec.log | grep "Agent is restarting"
while [ $? -eq 1 ]
do
  cat /var/ossec/logs/ossec.log | grep "Agent is restarting"
done

rpm -U wazuh-agent-4.2.0-1.x86_64.rpm
````
After reproducing the case and analyzing for possible causes, we are able to determine the following facts:

- The **update process** should start whilst the agent is restarting in order to replicate the error.
- Due to the exact timing that is required for the error to happen, we have not been able to reproduce the error by upgrading the agent with sources.
- This error is not only affecting `ossec-execd` but also the rest of binaries that are restarted during the update process. Here, we can see an example when `Syscheckd` fails:

````
2021/06/08 11:16:47 ossec-syscheckd: CRITICAL: (2301): Definition not found for: 'syscheck.sleep'.
````
- The error is reproducible by updating from any previous version of Wazuh. We've tested updates from **3.8**, **3.13**, and **4.1**.
- The agent's **restarting** **process** is done through the **ossec-control** tool after receiving the shared configuration: If the **update** process starts while the agent is being restarted, said process starts to replace files without first ensuring that the agent is properly stopped. Then, the restarting process finishes in the middle of the update, so the old binaries (that have not been replaced yet) run again. 
- It's probably that this issue is related to https://github.com/wazuh/wazuh/issues/8263, since the root cause is the same. It was apparently fixed at https://github.com/wazuh/wazuh-packages/pull/751, however, it seems that the fix wasn't enough to stop the agent without checking its status. During the **restart** process, the stop action is not performed as expected.

**With this in mind, we've reached the following conclusions:**

As being said, this error is happening due to a lack of atomicity during the **restarting process** of the old service and the **updating process** of the new one. 

Our main goal is to get the package to ensure the agent is not restarting when the update process begins, stopping the agent during the preinstalling process, as expected. As we cannot modify the restart process for older versions, we should modify the update process itself.

On other hand, since **v4.2**, the **restart** process of the agent is done through the `Active Response` script, which creates a file called `.restart` that works as a semaphore that ensures the non-simultaneity of both processes.

Best regards,
Álvaro Romero.

**Comment by vikman90** [comment]
## Rationale

After researching with @alromeros, @chemamartinez, and @alberpilot, we concluded that there are two related issues:

1. If we upgrade during a restart (`systemctl restart wazuh-agent`), the package's preinstall assumes that the agent is stopped ([preinst](https://github.com/wazuh/wazuh-packages/blob/d77134014c28f021a696e8a02bfc2a7766a4abc0/debs/SPECS/4.2.0/wazuh-agent/debian/preinst#L22)). This causes the installer to upgrade the agent while it's running. This log reflects that problem:
```
ossec-syscheckd: CRITICAL: (2301): Definition not found for: 'syscheck.sleep'.
```
2. If we run the upgrade just before an auto-restart, the Execd's child process that will run `ossec-control restart` does not die with the agent stop by the preinstall. The child process has a 1-second delay before launching the restart. In that moment, `ossec-control` may have been replaced by `wazuh-control`, and that prints this error:
```
ossec-execd: ERROR: (1312): Error executing '/var/ossec/bin/ossec-control': No such file or directory
```
