### ISSUE TITLE
Vulnerability detector offline updates should insert data to the DB only if there is new CVE's information

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#8904]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| - | Vulnerability Detector | Manager | Packages/Sources | Any |

### Description

The vulnerability detector module can download the CVE's data from the official online repositories or from a local directory (offline update).

This offline update is described in the documentation and there is a script proposed for this procedure.
The whole download is carried out without checking the repository state, so the same information could be downloaded more than once. And every time the manager starts or the **update_interval** expires, the feed's DB is updated even if there is no new information.

**Comment by pereyra-m** [comment]
**Observation**

This behavior affects the implementation of the new CVEs alert's inventory #7749 because many FULL scans could be triggered caused by a recent fake feed update.
The integration tests developed in [1261](https://github.com/wazuh/wazuh-qa/issues/1261) showed this situation.

**Comment by palaciosjeremias** [comment]
During the implementation of this fix, it was identified that the scope of this problem is bigger and it also affects the **online custom feeds** and the **ArchLinux default feed**.
A new [issue ](https://github.com/wazuh/wazuh/issues/8949)was created to design a new mechanism able to cover all the scenarios.
