### ISSUE TITLE
How to set public IP to Wazuh Server?

### ISSUE THREAD

**Issue by javiviera8** [wazuh/wazuh#8942]
Hello, 

I installed Wazuh Server on one pc (Ubuntu 18.04)(All-in-one Deplyment method(Step-by-Step)), and I have other pc (Windows 10 PRO)(registering via cmd with agent-auth.exe). Version of Wazuh = 4.1.5.

I was wondering if I can change the Wazuh Server IP to a public IP, I mean, since 3.0.0 the configuration of ip address is deprecated. When I install all Wazuh with filebeat, EL and kibana, the result server for wazuh web is set to 0.0.0.0, but what if i want to change it to a public IP?  
My intention is if I have a Wazuh Server, one or two pc can connect to my server in the same network, and one or two can connect to my server that are out of my network. It is possible?

At the moment, Windows Agent is running and is connected to Wazuh Server, but is configure to connect to my private ip server (192.168.2.128), but i want this server be public if possible, to try to connect other pc out my network.

Thanks.

**Comment by pereyra-m** [comment]
Hi @javiviera8 !
Thanks for using Wazuh!

You can have agents connected to your manager within the same network and from outside of course. I'll try to explain a few things.
 
If your server is connected to a Local Area Network (LAN), then the local agents will be pointing to the local IP (**192.168.2.128** for example). At the same time, if your server has access to internet, the internet provider has assigned a public IP to your router because it belongs to a Wide Area Network (WAN). You should configure port forwarding to allow the incoming traffic to be redirected to your manager. By default, the agents are registered in the port **1515** and communicate the rest of the data through the port **1514**.  Also consider that the public IP may change.

Now, about the Kibana's IP: it is mentioned in [Customizing the installation](https://documentation.wazuh.com/4.1/installation-guide/open-distro/all-in-one-deployment/unattended-installation.html#customizing-the-installation) that 

```
The Kibana configuration found at the /etc/kibana/kibana.yml file has the server.host parameter set to 0.0.0.0. This means that Kibana can be accessed from the outside and accepts all the available IPs of the host. This value can be changed for a specific IP if needed.
```

Finally, related to the deprecated option, you can see in the [client](https://documentation.wazuh.com/4.1/user-manual/reference/ossec-conf/client.html#client) section that both **server-ip** and **server-hostname** have been merged in [address](https://documentation.wazuh.com/4.1/user-manual/reference/ossec-conf/client.html#address). So this is the option you really need.

I hope to have clarified some concepts, but please, write us again if you need.
Regards.

**Comment by javiviera8** [comment]
Hi Matias!

Thanks you for your quickly reply. You clarified me some isssues. Ok, I show what i want.

So, if i understood it is like this:

- 1 pc outside my network: 
   - I have to change the client section (address) to point my public IP of my router or maybe install agent via command on cmd or terminal and set the option -m public_IP, right?
   - On my router, I have to allow port 1515 & 1514 and redirect it to the server/manager IP.

And that's all?

Regards.

**Comment by javiviera8** [comment]
Hi @pereyra-m, 

I successfully installed Wazuh Agent taking public IP and allowing port forwarding (1515 & 1514), and it's running correctly.

Just another question. Do you know what is RAM Scrapping attack? Im preparing a tool to detect it, and I'm wondering if you know which would be the best tool/Ruleset on Wazuh that can give me some indications (system call process for example) if it exists on system.

Oh, and thanks you for help me for the Agents/Servers connections!!

Regards!

**Comment by pereyra-m** [comment]
Your welcome @javiviera8, so glad to hear it's working!

But if we want to keep the repository organized, it'd be a good idea to open a new issue with a different title and tag, because this problem is not related to a connection issue.
Then, we'll continue working in the new issue.

Thank you very much.
Regards.

**Comment by javiviera8** [comment]
Hi @pereyra-m, sorry for reopen the issue.

I'm trying now to change Kibana IP, with default settings (0.0.0.0/443), I'm able to connect from my other pc putting up on browser https://192.168.2.128 and works fine in to my own network, but when I try to change that IP for my public IP 188.XX.XX.XX, chosing 8080 port, i doesn't work. What is the correct configuration for that?

Thanks and regards!

**Comment by pereyra-m** [comment]
Hi again @javiviera8 ! 
No problem at all.

If you want to access the **8080** port from outside the network, you should make the same port forwarding you did for **1514** and **1515**. 

If you've already done this and it's still not working, could you please share your current configuration files?

Regards.

**Comment by javiviera8** [comment]
Hi @pereyra-m, 
I changed kibana.yml server.host to my public IP and port 8080. I make port forwarding and it doesn't work. I give you my kibana, elasticsearch and filebeat files configuration. I supose I miss something, but I tryed change many times and parameters of those files.
[kibana.txt](https://github.com/wazuh/wazuh/files/6662707/kibana.txt)
[elasticsearch.txt](https://github.com/wazuh/wazuh/files/6662708/elasticsearch.txt)
[filebeat.txt](https://github.com/wazuh/wazuh/files/6662709/filebeat.txt)

I give you a png of my port forwarding router. It's something weird, because if i put internal port 8080, always change the external port to a TCP or UDP port, so, it means that i have to connect through port 4402 to kibana with my public ip?
![Port-forwarding](https://user-images.githubusercontent.com/48414927/122213600-68eba280-cea9-11eb-80a4-02c249168267.PNG)

I'm very noob on Wazuh, sorry!!

Thanks a lot!

**Comment by MiguelazoDS** [comment]
Hi @javiviera8,

To access Kibana (wazuh_web) from outside your network it should be possible with **public_ip:4402**, according to your settings, and keeping the kibana.yml config with **server.host: 0.0.0.0**.  This way Kibana will be reachable from remote users.

If I'm not misunderstanding you tried that and it didn't work, I suggest you configure server.host as above.

Please let us know how it goes.

Best regards!

**Comment by javiviera8** [comment]
Hi @MiguelazoDS, 

Yes! It's working!! I don't know, I tried those configurations, but it can be I didn't use correct port. Now you can close this issue.

Thank you very much for your patience!

Best regards!

Javi.

**Comment by MiguelazoDS** [comment]
Glad to know that @javiviera8! Have a good day!
