### ISSUE TITLE
Vulnerability Detection not matching OS

### ISSUE THREAD

**Issue by mikykeane** [wazuh/wazuh#8967]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.5 | Vulnerability Detection | Manager | Cloud | OS version |

Hi team, 

We have observed an issue with the Vulnerability Detector. 

Basically, we could only see vulnerabilities from one Firefox package from one out of 4 agents (the rest had updated packages). 

All agents were distributions of Windows 10 Pro. I believe, they might be a bundled-up OS from Dell. Therefore not matching with the vulnerability database correctly. 

The information I could gather from the agents is the following: 

![image](https://user-images.githubusercontent.com/4438081/121706598-10e22400-cad6-11eb-8eca-618bd2f01e76.png)

![image](https://user-images.githubusercontent.com/4438081/121706067-91eceb80-cad5-11eb-9dfb-565aff9cc142.png)

![image](https://user-images.githubusercontent.com/4438081/121706138-a204cb00-cad5-11eb-963b-69e51f47eac6.png)

I could verify that Vulnerability analysis was taking place on all agents. I forced multiple analyses. Packages with a Vulnerability would show up on every scan. In this case, only an outdated Firefox would show up. But we could not see any vulnerabilities on the OS. 

Let me know if there is any information you would like me to add.

**Comment by MarcelKemp** [comment]
Hi @mikykeane,

After investigating the case, it appears to be a problem that we recently discovered. It is found in the new versions of Windows 10 and seems to be from build 19042.

To verify that this is the problem that I am going to mention below, you can run the following command in the _`API console`_ / _`dev tools`_: `GET /syscollector/<agent_id>/os`
And the `os_release` field must contain the value **'2009'**. 
If this is not the case, then I would need you to send me the patches that the agent contains together with the information of the command executed.

Since build 19042, they have added a new `DisplayVersion` field to the registries modifying the version that they show the user, which instead of being 2009, is currently the value of the new 20h2 field in this case (it seems that this same change affects all the new versions, since the most recent version contains the value 21h1). 
There is already an open issue for the collection of this new field: https://github.com/wazuh/wazuh/issues/8691

This field affects the vulnerability detector, because NVD CPEs now match version 20h2 instead of 2009, which is the field we currently collect.
- NVD '2009' (no matches found): [CPEs 2009](https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cpe%3A2.3%3Ao%3Amicrosoft%3Awindows_10%3A2009%3A*%3A*%3A*%3A*%3A*%3A*%3A*)
- NVD '20H2' (3 matches found): [CPEs 20H2](https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cpe%3A2.3%3Ao%3Amicrosoft%3Awindows_10%3A20h2%3A*%3A*%3A*%3A*%3A*%3A*%3A*)

After having carried out several tests in my environment, once we obtain the value of the new field, it would be necessary to make some modification in the vulnerability detector code to use that value and also to correctly match the CPEs collected in the database (it would be necessary to modify both the query and some tables in the DB).

**Comment by alromeros** [comment]
**#8967 update:**

Hi team,

Regarding the upcoming release of **Windows 11**, we consider it necessary to start working in giving support to said **OS**, in addition to the **Windows 10** versions mentioned in this issue.

We will update this issue as soon as we gather more related information.

Best regards

**Comment by chemamartinez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core---Kernel-Ponies-6039010607e005001a301509/issues/wazuh/wazuh/8967?planning-poker) with ZenHub @alromeros @MarcelKemp @juanmanuelug

**Comment by chemamartinez** [comment]
Done at #10168
