### ISSUE TITLE
FIM unable to send file changes

### ISSUE THREAD

**Issue by muddiwaller** [wazuh/wazuh#9011]
Hello,

I am trying to configure FIM for my Windows Endpoint.

I have configured a directory to monitor like C:\Users\frank.albert\Downloads to monitor in the configuration of Wazuh Agent.

like this :
<directories check_all="yes" realtime="yes">%Downloads%</directories>
%Downloads% is the environment variable.

However I am unable to get the file changes data on the wazuh's app.

Upon debugging the endpoint I saw the below message.

fim_db.c:150 at fim_db_clean(): DEBUG: (6340): Failed to delete FIM database 'queue/fim/db/fim.db'- 1º try.

Any suggesstions.

**Comment by Molter73** [comment]
Hi @muddiwaller,

My best bet here is that the `Downloads` environment variable is not expanding properly.

First things first, you could replace the environment variable with the path you want to monitor and restart the agent to discard whether FIM works correctly. Keep in mind that if you are not using `realtime` or `whodata` you will need to wait for the periodic scan to get an alert on any changes made on the directory.

If replacing the full path worked, then check the `Downloads` environment variable is set as a system variable, if you defined it for a specific user then Wazuh won't be able to see it.

Since you are looking at the log, you should be able to see some lines such as the following when the agent restarts:
```
2021/06/15 14:00:44 wazuh-agent: INFO: (6003): Monitoring path: 'c:\testdir\test1', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | realtime'.
2021/06/15 14:00:44 wazuh-agent: INFO: (6003): Monitoring path: 'c:\testdir\test2', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | realtime'.
2021/06/15 14:00:44 wazuh-agent: INFO: (6003): Monitoring path: 'c:\testdir\test3', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | realtime'.
```

If the environment variable is not expanding properly, then it will show up as `%Downloads%` in the log instead of `C:\Users\frank.albert\Downloads`

You can also use the `GET /agents/{agent_id}/config/syscheck/syscheck` API call to get the active configuration of the agent, again, if it show `%Downloads%` instead of the path, then it is not being properly expanded.

**Comment by Molter73** [comment]
I'm closing this issue due to a lack of activity, if you are still experiencing problems, feel free to reopen it.
