### ISSUE TITLE
Monitoring service stop or reboot with Wazuh

### ISSUE THREAD

**Issue by rejszynski** [wazuh/wazuh#9013]
Hi,

I am wondering if there is a way to monitor services stop/reboot with Wazuh?
I tried with syslog, mysql, but I did not get any alert about these events.
Thank you in advance.

**Comment by pereyra-m** [comment]
Hi @rejszynski !

Thanks for using Wazuh.
I'll make a little example, but you can tell me if this isn't what you need.

The [syscollector](https://documentation.wazuh.com/4.1/user-manual/capabilities/log-data-collection/index.html) module is in charge of reading the logs files. In Linux, we can find the following messages in **/var/log/auth.log** after a `sshd` restart

```
Jun 15 22:36:09 ubuntu-focal sshd[14671]: Received signal 15; terminating.
Jun 15 22:36:09 ubuntu-focal sshd[14897]: Server listening on 0.0.0.0 port 22.
Jun 15 22:36:09 ubuntu-focal sshd[14897]: Server listening on :: port 22.
```

Wazuh already monitors this file by default with this block in **ossec.conf**

```
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/auth.log</location>
  </localfile>
```

If we don't see any alert, we need to create a [custom](https://documentation.wazuh.com/4.1/user-manual/ruleset/custom.html) rule in **etc/rules/local_rules.xml**:

```
  <rule id="100001" level="5">
    <match>^Server listening</match>
    <program_name>sshd</program_name>
    <description>The services sshd has been restarted</description>
  </rule>
```

We know it's working because the **wazuh-logtest** tool shows the new alert for the desired logs:

![sshd_restart](https://user-images.githubusercontent.com/65046601/122134629-5fb0f600-ce15-11eb-8108-7115514bf10e.png)

This covers the whole process for the **sshd** service as an example.
Please, tell me if you need help with any of these steps.

Regards.

**Comment by rejszynski** [comment]
Hi Matias!
Thank you for a quick response.
I see that I have default rules for syslog restart:

```
<rule id="1005" level="5">
    <program_name>syslogd</program_name>
    <match>^restart</match>
    <description>Syslogd restarted.</description>
    <group>pci_dss_10.6.1,gpg13_10.1,gpg13_4.14,gdpr_IV_35.7.d,hipaa_164.312.b,nist_800_53_AU.6,tsc_CC7.2,tsc_CC7.3,</group>
  </rule>

  <rule id="1006" level="5">
    <regex>^syslogd \S+ restart</regex>
    <description>Syslogd restarted.</description>
    <group>pci_dss_10.6.1,gpg13_10.1,gpg13_4.14,gdpr_IV_35.7.d,hipaa_164.312.b,nist_800_53_AU.6,tsc_CC7.2,tsc_CC7.3,</group>
  </rule>

```
I restart syslog on my test ubuntu host, where agent is deployed and nothing about it is reported.
Agent is connected and sends events properly.
Could it be associated with issue that on ubuntu I have rsyslog deamon, not syslog?
The second thought is if agent requires auditd module to record such events?

**Comment by pereyra-m** [comment]
Hi again @rejszynski !

You don't need another module, the **rsyslog** daemon is not matching the existing **syslog** rule.

What I recommend to you in these cases, is to temporary turn on the [logall](https://documentation.wazuh.com/4.1/user-manual/reference/ossec-conf/global.html?highlight=logall#logall) option (don't forget to turn it off later because it will use too much disk space).

This way, you can examine all the logs Wazuh is analyzing, even if they didn't trigger an alert.
If I restart the service like this `sudo systemctl restart rsyslog`, I can find in **/var/ossec/logs/archives/archives.log** the following logs:

```
2021 Jun 16 18:43:55 ubuntu-focal->/var/log/syslog Jun 16 18:43:54 ubuntu-focal rsyslogd: [origin software="rsyslogd" swVersion="8.2001.0" x-pid="3195" x-info="https://www.rsyslog.com"] start
...
2021 Jun 16 18:43:55 ubuntu-focal->/var/log/syslog Jun 16 18:43:54 ubuntu-focal systemd[1]: Stopping System Logging Service...
2021 Jun 16 18:43:55 ubuntu-focal->/var/log/syslog Jun 16 18:43:54 ubuntu-focal systemd[1]: Starting System Logging Service...
2021 Jun 16 18:43:55 ubuntu-focal->/var/log/syslog Jun 16 18:43:54 ubuntu-focal systemd[1]: Started System Logging Service.

```

So if we are looking for a specific rule for **rsyslogd**, we can create this rule:

```
  <rule id="100002" level="5">
    <match>start</match>
    <program_name>rsyslogd</program_name>
    <description>The service rsyslogd has been restarted</description>
  </rule
```

Here you have the `wazuh-logtest` result

![rsyslog_restart](https://user-images.githubusercontent.com/65046601/122276450-2cc13d80-cebb-11eb-872c-bcdc88d496ad.png)

But you can also have a child rule for **systemd** when a service is restarted. This would be more generic:

```
  <rule id="100003" level="5">
    <if_sid>40700</if_sid>
    <match>Starting</match>
    <description>A service has been restarted</description>
  </rule>
```

![systemd_restart](https://user-images.githubusercontent.com/65046601/122286043-d279aa00-cec5-11eb-82cd-a2a87a4ae999.png)

I hope this to be useful for you.
Regards.

**Comment by rejszynski** [comment]
Hi again @pereyra-m !

That did the trick. Thank you very much for your help!

**Comment by rejszynski** [comment]
My bad. I did changes on all nodes and it works fine now.
Thank you very much for your support @pereyra-m !

**Comment by pereyra-m** [comment]
Great news @rejszynski ! Thanks to you!

**Comment by pereyra-m** [comment]
Great news @rejszynski ! Thanks to you!

Note that **archives.log** will store all the events (those that trigger an alert, and those that didn't) only if you enable the `logall` option. So now that you turned it off, you'll only find the alerts in **alerts.log** and the rest of the events will be discarded.

I'm closing this issue, but feel free to contact us again anytime you need.
Have a nice day.

Regards.
