### ISSUE TITLE
Add parameter that allows to modify the maximum API upload size

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#9054]
Hi team,

After the research done on the issue: https://github.com/wazuh/wazuh/issues/8876. We need to add a new parameter to the API that allows us to modify the maximum file upload size.

Currently, the API has a limit of 1MB when uploading any type of data. When we try to upload something that exceeds this size, we get the following error:

```
{
  "title": "Request Entity Too Large",
  "detail": "Maximum request body size 1048576 exceeded, actual body size XXX"
}
```

Where XXX is the size of what we want to upload. Therefore the objective of this issue is to add a new parameter to modify the maximum allowed value.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Selutario** [comment]
## Issue update

Hi team,

I am investigating how to set the maximum size that the API supports when receiving information. In theory, this can be set using the `client_max_size` parameter of the `web.Application()` class as showed in its documentation: https://docs.aiohttp.org/en/stable/web_reference.html#application

However, we do not create such an object since we use Zalando's `Connexion` library, which manages this. I have found this issue that talks about it: https://github.com/zalando/connexion/issues/1035. 

However, although now the `**options` are passed to the AioHTTP app, it doesn't seem to work since the app doesn't support the `client_max_size` parameter:
```Python
web.run_app(self.app, port=self.port, host=self.host, access_log=access_log, **options) 
```
```Python
def run_app(
    app: Union[Application, Awaitable[Application]],
    *,
    host: Optional[Union[str, HostSequence]] = None,
    port: Optional[int] = None,
    path: Optional[str] = None,
    sock: Optional[socket.socket] = None,
    shutdown_timeout: float = 60.0,
    ssl_context: Optional[SSLContext] = None,
    print: Callable[..., None] = print,
    backlog: int = 128,
    access_log_class: Type[AbstractAccessLogger] = AccessLogger,
    access_log_format: str = AccessLogger.LOG_FORMAT,
    access_log: Optional[logging.Logger] = access_logger,
    handle_signals: bool = True,
    reuse_address: Optional[bool] = None,
    reuse_port: Optional[bool] = None,
) -> None:
```

I will continue investigating.

Best regards,
Selu.
