### ISSUE TITLE
Error. 3013 - Invalid 'wazuh-app-version' header after upgrade

### ISSUE THREAD

**Issue by frayber** [wazuh/wazuh#909]
Hi, I've just upgraded from 3.2.4 to 3.3.1 on a centos 7 system with yum upgrade, now I got this error:

Manager. Error. 3013 - Invalid 'wazuh-app-version' header. Expected version '3.3.x', and found '3.2.x'.

the package info reports this data:

> Name        : wazuh-manager
> Arch        : i386
> Version     : 3.3.1

> Name        : wazuh-api
> Arch        : x86_64
> Version     : 3.3.1

 /etc/ossec-init.conf 

> VERSION="v3.3.1"

what else should I check?
Thanks

**Comment by jesusgn90** [comment]
Hello @frayber ,

Since the Wazuh App is compatible with a patch version of the Wazuh API you must install a newer version of the Wazuh App. Please execute the next commands where Kibana is installed:

```
systemctl stop kibana
/usr/share/kibana/bin/kibana-plugin remove wazuh
rm -rf /usr/share/kibana/optimize/bundles
/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.3.1_6.3.0.zip
systemctl start kibana
```

What we are doing is to upgrade your Wazuh App to a compatible version. Hope it helps.

Regards,
Jesús

**Comment by frayber** [comment]
Solved, I forgot this step.
Thank you very much.

**Comment by jesusgn90** [comment]
You are welcome!

**Comment by lukelee1987** [comment]
By doing this, will it remove all the existing agents ?
