### ISSUE TITLE
Re-process logfiles

### ISSUE THREAD

**Issue by salyh** [wazuh/wazuh#91]
Is there a possibility to force an agent to re-send logfiles and let the master re-process them an create alerts for this again?

**Comment by vikman90** [comment]
Hi @salyh,

unfortunately there is no such option at this moment, since every time that an agent starts it opens every file and places the "cursor" at the end of each one. Only new lines are sent.

However you could make a workaround to force logs to be read: simply let the agent think that the file was rotated by erasing the content.

For example, we can re-send the complete file _/var/log/syslog_ by creating a backup and erasing the content.

> cp /var/log/syslog /var/log/syslog.temp
> echo -n > /var/log/syslog

At this point we wait for this alert (rule 592) at file _/var/ossec/logs/alerts.log_ (it takes about a minute to detect this change):

> ** Alert 1489863108.167: - ossec,attacks,pci_dss_10.5.2,pci_dss_11.4,
> 2017 Mar 18 11:51:48 ubuntu->ossec-logcollector
> Rule: 592 (level 8) -> 'Log file size reduced.'
> ossec: File size reduced (inode remained): '/var/log/syslog'.

And now the we write the data back into the original syslog file:

> cat /var/log/syslog.temp >> /var/log/syslog
> rm /var/log/syslog.temp

This will make the entire log to be sent to the manager. You should be able to read the corresponding alerts.

Hope it help.

Best regards.
