### ISSUE TITLE
wazuh-remoted: WARNING: Too big message size from 192.168.0.55 [14].

### ISSUE THREAD

**Issue by mashaobu** [wazuh/wazuh#9138]
|Wazuh 4.3.0|wazuh-remoted|server|Sources|centos7|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

why can receive TooBig message? how to resolv it?

**Comment by jnasselle** [comment]
Hi @mashaobu ,

This might be caused because:

- In case that IP is from an agent: agent is generating messages bigger than 64KB or agent (with little endian architecture) was compiled from sources without BIG_ENDIAN flag.
- In case that IP is from a syslog device: syslog device pointing to 1514 rather than 514 port

Please let me know if this helps.

Regards,
Nico

**Comment by mashaobu** [comment]
Thanks very much!

I use X86 platform in vmware, use wazuh's MAKE method. without use any XXX_ENDIAN flag.
the wazuh server and wazuh agent are my self virtual linux. it is not impossible other device's syslog information
