### ISSUE TITLE
SUSE support: Design how to solve dependencies for the OVAL scan

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#9153]
### Description

The goal of this issue is to decide the design to implement the described at #9091.

Before starting to develop a solution, we need to look for the solution that best fits our needs in all of the following stages:

- **OVAL parsing**

Currently, the parser for the OVAL is located at [`wm_vuldet_oval_xml_parser()`](https://github.com/wazuh/wazuh/blob/a3d2d1ac101775000fa6ac0af0690e9ccec1abba/src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c#L3204) which is a very tricky method customized for every OVAL that Vulnerability Detector parses.

We have to include this new feature to parse the criteria operators without affecting the parsing of the rest of the OVALs.

- **DB schema and insertion**

For now, the OVAL vulnerabilities had no dependencies so the table `VULNERABILITIES` was enough to store all the criteria to match packages and detect vulnerabilities. Now, packages stored in that table have to be related to other dependencies so the vulnerability database should be adapted to support this change.

- **OVAL scan**

In this stage, we have to take into account the new dependencies added to the database when evaluating SUSE packages. The first approach is to create a pre-scan where dependencies are evaluated and stored, avoiding the correlation for every scanned package in the standard scan so making it more efficient.

**Comment by juanmanuelug** [comment]
### Issue #9153 -> OVAL parsing update:
Hi team,

After some research and, as the first approach, we consider the workflow described by this chart to be the more reliable in regards to the modification of the wm_vuldet_oval_xml_parser() function.

![opcion2ActivityDiagram](https://user-images.githubusercontent.com/74183704/124279447-cf2e2180-db47-11eb-887d-4820b7d4fa20.jpg)

**Comment by alromeros** [comment]
**#9153 Update:**
## Oval feed distribution and package-dependency relation:

In order to properly develop the dependency detection mechanism in the **OVAL** parser, we have been researching the features and peculiarities of **SUSE** feeds, specifically, the `criteria` and `criterion` sections:

```xml
<definition id="oval:org.opensuse.security:def:20022443" version="1" class="vulnerability">
	...
        <criteria operator="AND">
            <criteria operator="OR">
                <criterion test_ref="oval:org.opensuse.security:tst:2009073771" comment="SUSE Linux Enterprise Desktop 11 SP2 is installed"/>
                <criterion test_ref="oval:org.opensuse.security:tst:2009077540" comment="SUSE Linux Enterprise Desktop 11 SP3 is installed"/>
                <criterion test_ref="oval:org.opensuse.security:tst:2009117401" comment="SUSE Linux Enterprise Desktop 11 SP4 is installed"/>
            </criteria>
                <criterion test_ref="oval:org.opensuse.security:tst:2009334270" comment="ghostscript-library is not affected"/>
        </criteria>
</definition>
````

**We have drawn two main conclusions from these sections:**

- The order in which the **OR** and **AND** operators are distributed is predictable for all cases, and follows the following logic:
```xml
<criteria operator="OR">     <!-- Optional -->
    <criteria operator="AND">
         <criteria operator="OR">  <!-- Optional -->
````
Being the **AND** section the one containing all the relevant information between dependencies and packages.

- Inside each **AND** section, the first group of `<criterion ...>` always contains the dependencies, while the second one always contains the packages.

With that being said, we have considered two main approaches when relating each list of dependencies and packages.

## OVAL parsing options

### Option 1: To save and parse each `<criteria operator="AND">` independently.
This option would imply assigning a list of **AND** structures to each **CVE**, which would later be parsed and related to the packages. This option has the advantage of being more maintainable and independent of the information provided in the feeds: The order in which the information is presented in these feeds is not part of any **OVAL** language standard, so relying on it can be risky.

However, it has the disadvantage of being less intuitive and more expensive performance-wise. It would also require a bigger rework in the **OVAL** parser.

This option would require:
1. Creating a linked list of structures within `info_cve`, where the information extracted from each **AND** section would be stored for each **CVE**.
2. Extracting this information in a new section within the **OVAL** parser.
3. Correlating the extracted data with the packages.

### Option 2: Take advantage of package parsing to map dependencies.

This option has the disadvantage of depending on the order in which the information is presented in the **SUSE** feeds. This order is not standardized, so it could be subject to change in the future. However, it has been maintained in all **SUSE** feeds regardless of the operating system, so relying on it shouldn't be unconsidered.

It is, however, much more efficient, readable, and easy to implement, requiring:

1. To save the dependencies in a linked list of structures when the parser is in charge of fetching the packages. In **vulnerability detector**'s source code, there is already an option to detect **SUSE** dependencies:

https://github.com/wazuh/wazuh/blob/308952daa3b18da711c2b965c1a368dcdb77354d/src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c#L3704-L3716

2. After saving this list of dependencies, it would be enough to assign it to each one of the packages that are extracted afterward. The diagram provided in the [message above](https://github.com/wazuh/wazuh/issues/9153#issuecomment-872987871) explains this flow more visually.

This option can always be enhanced with more error handling, so, in case the order of the feed changes, the dependencies could still be assigned appropriately.

### Conclusions
After comparing the advantages of one option with the other, **we have decided to start working on the second option** and, if necessary, enhance the implementation with more error handling, in case we end up considering it problematic to rely on a non-standardized feed order.

**Comment by MarcelKemp** [comment]
## DB schema and insertion

For the insertion of packages and dependencies in the database, we have observed that most of the dependencies are repeated, so we have considered dividing these dependencies in another table and relating them to the packages they affect.

Said _DEPENDENCIES_ table will contain the following columns:
- _ID_: Primary key.
- _Name_: Name of the dependency.
- _Operation_: Operator used to compare the version.
- _Operation_value_: Version of the dependency.
- _Available_: This is a flag that will be activated in the pre-scan as long as this dependency has been detected in the agent.

In addition, in the _VULNERABILITIES_ table it is necessary to add an additional column to be able to connect it with the related dependencies.

To try to avoid repeating the rows of each table, we have considered the following options:

### First option:
Create an One-to-Many (1:M) table schema. So we have the Vulnerabilities table that contains all the dependency ids in an array, so that they are related through that field.

![Screenshot from 2021-07-05 15-31-41](https://user-images.githubusercontent.com/37207742/124483424-9d68c500-ddaa-11eb-8b5b-ea7a93c4e563.png)

### Second option:
Create a Many-to-Many (M:M) table schema. With this option we avoid that a field is too long and we can also easily check both dependencies and vulnerable packages.

![Screenshot from 2021-07-05 15-31-15](https://user-images.githubusercontent.com/37207742/124483462-a8bbf080-ddaa-11eb-804e-e1b624cec55e.png)

As we can see, a join table is considered that contains the relationships between the vulnerable packages and the dependencies of each package.

To try to optimize the entries in this table, we have considered that the relationship of the vulnerable packages will be connected by means of an id given by each AND, since within a feed all the packages that are within that AND contain the same dependencies (for this reason, the column `deps_ID` thought in the first option is replaced by the name `and_ID`).

If it was not possible, then it would be related by an id given by each vulnerable package.

### Final decision: 
As we can see, the second option is almost a correction of the first, since 1 vulnerability has many dependencies and vice versa, so we are talking about a M:M scheme. That is why it is the option that we are going to implement in development.

In this way we would have the following table schema in the DB (new and modified tables):

![Screenshot from 2021-07-05 15-31-56](https://user-images.githubusercontent.com/37207742/124483780-018b8900-ddab-11eb-8980-6896fee8bec7.png)

**Comment by chemamartinez** [comment]
GJ @alromeros, @juanmanuelug, and @MarcelKemp!
