### ISSUE TITLE
Log compression works only for the first log of the day

### ISSUE THREAD

**Issue by ElGullo** [wazuh/wazuh#9159]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.5/master branch |monitord | Manager | Packages/Sources | Linux|

We (me and @veshialle) noticed a bug in alerts logs compression when log rotation produces more than one log per day.

Only the first file (ossec-alerts-dd.json) gets compressed, the others (ossec-alerts-dd-xxx.json) are ignored.

This is due to a bug inside monitord/manage_files.c
After every compression, the function checks if the current uncompressed file exists, and if so tries to compress the next one.
BUT the compression functions deletes the uncompressed file after it's done.
So only the first log file is ever compressed.

We already have a fix for this and I will post a PR soon :)

**Comment by vikman90** [comment]
Hi @ElGullo,

I think this problem is related to a comment on #2290, which is part of #3072, and it's fixed by commit 3f6b1795941aa88241cfb98e78147763a3d8c42f (PR #3175).

Unfortunately, we've moved that issue to the icebox due to conflicts and a lack of integrated tests. I hope we can get back to work on this soon.

Best regards.
