### ISSUE TITLE
macOS System Inventory Issue

### ISSUE THREAD

**Issue by a108a108** [wazuh/wazuh#9177]
|version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.5 | Syscollector| Agent | Packages | macOS 11.4 |

Hello,
I am having an ussie with software detection on macOS, basically when an app is not installed in the default directories /System/Library/CoreServices/, /Applications, /System/Applications/, but rather in a sub directory it's not detected in System Inventory -> Packages and I guess by extension not checked by the vulnerability scanner.

Example:
"/Applications/Adobe Photoshop 2021/Adobe Photoshop 2021.app"

Can I set from somewhere where to look for it ? Any quick fix ?

**Comment by MarcelKemp** [comment]
Hi @a108a108,

Currently the app is collected from the following list of paths:
- `/Applications`
- `/Applications/Utilities`
- `/System/Applications`
- `/System/Applications/Utilities`
- `/System/Library/CoreServices`

And as you say, if the app is inside a subdirectory, syscollector does not detect it, which implies that since it does not have the information of the app, it cannot be verified by vulnerability detector.

In the code, you can find it in the following file (v4.1.5):
https://github.com/wazuh/wazuh/blob/c9b0b1d73b3884cacf4c20a24489c7bcfae06d63/src/wazuh_modules/syscollector/syscollector_bsd.c#L69


The workaround to solve it easily would be to move the `.app` that is not detected to one of the paths mentioned above. So syscollector will detect the app and the info will be collected.

We will take this problem into account, that as a first option to solve it we could perform a recursive search in these paths to find apps that are in the subdirectories and thus be able to extract their information.

Sorry for the inconvenience.

If you have any other questions, do not hesitate to ask.

**Comment by a108a108** [comment]
Hi @MarcelKemp 
Thank you for the answer, I will try moving the apps.
