### ISSUE TITLE
Feature request: Direct integration with GITLAB API

### ISSUE THREAD

**Issue by gitup66** [wazuh/wazuh#9218]
Direct GITLAB integration would be nice, like the JIRA integration. 

Creating incidents/issues directly from Wazuh Alerts to GITLAB as issue on a specific project.

GITLAB Issue API:  [https://docs.gitlab.com/ee/api/issues.html](https://docs.gitlab.com/ee/api/issues.html)
Python-gitlab: [https://github.com/python-gitlab/python-gitlab](https://github.com/python-gitlab/python-gitlab)

What at least needs to be included in the payload:

project_id
issue_type
description
....

Thank you.

**Comment by antoniomanuelfr** [comment]
Hi @gitup66 

Wazuh provides a module called `integrator`  that allows the user to create custom integrations. This module will receive the alerts and will send those alerts to a custom script. You can use this module to achieve this integration. In this [blogpost](https://wazuh.com/blog/how-to-integrate-external-software-using-integrator/) you can find an example that uses a Python script to integrate Wazuh and Jira.

My recommendation is to develop the python script until it works (without the integration with wazuh) and once the script is working, adapt the script with the necessary changes in order to make it work with integrator. 

Another tip, you can enable the debug mode of integratord by adding the following line to the file `/var/ossec/etc/local_internal_options` 
```
integratord.debug=2
``` 
https://wazuh.com/blog/how-to-integrate-external-software-using-integrator/

I hope this information is useful and don't hesitate to contact us if you have any problems

**Comment by antoniomanuelfr** [comment]
Closing this issue due to innactivity.
