### ISSUE TITLE
Review all framework cached functions calls

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#9234]
|Wazuh version|Component|
|---|---|
| 4.3.0 | Framework |

Hello team,

During the API profiling issues we noticed that calling a cached function to compare its value without previously saving it would not apply cache.

For instance, having the following cached function:

```python
@context_cached('cached_var')
def func():
  pass
```

If we used it like this, cache would not be applied (keeping in mind that we called `func()` before entering the loop):

```python
for i in range(100):
  return i in func()
```

To correctly apply cache we would have to save its value beforehand like this:

```python
cached_value = func()
for i in range(100):
  return i in cached_value
```

A fixed example is the following:

https://github.com/wazuh/wazuh/blob/79e4860309b6483e51223995b0a2ffb772ce35f1/framework/wazuh/agent.py#L152-L157

We need to check if this occurs in the framework to fix it, as it has a big impact in performance.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/test/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Víctor

**Comment by noise-kngdm** [comment]
### Issue update
Hello team,
before applying the suggested workaround, I decided to try to discover beforehand the root of the problem, so I could fix it in a more proper way if possible.
The cache is indeed working fine, the efficiency problem stems from the way the `context_cached` decorator works. `context_cached` will return a deep copy of the return value of the requested method, which works fine for small objects, but for a large one, it's a very time-consuming task.

Because of this, I'll apply the suggested fix since it will tackle this issue in a convenient way.

Regards,
Gonzalo.
