### ISSUE TITLE
error with wazuh agent in container that run on GCP Cloud run

### ISSUE THREAD

**Issue by spinbitnow** [wazuh/wazuh#9272]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.5-1 | Wazuh component | Agent | RPM | RH UBI STD 8 |

someone have experience with wazuh agent in container that run on GCP Cloud Run ?
I got error Container Sandbox: Unsupported syscall setsockopt(0x9,0x1,0x21,0x3e5e0bff1d00,0x4,0x4) when the container executed

**Comment by vikman90** [comment]
Hi @spinbitnow,

This error is familiar to me, we had a similar issue when trying to run the manager on Docker using gVisor: #6439.

In fact, GCP Cloud Run uses gVisor ([Container runtime contract](https://cloud.google.com/run/docs/reference/container-contract)):
> The Cloud Run container instances are sandboxed using the [gVisor](https://gvisor.dev/) container runtime sandbox. As documented in the [syscall compatibility reference](https://gvisor.dev/docs/user_guide/compatibility/linux/amd64/), some system calls might not be supported by this container sandbox.

As we find in the syscall compatibility reference, `setsockopt` and `getsockopt` are **partially supported**, and I guess that is producing the error you're reporting.

On the other hand,
```c
setsockopt(0x9,0x1,0x21,0x3e5e0bff1d00,0x4,0x4)
```

That performs an operation on socket 9, level 1, option 3 (`0x21`). That corresponds to `SO_RCVBUFFORCE` ([socket.h](https://github.com/torvalds/linux/blob/7fef2edf7cc753b51f7ccc74993971b0a9c81eca/include/uapi/asm-generic/socket.h#L20)), but the agent does not use that option, at least directly. I found only one reference in the Audit library ([sockoptnametab.h](https://github.com/linux-audit/audit-userspace/blob/16e9558cd389d64589bbedd5bdf891cca7be6116/auparse/sockoptnametab.h#L57)), but that is a table.

We applied a fix to prevent the manager from exiting when `getsockopt` fails due to an unimplemented call (#6444).

I'm not familiar with CGP Cloud Run. Where did you find that error? Did the agent print any error or warning in _ossec.log_? If it did, maybe you can enable debug logging so that the agent will print the line that produced the error.

Best regards.

**Comment by spinbitnow** [comment]
Hi @vikman90 

I found that error from Cloud Run log,
which debug that I need to enable ( become level 2) ? 
as far I know there is around 10 debug logging that need to enable ( https://documentation.wazuh.com/current/user-manual/reference/internal-options.html )

**Comment by vikman90** [comment]
Hi @spinbitnow,

Enabling debug is only helpful if the agent is printing any error like this in _ossec.log_:
```

**Comment by spinbitnow** [comment]
there is error in ossec.log :
ossec-agentd: ERROR: ( 4104 ): Invalid hostname: 'localhost'.
do you think good idea to set debug level 2 ( agent.debug ) ?

**Comment by vikman90** [comment]
I think we don't need that. I'm pretty sure it comes from [enrollment_op.c](https://github.com/wazuh/wazuh/blob/c9b0b1d73b3884cacf4c20a24489c7bcfae06d63/src/shared/enrollment_op.c#L158-L159).

I think there are two reasons that may produce that error:
1. We defined a server address containing a slash.
2. The agent is trying to get its hostname to enroll to the manager, but it's `localhost` (not allowed).

The agent does not allow `localhost` as hostname because the name of the agent must be unique. To fix this, define an agent name manually through option `<agent_name>`:

```xml
<client>
  <enrollment>
    <agent_name>agent</agent_name>
  </enrollment>
</client>
```

More info at the [enrollment reference](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#enrollment).

Best regards.

**Comment by spinbitnow** [comment]
Hi @vikman90 

I try that way, there is progress for the implementation, now it can register to manager, but looks like after first connection, it never connect again. anything missing here ? same configuration I try in another environment it will reconnect after 1-2 mins

**Comment by vikman90** [comment]
Hi @spinbitnow,

The agent is expected to try to connect again and again until it's able to establish a connection. If you tried the same configuration in two agents but only one of them works, I wonder if you could share with us your configuration and the logs from both agents so we can analyze the differences.

Just to rule out, we need to define different values for `<agent_name>` in each agent, because the name of the agent must be unique. Otherwise, each one will cause the manager to delete the other agent. In this scenario, the logs from `ossec-authd` in the manager's _ossec.log_ is very helpful.

Best regards.

**Comment by spinbitnow** [comment]
Hi @vikman90,

I turn on one container in GKE ( with Wazuh agent inside ) --> this is successful running and connected, its got some host name with random number ( I believe its random name from container host name when we deploy container in Kubernetes )

I turn on one container in Cloud Run ( with Wazuh agent inside ) --> this one that have problem, last time cannot connect and we fix it with additional <agent_name>, now can register and connect, but looks like after first connection, it never connect again.

here is the link for configuration : https://github.com/spinbitnow/wazuh/blob/master/wazuh-all/wazuh-agent-rh-ubi-std/ossec.conf

let me know if you still need some logs

**Comment by vikman90** [comment]
Hi @spinbitnow,

The configuration seems right. I wonder if multiple agents are trying to enroll with the same name, which would cause other agents to be removed. 

We would see many enrollments and connection attempts in the agent's _ossec.log_ if that occurs. On the other hand, the manager's log would show some warnings by Remoted about invalid connections. In addition, Authd would report duplicate agent additions.

If you are experiencing duplicate agent enrollments, I suggest you to apply two changes:

1. Make sure to set a different `<agent_name>` value in agents which cannot get a unique hostname.
2. Set up a time margin in `<auth>`([ossec.conf](https://github.com/spinbitnow/wazuh/blob/2a39cdd11d1f6add8fd9029723754d4913c6c4b2/wazuh-all/wazuh-kubernetes/wazuh/wazuh_managers/wazuh_conf/master.conf#L328)) (such as 600 seconds). That prevents Authd from removing duplicate agents if they are connected.

Hope this helps you.

Best regards.
