### ISSUE TITLE
archives.log is empty

### ISSUE THREAD

**Issue by agentsofshield** [wazuh/wazuh#928]
Hello, I understood that the manager is saving every log that is sent to him by the agents inside the file archives.log or archives.json. 
I'm currently monitoring Windows logs with the Windows agent.
I have an archives.log file inside /var/ossec/logs/archives but it is empty, also every ossec-archive-xx.log.gz is empty. I couldn't find the problem online or what configuration handles the archives files. 
The alerts.json and alerts.log are fine though.
Do you know what stops the manager from saving the windows logs?
Thanks in advance!

**Comment by chemamartinez** [comment]
Hi @agentsofshield,

Did you enable the option `logall` and `logall_json` in the manager configuration? They are the options to store every event from agents and is disabled by default due to disk space reasons.

Here you have the documentation section about the above options:

https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#logall

After enabling them, remember to restart the manager service to apply the changes.

Regards,
Chema.

**Comment by agentsofshield** [comment]
How did I miss it?? Thank you very much!
