### ISSUE TITLE
Review current SSL/TLS Encryption enabled

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#9328]
Hi team,

In this issue, we are looking to check the version of the SSL/TLS protocol used by Wazuh. We need to know which version is currently being used and which ones are compatible with the API.

As an informative note, the version we should have is TLS 1.1 onwards, although TLS 1.1 is being deprecated by some browsers so in our case, we should use TLS 1.2 onwards. TLS 1.0 and SSL 3.0 are not recommended for production use.

More information here:https://www.ssl.com/guide/ssl-best-practices/#:~:text=While%20TLS%201.2%20is%20currently,encryption%2C%20or%20stronger%20when%20possible

**Comment by noise-kngdm** [comment]
## Issue update
Hi team,

after a little investigation I came across the following conclusions. By default `apid` will use TLSv1.2, as can be seen in the following lines https://github.com/wazuh/wazuh/blob/15dbea626f0d19f5ed56041b11495a36fd4b84d2/api/api/configuration.py#L39-L47

Using the tool `sslscan` shows that the only protocol available right now is TLSv1.2:
```
Version: 2.0.10
OpenSSL 1.1.1k  25 Mar 2021

Connected to ::1

Testing SSL server localhost on port 55000 using SNI name localhost

  SSL/TLS Protocols:
SSLv2     disabled
SSLv3     disabled
TLSv1.0   disabled
TLSv1.1   disabled
TLSv1.2   enabled
TLSv1.3   disabled

  TLS Fallback SCSV:
Server supports TLS Fallback SCSV

  TLS renegotiation:
Session renegotiation not supported

  TLS Compression:
OpenSSL version does not support compression
Rebuild with zlib1g-dev package for zlib support

  Heartbleed:
TLSv1.2 not vulnerable to heartbleed

  Supported Server Cipher(s):
Preferred TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve 25519 DHE 253
Accepted  TLSv1.2  256 bits  ECDHE-RSA-CHACHA20-POLY1305   Curve 25519 DHE 253
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-GCM-SHA256   Curve 25519 DHE 253
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA384       Curve 25519 DHE 253
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-SHA256       Curve 25519 DHE 253
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA          Curve 25519 DHE 253
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-SHA          Curve 25519 DHE 253
Accepted  TLSv1.2  256 bits  AES256-GCM-SHA384            
Accepted  TLSv1.2  128 bits  AES128-GCM-SHA256            
Accepted  TLSv1.2  256 bits  AES256-SHA256                
Accepted  TLSv1.2  128 bits  AES128-SHA256                
Accepted  TLSv1.2  256 bits  AES256-SHA                   
Accepted  TLSv1.2  128 bits  AES128-SHA                   

  Server Key Exchange Group(s):
TLSv1.2  128 bits  secp256r1 (NIST P-256)
TLSv1.2  192 bits  secp384r1 (NIST P-384)
TLSv1.2  260 bits  secp521r1 (NIST P-521)
TLSv1.2  128 bits  x25519
TLSv1.2  224 bits  x448

  SSL Certificate:
Signature Algorithm: sha256WithRSAEncryption
RSA Key Strength:    2048

Subject:  wazuh.com
Altnames: DNS:localhost
Issuer:   wazuh.com

Not valid before: Jul 29 08:13:27 2021 GMT
Not valid after:  Jul 29 08:13:27 2022 GMT

```

Even thought there is already a [new version of the TLS protocol](https://datatracker.ietf.org/doc/html/rfc8446), there's no problem with using TLSv1.2 when taking into consideration the main problem it has: that it allows to use *insecure* or *legacy* cipher algorithms. This issue is not currently being tackled, and if the client requires to use a weak algorithm such as 'ECDHE-RSA-AES256-SHA384' (more info on that algorithm [here](https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384/)), the api daemon will have no problem in accepting it. Part of the output of `openssl s_client -cipher 'ECDHE-RSA-AES256-SHA384' -connect localhost:55000 -tls1_2` is the following:
```
CONNECTED(00000003)
....
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-SHA384
....
```

It's also worth mentioning that right now TLSv1.0 and TLSv1.1 are part of the api daemon allowed protocols, like the code snippet below states. https://github.com/wazuh/wazuh/blob/15dbea626f0d19f5ed56041b11495a36fd4b84d2/api/scripts/wazuh-apid.py#L87-L92

This means that an user could change it's Wazuh api configuration and make it run using [deprecated TLS versions](https://datatracker.ietf.org/doc/rfc8996/).


As a solution to these problems I'd start using the way recommended by [python ssl library docs](https://docs.python.org/3/library/ssl.html#context-creation) of creating a SSLContext, which is using `ssl.create_default_context(Purpose.CLIENT_AUTH)` specifying that's going to be used for creating server-side sockets with the `Purpose.CLIENT_AUTH`. This option disables the possibility of using SSLv2, SSLv3 and only uses high encryption cipher suites. I'd also  add a set of robust cipher algorithms to use with TLSv1.2 and avoid every request that tries to use an insecure one, and would stop supporting the possibility of using TLSv1.0 and TLSv1.1 by modifying the configuration files.

It would also be interesting to start using of TLSv1.3, but sadly python [doesn't offer full support for it yet](https://docs.python.org/3/library/ssl.html#tls-1-3). Anyway, we are looking forward to that.

Regards,
Gonzalo.
