### ISSUE TITLE
How could wazuh know the ip that were blocked before when we used repeated offenders ?

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh#933]
For example, Ip 192.168.56.201 were blocked for about 5 minutes using firewall-drop. After that i used `<repeated_offender>` to increase the timeout value for that active-response let's say 10, 20, 30. When an ip 192.168.56.201 caught triggered that active-response, it was blocked again for 10 minutes. 

How could Wazuh know the ip 192.168.56.201 were already blocked once so wazuh automatically blocked the ip and used the repeated offender timeout range ? When there is another Ip that triggered the same active-response, it's not triggered the reepeated offenders,

**Comment by Cerv1** [comment]
Hi @gagantous,

If I have understood your question correctly, you want to distinguish one IP from another to decide whether or not to trigger the timeout defined by `repeated_offenders`.

Unfortunately, this is not currently possible. But if you are interested in this functionality, we can create an issue to be developed as soon as possible. Don't hesitate to ask any questions, I will be happy to answer them.

Best regards,
Sergio.

**Comment by Cerv1** [comment]
Hello @gagantous,

That's right, Wazuh stores the IP and the command that were executed by `active_response`. 

In order to do this, Wazuh checks if this is the first time that the command is going to be executed. If so, it saves certain information (such as the IP or command).

Because of this, when a command that was previously stored is executed again and it has the `repeated_offenders` configuration established, the correct timeout will be applied.

However, this information about previous commands and IP's is deleted after the agent restarts.

Regarding the initial question, I've opened an issue to improve `active_response` behaviour. You can check the progress here #1153.

I hope you find this useful. 

Best regards,
Sergio.

**Comment by Zenidd** [comment]
Hi @gagantous,

Thank you very much for your contribution to the Wazuh project, when our workflow allows us to do so, we will work on the functionality you proposed.

I'm closing this issue, you can track the progress on https://github.com/wazuh/wazuh/issues/1153

If you need our help please do not hesitate to reopen this ticket or open a new one.

<br></br>
Kind regards,

Juan Pablo Sáez
