### ISSUE TITLE
False positive: Trojaned version of file '/usr/sbin/apachectl' detected

### ISSUE THREAD

**Issue by alitheg** [wazuh/wazuh#9337]
I've been doing some digging into this one which showed up as I started rolling Wazuh out. Looks like the version of apachectl that comes on macOS has replaced the interpreter with /bin/bash instead of /bin/sh, and if I'm understanding the regex correctly (and in OSSEC as well), that makes it look "trojaned"

**Comment by jnasselle** [comment]
Hi @alitheg ,

I've moved you issue to this repository because [wazuh/wazuh-ruleset](https://github.com/wazuh/wazuh-ruleset) was deprecated and absorbed by [wazuh/wazuh](https://github.com/wazuh/wazuh) under `ruleset` folder.

After a little research i found that Apple has their own taste of Apache with some customizations applied to the original one shared by Apache, meaning that it's in certain way a false positive. You could find here the patch that affects apachectl: [https://opensource.apple.com/source/apache/apache-856/patches/apachectl.diff.auto.html](https://opensource.apple.com/source/apache/apache-856/patches/apachectl.diff.auto.html)

```
--- support/apachectl.in.orig	2012-01-31 19:47:28.000000000 -0800
+++ support/apachectl.in	2013-11-12 14:00:54.000000000 -0800
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
```

There are two posibles workarrounds:
- Ignore `apachectl` check by specifying [ignore](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/rootcheck.html#ignore) option 
- Modify `rootkit_trojans.txt` entry related to `apachectl`
- Replace MacOs Apache default installation by Homebrew version that uses `/bin/sh`

Hope this helps!

Regards,
Nico

**Comment by alitheg** [comment]
Hi Nico, thanks for moving it for me!

For the short term I'll likely either ignore it or modify the check. However as I understand it this Apache comes with the system (I'm not using it!) and it can't be removed as it resides in /etc/. The homebrew one would install in /usr/local, so you'd still get these alerts from the original I suspect, unless you exclude it anyway?

My reasoning being that if this comes on Macs, then it'd probably make sense to have a seprate rule for it.

**Comment by giso79** [comment]
Hi 
I run in the same issue with a monitored macOS instance.
A separate rules for macOS sounds good. I would Vote for it. 

Best
Giso

**Comment by tyyang89** [comment]
Dear Nico,

hi there. may i check with you regarding the walkaround for this false positive on "apachectl", to confirm if my understanding is correct: even if we install the latest Wazuh agent version 4.3.10 into our MacOS Ventura V13.2.1, due to Mac's default installation for apachectl, this will trigger a false positive. Could you kindly confirm if this is correct?

1.  May I check will specifying this ignore on the directory during scan will also ignore a legitimate trojan/malware?
To ignore the “apachectl” option, we modify our Mac endpoint ossec.config file with the follow below? 


<rootcheck>
  <disabled>no</disabled>
  <check_unixaudit>yes</check_unixaudit>
  **<check_files>ignore</check_files>**
  <check_trojans>yes</check_trojans>
  **<check_dev>ignore</check_dev>
  <check_sys>ignore</check_sys>**
  <check_pids>yes</check_pids>
  <check_ports>yes</check_ports>
  <check_if>yes</check_if>
  <ignore type="sregex">^/etc/</ignore>

  
  <frequency>43200</frequency>

  <rootkit_files>etc/shared/rootkit_files.txt</rootkit_files>
  <rootkit_trojans>etc/shared/rootkit_trojans.txt</rootkit_trojans>

  <skip_nfs>yes</skip_nfs>
</rootcheck>

2 .  How do we modify the “rootkit_trojan.txt” for apachectl? 
How do we replace the default installation with Homebrew version to remove this false positive detection? Is there a documentation that shows the steps to this that happens on MacOS endpoint?


Please help advice.

Thanks & Best Regards,
Isaac

**Comment by vikman90** [comment]
Hi, this issue has been fixed by PR:
- https://github.com/wazuh/wazuh/pull/26141

Best regards.
