### ISSUE TITLE
Agent Fails to Recover after Buffer Fills with large amount of source files

### ISSUE THREAD

**Issue by chewbacca-us** [wazuh/wazuh#9351]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.5-rev | Wazuh Agent| Agent | Packages | Windows Server 2012 |

We are using wazuh agents to pull logs from custom directories for a client and have a requirement to use a wildcard path to pull any files that may be in the directory(ies).  The problem is that if there are a high number of files that match the wildcard, the agent fills the local buffer, and then the log collection from this custom configured directory fails to send any more logs until the agent is restarted.  The agent and manager are still working well enough at this point that the agent restart can be performed remotely from the manager. It's only the specifically configured directory that fails.

The settings and logs provided are from a development environment set up to mimic the production failure.  I am using a Windows Server 2012 box with a v4.1.5 agent joined to an Ubuntu 20 box with a v4.1.5 manager.  On the Windows box, I have created a fairly small log file with around 32000 logs that I duplicated 1000 times to mimic the problem of grabbing from hundreds of files with an agent in the production environment.  We have experienced, tested, and confirmed this issue with the agent and manager running on either v3.10.2 or 4.1.5.

Full copy of /var/ossec/etc/shared/default/agent.conf on manager:

```
<agent_config name="WIN-NQSAJQ6F4M4">
  <localfile>
    <log_format>syslog</log_format>
    <location>C:\logs\*.log</location>
  </localfile>
  <client_buffer>
    <disabled>no</disabled>
    <queue_size>5000</queue_size>
    <events_per_second>500</events_per_second>
  </client_buffer>
  <!-- Shared agent configuration here -->

</agent_config>
```

logs on agent server when trying to ingest a large number of files:

```
2021/07/20 15:23:32 ossec-agent: WARNING: (1960): File limit has been reached (200).
2021/07/20 15:28:23 ossec-agent: WARNING: Agent buffer at 90 %.
2021/07/20 15:28:23 ossec-agent: WARNING: Agent buffer is full: Events may be lost.
2021/07/20 15:28:41 ossec-agent: WARNING: Agent buffer is flooded: Producing too many even
2021/07/20 15:30:32 ossec-agent: INFO: Agent buffer is under 70 %. Working properly again.
```

logs from the custom, wildcarded directory defined in the shared config stop sending at this point (around 7500 total logs out of 32 million)

Only the custom log directory listed above stops working at this point.  Other logs handled by this agent continue to ship fine (Windows Event Channel). The manager never shows sign of an issue through this process.  It continues to work properly for other logs from the failed agent, and from any other agents that are deployed to the manager.

Have tried modifying client_buffer settings in shared config with results anywhere from getting only a few thousand more total logs before failure, and causing the server running the agent to become unresponsive when disabling the buffer.

Have tried modifying internal_options.conf settings on the server with the agent to rate limit it.  When I approach the low limits of the settings available for the logcollector module, I can get as many as 35000 total (still out of 32 million) logs to send from the agent before a failure happens.

In production, we do not  have control of the servers running agents as we are using Wazuh as part of a managed service offering.  Any guidance that can be provided to enable the agents to recover after filling the buffer would be appreciated, with a heavy emphasis on solutions being handled from the manager's shared config over direct changes to the agents.

**Comment by DProvinciani** [comment]
Hi @chewbacca-us! I spent some time reviewing this issue and performing some tests in a local testing environment. Before giving details on the environment and the results of the test, let's see some key points to bear in mind about all the tasks and settings involved in the log monitoring.

1. The number of logs to be monitored in a Windows agent is limited to 200.
2. There is a setting that determines the number of lines that are attempted to be read by the reading threads of `logcollector`. See [logcollector.max_lines](https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#logcollector).
3. The reading threads put the lines in a `logcollector` internal circular queue. The size of this queue is determined by the [logcollector.queue_size](https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#logcollector).
4. Those logs are extracted from the circular queue and finally put in the agent buffer to finally send them to the manager. Related settings are [<client_buffer>](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client_buffer.html).

Having said that, I decided to test this with a fixed number of logs and modify the settings in order to evaluate the possibility of reducing the number of events being lost. Configuration:

- Centos 7 with Wazuh manager 4.5.1.
- Windows 8.1 with Wazuh agent 4.1.5.
- Logfile with 100000 repeated lines.

|Round|Logcollector `max_lines`|Buffer `queue_size`|Buffer `events_per_second`|Logs received in the manager|
|-|-|-|-|-|
|1|10000|5000|500|5571|
|2|500|5000|500|23014|
|3|250|50000|1000|83059|

Some conclusions about the results of the tests:

- By increasing the Buffer `queue_size` and `events_per_second`, the buffer takes more time to be full and it is reduced the number of logs lost.
  - The increase of these values also increases the amount of memory consumed by the Wazuh agent.
- By reducing the `max_lines`, the buffer takes more time to be full and it is reduced the number of logs lost.
  - The reduction of this value, reduces the velocity of the log data collection.

Although seems complicated to achieve a point with no logs being lost, it would be interesting to evaluate a reduction of the logcollector `max_lines` in environments with many logs like yours.

**Note:** There is one more pending test to confirm that after getting the message `INFO: Agent buffer is under 70 %. Working properly again.`, if I add a new log to the folder, the data is sent. This would confirm that logcollector continues working but, all the data that was not received by the manager was actually lost in the agent because of having a buffer full.

**Comment by DProvinciani** [comment]
I spent more time analyzing the issue and validating what happens if after seeing the log `INFO: Agent buffer is under 70 %. Working properly again.` I add more lines of logs to the monitored log files.

Configuration:

- Centos 7 with Wazuh manager 4.5.1.
- Windows 8.1 with Wazuh agent 4.1.5.
- Logfile `test.log` with 100000 repeated lines.
- After getting the message, I ran a script that adds a numerated line of log in an infinite loop after each `0.1s`. 

The settings in the agent were the same three groups of settings described in the https://github.com/wazuh/wazuh/issues/9351#issuecomment-885943097.

**Results:** In any of the cases I didn't see again the log that indicates that the agent buffer is full, and all the written logs were properly sent to the manager. Having said that, it seems like the issue only happens after starting the agent, when it finds a big number of logs that must be sent to the manager.

**Comment by DProvinciani** [comment]
This scenario only occurs when the agent finds huge log files to be sent to the manager, but after sending all the files it continues working as expected. The possibility of losing events because of the big log files is explained in the Wazuh documentation.

https://documentation.wazuh.com/current/user-manual/capabilities/antiflooding.html
https://documentation.wazuh.com/current/learning-wazuh/survive-flood.html

Having said that, this is not an issue but instead, it is probably a limitation that could be improved. If you consider this should be improved, you could always open an FMR issue requesting this change and we will be glad to evaluate the possibilities to do it.
