### ISSUE TITLE
Wazuh Manager + Suricata

### ISSUE THREAD

**Issue by rejszynski** [wazuh/wazuh#9419]
Hi,

I want to integrate Wazuh with Suricata, but according to Wazuh documentation you have to deploy Suricata along with Wazuh Agent. I want to deploy Suricata in my Wazuh Manager cluster and send the copy of traffic (via SPAN port) to Suricata cluster.
Is it possible or Suricata could be deployed only along with Wazuh Agent?
I would like to avoid installing Suricata agents on every host where Wazuh Agent is deployed (got around 900 of agents).
Sorry if there was a issue similiar to mine but I couldn't find any information about in the Internet.

**Comment by vikman90** [comment]
Hi @rejszynski. Apologies for the late reply.

Do you mean the [suspicious network traffic page](https://documentation.wazuh.com/current/learning-wazuh/suricata.html) in the documentation? That explains how to set up Suricata and configure the agent to monitor the Suricata's output file (_eve.json_) through `<localfile>`. 

Despite the documentation explains how to do it with a Wazuh agent, you can also do that with a manager because Logcollector (the component which monitors files) works in both agent and manager.

This is the file monitoring flow diagram ([Log data collection | how it works](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/how-it-works.html)):

![Log analysis flow](https://documentation.wazuh.com/current/_images/log-analysis-flow1.png)

It shows that we can monitor files in both the manager and the agents. There are some particularities, like Windows event monitoring, which is only available in agents as the manager cannot run on Windows.

Hope this helps you.
Best regards.
