### ISSUE TITLE
Logcollector decrease default monitoring limit

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#9432]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0-40209 | Logcollector | Agent | Packages | Ubuntu |

Hello team,

We have detected a change into one of our testing charts. In such chart Logcollector seems to decrease the number of files monitored by default from 1000 to  400. This change is produced just after log rotation.
![image](https://user-images.githubusercontent.com/10661307/127826899-e0b69484-f13f-4b95-a198-2d536fe19901.png)

It's hard to reproduce but we could try to catch the error, thanks in advance.

Regards.

**Comment by teddytpc1** [comment]
@okynos 
Yesterday I executed a test and modified some parameters for the agent in order to increase the ossec.log rotation rate:
- Parameters:
![Screenshot from 2021-08-04 17-14-58](https://user-images.githubusercontent.com/33964202/128249512-a0defc73-db4d-4371-9a97-7c21d9ffd9d5.png)

-Log rotation evidence:
![Screenshot from 2021-08-04 17-13-09](https://user-images.githubusercontent.com/33964202/128249468-1963d152-da7e-44a1-8050-c9653f52faff.png)

- FD graphic. It does not show the same behavior, it worked fine:
![monitor-agent-Test_stress_B1322_ubuntu-warehouse-branches_FD](https://user-images.githubusercontent.com/33964202/128249578-a04aa150-c3a0-4604-a3bd-9e67ef0dcd5a.png)
