### ISSUE TITLE
The Auth daemon slows down when registry conflicts arise

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#9446]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.2-1 | Authd | Manager | All | All |

## Description

The goal of this issue is to extend the case reported at https://github.com/wazuh/wazuh/issues/9293, running new tests to get conclusions and look for a solution.

## Rationale

The Auth daemon works with the agent keys loaded in memory. Every time that a new registration request arrives, [the writer thread](https://github.com/wazuh/wazuh/blob/v4.1.2/src/os_auth/main-server.c#L749) dumps these keys into the disk (`client.keys` file) which is synchronized along with the rest of the cluster nodes when applicable.

As explained at https://github.com/wazuh/wazuh/issues/9293, when replacing agents due to conflicts, the update time for the `client.keys` file increases significantly.

## Reproducing the issue

The test conditions are the following:

- Master node (one single manager)
- Ubuntu 20.04 4GB RAM 2 CPUs
- Wazuh version 4.1.2
- Simulation of 5000 agents registration and re-registration leading to conflicts progressively
- Duration: 5 minutes
- Script: [register.py.txt](https://github.com/wazuh/wazuh/files/6925056/register.py.txt)

The script used for this test register a specific number of agents, after that, keeps registering agents with the same names leading Authd to replace them in the `client.keys` file.

The following graph shows the time elapsed between successive updates of the `client.keys` file during the whole test.

![image](https://user-images.githubusercontent.com/29475387/128038184-fb0ffc83-e60d-4e03-a2f7-5fb9fd1973f7.png)

Conflicts start to be generated at the time 14:42:39, when the first peak appears. Before the peak, while registering the 5000 agents with no conflicts, the update interval is around 10 ms (~ 1000 updates per second). After that, the refresh interval of the `client.keys` update keeps growing until the last read value, **16 seconds**.

Test results are scalable to the number of agents applied.

## Conclusions

This test reveals that the number of operations performed for every agent individually:

- Updating the timestamp file
- Removing the counters
- Delete the agent info file
- Delete the DB entry
- Remove the group

is the most time-consuming process (despite the considerable optimization in the timestamp file update included at https://github.com/wazuh/wazuh/pull/9295). This provokes the delay of starting a new iteration to update the `client.keys` file.

**Comment by alromeros** [comment]
**#9446 update:**

# Test analysis

Hi team,

After conducting several tests using the pipeline described in https://github.com/wazuh/wazuh-qa/issues/1668, we've come to gather several conclusions regarding this issue and the effectiveness of its [proposed fix](https://github.com/wazuh/wazuh/pull/9295).

The tests have been performed following these next steps:

1. Tests have been made in **clustered environments**, with one master node and one worker node.
2. Both the worker and the master node were created with **default configuration**. However, a preexisting `client.keys` file with **50000** agents was added to the master node, in order to facilitate the stress condition. 
3. After deploying both nodes, **Wazuh** was stressed with **700** real agents that were being re-registered successively during a defined period of time.
4. After this stress period, the environment was left at a **rest state** with the **700** agents still working, so we could gather some conclusions from the behavior of the nodes and agents.
5. During the whole test, a **monitoring script** parsed and saved in **CSV** all the relevant information from logs and daemons.

After testing with different conditions, settings, and environments, we have obtained several data from which to draw conclusions. We'll present these conclusions with two main tests that stand out as particularly relevant: 

## Test A: Environment without fix

|Number of agents|Number of workers|Manager specs|Branch|Duration|
|---|---|---|---|---|
| 700 | 1 | **t3.medium** (2 core / 4GB RAM) | [4.1.2-authd-metrics](https://github.com/wazuh/wazuh/pull/9295) | 1h 42m |

|Enrollment settings|value|
|---|---|
|`retry_interval`|10|
|`max_retries`|5|
|`delay_after_enrollment`|20|

The test was conducted and finished successfully. As expected, the worker and masters entered in a stress condition that exponentially increased the time needed for updating `client.keys`. This prevented agents to connect again and stabilize with the manager nodes. In short, **the unexpected behavior described in** https://github.com/wazuh/wazuh/issues/9293 **was replicated with real agents**.

These next graphs show the behavior of the module during the stress:

### a) Time spent in updating `client.keys`
![client_keys_update](https://user-images.githubusercontent.com/52510206/129155561-c4254448-d1ff-4df5-91d9-7be1e87fdb24.png)

As described, the exponential elongation in time for updating `client.keys` makes it impossible for agents to stabilize and connect with the manager.

### b) Replaced agents with time
![removed_agents](https://user-images.githubusercontent.com/52510206/129155770-b5136782-4c5a-4e2b-84ef-d7d50fcfd214.png)

As a consequence of the behavior shown in the previous graph, the number of disconnected agents ends up accumulating indefinitely.


## Test B: Fixed environment

|Number of agents|Number of workers|Manager specs|Branch|Duration|
|---|---|---|---|---|
| 700 | 1 | **t3.medium** (2 core / 4GB RAM) | [4.1.2-authd-force-time](https://github.com/wazuh/wazuh/pull/9295) | 1h 41m |

|Enrollment settings|value|
|---|---|
|`retry_interval`|10|
|`max_retries`|5|
|`delay_after_enrollment`|20|

The test was conducted under the same conditions as the one before, with the only difference being the fix to increase `authd`'s performance. The results were successful, as **the agents ended up stabilizing and connecting to the manager**: Instead of exponentially increasing the update time for `client.keys`, its modification kept working gradually, in even peaks.

Once again, these next graphs show the behavior of the module during the stress:

### a) Time spent in updating `client.keys`
![client_keys_update](https://user-images.githubusercontent.com/52510206/129156144-982b1b1e-0989-4831-8a00-07f382147671.png)

As described, the graph shows a stabilized and gradual time for updating `client.keys`. 

### b) Replaced agents with time
![removed_agents](https://user-images.githubusercontent.com/52510206/129156184-88fe04b6-4c49-45dc-bebf-a5aa93ce33f5.png)

As a consequence of the previous behavior, agents are gradually connected to the manager until they stabilize, with no irregular peaks and unexpected bottlenecks.

## Conclusions

After checking both the previous graphs and the general results of the test, we've come to reach the following conclusions:

- The exponential increase in time for updating `client.keys` happened due to a lack of performance in `authd` when re-registering a high number of agents.
- The increase of time needed to update `client.keys` led to a permanent state of disconnection in agents.
- The fix introduced in https://github.com/wazuh/wazuh/pull/9295 considerably increased performance in the module, which led to a stabilized and somewhat constant time for updating `client.keys`.

Best regards,
Álvaro Romero.

**Comment by chemamartinez** [comment]
Thanks for the feedback @alromeros! GJ
