### ISSUE TITLE
Inventory Data not accurate on Linux hosts

### ISSUE THREAD

**Issue by kmfreder1** [wazuh/wazuh#9483]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.5 | Syscollector | Agent | Packages | Debian 8 and 10 and Ubuntu 16.04.7,18.04 and 20.04 |
|4.1.5-4108|Syscollector|Manager|Packages|Ubuntu 20.04|

While investigating possible False Positives in Vulnerability Detector findings reported from a customer, I found evidence that the Syscollector data for the agent I was looking into was not correct.  This became clear when I found Syscollector reporting Wazuh Agent version 3.13.2 on the Inventory Data tab even though the agent reports 4.1.5 on the "Agents" screen. 

**From the Agents screen:**
![image](https://user-images.githubusercontent.com/28792720/128201773-b85ff9b3-d96c-4d54-8b63-9a1e8cf0ca31.png)

**From Inventory Data on same agent:**
![image](https://user-images.githubusercontent.com/28792720/128207154-12bd44bc-7878-486a-9c4b-d2c9aac5b0ed.png)

When I investigated further, I found that the other two Debian 10 agents and the Ubuntu agent were all reporting the same error in the Wazuh version.  However, Windows Servers (2012, 2016 and 2019) and Windows 10 Pro and Home systems are reporting their Wazuh version correctly.  

I also confirmed this same issue exists on another clients Wazuh-manager/agent installations.

I do not have direct access to most of these systems so I cannot directly verify the other packages, however, this would seem to indicate that the Syscollector data is not updating properly. 

This is the syscollector config section from the agent.conf for these hosts:

    
    <wodle name="syscollector">
      <disabled>no</disabled>
      <interval>1h</interval>
      <scan_on_start>yes</scan_on_start>
      <hardware>yes</hardware>
      <os>yes</os>
      <network>yes</network>
      <packages>yes</packages>
      <ports all="no">yes</ports>
      <processes>yes</processes>
    </wodle>

**Comment by Dwordcito** [comment]
Hi, I hope you are well.

I am trying to reproduce the issue without success, could you tell me if you did any version upgrade and if the answer is "yes", how did I do the clean installation process and then the update.

Thanks,

**Comment by branchnetconsulting** [comment]
The version number of the Wazuh agent reported by the local packaging system does not appear to get updated when the agent receives a WPK push upgrade.  It is understandable that this would be the case since WPK files are not RPM's, DEBs,, MSIs, etc...  But still it does feel like this leaves agent operating systems in a somewhat inconsistent state with the version of Wazuh reported by the packaging system (and thus by Syscollector) no longer matching the actual installed version of Wazuh agent.  Would it be feasible for WPK upgrades packages to include some kind of step to inform the local packaging system about the new version of Wazuh Agent it just upgraded the system to?

**Comment by kmfreder1** [comment]
As @branchnetconsulting suggested.  The initial installation of the Wazuh agent was via the .deb package, probably at the Inventory Data referenced version number.  Then, there was a push upgrade to 4.0.4 when that version came out and again to 4.1.5 when it came out.  I will have to dig further to see if the other packages the customer reported as FP's are also being misreported in Inventory Data.  I agree with @branchnetconsulting that the push upgrades leaving the package management system in a state where it is misreporting the Wazuh version after a push upgrade would be good to address.

**Comment by Dwordcito** [comment]
Thank you very much for expanding the detail of how the issue is reproduced!

This is a known issue, which we will fix ASAP, at this time the estimate is for Q1 2022, and we are defining in which version we will incorporate this fix/change.

To monitor progress, I suggest you follow the issue https://github.com/wazuh/wazuh/issues/3377

**Comment by kmfreder1** [comment]
A bit of additional information.  When looking into some of the other packages reported by Wazuh as critical vulnerabilities, but that that the customer reported as FP's, we found that the package detail provided in the Inventory Data for the other packages was actually correct.  

The customer had performed a dist-upgrade from Debian 9 to Debian 10 at some point in the past, so older packages from Debian 9 were left installed even though he had completed upgrades in Debian 10.  

So, for instance, perl-modules-5.24.1-3+deb9u5, leftover from the Debian 9 installation was still installed along with the newer perl-modules-5.28.1-6+deb10u1.  So, Vulnerability Detector was right about their being packages installed with critical vulnerabilities.  So the only thing we found that was not accurate was indeed the Wazuh agent version.
