### ISSUE TITLE
Investigate if it is possible to reduce the upgrade response time to API request

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#9502]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.x | Upgrade Module | Manager | Packages/Sources | Linux |

### Description

Related to https://github.com/wazuh/wazuh/issues/8939.

One of the main problems with the upgrade module is that the response time to the API request could be very large if the number of agents to analyze is big. Default API timeout is 20s.

In order to reduce this time, which will allow to execute more upgrades in parallel per API request, it is necessary to reduce the processing time of the request.

The idea of this issue is to investigate if the upgrade and task modules could be modified in order to perform the agents analysis in a shorter period of time, which will allow to reduce the response time.

**Comment by Dooque** [comment]
# Data Base Insertion/Selection Time Test Resuls

The goal of this test is to analyze the difference in performance, in terms of time, between performing individual database queries versus bulk queries. These access to the database are part of the upgrade process, so reducing the time is takes to access the database will reduce the time it takes to generate the response.

## Insertion Times

In this case we tested the INSERT query.

### One insertion per transaction

The table below shows the times it takes to insert a particular amount of elements in the data base performing one insertion at a time.

| N° of items | Time |
| ---- | --- |
| 10 | 0.061226s |
| 100 | 0.588134s |
| 1000 | 5.932277s |
| 10000 | 58.184220s |

We can see how the time increases linearly with respect to the number of inserted elements. The average time per transaction is about **6.184ms**.

### Multiple insertions per transaction

The table below shows the times it takes to insert a particular amount of elements in the data base performing more than one insertion at a time. The *Block size* is the amount is INSERT queries in the transaction.

| N° of items / Block size | 10 | 100 | 1000 | 2000 | 4000 | 10000 |
| - | - | - | - | - | - | - |
| 10 | 0.006600s | -------------- | -------------- | -------------- | -------------- | -------------- |
| 100 | 0.070717s | 0.020883s | -------------- | -------------- | -------------- | -------------- |
| 1000 | 0.695112s | 0.125409s | 0.050491s | -------------- | -------------- | -------------- |
| 10000 | 6.829824s | 1.107527s | 0.450718s | 0.635637s | 0.860959s | 1.378700s |

We can see how the time increases linearly with respect to the number of inserted elements, but we also can see a considerable reduction of the time it takes to insert the same amount of elements. We can also say that the best rate is when we insert elements in blocks of 1000 INSERT per transaction. In this case, the average time per transaction is about **0.046ms**

**CONCLUSION:** We can observe that inserting more than 1000 elements in blocks of 1000 INSERT per transaction is **100 times** faster than doing it in individual transactions.

## Selection Times

In this case we tested the SELECT query.

### One selection per transaction

The table below shows the times it takes to select a particular amount of elements from the data base performing one selection at a time.

| N° of items | Time |
| ---- | --- |
| 10 | 0.000940s |
| 100 | 0.006139s |
| 1000 | 0.050559s |
| 10000 | 0.510102s |
| 100000 | 4.868382s |

We can see how the time increases linearly with respect to the number of selected elements. The average time per transaction is about **0.061ms**.

### Multiple selections per transaction

The table below shows the times it takes to select a particular amount of elements from the data base performing more than one selection at a time. The *Block size* is the amount is SELECT queries in the transaction.

| N° of items / Block size | 10 | 100 | 1000 | 2000 | 4000 | 10000 |
| - | - | - | - | - | - | - |
| 10 | 0.000819s | -------------- | -------------- | -------------- | -------------- | -------------- |
| 100 | 0.006759s | 0.004608s | -------------- | -------------- | -------------- | -------------- |
| 1000 | 0.056441s | 0.043519s | 0.043072s | -------------- | -------------- | -------------- |
| 10000 | 0.560241s | 0.426276s | 0.412891s | 0.410502s | 0.481306s | 0.441243s |

We can see how the time increases linearly with respect to the number of inserted elements but we don't see, as in the previous case, a considerable reduction of the time it takes to select the same amount of elements. We can also say that the best rate is when we select elements in blocks of 1000 SELECT per transaction. In this case, the average time per transaction is about **0.041ms**

**CONCLUSION:** In this case we can conclude that the improvement in performance is not significant since it does not exceed **1.5%**.

**Comment by Nicogp** [comment]
# Upgrade module response time test

The goal of this test is to analyze the response time of the remote upgrade request based on the number of agent IDs in the request.

Due to limitations in the test environment, to carry out the tests I filled the global.db with the information of agents and the different queries were executed.

## Upgrade request from the API

For testing from the API, the limitation of 100 agents per request also had to be removed.
Agents ids range: 1000 to 10000

`time curl -k -X PUT "https://localhost:55000/agents/upgrade?agents_list=<agent_ids>&pretty=true&force=true&version=v4.1.5" -H  "Authorization: Bearer $TOKEN"`

The following table shows the time measured by the time command when executing the different requests

| N° of items | Time |
| ---- | --- |
| 10 | 0.082s |
| 100 | 0.184s |
| 1000 | 1.843s |
| 1500 | 2.361s |
| 1700 | ERROR: Got more than 8190 bytes (9065) when reading Status line is too long. |

**Note:** the API have implemented a mechanism in which if the original request has more than 100 agents, it parses the request in chuncks of maximum 100 and executes the necessary number of requests to the upgrade module.

The following table shows the time measured within the upgrade module in which it takes to process the upgrade request and return the response with the task_ids to the API

| N° of items | Time |
| ---- | --- |
| 10 | 0.0205s |
| 100 | 0.123s |
| 1000 | 1.716s |
| 1500 | 2.155s |

**Comment by Dooque** [comment]
# Upgrade module response time test - Addendum

The goal of this test is to analyze the response time of the remote upgrade request based on the number of agent IDs in the request.

The difference with the previous test is that in this case the test was performed with real agents workings.

The idea was to run agents in Docker containers. Due to limitations in the test environment we were able to execute a maximum of 100 agents at a time.

## Upgrade request from the API

For testing from the API, the limitation of 100 agents per request also had to be removed.

Command used for the test:
```bash
time curl -k -X PUT "https://localhost:55000/agents/upgrade?agents_list=<agent_ids>&pretty=true&force=true&version=v4.1.5" -H "Authorization: Bearer $TOKEN"
```

The following table shows the time measured by the `time` command when executing the different requests:

| N° of items | Time |
| -- | -- |
| 10 | 0,117s |
| 100 | 0,159s |

The following table shows the time measured within the upgrade module in which it takes to process the upgrade request and return the response with the task_ids to the API:

| N° of items | Time |
| -- | -- |
| 10 | 0.013274 |
| 100 | 0.060045 |

**Comment by Nicogp** [comment]
# Upgrade module response time test - Chunk size test

The API has implemented a mechanism where if the original request has more than 100 agents, it parses the request into chunks of a maximum of 100 and executes the required number of requests to the upgrade module. The goal of this test is to analyze the response time of the remote upgrade request based on the size of the chunks.

Command used for the test:
```bash
time curl -k -X PUT "https://localhost:55000/agents/upgrade?agents_list=<agent_ids>&pretty=true&force=true&version=v4.1.5" -H "Authorization: Bearer $TOKEN"
```

The following table shows the time measured by the time command when executing the different requests:

| N° of items | Time: chunk=100 | Time: chunk=200 | Time: chunk=300 | Time: chunk=400 | Time: chunk=500 |
| -- | -- | -- | -- | -- | -- |
| 10 | 0.080s | 0.077s | 0.078s | 0.078s | 0.078s |
| 100 | 0.184s | 0.178s | 0.172s | 0.169s | 0.173s |
| 1000 | 1.862s | 1.766s | 1.662s | 1.628s | 1.504s |
| 1500 | 2.754s | 2.649s | 2.456s | 2.281s | 2.119s |
