### ISSUE TITLE
Fix the wrong bit map usage in the enrollment structure

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#9572]
There is a bitmap usage in the enrollment structure that should be replaced by native `C` data types. Considering the changes implemented as part of the epic https://github.com/wazuh/wazuh/issues/9549, we should modify this data structure and all the places where its fields are used.

**Comment by MiguelazoDS** [comment]
It was not a big change, but it was interesting to read about it. The use of bitfields seems to be worth it in case we need to reduce the memory usage in fields we know will never exceed certain bit size. However, trying to make the program more efficient could lead to an "de-optimization" since it will lead to an increase in the program memory by adding more asm operations like mask and shift to operate over a single bit.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/9722 was merged.
