### ISSUE TITLE
PCI DSS Compliance does not load in any agent

### ISSUE THREAD

**Issue by VinniMarcon** [wazuh/wazuh#9661]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.5 | Sample Data | Manager | Packages | Ubuntu 20.04 |

I'm having an issue with **PCI DSS Compliance** where none of my agents upload their information to the dashboard. As shown in the figure below, it keeps loading infinitely and never displays any information.

![Capturar](https://user-images.githubusercontent.com/42422427/128952145-da7313ba-fa01-4c94-85d0-902b09d4f3ae.PNG)

apparently I need to **add a Sample Data that collects and works with the PCI DSS data**, but I don't have this sample data on my list:

![Capturar](https://user-images.githubusercontent.com/42422427/128952280-740b81e0-ca9e-45b5-a66b-422e065df145.PNG)

The image below shows 4 sample datas, where the last sample data would be the data I need to add. This image was taken from [here](https://github.com/wazuh/wazuh-kibana-app/issues/2115#issuecomment-614120849):

![Capturar](https://user-images.githubusercontent.com/34042064/79355699-4e810680-7f3e-11ea-9277-bf6125c84171.png)

But **my Wazuh Manager has only 3 Sample Data, and it doesn't have Sample Data that works with PCI DSS**:

![Capturar](https://user-images.githubusercontent.com/42422427/128952602-7368bb49-9437-43d5-90a4-0bcad7888fb1.PNG)

what I want to know is **how do I make the Compliance work? how can I get each agent's information to be collected and display into the PCI DSS dashboard? do I need to add this Sample data showed in the third screenshot? and if yes, how do i do it?**

**Comment by DProvinciani** [comment]
Hi @VinniMarcon ! First of all, apologies for the big delay in the answer. Not sure who this got missed in the issues.

Related to your question, it isn't necessary to add Sample Data that collects and works with the PCI DSS data. Let me explain to you. The Wazuh rules are classified according to the standard requirements. In the next link you can find a summary of the requirements.

[Wazuh for PCI DSS Guide (PDF)](https://wazuh.com/resources/Wazuh_PCI_DSS_Guide.pdf)

And in the next link, you can see how we classify or rules by requirements using the tag **pci_dss_xxxx**.

https://github.com/wazuh/wazuh/blob/master/ruleset/rules/0016-wazuh_rules.xml#L26

Having said that, the PCI DSS compliance graphs should be generated based on the tags in the alerts that were triggered. So, the issue here seems to be related to the Wazuh alerts generation. Considering this, let's verify some things and do some troubleshooting to identify the issue.

1. Do you see any alert generated in the Wazuh UI in Kibana in any of the dashboards?
2. Could you verify that you have alerts generated for different agents in the file `/var/ossec/logs/alerts/alerts.log`?
3. Could you verify that your agents are connected and reporting to the manager? You can check this in the Wazuh UI checking the agents' status.

Please, check these things and let me know the result of each of them. I'll be waiting for your answer.

**Comment by DProvinciani** [comment]
As we didn't receive any update on this, we assume that probably it was resolved. Closing the issue.

**Comment by KhaledEid020** [comment]
The alerts are shown very well; however, do all the rules cover the PCI DSS requirements?
![image](https://github.com/user-attachments/assets/348fcd8d-6e78-4377-903e-8ba7f71eebc4)
