### ISSUE TITLE
Wazuh daemons file descriptor leak

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#9743]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2-rc13 | Any | Manager - Agent | Packages - Sources | Any |

## Description
Hi team!

Currently there's file descriptor leak for every wazuh daemon. Those FDs points to:
- /proc/stats
- /proc/uptime

## Steps to reproduce

1. Start Wazuh agent/process
2. Check wazuh processes FDs related to /proc/stats and /proc/uptime
```
lsof | grep wazuh- | grep /proc
```
## Actual result
- FDs are opened and remains opened during process lifetime.
![image](https://user-images.githubusercontent.com/1791430/129791922-f443e74a-5c79-4a42-b1e2-54e6244881a1.png)

## Desired result
- FDs are opened and close during process startup and remain closed.

## DoD
- [x] RCA
- [ ] Propose a fix, if necessary.

Regards,
Nico

**Comment by Dwordcito** [comment]
![image](https://user-images.githubusercontent.com/14300208/130274066-2bf3283b-07bb-46bd-85c0-6e5969b8e2b7.png)
![image](https://user-images.githubusercontent.com/14300208/130274269-c39414f6-6e57-4e54-8f58-ce91f719041f.png)
![image](https://user-images.githubusercontent.com/14300208/130274297-487c6e86-2702-4ec2-8aba-ca1dd5a751dd.png)


Within it there are three attributes ((constructor)) without defining an order of execution priorities, worse, in turn, procps has an interdependence between the constructors, which makes it necessary to have them properly synchronized.

Basically, the procps is making use of a constructor (init_libproc) of the linux_version_code variable that is set in the init_Linux_version constructor that is called later, this causes the init_libproc constructor not to look for the AT_CLKTCK elf_note since there is no successful match for the comparison linux_version_code > LINUX_VERSION (2,4,0) 0> ~ 33000
In turn, it is horrendous that the libproc leaves open the FDs of things that you only use once.

The workaround is simple for the issue, https://gcc.gnu.org/onlinedocs/gcc-4.7.0/gcc/Function-Attributes.html -> constructor (priority), but the RC for this change needs to be found.
It also seems that in the latest version of the libprocps this was solved https://gitlab.com/procps-ng/procps/-/blob/master/proc/sysinfo.c#L347

**Comment by Dwordcito** [comment]
The packages have already been updated after a modification in the procps code equivalent to this: https://github.com/Dwordcito/procps/commit/0b9ecc1ffefeb4bc05281243966fc73911514a10
