### ISSUE TITLE
whoscan data error on server 2016

### ISSUE THREAD

**Issue by moodstory** [wazuh/wazuh#9773]
**Hi there,**

Can't get whodata on my fileserver.  Osseclogs on agent are below. 

ERROR: (6621): Event Channel subscription could not be made. Whodata scan is disabled.
ERROR: (6710): Failed to start the Whodata engine. Directories/files will be monitored in Realtime mode

 
**And my event ID Querry,**

<query>Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and
      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and
      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and
      EventID != 5152 and EventID != 5157]</query>

Thanks for your kind help.

**Comment by antoniomanuelfr** [comment]
Hello @moodstory 

I have been checking the logs that you shared and I have an idea of where it's the problem.

When monitoring a folder with whodata, FIM sets audit policies to the monitored directories and then it tries to subscribe to the security channel. When the subscribing process fails, the logs that you shared are shown and the monitoring is changed from whodata to realtime. 

Now, we need some more information in order to debug this:

- Wazuh version.
- Syscheck section of the configuration.
- Are you using a centralized configuration?

The best way to get the configuration of the agent is using the API with the following request (on the manager side)

- Get the authentication token: `TOKEN=$(curl -u <user>:<password> -k -X GET "https://localhost:55000/security/user/authenticate?raw=true")`
 - Request the configuration to the API: `curl -u '<user>:<password> -k -X GET 'https://localhost:55000/agents/<agentid>/config/syscheck/syscheck' -H "Authorization: Bearer $TOKEN"`

With this, you will get a JSON with the agent configuration. We will need this JSON with the agent configuration to check that everything is correct.

I'm also going to open an issue to change these kinds of error messages to show the error codes because that will help us to debug and find issues more easily.

**Comment by moodstory** [comment]
Hello @antoniomanuelfr 

Thanks for your support. 
I think i found out the problem. 
When i checked event viewer on my fileserver cluster Security Event Section not responding. 
Seems like it caused by windows server configs.
