### ISSUE TITLE
Maybe  TCP connection have some bug，

### ISSUE THREAD

**Issue by mashaobu** [wazuh/wazuh#9781]
|4.3.0|Component|server|self compile|centos7|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

Server : 192.168.0.56
two agent: 55 and 135

When I uninstal server's wazuh and reinstall it,  Found there are many tcp connections.  If  many agent , it maybe disaster。
can optimize it ?

[root@localhost bin]# netstat -na|grep 1514
tcp        0      0 0.0.0.0:1514            0.0.0.0:*               LISTEN     
tcp        0      0 192.168.0.56:1514       192.168.0.55:42674      TIME_WAIT  
tcp        0      0 192.168.0.56:1514       192.168.0.55:42676      FIN_WAIT2  
tcp        0      0 192.168.0.56:1514       192.168.0.135:23122     TIME_WAIT  
tcp        0      0 192.168.0.56:1514       192.168.0.55:42670      TIME_WAIT  
tcp        0      0 192.168.0.56:1514       192.168.0.55:42662      TIME_WAIT  
tcp        0      0 192.168.0.56:1514       192.168.0.135:2095      TIME_WAIT  
tcp        0      0 192.168.0.56:1514       192.168.0.55:42660      TIME_WAIT  
tcp        0      0 192.168.0.56:1514       192.168.0.55:42664      TIME_WAIT  
tcp        0      0 192.168.0.56:1514       192.168.0.135:27768     TIME_WAIT  
tcp        0      0 192.168.0.56:1514       192.168.0.135:13099     TIME_WAIT  
tcp        0      0 192.168.0.56:1514       192.168.0.55:42672      TIME_WAIT  
tcp        0      0 192.168.0.56:1514       192.168.0.135:1030      FIN_WAIT2

**Comment by vikman90** [comment]
Hi @mashaobu. This is the normal operation of the TCP connections. States `FIN_WAIT1`, `FIN_WAIT2` and `TIME_WAIT` belong to the active closer peer (which first closes the connection).

This is the TCP diagram state ([Wikipedia](https://en.wikipedia.org/wiki/File:Tcp_state_diagram.png)):

![TCP state diagram](https://upload.wikimedia.org/wikipedia/en/5/57/Tcp_state_diagram.png)

The agent normally closes the connection (when stopping or restarting). However, Remoted may close connections (and leave some connections in those states) due to:

- Clients that are not Wazuh agents (invalid data input).
- Unauthorized agents (which do not have a valid key).
- Data delivery timeout (if the agent does not respond within one minute).

Obviously, when we stop the manager (including upgrade and reinstallation), the operating system must close all the active connections. That's why _netstat_ shows some connections in `TIME_WAIT2` (waiting for the agent to close the connection for its part) and others in `TIME_WAIT` (that is a 60-second timeout by the OS).

The reason for that timeout is just to prevent other connections from reusing the same port during the MSL ([maximum segment lifetime](https://en.wikipedia.org/wiki/Maximum_segment_lifetime)), which would cause confusion with an eventually new connexion.

So, the `TIME_WAIT` timeout is _2 * MSL_. On Linux, MSL is 60 seconds, and the `TIME_WAIT` timeout is two minutes:

```sh
$ cat /proc/sys/net/ipv4/tcp_fin_timeout
60
```

I know it seems weird to find those ports open after stopping the manager, but that is part of how TCP works. However, they must disappear within 2 minutes.

Hope this helps you.
Best regards.
