### ISSUE TITLE
disabling servers scans while enabled on agent

### ISSUE THREAD

**Issue by evilpete** [wazuh/wazuh#981]
Is there a way to have syscollector and vulnerability-detector disabled on the cluster nodes but still active on the agents ?

when the servers are run in a autoscaling group, these scans are unnecessary given since the hosts are clones of each other and ephemeral.

**Comment by vikman90** [comment]
Hi @evilpete,

Yes, you can disable Syscollector in the cluster nodes with this configuration:

```xml
<wodle name="syscollector">
  <disabled>yes</disabled>
```

Put that configuration into the file `ossec.conf` of the master node, and it will spread that setting to the rest of the nodes.

On the other hand, Vulnerability Detector needs to be enabled in all the cluster nodes. If Syscollector is disabled in these nodes, no vulnerability alerts will appear for them.

This is because Syscollector gathers software information from the agents and sends it to the managers (nodes). They store such information in a database. Then, Vulnerability Detector (in the manager) uses this data to find vulnerabilities in the agents. If Syscollector is disabled in the managers, no software version data will be available and Vulnerability Detector will not produce alerts of vulnerabilities in the cluster nodes.

Hope it help.
Best regards.

**Comment by evilpete** [comment]
I was under the impression that ossec.conf is for **local only** config and shared configs are put in agent.conf located in etc/shared

**Comment by vikman90** [comment]
Hi @evilpete,

Apologies for not responding to your comment.

You're right: each manager node and each agent have an _ossec.conf_ file for local configuration. That's why I suggested disabling Syscollector locally on every manager, leaving it enabled on the agents.

Let me close this issue. Please don't hesitate to reopen it if I did not clarify your question.

Best regards.
