### ISSUE TITLE
Failed Upgrade From 3.13 to 4.1

### ISSUE THREAD

**Issue by moosa-aslam** [wazuh/wazuh#9830]
After Upgrading my Wazuh Single Node deployment from 3.13 to 4.1 using the official wazuh guide [](https://documentation.wazuh.com/current/upgrade-guide/upgrading-wazuh.html) my instance is down please view attached log file

Kibana server "Kibana server is not ready yet"

elasticsearch-7.11.2
kibana-7.11.2

[elasticsearch.log](https://github.com/wazuh/wazuh/files/7038630/elasticsearch.log)
[kibana.log](https://github.com/wazuh/wazuh/files/7038631/kibana.log)

**Comment by DProvinciani** [comment]
Hi @moosa-aslam! Thanks for using Wazuh!

First of all sorry because of the late answer. I spent some time reviewing your logs, and the problem seems to be explained in the next line:

```
Moving to ERROR step
org.elasticsearch.common.ValidationException: Validation Failed: 1: this action would add [2] total shards, but this cluster currently has [1000]/[1000] maximum shards open;
```

Let me give you more context. The maximum number of shard configured by default for each node is `1000` so, in your case you reaches this limit and it fails. The question now is, how could yo fix this? Let's explore some alternatives...

- You could increase the number of nodes of your Elasticsearch cluster.
- Increase the number of shards. In [this](https://documentation.wazuh.com/current/user-manual/elasticsearch/elastic_tuning.html#shards-and-replicas) link of the Wazuh documentation we explain how to set the number of shards and replicas. 
- Delete indices that you no longer need. Apart from that, you could set a policy to avoid this situation as we explain [here](https://wazuh.com/blog/wazuh-index-management/).

I hope this could be useful for you, and considering the delay, that you could already fix this issue.

**Comment by DProvinciani** [comment]
Closing the issue as we didn't have an answer after a while.
