### ISSUE TITLE
Improve the configuration of Authd - Analysis

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#9929]
In order to address the new implementation described in issue #9550 and related to the previous improvement added as part of #9549, it is needed to discuss the following items.

- Validation of the three new options described. Considering the readability of option names. 
- Use cases analysis to find dependencies between options.
- Possible and default values of each option. 
- Projects affected by this implementation.
- Any other implications of this development.

**Comment by pereyra-m** [comment]
### Epic analysis

This brief first approach will be discussed with the team to implement the required feature.

#### Definitions

Different names for the required settings are proposed. The most adequate and clear words should be used after the corresponding analysis.

- `enabled`: When the same IP/name is found, this option decides if it is possible to re-register
- `pre_existent_key`: This toggles the key compassion   
- `by_status`: This toggles the status check 
- `registered_since_time`: Checking the time since the agent has registered

Possible values:

```
    <force>
          <enabled>yes|no</enabled>          
          <pre_existent_key>replace_without_checking|only_if_different</pre_existent_key> 
          <by_status>not_active (pending-never_connected-disconnected)|any</by_status>    
          <registered_since_time>2h</time>            
    </force>
```
**Default values proposed**
        - `enabled`: yes
        - `pre_existent_key`: only_if_different 
        - `by_status`: disconnected
        - `registered_since_time`: 0

####   Requirements: 

The expected result for some cases:

- `Enabled = no` : If an agent is trying to request a key, but its name/IP already exists, the enrollment is denied.
- `Enabled = yes`:
    - `pre_existen_key = only_if_different` : the manager's compare both keys and rejects the request if the are the same
    - `by_status = not_active` : the manager replaces the agent if it's pending, never_connected or disconnected
    - `registered_since_time` : the registration time must excede this setting to allow the replacement.

#### Task list: first approach

**Core**
- Issue 1: Create new settings and deprecate old ones
    - After this implementation, the new values are read from the configuration and correctly read by **authd**
    - The settings can be requested from the socket
    - The old settings are ignored and the proper warning is logged
        
- Issue 2: Update the `w_auth_replace_agent()` method with the new behavior
    - After this implementation, all the new settings should be considered in every key request
    - The UT for this function should fixed and new cases have to be implemented
        
- Issue 3: Define the configurations behavior under cluster scenario
    - The `w_request_agent_add_local()` should consider the new configurations when sending the registration message to master
    - The UT for this function should fixed and new cases have to be implemented

- Issue 4: Exploratory testing

**Documentation**
- The new settings and behavior should be described in the documentation
- Some diagramas would be really helpful to allow the user easily understand all the possible scenarios
    
**QA**
- The integration tests should consider this new behavior for single master and cluster
    
Also, it is necessary to coordinate with the API and Framework team the new implementation.

### Questions:
- How the registration process should manage the settings for master and worker in a cluster?
- Could the `by_status` setting allow different combinations and/or negations? Or only the two proposed? 
- Does the option `by_status` creates a conflict with the auto-enrollment feature?
    - With auto-enrollment activated and `by_status = disconnected`, will a new agent (never_connected) be able to register? 
    - With auto-enrollment activated and `by_status = disconnected`, an agent may lose connection with **remoted** but would be rejected by **authd** until its status updates to disconnected ? (the legacy agents don't send it's key hash)

**Comment by DProvinciani** [comment]
Based on the analysis in the comments and all the issues created for the epic https://github.com/wazuh/wazuh/issues/9550, we close this issue.
