### ISSUE TITLE
IOT log decoder not work properly 

### ISSUE THREAD

**Issue by Hasitha9796** [wazuh/wazuh#9972]
This is the log i got from iot device.

2021-08-27 19:01:52 osb/smart_security/flix11-rajagiriya/v1/n2b/heartbeat {"SYS_BIT":4,"SysBoot":"2021:8:27 11:19:32","DateTime":"2021:8:27 19:1:45","HeartBeat":[75,0,1,1,0],"TH":[0.00,0.00],"ActiveStatusWired":[1,1,1,1,11,1,1,1,1,1,1,1,1,1,1],"ActiveStatusZone":[1,1,1,1,1,1]}

<decoder name="IOT">
    <prematch>^\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d </prematch>
</decoder>

<decoder name="IOT1">
  <parent>IOT</parent>
  <regex>^(\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d)</regex>
  <order>datetime</order>
</decoder>

<decoder name="IOT1">
  <parent>IOT</parent>
  <regex>"DateTime":"(\S+)","HeartBeat":"(\S+)","TH":"(\S+)"</regex>
  <order>datetime, heartbeat, th</order>
</decoder>

my parser is mentioned above
Its giving decoder output as windows-date-format 
Any solutions please

**Comment by juliancnn** [comment]
Hi @Hasitha9796 ,

A possible solution is to use the `windows-date-format` decoder as [parent decoder](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/decoders.html#parent). For example, we could have a child decoder that looks for the word heartbeat and also complies with the date format of "windows-date-format". I have created the following decoder that might be useful to you:

```xml

<decoder name="iot_heartbeat">
  <parent>windows-date-format</parent>
  <use_own_name>true</use_own_name>
  <prematch offset="after_parent">^\S+/heartbeat </prematch>
  <regex>"DateTime":"(\.+)","HeartBeat":(\.+),"TH":(\.+),"ActiveStatusWired"</regex>
  <order>date_time, heartbeat, th </order>
</decoder>
```

I have tested the log you have shared with us in Wazuh-Logtest and it extracts the data correctly:

```console
/var/ossec/bin/wazuh-logtest                     
Starting wazuh-logtest v4.2.1
Type one log per line

2021-08-27 19:01:52 osb/smart_security/flix11-rajagiriya/v1/n2b/heartbeat {"SYS_BIT":4,"SysBoot":"2021:8:27 11:19:32","DateTime":"2021:8:27 19:1:45","HeartBeat":[75,0,1,1,0],"TH":[0.00,0.00],"ActiveStatusWired":[1,1,1,1,11,1,1,1,1,1,1,1,1,1,1],"ActiveStatusZone":[1,1,1,1,1,1]}

**Phase 1: Completed pre-decoding.
        full event: '2021-08-27 19:01:52 osb/smart_security/flix11-rajagiriya/v1/n2b/heartbeat {"SYS_BIT":4,"SysBoot":"2021:8:27 11:19:32","DateTime":"2021:8:27 19:1:45","HeartBeat":[75,0,1,1,0],"TH":[0.00,0.00],"ActiveStatusWired":[1,1,1,1,11,1,1,1,1,1,1,1,1,1,1],"ActiveStatusZone":[1,1,1,1,1,1]}'

**Phase 2: Completed decoding.
        name: 'iot_heartbeat'
        parent: 'windows-date-format'
        date_time: '2021:8:27 19:1:45'
        heartbeat: '[75, 0, 1, 1, 0]'
        th: '[0, 0]'
```

On the other hand, in order to have a better understanding on how does the rules/decoders work, I would strongly recommend you reading the following links:
https://wazuh.com/blog/creating-decoders-and-rules-from-scratch/
https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html
https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/decoders.html


Please let me know if you found this helpful.

**Comment by juliancnn** [comment]
Hi @Hasitha9796  

Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our Slack channel or subscribe to our mailing list.

Best regards,
Julian
