### ISSUE TITLE
Infinite loop starting wazuh api.

### ISSUE THREAD

**Issue by rpermig** [wazuh/wazuh#9979]
Hello:

When starting wazuh-api and doing the health checks, the api enters on a infinite loop. I have been looking for errors and I found nothing.

Thanks

**Comment by AdriiiPRodri** [comment]
Hi @rpermig,

In order to help you we need more information about the problem:
- Which version of Wazuh are you using?
- What is the output of the `service wazuh-manager restart` command?
- What is the output of the following API request `curl -k -u wazuh:wazuh -X GET https://localhost:55000/security/user/authenticate` ?
- Finally, could you post the output of the following command: `tail -n20 /var/ossec/logs/api.log`?

I'm looking forward to your answer. If you have any questions about the above points, feel free to ask.

Regards.

**Comment by rpermig** [comment]
The initial error was:
 - Check Elasticsearch index pattern: Error
 - Check Elasticsearch template: Error
 
The selected index-pattern is not present
No template found for the selected index-pattern.

Then I get the infinite loop when disabling checks.pattern and checks.templates in wazuh.yml.

Now I look at the info you have requested.

**Comment by rpermig** [comment]
- Version 4.0

![WhatsApp Image 2021-09-06 at 11 22 20](https://user-images.githubusercontent.com/64162082/132193766-11f006c4-f758-48a0-b876-319dc00a5a02.jpeg)

![WhatsApp Image 2021-09-06 at 11 23 17](https://user-images.githubusercontent.com/64162082/132193804-60c99d8a-514b-43a6-a136-f2072462addd.jpeg)

![WhatsApp Image 2021-09-06 at 11 26 08](https://user-images.githubusercontent.com/64162082/132194111-bdfafbb0-8cf2-4bfe-9007-49962d98c9ec.jpeg)


Thanks

**Comment by AdriiiPRodri** [comment]
You're welcome, the API is working correctly and the problem seems to be on the interface side of Wazuh. Is it possible that you have upgraded Wazuh from a 3.X version to 4.0?

Otherwise, please run the following call to check what indexes the system currently has:
```
curl elastic_ip:9200/_cat/templates -s | grep wazuh
```

Next, let's check the index-patterns used for the interface visualizations. To do so, share with us the elements that appear in the `Management -> index-patterns` section of Kibana.

**Comment by rpermig** [comment]
No, I have not update the version. I installed 4.0 version directly.

![WhatsApp Image 2021-09-06 at 12 44 37](https://user-images.githubusercontent.com/64162082/132205848-28f3b6e2-e8a0-4d97-a945-46ef5582a472.jpeg)

![WhatsApp Image 2021-09-06 at 12 47 55](https://user-images.githubusercontent.com/64162082/132205995-7fdccae9-8132-4b16-a3f0-0949c9125df1.jpeg)

**Comment by rpermig** [comment]
When I go to Index Management in kibana I have a different name, not wazuh-alerts-*. 
Where do you configure index management name? In wazuh-template.json?

**Comment by AdriiiPRodri** [comment]
I recommend you install the latest stable version of Wazuh, currently 4.2.1. This latest version improves the overall performance, fixes bugs, and adds interesting features.

In any case, we can see a difference and what you say about wazuh-alerts-* may be the problem. In addition to this, I see the `wazuh-archives-4.x-*` file, however, in the interface, I do not see it, this may be because you do not have the archives option enabled within the filebeat.yml file (https://github.com/wazuh/wazuh/blob/master/extensions/filebeat/7.x/filebeat.yml#L7). After enabling this option, it would be necessary to restart the service.

On the other hand, please check that the names match the information in the wazuh-template.json file. You can find more information here: https://documentation.wazuh.com/current/user-manual/kibana-app/reference/configure-indices.html

**Comment by rpermig** [comment]
Thank you, but still continue the error.

Can I install de latest wazuh-manager version without installing the latest api kibana version?

**Comment by rpermig** [comment]
It is just working now. The only thing I have done is deleting all kibana index using curl XDELETE.

Thank you.
