### ISSUE TITLE
Move FIM db unit tests to gtest

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh#9981]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|[9103-replace-fim-db-dbsync](https://github.com/wazuh/wazuh/tree/9103-replace-fim-db-dbsync) | FIMDB | Manager/Agent | Packages/Sources | All |

Hi team!

With the changes that are going to be introduced in https://github.com/wazuh/wazuh/issues/9103, we are going to stop using `cmocka` to perform the unit testing for the FIM DB and use Gtest instead.

This issue aims to collect all the needed changes, investigation, and creation of the unit tests with the new test framework.

- [x] Create testing structure (needed folders, cmakelists, etc)
- [x] Create a sample test with Gtest to check everything compile and work

**Comment by JoseAntonioMHerrera** [comment]
Update: The linked PR covers all the necessary files to fulfill the requirement of a sample test (Gtest) working under syscheck/db/tests/ folder and some fixes to allow the compilation of windows targets with TEST flag. The pending task to close this issue is fixing the syscheck unit tests compilation. For the sake of simplicity, this task will be continued once the development of [FIM DB engine rework ](https://github.com/wazuh/wazuh/issues/9103) has advanced enough to come for a clean solution for the unit tests compatibility problems.
